var pairs =
{
"example":{"-dealing":1,"designed":1,"example":1,"executed":1,"example6.sh":1,"resides":1,"made":1}
,"-dealing":{"job":1}
,"job":{"exceptions":1,"execution":1,"execute":1,"throw":1,"again":1,"creates":1,"immediately":1,"jobexecutionexception":1,"refire":1,"\u002F\u002Fso":1,"run":1,"scheduled":1,"fire":1,"=newjob":1,"program":1,"attempt":1}
,"exceptions":{"example":1,"jobs":1,"quartz":1}
,"designed":{"demonstrate":1}
,"demonstrate":{"deal":1}
,"deal":{"job":1}
,"execution":{"exceptions":1}
,"jobs":{"quartz":1,"job":1,"throw":1,"plenty":1,"(badjob1":1,"completed":1}
,"quartz":{"permitted":1,"specified":1,"scheduler":1,"appropriate":1,"refire":1,"schedule":1,"run":1,"runs":1,"shutdown":1}
,"permitted":{"throw":1}
,"throw":{"jobexecutionexceptions":1,"exceptions":1,"exception":1,"force":1}
,"jobexecutionexceptions":{"exception":1}
,"exception":{"thrown":1,"instruct":1,"(divide":1,"occurs":1,"job":1}
,"thrown":{"direct":1,"refire":1,"ensure":1}
,"direct":{"quartz":1}
,"specified":{"action":1}
,"action":{"program":1}
,"program":{"perform":1,"wait":1,"badjob1":1,"starts":1,"sleep":1,"gracefully":1}
,"perform":{"following":1}
,"following":{"actions":1,"classes":1}
,"actions":{"start":1}
,"start":{"quartz":1}
,"scheduler":{"schedule":1,"running":1,"done":1,"create":1,"schedulerfactory":1,"sched":1,"started":1,"opportunity":1,"run":1,"sched.shutdown":1,"wait":1}
,"schedule":{"two":1,"job":1}
,"two":{"jobs":1,"ways":1}
,"execute":{"every":1}
,"every":{"three":1,"seconds":1}
,"three":{"seconds":1}
,"seconds":{"indefinite":1,"two":1,"indefinitely":1}
,"indefinite":{"period":1}
,"period":{"time":1}
,"time":{"jobs":1,"run":1}
,"appropriate":{"action":1}
,"wait":{"seconds":1,"until":1}
,"plenty":{"time":1}
,"run":{"shut":1,"example":1,"job":1,"again":1,"every":1,"jobs":1}
,"shut":{"down":1}
,"down":{"scheduler":1}
,"running":{"example":1,"returning":1}
,"executed":{"examples\u002Fexample6":1}
,"examples\u002Fexample6":{"directory":1}
,"directory":{"two":1}
,"ways":{"run":1}
,"example6.sh":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"script":1}
,"script":{"example6.bat":1}
,"example6.bat":{"windows":1}
,"windows":{"batch":1}
,"batch":{"file":1}
,"file":{"code":1}
,"code":{"code":1,"example":1}
,"resides":{"package":1}
,"package":{"org.quartz.examples.example6":1}
,"org.quartz.examples.example6":{"code":1}
,"made":{"following":1}
,"classes":{"class":1}
,"class":{"name":1}
,"name":{"description":1}
,"description":{"jobexceptionexample":1}
,"jobexceptionexample":{"main":1,"program":1}
,"main":{"program":1}
,"badjob1":{"simple":1,"badjob1":1,"jobdetail":1,"group1":1}
,"simple":{"job":1,"ram-based":1}
,"instruct":{"quartz":1}
,"refire":{"trigger":1,"job":1,"immediately":1}
,"trigger":{"immediately":1,"=newtrigger":1}
,"immediately":{"badjob2":1,"try":1,"e2.refireimmediately":1,"job":1}
,"badjob2":{"simple":1,"badjob2":1,"job":1,"group1":1}
,"again":{"badjob1":1,"badjob2":1,"try":1,"e2.setunschedulealltriggers":1,"jobexceptionexample":1,"finally":1}
,"creates":{"artificial":1}
,"artificial":{"exception":1}
,"(divide":{"zero)":1}
,"zero)":{"exception":1}
,"occurs":{"jobexecutionexception":1}
,"jobexecutionexception":{"thrown":1,"=new":1,"(e)":1}
,"try":{"{int":1}
,"{int":{"zero":1}
,"zero":{"int":1}
,"int":{"calculation":1}
,"calculation":{"=4815":1}
,"=4815":{"\u002Fzero":1}
,"\u002Fzero":{"catch":1}
,"catch":{"(exception":1}
,"(exception":{"{_log.info":1}
,"{_log.info":{"(\u0022---error":1}
,"(\u0022---error":{"job":1}
,"=new":{"jobexecutionexception":1,"stdschedulerfactory":1}
,"(e)":{"\u002F\u002Fthis":1,"\u002F\u002Fquartz":1}
,"\u002F\u002Fthis":{"job":1}
,"e2.refireimmediately":{"throw":1}
,"force":{"quartz":1}
,"ensure":{"quartz":1}
,"runs":{"job":1}
,"\u002F\u002Fquartz":{"automatically":1}
,"automatically":{"unschedule":1}
,"unschedule":{"\u002F\u002Fall":1}
,"\u002F\u002Fall":{"triggers":1}
,"triggers":{"associated":1}
,"associated":{"job":1}
,"\u002F\u002Fso":{"run":1}
,"e2.setunschedulealltriggers":{"(true)":1}
,"(true)":{"throw":1,"passing":1}
,"shutdown":{"job":1,"method":1}
,"starts":{"getting":1}
,"getting":{"instance":1}
,"instance":{"scheduler":1}
,"done":{"creating":1}
,"creating":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"using":1,"scheduler":1}
,"using":{"create":1}
,"create":{"scheduler":1,"simple":1}
,"ram-based":{"scheduler":1}
,"schedulerfactory":{"=new":1}
,"sched":{"=sf.getscheduler":1}
,"=sf.getscheduler":{"job":1}
,"scheduled":{"run":1}
,"indefinitely":{"job":1}
,"fire":{"badjob1":1,"badjob2":1}
,"jobdetail":{"job":1}
,"=newjob":{"(badjob1.class)":1,"(badjob2.class)":1}
,"(badjob1.class)":{".withidentity":1}
,".withidentity":{"badjob1":1,"trigger1":1,"badjob2":1,"trigger2":1}
,"group1":{".build":1,".startat":1}
,".build":{"simpletrigger":1,"date":1,"trigger":1,"=sched.schedulejob":1}
,"simpletrigger":{"trigger":1}
,"=newtrigger":{".withidentity":1}
,"trigger1":{"group1":1}
,".startat":{"(starttime)":1}
,"(starttime)":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(3)":1}
,"(3)":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1}
,"date":{"=sched.schedulejob":1}
,"=sched.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"trigger)":{"job":1,"scheduler":1}
,"(badjob2.class)":{".withidentity":1}
,"trigger2":{"group1":1}
,"started":{"sched.start":1}
,"sched.start":{"scheduler":1}
,"opportunity":{"run":1}
,"sleep":{"minute":1}
,"minute":{"(60":1}
,"(60":{"seconds)":1}
,"seconds)":{"thread.sleep":1}
,"thread.sleep":{"(60l":1}
,"(60l":{"*1000l)":1}
,"*1000l)":{"scheduler":1}
,"(badjob1":{"badjob2)":1}
,"badjob2)":{"job":1}
,"attempt":{"refire":1}
,"finally":{"program":1}
,"gracefully":{"shuts":1}
,"shuts":{"down":1}
,"sched.shutdown":{"(true)":1}
,"passing":{"true":1}
,"true":{"shutdown":1}
,"method":{"tells":1,"call":1}
,"tells":{"quartz":1}
,"until":{"jobs":1}
,"completed":{"running":1}
,"returning":{"method":1}
}
;Search.control.loadWordPairs(pairs);
