var pairs =
{
"questions":{"transactions":1}
,"transactions":{"i\u0027m":1,"locking":1}
,"i\u0027m":{"using":1,"seeing":1}
,"using":{"jobstorecmt":1,"scheduler":1,"usertransaction":1,"oracle":1}
,"jobstorecmt":{"i\u0027m":1,"currently":1}
,"seeing":{"deadlocks":1}
,"deadlocks":{"jobstorecmt":1,"cases":1,"databases":1,"takes":1,"oracle":1}
,"currently":{"used":1}
,"used":{"heavy":1}
,"heavy":{"load":1}
,"load":{"sites":1}
,"sites":{"believed":1}
,"believed":{"free":1}
,"free":{"bugs":1}
,"bugs":{"cause":1}
,"cause":{"deadlock":1}
,"deadlock":{"however":1}
,"however":{"every":1}
,"every":{"user":1}
,"user":{"complains":1,"error":1}
,"complains":{"deadlocks":1}
,"cases":{"thus":1}
,"thus":{"far":1}
,"far":{"turned":1}
,"turned":{"user":1}
,"error":{"list":1}
,"list":{"below":1}
,"below":{"describes":1}
,"describes":{"things":1}
,"things":{"check":1}
,"check":{"experiencing":1}
,"experiencing":{"deadlocks":1}
,"databases":{"falsely":1}
,"falsely":{"detect":1}
,"detect":{"deadlocks":1}
,"takes":{"long":1}
,"long":{"time":1}
,"time":{"sure":1}
,"sure":{"put":1,"least":1,"managed":1,"work":1,"transaction":1}
,"put":{"indexes":1}
,"indexes":{"tables":1}
,"tables":{"(see":1}
,"(see":{"improving":1}
,"improving":{"performance":1}
,"performance":{"jdbcjobstore)":1}
,"jdbcjobstore)":{"sure":1}
,"least":{"number-of-threads-in-thread-pool":1}
,"number-of-threads-in-thread-pool":{"connections":1}
,"connections":{"datasources":1}
,"datasources":{"sure":1}
,"managed":{"non-managed":1}
,"non-managed":{"datasource":1}
,"datasource":{"configured":1}
,"configured":{"quartz":1}
,"quartz":{"sure":1,"config":1,"known":1}
,"work":{"scheduler":1,"done":1,"fine":1}
,"scheduler":{"interface":1,"within":1,"sure":1}
,"interface":{"done":1}
,"done":{"within":1,"jobs":1}
,"within":{"transaction":1,"sessionbean":1,"messagedrivenbean":1}
,"transaction":{"accomplish":1,"progress":1}
,"accomplish":{"using":1}
,"sessionbean":{"settings":1}
,"settings":{"required":1,"finally":1}
,"required":{"container":1}
,"container":{"within":1}
,"messagedrivenbean":{"similar":1}
,"similar":{"settings":1}
,"finally":{"start":1}
,"start":{"usertransaction":1}
,"usertransaction":{"yourself":1,"setting":1}
,"yourself":{"commit":1}
,"commit":{"work":1}
,"jobs":{"execute":1}
,"execute":{"methods":1}
,"methods":{"scheduler":1}
,"progress":{"using":1}
,"setting":{"quartz":1}
,"config":{"property":1}
,"property":{"org.quartz.scheduler.wrapjobexecutioninusertransaction=true":1}
,"org.quartz.scheduler.wrapjobexecutioninusertransaction=true":{"i\u0027m":1}
,"oracle":{"rac":1}
,"rac":{"i\u0027m":1,"limitations":1,"you\u0027re":1}
,"limitations":{"relating":1}
,"relating":{"transactions":1}
,"locking":{"quartz":1}
,"known":{"work":1}
,"fine":{"oracle":1}
,"you\u0027re":{"careful":1,"having":1}
,"careful":{"setup":1}
,"setup":{"qtz-149":1}
,"qtz-149":{"issue":1}
,"issue":{"contains":1}
,"contains":{"discussion":1}
,"discussion":{"links":1}
,"links":{"may":1}
,"may":{"help":1}
,"help":{"you\u0027re":1}
,"having":{"issues":1}
}
;Search.control.loadWordPairs(pairs);
