var pairs =
{
"jdbc":{"jobstorecmt":1,"connections":1,"jobstore":1}
,"jobstorecmt":{"configuration":1,"relies":1,"actually":1,"appropriate":1,"tuned":1,"required":1,"requires":1,"experimental":1}
,"configuration":{"jdbcjobstore":1,"properties":1,"org.quartz.jobstore.nonmanagedtxdatasource":1,"docs":1,"feature":1}
,"jdbcjobstore":{"used":1,"classes":1,"values":1}
,"used":{"store":1,"within":1,"property":1,"produce":1,"locking":1,"users":1}
,"store":{"scheduling":1,"data":1}
,"scheduling":{"information":1,"part":1}
,"information":{"(job":1,"datasource":1,"configuration":1}
,"(job":{"triggers":1}
,"triggers":{"calendars)":1,"jobstore":1,"may":1,"fire":1}
,"calendars)":{"within":1}
,"within":{"relational":1,"weblogic)":1,"application":1,"database":1,"explicit":1}
,"relational":{"database":1}
,"database":{"actually":1,"systems":1,"multiple":1,"different":1,"tables":1,"lock":1}
,"actually":{"two":1,"requires":1}
,"two":{"separate":1,"datasources":1}
,"separate":{"jdbcjobstore":1}
,"classes":{"select":1,"blob":1,"implement":1,"simplepropertiestriggerpersistencedelegatesupport":1}
,"select":{"depending":1,"*from":1,"appropriate":1}
,"depending":{"transactional":1}
,"transactional":{"behavior":1}
,"behavior":{"need":1,"occur":1}
,"need":{"jobstorecmt":1}
,"relies":{"upon":1}
,"upon":{"transactions":1}
,"transactions":{"managed":1,"jobstorecmt":1,"(such":1,"typically":1,"value":1,"org.quartz.jobstore.txisolationlevelreadcommitted":1,"org.quartz.jobstore.acquiretriggerswithinlock":1}
,"managed":{"application":1}
,"application":{"using":1,"server":1}
,"using":{"quartz":1,"jta":1,"following":1,"jobstorecmt":1}
,"quartz":{"jta":1,"obtain":1,"directly":1,"tables":1,"database":1,"call":1,"2.1.1":1,"select":1,"may":1,"pages":1}
,"jta":{"transaction":1,"transactions":1,"(i.e":1}
,"transaction":{"progress":1,"jobstorecmt":1}
,"progress":{"attempt":1}
,"attempt":{"schedule":1}
,"schedule":{"(or":1}
,"(or":{"unschedule)":1,"true":1}
,"unschedule)":{"jobs\u002Ftriggers":1}
,"jobs\u002Ftriggers":{"allows":1}
,"allows":{"work":1}
,"work":{"scheduling":1,"jobstore":1,"stdjdbcdelegate":1,"delegates":1}
,"part":{"applications":1,"container-managed":1}
,"applications":{"larger":1,"using":1}
,"larger":{"transaction":1}
,"requires":{"two":1,"(second)":1}
,"datasources":{"datasource":1,"defined":1}
,"datasource":{"connection\u0027s":1,"contains":1,"configured":1,"configuration":1,"contain":1,"(s)":1}
,"connection\u0027s":{"transactions":1}
,"server":{"(via":1,"sybase)":1,"quartz":1,"users":1}
,"(via":{"jta)":1}
,"jta)":{"connections":1}
,"connections":{"participate":1,"capable":1,"part":1,"words":1,"legal":1,"obtained":1,"helpful":1}
,"participate":{"global":1}
,"global":{"(jta)":1}
,"(jta)":{"transactions":1}
,"appropriate":{"applications":1,"(pre-bundled)":1}
,"(such":{"via":1,"db2)":1}
,"via":{"ejb":1,"jndi":1}
,"ejb":{"session":1}
,"session":{"beans)":1}
,"beans)":{"perform":1}
,"perform":{"work":1}
,"jobstore":{"selected":1,"handle":1,"used":1}
,"selected":{"setting":1}
,"setting":{"org.quartz.jobstore.class":1,"parameter":1}
,"org.quartz.jobstore.class":{"property":1,"=org.quartz.impl.jdbcjobstore.jobstorecmt":1}
,"property":{"org.quartz.jobstore.class":1,"name":1,"string":1,"configuration)":1,"true":1,"defaults":1,"org.quartz.jobstore.dontsetautocommitfalse":1,"tells":1,"called":1}
,"=org.quartz.impl.jdbcjobstore.jobstorecmt":{"jobstorecmt":1}
,"tuned":{"using":1}
,"following":{"properties":1}
,"properties":{"property":1,"file":1,"(and":1}
,"name":{"required":1,"datasources":1,"org.quartz.jobstore.txisolationlevelserializable":1,"used":1}
,"required":{"type":1,"datasource":1}
,"type":{"default":1}
,"default":{"value":1,"select":1,"batchtriggeracquisitionmaxcount":1,"quartz":1}
,"value":{"org.quartz.jobstore.driverdelegateclass":1,"property":1,"(if":1,"true":1,"false":1}
,"org.quartz.jobstore.driverdelegateclass":{"string":1,"driver":1}
,"string":{"null":1,"qrtz_\u0022":1,"select":1,"equal":1,"selects":1,"works":1,"follows":1}
,"null":{"org.quartz.jobstore.datasource":1,"org.quartz.jobstore":1,"org.quartz.jobstore.tableprefix":1,"org.quartz.jobstore.driverdelegateinitstring":1,"org.quartz.jobstore.driverdelegateclass":1}
,"org.quartz.jobstore.datasource":{"string":1,"value":1}
,"org.quartz.jobstore":{"nonmanagedtxdatasource":1,"maxmisfirestohandleatatime":1,"dontsetautocommitfalse":1,"dontsetnonmanagedtxconnection":1,"txisolationlevelserializable":1,"txisolationlevelreadcommitted":1,"acquiretriggerswithinlock":1}
,"nonmanagedtxdatasource":{"string":1,"org.quartz.jobstore.selectwithlocksql":1}
,"org.quartz.jobstore.tableprefix":{"string":1,"jdbcjobstore\u0027s":1}
,"qrtz_\u0022":{"org.quartz.jobstore.useproperties":1}
,"org.quartz.jobstore.useproperties":{"boolean":1,"useproperties":1}
,"boolean":{"false":1}
,"false":{"org.quartz.jobstore.misfirethreshold":1,"org.quartz.jobstore.clustercheckininterval":1,"org.quartz.jobstore":1,"org.quartz.jobstore.selectwithlocksql":1,"(or":1,"drivers":1,"org.quartz.scheduler.batchtriggeracquisitionmaxcount":1}
,"org.quartz.jobstore.misfirethreshold":{"int":1,"number":1}
,"int":{"60000":1,"org.quartz.jobstore":1}
,"60000":{"org.quartz.jobstore.isclustered":1,"(60":1}
,"org.quartz.jobstore.isclustered":{"boolean":1,"true":1}
,"org.quartz.jobstore.clustercheckininterval":{"long":1,"frequency":1}
,"long":{"15000":1,"enough":1}
,"15000":{"org.quartz.jobstore":1}
,"maxmisfirestohandleatatime":{"int":1}
,"dontsetautocommitfalse":{"boolean":1}
,"dontsetnonmanagedtxconnection":{"autocommitfalse":1}
,"autocommitfalse":{"boolean":1}
,"org.quartz.jobstore.selectwithlocksql":{"string":1,"sql":1}
,"*from":{"{0}":1}
,"{0}":{"locks":1,"replaced":1}
,"locks":{"sched_name":1,"table":1}
,"sched_name":{"={1}":1}
,"={1}":{"lock_name":1}
,"lock_name":{"update":1}
,"update":{"org.quartz.jobstore":1,"query":1}
,"txisolationlevelserializable":{"boolean":1}
,"txisolationlevelreadcommitted":{"boolean":1}
,"acquiretriggerswithinlock":{"boolean":1}
,"true":{"-see":1,"order":1,"having":1,"tells":1,"property":1,"avoid":1,"default":1}
,"-see":{"doc":1}
,"doc":{"below)":1}
,"below)":{"org.quartz.jobstore.lockhandler.class":1}
,"org.quartz.jobstore.lockhandler.class":{"string":1,"class":1}
,"org.quartz.jobstore.driverdelegateinitstring":{"string":1,"pipe-delimited":1}
,"driver":{"delegates":1,"complains":1}
,"delegates":{"understand":1,"databases":1,"ship":1}
,"understand":{"dialects":1}
,"dialects":{"various":1}
,"various":{"database":1}
,"systems":{"possible":1}
,"possible":{"choices":1}
,"choices":{"include":1}
,"include":{"org.quartz.impl.jdbcjobstore.stdjdbcdelegate":1}
,"org.quartz.impl.jdbcjobstore.stdjdbcdelegate":{"(for":1}
,"(for":{"fully":1,"microsoft":1,"weblogic":1,"oracle":1}
,"fully":{"jdbc-compliant":1}
,"jdbc-compliant":{"drivers)":1}
,"drivers)":{"org.quartz.impl.jdbcjobstore.mssqldelegate":1,"org.quartz.impl.jdbcjobstore.oracle.oracledelegate":1}
,"org.quartz.impl.jdbcjobstore.mssqldelegate":{"(for":1}
,"microsoft":{"sql":1}
,"sql":{"server":1,"string":1}
,"sybase)":{"org.quartz.impl.jdbcjobstore.postgresqldelegate":1}
,"org.quartz.impl.jdbcjobstore.postgresqldelegate":{"org.quartz.impl.jdbcjobstore.weblogicdelegate":1}
,"org.quartz.impl.jdbcjobstore.weblogicdelegate":{"(for":1}
,"weblogic":{"drivers)":1}
,"org.quartz.impl.jdbcjobstore.oracle.oracledelegate":{"org.quartz.impl.jdbcjobstore.oracle.weblogicoracledelegate":1}
,"org.quartz.impl.jdbcjobstore.oracle.weblogicoracledelegate":{"(for":1}
,"oracle":{"drivers":1}
,"drivers":{"used":1,"require":1}
,"weblogic)":{"org.quartz.impl.jdbcjobstore.oracle.weblogic.weblogicoracledelegate":1,"org.quartz.impl.jdbcjobstore.cloudscapedelegate":1}
,"org.quartz.impl.jdbcjobstore.oracle.weblogic.weblogicoracledelegate":{"(for":1}
,"org.quartz.impl.jdbcjobstore.cloudscapedelegate":{"org.quartz.impl.jdbcjobstore.db2v6delegate":1}
,"org.quartz.impl.jdbcjobstore.db2v6delegate":{"org.quartz.impl.jdbcjobstore.db2v7delegate":1}
,"org.quartz.impl.jdbcjobstore.db2v7delegate":{"org.quartz.impl.jdbcjobstore.db2v8delegate":1}
,"org.quartz.impl.jdbcjobstore.db2v8delegate":{"org.quartz.impl.jdbcjobstore.hsqldbdelegate":1}
,"org.quartz.impl.jdbcjobstore.hsqldbdelegate":{"org.quartz.impl.jdbcjobstore.pointbasedelegate":1}
,"org.quartz.impl.jdbcjobstore.pointbasedelegate":{"org.quartz.impl.jdbcjobstore.sybasedelegate":1}
,"org.quartz.impl.jdbcjobstore.sybasedelegate":{"note":1}
,"note":{"databases":1}
,"databases":{"known":1,"derby":1,"{0}":1,"high":1,"(such":1,"longer":1}
,"known":{"work":1}
,"stdjdbcdelegate":{"others":1,"descendants":1}
,"others":{"known":1}
,"derby":{"example":1}
,"example":{"works":1}
,"works":{"cloudscape":1,"databases":1}
,"cloudscape":{"delegate":1}
,"delegate":{"org.quartz.jobstore.datasource":1,"custom":1}
,"defined":{"configuration":1}
,"file":{"jobstorecmt":1,"datasource":1}
,"contains":{"connections":1}
,"capable":{"participating":1}
,"participating":{"jta":1}
,"(i.e":{"container-managed)":1}
,"container-managed)":{"transactions":1}
,"typically":{"means":1}
,"means":{"datasource":1}
,"configured":{"maintained":1,"above":1}
,"maintained":{"within":1}
,"obtain":{"handle":1}
,"handle":{"via":1,"given":1}
,"jndi":{"information":1}
,"org.quartz.jobstore.nonmanagedtxdatasource":{"jobstorecmt":1}
,"(second)":{"datasource":1}
,"container-managed":{"transactions":1}
,"contain":{"non-cmt":1}
,"non-cmt":{"connections":1}
,"words":{"connections":1}
,"legal":{"quartz":1}
,"directly":{"call":1}
,"call":{"commit":1,"setautocommit":1,"settransactionisolation":1}
,"commit":{"rollback":1}
,"rollback":{"org.quartz.jobstore.tableprefix":1}
,"jdbcjobstore\u0027s":{"tableprefix":1}
,"tableprefix":{"property":1}
,"equal":{"prefix":1}
,"prefix":{"given":1}
,"given":{"quartz":1,"pass":1}
,"tables":{"created":1,"within":1,"otherwise":1,"locked":1}
,"created":{"database":1}
,"multiple":{"sets":1,"instances":1}
,"sets":{"quartz":1}
,"different":{"table":1}
,"table":{"prefixes":1,"places":1}
,"prefixes":{"org.quartz.jobstore.useproperties":1}
,"useproperties":{"flag":1}
,"flag":{"instructs":1}
,"instructs":{"jdbcjobstore":1}
,"values":{"jobdatamaps":1}
,"jobdatamaps":{"strings":1}
,"strings":{"therefore":1}
,"therefore":{"stored":1}
,"stored":{"name-value":1}
,"name-value":{"pairs":1}
,"pairs":{"rather":1}
,"rather":{"storing":1}
,"storing":{"complex":1,"custom":1}
,"complex":{"objects":1}
,"objects":{"serialized":1}
,"serialized":{"form":1}
,"form":{"blob":1}
,"blob":{"column":1,"org.quartz.jobstore.misfirethreshold":1}
,"column":{"handy":1}
,"handy":{"avoid":1}
,"avoid":{"class":1,"dead-locks":1,"data":1}
,"class":{"-versioning":1,"name":1}
,"-versioning":{"issues":1}
,"issues":{"arise":1}
,"arise":{"serializing":1}
,"serializing":{"non-string":1}
,"non-string":{"classes":1}
,"number":{"milliseconds":1,"misfired":1}
,"milliseconds":{"scheduler":1}
,"scheduler":{"allow":1}
,"allow":{"trigger":1}
,"trigger":{"pass":1,"types":1}
,"pass":{"next-fire-time":1,"handling":1}
,"next-fire-time":{"considered":1}
,"considered":{"misfired":1,"necessary":1}
,"misfired":{"default":1,"triggers":1}
,"(if":{"don\u0027t":1}
,"don\u0027t":{"entry":1}
,"entry":{"property":1}
,"configuration)":{"60000":1}
,"(60":{"seconds)":1}
,"seconds)":{"org.quartz.jobstore.isclustered":1}
,"order":{"turn":1}
,"turn":{"clustering":1}
,"clustering":{"features":1,"<<ffc-this":1}
,"features":{"property":1}
,"having":{"multiple":1}
,"instances":{"quartz":1,"cluster":1,"org.quartz.jobstore.maxmisfirestohandleatatime":1}
,"otherwise":{"data":1}
,"data":{"corruption":1,"advanced":1}
,"corruption":{"erratic":1,"(as":1}
,"erratic":{"behavior":1}
,"occur":{"information":1,"within":1}
,"docs":{"clustering":1}
,"<<ffc-this":{"reference":1}
,"reference":{"linked":1,"lead":1}
,"linked":{"original":1}
,"original":{"content":1}
,"content":{"won\u2019t":1}
,"won\u2019t":{"link":1}
,"link":{"furture":1}
,"furture":{"determine":1}
,"determine":{"reference":1}
,"lead":{"insert":1}
,"insert":{"it.>>":1}
,"it.>>":{"org.quartz.jobstore.clustercheckininterval":1}
,"frequency":{"(in":1}
,"(in":{"milliseconds)":1,"previous":1}
,"milliseconds)":{"instance":1}
,"instance":{"checks-in":1,"org.quartz.impl.jdbcjobstore.semaphore":1}
,"checks-in":{"instances":1}
,"cluster":{"affects":1}
,"affects":{"quickness":1}
,"quickness":{"detecting":1}
,"detecting":{"failed":1}
,"failed":{"instances":1}
,"org.quartz.jobstore.maxmisfirestohandleatatime":{"maximum":1}
,"maximum":{"number":1}
,"handling":{"(more":1}
,"(more":{"couple":1}
,"couple":{"dozen)":1}
,"dozen)":{"once":1}
,"once":{"cause":1,"necessary":1}
,"cause":{"database":1}
,"locked":{"long":1}
,"enough":{"performance":1}
,"performance":{"firing":1,"using":1}
,"firing":{"(not":1}
,"(not":{"misfired)":1}
,"misfired)":{"triggers":1}
,"may":{"hampered":1,"interest":1,"give":1}
,"hampered":{"org.quartz.jobstore.dontsetautocommitfalse":1}
,"org.quartz.jobstore.dontsetautocommitfalse":{"setting":1,"except":1}
,"parameter":{"true":1}
,"tells":{"quartz":1}
,"setautocommit":{"(false)":1}
,"(false)":{"connections":1,"called":1}
,"obtained":{"datasource":1}
,"(s)":{"helpful":1}
,"helpful":{"few":1,"prevent":1}
,"few":{"situations":1}
,"situations":{"driver":1}
,"complains":{"called":1}
,"called":{"already":1,"org.quartz.jobstore.dontsetnonmanagedtxconnectionautocommitfalse":1,"triggerpersistencedelegateclasses":1}
,"already":{"property":1}
,"defaults":{"false":1}
,"require":{"setautocommit":1}
,"org.quartz.jobstore.dontsetnonmanagedtxconnectionautocommitfalse":{"property":1}
,"except":{"applies":1}
,"applies":{"nonmanagedtxdatasource":1}
,"selects":{"row":1}
,"row":{"locks":1,"default":1}
,"places":{"lock":1}
,"lock":{"row":1,"timeouts":1,"once":1}
,"query":{"string":1}
,"replaced":{"run":1,"scheduler\u0027s":1}
,"run":{"time":1}
,"time":{"table_prefix":1}
,"table_prefix":{"configured":1}
,"above":{"{1}":1}
,"{1}":{"replaced":1}
,"scheduler\u0027s":{"name":1}
,"org.quartz.jobstore.txisolationlevelserializable":{"value":1}
,"settransactionisolation":{"(connection.transaction_serializable)":1,"(connection.transaction_read_committed)":1}
,"(connection.transaction_serializable)":{"jdbc":1}
,"prevent":{"lock":1}
,"timeouts":{"databases":1}
,"high":{"loads":1}
,"loads":{"running":1}
,"running":{"long-lasting":1}
,"long-lasting":{"transactions":1}
,"org.quartz.jobstore.txisolationlevelreadcommitted":{"true":1}
,"(connection.transaction_read_committed)":{"non-managed":1}
,"non-managed":{"jdbc":1}
,"db2)":{"high":1}
,"org.quartz.jobstore.acquiretriggerswithinlock":{"whether":1}
,"whether":{"acquisition":1}
,"acquisition":{"next":1}
,"next":{"triggers":1}
,"fire":{"occur":1}
,"explicit":{"database":1}
,"necessary":{"(in":1,"hence":1}
,"previous":{"versions":1}
,"versions":{"quartz)":1}
,"quartz)":{"avoid":1,"support":1}
,"dead-locks":{"particular":1}
,"particular":{"databases":1}
,"longer":{"considered":1,"valid":1}
,"hence":{"default":1}
,"org.quartz.scheduler.batchtriggeracquisitionmaxcount":{"jdbc":1}
,"(as":{"quartz":1}
,"2.1.1":{"true":1}
,"batchtriggeracquisitionmaxcount":{"org.quartz.jobstore.lockhandler.class":1}
,"produce":{"instance":1}
,"org.quartz.impl.jdbcjobstore.semaphore":{"used":1}
,"locking":{"control":1}
,"control":{"job":1}
,"job":{"store":1}
,"advanced":{"configuration":1}
,"feature":{"used":1}
,"users":{"default":1,"jtanonclusteredsemaphore":1}
,"(pre-bundled)":{"semaphore":1}
,"semaphore":{"implementation":1}
,"implementation":{"org.quartz.impl.jdbcjobstore.updatelockrowsemaphore":1,"quartz-441":1}
,"org.quartz.impl.jdbcjobstore.updatelockrowsemaphore":{"quartz-497":1}
,"quartz-497":{"may":1}
,"interest":{"sql":1}
,"jtanonclusteredsemaphore":{"bundled":1}
,"bundled":{"quartz":1}
,"give":{"improved":1}
,"improved":{"performance":1}
,"experimental":{"implementation":1}
,"quartz-441":{"quartz-442":1}
,"quartz-442":{"ffc-the":1}
,"ffc-the":{"references":1}
,"references":{"quartz":1}
,"pages":{"longer":1}
,"valid":{"strike":1}
,"strike":{"statements":1}
,"statements":{"address":1}
,"address":{"future":1}
,"future":{"revision":1}
,"revision":{"org.quartz.jobstore.driverdelegateinitstring":1}
,"pipe-delimited":{"list":1}
,"list":{"properties":1,"classes":1}
,"(and":{"values)":1}
,"values)":{"passed":1}
,"passed":{"driverdelegate":1}
,"driverdelegate":{"during":1}
,"during":{"initialization":1}
,"initialization":{"format":1}
,"format":{"string":1}
,"follows":{"settingname=settingvalue":1}
,"settingname=settingvalue":{"othersettingname=othersettingvalue":1}
,"othersettingname=othersettingvalue":{"stdjdbcdelegate":1}
,"descendants":{"(all":1}
,"(all":{"delegates":1}
,"ship":{"quartz)":1}
,"support":{"property":1}
,"triggerpersistencedelegateclasses":{"comma-separated":1}
,"comma-separated":{"list":1}
,"implement":{"triggerpersistencedelegate":1}
,"triggerpersistencedelegate":{"interface":1}
,"interface":{"storing":1}
,"custom":{"trigger":1}
,"types":{"java":1}
,"java":{"classes":1}
,"simplepropertiestriggerpersistencedelegatesupport":{"simplepropertiestriggerpersistencedelegatesupport":1,"examples":1}
,"examples":{"writing":1}
,"writing":{"persistence":1}
,"persistence":{"delegate":1}
}
;Search.control.loadWordPairs(pairs);
