var pairs =
{
"plugin":{"configuration":1,"logging":1,"catches":1,"job":1,"reads":1,"shutdown-hook":1}
,"configuration":{"listeners":1,"file":1,"logging":1,"xml":1,"shutdown":1}
,"listeners":{"configuring":1}
,"configuring":{"plugins":1,"few":1}
,"plugins":{"configuration":1,"quartz":1}
,"file":{"consists":1,"adds":1,"found":1}
,"consists":{"giving":1}
,"giving":{"name":1}
,"name":{"specifying":1,"properties":1}
,"specifying":{"class":1}
,"class":{"name":1,"no-arg":1}
,"properties":{"instance":1,"reflectively":1}
,"instance":{"class":1}
,"no-arg":{"constructor":1}
,"constructor":{"properties":1}
,"reflectively":{"primitive":1}
,"primitive":{"data":1}
,"data":{"type":1,"processor":1,"class\u2019s":1}
,"type":{"values":1}
,"values":{"(including":1}
,"(including":{"strings)":1}
,"strings)":{"supported":1}
,"supported":{"general":1}
,"general":{"pattern":1}
,"pattern":{"defining":1}
,"defining":{"plug-in":1}
,"plug-in":{"org.quartz.plugin.name.class":1}
,"org.quartz.plugin.name.class":{"=com.foo.mypluginclass":1}
,"=com.foo.mypluginclass":{"org.quartz.plugin.name.propname":1}
,"org.quartz.plugin.name.propname":{"=propvalue":1}
,"=propvalue":{"org.quartz.plugin.name.prop2name":1}
,"org.quartz.plugin.name.prop2name":{"=prop2value":1}
,"=prop2value":{"several":1}
,"several":{"plugins":1}
,"quartz":{"found":1}
,"found":{"org.quartz.plugins":1,"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjob_scheduling_data_1_8.xsd":1}
,"org.quartz.plugins":{"package":1}
,"package":{"(and":1}
,"(and":{"subpackages)":1}
,"subpackages)":{"examples":1}
,"examples":{"configuring":1}
,"few":{"shown":1}
,"shown":{"topics":1}
,"topics":{"follow":1}
,"follow":{"sample":1}
,"sample":{"configuration":1}
,"logging":{"trigger":1}
,"trigger":{"history":1,"events":1,"listener)":1}
,"history":{"plugin":1}
,"catches":{"trigger":1,"event":1}
,"events":{"(it":1}
,"(it":{"trigger":1}
,"listener)":{"logs":1}
,"logs":{"jakarta":1}
,"jakarta":{"commons-logging":1}
,"commons-logging":{"class\u2019s":1}
,"class\u2019s":{"javadoc":1}
,"javadoc":{"list":1,"details":1}
,"list":{"possible":1}
,"possible":{"parameters":1}
,"parameters":{"org.quartz.plugin.trigghistory.class":1}
,"org.quartz.plugin.trigghistory.class":{"=\u005Corg.quartz.plugins.history.loggingtriggerhistoryplugin":1}
,"=\u005Corg.quartz.plugins.history.loggingtriggerhistoryplugin":{"org.quartz.plugin.trigghistory.triggerfiredmessage":1}
,"org.quartz.plugin.trigghistory.triggerfiredmessage":{"=\u005Ctrigger":1}
,"=\u005Ctrigger":{"\u005C{1\u005C}":1}
,"\u005C{1\u005C}":{".\u005C{0\u005C}":1}
,".\u005C{0\u005C}":{"fired":1,"completed":1}
,"fired":{"job":1}
,"job":{"\u005C{6\u005C}":1,"initialization":1}
,"\u005C{6\u005C}":{".\u005C{5\u005C}":1}
,".\u005C{5\u005C}":{"\u005C{4":1}
,"\u005C{4":{"date":1}
,"date":{"hh:mm:ss":1}
,"hh:mm:ss":{"mm\u002Fdd\u002Fyyyy}":1,"mm\u002Fdd\u002Fyyyy\u005C}":1}
,"mm\u002Fdd\u002Fyyyy}":{"org.quartz.plugin.trigghistory.triggercompletemessage":1}
,"org.quartz.plugin.trigghistory.triggercompletemessage":{"=\u005Ctrigger":1}
,"completed":{"firing":1}
,"firing":{"job":1}
,"mm\u002Fdd\u002Fyyyy\u005C}":{"sample":1}
,"xml":{"scheduling":1,"file":1,"schema":1}
,"scheduling":{"data":1}
,"processor":{"plugin":1}
,"initialization":{"plugin":1,"delete":1}
,"reads":{"jobs":1}
,"jobs":{"triggers":1}
,"triggers":{"xml":1}
,"adds":{"scheduler":1}
,"scheduler":{"during":1,"org.quartz.plugin.shutdownhook.class":1}
,"during":{"initialization":1}
,"delete":{"existing":1}
,"existing":{"data":1}
,"details":{"org.quartz.plugin.jobinitializer.class":1}
,"org.quartz.plugin.jobinitializer.class":{"=\u005Corg.quartz.plugins.xml.xmlschedulingdataprocessorplugin":1}
,"=\u005Corg.quartz.plugins.xml.xmlschedulingdataprocessorplugin":{"org.quartz.plugin.jobinitializer.filenames":1}
,"org.quartz.plugin.jobinitializer.filenames":{"=\u005Cdata\u002Fmy_job_data.xml":1}
,"=\u005Cdata\u002Fmy_job_data.xml":{"org.quartz.plugin.jobinitializer.failonfilenotfound":1}
,"org.quartz.plugin.jobinitializer.failonfilenotfound":{"=true":1}
,"=true":{"xml":1}
,"schema":{"definition":1}
,"definition":{"file":1}
,"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjob_scheduling_data_1_8.xsd":{"<<ffc-verify":1}
,"<<ffc-verify":{"correct":1}
,"correct":{"xsd.>>":1}
,"xsd.>>":{"sample":1}
,"shutdown":{"hook":1,"scheduler":1}
,"hook":{"plugin":1}
,"shutdown-hook":{"plugin":1}
,"event":{"jvm":1}
,"jvm":{"terminating":1}
,"terminating":{"calls":1}
,"calls":{"shutdown":1}
,"org.quartz.plugin.shutdownhook.class":{"=\u005Corg.quartz.plugins.management.shutdownhookplugin":1}
,"=\u005Corg.quartz.plugins.management.shutdownhookplugin":{"org.quartz.plugin.shutdownhook.cleanshutdown":1}
,"org.quartz.plugin.shutdownhook.cleanshutdown":{"=true":1}
}
;Search.control.loadWordPairs(pairs);
