var pairs =
{
"how-to":{"store":1}
,"store":{"job":1,"sched.addjob":1}
,"job":{"later":1,"\u002F\u002Fdefine":1,"instance":1,"scheduler\u0027s":1}
,"later":{"storing":1}
,"storing":{"job":1}
,"\u002F\u002Fdefine":{"durable":1}
,"durable":{"job":1}
,"instance":{"(durable":1}
,"(durable":{"jobs":1}
,"jobs":{"exist":1}
,"exist":{"without":1}
,"without":{"triggers)":1}
,"triggers)":{"jobdetail":1}
,"jobdetail":{"job1":1}
,"job1":{"=newjob":1,"group1":1}
,"=newjob":{"(myjobclass.class)":1}
,"(myjobclass.class)":{".withidentity":1}
,".withidentity":{"job1":1}
,"group1":{".storedurably":1}
,".storedurably":{".build":1}
,".build":{"\u002F\u002Fadd":1}
,"\u002F\u002Fadd":{"job":1}
,"scheduler\u0027s":{"store":1}
,"sched.addjob":{"(job":1}
,"(job":{"false)":1}
}
;Search.control.loadWordPairs(pairs);
