var pairs =
{
"rmi":{"configuration":1,"need":1,"create":1,"codebase":1,"server":1,"registry":1,"service":1}
,"configuration":{"none":1}
,"none":{"primary":1}
,"primary":{"properties":1}
,"properties":{"required":1,"false":1}
,"required":{"reasonable":1,"default":1}
,"reasonable":{"defaults":1}
,"defaults":{"using":1}
,"using":{"quartz":1,"existing":1}
,"quartz":{"via":1,"configured":1,"scheduler":1,"cause":1,"create":1,"first":1,"attempt":1}
,"via":{"rmi":1}
,"need":{"start":1,"understanding":1}
,"start":{"instance":1}
,"instance":{"quartz":1}
,"configured":{"export":1}
,"export":{"services":1,"itself":1,"property":1}
,"services":{"via":1}
,"create":{"clients":1,"registry":1}
,"clients":{"server":1}
,"server":{"configuring":1,"users":1,"work":1,"org.quartz.scheduler.rmi.registryhost":1}
,"configuring":{"quartz":1}
,"scheduler":{"proxy":1,"export":1,"service":1,"bound":1,"org.quartz.scheduler.rmi.proxy":1}
,"proxy":{"work":1}
,"work":{"server":1,"problems":1}
,"users":{"experience":1}
,"experience":{"problems":1}
,"problems":{"class":1,"you\u0027ll":1}
,"class":{"availability":1}
,"availability":{"(namely":1}
,"(namely":{"job":1}
,"job":{"classes)":1}
,"classes)":{"client":1}
,"client":{"server":1}
,"you\u0027ll":{"need":1}
,"understanding":{"rmi":1}
,"codebase":{"security":1,"http:\u002F\u002Fwww.kedwards.com\u002Fjini\u002Fcodebase.html":1,"used":1}
,"security":{"managers":1}
,"managers":{"may":1}
,"may":{"find":1}
,"find":{"resources":1}
,"resources":{"useful":1}
,"useful":{"description":1}
,"description":{"rmi":1}
,"http:\u002F\u002Fwww.kedwards.com\u002Fjini\u002Fcodebase.html":{"(one":1}
,"(one":{"important":1}
,"important":{"points":1}
,"points":{"realize":1}
,"realize":{"codebase":1}
,"used":{"client.)":1}
,"client.)":{"java":1}
,"java":{"api":1}
,"api":{"docs":1}
,"docs":{"rmisecuritymanager":1}
,"rmisecuritymanager":{"property":1}
,"property":{"name":1,"org.quartz.rmi.registryhost":1,"ignored":1}
,"name":{"required":1}
,"default":{"value":1,"rmi":1}
,"value":{"org.quartz.scheduler.rmi.export":1}
,"org.quartz.scheduler.rmi.export":{"false":1,"true":1,"org.quartz.scheduler.rmi.proxyto":1}
,"false":{"org.quartz.scheduler.rmi.registryhost":1,"org.quartz.scheduler.rmi.export":1,"don\u0027t":1,"course":1}
,"org.quartz.scheduler.rmi.registryhost":{"\u0027localhost":1,"host":1}
,"\u0027localhost":{"org.quartz.scheduler.rmi.registryport":1,"port":1}
,"org.quartz.scheduler.rmi.registryport":{"1099":1,"port":1,"property":1}
,"1099":{"org.quartz.scheduler.rmi.createregistry":1,"sense":1}
,"org.quartz.scheduler.rmi.createregistry":{"\u0027never":1,"specifies":1}
,"\u0027never":{"org.quartz.scheduler.rmi.serverport":1}
,"org.quartz.scheduler.rmi.serverport":{"random":1,"port":1}
,"random":{"org.quartz.scheduler.rmi.proxy":1}
,"org.quartz.scheduler.rmi.proxy":{"false":1,"connect":1,"flag":1}
,"true":{"want":1,"as_needed":1,"specify":1,"config":1}
,"want":{"quartz":1}
,"itself":{"via":1}
,"host":{"rmi":1,"port":1}
,"registry":{"found":1,"listening":1,"false":1,"(e.g":1,"running)":1,"fall":1,"created":1,"org.quartz.scheduler.rmi.proxy":1,"process":1}
,"found":{"(often":1}
,"(often":{"localhost)":1}
,"localhost)":{"org.quartz.scheduler.rmi.registryport":1}
,"port":{"rmi":1,"number":1,"quartz":1,"scheduler":1,"1099":1}
,"listening":{"(usually":1}
,"(usually":{"1099)":1}
,"1099)":{"org.quartz.scheduler.rmi.createregistry":1}
,"specifies":{"want":1}
,"cause":{"creation":1}
,"creation":{"rmi":1}
,"don\u0027t":{"want":1}
,"(e.g":{"already":1}
,"already":{"external":1}
,"external":{"registry":1}
,"running)":{"true":1}
,"as_needed":{"want":1}
,"first":{"attempt":1}
,"attempt":{"existing":1,"creating":1}
,"existing":{"registry":1}
,"fall":{"back":1}
,"back":{"creating":1,"using":1}
,"creating":{"always":1,"registry":1}
,"always":{"want":1}
,"created":{"bound":1}
,"bound":{"port":1,"rmi":1}
,"number":{"given":1}
,"given":{"org.quartz.scheduler.rmi.registryport":1}
,"org.quartz.rmi.registryhost":{"localhost":1}
,"localhost":{"org.quartz.scheduler.rmi.serverport":1}
,"service":{"bind":1,"randomly":1}
,"bind":{"listen":1}
,"listen":{"connections":1}
,"connections":{"default":1}
,"randomly":{"select":1}
,"select":{"port":1}
,"connect":{"(use)":1}
,"(use)":{"remotely":1}
,"remotely":{"served":1}
,"served":{"scheduler":1}
,"flag":{"true":1}
,"specify":{"host":1}
,"process":{"-which":1}
,"-which":{"typically":1}
,"typically":{"\u0027localhost":1}
,"sense":{"org.quartz.scheduler.rmi.export":1}
,"org.quartz.scheduler.rmi.proxyto":{"true":1}
,"config":{"file":1}
,"file":{"export":1}
,"ignored":{"setting":1}
,"setting":{"properties":1}
,"course":{"valid":1}
,"valid":{"using":1}
}
;Search.control.loadWordPairs(pairs);
