var pairs =
{
"how-to":{"update":1}
,"update":{"trigger":1}
,"trigger":{"replacing":1,"\u002F\u002Fdefine":1,"trigger":1,"=newtrigger":1,"given":1,"\u002F\u002Fretrieve":1,"oldtrigger":1,"triggerbuilder":1,"\u002F\u002F(other":1,"\u002F\u002Fdesired":1,"newtrigger":1}
,"replacing":{"trigger":1}
,"\u002F\u002Fdefine":{"new":1}
,"new":{"trigger":1,"place":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"newtrigger":1}
,"newtrigger":{"group1":1,"=tb.withschedule":1}
,"group1":{".startnow":1,"trigger)":1,"\u002F\u002Fobtain":1}
,".startnow":{".build":1}
,".build":{"\u002F\u002Ftell":1,"sched.reschedulejob":1}
,"\u002F\u002Ftell":{"scheduler":1}
,"scheduler":{"remove":1}
,"remove":{"old":1}
,"old":{"trigger":1}
,"given":{"key":1}
,"key":{"\u002F\u002Fput":1}
,"\u002F\u002Fput":{"new":1}
,"place":{"sched.reschedulejob":1}
,"sched.reschedulejob":{"(triggerkey":1,"(oldtrigger.getkey":1}
,"(triggerkey":{"oldtrigger":1}
,"oldtrigger":{"group1":1,"=sched.gettrigger":1}
,"trigger)":{"updating":1}
,"updating":{"existing":1}
,"existing":{"trigger":1}
,"\u002F\u002Fretrieve":{"trigger":1}
,"=sched.gettrigger":{"(triggerkey":1}
,"\u002F\u002Fobtain":{"builder":1}
,"builder":{"produce":1,"build":1,"methods":1}
,"produce":{"trigger":1}
,"triggerbuilder":{"=oldtrigger.gettriggerbuilder":1}
,"=oldtrigger.gettriggerbuilder":{"\u002F\u002Fupdate":1}
,"\u002F\u002Fupdate":{"schedule":1}
,"schedule":{"associated":1}
,"associated":{"builder":1}
,"build":{"new":1}
,"\u002F\u002F(other":{"builder":1}
,"methods":{"called":1}
,"called":{"change":1}
,"change":{"trigger":1}
,"\u002F\u002Fdesired":{"way)":1}
,"way)":{"trigger":1}
,"=tb.withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(10)":1}
,"(10)":{".withrepeatcount":1,".build":1}
,".withrepeatcount":{"(10)":1}
,"(oldtrigger.getkey":{"newtrigger)":1}
}
;Search.control.loadWordPairs(pairs);
