var pairs =
{
"example":{"-job":1,"designed":1,"example":1,"executed":1,"example5.sh":1,"resides":1,"made":1}
,"-job":{"misfires":1}
,"misfires":{"example":1,"program":1}
,"designed":{"demonstrate":1}
,"demonstrate":{"concepts":1}
,"concepts":{"related":1}
,"related":{"trigger":1}
,"trigger":{"misfires":1,"firing":1,"=newtrigger":1,"job":1,"soon":1,"fire":1}
,"program":{"perform":1,"wait":1,"statefuldumbjob":1,"starts":1,"sleeps":1,"gracefully":1}
,"perform":{"following":1}
,"following":{"actions":1,"classes":1}
,"actions":{"start":1}
,"start":{"quartz":1}
,"quartz":{"scheduler":1,"refire":1}
,"scheduler":{"schedule":1,"running":1,"done":1,"create":1,"quartz.properties":1,"sched":1,"started":1,"opportunity":1,"sched.shutdown":1,"wait":1}
,"schedule":{"two":1}
,"two":{"jobs":1,"ways":1}
,"jobs":{"job":1,"ten":1,"plenty":1,"completed":1}
,"job":{"execute":1,"different":1,"class":1,"prints":1,"parameter":1,"default":1,"keeps":1,"{public":1,"scheduled":1,"jobdetail":1,"=newjob":1,"job":1,"misfire":1,"uses":1,"program":1}
,"execute":{"every":1,"method":1,"(jobexecutioncontext":1}
,"every":{"three":1,"seconds":1}
,"three":{"seconds":1,"seconds)":1}
,"seconds":{"indefinite":1,"run":1,"job":1,"indefinitely":1,"passed":1}
,"indefinite":{"length":1}
,"length":{"time":1}
,"time":{"jobs":1,"run":1,"waits":1,"completing":1,"defined":1,"seconds":1,"scheduler":1}
,"ten":{"seconds":1,"minutes":1}
,"run":{"(preventing":1,"shut":1,"example":1,"statefuldumbjob":1,"every":1,"job":1}
,"(preventing":{"execution":1}
,"execution":{"trigger":1,"time":1,"count":1,"@persistjobdataafterexecution":1,"delay":1}
,"firing":{"every":1}
,"seconds)":{"job":1,"thread.sleep":1}
,"different":{"misfire":1}
,"misfire":{"instructions":1,"instruction":1,"policy":1}
,"instructions":{"program":1}
,"wait":{"minutes":1,"time":1,"until":1}
,"minutes":{"two":1,"(600":1}
,"plenty":{"time":1}
,"shut":{"down":1}
,"down":{"scheduler":1}
,"running":{"example":1,"returning":1}
,"executed":{"examples\u002Fexample5":1,"using":1}
,"examples\u002Fexample5":{"directory":1}
,"directory":{"two":1}
,"ways":{"run":1}
,"example5.sh":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"script":1}
,"script":{"example5.bat":1}
,"example5.bat":{"windows":1}
,"windows":{"batch":1}
,"batch":{"file":1}
,"file":{"code":1}
,"code":{"code":1,"example":1}
,"resides":{"package":1}
,"package":{"org.quartz.examples.example5":1}
,"org.quartz.examples.example5":{"code":1}
,"made":{"following":1}
,"classes":{"class":1}
,"class":{"name":1,"whose":1,"persistjobdataafterexecution":1,"statefuldumbjob":1}
,"name":{"description":1}
,"description":{"misfireexample":1}
,"misfireexample":{"main":1,"program":1}
,"main":{"program":1}
,"statefuldumbjob":{"simple":1,"statefuldumbjob":1,"implements":1,"public":1}
,"simple":{"job":1,"ram-based":1,"triggers":1}
,"whose":{"execute":1}
,"method":{"takes":1,"tells":1,"call":1}
,"takes":{"seconds":1}
,"prints":{"execution":1}
,"waits":{"period":1}
,"period":{"time":1}
,"completing":{"amount":1}
,"amount":{"wait":1}
,"defined":{"job":1}
,"parameter":{"execution_delay":1,"passed":1}
,"execution_delay":{"job":1,"executiondelay":1}
,"passed":{"job":1}
,"default":{"wait":1,"smart":1}
,"keeps":{"count":1}
,"count":{"times":1,"preserved":1,"policy":1}
,"times":{"executed":1}
,"using":{"value":1,"create":1}
,"value":{"jobdatamap":1}
,"jobdatamap":{"called":1,"map":1}
,"called":{"num_executions":1}
,"num_executions":{"class":1,"numexecutions":1}
,"persistjobdataafterexecution":{"annotation":1}
,"annotation":{"execution":1}
,"preserved":{"execution":1}
,"@persistjobdataafterexecution":{"@disallowconcurrentexecution":1}
,"@disallowconcurrentexecution":{"public":1}
,"public":{"class":1,"static":1,"statefuldumbjob":1,"void":1}
,"implements":{"job":1}
,"{public":{"static":1}
,"static":{"final":1}
,"final":{"string":1}
,"string":{"num_executions":1,"execution_delay":1}
,"numexecutions":{"public":1}
,"executiondelay":{"public":1}
,"void":{"execute":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"{system.err.println":1}
,"{system.err.println":{"(\u0022---\u0022":1}
,"(\u0022---\u0022":{"context.getjobdetail":1}
,"context.getjobdetail":{".getkey":1}
,".getkey":{"executing":1,"complete":1}
,"executing":{"new":1}
,"new":{"date":1}
,"date":{"jobdatamap":1}
,"map":{"=context.getjobdetail":1}
,"=context.getjobdetail":{".getjobdatamap":1}
,".getjobdatamap":{"int":1}
,"int":{"executecount":1}
,"executecount":{"(map.containskey":1,"map.put":1,"misfireexample":1}
,"(map.containskey":{"(num_executions))":1,"(execution_delay))":1}
,"(num_executions))":{"{executecount":1}
,"{executecount":{"=map.getint":1}
,"=map.getint":{"(num_executions)":1}
,"(num_executions)":{"executecount":1}
,"map.put":{"(num_executions":1}
,"(num_executions":{"executecount)":1}
,"executecount)":{"long":1}
,"long":{"delay":1}
,"delay":{"=5000l":1,"seconds":1}
,"=5000l":{"(map.containskey":1}
,"(execution_delay))":{"{delay":1}
,"{delay":{"=map.getlong":1}
,"=map.getlong":{"(execution_delay)":1}
,"(execution_delay)":{"try":1}
,"try":{"{thread.sleep":1}
,"{thread.sleep":{"(delay)":1}
,"(delay)":{"catch":1}
,"catch":{"(exception":1}
,"(exception":{"ignore)":1}
,"ignore)":{"system.err.println":1}
,"system.err.println":{"context.getjobdetail":1}
,"complete":{"executecount":1}
,"starts":{"getting":1}
,"getting":{"instance":1}
,"instance":{"scheduler":1}
,"done":{"creating":1}
,"creating":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"using":1,"scheduler":1}
,"create":{"scheduler":1,"simple":1}
,"ram-based":{"scheduler":1}
,"quartz.properties":{"telling":1}
,"telling":{"otherwise":1}
,"otherwise":{"provided":1}
,"provided":{"schedulerfactory":1}
,"schedulerfactory":{"=new":1}
,"=new":{"stdschedulerfactory":1}
,"sched":{"=sf.getscheduler":1}
,"=sf.getscheduler":{"job":1}
,"scheduled":{"run":1}
,"indefinitely":{"execution":1}
,"jobdetail":{"job":1}
,"=newjob":{"(statefuldumbjob.class)":1}
,"(statefuldumbjob.class)":{".withidentity":1}
,".withidentity":{"statefuljob1":1,"trigger1":1,"statefuljob2":1,"trigger2":1}
,"statefuljob1":{"group1":1}
,"group1":{".usingjobdata":1,".startat":1}
,".usingjobdata":{"(statefuldumbjob.execution_delay":1}
,"(statefuldumbjob.execution_delay":{"10000l)":1}
,"10000l)":{".build":1}
,".build":{"simpletrigger":1,"sched.schedulejob":1,"trigger":1}
,"simpletrigger":{"trigger":1}
,"=newtrigger":{".withidentity":1}
,"trigger1":{"group1":1}
,".startat":{"(starttime)":1}
,"(starttime)":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(3)":1}
,"(3)":{".repeatforever":1}
,".repeatforever":{"())":1,".withmisfirehandlinginstructionnowwithexistingcount":1}
,"())":{".build":1,"\u002F\u002Fset":1}
,"sched.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"trigger)":{"job":1}
,"statefuljob2":{"group1":1}
,"trigger2":{"group1":1}
,".withmisfirehandlinginstructionnowwithexistingcount":{"())":1}
,"\u002F\u002Fset":{"\u2002\u002F\u002Fmisfire":1}
,"\u2002\u002F\u002Fmisfire":{"instruction":1}
,"instruction":{".build":1,"cause":1}
,"cause":{"reschedule":1}
,"reschedule":{"existing":1}
,"existing":{"repeat":1}
,"repeat":{"count":1}
,"policy":{"forces":1,"simple":1}
,"forces":{"quartz":1}
,"refire":{"trigger":1}
,"soon":{"possible":1}
,"possible":{"job":1}
,"uses":{"default":1}
,"smart":{"misfire":1}
,"triggers":{"causes":1}
,"causes":{"trigger":1}
,"fire":{"it\u2019s":1}
,"it\u2019s":{"next":1}
,"next":{"normal":1}
,"normal":{"execution":1}
,"started":{"sched.start":1}
,"sched.start":{"scheduler":1}
,"opportunity":{"run":1}
,"sleeps":{"ten":1}
,"(600":{"seconds)":1}
,"thread.sleep":{"(600l":1}
,"(600l":{"*1000l)":1}
,"*1000l)":{"finally":1}
,"finally":{"program":1}
,"gracefully":{"shuts":1}
,"shuts":{"down":1}
,"sched.shutdown":{"(true)":1}
,"(true)":{"passing":1}
,"passing":{"true":1}
,"true":{"shutdown":1}
,"shutdown":{"method":1}
,"tells":{"quartz":1}
,"until":{"jobs":1}
,"completed":{"running":1}
,"returning":{"method":1}
}
;Search.control.loadWordPairs(pairs);
