var pairs =
{
"jobs":{"triggers":1,"wish":1,"store":1,"remain":1,"maintenance":1,"name":1,"jobdetails":1}
,"triggers":{"job":1,"may":1,"define":1,"expired":1,"given":1,"(jobkey":1,"categories":1,"jobs":1}
,"job":{"class":1,"interface":1,"{public":1,"instance":1,"added":1,"jobdatamap":1,"instantiate":1,"parameters":1,"given":1,"schedulers":1,"identifier":1,"trigger":1,"scheduler":1,"benefit":1,"identities":1}
,"class":{"implements":1,"jobdetail":1}
,"implements":{"job":1}
,"interface":{"shown":1,"simple":1,"job":1}
,"shown":{"below":1}
,"below":{"interface":1}
,"simple":{"method":1}
,"method":{"package":1,"invoked":1,"provides":1}
,"package":{"org.quartz":1}
,"org.quartz":{"public":1}
,"public":{"interface":1}
,"{public":{"void":1}
,"void":{"execute":1}
,"execute":{"(jobexecutioncontext":1,"method":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"job\u0027s":1}
,"job\u0027s":{"trigger":1,"jobdetail":1}
,"trigger":{"fires":1,"triggered":1,"objects":1,"execution":1,"\u0027tune":1,"quartz":1,"types":1,"enables":1,"without":1,"unique":1,"composed":1}
,"fires":{"execute":1}
,"invoked":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"worker":1}
,"worker":{"threads":1}
,"threads":{"jobexecutioncontext":1}
,"jobexecutioncontext":{"object":1}
,"object":{"passed":1,"few":1,"created":1,"contains":1,"essentially":1}
,"passed":{"method":1}
,"provides":{"job":1}
,"instance":{"information":1,"job":1,"trigger":1}
,"information":{"run-time":1,"given":1,"jobs":1}
,"run-time":{"environment":1}
,"environment":{"including":1}
,"including":{"handle":1}
,"handle":{"scheduler":1,"trigger":1}
,"scheduler":{"executed":1,"object":1,"independent":1,"associated":1,"keys":1}
,"executed":{"handle":1}
,"triggered":{"execution":1}
,"execution":{"job\u0027s":1,"(or":1,"(just":1,"job":1,"time":1}
,"jobdetail":{"object":1}
,"few":{"items":1}
,"items":{"jobdetail":1}
,"created":{"quartz":1}
,"quartz":{"client":1,"ships":1,"designed":1,"scheduler":1}
,"client":{"(your":1}
,"(your":{"program)":1}
,"program)":{"time":1}
,"time":{"job":1,"repeat":1,"(or":1}
,"added":{"scheduler":1}
,"contains":{"various":1}
,"various":{"property":1}
,"property":{"settings":1}
,"settings":{"job":1}
,"jobdatamap":{"used":1,"associated":1,"useful":1}
,"used":{"store":1,"trigger":1,"types":1}
,"store":{"state":1,"job":1}
,"state":{"information":1}
,"given":{"instance":1,"moment":1,"time":1,"identifying":1}
,"essentially":{"definition":1}
,"definition":{"job":1}
,"objects":{"used":1,"quartz":1}
,"(or":{"\u0027firing\u0027)":1,"schedule)":1,"identifier)":1}
,"\u0027firing\u0027)":{"jobs":1}
,"wish":{"schedule":1,"triggering":1}
,"schedule":{"job":1,"work":1,"design":1}
,"instantiate":{"trigger":1}
,"\u0027tune":{"properties":1}
,"properties":{"provide":1}
,"provide":{"scheduling":1}
,"scheduling":{"want":1}
,"want":{"triggers":1}
,"may":{"jobdatamap":1}
,"associated":{"jobdatamap":1,"triggers":1,"job":1}
,"useful":{"passing":1,"wish":1,"organizing":1}
,"passing":{"job":1}
,"parameters":{"specific":1}
,"specific":{"firings":1}
,"firings":{"trigger":1}
,"ships":{"handful":1}
,"handful":{"different":1}
,"different":{"trigger":1}
,"types":{"commonly":1,"simpletrigger":1}
,"commonly":{"used":1}
,"simpletrigger":{"crontrigger":1,"handy":1}
,"crontrigger":{"simpletrigger":1,"useful":1}
,"handy":{"need":1}
,"need":{"\u0027one-shot":1,"fire":1}
,"\u0027one-shot":{"execution":1}
,"(just":{"single":1}
,"single":{"execution":1}
,"moment":{"time)":1}
,"time)":{"need":1}
,"fire":{"job":1}
,"repeat":{"times":1}
,"times":{"delay":1}
,"delay":{"executions":1}
,"executions":{"crontrigger":1}
,"triggering":{"based":1}
,"based":{"calendar-like":1}
,"calendar-like":{"schedules":1}
,"schedules":{"every":1}
,"every":{"friday":1,"month":1}
,"friday":{"noon":1}
,"noon":{"10:15":1}
,"10:15":{"10th":1}
,"10th":{"day":1}
,"day":{"every":1}
,"month":{"jobs":1}
,"schedulers":{"separate":1}
,"separate":{"notions":1}
,"notions":{"jobs":1}
,"define":{"\u0027job":1}
,"\u0027job":{"simply":1}
,"simply":{"execution":1}
,"schedule)":{"along":1}
,"along":{"small":1}
,"small":{"job":1}
,"identifier":{"others":1}
,"others":{"union":1}
,"union":{"quartz\u0027s":1}
,"quartz\u0027s":{"job":1}
,"designed":{"create":1}
,"create":{"separation":1,"jobs":1}
,"separation":{"schedule":1}
,"work":{"performed":1}
,"performed":{"schedule":1}
,"design":{"benefits":1}
,"benefits":{"example":1}
,"example":{"create":1}
,"independent":{"trigger":1}
,"enables":{"associate":1,"reschedule":1}
,"associate":{"triggers":1}
,"benefit":{"loose-coupling":1}
,"loose-coupling":{"ability":1}
,"ability":{"configure":1}
,"configure":{"jobs":1}
,"remain":{"scheduler":1}
,"expired":{"enables":1}
,"reschedule":{"later":1}
,"later":{"without":1}
,"without":{"having":1}
,"having":{"re-define":1}
,"re-define":{"allows":1,"associated":1}
,"allows":{"modify":1}
,"modify":{"replace":1}
,"replace":{"trigger":1}
,"identities":{"jobs":1}
,"identifying":{"keys":1}
,"keys":{"registered":1,"jobs":1}
,"registered":{"quartz":1}
,"(jobkey":{"triggerkey)":1}
,"triggerkey)":{"allow":1}
,"allow":{"placed":1}
,"placed":{"\u0027groups":1}
,"\u0027groups":{"useful":1}
,"organizing":{"jobs":1}
,"categories":{"reporting":1}
,"reporting":{"jobs":1}
,"maintenance":{"jobs":1}
,"name":{"portion":1,"group":1}
,"portion":{"key":1}
,"key":{"job":1,"(or":1}
,"unique":{"within":1}
,"within":{"group":1}
,"group":{"words":1,"detailed":1}
,"words":{"complete":1}
,"complete":{"key":1}
,"identifier)":{"job":1}
,"composed":{"name":1}
,"detailed":{"information":1}
,"jobdetails":{"working":1}
,"working":{"triggers":1}
}
;Search.control.loadWordPairs(pairs);
