var pairs =
{
"global":{"listener":1,"listeners":1,"triggerlistener":1,"joblistener":1}
,"listener":{"configuration":1}
,"configuration":{"global":1,"file":1}
,"listeners":{"instantiated":1,"scheduler":1,"listen":1,"configuration":1}
,"instantiated":{"configured":1}
,"configured":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"application":1}
,"application":{"itself":1}
,"itself":{"run":1}
,"run":{"time":1}
,"time":{"register":1}
,"register":{"listeners":1}
,"scheduler":{"global":1}
,"listen":{"events":1}
,"events":{"every":1}
,"every":{"job":1}
,"job":{"trigger":1}
,"trigger":{"rather":1}
,"rather":{"just":1}
,"just":{"jobs":1}
,"jobs":{"triggers":1}
,"triggers":{"reference":1}
,"reference":{"directly":1}
,"directly":{"configuring":1}
,"configuring":{"listeners":1,"global":1}
,"file":{"consists":1}
,"consists":{"giving":1}
,"giving":{"name":1}
,"name":{"specifying":1,"properties":1}
,"specifying":{"class":1}
,"class":{"name":1,"no-arg":1}
,"properties":{"instance":1,"reflectively":1}
,"instance":{"class":1}
,"no-arg":{"constructor":1}
,"constructor":{"properties":1}
,"reflectively":{"primitive":1}
,"primitive":{"data":1}
,"data":{"type":1}
,"type":{"values":1}
,"values":{"(including":1}
,"(including":{"strings)":1}
,"strings)":{"supported":1}
,"supported":{"configuring":1}
,"triggerlistener":{"general":1,"org.quartz.triggerlistener.name.class":1}
,"general":{"pattern":1}
,"pattern":{"defining":1}
,"defining":{"global":1}
,"org.quartz.triggerlistener.name.class":{"=com.foo.mylistenerclass":1}
,"=com.foo.mylistenerclass":{"org.quartz.triggerlistener.name.propname":1,"org.quartz.joblistener.name.propname":1}
,"org.quartz.triggerlistener.name.propname":{"=propvalue":1}
,"=propvalue":{"org.quartz.triggerlistener.name.prop2name":1,"org.quartz.joblistener.name.prop2name":1}
,"org.quartz.triggerlistener.name.prop2name":{"=prop2value":1}
,"=prop2value":{"configuring":1}
,"joblistener":{"general":1,"org.quartz.joblistener.name.class":1}
,"org.quartz.joblistener.name.class":{"=com.foo.mylistenerclass":1}
,"org.quartz.joblistener.name.propname":{"=propvalue":1}
,"org.quartz.joblistener.name.prop2name":{"=prop2value":1}
}
;Search.control.loadWordPairs(pairs);
