var pairs =
{
"example":{"-your":1,"designed":1,"fire":1,"example":1,"executed":1,"example1.sh":1,"resides":1,"made":1}
,"-your":{"first":1}
,"first":{"quartz":1}
,"quartz":{"program":1,"example":1,"scheduler":1,"chance":1,"using":1,"schedule":1}
,"program":{"example":1,"perform":1,"hellojob":1,"starts":1,"sleeps":1,"gracefully":1}
,"designed":{"demonstrate":1}
,"demonstrate":{"running":1}
,"running":{"quartz":1,"example":1,"tell":1,"background":1,"returning":1}
,"fire":{"simple":1,"next":1,"job":1}
,"simple":{"job":1,"ram-based":1}
,"job":{"says":1,"run":1,"shut":1,"implements":1,"interface":1,"exactly":1,"execcuted":1,"quartz":1,"tie":1,"=newjob":1,"trigger":1,"using":1,"scheduled":1,"program":1,"during":1}
,"says":{"hello":1}
,"hello":{"world":1}
,"world":{"program":1,"hellojob":1,"display":1,"new":1}
,"perform":{"following":1}
,"following":{"actions":1,"classes":1}
,"actions":{"start":1}
,"start":{"quartz":1,"sched.start":1}
,"scheduler":{"schedule":1,"running":1,"done":1,"create":1,"schedulerfactory":1,"sched":1,"\u002F\u002Ftell":1,"start":1,"opportunity":1,"sched.shutdown":1,"wait":1}
,"schedule":{"job":1}
,"run":{"next":1,"job":1,"example":1,"trigger":1}
,"next":{"even":1,"round":1}
,"even":{"minute":1}
,"minute":{"wait":1,"\u002F\u002Fcompute":1,"date":1,"trigger":1}
,"wait":{"seconds":1,"until":1}
,"seconds":{"give":1,"scheduler":1,"thread.sleep":1}
,"give":{"quartz":1}
,"chance":{"run":1}
,"shut":{"down":1}
,"down":{"scheduler":1}
,"executed":{"examples\u002Fexample1":1}
,"examples\u002Fexample1":{"directory":1}
,"directory":{"two":1}
,"two":{"ways":1}
,"ways":{"run":1}
,"example1.sh":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"script":1}
,"script":{"example1.bat":1}
,"example1.bat":{"windows":1}
,"windows":{"batch":1}
,"batch":{"file":1}
,"file":{"code":1}
,"code":{"code":1,"example":1}
,"resides":{"package":1}
,"package":{"org.quartz.examples.example1":1}
,"org.quartz.examples.example1":{"code":1}
,"made":{"following":1}
,"classes":{"class":1}
,"class":{"name":1,"\u002F\u002Fdefine":1,"jobdetail":1}
,"name":{"description":1}
,"description":{"simpleexample":1}
,"simpleexample":{"main":1,"program":1}
,"main":{"program":1}
,"hellojob":{"simple":1,"hellojob":1,"defined":1,"class":1}
,"implements":{"job":1}
,"interface":{"logs":1}
,"logs":{"message":1}
,"message":{"log":1}
,"log":{"(by":1}
,"(by":{"default":1}
,"default":{"simply":1}
,"simply":{"screen)":1}
,"screen)":{"current":1}
,"current":{"date":1}
,"date":{"time":1,"())":1,"runtime":1}
,"time":{"printed":1,"next":1}
,"printed":{"job":1}
,"exactly":{"job":1}
,"execcuted":{"public":1}
,"public":{"void":1}
,"void":{"execute":1}
,"execute":{"(jobexecutioncontext":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"{\u002F\u002Fsay":1}
,"{\u002F\u002Fsay":{"hello":1}
,"display":{"date\u002Ftime":1}
,"date\u002Ftime":{"_log.info":1}
,"_log.info":{"hello":1}
,"new":{"date":1}
,"())":{"simpleexample":1,"\u002F\u002Ftrigger":1}
,"starts":{"getting":1}
,"getting":{"instance":1}
,"instance":{"scheduler":1}
,"done":{"creating":1}
,"creating":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"using":1,"scheduler":1}
,"using":{"create":1,"jobdetail":1,"trigger":1}
,"create":{"scheduler":1,"simple":1,"simpletrigger":1}
,"ram-based":{"scheduler":1}
,"schedulerfactory":{"=new":1}
,"=new":{"stdschedulerfactory":1}
,"sched":{"=sf.getscheduler":1}
,"=sf.getscheduler":{"hellojob":1}
,"defined":{"job":1}
,"jobdetail":{"class":1,"job":1}
,"\u002F\u002Fdefine":{"job":1}
,"tie":{"hellojob":1}
,"=newjob":{"(hellojob.class)":1}
,"(hellojob.class)":{".withidentity":1}
,".withidentity":{"job1":1,"trigger1":1}
,"job1":{"group1":1}
,"group1":{".build":1,".startat":1}
,".build":{"create":1,"associate":1}
,"simpletrigger":{"fire":1}
,"round":{"minute":1}
,"\u002F\u002Fcompute":{"time":1}
,"runtime":{"=evenminutedate":1}
,"=evenminutedate":{"(new":1}
,"(new":{"date":1}
,"\u002F\u002Ftrigger":{"job":1}
,"trigger":{"trigger":1,"=newtrigger":1,"scheduler":1,"sched.schedulejob":1,"fires":1}
,"=newtrigger":{".withidentity":1}
,"trigger1":{"group1":1}
,".startat":{"(runtime)":1}
,"(runtime)":{".build":1}
,"associate":{"job":1}
,"\u002F\u002Ftell":{"quartz":1}
,"sched.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"trigger)":{"point":1}
,"point":{"job":1}
,"scheduled":{"run":1}
,"fires":{"however":1}
,"however":{"scheduler":1}
,"tell":{"scheduler":1}
,"sched.start":{"scheduler":1}
,"opportunity":{"run":1}
,"sleeps":{"seconds":1}
,"background":{"fire":1}
,"during":{"seconds":1}
,"thread.sleep":{"(90l":1}
,"(90l":{"*1000l)":1}
,"*1000l)":{"finally":1}
,"finally":{"program":1}
,"gracefully":{"shuts":1}
,"shuts":{"down":1}
,"sched.shutdown":{"(true)":1}
,"(true)":{"passing":1}
,"passing":{"true":1}
,"true":{"shutdown":1}
,"shutdown":{"method":1}
,"method":{"tells":1,"call":1}
,"tells":{"quartz":1}
,"until":{"jobs":1}
,"jobs":{"completed":1}
,"completed":{"running":1}
,"returning":{"method":1}
}
;Search.control.loadWordPairs(pairs);
