var pairs =
{
"example":{"-trigger":1,"demonstrate":1,"example":1,"executed":1,"example14.sh":1,"resides":1,"made":1}
,"-trigger":{"priorities":1}
,"priorities":{"example":1,"manage":1,"fire":1,"act":1}
,"demonstrate":{"trigger":1}
,"trigger":{"priorities":1,"priority10trigger15secondrepeat":1,"priority5trigger10secondrepeat":1,"priorityneg5trigger5secondrepeat":1,"fired":1,"context.gettrigger":1,"priority":1,"trigger1":1,"default":1,"trigger2":1,"trigger3":1,"sched.schedulejob":1}
,"manage":{"firing":1}
,"firing":{"order":1,"times":1}
,"order":{"triggers":1,"priority":1,"staggered":1}
,"triggers":{"fire":1,"different":1,"shut":1,"compete":1,"scheduled":1,"seconds":1,"job":1}
,"fire":{"time":1,"first":1,"triggers":1,"twice":1,"second":1,"job":1}
,"time":{"program":1,"time":1,"second":1,"staggered":1,"order":1,"ordered":1,"five":1,"triggers":1,"need":1}
,"program":{"perform":1,"triggerechojob":1,"starts":1,"sleeps":1,"gracefully":1}
,"perform":{"following":1}
,"following":{"actions":1,"classes":1}
,"actions":{"create":1}
,"create":{"scheduler":1,"ram-based":1,"three":1}
,"scheduler":{"single":1,"wait":1,"running":1,"done":1,"schedulerfactory":1,"sched":1,"instance":1,"worker":1,"first":1,"\u002F\u002Ftell":1,"opportunity":1,"sched.shutdown":1}
,"single":{"worker":1,"thread":1}
,"worker":{"thread":1}
,"thread":{"schedule":1,"priorities":1,"quartz_priority.properties":1,"count":1}
,"schedule":{"three":1,"job":1}
,"three":{"triggers":1,"simpletriggers":1}
,"different":{"priorities":1}
,"first":{"time":1}
,"second":{"time":1,"intervals":1}
,"staggered":{"intervals":1,"firing":1,"five":1}
,"intervals":{"start":1,"\u002F\u002Fcalculate":1}
,"start":{"quartz":1,"time":1,"sched.start":1}
,"quartz":{"scheduler":1,"chance":1,"properties":1,"using":1,"schedule":1}
,"wait":{"seconds":1,"until":1}
,"seconds":{"give":1,"different":1,"date":1,"trigger":1,"scheduler":1,"thread.sleep":1}
,"give":{"quartz":1}
,"chance":{"fire":1}
,"shut":{"down":1}
,"down":{"scheduler":1}
,"running":{"example":1,"tell":1,"background":1,"returning":1}
,"executed":{"examples\u002Fexample14":1}
,"examples\u002Fexample14":{"directory":1}
,"directory":{"two":1}
,"two":{"ways":1}
,"ways":{"run":1}
,"run":{"example":1,"however":1,"job":1}
,"example14.sh":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"script":1}
,"script":{"example14.bat":1}
,"example14.bat":{"windows":1}
,"windows":{"batch":1}
,"batch":{"file":1}
,"file":{"expected":1,"stdschedulerfactory":1}
,"expected":{"results":1}
,"results":{"three":1}
,"twice":{"once":1}
,"once":{"order":1}
,"priority":{"start":1,"org.quartz.threadpool.threadcount=1":1,"repeat":1,"(default)":1}
,"times":{"something":1,"during":1}
,"something":{"log":1}
,"log":{"console":1,"(by":1}
,"console":{"info":1}
,"info":{"aug":1}
,"aug":{"12:15:51.345":1,"12:15:56.220":1,"12:16:01.220":1,"12:16:06.220":1}
,"12:15:51.345":{"priorityexamplescheduler_worker-0":1}
,"priorityexamplescheduler_worker-0":{"org.quartz.examples.example14.triggerechojob":1}
,"org.quartz.examples.example14.triggerechojob":{"trigger":1}
,"priority10trigger15secondrepeat":{"info":1,"code":1,".startat":1}
,"priority5trigger10secondrepeat":{"info":1,".startat":1}
,"priorityneg5trigger5secondrepeat":{"info":1,".startat":1}
,"12:15:56.220":{"priorityexamplescheduler_worker-0":1}
,"12:16:01.220":{"priorityexamplescheduler_worker-0":1}
,"12:16:06.220":{"priorityexamplescheduler_worker-0":1}
,"code":{"code":1,"example":1}
,"resides":{"package":1}
,"package":{"org.quartz.examples.example14":1}
,"org.quartz.examples.example14":{"code":1}
,"made":{"following":1}
,"classes":{"class":1}
,"class":{"name":1,"shown":1}
,"name":{"description":1,"trigger":1}
,"description":{"priorityexample":1}
,"priorityexample":{"main":1,"program":1}
,"main":{"program":1}
,"triggerechojob":{"simple":1,"triggerechojob":1,"defined":1,"null":1}
,"simple":{"job":1}
,"job":{"echoes":1,"implements":1,"interface":1,"quartz":1,"=new":1,"scheduler":1,"itself":1,"using":1,"program":1,"six":1}
,"echoes":{"name":1}
,"fired":{"triggerechojob":1,"log":1}
,"implements":{"job":1}
,"interface":{"writes":1}
,"writes":{"name":1}
,"(by":{"default":1}
,"default":{"simply":1,"group":1,"priority":1}
,"simply":{"screen)":1}
,"screen)":{"public":1}
,"public":{"void":1}
,"void":{"execute":1}
,"execute":{"(jobexecutioncontext":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"{log.info":1}
,"{log.info":{"trigger":1}
,"context.gettrigger":{".getkey":1}
,".getkey":{"())":1}
,"())":{"priorityexample":1}
,"starts":{"getting":1}
,"getting":{"instance":1}
,"instance":{"scheduler":1,"properties":1}
,"done":{"creating":1}
,"creating":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"using":1,"org\u002Fquartz\u002Fexamples\u002Fexample14\u002Fquartz_priority.properties":1,"configure":1}
,"using":{"create":1,"jobdetail":1,"trigger":1}
,"schedulerfactory":{"=new":1}
,"=new":{"stdschedulerfactory":1,"jobdetail":1}
,"org\u002Fquartz\u002Fexamples\u002Fexample14\u002Fquartz_priority.properties":{"scheduler":1}
,"sched":{"=sf.getscheduler":1}
,"=sf.getscheduler":{"pass":1}
,"pass":{"specific":1}
,"specific":{"quartz":1}
,"properties":{"file":1,"create":1}
,"configure":{"new":1}
,"new":{"scheduler":1}
,"ram-based":{"scheduler":1}
,"act":{"tie":1}
,"tie":{"breaker":1}
,"breaker":{"triggers":1}
,"compete":{"single":1}
,"quartz_priority.properties":{"org.quartz.scheduler.instancename=priorityexamplescheduler":1}
,"org.quartz.scheduler.instancename=priorityexamplescheduler":{"thread":1}
,"count":{"force":1}
,"force":{"triggers":1}
,"scheduled":{"time":1,"run":1}
,"ordered":{"priority":1}
,"org.quartz.threadpool.threadcount=1":{"org.quartz.threadpool.class=org.quartz.simpl.simplethreadpool":1}
,"org.quartz.threadpool.class=org.quartz.simpl.simplethreadpool":{"org.quartz.jobstore.class=org.quartz.simpl.ramjobstore":1}
,"org.quartz.jobstore.class=org.quartz.simpl.ramjobstore":{"triggerechojob":1}
,"defined":{"job":1}
,"jobdetail":{"class":1,"job":1,"triggerechojob":1}
,"shown":{"below":1}
,"below":{"passes":1}
,"passes":{"null":1}
,"null":{"group":1,"triggerechojob.class)":1}
,"group":{"default":1,"jobdetail":1}
,"triggerechojob.class)":{"create":1}
,"simpletriggers":{"fire":1}
,"five":{"seconds":1,"second":1}
,"\u002F\u002Fcalculate":{"start":1}
,"date":{"starttime":1}
,"starttime":{"=futuredate":1}
,"=futuredate":{"intervalunit.second)":1}
,"intervalunit.second)":{"\u002F\u002Ffirst":1}
,"\u002F\u002Ffirst":{"trigger":1}
,"repeat":{"seconds":1}
,"trigger1":{"=newtrigger":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"priorityneg5trigger5secondrepeat":1,"priority5trigger10secondrepeat":1,"priority10trigger15secondrepeat":1}
,".startat":{"(starttime)":1}
,"(starttime)":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withrepeatcount":1}
,".withrepeatcount":{"(1)":1}
,"(1)":{".withintervalinseconds":1,".forjob":1}
,".withintervalinseconds":{"(5))":1,"(10))":1,"(15))":1}
,"(5))":{".withpriority":1}
,".withpriority":{"(1)":1,"(10)":1}
,".forjob":{"(job)":1}
,"(job)":{".build":1}
,".build":{"\u002F\u002Fsecond":1,"\u002F\u002Fthird":1,"associate":1}
,"\u002F\u002Fsecond":{"trigger":1}
,"(default)":{"repeat":1}
,"trigger2":{"=newtrigger":1}
,"(10))":{".forjob":1}
,"\u002F\u002Fthird":{"trigger":1}
,"trigger3":{"=newtrigger":1}
,"(15))":{".withpriority":1}
,"(10)":{".forjob":1}
,"associate":{"three":1}
,"need":{"add":1}
,"add":{"job":1}
,"itself":{"scheduler":1}
,"\u002F\u002Ftell":{"quartz":1}
,"sched.schedulejob":{"(job":1,"(trigger2)":1,"(trigger3)":1}
,"(job":{"trigger1)":1}
,"trigger1)":{"sched.schedulejob":1}
,"(trigger2)":{"sched.schedulejob":1}
,"(trigger3)":{"point":1}
,"point":{"triggers":1}
,"however":{"scheduler":1}
,"tell":{"start":1}
,"sched.start":{"scheduler":1}
,"opportunity":{"run":1}
,"sleeps":{"seconds":1}
,"background":{"fire":1}
,"six":{"times":1}
,"during":{"seconds":1}
,"thread.sleep":{"(30l":1}
,"(30l":{"*1000l)":1}
,"*1000l)":{"finally":1}
,"finally":{"program":1}
,"gracefully":{"shuts":1}
,"shuts":{"down":1}
,"sched.shutdown":{"(true)":1}
,"(true)":{"passing":1}
,"passing":{"true":1}
,"true":{"shutdown":1}
,"shutdown":{"method":1}
,"method":{"tells":1,"call":1}
,"tells":{"quartz":1}
,"until":{"jobs":1}
,"jobs":{"completed":1}
,"completed":{"running":1}
,"returning":{"method":1}
}
;Search.control.loadWordPairs(pairs);
