var pairs =
{
"how-to":{"trigger":1}
,"trigger":{"listeners":1,"jobexecutioncontext":1,"scheduler.getlistenermanager":1}
,"listeners":{"creating":1}
,"creating":{"triggerlistener":1}
,"triggerlistener":{"implement":1,"interface":1,"{private":1,"scheduler":1}
,"implement":{"triggerlistener":1}
,"interface":{"package":1}
,"package":{"foo":1}
,"foo":{"import":1}
,"import":{"org.quartz.jobexecutioncontext":1,"org.quartz.trigger":1,"org.quartz.triggerlistener":1,"org.quartz.trigger.completedexecutioninstruction":1,"org.quartz.listeners.triggerlistenersupport":1}
,"org.quartz.jobexecutioncontext":{"import":1}
,"org.quartz.trigger":{"import":1}
,"org.quartz.triggerlistener":{"import":1}
,"org.quartz.trigger.completedexecutioninstruction":{"public":1}
,"public":{"class":1,"mytriggerlistener":1,"string":1,"void":1,"boolean":1,"myothertriggerlistener":1}
,"class":{"mytriggerlistener":1,"myothertriggerlistener":1}
,"mytriggerlistener":{"implements":1,"(string":1,"alltriggers":1,"triggerkeyequals":1,"triggergroupequals":1}
,"implements":{"triggerlistener":1}
,"{private":{"string":1}
,"string":{"name":1,"getname":1}
,"name":{"public":1,"@override":1}
,"(string":{"name)":1}
,"name)":{"{this.name":1}
,"{this.name":{"=name":1}
,"=name":{"public":1}
,"getname":{"{return":1}
,"{return":{"name":1}
,"void":{"triggercomplete":1,"triggerfired":1,"triggermisfired":1}
,"triggercomplete":{"(trigger":1}
,"(trigger":{"trigger":1,"trigger)":1}
,"jobexecutioncontext":{"context":1,"context)":1}
,"context":{"completedexecutioninstruction":1}
,"completedexecutioninstruction":{"triggerinstructioncode)":1}
,"triggerinstructioncode)":{"{\u002F\u002Fdo":1}
,"{\u002F\u002Fdo":{"something":1}
,"something":{"event":1}
,"event":{"public":1,"return":1,"registering":1}
,"triggerfired":{"(trigger":1}
,"context)":{"{\u002F\u002Fdo":1}
,"triggermisfired":{"(trigger":1}
,"trigger)":{"{\u002F\u002Fdo":1}
,"boolean":{"vetojobexecution":1}
,"vetojobexecution":{"(trigger":1}
,"return":{"false":1}
,"false":{"-or":1}
,"-or":{"-extend":1}
,"-extend":{"triggerlistenersupport":1}
,"triggerlistenersupport":{"package":1,"{private":1}
,"org.quartz.listeners.triggerlistenersupport":{"public":1}
,"myothertriggerlistener":{"extends":1,"(string":1}
,"extends":{"triggerlistenersupport":1}
,"@override":{"public":1}
,"registering":{"triggerlistener":1}
,"scheduler":{"listen":1}
,"listen":{"triggers":1,"specific":1}
,"triggers":{"scheduler.getlistenermanager":1,"group":1}
,"scheduler.getlistenermanager":{".addtriggerlistener":1}
,".addtriggerlistener":{"mytriggerlistener":1}
,"alltriggers":{"())":1}
,"())":{"registering":1}
,"specific":{"trigger":1}
,"triggerkeyequals":{"(triggerkey":1}
,"(triggerkey":{"mytriggername":1}
,"mytriggername":{"mytriggergroup":1}
,"mytriggergroup":{"\u0022)))":1,"\u0022))":1}
,"\u0022)))":{"registering":1}
,"group":{"scheduler.getlistenermanager":1}
,"triggergroupequals":{"mytriggergroup":1}
}
;Search.control.loadWordPairs(pairs);
