var pairs =
{
"components":{"configure":1,"need":1}
,"configure":{"architecture":1}
,"architecture":{"quartz":1}
,"quartz":{"modular":1,"work":1,"executing":1,"users":1,"block":1,"ships":1,"uses":1}
,"modular":{"therefore":1}
,"therefore":{"running":1}
,"running":{"several":1}
,"several":{"components":1}
,"need":{"snapped":1,"configured":1,"even":1,"create":1}
,"snapped":{"together":1}
,"together":{"fortunately":1}
,"fortunately":{"helpers":1}
,"helpers":{"exist":1}
,"exist":{"making":1}
,"making":{"happen":1}
,"happen":{"major":1}
,"major":{"components":1}
,"configured":{"quartz":1,"misfire":1}
,"work":{"threadpool":1}
,"threadpool":{"jobstore":1,"provides":1,"interface":1,"implementation":1,"named":1,"simply":1,"rmi":1}
,"jobstore":{"datasources":1,"threadpool":1}
,"datasources":{"(if":1,"discussed":1}
,"(if":{"necessary)":1}
,"necessary)":{"scheduler":1}
,"scheduler":{"itself":1,"real":1,"instance":1,"create":1,"instances":1,"factories":1}
,"itself":{"threadpool":1,"needs":1,"server":1,"available":1}
,"provides":{"threads":1}
,"threads":{"quartz":1,"pool":1,"may":1,"plenty":1,"tens-of-thousands":1,"small":1}
,"executing":{"jobs":1}
,"jobs":{"threads":1,"run":1,"given":1,"generally":1,"short-lived":1,"trying":1,"fire":1}
,"pool":{"greater":1,"completely":1,"-never":1,"jobstores":1}
,"greater":{"number":1}
,"number":{"jobs":1,"threads":1,"milliseconds":1}
,"run":{"concurrently":1,"time":1}
,"concurrently":{"however":1}
,"however":{"threads":1,"want":1}
,"may":{"bog-down":1,"even":1}
,"bog-down":{"system":1}
,"system":{"quartz":1}
,"users":{"find":1}
,"find":{"five":1,"need":1}
,"five":{"threads":1}
,"plenty":{"fewer":1}
,"fewer":{"100":1}
,"100":{"jobs":1,"threads":1}
,"given":{"time":1,"moment":1,"name":1}
,"time":{"jobs":1,"note":1,"fire":1}
,"generally":{"scheduled":1}
,"scheduled":{"run":1}
,"short-lived":{"(complete":1}
,"(complete":{"quickly)":1}
,"quickly)":{"users":1}
,"even":{"100":1,"cause":1}
,"tens-of-thousands":{"triggers":1}
,"triggers":{"various":1}
,"various":{"schedules":1}
,"schedules":{"end":1}
,"end":{"having":1}
,"having":{"average":1}
,"average":{"100":1}
,"trying":{"execute":1}
,"execute":{"given":1,"number":1}
,"moment":{"finding":1}
,"finding":{"right":1}
,"right":{"size":1}
,"size":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"pool":1,"configured":1}
,"completely":{"dependent":1}
,"dependent":{"you\u0027re":1}
,"you\u0027re":{"using":1}
,"using":{"scheduler":1,"quartz":1}
,"real":{"rules":1}
,"rules":{"keep":1}
,"keep":{"number":1}
,"small":{"possible":1}
,"possible":{"(for":1}
,"(for":{"sake":1}
,"sake":{"machine\u0027s":1}
,"machine\u0027s":{"resources)":1}
,"resources)":{"however":1}
,"want":{"sure":1}
,"sure":{"enough":1}
,"enough":{"jobs":1}
,"fire":{"time":1,"arrives":1}
,"note":{"trigger\u0027s":1}
,"trigger\u0027s":{"time":1}
,"arrives":{"isn\u0027t":1}
,"isn\u0027t":{"available":1}
,"available":{"thread":1,"job":1,"remote":1}
,"thread":{"quartz":1,"comes":1,"misfire":1,"duration":1}
,"block":{"(pause)":1}
,"(pause)":{"until":1}
,"until":{"thread":1}
,"comes":{"available":1}
,"job":{"execute":1}
,"milliseconds":{"later":1}
,"later":{"may":1}
,"cause":{"thread":1}
,"misfire":{"available":1,"threshold":1}
,"duration":{"scheduler\u0027s":1}
,"threshold":{"threadpool":1}
,"interface":{"defined":1,"bundled":1}
,"defined":{"org.quartz.spi":1}
,"org.quartz.spi":{"package":1}
,"package":{"create":1}
,"create":{"threadpool":1,"finally":1,"scheduler":1,"itself":1}
,"implementation":{"quartz":1}
,"ships":{"simple":1}
,"simple":{"(but":1}
,"(but":{"satisfactory)":1}
,"satisfactory)":{"threadpool":1}
,"named":{"org.quartz.simpl.simplethreadpool":1}
,"org.quartz.simpl.simplethreadpool":{"threadpool":1}
,"simply":{"maintains":1}
,"maintains":{"fixed":1}
,"fixed":{"threads":1}
,"-never":{"grows":1}
,"grows":{"shrinks":1}
,"shrinks":{"otherwise":1}
,"otherwise":{"quite":1}
,"quite":{"robust":1}
,"robust":{"tested":1}
,"tested":{"nearly":1}
,"nearly":{"everyone":1}
,"everyone":{"using":1}
,"uses":{"pool":1}
,"jobstores":{"datasources":1,"worth":1,"implement":1,"fit":1}
,"discussed":{"working":1}
,"working":{"jobstores":1}
,"worth":{"noting":1}
,"noting":{"fact":1}
,"fact":{"jobstores":1}
,"implement":{"org.quartz.spi.jobstore":1}
,"org.quartz.spi.jobstore":{"interface":1}
,"bundled":{"jobstores":1}
,"fit":{"needs":1}
,"needs":{"create":1,"given":1}
,"finally":{"need":1}
,"instance":{"scheduler":1}
,"name":{"told":1}
,"told":{"rmi":1}
,"rmi":{"settings":1,"(make":1}
,"settings":{"handed":1,"include":1}
,"handed":{"instances":1}
,"instances":{"jobstore":1,"actually":1}
,"include":{"whether":1}
,"whether":{"scheduler":1}
,"server":{"object":1}
,"object":{"rmi":1}
,"(make":{"itself":1}
,"remote":{"connections)":1,"processes":1}
,"connections)":{"host":1}
,"host":{"port":1}
,"port":{"forth":1}
,"forth":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"(discussed":1,"scheduler":1}
,"(discussed":{"below)":1}
,"below)":{"produce":1}
,"produce":{"scheduler":1}
,"actually":{"proxies":1}
,"proxies":{"(rmi":1}
,"(rmi":{"stubs)":1}
,"stubs)":{"schedulers":1}
,"schedulers":{"created":1}
,"created":{"remote":1}
,"processes":{"information":1}
,"information":{"stdschedulerfactory":1}
}
;Search.control.loadWordPairs(pairs);
