var pairs =
{
"questions":{"clustering":1}
,"clustering":{"(scaling":1,"capabilities":1,"section":1,"features":1}
,"(scaling":{"high-availability)":1}
,"high-availability)":{"features":1}
,"features":{"clustering":1,"read":1,"configuring":1,"rely":1}
,"capabilities":{"exist":1,"offer":1}
,"exist":{"quartz":1}
,"quartz":{"quartz":1,"ships":1,"scheduler":1,"user":1}
,"ships":{"well-proven":1}
,"well-proven":{"clustering":1}
,"offer":{"scaling":1}
,"scaling":{"high":1}
,"high":{"availability":1}
,"availability":{"features":1}
,"read":{"features":1}
,"configuring":{"clustering":1}
,"section":{"quartz":1}
,"scheduler":{"configuration":1}
,"configuration":{"guide":1}
,"guide":{"additional":1,"<<verify":1}
,"additional":{"clustering":1}
,"rely":{"upon":1}
,"upon":{"backing":1}
,"backing":{"database":1}
,"database":{"available":1}
,"available":{"terracotta":1}
,"terracotta":{"information":1,"quartz":1}
,"information":{"capability":1}
,"capability":{"terracotta":1}
,"user":{"guide":1}
,"<<verify":{"free":1}
,"free":{"cost":1}
,"cost":{"foram>>":1}
}
;Search.control.loadWordPairs(pairs);
