var pairs =
{
"quartz":{"scheduler":1}
,"scheduler":{"quartz":1,"capability":1,"allows":1,"enables":1,"provides":1,"familiar":1,"information":1,"documentation":1}
,"capability":{"provided":1}
,"provided":{"terracotta":1}
,"terracotta":{"quartz":1,"clients":1}
,"allows":{"control":1}
,"control":{"jobs":1}
,"jobs":{"execute":1,"triggers":1,"nodes":1}
,"execute":{"quartz":1}
,"enables":{"jobs":1}
,"triggers":{"run":1,"locality":1}
,"run":{"specified":1}
,"specified":{"terracotta":1,"group":1}
,"clients":{"instead":1}
,"instead":{"randomly":1}
,"randomly":{"chosen":1}
,"chosen":{"ones":1}
,"ones":{"quartz":1}
,"provides":{"locality":1}
,"locality":{"api":1}
,"api":{"readable":1,"together":1,"quartz":1}
,"readable":{"fluent":1}
,"fluent":{"interface":1}
,"interface":{"creating":1}
,"creating":{"scheduling":1}
,"scheduling":{"jobs":1}
,"together":{"configuration":1}
,"configuration":{"used":1}
,"used":{"route":1}
,"route":{"jobs":1}
,"nodes":{"based":1,"document":1}
,"based":{"defined":1}
,"defined":{"criteria":1}
,"criteria":{"specific":1}
,"specific":{"resources":1,"system":1}
,"resources":{"constraints":1}
,"constraints":{"free":1}
,"free":{"memory":1}
,"memory":{"specific":1}
,"system":{"characteristics":1,"member":1}
,"characteristics":{"type":1}
,"type":{"operating":1}
,"operating":{"system":1}
,"member":{"specified":1}
,"group":{"nodes":1}
,"document":{"shows":1}
,"shows":{"configure":1}
,"configure":{"locality":1}
,"familiar":{"quartz":1}
,"information":{"quartz":1}
,"documentation":{"http:\u002F\u002Fquartz-scheduler.org\u002Fdocumentation":1}
}
;Search.control.loadWordPairs(pairs);
