var pairs =
{
"welcome":{"quartz":1}
,"quartz":{"scheduler":1}
,"scheduler":{"2.2.x":1,"richly":1,"create":1,"includes":1}
,"2.2.x":{"online":1}
,"online":{"documentation":1}
,"documentation":{"library":1,"quartz":1}
,"library":{"library":1,"contains":1,"integrated":1}
,"contains":{"product":1}
,"product":{"documentation":1}
,"richly":{"featured":1}
,"featured":{"open":1}
,"open":{"source":1}
,"source":{"job":1}
,"job":{"scheduling":1}
,"scheduling":{"library":1}
,"integrated":{"within":1}
,"within":{"virtually":1}
,"virtually":{"java":1,"anything":1}
,"java":{"application":1,"components":1}
,"application":{"quartz":1}
,"create":{"simple":1}
,"simple":{"complex":1}
,"complex":{"schedules":1}
,"schedules":{"executing":1}
,"executing":{"tens":1}
,"tens":{"hundreds":1}
,"hundreds":{"even":1}
,"even":{"tens-of-thousands":1}
,"tens-of-thousands":{"jobs":1}
,"jobs":{"jobs":1,"whose":1}
,"whose":{"tasks":1}
,"tasks":{"defined":1}
,"defined":{"standard":1}
,"standard":{"java":1}
,"components":{"may":1}
,"may":{"execute":1,"program":1}
,"execute":{"virtually":1}
,"anything":{"may":1}
,"program":{"quartz":1}
,"includes":{"enterprise-class":1}
,"enterprise-class":{"features":1}
,"features":{"support":1}
,"support":{"jta":1}
,"jta":{"transactions":1}
,"transactions":{"clustering":1}
}
;Search.control.loadWordPairs(pairs);
