var pairs =
{
"key":{"interfaces":1}
,"interfaces":{"key":1,"quartz":1}
,"quartz":{"api":1,"provides":1,"schedule":1}
,"api":{"scheduler":1,"interacting":1}
,"scheduler":{"-the":1,"job":1,"execute":1,"interface":1,"actually":1,"quartz":1}
,"-the":{"main":1}
,"main":{"api":1}
,"interacting":{"scheduler":1}
,"job":{"-an":1,"executed":1,"tie":1,"=newjob":1,"run":1,"using":1,"definition":1}
,"-an":{"interface":1}
,"interface":{"implemented":1,"used":1,"example":1}
,"implemented":{"components":1}
,"components":{"want":1}
,"want":{"scheduler":1}
,"execute":{"jobdetail":1}
,"jobdetail":{"-used":1,"instances":1,"job":1}
,"-used":{"define":1,"define\u002Fbuild":1}
,"define":{"instances":1,"domain":1}
,"instances":{"jobs":1,"define":1,"scheduler\u2019s":1,"particular":1}
,"jobs":{"trigger":1,"triggerbuilder":1,"triggers":1}
,"trigger":{"component":1,"instances":1,"trigger":1,"=newtrigger":1,"sched.schedulejob":1,"using":1}
,"component":{"defines":1}
,"defines":{"schedule":1}
,"schedule":{"upon":1,"job":1}
,"upon":{"given":1}
,"given":{"job":1}
,"executed":{"jobbuilder":1}
,"jobbuilder":{"-used":1,"class":1}
,"define\u002Fbuild":{"jobdetail":1,"trigger":1}
,"triggerbuilder":{"-used":1,"class":1}
,"scheduler\u2019s":{"life-cycle":1}
,"life-cycle":{"bounded":1}
,"bounded":{"creation":1}
,"creation":{"via":1}
,"via":{"schedulerfactory":1}
,"schedulerfactory":{"call":1}
,"call":{"shutdown":1}
,"shutdown":{"method":1}
,"method":{"once":1,"shown":1}
,"once":{"created":1}
,"created":{"scheduler":1}
,"used":{"add":1}
,"add":{"remove":1}
,"remove":{"list":1}
,"list":{"jobs":1}
,"triggers":{"perform":1,"(execute":1}
,"perform":{"scheduling-related":1}
,"scheduling-related":{"operations":1}
,"operations":{"(such":1}
,"(such":{"pausing":1,"date":1}
,"pausing":{"trigger)":1}
,"trigger)":{"however":1,"block":1}
,"however":{"scheduler":1}
,"actually":{"act":1}
,"act":{"triggers":1}
,"(execute":{"jobs)":1}
,"jobs)":{"until":1}
,"until":{"started":1}
,"started":{"start":1}
,"start":{"method":1}
,"shown":{"instantiating":1}
,"instantiating":{"scheduler":1}
,"provides":{"builder":1}
,"builder":{"classes":1}
,"classes":{"define":1,"methods":1}
,"domain":{"specific":1}
,"specific":{"language":1}
,"language":{"(or":1}
,"(or":{"dsl":1}
,"dsl":{"sometimes":1,"achieved":1}
,"sometimes":{"referred":1}
,"referred":{"fluent":1}
,"fluent":{"interface":1}
,"example":{"\u002F\u002Fdefine":1}
,"\u002F\u002Fdefine":{"job":1}
,"tie":{"hellojob":1}
,"hellojob":{"class":1}
,"class":{"jobdetail":1,"likewise":1,"-as":1,"static":1,"contains":1}
,"=newjob":{"(hellojob.class)":1}
,"(hellojob.class)":{".withidentity":1}
,".withidentity":{"myjob":1,"mytrigger":1}
,"myjob":{"group1":1,"group":1}
,"group1":{"\u002F\u002Fname":1,".build":1,".startnow":1}
,"\u002F\u002Fname":{"myjob":1}
,"group":{"group1":1}
,".build":{"\u002F\u002Ftrigger":1,"\u002F\u002Ftell":1}
,"\u002F\u002Ftrigger":{"job":1}
,"run":{"every":1}
,"every":{"seconds":1}
,"seconds":{"trigger":1}
,"=newtrigger":{".withidentity":1}
,"mytrigger":{"group1":1}
,".startnow":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(40)":1}
,"(40)":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1}
,"\u002F\u002Ftell":{"quartz":1}
,"using":{"trigger":1,"methods":1}
,"sched.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"block":{"code":1}
,"code":{"builds":1}
,"builds":{"job":1,"trigger":1}
,"definition":{"using":1}
,"methods":{"statically":1,"imported":1,"relating":1,"easily":1}
,"statically":{"imported":1}
,"imported":{"jobbuilder":1,"triggerbuilder":1}
,"likewise":{"block":1}
,"-as":{"simpleschedulebulder":1}
,"simpleschedulebulder":{"class":1}
,"static":{"imports":1,"org.quartz.jobbuilder.*":1,"org.quartz.simpleschedulebuilder.*":1,"org.quartz.cronschedulebuilder.*":1,"org.quartz.calendarintervalschedulebuilder.*":1,"org.quartz.triggerbuilder.*":1,"org.quartz.datebuilder.*":1}
,"imports":{"dsl":1}
,"achieved":{"import":1}
,"import":{"statements":1,"static":1}
,"statements":{"import":1}
,"org.quartz.jobbuilder.*":{"import":1}
,"org.quartz.simpleschedulebuilder.*":{"import":1}
,"org.quartz.cronschedulebuilder.*":{"import":1}
,"org.quartz.calendarintervalschedulebuilder.*":{"import":1}
,"org.quartz.triggerbuilder.*":{"import":1}
,"org.quartz.datebuilder.*":{"various":1}
,"various":{"schedulebuilder":1,"methods":1}
,"schedulebuilder":{"classes":1}
,"relating":{"defining":1}
,"defining":{"different":1}
,"different":{"types":1}
,"types":{"schedules":1}
,"schedules":{"datebuilder":1}
,"datebuilder":{"class":1}
,"contains":{"various":1}
,"easily":{"constructing":1}
,"constructing":{"java.util.date":1}
,"java.util.date":{"instances":1}
,"particular":{"points":1}
,"points":{"time":1}
,"time":{"(such":1}
,"date":{"represents":1}
,"represents":{"next":1}
,"next":{"even":1}
,"even":{"hour":1}
,"hour":{"-or":1}
,"-or":{"words":1}
,"words":{"10:00:00":1}
,"10:00:00":{"currently":1}
,"currently":{"9:43:27)":1}
}
;Search.control.loadWordPairs(pairs);
