var pairs =
{
"usage":{"notes":1}
,"notes":{"topic":1}
,"topic":{"contains":1}
,"contains":{"information":1,"deep":1}
,"information":{"functional":1}
,"functional":{"aspects":1}
,"aspects":{"terracotta":1}
,"terracotta":{"quartz":1,"client":1,"clients":1,"server":1,"cluster":1}
,"quartz":{"scheduler":1,"configuration":1,"schedulers":1}
,"scheduler":{"optimizing":1,"execution":1,"node":1,"job":1,"updating":1,"forces":1,"case":1,"employ":1}
,"optimizing":{"terracottajobstore":1}
,"terracottajobstore":{"quartz":1,"contains":1}
,"execution":{"jobs":1,"time":1,"new":1}
,"jobs":{"general":1,"execution":1,"long-running":1,"lessens":1,"lock":1,"fired":1,"across":1}
,"general":{"case":1}
,"case":{"exactly":1,"small":1,"consider":1}
,"exactly":{"quartz":1,"once":1}
,"node":{"terracotta":1,"execute":1,"based":1,"striping":1}
,"client":{"executes":1,"blocks":1,"continues":1}
,"executes":{"clustered":1}
,"clustered":{"job":1,"jobdatamap":1}
,"job":{"job\u0027s":1,"job":1,"repeats":1,"quartz":1,"assigned":1,"added":1,"stateful":1,"completes":1}
,"job\u0027s":{"trigger":1,"jobdatamap":1}
,"trigger":{"fires":1}
,"fires":{"nodes":1}
,"nodes":{"job":1,"exactly":1,"jobs":1}
,"repeats":{"may":1}
,"may":{"executed":1,"useful":1}
,"executed":{"nodes":1}
,"once":{"per":1}
,"per":{"interval":1}
,"interval":{"configured":1}
,"configured":{"possible":1}
,"possible":{"predict":1}
,"predict":{"node":1}
,"execute":{"job":1}
,"assigned":{"specific":1}
,"specific":{"node":1}
,"based":{"certain":1}
,"certain":{"criteria":1}
,"criteria":{"working":1}
,"working":{"jobdatamaps":1}
,"jobdatamaps":{"jobdatamaps":1,"contain":1}
,"contain":{"data":1}
,"data":{"may":1,"mutable":1,"safety":1,"transactions":1}
,"useful":{"jobs":1}
,"time":{"jobdatamap":1,"associated":1}
,"jobdatamap":{"stored":1,"updated":1,"update":1,"terracottajobstore":1,"objects":1,"jobdatamap":1,"introduce":1}
,"stored":{"time":1,"job":1,"again":1,"copy":1,"best":1,"maximize":1}
,"associated":{"job":1}
,"added":{"scheduler":1}
,"updating":{"jobdatamap":1}
,"stateful":{"(meaning":1,"explicitly":1}
,"(meaning":{"implements":1}
,"implements":{"statefuljob":1}
,"statefuljob":{"interface)":1}
,"interface)":{"contents":1}
,"contents":{"jobdatamap":1}
,"updated":{"(from":1}
,"(from":{"within":1}
,"within":{"job)":1}
,"job)":{"during":1}
,"during":{"execution":1}
,"new":{"copy":1}
,"copy":{"jobdatamap":1,"job\u0027s":1,"reflect":1}
,"completes":{"job":1}
,"explicitly":{"stored":1}
,"again":{"changed":1}
,"changed":{"jobdatamap":1}
,"update":{"stored":1}
,"deep":{"copies":1,"copy":1}
,"copies":{"jobdatamap":1}
,"objects":{"reflect":1,"jobdatamap":1,"application":1,"deep":1,"serialized":1,"clustered":1}
,"reflect":{"updates":1,"changes":1}
,"updates":{"made":1}
,"made":{"jobdatamap":1}
,"best":{"practices":1}
,"practices":{"storing":1}
,"storing":{"objects":1}
,"application":{"code":1,"relies":1}
,"code":{"references":1}
,"references":{"mutable":1,"risk":1}
,"mutable":{"jobdatamap":1,"objects":1}
,"relies":{"references":1}
,"risk":{"getting":1}
,"getting":{"stale":1}
,"stale":{"data":1}
,"changes":{"made":1}
,"maximize":{"performance":1,"data":1}
,"performance":{"ensure":1,"terracotta":1,"add":1}
,"ensure":{"long-term":1}
,"long-term":{"compatibility":1}
,"compatibility":{"place":1}
,"place":{"strings":1}
,"strings":{"primitives":1}
,"primitives":{"jobdatamap":1,"cluster":1}
,"serialized":{"prone":1}
,"prone":{"class-versioning":1}
,"class-versioning":{"issues":1}
,"issues":{"putting":1}
,"putting":{"complex":1}
,"complex":{"objects":1}
,"introduce":{"errors":1}
,"errors":{"avoided":1}
,"avoided":{"strings":1}
,"cluster":{"data":1,"asynchronous":1,"however":1,"until":1,"client":1}
,"safety":{"default":1,"requiring":1}
,"default":{"terracotta":1}
,"clients":{"(application":1,"cost":1}
,"(application":{"servers)":1}
,"servers)":{"block":1}
,"block":{"wait":1}
,"wait":{"transaction":1}
,"transaction":{"received":1,"written":1,"committed":1}
,"received":{"acknowledgment":1,"terracotta":1}
,"acknowledgment":{"terracotta":1,"available":1,"received":1}
,"server":{"writing":1,"ensures":1}
,"writing":{"data":1}
,"transactions":{"cluster":1}
,"asynchronous":{"write":1}
,"write":{"mode":1}
,"mode":{"translates":1}
,"translates":{"better":1}
,"better":{"performance":1}
,"however":{"option":1,"using":1}
,"option":{"maximize":1}
,"requiring":{"acknowledgment":1}
,"available":{"using":1}
,"using":{"following":1,"single":1}
,"following":{"quartz":1}
,"configuration":{"property":1}
,"property":{"org.quartz.jobstore.synchronouswrite":1}
,"org.quartz.jobstore.synchronouswrite":{"\u00A0=\u00A0":1}
,"\u00A0=\u00A0":{"true":1}
,"true":{"synchronouswrite":1,"client":1}
,"synchronouswrite":{"true":1}
,"blocks":{"transaction":1}
,"written":{"cluster":1}
,"until":{"acknowledgment":1}
,"ensures":{"transaction":1}
,"committed":{"cluster":1}
,"continues":{"work":1}
,"work":{"effective":1}
,"effective":{"scaling":1,"approach":1,"reduce":1}
,"scaling":{"strategies":1}
,"strategies":{"clustering":1}
,"clustering":{"quartz":1}
,"schedulers":{"effective":1,"run":1,"nodes":1}
,"approach":{"distributing":1}
,"distributing":{"load":1,"jobs":1}
,"load":{"number":1}
,"number":{"nodes":1,"short-lived":1,"schedulers":1}
,"long-running":{"cpu":1}
,"cpu":{"intensive":1}
,"intensive":{"(or":1}
,"(or":{"both)":1}
,"both)":{"distributing":1}
,"lessens":{"burden":1}
,"burden":{"system":1}
,"system":{"resources":1}
,"resources":{"case":1}
,"small":{"jobs":1}
,"lock":{"contention":1,"pattern":1,"becomes":1}
,"contention":{"usually":1,"adding":1}
,"usually":{"infrequent":1}
,"infrequent":{"however":1}
,"single":{"scheduler":1}
,"forces":{"cluster-wide":1}
,"cluster-wide":{"lock":1,"locks":1}
,"pattern":{"degrades":1}
,"degrades":{"performance":1}
,"add":{"clients":1}
,"cost":{"cluster-wide":1}
,"becomes":{"evident":1}
,"evident":{"large":1}
,"large":{"number":1}
,"short-lived":{"jobs":1}
,"fired":{"single":1}
,"consider":{"partitioning":1}
,"partitioning":{"jobs":1}
,"across":{"scheduler":1}
,"employ":{"multiple":1}
,"multiple":{"schedulers":1}
,"run":{"every":1}
,"every":{"node":1}
,"striping":{"cluster-wide":1}
,"locks":{"effective":1}
,"reduce":{"lock":1}
,"adding":{"scale":1}
,"scale":{"intend":1,"measure":1}
,"intend":{"scale":1}
,"measure":{"cluster\u0027s":1}
,"cluster\u0027s":{"throughput":1}
,"throughput":{"test":1}
,"test":{"environment":1}
,"environment":{"discover":1}
,"discover":{"optimal":1}
,"optimal":{"number":1}
}
;Search.control.loadWordPairs(pairs);
