var pairs =
{
"how-to":{"create":1}
,"create":{"trigger":1,"simpletrigger":1}
,"trigger":{"executes":1,"meant":1,"always":1,"=newtrigger":1}
,"executes":{"every":1,"3:00":1}
,"every":{"weeks":1,"two":1,"days.)":1}
,"weeks":{"trigger":1,"(14":1,".build":1}
,"meant":{"fire":1}
,"fire":{"every":1,"3:00":1,"time":1}
,"two":{"days":1,"weeks":1}
,"days":{"crontrigger":1,"daylight":1}
,"crontrigger":{"work":1}
,"work":{"schedule":1}
,"schedule":{"(for":1}
,"(for":{"information":1}
,"information":{"issue":1}
,"issue":{"how-to":1}
,"days.)":{"need":1}
,"need":{"simpletrigger":1}
,"simpletrigger":{"calendarintervaltrigger":1,"create":1,"executes":1}
,"calendarintervaltrigger":{"using":1,"trigger":1}
,"using":{"simpletrigger":1,"calendarintervaltrigger":1}
,"3:00":{"tomorrow":1,"adding":1,"time":1}
,"tomorrow":{"every":1,".withschedule":1}
,"(14":{"*24":1,"*24)":1}
,"*24":{"hours)":1,"hours":1}
,"hours)":{"aware":1}
,"aware":{"trigger":1}
,"always":{"fire":1}
,"adding":{"(14":1}
,"*24)":{"hours":1,"\u2002\u002F\u002Finterval":1}
,"hours":{"days":1,"worth":1}
,"daylight":{"savings":1}
,"savings":{"time":1}
,"time":{"shifts":1,"2:00":1,"started":1,"trigger":1,"15:00:00":1}
,"shifts":{"result":1}
,"result":{"execution":1}
,"execution":{"time":1}
,"2:00":{"4:00":1}
,"4:00":{"depending":1}
,"depending":{"upon":1}
,"upon":{"whether":1}
,"whether":{"3:00":1}
,"started":{"during":1}
,"during":{"dst":1}
,"dst":{"standard":1}
,"standard":{"time":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"trigger3":1}
,"trigger3":{"group1":1}
,"group1":{".startat":1}
,".startat":{"(tomorrowat":1}
,"(tomorrowat":{"(15":1}
,"(15":{"\u002F\u002Ffirst":1,"\u002F\u002F15:00:00":1}
,"\u002F\u002Ffirst":{"fire":1}
,"15:00:00":{"tomorrow":1}
,".withschedule":{"(simpleschedule":1,"(calendarintervalschedule":1}
,"(simpleschedule":{".withintervalinhours":1}
,".withintervalinhours":{"(14":1}
,"\u2002\u002F\u002Finterval":{"actually":1}
,"actually":{"*24":1}
,"worth":{"milliseconds":1}
,"milliseconds":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1}
,".build":{"using":1}
,"\u002F\u002F15:00:00":{"tomorrow":1}
,"(calendarintervalschedule":{".withintervalinweeks":1}
,".withintervalinweeks":{"(2))":1}
,"(2))":{"\u002F\u002Finterval":1}
,"\u002F\u002Finterval":{"calendar":1}
,"calendar":{"weeks":1}
}
;Search.control.loadWordPairs(pairs);
