var pairs =
{
"datasource":{"configuration":1,"(or":1,"itself":1,"specified":1,"max":1,"define":1}
,"configuration":{"you\u0027re":1}
,"you\u0027re":{"using":1}
,"using":{"jdbc-jobstore":1,"jobstorecmt)":1,"jobstorecmt":1}
,"jdbc-jobstore":{"need":1}
,"need":{"datasource":1,"additional":1}
,"(or":{"two":1}
,"two":{"datasources":1}
,"datasources":{"you\u0027re":1,"configured":1}
,"jobstorecmt)":{"datasources":1}
,"configured":{"three":1,"least":1}
,"three":{"ways":1,"may":1}
,"ways":{"pool":1}
,"pool":{"properties":1,"plus":1}
,"properties":{"specified":1,"define":1}
,"specified":{"quartz.properties":1,"quartz":1}
,"quartz.properties":{"file":1}
,"file":{"quartz":1}
,"quartz":{"create":1,"custom":1}
,"create":{"datasource":1}
,"itself":{"jndi":1}
,"jndi":{"location":1}
,"location":{"application":1}
,"application":{"server":1,"making":1}
,"server":{"managed":1}
,"managed":{"datasource":1}
,"custom":{"defined":1}
,"defined":{"org.quartz.utils.connectionprovider":1}
,"org.quartz.utils.connectionprovider":{"implementations":1}
,"implementations":{"recommended":1}
,"recommended":{"datasource":1}
,"max":{"connection":1}
,"connection":{"size":1}
,"size":{"configured":1,"least":1}
,"least":{"number":1,"four":1}
,"number":{"worker":1}
,"worker":{"threads":1}
,"threads":{"thread":1}
,"thread":{"pool":1}
,"plus":{"three":1}
,"may":{"need":1}
,"additional":{"connections":1}
,"connections":{"application":1}
,"making":{"frequent":1}
,"frequent":{"calls":1}
,"calls":{"scheduler":1}
,"scheduler":{"api":1}
,"api":{"using":1}
,"jobstorecmt":{"non-managed":1}
,"non-managed":{"datasource":1}
,"four":{"datasource":1}
,"define":{"(typically":1,"contain":1}
,"(typically":{"two)":1}
,"two)":{"given":1}
,"given":{"name":1}
,"name":{"properties":1,"datasource\u2019s":1,"anything":1}
,"contain":{"name":1}
,"datasource\u2019s":{"name":1}
,"anything":{"want":1}
,"want":{"meaning":1}
,"meaning":{"able":1}
,"able":{"identify":1}
,"identify":{"assigned":1}
,"assigned":{"jdbcjobstore":1}
}
;Search.control.loadWordPairs(pairs);
