var pairs =
{
"adding":{"terracotta":1}
,"terracotta":{"clustering":1,"add":1,"jar":1,"server":1,"kit":1,"toolkit":1,"client":1,"configuration":1,"following":1,"cluster":1,"management":1,"servers":1}
,"clustering":{"quartz":1,"application":1}
,"quartz":{"scheduler":1,"application":1,"documentation":1,"objects":1,"(2.2.0":1,"configuration":1,"available":1,"schedulerand":1}
,"scheduler":{"document":1,"installation":1,"application":1,"guaranteed":1,"however":1,"quartz":1,"instance":1,"default":1,"receives":1,"names":1,"instances)":1,"name":1,"instances":1}
,"document":{"describes":1,"continue":1}
,"describes":{"add":1}
,"add":{"terracotta":1,"following":1,"jar":1,"<jvm-options>-dcom.sun.enterprise.server.ss.asquickstartup=false":1,"quartz":1,"failover":1,"high":1,"second":1}
,"application":{"using":1,"single":1,"run":1,"specified":1,"add":1,"servers":1,"server":1,"server)":1,"nodes":1,"node":1,"application":1}
,"using":{"quartz":1,"jdbc-jobstore":1,"war":1,"different":1,"scheduler":1,"mirror":1}
,"installation":{"running":1,"quartz":1}
,"running":{"quartz":1}
,"single":{"jvm":1}
,"jvm":{"cluster":1}
,"cluster":{"using":1,"terracotta":1,"application":1,"(logically":1,"step":1,"start":1,"add":1,"multiple":1,"closer":1,"unix\u002Flinux":1,"sure":1}
,"jdbc-jobstore":{"cluster":1}
,"jar":{"application":1,"files":1,"contains":1,"(4.0.2":1,"file":1}
,"run":{"terracotta":1,"installer":1,"clients":1,"cluster":1}
,"server":{"array":1,"clustered":1,"add":1,"supported":1,"known":1,"loading":1,"give":1,"local":1,"unix\u002Flinux":1,"machine":1,"found":1,"referred":1,"-->":1,"configure":1,"following":1,"tc-config.xml":1,"start":1,"view":1}
,"array":{"except":1}
,"except":{"noted":1}
,"noted":{"document":1}
,"continue":{"quartz":1}
,"specified":{"quartz":1}
,"documentation":{"prerequisites":1}
,"prerequisites":{"jdk":1}
,"jdk":{"1.6":1}
,"1.6":{"higher":1}
,"higher":{"bigmemory":1,"download":1}
,"bigmemory":{"max":1}
,"max":{"4.0.2":1,"separate":1}
,"4.0.2":{"higher":1}
,"download":{"kit":1}
,"kit":{"run":1,"installing":1}
,"installer":{"machine":1}
,"machine":{"host":1,"creating":1,"server":1,"entering":1}
,"host":{"terracotta":1,"jobstore":1,"server\u0027s":1}
,"clustered":{"quartz":1,"terracotta":1}
,"objects":{"serializable":1,"trigger":1}
,"serializable":{"example":1,"step":1}
,"example":{"create":1,"shows":1,"terracotta":1}
,"create":{"quartz":1,"terracotta":1}
,"trigger":{"types":1}
,"types":{"serializable":1}
,"step":{"install":1,"configure":1,"start":1,"edit":1,"shows":1}
,"install":{"quartz":1,"bigmemory":1,"application":1}
,"guaranteed":{"compatibility":1}
,"compatibility":{"jar":1}
,"files":{"included":1,"application\u0027s":1,"web-inf\u002Flib":1}
,"included":{"terracotta":1,"web-inf\u002Flib":1}
,"installing":{"mixing":1}
,"mixing":{"older":1}
,"older":{"components":1}
,"components":{"may":1}
,"may":{"cause":1}
,"cause":{"errors":1}
,"errors":{"unexpected":1}
,"unexpected":{"behavior":1}
,"behavior":{"install":1}
,"following":{"jar":1,"glassfish":1,"properties":1,"example":1,"quartz.properties":1,"moving":1,"xml":1,"replacing":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"${terracotta_home}\u002Fquartz\u002Fquartz-ee-<quartz-version>":1,"using":1}
,"${terracotta_home}\u002Fquartz\u002Fquartz-ee-<quartz-version>":{".jar":1}
,".jar":{"<quartz-version>":1,"terracotta":1}
,"<quartz-version>":{"current":1}
,"current":{"version":1}
,"version":{"quartz":1,"terracotta":1}
,"(2.2.0":{"higher)":1}
,"higher)":{"${terracotta_home}\u002Fcommon\u002Fterracotta-toolkit-runtime-ee-<version>":1,"using":1}
,"${terracotta_home}\u002Fcommon\u002Fterracotta-toolkit-runtime-ee-<version>":{".jar":1}
,"toolkit":{"jar":1}
,"contains":{"terracotta":1}
,"client":{"libraries":1,"(or":1,"client":1,"load":1,"logs":1}
,"libraries":{"<version>":1}
,"<version>":{"current":1}
,"(4.0.2":{"higher)":1}
,"war":{"file":1}
,"file":{"add":1,"quartz.properties":1,"web-inf\u002Fclasses":1,"included":1,"terracotta":1,"(tc-config.xml":1,"located":1,"called":1}
,"web-inf\u002Flib":{"directory":1,"add":1,"start":1}
,"directory":{"application":1}
,"servers":{"(or":1,"monitor":1,"start":1,"separate":1,"creating":1,"perform":1,"node":1,"org.quartz.jobstore.tcconfigurl":1,"configured":1}
,"(or":{"web":1,"application":1}
,"web":{"containers)":1}
,"containers)":{"work":1}
,"work":{"installation":1}
,"however":{"note":1,"property":1}
,"note":{"following":1}
,"glassfish":{"application":1}
,"<jvm-options>-dcom.sun.enterprise.server.ss.asquickstartup=false":{"<\u002Fjvm-options>":1}
,"<\u002Fjvm-options>":{"domains.xml":1}
,"domains.xml":{"weblogic":1}
,"weblogic":{"application":1,"support":1}
,"supported":{"versions":1}
,"versions":{"weblogic":1}
,"support":{"information":1}
,"information":{"https:\u002F\u002Fconfluence.terracotta.org\u002Fdisplay\u002Frelease\u002Fhome":1}
,"https:\u002F\u002Fconfluence.terracotta.org\u002Fdisplay\u002Frelease\u002Fhome":{"step":1}
,"configure":{"quartz":1,"tc-config.xml":1}
,"configuration":{"file":1,"clustered":1,"terracotta":1,"following":1,"loaded":1,"file\u0027s":1,"source":1,"scheduler":1,"step":1,"add":1}
,"quartz.properties":{"default":1,"follows":1,"property":1,"list":1,"application":1}
,"default":{"application\u0027s":1,"name":1}
,"web-inf\u002Fclasses":{"jar":1}
,"properties":{"quartz.properties":1}
,"follows":{"jobstore":1}
,"jobstore":{"class":1}
,"class":{"terracottajobstore":1}
,"terracottajobstore":{"quartz":1}
,"available":{"org.quartz.jobstore.class":1}
,"org.quartz.jobstore.class":{"=org.terracotta.quartz.enterpriseterracottajobstore":1}
,"=org.terracotta.quartz.enterpriseterracottajobstore":{"org.quartz.jobstore.tcconfigurl":1}
,"org.quartz.jobstore.tcconfigurl":{"=<path\u002Fto\u002Fterracotta\u002Fconfiguration>":1,"point":1,"=localhost:9510":1,"=file:\u002F\u002Fmyhost.mynet.net\u002Fusr\u002Flocal\u002Fterracottahome\u002Ftc-config.xml":1,"property":1,"=<server.1.ip.address>":1}
,"=<path\u002Fto\u002Fterracotta\u002Fconfiguration>":{"property":1}
,"property":{"org.quartz.jobstore.tcconfigurl":1,"org.quartz.scheduler.instancename":1,"required":1,"instantiate":1,"quartz.properties":1}
,"point":{"client":1}
,"server)":{"location":1}
,"location":{"terracotta":1,"accessible":1}
,"known":{"client":1}
,"load":{"configuration":1,"terracotta":1}
,"loading":{"server":1}
,"give":{"server\u0027s":1}
,"server\u0027s":{"hostname":1,"address":1}
,"hostname":{"tsa-port":1}
,"tsa-port":{"(9510":1}
,"(9510":{"default)":1}
,"default)":{"found":1,"path":1}
,"found":{"terracotta":1,"replace":1}
,"shows":{"configuration":1,"run":1}
,"loaded":{"terracotta":1}
,"local":{"host":1}
,"=localhost:9510":{"load":1}
,"(tc-config.xml":{"default)":1}
,"path":{"example":1}
,"located":{"myhost.mynet.net":1}
,"myhost.mynet.net":{"\u002Fusr\u002Flocal\u002Fterracottahome":1}
,"\u002Fusr\u002Flocal\u002Fterracottahome":{"full":1}
,"full":{"uri":1}
,"uri":{"along":1}
,"along":{"configuration":1}
,"file\u0027s":{"name":1}
,"name":{"jobstore":1,"quartz":1,"configured":1,"allows":1,"gave":1,"flag":1}
,"=file:\u002F\u002Fmyhost.mynet.net\u002Fusr\u002Flocal\u002Fterracottahome\u002Ftc-config.xml":{"terracotta":1}
,"source":{"changes":1}
,"changes":{"later":1}
,"later":{"time":1}
,"time":{"updated":1}
,"updated":{"configuration":1}
,"instance":{"name":1}
,"configured":{"following":1,"second":1,"start":1}
,"org.quartz.scheduler.instancename":{"=quartzscheduler":1}
,"=quartzscheduler":{"setting":1}
,"setting":{"property":1}
,"required":{"however":1}
,"instantiate":{"differentiate":1}
,"differentiate":{"two":1}
,"two":{"instances":1}
,"instances":{"scheduler":1,"share":1}
,"receives":{"separate":1}
,"separate":{"store":1,"machines":1,"machine":1}
,"store":{"terracotta":1,"cluster":1}
,"different":{"scheduler":1,"job":1}
,"names":{"allows":1}
,"allows":{"isolate":1,"different":1}
,"isolate":{"different":1}
,"job":{"stores":1,"store":1}
,"stores":{"within":1}
,"within":{"terracotta":1}
,"(logically":{"unique":1}
,"unique":{"scheduler":1}
,"instances)":{"using":1}
,"share":{"job":1}
,"start":{"cluster":1,"terracotta":1,"application":1,"server":1,"becomes":1,"mirrors":1}
,"unix\u002Flinux":{"[prompt]":1}
,"[prompt]":{"${terracotta_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":1,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":1,"${terracotta_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Fstart-tmc.sh":1,"${terracotta_home}\u005Ctools\u005Cmanagement-console\u005Cbin\u005Cstart-tmc.bat":1,"${terracotta_home}\u002Fserver\u002Fbin\u002Fstop-tc-server.sh":1,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstop-tc-server.bat":1}
,"${terracotta_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":{"&on":1,"\u005C-f":1}
,"&on":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":{"start":1,"<path\u005Cto\u005Ctc-config.xml>":1}
,"monitor":{"servers":1}
,"management":{"console":1,"server":1}
,"console":{"unix\u002Flinux":1}
,"${terracotta_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Fstart-tmc.sh":{"&on":1}
,"${terracotta_home}\u005Ctools\u005Cmanagement-console\u005Cbin\u005Cstart-tmc.bat":{"step":1}
,"edit":{"terracotta":1,"org.quartz.jobstore.tcconfigurl":1}
,"clients":{"servers":1,"-->":1}
,"machines":{"add":1}
,"failover":{"(high":1}
,"(high":{"availability)":1}
,"availability)":{"expand":1}
,"expand":{"terracotta":1}
,"high":{"availability":1}
,"availability":{"doing":1}
,"doing":{"following":1}
,"moving":{"terracotta":1}
,"creating":{"cluster":1,"multiple":1}
,"multiple":{"terracotta":1,"application":1}
,"nodes":{"tasks":1}
,"tasks":{"bring":1}
,"bring":{"cluster":1}
,"closer":{"production":1}
,"production":{"architecture":1}
,"architecture":{"procedure":1}
,"procedure":{"shut":1}
,"shut":{"down":1}
,"down":{"terracotta":1}
,"${terracotta_home}\u002Fserver\u002Fbin\u002Fstop-tc-server.sh":{"microsoft":1}
,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstop-tc-server.bat":{"create":1}
,"called":{"tc-config.xml":1}
,"tc-config.xml":{"contents":1,"copy":1,"location":1,"unix\u002Flinux":1}
,"contents":{"similar":1}
,"similar":{"following":1}
,"xml":{"version=\u0022":1}
,"version=\u0022":{"1.0":1}
,"1.0":{"encoding=\u0022":1}
,"encoding=\u0022":{"utf-8":1}
,"utf-8":{"<con:tc-config":1}
,"<con:tc-config":{"xmlns:con=\u0022":1}
,"xmlns:con=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":{"<servers>":1}
,"<servers>":{"<mirror-group":1}
,"<mirror-group":{"group-name=\u0022":1}
,"group-name=\u0022":{"default-group":1}
,"default-group":{"<!--sets":1}
,"<!--sets":{"terracotta":1,"generated":1}
,"replace":{"value":1}
,"value":{"host":1}
,"address":{"-->":1}
,"-->":{"<server":1,"<clients>":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"name=\u0022":1}
,"name=\u0022":{"server1":1,"server2":1}
,"server1":{"<offheap>":1,"name":1,"&on":1,"&if":1}
,"<offheap>":{"<enabled>":1}
,"<enabled>":{"true":1,"false":1}
,"true":{"<\u002Fenabled>":1,"\u0022\u002F>":1}
,"<\u002Fenabled>":{"<maxdatasize>":1,"<\u002Fupdate-check>":1,"<\u002Fgarbage-collection>":1}
,"<maxdatasize>":{"512m":1}
,"512m":{"<\u002Fmaxdatasize>":1}
,"<\u002Fmaxdatasize>":{"<\u002Foffheap>":1}
,"<\u002Foffheap>":{"<tsa-port>":1}
,"<tsa-port>":{"9510":1,"9511":1}
,"9510":{"<\u002Ftsa-port>":1}
,"<\u002Ftsa-port>":{"<jmx-port>":1,"<data>":1}
,"<jmx-port>":{"9520":1}
,"9520":{"<\u002Fjmx-port>":1}
,"<\u002Fjmx-port>":{"<data>":1}
,"<data>":{"terracotta\u002Fdata":1,"terracotta\u002Fdata-dos":1}
,"terracotta\u002Fdata":{"<\u002Fdata>":1}
,"<\u002Fdata>":{"<logs>":1}
,"<logs>":{"terracotta\u002Flogs":1,"terracotta\u002Flogs-dos":1}
,"terracotta\u002Flogs":{"<\u002Flogs>":1}
,"<\u002Flogs>":{"<data-backup>":1,"<\u002Fclients>":1}
,"<data-backup>":{"terracotta\u002Fbackups":1,"terracotta\u002Fbackups-dos":1}
,"terracotta\u002Fbackups":{"<\u002Fdata-backup>":1}
,"<\u002Fdata-backup>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<!--if":1,"<\u002Fmirror-group>":1}
,"<!--if":{"using":1}
,"mirror":{"terracotta":1,"servers":1}
,"referred":{"active-passive":1}
,"active-passive":{"configuration":1}
,"second":{"server":1}
,"server2":{"<offheap>":1}
,"9511":{"<\u002Ftsa-port>":1}
,"terracotta\u002Fdata-dos":{"<\u002Fdata>":1}
,"terracotta\u002Flogs-dos":{"<\u002Flogs>":1}
,"terracotta\u002Fbackups-dos":{"<\u002Fdata-backup>":1}
,"<\u002Fmirror-group>":{"<update-check>":1}
,"<update-check>":{"<enabled>":1}
,"false":{"<\u002Fenabled>":1}
,"<\u002Fupdate-check>":{"<garbage-collection>":1}
,"<garbage-collection>":{"<enabled>":1}
,"<\u002Fgarbage-collection>":{"<restartable":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"\u0022\u002F>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"<!--sets":1}
,"generated":{"client":1}
,"logs":{"saved":1}
,"saved":{"clients":1}
,"<clients>":{"<logs>":1}
,"<\u002Fclients>":{"<\u002Fcon:tc-config>":1}
,"<\u002Fcon:tc-config>":{"install":1}
,"copy":{"tc-config.xml":1,"quartz.properties":1}
,"accessible":{"terracotta":1}
,"perform":{"step":1}
,"schedulerand":{"step":1}
,"node":{"want":1,"edit":1,"ensure":1}
,"want":{"run":1}
,"sure":{"install":1}
,"list":{"terracotta":1}
,"=<server.1.ip.address>":{":9510":1}
,":9510":{"<server.2.ip.address>":1,"copy":1}
,"<server.2.ip.address>":{":9510":1}
,"ensure":{"application\u0027s":1}
,"replacing":{"server1":1}
,"gave":{"server":1}
,"\u005C-f":{"<path\u002Fto\u002Ftc-config.xml>":1}
,"<path\u002Fto\u002Ftc-config.xml>":{"server1":1}
,"<path\u005Cto\u005Ctc-config.xml>":{"server1":1}
,"&if":{"configured":1}
,"entering":{"name":1}
,"flag":{"second":1}
,"becomes":{"mirror":1}
,"mirrors":{"start":1}
,"view":{"cluster":1}
}
;Search.control.loadWordPairs(pairs);
