var pairs =
{
"starting":{"sample":1}
,"sample":{"application":1,"logging":1}
,"application":{"following":1,"terminate":1}
,"following":{"code":1}
,"code":{"obtains":1,"sample":1,"start":1,"samples":1}
,"obtains":{"instance":1}
,"instance":{"scheduler":1}
,"scheduler":{"starts":1,"using":1,"v.2.0.0-snapshot":1,"meta-data":1,"(v2.0.0)":1,"class":1,"\u0027scheduler":1,"version":1,"scheduler_$_non_clustered":1,"example":1}
,"starts":{"shuts":1}
,"shuts":{"down":1}
,"down":{"quartztest.java":1,"[info]":1}
,"quartztest.java":{"import":1}
,"import":{"org.quartz.scheduler":1,"org.quartz.schedulerexception":1,"org.quartz.impl.stdschedulerfactory":1,"static":1}
,"org.quartz.scheduler":{"import":1}
,"org.quartz.schedulerexception":{"import":1}
,"org.quartz.impl.stdschedulerfactory":{"import":1}
,"static":{"org.quartz.jobbuilder.*":1,"org.quartz.triggerbuilder.*":1,"org.quartz.simpleschedulebuilder.*":1,"imports":1}
,"org.quartz.jobbuilder.*":{"import":1}
,"org.quartz.triggerbuilder.*":{"import":1}
,"org.quartz.simpleschedulebuilder.*":{"once":1}
,"once":{"obtain":1}
,"obtain":{"scheduler":1}
,"using":{"stdschedulerfactory.getdefaultscheduler":1,"thread":1,"job-store":1,"trigger":1}
,"stdschedulerfactory.getdefaultscheduler":{"application":1}
,"terminate":{"until":1}
,"until":{"call":1}
,"call":{"scheduler.shutdown":1,"thread.sleep":1}
,"scheduler.shutdown":{"active":1}
,"active":{"threads":1}
,"threads":{"note":1,"using":1}
,"note":{"static":1}
,"imports":{"play":1}
,"play":{"next":1}
,"next":{"code":1}
,"logging":{"log":1}
,"log":{"information":1}
,"information":{"sent":1}
,"sent":{"console":1}
,"console":{"output":1}
,"output":{"look":1}
,"look":{"similar":1}
,"similar":{"[info]":1}
,"[info]":{"jan":1}
,"jan":{"08:46:27.857":1,"08:46:27.859":1,"08:46:27.865":1,"08:46:27.866":1,"08:46:27.867":1}
,"08:46:27.857":{"main":1}
,"main":{"[org.quartz.core.quartzscheduler]":1,"[org.quartz.simpl.ramjobstore]":1,"[org.quartz.impl.stdschedulerfactory]":1}
,"[org.quartz.core.quartzscheduler]":{"quartz":1,"scheduler":1}
,"quartz":{"scheduler":1,"package":1,"schedule":1}
,"v.2.0.0-snapshot":{"created":1}
,"created":{"[info]":1}
,"08:46:27.859":{"main":1}
,"[org.quartz.simpl.ramjobstore]":{"ramjobstore":1}
,"ramjobstore":{"initialized":1}
,"initialized":{"[info]":1,"default":1}
,"08:46:27.865":{"main":1}
,"meta-data":{"quartz":1}
,"(v2.0.0)":{"\u0027scheduler":1}
,"\u0027scheduler":{"instanceid":1,"initialized":1}
,"instanceid":{"\u0027non_clustered":1}
,"\u0027non_clustered":{"scheduler":1}
,"class":{"\u0027org.quartz.core.quartzscheduler":1,"jobdetail":1}
,"\u0027org.quartz.core.quartzscheduler":{"-running":1}
,"-running":{"locally":1}
,"locally":{"started":1}
,"started":{"currently":1,"[info]":1}
,"currently":{"standby":1}
,"standby":{"mode":1}
,"mode":{"number":1}
,"number":{"jobs":1}
,"jobs":{"executed":1}
,"executed":{"using":1,"calling":1}
,"thread":{"pool":1}
,"pool":{"\u0027org.quartz.simpl.simplethreadpool":1}
,"\u0027org.quartz.simpl.simplethreadpool":{"-with":1}
,"-with":{"threads":1}
,"job-store":{"\u0027org.quartz.simpl.ramjobstore":1}
,"\u0027org.quartz.simpl.ramjobstore":{"-which":1}
,"-which":{"support":1}
,"support":{"persistence":1}
,"persistence":{"clustered":1}
,"clustered":{"[info]":1}
,"[org.quartz.impl.stdschedulerfactory]":{"quartz":1}
,"default":{"resource":1}
,"resource":{"file":1}
,"file":{"quartz":1}
,"package":{"\u0027quartz.properties":1}
,"\u0027quartz.properties":{"[info]":1}
,"08:46:27.866":{"main":1}
,"version":{"2.0.0":1}
,"2.0.0":{"[info]":1}
,"scheduler_$_non_clustered":{"started":1,"shutting":1,"paused":1,"shutdown":1}
,"shutting":{"down":1}
,"paused":{"[info]":1}
,"08:46:27.867":{"main":1}
,"shutdown":{"complete":1,"calls":1,"simple":1}
,"complete":{"something":1}
,"something":{"need":1}
,"need":{"provide":1,"allow":1}
,"provide":{"code":1}
,"start":{"shutdown":1}
,"calls":{"need":1}
,"allow":{"time":1}
,"time":{"job":1}
,"job":{"triggered":1,"tie":1,"=newjob":1,"run":1,"using":1}
,"triggered":{"executed":1}
,"calling":{"shutdown":1}
,"simple":{"example":1}
,"example":{"call":1,"programs":1}
,"thread.sleep":{"(60000)":1}
,"(60000)":{"\u002F\u002Fdefine":1}
,"\u002F\u002Fdefine":{"job":1}
,"tie":{"hellojob":1}
,"hellojob":{"class":1}
,"jobdetail":{"job":1}
,"=newjob":{"(hellojob.class)":1}
,"(hellojob.class)":{".withidentity":1}
,".withidentity":{"job1":1,"trigger1":1}
,"job1":{"group1":1}
,"group1":{".build":1,".startnow":1}
,".build":{"\u002F\u002Ftrigger":1,"\u002F\u002Ftell":1}
,"\u002F\u002Ftrigger":{"job":1}
,"run":{"repeat":1}
,"repeat":{"every":1}
,"every":{"seconds":1}
,"seconds":{"trigger":1}
,"trigger":{"trigger":1,"=newtrigger":1,"scheduler.schedulejob":1}
,"=newtrigger":{".withidentity":1}
,"trigger1":{"group1":1}
,".startnow":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(40)":1}
,"(40)":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1}
,"\u002F\u002Ftell":{"quartz":1}
,"schedule":{"job":1}
,"scheduler.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"trigger)":{"additional":1}
,"additional":{"code":1}
,"samples":{"quartz":1}
,"programs":{"code":1}
}
;Search.control.loadWordPairs(pairs);
