var pairs =
{
"creating":{"listeners":1}
,"listeners":{"create":1,"registered":1,"typically":1,"need":1,"used":1,"following":1}
,"create":{"listener":1,"object":1,"need":1}
,"listener":{"simply":1,"wants":1}
,"simply":{"create":1,"override":1}
,"object":{"implements":1}
,"implements":{"org.quartz.triggerlistener":1}
,"org.quartz.triggerlistener":{"and\u002For":1}
,"and\u002For":{"org.quartz.joblistener":1}
,"org.quartz.joblistener":{"interface":1}
,"interface":{"listeners":1}
,"registered":{"scheduler":1,"scheduler\u0027s":1}
,"scheduler":{"run":1,"during":1,"listeners":1}
,"run":{"time":1}
,"time":{"given":1,"stored":1,"application":1}
,"given":{"name":1}
,"name":{"(or":1,"via":1}
,"(or":{"rather":1}
,"rather":{"advertise":1,"implementing":1}
,"advertise":{"name":1}
,"via":{"getname":1}
,"getname":{"method)":1}
,"method)":{"convenience":1}
,"convenience":{"rather":1}
,"implementing":{"interfaces":1}
,"interfaces":{"class":1}
,"class":{"extend":1,"joblistenersupport":1}
,"extend":{"class":1}
,"joblistenersupport":{"triggerlistenersupport":1}
,"triggerlistenersupport":{"simply":1}
,"override":{"events":1}
,"events":{"you\u0027re":1,"listeners":1,"without":1}
,"you\u0027re":{"interested":1}
,"interested":{"listeners":1,"particular":1,"jobs":1}
,"scheduler\u0027s":{"listenermanager":1}
,"listenermanager":{"along":1}
,"along":{"matcher":1,"jobs":1}
,"matcher":{"describes":1,"key":1}
,"describes":{"jobs\u002Ftriggers":1}
,"jobs\u002Ftriggers":{"listener":1}
,"wants":{"receive":1}
,"receive":{"events":1}
,"during":{"run":1}
,"stored":{"jobstore":1}
,"jobstore":{"along":1}
,"jobs":{"triggers":1,"adding":1,"particular":1,"two":1,"scheduler.getlistenermanager":1}
,"triggers":{"listeners":1}
,"typically":{"integration":1}
,"integration":{"point":1}
,"point":{"application":1}
,"application":{"hence":1,"runs":1,"requirements":1,"code":1}
,"hence":{"time":1}
,"runs":{"listeners":1}
,"need":{"re-registered":1,"notification":1}
,"re-registered":{"scheduler":1}
,"used":{"users":1}
,"users":{"quartz":1}
,"quartz":{"handy":1}
,"handy":{"application":1}
,"requirements":{"create":1}
,"notification":{"events":1}
,"without":{"job":1}
,"job":{"itself":1,"scheduler.getlistenermanager":1}
,"itself":{"having":1}
,"having":{"explicitly":1}
,"explicitly":{"notify":1}
,"notify":{"application":1}
,"code":{"samples":1}
,"samples":{"adding":1,"illustrate":1}
,"adding":{"listeners":1,"triggerlisteners":1,"joblistener":1}
,"following":{"code":1}
,"illustrate":{"ways":1}
,"ways":{"add":1}
,"add":{"joblisteners":1}
,"joblisteners":{"interest":1}
,"interest":{"different":1}
,"different":{"types":1}
,"types":{"jobs":1}
,"triggerlisteners":{"works":1}
,"works":{"adding":1}
,"joblistener":{"interested":1}
,"particular":{"job":1,"group":1,"groups":1}
,"scheduler.getlistenermanager":{".addjoblistener":1}
,".addjoblistener":{"(myjoblistener":1}
,"(myjoblistener":{"keymatcher.jobkeyequals":1,"jobkeyequals":1,"jobgroupequals":1,"(jobgroupequals":1,"alljobs":1}
,"keymatcher.jobkeyequals":{"(new":1}
,"(new":{"jobkey":1}
,"jobkey":{"myjobname":1}
,"myjobname":{"myjobgroup":1}
,"myjobgroup":{"\u0022)))":1,"\u0022))":1,"jobgroupequals":1}
,"\u0022)))":{"may":1,"adding":1}
,"may":{"want":1}
,"want":{"static":1}
,"static":{"imports":1,"org.quartz.jobkey.*":1,"org.quartz.impl.matchers.keymatcher.*":1,"org.quartz.impl.matchers.groupmatcher.*":1,"org.quartz.impl.matchers.andmatcher.*":1,"org.quartz.impl.matchers.ormatcher.*":1,"org.quartz.impl.matchers.everythingmatcher.*":1}
,"imports":{"matcher":1}
,"key":{"classes":1}
,"classes":{"defining":1}
,"defining":{"matchers":1}
,"matchers":{"cleaner":1}
,"cleaner":{"import":1}
,"import":{"static":1}
,"org.quartz.jobkey.*":{"import":1}
,"org.quartz.impl.matchers.keymatcher.*":{"import":1}
,"org.quartz.impl.matchers.groupmatcher.*":{"import":1}
,"org.quartz.impl.matchers.andmatcher.*":{"import":1}
,"org.quartz.impl.matchers.ormatcher.*":{"import":1}
,"org.quartz.impl.matchers.everythingmatcher.*":{".etc":1}
,".etc":{"turns":1}
,"turns":{"above":1}
,"above":{"example":1}
,"example":{"scheduler.getlistenermanager":1}
,"jobkeyequals":{"(jobkey":1}
,"(jobkey":{"myjobname":1}
,"group":{"scheduler.getlistenermanager":1}
,"jobgroupequals":{"myjobgroup":1,"yourgroup":1}
,"\u0022))":{"adding":1}
,"two":{"particular":1}
,"groups":{"scheduler.getlistenermanager":1}
,"(jobgroupequals":{"myjobgroup":1}
,"yourgroup":{"\u0022)))":1}
,"alljobs":{"())":1}
}
;Search.control.loadWordPairs(pairs);
