var pairs =
{
"custom":{"connectionprovider":1}
,"connectionprovider":{"implementations":1,"instantiating":1,"implementation":1}
,"implementations":{"property":1}
,"property":{"name":1}
,"name":{"required":1,"connectionprovider":1}
,"required":{"type":1}
,"type":{"default":1}
,"default":{"value":1}
,"value":{"org.quartz.datasource.name":1}
,"org.quartz.datasource.name":{"connectionprovider.class":1}
,"connectionprovider.class":{"string":1}
,"string":{"(class":1}
,"(class":{"name)":1}
,"name)":{"null":1}
,"null":{"org.quartz.datasource.name.connectionprovider.class":1}
,"org.quartz.datasource.name.connectionprovider.class":{"class":1}
,"class":{"name":1,"quartz":1}
,"instantiating":{"class":1}
,"quartz":{"automatically":1}
,"automatically":{"configuration":1}
,"configuration":{"properties":1}
,"properties":{"instance":1}
,"instance":{"bean-style":1}
,"bean-style":{"following":1}
,"following":{"example":1}
,"example":{"using":1}
,"using":{"custom":1}
,"implementation":{"org.quartz.datasource.mycustomds.connectionprovider.class":1}
,"org.quartz.datasource.mycustomds.connectionprovider.class":{"=com.foo.fooconnectionprovider":1}
,"=com.foo.fooconnectionprovider":{"org.quartz.datasource.mycustomds.somestringproperty":1}
,"org.quartz.datasource.mycustomds.somestringproperty":{"=somevalue":1}
,"=somevalue":{"org.quartz.datasource.mycustomds.someintproperty":1}
}
;Search.control.loadWordPairs(pairs);
