var pairs =
{
"simpletrigger":{"simpletrigger":1,"meet":1,"include":1,"instances":1,"trigger":1,"misfire":1,"several":1,"itself":1,"dynamically":1,"instance":1}
,"meet":{"scheduling":1}
,"scheduling":{"needs":1}
,"needs":{"need":1}
,"need":{"job":1}
,"job":{"execute":1,"name":1,"handle":1,"jobkey":1,".build":1}
,"execute":{"exactly":1}
,"exactly":{"once":1,"11:23:54":1,"you\u0027d":1}
,"once":{"specific":1,"five":1}
,"specific":{"moment":1,"interval":1}
,"moment":{"time":1}
,"time":{"specific":1,"followed":1,"fire":1,"rather":1,"looking":1,"(immediately)":1,"repeats":1,"repeating":1,"given":1}
,"followed":{"repeats":1}
,"repeats":{"specific":1,"simpletrigger":1,"give":1}
,"interval":{"example":1,"properties":1,"property":1,"zero":1}
,"example":{"want":1,"\u0027forjob":1}
,"want":{"trigger":1,"fire":1}
,"trigger":{"fire":1,"happen":1,"fire-times":1,"fires":1,"actually":1,"similarly":1,"specific":1,"=(simpletrigger)":1,"=newtrigger":1,"passed":1,"types":1}
,"fire":{"exactly":1,"time":1,"five":1,"end-time":1,"once":1,"repeat":1,"top":1}
,"11:23:54":{"january":1}
,"january":{"2015":1}
,"2015":{"want":1}
,"five":{"times":1,"minutes":1}
,"times":{"every":1,"repeat":1,"trigger":1}
,"every":{"ten":1,"seconds":1,"five":1,"hours":1}
,"ten":{"seconds":1,"times":1}
,"seconds":{"description":1,"until":1,"ten":1}
,"description":{"may":1}
,"may":{"find":1,"demonstrated":1}
,"find":{"surprising":1,"properties":1,"helpful":1}
,"surprising":{"find":1}
,"properties":{"simpletrigger":1,"exactly":1,"explicitly":1}
,"include":{"start-time":1,"misfire_instruction_ignore_misfire_policy":1}
,"start-time":{"end-time":1}
,"end-time":{"repeat":1,"property":1,"simply":1,"arrives)":1}
,"repeat":{"count":1,"interval":1,"start-time":1,"every":1}
,"count":{"repeat":1,"zero":1,"firings":1,"property":1,"repeat_indefinitely":1,"huge":1}
,"you\u0027d":{"expect":1}
,"expect":{"couple":1}
,"couple":{"special":1}
,"special":{"notes":1}
,"notes":{"related":1}
,"related":{"end-time":1}
,"property":{"repeat":1,"zero":1,"(if":1,"useful":1}
,"zero":{"positive":1,"cause":1,"00:00":1}
,"positive":{"integer":1,"long":1}
,"integer":{"constant":1}
,"constant":{"value":1}
,"value":{"simpletrigger.repeat_indefinitely":1,"represents":1,"properties":1}
,"simpletrigger.repeat_indefinitely":{"repeat":1}
,"long":{"value":1}
,"represents":{"number":1}
,"number":{"milliseconds":1,"times":1,"sure":1}
,"milliseconds":{"note":1}
,"note":{"repeat":1,"triggerbuilder":1}
,"cause":{"\u0027repeat":1}
,"\u0027repeat":{"count":1}
,"firings":{"trigger":1,".forjob":1}
,"happen":{"concurrently":1}
,"concurrently":{"(or":1,"scheduler":1}
,"(or":{"close":1,"endtime)":1}
,"close":{"concurrently":1}
,"scheduler":{"manage)":1,"along":1}
,"manage)":{"you\u0027re":1}
,"you\u0027re":{"already":1,"trying":1}
,"already":{"familiar":1}
,"familiar":{"quartz\u0027s":1,"options":1}
,"quartz\u0027s":{"datebuilder":1,"builders)":1}
,"datebuilder":{"class":1,"create":1}
,"class":{"may":1}
,"helpful":{"computing":1}
,"computing":{"trigger":1}
,"fire-times":{"depending":1}
,"depending":{"starttime":1}
,"starttime":{"(or":1}
,"endtime)":{"you\u0027re":1}
,"trying":{"create":1}
,"create":{"endtime":1,"trigger":1,"\u2002\u002F\u002Fa":1}
,"endtime":{"property":1}
,"(if":{"specified)":1,"line":1}
,"specified)":{"overrides":1}
,"overrides":{"repeat":1}
,"useful":{"wish":1}
,"wish":{"create":1}
,"fires":{"every":1}
,"until":{"given":1,"hour":1}
,"given":{"moment":1,"(if":1,"simpletrigger":1}
,"rather":{"having":1}
,"having":{"compute":1}
,"compute":{"number":1}
,"simply":{"specify":1}
,"specify":{"end-time":1,"repeat":1,"misfire":1}
,"repeat_indefinitely":{"(you":1}
,"(you":{"even":1}
,"even":{"specify":1}
,"huge":{"number":1}
,"sure":{"number":1}
,"actually":{"fire":1}
,"arrives)":{"simpletrigger":1}
,"instances":{"built":1}
,"built":{"using":1}
,"using":{"triggerbuilder":1}
,"triggerbuilder":{"(for":1,"simpleschedulebuilder":1,"(and":1,"generate":1}
,"(for":{"trigger\u0027s":1,"simpletrigger-specific":1,"information":1}
,"trigger\u0027s":{"main":1}
,"main":{"properties)":1}
,"properties)":{"simpleschedulebuilder":1,"builders":1}
,"simpleschedulebuilder":{"(for":1,"familiar":1}
,"simpletrigger-specific":{"properties)":1}
,"builders":{"dsl-style":1}
,"dsl-style":{"static":1}
,"static":{"imports":1,"org.quartz.triggerbuilder.*":1,"org.quartz.simpleschedulebuilder.*":1,"org.quartz.datebuilder.*":1}
,"imports":{"import":1}
,"import":{"static":1}
,"org.quartz.triggerbuilder.*":{"import":1}
,"org.quartz.simpleschedulebuilder.*":{"import":1}
,"org.quartz.datebuilder.*":{"examples":1}
,"examples":{"defining":1,"shown":1,"don\u0027t":1}
,"defining":{"triggers":1}
,"triggers":{"different":1,"simple":1,"topic.)":1,"misfire_instruction_smart_policy":1}
,"different":{"schedules":1}
,"schedules":{"following":1,"review":1}
,"following":{"various":1}
,"various":{"examples":1,"misfile":1}
,"simple":{"schedules":1,"schedule":1}
,"review":{"show":1}
,"show":{"least":1}
,"least":{"new\u002Fdifferent":1}
,"new\u002Fdifferent":{"point":1}
,"point":{"spend":1}
,"spend":{"time":1}
,"looking":{"available":1}
,"available":{"methods":1,"may":1,"instruction":1}
,"methods":{"language":1,"triggerbuilder":1}
,"language":{"defined":1}
,"defined":{"triggerbuilder":1,"constants":1}
,"options":{"available":1}
,"demonstrated":{"examples":1}
,"shown":{"note":1}
,"(and":{"quartz\u0027s":1}
,"builders)":{"generally":1}
,"generally":{"choose":1}
,"choose":{"reasonable":1}
,"reasonable":{"value":1}
,"explicitly":{"examples":1}
,"don\u0027t":{"call":1}
,"call":{"withidentity":1,"startat":1}
,"withidentity":{"methods":1}
,"generate":{"random":1}
,"random":{"name":1}
,"name":{"trigger":1,"group":1}
,"similarly":{"don\u2019t":1}
,"don\u2019t":{"call":1}
,"startat":{"current":1}
,"current":{"time":1}
,"(immediately)":{"assumed":1}
,"assumed":{"build":1}
,"build":{"trigger":1}
,"=(simpletrigger)":{"newtrigger":1}
,"newtrigger":{".withidentity":1}
,".withidentity":{"trigger1":1,"trigger3":1,"trigger5":1,"trigger7":1,"trigger8":1}
,"trigger1":{"group1":1}
,"group1":{".startat":1,"\u002F\u002Fidentify":1,".withschedule":1}
,".startat":{"(mystarttime)":1,"(mytimetostartfiring)":1,"(futuredate":1,"(evenhourdate":1}
,"(mystarttime)":{"\u002F\u002Fsome":1}
,"\u002F\u002Fsome":{"date":1}
,"date":{".forjob":1,"future":1}
,".forjob":{"job1":1,"(myjob)":1,"(myjobkey)":1}
,"job1":{"group1":1}
,"\u002F\u002Fidentify":{"job":1}
,"group":{"strings":1,"specified":1,".startat":1}
,"strings":{".build":1}
,".build":{"build":1,"scheduler.schedulejob":1}
,"repeating":{"every":1}
,"=newtrigger":{".withidentity":1}
,"trigger3":{"group1":1}
,"(mytimetostartfiring)":{"\u002F\u002Fif":1}
,"\u002F\u002Fif":{"start":1}
,"start":{"time":1}
,"line":{"\u2002\u002F\u002Fwere":1}
,"\u2002\u002F\u002Fwere":{"omitted)":1}
,"omitted)":{"implied":1}
,"implied":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1,".withintervalinminutes":1,".withintervalinhours":1}
,".withintervalinseconds":{"(10)":1}
,"(10)":{".withrepeatcount":1}
,".withrepeatcount":{"(10))":1}
,"(10))":{"\u002F\u002Fnote":1}
,"\u002F\u002Fnote":{"repeats":1,"example":1}
,"give":{"total":1}
,"total":{"\u2002\u002F\u002F11":1}
,"\u2002\u002F\u002F11":{"firings":1}
,"(myjob)":{"\u002F\u002Fidentify":1}
,"handle":{"jobdetail":1}
,"jobdetail":{"itself":1}
,"itself":{".build":1,"(including":1}
,"minutes":{"future":1,"until":1}
,"future":{"trigger":1,".forjob":1}
,"trigger5":{"group1":1}
,"(futuredate":{"intervalunit.minute))":1}
,"intervalunit.minute))":{"\u002F\u002Fuse":1}
,"\u002F\u002Fuse":{"datebuilder":1}
,"\u2002\u002F\u002Fa":{"date":1}
,"(myjobkey)":{"\u002F\u002Fidentify":1}
,"jobkey":{".build":1}
,"hour":{"22:00":1,"repeat":1}
,"22:00":{"trigger":1}
,"trigger7":{"group1":1}
,".withintervalinminutes":{"(5)":1}
,"(5)":{".repeatforever":1}
,".repeatforever":{"())":1,".withmisfirehandlinginstructionnextwithexistingcount":1}
,"())":{".endat":1,"\u002F\u002Fnote":1,".build":1}
,".endat":{"(dateof":1}
,"(dateof":{"(22":1}
,"(22":{"0))":1}
,"0))":{".build":1}
,"top":{"next":1}
,"next":{"hour":1,"even-hour":1}
,"hours":{"forever":1}
,"forever":{"trigger":1}
,"trigger8":{"\u002F\u002Fbecause":1,"\u2002\u002F\u002Fwill":1}
,"\u002F\u002Fbecause":{"group":1}
,"specified":{"trigger8":1}
,"\u2002\u002F\u002Fwill":{"default":1}
,"default":{"group":1,"trigger":1}
,"(evenhourdate":{"(null))":1}
,"(null))":{"\u002F\u002Fget":1}
,"\u002F\u002Fget":{"next":1}
,"even-hour":{"(minutes":1}
,"(minutes":{"\u2002\u002F\u002Fseconds":1}
,"\u2002\u002F\u002Fseconds":{"zero":1}
,"00:00":{"\u0022))":1}
,"\u0022))":{".withschedule":1}
,".withintervalinhours":{"(2)":1}
,"(2)":{".repeatforever":1}
,"\u0027forjob":{"called":1}
,"called":{"\u002F\u002F-which":1}
,"\u002F\u002F-which":{"valid":1}
,"valid":{"trigger":1}
,"passed":{"scheduler":1}
,"along":{"job":1}
,"scheduler.schedulejob":{"(trigger":1}
,"(trigger":{"job)":1}
,"job)":{"simpletrigger":1}
,"misfire":{"instructions":1,"occurs":1,"instruction":1}
,"instructions":{"simpletrigger":1,"used":1,"defined":1,"based":1}
,"several":{"instructions":1}
,"used":{"inform":1,"simpletrigger":1}
,"inform":{"quartz":1}
,"quartz":{"misfire":1}
,"occurs":{"(for":1}
,"information":{"misfires":1}
,"misfires":{"triggers":1}
,"topic.)":{"instructions":1}
,"constants":{"simpletrigger":1,"include":1}
,"(including":{"javadoc":1}
,"javadoc":{"describes":1,"simpletrigger.updateaftermisfire":1}
,"describes":{"behavior)":1}
,"behavior)":{"constants":1}
,"misfire_instruction_ignore_misfire_policy":{"misfire_instruction_fire_now":1}
,"misfire_instruction_fire_now":{"misfire_instruction_reschedule_now_with_existing_repeat_count":1}
,"misfire_instruction_reschedule_now_with_existing_repeat_count":{"misfire_instruction_reschedule_now_with_remaining_repeat_count":1}
,"misfire_instruction_reschedule_now_with_remaining_repeat_count":{"misfire_instruction_reschedule_next_with_remaining_count":1}
,"misfire_instruction_reschedule_next_with_remaining_count":{"misfire_instruction_reschedule_next_with_existing_count":1}
,"misfire_instruction_reschedule_next_with_existing_count":{"triggers":1}
,"misfire_instruction_smart_policy":{"instruction":1}
,"instruction":{"available":1,"default":1,"used":1,"part":1}
,"types":{"\u0027smart":1}
,"\u0027smart":{"policy":1}
,"policy":{"instruction":1}
,"dynamically":{"chooses":1}
,"chooses":{"various":1}
,"misfile":{"instructions":1}
,"based":{"configuration":1}
,"configuration":{"state":1}
,"state":{"given":1}
,"instance":{"javadoc":1}
,"simpletrigger.updateaftermisfire":{"method":1}
,"method":{"explains":1}
,"explains":{"details":1}
,"details":{"dynamic":1}
,"dynamic":{"behavior":1}
,"behavior":{"building":1}
,"building":{"simpletriggers":1}
,"simpletriggers":{"specify":1}
,"part":{"simple":1}
,"schedule":{"(via":1}
,"(via":{"simpleschedulerbuilder)":1}
,"simpleschedulerbuilder)":{"trigger":1}
,".withmisfirehandlinginstructionnextwithexistingcount":{"())":1}
}
;Search.control.loadWordPairs(pairs);
