var pairs =
{
"threadpool":{"configuration":1,"implementation":1,"ships":1}
,"configuration":{"property":1,"settings":1}
,"property":{"name":1,"main":1,"shown":1}
,"name":{"required":1,"threadpool":1}
,"required":{"type":1}
,"type":{"default":1}
,"default":{"value":1,"thread.norm_priority":1,"false":1}
,"value":{"org.quartz.threadpool.class":1,"org.quartz.threadpool.makethreadsdaemons":1}
,"org.quartz.threadpool.class":{"string":1,"name":1,"=com.mycompany.goo.foothreadpool":1}
,"string":{"(class":1,"[scheduler":1}
,"(class":{"name)":1}
,"name)":{"null":1}
,"null":{"org.quartz.threadpool.threadcount":1}
,"org.quartz.threadpool.threadcount":{"int":1,"number":1}
,"int":{"org.quartz.threadpool.threadpriority":1,"thread.norm_priority":1,"thread.min_priority":1}
,"org.quartz.threadpool.threadpriority":{"int":1}
,"thread.norm_priority":{"(5)":1}
,"(5)":{"org.quartz.threadpool.class":1,"simplethreadpool-specific":1}
,"implementation":{"threadpool":1,"thread":1}
,"ships":{"quartz":1}
,"quartz":{"org.quartz.simpl.simplethreadpool":1}
,"org.quartz.simpl.simplethreadpool":{"meet":1}
,"meet":{"needs":1}
,"needs":{"nearly":1}
,"nearly":{"every":1}
,"every":{"user":1,"minute":1}
,"user":{"simple":1}
,"simple":{"behavior":1}
,"behavior":{"tested":1}
,"tested":{"provides":1}
,"provides":{"fixed-size":1}
,"fixed-size":{"pool":1}
,"pool":{"threads":1,"created":1,"postpended":1,"properties":1}
,"threads":{"\u0027live":1,"available":1,"pool":1,"default":1}
,"\u0027live":{"lifetime":1}
,"lifetime":{"scheduler":1}
,"scheduler":{"org.quartz.threadpool.threadcount":1,"configuration":1}
,"number":{"threads":1,"custom":1}
,"available":{"concurrent":1}
,"concurrent":{"execution":1}
,"execution":{"jobs":1}
,"jobs":{"specify":1,"fire":1,"firing":1,"perform":1}
,"specify":{"positive":1}
,"positive":{"integer":1}
,"integer":{"although":1}
,"although":{"numbers":1}
,"numbers":{"100":1}
,"100":{"practical":1,"(this":1}
,"practical":{"few":1}
,"few":{"jobs":1,"times":1}
,"fire":{"few":1}
,"times":{"day":1}
,"day":{"thread":1}
,"thread":{"plenty":1,"count":1,"boolean":1,"names":1,"pool":1}
,"plenty":{"tens":1}
,"tens":{"thousands":1}
,"thousands":{"jobs":1}
,"firing":{"every":1}
,"minute":{"want":1}
,"want":{"thread":1}
,"count":{"100":1}
,"(this":{"highly":1}
,"highly":{"depends":1}
,"depends":{"nature":1}
,"nature":{"work":1}
,"work":{"jobs":1}
,"perform":{"systems":1}
,"systems":{"resources)":1}
,"resources)":{"org.quartz.threadpool.threadpriority":1}
,"thread.min_priority":{"(which":1}
,"(which":{"thread.max_priority":1,"10)":1}
,"thread.max_priority":{"(which":1}
,"10)":{"default":1}
,"simplethreadpool-specific":{"properties":1}
,"properties":{"property":1,"reflectively":1}
,"org.quartz.threadpool.makethreadsdaemons":{"boolean":1,"true":1}
,"boolean":{"false":1,"true":1}
,"false":{"org.quartz.threadpool":1,"org.quartz.threadpool.threadnameprefix":1,"org.quartz.scheduler.makeschedulerthreaddaemon":1,"defaults":1}
,"org.quartz.threadpool":{"threadsinheritgroupofinitializingthread":1,"threadsinheritcontextclassloaderofinitializing":1}
,"threadsinheritgroupofinitializingthread":{"boolean":1}
,"true":{"org.quartz.threadpool":1,"threads":1,"false":1,"org.quartz.threadpool.threadsinheritcontextclassloaderofinitializingthread":1}
,"threadsinheritcontextclassloaderofinitializing":{"thread":1}
,"org.quartz.threadpool.threadnameprefix":{"string":1,"prefix":1}
,"[scheduler":{"name]_worker":1}
,"name]_worker":{"org.quartz.threadpool.makethreadsdaemons":1}
,"created":{"daemon":1}
,"daemon":{"threads":1}
,"org.quartz.scheduler.makeschedulerthreaddaemon":{"property":1}
,"main":{"scheduler":1}
,"settings":{"org.quartz.threadpool.threadsinheritgroupofinitializingthread":1}
,"org.quartz.threadpool.threadsinheritgroupofinitializingthread":{"true":1}
,"defaults":{"true":1,"false":1}
,"org.quartz.threadpool.threadsinheritcontextclassloaderofinitializingthread":{"true":1}
,"prefix":{"thread":1}
,"names":{"worker":1}
,"worker":{"pool":1}
,"postpended":{"number":1}
,"custom":{"threadpools":1}
,"threadpools":{"implementation":1}
,"reflectively":{"naming":1}
,"naming":{"property":1}
,"shown":{"org.quartz.threadpool.class":1}
,"=com.mycompany.goo.foothreadpool":{"org.quartz.threadpool.somepropoffoothreadpool":1}
,"org.quartz.threadpool.somepropoffoothreadpool":{"=somevalue":1}
}
;Search.control.loadWordPairs(pairs);
