var pairs =
{
"jobs":{"jobdetails":1,"easy":1,"execute":1,"no-argument":1,"trigger":1,"here\u0027s":1,"life":1}
,"jobdetails":{"jobs":1,"job":1,"-each":1}
,"easy":{"implement":1}
,"implement":{"having":1,"code":1}
,"having":{"just":1,"hand-code":1,"application\u0027s":1}
,"just":{"single":1,"few":1}
,"single":{"\u0027execute":1,"job":1}
,"\u0027execute":{"method":1}
,"method":{"interface":1,"job":1,"execution":1,"data":1,"triggers":1,"cleaner":1,"completes":1,"return":1,"type":1,"jobexecutionexception":1,"\u0027try-catch":1}
,"interface":{"just":1,"jobdetails":1,"added":1,"called":1}
,"few":{"things":1,"details":1}
,"things":{"need":1,"having":1}
,"need":{"understand":1,"explicitly":1,"inform":1}
,"understand":{"nature":1}
,"nature":{"jobs":1}
,"execute":{"method":1,"(jobexecutioncontext":1,"multiple":1,"given":1,"concurrently":1,"method)":1}
,"job":{"interface":1,"class":1,"quartz":1,"done":1,"schedules":1,"tie":1,"=newjob":1,"run":1,"using":1,"{public":1,"executed":1,"creates":1,"executions":1,"instance":1,"scheduler":1,"instantiated":1,"stored":1,"different":1,"execution":1,"{string":1,"instances":1,"coded":1,"salesreportforjoe":1,"definition":1,"job":1,"used":1,"state":1,"class)":1,"(jobdetail)":1,"non-durable":1,"requests":1,"provide":1}
,"class":{"implement":1,"mentioned":1,"typically":1,"jobdetail":1,"hellojob":1,"build":1,"calling":1,"instance":1,"-as":1,"dumbjob":1,"serialized":1,"correspond":1,"look":1,"longer":1,"store":1,"implements":1,"refers":1,"attempts":1,"match":1,"implementing":1,"job":1,"affect":1,"tells":1,"however":1,"itself":1,"coded":1,"carry":1}
,"code":{"knows":1,"import":1,"snippet":1,"class":1,"execute":1,"longer":1,"within":1}
,"knows":{"actual":1,"type":1}
,"actual":{"work":1}
,"work":{"particular":1}
,"particular":{"type":1}
,"type":{"job":1,"exception":1}
,"quartz":{"needs":1,"schedule":1,"execute":1,"update":1}
,"needs":{"informed":1}
,"informed":{"various":1}
,"various":{"attributes":1,"directives":1}
,"attributes":{"may":1,"jobs":1}
,"may":{"wish":1,"create":1,"want":1}
,"wish":{"instance":1,"made":1,"rely":1}
,"instance":{"job":1,"knows":1,"class":1,"dropped":1,"garbage":1,"keep":1,"executes":1,"key":1,"stored":1,"executing":1,"instance":1,"salesreportforjoe":1,"salesreportformike":1,"definition":1,"decided":1,"via":1}
,"done":{"via":1}
,"via":{"jobdetail":1,"jobfactory":1}
,"jobdetail":{"class":1,"instances":1,"job":1,"instance":1,"(and":1,"object":1,"prior":1,"found":1,"(instance":1,"referred":1}
,"mentioned":{"briefly":1}
,"briefly":{"previous":1}
,"previous":{"section":1,"example":1}
,"section":{"jobdetail":1,"tutorial)":1,"salesreportjob":1}
,"instances":{"built":1,"care":1,"create":1,"jobdetails":1,"given":1,"job":1}
,"built":{"using":1}
,"using":{"jobbuilder":1,"trigger":1,"default":1,"@disallowconcurrentexecution":1}
,"jobbuilder":{"class":1}
,"typically":{"want":1}
,"want":{"static":1,"supply":1,"create":1,"exception":1}
,"static":{"import":1,"org.quartz.jobbuilder.*":1}
,"import":{"methods":1,"static":1}
,"methods":{"order":1,"storing":1,"job":1,"rather":1,"class":1}
,"order":{"dsl-feel":1,"avoid":1}
,"dsl-feel":{"within":1}
,"within":{"code":1,"execute":1,"scheduler":1,"jobdatamap":1,"crashes":1}
,"org.quartz.jobbuilder.*":{"following":1}
,"following":{"code":1,"additional":1}
,"snippet":{"defines":1}
,"defines":{"job":1}
,"schedules":{"execution":1}
,"execution":{"\u002F\u002Fdefine":1,"complete":1,"public":1,"serves":1,"job":1}
,"\u002F\u002Fdefine":{"job":1}
,"tie":{"hellojob":1,"dumbjob":1}
,"hellojob":{"class":1,"shown":1,"implements":1,"public":1,"executing":1}
,"=newjob":{"(hellojob.class)":1,"(dumbjob.class)":1}
,"(hellojob.class)":{".withidentity":1}
,".withidentity":{"myjob":1,"mytrigger":1}
,"myjob":{"group1":1,"group":1}
,"group1":{"\u002F\u002Fname":1,".build":1,".startnow":1,".usingjobdata":1}
,"\u002F\u002Fname":{"myjob":1}
,"group":{"group1":1}
,".build":{"\u002F\u002Ftrigger":1,"\u002F\u002Ftell":1,"example":1}
,"\u002F\u002Ftrigger":{"job":1}
,"run":{"every":1}
,"every":{"seconds":1}
,"seconds":{"trigger":1}
,"trigger":{"trigger":1,"=newtrigger":1,"sched.schedulejob":1,"values":1,"fires":1}
,"=newtrigger":{".withidentity":1}
,"mytrigger":{"group1":1}
,".startnow":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(40)":1}
,"(40)":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1,"system.err.println":1}
,"\u002F\u002Ftell":{"quartz":1}
,"schedule":{"job":1}
,"sched.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"trigger)":{"consider":1}
,"consider":{"job":1,"using":1}
,"shown":{"below":1}
,"below":{"public":1}
,"public":{"class":1,"void":1,"dumbjob":1}
,"implements":{"job":1}
,"{public":{"hellojob":1,"dumbjob":1}
,"void":{"execute":1,"setjobsays":1,"setmyfloatvalue":1,"setstate":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"{system.err.println":1,"{jobkey":1,"finally":1,"generally":1,"job":1}
,"{system.err.println":{"hello":1}
,"hello":{"hellojob":1,"world":1}
,"executing":{"notice":1,"job":1,"during":1}
,"notice":{"give":1,"overall":1}
,"give":{"scheduler":1}
,"scheduler":{"jobdetail":1,"executes":1,"\u002F\u002Fdefine":1,"regular\u002Frepeated":1,"creating":1,"example":1,"default":1,"once":1,"(i.e":1,"started":1,"various":1}
,"executed":{"simply":1,"concurrently":1}
,"simply":{"providing":1,"calls":1}
,"providing":{"job\u0027s":1}
,"job\u0027s":{"class":1,"state":1,"execution":1}
,"build":{"jobdetail":1}
,"(and":{"every)":1}
,"every)":{"time":1}
,"time":{"scheduler":1,"someone":1,"execute":1,"hard":1,"looking":1}
,"executes":{"job":1,"jobdatamap":1}
,"creates":{"new":1}
,"new":{"instance":1}
,"calling":{"execute":1}
,"complete":{"references":1}
,"references":{"job":1}
,"dropped":{"instance":1}
,"garbage":{"collected":1}
,"collected":{"ramifications":1}
,"ramifications":{"behavior":1}
,"behavior":{"fact":1,"respect":1}
,"fact":{"jobs":1}
,"no-argument":{"constructor":1}
,"constructor":{"(when":1}
,"(when":{"using":1}
,"default":{"jobfactory":1}
,"jobfactory":{"implementation)":1,"implementation":1,"injecting":1,"configured":1,"simply":1,"accomplish":1}
,"implementation)":{"ramification":1}
,"ramification":{"sense":1}
,"sense":{"state":1}
,"state":{"data-fields":1,"executions":1,"=(arraylist)":1,"public":1,"concurrency":1,"data":1}
,"data-fields":{"defined":1}
,"defined":{"job":1}
,"-as":{"values":1}
,"values":{"preserved":1,"map":1,"latter":1,"former":1,"onto":1,"jobdatamap":1,"rather":1,"@disallowconcurrentexecution":1}
,"preserved":{"job":1}
,"executions":{"provide":1,"jobdatamap":1}
,"provide":{"properties\u002Fconfiguration":1,"scheduler":1}
,"properties\u002Fconfiguration":{"job":1}
,"keep":{"track":1}
,"track":{"job\u0027s":1}
,"jobdatamap":{"part":1,"jobdatamap":1,"used":1,"implementation":1,"defining\u002Fbuilding":1,"during":1,"datamap":1,"object":1,"mode":1,"(such":1,"found":1,"choice":1,"-and":1,"may":1,"execute":1}
,"part":{"jobdetail":1}
,"object":{"jobdatamap":1,"serialized":1,"durability":1}
,"used":{"hold":1,"auto-generate":1,"refers":1}
,"hold":{"amount":1}
,"amount":{"(serializable)":1}
,"(serializable)":{"data":1}
,"data":{"objects":1,"primitive":1,"jobdatamap":1,"example":1,"inputs":1,"jobexecutioncontext\u2019s":1,"map":1,"(aka":1,"left":1}
,"objects":{"wish":1}
,"made":{"available":1}
,"available":{"job":1}
,"implementation":{"java":1,"automatically":1,"jobfactory":1}
,"java":{"map":1,"types":1}
,"map":{"interface":1,"thus":1,"within":1,"values":1}
,"added":{"convenience":1,"job":1}
,"convenience":{"methods":1,"merge":1}
,"storing":{"retrieving":1}
,"retrieving":{"data":1}
,"primitive":{"types":1}
,"types":{"here\u0027s":1,"safe":1}
,"here\u0027s":{"snippets":1,"quick":1}
,"snippets":{"putting":1}
,"putting":{"data":1}
,"defining\u002Fbuilding":{"jobdetail":1}
,"prior":{"adding":1}
,"adding":{"job":1,"scheduler":1}
,"dumbjob":{"class":1,"implements":1,"public":1,"says":1}
,"(dumbjob.class)":{".withidentity":1}
,".usingjobdata":{"jobsays":1,"myfloatvalue":1}
,"jobsays":{"hello":1,"=datamap.getstring":1,"float":1,"val":1}
,"world":{".usingjobdata":1}
,"myfloatvalue":{"3.141f)":1,"=datamap.getfloat":1,"system.err.println":1,"arraylist":1}
,"3.141f)":{".build":1}
,"example":{"getting":1,"above)":1,"string":1,"state.add":1,"create":1,"previous":1}
,"getting":{"data":1}
,"during":{"job\u0027s":1,"job":1,"time":1}
,"{jobkey":{"key":1}
,"key":{"=context.getjobdetail":1,"dumbjob":1}
,"=context.getjobdetail":{".getkey":1,".getjobdatamap":1}
,".getkey":{"jobdatamap":1}
,"datamap":{"=context.getjobdetail":1,"=context.getmergedjobdatamap":1}
,".getjobdatamap":{"string":1}
,"string":{"jobsays":1}
,"=datamap.getstring":{"jobsays":1}
,"float":{"myfloatvalue":1}
,"=datamap.getfloat":{"myfloatvalue":1}
,"system.err.println":{"instance":1}
,"says":{"jobsays":1}
,"val":{"myfloatvalue)":1}
,"myfloatvalue)":{"persistent":1,"wish":1,"public":1,"{myfloatvalue":1}
,"persistent":{"jobstore":1}
,"jobstore":{"(discussed":1,"section":1}
,"(discussed":{"jobstore":1}
,"tutorial)":{"care":1}
,"care":{"deciding":1,"taken":1}
,"deciding":{"place":1}
,"place":{"jobdatamap":1}
,"serialized":{"therefore":1,"instances":1}
,"therefore":{"become":1}
,"become":{"prone":1}
,"prone":{"class-versioning":1}
,"class-versioning":{"problems":1}
,"problems":{"obviously":1,"add":1}
,"obviously":{"standard":1}
,"standard":{"java":1}
,"safe":{"beyond":1}
,"beyond":{"time":1}
,"someone":{"changes":1}
,"changes":{"definition":1}
,"definition":{"class":1,"jobdetail":1,"general":1,"(that":1,"(jobdetail)":1,"instance":1}
,"taken":{"break":1}
,"break":{"compatibility":1}
,"compatibility":{"optionally":1}
,"optionally":{"put":1}
,"put":{"jdbc-jobstore":1}
,"jdbc-jobstore":{"jobdatamap":1}
,"mode":{"primitives":1}
,"primitives":{"strings":1}
,"strings":{"allowed":1}
,"allowed":{"stored":1,"throw":1}
,"stored":{"map":1,"scheduler":1,"jobdetail":1,"copy":1,"values":1,"two":1}
,"thus":{"eliminating":1,"preventing":1}
,"eliminating":{"possibility":1}
,"possibility":{"later":1}
,"later":{"serialization":1}
,"serialization":{"problems":1}
,"add":{"setter":1,"job":1}
,"setter":{"methods":1}
,"correspond":{"names":1}
,"names":{"keys":1}
,"keys":{"jobdatamap":1,"within":1}
,"(such":{"setjobsays":1}
,"setjobsays":{"(string":1}
,"(string":{"val)":1,"jobsays)":1}
,"val)":{"method":1}
,"above)":{"quartz\u0027s":1}
,"quartz\u0027s":{"default":1,"behavior":1}
,"automatically":{"call":1,"deleted":1}
,"call":{"setters":1,"setter":1}
,"setters":{"job":1}
,"instantiated":{"thus":1,"via":1}
,"preventing":{"need":1}
,"explicitly":{"values":1,"understood":1}
,"triggers":{"jobdatamaps":1,"independent":1,"associated":1,"requestsrecovery":1}
,"jobdatamaps":{"associated":1,"input":1}
,"associated":{"useful":1,"loaded":1,"words":1}
,"useful":{"case":1}
,"case":{"job":1,"jobexecutioncontext.isrecovering":1}
,"regular\u002Frepeated":{"multiple":1}
,"multiple":{"triggers":1,"instances":1,"definitions":1}
,"independent":{"triggering":1}
,"triggering":{"want":1}
,"supply":{"job":1}
,"different":{"data":1}
,"inputs":{"jobdatamap":1}
,"found":{"jobexecutioncontext":1,"jobdetail":1,"trigger":1}
,"jobexecutioncontext":{"during":1}
,"serves":{"convenience":1}
,"merge":{"jobdatamap":1}
,"latter":{"overriding":1}
,"overriding":{"same-named":1}
,"same-named":{"values":1}
,"former":{"here\u0027s":1}
,"quick":{"example":1,"summary":1}
,"jobexecutioncontext\u2019s":{"merged":1}
,"merged":{"jobdatamap":1}
,"=context.getmergedjobdatamap":{"\u2002\u002F\u002Fnote":1}
,"\u2002\u002F\u002Fnote":{"difference":1}
,"difference":{"previous":1,"class":1}
,"arraylist":{"state":1}
,"=(arraylist)":{"datamap.get":1}
,"datamap.get":{"mystatedata":1}
,"mystatedata":{"state.add":1}
,"state.add":{"(new":1}
,"(new":{"date":1}
,"date":{"())":1}
,"rely":{"jobfactory":1}
,"injecting":{"data":1}
,"onto":{"class":1}
,"look":{"instead":1}
,"instead":{"public":1}
,"{string":{"jobsays":1}
,"jobsays)":{"{this.jobsays":1}
,"{this.jobsays":{"=jobsays":1}
,"=jobsays":{"public":1}
,"setmyfloatvalue":{"(float":1}
,"(float":{"myfloatvalue)":1}
,"{myfloatvalue":{"=myfloatvalue":1}
,"=myfloatvalue":{"public":1}
,"setstate":{"(arraylist":1}
,"(arraylist":{"state)":1}
,"state)":{"{state":1}
,"{state":{"=state":1}
,"=state":{"you\u0027ll":1}
,"you\u0027ll":{"notice":1}
,"overall":{"code":1}
,"longer":{"code":1,"actually":1,"active":1}
,"cleaner":{"argue":1}
,"argue":{"although":1}
,"although":{"code":1}
,"actually":{"took":1}
,"took":{"less":1}
,"less":{"coding":1}
,"coding":{"programmer\u0027s":1}
,"programmer\u0027s":{"ide":1}
,"ide":{"used":1}
,"auto-generate":{"setter":1}
,"rather":{"having":1,"originally":1}
,"hand-code":{"individual":1}
,"individual":{"calls":1}
,"calls":{"retrieve":1,"newinstance":1}
,"retrieve":{"values":1}
,"choice":{"yours":1}
,"yours":{"job":1}
,"create":{"single":1,"class":1,"multiple":1,"implementation":1}
,"store":{"\u0027instance":1}
,"\u0027instance":{"definitions":1}
,"definitions":{"within":1,"(jobdetails)":1}
,"creating":{"multiple":1}
,"-each":{"properties":1}
,"properties":{"jobdatamap":1,"define":1}
,"-and":{"adding":1}
,"called":{"salesreportjob":1,"job":1}
,"salesreportjob":{"job":1,"annotation":1}
,"coded":{"expect":1,"@persistjobdataafterexecution":1,"(e.g":1}
,"expect":{"parameters":1}
,"parameters":{"sent":1}
,"sent":{"(via":1}
,"(via":{"jobdatamap)":1}
,"jobdatamap)":{"specify":1,"concurrency":1}
,"specify":{"name":1}
,"name":{"sales":1}
,"sales":{"person":1,"report":1}
,"person":{"sales":1}
,"report":{"based":1}
,"based":{"may":1,"upon":1}
,"(jobdetails)":{"job":1}
,"salesreportforjoe":{"salesreportformike":1,"execute":1}
,"salesreportformike":{"joe":1,"constraint":1}
,"joe":{"mike":1}
,"mike":{"specified":1}
,"specified":{"corresponding":1}
,"corresponding":{"jobdatamaps":1}
,"input":{"respective":1}
,"respective":{"jobs":1}
,"fires":{"jobdetail":1}
,"(instance":{"definition)":1}
,"definition)":{"associated":1}
,"loaded":{"job":1}
,"refers":{"instantiated":1,"named":1,"given":1}
,"configured":{"scheduler":1}
,"newinstance":{"job":1}
,"attempts":{"call":1}
,"match":{"names":1}
,"accomplish":{"things":1}
,"application\u0027s":{"ioc":1}
,"ioc":{"container":1}
,"container":{"produce\u002Finitialize":1}
,"produce\u002Finitialize":{"job":1}
,"referred":{"job":1}
,"general":{"term":1}
,"term":{"job":1}
,"named":{"definition":1}
,"implementing":{"job":1}
,"concurrency":{"following":1,"couple":1}
,"additional":{"notes":1}
,"notes":{"job\u0027s":1}
,"(aka":{"jobdatamap)":1}
,"couple":{"annotations":1}
,"annotations":{"add":1}
,"affect":{"quartz\u0027s":1}
,"respect":{"aspects":1}
,"aspects":{"@disallowconcurrentexecution":1}
,"@disallowconcurrentexecution":{"annotation":1}
,"annotation":{"added":1,"instance":1,"carried":1,"applies":1,"strongly":1,"order":1}
,"tells":{"quartz":1}
,"given":{"job":1,"time":1}
,"(that":{"refers":1}
,"class)":{"concurrently":1}
,"concurrently":{"example":1,"instance":1,"attributes":1}
,"constraint":{"based":1}
,"upon":{"instance":1}
,"(jobdetail)":{"instances":1,"receives":1,"executed":1}
,"however":{"decided":1}
,"decided":{"(during":1,"job":1}
,"(during":{"design":1}
,"design":{"quartz)":1}
,"quartz)":{"annotation":1}
,"carried":{"class":1}
,"itself":{"often":1}
,"often":{"difference":1}
,"@persistjobdataafterexecution":{"annotation":1}
,"update":{"stored":1}
,"copy":{"jobdetail\u2019s":1}
,"jobdetail\u2019s":{"jobdatamap":1}
,"completes":{"successfully":1}
,"successfully":{"(without":1}
,"(without":{"throwing":1}
,"throwing":{"exception)":1}
,"exception)":{"next":1}
,"next":{"execution":1}
,"receives":{"updated":1}
,"updated":{"values":1}
,"originally":{"stored":1}
,"applies":{"job":1}
,"carry":{"attribute":1}
,"attribute":{"often":1}
,"(e.g":{"statefulness":1}
,"statefulness":{"need":1}
,"understood":{"code":1}
,"method)":{"@persistjobdataafterexecution":1}
,"strongly":{"consider":1}
,"avoid":{"possible":1}
,"possible":{"confusion":1}
,"confusion":{"(race":1}
,"(race":{"conditions)":1}
,"conditions)":{"data":1}
,"left":{"stored":1}
,"two":{"instances":1}
,"summary":{"properties":1}
,"define":{"job":1}
,"durability":{"-if":1}
,"-if":{"job":1}
,"non-durable":{"automatically":1,"jobs":1}
,"deleted":{"scheduler":1}
,"once":{"longer":1}
,"active":{"triggers":1}
,"words":{"non-durable":1}
,"life":{"span":1}
,"span":{"bounded":1}
,"bounded":{"existence":1}
,"existence":{"triggers":1}
,"requestsrecovery":{"-if":1}
,"requests":{"recovery":1}
,"recovery":{"executing":1}
,"hard":{"shutdown":1}
,"shutdown":{"scheduler":1}
,"(i.e":{"process":1}
,"process":{"running":1}
,"running":{"within":1}
,"crashes":{"machine":1}
,"machine":{"shut":1}
,"shut":{"off)":1}
,"off)":{"re-executed":1}
,"re-executed":{"scheduler":1}
,"started":{"again":1}
,"again":{"case":1}
,"jobexecutioncontext.isrecovering":{"method":1}
,"return":{"true":1}
,"true":{"jobexecutionexception":1}
,"finally":{"need":1}
,"inform":{"few":1}
,"details":{"job.execute":1}
,"job.execute":{"method":1}
,"exception":{"(including":1,"handled":1}
,"(including":{"runtimeexceptions)":1}
,"runtimeexceptions)":{"allowed":1}
,"throw":{"execute":1}
,"generally":{"wrap":1}
,"wrap":{"entire":1}
,"entire":{"contents":1}
,"contents":{"execute":1}
,"\u0027try-catch":{"block":1}
,"block":{"spend":1}
,"spend":{"time":1}
,"looking":{"documentation":1}
,"documentation":{"jobexecutionexception":1}
,"directives":{"want":1}
}
;Search.control.loadWordPairs(pairs);
