var pairs =
{
"main":{"scheduler":1,"thread":1,"scheduling":1}
,"scheduler":{"configuration":1,"top":1,"itself":1,"org.quartz.scheduler.instanceid":1,"within":1,"daemon":1,"wait":1,"otherwise":1,"context":1,"node":1,"large":1}
,"configuration":{"settings":1,"thread":1}
,"settings":{"properties":1,"property":1}
,"properties":{"configure":1,"using":1,"left":1}
,"configure":{"identification":1}
,"identification":{"scheduler":1}
,"top":{"level":1}
,"level":{"settings":1}
,"property":{"name":1,"org.quartz.scheduler.instanceid":1,"org.quartz.scheduler.instanceid)":1,"specified":1,"tuning":1,"however":1,"jta\u002Fusertransaction":1,"causes":1,"org.terracotta.quartz.skipupdatecheck=true":1,"jdbc":1,"org.quartz.jobstore.acquiretriggerswithinlock":1,"useful":1}
,"name":{"req\u0027d":1,"every":1,"time":1,"(inetaddress.getlocalhost":1,"java":1,"(org.quartz.scheduler.instancename)":1,"jobfactory":1}
,"req\u0027d":{"type":1}
,"type":{"default":1}
,"default":{"value":1,"org.quartz.simpl.propertysettingjobfactory":1}
,"value":{"org.quartz.scheduler.instancename":1,"meaning":1,"auto":1,"sys_prop":1,"system":1,"(true":1,"true":1,"(if":1,"false":1,"larger":1,"property":1}
,"org.quartz.scheduler.instancename":{"string":1}
,"string":{"\u0027quartzscheduler":1,"\u0027non_clustered":1,"(class":1,"instancename":1,"none":1,"(url)":1,"value":1,"unique":1,"valid":1,"\u0022_quartzschedulerthread":1}
,"\u0027quartzscheduler":{"org.quartz.scheduler.instanceid":1}
,"org.quartz.scheduler.instanceid":{"string":1,"org.quartz.scheduler.instanceidgenerator.class":1,"auto":1}
,"\u0027non_clustered":{"org.quartz.scheduler.instanceidgenerator.class":1}
,"org.quartz.scheduler.instanceidgenerator.class":{"string":1,"used":1}
,"(class":{"name)":1}
,"name)":{"org.quartz.simpl":1}
,"org.quartz.simpl":{"simpleinstanceid":1,"cascadingclass":1,"propertysetting":1,"package":1}
,"simpleinstanceid":{"generator":1}
,"generator":{"org.quartz.scheduler.threadname":1}
,"org.quartz.scheduler.threadname":{"string":1}
,"instancename":{"\u0027_quartzscheduler":1}
,"\u0027_quartzscheduler":{"thread":1}
,"thread":{"org.quartz.scheduler":1,"property":1,"receive":1,"scheduler":1,"org.quartz.threadpool.makethreadsdaemons":1,"pool":1,"(i.e":1,"initializes":1,"jdbcjobstore\u2019s":1,"(if":1}
,"org.quartz.scheduler":{"makeschedulerthreaddaemon":1,"threadsinheritcontextclassloaderofinitializer":1,"wrapjobexecutioninusertransaction":1,"batchtriggeracquisitionmaxcount":1,"batchtriggeracquisitionfireaheadtimewindow":1}
,"makeschedulerthreaddaemon":{"boolean":1}
,"boolean":{"false":1,"value":1}
,"false":{"org.quartz.scheduler":1,"org.quartz.scheduler.idlewaittime":1,"org.quartz.scheduler.skipupdatecheck":1,"may":1}
,"threadsinheritcontextclassloaderofinitializer":{"boolean":1}
,"org.quartz.scheduler.idlewaittime":{"long":1,"amount":1}
,"long":{"30000":1,"15000":1,"org.quartz.scheduler.instancename":1}
,"30000":{"org.quartz.scheduler.dbfailureretryinterval":1}
,"org.quartz.scheduler.dbfailureretryinterval":{"long":1,"amount":1}
,"15000":{"org.quartz.scheduler.classloadhelper.class":1}
,"org.quartz.scheduler.classloadhelper.class":{"string":1,"defaults":1}
,"cascadingclass":{"loadhelper":1}
,"loadhelper":{"org.quartz.scheduler.jobfactory.class":1}
,"org.quartz.scheduler.jobfactory.class":{"string":1,"class":1}
,"propertysetting":{"jobfactory":1}
,"jobfactory":{"org.quartz.context.key.some_key":1,"jobfatcory":1}
,"org.quartz.context.key.some_key":{"string":1,"name-value":1}
,"none":{"org.quartz.scheduler.usertransactionurl":1}
,"org.quartz.scheduler.usertransactionurl":{"string":1,"jndi":1}
,"(url)":{"\u0027java:comp\u002Fuser":1}
,"\u0027java:comp\u002Fuser":{"transaction":1}
,"transaction":{"org.quartz.scheduler":1,"wrapjobexecutioninusertransaction":1}
,"wrapjobexecutioninusertransaction":{"boolean":1,"property":1}
,"org.quartz.scheduler.skipupdatecheck":{"boolean":1,"whether":1}
,"batchtriggeracquisitionmaxcount":{"int":1}
,"int":{"org.quartz.scheduler":1}
,"batchtriggeracquisitionfireaheadtimewindow":{"long":1}
,"meaning":{"scheduler":1}
,"itself":{"-but":1}
,"-but":{"rather":1}
,"rather":{"serves":1}
,"serves":{"mechanism":1}
,"mechanism":{"client":1}
,"client":{"code":1}
,"code":{"distinguish":1}
,"distinguish":{"schedulers":1}
,"schedulers":{"multiple":1,"working":1}
,"multiple":{"instances":1}
,"instances":{"used":1,"jobclasses":1}
,"used":{"within":1,"org.quartz.scheduler.instanceid":1,"quartz":1,"property":1}
,"within":{"program":1,"cluster":1,"application":1,"jobstore":1}
,"program":{"using":1}
,"using":{"clustering":1,"(which":1,"quartz":1,"transactions":1,"ramjobstore":1,"contents":1,"jta":1,"@executeinjtatransaction":1}
,"clustering":{"features":1,"used)":1}
,"features":{"name":1}
,"every":{"instance":1,"classloadhelper":1}
,"instance":{"cluster":1,"based":1,"system":1,"time":1}
,"cluster":{"\u0027logically":1,"may":1,"recovery":1,"nodes":1}
,"\u0027logically":{"scheduler":1}
,"unique":{"schedulers":1}
,"working":{"\u0027logical":1}
,"\u0027logical":{"scheduler":1}
,"may":{"value":1,"help":1,"need":1,"interested":1}
,"auto":{"instanceid":1,"defaults":1}
,"instanceid":{"wish":1}
,"wish":{"generated":1}
,"generated":{"value":1}
,"sys_prop":{"want":1}
,"want":{"value":1,"quartz":1}
,"system":{"property":1,"environment":1}
,"defaults":{"org.quartz.simpl.simpleinstanceidgenerator":1,"robust":1,"larger":1}
,"org.quartz.simpl.simpleinstanceidgenerator":{"generates":1}
,"generates":{"instance":1}
,"based":{"upon":1}
,"upon":{"host":1}
,"host":{"name":1}
,"time":{"stamp":1,"milliseconds":1,"execution":1,"(in":1,"defaults":1,"however":1}
,"stamp":{"intanceidgenerator":1}
,"intanceidgenerator":{"implementations":1}
,"implementations":{"include":1,"found":1}
,"include":{"systempropertyinstanceidgenerator":1}
,"systempropertyinstanceidgenerator":{"(which":1}
,"(which":{"gets":1,"usually":1,"system":1}
,"gets":{"instance":1}
,"org.quartz.scheduler.instanceid)":{"hostnameinstanceidgenerator":1}
,"hostnameinstanceidgenerator":{"uses":1}
,"uses":{"local":1,"every":1}
,"local":{"host":1}
,"(inetaddress.getlocalhost":{".gethostname":1}
,".gethostname":{"())":1}
,"())":{"implement":1,"<<ffc-is":1}
,"implement":{"instanceidgenerator":1}
,"instanceidgenerator":{"interface":1}
,"interface":{"self":1}
,"self":{"org.quartz.scheduler.threadname":1}
,"valid":{"name":1,"org.quartz.scheduler.dbfailureretryinterval":1}
,"java":{"thread":1,"command":1}
,"specified":{"thread":1}
,"receive":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"name":1}
,"(org.quartz.scheduler.instancename)":{"plus":1}
,"plus":{"appended":1}
,"appended":{"string":1}
,"\u0022_quartzschedulerthread":{"org.quartz.scheduler.makeschedulerthreaddaemon":1}
,"org.quartz.scheduler.makeschedulerthreaddaemon":{"boolean":1}
,"(true":{"false)":1}
,"false)":{"specifies":1}
,"specifies":{"whether":1}
,"whether":{"main":1,"threads":1,"quartz":1,"skip":1}
,"daemon":{"thread":1}
,"org.quartz.threadpool.makethreadsdaemons":{"property":1}
,"tuning":{"simplethreadpool":1}
,"simplethreadpool":{"threadpool":1,"(if":1,"used)":1}
,"threadpool":{"configuration":1}
,"pool":{"implementation":1}
,"implementation":{"using":1}
,"usually":{"case)":1}
,"case)":{"org.quartz.scheduler.threadsinheritcontextclassloaderofinitializer":1}
,"org.quartz.scheduler.threadsinheritcontextclassloaderofinitializer":{"boolean":1}
,"threads":{"spawned":1,"simplethreadpool":1}
,"spawned":{"quartz":1}
,"quartz":{"inherit":1,"instance)":1,"main":1,"within":1,"locate":1,"configured":1,"start":1,"available":1,"logs":1}
,"inherit":{"context":1}
,"context":{"classloader":1,"strings":1}
,"classloader":{"initializing":1}
,"initializing":{"thread":1}
,"(i.e":{"thread":1,"database)":1}
,"initializes":{"quartz":1}
,"instance)":{"affect":1}
,"affect":{"quartz":1}
,"scheduling":{"thread":1}
,"jdbcjobstore\u2019s":{"misfire":1}
,"misfire":{"handling":1}
,"handling":{"thread":1}
,"(if":{"jdbcjobstore":1,"clustering":1,"simplethreadpool":1,"specified)":1,"statefuljob)":1}
,"jdbcjobstore":{"used)":1}
,"used)":{"cluster":1,"threads":1,"setting":1}
,"recovery":{"thread":1}
,"setting":{"value":1,"org.quartz.context.key.mykey":1}
,"true":{"may":1,"org.quartz.scheduler.wrapjobexecutioninusertransaction":1,"want":1,"avoid":1}
,"help":{"class":1}
,"class":{"loading":1,"turn":1,"until":1,"property":1,"name":1,"produce":1,"lets":1}
,"loading":{"jndi":1}
,"jndi":{"look-ups":1,"url":1}
,"look-ups":{"issues":1}
,"issues":{"related":1,"application":1}
,"related":{"using":1}
,"application":{"server":1,"servers":1,"server\u2019s":1}
,"server":{"org.quartz.scheduler.idlewaittime":1}
,"amount":{"time":1}
,"milliseconds":{"scheduler":1}
,"wait":{"re-queries":1,"re-tries":1}
,"re-queries":{"available":1}
,"available":{"triggers":1,"download":1,"quartz":1}
,"triggers":{"scheduler":1,"fire":1,"needing":1,"need":1}
,"otherwise":{"idle":1}
,"idle":{"normally":1}
,"normally":{"adjust":1}
,"adjust":{"parameter":1}
,"parameter":{"unless":1,"meaningful":1}
,"unless":{"you\u0027re":1,"using":1}
,"you\u0027re":{"using":1}
,"transactions":{"having":1,"org.quartz.scheduler.usertransactionurl":1}
,"having":{"problems":1}
,"problems":{"delayed":1}
,"delayed":{"firings":1}
,"firings":{"triggers":1}
,"fire":{"immediately":1,"time":1,"able":1,"trigger":1,"early)":1}
,"immediately":{"values":1}
,"values":{"less":1}
,"less":{"5000":1,"1000":1}
,"5000":{"recommended":1}
,"recommended":{"cause":1,"disable":1}
,"cause":{"excessive":1}
,"excessive":{"database":1}
,"database":{"querying":1}
,"querying":{"values":1}
,"1000":{"valid":1}
,"re-tries":{"detects":1}
,"detects":{"loss":1}
,"loss":{"connectivity":1}
,"connectivity":{"within":1}
,"jobstore":{"(i.e":1,"used":1}
,"database)":{"parameter":1}
,"meaningful":{"using":1}
,"ramjobstore":{"org.quartz.scheduler.classloadhelper.class":1}
,"robust":{"approach":1}
,"approach":{"org.quartz.simpl.cascadingclassloadhelper":1}
,"org.quartz.simpl.cascadingclassloadhelper":{"class":1}
,"turn":{"uses":1}
,"classloadhelper":{"class":1,"implementations":1}
,"until":{"works":1}
,"works":{"general":1,"almost":1}
,"general":{"need":1}
,"need":{"class":1,"property":1,"fired":1}
,"however":{"useful":1,"comes":1}
,"useful":{"resolving":1,"(for":1}
,"resolving":{"class-loading":1}
,"class-loading":{"issues":1}
,"servers":{"current":1,"websphere":1}
,"current":{"possible":1}
,"possible":{"classloadhelper":1,"imbalanced":1}
,"found":{"org.quartz.simpl":1,"reported":1}
,"package":{"org.quartz.scheduler.jobfactory.class":1}
,"jobfatcory":{"responsible":1}
,"responsible":{"producing":1}
,"producing":{"instances":1}
,"jobclasses":{"default":1}
,"org.quartz.simpl.propertysettingjobfactory":{"simply":1}
,"simply":{"calls":1}
,"calls":{"newinstance":1}
,"newinstance":{"class":1}
,"produce":{"new":1}
,"new":{"instance":1}
,"execution":{"occur":1}
,"occur":{"propertysettingjobfactory":1,"jobs":1}
,"propertysettingjobfactory":{"reflectively":1}
,"reflectively":{"sets":1}
,"sets":{"job\u0027s":1}
,"job\u0027s":{"bean":1,"execute":1}
,"bean":{"properties":1}
,"contents":{"schedulercontext":1}
,"schedulercontext":{"job":1}
,"job":{"trigger":1,"commit":1,"class":1,"whether":1}
,"trigger":{"jobdatamaps":1,"allowed":1,"time":1,"schedule":1}
,"jobdatamaps":{"org.quartz.context.key.some_key":1}
,"name-value":{"pair":1}
,"pair":{"placed":1}
,"placed":{"scheduler":1}
,"strings":{"(see":1}
,"(see":{"scheduler.getcontext":1}
,"scheduler.getcontext":{"())":1,".put":1}
,"<<ffc-is":{"reference":1}
,"reference":{"javadoc":1}
,"javadoc":{"say":1}
,"say":{"provide":1}
,"provide":{"direct":1}
,"direct":{"link":1}
,"link":{"today":1}
,"today":{"leave":1}
,"leave":{"address":1}
,"address":{"future":1}
,"future":{"release.>>":1}
,"release.>>":{"example":1}
,"example":{"setting":1}
,"org.quartz.context.key.mykey":{"myvalue":1}
,"myvalue":{"perform":1,"transaction-related":1}
,"perform":{"equivalent":1}
,"equivalent":{"scheduler.getcontext":1}
,".put":{"mykey":1}
,"mykey":{"myvalue":1}
,"transaction-related":{"properties":1}
,"left":{"config":1}
,"config":{"file":1}
,"file":{"unless":1}
,"jta":{"transactions":1,"transaction":1}
,"url":{"quartz":1}
,"locate":{"application":1}
,"server\u2019s":{"usertransaction":1}
,"usertransaction":{"manager":1,"calling":1}
,"manager":{"default":1}
,"specified)":{"java:comp\u002Fusertransaction":1}
,"java:comp\u002Fusertransaction":{"works":1}
,"almost":{"application":1}
,"websphere":{"users":1}
,"users":{"may":1}
,"jta\u002Fusertransaction":{"used":1}
,"configured":{"jobstorecmt":1}
,"jobstorecmt":{"org.quartz.scheduler.wrapjobexecutioninusertransaction":1}
,"org.quartz.scheduler.wrapjobexecutioninusertransaction":{"true":1}
,"start":{"usertransaction":1,"jta":1}
,"calling":{"execute":1}
,"execute":{"job":1,"method":1}
,"commit":{"job\u0027s":1}
,"method":{"completes":1}
,"completes":{"jobdatamap":1}
,"jobdatamap":{"updated":1}
,"updated":{"(if":1,"version":1}
,"statefuljob)":{"default":1}
,"interested":{"using":1}
,"@executeinjtatransaction":{"annotation":1}
,"annotation":{"job":1}
,"lets":{"control":1}
,"control":{"individual":1}
,"individual":{"job":1}
,"causes":{"occur":1}
,"jobs":{"org.quartz.scheduler.skipupdatecheck":1}
,"skip":{"running":1}
,"running":{"quick":1}
,"quick":{"web":1}
,"web":{"request":1}
,"request":{"determine":1}
,"determine":{"updated":1}
,"version":{"quartz":1}
,"download":{"check":1}
,"check":{"runs":1,"system":1,"production":1}
,"runs":{"update":1}
,"update":{"found":1,"check":1}
,"reported":{"available":1}
,"logs":{"disable":1}
,"disable":{"update":1}
,"org.terracotta.quartz.skipupdatecheck=true":{"(which":1}
,"environment":{"java":1}
,"command":{"line)":1}
,"line)":{"recommended":1}
,"production":{"deployments":1}
,"deployments":{"org.quartz.scheduler.batchtriggeracquisitionmaxcount":1}
,"org.quartz.scheduler.batchtriggeracquisitionmaxcount":{"maximum":1}
,"maximum":{"number":1}
,"number":{"triggers":1,"efficient":1,"likely":1}
,"node":{"allowed":1}
,"allowed":{"acquire":1,"acquired":1}
,"acquire":{"(for":1}
,"(for":{"firing)":1,"sake":1}
,"firing)":{"once":1}
,"once":{"default":1}
,"larger":{"number":1}
,"efficient":{"firing":1}
,"firing":{"(in":1}
,"(in":{"situations":1,"milliseconds)":1}
,"situations":{"triggers":1,"scheduler":1}
,"needing":{"fired":1}
,"fired":{"once)":1,"ahead":1,"near":1}
,"once)":{"cost":1}
,"cost":{"possible":1,"trigger":1}
,"imbalanced":{"load":1}
,"load":{"cluster":1}
,"nodes":{"value":1}
,"jdbc":{"jobstore":1}
,"org.quartz.jobstore.acquiretriggerswithinlock":{"true":1}
,"avoid":{"data":1}
,"data":{"corruption":1}
,"corruption":{"org.quartz.scheduler.batchtriggeracquisitionfireaheadtimewindow":1}
,"org.quartz.scheduler.batchtriggeracquisitionfireaheadtimewindow":{"amount":1}
,"milliseconds)":{"trigger":1}
,"acquired":{"fired":1}
,"ahead":{"scheduled":1}
,"scheduled":{"fire":1}
,"likely":{"batch":1}
,"batch":{"acquisition":1}
,"acquisition":{"triggers":1}
,"able":{"select":1}
,"select":{"fire":1}
,"comes":{"cost":1}
,"schedule":{"honored":1}
,"honored":{"precisely":1}
,"precisely":{"(triggers":1}
,"(triggers":{"fire":1}
,"early)":{"property":1}
,"sake":{"performance)":1}
,"performance)":{"situations":1}
,"large":{"number":1}
,"near":{"time":1}
}
;Search.control.loadWordPairs(pairs);
