var pairs =
{
"example":{"-cron-based":1,"designed":1,"fire":1,"example":1,"executed":1,"example3.sh":1,"resides":1,"made":1,"job":1}
,"-cron-based":{"triggers":1}
,"triggers":{"example":1}
,"designed":{"demonstrate":1}
,"demonstrate":{"crontriggers":1}
,"crontriggers":{"schedule":1}
,"schedule":{"jobs":1,"several":1}
,"jobs":{"example":1,"say":1,"using":1,"shut":1,"during":1,"hourly":1,"run":1,"completed":1}
,"fire":{"several":1}
,"several":{"simple":1,"jobs":1}
,"simple":{"jobs":1,"job":1,"ram-based":1}
,"say":{"hello":1}
,"hello":{"world":1}
,"world":{"display":1,"displays":1}
,"display":{"date":1}
,"date":{"time":1,"())":1}
,"time":{"job":1,"printed":1,"jobs":1}
,"job":{"executed":1,"says":1,"implements":1,"interface":1,"exactly":1,"scheduled":1,"=newjob":1,"program":1,"runs":1}
,"executed":{"program":1,"examples\u002Fexample3":1,"public":1}
,"program":{"perform":1,"simplejob":1,"starts":1,"sleeps":1,"gracefully":1}
,"perform":{"following":1}
,"following":{"actions":1,"classes":1}
,"actions":{"start":1}
,"start":{"quartz":1,"scheduling":1}
,"quartz":{"scheduler":1,"chance":1,"javadoc":1}
,"scheduler":{"schedule":1,"refer":1,"done":1,"create":1,"schedulerfactory":1,"sched":1,"started":1,"opportunity":1,"running":1,"sched.shutdown":1,"wait":1}
,"using":{"various":1,"create":1}
,"various":{"features":1}
,"features":{"crontrigger":1}
,"crontrigger":{"wait":1,"running":1,"trigger":1}
,"wait":{"300":1,"until":1}
,"300":{"seconds":1}
,"seconds":{"minutes)":1,"jobdetail":1,"past":1,"weekdays":1,"weekends":1}
,"minutes)":{"give":1}
,"give":{"quartz":1}
,"chance":{"run":1}
,"run":{"jobs":1,"example":1,"every":1,"10am":1,"job":1}
,"shut":{"down":1}
,"down":{"scheduler":1}
,"refer":{"quartz":1}
,"javadoc":{"thorough":1}
,"thorough":{"explanation":1}
,"explanation":{"crontrigger":1}
,"running":{"example":1,"background":1,"returning":1}
,"examples\u002Fexample3":{"directory":1}
,"directory":{"two":1}
,"two":{"ways":1}
,"ways":{"run":1}
,"example3.sh":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"script":1}
,"script":{"example3.bat":1}
,"example3.bat":{"windows":1}
,"windows":{"batch":1}
,"batch":{"file":1}
,"file":{"code":1}
,"code":{"code":1,"example":1}
,"resides":{"package":1}
,"package":{"org.quartz.examples.example3":1}
,"org.quartz.examples.example3":{"code":1}
,"made":{"following":1}
,"classes":{"class":1}
,"class":{"name":1}
,"name":{"description":1}
,"description":{"crontriggerexample":1}
,"crontriggerexample":{"main":1,"program":1}
,"main":{"program":1}
,"simplejob":{"simple":1,"simplejob":1,"says":1}
,"says":{"hello":1,"jobkey":1}
,"displays":{"date\u002Ftime":1}
,"date\u002Ftime":{"simplejob":1}
,"implements":{"job":1}
,"interface":{"logs":1}
,"logs":{"message":1}
,"message":{"log":1}
,"log":{"(by":1}
,"(by":{"default":1}
,"default":{"simply":1}
,"simply":{"screen)":1}
,"screen)":{"current":1}
,"current":{"date":1}
,"printed":{"job":1}
,"exactly":{"job":1}
,"public":{"void":1}
,"void":{"execute":1}
,"execute":{"(jobexecutioncontext":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"{jobkey":1}
,"{jobkey":{"jobkey":1}
,"jobkey":{"=context.getjobdetail":1,"executing":1}
,"=context.getjobdetail":{".getkey":1}
,".getkey":{"_log.info":1}
,"_log.info":{"simplejob":1}
,"executing":{"new":1}
,"new":{"date":1}
,"())":{"crontriggerexample":1}
,"starts":{"getting":1}
,"getting":{"instance":1}
,"instance":{"scheduler":1}
,"done":{"creating":1}
,"creating":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"using":1,"scheduler":1}
,"create":{"scheduler":1,"simple":1}
,"ram-based":{"scheduler":1}
,"schedulerfactory":{"=new":1}
,"=new":{"stdschedulerfactory":1}
,"sched":{"=sf.getscheduler":1}
,"=sf.getscheduler":{"job":1}
,"scheduled":{"run":1}
,"every":{"seconds":1,"minute":1,"three":1}
,"jobdetail":{"job":1}
,"=newjob":{"(simplejob.class)":1}
,"(simplejob.class)":{".withidentity":1}
,".withidentity":{"job1":1,"trigger1":1,"job2":1,"trigger2":1,"job3":1,"trigger3":1,"job4":1,"trigger4":1,"job5":1,"trigger5":1,"job6":1,"trigger6":1,"job7":1,"trigger7":1}
,"job1":{"group1":1}
,"group1":{".build":1,".withschedule":1}
,".build":{"crontrigger":1,"sched.schedulejob":1,"trigger":1}
,"trigger":{"=newtrigger":1}
,"=newtrigger":{".withidentity":1}
,"trigger1":{"group1":1}
,".withschedule":{"(cronschedule":1}
,"(cronschedule":{"0\u002F20":1,"0\u002F2":1,"0\u002F3":1,"10am":1,"0,30":1}
,"0\u002F20":{"****?":1}
,"****?":{"\u0022))":1}
,"\u0022))":{".build":1}
,"sched.schedulejob":{"(job":1}
,"(job":{"trigger)":1}
,"trigger)":{"job":1,"scheduler":1}
,"minute":{"starting":1,"job":1,"8am":1}
,"starting":{"seconds":1}
,"past":{"minute":1}
,"job2":{"group1":1}
,"trigger2":{"group1":1}
,"0\u002F2":{"***?":1,"8-17":1}
,"***?":{"\u0022))":1}
,"8am":{"5pm":1}
,"5pm":{"(17":1,"11pm":1}
,"(17":{":00)":1}
,":00)":{"job":1}
,"job3":{"group1":1}
,"trigger3":{"group1":1}
,"8-17":{"**?":1}
,"**?":{"\u0022))":1,"*mon-fri":1,"*sat":1}
,"three":{"minutes":1}
,"minutes":{"5pm":1,"(300":1}
,"11pm":{"job":1}
,"job4":{"group1":1}
,"trigger4":{"group1":1}
,"0\u002F3":{"17-23":1}
,"17-23":{"**?":1}
,"10am":{"1st":1,"1,15":1}
,"1st":{"15th":1}
,"15th":{"days":1}
,"days":{"month":1}
,"month":{"job":1}
,"job5":{"group1":1}
,"trigger5":{"group1":1}
,"1,15":{"\u0022))":1}
,"weekdays":{"(monday":1,"job":1}
,"(monday":{"friday)":1}
,"friday)":{"job":1}
,"job6":{"group1":1}
,"trigger6":{"group1":1}
,"0,30":{"**?":1}
,"*mon-fri":{"\u0022))":1}
,"weekends":{"(saturday":1,"thread.sleep":1}
,"(saturday":{"sunday)":1}
,"sunday)":{"job":1}
,"job7":{"group1":1}
,"trigger7":{"group1":1}
,"*sat":{"sun":1}
,"sun":{"\u0022))":1}
,"started":{"(it":1}
,"(it":{"fine":1}
,"fine":{"start":1}
,"scheduling":{"jobs)":1}
,"jobs)":{"sched.start":1}
,"sched.start":{"scheduler":1}
,"opportunity":{"run":1}
,"sleeps":{"five":1}
,"five":{"minutes":1}
,"(300":{"seconds)":1}
,"seconds)":{"scheduler":1}
,"background":{"fire":1}
,"during":{"time":1}
,"hourly":{"daily":1}
,"daily":{"restrictions":1}
,"restrictions":{"jobs":1}
,"runs":{"weekdays":1,"weekends":1}
,"thread.sleep":{"(300l":1}
,"(300l":{"*1000l)":1}
,"*1000l)":{"finally":1}
,"finally":{"program":1}
,"gracefully":{"shuts":1}
,"shuts":{"down":1}
,"sched.shutdown":{"(true)":1}
,"(true)":{"passing":1}
,"passing":{"true":1}
,"true":{"shutdown":1}
,"shutdown":{"method":1}
,"method":{"tells":1,"call":1}
,"tells":{"quartz":1}
,"until":{"jobs":1}
,"completed":{"running":1}
,"returning":{"method":1}
}
;Search.control.loadWordPairs(pairs);
