var pairs =
{
"questions":{"jdbcjobstore":1}
,"jdbcjobstore":{"improve":1}
,"improve":{"performance":1}
,"performance":{"jdbc-jobstore":1,"add":1}
,"jdbc-jobstore":{"few":1,"practical":1}
,"few":{"ways":1}
,"ways":{"speed":1}
,"speed":{"jdbc-jobstore":1}
,"practical":{"first":1}
,"first":{"obvious":1}
,"obvious":{"not-so-practical":1}
,"not-so-practical":{"buy":1}
,"buy":{"faster":1,"powerful":1,"different":1}
,"faster":{"network":1}
,"network":{"machine":1}
,"machine":{"runs":1,"run":1}
,"runs":{"quartz":1,"rdbms":1}
,"quartz":{"machine":1,"tables":1,"create":1,"properties":1}
,"rdbms":{"buy":1,"something":1}
,"powerful":{"machine":1}
,"run":{"database":1}
,"database":{"buy":1,"systems":1,"server":1}
,"different":{"rdbms":1}
,"something":{"simple":1}
,"simple":{"effective":1}
,"effective":{"build":1}
,"build":{"indexes":1}
,"indexes":{"quartz":1,"key":1,"every":1}
,"tables":{"database":1,"important":1,"distinct":1}
,"systems":{"automatically":1}
,"automatically":{"index":1}
,"index":{"primary-key":1,"foreign-key":1,"trigger":1,"idx_qrtz_t_next_fire_time":1,"idx_qrtz_t_state":1,"idx_qrtz_t_nf_st":1,"idx_qrtz_ft_trig_name":1,"idx_qrtz_ft_trig_group":1,"idx_qrtz_ft_trig_n_g":1,"idx_qrtz_ft_trig_inst_name":1,"idx_qrtz_ft_job_name":1,"idx_qrtz_ft_job_group":1,"idx_qrtz_t_next_fire_time_misfire":1,"idx_qrtz_t_nf_st_misfire":1,"idx_qrtz_t_nf_st_misfire_grp":1}
,"primary-key":{"fields":1}
,"fields":{"index":1,"every":1,"last":1}
,"foreign-key":{"field":1}
,"field":{"sure":1}
,"sure":{"yours":1,"connection":1,"datasource":1}
,"yours":{"indexes":1}
,"key":{"fields":1}
,"every":{"table":1,"column":1}
,"table":{"manually":1,"create":1}
,"manually":{"next":1,"add":1}
,"next":{"manually":1}
,"add":{"additional":1,"indexes":1,"clients":1}
,"additional":{"indexes":1}
,"important":{"index":1}
,"trigger":{"table\u0027s":1}
,"table\u0027s":{"next_fire_time":1}
,"next_fire_time":{"state":1,"trigger_state)":1,"trigger_group":1}
,"state":{"fields":1}
,"last":{"(but":1}
,"(but":{"important)":1}
,"important)":{"add":1}
,"column":{"fired_triggers":1}
,"fired_triggers":{"table":1}
,"create":{"index":1,"connection":1}
,"idx_qrtz_t_next_fire_time":{"qrtz_triggers":1}
,"qrtz_triggers":{"(next_fire_time)":1,"(trigger_state)":1,"(trigger_state":1}
,"(next_fire_time)":{"create":1}
,"idx_qrtz_t_state":{"qrtz_triggers":1}
,"(trigger_state)":{"create":1}
,"idx_qrtz_t_nf_st":{"qrtz_triggers":1}
,"(trigger_state":{"next_fire_time)":1}
,"next_fire_time)":{"create":1}
,"idx_qrtz_ft_trig_name":{"qrtz_fired_triggers":1}
,"qrtz_fired_triggers":{"(trigger_name)":1,"(trigger_group)":1,"(instance_name)":1,"(job_name)":1,"(job_group)":1}
,"(trigger_name)":{"create":1}
,"idx_qrtz_ft_trig_group":{"qrtz_fired_triggers":1}
,"(trigger_group)":{"create":1}
,"idx_qrtz_ft_trig_n_g":{"\u005Cqrtz_fired_triggers":1}
,"\u005Cqrtz_fired_triggers":{"(trigger_name":1}
,"(trigger_name":{"trigger_group)":1}
,"trigger_group)":{"create":1}
,"idx_qrtz_ft_trig_inst_name":{"qrtz_fired_triggers":1}
,"(instance_name)":{"create":1}
,"idx_qrtz_ft_job_name":{"qrtz_fired_triggers":1}
,"(job_name)":{"create":1}
,"idx_qrtz_ft_job_group":{"qrtz_fired_triggers":1}
,"(job_group)":{"create":1}
,"idx_qrtz_t_next_fire_time_misfire":{"\u005Cqrtz_triggers":1}
,"\u005Cqrtz_triggers":{"(misfire_instr":1}
,"(misfire_instr":{"next_fire_time)":1,"next_fire_time":1}
,"idx_qrtz_t_nf_st_misfire":{"\u005Cqrtz_triggers":1}
,"trigger_state)":{"create":1,"clustering":1}
,"idx_qrtz_t_nf_st_misfire_grp":{"\u005Cqrtz_triggers":1}
,"trigger_group":{"trigger_state)":1}
,"clustering":{"feature":1}
,"feature":{"works":1}
,"works":{"best":1,"long":1}
,"best":{"scaling":1}
,"scaling":{"long-running":1}
,"long-running":{"and\u002For":1}
,"and\u002For":{"cpu-intensive":1}
,"cpu-intensive":{"jobs":1}
,"jobs":{"(distributing":1,"consider":1,"using":1}
,"(distributing":{"work-load":1}
,"work-load":{"multiple":1}
,"multiple":{"nodes)":1,"distinct":1,"sets":1}
,"nodes)":{"need":1}
,"need":{"scale":1,"think":1}
,"scale":{"support":1}
,"support":{"thousands":1}
,"thousands":{"short-running":1}
,"short-running":{"second)":1}
,"second)":{"jobs":1}
,"consider":{"partitioning":1}
,"partitioning":{"jobs":1}
,"using":{"multiple":1,"scheduler":1}
,"distinct":{"schedulers":1,"prefixes)":1}
,"schedulers":{"(and":1}
,"(and":{"hence":1}
,"hence":{"multiple":1}
,"sets":{"tables":1}
,"prefixes)":{"using":1}
,"scheduler":{"forces":1}
,"forces":{"cluster-wide":1}
,"cluster-wide":{"lock":1}
,"lock":{"pattern":1}
,"pattern":{"degrades":1}
,"degrades":{"performance":1}
,"clients":{"connections":1}
,"connections":{"recover":1}
,"recover":{"properly":1}
,"properly":{"database":1}
,"server":{"restarted":1,"sure":1}
,"restarted":{"you\u0027re":1}
,"you\u0027re":{"having":1,"datasource":1}
,"having":{"quartz":1}
,"connection":{"datasource":1,"parameters":1,"validation":1,"good":1}
,"datasource":{"(by":1,"managed":1,"configured":1}
,"(by":{"specifying":1}
,"specifying":{"connection":1}
,"parameters":{"quartz":1}
,"properties":{"file)":1}
,"file)":{"sure":1}
,"validation":{"query":1}
,"query":{"specified":1,"extremely":1,"always":1}
,"specified":{"org.quartz.datasource.myds.validationquery=select":1}
,"org.quartz.datasource.myds.validationquery=select":{"dual":1}
,"dual":{"particular":1}
,"particular":{"query":1}
,"extremely":{"efficient":1}
,"efficient":{"oracle":1,"query":1}
,"oracle":{"databases":1}
,"databases":{"you\u0027ll":1}
,"you\u0027ll":{"need":1}
,"think":{"efficient":1}
,"always":{"works":1}
,"long":{"connection":1}
,"good":{"you\u0027re":1}
,"managed":{"application":1}
,"application":{"server":1}
,"configured":{"detect":1}
,"detect":{"failed":1}
,"failed":{"connections":1}
}
;Search.control.loadWordPairs(pairs);
