var pairs =
{
"quartz":{"example":1,"ships":1,"quartz":1,"api":1,"distribution":1,"examples":1,"directory":1,"program":1,"plug-ins":1,"scheduler":1,"demonstrates":1,"used":1,"database":1,"using":1}
,"example":{"programs":1,"sub-directory":1,"readme.txt":1,"examples":1,"-first":1,"quartz":1,"-your":1,"-simple":1,"-cron":1,"-cron-based":1,"-job":1,"-handling":1,"-dealing":1,"-interrupting":1,"-fun":1,"-using":1,"-quartz":1,"-remote":1,"-clustered":1,"-trigger":1,"-tc":1}
,"programs":{"welcome":1,"quartz":1,"documentation":1}
,"welcome":{"documentation":1}
,"documentation":{"quartz":1,"provided":1}
,"ships":{"out-of-the-box":1}
,"out-of-the-box":{"examples":1}
,"examples":{"demonstrate":1,"examples":1,"listed":1,"reside":1,"directory":1,"windows":1,"source":1,"located":1,"following":1,"noted":1,"become":1}
,"demonstrate":{"various":1}
,"various":{"features":1}
,"features":{"quartz":1}
,"api":{"find":1}
,"find":{"examples":1,"sub-directory":1,"sub-package":1}
,"listed":{"below":1}
,"below":{"part":1,"ffc-don":1}
,"part":{"quartz":1}
,"distribution":{"quartz":1}
,"reside":{"examples":1}
,"directory":{"main":1,"examples":1,"find":1}
,"main":{"quartz":1}
,"sub-directory":{"example":1,"includes":1}
,"includes":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"scripts":1}
,"scripts":{"executing":1}
,"executing":{"examples":1}
,"windows":{"batch":1}
,"batch":{"files":1}
,"files":{"additionally":1}
,"additionally":{"every":1}
,"every":{"example":1}
,"readme.txt":{"file":1}
,"file":{"please":1,"running":1}
,"please":{"consult":1}
,"consult":{"readme":1}
,"readme":{"file":1}
,"running":{"examples":1}
,"source":{"code":1}
,"code":{"examples":1,"jobs":1}
,"located":{"org.quartz.examples":1}
,"org.quartz.examples":{"package":1}
,"package":{"find":1}
,"sub-package":{"example":1}
,"following":{"provides":1}
,"provides":{"overview":1,"hello":1}
,"overview":{"example":1}
,"provided":{"certain":1}
,"certain":{"examples":1}
,"noted":{"below":1}
,"ffc-don":{"need":1}
,"need":{"add":1}
,"add":{"missing":1}
,"missing":{"xrefs":1}
,"xrefs":{"examples":1}
,"become":{"available":1}
,"available":{"example":1}
,"-first":{"quartz":1}
,"program":{"provides":1,"example":1}
,"hello":{"world":1}
,"world":{"example":1}
,"-your":{"first":1}
,"first":{"quartz":1}
,"-simple":{"triggers":1}
,"triggers":{"shows":1,"schedule":1,"used":1,"example":1,"fire":1}
,"shows":{"dozen":1,"cron":1,"deal":1,"scheduler":1,"job":1,"thread":1,"remote":1}
,"dozen":{"different":1}
,"different":{"ways":1}
,"ways":{"using":1}
,"using":{"simple":1,"rmi":1,"terracotta":1}
,"simple":{"triggers":1,"workflow":1}
,"schedule":{"jobs":1,"job":1}
,"jobs":{"example":1,"jobs":1,"maintain":1,"shows":1,"code":1,"deal":1,"holiday":1,"execute":1}
,"-cron":{"triggers":1}
,"cron":{"triggers":1}
,"used":{"schedule":1,"exclude":1,"clustered":1,"manage":1}
,"job":{"example":1,"state":1,"misfires":1,"execute":1,"exceptions":1,"listeners":1,"trigger":1,"building":1,"initialization":1,"scheduling":1}
,"-cron-based":{"triggers":1}
,"-job":{"state":1,"parameters":1,"misfires":1,"listeners":1}
,"state":{"parameters":1,"example":1}
,"parameters":{"demonstrates":1,"passed":1,"job":1}
,"demonstrates":{"parameters":1,"holiday":1,"xml":1,"quartz":1,"trigger":1,"cluster":1}
,"passed":{"jobs":1}
,"maintain":{"state":1}
,"-handling":{"job":1}
,"misfires":{"show":1,"job":1,"example":1}
,"show":{"handle":1}
,"handle":{"misfires":1}
,"execute":{"supposed":1,"simultaneously":1}
,"supposed":{"example":1}
,"-dealing":{"job":1}
,"exceptions":{"shows":1,"thrown":1,"example":1}
,"deal":{"exceptions":1,"interruptions":1}
,"thrown":{"job":1}
,"-interrupting":{"jobs":1}
,"scheduler":{"interrupt":1,"remotely":1}
,"interrupt":{"jobs":1}
,"interruptions":{"example":1}
,"-fun":{"calendars":1}
,"calendars":{"demonstrates":1}
,"holiday":{"calendar":1,"example":1}
,"calendar":{"used":1}
,"exclude":{"execution":1}
,"execution":{"jobs":1}
,"listeners":{"shows":1,"job":1}
,"trigger":{"job":1,"priorities":1}
,"building":{"simple":1}
,"workflow":{"example":1}
,"-using":{"quartz":1}
,"plug-ins":{"demonstrates":1,"example":1}
,"xml":{"job":1}
,"initialization":{"plug-in":1}
,"plug-in":{"history":1}
,"history":{"logging":1}
,"logging":{"plug-ins":1}
,"-quartz":{"high":1}
,"high":{"load":1}
,"load":{"shows":1}
,"thread":{"pools":1}
,"pools":{"limit":1}
,"limit":{"number":1}
,"number":{"jobs":1}
,"simultaneously":{"example":1}
,"-remote":{"job":1}
,"scheduling":{"using":1,"information":1}
,"rmi":{"shows":1}
,"remote":{"method":1}
,"method":{"invocation":1}
,"invocation":{"quartz":1}
,"remotely":{"scheduled":1}
,"scheduled":{"client":1}
,"client":{"example":1}
,"-clustered":{"quartz":1}
,"clustered":{"environment":1,"quartz":1}
,"environment":{"quartz":1}
,"database":{"persist":1}
,"persist":{"scheduling":1}
,"information":{"example":1}
,"-trigger":{"priorities":1}
,"priorities":{"demonstrates":1,"used":1,"example":1}
,"manage":{"firing":1}
,"firing":{"order":1}
,"order":{"triggers":1}
,"fire":{"time":1}
,"time":{"example":1}
,"-tc":{"clustered":1}
,"cluster":{"quartz":1}
,"terracotta":{"server":1}
,"server":{"array":1}
,"array":{"rather":1}
,"rather":{"database":1}
}
;Search.control.loadWordPairs(pairs);
