var pairs =
{
"code":{"snippets":1,"examples":1}
,"snippets":{"quartz":1,"collection":1,"assume":1}
,"quartz":{"code":1,"snippets":1}
,"collection":{"code":1}
,"examples":{"show":1}
,"show":{"specific":1}
,"specific":{"things":1}
,"things":{"quartz":1}
,"assume":{"used":1}
,"used":{"static":1}
,"static":{"imports":1,"org.quartz.jobbuilder.*":1,"org.quartz.triggerbuilder.*":1,"org.quartz.simpleschedulebuilder.*":1,"org.quartz.cronschedulebuilder.*":1,"org.quartz.calendarintervalschedulebuilder.*":1,"org.quartz.jobkey.*":1,"org.quartz.triggerkey.*":1,"org.quartz.datebuilder.*":1,"org.quartz.impl.matchers.keymatcher.*":1,"org.quartz.impl.matchers.groupmatcher.*":1,"org.quartz.impl.matchers.andmatcher.*":1,"org.quartz.impl.matchers.ormatcher.*":1,"org.quartz.impl.matchers.everythingmatcher.*":1}
,"imports":{"quartz\u0027s":1}
,"quartz\u0027s":{"dsl":1}
,"dsl":{"classes":1}
,"classes":{"import":1}
,"import":{"static":1}
,"org.quartz.jobbuilder.*":{"import":1}
,"org.quartz.triggerbuilder.*":{"import":1}
,"org.quartz.simpleschedulebuilder.*":{"import":1}
,"org.quartz.cronschedulebuilder.*":{"import":1}
,"org.quartz.calendarintervalschedulebuilder.*":{"import":1}
,"org.quartz.jobkey.*":{"import":1}
,"org.quartz.triggerkey.*":{"import":1}
,"org.quartz.datebuilder.*":{"import":1}
,"org.quartz.impl.matchers.keymatcher.*":{"import":1}
,"org.quartz.impl.matchers.groupmatcher.*":{"import":1}
,"org.quartz.impl.matchers.andmatcher.*":{"import":1}
,"org.quartz.impl.matchers.ormatcher.*":{"import":1}
}
;Search.control.loadWordPairs(pairs);
