var pairs =
{
"how-to":{"instantiate":1}
,"instantiate":{"scheduler":1}
,"scheduler":{"instantiating":1,"\u002F\u002Fthe":1,"defined":1,"scheduler":1,"=sf.getscheduler":1,"specific":1}
,"instantiating":{"default":1,"specific":1,"aspecific":1}
,"default":{"scheduler":1,"quartz.jar":1}
,"\u002F\u002Fthe":{"\u0027default":1}
,"\u0027default":{"scheduler":1}
,"defined":{"quartz.properties":1}
,"quartz.properties":{"found":1}
,"found":{"\u002F\u002Fin":1}
,"\u002F\u002Fin":{"current":1}
,"current":{"working":1}
,"working":{"directory":1}
,"directory":{"classpath":1}
,"classpath":{"\u002F\u002Fresorts":1}
,"\u002F\u002Fresorts":{"fall-back":1}
,"fall-back":{"default":1}
,"quartz.jar":{"schedulerfactory":1}
,"schedulerfactory":{"=new":1}
,"=new":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"scheduler":1,"=new":1,"sf.initialize":1}
,"=sf.getscheduler":{"\u002F\u002Fscheduler":1}
,"\u002F\u002Fscheduler":{"execute":1}
,"execute":{"jobs":1}
,"jobs":{"until":1}
,"until":{"started":1}
,"started":{"(though":1}
,"(though":{"\u002F\u002Fcan":1}
,"\u002F\u002Fcan":{"scheduled":1}
,"scheduled":{"start":1}
,"start":{"())":1}
,"())":{"scheduler.start":1}
,"scheduler.start":{"instantiating":1}
,"specific":{"scheduler":1,"properties":1,"property":1}
,"properties":{"stdschedulerfactory":1}
,"sf.initialize":{"(schedulerproperties)":1,"(filename)":1}
,"(schedulerproperties)":{"scheduler":1}
,"aspecific":{"scheduler":1}
,"property":{"file":1}
,"file":{"stdschedulerfactory":1}
,"(filename)":{"scheduler":1}
}
;Search.control.loadWordPairs(pairs);
