var pairs =
{
"jdbc":{"jobstore":1}
,"jobstore":{"tips":1}
,"tips":{"write":1}
,"write":{"directly":1}
,"directly":{"quartz\u0027s":1,"database":1}
,"quartz\u0027s":{"tables":1}
,"tables":{"writing":1,"instances":1}
,"writing":{"scheduling":1}
,"scheduling":{"data":1,"api":1}
,"data":{"directly":1,"corruption":1,"scrambled":1}
,"database":{"(via":1,"scheduler":1,"tables":1}
,"(via":{"sql)":1}
,"sql)":{"rather":1}
,"rather":{"using":1}
,"using":{"scheduling":1,"jobstorecmt":1}
,"api":{"results":1,"using":1}
,"results":{"data":1,"job":1}
,"corruption":{"(deleted":1,"point":1,"ensure":1}
,"(deleted":{"data":1}
,"scrambled":{"data)":1}
,"data)":{"results":1}
,"job":{"seemingly":1,"executing":1}
,"seemingly":{"vanishing":1}
,"vanishing":{"without":1}
,"without":{"executing":1}
,"executing":{"trigger\u0027s":1,"just":1}
,"trigger\u0027s":{"fire":1}
,"fire":{"time":1}
,"time":{"arrives":1}
,"arrives":{"results":1,"may":1}
,"just":{"sitting":1}
,"sitting":{"trigger\u0027s":1}
,"may":{"result":1,"occur":1,"need":1}
,"result":{"dead-locks":1}
,"dead-locks":{"strange":1}
,"strange":{"problems":1}
,"problems":{"data":1}
,"point":{"non-clustered":1,"scheduler":1}
,"non-clustered":{"scheduler":1}
,"scheduler":{"database":1,"scheduler":1,"name":1,"instance":1,"api":1}
,"name":{"point":1}
,"instance":{"database":1}
,"instances":{"configured":1}
,"configured":{"clustering":1,"least":1}
,"clustering":{"following":1}
,"following":{"may":1}
,"occur":{"results":1}
,"ensure":{"adequate":1}
,"adequate":{"datasource":1}
,"datasource":{"connection":1,"max":1}
,"connection":{"size":1}
,"size":{"recommended":1,"configured":1,"least":1}
,"recommended":{"datasource":1}
,"max":{"connection":1}
,"least":{"number":1,"four":1}
,"number":{"worker":1}
,"worker":{"threads":1}
,"threads":{"thread":1}
,"thread":{"pool":1}
,"pool":{"plus":1}
,"plus":{"three":1}
,"three":{"may":1}
,"need":{"additional":1}
,"additional":{"connections":1}
,"connections":{"application":1}
,"application":{"making":1}
,"making":{"frequent":1}
,"frequent":{"calls":1}
,"calls":{"scheduler":1}
,"jobstorecmt":{"non-managed":1}
,"non-managed":{"datasource":1}
}
;Search.control.loadWordPairs(pairs);
