var pairs =
{
"plug-ins":{"quartz":1}
,"quartz":{"provides":1,"provide":1}
,"provides":{"org.quartz.spi.schedulerplugin":1}
,"org.quartz.spi.schedulerplugin":{"interface":1}
,"interface":{"plugging-in":1}
,"plugging-in":{"additional":1}
,"additional":{"functionality":1}
,"functionality":{"plugins":1,"auto-scheduling":1}
,"plugins":{"ship":1,"provide":1}
,"ship":{"quartz":1}
,"provide":{"various":1,"functionality":1}
,"various":{"utility":1}
,"utility":{"capabilities":1}
,"capabilities":{"documented":1}
,"documented":{"org.quartz.plugins":1}
,"org.quartz.plugins":{"package":1}
,"package":{"plugins":1}
,"auto-scheduling":{"jobs":1}
,"jobs":{"upon":1}
,"upon":{"scheduler":1}
,"scheduler":{"startup":1,"shuts":1}
,"startup":{"logging":1}
,"logging":{"history":1}
,"history":{"job":1}
,"job":{"trigger":1}
,"trigger":{"events":1}
,"events":{"ensuring":1}
,"ensuring":{"scheduler":1}
,"shuts":{"down":1}
,"down":{"cleanly":1}
,"cleanly":{"jvm":1}
,"jvm":{"exits":1}
}
;Search.control.loadWordPairs(pairs);
