var pairs =
{
"ramjobstore":{"ramjobstore":1,"simplest":1,"name":1,"application":1,"cannot":1,"(and":1}
,"simplest":{"jobstore":1}
,"jobstore":{"offers":1}
,"offers":{"best":1}
,"best":{"performance":1}
,"performance":{"(in":1}
,"(in":{"terms":1}
,"terms":{"cpu":1}
,"cpu":{"time)":1}
,"time)":{"ramjobstore":1}
,"name":{"indicates":1}
,"indicates":{"keeps":1}
,"keeps":{"data":1}
,"data":{"ram":1}
,"ram":{"it\u0027s":1}
,"it\u0027s":{"lightning-fast":1}
,"lightning-fast":{"simple":1}
,"simple":{"configure":1}
,"configure":{"drawback":1}
,"drawback":{"using":1}
,"using":{"ramjobstore":1,"stdschedulerfactory)":1}
,"application":{"ends":1}
,"ends":{"(or":1}
,"(or":{"crashes)":1}
,"crashes)":{"scheduling":1}
,"scheduling":{"information":1}
,"information":{"lost":1}
,"lost":{"therefore":1}
,"therefore":{"ramjobstore":1}
,"cannot":{"honor":1}
,"honor":{"setting":1}
,"setting":{"non-volatility":1}
,"non-volatility":{"jobs":1}
,"jobs":{"triggers":1}
,"triggers":{"applications":1}
,"applications":{"acceptable":1,"may":1}
,"acceptable":{"even":1}
,"even":{"desired":1}
,"desired":{"behavior":1}
,"behavior":{"applications":1}
,"may":{"disastrous":1}
,"disastrous":{"ramjobstore":1}
,"(and":{"assuming":1}
,"assuming":{"you\u0027re":1}
,"you\u0027re":{"using":1}
,"stdschedulerfactory)":{"simply":1}
,"simply":{"org.quartz.jobstore.class":1}
,"org.quartz.jobstore.class":{"property":1,"=org.quartz.simpl.ramjobstore":1}
,"property":{"org.quartz.simpl.ramjobstore":1}
,"org.quartz.simpl.ramjobstore":{"illustrated":1}
,"illustrated":{"example":1}
,"example":{"below":1}
,"below":{"org.quartz.jobstore.class":1}
,"=org.quartz.simpl.ramjobstore":{"settings":1}
,"settings":{"need":1}
,"need":{"worry":1}
}
;Search.control.loadWordPairs(pairs);
