var pairs =
{
"jta":{"transactions":1,"transaction":1}
,"transactions":{"jobstorecmt":1,"jobs":1,"calls":1,"using":1}
,"jobstorecmt":{"allows":1,"just":1}
,"allows":{"quartz":1}
,"quartz":{"scheduling":1,"automatically":1}
,"scheduling":{"operations":1}
,"operations":{"performed":1}
,"performed":{"within":1}
,"within":{"larger":1,"jta":1,"sessionbean":1}
,"larger":{"jta":1}
,"jobs":{"execute":1,"indicate":1}
,"execute":{"within":1,"method":1,"terminates":1}
,"transaction":{"(usertransaction)":1,"begin":1,"wrap":1,"calling":1}
,"(usertransaction)":{"setting":1}
,"setting":{"org.quartz.scheduler.wrapjobexecutioninusertransaction":1}
,"org.quartz.scheduler.wrapjobexecutioninusertransaction":{"property":1}
,"property":{"true":1}
,"true":{"option":1}
,"option":{"jta":1}
,"begin":{"just":1}
,"just":{"job\u0027s":1,"call":1,"sure":1}
,"job\u0027s":{"execute":1}
,"method":{"called":1,"scheduler":1}
,"called":{"commit":1}
,"commit":{"just":1}
,"call":{"execute":1}
,"terminates":{"applies":1}
,"applies":{"jobs":1}
,"indicate":{"per":1}
,"per":{"job":1}
,"job":{"whether":1,"class":1,"executions":1}
,"whether":{"jta":1}
,"wrap":{"execution":1}
,"execution":{"@executeinjtatransaction":1}
,"@executeinjtatransaction":{"annotation":1}
,"annotation":{"job":1}
,"class":{"aside":1}
,"aside":{"quartz":1}
,"automatically":{"wrapping":1}
,"wrapping":{"job":1}
,"executions":{"jta":1}
,"calls":{"scheduler":1}
,"scheduler":{"interface":1,"either":1,"within":1}
,"interface":{"participate":1}
,"participate":{"transactions":1}
,"using":{"jobstorecmt":1}
,"sure":{"you\u0027ve":1}
,"you\u0027ve":{"started":1}
,"started":{"transaction":1}
,"calling":{"method":1}
,"either":{"directly":1}
,"directly":{"usertransaction":1}
,"usertransaction":{"putting":1}
,"putting":{"code":1}
,"code":{"uses":1}
,"uses":{"scheduler":1,"container-managed":1}
,"sessionbean":{"uses":1}
,"container-managed":{"transactions":1}
}
;Search.control.loadWordPairs(pairs);
