var pairs =
{
"factory-shipped":{"jobs":1}
,"jobs":{"ffc-can":1,"chapter":1,"application":1,"org.quartz.jobs":1}
,"ffc-can":{"find":1}
,"find":{"new":1,"documentation":1}
,"new":{"home":1}
,"home":{"topic":1}
,"topic":{"example":1}
,"example":{"jobs":1}
,"chapter":{"quartz":1}
,"quartz":{"provides":1}
,"provides":{"number":1}
,"number":{"utility":1}
,"utility":{"jobs":1}
,"application":{"doing":1}
,"doing":{"things":1}
,"things":{"sending":1}
,"sending":{"e-mails":1}
,"e-mails":{"invoking":1}
,"invoking":{"ejbs":1}
,"ejbs":{"find":1}
,"documentation":{"jobs":1}
,"org.quartz.jobs":{"package":1}
}
;Search.control.loadWordPairs(pairs);
