var pairs =
{
"production":{"system":1,"deployments":1}
,"system":{"tips":1,"property":1,"environment":1}
,"tips":{"skip":1}
,"skip":{"update":1}
,"update":{"check":1,"found":1}
,"check":{"quartz":1,"feature":1,"new":1,"runs":1,"setting":1,"production":1}
,"quartz":{"contains":1,"available":1,"fails":1,"logs":1,"property":1}
,"contains":{"update":1}
,"feature":{"connects":1}
,"connects":{"server":1}
,"server":{"check":1}
,"new":{"version":1}
,"version":{"quartz":1}
,"available":{"download":1,"quartz":1}
,"download":{"check":1}
,"runs":{"asynchronously":1,"update":1}
,"asynchronously":{"affect":1}
,"affect":{"startup\u002Finitialization":1}
,"startup\u002Finitialization":{"time":1}
,"time":{"quartz":1}
,"fails":{"gracefully":1}
,"gracefully":{"connection":1}
,"connection":{"cannot":1}
,"cannot":{"made":1}
,"made":{"check":1}
,"found":{"reported":1}
,"reported":{"available":1}
,"logs":{"disable":1}
,"disable":{"update":1}
,"setting":{"quartz":1}
,"property":{"org.quartz.scheduler.skipupdatecheck:true":1,"org.terracotta.quartz.skipupdatecheck=true":1}
,"org.quartz.scheduler.skipupdatecheck:true":{"system":1}
,"org.terracotta.quartz.skipupdatecheck=true":{"(which":1}
,"(which":{"system":1}
,"environment":{"java":1}
,"java":{"command":1}
,"command":{"line)":1}
,"line)":{"recommended":1}
,"recommended":{"disable":1}
}
;Search.control.loadWordPairs(pairs);
