var pairs =
{
"application":{"server":1}
,"server":{"datasource":1,"defined":1,"org.quartz.datasource.name.java.naming.factory.initial":1,"org.quartz.datasource.myotherds.jndiurl=jdbc\u002Fmydatasource":1}
,"datasource":{"properties":1,"managed":1,"referenced":1}
,"properties":{"datasources":1,"property":1}
,"datasources":{"managed":1}
,"managed":{"application":1}
,"defined":{"using":1}
,"using":{"following":1}
,"following":{"properties":1}
,"property":{"name":1}
,"name":{"required":1,"jndi":1}
,"required":{"type":1}
,"type":{"default":1}
,"default":{"value":1}
,"value":{"org.quartz.datasource.name.jndiurl":1}
,"org.quartz.datasource.name.jndiurl":{"string":1,"jndi":1}
,"string":{"null":1}
,"null":{"org.quartz.datasource.name.java":1,"org.quartz.datasource.name.jndiurl":1}
,"org.quartz.datasource.name.java":{"naming.factory.initial":1,"naming.provider.url":1,"naming.security.principal":1,"naming.security.credentials":1}
,"naming.factory.initial":{"string":1}
,"naming.provider.url":{"string":1}
,"naming.security.principal":{"string":1}
,"naming.security.credentials":{"string":1}
,"jndi":{"url":1,"initialcontextfactory":1,"context":1}
,"url":{"datasource":1,"connecting":1}
,"org.quartz.datasource.name.java.naming.factory.initial":{"(optional)":1}
,"(optional)":{"class":1,"url":1,"user":1}
,"class":{"name":1}
,"initialcontextfactory":{"org.quartz.datasource.name.java.naming.provider.url":1}
,"org.quartz.datasource.name.java.naming.provider.url":{"(optional)":1}
,"connecting":{"jndi":1}
,"context":{"org.quartz.datasource.name.java.naming.security.principal":1,"org.quartz.datasource.name.java.naming.security.credentials":1,"example":1}
,"org.quartz.datasource.name.java.naming.security.principal":{"(optional)":1}
,"user":{"principal":1,"credentials":1}
,"principal":{"connecting":1}
,"org.quartz.datasource.name.java.naming.security.credentials":{"(optional)":1}
,"credentials":{"connecting":1}
,"example":{"datasource":1}
,"referenced":{"application":1}
,"org.quartz.datasource.myotherds.jndiurl=jdbc\u002Fmydatasource":{"org.quartz.datasource.myotherds.java.naming.factory.initial=com.evermind":1}
,"org.quartz.datasource.myotherds.java.naming.factory.initial=com.evermind":{"server.rmi.rmiinitialcontextfactory":1}
,"server.rmi.rmiinitialcontextfactory":{"org.quartz.datasource.myotherds.java.naming.provider.url=ormi:\u002F\u002Flocalhost":1}
,"org.quartz.datasource.myotherds.java.naming.provider.url=ormi:\u002F\u002Flocalhost":{"org.quartz.datasource.myotherds.java.naming.security.principal=admin":1}
,"org.quartz.datasource.myotherds.java.naming.security.principal=admin":{"org.quartz.datasource.myotherds.java.naming.security.credentials=123":1}
}
;Search.control.loadWordPairs(pairs);
