var pairs =
{
"crontriggers":{"cron":1,"crontrigger":1,"specify":1}
,"cron":{"unix":1,"crontrigger":1,"expressions":1}
,"unix":{"tool":1}
,"tool":{"around":1}
,"around":{"long":1}
,"long":{"time":1}
,"time":{"scheduling":1,"shift":1,"moves":1}
,"scheduling":{"capabilities":1}
,"capabilities":{"powerful":1,"cron":1}
,"powerful":{"proven":1}
,"proven":{"crontrigger":1}
,"crontrigger":{"class":1,"uses":1,"often":1,"specify":1,"starttime":1,"cron-expressions":1,"javadoc)":1,"instances":1,"misfire":1,"(misfire":1,"itself":1,"misfire_instruction_fire_now":1}
,"class":{"based":1}
,"based":{"scheduling":1,"calendar-like":1}
,"uses":{"cron":1}
,"expressions":{"able":1,"cron-expressions":1,"simple":1}
,"able":{"create":1}
,"create":{"firing":1}
,"firing":{"schedules":1,"occur":1}
,"schedules":{"8:00am":1}
,"8:00am":{"every":1}
,"every":{"monday":1,"last":1,"friday":1,"weekday":1,"minutes":1,"wednesday":1,"possible":1,"month":1,"day":1,"35th":1,"minute":1,"days":1,"november":1}
,"monday":{"friday":1,"wednesday":1,"16th":1,"3rd":1,"month":1,"tuesday":1}
,"friday":{"1:30am":1,"month":1,"noon":1,"during":1,"\u002F-used":1,"14th":1,"fire":1,"every":1}
,"1:30am":{"every":1}
,"last":{"friday":1,"different":1,"day":1,"xxx":1,"-has":1,"weekday":1}
,"month":{"crontrigger":1,"day-of-week":1,"field":1,"months":1,"-day":1,"-for":1,"specify":1,"l-3":1,"using":1,"used":1,"example":1,"format":1,"1-31":1,"1-12":1,"(say":1,"last":1,"15th":1,"-used":1,"(day":1,"=the":1,"note":1,"firing":1,"legal":1,"march":1,"fire":1,"l-2":1,"*6l":1,"during":1,"1\u002F5":1,"starting":1}
,"often":{"useful":1}
,"useful":{"simpletrigger":1,"need":1}
,"simpletrigger":{"need":1,"crontrigger":1}
,"need":{"job-firing":1,"careful":1,"specify":1}
,"job-firing":{"schedule":1}
,"schedule":{"recurs":1,"force":1,"discontinued":1,"sub-expression":1,"(via":1}
,"recurs":{"based":1}
,"calendar-like":{"notions":1}
,"notions":{"rather":1}
,"rather":{"exactly":1}
,"exactly":{"specified":1}
,"specified":{"intervals":1,"values":1,"day-of-month":1}
,"intervals":{"simpletrigger":1}
,"specify":{"firing-schedules":1,"increments":1,"specific":1,"something":1,"offset":1,"lists":1,"weekday":1,"15w":1,"nth":1,"ranges":1,"additional":1,"character":1,"value":1,"given":1,"misfire":1}
,"firing-schedules":{"every":1}
,"noon":{"every":1}
,"weekday":{"9:30":1,"(monday-friday)":1,"15th":1,"month":1,"-used":1}
,"9:30":{"even":1}
,"even":{"every":1,"simpletrigger":1,"mon-wed":1}
,"minutes":{"9:00":1,"hours":1,"values":1,"field":1,"-it":1,"starting":1}
,"9:00":{"10:00":1}
,"10:00":{"every":1}
,"wednesday":{"friday":1,"12:00:00":1,"month":1,"thursday":1}
,"during":{"january":1,"year":1,"years":1}
,"january":{"even":1,"day":1}
,"starttime":{"specifies":1}
,"specifies":{"schedule":1}
,"force":{"(optional)":1}
,"(optional)":{"endtime":1}
,"endtime":{"specifies":1}
,"discontinued":{"cron":1}
,"cron-expressions":{"used":1,"strings":1}
,"used":{"configure":1,"say":1,"specify":1,"3\u002F20":1,"day-of-week":1,"inform":1}
,"configure":{"instances":1}
,"instances":{"crontrigger":1,"built":1}
,"strings":{"actually":1,"jan":1,"sun":1}
,"actually":{"made":1}
,"made":{"seven":1}
,"seven":{"sub-expressions":1}
,"sub-expressions":{"describe":1,"contain":1}
,"describe":{"individual":1}
,"individual":{"details":1,"sub-expressions":1}
,"details":{"schedule":1,"behavior":1}
,"sub-expression":{"separated":1}
,"separated":{"white-space":1}
,"white-space":{"represent":1}
,"represent":{"seconds":1}
,"seconds":{"minutes":1,"0-59":1,"field":1,"5\u002F15":1,"specify":1}
,"hours":{"day-of-month":1,"-used":1,"morning":1}
,"day-of-month":{"month":1,"value":1,"day-of-week":1,"field":1,"1st":1,"single":1,"fields":1}
,"day-of-week":{"year":1,"field":1,"fields":1,"month":1,"day-of-month":1}
,"year":{"(optional":1,"empty":1,"2005":1}
,"(optional":{"field)":1}
,"field)":{"example":1}
,"example":{"complete":1,"day":1,"replaced":1,"simply":1,"put":1,"value":1,"fril":1,"specify":1,"\u0022*\u0022":1,"want":1,"10-12":1,"mon":1,"0\u002F15":1,"means":1}
,"complete":{"cron-expression":1,"(you":1}
,"cron-expression":{"string":1}
,"string":{"wed":1}
,"wed":{"\u0022*-which":1,"example":1,"fri":1,"thu":1,"fire":1}
,"\u0022*-which":{"means":1}
,"means":{"every":1,"\u0027every":1,"last":1,"sat":1,"third":1,"hours":1,"days":1,"seconds":1,"fire":1}
,"12:00:00":{"individual":1}
,"contain":{"ranges":1}
,"ranges":{"and\u002For":1,"values":1,"example":1}
,"and\u002For":{"lists":1}
,"lists":{"example":1,"ranges":1}
,"day":{"week":1,"month":1,"february":1,"calendar":1,"example":1,"range":1,"**fire":1,"**?":1,"during":1,"0\u002F5":1,"0-5":1,"10,44":1,"every":1,"trigger":1}
,"week":{"field":1,"fields":1,"1-7":1,"happens":1,"case":1}
,"field":{"previous":1,"therefore":1,"means":1,"mean":1,"note":1,"itself":1,"value":1,"meaning":1,"name":1,"example":1,"day-of-week":1,"examples":1,"yield":1}
,"previous":{"(which":1,"example":1}
,"(which":{"reads":1}
,"reads":{"wed":1}
,"replaced":{"mon-fri":1}
,"mon-fri":{"mon":1,"2002-2010":1}
,"mon":{"wed":1,"tue":1,"mon":1,"examples":1}
,"fri":{"even":1,"sat":1,"day-of-week":1}
,"mon-wed":{"sat":1}
,"sat":{"wild-cards":1,"character":1,"used":1}
,"wild-cards":{"(the":1}
,"(the":{"character)":1}
,"character)":{"used":1}
,"say":{"every":1}
,"possible":{"value":1}
,"value":{"field":1,"1-31":1,"useful":1,"day-of-month":1,"means":1,"fri":1,"-useful":1,"day-of-week":1,"complete":1}
,"therefore":{"character":1,"obviously":1}
,"character":{"month":1,"used":1,"allowed":1,"short-hand":1,"-in":1,"specified":1,"fields)":1}
,"simply":{"means":1}
,"obviously":{"mean":1}
,"mean":{"every":1,"\u0027every":1,"last":1,"third-to-last":1}
,"fields":{"valid":1,"used":1,"examples":1,"character":1,"example":1,"follows":1,"allowed":1,"notes":1}
,"valid":{"values":1}
,"values":{"specified":1,"fairly":1,"hours":1,"using":1,"=sunday)":1,"example":1,"you\u0027ll":1,"allowed":1,"within":1}
,"fairly":{"obvious":1}
,"obvious":{"-such":1}
,"-such":{"numbers":1}
,"numbers":{"seconds":1}
,"1-31":{"need":1,"-*?":1}
,"careful":{"days":1,"setting":1}
,"days":{"given":1,"monday":1,"starting":1,"character":1,"characters":1,"week":1,"every":1}
,"given":{"month":1,"day":1,"day-of-week":1}
,"months":{"specified":1,"days":1}
,"using":{"strings":1,"option":1,"triggerbuilder":1}
,"jan":{"feb":1,"mar":1}
,"feb":{"mar":1}
,"mar":{"apr":1,"sep":1}
,"apr":{"may":1}
,"may":{"jun":1,"find":1}
,"jun":{"jul":1}
,"jul":{"aug":1}
,"aug":{"sep":1}
,"sep":{"oct":1,"mon-fri":1}
,"oct":{"nov":1}
,"nov":{"dec":1}
,"dec":{"days-of-week":1}
,"days-of-week":{"specified":1}
,"=sunday)":{"using":1}
,"sun":{"mon":1}
,"tue":{"wed":1}
,"thu":{"fri":1}
,"increments":{"values":1,"example":1}
,"put":{"0\u002F15":1,"day-of-month":1}
,"0\u002F15":{"minutes":1,"seconds":1}
,"\u0027every":{"15th":1,"20th":1}
,"15th":{"minute":1,"month":1,"saturday":1,"sunday":1,"tuesday":1,"however":1,"day":1}
,"minute":{"hour":1,"zero":1,"three":1,"field":1,"specific":1,"starting":1,"8am":1}
,"hour":{"starting":1,"field":1,"2:00":1}
,"starting":{"minute":1,"first":1,"2pm":1,"6pm":1}
,"zero":{"used":1,"-or":1}
,"3\u002F20":{"minutes":1}
,"20th":{"minute":1}
,"three":{"-or":1}
,"-or":{"words":1}
,"words":{"specifying":1}
,"specifying":{"3,23,43":1,"0,35":1,"day-of-week":1}
,"3,23,43":{"minutes":1}
,"note":{"subtlety":1,"specify":1}
,"subtlety":{"\u0022\u002F35":1}
,"\u0022\u002F35":{"not*mean":1}
,"not*mean":{"every":1}
,"-it":{"means":1}
,"35th":{"minute":1}
,"0,35":{"character":1}
,"allowed":{"day-of-month":1,"values":1,"special":1,"example":1}
,"specific":{"value":1}
,"something":{"two":1}
,"two":{"fields":1}
,"examples":{"below":1,"=the":1,"full":1,"expression":1}
,"below":{"(and":1,"clarification":1}
,"(and":{"crontrigger":1}
,"javadoc)":{"clarification":1}
,"clarification":{"character":1,"--used":1}
,"short-hand":{"last":1}
,"different":{"meaning":1}
,"meaning":{"two":1,"nearest":1,"**?":1}
,"-day":{"january":1}
,"february":{"non-leap":1}
,"non-leap":{"years":1}
,"years":{"used":1,"2002":1}
,"itself":{"simply":1,"(including":1}
,"xxx":{"day":1,"weekday":1}
,"-for":{"example":1}
,"fril":{"mean":1}
,"offset":{"last":1}
,"l-3":{"mean":1}
,"third-to-last":{"day":1}
,"calendar":{"month":1}
,"option":{"important":1}
,"important":{"specify":1}
,"you\u0027ll":{"confusing\u002Funexpected":1}
,"confusing\u002Funexpected":{"results":1}
,"results":{"used":1,"weekday":1}
,"(monday-friday)":{"nearest":1}
,"nearest":{"given":1,"weekday":1}
,"15w":{"value":1}
,"nth":{"xxx":1}
,"third":{"friday":1}
,"format":{"fields":1}
,"follows":{"field":1}
,"name":{"mandatory":1}
,"mandatory":{"allowed":1}
,"special":{"characters":1}
,"characters":{"seconds":1,"*(all":1,"combined":1,"names":1}
,"0-59":{"-*minutes":1,"-*hours":1}
,"-*minutes":{"0-59":1}
,"-*hours":{"0-23":1}
,"0-23":{"-*day":1}
,"-*day":{"month":1,"week":1}
,"-*?":{"month":1,"year":1}
,"1-12":{"jan-dec":1}
,"jan-dec":{"-*day":1}
,"1-7":{"sun-sat":1}
,"sun-sat":{"-*?":1}
,"empty":{"1970-2099":1}
,"1970-2099":{"-*so":1}
,"-*so":{"cron":1}
,"simple":{"****?":1,"schedule":1}
,"****?":{"*or":1}
,"*or":{"complex":1}
,"complex":{"0\u002F5":1}
,"0\u002F5":{"14,18,3-39,52":1,"**?":1,"14,18":1}
,"14,18,3-39,52":{"jan":1}
,"2002-2010":{"special":1}
,"*(all":{"values)":1}
,"values)":{"-used":1}
,"-used":{"select":1,"specify":1}
,"select":{"values":1}
,"within":{"field":1}
,"\u0022*\u0022":{"minute":1}
,"-useful":{"need":1}
,"want":{"trigger":1}
,"trigger":{"fire":1,"=newtrigger":1,"types":1}
,"fire":{"particular":1,"every":1,"friday":1,"monday":1,"tuesday":1,"12pm":1,"10:15am":1,"2:10pm":1,"times":1,"daily":1,"wednesdays":1}
,"particular":{"day":1}
,"(say":{"10th)":1}
,"10th)":{"don\u0027t":1}
,"don\u0027t":{"care":1}
,"care":{"day":1}
,"happens":{"put":1}
,"--used":{"specify":1}
,"10-12":{"hour":1}
,"additional":{"values":1}
,"\u002F-used":{"specify":1}
,"5\u002F15":{"seconds":1}
,"-in":{"case":1}
,"case":{"equivalent":1,"sensitive":1}
,"equivalent":{"having":1}
,"having":{"1\u002F3":1}
,"1\u002F3":{"day-of-month":1}
,"first":{"day":1,"monday":1}
,"-has":{"different":1}
,"saturday":{"trigger":1}
,"14th":{"15th":1}
,"sunday":{"trigger":1}
,"16th":{"15th":1}
,"tuesday":{"fire":1,"15th":1,"wednesday":1}
,"however":{"specify":1}
,"1st":{"saturday":1}
,"3rd":{"\u0027jump":1,"month)":1}
,"\u0027jump":{"boundary":1}
,"boundary":{"month\u0027s":1}
,"month\u0027s":{"days":1}
,"single":{"day":1}
,"range":{"list":1}
,"list":{"days":1}
,"combined":{"day-of-month":1}
,"yield":{"\u0027lw":1}
,"\u0027lw":{"translates":1}
,"translates":{"last":1}
,"(day":{"=friday":1}
,"=friday":{"=the":1}
,"=the":{"3rd":1,"first":1,"fifth":1}
,"month)":{"examples":1}
,"fifth":{"wednesday":1}
,"occur":{"month":1,"locale":1}
,"legal":{"characters":1}
,"names":{"months":1}
,"sensitive":{"mon":1}
,"full":{"examples":1}
,"expression":{"meaning":1}
,"**?":{"fire":1,"*fire":1,"2005":1,"\u0022))":1,".withmisfirehandlinginstructionfireandproceed":1}
,"12pm":{"(noon)":1}
,"(noon)":{"every":1}
,"**fire":{"10:15am":1}
,"10:15am":{"every":1,"15th":1,"last":1,"2nd-to-last":1,"third":1}
,"*fire":{"10:15am":1}
,"2005":{"fire":1,"*14":1}
,"*14":{"**?":1}
,"2pm":{"ending":1}
,"ending":{"2:59pm":1,"2:55pm":1,"6:55pm":1,"2:05pm":1}
,"2:59pm":{"every":1}
,"2:55pm":{"every":1,"fire":1}
,"14,18":{"**?":1}
,"6pm":{"ending":1}
,"6:55pm":{"every":1}
,"0-5":{"**?":1}
,"2:05pm":{"every":1}
,"10,44":{"wed":1}
,"2:10pm":{"2:44pm":1}
,"2:44pm":{"every":1}
,"march":{"*mon-fri":1}
,"*mon-fri":{"fire":1}
,"thursday":{"friday":1}
,"l-2":{"fire":1}
,"2nd-to-last":{"day":1}
,"*6l":{"fire":1,"2002-2005":1}
,"2002-2005":{"fire":1}
,"2002":{"2003":1}
,"2003":{"2004":1}
,"2004":{"2005":1}
,"1\u002F5":{"fire":1}
,"november":{"11th":1}
,"11th":{"11:11am":1}
,"11:11am":{"pay":1}
,"pay":{"attention":1}
,"attention":{"effects":1}
,"effects":{"day-of-week":1}
,"notes":{"support":1}
,"support":{"specifying":1}
,"(you":{"currently":1}
,"currently":{"character":1}
,"fields)":{"careful":1}
,"setting":{"fire":1}
,"times":{"hours":1}
,"morning":{"daylight":1}
,"daylight":{"savings":1}
,"savings":{"changes":1}
,"changes":{"occur":1}
,"locale":{"(for":1,"https:\u002F\u002Fsecure.wikimedia.org\u002Fwikipedia\u002Fen\u002Fwiki\u002Fdaylight_saving_time_around_the_world":1}
,"(for":{"locales":1,"trigger\u0027s":1,"crontrigger-specific":1}
,"locales":{"typically":1}
,"typically":{"hour":1}
,"2:00":{"-because":1}
,"-because":{"time":1}
,"shift":{"cause":1}
,"cause":{"skip":1}
,"skip":{"repeat":1}
,"repeat":{"depending":1}
,"depending":{"whether":1}
,"whether":{"time":1}
,"moves":{"back":1}
,"back":{"jumps":1}
,"jumps":{"forward":1}
,"forward":{"may":1}
,"find":{"wikipedia":1}
,"wikipedia":{"entry":1}
,"entry":{"helpful":1}
,"helpful":{"determining":1}
,"determining":{"specifics":1}
,"specifics":{"locale":1}
,"https:\u002F\u002Fsecure.wikimedia.org\u002Fwikipedia\u002Fen\u002Fwiki\u002Fdaylight_saving_time_around_the_world":{"building":1}
,"building":{"crontriggers":1}
,"built":{"using":1}
,"triggerbuilder":{"(for":1}
,"trigger\u0027s":{"main":1}
,"main":{"properties)":1}
,"properties)":{"cronschedulebuilder":1,"builders":1}
,"cronschedulebuilder":{"(for":1}
,"crontrigger-specific":{"properties)":1}
,"builders":{"dsl-style":1}
,"dsl-style":{"static":1}
,"static":{"imports":1,"org.quartz.triggerbuilder.*":1,"org.quartz.cronschedulebuilder.*":1,"org.quartz.datebuilder.*":1}
,"imports":{"import":1}
,"import":{"static":1}
,"org.quartz.triggerbuilder.*":{"import":1}
,"org.quartz.cronschedulebuilder.*":{"import":1}
,"org.quartz.datebuilder.*":{"build":1}
,"build":{"trigger":1}
,"8am":{"5pm":1}
,"5pm":{"every":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"trigger3":1}
,"trigger3":{"group1":1}
,"group1":{".withschedule":1,".build":1}
,".withschedule":{"(cronschedule":1,"(dailyathourandminute":1,"(weeklyondayandhourandminute":1}
,"(cronschedule":{"0\u002F2":1,"**?":1,"*wed":1}
,"0\u002F2":{"8-17":1}
,"8-17":{"**?":1}
,"\u0022))":{".forjob":1,".build":1,".intimezone":1}
,".forjob":{"myjob":1,"(myjobkey)":1}
,"myjob":{"group1":1}
,".build":{"build":1,"-trigger":1,"crontrigger":1}
,"daily":{"10:42":1}
,"10:42":{"trigger":1,"timezone":1}
,"(dailyathourandminute":{"(10":1}
,"(10":{"42))":1}
,"42))":{".forjob":1}
,"(myjobkey)":{".build":1,".intimezone":1}
,"-trigger":{"=newtrigger":1}
,"wednesdays":{"10:42":1}
,"timezone":{"system\u0027s":1}
,"system\u0027s":{"default":1}
,"default":{"trigger":1}
,"(weeklyondayandhourandminute":{"(datebuilder.wednesday":1}
,"(datebuilder.wednesday":{"42))":1}
,".intimezone":{"(timezone.gettimezone":1}
,"(timezone.gettimezone":{"america\u002Flos_angeles":1}
,"america\u002Flos_angeles":{"\u0022))":1}
,"*wed":{"\u0022))":1}
,"misfire":{"instructions":1,"occurs":1,"instruction":1}
,"instructions":{"following":1,"used":1,"defined":1,"include":1}
,"following":{"instructions":1}
,"inform":{"quartz":1}
,"quartz":{"misfire":1}
,"occurs":{"crontrigger":1}
,"(misfire":{"situations":1}
,"situations":{"introduced":1}
,"introduced":{"triggers":1}
,"triggers":{"section":1,"misfire_instruction_smart_policy":1}
,"section":{"tutorial)":1}
,"tutorial)":{"instructions":1}
,"defined":{"constants":1}
,"constants":{"crontrigger":1}
,"(including":{"javadoc":1}
,"javadoc":{"describing":1,"crontrigger.updateaftermisfire":1}
,"describing":{"behavior)":1}
,"behavior)":{"instructions":1}
,"include":{"misfire_instruction_ignore_misfire_policy":1}
,"misfire_instruction_ignore_misfire_policy":{"misfire_instruction_do_nothing":1}
,"misfire_instruction_do_nothing":{"misfire_instruction_fire_now":1}
,"misfire_instruction_fire_now":{"triggers":1,"javadoc":1}
,"misfire_instruction_smart_policy":{"instruction":1}
,"instruction":{"available":1,"default":1,"interpreted":1,"part":1}
,"available":{"instruction":1}
,"types":{"\u0027smart":1}
,"\u0027smart":{"policy":1}
,"policy":{"instruction":1}
,"interpreted":{"crontrigger":1}
,"crontrigger.updateaftermisfire":{"method":1}
,"method":{"explains":1}
,"explains":{"exact":1}
,"exact":{"details":1}
,"behavior":{"building":1}
,"part":{"simple":1}
,"(via":{"cronschedulerbuilder)":1}
,"cronschedulerbuilder)":{"trigger":1}
,".withmisfirehandlinginstructionfireandproceed":{"())":1}
,"())":{".forjob":1}
}
;Search.control.loadWordPairs(pairs);
