var pairs =
{
"jdbcjobstore":{"jdbcjobstore":1,"keeps":1,"works":1,"first":1,"prefix":1,"connections":1,"jndi":1,"(and":1,"following":1,"driverdelegate":1,"table":1,"values":1}
,"keeps":{"data":1}
,"data":{"database":1}
,"database":{"via":1,"bit":1,"tables":1,"used":1,"type":1,"once":1,"datasources":1,"approach":1,"stdjdbcdelegate":1,"try":1}
,"via":{"jdbc":1}
,"jdbc":{"uses":1,"work":1,"code":1,"drivers":1}
,"uses":{"database":1,"vanilla":1}
,"bit":{"complicated":1}
,"complicated":{"configure":1}
,"configure":{"ramjobstore":1,"jobstoretx":1,"jdbcjobstore":1}
,"ramjobstore":{"fast":1}
,"fast":{"however":1}
,"however":{"performance":1}
,"performance":{"draw-back":1}
,"draw-back":{"terribly":1}
,"terribly":{"bad":1}
,"bad":{"especially":1}
,"especially":{"build":1}
,"build":{"database":1}
,"tables":{"indexes":1,"quartz":1,"start":1,"qrtz_triggers":1,"multiple":1,"need":1}
,"indexes":{"primary":1}
,"primary":{"keys":1}
,"keys":{"fairly":1}
,"fairly":{"modern":1}
,"modern":{"machines":1}
,"machines":{"decent":1}
,"decent":{"lan":1}
,"lan":{"(between":1}
,"(between":{"scheduler":1}
,"scheduler":{"database)":1,"instances":1,"busy":1}
,"database)":{"time":1}
,"time":{"retrieve":1}
,"retrieve":{"update":1}
,"update":{"firing":1}
,"firing":{"trigger":1}
,"trigger":{"typically":1}
,"typically":{"less":1}
,"less":{"milliseconds":1}
,"milliseconds":{"jdbcjobstore":1}
,"works":{"nearly":1}
,"nearly":{"database":1,"always":1}
,"used":{"widely":1,"jobstore":1}
,"widely":{"oracle":1}
,"oracle":{"postgresql":1}
,"postgresql":{"mysql":1}
,"mysql":{"sqlserver":1}
,"sqlserver":{"hsqldb":1}
,"hsqldb":{"db2":1}
,"db2":{"jdbcjobstore":1,"version":1}
,"first":{"create":1,"need":1}
,"create":{"database":1,"manage":1}
,"quartz":{"find":1,"distribution":1,"properties)":1,"manage":1,"work":1,"app":1,"properties":1,"create":1,"datasource":1,"running":1,"configuration":1,"provides":1}
,"find":{"table-creation":1}
,"table-creation":{"sql":1}
,"sql":{"scripts":1,"statements)":1}
,"scripts":{"docs\u002Fdbtables":1,"tables":1}
,"docs\u002Fdbtables":{"directory":1}
,"directory":{"quartz":1}
,"distribution":{"already":1}
,"already":{"script":1}
,"script":{"database":1}
,"type":{"just":1,"transactions":1}
,"just":{"look":1}
,"look":{"existing":1}
,"existing":{"ones":1}
,"ones":{"modify":1}
,"modify":{"necessary":1}
,"necessary":{"note":1}
,"note":{"scripts":1}
,"start":{"prefix":1}
,"prefix":{"qrtz_\u0022":1,"actually":1,"(in":1,"(discussed":1,"org.quartz.jobstore.tableprefix":1}
,"qrtz_\u0022":{"(such":1}
,"(such":{"tables":1,"adding":1}
,"qrtz_triggers":{"qrtz_job_detail":1}
,"qrtz_job_detail":{"prefix":1}
,"actually":{"anything":1}
,"anything":{"you\u0027d":1}
,"you\u0027d":{"long":1}
,"long":{"inform":1,"term":1}
,"inform":{"jdbcjobstore":1,"jobstore":1}
,"(in":{"quartz":1}
,"properties)":{"using":1,"org.quartz.jobstore.datasource":1}
,"using":{"different":1,"jobstoretx":1,"several":1,"stdschedulerfactory)":1,"delegate":1,"jdbc":1,"oracle)":1,"following":1}
,"different":{"prefixes":1}
,"prefixes":{"may":1}
,"may":{"useful":1,"needed":1}
,"useful":{"creating":1}
,"creating":{"multiple":1}
,"multiple":{"sets":1,"scheduler":1}
,"sets":{"tables":1}
,"instances":{"within":1}
,"within":{"database":1,"j2ee":1,"quartz":1}
,"once":{"created":1,"you\u0027ve":1}
,"created":{"tables":1}
,"need":{"decide":1,"tie":1,"quartz":1,"jobstore":1,"select":1,"inform":1,"datasource":1}
,"decide":{"type":1}
,"transactions":{"application":1,"quartz":1,"(for":1,"lastly":1}
,"application":{"needs":1,"server)":1,"server":1}
,"needs":{"don\u0027t":1}
,"don\u0027t":{"need":1}
,"tie":{"scheduling":1}
,"scheduling":{"commands":1}
,"commands":{"(such":1}
,"adding":{"removing":1}
,"removing":{"triggers)":1}
,"triggers)":{"transactions":1}
,"manage":{"transaction":1,"transactions":1,"datasource":1}
,"transaction":{"using":1}
,"jobstoretx":{"jobstore":1,"org.quartz.jobstore.class":1}
,"jobstore":{"(this":1,"class":1,"driverdelegate":1,"table":1,"named":1}
,"(this":{"common":1}
,"common":{"selection)":1}
,"selection)":{"need":1}
,"work":{"along":1,"may":1,"isn\u0027t":1}
,"along":{"transactions":1}
,"(for":{"example":1,"db2":1,"hsqldb)":1,"microsoft":1,"postgresql)":1,"using":1}
,"example":{"within":1,"config":1,"shows":1}
,"j2ee":{"application":1}
,"server)":{"jobstorecmt":1}
,"jobstorecmt":{"case":1}
,"case":{"quartz":1,"we\u0027re":1}
,"app":{"server":1}
,"server":{"container":1,"within":1}
,"container":{"manage":1}
,"lastly":{"datasource":1}
,"datasource":{"jdbcjobstore":1,"itself":1,"managed":1,"details":1,"used":1,"defined":1,"name":1,"size":1}
,"connections":{"database":1,"datasource":1}
,"datasources":{"defined":1}
,"defined":{"quartz":1,"elsewhere":1}
,"properties":{"using":1,"consult":1,"case":1}
,"several":{"approaches":1}
,"approaches":{"approach":1}
,"approach":{"quartz":1}
,"itself":{"providing":1}
,"providing":{"connection":1,"jdbcjobstore":1}
,"connection":{"information":1}
,"information":{"database":1}
,"managed":{"application":1}
,"running":{"providing":1}
,"jndi":{"name":1}
,"name":{"datasource":1,"delegate":1,"myds":1}
,"details":{"properties":1}
,"consult":{"example":1}
,"config":{"files":1,"parameter":1}
,"files":{"docs\u002Fconfig":1}
,"docs\u002Fconfig":{"folder":1}
,"folder":{"jdbcjobstore":1}
,"(and":{"assuming":1,"sql":1}
,"assuming":{"you\u0027re":1}
,"you\u0027re":{"using":1}
,"stdschedulerfactory)":{"first":1}
,"class":{"property":1,"name":1,"versioning":1}
,"property":{"quartz":1}
,"configuration":{"following":1,"properties)":1}
,"following":{"org.quartz.impl.jdbcjobstore.jobstoretx":1,"example":1}
,"org.quartz.impl.jdbcjobstore.jobstoretx":{"org.quartz.impl.jdbcjobstore.jobstorecmt":1}
,"org.quartz.impl.jdbcjobstore.jobstorecmt":{"choice":1}
,"choice":{"depends":1}
,"depends":{"selection":1}
,"selection":{"made":1}
,"made":{"based":1,"specifically":1,"weblogic)":1}
,"based":{"explanations":1}
,"explanations":{"above":1}
,"above":{"paragraphs":1}
,"paragraphs":{"following":1}
,"shows":{"configure":1}
,"org.quartz.jobstore.class":{"=org.quartz.impl.jdbcjobstore.jobstoretx":1}
,"=org.quartz.impl.jdbcjobstore.jobstoretx":{"next":1}
,"next":{"need":1}
,"select":{"driverdelegate":1}
,"driverdelegate":{"jobstore":1,"responsible":1,"org.quartz.jobstore.driverdelegateclass":1}
,"responsible":{"doing":1}
,"doing":{"jdbc":1}
,"needed":{"specific":1}
,"specific":{"database":1}
,"stdjdbcdelegate":{"delegate":1,"delegates":1}
,"delegate":{"uses":1,"made":1,"quartz":1,"class":1,"jdbcjobstore":1}
,"vanilla":{"jdbc":1}
,"code":{"(and":1}
,"statements)":{"work":1}
,"isn\u0027t":{"delegate":1}
,"specifically":{"database":1}
,"try":{"using":1}
,"provides":{"database-specific":1}
,"database-specific":{"delegates":1}
,"delegates":{"databases":1,"found":1,"include":1}
,"databases":{"operate":1}
,"operate":{"stdjdbcdelegate":1}
,"found":{"org.quartz.impl.jdbcjobstore":1}
,"org.quartz.impl.jdbcjobstore":{"package":1}
,"package":{"sub-packages":1}
,"sub-packages":{"delegates":1}
,"include":{"db2v6delegate":1}
,"db2v6delegate":{"(for":1}
,"version":{"earlier)":1}
,"earlier)":{"hsqldbdelegate":1}
,"hsqldbdelegate":{"(for":1}
,"hsqldb)":{"mssqldelegate":1}
,"mssqldelegate":{"(for":1}
,"microsoft":{"sqlserver)":1}
,"sqlserver)":{"postgresqldelegate":1}
,"postgresqldelegate":{"(for":1}
,"postgresql)":{"weblogicdelegate":1}
,"weblogicdelegate":{"(for":1}
,"drivers":{"made":1}
,"weblogic)":{"oracledelegate":1}
,"oracledelegate":{"(for":1}
,"oracle)":{"others":1}
,"others":{"once":1}
,"you\u0027ve":{"selected":1}
,"selected":{"delegate":1}
,"org.quartz.jobstore.driverdelegateclass":{"=org.quartz.impl.jdbcjobstore.stdjdbcdelegate":1}
,"=org.quartz.impl.jdbcjobstore.stdjdbcdelegate":{"next":1}
,"table":{"prefix":1}
,"(discussed":{"above)":1}
,"above)":{"using":1}
,"org.quartz.jobstore.tableprefix":{"=qrtz_and":1}
,"=qrtz_and":{"finally":1}
,"finally":{"need":1}
,"named":{"datasource":1}
,"we\u0027re":{"specifying":1}
,"specifying":{"quartz":1}
,"myds":{"(that":1}
,"(that":{"defined":1}
,"elsewhere":{"configuration":1}
,"org.quartz.jobstore.datasource":{"=myds":1}
,"=myds":{"scheduler":1}
,"busy":{"meaning":1}
,"meaning":{"nearly":1}
,"always":{"executing":1}
,"executing":{"number":1}
,"number":{"jobs":1,"connections":1}
,"jobs":{"size":1}
,"size":{"thread":1}
,"thread":{"pool":1}
,"pool":{"probably":1,"org.quartz.jobstore.useproperties":1}
,"probably":{"number":1}
,"org.quartz.jobstore.useproperties":{"config":1}
,"parameter":{"true":1}
,"true":{"(it":1}
,"(it":{"defaults":1}
,"defaults":{"false)":1}
,"false)":{"order":1}
,"order":{"instruct":1}
,"instruct":{"jdbcjobstore":1}
,"values":{"jobdatamaps":1}
,"jobdatamaps":{"strings":1}
,"strings":{"therefore":1}
,"therefore":{"stored":1}
,"stored":{"name-value":1}
,"name-value":{"pairs":1}
,"pairs":{"rather":1}
,"rather":{"storing":1}
,"storing":{"complex":1}
,"complex":{"objects":1}
,"objects":{"serialized":1}
,"serialized":{"form":1}
,"form":{"blob":1}
,"blob":{"column":1}
,"column":{"safer":1}
,"safer":{"long":1}
,"term":{"avoid":1}
,"avoid":{"class":1}
,"versioning":{"issues":1}
,"issues":{"serializing":1}
,"serializing":{"non-string":1}
,"non-string":{"classes":1}
,"classes":{"blob":1}
}
;Search.control.loadWordPairs(pairs);
