var pairs =
{
"how-to":{"scheduler":1}
,"scheduler":{"listeners":1,"scheduler.getlistenermanager":1}
,"listeners":{"creating":1}
,"creating":{"schedulerlistener":1}
,"schedulerlistener":{"extend":1,"scheduler":1}
,"extend":{"triggerlistenersupport":1}
,"triggerlistenersupport":{"override":1}
,"override":{"methods":1}
,"methods":{"events":1}
,"events":{"interested":1}
,"interested":{"package":1}
,"package":{"foo":1}
,"foo":{"import":1}
,"import":{"org.quartz.trigger":1,"org.quartz.listeners.schedulerlistenersupport":1}
,"org.quartz.trigger":{"import":1}
,"org.quartz.listeners.schedulerlistenersupport":{"public":1}
,"public":{"class":1,"void":1}
,"class":{"myotherschedulerlistener":1}
,"myotherschedulerlistener":{"extends":1}
,"extends":{"schedulerlistenersupport":1}
,"schedulerlistenersupport":{"{@override":1}
,"{@override":{"public":1}
,"void":{"schedulerstarted":1,"schedulershutdown":1,"jobscheduled":1}
,"schedulerstarted":{"{\u002F\u002Fdo":1}
,"{\u002F\u002Fdo":{"something":1}
,"something":{"event":1}
,"event":{"@override":1,"registering":1}
,"@override":{"public":1}
,"schedulershutdown":{"{\u002F\u002Fdo":1}
,"jobscheduled":{"(trigger":1}
,"(trigger":{"trigger)":1}
,"trigger)":{"{\u002F\u002Fdo":1}
,"registering":{"schedulerlistener":1}
,"scheduler.getlistenermanager":{".addschedulerlistener":1}
,".addschedulerlistener":{"(myschedlistener)":1}
}
;Search.control.loadWordPairs(pairs);
