var pairs =
{
"jobdatamap":{"tips":1,"store":1,"avoid":1,"jobdatamap":1,"found":1,"values":1}
,"tips":{"store":1}
,"store":{"primitive":1}
,"primitive":{"data":1}
,"data":{"types":1,"serialization":1,"inputs":1}
,"types":{"(including":1}
,"(including":{"strings)":1}
,"strings)":{"jobdatamap":1}
,"avoid":{"data":1}
,"serialization":{"issues":1}
,"issues":{"short":1}
,"short":{"long-term":1}
,"long-term":{"merged":1}
,"merged":{"jobdatamap":1}
,"found":{"jobexecutioncontext":1,"jobdetail":1,"trigger":1}
,"jobexecutioncontext":{"during":1,"rather":1}
,"during":{"job":1}
,"job":{"execution":1,"stored":1,"different":1}
,"execution":{"serves":1}
,"serves":{"convenience":1}
,"convenience":{"merge":1}
,"merge":{"jobdatamap":1}
,"jobdetail":{"found":1}
,"trigger":{"value":1,"useful":1}
,"value":{"latter":1}
,"latter":{"overriding":1}
,"overriding":{"same-named":1}
,"same-named":{"values":1}
,"values":{"former":1,"trigger":1,"jobdatamap":1}
,"former":{"storing":1}
,"storing":{"jobdatamap":1}
,"useful":{"case":1}
,"case":{"job":1}
,"stored":{"scheduler":1}
,"scheduler":{"regular\u002Frepeated":1}
,"regular\u002Frepeated":{"multiple":1}
,"multiple":{"triggers":1}
,"triggers":{"independent":1}
,"independent":{"triggering":1}
,"triggering":{"want":1}
,"want":{"supply":1}
,"supply":{"job":1}
,"different":{"data":1}
,"inputs":{"best":1}
,"best":{"practice":1}
,"practice":{"code":1}
,"code":{"within":1}
,"within":{"job.execute":1}
,"job.execute":{"method":1}
,"method":{"generally":1}
,"generally":{"retrieve":1}
,"retrieve":{"values":1}
,"rather":{"directly":1}
,"directly":{"jobdetail":1}
}
;Search.control.loadWordPairs(pairs);
