var pairs =
{
"sample":{"code":1}
,"code":{"quartz":1,"snippet":1}
,"quartz":{"scheduler":1}
,"scheduler":{"example":1,"following":1,"scheduler":1,"instances":1,"create":1,"fluent":1,"constraints":1}
,"example":{"cluster":1,"showed":1,"trigger2":1}
,"cluster":{"terracotta":1,"example":1}
,"terracotta":{"clients":1}
,"clients":{"running":1}
,"running":{"quartz":1,"linux":1}
,"following":{"hosts":1,"properties":1,"configuration":1,"code":1,"trigger":1,"job":1,"assumes":1}
,"hosts":{"node0":1}
,"node0":{"node1":1}
,"node1":{"node2":1}
,"node2":{"node3":1,"org.quartz.locality.nodegroup.allnodes":1}
,"node3":{"hostnames":1,"org.quartz.locality.nodegroup.fastjobs":1,"org.quartz.locality.nodegroup.slowjobs.triggergroups":1}
,"hostnames":{"used":1,"instance":1}
,"used":{"instance":1,"route":1}
,"instance":{"ids":1}
,"ids":{"quartz":1,"org.quartz.scheduler.instanceidgenerator.class":1}
,"instances":{"following":1}
,"properties":{"quartz.properties":1,"quartzlocality.properties":1}
,"quartz.properties":{"shown":1}
,"shown":{"org.quartz.scheduler.instanceid":1}
,"org.quartz.scheduler.instanceid":{"=auto":1}
,"=auto":{"sets":1}
,"sets":{"hostnames":1,"job":1}
,"org.quartz.scheduler.instanceidgenerator.class":{"=org.quartz.simpl.hostnameinstanceidgenerator":1}
,"=org.quartz.simpl.hostnameinstanceidgenerator":{"setting":1}
,"setting":{"quartzlocality":1,"threshold":1}
,"quartzlocality":{"properties":1}
,"quartzlocality.properties":{"following":1}
,"configuration":{"org.quartz.locality.nodegroup.slowjobs":1}
,"org.quartz.locality.nodegroup.slowjobs":{"=node0":1}
,"=node0":{"node3":1,"node1":1}
,"org.quartz.locality.nodegroup.fastjobs":{"=node1":1}
,"=node1":{"node2":1}
,"org.quartz.locality.nodegroup.allnodes":{"=node0":1}
,"org.quartz.locality.nodegroup.slowjobs.triggergroups":{"=slowtriggers":1}
,"=slowtriggers":{"org.quartz.locality.nodegroup.fastjobs.triggergroups":1}
,"org.quartz.locality.nodegroup.fastjobs.triggergroups":{"=fasttriggers":1}
,"=fasttriggers":{"creating":1}
,"creating":{"locality-aware":1}
,"locality-aware":{"jobs":1,"job":1,"trigger":1,"triggers":1}
,"jobs":{"triggers":1,"fired":1,"conflicting":1,"machines":1,"example":1}
,"triggers":{"following":1,"\u002F\u002Fnote":1,"jobs":1,"priority":1}
,"snippet":{"uses":1}
,"uses":{"quartz":1}
,"create":{"locality-aware":1}
,"\u002F\u002Fnote":{"static":1}
,"static":{"imports":1,"org.quartz.jobbuilder.newjob":1,"org.quartz.triggerbuilder.newtrigger":1,"org.quartz.locality.localitytriggerbuilder.localtrigger":1,"org.quartz.locality.nodespecbuilder.node":1,"org.quartz.locality.constraint.nodegroupconstraint.partofnodegroup":1,"org.quartz.locality.constraint.cpuconstraint.loadatmost":1}
,"imports":{"builder":1,"\u002F\u002Fusing":1}
,"builder":{"classes":1}
,"classes":{"define":1}
,"define":{"domain":1}
,"domain":{"specific":1}
,"specific":{"language":1,"group":1}
,"language":{"(dsl)":1}
,"(dsl)":{"import":1}
,"import":{"static":1,"org.quartz.jobdetail":1,"org.quartz.locality.localitytrigger":1}
,"org.quartz.jobbuilder.newjob":{"import":1}
,"org.quartz.triggerbuilder.newtrigger":{"import":1}
,"org.quartz.locality.localitytriggerbuilder.localtrigger":{"import":1}
,"org.quartz.locality.nodespecbuilder.node":{"import":1}
,"org.quartz.locality.constraint.nodegroupconstraint.partofnodegroup":{"import":1}
,"org.quartz.jobdetail":{"import":1}
,"org.quartz.locality.localitytrigger":{"\u002F\u002Fother":1}
,"\u002F\u002Fother":{"required":1}
,"required":{"imports":1}
,"\u002F\u002Fusing":{"quartz":1}
,"fluent":{"interface":1}
,"interface":{"dsl":1}
,"dsl":{"\u002F*****node":1}
,"\u002F*****node":{"group":1}
,"group":{"constraint":1,"that\u0027s":1,"allnodes":1}
,"constraint":{"create":1,"based":1,"myjob1":1,"override":1,"allows":1,"refers":1}
,"job":{"run":1,"jobdetail":1,"following":1,"detail":1,"(cachejob)":1,"work":1,"met":1,"fired":1,"immediately":1}
,"run":{"node":1,"jobs":1}
,"node":{"nodegroup":1,"certain":1,"allnodes":1,"mycache":1,"minimum":1,"trigger":1,"specific":1}
,"nodegroup":{"group1":1}
,"group1":{"runs":1,"\u0022))":1}
,"runs":{"linux":1}
,"linux":{"*****\u002Flocalityjobdetail":1,"*****\u002Flocalitytrigger":1}
,"*****\u002Flocalityjobdetail":{"jobdetail1":1}
,"jobdetail1":{"=localjob":1}
,"=localjob":{"(newjob":1}
,"(newjob":{"(myjob1.class)":1,"(cachejob.class)":1}
,"(myjob1.class)":{".withidentity":1}
,".withidentity":{"myjob1":1,"mytrigger1":1,"myjob2":1,"mytrigger2":1,"mytrigger3":1,"cachejob":1,"sometrigger":1}
,"myjob1":{".storedurably":1,"trigger":1,".withidentity":1,"node":1,"triggers":1,"constraints":1}
,".storedurably":{"(true)":1}
,"(true)":{".build":1}
,".build":{"())":1,"\u002F\u002Fcreate":1,"\u002F*****memory":1,"\u002F*****a":1,"\u002F*****locality":1,"notice":1,"load":1}
,"())":{".where":1}
,".where":{"(node":1}
,"(node":{".is":1,"\u002F\u002Ffire":1,".has":1}
,".is":{"(partofnodegroup":1,"(osconstraint.linux))":1}
,"(partofnodegroup":{"group1":1,"allnodes":1}
,"\u0022))":{".is":1,".where":1,".has":1}
,"(osconstraint.linux))":{".build":1}
,"\u002F\u002Fcreate":{"trigger":1,"second":1,"job":1,"locality-aware":1}
,"trigger":{"myjob1":1,"trigger1":1,"myjob2":1,"existing":1,"fire":1,"defined":1,"job":1,"error":1,"somejob":1,"=localtrigger":1,"cannot":1}
,"trigger1":{"=newtrigger":1}
,"=newtrigger":{".forjob":1}
,".forjob":{"myjob1":1,"myjob2":1,"somejob":1}
,"mytrigger1":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(10)":1}
,"(10)":{".withrepeatcount":1}
,".withrepeatcount":{"(2))":1}
,"(2))":{".build":1}
,"second":{"job":1}
,"jobdetail":{"jobdetail2":1}
,"jobdetail2":{"=newjob":1}
,"=newjob":{"(myjob2.class)":1}
,"(myjob2.class)":{".withidentity":1}
,"myjob2":{".storedurably":1,"fire":1,".withidentity":1,"node":1}
,"\u002F*****memory":{"constraint":1}
,"fire":{"node":1,"myjob1":1,"constraints":1,"myjob2":1}
,"certain":{"amount":1}
,"amount":{"free":1,"data":1}
,"free":{"memory":1}
,"memory":{"available":1,".is":1,"node-group":1,"constraint":1}
,"available":{"*****\u002Flocalitytrigger":1,"threads":1}
,"*****\u002Flocalitytrigger":{"trigger2":1,"trigger3":1}
,"trigger2":{"=localtrigger":1,"fire":1}
,"=localtrigger":{"(newtrigger":1}
,"(newtrigger":{".forjob":1}
,"mytrigger2":{"\u0022))":1}
,"\u002F\u002Ffire":{"node":1}
,"allnodes":{"\u002F\u002Fwith":1,"\u0022))":1,"group":1,"\u0022)))":1,"specified":1}
,"\u002F\u002Fwith":{"least":1,"specified":1}
,"least":{"100mb":1}
,"100mb":{"free":1}
,".has":{"(atleastavailable":1,"(elements":1,"(loadatmost":1}
,"(atleastavailable":{"(100":1}
,"(100":{"memoryconstraint.unit.mb)))":1}
,"memoryconstraint.unit.mb)))":{".build":1}
,"\u002F*****a":{"locality-aware":1}
,"existing":{"job":1}
,"that\u0027s":{"running":1}
,"trigger3":{"=localtrigger":1,"third":1,"provide":1}
,"mytrigger3":{"\u0022))":1}
,"\u0022)))":{".build":1}
,"\u002F*****locality":{"constraint":1}
,"based":{"cache":1,"operating":1}
,"cache":{"keys":1,"mycache":1}
,"keys":{"following":1,"specified":1,"elements":1,"<string>":1,"target":1}
,"detail":{"sets":1}
,"(cachejob)":{"fired":1}
,"fired":{"node":1,"frequently":1,"using":1}
,"mycache":{"locally":1,"=cachemanager.getehcache":1,"\u002F\u002Fa":1,"\u002F\u002Fcreate":1}
,"locally":{"keys":1}
,"specified":{"collection":1,"load":1,"minimum":1}
,"collection":{"mykeys":1,"needed":1}
,"mykeys":{"best":1,"=new":1,"keys":1}
,"best":{"match":1}
,"match":{"found":1}
,"found":{"missing":1,"cpu":1}
,"missing":{"elements":1}
,"elements":{"faulted":1,"targeted":1,"mycache":1,"localityjobdetail":1}
,"faulted":{"types":1,"performance":1}
,"types":{"jobs":1}
,"frequently":{"large":1}
,"large":{"amount":1}
,"data":{"often":1,"already":1}
,"often":{"faulted":1}
,"performance":{"degrade":1,"ensure":1}
,"degrade":{"maintain":1}
,"maintain":{"performance":1}
,"ensure":{"targeted":1}
,"targeted":{"data":1,"cachejob":1}
,"already":{"cached":1,"configured":1}
,"cached":{"*****\u002F\u002F\u002Fmycache":1}
,"*****\u002F\u002F\u002Fmycache":{"already":1}
,"configured":{"populated":1}
,"populated":{"distributed":1}
,"distributed":{"cache":1}
,"=cachemanager.getehcache":{"mycache":1}
,"\u002F\u002Fa":{"collection":1}
,"needed":{"hold":1}
,"hold":{"keys":1}
,"cachejob":{"\u002F\u002Fthe":1,".storedurably":1}
,"\u002F\u002Fthe":{"following":1}
,"assumes":{"string":1}
,"string":{"keys":1}
,"<string>":{"mykeys":1,"\u002F\u002Fpopulate":1}
,"=new":{"hashset":1}
,"hashset":{"<string>":1}
,"\u002F\u002Fpopulate":{"mykeys":1}
,"target":{"elements":1}
,"work":{"target":1}
,"localityjobdetail":{"cachejobdetail":1}
,"cachejobdetail":{"=localjob":1}
,"(cachejob.class)":{".withidentity":1}
,"(elements":{"(mycache":1}
,"(mycache":{"mykeys)))":1}
,"mykeys)))":{".build":1}
,"notice":{"trigger3":1}
,"third":{"trigger":1}
,"defined":{"overrode":1}
,"overrode":{"partofnodegroup":1}
,"partofnodegroup":{"constraint":1}
,"conflicting":{"constraints":1}
,"constraints":{"triggers":1,"effect":1,"cpu":1,"include":1,"cannot":1,"tested":1,"cluster":1,"used":1}
,"priority":{"however":1}
,"however":{"trigger3":1}
,"provide":{"constraint":1}
,"override":{"constraint":1}
,"effect":{"trigger":1}
,"met":{"trigger":1,"node":1}
,"error":{"state":1}
,"state":{"job":1,"applications":1}
,"using":{"cpu-based":1,"quartz":1}
,"cpu-based":{"constraints":1}
,"cpu":{"constraint":1,"load":1,"likely":1,"setting":1,"constraints":1,"cores":1}
,"allows":{"run":1}
,"machines":{"adequate":1}
,"adequate":{"processing":1}
,"processing":{"power":1}
,"power":{"import":1}
,"org.quartz.locality.constraint.cpuconstraint.loadatmost":{"\u002F\u002Fcreate":1}
,"somejob":{"localitytrigger":1,".withidentity":1}
,"localitytrigger":{"trigger":1}
,"sometrigger":{"\u0022))":1}
,"load":{".is":1,"constraint":1,"standard":1,"measurement)":1,"average":1,"freer":1}
,"(loadatmost":{"(.80)))":1}
,"(.80)))":{".build":1}
,"refers":{"cpu":1}
,"standard":{"*nix":1}
,"*nix":{"load":1}
,"measurement)":{"averaged":1}
,"averaged":{"last":1}
,"last":{"minute":1}
,"minute":{"load":1}
,"average":{"below":1}
,"below":{"1.00":1}
,"1.00":{"indicates":1}
,"indicates":{"cpu":1}
,"likely":{"execute":1}
,"execute":{"job":1}
,"immediately":{"smaller":1}
,"smaller":{"load":1}
,"freer":{"cpu":1}
,"threshold":{"low":1}
,"low":{"difficult":1}
,"difficult":{"match":1}
,"include":{"cpucontraint.coresatleast":1}
,"cpucontraint.coresatleast":{"(int":1}
,"(int":{"amount)":1}
,"amount)":{"specifies":1}
,"specifies":{"node":1}
,"minimum":{"number":1,"amount":1}
,"number":{"cpu":1,"available":1}
,"cores":{"cpuconstraint.threadsavailableatleast":1}
,"cpuconstraint.threadsavailableatleast":{"(int":1}
,"threads":{"trigger":1}
,"cannot":{"fire":1,"met":1}
,"applications":{"using":1}
,"tested":{"conditions":1}
,"conditions":{"simulate":1}
,"simulate":{"constraints":1}
,"showed":{"memory":1}
,"node-group":{"constraints":1}
,"route":{"locality-aware":1}
,"operating":{"system":1}
,"system":{"(linux":1}
,"(linux":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"apple":1}
,"apple":{"osx":1}
,"osx":{"oracle":1}
,"oracle":{"solaris)":1}
,"solaris)":{"available":1}
}
;Search.control.loadWordPairs(pairs);
