var pairs =
{
"daylight":{"savings":1}
,"savings":{"time":1}
,"time":{"tips":1,"specifics":1,"clock":1,"always":1,"repeat":1,"zones\u002Flocations":1,"following":1,"amount":1,"shifted":1}
,"tips":{"avoid":1}
,"avoid":{"scheduling":1}
,"scheduling":{"jobs":1,"united":1,"fire":1}
,"jobs":{"near":1}
,"near":{"transition":1}
,"transition":{"hours":1,"hour":1}
,"hours":{"daylight":1,"1:00":1}
,"specifics":{"transition":1,"time":1}
,"hour":{"amount":1}
,"amount":{"time":1,"adjustment":1}
,"clock":{"moves":1}
,"moves":{"forward":1}
,"forward":{"back":1}
,"back":{"varies":1}
,"varies":{"locale":1}
,"locale":{"https:\u002F\u002Fsecure.wikimedia.org\u002Fwikipedia\u002Fen\u002Fwiki\u002Fdaylight_saving_time_around_the_world":1,"trigger":1}
,"https:\u002F\u002Fsecure.wikimedia.org\u002Fwikipedia\u002Fen\u002Fwiki\u002Fdaylight_saving_time_around_the_world":{"simpletriggers":1}
,"simpletriggers":{"affected":1}
,"affected":{"daylight":1,"however":1}
,"always":{"fire":1}
,"fire":{"exact":1,"given":1,"times":1,"time":1}
,"exact":{"millisecond":1,"number":1,"amounts":1}
,"millisecond":{"time":1}
,"repeat":{"exact":1}
,"number":{"milliseconds":1}
,"milliseconds":{"apart":1}
,"apart":{"crontriggers":1}
,"crontriggers":{"fire":1}
,"given":{"hours\u002Fminutes\u002Fseconds":1}
,"hours\u002Fminutes\u002Fseconds":{"subject":1}
,"subject":{"oddities":1}
,"oddities":{"dst":1}
,"dst":{"transitions":1}
,"transitions":{"occur":1}
,"occur":{"example":1,"using":1,"twice":1,"thus":1}
,"example":{"possible":1}
,"possible":{"issues":1,"2:05":1,"again":1}
,"issues":{"scheduling":1}
,"united":{"states":1}
,"states":{"within":1}
,"within":{"time":1}
,"zones\u002Flocations":{"observe":1}
,"observe":{"daylight":1}
,"following":{"problems":1}
,"problems":{"may":1}
,"may":{"occur":1}
,"using":{"crontrigger":1}
,"crontrigger":{"scheduling":1,"possible":1}
,"times":{"during":1}
,"during":{"hours":1}
,"1:00":{"2:00":1}
,"2:00":{"1:05":1}
,"1:05":{"may":1}
,"twice":{"thus":1,"trigger":1}
,"thus":{"duplicate":1,"missed":1}
,"duplicate":{"firings":1}
,"firings":{"crontrigger":1}
,"2:05":{"may":1}
,"missed":{"firings":1}
,"again":{"specifics":1}
,"adjustment":{"varies":1}
,"trigger":{"types":1,"type":1}
,"types":{"based":1}
,"based":{"sliding":1}
,"sliding":{"along":1}
,"along":{"calendar":1}
,"calendar":{"(rather":1}
,"(rather":{"exact":1}
,"amounts":{"time)":1}
,"time)":{"calenderintervaltrigger":1}
,"calenderintervaltrigger":{"similarly":1}
,"similarly":{"affected":1}
,"however":{"rather":1}
,"rather":{"missing":1}
,"missing":{"firing":1}
,"firing":{"firing":1,"twice":1}
,"type":{"end":1}
,"end":{"having":1}
,"having":{"fire":1}
,"shifted":{"hour":1}
}
;Search.control.loadWordPairs(pairs);
