var pairs =
{
"terracottajobstore":{"terracottajobstore":1,"provides":1,"ran":1,"(and":1,"terracotta":1}
,"provides":{"means":1,"storage":1}
,"means":{"scaling":1,"database":1}
,"scaling":{"robustness":1}
,"robustness":{"without":1}
,"without":{"database":1}
,"database":{"means":1,"kept":1,"via":1}
,"kept":{"free":1}
,"free":{"load":1}
,"load":{"quartz":1}
,"quartz":{"instead":1,"configuration":1,"user":1}
,"instead":{"resources":1}
,"resources":{"saved":1}
,"saved":{"rest":1}
,"rest":{"application":1}
,"application":{"terracottajobstore":1,"restarts":1}
,"ran":{"clustered":1}
,"clustered":{"non-clustered":1}
,"non-clustered":{"either":1}
,"either":{"case":1}
,"case":{"provides":1}
,"storage":{"medium":1}
,"medium":{"job":1}
,"job":{"data":1}
,"data":{"persistent":1,"stored":1}
,"persistent":{"application":1}
,"restarts":{"data":1}
,"stored":{"terracotta":1}
,"terracotta":{"server":1,"quartz":1}
,"server":{"performance":1,"org.quartz.jobstore.class":1}
,"performance":{"better":1}
,"better":{"using":1}
,"using":{"database":1,"stdschedulerfactory)":1}
,"via":{"jdbcjobstore":1}
,"jdbcjobstore":{"(about":1}
,"(about":{"order":1}
,"order":{"magnitude":1}
,"magnitude":{"better)":1}
,"better)":{"fairly":1}
,"fairly":{"slower":1}
,"slower":{"ramjobstore":1}
,"ramjobstore":{"terracottajobstore":1}
,"(and":{"assuming":1}
,"assuming":{"you\u0027re":1}
,"you\u0027re":{"using":1}
,"stdschedulerfactory)":{"simply":1}
,"simply":{"org.quartz.jobstore.class":1}
,"org.quartz.jobstore.class":{"property":1,"=org.terracotta.quartz.terracottajobstore":1}
,"property":{"org.terracotta.quartz.terracottajobstore":1,"specify":1}
,"org.terracotta.quartz.terracottajobstore":{"quartz":1}
,"configuration":{"add":1}
,"add":{"extra":1}
,"extra":{"property":1}
,"specify":{"location":1}
,"location":{"terracotta":1}
,"=org.terracotta.quartz.terracottajobstore":{"org.quartz.jobstore.tcconfigurl":1}
,"org.quartz.jobstore.tcconfigurl":{"=localhost:9510":1}
,"=localhost:9510":{"information":1}
,"information":{"terracottajobstore":1}
,"user":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
