var pairs =
{
"quartz":{"features":1,"run":1,"instantiated":1,"application\u0027s":1,"includes":1,"participate":1,"manage":1,"provide":1,"keeping":1,"ships":1}
,"features":{"runtime":1,"provides":1,"rely":1}
,"runtime":{"environments":1}
,"environments":{"quartz":1}
,"run":{"embedded":1,"stand-alone":1,"given":1}
,"embedded":{"within":1}
,"within":{"free":1,"application":1,"registered":1,"scheduler":1,"enterprise":1,"jta":1}
,"free":{"standing":1}
,"standing":{"application":1}
,"application":{"quartz":1,"server":1}
,"instantiated":{"within":1,"cluster":1,"quartz":1}
,"server":{"(or":1}
,"(or":{"servlet":1}
,"servlet":{"container)":1}
,"container)":{"participate":1}
,"participate":{"transactions":1,"jta":1}
,"transactions":{"quartz":1,"via":1,"(begin":1}
,"stand-alone":{"program":1,"programs":1}
,"program":{"(within":1,"executions":1}
,"(within":{"java":1}
,"java":{"virtual":1,"environment":1,"class":1,"objects":1}
,"virtual":{"machine)":1}
,"machine)":{"used":1}
,"used":{"via":1,"add":1}
,"via":{"rmi":1,"jdbc":1,"jobstorecmt":1,"jdbcjobstore":1}
,"rmi":{"quartz":1}
,"cluster":{"stand-alone":1}
,"programs":{"(with":1}
,"(with":{"load-balance":1}
,"load-balance":{"fail-over":1}
,"fail-over":{"capabilities)":1,"provides":1}
,"capabilities)":{"execution":1}
,"execution":{"jobs":1,"job":1}
,"jobs":{"job":1,"scheduled":1,"given":1,"added":1,"perform":1,"java":1,"completed":1,"included":1,"triggers":1}
,"job":{"scheduling":1,"execution":1,"interface":1,"class":1,"executed":1,"job":1,"persistence":1,"work":1,"automatically":1,"executions":1,"trigger":1}
,"scheduling":{"jobs":1,"events":1}
,"scheduled":{"run":1}
,"given":{"trigger":1,"names":1}
,"trigger":{"occurs":1,"definitions":1}
,"occurs":{"triggers":1,"scheduler":1}
,"triggers":{"created":1,"may":1,"within":1,"configured":1,"stored":1}
,"created":{"nearly":1}
,"nearly":{"combination":1}
,"combination":{"following":1}
,"following":{"directives":1}
,"directives":{"certain":1}
,"certain":{"time":1,"days":1}
,"time":{"day":1}
,"day":{"(to":1}
,"(to":{"millisecond)":1}
,"millisecond)":{"certain":1}
,"days":{"week":1,"month":1,"year":1,"listed":1}
,"week":{"certain":1}
,"month":{"certain":1}
,"year":{"certain":1}
,"listed":{"within":1}
,"registered":{"calendar":1,"multiple":1}
,"calendar":{"(such":1}
,"(such":{"business":1}
,"business":{"holidays)":1}
,"holidays)":{"repeated":1}
,"repeated":{"specific":1,"until":1,"indefinitely":1,"delay":1}
,"specific":{"number":1,"time\u002Fdate":1}
,"number":{"times":1,"factory":1}
,"times":{"repeated":1}
,"until":{"specific":1}
,"time\u002Fdate":{"repeated":1}
,"indefinitely":{"repeated":1}
,"delay":{"interval":1}
,"interval":{"jobs":1}
,"names":{"creator":1,"placed":1}
,"creator":{"organized":1}
,"organized":{"named":1}
,"named":{"groups":1}
,"groups":{"triggers":1,"order":1}
,"may":{"given":1}
,"placed":{"groups":1}
,"order":{"easily":1}
,"easily":{"organize":1}
,"organize":{"within":1}
,"scheduler":{"jobs":1,"once":1,"notifies":1,"success":1,"actions":1}
,"added":{"scheduler":1}
,"once":{"registered":1}
,"multiple":{"triggers":1}
,"enterprise":{"java":1}
,"environment":{"jobs":1}
,"perform":{"work":1,"job":1}
,"work":{"part":1,"jobs":1,"performed":1}
,"part":{"distributed":1}
,"distributed":{"(xa)":1}
,"(xa)":{"transaction":1}
,"transaction":{"job":1,"clustering":1}
,"class":{"implements":1,"instances":1}
,"implements":{"simple":1}
,"simple":{"job":1,"java":1}
,"interface":{"leaving":1,"implemented":1}
,"leaving":{"infinite":1}
,"infinite":{"possibilities":1}
,"possibilities":{"work":1}
,"instances":{"instantiated":1}
,"application\u0027s":{"framework":1}
,"framework":{"trigger":1}
,"notifies":{"zero":1}
,"zero":{"java":1}
,"objects":{"implementing":1,"ejbs":1}
,"implementing":{"joblistener":1,"listener":1}
,"joblistener":{"triggerlistener":1}
,"triggerlistener":{"interfaces":1}
,"interfaces":{"(listeners":1,"plug-in":1}
,"(listeners":{"simple":1}
,"ejbs":{"jms":1}
,"jms":{"publishers":1}
,"publishers":{"etc.)":1}
,"etc.)":{"listeners":1}
,"listeners":{"notified":1,"&plug-ins":1}
,"notified":{"job":1}
,"executed":{"jobs":1}
,"completed":{"return":1}
,"return":{"jobcompletioncode":1}
,"jobcompletioncode":{"informs":1,"instruct":1}
,"informs":{"scheduler":1}
,"success":{"failure":1}
,"failure":{"jobcompletioncode":1}
,"instruct":{"scheduler":1}
,"actions":{"based":1}
,"based":{"success\u002Ffail":1}
,"success\u002Ffail":{"code":1}
,"code":{"-such":1}
,"-such":{"immediate":1}
,"immediate":{"re-execution":1}
,"re-execution":{"job":1}
,"persistence":{"design":1,"via":1}
,"design":{"quartz":1}
,"includes":{"jobstore":1}
,"jobstore":{"interface":1}
,"implemented":{"provide":1}
,"provide":{"various":1,"clustering":1}
,"various":{"mechanisms":1}
,"mechanisms":{"storage":1}
,"storage":{"jobs":1}
,"included":{"jdbcjobstore":1,"ramjobstore":1}
,"jdbcjobstore":{"jobs":1,"(described":1}
,"configured":{"non-volatile":1}
,"non-volatile":{"stored":1}
,"stored":{"relational":1,"ram":1}
,"relational":{"database":1}
,"database":{"via":1,"transactions":1,"persistence":1,"listeners":1}
,"jdbc":{"included":1}
,"ramjobstore":{"jobs":1}
,"ram":{"therefore":1}
,"therefore":{"persist":1}
,"persist":{"program":1}
,"executions":{"-but":1,"loading":1}
,"-but":{"advantage":1}
,"advantage":{"requiring":1}
,"requiring":{"external":1}
,"external":{"database":1}
,"jta":{"transactions":1,"transaction":1}
,"jobstorecmt":{"subclass":1}
,"subclass":{"jdbcjobstore)":1}
,"jdbcjobstore)":{"quartz":1}
,"manage":{"jta":1}
,"(begin":{"commit":1}
,"commit":{"them)":1}
,"them)":{"around":1}
,"around":{"execution":1}
,"performed":{"job":1}
,"automatically":{"happens":1}
,"happens":{"within":1}
,"clustering":{"features":1,"capabilities":1}
,"provides":{"fail-over":1,"load":1}
,"load":{"balancing":1}
,"balancing":{"quartz\u0027s":1}
,"quartz\u0027s":{"built-in":1}
,"built-in":{"clustering":1}
,"rely":{"upon":1}
,"upon":{"database":1}
,"(described":{"above)":1}
,"above)":{"terracotta":1}
,"terracotta":{"extensions":1}
,"extensions":{"quartz":1}
,"capabilities":{"without":1}
,"without":{"need":1}
,"need":{"back-end":1}
,"back-end":{"database":1}
,"&plug-ins":{"applications":1}
,"applications":{"catch":1}
,"catch":{"scheduling":1}
,"events":{"monitor":1}
,"monitor":{"control":1}
,"control":{"job\u002Ftrigger":1}
,"job\u002Ftrigger":{"behavior":1}
,"behavior":{"implementing":1}
,"listener":{"interfaces":1}
,"plug-in":{"mechanism":1}
,"mechanism":{"used":1}
,"add":{"functionality":1}
,"functionality":{"quartz":1}
,"keeping":{"history":1}
,"history":{"job":1}
,"loading":{"job":1}
,"definitions":{"file":1}
,"file":{"quartz":1}
,"ships":{"number":1}
,"factory":{"built":1}
,"built":{"plug-ins":1}
,"plug-ins":{"listeners":1}
}
;Search.control.loadWordPairs(pairs);
