var pairs =
{
"miscellaneous":{"questions":1}
,"questions":{"jobs":1}
,"jobs":{"quartz":1,"triggers":1,"running":1,"run":1,"jobs":1,"long":1,"once":1,"shared":1,"(distributing":1,"consider":1,"using":1,"without":1}
,"quartz":{"capable":1,"actually":1,"store":1,"running":1,"itself":1,"instance":1,"instances":1,"managing":1,"load-balancing":1,"need":1,"via":1,"user":1}
,"capable":{"running":1}
,"running":{"tough":1,"quartz":1,"moment":1,"within":1}
,"tough":{"question":1}
,"question":{"answer":1,"jobs":1,"however":1}
,"answer":{"basically":1,"question":1}
,"basically":{"depends":1}
,"depends":{"first":1,"almost":1}
,"first":{"jobstore":1}
,"jobstore":{"plays":1,"(1000x)":1,"speed":1,"(either":1}
,"plays":{"significant":1}
,"significant":{"factor":1}
,"factor":{"ram-based":1,"number":1}
,"ram-based":{"jobstore":1}
,"(1000x)":{"faster":1}
,"faster":{"jdbc-based":1}
,"jdbc-based":{"jobstore":1}
,"speed":{"jdbc-jobstore":1,"connection":1}
,"jdbc-jobstore":{"depends":1,"limiting":1}
,"almost":{"entirely":1}
,"entirely":{"speed":1}
,"connection":{"database":1}
,"database":{"data":1,"running":1,"course":1,"may":1,"first-come":1}
,"data":{"base":1}
,"base":{"system":1}
,"system":{"hardware":1,"cpu":1,"spends":1}
,"hardware":{"database":1}
,"actually":{"little":1,"listeners":1}
,"little":{"processing":1}
,"processing":{"itself":1,"job\u0027s":1}
,"itself":{"nearly":1,"using":1}
,"nearly":{"time":1}
,"time":{"spent":1,"thing":1,"limited":1,"careful":1,"juggling":1,"managing":1,"complete":1,"finally":1}
,"spent":{"database":1,"listener":1,"processing":1}
,"course":{"ramjobstore":1}
,"ramjobstore":{"finite":1}
,"finite":{"limit":1}
,"limit":{"jobs":1}
,"triggers":{"stored":1,"jobs":1,"fire":1,"given":1}
,"stored":{"sure":1}
,"sure":{"less":1}
,"less":{"ram":1}
,"ram":{"hard-drive":1,"amount":1}
,"hard-drive":{"space":1}
,"space":{"database":1,"available":1}
,"may":{"look":1}
,"look":{"faq":1}
,"faq":{"improve":1}
,"improve":{"performance":1}
,"performance":{"jdbc-jobstore":1,"degrades":1,"plunges":1,"add":1,"quartz":1}
,"limiting":{"factor":1}
,"number":{"triggers":1,"jobs":1}
,"store":{"monitor":1,"question":1}
,"monitor":{"really":1}
,"really":{"amount":1,"need":1,"comes":1}
,"amount":{"storage":1,"ram":1,"disk":1}
,"storage":{"space":1}
,"available":{"jobstore":1}
,"(either":{"amount":1}
,"disk":{"space)":1}
,"space)":{"aside":1}
,"aside":{"store":1,"factors":1}
,"moment":{"time":1,"executing":1}
,"thing":{"slow":1}
,"slow":{"down":1}
,"down":{"quartz":1,"jobs":1}
,"using":{"lot":1,"listeners":1,"multiple":1,"scheduler":1,"quartz":1}
,"lot":{"listeners":1,"threads":1}
,"listeners":{"(triggerlisteners":1,"just":1,"specialized":1,"unless":1,"actual":1}
,"(triggerlisteners":{"joblisteners":1}
,"joblisteners":{"schedulerlisteners)":1}
,"schedulerlisteners)":{"time":1}
,"listener":{"obviously":1}
,"obviously":{"adds":1,"run":1}
,"adds":{"time":1}
,"job\u0027s":{"execution":1}
,"execution":{"outside":1,"job":1}
,"outside":{"actual":1}
,"actual":{"execution":1,"number":1}
,"job":{"mean":1}
,"mean":{"avoid":1}
,"avoid":{"using":1}
,"just":{"means":1}
,"means":{"judiciously":1}
,"judiciously":{"create":1}
,"create":{"global":1}
,"global":{"listeners":1}
,"specialized":{"ones":1}
,"ones":{"perform":1}
,"perform":{"expensive":1}
,"expensive":{"things":1}
,"things":{"listeners":1}
,"unless":{"really":1}
,"need":{"mindful":1,"scale":1,"i\u0027m":1}
,"mindful":{"plug-ins":1,"running":1}
,"plug-ins":{"(such":1}
,"(such":{"history":1}
,"history":{"plugin)":1}
,"plugin)":{"actually":1}
,"limited":{"size":1}
,"size":{"thread":1}
,"thread":{"pool":1}
,"pool":{"five":1}
,"five":{"threads":1,"jobs":1}
,"threads":{"pool":1,"jvm":1,"performance":1,"cases":1,"(or":1,"intensive)":1,"aside":1}
,"run":{"time":1,"jobs":1}
,"careful":{"creating":1}
,"creating":{"lot":1}
,"jvm":{"operating":1}
,"operating":{"system":1}
,"cpu":{"hard":1}
,"hard":{"time":1}
,"juggling":{"lots":1}
,"lots":{"threads":1}
,"degrades":{"system":1,"performance":1}
,"spends":{"time":1}
,"managing":{"threads":1,"hundreds-of-thousands":1}
,"cases":{"performance":1}
,"plunges":{"several":1}
,"several":{"hundreds":1,"dozen":1,"dozens":1}
,"hundreds":{"threads":1}
,"(or":{"fewer":1}
,"fewer":{"code":1}
,"code":{"executed":1}
,"executed":{"threads":1}
,"intensive)":{"mindful":1}
,"within":{"application":1}
,"application":{"server":1}
,"server":{"probably":1}
,"probably":{"several":1}
,"dozen":{"threads":1}
,"factors":{"really":1}
,"comes":{"down":1}
,"long":{"time":1}
,"complete":{"work":1}
,"work":{"cpu-intensive":1}
,"cpu-intensive":{"obviously":1,"jobs":1}
,"once":{"given":1}
,"given":{"span":1,"moment":1}
,"span":{"time":1}
,"finally":{"cannot":1,"important":1}
,"cannot":{"enough":1}
,"enough":{"horse-power":1}
,"horse-power":{"quartz":1}
,"instance":{"always":1,"run":1}
,"always":{"load-balance":1}
,"load-balance":{"quartz":1}
,"instances":{"separate":1}
,"separate":{"machines":1}
,"machines":{"instance":1}
,"shared":{"database":1}
,"first-come":{"first-serve":1}
,"first-serve":{"basis":1}
,"basis":{"quickly":1}
,"quickly":{"triggers":1}
,"fire":{"clustering":1}
,"clustering":{"feature":1}
,"feature":{"works":1}
,"works":{"best":1,"familiarize":1}
,"best":{"scaling":1}
,"scaling":{"long-running":1}
,"long-running":{"and\u002For":1}
,"and\u002For":{"cpu-intensive":1}
,"(distributing":{"work-load":1}
,"work-load":{"multiple":1}
,"multiple":{"nodes)":1,"distinct":1}
,"nodes)":{"need":1}
,"scale":{"support":1}
,"support":{"thousands":1}
,"thousands":{"short-running":1}
,"short-running":{"(e.g":1}
,"(e.g":{"second)":1}
,"second)":{"jobs":1}
,"consider":{"partitioning":1}
,"partitioning":{"jobs":1}
,"distinct":{"schedulers":1}
,"schedulers":{"using":1}
,"scheduler":{"forces":1}
,"forces":{"cluster-wide":1}
,"cluster-wide":{"lock":1}
,"lock":{"pattern":1}
,"pattern":{"degrades":1}
,"add":{"clients":1}
,"clients":{"difficult":1}
,"difficult":{"specifically":1}
,"specifically":{"answer":1}
,"however":{"installments":1}
,"installments":{"quartz":1}
,"hundreds-of-thousands":{"jobs":1}
,"executing":{"several":1}
,"dozens":{"jobs":1}
,"without":{"even":1}
,"even":{"utilizing":1}
,"utilizing":{"quartz":1}
,"load-balancing":{"capabilities":1}
,"capabilities":{"mind":1}
,"mind":{"users":1}
,"users":{"feel":1}
,"feel":{"confident":1}
,"confident":{"performance":1}
,"i\u0027m":{"having":1}
,"having":{"issues":1}
,"issues":{"using":1}
,"via":{"rmi":1}
,"rmi":{"rmi":1,"problematic":1,"works":1,"reading":1,"review":1,"codebase":1,"class":1}
,"problematic":{"especially":1}
,"especially":{"understanding":1}
,"understanding":{"class":1}
,"class":{"loading":1,"loader":1}
,"loading":{"via":1}
,"familiarize":{"yourself":1}
,"yourself":{"rmi":1}
,"reading":{"javadoc":1}
,"javadoc":{"rmi":1}
,"review":{"following":1}
,"following":{"references":1}
,"references":{"provided":1}
,"provided":{"quartz":1}
,"user":{"mike":1}
,"mike":{"curwen":1}
,"curwen":{"description":1}
,"description":{"rmi":1}
,"codebase":{"http:\u002F\u002Fwww.kedwards.com\u002Fjini\u002Fcodebase.html":1,"used":1}
,"http:\u002F\u002Fwww.kedwards.com\u002Fjini\u002Fcodebase.html":{"important":1}
,"important":{"points":1,"\u0027take":1}
,"points":{"realize":1}
,"realize":{"codebase":1}
,"used":{"client":1}
,"client":{"overview":1}
,"overview":{"security":1}
,"security":{"managers":1,"manager":1}
,"managers":{"<<ffc-find":1}
,"<<ffc-find":{"replacement":1}
,"replacement":{"link":1}
,"link":{"longer":1}
,"longer":{"valid>>":1}
,"valid>>":{"http:\u002F\u002Fgethelp.devx.com\u002Ftechtips\u002Fjava_pro\u002F10minutesolutions\u002F10min0500.asp":1}
,"http:\u002F\u002Fgethelp.devx.com\u002Ftechtips\u002Fjava_pro\u002F10minutesolutions\u002F10min0500.asp":{"finally":1}
,"\u0027take":{"away":1}
,"away":{"java":1}
,"java":{"api":1}
,"api":{"rmi":1}
,"loader":{"download":1}
,"download":{"classes":1}
,"classes":{"remote":1}
,"remote":{"locations":1}
,"locations":{"security":1}
}
;Search.control.loadWordPairs(pairs);
