var pairs =
{
"what\u0027s":{"new":1}
,"new":{"quartz":1,"features":1,"usertransaction":1}
,"quartz":{"scheduler":1,"library":1,"functionality":1,"requires":1,"including":1}
,"scheduler":{"2.2":1}
,"2.2":{"extend":1}
,"extend":{"thanks":1}
,"thanks":{"community":1}
,"community":{"contributors":1}
,"contributors":{"provided":1}
,"provided":{"ideas":1}
,"ideas":{"patches":1}
,"patches":{"work":1}
,"work":{"contained":1}
,"contained":{"release":1}
,"release":{"api":1,"notes":1}
,"api":{"changes":1,"changed":1}
,"changes":{"2.2.0":1}
,"2.2.0":{"(including":1,"qtz-370":1,"quartz":1}
,"(including":{"minor":1}
,"minor":{"backward":1}
,"backward":{"compatibility":1}
,"compatibility":{"breakage)":1}
,"breakage)":{"qtz-292":1}
,"qtz-292":{"-scheduler":1}
,"-scheduler":{"interface":1,"schedulejobs":1,"method":1}
,"interface":{"schedulejobs":1,"qtz-225":1,"qtz-275":1}
,"schedulejobs":{"method":1,"api":1}
,"method":{"triggers":1,"schedulerlistener":1,"schedulejob":1,"connectionprovider":1}
,"triggers":{"part":1,"job":1}
,"part":{"instead":1}
,"instead":{"list":1}
,"list":{"qtz-304":1}
,"qtz-304":{"-scheduler":1}
,"changed":{"support":1}
,"support":{"generics":1,"miscellaneous":1}
,"generics":{"avoid":1}
,"avoid":{"cast":1}
,"cast":{"qtz-366":1}
,"qtz-366":{"-deleted":1}
,"-deleted":{"long-deprecated":1}
,"long-deprecated":{"cloudscapedelegate":1}
,"cloudscapedelegate":{"qtz-212":1}
,"qtz-212":{"-added":1}
,"-added":{"schedulerstarting":1}
,"schedulerstarting":{"method":1}
,"schedulerlistener":{"interface":1}
,"qtz-225":{"-made":1}
,"-made":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"classloadhelper":1}
,"classloadhelper":{"available":1}
,"available":{"plugins":1}
,"plugins":{"initialized":1}
,"initialized":{"using":1}
,"using":{"jdbc":1,"simplethreadpool)":1}
,"jdbc":{"jobstore":1}
,"jobstore":{"schema":1,"internal":1}
,"schema":{"change":1}
,"change":{"requires":1}
,"requires":{"addition":1,"jdk":1}
,"addition":{"column":1}
,"column":{"fired_triggers":1,"sql":1,"sched_time":1}
,"fired_triggers":{"table":1}
,"table":{"add":1,"qrtz_fired_triggers":1}
,"add":{"column":1}
,"sql":{"statement":1}
,"statement":{"examples":1}
,"examples":{"shown":1}
,"shown":{"below":1}
,"below":{"(with":1}
,"(with":{"slight":1}
,"slight":{"variants":1}
,"variants":{"data":1}
,"data":{"type":1}
,"type":{"needed":1}
,"needed":{"depending":1}
,"depending":{"upon":1}
,"upon":{"database":1}
,"database":{"flavor)":1}
,"flavor)":{"oracle":1}
,"oracle":{"alter":1}
,"alter":{"table":1}
,"qrtz_fired_triggers":{"add":1}
,"sched_time":{"number":1,"bigint":1}
,"number":{"(13)":1}
,"(13)":{"null":1}
,"null":{"postgresql":1,"mysql":1,"new":1}
,"postgresql":{"alter":1}
,"bigint":{"null":1,"(13)":1}
,"mysql":{"alter":1}
,"features":{"2.2.0":1}
,"qtz-370":{"-ability":1}
,"-ability":{"override":1}
,"override":{"default":1,"worker":1}
,"default":{"transaction":1}
,"transaction":{"timeout":1}
,"timeout":{"beginning":1}
,"beginning":{"new":1}
,"usertransaction":{"qtz-323":1}
,"qtz-323":{"-ability":1}
,"worker":{"thread":1}
,"thread":{"names":1}
,"names":{"(when":1}
,"(when":{"using":1}
,"simplethreadpool)":{"qtz-79":1}
,"qtz-79":{"-improvements":1}
,"-improvements":{"out-of-the-box":1,"job":1}
,"out-of-the-box":{"sendmailjob":1,"jobs":1}
,"sendmailjob":{"qtz-121":1}
,"qtz-121":{"-an":1}
,"-an":{"ejb":1}
,"ejb":{"job":1}
,"job":{"invoker":1,"<trigger>":1,"once":1,"recovery":1}
,"invoker":{"supports":1}
,"supports":{"ejb3":1}
,"ejb3":{"created":1}
,"created":{"qtz-267":1}
,"qtz-267":{"-scheduler":1}
,"schedulejob":{"(jobdetail":1}
,"(jobdetail":{"job":1}
,"<trigger>":{"trigger)":1}
,"trigger)":{"schedule":1}
,"schedule":{"multiple":1}
,"multiple":{"triggers":1}
,"once":{"qtz-272":1}
,"qtz-272":{"-initialize":1}
,"-initialize":{"method":1}
,"connectionprovider":{"interface":1}
,"qtz-275":{"triggerless":1}
,"triggerless":{"initial":1}
,"initial":{"storing":1}
,"storing":{"non-durable":1}
,"non-durable":{"jobs":1}
,"jobs":{"qtz-315":1,"(see":1}
,"qtz-315":{"-improvements":1}
,"recovery":{"information":1}
,"information":{"qtz-154":1}
,"qtz-154":{"-osgi":1}
,"-osgi":{"support":1}
,"miscellaneous":{"2.2.0":1}
,"library":{"distributed":1}
,"distributed":{"two":1}
,"two":{"jar":1}
,"jar":{"files":1,"file":1}
,"files":{"jar":1}
,"file":{"provides":1}
,"provides":{"quartz":1,"out-of-the-box":1}
,"functionality":{"provides":1}
,"(see":{"qtz-378.)":1}
,"qtz-378.)":{"quartz":1}
,"jdk":{"1.6":1}
,"1.6":{"newer":1}
,"newer":{"(qtz-286.)":1}
,"(qtz-286.)":{"performance":1}
,"performance":{"improvements":1}
,"improvements":{"made":1,"select":1}
,"made":{"quartz":1}
,"including":{"improvements":1}
,"select":{"statements":1}
,"statements":{"jdbc":1}
,"internal":{"spi\u002Finterface":1}
,"spi\u002Finterface":{"refactorings":1}
,"refactorings":{"(cleanups)":1}
,"(cleanups)":{"driverdelegate":1}
,"driverdelegate":{"subclasses":1}
,"subclasses":{"semaphore":1}
,"semaphore":{"class":1}
,"class":{"forth":1}
,"forth":{"various":1}
,"various":{"bug":1}
,"bug":{"fixes":1}
,"fixes":{"complete":1}
,"complete":{"listing":1}
,"listing":{"release":1}
,"notes":{"jira":1}
,"jira":{"https:\u002F\u002Fjira.terracotta.org\u002Fjira\u002Fsecure\u002Freleasenote.jspa":1}
,"https:\u002F\u002Fjira.terracotta.org\u002Fjira\u002Fsecure\u002Freleasenote.jspa":{"projectid=10282&version=11041":1}
}
;Search.control.loadWordPairs(pairs);
