var pairs =
{
"example":{"-job":1,"designed":1,"example":1,"executed":1,"example4.sh":1,"resides":1,"made":1,"@persistjobdataafterexecution":1}
,"-job":{"parameters":1}
,"parameters":{"job":1,"quartz":1,"favorite":1}
,"job":{"state":1,"program":1,"execute":1,"parameter":1,"instance":1,"prints":1,"interface":1,"{the":1,"allowed":1,"code":1,"executed":1,"map":1,"map)":1,"member":1,"data":1,"scheduled":1,"passed":1,"parameters":1}
,"state":{"example":1,"job":1,"preserved":1,"jobstateexample":1}
,"designed":{"demonstrate":1}
,"demonstrate":{"pass":1}
,"pass":{"run-time":1}
,"run-time":{"parameters":1,"job":1,"parameter)":1}
,"quartz":{"jobs":1,"scheduler":1,"always":1}
,"jobs":{"maintain":1,"job":1,"plenty":1,"completed":1}
,"maintain":{"state":1}
,"program":{"perform":1,"wait":1,"colorjob":1,"starts":1,"sleep":1,"gracefully":1}
,"perform":{"following":1}
,"following":{"actions":1,"classes":1,"information":1}
,"actions":{"start":1}
,"start":{"quartz":1}
,"scheduler":{"schedule":1,"pass":1,"running":1,"done":1,"create":1,"schedulerfactory":1,"sched":1,"started":1,"opportunity":1,"sched.shutdown":1,"wait":1}
,"schedule":{"two":1}
,"two":{"jobs":1,"ways":1,"job":1}
,"execute":{"every":1,"method":1}
,"every":{"ten":1,"seconds)":1,"seconds":1}
,"ten":{"seconds":1}
,"seconds":{"specified":1,"two":1,"run":1,"total":1}
,"specified":{"total":1}
,"total":{"times":1,"five":1}
,"times":{"scheduler":1,"jobdetail":1}
,"parameter":{"green":1,"red":1,"_log.info":1,"retrieved":1}
,"green":{"first":1,"execution":1,"job1.getjobdatamap":1}
,"first":{"job":1}
,"instance":{"scheduler":1,"program":1,"class":1}
,"red":{"second":1,"execution":1,"job2.getjobdatamap":1}
,"second":{"job":1}
,"wait":{"seconds":1,"until":1}
,"plenty":{"time":1}
,"time":{"run":1}
,"run":{"shut":1,"example":1,"concurrently":1,"scheduled":1,"every":1,"job":1}
,"shut":{"down":1}
,"down":{"scheduler":1}
,"running":{"example":1,"returning":1}
,"executed":{"examples\u002Fexample4":1,"job\u0027s":1}
,"examples\u002Fexample4":{"directory":1}
,"directory":{"two":1}
,"ways":{"run":1}
,"example4.sh":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"shell":1}
,"shell":{"script":1}
,"script":{"example4.bat":1}
,"example4.bat":{"windows":1}
,"windows":{"batch":1}
,"batch":{"file":1}
,"file":{"code":1}
,"code":{"code":1,"example":1,"execute":1}
,"resides":{"package":1}
,"package":{"org.quartz.examples.example4":1}
,"org.quartz.examples.example4":{"code":1}
,"made":{"following":1}
,"classes":{"class":1}
,"class":{"name":1,"implement":1,"colorjob":1,"private":1,"during":1}
,"name":{"description":1}
,"description":{"jobstateexample":1}
,"jobstateexample":{"main":1,"program":1}
,"main":{"program":1}
,"colorjob":{"simple":1,"colorjob":1,"implements":1,"logs":1,"jobkey":1}
,"simple":{"job":1,"class":1,"ram-based":1}
,"prints":{"favorite":1}
,"favorite":{"color":1}
,"color":{"(passed":1,"(which":1,"favoritecolor":1,"value":1}
,"(passed":{"run-time":1}
,"parameter)":{"displays":1,"job\u0027s":1}
,"displays":{"execution":1}
,"execution":{"count":1,"purposes":1,"job\u0027s":1,"prevents":1}
,"count":{"colorjob":1,"calculated":1,"maintained":1,"(from":1,"\u0022\u005Cn":1,"stored":1,"=data.getint":1,"data.put":1,"always":1,"initialized":1}
,"implement":{"job":1}
,"interface":{"annotated":1}
,"annotated":{"shown":1}
,"shown":{"below":1}
,"below":{"@persistjobdataafterexecution":1}
,"@persistjobdataafterexecution":{"@disallowconcurrentexecution":1,"annotation":1}
,"@disallowconcurrentexecution":{"public":1,"annotation":1}
,"public":{"class":1}
,"implements":{"job":1}
,"{the":{"annotations":1}
,"annotations":{"cause":1}
,"cause":{"behavior":1}
,"behavior":{"names":1}
,"names":{"describe":1}
,"describe":{"multiple":1}
,"multiple":{"instances":1}
,"instances":{"job":1}
,"allowed":{"run":1}
,"concurrently":{"(consider":1}
,"(consider":{"case":1}
,"case":{"job":1}
,"method":{"takes":1,"tells":1,"call":1}
,"takes":{"seconds":1}
,"scheduled":{"trigger":1,"run":1}
,"trigger":{"repeats":1}
,"repeats":{"every":1}
,"seconds)":{"jobdatamap":1,"thread.sleep":1}
,"jobdatamap":{"contents":1,"jobdatamap":1,"data":1}
,"contents":{"re-persisted":1}
,"re-persisted":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"jobstore":1}
,"jobstore":{"execution":1}
,"purposes":{"example":1}
,"annotation":{"truly":1,"prevent":1}
,"truly":{"relevant":1}
,"relevant":{"it\u0027s":1}
,"it\u0027s":{"always":1}
,"always":{"wise":1,"displayed":1,"instantiate":1}
,"wise":{"@disallowconcurrentexecution":1}
,"prevent":{"race-conditions":1}
,"race-conditions":{"saved":1}
,"saved":{"data":1}
,"data":{"colorjob":1,"=context.getjobdetail":1,"map":1}
,"logs":{"following":1}
,"information":{"job":1}
,"job\u0027s":{"identification":1,"favorite":1,"execution":1}
,"identification":{"key":1}
,"key":{"(name":1}
,"(name":{"group)":1}
,"group)":{"time\u002Fdate":1}
,"time\u002Fdate":{"execution":1}
,"(which":{"passed":1}
,"passed":{"run-time":1,"job":1,"two":1}
,"calculated":{"member":1}
,"member":{"variable":1,"variable)":1,"variables":1}
,"variable":{"job\u0027s":1,"favoritecolor":1,"count":1,"later":1,"named":1,"defined":1,"class":1,"incremented":1}
,"maintained":{"job":1}
,"map":{"parameter":1,"jobdatamap":1,"job":1}
,"_log.info":{"colorjob":1}
,"jobkey":{"executing":1}
,"executing":{"new":1}
,"new":{"date":1,"instance":1}
,"date":{"\u0022\u005Cn":1}
,"\u0022\u005Cn":{"favorite":1,"execution":1}
,"favoritecolor":{"\u0022\u005Cn":1,"passed":1,"=data.getstring":1}
,"(from":{"job":1}
,"map)":{"count":1}
,"variable)":{"_counter)":1}
,"_counter)":{"variable":1}
,"retrieved":{"follows":1}
,"follows":{"jobdatamap":1}
,"=context.getjobdetail":{".getjobdatamap":1}
,".getjobdatamap":{"string":1,"int":1}
,"string":{"favoritecolor":1}
,"=data.getstring":{"(favorite_color)":1}
,"(favorite_color)":{"variable":1}
,"stored":{"job":1,"back":1}
,"int":{"count":1,"_counter":1}
,"=data.getint":{"(execution_count)":1}
,"(execution_count)":{"variable":1}
,"later":{"incremented":1}
,"incremented":{"stored":1,"displayed":1}
,"back":{"job":1}
,"preserved":{"count":1}
,"data.put":{"(execution_count":1}
,"(execution_count":{"count)":1}
,"count)":{"member":1}
,"named":{"counter":1}
,"counter":{"variable":1}
,"defined":{"member":1}
,"private":{"int":1}
,"_counter":{"variable":1}
,"displayed":{"however":1,"quartz":1}
,"however":{"count":1}
,"instantiate":{"new":1}
,"during":{"execution":1}
,"prevents":{"member":1}
,"variables":{"used":1}
,"used":{"maintain":1}
,"starts":{"getting":1}
,"getting":{"instance":1}
,"done":{"creating":1}
,"creating":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"using":1,"scheduler":1}
,"using":{"create":1}
,"create":{"scheduler":1,"simple":1}
,"ram-based":{"scheduler":1}
,"schedulerfactory":{"=new":1}
,"=new":{"stdschedulerfactory":1}
,"sched":{"=sf.getscheduler":1}
,"=sf.getscheduler":{"job":1}
,"five":{"times":1}
,"jobdetail":{"job1":1,"job2":1}
,"job1":{"=newjob":1,"group1":1}
,"=newjob":{"(colorjob.class)":1}
,"(colorjob.class)":{".withidentity":1}
,".withidentity":{"job1":1,"trigger1":1,"job2":1,"trigger2":1}
,"group1":{".build":1,".startat":1}
,".build":{"simpletrigger":1,"job":1}
,"simpletrigger":{"trigger1":1,"trigger2":1}
,"trigger1":{"=newtrigger":1,"group1":1}
,"=newtrigger":{".withidentity":1}
,".startat":{"(starttime)":1}
,"(starttime)":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(10)":1}
,"(10)":{".withrepeatcount":1}
,".withrepeatcount":{"(4))":1}
,"(4))":{".build":1}
,"value":{"green":1,"job1.getjobdatamap":1,"red":1,"job2.getjobdatamap":1}
,"initialized":{"value":1}
,"job1.getjobdatamap":{".put":1}
,".put":{"(colorjob.favorite_color":1,"(colorjob.execution_count":1}
,"(colorjob.favorite_color":{"green":1,"red":1}
,"(colorjob.execution_count":{"job":1,"scheduler":1}
,"job2":{"=newjob":1,"group1":1}
,"trigger2":{"=newtrigger":1,"group1":1}
,"job2.getjobdatamap":{".put":1}
,"started":{"sched.start":1}
,"sched.start":{"scheduler":1}
,"opportunity":{"run":1}
,"sleep":{"minute":1}
,"minute":{"(60":1}
,"(60":{"seconds)":1}
,"thread.sleep":{"(60l":1}
,"(60l":{"*1000l)":1}
,"*1000l)":{"finally":1}
,"finally":{"program":1}
,"gracefully":{"shuts":1}
,"shuts":{"down":1}
,"sched.shutdown":{"(true)":1}
,"(true)":{"passing":1}
,"passing":{"true":1}
,"true":{"shutdown":1}
,"shutdown":{"method":1}
,"tells":{"quartz":1}
,"until":{"jobs":1}
,"completed":{"running":1}
,"returning":{"method":1}
}
;Search.control.loadWordPairs(pairs);
