var pairs =
{
"logging":{"quartz":1,"needs":1,"settings":1}
,"quartz":{"uses":1}
,"uses":{"slf4j":1}
,"slf4j":{"framework":1}
,"framework":{"logging":1,"beyond":1}
,"needs":{"order":1}
,"order":{"tune":1}
,"tune":{"logging":1}
,"settings":{"(such":1}
,"(such":{"amount":1}
,"amount":{"output":1}
,"output":{"output":1,"goes)":1}
,"goes)":{"need":1}
,"need":{"understand":1}
,"understand":{"slf4j":1}
,"beyond":{"scope":1}
,"scope":{"document":1}
,"document":{"want":1}
,"want":{"capture":1}
,"capture":{"extra":1}
,"extra":{"information":1}
,"information":{"trigger":1}
,"trigger":{"firings":1}
,"firings":{"job":1}
,"job":{"executions":1}
,"executions":{"may":1}
,"may":{"interested":1}
,"interested":{"enabling":1}
,"enabling":{"org.quartz.plugins.history.loggingjobhistoryplugin":1}
,"org.quartz.plugins.history.loggingjobhistoryplugin":{"and\u002For":1}
,"and\u002For":{"org.quartz.plugins.history.loggingtriggerhistoryplugin":1}
}
;Search.control.loadWordPairs(pairs);
