var pairs =
{
"configuring":{"quartz":1}
,"quartz":{"scheduler":1,"edit":1,"quartz":1}
,"scheduler":{"configure":1,"distribution":1,"org.quartz.threadpool.threadcount":1,"ramjobstore":1,"keep":1,"developer":1,"configuration":1}
,"configure":{"quartz":1}
,"edit":{"quartz.properties":1}
,"quartz.properties":{"file":1,"files":1}
,"file":{"place":1,"classpath":1,"org.quartz.scheduler.instancename":1,"include":1}
,"place":{"application\u0027s":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"information":1,"downloading":1}
,"information":{"adding":1,"job":1}
,"adding":{"properties":1}
,"properties":{"file":1,"org.quartz.scheduler.instancename":1,"quartz.properties":1}
,"downloading":{"installing":1}
,"installing":{"quartz":1}
,"distribution":{"package":1}
,"package":{"includes":1}
,"includes":{"several":1}
,"several":{"example":1}
,"example":{"quartz.properties":1,"shows":1,"specifies":1}
,"files":{"examples\u002Fdirectory":1}
,"examples\u002Fdirectory":{"following":1}
,"following":{"example":1,"properties":1}
,"shows":{"contents":1}
,"contents":{"basic":1}
,"basic":{"quartz.properties":1}
,"org.quartz.scheduler.instancename":{"=myscheduler":1,"property":1}
,"=myscheduler":{"org.quartz.threadpool.threadcount":1}
,"org.quartz.threadpool.threadcount":{"org.quartz.jobstore.class":1,"property":1}
,"org.quartz.jobstore.class":{"=org.quartz.simpl.ramjobstore":1,"property":1}
,"=org.quartz.simpl.ramjobstore":{"example":1}
,"specifies":{"following":1}
,"property":{"assigns":1,"allocates":1,"configures":1}
,"assigns":{"name":1}
,"name":{"myscheduler":1}
,"myscheduler":{"scheduler":1}
,"allocates":{"three":1}
,"three":{"threads":1,"jobs":1}
,"threads":{"thread":1}
,"thread":{"pool":1}
,"pool":{"meaning":1}
,"meaning":{"maximum":1}
,"maximum":{"three":1}
,"jobs":{"run":1}
,"run":{"simultaneously":1}
,"simultaneously":{"org.quartz.jobstore.class":1}
,"configures":{"scheduler":1}
,"ramjobstore":{"data":1}
,"data":{"storage":1,"memory":1}
,"storage":{"means":1}
,"means":{"scheduler":1}
,"keep":{"job":1}
,"job":{"trigger":1,"stores":1}
,"trigger":{"data":1}
,"memory":{"rather":1}
,"rather":{"database":1}
,"database":{"information":1}
,"stores":{"working":1,"quartz":1}
,"working":{"job":1}
,"developer":{"guide":1}
,"guide":{"descriptions":1,"<<ffc-insert":1}
,"descriptions":{"properties":1}
,"include":{"quartz":1}
,"configuration":{"guide":1}
,"<<ffc-insert":{"bookname":1}
,"bookname":{"conref":1}
,"conref":{"becomes":1}
,"becomes":{"available>>":1}
}
;Search.control.loadWordPairs(pairs);
