var pairs =
{
"job":{"tips":1,"typically":1,"ready":1,"reschedule":1,"throws":1,"catches":1,"coded":1}
,"tips":{"waiting":1}
,"waiting":{"conditions":1}
,"conditions":{"long-running":1}
,"long-running":{"jobs":1}
,"jobs":{"prevent":1,"execute":1,"exits":1,"work":1,"marked":1}
,"prevent":{"others":1}
,"others":{"running":1}
,"running":{"(if":1}
,"(if":{"threads":1}
,"threads":{"threadpool":1}
,"threadpool":{"busy)":1}
,"busy)":{"feel":1}
,"feel":{"need":1}
,"need":{"call":1}
,"call":{"thread.sleep":1}
,"thread.sleep":{"worker":1}
,"worker":{"thread":1}
,"thread":{"executing":1,"(exit":1,"job":1}
,"executing":{"job":1}
,"typically":{"sign":1,"immediately":1}
,"sign":{"job":1}
,"ready":{"rest":1}
,"rest":{"work":1}
,"work":{"needs":1,"around":1,"executed":1,"idempotent":1}
,"needs":{"wait":1}
,"wait":{"condition":1}
,"condition":{"(such":1}
,"(such":{"availability":1}
,"availability":{"data":1}
,"data":{"record)":1}
,"record)":{"become":1}
,"become":{"true":1}
,"true":{"better":1}
,"better":{"solution":1,"job":1}
,"solution":{"release":1}
,"release":{"worker":1}
,"(exit":{"job)":1}
,"job)":{"allow":1}
,"allow":{"jobs":1}
,"execute":{"thread":1,"method":1}
,"reschedule":{"itself":1}
,"itself":{"jobs":1}
,"exits":{"throwing":1}
,"throwing":{"exceptions":1}
,"exceptions":{"job\u0027s":1,"job":1,"encounter":1}
,"job\u0027s":{"execute":1,"work":1}
,"method":{"contain":1}
,"contain":{"try-catch":1}
,"try-catch":{"block":1}
,"block":{"handles":1}
,"handles":{"possible":1}
,"possible":{"exceptions":1}
,"throws":{"exception":1}
,"exception":{"quartz":1,"again)":1}
,"quartz":{"typically":1}
,"immediately":{"re-execute":1}
,"re-execute":{"(and":1}
,"(and":{"likely":1}
,"likely":{"throw":1}
,"throw":{"exception":1}
,"again)":{"it\u2019s":1}
,"it\u2019s":{"better":1}
,"catches":{"exceptions":1}
,"encounter":{"handle":1}
,"handle":{"reschedule":1}
,"around":{"issue":1}
,"issue":{"recoverability":1}
,"recoverability":{"idempotence":1}
,"idempotence":{"in-progress":1}
,"in-progress":{"jobs":1}
,"marked":{"recoverable":1}
,"recoverable":{"automatically":1}
,"automatically":{"re-executed":1}
,"re-executed":{"scheduler":1}
,"scheduler":{"fails":1}
,"fails":{"means":1}
,"means":{"job\u0027s":1,"job":1}
,"executed":{"twice":1}
,"twice":{"means":1}
,"coded":{"work":1}
}
;Search.control.loadWordPairs(pairs);
