var pairs =
{
"quartz":{"configuration":1,"typically":1}
,"configuration":{"configuration":1,"quartz":1,"file":1}
,"typically":{"done":1}
,"done":{"properties":1}
,"properties":{"file":1,"specified":1}
,"file":{"conjunction":1,"instantiates":1,"named":1,"located":1,"defaults":1,"want":1,"instance":1,"contains":1}
,"conjunction":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"(which":1,"load":1,"instances":1}
,"(which":{"consumes":1}
,"consumes":{"configuration":1}
,"instantiates":{"scheduler)":1}
,"scheduler)":{"default":1}
,"default":{"stdschedulerfactory":1}
,"load":{"properties":1}
,"named":{"quartz.properties":1}
,"quartz.properties":{"current":1,"file":1}
,"current":{"working":1}
,"working":{"directory":1}
,"directory":{"fails":1}
,"fails":{"quartz.properties":1}
,"located":{"(as":1}
,"(as":{"resource)":1}
,"resource)":{"org\u002Fquartz":1}
,"org\u002Fquartz":{"package":1}
,"package":{"loaded":1}
,"loaded":{"file":1}
,"defaults":{"define":1}
,"define":{"system":1}
,"system":{"property":1}
,"property":{"org.quartz.properties":1,"org.quartz.jobstore.myprop":1,"reference":1,"$@org.quartz.scheduler.instancename":1}
,"org.quartz.properties":{"point":1}
,"point":{"file":1}
,"want":{"alternatively":1}
,"alternatively":{"explicitly":1}
,"explicitly":{"initialize":1}
,"initialize":{"factory":1,"methods":1}
,"factory":{"calling":1}
,"calling":{"initialize":1,"getscheduler":1,"equivalent":1,"property\u0027s":1}
,"methods":{"calling":1}
,"getscheduler":{"stdschedulerfactory":1}
,"instances":{"specified":1}
,"specified":{"jobstore":1,"config":1}
,"jobstore":{"threadpool":1,"class":1}
,"threadpool":{"spi":1}
,"spi":{"classes":1}
,"classes":{"created":1}
,"created":{"name":1}
,"name":{"additional":1,"value":1}
,"additional":{"properties":1}
,"config":{"file":1}
,"instance":{"calling":1,"name":1}
,"equivalent":{"\u0027set":1}
,"\u0027set":{"method":1}
,"method":{"example":1,"setmyprop":1,"property":1}
,"example":{"properties":1,"reference":1}
,"contains":{"property":1}
,"org.quartz.jobstore.myprop":{"=10":1}
,"=10":{"jobstore":1}
,"class":{"instantiated":1}
,"instantiated":{"method":1}
,"setmyprop":{"called":1}
,"called":{"type":1}
,"type":{"conversion":1}
,"conversion":{"primitive":1}
,"primitive":{"java":1}
,"java":{"types":1}
,"types":{"(int":1}
,"(int":{"long":1}
,"long":{"float":1}
,"float":{"double":1}
,"double":{"boolean":1}
,"boolean":{"string)":1}
,"string)":{"performed":1}
,"performed":{"calling":1}
,"property\u0027s":{"setter":1,"value":1}
,"setter":{"method":1}
,"reference":{"property\u0027s":1,"scheduler\u0027s":1}
,"value":{"specifying":1,"following":1,"property":1}
,"specifying":{"value":1}
,"following":{"convention":1}
,"convention":{"$@other.property.name":1}
,"$@other.property.name":{"example":1}
,"scheduler\u0027s":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
