var pairs =
{
"triggerlisteners":{"joblisteners":1,"receive":1}
,"joblisteners":{"listeners":1,"receive":1}
,"listeners":{"objects":1}
,"objects":{"create":1}
,"create":{"perform":1}
,"perform":{"actions":1}
,"actions":{"based":1}
,"based":{"events":1}
,"events":{"occurring":1,"related":1,"include":1}
,"occurring":{"within":1}
,"within":{"scheduler":1}
,"scheduler":{"indicated":1}
,"indicated":{"names":1}
,"names":{"triggerlisteners":1}
,"receive":{"events":1}
,"related":{"triggers":1,"jobs":1}
,"triggers":{"joblisteners":1}
,"jobs":{"trigger-related":1,"fired":1}
,"trigger-related":{"events":1}
,"include":{"trigger":1,"notification":1}
,"trigger":{"firings":1,"misfirings":1,"completions":1,"finished)":1,"jobexecutioncontext":1}
,"firings":{"trigger":1}
,"misfirings":{"(discussed":1}
,"(discussed":{"working":1}
,"working":{"triggers)":1}
,"triggers)":{"trigger":1}
,"completions":{"(the":1}
,"(the":{"jobs":1}
,"fired":{"trigger":1}
,"finished)":{"org.quartz.triggerlistener":1}
,"org.quartz.triggerlistener":{"interface":1}
,"interface":{"public":1,"triggerlistener":1,"joblistener":1}
,"public":{"interface":1,"void":1,"boolean":1}
,"triggerlistener":{"{public":1}
,"{public":{"string":1}
,"string":{"getname":1}
,"getname":{"public":1}
,"void":{"triggerfired":1,"triggermisfired":1,"triggercomplete":1,"jobtobeexecuted":1,"jobexecutionvetoed":1,"jobwasexecuted":1}
,"triggerfired":{"(trigger":1}
,"(trigger":{"trigger":1,"trigger)":1}
,"jobexecutioncontext":{"context)":1,"context":1}
,"context)":{"public":1}
,"boolean":{"vetojobexecution":1}
,"vetojobexecution":{"(trigger":1}
,"triggermisfired":{"(trigger":1}
,"trigger)":{"public":1}
,"triggercomplete":{"(trigger":1}
,"context":{"int":1,"jobexecutionexception":1}
,"int":{"triggerinstructioncode)":1}
,"triggerinstructioncode)":{"job-related":1}
,"job-related":{"events":1}
,"notification":{"job":1}
,"job":{"executed":1,"completed":1}
,"executed":{"notification":1}
,"completed":{"execution":1}
,"execution":{"org.quartz.joblistener":1}
,"org.quartz.joblistener":{"interface":1}
,"joblistener":{"{public":1}
,"jobtobeexecuted":{"(jobexecutioncontext":1}
,"(jobexecutioncontext":{"context)":1,"context":1}
,"jobexecutionvetoed":{"(jobexecutioncontext":1}
,"jobwasexecuted":{"(jobexecutioncontext":1}
,"jobexecutionexception":{"jobexception)":1}
}
;Search.control.loadWordPairs(pairs);
