var pairs =
{
"cluster":{"configuration":1,"share":1,"firing":1,"copy":1,"unique":1}
,"configuration":{"quartz\u0027s":1,"properties":1}
,"quartz\u0027s":{"clustering":1}
,"clustering":{"features":1,"currently":1,"feature":1,"setting":1,"separate":1}
,"features":{"bring":1}
,"bring":{"high":1}
,"high":{"availability":1}
,"availability":{"scalability":1}
,"scalability":{"scheduler":1}
,"scheduler":{"via":1,"makes":1,"#============================================================================#":1,"properties":1}
,"via":{"fail-over":1}
,"fail-over":{"load":1,"occurs":1}
,"load":{"balancing":1}
,"balancing":{"functionality":1,"mechanism":1}
,"functionality":{"clustering":1}
,"currently":{"works":1}
,"works":{"jdbc-jobstore":1,"having":1,"best":1}
,"jdbc-jobstore":{"(jobstoretx":1}
,"(jobstoretx":{"jobstorecmt)":1}
,"jobstorecmt)":{"essentially":1}
,"essentially":{"works":1}
,"having":{"node":1}
,"node":{"cluster":1,"acquire":1,"fire":1,"run":1,"time":1,"chosen":1,"non-busy":1,"fails":1,"jobs":1}
,"share":{"database":1}
,"database":{"<<ffc-what":1,"progress":1,"tables":1}
,"<<ffc-what":{"terracotta":1}
,"terracotta":{"option>>":1}
,"option>>":{"load-balancing":1}
,"load-balancing":{"occurs":1}
,"occurs":{"automatically":1,"first":1,"nodes":1}
,"automatically":{"node":1}
,"firing":{"jobs":1,"time":1,"meaning":1}
,"jobs":{"quickly":1,"node":1,"database":1,"marked":1,"(i.e":1,"consider":1,"using":1}
,"quickly":{"trigger\u0027s":1}
,"trigger\u0027s":{"firing":1}
,"time":{"occurs":1,"selected":1,"related":1}
,"first":{"node":1}
,"acquire":{"(by":1}
,"(by":{"placing":1}
,"placing":{"lock":1,"auto":1}
,"lock":{"it)":1,"pattern":1}
,"it)":{"node":1}
,"fire":{"node":1,"job":1,"every":1}
,"job":{"firing":1,"repeating":1,"12:00:10":1,"forth":1}
,"meaning":{"job":1}
,"repeating":{"trigger":1}
,"trigger":{"fire":1,"fires":1}
,"every":{"seconds":1}
,"seconds":{"12:00:00":1}
,"12:00:00":{"exactly":1}
,"exactly":{"node":1}
,"run":{"job":1,"clustering":1}
,"12:00:10":{"exactly":1}
,"forth":{"won\u0027t":1}
,"won\u0027t":{"necessarily":1}
,"necessarily":{"node":1}
,"selected":{"node":1}
,"chosen":{"less":1}
,"less":{"random":1}
,"random":{"load":1}
,"mechanism":{"near-random":1}
,"near-random":{"busy":1}
,"busy":{"schedulers":1}
,"schedulers":{"(lots":1,"fail-over":1,"(including":1,"ha)":1}
,"(lots":{"triggers)":1}
,"triggers)":{"favors":1,"schedulers":1}
,"favors":{"node":1}
,"non-busy":{"(few":1}
,"(few":{"triggers)":1}
,"nodes":{"fails":1,"detect":1,"jobs":1,"(when":1,"-depending":1}
,"fails":{"midst":1,"nodes":1}
,"midst":{"executing":1}
,"executing":{"jobs":1}
,"detect":{"condition":1}
,"condition":{"identify":1}
,"identify":{"jobs":1}
,"progress":{"within":1}
,"within":{"failed":1,"second":1}
,"failed":{"node":1}
,"marked":{"recovery":1}
,"recovery":{"(with":1,"simply":1}
,"(with":{"requests":1}
,"requests":{"property":1}
,"property":{"jobdetail)":1,"true":1,"node":1,"information":1}
,"jobdetail)":{"re-executed":1}
,"re-executed":{"remaining":1}
,"remaining":{"nodes":1}
,"simply":{"freed":1}
,"freed":{"execution":1}
,"execution":{"next":1}
,"next":{"time":1}
,"related":{"trigger":1}
,"fires":{"clustering":1}
,"feature":{"works":1}
,"best":{"scaling":1}
,"scaling":{"long-running":1}
,"long-running":{"and\u002For":1}
,"and\u002For":{"cpu-intensive":1}
,"cpu-intensive":{"jobs":1}
,"(i.e":{"distributing":1}
,"distributing":{"work-load":1}
,"work-load":{"multiple":1}
,"multiple":{"nodes)":1,"distinct":1,"clustered":1}
,"nodes)":{"need":1}
,"need":{"scale":1}
,"scale":{"support":1}
,"support":{"thousands":1}
,"thousands":{"short-running":1}
,"short-running":{"(e.g":1}
,"(e.g":{"second)":1}
,"second)":{"jobs":1}
,"consider":{"partitioning":1}
,"partitioning":{"jobs":1}
,"using":{"multiple":1,"form":1}
,"distinct":{"schedulers":1}
,"(including":{"multiple":1}
,"clustered":{"schedulers":1,"scheduler":1}
,"ha)":{"scheduler":1}
,"makes":{"cluster-wide":1}
,"cluster-wide":{"lock":1}
,"pattern":{"degrades":1}
,"degrades":{"performance":1}
,"performance":{"add":1}
,"add":{"nodes":1}
,"(when":{"going":1}
,"going":{"beyond":1}
,"beyond":{"three":1}
,"three":{"nodes":1}
,"-depending":{"upon":1}
,"upon":{"database\u0027s":1}
,"database\u0027s":{"capabilities":1}
,"capabilities":{"etc.)":1}
,"etc.)":{"enable":1}
,"enable":{"clustering":1}
,"setting":{"org.quartz.jobstore.isclustered":1}
,"org.quartz.jobstore.isclustered":{"property":1}
,"true":{"instance":1}
,"instance":{"cluster":1,"against":1,"running":1}
,"copy":{"quartz.properties":1}
,"quartz.properties":{"file":1}
,"file":{"exceptions":1}
,"exceptions":{"properties":1,"different":1}
,"properties":{"files":1,"files)":1,"run":1,"clustered":1,"#============================================================================org.quartz.scheduler.instancename":1}
,"files":{"identical":1}
,"identical":{"following":1}
,"following":{"allowable":1}
,"allowable":{"exceptions":1}
,"different":{"thread":1,"value":1,"properties":1}
,"thread":{"pool":1}
,"pool":{"size":1}
,"size":{"different":1}
,"value":{"org.quartz.scheduler.instanceid":1,"property":1}
,"org.quartz.scheduler.instanceid":{"property":1,"=auto":1}
,"unique":{"instanceid":1}
,"instanceid":{"easily":1}
,"easily":{"done":1}
,"done":{"(without":1}
,"(without":{"needing":1}
,"needing":{"different":1}
,"files)":{"placing":1}
,"auto":{"value":1}
,"information":{"configuration":1}
,"separate":{"machines":1}
,"machines":{"unless":1}
,"unless":{"clocks":1}
,"clocks":{"synchronized":1,"within":1}
,"synchronized":{"using":1}
,"form":{"time-sync":1}
,"time-sync":{"service":1}
,"service":{"(daemon)":1}
,"(daemon)":{"runs":1}
,"runs":{"regularly":1}
,"regularly":{"(the":1}
,"(the":{"clocks":1}
,"second":{"other)":1}
,"other)":{"http:\u002F\u002Fwww.boulder.nist.gov\u002Ftimefreq\u002Fservice\u002Fits.htm":1}
,"http:\u002F\u002Fwww.boulder.nist.gov\u002Ftimefreq\u002Fservice\u002Fits.htm":{"unfamiliar":1}
,"unfamiliar":{"start":1}
,"start":{"(scheduler.start":1}
,"(scheduler.start":{"())":1}
,"())":{"non-clustered":1}
,"non-clustered":{"instance":1}
,"against":{"database":1,"doing":1}
,"tables":{"instance":1}
,"running":{"(start":1}
,"(start":{"ed)":1}
,"ed)":{"against":1}
,"doing":{"result":1}
,"result":{"data":1}
,"data":{"corruption":1}
,"corruption":{"erratic":1}
,"erratic":{"behavior":1}
,"behavior":{"example":1}
,"example":{"properties":1}
,"#============================================================================#":{"configure":1}
,"configure":{"main":1,"threadpool":1,"jobstore":1,"datasources":1}
,"main":{"scheduler":1}
,"#============================================================================org.quartz.scheduler.instancename":{"=myclusteredscheduler":1}
,"=myclusteredscheduler":{"org.quartz.scheduler.instanceid":1}
,"=auto":{"#============================================================================#":1}
,"threadpool":{"#============================================================================org.quartz.threadpool.class":1}
,"#============================================================================org.quartz.threadpool.class":{"=org.quartz.simpl.simplethreadpool":1}
,"=org.quartz.simpl.simplethreadpool":{"org.quartz.threadpool.threadcount":1}
,"org.quartz.threadpool.threadcount":{"=25":1}
,"=25":{"org.quartz.threadpool.threadpriority":1}
,"org.quartz.threadpool.threadpriority":{"#============================================================================#":1}
,"jobstore":{"#============================================================================org.quartz.jobstore.misfirethreshold":1}
,"#============================================================================org.quartz.jobstore.misfirethreshold":{"=60000":1}
,"=60000":{"org.quartz.jobstore.class":1}
,"org.quartz.jobstore.class":{"=org.quartz.impl.jdbcjobstore.jobstoretx":1}
,"=org.quartz.impl.jdbcjobstore.jobstoretx":{"org.quartz.jobstore.driverdelegateclass":1}
,"org.quartz.jobstore.driverdelegateclass":{"=org.quartz.impl.jdbcjobstore.oracle.oracledelegate":1}
,"=org.quartz.impl.jdbcjobstore.oracle.oracledelegate":{"org.quartz.jobstore.useproperties":1}
,"org.quartz.jobstore.useproperties":{"=false":1}
,"=false":{"org.quartz.jobstore.datasource":1}
,"org.quartz.jobstore.datasource":{"=myds":1}
,"=myds":{"org.quartz.jobstore.tableprefix":1}
,"org.quartz.jobstore.tableprefix":{"=qrtz":1}
,"=qrtz":{"_org.quartz.jobstore.isclustered":1}
,"_org.quartz.jobstore.isclustered":{"=true":1}
,"=true":{"org.quartz.jobstore.clustercheckininterval":1}
,"org.quartz.jobstore.clustercheckininterval":{"=20000":1}
,"=20000":{"#============================================================================#":1}
,"datasources":{"#============================================================================org.quartz.datasource.myds.driver":1}
,"#============================================================================org.quartz.datasource.myds.driver":{"=oracle.jdbc.driver.oracledriver":1}
,"=oracle.jdbc.driver.oracledriver":{"org.quartz.datasource.myds.url":1}
,"org.quartz.datasource.myds.url":{"=jdbc:oracle:thin:@polarbear:1521:dev":1}
,"=jdbc:oracle:thin:@polarbear:1521:dev":{"org.quartz.datasource.myds.user":1}
,"org.quartz.datasource.myds.user":{"=quartz":1}
,"=quartz":{"org.quartz.datasource.myds.password":1,"org.quartz.datasource.myds.maxconnections":1}
,"org.quartz.datasource.myds.password":{"=quartz":1}
,"org.quartz.datasource.myds.maxconnections":{"org.quartz.datasource.myds.validationquery=select":1}
,"org.quartz.datasource.myds.validationquery=select":{"dual":1}
}
;Search.control.loadWordPairs(pairs);
