var pairs =
{
"triggers":{"tips":1,"(schedules)":1,"schedules":1,"specific":1,"(for":1}
,"tips":{"triggerutils":1}
,"triggerutils":{"triggerutils":1,"offers":1}
,"offers":{"simpler":1,"simple":1,"helpers":1}
,"simpler":{"create":1}
,"create":{"triggers":1,"dates":1}
,"(schedules)":{"provides":1}
,"provides":{"various":1}
,"various":{"methods":1,"setter":1}
,"methods":{"creating":1,"configure":1}
,"creating":{"triggers":1}
,"schedules":{"meet":1}
,"meet":{"particular":1}
,"particular":{"descriptions":1}
,"descriptions":{"opposed":1}
,"opposed":{"directly":1}
,"directly":{"instantiating":1}
,"instantiating":{"triggers":1}
,"specific":{"type":1}
,"type":{"(e.g":1}
,"(e.g":{"simpletrigger":1}
,"simpletrigger":{"crontrigger)":1}
,"crontrigger)":{"invoking":1}
,"invoking":{"various":1}
,"setter":{"methods":1}
,"configure":{"offers":1}
,"simple":{"create":1}
,"dates":{"(for":1}
,"(for":{"start\u002Fend":1,"example":1}
,"start\u002Fend":{"dates)":1}
,"dates)":{"offers":1}
,"helpers":{"analyzing":1}
,"analyzing":{"triggers":1}
,"example":{"calculate":1}
,"calculate":{"future":1}
,"future":{"fire":1}
,"fire":{"times)":1}
}
;Search.control.loadWordPairs(pairs);
