var pairs =
{
"quartz":{"datasource":1}
,"datasource":{"properties":1,"create":1,"detect":1,"org.quartz.datasource.myds.driver":1}
,"properties":{"quartz-created":1,"property":1}
,"quartz-created":{"datasources":1}
,"datasources":{"defined":1}
,"defined":{"using":1}
,"using":{"following":1}
,"following":{"properties":1}
,"property":{"name":1,"default":1}
,"name":{"required":1,"jdbc":1,"connecting":1}
,"required":{"type":1}
,"type":{"default":1}
,"default":{"value":1,"seconds":1,"false":1,"example":1}
,"value":{"org.quartz.datasource.name.driver":1}
,"org.quartz.datasource.name.driver":{"string":1,"java":1}
,"string":{"null":1,"org.quartz.datasource.name.password":1,"org.quartz.datasource.name":1,"datasource":1}
,"null":{"org.quartz.datasource.name.url":1,"org.quartz.datasource.name.user":1,"org.quartz.datasource.name":1}
,"org.quartz.datasource.name.url":{"string":1,"connection":1}
,"org.quartz.datasource.name.user":{"string":1,"user":1}
,"org.quartz.datasource.name.password":{"string":1,"password":1}
,"org.quartz.datasource.name":{"maxconnections":1,"validationquery":1,"idleconnectionvalidationseconds":1,"validateoncheckout":1,"discardidleconnectionsseconds":1}
,"maxconnections":{"int":1}
,"int":{"org.quartz.datasource.name":1,"(disabled)":1}
,"validationquery":{"string":1}
,"idleconnectionvalidationseconds":{"int":1}
,"validateoncheckout":{"boolean":1}
,"boolean":{"false":1}
,"false":{"org.quartz.datasource.name":1,"validation":1,"org.quartz.datasource.name.discardidleconnectionsseconds":1}
,"discardidleconnectionsseconds":{"int":1}
,"(disabled)":{"org.quartz.datasource.name.driver":1}
,"java":{"class":1}
,"class":{"name":1}
,"jdbc":{"driver":1}
,"driver":{"database":1}
,"database":{"org.quartz.datasource.name.url":1,"org.quartz.datasource.name.user":1,"org.quartz.datasource.name.password":1,"org.quartz.datasource.name.maxconnections":1,"select":1,"sql":1}
,"connection":{"url":1,"database":1,"actually":1,"retrieved":1}
,"url":{"(host":1}
,"(host":{"port":1}
,"port":{"forth)":1}
,"forth)":{"connection":1}
,"user":{"name":1,"oracle":1}
,"connecting":{"database":1}
,"password":{"connecting":1}
,"org.quartz.datasource.name.maxconnections":{"maximum":1}
,"maximum":{"number":1}
,"number":{"connections":1,"seconds":1}
,"connections":{"datasource":1,"org.quartz.datasource.name.validationquery":1,"example":1,"applicable":1,"executed":1,"idle":1}
,"create":{"pool":1}
,"pool":{"connections":1,"ensure":1}
,"org.quartz.datasource.name.validationquery":{"optional":1}
,"optional":{"sql":1}
,"sql":{"query":1}
,"query":{"string":1,"fail":1,"property":1,"validate":1}
,"detect":{"replace":1}
,"replace":{"failed\u002Fcorrupt":1}
,"failed\u002Fcorrupt":{"connections":1}
,"example":{"user":1,"quartz-defined":1}
,"oracle":{"database":1}
,"select":{"table_name":1}
,"table_name":{"user_tables":1}
,"user_tables":{"query":1}
,"fail":{"unless":1}
,"unless":{"connection":1}
,"actually":{"bad":1}
,"bad":{"org.quartz.datasource.name.idleconnectionvalidationseconds":1}
,"org.quartz.datasource.name.idleconnectionvalidationseconds":{"number":1}
,"seconds":{"tests":1,"org.quartz.datasource.name.validateoncheckout":1,"disables":1}
,"tests":{"idle":1}
,"idle":{"connections":1,"seconds":1}
,"applicable":{"validation":1}
,"validation":{"query":1,"occur":1}
,"org.quartz.datasource.name.validateoncheckout":{"whether":1}
,"whether":{"database":1}
,"validate":{"connections":1}
,"executed":{"every":1}
,"every":{"time":1}
,"time":{"connection":1}
,"retrieved":{"pool":1}
,"ensure":{"valid":1}
,"valid":{"false":1}
,"occur":{"check-in":1}
,"check-in":{"default":1}
,"org.quartz.datasource.name.discardidleconnectionsseconds":{"discard":1}
,"discard":{"connections":1}
,"disables":{"feature":1}
,"feature":{"default":1}
,"quartz-defined":{"datasource":1}
,"org.quartz.datasource.myds.driver":{"=oracle.jdbc.driver.oracledriver":1}
,"=oracle.jdbc.driver.oracledriver":{"org.quartz.datasource.myds.url":1}
,"org.quartz.datasource.myds.url":{"=jdbc:oracle:thin:@10.0.1.23:1521:demodb":1}
,"=jdbc:oracle:thin:@10.0.1.23:1521:demodb":{"org.quartz.datasource.myds.user":1}
,"org.quartz.datasource.myds.user":{"=myuser":1}
,"=myuser":{"org.quartz.datasource.myds.password":1}
,"org.quartz.datasource.myds.password":{"=mypassword":1}
,"=mypassword":{"org.quartz.datasource.myds.maxconnections":1}
,"org.quartz.datasource.myds.maxconnections":{"=30":1}
}
;Search.control.loadWordPairs(pairs);
