var pairs =
{
"how-to":{"define":1}
,"define":{"job":1}
,"job":{"(with":1,"class":1,"{public":1,"public":1,"instance":1}
,"(with":{"input":1}
,"input":{"data)":1}
,"data)":{"job":1}
,"class":{"public":1,"printpropsjob":1,"contains":1}
,"public":{"class":1,"no-argument":1,"void":1}
,"printpropsjob":{"implements":1,"{\u002F\u002Finstances":1}
,"implements":{"job":1}
,"{public":{"printpropsjob":1}
,"{\u002F\u002Finstances":{"job":1}
,"no-argument":{"constructor":1}
,"constructor":{"public":1}
,"void":{"execute":1}
,"execute":{"(jobexecutioncontext":1,"method":1}
,"(jobexecutioncontext":{"context)":1}
,"context)":{"throws":1}
,"throws":{"jobexecutionexception":1}
,"jobexecutionexception":{"{jobdatamap":1}
,"{jobdatamap":{"data":1}
,"data":{"=context.getmergedjobdatamap":1}
,"=context.getmergedjobdatamap":{"system.out.println":1}
,"system.out.println":{"someprop":1}
,"someprop":{"data.getstring":1,"\u0022))":1,"somevalue":1}
,"data.getstring":{"someprop":1}
,"\u0022))":{"defining":1}
,"defining":{"job":1}
,"instance":{"\u002F\u002Fdefine":1,"jobdetail":1}
,"\u002F\u002Fdefine":{"job":1}
,"jobdetail":{"job1":1}
,"job1":{"=newjob":1,"group1":1}
,"=newjob":{"(myjobclass.class)":1}
,"(myjobclass.class)":{".withidentity":1}
,".withidentity":{"job1":1}
,"group1":{".usingjobdata":1}
,".usingjobdata":{"someprop":1}
,"somevalue":{".build":1}
,".build":{"note":1}
,"note":{"job":1}
,"contains":{"setter":1}
,"setter":{"methods":1,"method":1}
,"methods":{"match":1}
,"match":{"jobdatamap":1}
,"jobdatamap":{"keys":1,"value":1}
,"keys":{"(for":1}
,"(for":{"example":1}
,"example":{"setsomeprop":1,"above)":1}
,"setsomeprop":{"example":1}
,"above)":{"default":1}
,"default":{"jobfactory":1}
,"jobfactory":{"implementation":1}
,"implementation":{"quartz":1}
,"quartz":{"automatically":1}
,"automatically":{"call":1}
,"call":{"setter":1}
,"method":{"jobdatamap":1,"retrieve":1}
,"value":{"thus":1,"jobdatamap":1}
,"thus":{"need":1}
,"need":{"include":1}
,"include":{"code":1}
,"code":{"job\u0027s":1}
,"job\u0027s":{"execute":1}
,"retrieve":{"value":1}
}
;Search.control.loadWordPairs(pairs);
