var pairs =
{
"scheduler":{"factories":1,"properties":1,"initialize":1,"example":1,"instance":1,"(2)":1}
,"factories":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"implementation":1}
,"implementation":{"org.quartz.schedulerfactory":1,"useful":1}
,"org.quartz.schedulerfactory":{"interface":1}
,"interface":{"uses":1,"sample":1}
,"uses":{"properties":1}
,"properties":{"(java.util.properties)":1,"generally":1}
,"(java.util.properties)":{"create":1}
,"create":{"initialize":1,"scheduler":1}
,"initialize":{"quartz":1,"(and":1}
,"quartz":{"scheduler":1,"distribution":1}
,"generally":{"stored":1,"discouraged":1}
,"stored":{"loaded":1}
,"loaded":{"file":1}
,"file":{"created":1}
,"created":{"program":1}
,"program":{"handed":1}
,"handed":{"directly":1}
,"directly":{"factory":1}
,"factory":{"simply":1,"produce":1}
,"simply":{"calling":1}
,"calling":{"getscheduler":1}
,"getscheduler":{"factory":1}
,"produce":{"scheduler":1}
,"(and":{"threadpool":1}
,"threadpool":{"jobstore":1}
,"jobstore":{"datasources)":1}
,"datasources)":{"return":1}
,"return":{"handle":1}
,"handle":{"public":1}
,"public":{"interface":1}
,"sample":{"configurations":1,"code.ffc-don":1}
,"configurations":{"(including":1}
,"(including":{"descriptions":1}
,"descriptions":{"properties)":1}
,"properties)":{"docs\u002Fconfig":1}
,"docs\u002Fconfig":{"directory":1}
,"directory":{"quartz":1}
,"distribution":{"find":1}
,"find":{"complete":1}
,"complete":{"documentation":1}
,"documentation":{"document":1}
,"document":{"quartz":1}
,"example":{"programs":1}
,"programs":{"sample":1}
,"code.ffc-don":{"added":1}
,"added":{"book":1}
,"book":{"title":1}
,"title":{"manually":1}
,"manually":{"cite":1}
,"cite":{"tag":1}
,"tag":{"future":1}
,"future":{"change":1}
,"change":{"conref":1}
,"conref":{"directschedulerfactory":1}
,"directschedulerfactory":{"directschedulerfactory":1,"schedulerfactory":1}
,"schedulerfactory":{"implementation":1}
,"useful":{"want":1}
,"want":{"create":1}
,"instance":{"programmatic":1}
,"programmatic":{"generally":1}
,"discouraged":{"following":1}
,"following":{"reasons":1}
,"reasons":{"(1)":1}
,"(1)":{"requires":1}
,"requires":{"in-depth":1}
,"in-depth":{"understanding":1}
,"understanding":{"scheduler":1}
,"(2)":{"allow":1}
,"allow":{"declarative":1}
,"declarative":{"configuration":1}
,"configuration":{"(meaning":1}
,"(meaning":{"hard-code":1}
,"hard-code":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"settings)":1}
}
;Search.control.loadWordPairs(pairs);
