var pairs =
{
"how-to":{"initialize":1}
,"initialize":{"scheduler":1}
,"scheduler":{"within":1,"servlet":1}
,"within":{"servlet":1}
,"servlet":{"container":1,"web.xml":1}
,"container":{"two":1,"shown":1}
,"two":{"approaches":1}
,"approaches":{"initializing":1}
,"initializing":{"scheduler":1}
,"shown":{"below":1}
,"below":{"cases":1}
,"cases":{"sure":1}
,"sure":{"look":1}
,"look":{"javadoc":1}
,"javadoc":{"related":1}
,"related":{"classes":1}
,"classes":{"understand":1}
,"understand":{"possible":1}
,"possible":{"configuration":1,"parameters":1}
,"configuration":{"parameters":1}
,"parameters":{"following":1,"adding":1}
,"following":{"examples":1}
,"examples":{"show":1}
,"show":{"possible":1}
,"adding":{"context\u002Fcontainer":1,"start-up":1}
,"context\u002Fcontainer":{"listener":1}
,"listener":{"web.xml":1}
,"web.xml":{"<context-param>":1,"<servlet>":1}
,"<context-param>":{"<param-name>":1}
,"<param-name>":{"quartz:config-file":1,"quartz:shutdown-on-unload":1,"quartz:wait-on-shutdown":1,"quartz:start-scheduler-on-load":1,"shutdown-on-unload":1}
,"quartz:config-file":{"<\u002Fparam-name>":1}
,"<\u002Fparam-name>":{"<param-value>\u002Fsome\u002Fpath\u002Fmy_quartz.properties":1,"<param-value>":1}
,"<param-value>\u002Fsome\u002Fpath\u002Fmy_quartz.properties":{"<\u002Fparam-value>":1}
,"<\u002Fparam-value>":{"<\u002Fcontext-param>":1,"<\u002Finit-param>":1}
,"<\u002Fcontext-param>":{"<context-param>":1,"<listener>":1}
,"quartz:shutdown-on-unload":{"<\u002Fparam-name>":1}
,"<param-value>":{"true":1,"false":1}
,"true":{"<\u002Fparam-value>":1}
,"quartz:wait-on-shutdown":{"<\u002Fparam-name>":1}
,"false":{"<\u002Fparam-value>":1}
,"quartz:start-scheduler-on-load":{"<\u002Fparam-name>":1}
,"<listener>":{"<listener-class>":1}
,"<listener-class>":{"org.quartz.ee.servlet.quartzinitializerlistener":1}
,"org.quartz.ee.servlet.quartzinitializerlistener":{"<\u002Flistener-class>":1}
,"<\u002Flistener-class>":{"<\u002Flistener>":1}
,"<\u002Flistener>":{"adding":1}
,"start-up":{"servlet":1}
,"<servlet>":{"<servlet-name>":1}
,"<servlet-name>":{"quartzinitializer":1}
,"quartzinitializer":{"<\u002Fservlet-name>":1}
,"<\u002Fservlet-name>":{"<servlet-class>":1}
,"<servlet-class>":{"org.quartz.ee.servlet.quartzinitializerservlet":1}
,"org.quartz.ee.servlet.quartzinitializerservlet":{"<\u002Fservlet-class>":1}
,"<\u002Fservlet-class>":{"<init-param>":1}
,"<init-param>":{"<param-name>":1}
,"shutdown-on-unload":{"<\u002Fparam-name>":1}
,"<\u002Finit-param>":{"<load-on-startup>":1}
,"<load-on-startup>":{"<\u002Fload-on-startup>":1}
,"<\u002Fload-on-startup>":{"<\u002Fservlet>":1}
}
;Search.control.loadWordPairs(pairs);
