var pairs =
{
"exposing":{"scheduler":1}
,"scheduler":{"applications":1,"functionality":1}
,"applications":{"careful":1}
,"careful":{"security":1}
,"security":{"users":1}
,"users":{"expose":1,"define":1,"control":1}
,"expose":{"quartz\u0027s":1}
,"quartz\u0027s":{"scheduler":1}
,"functionality":{"application":1}
,"application":{"user":1}
,"user":{"interface":1}
,"interface":{"useful":1}
,"useful":{"extremely":1}
,"extremely":{"dangerous":1}
,"dangerous":{"sure":1}
,"sure":{"mistakenly":1}
,"mistakenly":{"allow":1}
,"allow":{"users":1}
,"define":{"jobs":1,"whatever":1}
,"jobs":{"type":1,"sendemailjob":1}
,"type":{"want":1}
,"want":{"whatever":1,"effectively":1}
,"whatever":{"parameters":1,"job":1}
,"parameters":{"choose":1}
,"choose":{"example":1}
,"example":{"quartz":1}
,"quartz":{"ships":1}
,"ships":{"pre-made":1}
,"pre-made":{"job":1}
,"job":{"org.quartz.jobs.nativejob":1,"want":1}
,"org.quartz.jobs.nativejob":{"execute":1}
,"execute":{"arbitrary":1}
,"arbitrary":{"native":1}
,"native":{"(operating":1}
,"(operating":{"system)":1}
,"system)":{"system":1}
,"system":{"command":1,"likewise":1,"sorts":1}
,"command":{"defined":1,"injection":1}
,"defined":{"malicious":1,"owasp":1}
,"malicious":{"users":1,"intent":1}
,"control":{"destroy":1}
,"destroy":{"system":1}
,"likewise":{"jobs":1}
,"sendemailjob":{"virtually":1}
,"virtually":{"others":1}
,"others":{"used":1}
,"used":{"malicious":1}
,"intent":{"aware":1}
,"aware":{"allowing":1}
,"allowing":{"users":1}
,"effectively":{"opens":1}
,"opens":{"system":1}
,"sorts":{"vulnerabilities":1}
,"vulnerabilities":{"comparable":1}
,"comparable":{"equivalent":1}
,"equivalent":{"command":1}
,"injection":{"attacks":1}
,"attacks":{"defined":1}
,"owasp":{"mitre":1}
}
;Search.control.loadWordPairs(pairs);
