var pairs =
{
"questions":{"triggers":1}
,"triggers":{"chain":1,"quartz":1,"fire":1,"second":1,"crontrigger":1}
,"chain":{"job":1,"triggers":1}
,"job":{"execution":1,"follows":1,"contains":1,"fire":1,"completes":1,"schedule":1,"several":1,"knows":1,"name":1,"abstract":1,"class\u0027s":1,"simply":1,"usage":1,"chain)":1}
,"execution":{"create":1}
,"create":{"workflow":1,"trigger":1}
,"workflow":{"currently":1}
,"currently":{"direct":1}
,"direct":{"free":1}
,"free":{"chain":1}
,"quartz":{"however":1,"already":1,"provide":1}
,"however":{"several":1,"implication":1,"depending":1,"firings":1,"rather":1}
,"several":{"ways":1,"users":1}
,"ways":{"accomplish":1}
,"accomplish":{"without":1}
,"without":{"effort":1,"creating":1}
,"effort":{"below":1}
,"below":{"outline":1}
,"outline":{"couple":1}
,"couple":{"approaches":1}
,"approaches":{"listener":1,"perhaps":1}
,"listener":{"triggerlistener":1,"job":1,"org.quartz.listeners.jobchainingjoblistener":1}
,"triggerlistener":{"joblistener":1}
,"joblistener":{"schedulerlistener)":1}
,"schedulerlistener)":{"notice":1}
,"notice":{"completion":1}
,"completion":{"job\u002Ftrigger":1}
,"job\u002Ftrigger":{"immediately":1}
,"immediately":{"schedule":1}
,"schedule":{"new":1,"next":1,"identified":1,"jobs":1,"simply":1,"particular":1}
,"new":{"trigger":1}
,"trigger":{"fire":1,"firing":1,"trigger":1,"group":1,"kept":1,"sunday":1,"may":1,"skipped":1,"types":1}
,"fire":{"approach":1,"job":1,"(other":1,"first":1,"every":1,"certain":1,"midnight":1,"hour":1,"time":1,"trigger":1}
,"approach":{"bit":1}
,"bit":{"involved":1}
,"involved":{"inform":1}
,"inform":{"listener":1}
,"follows":{"additionally":1}
,"additionally":{"need":1}
,"need":{"worry":1}
,"worry":{"persistence":1}
,"persistence":{"information":1}
,"information":{"listener":1}
,"org.quartz.listeners.jobchainingjoblistener":{"ships":1}
,"ships":{"quartz":1}
,"already":{"functionality":1,"occurred":1}
,"functionality":{"build":1}
,"build":{"job":1}
,"contains":{"within":1,"code":1}
,"within":{"jobdatamap":1}
,"jobdatamap":{"name":1,"using":1}
,"name":{"next":1,"group":1,"time":1}
,"next":{"job":1,"fire":1,"hour":1,"time":1}
,"completes":{"(the":1}
,"(the":{"last":1,"critical":1}
,"last":{"step":1}
,"step":{"execute":1}
,"execute":{"method)":1,"delegates":1}
,"method)":{"job":1}
,"users":{"doing":1,"simpletrigger":1}
,"doing":{"good":1}
,"good":{"luck":1}
,"luck":{"made":1}
,"made":{"base":1}
,"base":{"(abstract)":1}
,"(abstract)":{"class":1}
,"class":{"job":1,"included":1}
,"knows":{"job":1}
,"group":{"jobdatamap":1,"paused":1}
,"using":{"pre-defined":1}
,"pre-defined":{"keys":1}
,"keys":{"(constants)":1}
,"(constants)":{"contains":1}
,"code":{"schedule":1,"scheduling":1}
,"identified":{"job":1}
,"abstract":{"job\u0027s":1,"template":1}
,"job\u0027s":{"implementation":1}
,"implementation":{"execute":1}
,"delegates":{"abstract":1}
,"template":{"method":1}
,"method":{"dowork":1,"helps":1}
,"dowork":{"(where":1}
,"(where":{"extending":1}
,"extending":{"job":1}
,"class\u0027s":{"real":1}
,"real":{"work":1}
,"work":{"goes)":1,"job":1}
,"goes)":{"contains":1}
,"scheduling":{"follow-up":1}
,"follow-up":{"job":1}
,"simply":{"extensions":1,"keeps":1}
,"extensions":{"class":1}
,"included":{"work":1}
,"usage":{"\u0027durable":1}
,"\u0027durable":{"jobs":1}
,"jobs":{"overloaded":1,"once":1,"fire":1}
,"overloaded":{"addjob":1}
,"addjob":{"(jobdetail":1}
,"(jobdetail":{"boolean":1}
,"boolean":{"boolean)":1}
,"boolean)":{"method":1}
,"helps":{"application":1}
,"application":{"define":1}
,"define":{"jobs":1}
,"once":{"proper":1,"firing":1}
,"proper":{"data":1}
,"data":{"without":1}
,"creating":{"triggers":1,"schedules":1}
,"(other":{"trigger":1}
,"first":{"job":1,"review":1,"time":1}
,"chain)":{"future":1}
,"future":{"quartz":1}
,"provide":{"cleaner":1}
,"cleaner":{"until":1}
,"until":{"you\u0027ll":1}
,"you\u0027ll":{"above":1}
,"above":{"approaches":1}
,"perhaps":{"devise":1}
,"devise":{"works":1}
,"works":{"better":1}
,"better":{"isn\u0027t":1}
,"isn\u0027t":{"trigger":1}
,"firing":{"common":1,"triggers":1,"every":1,"say":1,"appears":1,"exactly":1,"trigger":1,"saturday":1,"time":1,"firing":1,"twice":1}
,"common":{"reason":1}
,"reason":{"having":1,"trigger":1,"depending":1}
,"having":{"called":1,"fire":1}
,"called":{"scheduler.start":1}
,"scheduler.start":{"tells":1}
,"tells":{"scheduler":1}
,"scheduler":{"start":1}
,"start":{"firing":1}
,"second":{"common":1}
,"paused":{"daylight":1}
,"daylight":{"saving":1,"savings":1,"event":1}
,"saving":{"time":1}
,"time":{"triggers":1,"first":1,"please":1,"started":1,"shift":1,"1:00":1,"order":1,"humans":1,"switches":1,"interval":1,"depends":1,"trigger":1,"ends":1,"triggerings":1,"2:00":1,"day":1,"fire":1,"occur":1,"occurs":1,"computes":1,"shifted":1}
,"crontrigger":{"simpletrigger":1,"allows":1,"respect":1,"fires":1}
,"simpletrigger":{"handle":1,"allows":1,"firing":1,"always":1}
,"handle":{"daylight":1}
,"savings":{"time":1,"switches":1,"4:00":1,"event":1,"think":1,"events":1}
,"review":{"daylight":1}
,"please":{"read":1}
,"read":{"resource":1}
,"resource":{"https:\u002F\u002Fsecure.wikimedia.org\u002Fwikipedia\u002Fen\u002Fwiki\u002Fdaylight_saving_time_around_the_world":1}
,"https:\u002F\u002Fsecure.wikimedia.org\u002Fwikipedia\u002Fen\u002Fwiki\u002Fdaylight_saving_time_around_the_world":{"readers":1}
,"readers":{"may":1}
,"may":{"unaware":1,"firing":1,"skipped":1,"appear":1}
,"unaware":{"rules":1}
,"rules":{"different":1,"mind":1}
,"different":{"different":1,"nations":1,"locals":1,"places":1}
,"nations":{"example":1}
,"example":{"2005":1}
,"2005":{"daylight":1}
,"started":{"united":1}
,"united":{"states":1}
,"states":{"april":1,"daylight":1}
,"april":{"egypt":1,"important":1}
,"egypt":{"april":1}
,"important":{"know":1}
,"know":{"starting":1}
,"starting":{"dates":1}
,"dates":{"different":1}
,"locals":{"time":1}
,"shift":{"different":1,"2:00":1,"time":1}
,"places":{"shift":1}
,"2:00":{"others":1,"crontrigger":1,"arrives":1,"hence":1}
,"others":{"shift":1,"3:00":1,"right":1}
,"1:00":{"others":1,"again":1}
,"3:00":{"others":1,"3:00":1,"daylight":1,"(the":1}
,"right":{"midnight":1}
,"midnight":{"simpletrigger":1,"3:00":1}
,"allows":{"schedule":1}
,"every":{"milliseconds":1,"seconds":1,"minutes":1,"hour":1,"hours":1,"day":1}
,"milliseconds":{"nothing":1,"regardless":1,"just":1}
,"nothing":{"particular":1}
,"particular":{"respect":1,"sunday":1,"daylight":1}
,"respect":{"daylight":1,"gregorian":1}
,"order":{"stay":1}
,"stay":{"schedule":1}
,"keeps":{"firing":1}
,"regardless":{"simpletrigger":1}
,"seconds":{"every":1,"relation":1}
,"minutes":{"every":1}
,"hour":{"every":1,"two":1,"time":1,"already":1,"triggerings":1}
,"hours":{"continue":1,"daylight":1,"instead":1,"respectively":1}
,"continue":{"however":1}
,"implication":{"confuses":1}
,"confuses":{"users":1}
,"say":{"every":1,"united":1}
,"switches":{"may":1,"continue":1}
,"appears":{"3:00":1}
,"4:00":{"4:00":1,"actually":1}
,"actually":{"bug":1}
,"bug":{"trigger":1}
,"kept":{"firing":1}
,"exactly":{"every":1}
,"just":{"name":1}
,"humans":{"impose":1}
,"impose":{"moment":1}
,"moment":{"changed":1}
,"changed":{"crontrigger":1}
,"certain":{"moments":1}
,"moments":{"respect":1}
,"gregorian":{"calendar":1}
,"calendar":{"hence":1,"(rather":1}
,"hence":{"create":1,"next":1}
,"day":{"10:00":1,"2:15":1,"beginning":1,"crontrigger":1,"day":1,"daylight":1,"computes":1,"trigger":1,"fires":1,"fire":1}
,"10:00":{"daylight":1,"firing":1,"hours":1}
,"depending":{"whether":1,"trigger\u0027s":1}
,"whether":{"spring":1}
,"spring":{"autumn":1}
,"autumn":{"daylight":1}
,"event":{"particular":1,"trigger":1}
,"sunday":{"actual":1,"morning":1}
,"actual":{"time":1}
,"interval":{"firing":1}
,"morning":{"10:00":1}
,"saturday":{"morning":1}
,"instead":{"hours":1}
,"respectively":{"additional":1}
,"additional":{"point":1}
,"point":{"understand":1}
,"understand":{"crontrigger":1}
,"think":{"carefully":1}
,"carefully":{"creating":1}
,"schedules":{"fire":1}
,"critical":{"window":1}
,"window":{"time":1}
,"depends":{"trigger\u0027s":1}
,"trigger\u0027s":{"locale":1,"schedule":1,"next":1}
,"locale":{"explained":1}
,"explained":{"above)":1}
,"above)":{"reason":1}
,"skipped":{"may":1,"2:15":1,"time":1}
,"appear":{"fire":1}
,"two":{"examples":1,"rules":1}
,"examples":{"say":1}
,"events":{"occur":1}
,"occur":{"2:00":1,"summary":1,"given":1}
,"fires":{"every":1,"exactly":1,"given":1,"once":1}
,"2:15":{"day":1,"occurs":1}
,"beginning":{"daylight":1}
,"occurs":{"day":1,"twice":1}
,"ends":{"hour":1}
,"triggerings":{"occur":1}
,"arrives":{"become":1}
,"become":{"1:00":1}
,"again":{"however":1}
,"firings":{"during":1}
,"during":{"o\u0027clock":1}
,"o\u0027clock":{"hour":1}
,"occurred":{"trigger\u0027s":1}
,"summary":{"makes":1}
,"makes":{"perfect":1}
,"perfect":{"sense":1}
,"sense":{"easy":1}
,"easy":{"remember":1}
,"remember":{"keep":1}
,"keep":{"two":1}
,"mind":{"simpletrigger":1}
,"always":{"fires":1}
,"relation":{"time":1}
,"given":{"time":1,"day":1}
,"computes":{"next":1}
,"twice":{"given":1,"end":1}
,"types":{"based":1}
,"based":{"sliding":1}
,"sliding":{"along":1}
,"along":{"calendar":1}
,"(rather":{"exact":1}
,"exact":{"amounts":1}
,"amounts":{"time)":1}
,"time)":{"calenderintervaltrigger":1}
,"calenderintervaltrigger":{"similarly":1}
,"similarly":{"affected":1}
,"affected":{"however":1}
,"rather":{"missing":1}
,"missing":{"firing":1}
,"end":{"having":1}
,"shifted":{"hour":1}
}
;Search.control.loadWordPairs(pairs);
