var pairs =
{
"general":{"questions":1}
,"questions":{"quartz":1}
,"quartz":{"quartz":1,"job":1,"scheduler":1,"quite":1,"light-weight":1,"fault-tolerant":1,"extremely":1,"realized":1,"grid":1,"-from":1,"distributed":1,"functionality":1,"process":1,"rather":1,"terracotta\u0027s":1,"terracotta":1,"team":1,"(and":1,"offers":1,"users":1,"known":1,"source":1,"ships":1,"cvs":1,"disable":1,"contains":1,"available":1,"fails":1,"logs":1,"config":1}
,"job":{"scheduling":1,"scheduler":1,"queue":1,"small":1,"execution":1,"interface":1}
,"scheduling":{"library":1,"(only":1}
,"library":{"integrated":1,"easily":1,"(.jar":1}
,"integrated":{"used":1}
,"used":{"along":1,"separately":1,"reasonable":1,"resource":1}
,"along":{"side":1}
,"side":{"virtually":1}
,"virtually":{"software":1}
,"software":{"system":1,"components":1,"component":1}
,"system":{"term":1,"restarts":1,"processes":1,"property":1,"environment":1}
,"term":{"job":1,"short":1}
,"scheduler":{"seems":1,"documentation":1,"service":1,"interface":1,"want":1,"project":1,"build":1}
,"seems":{"conjure":1,"natural":1}
,"conjure":{"different":1}
,"different":{"ideas":1,"people":1}
,"ideas":{"different":1}
,"people":{"quartz":1,"alterations":1}
,"documentation":{"give":1}
,"give":{"firm":1}
,"firm":{"idea":1}
,"idea":{"mean":1}
,"mean":{"term":1}
,"short":{"job":1}
,"service":{"component":1,"business":1}
,"component":{"responsible":1,"view":1}
,"responsible":{"executing":1}
,"executing":{"(or":1}
,"(or":{"notifying)":1}
,"notifying)":{"software":1}
,"components":{"pre-determined":1,"execution":1,"notified":1,"implement":1,"just":1}
,"pre-determined":{"(scheduled)":1}
,"(scheduled)":{"time":1}
,"time":{"arrives":1,"day":1,"quartz":1}
,"arrives":{"quartz":1,"components":1}
,"quite":{"flexible":1}
,"flexible":{"contains":1}
,"contains":{"multiple":1,"core":1,"method":1,"update":1}
,"multiple":{"usage":1}
,"usage":{"paradigms":1,"achieved":1}
,"paradigms":{"used":1}
,"separately":{"together":1}
,"together":{"order":1,"provide":1}
,"order":{"achieve":1}
,"achieve":{"desired":1}
,"desired":{"behavior":1}
,"behavior":{"enable":1}
,"enable":{"write":1}
,"write":{"code":1,"mechanism":1}
,"code":{"manner":1,"library":1}
,"manner":{"seems":1}
,"natural":{"project":1}
,"project":{"quartz":1,"november":1,"contributors":1}
,"light-weight":{"requires":1}
,"requires":{"little":1}
,"little":{"setup\u002Fconfiguration":1}
,"setup\u002Fconfiguration":{"actually":1}
,"actually":{"out-of-the-box":1}
,"out-of-the-box":{"needs":1}
,"needs":{"relatively":1}
,"relatively":{"basic":1}
,"basic":{"quartz":1}
,"fault-tolerant":{"persist":1}
,"persist":{"remember":1}
,"remember":{"scheduled":1,"organize":1}
,"scheduled":{"jobs":1,"fire-time":1}
,"jobs":{"system":1,"starting\u002Fstopping\u002Fpausing":1}
,"restarts":{"although":1}
,"although":{"quartz":1,"often":1}
,"extremely":{"useful":1}
,"useful":{"running":1}
,"running":{"certain":1}
,"certain":{"system":1,"simple":1}
,"processes":{"given":1,"isn\u2019t":1}
,"given":{"schedules":1}
,"schedules":{"full":1}
,"full":{"potential":1}
,"potential":{"quartz":1}
,"realized":{"learn":1}
,"learn":{"drive":1}
,"drive":{"flow":1}
,"flow":{"application\u0027s":1}
,"application\u0027s":{"business":1}
,"business":{"processes":1,"personnel":1}
,"isn\u2019t":{"quartz":1}
,"queue":{"although":1}
,"often":{"used":1}
,"reasonable":{"job":1}
,"small":{"scale":1,"java":1}
,"scale":{"quartz":1,"usage":1}
,"grid":{"computation":1}
,"computation":{"engine":1}
,"engine":{"however":1}
,"however":{"simple":1}
,"simple":{"small":1,"operations":1,"job":1,"applications":1}
,"achieved":{"effort":1}
,"effort":{"quartz":1}
,"execution":{"service":1,"implement":1}
,"personnel":{"code":1}
,"easily":{"embedded":1}
,"embedded":{"applications":1}
,"applications":{"need":1,"features":1}
,"need":{"capability":1}
,"capability":{"schedule":1}
,"schedule":{"application-related":1,"software":1}
,"application-related":{"tasks":1}
,"tasks":{"occur":1,"course":1}
,"occur":{"future":1}
,"future":{"recurring":1}
,"recurring":{"basis":1}
,"basis":{"quartz":1}
,"-from":{"software":1}
,"view":{"quartz":1}
,"distributed":{"small":1}
,"java":{"library":1,"built-in":1,"command":1}
,"(.jar":{"file)":1}
,"file)":{"contains":1}
,"core":{"quartz":1}
,"functionality":{"main":1,"scheduler":1}
,"main":{"interface":1,"quartz":1}
,"interface":{"(api)":1,"provides":1,"contains":1,"main":1}
,"(api)":{"functionality":1}
,"provides":{"simple":1}
,"operations":{"scheduling\u002Funscheduling":1}
,"scheduling\u002Funscheduling":{"jobs":1}
,"starting\u002Fstopping\u002Fpausing":{"scheduler":1}
,"want":{"schedule":1,"components":1,"look":1}
,"implement":{"simple":1,"either":1}
,"method":{"execute":1}
,"execute":{"want":1}
,"notified":{"scheduled":1}
,"fire-time":{"arrives":1}
,"either":{"triggerlistener":1}
,"triggerlistener":{"joblistener":1}
,"joblistener":{"interface":1}
,"process":{"started":1}
,"started":{"executed":1}
,"executed":{"within":1}
,"within":{"application":1,"j2ee":1}
,"application":{"stand-alone":1,"(with":1,"server":1}
,"stand-alone":{"application":1}
,"(with":{"rmi":1}
,"rmi":{"interface)":1}
,"interface)":{"within":1}
,"j2ee":{"application":1,"components":1}
,"server":{"used":1,"check":1}
,"resource":{"j2ee":1}
,"just":{"java.util.timer":1,"cron":1}
,"java.util.timer":{"jdk":1,"java.util.timertask":1}
,"jdk":{"1.3":1}
,"1.3":{"java":1}
,"built-in":{"timer":1}
,"timer":{"capabilities":1}
,"capabilities":{"java.util.timer":1}
,"java.util.timertask":{"classes":1}
,"classes":{"someone":1}
,"someone":{"quartz":1}
,"rather":{"standard":1}
,"standard":{"features":1}
,"features":{"reasons":1,"may":1,"services":1,"quartz":1}
,"reasons":{"few":1}
,"few":{"timers":1,"open":1}
,"timers":{"persistence":1,"inflexible":1,"don\u0027t":1,"real":1}
,"persistence":{"mechanism":1}
,"mechanism":{"timers":1,"remember":1}
,"inflexible":{"scheduling":1}
,"(only":{"able":1}
,"able":{"start-time":1}
,"start-time":{"&repeat":1}
,"&repeat":{"interval":1}
,"interval":{"nothing":1}
,"nothing":{"based":1}
,"based":{"dates":1}
,"dates":{"time":1}
,"day":{"forth.)":1}
,"forth.)":{"timers":1}
,"don\u0027t":{"utilize":1}
,"utilize":{"thread-pool":1}
,"thread-pool":{"(one":1}
,"(one":{"thread":1}
,"thread":{"per":1}
,"per":{"timer)":1}
,"timer)":{"timers":1}
,"real":{"management":1}
,"management":{"schemes":1}
,"schemes":{"write":1}
,"organize":{"retrieve":1}
,"retrieve":{"tasks":1}
,"course":{"certain":1}
,"may":{"important":1}
,"important":{"case":1}
,"case":{"right":1}
,"right":{"decision":1}
,"decision":{"quartz":1}
,"terracotta\u0027s":{"relationship":1}
,"relationship":{"quartz":1}
,"terracotta":{"acquired":1,"original":1,"brings":1,"offers":1}
,"acquired":{"quartz":1}
,"november":{"2009":1}
,"2009":{"terracotta":1}
,"original":{"quartz":1}
,"team":{"together":1}
,"provide":{"improved":1}
,"improved":{"features":1}
,"services":{"quartz":1,"available":1}
,"(and":{"always":1}
,"always":{"be)":1}
,"be)":{"open-source":1}
,"open-source":{"project":1}
,"contributors":{"around":1}
,"around":{"world":1}
,"world":{"terracotta":1}
,"brings":{"additional":1}
,"additional":{"expertise":1}
,"expertise":{"improving":1}
,"improving":{"advanced":1}
,"advanced":{"features":1}
,"offers":{"commercial":1,"great":1}
,"commercial":{"support":1}
,"support":{"services":1}
,"users":{"commercial":1,"available":1}
,"available":{"quartz":1,"alternatives":1,"download":1}
,"great":{"commercial":1}
,"alternatives":{"quartz":1}
,"known":{"competing":1}
,"competing":{"open":1}
,"open":{"source":1}
,"source":{"projects":1,"schedulers":1,"although":1}
,"projects":{"(there":1}
,"(there":{"few":1}
,"schedulers":{"basically":1}
,"basically":{"just":1}
,"cron":{"replacements":1}
,"replacements":{"written":1}
,"written":{"java)":1}
,"java)":{"commercially":1}
,"commercially":{"want":1}
,"look":{"well-regarded":1}
,"well-regarded":{"flux":1}
,"flux":{"scheduler":1}
,"build":{"quartz":1,"latest":1}
,"ships":{"pre-built":1,"quartz":1}
,"pre-built":{"people":1}
,"alterations":{"and\u002For":1}
,"and\u002For":{"build":1}
,"latest":{"\u0027non-released":1}
,"\u0027non-released":{"version":1}
,"version":{"quartz":1}
,"cvs":{"follow":1}
,"follow":{"instructions":1}
,"instructions":{"readme.txt":1}
,"readme.txt":{"file":1}
,"file":{"ships":1}
,"disable":{"update":1}
,"update":{"check":1,"found":1}
,"check":{"quartz":1,"feature":1,"new":1,"runs":1,"production":1}
,"feature":{"connects":1}
,"connects":{"server":1}
,"new":{"version":1}
,"download":{"check":1}
,"runs":{"asynchronously":1,"update":1}
,"asynchronously":{"affect":1}
,"affect":{"startup\u002Finitialization":1}
,"startup\u002Finitialization":{"time":1}
,"fails":{"gracefully":1}
,"gracefully":{"connection":1}
,"connection":{"cannot":1}
,"cannot":{"made":1}
,"made":{"check":1}
,"found":{"reported":1}
,"reported":{"available":1}
,"logs":{"disable":1}
,"config":{"property":1}
,"property":{"org.quartz.scheduler.skipupdatecheck":1,"org.terracotta.quartz.skipupdatecheck=true":1}
,"org.quartz.scheduler.skipupdatecheck":{"true":1}
,"true":{"system":1}
,"org.terracotta.quartz.skipupdatecheck=true":{"(which":1}
,"(which":{"system":1}
,"environment":{"java":1}
,"command":{"line)":1}
,"line)":{"recommended":1}
,"recommended":{"disable":1}
,"production":{"deployments":1}
}
;Search.control.loadWordPairs(pairs);
