var pairs =
{
"listeners":{"tips":1,"notified":1}
,"tips":{"(triggerlistener":1}
,"(triggerlistener":{"joblistener":1}
,"joblistener":{"schedulerlistener":1}
,"schedulerlistener":{"keep":1}
,"keep":{"listener":1}
,"listener":{"code":1,"handle":1,"method":1,"throws":1}
,"code":{"concise":1}
,"concise":{"efficient":1}
,"efficient":{"performing":1}
,"performing":{"large":1}
,"large":{"amounts":1}
,"amounts":{"work":1}
,"work":{"discouraged":1}
,"discouraged":{"thread":1}
,"thread":{"executing":1}
,"executing":{"job":1}
,"job":{"(or":1}
,"(or":{"completing":1}
,"completing":{"trigger":1}
,"trigger":{"moving":1}
,"moving":{"firing":1}
,"firing":{"job)":1}
,"job)":{"tied":1}
,"tied":{"within":1}
,"within":{"listener":1}
,"handle":{"exceptions":1}
,"exceptions":{"every":1,"listener":1}
,"every":{"listener":1}
,"method":{"contain":1}
,"contain":{"try-catch":1}
,"try-catch":{"block":1}
,"block":{"handles":1}
,"handles":{"possible":1}
,"possible":{"exceptions":1}
,"throws":{"exception":1}
,"exception":{"may":1}
,"may":{"cause":1}
,"cause":{"listeners":1}
,"notified":{"and\u002For":1}
,"and\u002For":{"prevent":1}
,"prevent":{"execution":1}
,"execution":{"job":1}
}
;Search.control.loadWordPairs(pairs);
