var pairs =
{
"using":{"systempropertyinstanceidgenerator":1}
,"systempropertyinstanceidgenerator":{"org.quartz.simpl.systempropertyinstanceidgenerator":1}
,"org.quartz.simpl.systempropertyinstanceidgenerator":{"useful":1}
,"useful":{"environments":1}
,"environments":{"initialization":1}
,"initialization":{"scripts":1}
,"scripts":{"configuration":1}
,"configuration":{"files":1,"resource":1}
,"files":{"example":1}
,"example":{"add":1,"configured":1}
,"add":{"instanceid":1}
,"instanceid":{"property":1}
,"property":{"application":1,"values":1}
,"application":{"server\u0027s":1}
,"server\u0027s":{"startup":1}
,"startup":{"script":1}
,"script":{"form":1}
,"form":{"-dorg.quartz.scheduler.instanceid=node1":1}
,"-dorg.quartz.scheduler.instanceid=node1":{"node1":1}
,"node1":{"instance":1,"node2":1}
,"instance":{"assigned":1,"used":1,"ids":1}
,"assigned":{"local":1}
,"local":{"quartz":1}
,"quartz":{"scheduler":1}
,"scheduler":{"scheduler":1,"added":1,"instance":1}
,"added":{"configuration":1}
,"resource":{"xml":1}
,"xml":{"file":1}
,"file":{"used":1}
,"used":{"environment":1,"quartzlocality.properties":1}
,"environment":{"instanceid":1}
,"values":{"configured":1}
,"configured":{"scheduler":1,"instance":1}
,"quartzlocality.properties":{"node":1}
,"node":{"groups":1}
,"groups":{"example":1,"org.quartz.locality.nodegroup.group1":1}
,"ids":{"node1":1,"node":1}
,"node2":{"node3":1,"org.quartz.locality.nodegroup.allnodes":1}
,"node3":{"ids":1}
,"org.quartz.locality.nodegroup.group1":{"=node1":1}
,"=node1":{"node2":1}
,"org.quartz.locality.nodegroup.allnodes":{"=node1":1}
}
;Search.control.loadWordPairs(pairs);
