var pairs =
{
"questions":{"spring":1}
,"spring":{"i\u0027m":1,"community":1,"defaults":1}
,"i\u0027m":{"using":1,"seeing":1}
,"using":{"quartz":1}
,"quartz":{"via":1,"property":1,"turn":1}
,"via":{"spring\u0027s":1}
,"spring\u0027s":{"scheduler":1}
,"scheduler":{"wrappers":1}
,"wrappers":{"need":1}
,"need":{"help":1}
,"help":{"consult":1}
,"consult":{"spring":1}
,"community":{"i\u0027m":1}
,"seeing":{"triggers":1}
,"triggers":{"stuck":1}
,"stuck":{"acquired":1}
,"acquired":{"state":1}
,"state":{"weird":1,"fix":1}
,"weird":{"data":1}
,"data":{"problems":1,"inconsistencies":1}
,"problems":{"spring":1,"relating":1}
,"defaults":{"quartz":1}
,"property":{"org.quartz.jobstore.dontsetautocommitfalse":1,"false":1}
,"org.quartz.jobstore.dontsetautocommitfalse":{"true":1,"property":1}
,"true":{"means":1}
,"means":{"quartz":1}
,"turn":{"auto-commit":1}
,"auto-commit":{"mode":1,"you\u0027ll":1}
,"mode":{"database":1}
,"database":{"connections":1}
,"connections":{"uses":1}
,"uses":{"opposite":1}
,"opposite":{"quartz\u0027s":1}
,"quartz\u0027s":{"default":1}
,"default":{"setting":1}
,"setting":{"connection":1}
,"connection":{"defaulting":1}
,"defaulting":{"auto-commit":1}
,"you\u0027ll":{"run":1}
,"run":{"sorts":1}
,"sorts":{"strange":1}
,"strange":{"problems":1}
,"relating":{"data":1}
,"inconsistencies":{"common":1}
,"common":{"symptom":1}
,"symptom":{"triggers":1}
,"fix":{"problem":1}
,"problem":{"org.quartz.jobstore.dontsetautocommitfalse":1}
}
;Search.control.loadWordPairs(pairs);
