var pairs =
{
"how-to":{"multiple":1}
,"multiple":{"(non-clustered)":1,"properties":1,"schedulers":1}
,"(non-clustered)":{"schedulers":1}
,"schedulers":{"reasons":1,"within":1,"course":1,"schedule":1,"jobs":1}
,"reasons":{"want":1}
,"want":{"managing":1,"scheduler":1,"look":1,"particular":1,"jobs":1}
,"managing":{"resources":1}
,"resources":{"example":1,"overwhelmed":1}
,"example":{"mix":1,"ramjobstore":1,"app":1}
,"mix":{"light-weight":1}
,"light-weight":{"heavy-weight":1}
,"heavy-weight":{"jobs":1}
,"jobs":{"want":1,"few":1,"doing":1,"concurrently":1,"application":1,"run":1,"(based":1,"(or":1,"placed":1,"execute":1,"(that":1,"example":1,"scheduled":1}
,"scheduler":{"threads":1,"names":1,"name":1,"remote":1,"needs":1,"unless":1,"run":1,"(s)":1,"instance":1,"(with":1,"scheduler":1,"app":1,"started":1}
,"threads":{"service":1,"jdbc-jobstore":1,"start":1}
,"service":{"lightweight":1,"heavy-weight":1}
,"lightweight":{"jobs":1}
,"few":{"threads":1}
,"doing":{"keep":1,"cause":1}
,"keep":{"machine\u2019s":1}
,"machine\u2019s":{"resources":1}
,"overwhelmed":{"running":1}
,"running":{"heavy-weight":1,"(start":1}
,"concurrently":{"schedule":1}
,"schedule":{"jobs":1,"(and":1}
,"application":{"execute":1,"unique":1,"executed":1,"following":1,"app":1,"instantiate":1}
,"execute":{"within":1,"scheduler.start":1,"jobs":1}
,"within":{"(when":1,"application":1,"process":1}
,"(when":{"using":1}
,"using":{"jdbc-jobstore)":1}
,"jdbc-jobstore)":{"note":1}
,"note":{"create":1}
,"create":{"schedulers":1,"scheduler":1}
,"unique":{"scheduler":1}
,"names":{"(typically":1}
,"(typically":{"defined":1}
,"defined":{"quartz.properties":1}
,"quartz.properties":{"file)":1,"run":1}
,"file)":{"means":1}
,"means":{"you\u0027ll":1}
,"you\u0027ll":{"need":1}
,"need":{"multiple":1,"specify":1,"run":1}
,"properties":{"files":1}
,"files":{"means":1}
,"specify":{"initialize":1}
,"initialize":{"stdschedulerfactory":1}
,"stdschedulerfactory":{"(as":1}
,"(as":{"defaults":1}
,"defaults":{"finding":1}
,"finding":{"quartz.properties":1}
,"run":{"multiple":1,"particular":1,"either":1,"local":1,"scheduler":1}
,"course":{"distinct":1}
,"distinct":{"characteristics":1,"scheduler":1}
,"characteristics":{"example":1}
,"ramjobstore":{"100":1}
,"100":{"worker":1}
,"worker":{"threads":1}
,"jdbc-jobstore":{"worker":1,"want":1}
,"start":{"(scheduler.start":1,"processing":1,"waiting":1,"scheduler":1}
,"(scheduler.start":{"())":1}
,"())":{"non-clustered":1}
,"non-clustered":{"instance":1}
,"instance":{"against":1,"scheduler":1,"start":1,"used":1}
,"against":{"database":1,"doing":1}
,"database":{"tables":1}
,"tables":{"instance":1,"prefixed":1}
,"name":{"running":1}
,"(start":{"ed)":1}
,"ed)":{"against":1}
,"cause":{"data":1}
,"data":{"corruption":1}
,"corruption":{"erratic":1}
,"erratic":{"behavior":1}
,"behavior":{"scheduling":1}
,"scheduling":{"jobs":1}
,"executed":{"application":1}
,"following":{"information":1}
,"information":{"applies":1}
,"applies":{"jdbc-jobstore":1}
,"look":{"rmi":1,"terracotta":1}
,"rmi":{"jmx":1}
,"jmx":{"features":1}
,"features":{"control":1,"currently":1,"suppose":1}
,"control":{"scheduler":1}
,"remote":{"process":1,"machine":1}
,"process":{"works":1,"want":1}
,"works":{"jobstore":1}
,"jobstore":{"additionally":1}
,"additionally":{"want":1}
,"terracotta":{"quartz":1}
,"quartz":{"features":1}
,"currently":{"want":1}
,"particular":{"jobs":1,"scheduler":1}
,"needs":{"distinct":1,"schedule":1}
,"unless":{"terracotta":1}
,"suppose":{"application":1}
,"app":{"needs":1,"create":1,"execute":1,"app":1,"schedule":1}
,"(based":{"user":1}
,"user":{"input)":1}
,"input)":{"need":1}
,"either":{"local":1}
,"local":{"process\u002Fmachine":1,"machine":1}
,"process\u002Fmachine":{"machine":1}
,"machine":{"(for":1,"machine":1,"achieved":1}
,"(for":{"simple":1,"complex":1}
,"simple":{"jobs)":1}
,"jobs)":{"remote":1,"possible":1,"however":1}
,"complex":{"jobs)":1}
,"possible":{"within":1}
,"instantiate":{"two":1}
,"two":{"(or":1}
,"(or":{"more)":1}
,"more)":{"schedulers":1}
,"placed":{"scheduler":1}
,"achieved":{"calling":1}
,"calling":{"scheduler.start":1}
,"scheduler.start":{"scheduler":1,"causes":1}
,"(s)":{"within":1}
,"causes":{"scheduler":1}
,"processing":{"jobs":1}
,"(that":{"start":1}
,"waiting":{"trigger-fire":1}
,"trigger-fire":{"times":1}
,"times":{"arrive":1}
,"arrive":{"executing":1}
,"executing":{"jobs)":1}
,"however":{"non-started":1}
,"non-started":{"scheduler":1}
,"used":{"schedule":1}
,"(and":{"retrieve)":1}
,"retrieve)":{"jobs":1}
,"(with":{"config":1}
,"config":{"points":1}
,"points":{"database":1}
,"prefixed":{"invoke":1}
,"invoke":{"start":1}
,"scheduled":{"scheduler":1}
,"started":{"app":1}
}
;Search.control.loadWordPairs(pairs);
