var pairs =
{
"clustering":{"clustering":1,"currently":1,"jobstoretx":1,"setting":1,"separate":1,"terracottajobstore":1,"may":1}
,"currently":{"works":1}
,"works":{"jdbc-jobstore":1}
,"jdbc-jobstore":{"(jobstoretx":1}
,"(jobstoretx":{"jobstorecmt)":1}
,"jobstorecmt)":{"terracottajobstore":1}
,"terracottajobstore":{"features":1,"simply":1,"described":1,"scheduler":1,"provides":1}
,"features":{"include":1,"persistence":1,"allow":1}
,"include":{"load-balancing":1}
,"load-balancing":{"job":1}
,"job":{"fail-over":1,"firing":1,"repeating":1,"12:00:10":1,"won\u0027t":1}
,"fail-over":{"(if":1}
,"(if":{"jobdetail\u0027s":1}
,"jobdetail\u0027s":{"request":1}
,"request":{"recovery":1}
,"recovery":{"flag":1}
,"flag":{"true)":1}
,"true)":{"clustering":1}
,"jobstoretx":{"jobstorecmt":1}
,"jobstorecmt":{"enable":1}
,"enable":{"clustering":1}
,"setting":{"org.quartz.jobstore.isclustered":1}
,"org.quartz.jobstore.isclustered":{"property":1}
,"property":{"true":1,"node":1,"run":1}
,"true":{"instance":1}
,"instance":{"cluster":1,"against":1,"running":1}
,"cluster":{"copy":1,"unique":1,"nodes":1}
,"copy":{"quartz.properties":1}
,"quartz.properties":{"file":1}
,"file":{"exceptions":1}
,"exceptions":{"properties":1,"different":1}
,"properties":{"files":1,"files)":1}
,"files":{"identical":1}
,"identical":{"following":1}
,"following":{"allowable":1}
,"allowable":{"exceptions":1}
,"different":{"thread":1,"value":1,"properties":1}
,"thread":{"pool":1}
,"pool":{"size":1}
,"size":{"different":1}
,"value":{"org.quartz.scheduler.instanceid":1,"property":1}
,"org.quartz.scheduler.instanceid":{"property":1}
,"node":{"cluster":1,"fire":1,"run":1,"time":1,"runs":1,"just":1}
,"unique":{"instanceid":1}
,"instanceid":{"easily":1}
,"easily":{"done":1}
,"done":{"(without":1}
,"(without":{"needing":1}
,"needing":{"different":1}
,"files)":{"placing":1}
,"placing":{"auto":1}
,"auto":{"value":1}
,"run":{"clustering":1,"job":1}
,"separate":{"machines":1}
,"machines":{"unless":1}
,"unless":{"clocks":1}
,"clocks":{"synchronized":1,"within":1}
,"synchronized":{"using":1}
,"using":{"form":1}
,"form":{"time-sync":1}
,"time-sync":{"service":1}
,"service":{"daemon":1}
,"daemon":{"runs":1}
,"runs":{"regularly":1,"load":1}
,"regularly":{"(the":1}
,"(the":{"clocks":1}
,"within":{"second":1}
,"second":{"other)":1}
,"other)":{"http:\u002F\u002Fwww.boulder.nist.gov\u002Ftimefreq\u002Fservice\u002Fits.htm":1}
,"http:\u002F\u002Fwww.boulder.nist.gov\u002Ftimefreq\u002Fservice\u002Fits.htm":{"unfamiliar":1}
,"unfamiliar":{"fire-up":1}
,"fire-up":{"non-clustered":1}
,"non-clustered":{"instance":1}
,"against":{"tables":1,"may":1}
,"tables":{"instance":1}
,"running":{"against":1,"array":1}
,"may":{"serious":1,"want":1}
,"serious":{"data":1}
,"data":{"corruption":1}
,"corruption":{"experience":1}
,"experience":{"erratic":1}
,"erratic":{"behavior":1}
,"behavior":{"node":1}
,"fire":{"job":1,"every":1}
,"firing":{"example":1}
,"example":{"job":1}
,"repeating":{"trigger":1}
,"trigger":{"tells":1}
,"tells":{"fire":1}
,"every":{"seconds":1}
,"seconds":{"12:00:00":1}
,"12:00:00":{"exactly":1}
,"exactly":{"node":1}
,"12:00:10":{"exactly":1}
,"won\u0027t":{"necessarily":1}
,"necessarily":{"node":1}
,"time":{"-it":1}
,"-it":{"less":1}
,"less":{"random":1}
,"random":{"node":1}
,"load":{"balancing":1}
,"balancing":{"mechanism":1}
,"mechanism":{"near-random":1}
,"near-random":{"busy":1}
,"busy":{"schedulers":1}
,"schedulers":{"(lots":1,"clustering":1}
,"(lots":{"triggers)":1}
,"triggers)":{"favors":1,"schedulers":1}
,"favors":{"node":1}
,"just":{"just":1,"active":1}
,"active":{"non-busy":1}
,"non-busy":{"(e.g":1}
,"(e.g":{"two":1}
,"two":{"triggers)":1}
,"simply":{"configure":1}
,"configure":{"scheduler":1}
,"scheduler":{"terracottajobstore":1,"clustering":1}
,"described":{"terracottajobstore":1}
,"want":{"consider":1}
,"consider":{"implications":1}
,"implications":{"setup":1}
,"setup":{"terracotta":1}
,"terracotta":{"server":1,"servers":1}
,"server":{"particularly":1}
,"particularly":{"configuration":1}
,"configuration":{"options":1}
,"options":{"turn":1}
,"turn":{"features":1}
,"persistence":{"running":1}
,"array":{"terracotta":1}
,"servers":{"licensed":1}
,"licensed":{"edition":1}
,"edition":{"terracottajobstore":1}
,"provides":{"advanced":1}
,"advanced":{"quartz":1}
,"quartz":{"features":1}
,"allow":{"intelligent":1}
,"intelligent":{"targeting":1}
,"targeting":{"jobs":1}
,"jobs":{"appropriate":1}
,"appropriate":{"cluster":1}
}
;Search.control.loadWordPairs(pairs);
