var pairs =
{
"configuring":{"quartz":1}
,"quartz":{"scheduler":1}
,"scheduler":{"configure":1,"follow":1,"intend":1,"code":1}
,"configure":{"quartz":1,"implementation":1,"node":1}
,"follow":{"steps":1}
,"steps":{"edit":1}
,"edit":{"quartz.properties":1}
,"quartz.properties":{"cluster":1,"quartz":1}
,"cluster":{"terracotta":1}
,"terracotta":{"details":1,"clustering":1}
,"details":{"adding":1}
,"adding":{"terracotta":1}
,"clustering":{"quartz":1}
,"intend":{"node":1}
,"node":{"groups":1,"ids":1,"trigger":1}
,"groups":{"configure":1,"quartzlocality.properties":1,"referenced":1,"whose":1,"example":1}
,"implementation":{"org.quartz.spi.instanceidgenerator":1}
,"org.quartz.spi.instanceidgenerator":{"generate":1}
,"generate":{"instance":1}
,"instance":{"ids":1}
,"ids":{"used":1,"understanding":1,"configure":1,"org.quartz.locality.nodegroup.slowjobs":1}
,"used":{"locality":1}
,"locality":{"configuration":1}
,"configuration":{"information":1}
,"information":{"generating":1}
,"generating":{"instance":1}
,"understanding":{"generated":1}
,"generated":{"node":1}
,"trigger":{"groups":1,"trigger":1,"group":1}
,"quartzlocality.properties":{"example":1,"classpath":1}
,"example":{"node":1,"trigger":1,"quartz":1}
,"referenced":{"application":1}
,"application":{"code":1}
,"code":{"values":1,"sample":1}
,"values":{"shown":1}
,"shown":{"instance":1}
,"org.quartz.locality.nodegroup.slowjobs":{"=node0":1}
,"=node0":{"node3":1,"node1":1}
,"node3":{"org.quartz.locality.nodegroup.fastjobs":1,"trigger":1,"org.quartz.locality.nodegroup.slowjobs.triggergroups":1}
,"org.quartz.locality.nodegroup.fastjobs":{"=node1":1}
,"=node1":{"node2":1}
,"node2":{"org.quartz.locality.nodegroup.allnodes":1,"node3":1}
,"org.quartz.locality.nodegroup.allnodes":{"=node0":1}
,"node1":{"node2":1}
,"whose":{"triggers":1}
,"triggers":{"fire":1}
,"fire":{"nodes":1,"node0":1}
,"nodes":{"specified":1}
,"specified":{"node":1}
,"group":{"slowtriggers":1}
,"slowtriggers":{"fire":1}
,"node0":{"node3":1}
,"org.quartz.locality.nodegroup.slowjobs.triggergroups":{"=slowtriggers":1}
,"=slowtriggers":{"org.quartz.locality.nodegroup.fastjobs.triggergroups":1}
,"org.quartz.locality.nodegroup.fastjobs.triggergroups":{"=fasttriggers":1}
,"=fasttriggers":{"ensure":1}
,"ensure":{"quartzlocality.properties":1}
,"classpath":{"quartz.properties":1}
,"sample":{"example":1}
}
;Search.control.loadWordPairs(pairs);
