var pairs =
{
"downloading":{"installing":1}
,"installing":{"quartz":1}
,"quartz":{"first":1,"jar":1,"package":1,"library":1,"primarily":1,"available":1,"depends":1,"jars":1,"application":1,"uses":1}
,"first":{"download":1,"required":1}
,"download":{"recent":1}
,"recent":{"stable":1}
,"stable":{"release":1}
,"release":{"http:\u002F\u002Fquartz-scheduler.org\u002Fdownloads":1}
,"http:\u002F\u002Fquartz-scheduler.org\u002Fdownloads":{"registration":1}
,"registration":{"required":1}
,"required":{"unpack":1,"want":1}
,"unpack":{"distribution":1}
,"distribution":{"install":1,"main":1,".zip":1}
,"install":{"application":1}
,"application":{"quartz":1,"server":1,"(.ear":1,"place":1,"depend":1,"add":1,"know":1,"(i.e":1,"using":1,"package":1,".ear":1}
,"jar":{"files":1,"located":1,"within":1,"example":1}
,"files":{"quartz":1,"located":1,"(including":1}
,"package":{"includes":1,"application":1}
,"includes":{"number":1,"different":1,"implementation":1}
,"number":{"jar":1,"third-party":1}
,"located":{"root":1,"application\u0027s":1}
,"root":{"directory":1,"application":1}
,"directory":{"distribution":1,"features":1}
,"main":{"quartz":1}
,"library":{"named":1}
,"named":{"quartz-xxx.jar":1}
,"quartz-xxx.jar":{"(where":1}
,"(where":{"xxx":1}
,"xxx":{"version":1}
,"version":{"number)":1}
,"number)":{"order":1}
,"order":{"quartz\u0027s":1}
,"quartz\u0027s":{"features":1}
,"features":{"jar":1,"quartz":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"quartz":1,"application":1,"along":1,"you\u0027re":1,"develop":1}
,"primarily":{"within":1}
,"within":{"application":1}
,"server":{"environment":1,"using":1}
,"environment":{"place":1,"unexpected":1,"includes":1}
,"place":{"quartz":1,"application\u0027s":1,"application\u2019s":1}
,"(.ear":{".war":1}
,".war":{"file)":1}
,"file)":{"want":1,"put":1}
,"want":{"quartz":1,"anything":1}
,"available":{"applications":1}
,"applications":{"sure":1}
,"sure":{"classpath":1}
,"using":{"stand-alone":1,"weblogic":1}
,"stand-alone":{"application":1,"quartz":1}
,"along":{"jars":1}
,"jars":{"application":1,"exist":1}
,"depend":{"quartz":1}
,"depends":{"number":1}
,"third-party":{"libraries":1}
,"libraries":{"(in":1,"classpath":1}
,"(in":{"form":1}
,"form":{"jars)":1,".war":1}
,"jars)":{"included":1}
,"included":{"distribution":1,"final":1}
,".zip":{"file":1}
,"file":{"\u0027lib":1,"quartz":1,"called":1,"necessary":1,"classpath":1,"web-inf\u002Fclasses":1,"configuration":1}
,"\u0027lib":{"directory":1}
,"exist":{"classpath":1}
,"you\u0027re":{"building":1}
,"building":{"stand-alone":1,"web":1}
,"add":{"libraries":1}
,"unexpected":{"results":1}
,"results":{"occur":1}
,"occur":{"environment":1}
,"different":{"versions":1}
,"versions":{"jar":1}
,"example":{"weblogic":1}
,"weblogic":{"includes":1,"workshop":1}
,"implementation":{"j2ee":1}
,"j2ee":{"(inside":1}
,"(inside":{"weblogic.jar)":1}
,"weblogic.jar)":{"differ":1}
,"differ":{"servlet.jar":1}
,"servlet.jar":{"case":1,"application":1}
,"case":{"usually":1}
,"usually":{"better":1}
,"better":{"leave":1}
,"leave":{"servlet.jar":1}
,"know":{"classes":1}
,"classes":{"utilized":1}
,"utilized":{"properties":1}
,"properties":{"file":1}
,"uses":{"properties":1}
,"called":{"quartz.properties":1}
,"quartz.properties":{"file":1}
,"necessary":{"first":1}
,"anything":{"basic":1}
,"basic":{"configuration":1}
,"configuration":{"file":1,"files":1,"project":1}
,"web":{"application":1}
,"(i.e":{"form":1}
,"put":{"quartz.properties":1}
,"web-inf\u002Fclasses":{"folder":1}
,"folder":{"place":1}
,"application\u2019s":{"classpath":1}
,"develop":{"application":1}
,"workshop":{"keep":1}
,"keep":{"configuration":1}
,"(including":{"quartz.properties)":1}
,"quartz.properties)":{"project":1}
,"project":{"root":1,"packaged":1}
,".ear":{"file":1,"doing":1}
,"packaged":{".jar":1}
,".jar":{"included":1}
,"final":{".ear":1}
,"doing":{"automatically":1}
,"automatically":{"put":1}
}
;Search.control.loadWordPairs(pairs);
