var pairs =
{
"available":{"constraints":1,"threads":1,"node":1}
,"constraints":{"quartz":1,"cpu":1,"based":1,"code":1}
,"quartz":{"scheduler":1}
,"scheduler":{"offers":1}
,"offers":{"following":1}
,"following":{"constraints":1}
,"cpu":{"provides":1,"load":1}
,"provides":{"methods":1}
,"methods":{"constraints":1}
,"based":{"minimum":1}
,"minimum":{"number":1,"amount":1}
,"number":{"cores":1}
,"cores":{"available":1}
,"threads":{"maximum":1}
,"maximum":{"amount":1}
,"amount":{"cpu":1,"memory":1}
,"load":{"resident":1}
,"resident":{"keys":1}
,"keys":{"node":1,"memory":1}
,"node":{"specified":1,"group":1,"running":1}
,"specified":{"bigmemory":1,"keys":1,"node":1,"operating":1}
,"bigmemory":{"max":1}
,"max":{"distributed":1}
,"distributed":{"cache":1}
,"cache":{"best":1}
,"best":{"match":1}
,"match":{"specified":1}
,"memory":{"minimum":1,"available":1}
,"group":{"node":1,"defined":1}
,"defined":{"quartzlocality.properties":1}
,"quartzlocality.properties":{"node":1}
,"running":{"specified":1}
,"operating":{"system":1}
,"system":{"understand":1}
,"understand":{"constraints":1}
,"code":{"samples":1,"quartz":1}
,"samples":{"provided":1}
,"provided":{"sample":1}
,"sample":{"code":1}
}
;Search.control.loadWordPairs(pairs);
