var pairs =
{
"terracottajobstore":{"configuration":1,"used":1,"performant":1,"selected":1,"tuned":1}
,"configuration":{"terracottajobstore":1,"options":1}
,"used":{"store":1}
,"store":{"scheduling":1}
,"scheduling":{"information":1,"data":1}
,"information":{"(job":1}
,"(job":{"triggers":1}
,"triggers":{"calendars)":1}
,"calendars)":{"within":1}
,"within":{"terracotta":1}
,"terracotta":{"server":1,"servers":1}
,"server":{"terracottajobstore":1,"particularly":1,"connect":1}
,"performant":{"utilizing":1}
,"utilizing":{"database":1}
,"database":{"storing":1}
,"storing":{"scheduling":1,"data":1}
,"data":{"(via":1,"disk":1}
,"(via":{"jdbc-jobstore)":1}
,"jdbc-jobstore)":{"offers":1}
,"offers":{"clustering":1}
,"clustering":{"features":1,"feature":1}
,"features":{"load-balancing":1,"storing":1}
,"load-balancing":{"fail-over":1}
,"fail-over":{"may":1}
,"may":{"want":1}
,"want":{"consider":1}
,"consider":{"implications":1,"partitioning":1}
,"implications":{"setup":1}
,"setup":{"terracotta":1}
,"particularly":{"configuration":1}
,"options":{"turn":1}
,"turn":{"features":1}
,"disk":{"utilization":1}
,"utilization":{"fsync":1}
,"fsync":{"running":1}
,"running":{"array":1}
,"array":{"terracotta":1}
,"servers":{"clustering":1}
,"feature":{"works":1}
,"works":{"best":1}
,"best":{"scaling":1}
,"scaling":{"long-running":1}
,"long-running":{"and\u002For":1}
,"and\u002For":{"cpu-intensive":1}
,"cpu-intensive":{"jobs":1}
,"jobs":{"(distributing":1,"consider":1,"using":1}
,"(distributing":{"work-load":1}
,"work-load":{"multiple":1}
,"multiple":{"nodes)":1,"distinct":1}
,"nodes)":{"need":1}
,"need":{"scale":1}
,"scale":{"support":1}
,"support":{"thousands":1}
,"thousands":{"short-running":1}
,"short-running":{"(e.g":1}
,"(e.g":{"second)":1}
,"second)":{"jobs":1}
,"partitioning":{"jobs":1}
,"using":{"multiple":1,"scheduler":1}
,"distinct":{"schedulers":1}
,"schedulers":{"using":1}
,"scheduler":{"currently":1,"allow":1}
,"currently":{"forces":1}
,"forces":{"cluster-wide":1}
,"cluster-wide":{"lock":1}
,"lock":{"pattern":1}
,"pattern":{"degrades":1}
,"degrades":{"performance":1}
,"performance":{"add":1}
,"add":{"clients":1}
,"clients":{"terracottajobstore":1}
,"selected":{"setting":1}
,"setting":{"org.quartz.jobstore.class":1}
,"org.quartz.jobstore.class":{"property":1,"=org.terracotta.quartz.terracottajobstore":1}
,"property":{"shown":1,"name":1,"configuration)":1}
,"shown":{"below":1}
,"below":{"org.quartz.jobstore.class":1}
,"=org.terracotta.quartz.terracottajobstore":{"terracottajobstore":1}
,"tuned":{"following":1}
,"following":{"properties":1}
,"properties":{"property":1}
,"name":{"required":1}
,"required":{"type":1}
,"type":{"default":1}
,"default":{"value":1}
,"value":{"org.quartz.jobstore.tcconfigurl":1,"(if":1}
,"org.quartz.jobstore.tcconfigurl":{"string":1,"host":1}
,"string":{"org.quartz.jobstore.misfirethreshold":1}
,"org.quartz.jobstore.misfirethreshold":{"int":1,"number":1}
,"int":{"60000":1}
,"60000":{"org.quartz.jobstore.tcconfigurl":1,"(60":1}
,"host":{"port":1}
,"port":{"identifying":1}
,"identifying":{"location":1}
,"location":{"terracotta":1}
,"connect":{"localhost:9510":1}
,"localhost:9510":{"org.quartz.jobstore.misfirethreshold":1}
,"number":{"milliseconds":1}
,"milliseconds":{"scheduler":1}
,"allow":{"trigger":1}
,"trigger":{"pass":1}
,"pass":{"next-fire-time":1}
,"next-fire-time":{"considered":1}
,"considered":{"misfired":1}
,"misfired":{"default":1}
,"(if":{"don\u0027t":1}
,"don\u0027t":{"entry":1}
,"entry":{"property":1}
,"configuration)":{"60000":1}
,"(60":{"seconds)":1}
}
;Search.control.loadWordPairs(pairs);
