var pairs =
{
"how-to":{"unschedule":1}
,"unschedule":{"job":1}
,"job":{"unscheduling":1,"\u002F\u002Funschedule":1,"job":1,"may":1,"trigger":1}
,"unscheduling":{"particular":1,"triggers":1}
,"particular":{"trigger":1}
,"trigger":{"job":1,"scheduler.deletejob":1}
,"\u002F\u002Funschedule":{"particular":1}
,"may":{"trigger)":1}
,"trigger)":{"scheduler.unschedulejob":1}
,"scheduler.unschedulejob":{"(triggerkey":1}
,"(triggerkey":{"trigger1":1}
,"trigger1":{"group1":1}
,"group1":{"\u0022))":1}
,"\u0022))":{"deleting":1}
,"deleting":{"job":1}
,"triggers":{"\u002F\u002Fschedule":1}
,"\u002F\u002Fschedule":{"job":1}
,"scheduler.deletejob":{"(jobkey":1}
,"(jobkey":{"job1":1}
,"job1":{"group1":1}
}
;Search.control.loadWordPairs(pairs);
