var pairs =
{
"how-to":{"create":1}
,"create":{"trigger":1,"simpletrigger":1}
,"trigger":{"executes":1,"restart":1,"always":1,"=newtrigger":1}
,"executes":{"every":1,"3:00":1}
,"every":{"days":1,"two":1,"month":1,"hours":1}
,"days":{"kind":1,"crontrigger":1,"typical":1,"two":1,"daylight":1,".build":1}
,"kind":{"schedule":1}
,"schedule":{"tempted":1,"using":1}
,"tempted":{"crontrigger":1}
,"crontrigger":{"however":1,"work":1}
,"however":{"truly":1}
,"truly":{"every":1}
,"two":{"days":1,"likewise":1}
,"work":{"illustrate":1}
,"illustrate":{"simply":1}
,"simply":{"think":1}
,"think":{"days":1}
,"typical":{"month":1}
,"month":{"(28-31)":1,"means":1}
,"(28-31)":{"cron":1}
,"cron":{"expression":1}
,"expression":{"2\u002F2":1,"1\u002F2":1}
,"2\u002F2":{"give":1}
,"give":{"trigger":1}
,"restart":{"count":1}
,"count":{"beginning":1}
,"beginning":{"every":1}
,"means":{"subsequent":1}
,"subsequent":{"firings":1}
,"firings":{"july":1}
,"july":{"august":1}
,"august":{"interval":1,"just":1}
,"interval":{"three":1}
,"three":{"days":1}
,"likewise":{"expression":1}
,"1\u002F2":{"end":1}
,"end":{"firing":1}
,"firing":{"july":1}
,"just":{"day":1}
,"day":{"apart":1}
,"apart":{"therefore":1}
,"therefore":{"schedule":1}
,"using":{"simpletrigger":1,"calendarintervaltrigger":1}
,"simpletrigger":{"calendarintervaltrigger":1,"create":1,"executes":1}
,"calendarintervaltrigger":{"makes":1,"trigger":1}
,"makes":{"sense":1}
,"sense":{"using":1}
,"3:00":{"tomorrow":1,"adding":1,"time":1}
,"tomorrow":{"every":1,".withschedule":1}
,"hours":{"aware":1,"days":1,"worth":1}
,"aware":{"trigger":1}
,"always":{"fire":1}
,"fire":{"3:00":1,"time":1}
,"adding":{"*24)":1}
,"*24)":{"hours":1,"\u2002\u002F\u002Finterval":1}
,"daylight":{"savings":1}
,"savings":{"time":1}
,"time":{"shifts":1,"2:00":1,"started":1,"trigger":1,"15:00:00":1}
,"shifts":{"result":1}
,"result":{"execution":1}
,"execution":{"time":1}
,"2:00":{"4:00":1}
,"4:00":{"depending":1}
,"depending":{"upon":1}
,"upon":{"whether":1}
,"whether":{"3:00":1}
,"started":{"during":1}
,"during":{"dst":1}
,"dst":{"standard":1}
,"standard":{"time":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"trigger3":1}
,"trigger3":{"group1":1}
,"group1":{".startat":1}
,".startat":{"(tomorrowat":1}
,"(tomorrowat":{"(15":1}
,"(15":{"\u002F\u002Ffirst":1,"\u002F\u002F15:00:00":1}
,"\u002F\u002Ffirst":{"fire":1}
,"15:00:00":{"tomorrow":1}
,".withschedule":{"(simpleschedule":1,"(calendarintervalschedule":1}
,"(simpleschedule":{".withintervalinhours":1}
,".withintervalinhours":{"*24)":1}
,"\u2002\u002F\u002Finterval":{"actually":1}
,"actually":{"hours":1}
,"worth":{"milliseconds":1}
,"milliseconds":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1}
,".build":{"using":1}
,"\u002F\u002F15:00:00":{"tomorrow":1}
,"(calendarintervalschedule":{".withintervalindays":1}
,".withintervalindays":{"(2))":1}
,"(2))":{"\u002F\u002Finterval":1}
,"\u002F\u002Finterval":{"calendar":1}
,"calendar":{"days":1}
}
;Search.control.loadWordPairs(pairs);
