var pairs =
{
"questions":{"jobs":1}
,"jobs":{"control":1,"org.quartz.spi.jobfactory":1}
,"control":{"instantiation":1}
,"instantiation":{"jobs":1}
,"org.quartz.spi.jobfactory":{"org.quartz.scheduler.setjobfactory":1}
,"org.quartz.scheduler.setjobfactory":{"method":1}
,"method":{"keep":1}
,"keep":{"job":1}
,"job":{"removed":1,"becomes":1,"longer":1,"firing":1,"class":1,"read":1,"currently":1}
,"removed":{"completes":1}
,"completes":{"property":1}
,"property":{"jobdetail.setdurability":1}
,"jobdetail.setdurability":{"(true)":1}
,"(true)":{"instructs":1}
,"instructs":{"quartz":1}
,"quartz":{"delete":1}
,"delete":{"job":1}
,"becomes":{"orphan":1}
,"orphan":{"(when":1}
,"(when":{"job":1}
,"longer":{"trigger":1}
,"trigger":{"referencing":1}
,"referencing":{"it)":1}
,"it)":{"keep":1}
,"firing":{"concurrently":1}
,"concurrently":{"job":1}
,"class":{"implement":1}
,"implement":{"statefuljob":1}
,"statefuljob":{"rather":1,"information":1}
,"rather":{"job":1}
,"read":{"javadoc":1}
,"javadoc":{"statefuljob":1}
,"information":{"stop":1}
,"stop":{"job":1}
,"currently":{"executing":1}
,"executing":{"org.quartz.interruptablejob":1}
,"org.quartz.interruptablejob":{"interface":1}
,"interface":{"scheduler.interrupt":1}
,"scheduler.interrupt":{"(string":1}
,"(string":{"string)":1}
,"string)":{"method":1}
}
;Search.control.loadWordPairs(pairs);
