var pairs =
{
"ramjobstore":{"configuration":1,"used":1,"fast":1,"selected":1,"tuned":1}
,"configuration":{"ramjobstore":1}
,"used":{"store":1}
,"store":{"scheduling":1}
,"scheduling":{"information":1}
,"information":{"(job":1,"lost":1}
,"(job":{"triggers":1}
,"triggers":{"calendars)":1}
,"calendars)":{"within":1}
,"within":{"memory":1}
,"memory":{"ramjobstore":1}
,"fast":{"lightweight":1}
,"lightweight":{"scheduling":1}
,"lost":{"process":1}
,"process":{"terminates":1}
,"terminates":{"ramjobstore":1}
,"selected":{"setting":1}
,"setting":{"org.quartz.jobstore.class":1}
,"org.quartz.jobstore.class":{"property":1,"=org.quartz.simpl.ramjobstore":1}
,"property":{"shown":1,"name":1,"configuration)":1}
,"shown":{"below":1}
,"below":{"org.quartz.jobstore.class":1}
,"=org.quartz.simpl.ramjobstore":{"ramjobstore":1}
,"tuned":{"following":1}
,"following":{"properties":1}
,"properties":{"property":1}
,"name":{"required":1}
,"required":{"type":1}
,"type":{"default":1}
,"default":{"value":1}
,"value":{"org.quartz.jobstore.misfirethreshold":1,"(if":1}
,"org.quartz.jobstore.misfirethreshold":{"int":1,"number":1}
,"int":{"60000":1}
,"60000":{"org.quartz.jobstore.misfirethreshold":1,"(60":1}
,"number":{"milliseconds":1}
,"milliseconds":{"scheduler":1}
,"scheduler":{"allow":1}
,"allow":{"trigger":1}
,"trigger":{"pass":1}
,"pass":{"next-fire-time":1}
,"next-fire-time":{"considered":1}
,"considered":{"misfired":1}
,"misfired":{"default":1}
,"(if":{"don\u0027t":1}
,"don\u0027t":{"entry":1}
,"entry":{"property":1}
,"configuration)":{"60000":1}
,"(60":{"seconds)":1}
}
;Search.control.loadWordPairs(pairs);
