var pairs =
{
"how-to":{"shut":1}
,"shut":{"down":1}
,"down":{"scheduler":1,"(unless":1}
,"scheduler":{"shutdown":1,"simply":1,"cannot":1,"suspend":1,"servlet":1,"application":1}
,"shutdown":{"\u002Fdestroy":1,"methods":1,"scheduler":1}
,"\u002Fdestroy":{"scheduler":1}
,"simply":{"call":1,"want":1}
,"call":{"scheduler\u2019s":1}
,"scheduler\u2019s":{"shutdown":1}
,"methods":{"once":1}
,"once":{"shutdown":1}
,"cannot":{"restarted":1}
,"restarted":{"(as":1}
,"(as":{"threads":1}
,"threads":{"resources":1}
,"resources":{"permanently":1}
,"permanently":{"destroyed)":1}
,"destroyed)":{"simply":1}
,"want":{"pause":1}
,"pause":{"scheduler":1}
,"suspend":{"method":1}
,"method":{"wait":1,"shutdown":1}
,"wait":{"executing":1}
,"executing":{"jobs":1}
,"jobs":{"finish":1,"complete":1,"continue":1}
,"finish":{"\u002F\u002Fshutdown":1}
,"\u002F\u002Fshutdown":{"return":1,"returns":1}
,"return":{"until":1}
,"until":{"executing":1}
,"complete":{"execution":1}
,"execution":{"scheduler.shutdown":1}
,"scheduler.shutdown":{"(true)":1,"\u002F\u002For":1,"(false)":1}
,"(true)":{"wait":1}
,"returns":{"immediately":1}
,"immediately":{"executing":1}
,"continue":{"running":1}
,"running":{"completion":1}
,"completion":{"scheduler.shutdown":1}
,"\u002F\u002For":{"scheduler.shutdown":1}
,"(false)":{"using":1}
,"using":{"org.quartz.ee.servlet.quartzinitializerlistener":1}
,"org.quartz.ee.servlet.quartzinitializerlistener":{"fire":1}
,"fire":{"scheduler":1}
,"servlet":{"container":1}
,"container":{"contextdestroyed":1}
,"contextdestroyed":{"method":1}
,"application":{"undeployed":1,"server":1}
,"undeployed":{"application":1}
,"server":{"shuts":1}
,"shuts":{"down":1}
,"(unless":{"shutdown-on-unload":1}
,"shutdown-on-unload":{"property":1}
,"property":{"explicitly":1}
,"explicitly":{"false)":1}
}
;Search.control.loadWordPairs(pairs);
