var pairs =
{
"terracotta":{"quartz":1,"server":1}
,"quartz":{"scheduler":1}
,"scheduler":{"terracotta":1,"licensed":1,"includes":1,"service":1,"provides":1}
,"licensed":{"version":1}
,"version":{"quartz":1}
,"includes":{"terracottajobstore":1}
,"terracottajobstore":{"enables":1}
,"enables":{"cluster":1}
,"cluster":{"quartz":1,"performance":1}
,"service":{"using":1}
,"using":{"terracotta":1}
,"server":{"array":1}
,"array":{"using":1}
,"provides":{"number":1,"locality":1,"clear":1}
,"number":{"advantages":1}
,"advantages":{"adds":1}
,"adds":{"high-availability":1}
,"high-availability":{"hot":1}
,"hot":{"standbys":1}
,"standbys":{"immediately":1}
,"immediately":{"replace":1}
,"replace":{"failed":1}
,"failed":{"servers":1}
,"servers":{"downtime":1}
,"downtime":{"lost":1}
,"lost":{"data":1}
,"data":{"provides":1,"without":1}
,"locality":{"api":1}
,"api":{"route":1}
,"route":{"jobs":1}
,"jobs":{"specific":1}
,"specific":{"node":1}
,"node":{"groups":1}
,"groups":{"base":1}
,"base":{"routing":1}
,"routing":{"decisions":1}
,"decisions":{"system":1}
,"system":{"characteristics":1}
,"characteristics":{"available":1}
,"available":{"resources":1}
,"resources":{"improves":1,"ensures":1}
,"improves":{"performance":1}
,"performance":{"offload":1}
,"offload":{"traditional":1}
,"traditional":{"databases":1}
,"databases":{"automatically":1}
,"automatically":{"distribute":1,"back":1}
,"distribute":{"load":1}
,"load":{"provides":1}
,"clear":{"scale-out":1}
,"scale-out":{"path":1}
,"path":{"add":1}
,"add":{"capacity":1}
,"capacity":{"without":1}
,"without":{"requiring":1,"impacting":1}
,"requiring":{"additional":1}
,"additional":{"database":1}
,"database":{"resources":1}
,"ensures":{"persistence":1}
,"persistence":{"automatically":1}
,"back":{"shared":1}
,"shared":{"data":1}
,"impacting":{"cluster":1}
}
;Search.control.loadWordPairs(pairs);
