var pairs =
{
"triggers":{"jobs":1,"easy":1,"select":1,"cron":1,"details":1,"common":1,"(or":1,"scheduled":1,"first":1,"fire":1,"highest":1,"misfired":1,"calendars":1,"time":1,"shown":1}
,"jobs":{"triggers":1}
,"easy":{"work":1}
,"work":{"however":1}
,"however":{"variety":1,"firings":1}
,"variety":{"customizable":1}
,"customizable":{"options":1}
,"options":{"need":1}
,"need":{"understand":1}
,"understand":{"full":1}
,"full":{"quartz":1}
,"quartz":{"different":1,"thread":1,"may":1,"worker":1,"projects":1,"calendar":1,"includes":1}
,"different":{"types":1,"scheduling":1,"trigger":1,"misfire":1}
,"types":{"triggers":1,"simple":1,"provided":1,"triggerkey":1,"common":1,"jobkey":1,"trigger":1,"different":1,"explained":1}
,"select":{"meet":1}
,"meet":{"different":1}
,"scheduling":{"needs":1,"calendar":1}
,"needs":{"two":1}
,"two":{"common":1,"triggers":1}
,"common":{"types":1,"trigger":1,"properties":1}
,"simple":{"triggers":1}
,"cron":{"triggers":1}
,"details":{"specific":1}
,"specific":{"trigger":1}
,"trigger":{"types":1,"attributes":1,"definition":1,"fires":1,"actually":1,"schedule":1,"triggers":1,"default":1,"scheduled":1,"misfire":1,"misses":1,"type":1,"defined":1,"=newtrigger":1,"trigger":1}
,"provided":{"working":1}
,"working":{"triggers":1}
,"attributes":{"aside":1}
,"aside":{"fact":1}
,"fact":{"trigger":1}
,"triggerkey":{"properties":1}
,"properties":{"tracking":1,"common":1,"using":1,"bit":1}
,"tracking":{"identities":1}
,"identities":{"number":1}
,"number":{"properties":1,"calendar":1}
,"using":{"triggerbuilder":1,"quartz":1}
,"triggerbuilder":{"building":1}
,"building":{"trigger":1}
,"definition":{"(examples":1}
,"(examples":{"follow)":1}
,"follow)":{"listing":1}
,"listing":{"properties":1}
,"jobkey":{"property":1}
,"property":{"indicates":1,"april":1,"trigger":1}
,"indicates":{"identity":1,"trigger\u0027s":1}
,"identity":{"job":1}
,"job":{"executed":1,"detected":1,"different":1,"every":1,"daily":1,"trigger":1,"trigger2":1}
,"executed":{"trigger":1,"first":1}
,"fires":{"starttime":1,"job":1}
,"starttime":{"property":1}
,"trigger\u0027s":{"schedule":1,"job":1,"firing":1}
,"schedule":{"first":1,"start":1,"every":1,"longer":1,"instance":1,"job":1}
,"first":{"comes":1,"firing":1,"crack":1,"triggers":1,"integer":1}
,"comes":{"effect":1}
,"effect":{"value":1,"words":1}
,"value":{"java.util.date":1,"allowed":1}
,"java.util.date":{"object":1}
,"object":{"defines":1,"implements":1}
,"defines":{"moment":1}
,"moment":{"time":1}
,"time":{"given":1,"others":1,"schedule":1,"july":1,"june":1,"case":1,"worker":1,"trigger":1,"scheduler":1,"trigger\u0027s":1,"narrow":1}
,"given":{"calendar":1,"trigger":1}
,"calendar":{"date":1,"objects":1,"excludes":1,"interface":1,"{public":1,"instance":1,"skipped":1,"implementations":1}
,"date":{"trigger":1}
,"actually":{"fire":1}
,"fire":{"start":1,"last":1,"triggers":1,"time":1,"10:59":1,"scheduled":1,"11:00":1,"daily":1}
,"start":{"time":1,"followed":1,"using":1}
,"others":{"simply":1}
,"simply":{"marks":1}
,"marks":{"time":1}
,"followed":{"means":1}
,"means":{"store":1,"calendars":1}
,"store":{"trigger":1}
,"every":{"5th":1,"weekday":1}
,"5th":{"day":1,"properties":1}
,"day":{"month":1}
,"month":{"during":1,"end":1}
,"during":{"january":1,"period":1}
,"january":{"starttime":1}
,"april":{"1st":1}
,"1st":{"few":1,"fire":1}
,"few":{"months":1,"worker":1}
,"months":{"first":1}
,"firing":{"endtime":1,"time":1,"schedule":1}
,"endtime":{"property":1}
,"longer":{"effect":1}
,"words":{"trigger":1}
,"end":{"time":1}
,"july":{"1st":1}
,"last":{"time":1}
,"june":{"5th":1}
,"bit":{"explanation":1}
,"explanation":{"discussed":1}
,"discussed":{"following":1}
,"following":{"sections":1}
,"sections":{"priority":1,"time":1}
,"priority":{"sometimes":1,"property":1,"executed":1,"positive":1,"trigger":1,"priorities":1,"original":1}
,"sometimes":{"triggers":1}
,"(or":{"few":1}
,"worker":{"threads":1}
,"threads":{"quartz":1,"purpose":1,"currently":1,"quartz\u0027s":1}
,"thread":{"pool)":1,"pool":1}
,"pool)":{"quartz":1}
,"may":{"enough":1,"want":1,"suit":1}
,"enough":{"resources":1}
,"resources":{"immediately":1}
,"immediately":{"fire":1}
,"scheduled":{"fire":1,"priority":1}
,"case":{"may":1}
,"want":{"control":1}
,"control":{"triggers":1}
,"crack":{"available":1}
,"available":{"quartz":1,"first":1,"threads":1,"default":1}
,"purpose":{"priority":1}
,"currently":{"available":1}
,"highest":{"priority":1}
,"integer":{"value":1}
,"allowed":{"priority":1}
,"positive":{"negative":1}
,"negative":{"priority":1}
,"default":{"priority":1,"\u0027smart":1}
,"priorities":{"compared":1}
,"compared":{"triggers":1}
,"10:59":{"always":1}
,"always":{"fire":1}
,"11:00":{"trigger\u0027s":1}
,"detected":{"require":1}
,"require":{"recovery":1}
,"recovery":{"recovery":1,"scheduled":1}
,"original":{"trigger":1}
,"misfire":{"instructions":1,"instruction":1,"occurs":1}
,"instructions":{"important":1,"available":1,"start":1,"defined":1,"specific":1}
,"important":{"property":1}
,"instruction":{"misfire":1,"-which":1}
,"occurs":{"persistent":1}
,"persistent":{"trigger":1,"triggers":1}
,"misses":{"firing":1}
,"scheduler":{"shutdown":1,"starts":1,"calendars":1,"via":1}
,"shutdown":{"available":1}
,"quartz\u0027s":{"thread":1}
,"pool":{"executing":1}
,"executing":{"job":1}
,"\u0027smart":{"policy":1}
,"policy":{"instruction":1}
,"-which":{"dynamic":1}
,"dynamic":{"behavior":1}
,"behavior":{"based":1}
,"based":{"trigger":1,"individually":1}
,"type":{"configuration":1,"timestamps":1}
,"configuration":{"scheduler":1}
,"starts":{"searches":1}
,"searches":{"persistent":1}
,"misfired":{"updates":1}
,"updates":{"based":1}
,"individually":{"configured":1}
,"configured":{"misfire":1}
,"projects":{"sure":1}
,"sure":{"familiarize":1}
,"familiarize":{"yourself":1}
,"yourself":{"misfire":1}
,"defined":{"given":1,"stored":1}
,"explained":{"javadoc":1}
,"javadoc":{"addition":1}
,"addition":{"information":1}
,"information":{"misfire":1}
,"calendars":{"quartz":1,"useful":1,"\u0027block":1,"instantiated":1}
,"objects":{"(not":1}
,"(not":{"java.util.calendar":1}
,"java.util.calendar":{"objects)":1}
,"objects)":{"associated":1}
,"associated":{"triggers":1}
,"stored":{"scheduler":1}
,"useful":{"excluding":1}
,"excluding":{"blocks":1}
,"blocks":{"time":1}
,"instance":{"create":1,"used":1}
,"create":{"trigger":1}
,"weekday":{"9:30":1}
,"9:30":{"add":1,".modifiedbycalendar":1}
,"add":{"calendar":1}
,"excludes":{"business\u0027s":1}
,"business\u0027s":{"holidays":1}
,"holidays":{"calendar\u0027s":1,".build":1}
,"calendar\u0027s":{"serializable":1}
,"serializable":{"object":1}
,"implements":{"calendar":1}
,"interface":{"{shown":1,"calendar":1}
,"{shown":{"below)":1}
,"below)":{"package":1}
,"package":{"org.quartz":1,"provides":1}
,"org.quartz":{"public":1}
,"public":{"interface":1,"long":1}
,"{public":{"boolean":1}
,"boolean":{"istimeincluded":1}
,"istimeincluded":{"(long":1}
,"(long":{"timestamp)":1}
,"timestamp)":{"public":1,"notice":1}
,"long":{"getnextincludedtime":1,"type":1}
,"getnextincludedtime":{"(long":1}
,"notice":{"parameters":1}
,"parameters":{"methods":1}
,"methods":{"long":1}
,"timestamps":{"millisecond":1}
,"millisecond":{"format":1,"likely":1}
,"format":{"means":1}
,"\u0027block":{"sections":1}
,"narrow":{"millisecond":1}
,"likely":{"you\u0027ll":1}
,"you\u0027ll":{"interested":1}
,"interested":{"\u0027blocking-out":1}
,"\u0027blocking-out":{"entire":1}
,"entire":{"days":1}
,"days":{"convenience":1,"wish":1}
,"convenience":{"quartz":1}
,"includes":{"class":1}
,"class":{"org.quartz.impl.holidaycalendar":1}
,"org.quartz.impl.holidaycalendar":{"just":1}
,"just":{"calendars":1}
,"instantiated":{"registered":1}
,"registered":{"scheduler":1}
,"via":{"addcalendar":1}
,"addcalendar":{"method":1}
,"method":{"holidaycalendar":1,"order":1}
,"holidaycalendar":{"instantiating":1,"cal":1,"cal.addexcludeddate":1}
,"instantiating":{"addexcludeddate":1}
,"addexcludeddate":{"(date":1}
,"(date":{"date)":1}
,"date)":{"method":1}
,"order":{"populate":1}
,"populate":{"days":1}
,"wish":{"excluded":1}
,"excluded":{"scheduling":1,"calendar":1}
,"used":{"multiple":1}
,"multiple":{"triggers":1}
,"shown":{"example":1}
,"example":{"below":1}
,"below":{"holidaycalendar":1}
,"cal":{"=new":1,"false)":1}
,"=new":{"holidaycalendar":1}
,"cal.addexcludeddate":{"(somedate":1,"(someotherdate":1}
,"(somedate":{"cal.addexcludeddate":1}
,"(someotherdate":{"sched.addcalendar":1}
,"sched.addcalendar":{"myholidays":1}
,"myholidays":{"cal":1,"\u002F\u002Fbut":1}
,"false)":{"trigger":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"mytrigger":1,"mytrigger2":1}
,"mytrigger":{".forjob":1}
,".forjob":{"myjob":1,"myjob2":1}
,"myjob":{".withschedule":1}
,".withschedule":{"(dailyathourandminute":1}
,"(dailyathourandminute":{"30))":1,"(11":1}
,"30))":{"\u002F\u002Fexecute":1}
,"\u002F\u002Fexecute":{"job":1}
,"daily":{"9:30":1,"11:30":1,"however":1}
,".modifiedbycalendar":{"myholidays":1}
,"\u002F\u002Fbut":{"holidays":1}
,".build":{"schedule":1}
,"mytrigger2":{".forjob":1}
,"myjob2":{".withschedule":1}
,"(11":{"30))":1}
,"11:30":{".modifiedbycalendar":1}
,"trigger2":{"code":1}
,"code":{"above":1}
,"above":{"creates":1}
,"creates":{"two":1}
,"firings":{"occurred":1}
,"occurred":{"during":1}
,"period":{"excluded":1}
,"skipped":{"org.quartz.impl.calendar":1}
,"org.quartz.impl.calendar":{"package":1}
,"provides":{"number":1}
,"implementations":{"may":1}
,"suit":{"needs":1}
}
;Search.control.loadWordPairs(pairs);
