var pairs =
{
"how-to":{"create":1}
,"create":{"trigger":1}
,"trigger":{"executes":1,"=newtrigger":1}
,"executes":{"every":1}
,"every":{"ten":1}
,"ten":{"seconds":1}
,"seconds":{"using":1}
,"using":{"simpletrigger":1}
,"simpletrigger":{"trigger":1}
,"=newtrigger":{".withidentity":1}
,".withidentity":{"trigger3":1}
,"trigger3":{"group1":1}
,"group1":{".startnow":1}
,".startnow":{".withschedule":1}
,".withschedule":{"(simpleschedule":1}
,"(simpleschedule":{".withintervalinseconds":1}
,".withintervalinseconds":{"(10)":1}
,"(10)":{".repeatforever":1}
,".repeatforever":{"())":1}
,"())":{".build":1}
}
;Search.control.loadWordPairs(pairs);
