var pairs =
{
"how-to":{"initialize":1}
,"initialize":{"job":1,"scheduler":1}
,"job":{"data":1,"initialization":1,"description":1}
,"data":{"scheduler":1,"here\u0027s":1}
,"scheduler":{"initialization":1,"predefined":1}
,"initialization":{"initialize":1,"plugin":1}
,"predefined":{"jobs":1}
,"jobs":{"triggers":1,"associated":1}
,"triggers":{"using":1,"example":1,"contain":1}
,"using":{"xmlschedulingdataprocessorplugin":1}
,"xmlschedulingdataprocessorplugin":{"example":1,"excerpt":1,"jobstorecmt":1}
,"example":{"provided":1,"quartz.properties":1,"jobs.xml":1,"xml":1}
,"provided":{"quartz":1}
,"quartz":{"distribution":1}
,"distribution":{"directory":1,"checkout":1}
,"directory":{"examples\u002Fexample10":1,"quartz":1}
,"examples\u002Fexample10":{"however":1,"directory":1}
,"however":{"following":1}
,"following":{"short":1,"describes":1}
,"short":{"description":1}
,"description":{"plugin":1,"<\u002Fdescription>":1}
,"plugin":{"works":1,"#===================================================org.quartz.plugin.jobinitializer.class":1,"thrown":1}
,"works":{"first":1}
,"first":{"explicitly":1}
,"explicitly":{"specify":1}
,"specify":{"want":1}
,"want":{"xmlschedulingdataprocessorplugin":1}
,"excerpt":{"example":1}
,"quartz.properties":{"#===================================================#":1}
,"#===================================================#":{"configure":1}
,"configure":{"job":1}
,"#===================================================org.quartz.plugin.jobinitializer.class":{"=org.quartz.plugins.xml.xmlschedulingdataprocessorplugin":1}
,"=org.quartz.plugins.xml.xmlschedulingdataprocessorplugin":{"org.quartz.plugin.jobinitializer.filenames":1}
,"org.quartz.plugin.jobinitializer.filenames":{"=jobs.xml":1}
,"=jobs.xml":{"org.quartz.plugin.jobinitializer.failonfilenotfound":1}
,"org.quartz.plugin.jobinitializer.failonfilenotfound":{"=true":1}
,"=true":{"org.quartz.plugin.jobinitializer.scaninterval":1}
,"org.quartz.plugin.jobinitializer.scaninterval":{"=10":1}
,"=10":{"org.quartz.plugin.jobinitializer.wrapinusertransaction":1}
,"org.quartz.plugin.jobinitializer.wrapinusertransaction":{"=false":1}
,"=false":{"following":1}
,"describes":{"property":1}
,"property":{"filenames":1,"specifies":1}
,"filenames":{"comma":1,"(with":1,"property)":1}
,"comma":{"separated":1}
,"separated":{"list":1}
,"list":{"filenames":1}
,"(with":{"paths)":1}
,"paths)":{"files":1}
,"files":{"contain":1,"found":1,"reloaded":1,"property":1,"checked":1}
,"contain":{"xml":1,"directives":1}
,"xml":{"definition":1,"version=":1,"schema":1}
,"definition":{"jobs":1,"file":1,"files":1}
,"associated":{"triggers":1}
,"jobs.xml":{"definition":1,"file":1}
,"file":{"shown":1,"(or":1,"filenames":1,"examples\u002Fexample10":1}
,"shown":{"later":1}
,"later":{"topic":1}
,"topic":{"failonfilenotfound":1}
,"failonfilenotfound":{"specifies":1}
,"specifies":{"whether":1,"interval":1}
,"whether":{"plugin":1,"xml":1}
,"thrown":{"exception":1}
,"exception":{"xml":1}
,"found":{"thus":1}
,"thus":{"preventing":1}
,"preventing":{"(the":1}
,"(the":{"plugin)":1}
,"plugin)":{"initializing":1}
,"initializing":{"scaninterval":1}
,"scaninterval":{"specifies":1}
,"reloaded":{"change":1}
,"change":{"detected":1}
,"detected":{"files":1}
,"interval":{"(in":1}
,"(in":{"seconds)":1}
,"seconds)":{"files":1}
,"checked":{"changes":1}
,"changes":{"disable":1}
,"disable":{"reloading":1}
,"reloading":{"wrapinusertransaction":1}
,"wrapinusertransaction":{"true":1}
,"true":{"using":1}
,"jobstorecmt":{"otherwise":1}
,"otherwise":{"experience":1}
,"experience":{"erratic":1}
,"erratic":{"behavior":1}
,"behavior":{"jobs.xml":1}
,"(or":{"name":1}
,"name":{"assign":1}
,"assign":{"file":1}
,"property)":{"declaratively":1}
,"declaratively":{"defines":1}
,"defines":{"jobs":1}
,"directives":{"delete":1}
,"delete":{"existing":1}
,"existing":{"data":1}
,"here\u0027s":{"self-explanatory":1}
,"self-explanatory":{"example":1}
,"version=":{"1.0":1}
,"1.0":{"encoding=\u0027utf-8":1}
,"encoding=\u0027utf-8":{"<job-scheduling-data":1}
,"<job-scheduling-data":{"xmlns=\u0022":1}
,"xmlns=\u0022":{"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjobschedulingdata":1}
,"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjobschedulingdata":{"xmlns:xsi=\u0022":1,"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjob_scheduling_data_1_8.xsd":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:schemalocation=\u0022":1}
,"xsi:schemalocation=\u0022":{"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjobschedulingdata":1}
,"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjob_scheduling_data_1_8.xsd":{"version=\u0022":1}
,"version=\u0022":{"1.8":1}
,"1.8":{"<schedule>":1}
,"<schedule>":{"<job>":1}
,"<job>":{"<name>":1}
,"<name>":{"my-very-clever-job":1,"my-trigger":1}
,"my-very-clever-job":{"<\u002Fname>":1,"<\u002Fjob-name>":1}
,"<\u002Fname>":{"<group>":1}
,"<group>":{"myjob_group":1,"mytrigger_group":1}
,"myjob_group":{"<\u002Fgroup>":1,"<\u002Fjob-group>":1}
,"<\u002Fgroup>":{"<description>":1,"<job-name>":1}
,"<description>":{"job":1}
,"<\u002Fdescription>":{"<job-class>":1}
,"<job-class>":{"com.acme.scheduler.job.cleverjob":1}
,"com.acme.scheduler.job.cleverjob":{"<\u002Fjob-class>":1}
,"<\u002Fjob-class>":{"<job-data-map":1}
,"<job-data-map":{"allows-transient-data=\u0022":1}
,"allows-transient-data=\u0022":{"false":1}
,"false":{"<entry>":1}
,"<entry>":{"<key>":1}
,"<key>":{"burger-type":1,"dressing-list":1}
,"burger-type":{"<\u002Fkey>":1}
,"<\u002Fkey>":{"<value>":1}
,"<value>":{"hotdog":1,"ketchup":1}
,"hotdog":{"<\u002Fvalue>":1}
,"<\u002Fvalue>":{"<\u002Fentry>":1}
,"<\u002Fentry>":{"<entry>":1,"<\u002Fjob-data-map>":1}
,"dressing-list":{"<\u002Fkey>":1}
,"ketchup":{"mayo":1}
,"mayo":{"<\u002Fvalue>":1}
,"<\u002Fjob-data-map>":{"<\u002Fjob>":1}
,"<\u002Fjob>":{"<trigger>":1}
,"<trigger>":{"<cron>":1}
,"<cron>":{"<name>":1}
,"my-trigger":{"<\u002Fname>":1}
,"mytrigger_group":{"<\u002Fgroup>":1}
,"<job-name>":{"my-very-clever-job":1}
,"<\u002Fjob-name>":{"<job-group>":1}
,"<job-group>":{"myjob_group":1}
,"<\u002Fjob-group>":{"<!--trigger":1}
,"<!--trigger":{"every":1}
,"every":{"night":1}
,"night":{"4:30":1}
,"4:30":{"-->":1}
,"-->":{"<!--do":1,"<cron-expression>":1}
,"<!--do":{"forget":1}
,"forget":{"light":1}
,"light":{"kitchen\u0027s":1,"-->":1}
,"kitchen\u0027s":{"light":1}
,"<cron-expression>":{"**?":1}
,"**?":{"<\u002Fcron-expression>":1}
,"<\u002Fcron-expression>":{"<\u002Fcron>":1}
,"<\u002Fcron>":{"<\u002Ftrigger>":1}
,"<\u002Ftrigger>":{"<\u002Fschedule>":1}
,"<\u002Fschedule>":{"<\u002Fjob-scheduling-data>":1}
,"<\u002Fjob-scheduling-data>":{"find":1}
,"find":{"example":1}
,"checkout":{"xml":1}
,"schema":{"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjob_scheduling_data_2_0.xsd":1}
,"http:\u002F\u002Fwww.quartz-scheduler.org\u002Fxml\u002Fjob_scheduling_data_2_0.xsd":{"full":1}
,"full":{"details":1}
,"details":{"possible":1}
}
;Search.control.loadWordPairs(pairs);
