var pairs =
{
"job":{"stores":1}
,"stores":{"jobstores":1}
,"jobstores":{"responsible":1}
,"responsible":{"keeping":1}
,"keeping":{"track":1}
,"track":{"work":1}
,"work":{"data":1,"scheduler":1}
,"data":{"give":1}
,"give":{"scheduler":1}
,"scheduler":{"jobs":1,"instance":1,"(and":1,"interface":1}
,"jobs":{"triggers":1}
,"triggers":{"calendars":1}
,"calendars":{"forth":1}
,"forth":{"selecting":1}
,"selecting":{"appropriate":1}
,"appropriate":{"jobstore":1}
,"jobstore":{"quartz":1,"scheduler":1,"instance":1,"behind-the-scenes":1,"work":1}
,"quartz":{"scheduler":1,"itself":1,"know":1}
,"instance":{"important":1,"jobstore":1,"directly":1}
,"important":{"step":1}
,"step":{"choice":1}
,"choice":{"easy":1}
,"easy":{"once":1}
,"once":{"understand":1}
,"understand":{"differences":1}
,"differences":{"declare":1}
,"declare":{"jobstore":1}
,"(and":{"configuration":1}
,"configuration":{"settings)":1}
,"settings)":{"properties":1}
,"properties":{"file":1}
,"file":{"(or":1}
,"(or":{"object)":1}
,"object)":{"provide":1}
,"provide":{"schedulerfactory":1}
,"schedulerfactory":{"produce":1}
,"produce":{"scheduler":1}
,"directly":{"code":1}
,"code":{"jobstore":1}
,"behind-the-scenes":{"quartz":1}
,"itself":{"quartz":1}
,"know":{"(through":1}
,"(through":{"configuration)":1}
,"configuration)":{"jobstore":1}
,"interface":{"code":1}
}
;Search.control.loadWordPairs(pairs);
