var pairs =
{
"how-to":{"job":1}
,"job":{"listeners":1,"scheduler.getlistenermanager":1}
,"listeners":{"creating":1}
,"creating":{"joblistener":1}
,"joblistener":{"implement":1,"interface":1,"{private":1,"scheduler":1}
,"implement":{"joblistener":1}
,"interface":{"package":1}
,"package":{"foo":1}
,"foo":{"import":1}
,"import":{"org.quartz.jobexecutioncontext":1,"org.quartz.jobexecutionexception":1,"org.quartz.joblistener":1,"org.quartz.listeners.joblistenersupport":1}
,"org.quartz.jobexecutioncontext":{"import":1}
,"org.quartz.jobexecutionexception":{"import":1}
,"org.quartz.joblistener":{"public":1}
,"public":{"class":1,"myjoblistener":1,"string":1,"void":1,"myotherjoblistener":1}
,"class":{"myjoblistener":1,"myotherjoblistener":1}
,"myjoblistener":{"implements":1,"(string":1}
,"implements":{"joblistener":1}
,"{private":{"string":1}
,"string":{"name":1,"getname":1}
,"name":{"public":1,"@override":1}
,"(string":{"name)":1}
,"name)":{"{this.name":1}
,"{this.name":{"=name":1}
,"=name":{"public":1}
,"getname":{"{return":1}
,"{return":{"name":1}
,"void":{"jobtobeexecuted":1,"jobwasexecuted":1,"jobexecutionvetoed":1}
,"jobtobeexecuted":{"(jobexecutioncontext":1}
,"(jobexecutioncontext":{"context)":1,"context":1}
,"context)":{"{\u002F\u002Fdo":1}
,"{\u002F\u002Fdo":{"something":1}
,"something":{"event":1}
,"event":{"public":1,"-or":1,"registering":1}
,"jobwasexecuted":{"(jobexecutioncontext":1}
,"context":{"jobexecutionexception":1}
,"jobexecutionexception":{"jobexception)":1}
,"jobexception)":{"{\u002F\u002Fdo":1}
,"jobexecutionvetoed":{"(jobexecutioncontext":1}
,"-or":{"-extend":1}
,"-extend":{"joblistenersupport":1}
,"joblistenersupport":{"package":1,"{private":1}
,"org.quartz.listeners.joblistenersupport":{"public":1}
,"myotherjoblistener":{"extends":1,"(string":1}
,"extends":{"joblistenersupport":1}
,"@override":{"public":1}
,"registering":{"joblistener":1}
,"scheduler":{"listen":1}
,"listen":{"jobs":1,"specific":1}
,"jobs":{"scheduler.getlistenermanager":1,"group":1}
,"scheduler.getlistenermanager":{".addjoblistener":1}
,".addjoblistener":{"(myjoblistener":1}
,"(myjoblistener":{"alljobs":1,"jobkeyequals":1,"jobgroupequals":1}
,"alljobs":{"())":1}
,"())":{"registering":1}
,"specific":{"job":1}
,"jobkeyequals":{"(jobkey":1}
,"(jobkey":{"myjobname":1}
,"myjobname":{"myjobgroup":1}
,"myjobgroup":{"\u0022)))":1,"\u0022))":1}
,"\u0022)))":{"registering":1}
,"group":{"scheduler.getlistenermanager":1}
,"jobgroupequals":{"myjobgroup":1}
}
;Search.control.loadWordPairs(pairs);
