var pairs =
{
"schedulerlisteners":{"schedulerlisteners":1,"triggerlisteners":1,"registered":1,"virtually":1}
,"triggerlisteners":{"joblisteners":1}
,"joblisteners":{"except":1}
,"except":{"receive":1}
,"receive":{"notification":1}
,"notification":{"events":1}
,"events":{"within":1,"related":1,"scheduler-related":1,"include":1}
,"within":{"scheduler":1}
,"scheduler":{"itself":1,"shutdown":1,"schedulerlisteners":1}
,"itself":{"necessarily":1}
,"necessarily":{"events":1}
,"related":{"specific":1}
,"specific":{"trigger":1}
,"trigger":{"job":1,"removal":1,"serious":1}
,"job":{"among":1,"trigger":1}
,"among":{"events":1}
,"scheduler-related":{"events":1}
,"include":{"addition":1}
,"addition":{"job":1}
,"removal":{"job":1}
,"serious":{"error":1}
,"error":{"within":1}
,"shutdown":{"scheduler":1}
,"registered":{"scheduler\u0027s":1}
,"scheduler\u0027s":{"listenermanager":1}
,"listenermanager":{"schedulerlisteners":1}
,"virtually":{"object":1}
,"object":{"implements":1}
,"implements":{"org.quartz.schedulerlistener":1}
,"org.quartz.schedulerlistener":{"interface":1}
,"interface":{"org.quartz.schedulerlistener":1,"public":1,"schedulerlistener":1}
,"public":{"interface":1,"void":1}
,"schedulerlistener":{"{public":1}
,"{public":{"void":1}
,"void":{"jobscheduled":1,"jobunscheduled":1,"triggerfinalized":1,"triggerspaused":1,"triggersresumed":1,"jobspaused":1,"jobsresumed":1,"schedulererror":1,"schedulerstarted":1,"schedulerinstandbymode":1,"schedulershutdown":1,"schedulingdatacleared":1}
,"jobscheduled":{"(trigger":1}
,"(trigger":{"trigger)":1}
,"trigger)":{"public":1}
,"jobunscheduled":{"(string":1}
,"(string":{"triggername":1,"jobname":1,"msg":1}
,"triggername":{"string":1}
,"string":{"triggergroup)":1,"jobgroup)":1}
,"triggergroup)":{"public":1}
,"triggerfinalized":{"(trigger":1}
,"triggerspaused":{"(string":1}
,"triggersresumed":{"(string":1}
,"jobspaused":{"(string":1}
,"jobname":{"string":1}
,"jobgroup)":{"public":1}
,"jobsresumed":{"(string":1}
,"schedulererror":{"(string":1}
,"msg":{"schedulerexception":1}
,"schedulerexception":{"cause)":1}
,"cause)":{"public":1}
,"schedulerstarted":{"public":1}
,"schedulerinstandbymode":{"public":1}
,"schedulershutdown":{"public":1}
}
;Search.control.loadWordPairs(pairs);
