var pairs =
{
"jobfactory":{"ffc-can":1,"configured":1,"simply":1,"accomplish":1}
,"ffc-can":{"find":1}
,"find":{"new":1}
,"new":{"home":1}
,"home":{"topic":1}
,"topic":{"example":1}
,"example":{"jobs":1}
,"jobs":{"chapter":1}
,"chapter":{"trigger":1}
,"trigger":{"fires":1}
,"fires":{"job":1}
,"job":{"associated":1,"class":1,"instance":1}
,"associated":{"instantiated":1,"scheduler.setjobfactory":1}
,"instantiated":{"via":1}
,"via":{"jobfactory":1}
,"configured":{"scheduler":1}
,"scheduler":{"default":1}
,"default":{"jobfactory":1}
,"simply":{"calls":1}
,"calls":{"newinstance":1}
,"newinstance":{"job":1}
,"class":{"may":1}
,"may":{"want":1}
,"want":{"create":1}
,"create":{"implementation":1}
,"implementation":{"jobfactory":1}
,"accomplish":{"things":1}
,"things":{"having":1}
,"having":{"application\u0027s":1}
,"application\u0027s":{"ioc":1}
,"ioc":{"ffc-spell":1}
,"ffc-spell":{"acronyms":1}
,"acronyms":{"container":1}
,"container":{"produce\u002Finitialize":1}
,"produce\u002Finitialize":{"job":1}
,"instance":{"org.quartz.spi.jobfactory":1}
,"org.quartz.spi.jobfactory":{"interface":1}
,"interface":{"associated":1}
,"scheduler.setjobfactory":{"(fact)":1}
,"(fact)":{"method":1}
}
;Search.control.loadWordPairs(pairs);
