var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fjmx-port":{"listening":1}
,"listening":{"jmx-port":1}
,"jmx-port":{"deprecated":1,"disabled":1,"9520":1}
,"deprecated":{"alternatively":1}
,"alternatively":{"monitoring":1}
,"monitoring":{"features":1}
,"features":{"provided":1}
,"provided":{"terracotta":1}
,"terracotta":{"management":1,"server\u0027s":1}
,"management":{"console":1}
,"console":{"(see":1,"user":1}
,"(see":{"terracotta":1,"wan":1}
,"user":{"guide)":1}
,"guide)":{"wan":1,"jmx-port":1}
,"wan":{"replication":1}
,"replication":{"service":1,"user":1}
,"service":{"(see":1}
,"disabled":{"default":1}
,"default":{"enable":1,"value":1,"9510":1}
,"enable":{"add":1}
,"add":{"jmx-enabled=\u0022":1}
,"jmx-enabled=\u0022":{"true":1}
,"true":{"<server":1,"section":1}
,"<server":{"host>":1,"host=\u0022":1}
,"host>":{"sections":1}
,"sections":{"tc-config.xml":1}
,"tc-config.xml":{"example":1}
,"example":{"<server":1}
,"host=\u0022":{"localhost":1}
,"localhost":{"name=\u0022":1}
,"name=\u0022":{"server":1}
,"server":{"name1":1}
,"name1":{"jmx-enabled=\u0022":1}
,"section":{"lets":1}
,"lets":{"port":1}
,"port":{"terracotta":1,"defaulted":1}
,"server\u0027s":{"jmx":1}
,"jmx":{"connector":1}
,"connector":{"listens":1}
,"listens":{"default":1}
,"value":{"jmx-port":1,"default":1,"tsa-port":1}
,"9520":{"tsa-port":1,"<\u002Fjmx-port>":1}
,"tsa-port":{"value":1,"plus":1}
,"9510":{"port":1}
,"defaulted":{"value":1}
,"plus":{"sample":1}
,"sample":{"configuration":1}
,"configuration":{"snippet":1}
,"snippet":{"<jmx-port>":1}
,"<jmx-port>":{"9520":1}
}
;Search.control.loadWordPairs(pairs);
