var pairs =
{
"local":{"transactions":1,"transactional":1,"write":1,"store":1}
,"transactions":{"local":1,"following":1,"instantiate":1}
,"transactional":{"caches":1}
,"caches":{"(with":1}
,"(with":{"transactionalmode":1}
,"transactionalmode":{"attribute":1}
,"attribute":{"local":1}
,"write":{"local":1}
,"store":{"using":1,"immediately":1,"may":1}
,"using":{"api":1,"following":1}
,"api":{"part":1,"local":1}
,"part":{"ehcache":1}
,"ehcache":{"core":1}
,"core":{"api":1}
,"following":{"characteristics":1,"version":1}
,"characteristics":{"recovery":1}
,"recovery":{"occurs":1}
,"occurs":{"time":1}
,"time":{"element":1}
,"element":{"accessed":1}
,"accessed":{"updates":1}
,"updates":{"written":1}
,"written":{"underlying":1}
,"underlying":{"store":1}
,"immediately":{"operations":1}
,"operations":{"underlying":1,"local":1,"fail":1}
,"may":{"block":1}
,"block":{"during":1}
,"during":{"commit":1}
,"commit":{"operations":1,"failures":1,"timeout":1,"txctrl.commit":1,"ignore":1}
,"instantiate":{"transactioncontroller":1}
,"transactioncontroller":{"instance":1,"txctrl":1}
,"instance":{"instead":1,"transactioncontroller":1}
,"instead":{"transaction":1}
,"transaction":{"manager":1,"bound":1,"process":1,"started":1,"times":1}
,"manager":{"instance":1}
,"txctrl":{"=cachemanager.gettransactioncontroller":1}
,"=cachemanager.gettransactioncontroller":{"txctrl.begin":1}
,"txctrl.begin":{"cache":1}
,"cache":{"foocache":1}
,"foocache":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"foo":1}
,"foo":{"foocache.put":1}
,"foocache.put":{"bar":1}
,"bar":{"txctrl.commit":1}
,"txctrl.commit":{"rollback":1,"(true)":1}
,"rollback":{"roll":1}
,"roll":{"back":1}
,"back":{"transaction":1}
,"bound":{"current":1}
,"current":{"thread":1,"value":1}
,"thread":{"find":1,"calling":1,"commit":1}
,"find":{"transaction":1}
,"process":{"current":1}
,"calling":{"transactioncontroller.getcurrenttransactioncontext":1}
,"transactioncontroller.getcurrenttransactioncontext":{"checking":1}
,"checking":{"return":1}
,"return":{"value":1}
,"value":{"value":1,"isn\u0027t":1,"int":1}
,"isn\u0027t":{"null":1}
,"null":{"transaction":1}
,"started":{"current":1}
,"failures":{"timeouts":1}
,"timeouts":{"commit":1}
,"fail":{"transaction":1}
,"times":{"default":1}
,"default":{"timeout":1}
,"timeout":{"requires":1,"using":1}
,"requires":{"tuning":1}
,"tuning":{"current":1}
,"int":{"currentdefaulttransactiontimeout":1}
,"currentdefaulttransactiontimeout":{"=txctrl.getdefaulttransactiontimeout":1}
,"=txctrl.getdefaulttransactiontimeout":{"txctrl.setdefaulttransactiontimeout":1}
,"txctrl.setdefaulttransactiontimeout":{"(30)":1}
,"(30)":{"\u002F\u002Fin":1}
,"\u002F\u002Fin":{"seconds":1}
,"seconds":{"--must":1}
,"--must":{"greater":1}
,"greater":{"zero":1}
,"zero":{"bypass":1}
,"bypass":{"commit":1}
,"version":{"commit":1}
,"(true)":{"\u002F\u002F\u0022":1}
,"\u002F\u002F\u0022":{"true":1}
,"true":{"forces":1}
,"forces":{"commit":1}
,"ignore":{"timeout":1}
}
;Search.control.loadWordPairs(pairs);
