var pairs =
{
"live":{"backup":1}
,"backup":{"backups":1,"feature":1,"stripe\u0027s":1}
,"backups":{"entire":1}
,"entire":{"data":1}
,"data":{"across":1,"providing":1,"backup":1}
,"across":{"stripes":1}
,"stripes":{"(mirror":1}
,"(mirror":{"groups)":1}
,"groups)":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"array":1}
,"array":{"made":1}
,"made":{"using":1}
,"using":{"tmc":1}
,"tmc":{"backup":1}
,"feature":{"feature":1,"creates":1,"available":1}
,"creates":{"time-stamped":1}
,"time-stamped":{"backup":1}
,"stripe\u0027s":{"data":1}
,"providing":{"snapshot":1}
,"snapshot":{"tsa\u0027s":1}
,"tsa\u0027s":{"in-memory":1}
,"in-memory":{"data":1}
,"available":{"fast":1}
,"fast":{"restartability":1}
,"restartability":{"(frs":1}
,"(frs":{"enabled":1}
,"enabled":{"tsa":1}
,"tsa":{"(<restartable":1}
,"(<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"tc-config.xml)":1}
}
;Search.control.loadWordPairs(pairs);
