var pairs =
{
"calculating":{"healthchecker":1,"worst-case":1}
,"healthchecker":{"maximum":1,"discover":1,"process":1}
,"maximum":{"following":1,"time":1,"time)":1}
,"following":{"formula":1,"max":1}
,"formula":{"help":1,"response":1,"simplified":1,"yields":1}
,"help":{"compute":1}
,"compute":{"maximum":1}
,"time":{"healthchecker":1,"=(ping.idletime)":1,"socket-connection":1,"likely":1,"process":1,"l1->":1}
,"discover":{"failed":1}
,"failed":{"disconnected":1}
,"disconnected":{"remote":1,"backup":1}
,"remote":{"nodes":1}
,"nodes":{"max":1}
,"max":{"time":1}
,"=(ping.idletime)":{"socketconnectcount":1,"[socketconnectcount":1}
,"socketconnectcount":{"*[(ping.interval":1,"multiplier":1}
,"*[(ping.interval":{"*ping.probes)":1}
,"*ping.probes)":{"(socketconnecttimeout":1}
,"(socketconnecttimeout":{"*ping.interval)]":1,"*ping.interval)":1}
,"*ping.interval)]":{"note":1}
,"note":{"following":1}
,"response":{"time":1,"received":1}
,"socket-connection":{"attempt":1}
,"attempt":{"less":1,"formula":1}
,"less":{"equal":1}
,"equal":{"(socketconnecttimeout":1}
,"*ping.interval)":{"calculating":1}
,"worst-case":{"scenario":1}
,"scenario":{"(absolute":1}
,"(absolute":{"maximum":1}
,"time)":{"equality":1}
,"equality":{"used":1}
,"used":{"real-world":1}
,"real-world":{"situations":1}
,"situations":{"socket-connect":1,"active":1}
,"socket-connect":{"response":1}
,"likely":{"close":1}
,"close":{"formula":1,"together":1}
,"simplified":{"following":1}
,"[socketconnectcount":{"*(ping.interval":1}
,"*(ping.interval":{"*ping.probes)]":1}
,"*ping.probes)]":{"ping.idletime":1}
,"ping.idletime":{"trigger":1}
,"trigger":{"full":1}
,"full":{"healthchecker":1}
,"process":{"counted":1,"triggered":1}
,"counted":{"once":1}
,"once":{"effect":1,"time":1}
,"effect":{"once":1}
,"triggered":{"socketconnectcount":1}
,"multiplier":{"incremented":1}
,"incremented":{"long":1}
,"long":{"positive":1}
,"positive":{"response":1}
,"received":{"socket":1}
,"socket":{"connection":1}
,"connection":{"attempt":1}
,"yields":{"ideal":1}
,"ideal":{"value":1}
,"value":{"slight":1}
,"slight":{"variations":1}
,"variations":{"actual":1}
,"actual":{"times":1}
,"times":{"occur":1}
,"occur":{"prevent":1}
,"prevent":{"clients":1}
,"clients":{"disconnecting":1,"ensure":1,"reconnect":1}
,"disconnecting":{"quickly":1}
,"quickly":{"situation":1}
,"situation":{"active":1}
,"active":{"server":1}
,"server":{"temporarily":1,"clients":1,"may":1}
,"temporarily":{"disconnected":1}
,"backup":{"server":1,"refuse":1}
,"ensure":{"max":1}
,"l1->":{"approximately":1}
,"approximately":{"8-12":1}
,"8-12":{"seconds":1}
,"seconds":{"longer":1}
,"longer":{"l2->":1}
,"l2->":{"values":1}
,"values":{"close":1}
,"together":{"certain":1}
,"certain":{"situations":1}
,"may":{"kill":1}
,"kill":{"backup":1}
,"refuse":{"allow":1}
,"allow":{"clients":1}
}
;Search.control.loadWordPairs(pairs);
