var pairs =
{
"failover":{"tuning":1,"priority":1,"works":1,"provided":1}
,"tuning":{"guaranteed":1,"requires":1,"failover":1,"script":1}
,"guaranteed":{"consistency":1}
,"consistency":{"clustered":1,"using":1,"availability":1,"explicit":1,"applied":1,"default":1,"<\u002Ffailover-priority>":1,"scenario":1,"setting":1,"start":1,"fail-over-action":1,"detects":1}
,"clustered":{"environment":1,"servers":1}
,"environment":{"network":1}
,"network":{"hardware":1,"connection":1}
,"hardware":{"issues":1}
,"issues":{"result":1}
,"result":{"active":1,"inconsistencies":1}
,"active":{"node":1,"configuration":1,"further":1,"mirror":1,"monitoring":1,"g1s1.state":1,"server":1,"passive":1,"active":1,"found":1,"until":1,"responding":1,"operation":1}
,"node":{"partition":1,"run":1,"sec":1,"mirror":1,"supported":1,"stripe":1,"fails":1,"automatically":1,"determine":1,"lost":1,"failed":1,"sets":1,"continues":1,"network":1,"cannot":1,"operating":1,"continue":1,"proceed":1,"reacts":1,"waiting":1,"acting":1,"join":1,"look":1,"left":1,"specified":1,"move":1,"currently":1,"log":1}
,"partition":{"cluster":1,"active":1}
,"cluster":{"detection":1,"may":1,"active":1,"configured":1,"g1s1.health":1,"tmc":1,"cases":1,"passive":1}
,"detection":{"situation":1}
,"situation":{"results":1,"during":1,"nodes":1}
,"results":{"active-left":1}
,"active-left":{"event":1}
,"event":{"described":1}
,"described":{"previous":1}
,"previous":{"sections":1}
,"sections":{"default":1}
,"default":{"behavior":1,"setting":1}
,"behavior":{"tsa":1,"availability":1}
,"tsa":{"remaining":1,"split":1,"running":1}
,"remaining":{"passive":1}
,"passive":{"node":1,"g1s2.state":1,"server":1,"tmc":1,"waiting":1,"flag":1,"consistency":1,"standby":1}
,"run":{"election":1}
,"election":{"finding":1,"won":1,"flag":1}
,"finding":{"active":1}
,"sec":{"default)":1}
,"default)":{"active":1}
,"configuration":{"ensures":1,"value":1,"tuning":1}
,"ensures":{"tight":1}
,"tight":{"availability":1}
,"availability":{"data":1,"versus":1,"default":1,"supported":1}
,"data":{"risks":1,"likely":1,"centers":1,"center)":1,"preserved":1}
,"risks":{"experiencing":1}
,"experiencing":{"so-called":1}
,"so-called":{"split":1}
,"split":{"brain":1}
,"brain":{"situation":1}
,"during":{"elections":1,"failover":1,"election":1}
,"elections":{"increased":1}
,"increased":{"case":1}
,"case":{"tsa":1,"questions":1,"happens":1,"active":1,"partition":1,"failure":1}
,"nodes":{"acting":1}
,"acting":{"active":1,"active-coordinator":1}
,"further":{"operations":1}
,"operations":{"performed":1}
,"performed":{"data":1,"explicitly":1,"operator":1}
,"likely":{"result":1}
,"inconsistencies":{"depending":1}
,"depending":{"mission":1}
,"mission":{"priorities":1}
,"priorities":{"cluster":1}
,"may":{"configured":1,"accessible":1,"required":1}
,"configured":{"emphasize":1,"otherwise":1,"fail-over":1}
,"emphasize":{"consistency":1}
,"using":{"failover":1,"server":1,"rest":1,"following":1,"tmc":1}
,"requires":{"feature":1}
,"feature":{"part":1}
,"part":{"license":1,"output":1}
,"license":{"key":1}
,"key":{"contact":1}
,"contact":{"nearest":1}
,"nearest":{"software":1}
,"software":{"representative":1,"ideal":1,"accessing":1}
,"representative":{"case":1}
,"questions":{"availability":1}
,"versus":{"consistency":1}
,"setting":{"seconds":1,"availabiility":1,"performed":1,"effect":1}
,"seconds":{"passives":1}
,"passives":{"automatically":1}
,"automatically":{"become":1,"stops":1,"--failfast":1}
,"become":{"actives":1,"active":1}
,"actives":{"consistency":1}
,"explicit":{"settings":1}
,"settings":{"<failover-priority>":1}
,"<failover-priority>":{"waiting-for-promotion":1,"consistency":1}
,"waiting-for-promotion":{"state":1,"g1s2.state":1}
,"state":{"requesting":1,"passive-standby":1,"state":1,"raises":1,"provided":1,"--restart":1}
,"requesting":{"operator":1}
,"operator":{"issue":1,"events":1,"alerts":1,"alert":1,"$kit\u002Fserver\u002Fbin\u002Ffail-over-action.sh":1}
,"issue":{"failover-action":1}
,"failover-action":{"command":1}
,"command":{"even":1,"starting":1,"passive":1,"performed":1,"call":1}
,"even":{"absence":1}
,"absence":{"configuration":1}
,"value":{"default":1}
,"supported":{"configuration":1,"common":1}
,"priority":{"consistency":1}
,"applied":{"clusters":1}
,"clusters":{"consisting":1}
,"consisting":{"two":1}
,"two":{"data":1,"servers":1}
,"centers":{"mirror":1}
,"mirror":{"group":1,"node":1,"groups":1}
,"group":{"cluster":1,"two":1}
,"groups":{"mirror":1}
,"common":{"example":1}
,"example":{"scenario":1}
,"scenario":{"integration":1,"mirror":1}
,"integration":{"server":1,"alert":1}
,"server":{"instances":1,"added":1,"stats":1,"crashing":1,"indicates":1,"waiting":1,"extended":1,"restart":1}
,"instances":{"(one":1}
,"(one":{"per":1}
,"per":{"data":1}
,"center)":{"require":1}
,"require":{"shared":1}
,"shared":{"(active-active":1}
,"(active-active":{"replicated)":1}
,"replicated)":{"database":1}
,"database":{"switch":1,"server":1}
,"switch":{"failover-priority":1}
,"failover-priority":{"consistency":1}
,"availabiility":{"changing":1}
,"changing":{"setting":1}
,"explicitly":{"following":1}
,"following":{"property":1,"block":1,"url":1}
,"property":{"<tc-config>":1}
,"<tc-config>":{"<servers>":1}
,"<servers>":{"<failover-priority>":1}
,"<\u002Ffailover-priority>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"<\u002Ftc-config>":1}
,"<\u002Ftc-config>":{"consistency":1}
,"servers":{"configured":1,"following":1,"fetch":1}
,"otherwise":{"startup":1}
,"startup":{"fail":1}
,"fail":{"consistency":1}
,"effect":{"single":1,"modified":1}
,"single":{"node":1}
,"stripe":{"effect":1,"once":1,"active":1}
,"modified":{"stripe":1}
,"once":{"new":1}
,"new":{"server":1,"active":1}
,"added":{"failover":1}
,"works":{"various":1}
,"various":{"scenarios":1}
,"scenarios":{"active":1}
,"fails":{"active":1,"mirror":1,"network":1}
,"stops":{"processing":1}
,"processing":{"data":1}
,"preserved":{"lost":1}
,"lost":{"transactions":1,"cannot":1,"mirror":1,"replayed":1}
,"transactions":{"point":1,"transit":1,"lost":1}
,"point":{"mirror":1}
,"determine":{"connection":1,"whether":1,"mirror":1,"active":1}
,"connection":{"active":1,"mirror":1,"lost":1,"fails":1,"refused":1}
,"cannot":{"determine":1}
,"whether":{"active":1,"just":1}
,"failed":{"whether":1}
,"just":{"break":1}
,"break":{"network":1}
,"sets":{"status":1}
,"status":{"waiting_for_promotion":1}
,"waiting_for_promotion":{"waits":1}
,"waits":{"human":1,"external":1}
,"human":{"interaction":1,"intervention":1}
,"interaction":{"determine":1}
,"continues":{"operation":1}
,"operation":{"without":1,"consequentially":1}
,"without":{"interruption":1,"changes":1}
,"interruption":{"human":1,"mirror":1}
,"intervention":{"required":1}
,"required":{"restart":1,"initiates":1}
,"restart":{"mirror":1,"automatically":1}
,"operating":{"however":1,"mirror":1,"above":1}
,"however":{"active":1,"case":1}
,"continue":{"without":1}
,"proceed":{"active":1}
,"above":{"details":1}
,"details":{"mirror":1}
,"reacts":{"case":1}
,"happens":{"transactions":1}
,"transit":{"during":1}
,"provided":{"client":1,"fail-over-action":1,"node":1}
,"client":{"running":1}
,"running":{"transactions":1,"g1s2.health":1,"failover-priority":1}
,"replayed":{"new":1}
,"monitoring":{"using":1}
,"stats":{"script":1}
,"script":{"server-stat":1,"packaged":1,"delivers":1}
,"server-stat":{"[sh\u002Fbat]":1,"utility":1}
,"[sh\u002Fbat]":{"script":1,"live":1,"deliver":1}
,"packaged":{"software":1}
,"ideal":{"tool":1}
,"tool":{"monitor":1}
,"monitor":{"cluster":1}
,"fail-over":{"tuning":1,"action":1}
,"delivers":{"information":1}
,"information":{"regarding":1,"shown":1,"using":1,"cluster":1}
,"regarding":{"states":1}
,"states":{"clustered":1}
,"block":{"shows":1}
,"shows":{"part":1}
,"output":{"server-stat":1,"below":1,"rest":1}
,"live":{"2-node":1}
,"2-node":{"cluster":1}
,"g1s1.health":{"g1s1.role":1}
,"g1s1.role":{"active":1}
,"g1s1.state":{"active-coordinator":1}
,"active-coordinator":{"g1s1.port":1,"cluster":1}
,"g1s1.port":{"9540":1}
,"9540":{"g1s1.group":1,"localhost.group":1}
,"g1s1.group":{"name":1}
,"name":{"group1":1,"unknown":1,"g1s2":1}
,"group1":{"g1s2.health":1,"case":1,"role":1,"name":1}
,"g1s2.health":{"g1s2.role":1}
,"g1s2.role":{"passive":1,"waiting-for-promotion":1}
,"g1s2.state":{"passive-standby":1}
,"passive-standby":{"g1s2.port":1,"managementport":1}
,"g1s2.port":{"9640":1}
,"9640":{"g1s2.group":1}
,"g1s2.group":{"name":1}
,"crashing":{"staus":1}
,"staus":{"deliverd":1}
,"deliverd":{"server-stat":1}
,"deliver":{"output":1,"useful":1}
,"below":{"localhost.health":1,"health":1}
,"localhost.health":{"unknown":1}
,"unknown":{"localhost.role":1,"localhost.state":1,"localhost.port":1,"localhost.error":1}
,"localhost.role":{"unknown":1}
,"localhost.state":{"unknown":1}
,"localhost.port":{"9540":1}
,"localhost.group":{"name":1}
,"localhost.error":{"connection":1}
,"refused":{"localhost:9540":1}
,"localhost:9540":{"tsa":1}
,"role":{"field":1,"waiting-for-promotion":1,"attribute":1}
,"field":{"passive":1}
,"indicates":{"waiting":1,"passive":1}
,"waiting":{"promotion":1}
,"promotion":{"monitoring":1,"give":1,"however":1}
,"rest":{"endpoints":1,"endpoint":1}
,"endpoints":{"server-stat":1}
,"utility":{"internally":1}
,"internally":{"uses":1}
,"uses":{"rest":1}
,"endpoint":{"servers":1,"addressed":1,"pass":1}
,"fetch":{"information":1}
,"shown":{"output":1}
,"addressed":{"directly":1}
,"directly":{"information":1}
,"url":{"<server:mgmt-port>\u002Ftc-management-api\u002Fv2\u002Flocal\u002Fstat":1,"passive":1}
,"<server:mgmt-port>\u002Ftc-management-api\u002Fv2\u002Flocal\u002Fstat":{"pointing":1}
,"pointing":{"url":1}
,"give":{"response":1}
,"response":{"below":1}
,"health":{"role":1}
,"managementport":{"<port":1}
,"<port":{"number>":1}
,"number>":{"servergroupname":1}
,"servergroupname":{"group1":1}
,"g1s2":{"role":1}
,"attribute":{"indicates":1}
,"tmc":{"case":1,"receive":1,"unable":1,"provides":1,"log":1,"may":1}
,"receive":{"operator":1}
,"events":{"indicating":1,"consistency":1}
,"indicating":{"passive":1}
,"failure":{"active":1}
,"unable":{"deliver":1}
,"useful":{"information":1}
,"cases":{"tmc":1}
,"provides":{"accurate":1}
,"accurate":{"operator":1}
,"start":{"consider":1}
,"consider":{"command":1}
,"starting":{"server":1}
,"extended":{"flag":1}
,"flag":{"--active":1,"node":1,"ignored":1}
,"--active":{"$kit\u002Fserver\u002Fbin\u002Fstart-server.sh":1,"flag":1}
,"$kit\u002Fserver\u002Fbin\u002Fstart-server.sh":{"[bat]":1}
,"[bat]":{"\u002Fpath\u002Fto\u002Ftc-config.xml":1}
,"\u002Fpath\u002Fto\u002Ftc-config.xml":{"<server-name>":1}
,"<server-name>":{"--active":1,"--promote":1,"action":1}
,"won":{"become":1}
,"found":{"during":1,"case":1}
,"ignored":{"node":1}
,"join":{"cluster":1,"passive":1}
,"look":{"active":1}
,"until":{"found":1}
,"responding":{"join":1}
,"fail-over-action":{"command":1}
,"standby":{"running":1}
,"detects":{"node":1}
,"left":{"move":1}
,"move":{"waiting-for-promotion":1,"active_coordinator":1}
,"raises":{"operator":1}
,"alerts":{"operator":1}
,"alert":{"appearing":1,"3rd":1}
,"appearing":{"tmc":1}
,"log":{"files":1,"appropriately":1}
,"files":{"tmc":1}
,"accessible":{"stripe":1}
,"consequentially":{"integration":1}
,"3rd":{"party":1}
,"party":{"software":1}
,"accessing":{"logs":1}
,"logs":{"may":1}
,"initiates":{"continuous":1}
,"continuous":{"logging":1}
,"logging":{"waits":1}
,"external":{"trigger":1}
,"trigger":{"trigger":1,"provided":1}
,"$kit\u002Fserver\u002Fbin\u002Ffail-over-action.sh":{"[bat]":1}
,"--promote":{"|--restart":1,"node":1}
,"|--restart":{"|--failfast":1}
,"|--failfast":{"command":1}
,"call":{"rest":1}
,"pass":{"fail-over":1}
,"action":{"node":1,"description":1}
,"specified":{"<server-name>":1}
,"description":{"--promote":1}
,"active_coordinator":{"state":1}
,"currently":{"waiting-for-promotion":1}
,"--restart":{"node":1}
,"appropriately":{"shutdown":1}
,"shutdown":{"mark":1,"without":1}
,"mark":{"dirty":1}
,"dirty":{"server":1}
,"--failfast":{"node":1}
,"changes":{"database":1}
}
;Search.control.loadWordPairs(pairs);
