var pairs =
{
"performance":{"improvement":1,"performance":1,"tips":1,"run":1}
,"improvement":{"performance":1,"bulk":1,"using":1}
,"bulk":{"loading":1,"load":1}
,"loading":{"order":1,"multiple":1,"likely":1}
,"order":{"magnitude":1}
,"magnitude":{"faster":1}
,"faster":{"ehcacheperf":1}
,"ehcacheperf":{"(spring":1}
,"(spring":{"pet":1}
,"pet":{"clinic)":1}
,"clinic)":{"project":1}
,"project":{"bulk-load":1}
,"bulk-load":{"test":1}
,"test":{"shows":1}
,"shows":{"performance":1}
,"using":{"terracotta":1}
,"terracotta":{"cluster":1}
,"cluster":{"consider":1}
,"consider":{"multi-threading":1}
,"multi-threading":{"likely":1}
,"likely":{"improve":1}
,"improve":{"performance":1}
,"tips":{"bulk":1}
,"multiple":{"nodes":1,"cachemanagers":1,"machines":1}
,"nodes":{"-the":1,"bulk":1}
,"-the":{"implementation":1}
,"implementation":{"scales":1}
,"scales":{"load":1}
,"load":{"split":1,"mode":1}
,"split":{"against":1}
,"against":{"multiple":1}
,"cachemanagers":{"multiple":1}
,"machines":{"adding":1}
,"adding":{"nodes":1}
,"run":{"bulk":1,"cache":1}
,"mode":{"time":1}
,"time":{"-terracotta":1}
,"-terracotta":{"clustering":1}
,"clustering":{"provides":1}
,"provides":{"consistency":1}
,"consistency":{"scaling":1,"however":1}
,"scaling":{"durability":1}
,"durability":{"applications":1}
,"applications":{"require":1}
,"require":{"consistency":1}
,"however":{"reference":1}
,"reference":{"data":1}
,"data":{"acceptable":1}
,"acceptable":{"run":1}
,"cache":{"permanently":1}
,"permanently":{"inconsistent":1}
,"inconsistent":{"mode":1}
}
;Search.control.loadWordPairs(pairs);
