var pairs =
{
"connecting":{"terracotta":1,"remotely":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"connect":1,"following":1}
,"connect":{"terracotta":1,"tmc":1}
,"following":{"connect":1,"uri":1}
,"tmc":{"using":1,"security":1,"without":1,"settings":1,"click":1,"online":1}
,"using":{"following":1,"tmc":1}
,"uri":{"standard":1}
,"standard":{"web":1}
,"web":{"browser":1}
,"browser":{"http:\u002F\u002Flocalhost:9889\u002Ftmc":1,"connections":1}
,"http:\u002F\u002Flocalhost:9889\u002Ftmc":{"connecting":1}
,"remotely":{"substitute":1}
,"substitute":{"appropriate":1}
,"appropriate":{"hostname":1}
,"hostname":{"secure":1}
,"secure":{"browser":1}
,"connections":{"https":1}
,"https":{"instead":1}
,"instead":{"http":1}
,"http":{"first":1}
,"first":{"connect":1}
,"security":{"setup":1,"information":1}
,"setup":{"page":1}
,"page":{"appears":1}
,"appears":{"choose":1}
,"choose":{"run":1}
,"run":{"tmc":1}
,"without":{"authentication":1}
,"authentication":{"authentication":1,"enabled\u002Fdisabled":1}
,"enabled\u002Fdisabled":{"tmc":1}
,"settings":{"panel":1}
,"panel":{"information":1}
,"information":{"setting":1,"using":1}
,"setting":{"security":1}
,"click":{"help":1}
,"help":{"links":1,"choosing":1,"toolbar":1}
,"links":{"available":1}
,"available":{"certain":1}
,"certain":{"pages":1}
,"pages":{"within":1}
,"within":{"access":1}
,"access":{"tmc":1}
,"online":{"help":1}
,"choosing":{"help":1}
}
;Search.control.loadWordPairs(pairs);
