var pairs =
{
"configuration":{"types":1,"type":1,"cluster":1,"terracotta":1}
,"types":{"terracotta":1,"listed":1}
,"terracotta":{"supports":1,"run-time":1,"server":1}
,"supports":{"terracotta":1,"creating":1}
,"run-time":{"component":1}
,"component":{"supports":1}
,"creating":{"instances":1}
,"instances":{"configuration":1}
,"listed":{"following":1}
,"following":{"table":1}
,"table":{"configuration":1}
,"type":{"common-cluster":1}
,"common-cluster":{"view":1}
,"view":{"configuration":1,"custom":1}
,"cluster":{"common-memory":1}
,"common-memory":{"configure":1}
,"configure":{"jvm":1,"tc-config.xml":1}
,"jvm":{"memory":1}
,"memory":{"settings":1}
,"settings":{"common-ports":1}
,"common-ports":{"view":1}
,"custom":{"port":1}
,"port":{"configuration":1}
,"server":{"array":1,"name":1}
,"array":{"instance":1}
,"instance":{"tc-config":1,"matches":1}
,"tc-config":{"configure":1}
,"tc-config.xml":{"file":1}
,"file":{"tc-server-server":1}
,"tc-server-server":{"assign":1}
,"assign":{"server":1}
,"name":{"terracotta":1,"tc-config.xml":1}
,"matches":{"server":1}
}
;Search.control.loadWordPairs(pairs);
