var pairs =
{
"high-availability":{"network":1}
,"network":{"architecture":1,"configurations":1,"machine":1}
,"architecture":{"testing":1}
,"testing":{"advantage":1}
,"advantage":{"terracotta":1}
,"terracotta":{"active-mirror":1,"clients":1,"failover":1}
,"active-mirror":{"server":1}
,"server":{"configuration":1,"instances":1}
,"configuration":{"certain":1}
,"certain":{"network":1}
,"configurations":{"necessary":1,"known":1,"work":1,"listed":1}
,"necessary":{"prevent":1}
,"prevent":{"split-brain":1}
,"split-brain":{"scenarios":1}
,"scenarios":{"ensure":1}
,"ensure":{"terracotta":1}
,"clients":{"(l1s)":1}
,"(l1s)":{"server":1}
,"instances":{"(l2s)":1}
,"(l2s)":{"behave":1}
,"behave":{"deterministic":1}
,"deterministic":{"manner":1}
,"manner":{"failure":1}
,"failure":{"occurs":1,"whether":1}
,"occurs":{"regardless":1}
,"regardless":{"nature":1}
,"nature":{"failure":1}
,"whether":{"network":1}
,"machine":{"type":1}
,"type":{"section":1}
,"section":{"outlines":1}
,"outlines":{"two":1}
,"two":{"possible":1}
,"possible":{"network":1}
,"known":{"work":1}
,"work":{"terracotta":1,"reliably":1}
,"failover":{"possible":1}
,"reliably":{"configurations":1}
,"listed":{"document":1}
,"document":{"tested":1}
,"tested":{"fully":1}
,"fully":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
