var pairs =
{
"environment":{"interoperability":1}
,"interoperability":{"questions":1}
,"questions":{"information":1}
,"information":{"platform":1,"latest":1,"page":1,"previous":1,"release":1,"integrations":1}
,"platform":{"compatibility":1,"support":1}
,"compatibility":{"version":1,"information":1}
,"version":{"terracotta":1}
,"terracotta":{"software":1,"products":1,"process":1,"server":1,"scripts":1,"clustering":1}
,"software":{"information":1,"ubuntu":1,"compatibility":1,"work":1,"integrates":1}
,"latest":{"releases":1,"platform":1}
,"releases":{"terracotta":1,"run":1}
,"products":{"including":1}
,"including":{"link":1}
,"link":{"latest":1}
,"support":{"found":1}
,"found":{"release":1}
,"release":{"platform":1}
,"page":{"page":1,"contains":1,"faq":1}
,"contains":{"table":1}
,"table":{"links":1}
,"links":{"information":1}
,"previous":{"releases":1}
,"run":{"terracotta":1}
,"process":{"microsoft":1,"terracotta":1}
,"microsoft":{"windows":1}
,"windows":{"service":1}
,"service":{"starting":1,"terracotta":1}
,"starting":{"terracotta":1}
,"server":{"windows":1,"array":1,"(l2)":1,"performs":1,"simplest":1}
,"array":{"product":1}
,"product":{"documentation":1}
,"documentation":{"advice":1,"terracotta":1,"<<ffc-update":1}
,"advice":{"running":1}
,"running":{"terracotta":1}
,"ubuntu":{"known":1,"default":1}
,"known":{"issues":1,"cause":1}
,"issues":{"trying":1}
,"trying":{"run":1}
,"default":{"shell":1,"jdk":1,"garbage":1}
,"shell":{"dashbash":1,"bash":1}
,"dashbash":{"terracotta":1}
,"scripts":{"don\u0027t":1,"\u002Fbin\u002Fbash":1,"believe":1}
,"don\u0027t":{"behave":1}
,"behave":{"dash":1}
,"dash":{"solve":1}
,"solve":{"issue":1}
,"issue":{"setting":1}
,"setting":{"default":1}
,"bash":{"changing":1}
,"changing":{"\u002Fbin\u002Fsh":1}
,"\u002Fbin\u002Fsh":{"scripts":1}
,"\u002Fbin\u002Fbash":{"ubuntu":1}
,"jdk":{"gnu":1}
,"gnu":{"terracotta":1}
,"faq":{"unknownhostexception":1,"section":1}
,"unknownhostexception":{"faq":1}
,"section":{"specific":1}
,"specific":{"errors":1}
,"errors":{"warnings":1}
,"warnings":{"garbage":1}
,"garbage":{"collector":1}
,"collector":{"terracotta":1,"pre-configured":1,"(cms)":1}
,"(l2)":{"process":1}
,"performs":{"best":1}
,"best":{"default":1,"reduce":1}
,"pre-configured":{"startup":1}
,"startup":{"scripts":1}
,"believe":{"java":1}
,"java":{"causing":1,"technologies":1}
,"causing":{"performance":1}
,"performance":{"degradation":1}
,"degradation":{"terracotta":1}
,"simplest":{"best":1}
,"reduce":{"latencies":1}
,"latencies":{"reducing":1}
,"reducing":{"collection":1}
,"collection":{"times":1}
,"times":{"store":1}
,"store":{"data":1}
,"data":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"generally":1}
,"generally":{"concurrent":1}
,"concurrent":{"mark":1}
,"mark":{"sweep":1}
,"sweep":{"collector":1}
,"(cms)":{"discouraged":1}
,"discouraged":{"known":1}
,"cause":{"heap":1}
,"heap":{"fragmentation":1}
,"fragmentation":{"certain":1}
,"certain":{"application-data":1}
,"application-data":{"usage":1}
,"usage":{"patterns":1}
,"patterns":{"expert":1}
,"expert":{"developers":1}
,"developers":{"considering":1}
,"considering":{"cms":1}
,"cms":{"consult":1}
,"consult":{"oracle":1}
,"oracle":{"tuning":1}
,"tuning":{"best-practice":1}
,"best-practice":{"documentation":1}
,"clustering":{"work":1}
,"work":{"hibernate":1,"terracotta":1}
,"hibernate":{"ehcache":1,"second-level":1}
,"ehcache":{"enable":1,"product":1}
,"enable":{"cluster":1}
,"cluster":{"hibernate":1}
,"second-level":{"caches":1}
,"caches":{"information":1}
,"integrations":{"book":1}
,"book":{"ehcache":1,"becomes":1}
,"<<ffc-update":{"ref":1}
,"ref":{"integrations":1}
,"becomes":{"available":1}
,"available":{"bigm":1}
,"bigm":{"libraries>>":1}
,"libraries>>":{"technologies":1}
,"technologies":{"terracotta":1,"used":1}
,"integrates":{"popular":1}
,"popular":{"java":1}
,"used":{"today":1}
,"today":{"full":1}
,"full":{"list":1}
,"list":{"contact":1}
}
;Search.control.loadWordPairs(pairs);
