var pairs =
{
"setting":{"expiration":1}
,"expiration":{"<<this":1,"configuration":1,"specify":1}
,"<<this":{"topic":1}
,"topic":{"shared":1,"switches":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"maxentriesincache":1}
,"product":{"docs.>>":1}
,"docs.>>":{"<<ffc-this":1}
,"<<ffc-this":{"topic":1}
,"switches":{"cache":1}
,"cache":{"data":1,"terracotta":1,"undergo":1,"elements":1}
,"data":{"store":1,"entries":1}
,"store":{"think":1,"without":1,"regardless":1}
,"think":{"need":1}
,"need":{"consistent":1}
,"consistent":{"within":1}
,"within":{"topic.>>":1,"allowed":1}
,"topic.>>":{"data":1}
,"entries":{"expire":1}
,"expire":{"based":1,"however":1}
,"based":{"parameters":1,"results":1}
,"parameters":{"configurable":1}
,"configurable":{"values":1}
,"values":{"eviction":1,"following":1,"based":1,"individual":1}
,"eviction":{"occurs":1,"takes":1,"(but":1,"configuration":1}
,"occurs":{"expired":1,"bring":1}
,"expired":{"elements":1}
,"elements":{"first":1,"(cache":1,"may":1,"caches":1}
,"first":{"removed":1}
,"removed":{"having":1}
,"having":{"effective":1}
,"effective":{"expiration":1}
,"configuration":{"critical":1,"impact":1,"affects":1}
,"critical":{"optimizing":1}
,"optimizing":{"resources":1}
,"resources":{"heap":1}
,"heap":{"maintaining":1}
,"maintaining":{"overall":1}
,"overall":{"performance":1}
,"performance":{"add":1,"tests":1}
,"add":{"expiration":1}
,"specify":{"values":1}
,"following":{"<cache>":1}
,"<cache>":{"attributes":1}
,"attributes":{"tune":1}
,"tune":{"values":1}
,"results":{"performance":1}
,"tests":{"timetoidleseconds":1}
,"timetoidleseconds":{"maximum":1}
,"maximum":{"number":1,"sum":1}
,"number":{"seconds":1,"elements":1}
,"seconds":{"element":1}
,"element":{"exist":1,"expires":1,"flushing":1}
,"exist":{"bigm":1}
,"bigm":{"bigmemory":1}
,"bigmemory":{"data":1,"max":1}
,"without":{"accessed":1}
,"accessed":{"element":1}
,"expires":{"limit":1}
,"limit":{"longer":1}
,"longer":{"returned":1}
,"returned":{"bigmemory":1}
,"max":{"default":1}
,"default":{"value":1}
,"value":{"means":1}
,"means":{"tti":1,"ttl":1,"cache":1}
,"tti":{"eviction":1}
,"takes":{"place":1}
,"place":{"(infinite":1}
,"(infinite":{"lifetime)":1}
,"lifetime)":{"timetoliveseconds":1,"bmm":1}
,"timetoliveseconds":{"maximum":1}
,"regardless":{"element":1}
,"ttl":{"eviction":1}
,"maxentriesincache":{"maximum":1,"reflects":1}
,"sum":{"total":1}
,"total":{"number":1}
,"(cache":{"entries)":1}
,"entries)":{"allowed":1}
,"allowed":{"distributed":1,"target":1}
,"distributed":{"cache":1}
,"terracotta":{"clients":1,"server":1}
,"clients":{"target":1}
,"target":{"exceeded":1,"default":1}
,"exceeded":{"eviction":1}
,"bring":{"count":1}
,"count":{"within":1}
,"undergo":{"capacity":1}
,"capacity":{"eviction":1}
,"(but":{"periodic":1}
,"periodic":{"resource":1}
,"resource":{"evictions":1}
,"evictions":{"allowed)":1}
,"allowed)":{"note":1}
,"note":{"maxentriesincache":1}
,"reflects":{"storage":1}
,"storage":{"allocated":1}
,"allocated":{"terracotta":1}
,"server":{"array":1}
,"array":{"eternal":1}
,"eternal":{"cache\u0027s":1,"flag":1,"eternal":1,"elements":1}
,"cache\u0027s":{"eternal":1}
,"flag":{"overrides":1}
,"overrides":{"finite":1}
,"finite":{"tti\u002Fttl":1}
,"tti\u002Fttl":{"values":1}
,"individual":{"cache":1}
,"may":{"eternal":1,"evicted":1}
,"caches":{"expire":1}
,"however":{"may":1}
,"evicted":{"information":1}
,"information":{"configuration":1}
,"impact":{"eviction":1}
,"affects":{"element":1}
,"flushing":{"eviction":1}
}
;Search.control.loadWordPairs(pairs);
