var pairs =
{
"start":{"stop":1}
,"stop":{"server":1}
,"server":{"scripts":1,"optionally":1,"note":1,"named":1,"exists":1,"started":1,"gracefully":1,"valid":1,"production":1,"standby":1,"failover":1,"shut":1,"secured":1,"user":1,"security":1}
,"scripts":{"(start-tc-server":1}
,"(start-tc-server":{"stop-tc-server)":1}
,"stop-tc-server)":{"start-tc-server":1}
,"start-tc-server":{"script":1}
,"script":{"run":1,"cause":1,"detects":1,"[u]":1}
,"run":{"terracotta":1}
,"terracotta":{"server":1}
,"optionally":{"specifying":1}
,"specifying":{"configuration":1}
,"configuration":{"file":1,"specified":1,"used":1}
,"file":{"microsoft":1,"url":1,"<server":1,"named":1,"used":1,"file":1,"path":1,"[--force]":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"bigmemory_home":1,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":1,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fstop-tc-server.sh":1}
,"bigmemory_home":{"%\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":1,"%\u005Cserver\u005Cbin\u005Cstop-tc-server.bat":1}
,"%\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":{"[-n":1}
,"[-n":{"<name":1}
,"<name":{"server>]":1}
,"server>]":{"[-f":1}
,"[-f":{"<config":1}
,"<config":{"specification>]":1,"specification>":1}
,"specification>]":{"unix\u002Flinux":1,"<config":1}
,"unix\u002Flinux":{"[prompt]":1}
,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":{"\u005C[-n":1}
,"\u005C[-n":{"<name":1}
,"specification>":{"path":1}
,"path":{"configuration":1,"url":1,"self-signed":1}
,"url":{"configuration":1,"ssl-secured":1}
,"<server":{"host>":1}
,"host>":{"<tsa-port>":1}
,"<tsa-port>":{"running":1}
,"running":{"terracotta":1}
,"note":{"following":1}
,"following":{"configuration":1}
,"specified":{"file":1,"server\u0027s":1,"admin":1}
,"named":{"tc-config.xml":1,"server":1}
,"tc-config.xml":{"current":1,"found":1}
,"current":{"working":1}
,"working":{"directory":1}
,"directory":{"used":1,"default":1}
,"used":{"configuration":1,"server":1,"error":1}
,"found":{"current":1}
,"default":{"configuration":1}
,"exists":{"configuration":1}
,"error":{"printed":1}
,"printed":{"standard":1}
,"standard":{"server":1}
,"started":{"stop-tc-server":1}
,"stop-tc-server":{"script":1}
,"cause":{"terracotta":1}
,"gracefully":{"terminate":1}
,"terminate":{"microsoft":1}
,"%\u005Cserver\u005Cbin\u005Cstop-tc-server.bat":{"<host-name>":1}
,"<host-name>":{"<jmx-port>":1}
,"<jmx-port>":{"<args>":1}
,"<args>":{"unix\u002Flinux":1,"<args>":1,"[f]":1}
,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fstop-tc-server.sh":{"<host-name>":1}
,"[f]":{"<file-or-url>":1}
,"<file-or-url>":{"specifies":1}
,"specifies":{"tc-config":1}
,"tc-config":{"file":1}
,"ssl-secured":{"server":1}
,"valid":{"path":1}
,"self-signed":{"certificate":1,"certificates":1}
,"certificate":{"specified":1}
,"server\u0027s":{"configuration":1}
,"[--force]":{"force":1}
,"force":{"shutdown":1}
,"shutdown":{"active":1}
,"active":{"server":1}
,"production":{"mode":1}
,"mode":{"stop-tc-server":1,"enabling":1,"[n]":1}
,"detects":{"mirror":1}
,"mirror":{"server":1}
,"standby":{"state":1}
,"state":{"isn\u0027t":1}
,"isn\u0027t":{"reachable":1}
,"reachable":{"issues":1}
,"issues":{"warning":1}
,"warning":{"fails":1}
,"fails":{"shut":1}
,"shut":{"down":1}
,"down":{"active":1,"defaults":1}
,"failover":{"concern":1}
,"concern":{"override":1}
,"override":{"behavior":1}
,"behavior":{"--force":1}
,"--force":{"flag":1}
,"flag":{"information":1,"causes":1}
,"information":{"production":1,"setting":1}
,"enabling":{"production":1}
,"[n]":{"<server-name>":1}
,"<server-name>":{"name":1}
,"name":{"server":1}
,"defaults":{"local":1}
,"local":{"host":1}
,"host":{"[s]":1}
,"[s]":{"server":1}
,"secured":{"jmx":1}
,"jmx":{"password":1,"username":1}
,"password":{"username":1,"passed":1,"[k]":1}
,"username":{"password":1,"ssl-secured":1}
,"passed":{"script":1}
,"[u]":{"specify":1}
,"specify":{"jmx":1}
,"user":{"specified":1}
,"admin":{"role":1}
,"role":{"[w]":1}
,"[w]":{"specify":1}
,"[k]":{"flag":1}
,"causes":{"invalid":1}
,"invalid":{"tms":1}
,"tms":{"ssl":1}
,"ssl":{"certificates":1}
,"certificates":{"ignored":1,"(ones":1}
,"ignored":{"option":1}
,"option":{"accept":1}
,"accept":{"self-signed":1}
,"(ones":{"signed":1}
,"signed":{"trusted":1}
,"trusted":{"ca)":1}
,"ca)":{"information":1}
,"setting":{"server":1}
,"security":{"bigmemory":1,"guide":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
}
;Search.control.loadWordPairs(pairs);
