var pairs =
{
"securing":{"tms":1}
,"tms":{"using":1}
,"using":{"terracotta":1,"keychain":1,"format":1,"flag":1}
,"terracotta":{"management":1}
,"management":{"server":1}
,"server":{"(tms)":1,"keychain":1,"entry":1,"tsa":1}
,"(tms)":{"jmx":1}
,"jmx":{"authentication":1}
,"authentication":{"every":1}
,"every":{"node":1}
,"node":{"cluster":1}
,"cluster":{"following":1}
,"following":{"entry":1}
,"entry":{"keychain":1,"using":1,"server2":1,"itself":1}
,"keychain":{"locked":1,"entry":1,"file":1,"avoid":1,"script":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"locked":{"identical":1}
,"identical":{"secret":1}
,"secret":{"jmx:net.sf.ehcache:type=repositoryservice":1}
,"jmx:net.sf.ehcache:type=repositoryservice":{"addition":1}
,"addition":{"server-server":1}
,"server-server":{"rest-agent":1}
,"rest-agent":{"communication":1}
,"communication":{"authorized":1}
,"authorized":{"using":1}
,"format":{"jmx:\u002F\u002F<user>@<host>":1}
,"jmx:\u002F\u002F<user>@<host>":{"<group-port>":1}
,"<group-port>":{"add":1}
,"add":{"entries":1}
,"entries":{"keychain":1}
,"file":{"described":1}
,"described":{"setting":1}
,"setting":{"server":1}
,"avoid":{"using":1}
,"flag":{"using":1}
,"script":{"example":1}
,"example":{"create":1}
,"create":{"entry":1}
,"server2":{"server1":1}
,"server1":{"keychain":1}
,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":{"server1keychain.tkc":1}
,"server1keychain.tkc":{"jmx:\u002F\u002Fserver2username@172.16.254.2:9530":1}
,"jmx:\u002F\u002Fserver2username@172.16.254.2:9530":{"server":1}
,"itself":{"server":1}
}
;Search.control.loadWordPairs(pairs);
