var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver":{"server":1}
,"server":{"stanza":1,"instance":1,"element":1,"host":1,"passed":1,"listens":1}
,"stanza":{"encapsulates":1}
,"encapsulates":{"configuration":1}
,"configuration":{"terracotta":1,"starts":1,"found":1,"snippet":1}
,"terracotta":{"server":1,"scripts":1}
,"instance":{"server":1,"needs":1,"configuration":1}
,"element":{"takes":1}
,"takes":{"three":1}
,"three":{"optional":1}
,"optional":{"attributes":1}
,"attributes":{"(see":1}
,"(see":{"table":1}
,"table":{"below)":1}
,"below)":{"attribute":1}
,"attribute":{"definition":1}
,"definition":{"value":1}
,"value":{"default":1,"host":1}
,"default":{"value":1}
,"host":{"address":1,"machine\u0027s":1,"runs":1,"contains":1,"name":1,"\u0027myhostname":1,"\u0027myotherhostname":1}
,"address":{"machine":1,"resolvable":1,"name":1,"0.0.0.0":1}
,"machine":{"hosting":1}
,"hosting":{"terracotta":1}
,"machine\u0027s":{"address":1}
,"resolvable":{"hostname":1}
,"hostname":{"host":1}
,"name":{"symbolic":1,"terracotta":1,"hostname":1,"i:tsa-port":1,"\u0027myhostname:tsa-port":1,"\u0027server1":1}
,"symbolic":{"name":1}
,"passed":{"terracotta":1}
,"scripts":{"start-tc-server":1}
,"start-tc-server":{"using":1}
,"using":{"<name>":1}
,"<name>":{"user-defined":1}
,"user-defined":{"string":1}
,"string":{"<host>":1}
,"<host>":{"<tsa-port>":1}
,"<tsa-port>":{"bind":1}
,"bind":{"network":1,"0.0.0.0":1,"192.168.1.27":1}
,"network":{"interface":1}
,"interface":{"terracotta":1}
,"listens":{"cluster":1}
,"cluster":{"traffic":1}
,"traffic":{"0.0.0.0":1}
,"0.0.0.0":{"specifies":1,"terracotta":1,"-->":1}
,"specifies":{"interfaces":1}
,"interfaces":{"interface\u0027s":1}
,"interface\u0027s":{"address":1}
,"needs":{"know":1}
,"know":{"configuration":1}
,"starts":{"server\u0027s":1}
,"server\u0027s":{"configured":1}
,"configured":{"name":1}
,"runs":{"host":1}
,"contains":{"server":1}
,"found":{"automatically":1}
,"automatically":{"sample":1}
,"sample":{"configuration":1}
,"snippet":{"<server>":1}
,"<server>":{"<!--my":1}
,"<!--my":{"host":1}
,"i:tsa-port":{"bind":1}
,"-->":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"myhostname":1,"myotherhostname":1}
,"myhostname":{"<!--my":1}
,"\u0027myhostname":{"name":1}
,"\u0027myhostname:tsa-port":{"bind":1}
,"myotherhostname":{"name=\u0022":1}
,"name=\u0022":{"server1":1}
,"server1":{"bind=\u0022":1}
,"bind=\u0022":{"192.168.1.27":1}
,"192.168.1.27":{"<!--my":1,"-->":1}
,"\u0027myotherhostname":{"name":1}
,"\u0027server1":{"bind":1}
}
;Search.control.loadWordPairs(pairs);
