var pairs =
{
"troubleshooting":{"questions":1}
,"questions":{"application":1}
,"application":{"interrupted":1,"often":1,"necessarily":1,"interrupt":1,"creating":1,"redeployed":1}
,"interrupted":{"thread":1,"something":1,"time":1}
,"thread":{"(or":1}
,"(or":{"threw":1}
,"threw":{"interruptedexception)":1}
,"interruptedexception)":{"terracotta":1}
,"terracotta":{"client":1,"cluster":1,"clients":1,"server":1,"configuration":1,"server)":1,"servers":1}
,"client":{"die":1,"library":1,"anticipate":1,"shut":1,"logs":1,"and\u002For":1,"server":1,"runs":1,"start":1,"jvm":1}
,"die":{"terracotta":1}
,"library":{"runs":1}
,"runs":{"application":1,"web":1}
,"often":{"involved":1}
,"involved":{"operations":1}
,"operations":{"application":1,"may":1,"additional":1}
,"necessarily":{"aware":1}
,"aware":{"operations":1}
,"may":{"interrupted":1,"near-memory-full":1,"slowed":1,"appear":1,"preventing":1,"blocked":1,"running":1,"may":1,"adequate":1,"cause":1,"encountering":1,"fixed":1}
,"something":{"terracotta":1}
,"anticipate":{"ensure":1}
,"ensure":{"application":1,"data":1,"power":1}
,"interrupt":{"clustered":1}
,"clustered":{"threads":1}
,"threads":{"common":1}
,"common":{"error":1,"reason":1}
,"error":{"cause":1,"state":1}
,"cause":{"terracotta":1,"active":1,"uneven":1,"losing":1}
,"shut":{"down":1}
,"down":{"error":1,"time":1,"happen":1,"ensure":1,"data":1}
,"state":{"restarted":1}
,"restarted":{"cluster":1}
,"cluster":{"seem":1,"performing":1,"network":1,"seeing":1,"stripe":1,"active":1,"lost":1,"went":1,"achieved":1,"members":1}
,"seem":{"running":1}
,"running":{"slowly":1,"server":1,"terminal":1,"ubuntu":1,"restartable":1,"terracotta":1}
,"slowly":{"reasons":1}
,"reasons":{"cluster":1}
,"performing":{"slow":1}
,"slow":{"down":1}
,"time":{"common":1,"problems":1,"hold":1,"every":1}
,"reason":{"slowdowns":1,"may":1,"client":1}
,"slowdowns":{"java":1,"occurring":1}
,"java":{"garbage":1}
,"garbage":{"collection":1}
,"collection":{"(gc)":1}
,"(gc)":{"cycles":1}
,"cycles":{"reason":1}
,"near-memory-full":{"conditions":1}
,"conditions":{"reached":1,"possible":1}
,"reached":{"tsa":1}
,"tsa":{"needs":1}
,"needs":{"clear":1}
,"clear":{"space":1,"crashed":1}
,"space":{"continued":1}
,"continued":{"operations":1}
,"additional":{"evictions":1}
,"evictions":{"information":1}
,"information":{"managing":1,"configuring":1,"bug":1}
,"managing":{"near-memory-full":1}
,"possible":{"cause":1}
,"active":{"server":1,"substantial":1,"terracotta":1}
,"server":{"syncing":1,"active":1,"clients":1,"running":1,"restartable":1,"remove":1,"restarts":1,"keeps":1,"either":1,"faq":1,"example":1,"seems":1,"comes":1,"separated":1,"firewall":1,"nodes":1,"processes":1,"instance":1,"instances":1,"array":1,"stripe":1,"indication":1}
,"syncing":{"mirror":1,"process":1}
,"mirror":{"server":1,"waiting":1}
,"substantial":{"load":1,"performance":1}
,"load":{"may":1,"terracotta":1}
,"slowed":{"syncing":1}
,"process":{"addition":1,"itself":1,"maintained":1,"workaround":1}
,"addition":{"syncing":1}
,"itself":{"may":1}
,"appear":{"slow":1}
,"happen":{"mirror":1}
,"waiting":{"specific":1}
,"specific":{"sequenced":1,"errors":1}
,"sequenced":{"data":1}
,"data":{"proceed":1,"restarts":1,"persist":1,"across":1,"files":1,"distributed":1,"based":1,"grossly":1,"terracotta":1,"intact":1,"directory":1,"entire":1,"persists":1,"lost":1,"cause":1,"disk":1,"remaining":1}
,"proceed":{"indicated":1}
,"indicated":{"log":1,"warnings":1}
,"log":{"messages":1,"entries":1}
,"messages":{"similar":1,"pending":1}
,"similar":{"following":1}
,"following":{"warn":1,"entry":1}
,"warn":{"com.tc.l2.ha.l2hacoordinator":1}
,"com.tc.l2.ha.l2hacoordinator":{"-10":1}
,"-10":{"messages":1}
,"pending":{"queue":1}
,"queue":{"message":1}
,"message":{"2273677":1,"log":1}
,"2273677":{"missing":1}
,"missing":{"message":1}
,"entries":{"changes":1}
,"changes":{"time":1}
,"problems":{"indicated":1}
,"warnings":{"indication":1,"cluster":1}
,"indication":{"slowdowns":1,"keys":1}
,"occurring":{"server":1}
,"clients":{"throttling":1,"attempt":1,"may":1,"redeploying":1}
,"throttling":{"transaction":1}
,"transaction":{"commits":1}
,"commits":{"appearance":1}
,"appearance":{"following":1}
,"entry":{"client":1}
,"logs":{"info":1}
,"info":{"com.tc.object.tx.remotetransactionmanagerimpl":1}
,"com.tc.object.tx.remotetransactionmanagerimpl":{"-clientid":1}
,"-clientid":{"[2]":1}
,"[2]":{"transactionid=[65037)":1}
,"transactionid=[65037)":{"took":1}
,"took":{"1000ms":1}
,"1000ms":{"add":1}
,"add":{"sequencer":1}
,"sequencer":{"1497":1}
,"1497":{"objects":1}
,"objects":{"disappear":1,"restart":1}
,"disappear":{"restart":1}
,"restart":{"server":1,"(frs)":1,"running":1,"terracotta":1,"client":1}
,"restartable":{"mode":1}
,"mode":{"server":1,"information":1,"remove":1,"can\u0027t":1,"active":1}
,"remove":{"object":1,"data":1}
,"object":{"data":1}
,"restarts":{"want":1,"run":1}
,"want":{"object":1,"objects":1}
,"persist":{"across":1,"data":1}
,"across":{"server":1,"restarts":1}
,"run":{"server":1}
,"configuring":{"fast":1}
,"fast":{"restart":1}
,"(frs)":{"old":1}
,"old":{"objects":1}
,"keeps":{"object":1}
,"either":{"disable":1}
,"disable":{"restartable":1}
,"files":{"disk":1}
,"disk":{"restart":1,"write":1,"cache":1,"caching":1}
,"faq":{"question":1}
,"question":{"enable":1}
,"enable":{"restartable":1}
,"can\u0027t":{"certain":1}
,"certain":{"nodes":1}
,"nodes":{"terracotta":1,"cluster":1,"exiting":1}
,"network":{"firewall":1,"latency":1}
,"firewall":{"may":1,"example":1,"client":1}
,"preventing":{"different":1}
,"different":{"nodes":1}
,"seeing":{"terracotta":1}
,"attempt":{"connect":1}
,"connect":{"terracotta":1}
,"example":{"server":1,"backup":1}
,"seems":{"knowledge":1}
,"knowledge":{"attempts":1}
,"attempts":{"clients":1}
,"blocked":{"firewall":1}
,"backup":{"terracotta":1}
,"comes":{"active":1,"due":1}
,"separated":{"active":1}
,"and\u002For":{"server":1}
,"exiting":{"regularly":1,"exiting":1,"logs)":1}
,"regularly":{"without":1,"may":1}
,"without":{"reason":1}
,"processes":{"quit":1}
,"quit":{"exiting":1}
,"logs)":{"seemingly":1}
,"seemingly":{"visible":1}
,"visible":{"reason":1}
,"terminal":{"session":1}
,"session":{"terminated":1}
,"terminated":{"parent":1}
,"parent":{"process":1}
,"maintained":{"life":1}
,"life":{"node":1}
,"node":{"process":1}
,"workaround":{"nohup":1}
,"nohup":{"option":1}
,"option":{"setup":1}
,"setup":{"active":1}
,"instance":{"number":1,"failing":1,"shared":1,"lost":1,"cluster":1}
,"number":{"standbys":1}
,"standbys":{"getting":1}
,"getting":{"errors":1}
,"errors":{"active":1,"warnings":1,"occur":1}
,"due":{"network":1}
,"latency":{"load":1}
,"instances":{"may":1,"every":1,"suffer":1}
,"adequate":{"time":1}
,"hold":{"election":1}
,"election":{"increase":1}
,"increase":{"<election-time>":1}
,"<election-time>":{"property":1}
,"property":{"terracotta":1}
,"configuration":{"file":1}
,"file":{"lowest":1}
,"lowest":{"value":1}
,"value":{"solves":1}
,"solves":{"issue":1}
,"issue":{"running":1,"hotspot":1}
,"ubuntu":{"note":1}
,"note":{"end":1}
,"end":{"unknownhostexception":1}
,"unknownhostexception":{"topic":1}
,"topic":{"section":1}
,"section":{"specific":1}
,"stripe":{"(more":1,"contain":1}
,"(more":{"active":1}
,"server)":{"data":1}
,"distributed":{"unevenly":1}
,"unevenly":{"two":1}
,"two":{"stripes":1}
,"stripes":{"terracotta":1}
,"array":{"distributes":1}
,"distributes":{"data":1}
,"based":{"hashcode":1}
,"hashcode":{"keys":1}
,"keys":{"enhance":1,"hashed":1,"type":1}
,"enhance":{"performance":1}
,"performance":{"server":1,"degradation":1}
,"contain":{"approximately":1}
,"approximately":{"amount":1}
,"amount":{"data":1}
,"grossly":{"uneven":1}
,"uneven":{"distribution":1}
,"distribution":{"data":1,"crashed":1}
,"servers":{"cluster":1,"configured":1}
,"hashed":{"application":1}
,"creating":{"keys":1}
,"type":{"hash":1}
,"hash":{"may":1}
,"crashed":{"terracotta":1,"server\u0027s":1}
,"failing":{"restart":1}
,"shared":{"data":1}
,"intact":{"however":1}
,"however":{"server\u0027s":1}
,"server\u0027s":{"database":1,"data":1}
,"database":{"somehow":1}
,"somehow":{"become":1}
,"become":{"corrupt":1}
,"corrupt":{"clear":1}
,"directory":{"restarting":1}
,"restarting":{"lost":1}
,"lost":{"data":1,"power":1,"terracotta":1,"turning":1}
,"entire":{"cluster":1}
,"power":{"went":1,"cluster":1,"interrupted":1,"supplies":1}
,"went":{"down":1}
,"persists":{"failure":1}
,"failure":{"data":1}
,"configured":{"persist":1}
,"losing":{"small":1}
,"small":{"amount":1}
,"write":{"caching":1}
,"caching":{"machines":1,"optimal":1}
,"machines":{"running":1,"crash":1}
,"every":{"terracotta":1}
,"remaining":{"disk":1}
,"cache":{"machine":1}
,"machine":{"lost":1}
,"turning":{"disk":1}
,"optimal":{"solution":1}
,"solution":{"machines":1,"ensure":1}
,"suffer":{"substantial":1}
,"degradation":{"better":1}
,"better":{"solution":1}
,"achieved":{"techniques":1}
,"techniques":{"using":1}
,"using":{"uninterruptible":1}
,"uninterruptible":{"power":1}
,"supplies":{"geographically":1}
,"geographically":{"subdividing":1}
,"subdividing":{"cluster":1}
,"members":{"restart":1}
,"redeploying":{"container":1}
,"container":{"errors":1}
,"occur":{"client":1,"hotspot":1}
,"web":{"application":1}
,"redeployed":{"causing":1,"sure":1}
,"causing":{"client":1}
,"start":{"properly":1}
,"properly":{"web":1}
,"sure":{"restart":1}
,"jvm":{"sparc":1}
,"sparc":{"machines":1,"problem":1}
,"crash":{"regularly":1}
,"encountering":{"known":1}
,"known":{"issue":1}
,"hotspot":{"jvm":1,"1.6.0_08":1}
,"problem":{"expected":1}
,"expected":{"occur":1}
,"1.6.0_08":{"higher":1}
,"higher":{"may":1}
,"fixed":{"later":1}
,"later":{"version":1}
,"version":{"information":1}
,"bug":{"report":1}
}
;Search.control.loadWordPairs(pairs);
