var pairs =
{
"safe":{"cluster":1}
,"cluster":{"shutdown":1,"first":1}
,"shutdown":{"procedure":1,"follow":1}
,"procedure":{"safe":1}
,"follow":{"steps":1}
,"steps":{"shut":1}
,"shut":{"down":1}
,"down":{"standby":1,"clients":1,"shut":1,"application":1,"active":1}
,"standby":{"servers":1}
,"servers":{"using":1,"started":1}
,"using":{"stop-tc-server":1}
,"stop-tc-server":{"script":1}
,"script":{"shut":1,"restart":1}
,"clients":{"terracotta":1}
,"terracotta":{"client":1}
,"client":{"shut":1}
,"application":{"shut":1}
,"active":{"server":1,"clustered":1}
,"server":{"using":1,"last":1}
,"restart":{"cluster":1}
,"first":{"start":1,"data":1}
,"start":{"server":1}
,"last":{"active":1}
,"clustered":{"data":1}
,"data":{"persisted":1,"conflicts":1}
,"persisted":{"servers":1}
,"started":{"first":1}
,"conflicts":{"place":1}
}
;Search.control.loadWordPairs(pairs);
