var pairs =
{
"configuring":{"bigmemory":1,"dynamic":1,"fast":1}
,"bigmemory":{"max":1,"hybrid":1,"distributed":1,"search":1,"data":1,"sql":1}
,"max":{"general":1,"configuring":1,"bigmemory":1,"configuration":1,"administrator":1,"data":1,"tier":1,"full":1,"developer":1,"transactional":1,"uses":1}
,"general":{"overview":1}
,"overview":{"configuring":1}
,"configuration":{"guide":1,"topics":1,"parameters":1,"sizing":1,"bigmemory":1,"large":1}
,"guide":{"specific":1,"dynamically":1,"pinning":1,"fast":1,"hybrid":1,"search":1,"transactional":1,"explicit":1,"logging":1,"scale":1,"learn":1}
,"specific":{"configuration":1}
,"topics":{"introduced":1,"bigmemory":1}
,"introduced":{"below":1}
,"below":{"automatic":1}
,"automatic":{"resource":1,"balancing":1}
,"resource":{"control":1,"management":1}
,"control":{"automatic":1,"(arc)":1}
,"(arc)":{"gives":1}
,"gives":{"fine-grained":1}
,"fine-grained":{"controls":1}
,"controls":{"tuning":1}
,"tuning":{"performance":1,"often":1,"cache":1}
,"performance":{"enabling":1}
,"enabling":{"trade-offs":1}
,"trade-offs":{"throughput":1}
,"throughput":{"latency":1}
,"latency":{"data":1}
,"data":{"access":1,"effective":1,"tiers":1,"important":1,"store":1,"bigmemory":1,"managing":1,"life":1,"planned":1,"local":1,"persistence":1,"(both":1,"storage":1,"stored":1,"indexed":1,"looked":1,"using":1,"stores":1,"sync":1}
,"access":{"independently":1,"in-memory":1,"point":1}
,"independently":{"adjustable":1}
,"adjustable":{"configuration":1}
,"parameters":{"include":1}
,"include":{"differentiated":1}
,"differentiated":{"tier-based":1}
,"tier-based":{"sizing":1}
,"sizing":{"pinning":1,"stores":1,"attributes":1,"tiers":1,"storage":1}
,"pinning":{"hot":1,"data":1,"expiration":1}
,"hot":{"eternal":1}
,"eternal":{"data":1}
,"effective":{"tier":1}
,"tier":{"details":1,"information":1,"in-memory":1}
,"details":{"automatic":1}
,"management":{"bigmemory":1,"console":1,"systems":1}
,"administrator":{"guide":1}
,"dynamically":{"sizing":1}
,"stores":{"tuning":1,"appropriately":1,"keeping":1}
,"often":{"involves":1}
,"involves":{"sizing":1,"managing":1}
,"appropriately":{"number":1}
,"number":{"ways":1}
,"ways":{"size":1}
,"size":{"different":1}
,"different":{"bigmemory":1}
,"tiers":{"using":1,"configuring":1,"bigmemory":1}
,"using":{"simple":1,"local":1,"bigmemory":1,"either":1,"tmc":1}
,"simple":{"configuration":1,"sql":1}
,"attributes":{"information":1}
,"information":{"sizing":1,"pinning":1,"data":1,"using":1,"searching":1,"configuring":1,"slf4j":1}
,"dynamic":{"allocation":1}
,"allocation":{"memory":1}
,"memory":{"automatic":1}
,"balancing":{"sizing":1}
,"storage":{"tiers":1,"tier":1,"bigmemory":1}
,"important":{"aspects":1}
,"aspects":{"running":1}
,"running":{"in-memory":1}
,"in-memory":{"data":1}
,"store":{"involves":1,"fully":1}
,"managing":{"life":1,"data":1}
,"life":{"data":1,"bigmemory":1}
,"expiration":{"eviction":1}
,"eviction":{"data":1}
,"fast":{"restartability":1,"restart":1}
,"restartability":{"bigmemory":1,"using":1}
,"full":{"fault":1}
,"fault":{"tolerance":1}
,"tolerance":{"allowing":1}
,"allowing":{"continuous":1}
,"continuous":{"access":1}
,"planned":{"unplanned":1}
,"unplanned":{"shutdown":1}
,"shutdown":{"option":1}
,"option":{"store":1}
,"fully":{"consistent":1}
,"consistent":{"record":1}
,"record":{"in-memory":1}
,"local":{"disk":1,"transactions":1}
,"disk":{"times":1,"storage":1}
,"times":{"information":1}
,"persistence":{"fast":1}
,"(both":{"heap":1}
,"heap":{"off-heap":1}
,"off-heap":{"stores)":1}
,"stores)":{"configuring":1}
,"restart":{"bigmemory":1}
,"hybrid":{"data":1,"extends":1,"mixture":1,"bigmemory":1}
,"extends":{"bigmemory":1}
,"distributed":{"terracotta":1,"configuration":1}
,"terracotta":{"server":1,"management":1}
,"server":{"array":1}
,"array":{"data":1}
,"stored":{"across":1}
,"across":{"hybrid":1}
,"mixture":{"ram":1}
,"ram":{"ssd\u002Fflash":1}
,"ssd\u002Fflash":{"additional":1}
,"additional":{"information":1}
,"search":{"search":1,"billions":1,"provides":1,"api":1}
,"billions":{"entries-gigabytes":1}
,"entries-gigabytes":{"even":1}
,"even":{"terabytes":1}
,"terabytes":{"data-with":1}
,"data-with":{"results":1}
,"results":{"returned":1,"sets":1}
,"returned":{"less":1}
,"less":{"second":1}
,"second":{"data":1}
,"indexed":{"without":1}
,"without":{"significant":1}
,"significant":{"overhead":1}
,"overhead":{"features":1}
,"features":{"groupby":1}
,"groupby":{"direct":1}
,"direct":{"support":1}
,"support":{"handling":1,"explicit":1}
,"handling":{"null":1,"huge":1}
,"null":{"values":1}
,"values":{"optimization":1}
,"optimization":{"around":1}
,"around":{"handling":1}
,"huge":{"results":1}
,"sets":{"included":1}
,"included":{"bigmemory":1}
,"provides":{"ability":1}
,"ability":{"data":1}
,"looked":{"based":1}
,"based":{"multiple":1}
,"multiple":{"criteria":1}
,"criteria":{"instead":1}
,"instead":{"just":1}
,"just":{"keys":1}
,"keys":{"query":1}
,"query":{"bigmemory":1}
,"either":{"simple":1}
,"sql":{"statements":1,"bigmemory":1}
,"statements":{"search":1}
,"api":{"information":1}
,"searching":{"cache":1,"bigmemory":1}
,"cache":{"searching":1,"usage":1}
,"developer":{"guide":1}
,"transactional":{"caching":1,"modes":1,"support":1}
,"caching":{"transactional":1}
,"modes":{"powerful":1,"transactional":1}
,"powerful":{"extension":1}
,"extension":{"performing":1}
,"performing":{"atomic":1}
,"atomic":{"operations":1}
,"operations":{"data":1}
,"keeping":{"data":1}
,"sync":{"database":1}
,"database":{"information":1}
,"explicit":{"locking":1}
,"locking":{"topics":1,"custom":1}
,"custom":{"alternative":1}
,"alternative":{"transactions":1}
,"transactions":{"local":1,"administration":1}
,"administration":{"monitoring":1,"application":1}
,"monitoring":{"terracotta":1,"administration":1}
,"console":{"(tmc)":1,"user\u0027s":1}
,"(tmc)":{"web-based":1}
,"web-based":{"monitoring":1}
,"application":{"tuning":1}
,"usage":{"detecting":1}
,"detecting":{"errors":1}
,"errors":{"providing":1}
,"providing":{"easy-to-use":1}
,"easy-to-use":{"access":1}
,"point":{"integrate":1}
,"integrate":{"production":1}
,"production":{"management":1}
,"systems":{"information":1}
,"tmc":{"terracotta":1}
,"user\u0027s":{"guide":1}
,"logging":{"bigmemory":1,"framework":1}
,"uses":{"flexible":1}
,"flexible":{"slf4j":1}
,"slf4j":{"logging":1}
,"framework":{"information":1}
,"scale":{"scale":1,"defining":1}
,"defining":{"distributed":1}
,"learn":{"configuration":1,"potential":1}
,"large":{"amounts":1}
,"amounts":{"in-memory":1}
,"potential":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
