var pairs =
{
"welcome":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"4.3":1}
,"4.3":{"online":1,"management":1}
,"online":{"documentation":1}
,"documentation":{"library":1}
,"library":{"new":1}
,"new":{"bigmemory":1}
,"management":{"monitoring":1,"console":1}
,"monitoring":{"upgraded":1}
,"upgraded":{"support":1}
,"support":{"wan":1,"java":1,"rhel":1}
,"wan":{"replication":1,"tab":1}
,"replication":{"service":1}
,"service":{"refer":1}
,"refer":{"using":1}
,"using":{"wan":1}
,"tab":{"terracotta":1}
,"terracotta":{"management":1}
,"console":{"user":1}
,"user":{"guide":1}
,"guide":{"platform":1}
,"platform":{"support":1}
,"java":{"platform":1}
,"rhel":{"centos":1}
,"centos":{"detailed":1}
,"detailed":{"information":1}
,"information":{"changed":1,"page":1}
,"changed":{"release":1}
,"release":{"release":1,"notes":1,"information":1}
,"notes":{"release":1}
,"page":{"https:\u002F\u002Fconfluence.terracotta.org\u002Fdisplay\u002Frelease\u002Fhome":1}
}
;Search.control.loadWordPairs(pairs);
