var pairs =
{
"best":{"practices":1,"performance":1}
,"practices":{"configuration":1,"cache":1}
,"configuration":{"considerations":1,"rules":1,"best":1,"guide":1}
,"considerations":{"deployment":1}
,"deployment":{"bigmemory":1,"cyclic":1,"offers":1}
,"bigmemory":{"wan":1,"max":1}
,"wan":{"replication":1,"recommended":1,"application":1,"result":1}
,"replication":{"service":1,"cache":1,"following":1,"configured":1}
,"service":{"run":1}
,"run":{"secure":1}
,"secure":{"trusted":1}
,"trusted":{"network":1}
,"network":{"recommended":1}
,"recommended":{"dedicated":1,"least":1,"avoid":1,"enable":1}
,"dedicated":{"server":1}
,"server":{"region\u0027s":1,"orchestrator\u0027s":1,"need":1}
,"region\u0027s":{"orchestrator":1}
,"orchestrator":{"equipped":1,"process":1,"region":1,"adding":1,"always":1,"information":1,"client\u0027s":1,"mark":1,"failure":1,"disposes":1,"continue":1,"running":1}
,"equipped":{"handle":1}
,"handle":{"cpu-and":1}
,"cpu-and":{"network-heavy":1}
,"network-heavy":{"processes":1}
,"processes":{"hardware":1}
,"hardware":{"recommendation":1,"sizing":1}
,"recommendation":{"similar":1}
,"similar":{"terracotta":1}
,"terracotta":{"server":1}
,"orchestrator\u0027s":{"server":1,"classpath":1}
,"need":{"ram":1}
,"ram":{"storing":1}
,"storing":{"less":1}
,"less":{"data":1}
,"data":{"hardware":1,"element":1}
,"sizing":{"account":1}
,"account":{"data":1,"configuring":1}
,"element":{"count":1,"size":1,"update":1,"state":1,"expiration":1,"recommended":1,"across":1}
,"count":{"element":1,"toward":1}
,"size":{"frequency":1,"settings":1}
,"frequency":{"element":1}
,"update":{"bandwidth":1}
,"bandwidth":{"latency":1}
,"latency":{"across":1}
,"across":{"wan":1,"regions":1}
,"least":{"additional":1,"master":1}
,"additional":{"orchestrator":1}
,"process":{"region":1}
,"region":{"serve":1,"note":1,"contains":1,"writes":1,"avoid":1,"deployment":1,"went":1,"master":1,"non-overlapping":1,"instead":1,"region":1,"bulk-load":1,"used":1}
,"serve":{"failover":1}
,"failover":{"master":1,"replica":1}
,"master":{"orchestrator":1,"caches":1,"cache":1,"perform":1,"control":1,"information":1}
,"note":{"region":1}
,"contains":{"replica":1}
,"replica":{"orchestrator":1,"caches":1,"regions":1,"gets":1}
,"adding":{"standby":1}
,"standby":{"replica":1}
,"always":{"beneficial":1}
,"beneficial":{"cause":1}
,"cause":{"slowness":1}
,"slowness":{"master":1}
,"caches":{"during":1,"located":1,"region":1,"per":1,"writes":1,"keys":1,"function":1,"non-ehcache":1,"unclustered":1,"tsas":1,"means":1,"overridden":1,"may":1}
,"during":{"failover":1}
,"information":{"section":1,"automatic":1,"configuring":1}
,"section":{"automatic":1,"general":1}
,"automatic":{"recovery":1,"resource":1}
,"recovery":{"scenarios":1,"recommended":1}
,"scenarios":{"master":1}
,"located":{"region":1}
,"writes":{"occur":1,"replicas":1,"elements":1}
,"occur":{"give":1,"simultaneously":1}
,"give":{"lowest":1}
,"lowest":{"number":1}
,"number":{"conflicts":1}
,"conflicts":{"highest":1,"cache":1}
,"highest":{"possible":1}
,"possible":{"performance":1,"locate":1,"tell":1,"cache":1,"caches":1}
,"performance":{"possible":1,"consistency":1,"removing":1}
,"locate":{"master":1}
,"avoid":{"deployments":1,"using":1,"repeated":1,"calling":1}
,"deployments":{"terminal":1}
,"terminal":{"region":1}
,"cyclic":{"dependency":1}
,"dependency":{"masters":1}
,"masters":{"replicas":1}
,"replicas":{"result":1,"effectively":1}
,"result":{"least":1,"constant":1}
,"cache":{"going":1,"keys":1,"mutability":1,"events":1,"operation":1,"configurations":1,"element":1,"orchestrators":1,"expiries":1,"size":1,"configuration":1,"different":1,"even":1,"orchestrator":1}
,"going":{"down":1}
,"down":{"given":1,"lead":1}
,"given":{"region":1}
,"went":{"down":1}
,"lead":{"longer":1}
,"longer":{"delays":1}
,"delays":{"recovering":1}
,"recovering":{"deployment":1}
,"offers":{"best":1}
,"consistency":{"distinct":1}
,"distinct":{"caches":1,"sets":1}
,"per":{"region":1}
,"effectively":{"read-only":1}
,"read-only":{"read\u002Fwrite-rarely":1}
,"read\u002Fwrite-rarely":{"distinct":1}
,"sets":{"cache":1}
,"keys":{"region":1,"regions":1,"means":1,"updated":1}
,"non-overlapping":{"sets":1}
,"regions":{"avoids":1,"count":1,"cache":1,"settings":1}
,"avoids":{"conflicts":1}
,"mutability":{"isolated":1}
,"isolated":{"example":1}
,"example":{"configure":1}
,"configure":{"counter":1}
,"counter":{"region":1,"non-simultaneous":1}
,"instead":{"using":1}
,"using":{"global":1,"custom":1,"tti-based":1}
,"global":{"counter":1}
,"non-simultaneous":{"updates":1}
,"updates":{"shared":1,"even":1}
,"shared":{"caches":1}
,"means":{"keys":1,"time":1}
,"updated":{"across":1}
,"application":{"ensures":1,"region":1}
,"ensures":{"don\u0027t":1}
,"don\u0027t":{"occur":1}
,"simultaneously":{"configuration":1}
,"rules":{"limitations":1}
,"limitations":{"following":1}
,"following":{"taken":1,"cache":1}
,"taken":{"account":1}
,"configuring":{"components":1,"nonstop":1,"fast":1}
,"components":{"wan":1}
,"events":{"replicated":1}
,"replicated":{"resulting":1,"write-behind":1,"explicitly":1,"possible":1}
,"resulting":{"element":1}
,"state":{"cache":1,"replicated":1}
,"operation":{"replicated":1,"bigmemory":1}
,"write-behind":{"queues":1}
,"queues":{"replicated":1}
,"explicitly":{"locked":1}
,"locked":{"caches":1}
,"function":{"lock":1}
,"lock":{"enforced":1}
,"enforced":{"locally":1}
,"locally":{"bulk-load":1}
,"bulk-load":{"state":1,"mode":1}
,"tell":{"region":1}
,"mode":{"bulk":1}
,"bulk":{"loading":1}
,"loading":{"otherwise":1}
,"otherwise":{"work":1,"info":1}
,"work":{"normal":1}
,"normal":{"using":1}
,"custom":{"value":1}
,"value":{"classes":1}
,"classes":{"jdk":1,"included":1}
,"jdk":{"types":1}
,"types":{"classes":1}
,"included":{"orchestrator\u0027s":1}
,"classpath":{"refer":1}
,"refer":{"step":1}
,"step":{"section":1}
,"general":{"steps":1}
,"steps":{"setting":1}
,"setting":{"wan":1}
,"configurations":{"supported":1,"symmetrical":1}
,"supported":{"transactional":1}
,"transactional":{"caches":1}
,"non-ehcache":{"caches":1}
,"unclustered":{"(standalone)":1}
,"(standalone)":{"caches":1}
,"tsas":{"different":1}
,"different":{"segment":1,"regions":1}
,"segment":{"counts":1}
,"counts":{"cache":1}
,"expiration":{"performed":1,"wan":1}
,"performed":{"master":1}
,"orchestrators":{"enforce":1}
,"enforce":{"master":1}
,"expiries":{"replica":1}
,"time":{"idle":1,"updates":1}
,"idle":{"(tti)":1,"countdown":1}
,"(tti)":{"settings":1}
,"settings":{"may":1,"replica":1,"impact":1,"include":1}
,"may":{"achieve":1,"cleared":1}
,"achieve":{"expected":1}
,"expected":{"results":1}
,"results":{"master":1}
,"perform":{"last":1}
,"last":{"accessed":1}
,"accessed":{"time":1}
,"even":{"gets":1,"clients":1}
,"gets":{"replica":1,"disconnected":1}
,"toward":{"resetting":1}
,"resetting":{"idle":1}
,"countdown":{"element":1}
,"tti-based":{"expiration":1}
,"configured":{"cache":1}
,"overridden":{"master":1}
,"control":{"cache":1}
,"symmetrical":{"possible":1}
,"impact":{"eviction":1}
,"eviction":{"element":1}
,"include":{"time-to-live":1}
,"time-to-live":{"option":1}
,"option":{"maxentriesincache":1}
,"maxentriesincache":{"attribute":1}
,"attribute":{"(configured":1}
,"(configured":{"ehcache.xml":1,"tc-config.xml":1}
,"ehcache.xml":{"file)":1}
,"file)":{"datastorage":1,"information":1}
,"datastorage":{"offheap":1}
,"offheap":{"elements":1}
,"elements":{"(configured":1,"wan":1,"avoided":1}
,"tc-config.xml":{"file)":1}
,"resource":{"management":1}
,"management":{"bigmemory":1}
,"max":{"administrator":1,"configuration":1}
,"administrator":{"guide":1}
,"guide":{"added":1}
,"added":{"reference":1}
,"reference":{"order":1,"avoid":1}
,"order":{"exceptions":1}
,"exceptions":{"client":1}
,"client":{"fails":1}
,"fails":{"connect":1}
,"connect":{"orchestrator":1}
,"client\u0027s":{"nonstop":1}
,"nonstop":{"timeoutbehavior":1,"operation":1}
,"timeoutbehavior":{"type":1}
,"type":{"exception":1}
,"exception":{"otherwise":1}
,"info":{"message":1}
,"message":{"waiting":1}
,"waiting":{"orchestrator":1}
,"mark":{"active":1}
,"active":{"event":1}
,"event":{"orchestrator":1}
,"failure":{"replica":1}
,"disconnected":{"master":1}
,"repeated":{"sustained":1}
,"sustained":{"conflicting":1}
,"conflicting":{"writes":1}
,"constant":{"conflict":1}
,"conflict":{"resolution":1}
,"resolution":{"lower":1}
,"lower":{"performance":1}
,"removing":{"elements":1}
,"avoided":{"possible":1}
,"cleared":{"orchestrator":1}
,"disposes":{"cache":1}
,"clients":{"dispose":1}
,"dispose":{"cache":1}
,"continue":{"hold":1}
,"hold":{"cannot":1}
,"cannot":{"destroyed":1}
,"destroyed":{"orchestrator":1}
,"running":{"recommended":1}
,"calling":{"cache.clear":1}
,"cache.clear":{"application":1}
,"used":{"disaster":1}
,"disaster":{"recovery":1}
,"enable":{"fast":1}
,"fast":{"restart":1}
,"restart":{"feature":1,"bigmemory":1}
,"feature":{"information":1}
}
;Search.control.loadWordPairs(pairs);
