var pairs =
{
"bigmemory":{"max":1}
,"max":{"<<needs":1,"supports":1,"combines":1,"enables":1,"general-purpose":1}
,"<<needs":{"fix-this":1}
,"fix-this":{"entire":1}
,"entire":{"topic":1}
,"topic":{"needs":1}
,"needs":{"reviewed":1}
,"reviewed":{"foram>>":1}
,"foram>>":{"bigmemory":1}
,"supports":{"distributed":1}
,"distributed":{"in-memory":1}
,"in-memory":{"data-storage":1,"data":1}
,"data-storage":{"topology":1}
,"topology":{"enables":1}
,"enables":{"sharing":1,"linearly":1,"query":1}
,"sharing":{"data":1}
,"data":{"among":1,"stores":1,"shared":1,"storage":1,"remains":1,"access":1,"store":1}
,"among":{"multiple":1}
,"multiple":{"caches":1,"jvms":1,"application":1}
,"caches":{"in-memory":1}
,"stores":{"multiple":1,"using":1}
,"jvms":{"uses":1}
,"uses":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"array":1}
,"array":{"manage":1,"ease":1}
,"manage":{"data":1}
,"shared":{"multiple":1}
,"application":{"nodes":1,"grow":1,"performance":1}
,"nodes":{"cluster":1}
,"cluster":{"bigmemory":1,"offload":1}
,"combines":{"power":1}
,"power":{"terracotta":1}
,"ease":{"ehcache":1}
,"ehcache":{"caching":1,"bigmemory":1}
,"caching":{"in-memory":1}
,"storage":{"enables":1}
,"linearly":{"scale":1}
,"scale":{"application":1}
,"grow":{"requirements":1}
,"requirements":{"rely":1}
,"rely":{"data":1}
,"remains":{"consistent":1}
,"consistent":{"across":1}
,"across":{"cluster":1}
,"offload":{"databases":1}
,"databases":{"reduce":1}
,"reduce":{"associated":1}
,"associated":{"overhead":1}
,"overhead":{"increase":1}
,"increase":{"application":1}
,"performance":{"distributed":1}
,"access":{"even":1}
,"even":{"powerful":1}
,"powerful":{"apis":1}
,"apis":{"leverage":1}
,"leverage":{"capabilities":1}
,"capabilities":{"bigmemory":1}
,"query":{"caches":1}
,"using":{"sql":1}
,"sql":{"ehcache":1}
,"general-purpose":{"cache\u002Fin-memory":1}
,"cache\u002Fin-memory":{"data":1}
,"store":{"second-level":1}
,"second-level":{"cache":1}
,"cache":{"hibernate":1}
,"hibernate":{"additionally":1}
,"additionally":{"integrate":1}
,"integrate":{"third-party":1}
,"third-party":{"products":1}
,"products":{"coldfusion":1}
,"coldfusion":{"google":1}
,"google":{"app":1}
,"app":{"engine":1}
,"engine":{"spring":1}
}
;Search.control.loadWordPairs(pairs);
