var pairs =
{
"response":{"headers":1,"header":1}
,"headers":{"typical":1}
,"typical":{"http":1}
,"http":{"request":1}
,"request":{"response":1}
,"header":{"similar":1}
,"similar":{"following":1}
,"following":{"--response":1}
,"--response":{"--200":1}
,"--200":{"content-type":1}
,"content-type":{"application\u002Fvnd.sun.wadl":1}
,"application\u002Fvnd.sun.wadl":{"xml":1}
,"xml":{"allow":1}
,"allow":{"options":1}
,"options":{"head":1}
,"head":{"content-length":1}
,"content-length":{"602":1}
,"602":{"server":1}
,"server":{"jetty":1}
,"jetty":{"(7.5.4.v20111024)":1}
}
;Search.control.loadWordPairs(pairs);
