var pairs =
{
"terracottaconfig":{"<terracottaconfig>":1}
,"<terracottaconfig>":{"element":1,"<tc-config>":1}
,"element":{"enables":1,"allows":1,"follows":1,"add":1}
,"enables":{"distributed-cache":1}
,"distributed-cache":{"client":1}
,"client":{"identify":1,"rejoin":1,"load":1,"information":1,"configuration":1}
,"identify":{"source":1}
,"source":{"terracotta":1,"changes":1}
,"terracotta":{"configuration":1,"server":1,"cluster":1,"host":1}
,"configuration":{"allows":1,"file":1,"terracotta":1,"parameters":1,"source":1,"adding":1,"embed":1}
,"allows":{"client":1,"enable":1}
,"rejoin":{"cluster":1,"feature":1}
,"cluster":{"disconnecting":1,"timed":1,"application":1,"specify":1}
,"disconnecting":{"cluster":1}
,"timed":{"terracotta":1}
,"server":{"information":1,"value":1,"terracotta":1,"known":1,"addresses":1}
,"information":{"rejoin":1,"client":1,"wan":1}
,"feature":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"high-availability":1,"administrator":1}
,"high-availability":{"guide":1}
,"guide":{"addition":1,"adding":1,"embedding":1}
,"addition":{"<terracottaconfig>":1}
,"enable":{"caches":1}
,"caches":{"wan":1}
,"wan":{"replication":1,"attribute":1}
,"replication":{"client":1,"user":1}
,"load":{"configuration":1}
,"file":{"terracotta":1,"system":1,"include":1,"ehcache.xml":1}
,"value":{"url":1}
,"url":{"attribute":1,"(for":1}
,"attribute":{"contain":1,"add":1,"<terracottaconfig>":1,"cache":1,"true":1}
,"contain":{"path":1}
,"path":{"file":1,"(for":1}
,"system":{"property":1}
,"property":{"address":1,"(for":1,"defined":1}
,"address":{"tsa":1,"form":1}
,"tsa":{"port":1}
,"port":{"(9510":1,"9510":1}
,"(9510":{"default)":1}
,"default)":{"server":1}
,"application":{"server":1}
,"known":{"client":1}
,"parameters":{"bigmemory":1}
,"administrator":{"guide":1}
,"adding":{"url":1,"wan":1}
,"add":{"url":1,"wanenabledtsa":1}
,"follows":{"<terracottaconfig":1,"<terracottaconfig>":1}
,"<terracottaconfig":{"url=\u0022":1,"wanenabledtsa=\u0022":1}
,"url=\u0022":{"<source>":1,"http:\u002F\u002Fwww.mydomain.com\u002Fpath\u002Fto\u002Ftc-config.xml)":1,"host1:9510":1}
,"<source>":{"<source>":1,"following":1}
,"following":{"path":1,"using":1}
,"(for":{"example":1}
,"example":{"url=\u0022\u002Fpath\u002Fto\u002Ftc-config.xml":1,"url=\u0022":1,"url=\u0022${terracotta.config.location}":1}
,"url=\u0022\u002Fpath\u002Fto\u002Ftc-config.xml":{"url":1}
,"http:\u002F\u002Fwww.mydomain.com\u002Fpath\u002Fto\u002Ftc-config.xml)":{"system":1}
,"url=\u0022${terracotta.config.location}":{"system":1}
,"defined":{"system.setproperty":1}
,"system.setproperty":{"terracotta.config.location":1}
,"terracotta.config.location":{"10.x.x.x:9510":1}
,"10.x.x.x:9510":{"terracotta":1}
,"host":{"address":1}
,"form":{"<host>":1}
,"<host>":{"<tsa-port>":1}
,"<tsa-port>":{"(for":1,"default":1}
,"host1:9510":{"note":1,"host2:9510":1}
,"note":{"following":1}
,"using":{"server":1}
,"addresses":{"form":1}
,"default":{"tsa":1}
,"9510":{"multi-server":1}
,"multi-server":{"cluster":1}
,"specify":{"comma-delimited":1}
,"comma-delimited":{"list":1}
,"list":{"(for":1}
,"host2:9510":{"host3:9510":1}
,"host3:9510":{"terracotta":1}
,"changes":{"later":1}
,"later":{"time":1}
,"time":{"updated":1}
,"updated":{"configuration":1}
,"cache":{"replicated":1}
,"replicated":{"ehcache.xml":1}
,"ehcache.xml":{"configuration":1,"follows":1}
,"include":{"wanenabledtsa":1}
,"wanenabledtsa":{"attribute":1}
,"true":{"within":1,"\u0022\u002F>":1}
,"within":{"<terracottaconfig>":1}
,"wanenabledtsa=\u0022":{"true":1}
,"\u0022\u002F>":{"information":1,"<server":1,"<\u002Fservers>":1}
,"user":{"guide":1}
,"embedding":{"terracotta":1}
,"embed":{"contents":1}
,"contents":{"terracotta":1}
,"<tc-config>":{"<servers>":1}
,"<servers>":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"server1":1,"server2":1}
,"server1":{"name=\u0022":1}
,"name=\u0022":{"\u0022\u002F>":1}
,"server2":{"name=\u0022":1}
,"<\u002Fservers>":{"<clients>":1}
,"<clients>":{"<logs>":1}
,"<logs>":{"app\u002Flogs-%":1}
,"app\u002Flogs-%":{"<\u002Flogs>":1}
,"<\u002Flogs>":{"<\u002Fclients>":1}
,"<\u002Fclients>":{"<\u002Ftc-config>":1}
,"<\u002Ftc-config>":{"<\u002Fterracottaconfig>":1}
}
;Search.control.loadWordPairs(pairs);
