var pairs =
{
"securing":{"tsa":1}
,"tsa":{"access":1,"feature":1,"malicious":1,"term":1,"client":1,"maintain":1,"features":1,"cross-stripe":1}
,"access":{"using":1,"tsa":1,"cluster":1}
,"using":{"permitted":1}
,"permitted":{"list":1}
,"list":{"white-listing":1,"ips":1}
,"white-listing":{"feature":1,"need":1,"enabled":1,"cannot":1,"server":1,"enabled\u002Fdisabled":1,"disabled":1}
,"feature":{"enables":1,"example":1,"(on":1,"want":1,"used":1}
,"enables":{"cluster":1}
,"cluster":{"administrator":1,"switch":1,"need":1,"caching":1,"every":1,"instead":1,"long":1}
,"administrator":{"ensure":1,"sure":1}
,"ensure":{"clients":1,"changes":1}
,"clients":{"certain":1,"attempting":1,"refers":1,"jmx":1,"http":1,"so-called":1,"running":1,"need":1,"192.168.5.28":1,"192.168.10.0\u002F24":1,"client":1,"non-white-listed":1,"send":1}
,"certain":{"explicitly":1}
,"explicitly":{"named":1}
,"named":{"addresses":1}
,"addresses":{"access":1,"host-level":1,"ipv4":1,"entry":1}
,"example":{"secure":1,"white-list.txt":1}
,"secure":{"tsa":1}
,"malicious":{"clients":1}
,"attempting":{"connect":1}
,"connect":{"tsa":1}
,"term":{"clients":1}
,"refers":{"caching":1}
,"caching":{"clients":1}
,"jmx":{"clients":1}
,"http":{"clients":1,"requests":1}
,"so-called":{"white-list":1}
,"white-list":{"list":1,"allowed":1,"known":1,"file":1,"cluster":1,"entries":1,"reading":1,"partial":1,"dynamic":1}
,"ips":{"clients":1,"allowed":1,"plain":1,"understood":1,"specified":1,"server":1,"resolution":1,"configured":1,"always":1}
,"running":{"ips":1,"however":1,"add":1,"order":1,"multi-stripe":1,"update-white-list":1}
,"allowed":{"access":1}
,"client":{"whose":1,"ips":1,"behaviors":1,"connects":1,"white-listed":1,"eof":1,"remain":1,"server":1,"rejected":1}
,"whose":{"white-list":1}
,"maintain":{"white-list":1}
,"known":{"client":1}
,"plain":{"text":1}
,"text":{"file":1}
,"file":{"cidr":1,"server":1,"updates":1,"need":1,"responsibility":1,"<file>":1,"white-listing":1,"file":1,"found":1,"present":1,"similarly":1,"white-list":1,"simple":1,"choose":1,"example":1,"contain":1,"kept":1,"processed":1,"execute":1,"path":1,"updated":1,"tc-config":1,"involves":1,"hostnames":1}
,"cidr":{"notations":1,"notation":1,"ignored":1}
,"notations":{"used":1}
,"used":{"cover":1,"tc-config":1,"recommended":1}
,"cover":{"range":1}
,"range":{"ips":1}
,"understood":{"usage":1}
,"usage":{"feature":1,"enable":1}
,"(on":{"own)":1}
,"own)":{"provide":1}
,"provide":{"strong":1}
,"strong":{"level":1}
,"level":{"security":1}
,"security":{"tsa":1,"additionally":1}
,"features":{"ssl":1}
,"ssl":{"encryption":1}
,"encryption":{"authentication":1}
,"authentication":{"enabled":1}
,"enabled":{"true":1,"white-listing":1,"entries":1,"caching":1}
,"true":{"security":1}
,"additionally":{"ideal":1}
,"ideal":{"enforce":1}
,"enforce":{"connection":1}
,"connection":{"restrictions":1,"verifies":1,"client":1,"established":1}
,"restrictions":{"based":1}
,"based":{"addresses":1,"presence":1}
,"host-level":{"firewalls":1}
,"firewalls":{"rather":1}
,"rather":{"feature":1}
,"want":{"white-listing":1}
,"need":{"enable":1,"access":1,"start":1,"ensure":1,"update":1}
,"enable":{"server":1,"white-listing":1}
,"server":{"startup":1,"started":1,"running":1,"following":1,"log":1,"ips":1,"always":1,"attempt":1,"directory":1,"fails":1,"signal":1,"finished":1,"node":1,"receives":1,"logs":1,"reads":1,"continue":1,"tsa-port":1,"first":1,"client":1}
,"startup":{"once":1,"cannot":1,"fail":1,"continue":1}
,"once":{"server":1}
,"started":{"white-listing":1}
,"cannot":{"turned":1,"switch":1}
,"turned":{"back":1}
,"back":{"server":1}
,"however":{"change":1}
,"change":{"existing":1}
,"existing":{"ip\u002Fcidr":1}
,"ip\u002Fcidr":{"entries":1}
,"entries":{"white-list":1,"instead":1,"raw":1,"supported":1,"dynamically":1,"logged":1}
,"add":{"delete":1}
,"delete":{"entries":1}
,"order":{"modify":1}
,"modify":{"clients":1}
,"switch":{"white-listing":1}
,"multi-stripe":{"cluster":1}
,"start":{"servers":1,"server":1}
,"servers":{"(both":1,"tc-config":1,"cluster":1}
,"(both":{"actives":1}
,"actives":{"passives)":1}
,"passives)":{"copy":1}
,"copy":{"white-list":1}
,"updates":{"white-list":1,"once":1,"effect":1,"took":1,"ignored":1,"applied":1}
,"changes":{"mirrored":1,"white-list":1}
,"mirrored":{"across":1}
,"across":{"stripes":1}
,"stripes":{"note":1}
,"note":{"tsa":1}
,"cross-stripe":{"validation":1}
,"validation":{"contents":1}
,"contents":{"white-list":1}
,"responsibility":{"cluster":1}
,"sure":{"happens":1,"updates":1}
,"happens":{"usage":1,"dynamic":1}
,"following":{"tc-config":1}
,"tc-config":{"property":1,"file":1,"entries":1,"update":1}
,"property":{"ip.white.list=\u0022":1,"entry":1,"complete":1,"specified":1}
,"ip.white.list=\u0022":{"<location>\u002F<file>":1}
,"<location>\u002F<file>":{"<location>":1}
,"<location>":{"path":1}
,"path":{"containing":1,"white-list":1,"argument":1}
,"containing":{"white-list":1}
,"<file>":{"name":1}
,"name":{"white-list":1,"file":1}
,"enabled\u002Fdisabled":{"based":1}
,"presence":{"tc-config":1}
,"entry":{"value":1,"valid":1}
,"value":{"property":1}
,"complete":{"path":1}
,"found":{"specified":1,"server":1}
,"specified":{"location":1,"white-listing":1,"tc-config":1}
,"location":{"server":1}
,"fail":{"appropriate":1,"dynamic":1}
,"appropriate":{"error":1}
,"error":{"message":1,"reading":1}
,"message":{"file":1}
,"present":{"error":1}
,"reading":{"file":1,"white-list":1,"tc-config":1}
,"continue":{"white-listing":1,"current":1}
,"disabled":{"failure":1,"server":1,"white-listing":1}
,"failure":{"logged":1,"happens":1}
,"logged":{"server":1}
,"log":{"property":1,"statements":1,"already":1,"thus":1}
,"always":{"white-listed":1}
,"white-listed":{"hostnames":1,"white-list":1,"closes":1,"case":1,"initially":1}
,"hostnames":{"used":1,"ips":1,"involves":1}
,"instead":{"ips":1,"client":1}
,"attempt":{"resolve":1,"http":1}
,"resolve":{"hostnames":1}
,"resolution":{"fails":1,"cases":1}
,"fails":{"server":1,"create":1}
,"recommended":{"ips":1}
,"configured":{"servers":1}
,"similarly":{"localhost":1}
,"localhost":{"ips":1}
,"simple":{"text":1}
,"choose":{"name":1}
,"white-list.txt":{"entries":1}
,"raw":{"addresses":1}
,"ipv4":{"format":1,"address":1}
,"format":{"cidr":1}
,"notation":{"represent":1}
,"represent":{"ranges":1}
,"ranges":{"ipv6":1}
,"ipv6":{"entries":1}
,"supported":{"line":1}
,"line":{"file":1}
,"contain":{"either":1}
,"either":{"single":1,"until":1}
,"single":{"address":1}
,"address":{"comma-separated":1,"valid":1}
,"comma-separated":{"addresses":1}
,"valid":{"ipv4":1,"cidr":1}
,"ignored":{"lines":1,"server":1}
,"lines":{"starting":1,"skipped":1}
,"starting":{"skipped":1}
,"skipped":{"blank":1,"sample":1}
,"blank":{"lines":1}
,"sample":{"white-list":1}
,"192.168.5.28":{"192.168.5.29":1}
,"192.168.5.29":{"192.168.5.30":1}
,"192.168.5.30":{"10.60.98.0\u002F28":1}
,"10.60.98.0\u002F28":{"clients":1}
,"192.168.10.0\u002F24":{"white-list":1}
,"kept":{"directory":1}
,"directory":{"write":1,"book-keeping":1}
,"write":{"permissions":1}
,"permissions":{"files":1}
,"files":{"created":1,"server":1}
,"created":{"server":1}
,"book-keeping":{"purposes":1}
,"purposes":{"server":1}
,"create":{"files":1}
,"dynamic":{"updates":1,"update":1}
,"dynamically":{"added\u002Fremoved":1}
,"added\u002Fremoved":{"white-list":1}
,"processed":{"server":1}
,"signal":{"server":1,"reloads":1}
,"finished":{"making":1}
,"making":{"changes":1}
,"execute":{"update-white-list.sh":1,"script":1}
,"update-white-list.sh":{"script":1}
,"script":{"packaged":1,"takes":1,"updates":1,"node":1,"server":1,"again":1}
,"packaged":{"kit":1}
,"kit":{"script":1}
,"takes":{"white-list":1}
,"argument":{"run":1}
,"run":{"script":1}
,"effect":{"few":1,"sure":1,"servers":1}
,"few":{"moments":1}
,"moments":{"corresponding":1}
,"corresponding":{"log":1}
,"statements":{"found":1}
,"already":{"mentioned":1}
,"mentioned":{"every":1}
,"every":{"server":1,"update":1,"dynamic":1}
,"node":{"(active":1,"separately":1}
,"(active":{"passive)":1}
,"passive)":{"copy":1}
,"update":{"white-list":1,"signal":1,"operation":1,"server":1,"in-memory":1,"updates":1,"won\u0027t":1,"removed":1}
,"separately":{"run":1}
,"receives":{"update":1}
,"reloads":{"white-list":1}
,"updated":{"white-list":1}
,"thus":{"every":1}
,"operation":{"check":1}
,"check":{"server":1}
,"logs":{"verify":1}
,"verify":{"updates":1}
,"took":{"effect":1}
,"reads":{"contents":1}
,"in-memory":{"white-list":1}
,"involves":{"disk":1,"dns":1}
,"disk":{"reading":1}
,"dns":{"lookup":1}
,"lookup":{"hostname":1}
,"hostname":{"resolution":1}
,"cases":{"failures":1}
,"failures":{"possible":1}
,"possible":{"failure":1}
,"current":{"white-list":1}
,"partial":{"updates":1}
,"applied":{"update":1}
,"won\u0027t":{"retried":1}
,"retried":{"either":1}
,"until":{"user":1}
,"user":{"signals":1}
,"signals":{"running":1}
,"update-white-list":{"script":1}
,"again":{"client":1}
,"behaviors":{"section":1,"white-listing":1}
,"section":{"details":1}
,"details":{"different":1}
,"different":{"client":1}
,"connects":{"server":1}
,"tsa-port":{"server":1}
,"first":{"accepts":1}
,"accepts":{"socket":1}
,"socket":{"connection":1}
,"verifies":{"incoming":1}
,"incoming":{"client":1}
,"closes":{"socket":1}
,"case":{"client":1}
,"eof":{"trying":1}
,"trying":{"read":1}
,"read":{"socket":1}
,"established":{"server":1}
,"initially":{"removed":1}
,"removed":{"white-list":1,"immediately":1}
,"immediately":{"cluster":1}
,"remain":{"connected":1}
,"connected":{"cluster":1}
,"long":{"network":1}
,"network":{"disconnection":1}
,"disconnection":{"client":1}
,"rejected":{"next":1}
,"next":{"reconnect":1}
,"reconnect":{"attempt":1}
,"non-white-listed":{"clients":1}
,"send":{"http":1}
,"requests":{"management":1}
,"management":{"port":1}
,"port":{"403":1}
,"403":{"forbidden":1}
,"forbidden":{"response":1}
}
;Search.control.loadWordPairs(pairs);
