var pairs =
{
"consistency":{"consistency":1,"ehcache.xml":1,"able":1,"hand":1,"terracotta":1,"strong":1,":type":1,"type":1}
,"ehcache.xml":{"configuration":1}
,"configuration":{"file":1}
,"file":{"cache":1}
,"cache":{"connect":1,"clustered":1,"performed":1,"operations":1,"remains":1,"brief":1,"exception":1,"allowed":1}
,"connect":{"clustered":1}
,"clustered":{"connector":1,"using":1}
,"connector":{"cache":1,"execute":1,"method":1}
,"using":{"strong":1,"eventual":1,"either":1}
,"strong":{"consistency":1,"operations":1,"mode":1,"eventual":1,"data":1,"cache":1}
,"able":{"strong":1,"perform":1}
,"operations":{"performed":1,"(for":1,"changes":1,"cache":1,"atomic":1,"accept":1,"value":1,"eventual":1}
,"performed":{"meaning":1,"strong":1,"using":1}
,"meaning":{"changes":1}
,"changes":{"made":1}
,"made":{"node":1}
,"node":{"cluster":1,"visible":1}
,"cluster":{"visible":1,"times":1}
,"visible":{"instantly":1,"nodes":1}
,"instantly":{"atomic":1}
,"atomic":{"operations":1,"ops":1}
,"(for":{"example":1}
,"example":{"putifabsent)":1,"consistency":1}
,"putifabsent)":{"always":1}
,"always":{"performed":1}
,"mode":{"cache":1,"guarantees":1}
,"eventual":{"consistency":1,"operations":1,"expect":1,"reads":1,"cache":1}
,"hand":{"able":1}
,"perform":{"strong":1}
,"nodes":{"eventually":1}
,"eventually":{"understand":1,"consistent":1}
,"understand":{"consistency":1}
,"terracotta":{"clustering":1}
,"clustering":{"level":1}
,"level":{"refer":1}
,"refer":{"bigmemory":1}
,"bigmemory":{"documentation":1}
,"documentation":{"provide":1}
,"provide":{"correct":1}
,"correct":{"external":1}
,"external":{"link":1}
,"link":{"cross-language":1}
,"cross-language":{"api":1}
,"api":{"consistencytype":1}
,"consistencytype":{"attribute":1}
,"attribute":{"sets":1}
,"sets":{"consistency":1}
,"expect":{"connector":1}
,"execute":{"operation":1,"eventually":1}
,"operation":{"example":1,"separate":1,"strong":1,"releasing":1}
,":type":{"type":1}
,"type":{"=consistency":1,"additional":1}
,"=consistency":{":strong":1}
,":strong":{"operations":1}
,"either":{"strong":1}
,"additional":{"parameter":1}
,"parameter":{"few":1,"strong":1}
,"few":{"operations":1}
,"ops":{"removeall":1}
,"removeall":{"queries":1}
,"queries":{"regular":1}
,"regular":{"cache":1}
,"accept":{"last":1}
,"last":{"parameter":1}
,"data":{"cache":1}
,"remains":{"consistent":1}
,"consistent":{"across":1,"operation":1,"operations":1}
,"across":{"cluster":1}
,"times":{"mode":1}
,"guarantees":{"read":1,"put":1}
,"read":{"gets":1}
,"gets":{"updated":1}
,"updated":{"value":1}
,"value":{"write":1,"completed":1}
,"write":{"operations":1}
,"completed":{"guarantees":1}
,"put":{"operation":1}
,"separate":{"transaction":1}
,"transaction":{"eventual":1}
,"reads":{"without":1}
,"without":{"locks":1}
,"locks":{"allowed":1,"used":1}
,"allowed":{"read\u002Fwrite":1,"result":1}
,"read\u002Fwrite":{"performance":1}
,"performance":{"substantially":1}
,"substantially":{"boosted":1}
,"boosted":{"cost":1}
,"cost":{"potentially":1}
,"potentially":{"having":1}
,"having":{"inconsistent":1}
,"inconsistent":{"cache":1}
,"brief":{"periods":1}
,"periods":{"time":1}
,"time":{"try":1}
,"try":{"execute":1}
,"exception":{"executing":1}
,"executing":{"strongly":1}
,"strongly":{"consistent":1}
,"result":{"locks":1}
,"used":{"connector":1}
,"method":{"return":1}
,"return":{"steps":1}
,"steps":{"finished":1}
,"finished":{"(acquiring":1}
,"(acquiring":{"appropriate":1}
,"appropriate":{"lock":1}
,"lock":{"performing":1}
,"performing":{"operation":1}
,"releasing":{"lock)":1}
}
;Search.control.loadWordPairs(pairs);
