var pairs =
{
"terracotta":{"servers":1,"server":1,"configuration":1,"server\u0027s":1,"management":1,"java":1,"kit":1,"instance":1}
,"servers":{"configured":1,"defined":1,"<management-port>":1,"multiple":1,"clients":1,"load":1}
,"configured":{"configure":1}
,"configure":{"terracotta":1,"multiple":1,"fast":1,"persistence":1}
,"server":{"create":1,"name1":1,"store":1,"listen":1,"-->":1,"name2":1,"array":1,"listens":1,"communicate":1,"instances":1,"requires":1,"minimum":1,"data":1,"startup":1,"example":1,"unix\u002Flinux":1}
,"create":{"tc-config.xml":1,"stripe":1}
,"tc-config.xml":{"configuration":1,"exists":1,"used":1}
,"configuration":{"file":1,"parameters":1,"following":1,"included":1,"configuration":1,"values":1}
,"file":{"update":1,"note":1,"<tsa-port>":1,"terracotta":1,"sources":1,"specified":1,"(default)":1,"tc-config.xml":1,"explicitly":1,"passing":1}
,"update":{"provided":1}
,"provided":{"config-samples\u002Fdirectory":1,"terracotta":1,"script":1}
,"config-samples\u002Fdirectory":{"bigmemory":1}
,"bigmemory":{"max":1,"server":1}
,"max":{"kit":1}
,"kit":{"example":1,"local":1}
,"example":{"xml":1,"<server":1,"start":1}
,"xml":{"version=\u0022":1,"file":1}
,"version=\u0022":{"1.0":1}
,"1.0":{"encoding=\u0022":1}
,"encoding=\u0022":{"utf-8":1}
,"utf-8":{"<tc:tc-config":1}
,"<tc:tc-config":{"xmlns:tc=\u0022":1}
,"xmlns:tc=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:schemalocation=\u0022":1}
,"xsi:schemalocation=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":{"<servers>":1}
,"<servers>":{"<server":1,"section":1,"either":1,"work":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"localhost":1}
,"localhost":{"name=\u0022":1}
,"name=\u0022":{"server":1}
,"name1":{"<!--specify":1,"jmx-enabled=\u0022":1}
,"<!--specify":{"path":1,"port":1}
,"path":{"server":1,"microsoft":1}
,"store":{"data":1,"allows":1}
,"data":{"-->":1,"directories":1,"directory":1,"persistence":1,"backed":1,"stored":1,"enable":1}
,"-->":{"<data>\u002Flocal\u002Fdisk\u002Fpath\u002Fto\u002Fterracotta\u002Fserver1-data":1,"<tsa-port>":1,"<datastorage":1,"<hybrid\u002F>":1,"<restartable":1}
,"<data>\u002Flocal\u002Fdisk\u002Fpath\u002Fto\u002Fterracotta\u002Fserver1-data":{"<\u002Fdata>":1}
,"<\u002Fdata>":{"<!--specify":1,"<tsa-port>":1}
,"port":{"server":1,"terracotta":1,"used":1}
,"listen":{"client":1}
,"client":{"traffic":1}
,"traffic":{"-->":1,"<jmx-port>":1}
,"<tsa-port>":{"9510":1,"port":1}
,"9510":{"<\u002Ftsa-port>":1}
,"<\u002Ftsa-port>":{"<jmx-port>":1}
,"<jmx-port>":{"9520":1,"port":1,"deprecated":1,"disabled":1}
,"9520":{"<\u002Fjmx-port>":1}
,"<\u002Fjmx-port>":{"<tsa-group-port>":1}
,"<tsa-group-port>":{"9530":1,"port":1}
,"9530":{"<\u002Ftsa-group-port>":1}
,"<\u002Ftsa-group-port>":{"<management-port>":1}
,"<management-port>":{"9540":1,"port":1}
,"9540":{"<\u002Fmanagement-port>":1}
,"<\u002Fmanagement-port>":{"<!--enable":1,"<datastorage":1}
,"<!--enable":{"bigmemory":1}
,"<datastorage":{"size=\u0022":1}
,"size=\u0022":{"800g":1,"200g":1}
,"800g":{"<offheap":1}
,"<offheap":{"size=\u0022":1}
,"200g":{"\u0022\u002F>":1,"<offheap":1}
,"\u0022\u002F>":{"<!--hybrid":1,"<\u002Fdatastorage>":1,"<\u002Fservers>":1}
,"<!--hybrid":{"storage":1}
,"storage":{"optional":1}
,"optional":{"-->":1,"specify":1}
,"<hybrid\u002F>":{"<\u002Fdatastorage>":1}
,"<\u002Fdatastorage>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<server":1,"<!--add":1}
,"name2":{"<data>\u002Flocal\u002Fdisk\u002Fpath\u002Fto\u002Fterracotta\u002Fserver2-data":1}
,"<data>\u002Flocal\u002Fdisk\u002Fpath\u002Fto\u002Fterracotta\u002Fserver2-data":{"<\u002Fdata>":1}
,"<!--add":{"restartable":1}
,"restartable":{"element":1}
,"element":{"fast":1,"point":1,"two":1}
,"fast":{"restartability":1}
,"restartability":{"(optional)":1,"enabling":1}
,"(optional)":{"-->":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1,"<server>":1,"<tsa-group-port>":1}
,"<\u002Fservers>":{"<clients>":1}
,"<clients>":{"<logs>":1}
,"<logs>":{"logs-%":1}
,"logs-%":{"<\u002Flogs>":1}
,"<\u002Flogs>":{"<\u002Fclients>":1}
,"<\u002Fclients>":{"<\u002Ftc:tc-config>":1}
,"<\u002Ftc:tc-config>":{"successfully":1}
,"successfully":{"configure":1}
,"array":{"using":1}
,"using":{"terracotta":1,"provided":1}
,"note":{"following":1}
,"following":{"two":1,"sources":1}
,"two":{"servers":1,"ways":1}
,"defined":{"<servers>":1}
,"section":{"terracotta":1}
,"listens":{"client":1,"listening":1}
,"server\u0027s":{"jmx":1,"<data>":1}
,"jmx":{"connector":1}
,"connector":{"listens":1}
,"listening":{"<jmx-port>":1}
,"deprecated":{"alternatively":1}
,"alternatively":{"monitoring":1}
,"monitoring":{"features":1}
,"features":{"provided":1}
,"management":{"console":1}
,"console":{"(see":1,"user":1,"(tmc)":1}
,"(see":{"terracotta":1,"wan":1}
,"user":{"guide)":1}
,"guide)":{"wan":1,"<jmx-port>":1}
,"wan":{"replication":1}
,"replication":{"service":1,"user":1}
,"service":{"(see":1}
,"disabled":{"default":1}
,"default":{"want":1,"configuration":1,"located":1}
,"want":{"enable":1}
,"enable":{"add":1,"<hybrid>":1}
,"add":{"jmx-enabled=\u0022":1}
,"jmx-enabled=\u0022":{"true":1}
,"<server>":{"elements":1,"<mirror-group>":1,"instances":1}
,"elements":{"example":1}
,"used":{"terracotta":1,"local":1,"default":1,"start":1}
,"communicate":{"terracotta":1}
,"(tmc)":{"uses":1}
,"uses":{"<servers>":1}
,"either":{"<server>":1}
,"<mirror-group>":{"configurations":1,"instances":1}
,"configurations":{"mixture":1}
,"mixture":{"may":1}
,"may":{"configure":1}
,"multiple":{"servers":1,"mirror":1}
,"mirror":{"groups":1,"group":1}
,"groups":{"<server>":1}
,"instances":{"<servers>":1,"terracotta":1,"share":1}
,"work":{"together":1}
,"together":{"mirror":1}
,"group":{"create":1}
,"stripe":{"<mirror-group>":1}
,"share":{"data":1}
,"directories":{"server\u0027s":1}
,"<data>":{"element":1}
,"point":{"different":1}
,"different":{"preferably":1}
,"preferably":{"local":1}
,"local":{"data":1,"remote":1,"xml":1}
,"directory":{"data":1,"terracotta":1,"path":1}
,"persistence":{"configure":1,"server":1}
,"enabling":{"<restartable>":1}
,"<restartable>":{"means":1,"false":1,"element":1}
,"means":{"shared":1}
,"shared":{"in-memory":1}
,"in-memory":{"data":1,"limited":1}
,"backed":{"case":1}
,"case":{"failure":1}
,"failure":{"automatically":1}
,"automatically":{"restored":1}
,"restored":{"setting":1}
,"setting":{"<restartable>":1}
,"false":{"omitting":1}
,"omitting":{"<restartable>":1}
,"ways":{"configure":1}
,"requires":{"off-heap":1}
,"off-heap":{"store":1}
,"allows":{"data":1}
,"stored":{"in-memory":1}
,"limited":{"amount":1}
,"amount":{"memory":1}
,"memory":{"server":1,"available":1}
,"minimum":{"<offheap>":1}
,"<offheap>":{"size":1}
,"size":{"additional":1,"<offheap>":1,"amount":1,"exceed":1,"servers":1}
,"additional":{"hybrid":1}
,"hybrid":{"storage":1}
,"specify":{"<datastorage>":1,"configuration":1}
,"<datastorage>":{"size":1}
,"available":{"server":1}
,"<hybrid>":{"<datastorage>":1}
,"exceed":{"<offheap>":1}
,"clients":{"running":1}
,"running":{"version":1}
,"version":{"terracotta":1}
,"java":{"information":1}
,"information":{"terracotta":1}
,"parameters":{"server":1}
,"startup":{"behavior":1,"terracotta":1}
,"behavior":{"startup":1}
,"load":{"configuration":1}
,"sources":{"default":1,"explored":1}
,"included":{"terracotta":1}
,"remote":{"xml":1,"configuration":1}
,"explored":{"below":1}
,"below":{"default":1}
,"specified":{"tc-config.xml":1,"local":1}
,"exists":{"directory":1}
,"instance":{"started":1}
,"started":{"default":1,"configuration":1}
,"values":{"used":1}
,"(default)":{"file":1}
,"located":{"directory":1}
,"explicitly":{"specified":1,"specify":1}
,"passing":{"option":1}
,"option":{"script":1}
,"script":{"used":1,"enter":1}
,"start":{"terracotta":1}
,"unix\u002Flinux":{"using":1}
,"enter":{"start-tc-server.sh":1}
,"start-tc-server.sh":{"<path_to_configuration_file>":1}
,"<path_to_configuration_file>":{"<path_to_configuration_file>":1,"url":1}
,"url":{"relative":1}
,"relative":{"directory":1}
,"microsoft":{"windows":1}
,"windows":{"start-tc-server.bat":1}
,"start-tc-server.bat":{"cygwin":1}
,"cygwin":{"(on":1}
,"(on":{"windows)":1}
,"windows)":{"supported":1}
,"supported":{"feature":1}
}
;Search.control.loadWordPairs(pairs);
