var pairs =
{
"scheduled":{"refresh":1,"jobs":1,"100":1}
,"refresh":{"ahead":1,"operation":1,"information":1,"scheduled":1,"job":1,"time":1,"batch":1,"due":1,"run":1}
,"ahead":{"configure":1,"configured":1,"information":1}
,"configure":{"refresh-ahead":1}
,"refresh-ahead":{"operations":1,"mechanism":1}
,"operations":{"occur":1}
,"occur":{"regular":1}
,"regular":{"schedule":1}
,"schedule":{"using":1,"defined":1}
,"using":{"quartz":1,"configured":1,"scheduled":1,"cache":1}
,"quartz":{"scheduled":1,"scheduler":1,"job":1,"instance":1,"property":1,"instances":1,"nodes":1}
,"jobs":{"jobs":1,"asynchronously":1,"scheduled":1,"always":1,"scheduledrefreshname":1,"run":1}
,"asynchronously":{"load":1}
,"load":{"new":1}
,"new":{"values":1}
,"values":{"using":1}
,"configured":{"cache":1,"caches":1,"using":1,"scheduled":1}
,"cache":{"loaders":1,"loader":1,"extension":1,"extensions":1,"configured":1,"filter":1,"information":1,"names":1,"property":1}
,"loaders":{"schedule":1}
,"defined":{"cron":1}
,"cron":{"expression":1,"format":1,"triggers":1}
,"expression":{"type":1,"contain":1,"cron":1}
,"type":{"refresh":1}
,"operation":{"useful":1,"(all":1}
,"useful":{"large":1}
,"large":{"portion":1}
,"portion":{"cache\u0027s":1}
,"cache\u0027s":{"data":1}
,"data":{"updated":1}
,"updated":{"regularly":1}
,"regularly":{"note":1}
,"note":{"least":1,"scheduled-refresh":1,"below":1}
,"least":{"cacheloader":1,"threads":1}
,"cacheloader":{"configured":1,"configuring":1}
,"caches":{"using":1}
,"information":{"configuring":1,"using":1,"ramjobstores":1,"creating":1,"bulk":1}
,"configuring":{"cache":1,"scheduled":1}
,"loader":{"implementing":1}
,"implementing":{"cacheloader":1,"refresh-ahead":1}
,"extension":{"information":1,"responsible":1}
,"extensions":{"cache":1,"<cache":1}
,"<cache":{"<cacheloaderfactory":1}
,"<cacheloaderfactory":{"class=\u0022":1}
,"class=\u0022":{"com.company.my.concretecacheloaderfactory":1,"net.sf.ehcache.constructs.scheduledrefresh.scheduledrefreshcacheextensionfactory":1}
,"com.company.my.concretecacheloaderfactory":{"properties=\u0022":1}
,"properties=\u0022":{"some_property=1":1,"batchsize=100":1}
,"some_property=1":{"some_other_property=2":1}
,"some_other_property=2":{"<cacheextensionfactory":1}
,"<cacheextensionfactory":{"class=\u0022":1}
,"net.sf.ehcache.constructs.scheduledrefresh.scheduledrefreshcacheextensionfactory":{"properties=\u0022":1}
,"batchsize=100":{"quartzjobcount=2":1}
,"quartzjobcount=2":{"cronexpression=0":1}
,"cronexpression=0":{"**?":1}
,"**?":{"propertyseparator=\u0022":1}
,"propertyseparator=\u0022":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"cron":1}
,"contain":{"commas":1}
,"commas":{"default":1}
,"default":{"delimiter":1,"value":1,"underlying":1,"ramjobstore":1,"jobstorefactory":1}
,"delimiter":{"properties":1,"cache-extension":1}
,"properties":{"propertyseparator":1,"optional":1,"classes":1}
,"propertyseparator":{"attribute":1}
,"attribute":{"used":1}
,"used":{"specify":1,"enumerate":1,"quartz":1,"scheduledrefreshterracottajobstorefactory":1}
,"specify":{"different":1}
,"different":{"delimiter":1}
,"cache-extension":{"class":1}
,"class":{"required":1,"implements":1}
,"required":{"implementing":1,"following":1,"string":1}
,"mechanism":{"cache":1}
,"responsible":{"instantiating":1}
,"instantiating":{"dedicated":1}
,"dedicated":{"quartz":1}
,"scheduler":{"ramjobstore":1,"developer":1}
,"ramjobstore":{"non-clustered":1,"used":1}
,"non-clustered":{"cache":1}
,"ramjobstores":{"working":1}
,"working":{"jobstores":1,"triggers":1}
,"jobstores":{"quartz":1}
,"developer":{"guide":1}
,"guide":{"note":1,"n\u002Fa":1}
,"scheduled-refresh":{"configuration":1,"nodes":1}
,"configuration":{"properties":1}
,"optional":{"unless":1}
,"unless":{"marked":1}
,"marked":{"required":1}
,"following":{"table":1}
,"table":{"describes":1}
,"describes":{"properties":1}
,"classes":{"found":1}
,"found":{"net.sf.ehcache.constructs.scheduledrefresh":1}
,"net.sf.ehcache.constructs.scheduledrefresh":{"property":1}
,"property":{"definition":1,"provides":1,"org.quartz.jobstore.tcconfigurl":1,"tcconfigurl":1}
,"definition":{"default":1}
,"value":{"cronexpression":1,"therefore":1,"creates":1,"improve":1,"equal":1,"confirm":1,"gauge":1,"quartzjobcount":1}
,"cronexpression":{"required":1}
,"string":{"expression":1}
,"format":{"dictating":1}
,"dictating":{"refresh":1}
,"job":{"run":1,"refresh":1,"store":1,"(always":1}
,"run":{"information":1,"refresh":1,"distributed":1,"quartz":1}
,"creating":{"cron":1}
,"triggers":{"working":1,"quartz":1}
,"n\u002Fa":{"batchsize":1,"paralleljobcount":1}
,"batchsize":{"(integer)":1}
,"(integer)":{"number":1}
,"number":{"keys":1,"threads":1,"simultaneous":1,"(identical)":1,"quartz":1}
,"keys":{"single":1,"cache":1,"refreshed":1,"loaded":1}
,"single":{"job":1}
,"time":{"jobs":1}
,"100":{"keygenerator":1}
,"keygenerator":{"null":1}
,"null":{"simplescheduledrefreshkeygenerator":1,"usebulkload":1,"evictonloadmiss":1}
,"simplescheduledrefreshkeygenerator":{"used":1}
,"enumerate":{"keys":1}
,"filter":{"keys":1}
,"refreshed":{"provide":1}
,"provide":{"class":1}
,"implements":{"scheduledrefreshkeygenerator":1}
,"scheduledrefreshkeygenerator":{"interface":1}
,"interface":{"overriding":1,"note":1}
,"overriding":{"generatekeys":1}
,"generatekeys":{"method":1}
,"method":{"null":1}
,"usebulkload":{"true":1}
,"true":{"node":1,"entries":1,"jobstorefactory":1}
,"node":{"put":1}
,"put":{"bulkload":1}
,"bulkload":{"mode":1}
,"mode":{"keys":1}
,"loaded":{"cache":1}
,"bulk":{"loading":1}
,"loading":{"bulk":1,"false":1}
,"false":{"quartzjobcount":1}
,"quartzjobcount":{"controls":1,"default":1}
,"controls":{"number":1}
,"threads":{"quartz":1,"needed":1,"process":1}
,"store":{"created":1,"named":1,"implement":1}
,"created":{"instance":1,"respect":1}
,"instance":{"schedulerefreshcacheextension":1,"define":1}
,"schedulerefreshcacheextension":{"least":1}
,"needed":{"controlling":1}
,"controlling":{"job":1}
,"batch":{"jobs":1}
,"always":{"additional":1}
,"additional":{"thread":1}
,"thread":{"created":1}
,"respect":{"value":1}
,"therefore":{"default":1}
,"creates":{"controlling":1}
,"(always":{"created)":1}
,"created)":{"worker":1}
,"worker":{"threads":1}
,"process":{"incoming":1}
,"incoming":{"jobs":1}
,"scheduledrefreshname":{"default":1}
,"underlying":{"quartz":1}
,"named":{"based":1}
,"based":{"combination":1,"time-to-live":1}
,"combination":{"cachemanager":1}
,"cachemanager":{"cache":1}
,"names":{"two":1}
,"two":{"scheduledrefreshextensions":1}
,"scheduledrefreshextensions":{"going":1}
,"going":{"attached":1}
,"attached":{"cache":1}
,"provides":{"necessary":1}
,"necessary":{"name":1}
,"name":{"separate":1}
,"separate":{"instances":1}
,"instances":{"null":1,"supporting":1,"quartz":1}
,"evictonloadmiss":{"boolean":1}
,"boolean":{"force":1}
,"force":{"immediate":1}
,"immediate":{"eviction":1}
,"eviction":{"reload":1,"takes":1}
,"reload":{"miss":1,"operation":1}
,"miss":{"(true)":1}
,"(true)":{"evict":1}
,"evict":{"normal":1}
,"normal":{"eviction":1}
,"takes":{"effect":1}
,"effect":{"(false)":1}
,"(false)":{"true":1}
,"entries":{"refresh":1}
,"due":{"failure":1}
,"failure":{"reload":1}
,"(all":{"cacheloaders":1}
,"cacheloaders":{"fail)":1}
,"fail)":{"evicted":1}
,"evicted":{"even":1}
,"even":{"expired":1}
,"expired":{"based":1}
,"time-to-live":{"time-to-idle":1}
,"time-to-idle":{"settings":1}
,"settings":{"true":1}
,"jobstorefactory":{"default":1,"scheduledrefreshramjobstorefactory":1,"used":1}
,"define":{"custom":1}
,"custom":{"job":1}
,"implement":{"scheduledrefreshjobstorepropertiesfactory":1}
,"scheduledrefreshjobstorepropertiesfactory":{"interface":1}
,"below":{"tcconfigurl":1}
,"tcconfigurl":{"url":1,"specified":1}
,"url":{"terracotta":1}
,"terracotta":{"server":1,"cluster":1}
,"server":{"form":1}
,"form":{"<server-address>":1}
,"<server-address>":{"<tsa-port>":1}
,"<tsa-port>":{"quartz":1}
,"org.quartz.jobstore.tcconfigurl":{"setting":1}
,"setting":{"allows":1}
,"allows":{"quartz":1}
,"supporting":{"scheduled":1}
,"distributed":{"terracotta":1,"scheduled-refresh":1}
,"cluster":{"n\u002Fa":1,"tune":1}
,"paralleljobcount":{"maximum":1}
,"maximum":{"number":1}
,"simultaneous":{"refresh":1}
,"tune":{"value":1}
,"improve":{"performance":1}
,"performance":{"beginning":1,"equals":1}
,"beginning":{"value":1}
,"equal":{"number":1}
,"(identical)":{"distributed":1}
,"nodes":{"multiplied":1,"example":1,"value":1}
,"multiplied":{"total":1}
,"total":{"number":1}
,"example":{"instances":1}
,"confirm":{"resources":1}
,"resources":{"overly":1,"underutilized":1,"performance":1}
,"overly":{"utilized":1}
,"utilized":{"resources":1}
,"underutilized":{"increase":1}
,"increase":{"value":1}
,"gauge":{"impact":1}
,"impact":{"resources":1}
,"equals":{"value":1}
,"scheduledrefreshramjobstorefactory":{"however":1}
,"however":{"property":1}
,"specified":{"jobstorefactory":1}
}
;Search.control.loadWordPairs(pairs);
