var pairs =
{
"special":{"resource":1}
,"resource":{"locations":1,"representations":1,"view":1}
,"locations":{"certain":1,"provide":1,"specified":1}
,"certain":{"resource":1}
,"provide":{"specific":1}
,"specific":{"monitoring":1,"cache-configuration":1}
,"monitoring":{"administration":1}
,"administration":{"services":1}
,"services":{"discovery":1}
,"discovery":{"discovery":1,"uri":1,"uris":1}
,"uri":{"format":1,"returns":1,"probe":1,"http:\u002F\u002Flocalhost:9889\u002Ftmc\u002Fapi\u002Fconfig\u002Fsettings\u002Fauthentication":1}
,"format":{"uses":1,"viewing":1,"configuration":1,"\u002Fagents":1,"http:\u002F\u002F127.0.0.1:9889\u002Ftmc\u002Fapi\u002Fagents\u002Fprobeurl\u002F$urltoprobe":1}
,"uses":{"path":1}
,"path":{"\u002Fagents\u002Finfo":1,"agents\u002Fcachemanagers":1}
,"\u002Fagents\u002Finfo":{"used":1}
,"used":{"terracotta":1,"embedded":1,"change":1}
,"terracotta":{"management":1}
,"management":{"server":1,"console":1}
,"server":{"(tms)":1}
,"(tms)":{"uri":1}
,"returns":{"metadata":1}
,"metadata":{"agents":1,"agent":1}
,"agents":{"known":1,"viewing":1,"cachemanagers":1}
,"known":{"(through":1,"agents":1}
,"(through":{"configuration)":1}
,"configuration)":{"tms":1}
,"tms":{"used":1}
,"embedded":{"web":1,"agencyof":1}
,"web":{"service":1}
,"service":{"metadata":1}
,"agent":{"returned":1,"reachable)":1,"given":1,"running":1,"available":1}
,"returned":{"(or":1,"native":1,"however":1,"json":1,"agentid":1,"note":1}
,"(or":{"404":1}
,"404":{"agent":1}
,"reachable)":{"information":1}
,"information":{"discovery":1,"rest":1}
,"uris":{"refer":1}
,"refer":{"examples":1}
,"examples":{"provided":1}
,"provided":{"discover":1}
,"discover":{"known":1}
,"viewing":{"configuration":1}
,"configuration":{"uri":1,"cachemanagers":1,"caches":1,"cache":1}
,"cachemanagers":{"caches":1,"following":1,"returned":1}
,"caches":{"uses":1,"specified":1,"following":1}
,"agents\u002Fcachemanagers":{"agents\u002Fcachemanagers\u002Fcaches":1}
,"agents\u002Fcachemanagers\u002Fcaches":{"agents":1}
,"specified":{"using":1,"request":1,"setting":1}
,"using":{"ids":1,"resource":1}
,"ids":{"names":1,"specified":1}
,"names":{"data":1}
,"data":{"returned":1}
,"native":{"xml":1}
,"xml":{"format":1}
,"following":{"format":1,"comprehensive":1,"return":1,"returned":1,"uri":1}
,"\u002Fagents":{"ids={comma_sep_agent_ids}]\u002Fcachemanagers":1}
,"ids={comma_sep_agent_ids}]\u002Fcachemanagers":{"names={comma_sep_cache_manager_names}]\u002Fconfigs":1,"names={comma_sep_cache_manager_names}]\u002Fcaches":1}
,"names={comma_sep_cache_manager_names}]\u002Fconfigs":{"client":1}
,"client":{"ids":1}
,"request":{"clients":1,"number":1}
,"clients":{"cachemanagers":1,"default":1,"display":1}
,"however":{"client":1}
,"number":{"clients":1}
,"default":{"maximum":1}
,"maximum":{"error":1,"number":1}
,"error":{"returned":1}
,"json":{"response":1}
,"response":{"jvm":1,"similar":1}
,"jvm":{"argument":1}
,"argument":{"com.terracotta.agent.defaultmaxclientstodisplay":1}
,"com.terracotta.agent.defaultmaxclientstodisplay":{"used":1}
,"change":{"maximum":1,"authentication":1}
,"display":{"configuration":1}
,"names={comma_sep_cache_manager_names}]\u002Fcaches":{"names={comma_sep_cache_names}\u002Fconfigs":1}
,"names={comma_sep_cache_names}\u002Fconfigs":{"setting":1}
,"setting":{"configuration":1,"specific":1}
,"cache":{"resource":1,"operations":1,"statistics":1}
,"cache-configuration":{"attributes":1}
,"attributes":{"using":1,"enabled":1}
,"representations":{"following":1}
,"comprehensive":{"list":1}
,"list":{"attributes":1}
,"enabled":{"boolean":1,":true}":1,":false":1}
,"boolean":{"enabling":1}
,"enabling":{"(true":1,"(true)":1}
,"(true":{"default)":1}
,"default)":{"disabling":1,"gathering":1,"sampling":1}
,"disabling":{"(false)":1,"(false":1}
,"(false)":{"cache":1}
,"operations":{"example":1}
,"example":{"disable":1,"following":1}
,"disable":{"cache\u0027s":1}
,"cache\u0027s":{"operation":1}
,"operation":{"put":1}
,"put":{"enabled":1}
,":true}":{"statsenabled":1}
,"statsenabled":{"boolean":1}
,"(true)":{"disabling":1}
,"(false":{"default)":1}
,"gathering":{"cache":1}
,"statistics":{"sampledstatsenabled":1,"probing":1}
,"sampledstatsenabled":{"boolean":1}
,"sampling":{"cache":1}
,"probing":{"new":1}
,"new":{"connection":1}
,"connection":{"uri":1}
,"probe":{"existence":1}
,"existence":{"agent":1}
,"given":{"location":1,"address":1}
,"location":{"url":1}
,"url":{"following":1}
,"http:\u002F\u002F127.0.0.1:9889\u002Ftmc\u002Fapi\u002Fagents\u002Fprobeurl\u002F$urltoprobe":{"example":1}
,"return":{"information":1}
,"rest":{"agent":1,"resource":1}
,"running":{"given":1}
,"address":{"(localhost:4343)":1}
,"(localhost:4343)":{"http:\u002F\u002F127.0.0.1:9889\u002Ftmc\u002Fapi\u002Fagents\u002Fprobeurl":1}
,"http:\u002F\u002F127.0.0.1:9889\u002Ftmc\u002Fapi\u002Fagents\u002Fprobeurl":{"\u00A0\u002Fhttp":1}
,"\u00A0\u002Fhttp":{"253a":1}
,"253a":{"252f":1}
,"252f":{"252flocalhost":1}
,"252flocalhost":{"253a4343":1}
,"253a4343":{"agent":1}
,"available":{"(status":1,":true":1,"status":1}
,"(status":{"code":1}
,"code":{"200":1,"204":1}
,"200":{"agentmetadataentity)":1}
,"agentmetadataentity)":{"response":1}
,"similar":{"following":1}
,"agentid":{"embedded":1}
,"agencyof":{"ehcache":1}
,"ehcache":{"available":1}
,":true":{"secured":1}
,"secured":{":false":1}
,":false":{"sslenabled":1,"needclientauth":1,"licensed":1,"samplehistorysize":1,"restapiversion":1}
,"sslenabled":{":false":1}
,"needclientauth":{":false":1}
,"licensed":{":false":1}
,"samplehistorysize":{":8640":1}
,":8640":{"sampleintervalseconds":1}
,"sampleintervalseconds":{":10":1}
,":10":{"enabled":1}
,"restapiversion":{"2.7.0":1}
,"2.7.0":{"available":1}
,"status":{"code":1,"authentication":1,"saved":1,"(authentication":1,"following":1,"settings":1}
,"204":{"content":1}
,"content":{"getting":1}
,"getting":{"authentication":1}
,"authentication":{"status":1}
,"saved":{"properties":1}
,"properties":{"file":1}
,"file":{"${user.home}\u002F.tc\u002Fmgmt\u002Fsettings.ini":1}
,"${user.home}\u002F.tc\u002Fmgmt\u002Fsettings.ini":{"rest":1}
,"view":{"status":1}
,"(authentication":{"off)":1}
,"off)":{"authentication":1}
,"http:\u002F\u002Flocalhost:9889\u002Ftmc\u002Fapi\u002Fconfig\u002Fsettings\u002Fauthentication":{"either":1}
,"either":{"true":1}
,"true":{"false":1}
,"false":{"returned":1}
,"note":{"change":1}
,"settings":{"terracotta":1}
}
;Search.control.loadWordPairs(pairs);
