var pairs =
{
"accessing":{"bigmemory":1}
,"bigmemory":{"data":1,"structured":1}
,"data":{"application":1,"made":1}
,"application":{"section":1,"explanation":1}
,"section":{"provides":1}
,"provides":{"basic":1}
,"basic":{"code":1}
,"code":{"snippets":1}
,"snippets":{"accessing":1}
,"explanation":{"refer":1}
,"refer":{"using":1,"api":1,"search":1}
,"using":{".net":1,"bigmemory":1}
,".net":{"client":1}
,"client":{"api":1,"demo":1}
,"api":{"complete":1,"documentation":1}
,"complete":{"class":1}
,"class":{"library":1}
,"library":{"documentation":1}
,"documentation":{"refer":1,"\u002Fapis\u002Fcsharp\u002Fapidoc-csharp.zip":1}
,"\u002Fapis\u002Fcsharp\u002Fapidoc-csharp.zip":{"directory":1}
,"directory":{"kit":1}
,"kit":{"create":1,"(see":1}
,"create":{"cachemanager":1}
,"cachemanager":{"snippet":1,"configuration":1,"cachemanager.close":1}
,"snippet":{"creates":1,"used":1}
,"creates":{"cachemanager":1}
,"configuration":{"uses":1}
,"uses":{"nirvana":1}
,"nirvana":{"shared":1}
,"shared":{"memory":1}
,"memory":{"(shm)":1}
,"(shm)":{"transport":1}
,"transport":{"provisions":1}
,"provisions":{"pool":1}
,"pool":{"connections":1}
,"connections":{"xplatform.createcachemanager":1}
,"xplatform.createcachemanager":{"(new":1}
,"(new":{"terracotta.ehcache.config.configuration":1}
,"terracotta.ehcache.config.configuration":{"(\u0022\u002Fdev\u002Fshm":1}
,"(\u0022\u002Fdev\u002Fshm":{"10))":1}
,"10))":{"retrieve":1}
,"retrieve":{"cache":1}
,"cache":{"cachemanager":1,"snippet":1}
,"used":{".net":1}
,"demo":{"samples":1,"samples)":1}
,"samples":{"kit":1}
,"(see":{".net":1}
,"samples)":{"notice":1}
,"notice":{"serializer":1,"option":1}
,"serializer":{"specified":1}
,"specified":{"cachemanager.getcache":1}
,"cachemanager.getcache":{"testcache":1}
,"testcache":{"new":1}
,"new":{"recipeserializer":1}
,"recipeserializer":{"())":1}
,"())":{"put":1}
,"put":{"entries":1,"operations":1}
,"entries":{"cache":1}
,"option":{"specify":1}
,"specify":{"consistency":1}
,"consistency":{"type":1}
,"type":{"put":1}
,"operations":{"cache.put":1}
,"cache.put":{"(recipe.name":1}
,"(recipe.name":{"recipe":1}
,"recipe":{"consistencytype.strong)":1}
,"consistencytype.strong)":{"close":1}
,"close":{"cachemanager":1}
,"cachemanager.close":{"search":1}
,"search":{"searches":1}
,"searches":{"bigmemory":1}
,"made":{"using":1}
,"structured":{"query":1}
,"query":{"language":1}
,"language":{"(sql)":1}
,"(sql)":{"refer":1}
}
;Search.control.loadWordPairs(pairs);
