var pairs =
{
"extending":{"server":1}
,"server":{"security":1,"authentication":1}
,"security":{"jmx":1,"beyond":1}
,"jmx":{"messages":1}
,"messages":{"encrypted":1}
,"encrypted":{"therefore":1,"tunnel":1}
,"therefore":{"server":1}
,"authentication":{"provide":1}
,"provide":{"secure":1}
,"secure":{"message":1,"location":1}
,"message":{"transmission":1}
,"transmission":{"valid":1}
,"valid":{"credentials":1}
,"credentials":{"provided":1}
,"provided":{"listening":1,"ssh":1}
,"listening":{"client":1}
,"client":{"extend":1}
,"extend":{"security":1}
,"beyond":{"login":1}
,"login":{"threshold":1}
,"threshold":{"consider":1}
,"consider":{"following":1}
,"following":{"options":1}
,"options":{"place":1}
,"place":{"terracotta":1}
,"terracotta":{"servers":1}
,"servers":{"secure":1}
,"location":{"private":1}
,"private":{"network":1}
,"network":{"restrict":1}
,"restrict":{"remote":1}
,"remote":{"queries":1}
,"queries":{"encrypted":1}
,"tunnel":{"provided":1}
,"ssh":{"stunnel":1}
,"stunnel":{"using":1}
,"using":{"public":1,"ehcache":1}
,"public":{"outside":1}
,"outside":{"networks":1}
,"networks":{"vpn":1}
,"vpn":{"communication":1}
,"communication":{"cluster":1}
,"cluster":{"using":1}
,"ehcache":{"add":1}
,"add":{"cache":1}
,"cache":{"decorator":1,"implements":1}
,"decorator":{"cache":1}
,"implements":{"encryption":1}
,"encryption":{"decryption":1}
}
;Search.control.loadWordPairs(pairs);
