var pairs =
{
"searching":{"you\u0027ve":1}
,"you\u0027ve":{"experimented":1}
,"experimented":{"bigmemory\u0027s":1}
,"bigmemory\u0027s":{"basic":1}
,"basic":{"crud":1}
,"crud":{"operations":1,"\u0022\u002F>":1}
,"operations":{"let\u0027s":1}
,"let\u0027s":{"look":1}
,"look":{"search":1}
,"search":{"capabilities":1,"<ehcache":1,"<searchable>":1,"import":1,"{public":1,"data":1,"\u002F\u002Fcreate":1,"program":1}
,"capabilities":{"create":1}
,"create":{"data":1,"configuration":1,"new":1,"search.java":1,"compile":1}
,"data":{"person":1,"final":1,"dataset.put":1}
,"person":{"objects":1,"janeausten":1,"jane":1,"charlesdickens":1,"charles":1,"janedoe":1,"{private":1,"(long":1}
,"objects":{"searchable":1,"final":1,"data":1}
,"searchable":{"attributes":1,"objects":1}
,"attributes":{"including":1}
,"including":{"height":1}
,"height":{"weight":1,"\u0022\u002F>":1,"private":1,"final":1,"public":1,"*(float)":1,"weight=\u0022":1}
,"weight":{"body":1,"\u0022\u002F>":1,"public":1,"\u002F((float)":1,"lbs":1}
,"body":{"mass":1}
,"mass":{"index":1}
,"index":{"create":1,"(bmi)":1}
,"configuration":{"file":1}
,"file":{"create":1,"called":1}
,"new":{"configuration":1,"cache":1}
,"called":{"ehcache-search.xml":1,"search":1}
,"ehcache-search.xml":{"classpath":1}
,"classpath":{"add":1}
,"add":{"new":1}
,"cache":{"called":1,"manager":1,"dataset":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"searchconfig":1,"hello-world":1,"crud":1,"search":1,"height":1,"weight":1,"bodymassindex":1}
,"searchconfig":{"maxbyteslocalheap=\u0022":1}
,"maxbyteslocalheap=\u0022":{"64m":1}
,"64m":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"hello-world":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<cache":1,"<searchattribute":1}
,"<searchable>":{"<searchattribute":1}
,"<searchattribute":{"name=\u0022":1}
,"bodymassindex":{"<\u002Fsearchable>":1,"\u002F\u002Fcreate":1}
,"<\u002Fsearchable>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"create":1}
,"search.java":{"create":1}
,"compile":{"java":1}
,"java":{"class":1}
,"class":{"called":1,"search":1,"person":1}
,"import":{"net.sf.ehcache.cache":1,"net.sf.ehcache.cachemanager":1,"net.sf.ehcache.element":1,"net.sf.ehcache.search.attribute":1,"net.sf.ehcache.search.query":1,"net.sf.ehcache.search.result":1,"net.sf.ehcache.search.results":1}
,"net.sf.ehcache.cache":{"import":1}
,"net.sf.ehcache.cachemanager":{"import":1}
,"net.sf.ehcache.element":{"import":1}
,"net.sf.ehcache.search.attribute":{"import":1}
,"net.sf.ehcache.search.query":{"import":1}
,"net.sf.ehcache.search.result":{"import":1}
,"net.sf.ehcache.search.results":{"public":1}
,"public":{"class":1,"static":1,"person":1,"string":1,"int":1,"float":1,"long":1}
,"{public":{"static":1}
,"static":{"void":1,"class":1}
,"void":{"main":1}
,"main":{"(final":1}
,"(final":{"string":1}
,"string":{"args)":1,"firstname":1,"lastname":1,"getfirstname":1,"getlastname":1,"tostring":1}
,"args)":{"{\u002F\u002Fcreate":1}
,"{\u002F\u002Fcreate":{"cache":1}
,"manager":{"using":1}
,"using":{"factory":1}
,"factory":{"method":1}
,"method":{"final":1}
,"final":{"cachemanager":1,"cache":1,"person":1,"query":1,"results":1,"string":1,"long":1,"int":1}
,"cachemanager":{"cachemanager":1,"=cachemanager.newinstance":1}
,"=cachemanager.newinstance":{"(crud.class":1}
,"(crud.class":{".getresource":1}
,".getresource":{"(\u0022\u002Fehcache-search.xml":1}
,"(\u0022\u002Fehcache-search.xml":{"\u0022))":1}
,"\u0022))":{"\u002F\u002Fretrieve":1}
,"\u002F\u002Fretrieve":{"search":1}
,"dataset":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"search":1}
,"\u002F\u002Fcreate":{"searchable":1,"query":1}
,"janeausten":{"=new":1}
,"=new":{"person":1}
,"jane":{"austen":1,"doe":1}
,"austen":{"*12":1}
,"*12":{"130)":1,"160)":1,"145)":1}
,"130)":{"final":1}
,"charlesdickens":{"=new":1}
,"charles":{"dickens":1}
,"dickens":{"*12":1}
,"160)":{"final":1}
,"janedoe":{"=new":1}
,"doe":{"*12":1}
,"145)":{"\u002F\u002Fput":1}
,"\u002F\u002Fput":{"searchable":1}
,"dataset.put":{"(new":1}
,"(new":{"element":1}
,"element":{"(janeausten.getid":1,"(charlesdickens.getid":1,"(janedoe.getid":1}
,"(janeausten.getid":{"janeausten))":1}
,"janeausten))":{"dataset.put":1}
,"(charlesdickens.getid":{"charlesdickens))":1}
,"charlesdickens))":{"dataset.put":1}
,"(janedoe.getid":{"janedoe))":1}
,"janedoe))":{"\u002F\u002Ffetch":1}
,"\u002F\u002Ffetch":{"body":1}
,"(bmi)":{"attribute":1}
,"attribute":{"attribute":1,"<object>":1}
,"<object>":{"bmi":1}
,"bmi":{"=dataset.getsearchattribute":1,"greater":1}
,"=dataset.getsearchattribute":{"bodymassindex":1}
,"query":{"people":1,"query":1,"=dataset.createquery":1,"final":1}
,"people":{"bmi":1}
,"greater":{"final":1}
,"=dataset.createquery":{".addcriteria":1}
,".addcriteria":{"(bmi.gt":1}
,"(bmi.gt":{"(23f))":1}
,"(23f))":{".includevalues":1}
,".includevalues":{"\u002F\u002Fexecute":1}
,"\u002F\u002Fexecute":{"query":1}
,"results":{"results":1,"=query.execute":1,"(result":1}
,"=query.execute":{"\u002F\u002Fprint":1}
,"\u002F\u002Fprint":{"results":1}
,"(result":{"result":1}
,"result":{"results.all":1}
,"results.all":{"())":1}
,"())":{"{system.out.println":1,"public":1}
,"{system.out.println":{"(result.getvalue":1}
,"(result.getvalue":{"())":1}
,"{private":{"final":1}
,"firstname":{"private":1,"final":1,"public":1,"lastname=\u0022":1}
,"private":{"final":1}
,"lastname":{"private":1,"final":1,"public":1,"height=\u0022":1}
,"long":{"private":1,"getid":1}
,"int":{"height":1,"weight":1,"weight)":1,"getheight":1,"getweight":1}
,"(long":{"final":1}
,"weight)":{"{this.id":1}
,"{this.id":{"=id":1}
,"=id":{"this.firstname":1}
,"this.firstname":{"=firstname":1}
,"=firstname":{"this.lastname":1}
,"this.lastname":{"=lastname":1}
,"=lastname":{"this.height":1}
,"this.height":{"=height":1}
,"=height":{"this.weight":1}
,"this.weight":{"=weight":1}
,"=weight":{"public":1}
,"getfirstname":{"{return":1}
,"{return":{"firstname":1,"lastname":1,"height":1,"weight":1,"((float)":1,"public":1,"[id=\u0022":1}
,"getlastname":{"{return":1}
,"getheight":{"{return":1}
,"getweight":{"{return":1}
,"float":{"getbodymassindex":1}
,"getbodymassindex":{"{return":1,"execute":1}
,"((float)":{"weight":1}
,"\u002F((float)":{"height":1}
,"*(float)":{"height))":1}
,"height))":{"*703":1}
,"*703":{"public":1}
,"getid":{"{return":1}
,"tostring":{"{return":1}
,"[id=\u0022":{"firstname=\u0022":1}
,"firstname=\u0022":{"firstname":1}
,"lastname=\u0022":{"lastname":1}
,"height=\u0022":{"height":1}
,"weight=\u0022":{"weight":1}
,"lbs":{"bmi=\u0022":1,"bmi=23.625288]":1,"bmi=24.126627]":1}
,"bmi=\u0022":{"getbodymassindex":1}
,"execute":{"run":1}
,"run":{"search":1}
,"program":{"terminal":1}
,"terminal":{"output":1}
,"output":{"[id=2":1}
,"[id=2":{"firstname=charles":1}
,"firstname=charles":{"lastname=dickens":1}
,"lastname=dickens":{"height=69":1}
,"height=69":{"weight=160":1}
,"weight=160":{"lbs":1}
,"bmi=23.625288]":{"[id=3":1}
,"[id=3":{"firstname=jane":1}
,"firstname=jane":{"lastname=doe":1}
,"lastname=doe":{"height=65":1}
,"height=65":{"weight=145":1}
,"weight=145":{"lbs":1}
,"bmi=24.126627]":{"next":1}
,"next":{"step":1}
,"step":{"next":1,"sorting":1}
,"sorting":{"results":1}
}
;Search.control.loadWordPairs(pairs);
