var pairs =
{
"common":{"issues":1}
,"issues":{"following":1,"encountered":1}
,"following":{"sections":1}
,"sections":{"summarize":1}
,"summarize":{"common":1}
,"encountered":{"clustering":1}
,"clustering":{"web":1,"events":1}
,"web":{"sessions":1}
,"sessions":{"sessions":1,"time":1,"expire":1,"hop":1,"run":1,"clustered":1,"deadlocks":1}
,"time":{"unexpectedly":1,"instead":1,"node":1,"validate":1,"original":1,"protocol":1,"zones":1,"later":1}
,"unexpectedly":{"sessions":1}
,"expire":{"certain":1,"unexpected":1}
,"certain":{"time":1}
,"instead":{"seem":1}
,"seem":{"expire":1}
,"unexpected":{"times":1}
,"times":{"sooner":1}
,"sooner":{"expected":1}
,"expected":{"problem":1,"although":1}
,"problem":{"occur":1,"even":1,"cause":1}
,"occur":{"sessions":1,"example":1}
,"hop":{"nodes":1}
,"nodes":{"system":1,"help":1,"different":1}
,"system":{"time":1}
,"node":{"receives":1,"checks":1,"adding":1,"servlet":1,"occur":1,"destroyed":1,"event":1,"first":1}
,"receives":{"request":1}
,"request":{"session":1,"made":1,"fails":1}
,"session":{"originated":1,"time":1,"locking":1,"access":1,"type":1,"locked":1,"created":1}
,"originated":{"different":1}
,"different":{"node":1,"time":1}
,"checks":{"local":1}
,"local":{"time":1}
,"validate":{"session":1}
,"original":{"node":1}
,"adding":{"network":1}
,"network":{"time":1}
,"protocol":{"(ntp)":1}
,"(ntp)":{"nodes":1}
,"help":{"avoid":1}
,"avoid":{"system-time":1}
,"system-time":{"drift":1}
,"drift":{"however":1}
,"however":{"note":1}
,"note":{"having":1}
,"having":{"nodes":1}
,"zones":{"cause":1}
,"cause":{"problem":1,"sessions":1}
,"even":{"ntp":1}
,"ntp":{"problem":1}
,"later":{"expected":1}
,"although":{"variation":1}
,"variation":{"causes":1}
,"causes":{"changes":1}
,"changes":{"replicated":1}
,"replicated":{"terracotta":1,"sessions":1}
,"terracotta":{"web":1,"clustering":1}
,"run":{"serialization":1}
,"serialization":{"mode":1}
,"mode":{"serialization":1,"sessions":1}
,"clustered":{"application":1}
,"application":{"follow":1}
,"follow":{"standard":1}
,"standard":{"servlet":1}
,"servlet":{"convention":1,"spec-defined":1}
,"convention":{"using":1}
,"using":{"setattribute":1}
,"setattribute":{"mutable":1}
,"mutable":{"objects":1}
,"objects":{"replicated":1}
,"deadlocks":{"session":1}
,"locking":{"enabled":1,"effect":1}
,"enabled":{"containers":1}
,"containers":{"frameworks":1}
,"frameworks":{"possible":1}
,"possible":{"deadlocks":1}
,"effect":{"happens":1}
,"happens":{"external":1}
,"external":{"request":1}
,"made":{"inside":1}
,"inside":{"locked":1}
,"locked":{"session":1,"events":1}
,"access":{"session":1}
,"type":{"request":1}
,"fails":{"session":1}
,"events":{"received":1,"work":1,"generated":1}
,"received":{"node":1,"second":1}
,"spec-defined":{"events":1}
,"work":{"terracotta":1}
,"generated":{"node":1}
,"example":{"session":1}
,"created":{"node":1}
,"destroyed":{"second":1}
,"second":{"node":1}
,"event":{"received":1}
,"first":{"node":1}
}
;Search.control.loadWordPairs(pairs);
