var pairs =
{
"viewing":{"hibernate":1}
,"hibernate":{"statistics":1,"using":1}
,"statistics":{"possible":1,"bigmemory":1,"using":1,"collection":1}
,"possible":{"access":1}
,"access":{"hibernate":1}
,"bigmemory":{"max":1,"max)":1}
,"max":{"statistics":1}
,"using":{"java":1,"apis":1}
,"java":{"management":1}
,"management":{"extensions":1}
,"extensions":{"(jmx)":1}
,"(jmx)":{"ehcachehibernatembean":1}
,"ehcachehibernatembean":{"main":1}
,"main":{"interface":1}
,"interface":{"exposes":1}
,"exposes":{"apis":1}
,"apis":{"via":1,"cache":1}
,"via":{"jmx":1}
,"jmx":{"basically":1}
,"basically":{"extends":1}
,"extends":{"two":1}
,"two":{"interfaces":1}
,"interfaces":{"ehcachestats":1}
,"ehcachestats":{"hibernatestats":1,"contains":1}
,"hibernatestats":{"names":1,"contains":1}
,"names":{"imply":1}
,"imply":{"ehcachestats":1}
,"contains":{"methods":1}
,"methods":{"related":1}
,"related":{"ehcache":1,"hibernate":1}
,"ehcache":{"(and":1}
,"(and":{"thereby":1}
,"thereby":{"bigmemory":1}
,"max)":{"hibernatestats":1}
,"cache":{"hit\u002Fmiss\u002Fput":1}
,"hit\u002Fmiss\u002Fput":{"rates":1}
,"rates":{"change":1}
,"change":{"config":1}
,"config":{"element":1}
,"element":{"values":1}
,"values":{"(e.g":1}
,"(e.g":{"maxelementinmemory":1}
,"maxelementinmemory":{"ttl":1}
,"ttl":{"tti)":1}
,"tti)":{"enable\u002Fdisable":1}
,"enable\u002Fdisable":{"statistics":1}
,"collection":{"various":1}
,"various":{"things":1}
,"things":{"details":1}
,"details":{"specific":1}
,"specific":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
