var pairs =
{
"adding":{"new":1}
,"new":{"server":1,"<server>":1}
,"server":{"add":1,"terracotta":1,"appear":1,"topology":1}
,"add":{"new":1}
,"terracotta":{"cluster":1,"configuration":1,"management":1}
,"cluster":{"follow":1,"new":1,"terracotta":1,"selected":1}
,"follow":{"steps":1}
,"steps":{"add":1}
,"<server>":{"block":1}
,"block":{"<servers>":1,"contain":1}
,"<servers>":{"<mirror-group>":1}
,"<mirror-group>":{"section":1}
,"section":{"terracotta":1}
,"configuration":{"file":1}
,"file":{"used":1,"\u0027\u002Fbigmemory-max-4\u002Ftc-config.xml":1}
,"used":{"cluster":1}
,"contain":{"minimum":1}
,"minimum":{"information":1}
,"information":{"required":1,"using":1}
,"required":{"configure":1}
,"configure":{"new":1}
,"appear":{"similar":1}
,"similar":{"following":1}
,"following":{"values":1,"2013-03-14":1}
,"values":{"substituted":1}
,"substituted":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"myhost":1}
,"myhost":{"name=\u0022":1}
,"name=\u0022":{"server2":1}
,"server2":{"<data>":1}
,"<data>":{"(user.home)\u002Fterracotta\u002Fserver2\u002Fserver-data":1}
,"(user.home)\u002Fterracotta\u002Fserver2\u002Fserver-data":{"<\u002Fdata>":1}
,"<\u002Fdata>":{"<logs>":1}
,"<logs>":{"(user.home)\u002Fterracotta\u002Fserver2\u002Fserver-logs":1}
,"(user.home)\u002Fterracotta\u002Fserver2\u002Fserver-logs":{"<\u002Flogs>":1}
,"<\u002Flogs>":{"<tsa-port>":1}
,"<tsa-port>":{"9510":1}
,"9510":{"<\u002Ftsa-port>":1}
,"<\u002Ftsa-port>":{"<management-port>":1}
,"<management-port>":{"9540":1}
,"9540":{"<\u002Fmanagement-port>":1}
,"<\u002Fmanagement-port>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"sure":1}
,"sure":{"connected":1}
,"connected":{"tmc":1,"target":1}
,"tmc":{"tmc":1,"connected":1,"don":1,"click":1}
,"target":{"cluster":1}
,"management":{"console":1}
,"console":{"user":1}
,"user":{"guide":1}
,"guide":{"information":1}
,"using":{"tmc":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"target":1}
,"selected":{"tmc":1}
,"click":{"administration":1,"reload":1}
,"administration":{"tab":1}
,"tab":{"choose":1}
,"choose":{"panel":1}
,"panel":{"click":1}
,"reload":{"message":1,"operation":1}
,"message":{"appears":1,"similar":1}
,"appears":{"result":1}
,"result":{"reload":1}
,"operation":{"successful":1,"logs":1}
,"successful":{"operation":1}
,"logs":{"message":1}
,"2013-03-14":{"13:25:44,821":1}
,"13:25:44,821":{"info":1}
,"info":{"-successfully":1}
,"-successfully":{"overridden":1}
,"overridden":{"server":1}
,"topology":{"file":1}
,"\u0027\u002Fbigmemory-max-4\u002Ftc-config.xml":{"start":1}
,"start":{"new":1}
}
;Search.control.loadWordPairs(pairs);
