var pairs =
{
"basic":{"high-availability":1}
,"high-availability":{"configuration":1}
,"configuration":{"basic":1,"following":1}
,"following":{"components":1}
,"components":{"two":1}
,"two":{"terracotta":1}
,"terracotta":{"server":1,"clients":1}
,"server":{"instances":1,"array":1,"instance":1}
,"instances":{"may":1,"work":1,"information":1,"terracotta":1,"automatic":1}
,"may":{"high":1}
,"high":{"availability":1}
,"availability":{"using":1}
,"using":{"either":1}
,"either":{"<server>":1}
,"<server>":{"<mirror-group>":1,"instances":1}
,"<mirror-group>":{"configurations":1,"instances":1}
,"configurations":{"note":1}
,"note":{"<server>":1}
,"work":{"together":1}
,"together":{"mirror":1}
,"mirror":{"group":1,"terracotta":1}
,"group":{"create":1}
,"create":{"stripe":1}
,"stripe":{"configure":1}
,"configure":{"election-time":1}
,"election-time":{"<mirror-group>":1}
,"information":{"cluster":1,"server-client":1}
,"cluster":{"multiple":1}
,"multiple":{"terracotta":1}
,"array":{"architecture":1}
,"architecture":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
,"guide":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"server-server":1}
,"server-server":{"reconnection":1}
,"reconnection":{"reconnection":1,"mechanism":1}
,"mechanism":{"enabled":1}
,"enabled":{"restore":1}
,"restore":{"lost":1}
,"lost":{"connections":1}
,"connections":{"active":1,"terracotta":1}
,"active":{"mirror":1}
,"automatic":{"server":1,"client":1}
,"instance":{"reconnect":1}
,"reconnect":{"information":1}
,"server-client":{"reconnection":1}
,"clients":{"server":1}
,"client":{"reconnect":1}
}
;Search.control.loadWordPairs(pairs);
