var pairs =
{
"healthchecker":{"healthchecker":1,"connection":1,"functions":1,"terracotta":1,"corrective":1,"default":1,"using":1}
,"connection":{"monitor":1}
,"monitor":{"similar":1}
,"similar":{"tcp":1}
,"tcp":{"keep-alive":1}
,"keep-alive":{"healthchecker":1}
,"functions":{"terracotta":1}
,"terracotta":{"server":1,"sever":1,"nodes":1,"node":1,"properties":1,"client":1}
,"server":{"instances":1,"instance":1,"terracotta":1,"(ha":1,"property":1}
,"instances":{"(in":1,"clients":1}
,"(in":{"high":1}
,"high":{"availability":1}
,"availability":{"environments)":1}
,"environments)":{"terracotta":1}
,"sever":{"instances":1}
,"clients":{"using":1}
,"using":{"healthchecker":1,"certain":1}
,"nodes":{"determine":1,"reachable":1}
,"determine":{"peer":1}
,"peer":{"nodes":1,"node":1}
,"reachable":{"operation":1}
,"operation":{"peer":1}
,"node":{"unreachable":1,"using":1}
,"unreachable":{"down":1}
,"down":{"terracotta":1}
,"corrective":{"action":1}
,"action":{"healthchecker":1}
,"default":{"configure":1}
,"configure":{"healthchecker":1}
,"certain":{"terracotta":1}
,"properties":{"grouped":1}
,"grouped":{"three":1}
,"three":{"different":1}
,"different":{"categories":1}
,"categories":{"terracotta":1}
,"instance":{"terracotta":1}
,"client":{"terracotta":1}
,"(ha":{"setup":1}
,"setup":{"only)":1}
,"only)":{"terracotta":1}
,"property":{"category":1,"applies":1}
,"category":{"indicated":1}
,"indicated":{"prefix":1}
,"prefix":{"l2.healthcheck.l1":1}
,"l2.healthcheck.l1":{"indicates":1}
,"indicates":{"l2.healthcheck.l2":1,"l1.healthcheck.l2":1,"example":1}
,"l2.healthcheck.l2":{"indicates":1}
,"l1.healthcheck.l2":{"indicates":1}
,"example":{"l2.healthcheck.l2.ping.enabled":1}
,"l2.healthcheck.l2.ping.enabled":{"property":1}
}
;Search.control.loadWordPairs(pairs);
