var pairs =
{
"security":{"bigmemory":1}
,"bigmemory":{"client":1}
,"client":{"security":1,"provide":1,"keychain":1,"certificate":1}
,"provide":{"client":1}
,"keychain":{"entry":1}
,"entry":{"keystore":1}
,"keystore":{"location":1}
,"location":{"example":1}
,"example":{".\u005Ctools\u005Csecurity\u005Cbin\u005Ckeychain.bat":1}
,".\u005Ctools\u005Csecurity\u005Cbin\u005Ckeychain.bat":{"keys\u002Fl1keychain.key":1}
,"keys\u002Fl1keychain.key":{"keys\u002Fcl-keystore.jks":1}
,"keys\u002Fcl-keystore.jks":{"add":1}
,"add":{"self-signed":1,"client":1,"truststore":1}
,"self-signed":{"certificates":1}
,"certificates":{"truststore":1,"folder":1}
,"truststore":{"add":1,"windows":1,"selfsignedcert.crt":1}
,"certificate":{"add":1,"windows":1,"selfsignedcert.crt":1}
,"windows":{"open":1}
,"open":{"start":1}
,"start":{"menu":1}
,"menu":{"click":1}
,"click":{"run":1,"certificates":1}
,"run":{"enter":1}
,"enter":{"certmgr.msc":1}
,"certmgr.msc":{"new":1}
,"new":{"window":1}
,"window":{"expand":1}
,"expand":{"personal":1,"trusted":1}
,"personal":{"folder":1}
,"folder":{"right":1,"select":1,"right-click":1}
,"right":{"click":1}
,"select":{"tasks->":1}
,"tasks->":{"import":1}
,"import":{"follow":1,"client":1,"truststore":1}
,"follow":{"instructions":1}
,"instructions":{"import":1}
,"selfsignedcert.crt":{"add":1}
,"trusted":{"root":1}
,"root":{"certification":1}
,"certification":{"authorities":1}
,"authorities":{"folder":1}
,"right-click":{"certificates":1}
}
;Search.control.loadWordPairs(pairs);
