var pairs =
{
"configuration":{"examples":1,"declares":1}
,"examples":{"configuration":1,"section":1}
,"section":{"show":1}
,"show":{"settings":1}
,"settings":{"healthchecker":1,"create":1}
,"healthchecker":{"however":1,"client":1,"low":1,"max":1,"configuration":1,"declared":1,"declares":1,"higher":1}
,"however":{"apply":1}
,"apply":{"similarly":1}
,"similarly":{"means":1}
,"means":{"server":1}
,"server":{"using":1}
,"using":{"healthchecker":1}
,"client":{"aggressive":1}
,"aggressive":{"following":1,"healthchecker":1}
,"following":{"settings":1,"2000":1,"5000":1}
,"create":{"aggressive":1,"healthchecker":1}
,"low":{"tolerance":1}
,"tolerance":{"short":1,"interruptions":1}
,"short":{"network":1}
,"network":{"outages":1,"cable":1,"communications":1}
,"outages":{"long":1}
,"long":{"cycles":1,"cycle":1}
,"cycles":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"l1.healthcheck.l2.ping.enabled":1,"l1.healthcheck.l2.ping.idletime":1,"l1.healthcheck.l2.ping.interval":1,"l1.healthcheck.l2.ping.probes":1,"l1.healthcheck.l2.socketconnect":1,"l1.healthcheck.l2.socketconnecttimeout":1,"l1.healthcheck.l2.socketconnectcount":1}
,"l1.healthcheck.l2.ping.enabled":{"value=\u0022":1}
,"value=\u0022":{"true":1,"2000":1,"1000":1,"<property":1,"according":1,"5000":1}
,"true":{"<property":1}
,"l1.healthcheck.l2.ping.idletime":{"value=\u0022":1}
,"2000":{"<property":1,"[(3":1,"*1000)":1}
,"l1.healthcheck.l2.ping.interval":{"value=\u0022":1}
,"1000":{"<property":1,"1000)]":1}
,"l1.healthcheck.l2.ping.probes":{"value=\u0022":1}
,"l1.healthcheck.l2.socketconnect":{"value=\u0022":1}
,"l1.healthcheck.l2.socketconnecttimeout":{"value=\u0022":1}
,"l1.healthcheck.l2.socketconnectcount":{"value=\u0022":1}
,"according":{"healthchecker":1}
,"max":{"time":1}
,"time":{"formula":1,"remote":1,"frame)":1,"likely":1}
,"formula":{"maximum":1}
,"maximum":{"time":1}
,"remote":{"node":1,"failed":1}
,"node":{"considered":1,"reachable":1,"dead":1,"completely":1}
,"considered":{"lost":1}
,"lost":{"computed":1}
,"computed":{"following":1}
,"[(3":{"*1000":1,"1000":1}
,"*1000":{"*1000)]":1,"=7000":1,"=13000":1}
,"*1000)]":{"=27000":1}
,"=27000":{"case":1}
,"case":{"initial":1,"healthchecker":1}
,"initial":{"idletime":1}
,"idletime":{"seconds":1}
,"seconds":{"remote":1,"point":1,"tolerant":1}
,"failed":{"respond":1}
,"respond":{"ping":1}
,"ping":{"probes":1}
,"probes":{"responded":1}
,"responded":{"every":1}
,"every":{"socket":1}
,"socket":{"connection":1}
,"connection":{"attempt":1}
,"attempt":{"indicating":1,"failed)":1}
,"indicating":{"node":1}
,"reachable":{"functional":1}
,"functional":{"(within":1}
,"(within":{"allowed":1}
,"allowed":{"time":1}
,"frame)":{"long":1,"excessively":1}
,"cycle":{"aggressive":1,"tolerant":1}
,"declares":{"node":1}
,"dead":{"seconds":1,"sooner":1}
,"point":{"node":1}
,"completely":{"unreachable":1}
,"unreachable":{"socket":1}
,"failed)":{"healthchecker":1}
,"declared":{"dead":1}
,"sooner":{"example":1}
,"example":{"problem":1}
,"problem":{"disconnected":1}
,"disconnected":{"network":1}
,"cable":{"max":1}
,"likely":{"even":1}
,"even":{"shorter":1}
,"shorter":{"2000":1,"5000":1}
,"*1000)":{"*1000":1}
,"=7000":{"case":1}
,"tolerant":{"following":1,"healthchecker":1}
,"higher":{"tolerance":1}
,"interruptions":{"network":1}
,"communications":{"long":1}
,"5000":{"<property":1,"[(3":1,"*1000)":1}
,"1000)]":{"=85000":1}
,"=85000":{"case":1}
,"excessively":{"long":1}
,"=13000":{"case":1}
}
;Search.control.loadWordPairs(pairs);
