var pairs =
{
"server":{"settings":1,"override":1,"versions":1,"tti=15":1,"tti":1}
,"settings":{"override":1,"tc.property":1,"server":1,"client":1,"maxentrieslocalheap":1,"global":1,"maxbyteslocalheap":1}
,"override":{"client":1,"cache":1}
,"client":{"settings":1,"tc.property":1,"server":1,"throw":1,"example":1,"join":1,"tti":1,"accept":1}
,"tc.property":{"ehcache.clustered.config.override.mode":1,"tc-config.xml":1}
,"ehcache.clustered.config.override.mode":{"allows":1}
,"allows":{"determine":1}
,"determine":{"cache":1}
,"cache":{"settings":1,"configuration":1}
,"tc-config.xml":{"file":1}
,"file":{"define":1}
,"define":{"system":1}
,"system":{"property":1}
,"property":{"com.tc":1}
,"com.tc":{"prefix":1}
,"prefix":{"possible":1}
,"possible":{"values":1}
,"values":{"none-default":1,"server\u2019s":1}
,"none-default":{"behavior":1}
,"behavior":{"discrepancy":1}
,"discrepancy":{"client":1}
,"versions":{"cache":1}
,"configuration":{"option":1,"includes":1}
,"option":{"causes":1}
,"causes":{"client":1}
,"throw":{"exception":1}
,"exception":{"global-allows":1}
,"global-allows":{"cache-wide":1}
,"cache-wide":{"settings":1}
,"example":{"client":1}
,"join":{"tti=10":1}
,"tti=10":{"server":1}
,"tti=15":{"server":1}
,"tti":{"value":1}
,"value":{"overrides":1,"local":1}
,"overrides":{"client":1}
,"local":{"settings":1}
,"maxentrieslocalheap":{"overridden":1}
,"overridden":{"-causes":1}
,"-causes":{"client":1}
,"accept":{"values":1}
,"server\u2019s":{"configuration":1}
,"includes":{"cache-wide":1}
,"global":{"local":1}
}
;Search.control.loadWordPairs(pairs);
