var pairs =
{
"initial":{"setup":1}
,"setup":{"terracotta":1,"page":1}
,"terracotta":{"management":1,"products":1,"license":1}
,"management":{"console":1,"server":1,"configured":1}
,"console":{"(tmc)":1,"allows":1}
,"(tmc)":{"web-based":1}
,"web-based":{"administration":1}
,"administration":{"monitoring":1}
,"monitoring":{"application":1}
,"application":{"terracotta":1}
,"products":{"tmc":1}
,"tmc":{"connections":1,"function":1,"running":1,"clicking":1,"authentication":1,"settings":1,"without":1,"affect":1,"security":1,"using":1,"administrator":1,"operator":1,"inactivity":1,"apache":1}
,"connections":{"managed":1,"ldap":1,"secured":1,"account":1,"create":1}
,"managed":{"terracotta":1}
,"server":{"(tms)":1,"information":1,"instructions":1}
,"(tms)":{"running":1}
,"running":{"tmc":1,"information":1}
,"function":{"confirm":1}
,"confirm":{"version":1}
,"version":{"tmc":1}
,"information":{"tmc":1,"simple":1,"setting":1,"bigmemory":1,"configured":1,"apache":1}
,"clicking":{"toolbar":1}
,"toolbar":{"first":1}
,"first":{"connect":1}
,"connect":{"tmc":1}
,"authentication":{"setup":1,"without":1,"enabled\u002Fdisabled":1,"connect":1,"following":1,"information":1,"ldap":1,"controls":1,"authentication":1,"using":1,"restart":1}
,"page":{"appears":1}
,"appears":{"choose":1,"select":1,"initializing":1,"time":1}
,"choose":{"run":1,".ini-file":1}
,"run":{"tmc":1}
,"without":{"authentication":1,"prompted":1,"user":1}
,"enabled\u002Fdisabled":{"tmc":1}
,"settings":{"panel":1}
,"panel":{"enable":1}
,"enable":{"authentication":1}
,"prompted":{"login":1}
,"login":{"password":1,"screen":1}
,"password":{"enable":1,"account":1}
,"following":{"choices":1,"block":1}
,"choices":{"appear":1}
,"appear":{".ini":1}
,".ini":{"file":1}
,"file":{"-simple":1,"needed":1,"simplest":1,"uncomment":1}
,"-simple":{"built-in":1}
,"built-in":{"role-based":1}
,"role-based":{"authentication":1,"accounts":1}
,"simple":{"account-based":1}
,"account-based":{"authentication":1}
,"ldap":{"-use":1,"server":1,"active":1}
,"-use":{"ldap":1,"active":1}
,"setting":{"ldap":1,"connections":1,"authorization":1,"unrelated":1}
,"active":{"directory":1,"default":1}
,"directory":{"authorization":1,"-use":1,"server":1,"available":1,"setting":1,"open":1}
,"authorization":{"microsoft":1,"setting":1,"authentication":1}
,"microsoft":{"active":1}
,"instructions":{"setting":1}
,"available":{"form":1}
,"form":{"appears":1}
,"select":{"ldap":1}
,"controls":{"access":1}
,"access":{"tmc":1}
,"affect":{"connections":1}
,"secured":{"separately":1}
,"separately":{"information":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
,"security":{"guide":1,"simple":1}
,"guide":{"addition":1}
,"addition":{"appropriate":1}
,"appropriate":{"terracotta":1}
,"license":{"file":1}
,"needed":{"run":1}
,"using":{"built-in":1,"stop-tmc":1}
,"accounts":{"backed":1,"control":1}
,"backed":{".ini":1}
,"simplest":{"scheme":1}
,"scheme":{"choose":1}
,".ini-file":{"authentication":1}
,"restart":{"tmc":1}
,"stop-tmc":{"start-tmc":1}
,"start-tmc":{"scripts":1}
,"scripts":{"setup":1}
,"initializing":{"two":1}
,"two":{"accounts":1}
,"control":{"access":1,"tmc":1}
,"administrator":{"-this":1}
,"-this":{"account":1,"read-only":1}
,"account":{"(username":1,"cannot":1,"click":1}
,"(username":{"admin":1,"operator":1}
,"admin":{"read":1}
,"read":{"write":1}
,"write":{"control":1}
,"operator":{"-this":1,"view":1}
,"read-only":{"account":1}
,"view":{"statistics":1}
,"statistics":{"information":1}
,"configured":{"connections":1,"inactivity":1}
,"cannot":{"add":1}
,"add":{"edit":1}
,"edit":{"connections":1}
,"create":{"password":1}
,"click":{"done":1}
,"done":{"login":1}
,"screen":{"login":1,"appears":1}
,"time":{"connection":1,"passed":1}
,"connection":{"made":1}
,"made":{"tmc":1}
,"inactivity":{"timeout":1,"navigate":1}
,"timeout":{"terracotta":1,"inactivity":1,"minutes":1,"setting":1}
,"allows":{"connected":1}
,"connected":{"user":1,"indefinitely":1}
,"user":{"remained":1,"active":1,"activity":1,"automatically":1}
,"remained":{"connected":1}
,"indefinitely":{"whether":1}
,"whether":{"user":1}
,"default":{"timeout":1,"value":1}
,"navigate":{"web_inf":1}
,"web_inf":{"directory":1}
,"open":{"web.xml":1}
,"web.xml":{"file":1}
,"uncomment":{"following":1}
,"block":{"accept":1}
,"accept":{"default":1}
,"value":{"idletimeoutminutes":1,"<context-param>":1}
,"idletimeoutminutes":{"specify":1,"<\u002Fparam-name>":1}
,"specify":{"different":1}
,"different":{"value":1}
,"<context-param>":{"<description>":1}
,"<description>":{"amount":1}
,"amount":{"time":1}
,"passed":{"without":1}
,"activity":{"user":1,"information":1}
,"automatically":{"logged":1}
,"logged":{"<\u002Fdescription>":1}
,"<\u002Fdescription>":{"<param-name>":1}
,"<param-name>":{"idletimeoutminutes":1}
,"<\u002Fparam-name>":{"<param-value>":1}
,"<param-value>":{"<\u002Fparam-value>":1}
,"<\u002Fparam-value>":{"<\u002Fcontext-param>":1}
,"<\u002Fcontext-param>":{"note":1}
,"note":{"internal":1}
,"internal":{"tsa":1}
,"tsa":{"tmc":1}
,"apache":{"shiro":1}
,"shiro":{"session":1,"shiro":1}
,"session":{"management":1}
,"minutes":{"expressed":1}
,"expressed":{"milliseconds":1}
,"milliseconds":{"securitymanager.sessionmanager.globalsessiontimeout":1}
,"securitymanager.sessionmanager.globalsessiontimeout":{"=600000":1}
,"=600000":{"however":1}
,"however":{"timeout":1}
,"unrelated":{"human":1}
,"human":{"end-user":1}
,"end-user":{"activity":1}
}
;Search.control.loadWordPairs(pairs);
