var pairs =
{
"common":{"causes":1,"error":1}
,"causes":{"failures":1}
,"failures":{"cluster":1}
,"cluster":{"common":1,"interruptions":1,"test":1,"disks":1}
,"interruptions":{"network":1}
,"network":{"long":1,"connections":1,"segments":1,"hardware":1}
,"long":{"java":1,"cycles":1}
,"java":{"cycles":1}
,"cycles":{"particular":1,"analyze":1,"inconsistent":1}
,"particular":{"nodes":1}
,"nodes":{"tuning":1,"cluster":1}
,"tuning":{"healthchecker":1}
,"healthchecker":{"reconnect":1}
,"reconnect":{"features":1}
,"features":{"reduce":1,"require":1}
,"reduce":{"eliminate":1}
,"eliminate":{"two":1}
,"two":{"problems":1}
,"problems":{"however":1}
,"however":{"additional":1}
,"additional":{"actions":1}
,"actions":{"considered":1}
,"considered":{"sporadic":1}
,"sporadic":{"disruptions":1}
,"disruptions":{"network":1}
,"connections":{"l2s":1,"client":1}
,"l2s":{"l2s":1,"l1s":1}
,"l1s":{"difficult":1}
,"difficult":{"track":1}
,"track":{"down":1,"memory":1}
,"down":{"sure":1,"error":1}
,"sure":{"thoroughly":1,"enough":1}
,"thoroughly":{"test":1}
,"test":{"network":1}
,"segments":{"connecting":1}
,"connecting":{"nodes":1}
,"hardware":{"check":1}
,"check":{"speed":1}
,"speed":{"noise":1}
,"noise":{"reliability":1}
,"reliability":{"applications":1}
,"applications":{"grab":1,"compete":1}
,"grab":{"bandwidth":1}
,"bandwidth":{"sources":1}
,"sources":{"failures":1}
,"disks":{"nearly":1}
,"nearly":{"full":1}
,"full":{"running":1}
,"running":{"slowly":1,"applications":1,"low":1}
,"slowly":{"running":1}
,"compete":{"node\u0027s":1}
,"node\u0027s":{"resources":1}
,"resources":{"interrupt":1}
,"interrupt":{"ensure":1,"clustered":1}
,"ensure":{"application":1}
,"application":{"interrupt":1,"often":1,"necessarily":1}
,"clustered":{"threads":1}
,"threads":{"common":1,"effect":1}
,"error":{"cause":1,"state":1}
,"cause":{"terracotta":1,"analyze":1}
,"terracotta":{"client":1,"server":1,"management":1,"logs":1,"configuration":1}
,"client":{"shut":1,"library":1,"cannot":1,"state":1,"disconnections":1,"logs":1,"operator":1,"consider":1}
,"shut":{"down":1}
,"state":{"restarted":1,"cannot":1,"memory":1}
,"restarted":{"terracotta":1}
,"library":{"runs":1}
,"runs":{"application":1}
,"often":{"involved":1}
,"involved":{"operations":1}
,"operations":{"application":1,"interrupted":1}
,"necessarily":{"aware":1}
,"aware":{"operations":1}
,"interrupted":{"something":1}
,"something":{"terracotta":1}
,"cannot":{"anticipate":1,"handle":1}
,"anticipate":{"interrupting":1}
,"interrupting":{"clustered":1}
,"effect":{"puts":1}
,"puts":{"client":1}
,"handle":{"diagnose":1}
,"diagnose":{"client":1,"cause":1}
,"disconnections":{"clients":1,"due":1,"continue":1}
,"clients":{"disconnect":1}
,"disconnect":{"regular":1}
,"regular":{"basis":1}
,"basis":{"try":1}
,"try":{"following":1}
,"following":{"diagnose":1,"2011-12-04":1}
,"analyze":{"terracotta":1}
,"logs":{"potential":1,"disconnection":1,"terracotta":1,"contain":1,"configured":1}
,"potential":{"issues":1}
,"issues":{"long":1}
,"server":{"logs":1,"client":1}
,"disconnection":{"information":1,"events":1}
,"information":{"rejections":1}
,"rejections":{"reconnection":1}
,"reconnection":{"attempts":1}
,"attempts":{"client":1}
,"operator":{"events":1}
,"events":{"panel":1,"note":1}
,"panel":{"terracotta":1}
,"management":{"console":1}
,"console":{"disconnection":1}
,"note":{"reason":1}
,"reason":{"disconnections":1}
,"due":{"long":1}
,"inconsistent":{"network":1}
,"consider":{"remedies":1,"configuring":1}
,"remedies":{"suggested":1}
,"suggested":{"section":1}
,"section":{"disconnections":1}
,"continue":{"happen":1}
,"happen":{"consider":1}
,"configuring":{"caches":1}
,"caches":{"nonstop":1,"features":1}
,"nonstop":{"behavior":1}
,"behavior":{"enabling":1}
,"enabling":{"rejoin":1}
,"rejoin":{"detect":1}
,"detect":{"memory":1}
,"memory":{"pressure":1,"usage":1,"free":1,"used":1,"max":1,"disk":1}
,"pressure":{"using":1}
,"using":{"terracotta":1}
,"contain":{"messages":1}
,"messages":{"help":1,"similar":1,"indicate":1}
,"help":{"track":1}
,"usage":{"locations":1,"node":1,"search":1}
,"locations":{"server":1}
,"configured":{"terracotta":1,"restartable":1}
,"configuration":{"file":1}
,"file":{"tc-config.xml":1}
,"tc-config.xml":{"view":1}
,"view":{"state":1}
,"node":{"finding":1,"running":1}
,"finding":{"messages":1}
,"similar":{"following":1}
,"2011-12-04":{"14:47:43,341":1}
,"14:47:43,341":{"[statistics":1}
,"[statistics":{"logger]":1}
,"logger]":{"memory":1}
,"free":{"39.992699":1}
,"39.992699":{"2011-12-04":1}
,"used":{"1560.007301":1}
,"1560.007301":{"2011-12-04":1}
,"max":{"1600.000000":1}
,"1600.000000":{"messages":1}
,"indicate":{"node":1}
,"low":{"memory":1}
,"disk":{"usage":1,"storage":1,"space":1}
,"search":{"fast":1}
,"fast":{"restart":1}
,"restart":{"enabled":1}
,"enabled":{"tsa":1,"sure":1}
,"tsa":{"may":1}
,"may":{"configured":1,"1.5":1}
,"restartable":{"addition":1}
,"addition":{"including":1}
,"including":{"searchable":1}
,"searchable":{"caches":1,"attributes":1}
,"require":{"disk":1}
,"storage":{"enabled":1,"required":1}
,"enough":{"disk":1}
,"space":{"available":1}
,"available":{"depending":1}
,"depending":{"upon":1}
,"upon":{"number":1}
,"number":{"searchable":1}
,"attributes":{"amount":1}
,"amount":{"disk":1,"in-memory":1}
,"required":{"may":1}
,"1.5":{"times":1}
,"times":{"amount":1}
,"in-memory":{"data":1}
}
;Search.control.loadWordPairs(pairs);
