var pairs =
{
"customizing":{"eviction":1}
,"eviction":{"strategy":1}
,"strategy":{"based":1}
,"based":{"upon":1}
,"upon":{"three":1}
,"three":{"types":1,"strategies":1}
,"types":{"evictors":1}
,"evictors":{"three":1}
,"strategies":{"employ":1}
,"employ":{"controlling":1}
,"controlling":{"size":1}
,"size":{"tsa\u0027s":1}
,"tsa\u0027s":{"data":1}
,"data":{"time":1}
,"time":{"idle":1,"live":1,"expired":1}
,"idle":{"(tti)":1}
,"(tti)":{"time":1}
,"live":{"(ttl)":1}
,"(ttl)":{"options":1}
,"options":{"entry":1}
,"entry":{"data":1,"datastorage":1}
,"expired":{"periodic":1}
,"periodic":{"evictor":1}
,"evictor":{"clear":1,"activated":1}
,"clear":{"entry":1}
,"datastorage":{"offheap":1}
,"offheap":{"sizes":1}
,"sizes":{"control":1}
,"control":{"bigmemory":1,"capacity-based":1}
,"bigmemory":{"used":1}
,"used":{"resource-based":1}
,"resource-based":{"evictor":1}
,"activated":{"maxentriesincache":1}
,"maxentriesincache":{"attribute":1}
,"attribute":{"control":1}
,"capacity-based":{"evictor":1}
}
;Search.control.loadWordPairs(pairs);
