var pairs =
{
"recovery":{"recovery":1,"throttle":1}
,"throttle":{"mode":1}
,"mode":{"automatic":1,"operator":1,"resource-driven":1,"clear":1}
,"automatic":{"soon":1}
,"soon":{"background":1}
,"background":{"evictions":1}
,"evictions":{"time":1}
,"time":{"reduce":1}
,"reduce":{"data":1}
,"data":{"within":1,"anticipate":1,"clear":1,"sets":1,"tab":1}
,"within":{"limitations":1}
,"limitations":{"tsa":1}
,"tsa":{"enters":1,"restricted":1}
,"enters":{"restricted":1}
,"restricted":{"mode":1}
,"operator":{"events":1}
,"events":{"logged":1,"programmatic":1}
,"logged":{"tmc":1}
,"tmc":{"user":1,"initiate":1,"programmatically)":1,"click":1}
,"user":{"programmatic":1}
,"programmatic":{"intervention":1,"logic":1}
,"intervention":{"necessary":1}
,"necessary":{"tmc":1}
,"initiate":{"actions":1}
,"actions":{"manually":1,"recommended":1}
,"manually":{"reduce":1}
,"anticipate":{"operator":1}
,"logic":{"respond":1}
,"respond":{"appropriately":1}
,"appropriately":{"following":1}
,"following":{"actions":1}
,"recommended":{"reducing":1}
,"reducing":{"data":1}
,"clear":{"caches":1,"cache":1,"pinned":1}
,"caches":{"(from":1,"tmc":1}
,"(from":{"tmc":1}
,"programmatically)":{"remove":1}
,"remove":{"entries":1}
,"entries":{"data":1}
,"sets":{"programmatically":1}
,"programmatically":{"eviction":1}
,"eviction":{"restricted":1}
,"resource-driven":{"changing":1}
,"changing":{"tti\u002Fttl":1}
,"tti\u002Fttl":{"maximum":1}
,"maximum":{"capacity":1}
,"capacity":{"move":1}
,"move":{"tsa":1}
,"click":{"application":1}
,"application":{"data":1}
,"tab":{"management":1}
,"management":{"sub-tab":1}
,"sub-tab":{"cache":1}
,"cache":{"clickable":1,"note":1}
,"clickable":{"option":1}
,"option":{"clear":1}
,"note":{"caution":1}
,"caution":{"used":1}
,"used":{"considering":1}
,"considering":{"whether":1}
,"whether":{"clear":1}
,"pinned":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
