var pairs =
{
"configuring":{"server":1}
,"server":{"security":1,"array":1,"participating":1,"cluster":1,"authenticated":1}
,"security":{"security":1,"terracotta":1,"cluster":1,"globally":1,"realm":1}
,"terracotta":{"server":1,"configuration":1}
,"array":{"terracotta":1}
,"configuration":{"file":1,"available":1,"example":1}
,"file":{"named":1,"format":1,"jks":1,"(when":1,"authentication\u002Fauthorization":1,"overridden":1}
,"named":{"tc-config.xml":1,"configuration":1}
,"tc-config.xml":{"default":1}
,"default":{"example":1,"false":1,"username":1}
,"example":{"<tc:tc-config":1,"name":1}
,"<tc:tc-config":{"xmlns:tc=\u0022":1}
,"xmlns:tc=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":{"<servers":1}
,"<servers":{"secure=\u0022":1}
,"secure=\u0022":{"true":1}
,"true":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"172.16.254.1":1}
,"172.16.254.1":{"name=\u0022":1}
,"name=\u0022":{"server1":1}
,"server1":{"<security>":1}
,"<security>":{"<ssl>":1,"block":1}
,"<ssl>":{"<certificate>":1}
,"<certificate>":{"jks:server1alias@\u002Fthe\u002Fpath\u002Fkeystore-file.jks":1}
,"jks:server1alias@\u002Fthe\u002Fpath\u002Fkeystore-file.jks":{"<\u002Fcertificate>":1}
,"<\u002Fcertificate>":{"<\u002Fssl>":1}
,"<\u002Fssl>":{"<keychain>":1}
,"<keychain>":{"<url>":1}
,"<url>":{"file:\u002F\u002F\u002F%":1}
,"file:\u002F\u002F\u002F%":{"(user.dir)\u002Fserver1keychain.tkc":1,"(user.dir)\u002Fmy_auth.ini":1}
,"(user.dir)\u002Fserver1keychain.tkc":{"<\u002Furl>":1}
,"<\u002Furl>":{"<\u002Fkeychain>":1,"<user>":1}
,"<\u002Fkeychain>":{"<auth>":1}
,"<auth>":{"<realm>":1}
,"<realm>":{"com.tc.net.core.security.shiroinirealm":1}
,"com.tc.net.core.security.shiroinirealm":{"<\u002Frealm>":1}
,"<\u002Frealm>":{"<url>":1}
,"(user.dir)\u002Fmy_auth.ini":{"<\u002Furl>":1}
,"<user>":{"server1username":1}
,"server1username":{"<\u002Fuser>":1}
,"<\u002Fuser>":{"<\u002Fauth>":1}
,"<\u002Fauth>":{"<\u002Fsecurity>":1}
,"<\u002Fsecurity>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"<\u002Ftc:tc-config>":1}
,"<\u002Ftc:tc-config>":{"every":1}
,"every":{"server":1}
,"participating":{"ssl-based":1}
,"ssl-based":{"secured":1,"security":1}
,"secured":{"cluster":1}
,"cluster":{"<security>":1,"ldap":1,"default":1}
,"block":{"security-related":1}
,"security-related":{"information":1,"elements":1}
,"information":{"encapsulated":1}
,"encapsulated":{"defined":1}
,"defined":{"keystore":1}
,"keystore":{"keychain":1,"file":1,"supported":1}
,"keychain":{".ini":1,"file":1,"realm":1,"usermanagement":1}
,".ini":{"files":1}
,"files":{"named":1,"created":1}
,"available":{"every":1}
,"ldap":{"microsoft":1,"ldap":1,"ldaps":1,"element\u0027s":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"directory":{"configured":1,"ldap":1,"standard":1}
,"configured":{"place":1,"url":1}
,"place":{"file-based":1}
,"file-based":{"authentication":1,"(.ini)":1}
,"authentication":{"authorization":1,"certificate":1}
,"authorization":{"following":1}
,"following":{"table":1}
,"table":{"defines":1}
,"defines":{"security-related":1}
,"elements":{"attributes":1}
,"attributes":{"shown":1}
,"shown":{"configuration":1}
,"name":{"definition":1,"part":1}
,"definition":{"notes":1}
,"notes":{"secure":1}
,"secure":{"attribute":1}
,"attribute":{"<servers>":1}
,"<servers>":{"element":1}
,"element":{"enables":1,"specifying":1}
,"enables":{"ssl":1}
,"ssl":{"security":1}
,"false":{"enables\u002Fdisables":1}
,"enables\u002Fdisables":{"ssl-based":1}
,"globally":{"certificate":1}
,"certificate":{"element":1,"containing":1,"keystore":1}
,"specifying":{"location":1}
,"location":{"server\u0027s":1,"jks:alias@\u002Fpath\u002Fto\u002Fkeystore":1}
,"server\u0027s":{"authentication":1,"credentials":1}
,"containing":{"keystore":1}
,"format":{"certificate-keystore":1}
,"certificate-keystore":{"location":1}
,"jks:alias@\u002Fpath\u002Fto\u002Fkeystore":{"alias":1}
,"alias":{"match":1}
,"match":{"value":1}
,"value":{"used":1,"specified":1}
,"used":{"key":1,"file-based":1}
,"key":{"certificate":1}
,"jks":{"type":1}
,"type":{"keystore":1,"authentication\u002Fauthorization":1}
,"supported":{"url":1}
,"url":{"uri":1,"locating":1}
,"uri":{"keychain":1}
,"(when":{"<keychain>)":1,"<auth>)":1}
,"<keychain>)":{"authentication\u002Fauthorization":1}
,"authentication\u002Fauthorization":{"mechanism":1,"source":1,"scheme":1}
,"mechanism":{"(when":1}
,"<auth>)":{"uris":1}
,"uris":{"passed":1}
,"passed":{"keychain":1}
,"realm":{"class":1,"shiro":1,"determines":1}
,"class":{"specify":1}
,"specify":{"keychain":1}
,"source":{"respectively":1}
,"respectively":{"files":1}
,"created":{"managed":1}
,"managed":{"keychain":1}
,"usermanagement":{"scripts":1}
,"scripts":{"using":1}
,"using":{"microsoft":1}
,"ldaps":{"connection":1}
,"connection":{"specified":1}
,"specified":{"configured":1,"section":1}
,"locating":{"keychain":1}
,"overridden":{"property":1}
,"property":{"com.tc.security":1}
,"com.tc.security":{"keychain.url":1}
,"keychain.url":{"realm":1}
,"shiro":{"security":1}
,"determines":{"type":1}
,"scheme":{"used":1,"user":1}
,"(.ini)":{"microsoft":1}
,"standard":{"ldap":1}
,"element\u0027s":{"value":1}
,"section":{"covering":1}
,"covering":{"setup":1}
,"setup":{"chosen":1}
,"chosen":{"authentication\u002Fauthorization":1}
,"user":{"username":1}
,"username":{"represents":1,"terracotta":1}
,"represents":{"server":1}
,"authenticated":{"servers":1}
,"servers":{"name":1}
,"part":{"server\u0027s":1}
,"credentials":{"default":1}
}
;Search.control.loadWordPairs(pairs);
