var pairs =
{
"data":{"types":1,"type":1}
,"types":{"searchable":1,"explicit":1,"examples":1}
,"searchable":{"using":1}
,"using":{"bigmemory":1}
,"bigmemory":{"sql":1}
,"sql":{"data":1}
,"type":{"attribute":1,"rules":1,"values":1,"int":1,"string":1,"name":1,"double":1}
,"attribute":{"following":1,"clause":1}
,"following":{"boolean":1}
,"boolean":{"byte":1,"date":1}
,"byte":{"char":1}
,"char":{"float":1}
,"float":{"short":1}
,"short":{"long":1}
,"long":{"int":1}
,"int":{"double":1,"select":1}
,"double":{"date":1}
,"date":{"sqldate":1}
,"sqldate":{"string":1,"surrounded":1}
,"string":{"value":1,"types":1,"boolean":1,"select":1}
,"value":{"attribute":1}
,"clause":{"follow":1}
,"follow":{"data":1}
,"rules":{"except":1}
,"except":{"integer":1}
,"integer":{"string":1}
,"explicit":{"cast":1}
,"cast":{"indicate":1}
,"indicate":{"data":1,"primitive":1}
,"values":{"string":1}
,"surrounded":{"single":1}
,"single":{"quotes":1}
,"quotes":{"data":1}
,"examples":{"select":1}
,"select":{"*from":1}
,"*from":{"person":1}
,"person":{"age":1,"name":1,"gender":1,"ismale":1,"birthdate":1}
,"age":{"=11":1,"=(byte)":1,"=(short)":1,"=(long)":1,"=(double)":1}
,"=11":{"\u002F\u002Fage":1}
,"\u002F\u002Fage":{"type":1}
,"name":{"=\u0027mary":1,"case-sensitive":1}
,"=\u0027mary":{"\u002F\u002Fname":1}
,"\u002F\u002Fname":{"type":1}
,"gender":{"=(char)":1}
,"=(char)":{"select":1}
,"ismale":{"=(bool)":1}
,"=(bool)":{"\u0027true":1}
,"\u0027true":{"select":1}
,"=(byte)":{"select":1}
,"=(short)":{"select":1}
,"=(long)":{"select":1}
,"=(double)":{"11.1":1}
,"11.1":{"select":1}
,"birthdate":{"=(date)":1}
,"=(date)":{"2003-01-10t14:25:22":1}
,"2003-01-10t14:25:22":{"data":1}
,"case-sensitive":{"example":1}
,"example":{"lowercase":1}
,"lowercase":{"(double)":1}
,"(double)":{"indicate":1}
,"primitive":{"type":1}
}
;Search.control.loadWordPairs(pairs);
