var pairs =
{
"nonstop":{"timeouts":1,"caches":1,"immediatetimeout":1}
,"timeouts":{"behaviors":1}
,"behaviors":{"nonstop":1}
,"caches":{"configured":1,"without":1,"terracotta":1}
,"configured":{"following":1}
,"following":{"attributes":1,"table":1}
,"attributes":{"enabled":1,"ever":1}
,"enabled":{"enables":1,"parameter":1}
,"enables":{"true":1}
,"true":{"default)":1,"disables":1}
,"default)":{"disables":1,"immediate":1}
,"disables":{"false":1}
,"false":{"ability":1,"default)":1}
,"ability":{"cache":1}
,"cache":{"execute":1,"operation":1,"operations":1,"data":1}
,"execute":{"certain":1}
,"certain":{"actions":1}
,"actions":{"terracotta":1}
,"terracotta":{"client":1,"clustering":1}
,"client":{"disconnects":1,"detects":1}
,"disconnects":{"attribute":1}
,"attribute":{"optional":1,"type":1,"values":1}
,"optional":{"enabling":1}
,"enabling":{"nonstop":1}
,"immediatetimeout":{"enables":1}
,"immediate":{"timeout":1}
,"timeout":{"response":1,"occurs":1,"occurs)":1}
,"response":{"terracotta":1,"timeout":1,"<timeoutbehavior>":1}
,"detects":{"network":1}
,"network":{"interruption":1}
,"interruption":{"(the":1}
,"(the":{"node":1}
,"node":{"disconnected":1}
,"disconnected":{"cluster)":1}
,"cluster)":{"enabled":1}
,"parameter":{"overrides":1}
,"overrides":{"timeoutmillis":1}
,"timeoutmillis":{"option":1,"specifies":1}
,"option":{"timeoutbehavior":1,"allow":1}
,"timeoutbehavior":{"effect":1,"searchtimeoutmillis":1,"<nonstop>":1}
,"effect":{"immediately":1}
,"immediately":{"timeoutmillis":1}
,"specifies":{"number":1}
,"number":{"milliseconds":1}
,"milliseconds":{"application":1}
,"application":{"waits":1,"continue":1}
,"waits":{"cache":1,"search":1}
,"operation":{"return":1}
,"return":{"timing":1,"null":1}
,"timing":{"default":1}
,"default":{"value":1}
,"value":{"30000":1,"behavior":1}
,"30000":{"(thirty":1}
,"(thirty":{"seconds)":1}
,"seconds)":{"behavior":1}
,"behavior":{"timeout":1,"exception":1}
,"occurs":{"determined":1,"(timeoutmillis":1}
,"determined":{"timeoutbehavior":1}
,"searchtimeoutmillis":{"specifies":1}
,"search":{"operations":1}
,"operations":{"return":1,"hibernate":1,"caches":1}
,"<nonstop>":{"self-closing":1}
,"self-closing":{"sub-element":1}
,"sub-element":{"<timeoutbehavior>":1,"determines":1}
,"<timeoutbehavior>":{"sub-element":1,"attribute":1}
,"determines":{"response":1}
,"(timeoutmillis":{"expires":1}
,"expires":{"immediate":1}
,"occurs)":{"response":1}
,"type":{"attribute":1}
,"values":{"listed":1}
,"listed":{"following":1}
,"table":{"<<ffc-when":1}
,"<<ffc-when":{"attributes":1}
,"ever":{"apply":1}
,"apply":{"caches":1}
,"without":{"clustering":1,"terracotta":1}
,"clustering":{"possibility":1,"allow":1,"throw":1}
,"possibility":{"mentioned":1}
,"mentioned":{"several":1}
,"several":{"times":1}
,"times":{"table.>>":1}
,"table.>>":{"value":1}
,"exception":{"(default)":1,"nonstopcacheexception":1,"localreadsandexceptiononwrite":1}
,"(default)":{"throw":1}
,"throw":{"nonstopcacheexception":1,"exception":1}
,"nonstopcacheexception":{"information":1,"thrown":1,"write":1}
,"information":{"exception":1}
,"thrown":{"noop":1}
,"noop":{"return":1}
,"null":{"gets":1}
,"gets":{"ignore":1}
,"ignore":{"cache":1}
,"hibernate":{"users":1}
,"users":{"may":1}
,"may":{"want":1}
,"want":{"option":1}
,"allow":{"application":1,"inconsistent":1}
,"continue":{"alternative":1}
,"alternative":{"data":1}
,"data":{"source":1,"ignore":1,"throw":1}
,"source":{"localreads":1}
,"localreads":{"caches":1}
,"inconsistent":{"reads":1}
,"reads":{"cache":1}
,"localreadsandexceptiononwrite":{"caches":1}
,"write":{"operations":1}
}
;Search.control.loadWordPairs(pairs);
