var pairs =
{
"cluster":{"topology":1,"following":1,"information":1,"including":1,"nodes":1,"identifier":1}
,"topology":{"interface":1,"information":1}
,"interface":{"net.sf.ehcache.cluster.cachecluster":1,"net.sf.ehcache.cluster.clusternode":1,"clusternode":1}
,"net.sf.ehcache.cluster.cachecluster":{"provides":1}
,"provides":{"methods":1}
,"methods":{"obtaining":1,"available":1}
,"obtaining":{"topology":1,"information":1}
,"information":{"terracotta":1,"currently":1,"collection":1,"nodes":1,"specific":1}
,"terracotta":{"cluster":1,"scheme":1}
,"following":{"methods":1}
,"available":{"string":1}
,"string":{"getscheme":1}
,"getscheme":{"returns":1}
,"returns":{"scheme":1,"information":1,"true":1}
,"scheme":{"name":1,"supported":1}
,"name":{"cluster":1,"used":1,"node":1}
,"currently":{"terracotta":1}
,"supported":{"scheme":1}
,"used":{"cachemanager.getcluster":1}
,"cachemanager.getcluster":{"return":1}
,"return":{"cluster":1}
,"collection":{"<clusternode>":1}
,"<clusternode>":{"getnodes":1}
,"getnodes":{"returns":1}
,"nodes":{"cluster":1,"public":1}
,"including":{"hostname":1}
,"hostname":{"address":1}
,"address":{"boolean":1,"node":1}
,"boolean":{"addtopologylistener":1,"removetopologylistener":1}
,"addtopologylistener":{"(clustertopologylistener":1}
,"(clustertopologylistener":{"listener)":1}
,"listener)":{"adds":1}
,"adds":{"cluster-events":1}
,"cluster-events":{"listener":1}
,"listener":{"returns":1,"already":1}
,"true":{"listener":1}
,"already":{"active":1,"inactive":1}
,"active":{"boolean":1}
,"removetopologylistener":{"(clustertopologylistener)":1}
,"(clustertopologylistener)":{"removes":1}
,"removes":{"cluster-events":1}
,"inactive":{"interface":1}
,"net.sf.ehcache.cluster.clusternode":{"provides":1}
,"specific":{"cluster":1}
,"public":{"interface":1}
,"clusternode":{"{\u002F***get":1}
,"{\u002F***get":{"unique":1}
,"unique":{"(per":1,"per":1}
,"(per":{"cluster)":1}
,"cluster)":{"identifier":1}
,"identifier":{"node":1,"*\u002Fstring":1}
,"node":{"**@return":1,"*\u002Fstring":1}
,"**@return":{"unique":1,"host":1,"address":1}
,"per":{"cluster":1}
,"*\u002Fstring":{"getid":1,"gethostname":1,"getip":1}
,"getid":{"\u002F***get":1}
,"\u002F***get":{"host":1,"address":1}
,"host":{"name":1}
,"gethostname":{"\u002F***get":1}
}
;Search.control.loadWordPairs(pairs);
