var pairs =
{
"adding":{"server":1}
,"server":{"array":1,"connecting":1,"instance":1,"directory":1,"keeps":1,"next":1}
,"array":{"terracotta":1,"array":1,"in-memory":1,"purposes":1,"case":1,"itself":1,"first":1,"(this":1,"previous":1,"output":1,"help":1}
,"terracotta":{"server":1,"license":1,"installation":1,"configuration":1,"element":1}
,"in-memory":{"data":1}
,"data":{"servers":1,"access":1,"enterprise":1,"sets":1,"classes":1,"managed":1,"always":1,"final":1,"element":1,"server":1,"isn\u0027t":1,"dataset.put":1,"\u002F\u002Ffetch":1,"\u002F\u002Fset.)":1,"automatically":1,"gender":1,"memory":1,"persistence":1,"restart":1}
,"servers":{"plug":1}
,"plug":{"seamlessly":1}
,"seamlessly":{"provide":1}
,"provide":{"applications":1}
,"applications":{"high-performance":1,"-->":1}
,"high-performance":{"low":1}
,"low":{"predictable":1}
,"predictable":{"latency":1}
,"latency":{"data":1}
,"access":{"terabytes":1}
,"terabytes":{"in-memory":1}
,"enterprise":{"capabilities":1}
,"capabilities":{"high":1}
,"high":{"availability":1}
,"availability":{"scalability":1}
,"scalability":{"fault":1}
,"fault":{"tolerance":1}
,"tolerance":{"let\u0027s":1}
,"let\u0027s":{"try":1,"create":1}
,"try":{"starting":1}
,"starting":{"terracotta":1}
,"connecting":{"data":1}
,"sets":{"preparation":1,"applications":1}
,"preparation":{"add":1}
,"add":{"valid":1,"following":1,"terracotta":1,"new":1,"easily":1,"data":1}
,"valid":{"terracotta":1}
,"license":{"key":1,"terracotta.org\u002Fdownloads\u002Fbigmemorymax":1}
,"key":{"top":1}
,"top":{"level":1}
,"level":{"terracotta":1}
,"installation":{"directory":1}
,"directory":{"don\u0027t":1,"bigmemory":1}
,"don\u0027t":{"register":1}
,"register":{"license":1}
,"terracotta.org\u002Fdownloads\u002Fbigmemorymax":{"add":1}
,"following":{"jar":1}
,"jar":{"bigmemory-max-4.x.x":1}
,"bigmemory-max-4.x.x":{"download":1}
,"download":{"kit":1}
,"kit":{"classpath":1}
,"classpath":{"apis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-4.x.x.jar":1,"add":1}
,"apis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-4.x.x.jar":{"add":1}
,"configuration":{"configuration":1,"file":1,"specific":1,"retrieved":1,"server":1,"options":1}
,"file":{"(see":1,"create":1,"called":1}
,"(see":{"below)":1}
,"below)":{"sure":1}
,"sure":{"data":1}
,"classes":{"serializable":1}
,"serializable":{"start":1,"{private":1}
,"start":{"terracotta":1}
,"instance":{"create":1,"terminal":1,"already":1}
,"create":{"configuration":1,"new":1,"serverarraytest.java":1,"compile":1,"objects":1}
,"new":{"configuration":1,"cache":1,"data":1}
,"called":{"ehcache-server-array.xml":1,"server-array":1,"serverarraytest":1}
,"ehcache-server-array.xml":{"classpath":1}
,"cache":{"called":1,"causes":1,"manager":1,"dataset":1}
,"server-array":{"(you":1,"<searchable>":1,"\u002F\u002Fcheck":1}
,"(you":{"name":1}
,"name":{"anything":1,"code)":1}
,"anything":{"want":1}
,"want":{"long":1}
,"long":{"correct":1,"serialversionuid":1,"private":1,"final":1,"getid":1}
,"correct":{"name":1}
,"code)":{"<ehcache":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"sampleconfig":1,"hello-world":1,"crud":1,"search":1,"height":1,"weight":1,"bodymassindex":1,"sort":1,"group":1,"gender":1,"bmi":1,"server-array":1}
,"sampleconfig":{"maxbyteslocalheap=\u0022":1}
,"maxbyteslocalheap=\u0022":{"64m":1}
,"64m":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"hello-world":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<cache":1,"<searchattribute":1,"<\u002Fsearchable>":1,"<\u002Fcache>":1,"<\u002Fehcache>":1}
,"crud":{"\u0022\u002F>":1}
,"search":{"<searchable>":1,"attributes":1}
,"<searchable>":{"<searchattribute":1}
,"<searchattribute":{"name=\u0022":1}
,"height":{"\u0022\u002F>":1,"=dataset.getsearchattribute":1,"attribute":1,"bmi":1,"avgheight":1,"private":1,"final":1,"public":1,"*(float)":1,"weight=\u0022":1,"66.0":1,"69.0":1,"65.0":1}
,"weight":{"\u0022\u002F>":1,"private":1,"public":1,"\u002F((float)":1,"lbs":1}
,"bodymassindex":{"<\u002Fsearchable>":1}
,"<\u002Fsearchable>":{"<\u002Fcache>":1,"<!--add":1}
,"<\u002Fcache>":{"<cache":1,"<!--add":1}
,"sort":{"<searchable>":1,"data":1}
,"group":{"<searchable>":1}
,"gender":{"\u0022\u002F>":1,"=dataset.getsearchattribute":1,"attribute":1,"\u002F\u002Fthe":1,"query.includeaggregator":1,"alphabetical":1,"thegender":1,"public":1,"final":1,"female":1,"male":1,"count":1}
,"bmi":{"expression=\u0022":1,"=dataset.getsearchattribute":1,"\u002F\u002Fcreate":1,"gender":1,"avgbmi)":1,"22.242641":1,"23.625288":1,"26.622484":1}
,"expression=\u0022":{"value.getbodymassindex":1}
,"value.getbodymassindex":{"\u0022\u002F>":1}
,"<!--add":{"terracotta":1,"terracottaconfig":1}
,"element":{"cache":1,"specify":1,"person1":1,"(janeausten.getid":1,"(charlesdickens.getid":1,"(janedoe.getid":1,"(alexsmith.getid":1}
,"causes":{"data":1}
,"managed":{"terracotta":1}
,"purposes":{"demonstration":1}
,"demonstration":{"consistency":1}
,"consistency":{"strong":1,"settings":1}
,"strong":{"ensure":1,"\u0022\u002F>":1}
,"ensure":{"data":1}
,"always":{"consistent":1}
,"consistent":{"across":1}
,"across":{"entire":1}
,"entire":{"distributed":1,"data":1}
,"distributed":{"system":1}
,"system":{"consistency":1}
,"settings":{"may":1,"used":1}
,"may":{"suitable":1}
,"suitable":{"different":1}
,"different":{"data":1,"configuration":1}
,"-->":{"<terracotta":1,"<terracottaconfig":1}
,"<terracotta":{"consistency=\u0022":1}
,"consistency=\u0022":{"strong":1}
,"terracottaconfig":{"element":1}
,"specify":{"find":1}
,"find":{"configuration":1,"data":1}
,"specific":{"server":1}
,"case":{"configuration":1}
,"retrieved":{"server":1}
,"itself":{"-->":1}
,"<terracottaconfig":{"url=\u0022":1}
,"url=\u0022":{"localhost:9510":1}
,"localhost:9510":{"\u0022\u002F>":1}
,"<\u002Fehcache>":{"create":1}
,"serverarraytest.java":{"create":1}
,"compile":{"java":1}
,"java":{"class":1}
,"class":{"called":1,"serverarraytest":1,"person":1}
,"serverarraytest":{"import":1,"{public":1,"program":1}
,"import":{"java.io.serializable":1,"java.util.list":1,"net.sf.ehcache.cache":1,"net.sf.ehcache.cachemanager":1,"net.sf.ehcache.element":1,"net.sf.ehcache.search.attribute":1,"net.sf.ehcache.search.direction":1,"net.sf.ehcache.search.query":1,"net.sf.ehcache.search.result":1,"net.sf.ehcache.search.results":1,"net.sf.ehcache.search.aggregator.aggregators":1}
,"java.io.serializable":{"import":1}
,"java.util.list":{"import":1}
,"net.sf.ehcache.cache":{"import":1}
,"net.sf.ehcache.cachemanager":{"import":1}
,"net.sf.ehcache.element":{"import":1}
,"net.sf.ehcache.search.attribute":{"import":1}
,"net.sf.ehcache.search.direction":{"import":1}
,"net.sf.ehcache.search.query":{"import":1}
,"net.sf.ehcache.search.result":{"import":1}
,"net.sf.ehcache.search.results":{"import":1}
,"net.sf.ehcache.search.aggregator.aggregators":{"public":1}
,"public":{"class":1,"static":1,"person":1,"string":1,"int":1,"float":1,"long":1}
,"{public":{"static":1}
,"static":{"void":1,"class":1,"final":1}
,"void":{"main":1}
,"main":{"(final":1}
,"(final":{"string":1,"long":1}
,"string":{"args)":1,"firstname":1,"lastname":1,"gender":1,"getfirstname":1,"getlastname":1,"getgender":1,"tostring":1}
,"args)":{"{\u002F\u002Fcreate":1}
,"{\u002F\u002Fcreate":{"cache":1}
,"manager":{"using":1}
,"using":{"factory":1,"bigmemory":1}
,"factory":{"method":1}
,"method":{"final":1}
,"final":{"cachemanager":1,"cache":1,"person":1,"query":1,"results":1,"long":1,"string":1,"int":1}
,"cachemanager":{"cachemanager":1,"=cachemanager.newinstance":1}
,"=cachemanager.newinstance":{"(group.class":1}
,"(group.class":{".getresource":1}
,".getresource":{"(\u0022\u002Fehcache-server-array.xml":1}
,"(\u0022\u002Fehcache-server-array.xml":{"\u0022))":1}
,"\u0022))":{"\u002F\u002Fretrieve":1}
,"\u002F\u002Fretrieve":{"sort":1}
,"dataset":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"server-array":1}
,"\u002F\u002Fcheck":{"there\u0027s":1}
,"there\u0027s":{"data":1}
,"person1":{"=dataset.get":1}
,"=dataset.get":{"(1l)":1}
,"(1l)":{"(person1":1}
,"(person1":{"==null)":1}
,"==null)":{"{system.out.println":1}
,"{system.out.println":{"didn\u0027t":1,"found":1}
,"didn\u0027t":{"find":1}
,"first":{"execution":1,"time":1}
,"execution":{"\u002F\u002Fthe":1,"need":1,"gender":1}
,"\u002F\u002Fthe":{"data":1,"results":1}
,"isn\u0027t":{"server":1}
,"(this":{"first":1,"query":1}
,"time":{"\u002F\u002Fran":1,"run":1}
,"\u002F\u002Fran":{"program)":1}
,"program)":{"let\u0027s":1}
,"objects":{"final":1,"data":1}
,"person":{"janeausten":1,"jane":1,"charlesdickens":1,"charles":1,"janedoe":1,"alexsmith":1,"alex":1,"implements":1,"(final":1}
,"janeausten":{"=new":1}
,"=new":{"person":1}
,"jane":{"austen":1,"doe":1}
,"austen":{"female":1}
,"female":{"*12":1,"count":1}
,"*12":{"130)":1,"160)":1,"145)":1}
,"130)":{"final":1}
,"charlesdickens":{"=new":1}
,"charles":{"dickens":1}
,"dickens":{"male":1}
,"male":{"*12":1,"count":1}
,"160)":{"final":1,"\u002F\u002Fput":1}
,"janedoe":{"=new":1}
,"doe":{"female":1}
,"145)":{"final":1}
,"alexsmith":{"=new":1}
,"alex":{"smith":1}
,"smith":{"*12":1}
,"\u002F\u002Fput":{"objects":1}
,"dataset.put":{"(new":1}
,"(new":{"element":1}
,"(janeausten.getid":{"janeausten))":1}
,"janeausten))":{"dataset.put":1}
,"(charlesdickens.getid":{"charlesdickens))":1}
,"charlesdickens))":{"dataset.put":1}
,"(janedoe.getid":{"janedoe))":1}
,"janedoe))":{"dataset.put":1}
,"(alexsmith.getid":{"alexsmith))":1}
,"alexsmith))":{"else":1}
,"else":{"{system.out.println":1}
,"found":{"data":1}
,"previous":{"execution":1}
,"need":{"create":1}
,"\u002F\u002Ffetch":{"search":1}
,"attributes":{"we\u0027ll":1}
,"we\u0027ll":{"query":1}
,"query":{"fetching":1,"object":1,"designed":1,"query":1,"=dataset.createquery":1,"final":1}
,"fetching":{"\u002F\u002Four":1}
,"\u002F\u002Four":{"results":1}
,"results":{"attribute":1,"query.includeaggregator":1,"back":1,"results":1,"=query.execute":1,"(result":1}
,"attribute":{"<integer>":1,"<string>":1,"<float>":1,"perform":1}
,"<integer>":{"height":1}
,"=dataset.getsearchattribute":{"height":1,"gender":1,"bmi":1}
,"<string>":{"gender":1}
,"<float>":{"bmi":1}
,"\u002F\u002Fcreate":{"query":1}
,"object":{"(this":1}
,"designed":{"select":1}
,"select":{"entire":1}
,"\u002F\u002Fset.)":{"final":1}
,"=dataset.createquery":{".addcriteria":1}
,".addcriteria":{"(height.gt":1}
,"(height.gt":{"*12))":1}
,"*12))":{"\u002F\u002Fgroup":1}
,"\u002F\u002Fgroup":{"gender":1}
,"perform":{"aggregations":1}
,"aggregations":{"\u002F\u002Fgender":1}
,"\u002F\u002Fgender":{"query.addgroupby":1}
,"query.addgroupby":{"(gender)":1}
,"(gender)":{"query.includeattribute":1,"\u002F\u002Finclude":1,"list":1}
,"query.includeattribute":{"(gender)":1}
,"\u002F\u002Finclude":{"aggregation":1,"count":1}
,"aggregation":{"average":1}
,"average":{"height":1,"bmi":1}
,"query.includeaggregator":{"(aggregators.average":1,"(aggregators.count":1}
,"(aggregators.average":{"(height))":1,"(bmi))":1}
,"(height))":{"query.includeaggregator":1}
,"(bmi))":{"\u002F\u002Finclude":1}
,"count":{"members":1,"=(integer)":1,"count":1,"average":1}
,"members":{"gender":1}
,"(aggregators.count":{"())":1}
,"())":{"\u002F\u002Fmake":1,"{string":1}
,"\u002F\u002Fmake":{"results":1}
,"back":{"sorted":1}
,"sorted":{"gender":1}
,"alphabetical":{"order":1}
,"order":{"query.addorderby":1}
,"query.addorderby":{"(gender":1}
,"(gender":{"direction.ascending)":1}
,"direction.ascending)":{"\u002F\u002Fexecute":1}
,"\u002F\u002Fexecute":{"query":1}
,"=query.execute":{"\u002F\u002Fprint":1}
,"\u002F\u002Fprint":{"results":1}
,"(result":{"result":1}
,"result":{"results.all":1}
,"results.all":{"())":1}
,"{string":{"thegender":1}
,"thegender":{"=result.getattribute":1,"count":1}
,"=result.getattribute":{"(gender)":1}
,"list":{"<object>":1}
,"<object>":{"aggregatorresults":1}
,"aggregatorresults":{"=result.getaggregatorresults":1}
,"=result.getaggregatorresults":{"float":1}
,"float":{"avgheight":1,"avgbmi":1,"getbodymassindex":1}
,"avgheight":{"=(float)":1,"average":1}
,"=(float)":{"aggregatorresults.get":1}
,"aggregatorresults.get":{"(0)":1,"(1)":1,"(2)":1}
,"(0)":{"float":1}
,"avgbmi":{"=(float)":1}
,"(1)":{"integer":1}
,"integer":{"count":1}
,"=(integer)":{"aggregatorresults.get":1}
,"(2)":{"system.out.println":1}
,"system.out.println":{"gender":1}
,"avgbmi)":{"public":1}
,"implements":{"serializable":1}
,"{private":{"static":1}
,"serialversionuid":{"=1l":1}
,"=1l":{"private":1}
,"private":{"final":1,"string":1}
,"firstname":{"private":1,"final":1,"public":1,"lastname=\u0022":1}
,"lastname":{"private":1,"final":1,"public":1,"height=\u0022":1}
,"int":{"height":1,"weight":1,"weight)":1,"getheight":1,"getweight":1}
,"weight)":{"{this.id":1}
,"{this.id":{"=id":1}
,"=id":{"this.firstname":1}
,"this.firstname":{"=firstname":1}
,"=firstname":{"this.lastname":1}
,"this.lastname":{"=lastname":1}
,"=lastname":{"this.gender":1}
,"this.gender":{"=gender":1}
,"=gender":{"this.height":1}
,"this.height":{"=height":1}
,"=height":{"this.weight":1}
,"this.weight":{"=weight":1}
,"=weight":{"public":1}
,"getfirstname":{"{return":1}
,"{return":{"firstname":1,"lastname":1,"gender":1,"height":1,"weight":1,"((float)":1,"public":1,"[id=\u0022":1}
,"getlastname":{"{return":1}
,"getgender":{"{return":1}
,"getheight":{"{return":1}
,"getweight":{"{return":1}
,"getbodymassindex":{"{return":1,"start":1}
,"((float)":{"weight":1}
,"\u002F((float)":{"height":1}
,"*(float)":{"height))":1}
,"height))":{"*703":1}
,"*703":{"public":1}
,"getid":{"{return":1}
,"tostring":{"{return":1}
,"[id=\u0022":{"firstname=\u0022":1}
,"firstname=\u0022":{"firstname":1}
,"lastname=\u0022":{"lastname":1}
,"height=\u0022":{"height":1}
,"weight=\u0022":{"weight":1}
,"lbs":{"bmi=\u0022":1}
,"bmi=\u0022":{"getbodymassindex":1}
,"terminal":{"server":1,"data":1}
,"bigmemory":{"max":1}
,"max":{"distribution":1,"full":1}
,"distribution":{"run":1}
,"run":{"start-tc-server":1,"serverarraytest":1}
,"start-tc-server":{"command":1}
,"command":{"\u002Fpath\u002Fto\u002Fbigmemory-max-4.x.x\u002Fserver":1}
,"\u002Fpath\u002Fto\u002Fbigmemory-max-4.x.x\u002Fserver":{".\u002Fbin\u002Fstart-tc-server.sh":1}
,".\u002Fbin\u002Fstart-tc-server.sh":{"execute":1}
,"execute":{"first":1}
,"program":{"terminal":1,"again":1,"next":1}
,"output":{"didn\u0027t":1,"found":1}
,"66.0":{"average":1}
,"22.242641":{"gender":1}
,"69.0":{"average":1}
,"23.625288":{"gender":1}
,"65.0":{"average":1}
,"26.622484":{"run":1,"default":1}
,"again":{"(without":1}
,"(without":{"restarting":1}
,"restarting":{"terracotta":1}
,"already":{"running)":1}
,"running)":{"data":1}
,"automatically":{"retrieved":1}
,"default":{"configuration":1}
,"keeps":{"data":1}
,"memory":{"(though":1}
,"(though":{"add":1}
,"easily":{"add":1}
,"persistence":{"fast":1}
,"fast":{"restartable":1}
,"restartable":{"store":1}
,"store":{"configuration)":1}
,"configuration)":{"clear":1}
,"clear":{"data":1}
,"restart":{"server":1}
,"next":{"run":1,"steps":1}
,"steps":{"just":1}
,"just":{"short":1}
,"short":{"example":1}
,"example":{"using":1}
,"full":{"power":1}
,"power":{"server":1}
,"help":{"started":1}
,"started":{"keep":1,"encourage":1}
,"keep":{"mind":1}
,"mind":{"settings":1}
,"used":{"chosen":1}
,"chosen":{"easy":1}
,"easy":{"possible":1}
,"possible":{"started":1}
,"encourage":{"read":1}
,"read":{"rest":1}
,"rest":{"documentation":1}
,"documentation":{"experiment":1}
,"experiment":{"different":1}
,"options":{"features":1}
,"features":{"deployment":1}
,"deployment":{"topologies":1}
,"topologies":{"available":1}
,"available":{"best":1}
,"best":{"meet":1}
,"meet":{"application\u0027s":1}
,"application\u0027s":{"performance":1}
,"performance":{"scale":1}
,"scale":{"needs":1}
}
;Search.control.loadWordPairs(pairs);
