var pairs =
{
"inline":{"refresh":1}
,"refresh":{"ahead":1,"allows":1,"entries":1,"inline":1,"requests":1,"work":1,"operations":1,"due":1,"refresh":1,"reload":1,"time":1,"entry":1}
,"ahead":{"inline":1,"configured":1,"ttl":1}
,"allows":{"caches":1}
,"caches":{"automatically":1}
,"automatically":{"refresh":1}
,"entries":{"based":1,"whose":1,"refresh":1}
,"based":{"timer":1,"time-to-live":1}
,"timer":{"entries":1,"reset":1}
,"whose":{"age":1}
,"age":{"reaches":1}
,"reaches":{"configured":1}
,"configured":{"time":1,"per":1,"refresh":1}
,"time":{"limit":1}
,"limit":{"accessed":1,"exceeded":1,"(ttr)":1,"ttl":1}
,"accessed":{"reloaded":1,"instead":1}
,"reloaded":{"cacheloader":1,"ahead":1}
,"cacheloader":{"methods":1,"implementing":1,"configuring":1}
,"methods":{"information":1}
,"information":{"cacheloader":1,"using":1}
,"implementing":{"cacheloader":1,"refresh-ahead":1}
,"configuring":{"inline":1}
,"per":{"cache":1}
,"cache":{"using":1,"decorator":1,"decorators":1,"cache\u0027s":1,"refreshed":1,"loaders":1,"ttr":1}
,"using":{"cache":1}
,"decorator":{"information":1,"left":1,"accessed":1,"multiple":1}
,"decorators":{"cache":1,"<cache":1}
,"<cache":{"<cacheloaderfactory":1}
,"<cacheloaderfactory":{"class=\u0022":1}
,"class=\u0022":{"com.company.my.concretecacheloaderfactory":1,"net.sf.ehcache.constructs.refreshahead":1}
,"com.company.my.concretecacheloaderfactory":{"properties=\u0022":1}
,"properties=\u0022":{"some_property=1":1,"name=mycacherefresher":1}
,"some_property=1":{"some_other_property=2":1}
,"some_other_property=2":{"<cachedecorator":1}
,"<cachedecorator":{"class=\u0022":1}
,"net.sf.ehcache.constructs.refreshahead":{".refreshaheadcachefactory":1}
,".refreshaheadcachefactory":{"properties=\u0022":1}
,"name=mycacherefresher":{"timetorefreshseconds=200":1}
,"timetorefreshseconds=200":{"batchsize=10":1}
,"batchsize=10":{"numberofthreads=4":1}
,"numberofthreads=4":{"maximumbacklogitems=100":1}
,"maximumbacklogitems=100":{"evictonloadmiss=true":1}
,"evictonloadmiss=true":{"<\u002Fcachedecorator>":1}
,"<\u002Fcachedecorator>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"cache-decorator":1}
,"cache-decorator":{"class":1}
,"class":{"required":1}
,"required":{"implementing":1,"following":1,"number":1,"maximum":1}
,"refresh-ahead":{"mechanism":1}
,"mechanism":{"note":1}
,"note":{"inline-refresh":1}
,"inline-refresh":{"configuration":1}
,"configuration":{"properties":1}
,"properties":{"optional":1,"property":1}
,"optional":{"unless":1}
,"unless":{"marked":1,"access":1}
,"marked":{"required":1}
,"following":{"table":1}
,"table":{"describes":1}
,"describes":{"properties":1}
,"property":{"definition":1}
,"definition":{"default":1}
,"default":{"value":1}
,"value":{"name":1,"100":1,"least":1}
,"name":{"name":1,"used":1,"referenced":1}
,"used":{"identify":1}
,"identify":{"cache":1}
,"left":{"null":1}
,"null":{"cache":1}
,"instead":{"underlying":1}
,"underlying":{"cache":1}
,"cache\u0027s":{"name":1}
,"referenced":{"n\u002Fa":1}
,"n\u002Fa":{"timetorefreshseconds":1,"maximumbacklogitems":1,"batchsize":1}
,"timetorefreshseconds":{"required":1,"works":1,"value":1}
,"number":{"seconds":1,"refresh":1,"threads":1}
,"seconds":{"entry":1,"ttl":1,"tti":1,"triggers":1}
,"entry":{"exist":1,"operation":1,"occurs":1,"assumes":1,"reloaded":1}
,"exist":{"cache":1}
,"refreshed":{"(reloaded)":1,"n\u002Fa":1}
,"(reloaded)":{"access":1}
,"access":{"expired":1,"effect":1,"occurs":1,"entry":1}
,"expired":{"items":1,"based":1}
,"items":{"evicted":1,"dropped":1}
,"evicted":{"cannot":1,"even":1}
,"cannot":{"refreshed":1}
,"maximumbacklogitems":{"required":1}
,"maximum":{"number":1}
,"requests":{"allowed":1,"queued":1,"batched":1,"cost":1}
,"allowed":{"refresh":1}
,"work":{"queue":1}
,"queue":{"once":1,"prevent":1}
,"once":{"limit":1}
,"exceeded":{"items":1,"n\u002Fa":1}
,"dropped":{"queue":1}
,"prevent":{"potentially":1}
,"potentially":{"overtaxing":1}
,"overtaxing":{"resources":1}
,"resources":{"refresh":1}
,"queued":{"faster":1}
,"faster":{"cleared":1}
,"cleared":{"limit":1}
,"batchsize":{"maximum":1}
,"batched":{"processing":1}
,"processing":{"thread":1,"requests":1}
,"thread":{"frequent":1}
,"frequent":{"processing":1}
,"cost":{"performance":1}
,"performance":{"lower":1}
,"lower":{"value":1}
,"100":{"numberofthreads":1}
,"numberofthreads":{"number":1}
,"threads":{"background":1}
,"background":{"refresh":1}
,"operations":{"decorator":1,"occur":1}
,"multiple":{"cache":1}
,"loaders":{"configured":1}
,"occur":{"turn":1}
,"turn":{"evictonloadmiss":1}
,"evictonloadmiss":{"boolean":1}
,"boolean":{"force":1}
,"force":{"immediate":1}
,"immediate":{"eviction":1}
,"eviction":{"reload":1,"takes":1}
,"reload":{"miss":1,"operation":1}
,"miss":{"(true)":1}
,"(true)":{"evict":1}
,"evict":{"normal":1}
,"normal":{"eviction":1}
,"takes":{"effect":1}
,"effect":{"(false)":1,"greater":1}
,"(false)":{"true":1}
,"true":{"entries":1}
,"due":{"failure":1}
,"failure":{"reload":1}
,"operation":{"(all":1,"triggers":1,"resets":1}
,"(all":{"cacheloaders":1}
,"cacheloaders":{"fail)":1}
,"fail)":{"evicted":1}
,"even":{"expired":1}
,"time-to-live":{"time-to-idle":1,"(ttl)":1}
,"time-to-idle":{"settings":1,"(tti)":1}
,"settings":{"false":1}
,"false":{"timetorefreshseconds":1}
,"works":{"expiration":1}
,"expiration":{"timetorefreshseconds":1}
,"least":{"old":1}
,"old":{"entry":1}
,"triggers":{"automatic":1}
,"automatic":{"refresh":1}
,"resets":{"entry\u0027s":1}
,"entry\u0027s":{"time-to-live":1}
,"(ttl)":{"countdown":1}
,"countdown":{"time-to-idle":1}
,"(tti)":{"setting":1}
,"setting":{"reset":1}
,"reset":{"upon":1}
,"upon":{"access":1}
,"greater":{"refresh":1}
,"(ttr)":{"unless":1}
,"occurs":{"example":1,"seconds":1}
,"example":{"cache":1}
,"ttr":{"seconds":1}
,"ttl":{"seconds":1,"limit":1,"timer":1}
,"tti":{"(infinite":1}
,"(infinite":{"idle":1}
,"idle":{"time)":1}
,"time)":{"access":1}
,"assumes":{"entry":1}
}
;Search.control.loadWordPairs(pairs);
