var pairs =
{
"scaling":{"terracotta":1}
,"terracotta":{"server":1,"cluster":1,"configuration":1,"clients":1}
,"server":{"array":1,"instances":1,"instance":1,"mirror":1,"rest":1,"election":1,"elected":1,"servers":1,"failed":1}
,"array":{"persistence":1,"mirror":1}
,"persistence":{"failover":1}
,"failover":{"scale":1}
,"scale":{"capacity":1}
,"capacity":{"requirements":1}
,"requirements":{"exceed":1}
,"exceed":{"capabilities":1}
,"capabilities":{"two-server":1}
,"two-server":{"active-mirror":1}
,"active-mirror":{"setup":1}
,"setup":{"expand":1,"(see":1}
,"expand":{"terracotta":1}
,"cluster":{"using":1,"configured":1,"terracotta":1,"designed":1,"begin":1,"rest":1,"mirror":1,"high":1,"failure":1,"stops":1,"cannot":1,"restarted":1}
,"using":{"mirror-groups":1,"mirror":1}
,"mirror-groups":{"configuration":1}
,"configuration":{"using":1,"file":1,"four":1,"allows":1}
,"mirror":{"groups":1,"server1":1,"server3":1,"group":1,"group\u0027s":1,"mirror":1,"cannot":1,"takes":1}
,"groups":{"multiple":1,"specified":1,"work":1,"group":1}
,"multiple":{"coordinated":1,"active":1}
,"coordinated":{"active":1}
,"active":{"terracotta":1,"servers":1,"groupa":1,"groupb":1,"once":1,"server":1,"mirror":1,"clients":1,"(active-coordinator":1,"within":1}
,"instances":{"adds":1,"following":1,"server":1,"mirror":1,"cluster":1,"become":1}
,"adds":{"scalability":1}
,"scalability":{"terracotta":1}
,"specified":{"<servers>":1,"seconds":1}
,"<servers>":{"section":1,"<mirror-group":1,"may":1,"work":1,"mirror":1}
,"section":{"terracotta":1}
,"file":{"mirror":1,"shows":1}
,"work":{"assigning":1,"managing":1,"without":1,"together":1,"load":1}
,"assigning":{"group":1}
,"group":{"memberships":1,"participate":1,"elected":1,"active":1,"fails":1,"-under":1,"configurations":1,"stripe":1}
,"memberships":{"terracotta":1}
,"following":{"snippet":1}
,"snippet":{"terracotta":1}
,"shows":{"mirror-group":1}
,"mirror-group":{"configuration":1,"becomes":1}
,"four":{"servers":1}
,"servers":{"<servers>":1,"mirror":1,"cast":1,"taken":1,"groupa":1,"groupb":1}
,"<mirror-group":{"election-time=\u0022":1}
,"election-time=\u0022":{"group-name=\u0022":1}
,"group-name=\u0022":{"groupa":1,"groupb":1}
,"groupa":{"<server":1,"server2":1,"seconds":1}
,"<server":{"name=\u0022":1}
,"name=\u0022":{"server1":1,"server2":1,"server3":1,"server4":1}
,"server1":{"<\u002Fserver>":1,"elected":1,"server3":1}
,"<\u002Fserver>":{"<server":1,"<\u002Fmirror-group>":1}
,"server2":{"<\u002Fserver>":1,"becomes":1}
,"<\u002Fmirror-group>":{"<mirror-group":1,"<restartable":1}
,"groupb":{"<server":1,"server4":1,"seconds":1}
,"server3":{"<\u002Fserver>":1,"elected":1,"automatically":1}
,"server4":{"<\u002Fserver>":1,"becomes":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"example":1}
,"example":{"cluster":1,"server":1,"servers":1}
,"configured":{"two":1}
,"two":{"active":1}
,"elected":{"active":1,"servers":1}
,"becomes":{"mirror":1,"active":1}
,"automatically":{"coordinate":1}
,"coordinate":{"work":1}
,"managing":{"terracotta":1,"cluster":1}
,"clients":{"shared":1,"continue":1}
,"shared":{"data":1}
,"data":{"across":1,"directory":1}
,"across":{"cluster":1}
,"designed":{"multiple":1}
,"participate":{"election":1}
,"election":{"choose":1,"takes":1,"time":1}
,"choose":{"active":1}
,"once":{"every":1}
,"every":{"mirror":1}
,"instance":{"active":1,"mirror":1,"started":1,"present":1,"becoming":1,"during":1,"running":1}
,"begin":{"cooperatively":1}
,"cooperatively":{"managing":1}
,"rest":{"server":1,"mirrors":1}
,"become":{"mirrors":1,"active":1}
,"mirrors":{"active":1,"create":1}
,"fails":{"new":1,"taken":1,"server":1}
,"new":{"election":1,"active":1}
,"takes":{"place":1,"data":1,"becomes":1}
,"place":{"determine":1}
,"determine":{"mirror":1}
,"group\u0027s":{"new":1}
,"continue":{"work":1}
,"without":{"regard":1}
,"regard":{"failure":1}
,"failure":{"server":1,"until":1,"active":1}
,"-under":{"<servers>":1}
,"may":{"either":1}
,"either":{"<server>":1}
,"<server>":{"<mirror-group>":1,"configurations":1}
,"<mirror-group>":{"configurations":1,"configuration":1}
,"configurations":{"<server>":1,"directly":1,"include":1,"terracotta":1}
,"directly":{"<servers>":1}
,"together":{"mirror":1}
,"create":{"stripe":1}
,"stripe":{"<mirror-group>":1,"behaves":1,"active":1,"cluster":1,"entire":1,"fails":1}
,"include":{"<server>":1}
,"behaves":{"similar":1}
,"similar":{"active-mirror":1}
,"(see":{"terracotta":1}
,"high":{"availability":1}
,"availability":{"example":1}
,"started":{"stripe":1}
,"present":{"synchronizes":1}
,"synchronizes":{"state":1}
,"state":{"active":1}
,"becoming":{"mirror":1}
,"cannot":{"become":1,"survive":1}
,"during":{"failure":1}
,"until":{"fully":1,"mirror":1}
,"fully":{"synchronized":1}
,"synchronized":{"active":1}
,"running":{"restartable":1}
,"restartable":{"mode":1}
,"mode":{"down":1}
,"down":{"mirror":1,"cluster":1}
,"directory":{"cleared":1}
,"cleared":{"bringing":1}
,"bringing":{"back":1}
,"back":{"crashed":1}
,"crashed":{"server":1}
,"time":{"<mirror-group>":1,"window":1}
,"allows":{"declare":1}
,"declare":{"election":1}
,"window":{"active":1,"value":1,"above":1,"(based":1}
,"cast":{"vote":1}
,"vote":{"within":1}
,"within":{"window":1,"allowed":1}
,"value":{"specified":1}
,"seconds":{"default":1,"network":1,"elect":1,"stripe":1}
,"default":{"seconds":1}
,"network":{"latency":1}
,"latency":{"work":1}
,"load":{"servers":1}
,"taken":{"consideration":1,"down":1}
,"consideration":{"choosing":1}
,"choosing":{"appropriate":1}
,"appropriate":{"window":1}
,"above":{"example":1}
,"elect":{"active":1}
,"stops":{"until":1}
,"(active-coordinator":{"status)":1}
,"status)":{"however":1}
,"however":{"cluster":1}
,"survive":{"loss":1}
,"loss":{"entire":1}
,"entire":{"stripe":1,"cluster":1}
,"failed":{"mirror-group":1}
,"allowed":{"window":1}
,"(based":{"election-time":1}
,"election-time":{"setting)":1}
,"setting)":{"entire":1}
}
;Search.control.loadWordPairs(pairs);
