var pairs =
{
"deployment":{"configuration":1}
,"configuration":{"fully":1,"relies":1,"switch":1,"test":1,"simple":1}
,"fully":{"redundant":1,"functioning":1}
,"redundant":{"deployment":1,"description":1,"network":1,"gateways":1}
,"description":{"fully":1,"http:\u002F\u002Fwww.linuxfoundation.org\u002Fcollaborate\u002Fworkgroups\u002Fnetworking\u002Fbonding":1}
,"network":{"configuration":1,"paths":1,"link":1,"interfaces":1,"following":1,"failures":1,"configured":1,"network":1,"testing":1,"interruption":1,"links":1,"outage":1}
,"relies":{"failover":1}
,"failover":{"capabilities":1,"standby":1,"secondary":1}
,"capabilities":{"terracotta":1}
,"terracotta":{"switches":1,"fail":1}
,"switches":{"operating":1,"connected":1,"need":1,"linux":1,"fail":1,"non-functioning":1}
,"operating":{"system":1}
,"system":{"scenario":1,"event":1,"fail":1,"-hosts":1}
,"scenario":{"even":1,"software":1}
,"even":{"possible":1}
,"possible":{"sustain":1,"non-functioning":1}
,"sustain":{"certain":1}
,"certain":{"double":1}
,"double":{"failures":1}
,"failures":{"maintain":1,"redundant":1,"(pt":1}
,"maintain":{"fully":1}
,"functioning":{"cluster":1}
,"cluster":{"diagram":1,"machines":1,"servers":1,"continues":1,"fs15":1,"depending":1,"fs18":1,"test":1}
,"diagram":{"addressing":1,"two":1}
,"addressing":{"scheme":1}
,"scheme":{"merely":1,"specific":1}
,"merely":{"demonstrate":1}
,"demonstrate":{"l1s":1}
,"l1s":{"(l1a":1,"fail":1,"non-functioning":1}
,"(l1a":{"&l1b)":1}
,"&l1b)":{"different":1}
,"different":{"subnet":1,"switches":1}
,"subnet":{"l2s":1,"need":1,"switches":1}
,"l2s":{"(tcservera":1,"non-functioning":1}
,"(tcservera":{"&tcserverb)":1}
,"&tcserverb)":{"actual":1}
,"actual":{"addressing":1}
,"specific":{"environment":1}
,"environment":{"choose":1}
,"choose":{"implement":1,"mode":1}
,"implement":{"single":1,"virtual":1,"vrrp":1}
,"single":{"subnet":1,"vlan":1,"link":1,"host":1,"trunk":1}
,"need":{"vrrp\u002Fhsrp":1,"configure":1,"fail":1,"implement":1,"trunked":1,"configured":1}
,"vrrp\u002Fhsrp":{"need":1}
,"configure":{"single":1}
,"vlan":{"(can":1,"cluster":1}
,"(can":{"vlan":1}
,"machines":{"diagram":1}
,"two":{"switches":1,"lines":1,"operating":1,"different":1}
,"connected":{"trunked":1,"two":1}
,"trunked":{"links":1,"connection":1}
,"links":{"redundancy":1,"nodes":1,"system)":1,"possible":1,"mirror":1,"effect":1}
,"redundancy":{"implement":1,"protocol":1,"fs14":1,"fs16":1}
,"virtual":{"router":1}
,"router":{"redundancy":1,"two":1}
,"protocol":{"(vrrp)":1}
,"(vrrp)":{"hsrp":1}
,"hsrp":{"provide":1,"implementation":1}
,"provide":{"redundant":1}
,"paths":{"cluster":1}
,"servers":{"event":1,"configured":1}
,"event":{"switch":1,"nic":1}
,"switch":{"failure":1,"-switches":1,"ready":1,"remaining":1,"assumes":1,"trunk":1,"pull":1}
,"failure":{"additionally":1,"single":1,"splitting":1,"expected":1,"scenarios":1}
,"additionally":{"servers":1}
,"configured":{"primary":1,"bonded":1,"properly":1,"test":1}
,"primary":{"secondary":1,"network":1,"links":1,"link":1}
,"secondary":{"network":1,"link":1}
,"link":{"controlled":1,"failure":1,"operating":1,"without":1,"failover":1,"fs9":1,"fs10":1,"switch":1,"during":1,"noticeable":1,"down":1,"brief":1,"effect":1}
,"controlled":{"operating":1}
,"nic":{"link":1,"cards":1}
,"fail":{"backup":1,"identical":1,"scenario":1,"additional":1,"secondary":1,"nics":1,"new":1,"standby":1}
,"backup":{"link":1}
,"without":{"disturbing":1,"redundancy":1,"trunk":1}
,"disturbing":{"(e.g":1}
,"(e.g":{"restarting)":1}
,"restarting)":{"java":1}
,"java":{"processes":1}
,"processes":{"(l1":1}
,"(l1":{"l2)":1}
,"l2)":{"systems":1}
,"systems":{"terracotta":1}
,"identical":{"simple":1}
,"simple":{"case":1,"ping":1}
,"case":{"above":1}
,"above":{"however":1}
,"however":{"nic":1}
,"cards":{"single":1}
,"host":{"need":1,"action":1,"successful":1,"failover":1,"effect":1}
,"software":{"initiates":1}
,"initiates":{"fail":1}
,"additional":{"configuration":1}
,"-switches":{"need":1}
,"vrrp":{"hsrp":1,"address":1,"transition":1}
,"gateways":{"subnet":1}
,"connection":{"two":1}
,"lines":{"order":1}
,"order":{"prevent":1}
,"prevent":{"single":1}
,"splitting":{"virtual":1}
,"-hosts":{"need":1}
,"bonded":{"network":1}
,"interfaces":{"connected":1}
,"linux":{"choose":1,"channel":1,"bonding":1}
,"mode":{"information":1}
,"information":{"linux":1}
,"channel":{"bonding":1}
,"bonding":{"found":1,"driver":1,"configuration":1}
,"found":{"linux":1}
,"driver":{"description":1}
,"http:\u002F\u002Fwww.linuxfoundation.org\u002Fcollaborate\u002Fworkgroups\u002Fnetworking\u002Fbonding":{"pay":1}
,"pay":{"special":1}
,"special":{"attention":1}
,"attention":{"amount":1}
,"amount":{"time":1}
,"time":{"takes":1}
,"takes":{"vrrp":1}
,"implementation":{"reconverge":1,"fs17":1}
,"reconverge":{"recovery":1}
,"recovery":{"don\u0027t":1}
,"don\u0027t":{"want":1}
,"want":{"nics":1}
,"nics":{"change":1,"necessary":1}
,"change":{"switch":1}
,"ready":{"pass":1}
,"pass":{"traffic":1}
,"traffic":{"tunable":1}
,"tunable":{"bonding":1}
,"test":{"plan":1,"configuration":1}
,"plan":{"-network":1,"network":1}
,"-network":{"failures":1,"testing":1}
,"following":{"tests":1}
,"tests":{"continue":1,"listed":1,"confirm":1,"various":1,"testid":1}
,"continue":{"tests":1}
,"listed":{"network":1}
,"(pt":{"tests":1}
,"confirm":{"network":1}
,"properly":{"testid":1}
,"testid":{"failure":1,"host":1}
,"expected":{"outcome":1}
,"outcome":{"fs8":1,"nt4":1}
,"fs8":{"loss":1}
,"loss":{"primary":1,"switch":1,"(both":1,"active":1,"mirror":1,"switches":1,"single":1,"trunk":1,"l1s":1,"l2s":1}
,"standby":{"link":1}
,"fs9":{"loss":1}
,"nodes":{"fail":1,"detect":1}
,"fs10":{"loss":1}
,"remaining":{"switch":1}
,"assumes":{"vrrp":1}
,"address":{"switches":1}
,"necessary":{"fs11":1}
,"fs11":{"loss":1}
,"(both":{"links":1}
,"system)":{"cluster":1}
,"continues":{"normal":1}
,"normal":{"using":1,"without":1}
,"using":{"fs12":1}
,"fs12":{"loss":1}
,"active":{"mirror":1,"l1s":1,"fs13":1,"pull":1,"nt8":1}
,"mirror":{"becomes":1,"cluster":1,"pull":1}
,"becomes":{"new":1,"active":1}
,"new":{"active":1}
,"fs13":{"loss":1}
,"fs14":{"loss":1}
,"non-functioning":{"cluster":1}
,"fs15":{"loss":1}
,"trunk":{"cluster":1,"redundancy":1,"links":1,"link":1}
,"fs16":{"loss":1}
,"depending":{"vrrp":1}
,"fs17":{"loss":1}
,"fs18":{"loss":1}
,"testing":{"redundant":1,"consists":1}
,"ping":{"tests":1,"every":1,"nt5":1,"host":1}
,"various":{"failure":1}
,"scenarios":{"test":1}
,"consists":{"following":1}
,"action":{"expected":1}
,"nt4":{"ping":1}
,"every":{"host":1}
,"successful":{"ping":1}
,"nt5":{"pull":1}
,"pull":{"primary":1,"standby":1,"network":1,"single":1}
,"during":{"continuous":1}
,"continuous":{"ping":1}
,"noticeable":{"network":1}
,"interruption":{"nt6":1}
,"nt6":{"pull":1}
,"effect":{"nt7":1,"nt9":1}
,"nt7":{"active":1}
,"nt8":{"mirror":1}
,"nt9":{"switcha":1}
,"switcha":{"reload":1}
,"reload":{"nodes":1,"brief":1}
,"detect":{"link":1}
,"down":{"fail":1}
,"brief":{"network":1}
,"outage":{"vrrp":1}
,"transition":{"occurs":1}
,"occurs":{"nt10":1,"nt11":1}
,"nt10":{"switchb":1}
,"switchb":{"reload":1}
,"nt11":{"switch":1}
}
;Search.control.loadWordPairs(pairs);
