var pairs =
{
"wan":{"tab":1,"tab\u0027s":1,"number":1}
,"tab":{"statistics":1,"monitor":1}
,"statistics":{"wan":1,"master":1,"displayed":1,"statistic":1}
,"monitor":{"statistics":1}
,"master":{"orchestrator":1}
,"orchestrator":{"replica":1,"change":1,"master":1,"statistics":1,"immediate":1}
,"replica":{"orchestrator":1,"orchestrators":1}
,"change":{"default":1}
,"default":{"statistics":1}
,"displayed":{"wan":1}
,"tab\u0027s":{"overview":1}
,"overview":{"panels":1}
,"panels":{"click":1}
,"click":{"configure":1}
,"configure":{"columns":1}
,"columns":{"select":1}
,"select":{"following":1}
,"following":{"statistics":1}
,"statistic":{"description":1}
,"description":{"conflict":1,"inbound":1}
,"conflict":{"count":1,"table":1,"simply":1}
,"count":{"number":1,"applicable":1,"total":1}
,"number":{"conflicts":1,"outstanding":1,"higher":1,"processed":1,"transactions":1}
,"conflicts":{"resolved":1,"entries":1}
,"resolved":{"applicable":1}
,"applicable":{"bidirectional":1}
,"bidirectional":{"mode":1}
,"mode":{"conflict":1,"inbound":1}
,"table":{"size":1}
,"size":{"number":1,"size":1,"cluster":1}
,"outstanding":{"conflicts":1}
,"entries":{"may":1}
,"may":{"may":1,"conflict":1}
,"simply":{"means":1}
,"means":{"replicated":1}
,"replicated":{"replicas":1}
,"replicas":{"wan":1}
,"higher":{"conflict":1}
,"inbound":{"buffer":1}
,"buffer":{"size":1,"processing":1,"replication":1}
,"cluster":{"listener":1}
,"listener":{"buffer":1}
,"processing":{"rate":1,"mean":1,"count":1}
,"rate":{"min.)":1,"(15":1,"average":1}
,"min.)":{"average":1}
,"average":{"processed":1,"synchronization":1,"transactions":1}
,"processed":{"transactions":1,"transaction":1}
,"transactions":{"per":1,"entire":1}
,"per":{"second":1}
,"second":{"(tps)":1,"last":1}
,"(tps)":{"last":1,"entire":1,"during":1}
,"last":{"minute":1,"five":1,"fifteen":1}
,"minute":{"processed":1,"sync":1,"replication":1}
,"transaction":{"recorded":1}
,"recorded":{"master":1}
,"immediate":{"eventual":1}
,"eventual":{"transmission":1}
,"transmission":{"replica":1}
,"orchestrators":{"processing":1}
,"five":{"minutes":1}
,"minutes":{"processing":1,"sync":1,"replication":1}
,"(15":{"min.)":1}
,"fifteen":{"minutes":1}
,"mean":{"rate":1}
,"entire":{"application":1,"synchronization":1}
,"application":{"lifespan":1}
,"lifespan":{"processing":1,"sync":1,"replication":1}
,"total":{"number":1}
,"sync":{"rate":1,"mean":1,"count":1}
,"synchronization":{"transactions":1,"interval":1}
,"interval":{"sync":1,"replica":1}
,"replication":{"rate":1,"last":1,"mean":1,"count":1}
,"during":{"replication":1}
}
;Search.control.loadWordPairs(pairs);
