var pairs =
{
"reverting":{"tsas":1}
,"tsas":{"previous":1,"(as":1}
,"previous":{"version":1,"4.2":1}
,"version":{"revert":1,"procedure":1,"upgrades":1,"older":1}
,"revert":{"tsa":1}
,"tsa":{"4.2.x":1}
,"4.2.x":{"previous":1}
,"4.2":{"version":1}
,"procedure":{"used":1}
,"used":{"upgrading":1}
,"upgrading":{"tsas":1}
,"(as":{"described":1}
,"described":{"installing":1}
,"installing":{"maintenance":1}
,"maintenance":{"version":1}
,"upgrades":{"4.2)":1}
,"4.2)":{"simply":1}
,"simply":{"substitute":1}
,"substitute":{"newer":1}
,"newer":{"version":1}
,"older":{"version":1}
}
;Search.control.loadWordPairs(pairs);
