var pairs =
{
"dynamically":{"changing":1,"cache.setstatistics":1,"details":1}
,"changing":{"distributed":1,"common":1}
,"distributed":{"configuration":1,"bigmemory":1,"therefore":1}
,"configuration":{"just":1,"distributed":1,"options":1,"effect":1,"option":1,"however":1,"restarting":1,"cache":1,"apply":1}
,"just":{"standalone":1}
,"standalone":{"bigmemory":1}
,"bigmemory":{"mutating":1,"requires":1,"max":1}
,"mutating":{"configuration":1}
,"requires":{"access":1}
,"access":{"methods":1}
,"methods":{"cache.getcacheconfiguration":1}
,"cache.getcacheconfiguration":{"following":1}
,"following":{"table":1,"values":1}
,"table":{"provides":1}
,"provides":{"information":1}
,"information":{"dynamically":1}
,"common":{"configuration":1}
,"options":{"terracotta":1,"whose":1}
,"terracotta":{"cluster":1,"client":1,"server":1,"logging":1}
,"cluster":{"scope":1,"client":1,"events":1}
,"scope":{"column":1,"covers":1,"notes":1}
,"column":{"specifies":1}
,"specifies":{"configuration":1}
,"effect":{"following":1}
,"values":{"client":1}
,"client":{"terracotta":1,"cachemanager":1,"tsa":1,"enable":1,"nonstop":1,"certain":1,"copy":1,"statistics":1,"cache":1,"ehcache":1,"possible":1,"apply":1}
,"cachemanager":{"runs":1,"creating":1,"updated":1}
,"runs":{"tsa":1}
,"tsa":{"terracotta":1,"note":1,"nonstop":1,"persistence":1,"eternal":1}
,"server":{"array":1}
,"array":{"cluster":1}
,"note":{"configuration":1}
,"whose":{"scope":1}
,"covers":{"distributed":1}
,"therefore":{"affect":1}
,"affect":{"cache":1}
,"cache":{"clients":1,"name":1,"tsa":1,"statistics":1,"add":1,"new":1,"names":1}
,"clients":{"configuration":1}
,"option":{"dynamic":1}
,"dynamic":{"scope":1}
,"notes":{"cache":1}
,"name":{"tsa":1,"removed":1}
,"nonstop":{"client":1,"timeout":1,"immediate":1,"time":1}
,"enable":{"high":1}
,"high":{"availability":1}
,"availability":{"timeout":1}
,"timeout":{"client":1,"behavior":1,"disconnected":1}
,"behavior":{"client":1}
,"immediate":{"timeout":1}
,"disconnected":{"client":1}
,"time":{"idle":1,"live":1}
,"idle":{"time":1}
,"live":{"maximum":1}
,"maximum":{"entries":1,"off-heap":1}
,"entries":{"bytes":1,"cache":1}
,"bytes":{"local":1}
,"local":{"stores":1}
,"stores":{"client":1}
,"certain":{"sizing":1}
,"sizing":{"attributes":1}
,"attributes":{"may":1}
,"may":{"pooled":1}
,"pooled":{"cachemanager":1}
,"creating":{"limitations":1}
,"limitations":{"changed":1}
,"changed":{"maximum":1}
,"persistence":{"strategy":1}
,"strategy":{"n\u002Fa":1}
,"n\u002Fa":{"n\u002Fa":1,"disk":1,"maximum":1}
,"disk":{"expiry":1,"spool":1}
,"expiry":{"thread":1}
,"thread":{"interval":1}
,"interval":{"n\u002Fa":1}
,"spool":{"buffer":1}
,"buffer":{"size":1}
,"size":{"n\u002Fa":1}
,"off-heap":{"n\u002Fa":1,"memory":1}
,"memory":{"allotted":1}
,"allotted":{"tsa":1}
,"eternal":{"pinning":1}
,"pinning":{"details":1}
,"details":{"managing":1,"cluster":1,"bulk":1}
,"managing":{"data":1}
,"data":{"life":1}
,"life":{"clear":1}
,"clear":{"flush":1}
,"flush":{"client":1}
,"copy":{"read":1,"write":1}
,"read":{"client":1}
,"write":{"client":1}
,"statistics":{"client":1,"change":1}
,"change":{"dynamically":1}
,"cache.setstatistics":{"(boolean)":1}
,"(boolean)":{"method":1}
,"method":{"logging":1}
,"logging":{"client":1,"specified":1}
,"ehcache":{"terracotta":1}
,"specified":{"configuration":1}
,"however":{"cluster":1}
,"events":{"dynamically":1,"developer":1}
,"developer":{"guide":1}
,"guide":{"bigmemory":1}
,"max":{"consistency":1,"synchronous":1}
,"consistency":{"client":1}
,"possible":{"switch":1}
,"switch":{"bulk":1}
,"bulk":{"mode":1,"loading":1}
,"mode":{"details":1}
,"loading":{"developer":1}
,"synchronous":{"writes":1}
,"writes":{"client":1}
,"apply":{"non-dynamic":1}
,"non-dynamic":{"changes":1}
,"changes":{"remove":1}
,"remove":{"existing":1}
,"existing":{"cache":1}
,"add":{"(to":1}
,"(to":{"cachemanager)":1}
,"cachemanager)":{"new":1}
,"new":{"cache":1,"configuration":1}
,"removed":{"cache":1}
,"restarting":{"cachemanager":1}
,"updated":{"configuration":1}
,"names":{"previous":1}
,"previous":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
