var pairs =
{
"creating":{"backup":1}
,"backup":{"tmc":1,"button":1,"request":1,"function":1,"written":1,"consistent":1,"taken":1}
,"tmc":{"select":1,"sends":1}
,"select":{"administration":1}
,"administration":{"tab":1}
,"tab":{"backups":1}
,"backups":{"sub-tab":1}
,"sub-tab":{"click":1}
,"click":{"backup":1}
,"button":{"perform":1}
,"perform":{"backup":1}
,"sends":{"backup":1}
,"request":{"stripes":1}
,"stripes":{"cluster":1,"complete":1}
,"cluster":{"order":1,"stripe":1}
,"order":{"capture":1}
,"capture":{"consistent":1}
,"consistent":{"snapshot":1,"record":1}
,"snapshot":{"in-memory":1}
,"in-memory":{"data":1,"search":1}
,"data":{"backup":1}
,"function":{"creates":1}
,"creates":{"pause":1}
,"pause":{"transactions":1}
,"transactions":{"allowing":1,"complete":1}
,"allowing":{"unfinished":1}
,"unfinished":{"transactions":1}
,"complete":{"backup":1,"window":1}
,"written":{"allows":1}
,"allows":{"backup":1}
,"record":{"entries":1}
,"entries":{"in-memory":1}
,"search":{"indices":1}
,"indices":{"note":1}
,"note":{"backing":1}
,"backing":{"cluster":1}
,"stripe":{"backed":1}
,"backed":{"independently":1}
,"independently":{"slightly":1}
,"slightly":{"different":1}
,"different":{"time":1}
,"time":{"stripes":1}
,"window":{"appears":1}
,"appears":{"confirms":1}
,"confirms":{"backup":1}
,"taken":{"provides":1}
,"provides":{"time-stamped":1}
,"time-stamped":{"file":1}
,"file":{"name":1}
,"name":{"(s)":1}
,"(s)":{"backup":1}
}
;Search.control.loadWordPairs(pairs);
