var pairs =
{
"database":{"backup":1}
,"backup":{"utility":1,"data":1,"override":1,"directory":1,"backup":1,"place":1,"cluster":1,"process":1,"complete":1,"restoring":1}
,"utility":{"(backup-data)":1,"creates":1,"creating":1,"relies":1}
,"(backup-data)":{"backup":1}
,"creates":{"backup":1}
,"data":{"shared":1,"held":1,"files":1,"place":1,"backup":1}
,"shared":{"application":1}
,"application":{"taking":1}
,"taking":{"snapshot":1}
,"snapshot":{"data":1}
,"held":{"terracotta":1}
,"terracotta":{"server":1,"management":1}
,"server":{"array":1,"(tms)":1,"tsa":1}
,"array":{"(tsa)":1}
,"(tsa)":{"unless":1}
,"unless":{"different":1}
,"different":{"directory":1,"backup":1}
,"directory":{"specified":1,"${user.dir}\u002Fterracotta\u002Fbackups":1,"server\u0027s":1}
,"specified":{"configuration":1,"[p]":1,"[a]":1}
,"configuration":{"backups":1,"file":1}
,"backups":{"saved":1,"tms":1}
,"saved":{"default":1}
,"default":{"directory":1,"behavior":1,"[u]":1}
,"${user.dir}\u002Fterracotta\u002Fbackups":{"configuring":1}
,"configuring":{"backup":1}
,"override":{"default":1}
,"behavior":{"specifying":1}
,"specifying":{"different":1}
,"server\u0027s":{"configuration":1}
,"file":{"using":1}
,"using":{"<data-backup>":1,"backup":1}
,"<data-backup>":{"property":1}
,"property":{"<servers>":1}
,"<servers>":{"<restartable":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"name=\u0022":1}
,"name=\u0022":{"myserver":1}
,"myserver":{"<data-backup>\u002Fusers\u002Fmybackups":1}
,"<data-backup>\u002Fusers\u002Fmybackups":{"<\u002Fdata-backup>":1}
,"<\u002Fdata-backup>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"note":1}
,"note":{"enabling":1}
,"enabling":{"<restartable>":1}
,"<restartable>":{"mode":1}
,"mode":{"required":1}
,"required":{"using":1}
,"creating":{"backup":1}
,"relies":{"terracotta":1}
,"management":{"server":1,"console":1}
,"(tms)":{"locate":1}
,"locate":{"execute":1}
,"execute":{"backups":1}
,"tms":{"running":1,"omitted":1,"requires":1,"agent":1,"returns":1,"ssl":1}
,"running":{"connected":1}
,"connected":{"tsa":1}
,"tsa":{"backup":1,"terracotta":1,"agent":1,"configured":1}
,"place":{"information":1,"current":1}
,"information":{"connecting":1,"restoring":1}
,"connecting":{"terracotta":1}
,"console":{"user":1}
,"user":{"guide":1}
,"guide":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"bigmemory_home":1,"${bigmemory_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Fbackup-data.sh":1}
,"bigmemory_home":{"%\u005Ctools\u005Cmanagement-console\u005Cbin\u005Cbackup-data.bat":1}
,"%\u005Ctools\u005Cmanagement-console\u005Cbin\u005Cbackup-data.bat":{"<args>":1}
,"<args>":{"unix\u002Flinux":1,"<args>":1,"[l]":1}
,"unix\u002Flinux":{"[prompt]":1}
,"${bigmemory_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Fbackup-data.sh":{"<args>":1,"my-tms-host:9889":1}
,"[l]":{"<tms-host:port>":1}
,"<tms-host:port>":{"host":1}
,"host":{"port":1}
,"port":{"used":1}
,"used":{"connect":1,"default":1,"restore":1}
,"connect":{"tms":1}
,"omitted":{"localhost:9889":1}
,"localhost:9889":{"used":1}
,"[u]":{"<username>":1}
,"<username>":{"tms":1}
,"requires":{"authentication":1}
,"authentication":{"username":1,"password":1}
,"username":{"specified":1}
,"[p]":{"<password>":1}
,"<password>":{"tms":1}
,"password":{"specified":1}
,"[a]":{"<agentid>":1}
,"<agentid>":{"specify":1}
,"specify":{"agent":1}
,"agent":{"tsa":1,"connection":1,"provided":1,"ids":1,"someconnection":1}
,"connection":{"name":1,"tsa":1}
,"name":{"connection":1}
,"configured":{"tms":1,"agent":1}
,"provided":{"tms":1}
,"returns":{"list":1}
,"list":{"configured":1}
,"ids":{"[k]":1}
,"[k]":{"flag":1}
,"flag":{"causes":1}
,"causes":{"invalid":1}
,"invalid":{"tms":1}
,"ssl":{"certificates":1}
,"certificates":{"ignored":1}
,"ignored":{"example":1}
,"example":{"initiate":1}
,"initiate":{"backup":1}
,"cluster":{"agent":1}
,"someconnection":{"${bigmemory_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Fbackup-data.sh":1,"initiation":1}
,"my-tms-host:9889":{"\u005C-u":1}
,"\u005C-u":{"admin":1}
,"admin":{"admin":1,"someconnection":1}
,"initiation":{"successful":1}
,"successful":{"script":1}
,"script":{"reports":1}
,"reports":{"backup":1}
,"process":{"started":1}
,"started":{"once":1}
,"once":{"backup":1}
,"complete":{"backup":1}
,"files":{"used":1,"information":1}
,"restore":{"data":1}
,"current":{"data":1}
,"restoring":{"data":1}
}
;Search.control.loadWordPairs(pairs);
