var pairs =
{
"certificate-based":{"client":1}
,"client":{"authentication":1}
,"authentication":{"alternative":1,"scheme":1,"bigmemory":1,"available":1,"automatically":1,"note":1,"enable":1,"rest":1}
,"alternative":{"hash-based":1}
,"hash-based":{"message":1,"authentication":1}
,"message":{"authentication":1}
,"scheme":{"basic":1}
,"basic":{"security":1,"connection":1}
,"security":{"(as":1,"option":1,"adding":1}
,"(as":{"described":1}
,"described":{"basic":1,"following":1,"creating":1}
,"connection":{"security)":1,"security":1,"managed":1}
,"security)":{"certificate-based":1}
,"bigmemory":{"nodes":1,"kit)":1}
,"nodes":{"form":1}
,"form":{"authentication":1}
,"available":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"array":1,"add":1}
,"array":{"setting":1}
,"setting":{"client":1,"managementrestservice":1,"truststore":1,"identity-store":1}
,"automatically":{"turns":1}
,"turns":{"hash-based":1}
,"note":{"configure":1,"following":1}
,"configure":{"ssl":1}
,"ssl":{"security":1,"keystores":1,"addition":1,"connection":1,"connector":1,"port":1}
,"option":{"procedures":1}
,"procedures":{"adding":1}
,"adding":{"ssl":1}
,"keystores":{"managed":1}
,"managed":{"agents":1,"agent\u0027s":1,"agent":1}
,"agents":{"truststore":1,"keystore":1}
,"truststore":{"tms":1,"managed":1,"location":1,"included":1,"file\u0027s":1,"\u0022>\u002Fhome\u002F.tc\u002Fmgmt\u002Ftms-truststore":1,"used":1}
,"tms":{"described":1,"default":1,"unless":1,"identity":1,"deployed":1,"war":1}
,"addition":{"truststores":1}
,"truststores":{"managed":1}
,"keystore":{"tms":1,"\u0022>\u002Fhome\u002F.tc\u002Fmgmt\u002Ftms-keystore":1,"truststore":1}
,"following":{"procedure":1,"\u002Fmanagement-console\u002Fetc\u002Fjetty.xml":1,"configuration":1}
,"procedure":{"enable":1}
,"enable":{"certificate-based":1,"client":1}
,"rest":{"service":1}
,"service":{"setting":1}
,"managementrestservice":{"element\u0027s":1}
,"element\u0027s":{"needclientauth":1}
,"needclientauth":{"attribute":1,"true":1}
,"attribute":{"true":1}
,"true":{"managed":1,"securityservicelocation=\u0022":1,"needclientauth=\u0022":1,"<\u002Fehcache>":1,"<\u002Fset>":1}
,"agent\u0027s":{"configuration":1,"keychain":1}
,"configuration":{"<ehcache":1,"shown":1}
,"<ehcache":{"<managementrestservice":1}
,"<managementrestservice":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"securityservicelocation=\u0022":{"http:\u002F\u002Flocalhost:9889\u002Ftmc\u002Fapi\u002Fassertidentity":1}
,"http:\u002F\u002Flocalhost:9889\u002Ftmc\u002Fapi\u002Fassertidentity":{"sslenabled=\u0022":1}
,"sslenabled=\u0022":{"true":1}
,"needclientauth=\u0022":{"true":1}
,"<\u002Fehcache>":{"provide":1}
,"provide":{"truststore":1,"identity":1}
,"agent":{"default":1,"rejected":1,"ssl":1}
,"default":{"location":1,"keystore":1}
,"location":{"${user.home}\u002F.tc\u002Fmgmt\u002Ftruststore":1,"system":1,"${user.home}\u002F.tc\u002Fmgmt\u002Ftms-keystore":1}
,"${user.home}\u002F.tc\u002Fmgmt\u002Ftruststore":{"setting":1}
,"system":{"property":1}
,"property":{"javax.net.ssl.truststore":1,"javax.net.ssl.truststorepassword":1,"javax.net.ssl.keystore":1,"javax.net.ssl.keystorepassword":1}
,"javax.net.ssl.truststore":{"password":1}
,"password":{"truststore":1,"keyed":1,"system":1,"tms":1}
,"included":{"managed":1,"keychain":1}
,"keychain":{"password":1,"described":1}
,"keyed":{"truststore":1,"identity-store":1}
,"file\u0027s":{"uri":1}
,"uri":{"password":1,"alternatively":1}
,"javax.net.ssl.truststorepassword":{"provide":1}
,"identity":{"store":1}
,"store":{"tms":1,"included":1}
,"${user.home}\u002F.tc\u002Fmgmt\u002Ftms-keystore":{"setting":1}
,"identity-store":{"location":1,"file\u0027s":1}
,"javax.net.ssl.keystore":{"managed":1}
,"rejected":{"tms":1}
,"unless":{"valid":1}
,"valid":{"certificate":1}
,"certificate":{"found":1}
,"found":{"password":1}
,"creating":{"shared":1}
,"shared":{"secret":1}
,"secret":{"password":1}
,"alternatively":{"password":1}
,"javax.net.ssl.keystorepassword":{"allow":1}
,"allow":{"ssl":1}
,"connector":{"configured":1}
,"configured":{"tms":1}
,"deployed":{"provided":1,"different":1}
,"provided":{"jetty":1}
,"jetty":{"web":1,"tool":1}
,"web":{"server":1}
,"add":{"following":1}
,"\u002Fmanagement-console\u002Fetc\u002Fjetty.xml":{"(in":1}
,"(in":{"bigmemory":1}
,"kit)":{"shown":1}
,"shown":{"<call":1,"tms":1,"above":1}
,"<call":{"name=\u0022":1}
,"name=\u0022":{"addconnector":1,"keystore":1,"keystorepassword":1,"keymanagerpassword":1,"truststore":1,"needclientauth":1,"port":1,"maxidletime":1}
,"addconnector":{"<arg>":1}
,"<arg>":{"<new":1}
,"<new":{"class=\u0022":1}
,"class=\u0022":{"org.eclipse.jetty.server.ssl.sslselectchannelconnector":1,"org.eclipse.jetty.http.ssl.sslcontextfactory":1}
,"org.eclipse.jetty.server.ssl.sslselectchannelconnector":{"<arg>":1}
,"org.eclipse.jetty.http.ssl.sslcontextfactory":{"<set":1}
,"<set":{"name=\u0022":1}
,"\u0022>\u002Fhome\u002F.tc\u002Fmgmt\u002Ftms-keystore":{"<\u002Fset>":1}
,"<\u002Fset>":{"<set":1,"<\u002Fnew>":1}
,"keystorepassword":{"obf:1v9u1w1c1ym51xmq1rwd1rwh1xmk1ym91w261v8s":1}
,"obf:1v9u1w1c1ym51xmq1rwd1rwh1xmk1ym91w261v8s":{"<\u002Fset>":1}
,"keymanagerpassword":{"obf:1v9u1w1c1ym51xmq1rwd1rwh1xmk1ym91w261v8s":1}
,"\u0022>\u002Fhome\u002F.tc\u002Fmgmt\u002Ftms-truststore":{"<\u002Fset>":1}
,"<\u002Fnew>":{"<\u002Farg>":1}
,"<\u002Farg>":{"<set":1,"<\u002Fcall>":1}
,"port":{"9999":1,"free":1}
,"9999":{"<\u002Fset>":1}
,"maxidletime":{"30000":1,"value":1}
,"30000":{"<\u002Fset>":1}
,"<\u002Fcall>":{"note":1}
,"war":{"deployed":1}
,"different":{"container":1}
,"container":{"equivalent":1,"ssl":1}
,"equivalent":{"changes":1}
,"changes":{"appropriate":1}
,"appropriate":{"container":1}
,"free":{"(unused":1}
,"(unused":{"process)":1}
,"process)":{"avoid":1}
,"avoid":{"collisions":1}
,"collisions":{"maxidletime":1}
,"value":{"suits":1}
,"suits":{"environment":1}
,"environment":{"default":1}
,"used":{"enter":1,"passwords":1}
,"enter":{"correct":1}
,"correct":{"paths":1}
,"paths":{"keystore":1}
,"passwords":{"obfuscated":1}
,"obfuscated":{"using":1,"version":1}
,"using":{"built-in":1}
,"built-in":{"jetty":1}
,"tool":{"java":1}
,"java":{"-cp":1,"command":1}
,"-cp":{"lib\u002Fjetty-util-8.1.15.v20140411.jar":1}
,"lib\u002Fjetty-util-8.1.15.v20140411.jar":{"org.eclipse.jetty.util.security.password":1}
,"org.eclipse.jetty.util.security.password":{"mypassword":1}
,"mypassword":{"lib":1}
,"lib":{"folder":1}
,"folder":{"\u002Fmanagement-console\u002Fjetty-distribution\u002Flib\u002Ffolder":1}
,"\u002Fmanagement-console\u002Fjetty-distribution\u002Flib\u002Ffolder":{"product":1}
,"product":{"installation":1}
,"installation":{"jar":1}
,"jar":{"file":1}
,"file":{"name":1,"match":1}
,"name":{"consists":1,"jetty-util":1}
,"consists":{"jetty-util":1}
,"jetty-util":{"followed":1,"jar":1}
,"followed":{"additional":1}
,"additional":{"characters":1}
,"characters":{"name":1}
,"match":{"shown":1}
,"above":{"adapt":1}
,"adapt":{"java":1}
,"command":{"accordingly":1,"returns":1}
,"accordingly":{"command":1}
,"returns":{"obfuscated":1}
,"version":{"mypassword":1}
}
;Search.control.loadWordPairs(pairs);
