var pairs =
{
"implementing":{"cacheloader":1,"cacheloaderfactory":1}
,"cacheloader":{"implementing":1,"returns":1,"cacheloader":1,"=concretecacheloaderfactory.createcacheloader":1,"note":1,"implement":1}
,"cacheloaderfactory":{"bigmemory":1,"elements":1}
,"bigmemory":{"max":1}
,"max":{"api":1}
,"api":{"required":1}
,"required":{"effect":1}
,"effect":{"reloading":1}
,"reloading":{"entries":1}
,"entries":{"refresh-ahead":1}
,"refresh-ahead":{"operations":1}
,"operations":{"configuration":1}
,"configuration":{"specify":1}
,"specify":{"concrete":1}
,"concrete":{"class":1}
,"class":{"extends":1,"following":1}
,"extends":{"net.sf.ehcache.loader.cacheloaderfactory":1}
,"net.sf.ehcache.loader.cacheloaderfactory":{"call":1}
,"call":{"createcacheloader":1}
,"createcacheloader":{"(mycache":1}
,"(mycache":{"properties)":1}
,"properties)":{"create":1,"\u002F\u002Fcustom":1}
,"create":{"cache\u0027s":1}
,"cache\u0027s":{"cache":1}
,"cache":{"loader":1}
,"loader":{"example":1}
,"example":{"configured":1}
,"configured":{"concrete":1}
,"following":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"mycache":1}
,"mycache":{"<cacheloaderfactory":1}
,"<cacheloaderfactory":{"class=\u0022":1}
,"class=\u0022":{"com.company.my.concretecacheloaderfactory":1}
,"com.company.my.concretecacheloaderfactory":{"properties=\u0022":1}
,"properties=\u0022":{"some_property=1":1}
,"some_property=1":{"some_other_property=2":1}
,"some_other_property=2":{"<!--additional":1}
,"<!--additional":{"cacheloaderfactory":1}
,"elements":{"added":1}
,"added":{"form":1}
,"form":{"chain":1}
,"chain":{"cacheloader":1}
,"returns":{"null":1}
,"null":{"next":1}
,"next":{"line":1}
,"line":{"tried":1}
,"tried":{"-->":1}
,"-->":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"used":1}
,"used":{"programmatically":1}
,"programmatically":{"cacheloader":1}
,"=concretecacheloaderfactory.createcacheloader":{"(mycache":1}
,"\u002F\u002Fcustom":{"properties":1}
,"properties":{"passed":1}
,"passed":{"implemented":1}
,"implemented":{"cacheloader":1}
,"note":{"cacheloader":1}
,"implement":{"cacheloader.loadall":1}
,"cacheloader.loadall":{"method":1}
,"method":{"load":1}
,"load":{"refreshed":1}
,"refreshed":{"entries":1}
}
;Search.control.loadWordPairs(pairs);
