var pairs =
{
"enable":{"ssl":1}
,"ssl":{"securing":1,"connections":1,"security":1,"connection":1}
,"securing":{"client":1}
,"client":{"terracotta":1,"prepend":1,"username":1,"connect":1,"initiate":1,"credentials":1,"contains":1}
,"terracotta":{"clients":1,"server":1,"admin":1,"servers":1}
,"clients":{"require":1,"non-ssl":1}
,"require":{"specific":1}
,"specific":{"configuration":1}
,"configuration":{"enable":1,"example":1}
,"connections":{"terracotta":1}
,"server":{"array":1,"running":1,"configuration":1,"cluster":1}
,"array":{"script":1}
,"script":{"names":1}
,"names":{"examples":1}
,"examples":{"given":1}
,"given":{"below":1}
,"below":{"unix":1}
,"unix":{"linux":1}
,"linux":{"systems":1}
,"systems":{"equivalent":1}
,"equivalent":{"scripts":1}
,"scripts":{"available":1}
,"available":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"locations":1}
,"locations":{"replace":1}
,"replace":{".sh":1}
,".sh":{"extension":1}
,"extension":{".bat":1}
,".bat":{"convert":1}
,"convert":{"path":1}
,"path":{"delimiters":1}
,"delimiters":{"appropriate":1}
,"appropriate":{"enable":1}
,"security":{"client":1}
,"prepend":{"client":1}
,"username":{"address":1,"authenticated":1,"automatically":1,"client1":1,"corresponding":1,"included":1}
,"address":{"used":1,"active":1,"client1@172.16.254.1:9510":1,"<host>":1}
,"used":{"client":1,"start":1}
,"connect":{"cluster":1,"server":1}
,"cluster":{"username":1}
,"authenticated":{"followed":1}
,"followed":{"sign":1}
,"sign":{"(\u0022@\u0022)":1}
,"(\u0022@\u0022)":{"address":1}
,"active":{"server":1,"directory":1}
,"running":{"secure":1}
,"secure":{"mode":1}
,"mode":{"format":1}
,"format":{"<client-username>@<host>":1}
,"<client-username>@<host>":{"<tsa-port>":1}
,"<tsa-port>":{"prepending":1,"used":1}
,"prepending":{"username":1}
,"automatically":{"causes":1}
,"causes":{"client":1}
,"initiate":{"ssl":1}
,"connection":{"client":1}
,"client1":{"example":1}
,"example":{"attempts":1,"address":1}
,"attempts":{"connect":1}
,"client1@172.16.254.1:9510":{"uri":1}
,"uri":{"replaces":1,"password":1}
,"replaces":{"address":1}
,"<host>":{"<tsa-port>":1}
,"start":{"clients":1}
,"non-ssl":{"clusters":1}
,"clusters":{"verify":1}
,"verify":{"client":1}
,"corresponding":{"password":1}
,"password":{"match":1,"local":1}
,"match":{"server\u0027s":1}
,"server\u0027s":{".ini":1}
,".ini":{"file":1}
,"file":{"credentials":1}
,"credentials":{"ldap":1,"associated":1}
,"ldap":{"active":1}
,"directory":{"username":1}
,"included":{"uri":1}
,"local":{"keychain":1}
,"keychain":{"entry":1}
,"entry":{"create":1}
,"create":{"client":1}
,"associated":{"role":1}
,"role":{"terracotta":1}
,"admin":{"terracotta":1}
,"servers":{"using":1}
,"using":{"self-signed":1}
,"self-signed":{"certificates":1}
,"certificates":{"(not":1,"signed":1}
,"(not":{"certificates":1}
,"signed":{"well-known":1}
,"well-known":{"ca)":1}
,"ca)":{"specify":1}
,"specify":{"truststore":1}
,"truststore":{"client":1}
,"contains":{"public":1}
,"public":{"key":1}
,"key":{"every":1}
,"every":{"server":1}
}
;Search.control.loadWordPairs(pairs);
