var pairs =
{
"working":{"replication":1}
,"replication":{"logs":1,"provides":1,"log":1}
,"logs":{"bigmemory":1,"synchronization":1}
,"bigmemory":{"wan":1}
,"wan":{"replication":1,"process":1}
,"provides":{"logging":1}
,"logging":{"messages":1,"includes":1}
,"messages":{"easily":1,"regard":1,"below":1,"incremental":1,"issued":1}
,"easily":{"parsable":1}
,"parsable":{"third-party":1}
,"third-party":{"log":1}
,"log":{"watchers":1,"messages":1,"message":1}
,"watchers":{"scrapers":1}
,"scrapers":{"logging":1}
,"includes":{"topology":1}
,"topology":{"changes":1}
,"changes":{"regularly":1}
,"regularly":{"print":1}
,"print":{"stats":1}
,"stats":{"number":1}
,"number":{"mutations":1,"sync_updates":1,"sync_update":1}
,"mutations":{"message":1}
,"message":{"size":1,"issued":1,"posting":1}
,"size":{"data":1}
,"data":{"conflicts":1}
,"conflicts":{"repairs":1}
,"repairs":{"failover\u002Frecovery":1}
,"failover\u002Frecovery":{"status\u002Fprogress":1}
,"status\u002Fprogress":{"significant":1}
,"significant":{"wan":1}
,"regard":{"synchronization":1}
,"synchronization":{"incremental":1,"master":1,"batch":1,"replica":1,"updates":1,"info":1}
,"incremental":{"updates":1}
,"updates":{"messages":1,"master":1,"log":1,"bidirectional":1,"batched":1,"tsa":1}
,"below":{"provide":1}
,"provide":{"important":1}
,"important":{"markers":1}
,"markers":{"wan":1}
,"master":{"side":1,"cache":1,"replica":1,"\u0027localhost:9001":1,"receiving":1}
,"side":{"log":1}
,"issued":{"master":1,"once":1,"replica":1}
,"cache":{"sending":1,"info":1,"\u0027tc_clustered-ehcache":1,"started":1,"processed":1,"completed":1,"replica":1,"successfully":1}
,"sending":{"synchronization":1}
,"batch":{"replica":1,"synchronization":1,"updates":1}
,"replica":{"cache":1,"\u0027localhost:9002":1,"info":1,"completed":1,"side":1,"activated":1,"successfully":1,"succesfully":1}
,"info":{"[master-sync-13]":1,"[new":1,"[replica-sync-4]":1,"[replica-sync-2]":1,"[replica-sync-5]":1,"[master-0]":1}
,"[master-sync-13]":{"fullscanmastersynchronizer":1}
,"fullscanmastersynchronizer":{"-master":1,"-total":1}
,"-master":{"\u0027localhost:9001":1}
,"\u0027localhost:9001":{"sent":1,"successfully":1,"cache":1,"incremental":1,"info":1}
,"sent":{"sync_update":1}
,"sync_update":{"request":1,"requests":1}
,"request":{"events":1,"master":1}
,"events":{"replica":1}
,"\u0027localhost:9002":{"cache":1,"184":1,"activated":1}
,"\u0027tc_clustered-ehcache":{"default__|":1}
,"default__|":{"wan-test-cache1":1,"wan-test-cache3":1,"wan-test-cache1@localhost:9002":1}
,"wan-test-cache1":{"log":1,"keys":1,"1199":1}
,"posting":{"total":1}
,"total":{"number":1}
,"sync_updates":{"processed":1}
,"processed":{"replica":1,"batch":1}
,"[new":{"i\u002Fo":1}
,"i\u002Fo":{"worker":1}
,"worker":{"fullscanmastersynchronizer":1,"replicacache":1}
,"-total":{"number":1}
,"requests":{"submitted":1}
,"submitted":{"replica":1}
,"184":{"log":1}
,"once":{"synchronization":1}
,"completed":{"info":1,"synchronization":1}
,"successfully":{"synchronized":1,"activated":1,"storing":1,"acknowledged":1}
,"synchronized":{"replica":1}
,"wan-test-cache3":{"synchronization":1,"log":1,"request":1}
,"started":{"synchronzing":1}
,"synchronzing":{"master":1}
,"[replica-sync-4]":{"fullscanreplicasynchronizer":1}
,"fullscanreplicasynchronizer":{"-replica":1}
,"-replica":{"sync_start":1,"sync_update":1,"sync_end":1,"\u0027localhost:9002":1,"cache":1,"\u0027tc_clustered-ehcache":1}
,"sync_start":{"request":1}
,"[replica-sync-2]":{"fullscanreplicasynchronizer":1}
,"keys":{"log":1}
,"activated":{"info":1,"synchronization":1,"cache":1}
,"[replica-sync-5]":{"fullscanreplicasynchronizer":1}
,"sync_end":{"request":1}
,"replicacache":{"-replica":1}
,"bidirectional":{"mode":1}
,"mode":{"note":1}
,"note":{"watermarks":1}
,"watermarks":{"batches":1}
,"batches":{"updates":1}
,"batched":{"part":1}
,"part":{"internal":1}
,"internal":{"wan":1}
,"process":{"log":1}
,"receiving":{"acknowledgements":1}
,"acknowledgements":{"replica":1}
,"storing":{"batch":1}
,"tsa":{"info":1,"master":1}
,"[master-0]":{"unitreplicator":1,"mastercache":1}
,"unitreplicator":{"-replica":1}
,"wan-test-cache1@localhost:9002":{"watermark":1,"successfully":1}
,"watermark":{"1131":1,"across":1,"1199":1}
,"1131":{"1199":1,"master":1}
,"1199":{"info":1,"log":1,"master":1}
,"mastercache":{"-lowest":1}
,"-lowest":{"watermark":1}
,"across":{"replicas":1}
,"replicas":{"cache":1}
,"succesfully":{"acklowledged":1}
,"acklowledged":{"storage":1}
,"storage":{"updates":1}
,"acknowledged":{"watermark":1}
}
;Search.control.loadWordPairs(pairs);
