var pairs =
{
"using":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"hibernate":1,"easily":1,"project":1,"cache":1,"second-level":1}
,"hibernate":{"bigm":1,"object\u002Frelational":1,"download":1,"configure":1,"configuration":1,"caching":1,"entities":1,"hibernate":1,"product":1}
,"bigm":{"bigmemory":1}
,"easily":{"integrates":1}
,"integrates":{"hibernate":1}
,"object\u002Frelational":{"persistence":1}
,"persistence":{"query":1}
,"query":{"service":1,"cache":1,"want":1,"configured":1}
,"service":{"configure":1}
,"configure":{"bigmemory":1,"hibernate":1,"ehcache.xml":1}
,"download":{"install":1}
,"install":{"bigmemory":1}
,"project":{"described":1}
,"described":{"downloading":1,"configuring":1,"enabling":1}
,"downloading":{"installing":1}
,"installing":{"bigmemory":1}
,"cache":{"provider":1,"query":1,"settings":1,"described":1,"configuration":1}
,"provider":{"project\u0027s":1,"enable":1}
,"project\u0027s":{"hibernate":1}
,"configuration":{"described":1,"hibernate":1}
,"configuring":{"bigmemory":1,"hibernate":1,"ehcache.xml":1}
,"second-level":{"cache":1,"caching":1}
,"enable":{"second-level":1}
,"caching":{"project\u0027s":1,"entity":1,"configure":1,"described":1}
,"enabling":{"second-level":1}
,"settings":{"configure":1,"additional":1}
,"entity":{"collection":1}
,"collection":{"query":1}
,"want":{"cache":1}
,"entities":{"second-level":1}
,"ehcache.xml":{"file":1,"settings":1}
,"file":{"entity":1}
,"configured":{"caching":1}
,"additional":{"information":1}
,"information":{"cache":1}
,"product":{"documentation":1}
,"documentation":{"http:\u002F\u002Fwww.hibernate.org\u002F":1}
}
;Search.control.loadWordPairs(pairs);
