var pairs =
{
"summary":{"changes":1}
,"changes":{"4.0":1,"automatic":1,"recovery":1}
,"4.0":{"4.1":1}
,"4.1":{"area":1,"tsa":1}
,"area":{"change":1}
,"change":{"change":1,"4.0":1,"datastorage":1}
,"tsa":{"operation":1,"disk":1,"configuration":1,"monitoring":1}
,"operation":{"changes":1}
,"automatic":{"resource":1}
,"resource":{"management":1}
,"management":{"bigmemory":1}
,"bigmemory":{"hybrid":1,"sql":1}
,"hybrid":{"changes":1,"tsa":1,"elements":1,"statistics":1}
,"recovery":{"near-memory-full":1}
,"near-memory-full":{"conditions":1}
,"conditions":{"bigmemory":1}
,"disk":{"usage":1}
,"usage":{"bigmemory":1}
,"configuration":{"offheap":1,"change":1,"maxelementsinmemory":1}
,"offheap":{"configuration":1}
,"datastorage":{"hybrid":1}
,"elements":{"added":1}
,"added":{"maxdatasize":1,"interoperability":1,"search":1}
,"maxdatasize":{"element":1}
,"element":{"deprecated":1}
,"deprecated":{"tsa":1,"(use":1}
,"monitoring":{"data":1}
,"data":{"lifecycle":1}
,"lifecycle":{"support":1}
,"support":{"bigmemory":1,"nulls":1}
,"statistics":{"wan":1}
,"wan":{"replication":1}
,"replication":{"wan":1,"service":1}
,"service":{"added":1}
,"interoperability":{"cross-language":1}
,"cross-language":{"clients":1}
,"clients":{"added":1}
,"search":{"query":1}
,"query":{"using":1}
,"using":{"bigmemory":1}
,"sql":{"support":1}
,"nulls":{"pagination":1}
,"pagination":{"tier":1}
,"tier":{"configuration":1}
,"maxelementsinmemory":{"deprecated":1}
,"(use":{"maxentrieslocalheap":1}
,"maxentrieslocalheap":{"instead)":1}
}
;Search.control.loadWordPairs(pairs);
