var pairs =
{
"client":{"demo":1,"page":1,"cross-language":1,"connector":1,"component":1,"dependencies":1}
,"demo":{"sample":1,"recipe":1,"(linux)":1}
,"sample":{"following":1,"provided":1}
,"following":{"sample":1,"files":1}
,"provided":{"code-samples\u002Fcross-lang\u002Fexample03\u002Fdirectory":1}
,"code-samples\u002Fcross-lang\u002Fexample03\u002Fdirectory":{"kit":1}
,"kit":{"demo":1}
,"recipe":{"app":1,"classes":1,"recipeprotobufserializer":1}
,"app":{"includes":1}
,"includes":{"ingredients":1}
,"ingredients":{"measurements":1}
,"measurements":{"instructions":1}
,"instructions":{"uses":1}
,"uses":{"google":1}
,"google":{"protocol":1}
,"protocol":{"buffer":1}
,"buffer":{"serialization":1}
,"serialization":{"consists":1}
,"consists":{"following":1}
,"files":{"main.cpp":1}
,"main.cpp":{"recipe.pb.cc":1,"requires":1}
,"recipe.pb.cc":{"recipe.pb.h":1}
,"recipe.pb.h":{"recipeprotobufserializer.cpp":1}
,"recipeprotobufserializer.cpp":{"recipeprotobufserializer.h":1}
,"recipeprotobufserializer.h":{"compile":1}
,"compile":{"run":1,"link":1}
,"run":{"demo":1,"example":1,"main.cpp":1,"application":1}
,"(linux)":{"install":1}
,"install":{"cross-language":1}
,"cross-language":{"connector":1}
,"connector":{"customize":1,"run":1,"classpaths":1,"component":1}
,"customize":{"cross-lang-config.xml":1}
,"cross-lang-config.xml":{"file":1}
,"file":{"described":1}
,"described":{"installing":1}
,"installing":{"configuring":1}
,"configuring":{"bigmemory":1}
,"bigmemory":{"client":1}
,"page":{"start":1,"note":1}
,"start":{"server":1}
,"server":{"described":1}
,"note":{"already":1}
,"already":{"installed":1}
,"installed":{"bigmemory":1}
,"example":{"adding":1,"<bmkit>\u002Fapis\u002Fcpp\u002Finclude":1}
,"adding":{"external":1}
,"external":{"protobuf":1}
,"protobuf":{"dependency":1}
,"dependency":{"maven":1,"need":1}
,"maven":{"link":1}
,"link":{"<dependency>":1,"platform":1}
,"<dependency>":{"<groupid>":1}
,"<groupid>":{"com.google.protobuf":1}
,"com.google.protobuf":{"<\u002Fgroupid>":1}
,"<\u002Fgroupid>":{"<artifactid>":1}
,"<artifactid>":{"protobuf-java":1}
,"protobuf-java":{"<\u002Fartifactid>":1}
,"<\u002Fartifactid>":{"<version>":1}
,"<version>":{"2.5.0":1}
,"2.5.0":{"<\u002Fversion>":1}
,"<\u002Fversion>":{"<\u002Fdependency>":1}
,"<\u002Fdependency>":{"dependency":1}
,"need":{"bigmemory":1}
,"classpaths":{"connector":1}
,"component":{"needs":1,"run":1}
,"needs":{"ehcachethriftconfiguration.builder":1}
,"ehcachethriftconfiguration.builder":{".cacheserializerfactory":1}
,".cacheserializerfactory":{"(recipeserializerfactory.class)":1}
,"(recipeserializerfactory.class)":{"recipeserializerfactory":1}
,"recipeserializerfactory":{"recipeprotobufserializer":1}
,"recipeprotobufserializer":{"recipe":1,"classes":1}
,"classes":{"connector\u0027s":1,"classpath":1}
,"connector\u0027s":{"classpath":1}
,"classpath":{"bigmemory":1,"along":1}
,"requires":{"main":1}
,"main":{"recipe":1}
,"along":{"bigmemory":1}
,"dependencies":{"run":1}
,"application":{"compile":1}
,"platform":{"serializer":1}
,"serializer":{"libraries":1}
,"libraries":{"output":1}
,"output":{"console":1}
,"console":{"example":1}
,"<bmkit>\u002Fapis\u002Fcpp\u002Finclude":{"<googleprotocolbufferinclude>":1}
,"<googleprotocolbufferinclude>":{"<bmkit>\u002Fapis\u002Fcpp\u002F<platform>\u002F<arch>":1}
,"<bmkit>\u002Fapis\u002Fcpp\u002F<platform>\u002F<arch>":{"<googleprotocolbufferlib>":1}
,"<googleprotocolbufferlib>":{"-lbigmemoryconnector":1}
,"-lbigmemoryconnector":{"-lprotobuf":1}
,"-lprotobuf":{"*.cc":1}
,"*.cc":{"*.cpp":1}
,"*.cpp":{"console":1}
}
;Search.control.loadWordPairs(pairs);
