var pairs =
{
"user":{"roles":1,"admin":1,"sets":1,"perform":1,"connect":1,"start":1}
,"roles":{"two":1,"available":1}
,"two":{"roles":1}
,"available":{"terracotta":1}
,"terracotta":{"servers":1,"-this":1,"terracotta":1,"user":1}
,"servers":{"clients":1,"clearing":1}
,"clients":{"admin":1}
,"admin":{"-the":1,"role":1,"user":1}
,"-the":{"user":1}
,"role":{"initial":1,"default":1,"terracotta":1,"order":1}
,"initial":{"user":1}
,"sets":{"security":1}
,"security":{"thereafter":1}
,"thereafter":{"admin":1}
,"perform":{"system":1}
,"system":{"functions":1}
,"functions":{"shutting":1}
,"shutting":{"down":1}
,"down":{"servers":1}
,"clearing":{"deleting":1}
,"deleting":{"caches":1}
,"caches":{"cache":1}
,"cache":{"managers":1}
,"managers":{"reloading":1}
,"reloading":{"configurations":1}
,"configurations":{"terracotta":1}
,"-this":{"operator":1}
,"operator":{"role":1}
,"default":{"username":1}
,"username":{"operator":1}
,"connect":{"tmc":1}
,"tmc":{"access":1}
,"access":{"read-only":1}
,"read-only":{"areas":1}
,"areas":{"addition":1}
,"addition":{"terracotta":1}
,"start":{"secure":1}
,"secure":{"server":1}
,"server":{"user":1}
,"order":{"run":1}
,"run":{"stop-tc-server":1}
,"stop-tc-server":{"script":1}
}
;Search.control.loadWordPairs(pairs);
