var pairs =
{
"basic":{"steps":1}
,"steps":{"server":1,"following":1}
,"server":{"security":1,"follow":1}
,"security":{"security":1,"terracotta":1}
,"terracotta":{"server":1}
,"follow":{"steps":1}
,"following":{"procedures":1}
,"procedures":{"script":1}
,"script":{"names":1}
,"names":{"examples":1}
,"examples":{"given":1}
,"given":{"below":1}
,"below":{"unix":1}
,"unix":{"linux":1}
,"linux":{"systems":1}
,"systems":{"equivalent":1}
,"equivalent":{"scripts":1}
,"scripts":{"available":1}
,"available":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"locations":1,"replace":1}
,"locations":{"windows":1}
,"replace":{".sh":1}
,".sh":{"extension":1}
,"extension":{".bat":1}
,".bat":{"convert":1}
,"convert":{"path":1}
,"path":{"delimiters":1}
,"delimiters":{"appropriate":1}
}
;Search.control.loadWordPairs(pairs);
