var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fgarbage-collection":{"section":1}
,"section":{"lets":1}
,"lets":{"configure":1}
,"configure":{"periodic":1}
,"periodic":{"distributed":1,"dgc":1}
,"distributed":{"garbage":1}
,"garbage":{"collector":1,"java":1,"collection":1,"addition":1,"however":1}
,"collector":{"(dgc)":1}
,"(dgc)":{"runs":1}
,"runs":{"tsa":1}
,"tsa":{"dgc":1}
,"dgc":{"collects":1,"caches":1,"normally":1,"little":1,"may":1,"functions":1}
,"collects":{"shared":1}
,"shared":{"data":1}
,"data":{"made":1,"becomes":1,"structures":1}
,"made":{"garbage":1}
,"java":{"garbage":1}
,"collection":{"cases":1,"configuration":1,"default":1,"performed":1}
,"cases":{"need":1}
,"need":{"enable":1,"enabled":1}
,"enable":{"periodic":1}
,"caches":{"efficient":1}
,"efficient":{"automatic":1}
,"automatic":{"inline":1}
,"inline":{"dgc":1}
,"normally":{"sufficient":1}
,"sufficient":{"clearing":1}
,"clearing":{"garbage":1}
,"addition":{"certain":1}
,"certain":{"read-heavy":1,"data":1}
,"read-heavy":{"applications":1}
,"applications":{"require":1}
,"require":{"periodic":1}
,"little":{"shared":1}
,"becomes":{"garbage":1}
,"however":{"concerning":1}
,"concerning":{"certain":1}
,"structures":{"periodic":1,"dgc":1}
,"may":{"need":1,"available":1}
,"enabled":{"inline":1}
,"available":{"data":1}
,"functions":{"managing":1}
,"managing":{"distributed":1}
,"configuration":{"snippet":1}
,"snippet":{"<garbage-collection>":1}
,"<garbage-collection>":{"<!--default":1}
,"<!--default":{"false":1}
,"false":{"-->":1,"<\u002Fverbose>":1}
,"-->":{"<enabled>":1,"<verbose>":1,"<interval>":1}
,"<enabled>":{"true":1}
,"true":{"<\u002Fenabled>":1,"additional":1}
,"<\u002Fenabled>":{"<!--if":1}
,"<!--if":{"true":1}
,"additional":{"information":1}
,"information":{"logged":1}
,"logged":{"server":1}
,"server":{"performs":1}
,"performs":{"distributed":1}
,"default":{"false":1,"3600":1}
,"<verbose>":{"false":1}
,"<\u002Fverbose>":{"<!--how":1}
,"<!--how":{"often":1}
,"often":{"distributed":1}
,"performed":{"seconds":1}
,"seconds":{"default":1}
,"3600":{"(60":1,"<\u002Finterval>":1}
,"(60":{"minutes)":1}
,"minutes)":{"-->":1}
,"<interval>":{"3600":1}
,"<\u002Finterval>":{"<\u002Fgarbage-collection>":1}
}
;Search.control.loadWordPairs(pairs);
