var pairs =
{
"lifecycle":{"actions":1,"command":1,"operations":1}
,"actions":{"terracotta":1}
,"terracotta":{"following":1,"supports":1,"action":1,"server":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"actions":1}
,"supports":{"sagcc":1}
,"sagcc":{"exec":1}
,"exec":{"lifecycle":1}
,"command":{"operation":1}
,"operation":{"taken":1}
,"taken":{"against":1}
,"against":{"terracotta":1}
,"action":{"executed":1,"description":1}
,"executed":{"execute":1}
,"execute":{"lifecycle":1}
,"operations":{"correct":1}
,"correct":{"order":1}
,"order":{"ensure":1}
,"ensure":{"safe":1}
,"safe":{"startup":1}
,"startup":{"shutdown":1}
,"shutdown":{"restart":1}
,"restart":{"terracotta":1,"restart":1,"running":1}
,"server":{"array":1,"instance":1}
,"array":{"cluster":1}
,"cluster":{"instances":1}
,"instances":{"action":1}
,"description":{"start":1}
,"start":{"start":1,"server":1}
,"instance":{"stopped":1,"restart":1}
,"stopped":{"stop":1}
,"stop":{"stop":1,"running":1}
,"running":{"server":1}
}
;Search.control.loadWordPairs(pairs);
