var pairs =
{
".net":{"client":1,"native":1}
,"client":{"serialization":1}
,"serialization":{"cross-language":1,"data":1,"single-language":1,"including":1,"refer":1}
,"cross-language":{"serialization":1}
,"data":{"shared":1}
,"shared":{"across":1}
,"across":{"languages":1}
,"languages":{"needs":1}
,"needs":{"serialized":1,"choice":1}
,"serialized":{"choice":1}
,"choice":{"serializer":1}
,"serializer":{"depends":1,"pros":1,"manually":1,"automatically":1,"however":1,"using":1,"=new":1}
,"depends":{"upon":1}
,"upon":{"environment":1}
,"environment":{"planning":1}
,"planning":{"consideration":1}
,"consideration":{"needs":1}
,"pros":{"cons":1}
,"cons":{"related":1}
,"related":{"example":1}
,"example":{"bson":1,"google":1,"icachemanager":1}
,"bson":{"serializer":1,"bsonwriter":1,"version":1}
,"manually":{"annotate":1}
,"annotate":{"domain":1}
,"domain":{"object":1}
,"object":{"desired":1,"annotation":1,"using":1,"value":1}
,"desired":{"attributes":1}
,"attributes":{"hand":1,"nvpairs":1}
,"hand":{"google":1}
,"google":{"protocol":1}
,"protocol":{"buffer":1}
,"buffer":{"serializer":1}
,"automatically":{"generate":1}
,"generate":{"domain":1}
,"annotation":{"serializer":1}
,"however":{"existing":1}
,"existing":{"domain":1}
,"using":{"automatic":1,"newtonsoft.json":1,"newtonsoft.json.bson":1,"newtonsoft.json.converters":1,"newtonsoft.json.linq":1,"system":1,"system.collections.generic":1,"system.io":1,"system.text":1,"terracotta.ehcache":1,"terracotta.ehcache.thrift":1}
,"automatic":{"generation":1}
,"generation":{"intrusive":1}
,"intrusive":{"serializer\u002Fdeserializer":1}
,"serializer\u002Fdeserializer":{"class":1}
,"class":{"include":1,"definition":1,"leverage":1,"cache":1}
,"include":{"following":1}
,"following":{"list":1,"methods\u002Ffunctions":1}
,"list":{"namespaces\u002Fpackages":1}
,"namespaces\u002Fpackages":{"used":1}
,"used":{"class":1}
,"definition":{"consisting":1,"serializekey":1,"deserializekey":1,"serializevalue":1,"deserializevalue":1}
,"consisting":{"following":1}
,"methods\u002Ffunctions":{"serializekey":1}
,"serializekey":{"-accepts":1,"public":1,"(string":1}
,"-accepts":{"key":1,"pnf":1,"object":1}
,"key":{"returns":1,"serializevalue":1}
,"returns":{"platform-neutral":1,"key":1,"pnf":1,"object":1}
,"platform-neutral":{"format":1}
,"format":{"(pnf)":1}
,"(pnf)":{"value":1}
,"value":{"deserializekey":1,"returns":1,"example":1,"serializekey":1,"val.stringvalue":1}
,"deserializekey":{"-accepts":1,"public":1,"(terracotta.ehcache":1,"(value":1}
,"pnf":{"value":1,"storedvalue":1}
,"serializevalue":{"-accepts":1,"public":1,"(recipe2":1,"(recipeproject.recipestructure":1}
,"storedvalue":{"deserializevalue":1,"returns":1,"serializevalue":1}
,"deserializevalue":{"-accepts":1,"public":1,"(terracotta.ehcache.thrift.storedvalue":1,"(storedvalue":1}
,"newtonsoft.json":{"using":1}
,"newtonsoft.json.bson":{"using":1}
,"newtonsoft.json.converters":{"using":1}
,"newtonsoft.json.linq":{"using":1}
,"system":{"using":1}
,"system.collections.generic":{"using":1}
,"system.io":{"using":1}
,"system.text":{"using":1}
,"terracotta.ehcache":{"using":1}
,"terracotta.ehcache.thrift":{"class":1}
,"public":{"terracotta.ehcache.thrift.value":1,"string":1,"storedvalue":1,"recipe2":1,"value":1,"recipeproject.recipestructure":1}
,"terracotta.ehcache.thrift.value":{"serializekey":1}
,"(string":{"key)":1}
,"key)":{"{return":1,"{value":1}
,"{return":{"valuehelper.newvalue":1,"(string)":1,"serializedkey.stringvalue":1}
,"valuehelper.newvalue":{"(key)":1}
,"(key)":{"class":1}
,"string":{"deserializekey":1}
,"(terracotta.ehcache":{"thrift.value":1}
,"thrift.value":{"serializedkey)":1}
,"serializedkey)":{"{return":1}
,"(string)":{"valuehelper.findsetvalue":1}
,"valuehelper.findsetvalue":{"(serializedkey)":1}
,"(serializedkey)":{"class":1}
,"(recipe2":{"objectvalue)":1}
,"objectvalue)":{"{memorystream":1,"byte":1,"{dictionary":1,"return":1}
,"{memorystream":{"=new":1}
,"=new":{"memorystream":1,"bsonwriter":1,"jsonserializer":1,"dictionary":1,"bsonreader":1,"value":1}
,"memorystream":{"\u002F\u002Fserialize":1,"(value.value":1,"=new":1,"protobuf.serializer.serialize":1,"(value.value.binaryvalue)":1}
,"\u002F\u002Fserialize":{"recipe":1}
,"recipe":{"bson":1,"byte":1,"=serializer.deserialize":1,"example":1}
,"bsonwriter":{"writer":1,"(ms)":1}
,"writer":{"=new":1}
,"(ms)":{"jsonserializer":1,"single-language":1}
,"jsonserializer":{"serializer":1,"serializer.serialize":1,"recipe2":1}
,"serializer.serialize":{"(writer":1}
,"(writer":{"objectvalue)":1}
,"byte":{"barray":1,"array":1}
,"barray":{"=ms.toarray":1}
,"=ms.toarray":{"dictionary":1}
,"dictionary":{"<string":1}
,"<string":{"object>":1,"string>":1}
,"object>":{"nvpairs":1,"\u002F\u002Ftwo":1,"nvpairs.add":1}
,"nvpairs":{"=new":1,"name":1,"bakingtime":1}
,"\u002F\u002Ftwo":{"indexable":1}
,"indexable":{"attributes":1}
,"name":{"=objectvalue.name":1}
,"=objectvalue.name":{"nvpairs":1}
,"bakingtime":{"=objectvalue.bakingtime":1}
,"=objectvalue.bakingtime":{"\u002F\u002Fship":1}
,"\u002F\u002Fship":{"bson":1}
,"version":{"recipe":1}
,"array":{"return":1}
,"return":{"valuehelper.nullsafestoredvalue":1,"recipe":1,"val":1,"protobuf.serializer.deserialize":1}
,"valuehelper.nullsafestoredvalue":{"(barray":1,"(ms.toarray":1}
,"(barray":{"nvpairs)":1}
,"nvpairs)":{"class":1}
,"recipe2":{"deserializevalue":1,"recipe":1}
,"(terracotta.ehcache.thrift.storedvalue":{"value)":1}
,"value)":{"{memorystream":1}
,"(value.value":{"binaryvalue)":1}
,"binaryvalue)":{"ms.seek":1}
,"ms.seek":{"seekorigin.begin)":1}
,"seekorigin.begin)":{"bsonreader":1}
,"bsonreader":{"reader":1,"(ms)":1}
,"reader":{"=new":1}
,"=serializer.deserialize":{"<recipe2>":1}
,"<recipe2>":{"(reader)":1}
,"(reader)":{"return":1}
,"{value":{"val":1}
,"val":{"=new":1,"class":1}
,"val.stringvalue":{"=key":1}
,"=key":{"return":1}
,"(value":{"serializedkey)":1}
,"serializedkey.stringvalue":{"class":1}
,"(recipeproject.recipestructure":{"objectvalue)":1}
,"{dictionary":{"<string":1}
,"nvpairs.add":{"(key_name":1}
,"(key_name":{"objectvalue.name)":1}
,"objectvalue.name)":{"memorystream":1}
,"protobuf.serializer.serialize":{"<recipeproject":1}
,"<recipeproject":{"recipestructure>":1}
,"recipestructure>":{"(ms":1,"(ms)":1}
,"(ms":{"objectvalue)":1}
,"(ms.toarray":{"nvpairs)":1}
,"recipeproject.recipestructure":{"deserializevalue":1}
,"(storedvalue":{"value)":1}
,"(value.value.binaryvalue)":{"return":1}
,"protobuf.serializer.deserialize":{"<recipeproject":1}
,"single-language":{"serialization":1,"cases":1}
,"cases":{"necessary":1}
,"necessary":{"create":1}
,"create":{"serializer\u002Fdeserializer":1}
,"leverage":{".net\u0027s":1}
,".net\u0027s":{"native":1}
,"native":{"binary":1,"serialization":1}
,"binary":{"serialization":1}
,"including":{"provided":1}
,"provided":{"csharpnativeserializer":1}
,"csharpnativeserializer":{"class":1,"<string":1,"available":1}
,"cache":{"operations":1,"<string":1}
,"operations":{"example":1}
,"icachemanager":{"manager":1}
,"manager":{"=xplatform.createcachemanager":1}
,"=xplatform.createcachemanager":{"icache":1}
,"icache":{"cache":1}
,"string>":{"=manage.getcache":1,"())":1}
,"=manage.getcache":{"cachename":1}
,"cachename":{"new":1}
,"new":{"csharpnativeserializer":1}
,"())":{"api":1}
,"api":{"documentation":1}
,"documentation":{"csharpnativeserializer":1}
,"available":{"\u002Fapis\u002Fcsharp\u002Fapidoc\u002Fdirectory":1}
,"\u002Fapis\u002Fcsharp\u002Fapidoc\u002Fdirectory":{"kit":1}
,"kit":{"information":1}
,"information":{".net":1}
,"refer":{"http:\u002F\u002Fmsdn.microsoft.com\u002Fen-us\u002Flibrary\u002F7ay27kt9":1}
,"http:\u002F\u002Fmsdn.microsoft.com\u002Fen-us\u002Flibrary\u002F7ay27kt9":{"28v=vs.90":1}
,"28v=vs.90":{"29.aspx":1}
,"29.aspx":{"don":1}
,"don":{"added":1}
,"added":{"link":1}
}
;Search.control.loadWordPairs(pairs);
