var pairs =
{
"general":{"questions":1}
,"questions":{"what\u0027s":1}
,"what\u0027s":{"difference":1}
,"difference":{"bigmemory":1}
,"bigmemory":{"bigmemory":1,"max":1,"in-memory":1,"overview":1}
,"max":{"bigmemory":1,"distributed":1}
,"in-memory":{"data":1,"management":1}
,"data":{"management":1,"sharing":1}
,"management":{"single":1,"across":1}
,"single":{"jvm":1}
,"jvm":{"(in-process)":1,"enables":1,"starts":1,"(i.e":1}
,"(in-process)":{"bigmemory":1}
,"distributed":{"in-memory":1}
,"across":{"array":1}
,"array":{"servers":1,"platforms":1,"engage":1,"terracotta":1,"processes":1,"process":1,"designed":1}
,"servers":{"max":1}
,"overview":{"platforms":1}
,"platforms":{"terracotta":1,"jvms":1,"listed":1}
,"terracotta":{"software":1,"support":1,"designed":1,"client":1,"terracotta":1,"server":1,"clients":1}
,"software":{"run":1}
,"run":{"application":1}
,"application":{"stacks":1,"server":1,"runs":1}
,"stacks":{"terracotta":1}
,"support":{"terracotta":1}
,"designed":{"work":1,"provide":1}
,"work":{"broad":1}
,"broad":{"array":1}
,"jvms":{"application":1}
,"server":{"versions":1,"array":1,"container)":1}
,"versions":{"possible":1}
,"possible":{"supported":1}
,"supported":{"platforms":1}
,"listed":{"release":1}
,"release":{"platform":1}
,"platform":{"compatibility":1}
,"compatibility":{"information":1}
,"information":{"terracotta":1}
,"client":{"terracotta":1,"functionality":1,"automatically":1}
,"functionality":{"java":1}
,"java":{"library":1,"application":1}
,"library":{"operates":1}
,"operates":{"inside":1}
,"inside":{"jvm":1}
,"enables":{"clustering":1}
,"clustering":{"jvm":1,"services":1}
,"starts":{"code":1}
,"code":{"called":1}
,"called":{"initializes":1}
,"initializes":{"terracotta":1}
,"automatically":{"connects":1}
,"connects":{"terracotta":1}
,"engage":{"clustering":1}
,"services":{"lock":1}
,"lock":{"manager":1}
,"manager":{"object":1,"memory":1,"terracotta":1}
,"object":{"manager":1}
,"memory":{"manager":1}
,"processes":{"coordinate":1}
,"coordinate":{"data":1}
,"sharing":{"among":1}
,"among":{"terracotta":1}
,"clients":{"cluster":1}
,"cluster":{"terracotta":1}
,"process":{"simple":1}
,"simple":{"java":1}
,"runs":{"directly":1}
,"directly":{"jvm":1}
,"(i.e":{"without":1}
,"without":{"application":1}
,"container)":{"terracotta":1}
,"provide":{"maximal":1}
,"maximal":{"high":1}
,"high":{"availability":1}
,"availability":{"scalability":1}
}
;Search.control.loadWordPairs(pairs);
