var pairs =
{
"troubleshooting":{"cases":1}
,"cases":{"terracotta":1}
,"terracotta":{"cluster":1,"return":1,"\u002F\u002Fmgr":1,"clustering":1,"client":1,"nodejoined":1,"clients":1}
,"cluster":{"events":1,"exists":1,"information":1,"=mgr.getcluster":1,"code":1,"checking":1,"online":1}
,"events":{"api":1,"jvm":1,"generated":1}
,"api":{"behaves":1}
,"behaves":{"expected":1}
,"expected":{"unexpected":1}
,"unexpected":{"results":1}
,"results":{"occur":1}
,"occur":{"circumstances":1}
,"circumstances":{"described":1}
,"described":{"below":1}
,"below":{"getcluster":1}
,"getcluster":{"returns":1,"terracotta":1}
,"returns":{"null":1}
,"null":{"programmatically":1,"even":1}
,"programmatically":{"created":1,"(without":1,"cachemanager":1}
,"created":{"cachemanagers":1,"configured":1}
,"cachemanagers":{"cachemanager":1}
,"cachemanager":{"instance":1,"mgr":1,"\u002F\u002Fmycache":1}
,"instance":{"created":1}
,"configured":{"programmatically":1}
,"(without":{"ehcache.xml":1}
,"ehcache.xml":{"external":1}
,"external":{"configuration":1}
,"configuration":{"resource)":1}
,"resource)":{"getcluster":1}
,"return":{"null":1}
,"even":{"terracotta":1}
,"exists":{"ensure":1}
,"ensure":{"cluster":1}
,"information":{"returned":1,"cachecluster":1}
,"returned":{"case":1}
,"case":{"cache":1}
,"cache":{"clustered":1,"cache":1,"=mgr.getehcache":1}
,"clustered":{"terracotta":1}
,"\u002F\u002Fmgr":{"created":1}
,"mgr":{"=new":1}
,"=new":{"cachemanager":1}
,"\u002F\u002Fmycache":{"terracotta":1}
,"clustering":{"cache":1}
,"=mgr.getehcache":{"mycache":1}
,"mycache":{"\u002F\u002Fa":1}
,"\u002F\u002Fa":{"terracotta":1}
,"client":{"started":1}
,"started":{"making":1}
,"making":{"available":1}
,"available":{"cluster":1}
,"cachecluster":{"cluster":1}
,"=mgr.getcluster":{"terracotta":1}
,"nodejoined":{"current":1,"event":1,"events":1}
,"current":{"node":1}
,"node":{"68163}":1,"joins":1,"may":1,"cluster":1}
,"68163}":{"current":1}
,"joins":{"cluster":1}
,"code":{"adding":1}
,"adding":{"topology":1}
,"topology":{"listener":1}
,"listener":{"runs":1}
,"runs":{"current":1}
,"may":{"receive":1}
,"receive":{"nodejoined":1}
,"event":{"detect":1}
,"detect":{"current":1}
,"checking":{"whether":1}
,"whether":{"cluster":1}
,"online":{"cluster.addtopologylistener":1}
,"cluster.addtopologylistener":{"(cachelistener)":1}
,"(cachelistener)":{"(cluster.isclusteronline":1}
,"(cluster.isclusteronline":{"())":1}
,"())":{"{cachelistener.clusteronline":1,"multiple":1}
,"{cachelistener.clusteronline":{"(cluster.getcurrentnode":1}
,"(cluster.getcurrentnode":{"())":1}
,"multiple":{"nodejoined":1,"terracotta":1}
,"jvm":{"multiple":1,"remote":1}
,"clients":{"exist":1,"able":1,"generated":1}
,"exist":{"jvm":1}
,"generated":{"jvm":1,"nodejoined":1}
,"remote":{"clients":1}
,"able":{"differentiate":1}
,"differentiate":{"clients":1}
}
;Search.control.loadWordPairs(pairs);
