var pairs =
{
"editing":{"configuration":1}
,"configuration":{"existing":1,"reload":1,"following":1,"terracotta":1,"source":1,"mismatch":1}
,"existing":{"server":1,"live":1,"server\u0027s":1}
,"server":{"edit":1,"attempt":1,"following":1,"instead":1,"topology":1,"clients":1,"array":1}
,"edit":{"configuration":1,"existing":1,"server\u0027s":1}
,"live":{"server":1}
,"attempt":{"reload":1}
,"reload":{"configuration":1,"operation":1,"message":1}
,"operation":{"fail":1,"able":1}
,"fail":{"however":1,"remain":1}
,"however":{"successfully":1}
,"successfully":{"edit":1}
,"server\u0027s":{"configuration":1,"<server>":1}
,"following":{"steps":1}
,"steps":{"remove":1,"removing":1}
,"remove":{"server":1}
,"removing":{"existing":1}
,"instead":{"deleting":1}
,"deleting":{"server\u0027s":1}
,"<server>":{"block":1}
,"block":{"comment":1,"changed":1,"tmc\u0027s":1}
,"comment":{"don":1}
,"don":{"added":1}
,"added":{"link":1}
,"link":{"edit":1}
,"changed":{"values":1}
,"values":{"add":1}
,"add":{"(or":1}
,"(or":{"uncomment)":1}
,"uncomment)":{"edited":1}
,"edited":{"<server>":1}
,"tmc\u0027s":{"change":1}
,"change":{"server":1}
,"topology":{"panel":1}
,"panel":{"click":1}
,"click":{"reload":1}
,"message":{"appears":1}
,"appears":{"result":1}
,"result":{"reload":1}
,"able":{"edit":1}
,"clients":{"load":1}
,"load":{"configuration":1}
,"terracotta":{"server":1}
,"array":{"clients":1}
,"source":{"fail":1}
,"remain":{"connected":1}
,"connected":{"tsa":1}
,"tsa":{"due":1}
,"due":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
