var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fclient-reconnect-window":{"section":1}
,"section":{"lets":1}
,"lets":{"declare":1}
,"declare":{"window":1}
,"window":{"time":1,"client":1,"lead":1,"lowers":1,"effect":1}
,"time":{"servers":1,"window":1}
,"servers":{"allow":1}
,"allow":{"disconnected":1}
,"disconnected":{"clients":1}
,"clients":{"reconnect":1}
,"reconnect":{"cluster":1}
,"cluster":{"client":1,"paused":1,"tuning":1}
,"client":{"outside":1,"rejoin":1,"value":1,"server":1}
,"outside":{"window":1}
,"rejoin":{"new":1}
,"new":{"client":1}
,"value":{"specified":1,"note":1}
,"specified":{"seconds":1}
,"seconds":{"default":1,"adjusting":1}
,"default":{"120":1}
,"120":{"seconds":1}
,"adjusting":{"value":1}
,"note":{"too-short":1}
,"too-short":{"reconnection":1}
,"reconnection":{"window":1,"executed":1,"properties":1}
,"lead":{"unsuccessful":1}
,"unsuccessful":{"reconnections":1}
,"reconnections":{"during":1}
,"during":{"failure":1}
,"failure":{"recovery":1}
,"recovery":{"too-long":1}
,"too-long":{"window":1}
,"lowers":{"efficiency":1}
,"efficiency":{"cluster":1}
,"paused":{"time":1}
,"effect":{"information":1}
,"information":{"client":1}
,"server":{"reconnection":1}
,"executed":{"terracotta":1}
,"terracotta":{"cluster":1}
,"tuning":{"reconnection":1}
,"properties":{"high-availability":1}
,"high-availability":{"environment":1,"guide":1}
,"environment":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"high-availability":1}
}
;Search.control.loadWordPairs(pairs);
