var pairs =
{
"setting":{"server":1}
,"server":{"keychain":1,"configuration":1,"starts":1,"local":1,"connect":1,"create":1,"configuration\u0027s":1}
,"keychain":{"keystore":1,"file":1,"script":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"keystore":{"certificate":1,"entry":1,"password":1,"default":1,"example":1}
,"certificate":{"entry":1,"keystore":1}
,"entry":{"protected":1,"local":1,"entry":1,"every":1,"server1":1,"server2":1,"server2username@172.16.254.2:9530":1}
,"protected":{"passwords":1}
,"passwords":{"stored":1,"using":1}
,"stored":{"server":1,"creating":1}
,"file":{"location":1,"specified":1,"example":1,"searched":1,"called":1,"following":1,"named":1,"stores":1,"switch":1,"exist":1}
,"location":{"keychain":1}
,"specified":{"value":1,"server":1,"username":1}
,"value":{"<url>":1,"server":1,"<user>":1,"<security>\u002F<auth>\u002F<user>":1}
,"<url>":{"element":1}
,"element":{"<keychain>":1,"server\u0027s":1,"(including":1,"<certificate-uri>":1,"exactly":1}
,"<keychain>":{"element":1}
,"server\u0027s":{"configuration":1,"keystore":1,"certificate":1}
,"configuration":{"file":1,"server":1,"example":1}
,"example":{"server":1,"keychain":1,"create":1,"above":1}
,"starts":{"keychain":1}
,"searched":{"user\u0027s":1,"server1":1}
,"user\u0027s":{"(process":1}
,"(process":{"owner\u0027s)":1}
,"owner\u0027s)":{"home":1}
,"home":{"directory":1}
,"directory":{"configuration":1,"creating":1}
,"called":{"server1keychain.tkc":1}
,"server1keychain.tkc":{"searched":1,"jks:server1alias@\u002Fthe\u002Fpath\u002Fkeystore-file.jks":1,"tc:\u002F\u002Fserver2username@172.16.254.2:9530":1}
,"server1":{"started":1,"configuration":1,"keychain":1,"added":1}
,"started":{"keychain":1}
,"following":{"entries":1}
,"entries":{"entry":1,"created":1,"remote":1}
,"local":{"server\u0027s":1,"server":1}
,"every":{"server":1}
,"connect":{"entries":1}
,"created":{"using":1}
,"using":{"keychain":1,"obfuscation":1,"encrypted":1}
,"script":{"found":1,"operation":1}
,"found":{"terracotta":1}
,"terracotta":{"kit\u0027s":1,"management":1,"used":1}
,"kit\u0027s":{"tools\u002Fsecurity\u002Fbin":1}
,"tools\u002Fsecurity\u002Fbin":{"directory":1}
,"creating":{"entry":1,"entries":1}
,"create":{"entry":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"password":{"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1,"associate":1,"used":1,"want":1,"jks:server1alias@\u002Fthe\u002Fpath\u002Fkeystore-file.jks":1}
,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":{"<keychain-file>":1,"server1keychain.tkc":1,"server2keychain.tkc":1}
,"<keychain-file>":{"<certificate-uri>":1,"file":1}
,"<certificate-uri>":{"<keychain-file>":1,"uri":1,"match":1,"prompted":1}
,"named":{"server":1}
,"configuration\u0027s":{"<keychain>\u002F<url>":1,"<ssl>\u002F<certificate>":1,"<security>\u002F<auth>\u002F<user>":1}
,"<keychain>\u002F<url>":{"element":1}
,"(including":{"correct":1}
,"correct":{"path)":1}
,"path)":{"<certificate-uri>":1}
,"uri":{"value":1,"enter":1}
,"<ssl>\u002F<certificate>":{"element":1}
,"match":{"server":1}
,"exactly":{"including":1}
,"including":{"path":1}
,"path":{"keystore":1}
,"default":{"keychain":1,"example":1}
,"stores":{"passwords":1}
,"obfuscation":{"scheme":1}
,"scheme":{"requiring":1,"using":1}
,"requiring":{"(hyphen":1}
,"(hyphen":{"capital":1}
,"capital":{"letter":1}
,"letter":{"keychain":1}
,"operation":{"file":1}
,"switch":{"secure":1}
,"secure":{"encryption-based":1,"server\u0027s":1}
,"encryption-based":{"scheme":1}
,"encrypted":{"keychains":1}
,"keychains":{"keychain":1}
,"exist":{"add":1}
,"add":{"option":1}
,"option":{"create":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"prompted":{"enter":1}
,"enter":{"password":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"associate":{"uri":1,"url":1,"entry":1}
,"used":{"secure":1,"default":1}
,"above":{"enter":1}
,"jks:server1alias@\u002Fthe\u002Fpath\u002Fkeystore-file.jks":{"terracotta":1,"successfully":1}
,"management":{"console":1}
,"console":{"-keychain":1}
,"-keychain":{"client":1}
,"client":{"enter":1}
,"want":{"associate":1}
,"url":{"server1pass":1}
,"server1pass":{"confirm":1,"password":1}
,"confirm":{"password":1}
,"successfully":{"stored":1}
,"remote":{"servers":1}
,"servers":{"entries":1,"format":1}
,"format":{"tc:\u002F\u002F<user>@<host>":1}
,"tc:\u002F\u002F<user>@<host>":{"<group-port>":1}
,"<group-port>":{"note":1}
,"note":{"value":1}
,"<user>":{"specified":1}
,"<security>\u002F<auth>\u002F<user>":{"related":1,"specified":1}
,"related":{"user":1}
,"user":{"running":1}
,"running":{"process":1}
,"process":{"owner":1}
,"owner":{"value":1}
,"username":{"terracotta":1}
,"server2":{"server1":1,"keychain":1}
,"tc:\u002F\u002Fserver2username@172.16.254.2:9530":{"keychain":1,"prompted":1}
,"server2username@172.16.254.2:9530":{"entry":1}
,"added":{"server2":1}
,"server2keychain.tkc":{"tc:\u002F\u002Fserver1@172.16.254.1:9530":1}
}
;Search.control.loadWordPairs(pairs);
