var pairs =
{
"configuring":{"ssl-based":1}
,"ssl-based":{"security":1}
,"security":{"learn":1,"cluster":1,"enabling":1}
,"learn":{"secure":1}
,"secure":{"sockets":1,"enterprise":1}
,"sockets":{"layer":1}
,"layer":{"(ssl)":1}
,"(ssl)":{"encryption":1}
,"encryption":{"certificate-based":1}
,"certificate-based":{"authentication":1}
,"authentication":{"secure":1}
,"enterprise":{"versions":1}
,"versions":{"terracotta":1}
,"terracotta":{"clusters":1,"clients":1,"cluster":1}
,"clusters":{"following":1}
,"following":{"sections":1}
,"sections":{"security":1}
,"cluster":{"setting":1,"reduces":1}
,"setting":{"server":1}
,"server":{"security":1}
,"enabling":{"ssl":1}
,"ssl":{"terracotta":1,"info":1}
,"clients":{"note":1}
,"note":{"using":1}
,"using":{"ssl":1}
,"reduces":{"performance":1}
,"performance":{"due":1}
,"due":{"overhead":1}
,"overhead":{"introduced":1}
,"introduced":{"encrypting":1}
,"encrypting":{"inter-node":1}
,"inter-node":{"communication":1}
,"communication":{"ffc-this":1}
,"ffc-this":{"content":1}
,"content":{"closer":1}
,"closer":{"information":1}
,"information":{"relating":1}
,"relating":{"ssl":1}
,"info":{"ended":1}
,"ended":{"migration":1}
,"migration":{"probably":1}
,"probably":{"better":1}
,"better":{"place":1}
}
;Search.control.loadWordPairs(pairs);
