var pairs =
{
"grouping":{"results":1,"aggregation":1}
,"results":{"addition":1,"ehcache":1,"attribute":1,"query.includeaggregator":1,"back":1,"results":1,"=query.execute":1,"(result":1}
,"addition":{"sorting":1}
,"sorting":{"results":1}
,"ehcache":{"search":1}
,"search":{"interface":1,"<searchable>":1,"attributes":1}
,"interface":{"provides":1}
,"provides":{"grouping":1}
,"aggregation":{"functionality":1,"average":1}
,"functionality":{"let\u0027s":1}
,"let\u0027s":{"try":1}
,"try":{"modifying":1}
,"modifying":{"sample":1}
,"sample":{"code":1}
,"code":{"exercise":1}
,"exercise":{"features":1}
,"features":{"create":1}
,"create":{"configuration":1,"new":1,"group.java":1,"compile":1}
,"configuration":{"file":1,"<ehcache":1}
,"file":{"create":1,"called":1}
,"new":{"configuration":1,"cache":1}
,"called":{"ehcache-group.xml":1,"group":1}
,"ehcache-group.xml":{"classpath":1}
,"classpath":{"add":1}
,"add":{"new":1,"gender":1,"searchattribute":1}
,"cache":{"called":1,"manager":1,"dataset":1}
,"group":{"we\u0027re":1,"<searchable>":1,"import":1,"{public":1,"\u002F\u002Fcreate":1,"program":1}
,"we\u0027re":{"going":1}
,"going":{"add":1}
,"gender":{"attribute":1,"\u0022\u002F>":1,"=dataset.getsearchattribute":1,"\u002F\u002Fthe":1,"query.includeaggregator":1,"alphabetical":1,"thegender":1,"public":1,"final":1,"female":1,"male":1,"count":1}
,"attribute":{"person":1,"<integer>":1,"<string>":1,"<float>":1,"perform":1}
,"person":{"class":1,"janeausten":1,"jane":1,"charlesdickens":1,"charles":1,"janedoe":1,"alexsmith":1,"alex":1,"{private":1,"(final":1}
,"class":{"we\u0027ll":1,"called":1,"group":1,"person":1}
,"we\u0027ll":{"add":1,"query":1}
,"searchattribute":{"configuration":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"sampleconfig":1,"hello-world":1,"crud":1,"search":1,"height":1,"weight":1,"bodymassindex":1,"sort":1,"group":1,"gender":1,"bmi":1}
,"sampleconfig":{"maxbyteslocalheap=\u0022":1}
,"maxbyteslocalheap=\u0022":{"64m":1}
,"64m":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"hello-world":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<cache":1,"<searchattribute":1,"<\u002Fsearchable>":1}
,"crud":{"\u0022\u002F>":1}
,"<searchable>":{"<searchattribute":1}
,"<searchattribute":{"name=\u0022":1}
,"height":{"\u0022\u002F>":1,"=dataset.getsearchattribute":1,"attribute":1,"bmi":1,"avgheight":1,"private":1,"final":1,"public":1,"*(float)":1,"weight=\u0022":1,"66.0":1,"69.0":1,"65.0":1}
,"weight":{"\u0022\u002F>":1,"private":1,"public":1,"\u002F((float)":1,"lbs":1}
,"bodymassindex":{"<\u002Fsearchable>":1}
,"<\u002Fsearchable>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"<cache":1,"<\u002Fehcache>":1}
,"sort":{"<searchable>":1,"data":1}
,"bmi":{"expression=\u0022":1,"=dataset.getsearchattribute":1,"\u002F\u002Fcreate":1,"gender":1,"avgbmi)":1,"22.242641":1,"23.625288":1,"26.622484":1}
,"expression=\u0022":{"value.getbodymassindex":1}
,"value.getbodymassindex":{"\u0022\u002F>":1}
,"<\u002Fehcache>":{"create":1}
,"group.java":{"create":1}
,"compile":{"java":1}
,"java":{"class":1}
,"import":{"java.util.list":1,"net.sf.ehcache.cache":1,"net.sf.ehcache.cachemanager":1,"net.sf.ehcache.element":1,"net.sf.ehcache.search.attribute":1,"net.sf.ehcache.search.direction":1,"net.sf.ehcache.search.query":1,"net.sf.ehcache.search.result":1,"net.sf.ehcache.search.results":1,"net.sf.ehcache.search.aggregator.aggregators":1}
,"java.util.list":{"import":1}
,"net.sf.ehcache.cache":{"import":1}
,"net.sf.ehcache.cachemanager":{"import":1}
,"net.sf.ehcache.element":{"import":1}
,"net.sf.ehcache.search.attribute":{"import":1}
,"net.sf.ehcache.search.direction":{"import":1}
,"net.sf.ehcache.search.query":{"import":1}
,"net.sf.ehcache.search.result":{"import":1}
,"net.sf.ehcache.search.results":{"import":1}
,"net.sf.ehcache.search.aggregator.aggregators":{"public":1}
,"public":{"class":1,"static":1,"person":1,"string":1,"int":1,"float":1,"long":1}
,"{public":{"static":1}
,"static":{"void":1,"class":1}
,"void":{"main":1}
,"main":{"(final":1}
,"(final":{"string":1,"long":1}
,"string":{"args)":1,"firstname":1,"lastname":1,"gender":1,"getfirstname":1,"getlastname":1,"getgender":1,"tostring":1}
,"args)":{"{\u002F\u002Fcreate":1}
,"{\u002F\u002Fcreate":{"cache":1}
,"manager":{"using":1}
,"using":{"factory":1}
,"factory":{"method":1}
,"method":{"final":1}
,"final":{"cachemanager":1,"cache":1,"person":1,"query":1,"results":1,"string":1,"long":1,"int":1}
,"cachemanager":{"cachemanager":1,"=cachemanager.newinstance":1}
,"=cachemanager.newinstance":{"(group.class":1}
,"(group.class":{".getresource":1}
,".getresource":{"(\u0022\u002Fehcache-group.xml":1}
,"(\u0022\u002Fehcache-group.xml":{"\u0022))":1}
,"\u0022))":{"\u002F\u002Fretrieve":1}
,"\u002F\u002Fretrieve":{"sort":1}
,"data":{"final":1,"dataset.put":1,"\u002F\u002Fset.)":1}
,"dataset":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"group":1}
,"\u002F\u002Fcreate":{"objects":1,"query":1}
,"objects":{"final":1,"data":1}
,"janeausten":{"=new":1}
,"=new":{"person":1}
,"jane":{"austen":1,"doe":1}
,"austen":{"female":1}
,"female":{"*12":1,"count":1}
,"*12":{"130)":1,"160)":1,"145)":1}
,"130)":{"final":1}
,"charlesdickens":{"=new":1}
,"charles":{"dickens":1}
,"dickens":{"male":1}
,"male":{"*12":1,"count":1}
,"160)":{"final":1,"\u002F\u002Fput":1}
,"janedoe":{"=new":1}
,"doe":{"female":1}
,"145)":{"final":1}
,"alexsmith":{"=new":1}
,"alex":{"smith":1}
,"smith":{"*12":1}
,"\u002F\u002Fput":{"objects":1}
,"dataset.put":{"(new":1}
,"(new":{"element":1}
,"element":{"(janeausten.getid":1,"(charlesdickens.getid":1,"(janedoe.getid":1,"(alexsmith.getid":1}
,"(janeausten.getid":{"janeausten))":1}
,"janeausten))":{"dataset.put":1}
,"(charlesdickens.getid":{"charlesdickens))":1}
,"charlesdickens))":{"dataset.put":1}
,"(janedoe.getid":{"janedoe))":1}
,"janedoe))":{"dataset.put":1}
,"(alexsmith.getid":{"alexsmith))":1}
,"alexsmith))":{"\u002F\u002Ffetch":1}
,"\u002F\u002Ffetch":{"search":1}
,"attributes":{"we\u0027ll":1}
,"query":{"fetching":1,"object":1,"designed":1,"query":1,"=dataset.createquery":1,"final":1}
,"fetching":{"\u002F\u002Four":1}
,"\u002F\u002Four":{"results":1}
,"<integer>":{"height":1}
,"=dataset.getsearchattribute":{"height":1,"gender":1,"bmi":1}
,"<string>":{"gender":1}
,"<float>":{"bmi":1}
,"object":{"(this":1}
,"(this":{"query":1}
,"designed":{"select":1}
,"select":{"entire":1}
,"entire":{"data":1}
,"\u002F\u002Fset.)":{"final":1}
,"=dataset.createquery":{".addcriteria":1}
,".addcriteria":{"(height.gt":1}
,"(height.gt":{"*12))":1}
,"*12))":{"\u002F\u002Fgroup":1}
,"\u002F\u002Fgroup":{"gender":1}
,"perform":{"aggregations":1}
,"aggregations":{"\u002F\u002Fgender":1}
,"\u002F\u002Fgender":{"query.addgroupby":1}
,"query.addgroupby":{"(gender)":1}
,"(gender)":{"query.includeattribute":1,"\u002F\u002Finclude":1,"list":1}
,"query.includeattribute":{"(gender)":1}
,"\u002F\u002Finclude":{"aggregation":1,"count":1}
,"average":{"height":1,"bmi":1}
,"\u002F\u002Fthe":{"results":1}
,"query.includeaggregator":{"(aggregators.average":1,"(aggregators.count":1}
,"(aggregators.average":{"(height))":1,"(bmi))":1}
,"(height))":{"query.includeaggregator":1}
,"(bmi))":{"\u002F\u002Finclude":1}
,"count":{"members":1,"=(integer)":1,"count":1,"average":1}
,"members":{"gender":1}
,"(aggregators.count":{"())":1}
,"())":{"\u002F\u002Fmake":1,"{string":1}
,"\u002F\u002Fmake":{"results":1}
,"back":{"sorted":1}
,"sorted":{"gender":1}
,"alphabetical":{"order":1}
,"order":{"query.addorderby":1}
,"query.addorderby":{"(gender":1}
,"(gender":{"direction.ascending)":1}
,"direction.ascending)":{"\u002F\u002Fexecute":1}
,"\u002F\u002Fexecute":{"query":1}
,"=query.execute":{"\u002F\u002Fprint":1}
,"\u002F\u002Fprint":{"results":1}
,"(result":{"result":1}
,"result":{"results.all":1}
,"results.all":{"())":1}
,"{string":{"thegender":1}
,"thegender":{"=result.getattribute":1,"count":1}
,"=result.getattribute":{"(gender)":1}
,"list":{"<object>":1}
,"<object>":{"aggregatorresults":1}
,"aggregatorresults":{"=result.getaggregatorresults":1}
,"=result.getaggregatorresults":{"float":1}
,"float":{"avgheight":1,"avgbmi":1,"getbodymassindex":1}
,"avgheight":{"=(float)":1,"average":1}
,"=(float)":{"aggregatorresults.get":1}
,"aggregatorresults.get":{"(0)":1,"(1)":1,"(2)":1}
,"(0)":{"float":1}
,"avgbmi":{"=(float)":1}
,"(1)":{"integer":1}
,"integer":{"count":1}
,"=(integer)":{"aggregatorresults.get":1}
,"(2)":{"system.out.println":1}
,"system.out.println":{"gender":1}
,"avgbmi)":{"public":1}
,"{private":{"final":1}
,"firstname":{"private":1,"final":1,"public":1,"lastname=\u0022":1}
,"private":{"final":1,"string":1}
,"lastname":{"private":1,"final":1,"public":1,"height=\u0022":1}
,"long":{"private":1,"final":1,"getid":1}
,"int":{"height":1,"weight":1,"weight)":1,"getheight":1,"getweight":1}
,"weight)":{"{this.id":1}
,"{this.id":{"=id":1}
,"=id":{"this.firstname":1}
,"this.firstname":{"=firstname":1}
,"=firstname":{"this.lastname":1}
,"this.lastname":{"=lastname":1}
,"=lastname":{"this.gender":1}
,"this.gender":{"=gender":1}
,"=gender":{"this.height":1}
,"this.height":{"=height":1}
,"=height":{"this.weight":1}
,"this.weight":{"=weight":1}
,"=weight":{"public":1}
,"getfirstname":{"{return":1}
,"{return":{"firstname":1,"lastname":1,"gender":1,"height":1,"weight":1,"((float)":1,"public":1,"[id=\u0022":1}
,"getlastname":{"{return":1}
,"getgender":{"{return":1}
,"getheight":{"{return":1}
,"getweight":{"{return":1}
,"getbodymassindex":{"{return":1,"execute":1}
,"((float)":{"weight":1}
,"\u002F((float)":{"height":1}
,"*(float)":{"height))":1}
,"height))":{"*703":1}
,"*703":{"public":1}
,"getid":{"{return":1}
,"tostring":{"{return":1}
,"[id=\u0022":{"firstname=\u0022":1}
,"firstname=\u0022":{"firstname":1}
,"lastname=\u0022":{"lastname":1}
,"height=\u0022":{"height":1}
,"weight=\u0022":{"weight":1}
,"lbs":{"bmi=\u0022":1}
,"bmi=\u0022":{"getbodymassindex":1}
,"execute":{"run":1}
,"run":{"group":1}
,"program":{"terminal":1}
,"terminal":{"output":1}
,"output":{"gender":1}
,"66.0":{"average":1}
,"22.242641":{"gender":1}
,"69.0":{"average":1}
,"23.625288":{"gender":1}
,"65.0":{"average":1}
,"26.622484":{"next":1}
,"next":{"step":1}
,"step":{"next":1,"adding":1}
,"adding":{"server":1}
,"server":{"array":1}
}
;Search.control.loadWordPairs(pairs);
