var pairs =
{
"serialization":{"securing":1}
,"securing":{"against":1}
,"against":{"untrusted":1}
,"untrusted":{"clients":1}
,"clients":{"typically":1,"reading":1,"trusted":1}
,"typically":{"java":1}
,"java":{"objects":1,"deserialization":1}
,"objects":{"serialized":1,"included":1}
,"serialized":{"writing":1,"stream":1}
,"writing":{"cache":1}
,"cache":{"deserialized":1,"cache":1,"clients":1,"nature":1}
,"deserialized":{"clients":1,"java":1}
,"reading":{"cache":1}
,"trusted":{"common":1}
,"common":{"deployment":1}
,"deployment":{"pattern)":1}
,"pattern)":{"java":1}
,"deserialization":{"poses":1,"used":1,"process":1,"happens":1,"known":1}
,"poses":{"security":1}
,"security":{"issue":1}
,"issue":{"however":1,"per":1,"deserialization":1,"technical":1,"examples":1}
,"however":{"cases":1}
,"cases":{"client":1}
,"client":{"attacker":1,"specially":1,"side":1}
,"attacker":{"deserialization":1}
,"used":{"inject":1}
,"inject":{"malicious":1}
,"malicious":{"code":1}
,"code":{"client":1,"execution":1}
,"specially":{"crafted":1}
,"crafted":{"objects":1}
,"included":{"serialized":1}
,"stream":{"bytes":1}
,"bytes":{"deserialized":1}
,"process":{"lead":1}
,"lead":{"arbitrary":1}
,"arbitrary":{"code":1}
,"execution":{"cache":1}
,"nature":{"security":1}
,"per":{"deserialization":1}
,"happens":{"client":1}
,"side":{"attacks":1}
,"attacks":{"mitigated":1}
,"mitigated":{"security":1}
,"known":{"issue":1}
,"technical":{"community":1}
,"community":{"result":1}
,"result":{"various":1}
,"various":{"solutions":1}
,"solutions":{"(such":1}
,"(such":{"blacklists\u002Fwhitelists":1}
,"blacklists\u002Fwhitelists":{"classes)":1}
,"classes)":{"address":1}
,"address":{"issue":1}
,"examples":{"notsoserial":1}
,"notsoserial":{"(https:\u002F\u002Fgithub.com\u002Fkantega\u002Fnotsoserial\u002F)":1}
,"(https:\u002F\u002Fgithub.com\u002Fkantega\u002Fnotsoserial\u002F)":{"ikkisoft":1}
,"ikkisoft":{"serialkiller":1}
,"serialkiller":{"(https:\u002F\u002Fgithub.com\u002Fikkisoft\u002Fserialkiller\u002F)":1}
,"(https:\u002F\u002Fgithub.com\u002Fikkisoft\u002Fserialkiller\u002F)":{"validatingobjectinputstream":1}
,"validatingobjectinputstream":{"apache":1}
,"apache":{"commons":1}
}
;Search.control.loadWordPairs(pairs);
