var pairs =
{
"process":{"diagram":1,"establishing":1,"symmetrical":1}
,"diagram":{"following":1,"illustrates":1}
,"following":{"diagram":1}
,"illustrates":{"flow":1}
,"flow":{"security":1}
,"security":{"information":1,"checks":1}
,"information":{"during":1,"terracotta":1}
,"during":{"initial":1,"lifetime":1}
,"initial":{"cluster":1}
,"cluster":{"connections":1,"startup":1,"during":1,"active":1,"client":1}
,"connections":{"shows":1}
,"shows":{"security-related":1}
,"security-related":{"file":1}
,"file":{"originates":1,"password":1}
,"originates":{"security":1}
,"terracotta":{"server":1,"client":1}
,"server":{"point":1,"cluster":1,"clients":1,"uri":1,"client":1}
,"point":{"view":1}
,"view":{"security":1}
,"checks":{"place":1,"occur":1}
,"place":{"time":1}
,"time":{"connection":1,"client":1}
,"connection":{"made":1,"requests":1,"request":1,"using":1,"takes":1}
,"made":{"node":1}
,"node":{"cluster":1}
,"startup":{"servers":1}
,"servers":{"connection":1,"named":1,"cluster":1,"fail":1,"terracotta":1}
,"requests":{"servers":1}
,"named":{"configuration":1}
,"configuration":{"connection":1}
,"request":{"server2":1,"terracotta":1}
,"server2":{"initiates":1,"using":1,"process":1,"authenticates":1}
,"initiates":{"process":1,"secure":1}
,"establishing":{"secure":1}
,"secure":{"connection":1}
,"using":{"ssl":1,"stored":1}
,"ssl":{"server1":1,"established":1}
,"server1":{"authenticates":1,"connection":1}
,"authenticates":{"server2":1,"authorizes":1}
,"stored":{"credentials":1}
,"credentials":{"credentials":1,"associated":1}
,"associated":{"role":1,"roles":1,"client":1}
,"role":{"authorizes":1}
,"authorizes":{"server2":1,"server1":1,"client":1}
,"symmetrical":{"server2":1}
,"client":{"initiates":1,"using":1,"communicate":1,"able":1,"point":1,"attempts":1,"uses":1,"username":1,"sends":1}
,"roles":{"client":1}
,"communicate":{"active":1}
,"active":{"server":1,"servers":1}
,"lifetime":{"client":1}
,"able":{"authenticate":1}
,"authenticate":{"active":1,"against":1}
,"clients":{"able":1}
,"against":{"servers":1}
,"fail":{"mirror":1}
,"mirror":{"servers":1}
,"occur":{"time":1}
,"attempts":{"connect":1}
,"connect":{"active":1}
,"uses":{"server":1}
,"uri":{"includes":1,"<server-address>":1,"initiates":1}
,"includes":{"client":1}
,"username":{"typical":1}
,"typical":{"(non-secure)":1}
,"(non-secure)":{"uri":1}
,"<server-address>":{"<port>":1}
,"<port>":{"uri":1,"secure":1}
,"takes":{"form":1}
,"form":{"<client-username>@<server-address>":1}
,"<client-username>@<server-address>":{"<port>":1}
,"established":{"server":1}
,"sends":{"password":1}
,"password":{"fetched":1,"associated":1}
,"fetched":{"local":1}
,"local":{"keychain":1}
,"keychain":{"file":1}
}
;Search.control.loadWordPairs(pairs);
