var pairs =
{
"introduction":{"terracotta":1}
,"terracotta":{"clusters":1,"cluster":1,"management":1,"configuration":1,"kit":1}
,"clusters":{"secured":1}
,"secured":{"using":1}
,"using":{"authentication":1,"terracotta":1}
,"authentication":{"authorization":1}
,"authorization":{"encryption":1,"external":1}
,"encryption":{"built-in":1,"communications":1}
,"built-in":{"authentication":1}
,"external":{"directory":1}
,"directory":{"services":1}
,"services":{"certificate-based":1}
,"certificate-based":{"secure":1}
,"secure":{"sockets":1,"including":1}
,"sockets":{"layer":1}
,"layer":{"(ssl)":1}
,"(ssl)":{"encryption":1}
,"communications":{"nodes":1}
,"nodes":{"security":1}
,"security":{"terracotta":1,"enabled":1,"using":1}
,"cluster":{"includes":1,"ensures":1}
,"includes":{"server-server":1}
,"server-server":{"connections":1}
,"connections":{"client-server":1,"security":1,"terracotta":1}
,"client-server":{"connections":1}
,"enabled":{"globally":1}
,"globally":{"cluster":1}
,"ensures":{"every":1}
,"every":{"connection":1}
,"connection":{"secure":1}
,"including":{"connections":1}
,"management":{"server":1}
,"server":{"security":1}
,"configuration":{"tools":1}
,"tools":{"provided":1,"public":1}
,"provided":{"terracotta":1}
,"kit":{"standard":1}
,"standard":{"java":1,"digital":1}
,"java":{"tools":1}
,"public":{"key":1}
,"key":{"infrastructure":1}
,"infrastructure":{"(via":1}
,"(via":{"standard":1}
,"digital":{"x.509":1,"certificates)":1}
,"x.509":{"digital":1}
}
;Search.control.loadWordPairs(pairs);
