var pairs =
{
"jmx":{"authentication":1}
,"authentication":{"using":1}
,"using":{"keychain":1}
,"keychain":{"following":1,"locked":1,"entry":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"following":{"required":1,"entry":1,"format":1}
,"required":{"server-to-client":1}
,"server-to-client":{"rest-agent":1}
,"rest-agent":{"authorization":1,"communication":1}
,"authorization":{"every":1}
,"every":{"node":1}
,"node":{"cluster":1}
,"cluster":{"following":1}
,"entry":{"keychain":1,"following":1,"server2":1,"itself":1,"server":1}
,"locked":{"identical":1}
,"identical":{"secret":1}
,"secret":{"jmx:net.sf.ehcache:type=remoteagentendpoint":1}
,"jmx:net.sf.ehcache:type=remoteagentendpoint":{"addition":1}
,"addition":{"server-server":1}
,"server-server":{"rest-agent":1}
,"communication":{"authorized":1}
,"authorized":{"using":1}
,"format":{"jmx:\u002F\u002F<user>@<host>":1}
,"jmx:\u002F\u002F<user>@<host>":{"<group-port>":1}
,"<group-port>":{"note":1}
,"note":{"value":1}
,"value":{"<user>":1}
,"<user>":{"specified":1}
,"specified":{"server":1}
,"server":{"configuration\u0027s":1,"entry":1,"tsa":1}
,"configuration\u0027s":{"<security>\u002F<auth>\u002F<user>":1}
,"<security>\u002F<auth>\u002F<user>":{"related":1}
,"related":{"user":1}
,"user":{"running":1}
,"running":{"process":1}
,"process":{"owner":1}
,"owner":{"example":1}
,"example":{"create":1}
,"create":{"entry":1}
,"server2":{"server1":1}
,"server1":{"keychain":1}
,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":{"server1keychain.tkc":1}
,"server1keychain.tkc":{"jmx:\u002F\u002Fserver2username@172.16.254.2:9530":1}
,"jmx:\u002F\u002Fserver2username@172.16.254.2:9530":{"server":1}
,"itself":{"entry":1}
}
;Search.control.loadWordPairs(pairs);
