var pairs =
{
"clause":{"condition":1,"fetches":1}
,"condition":{"expression":1}
,"expression":{"associated":1,"((attribute":1}
,"associated":{"clause":1}
,"fetches":{"ehcache":1}
,"ehcache":{"elements":1}
,"elements":{"match":1}
,"match":{"particular":1,"charlist]":1}
,"particular":{"criterion":1}
,"criterion":{"general":1}
,"general":{"syntax":1}
,"syntax":{"condition":1}
,"((attribute":{"[=|":1}
,"[=|":{">=|":1}
,">=|":{"<=|":1}
,"<=|":{"!=|":1}
,"!=|":{"ilike":1}
,"ilike":{"value)":1,"example":1,"\u0027san*":1,"takes":1,"\u0027c*":1,"find":1,"\u0027*e*p*":1,"[charlist]":1}
,"value)":{"[and":1}
,"[and":{"(attribute":1,"example":1}
,"(attribute":{"[=|":1}
,"example":{"select":1}
,"select":{"*from":1,"city":1,"key":1}
,"*from":{"person":1,"searchable":1}
,"person":{"((age":1,"age":1,"(age":1}
,"((age":{"zip=94115)":1,"100":1}
,"zip=94115)":{"(time":1}
,"(time":{"fun":1}
,"fun":{"100))":1}
,"100))":{"examples":1,"select":1}
,"examples":{"select":1}
,"age":{"=18":1,"!=18":1,"<18":1,"select":1,"<=18":1,">=18":1,"boolean":1}
,"=18":{"select":1}
,"!=18":{"select":1}
,"<18":{"select":1}
,"<=18":{"select":1}
,">=18":{"ilike":1}
,"city":{"address":1,"ilike":1,"\u0027san":1}
,"address":{"city":1}
,"\u0027san*":{"note":1}
,"note":{"ilike":1,"takes":1}
,"takes":{"wildcard":1}
,"wildcard":{"character":1}
,"character":{"*for":1,"find":1,"zero":1,"specified":1}
,"*for":{"zero":1}
,"zero":{"characters":1}
,"characters":{"single":1,"_for":1,"match":1}
,"single":{"character":1}
,"find":{"\u0027cat":1,"elephant":1}
,"\u0027cat":{"\u0027cow":1,"exclude":1}
,"\u0027cow":{"select":1}
,"searchable":{"animal":1}
,"animal":{"ilike":1,"find":1,"\u0027c_t":1,"bigmemory":1}
,"\u0027c*":{"find":1}
,"exclude":{"\u0027cow":1,"weasel":1}
,"elephant":{"sheep":1}
,"sheep":{"exclude":1}
,"weasel":{"select":1}
,"\u0027*e*p*":{"example":1}
,"\u0027san":{"note":1}
,"_for":{"single":1}
,"\u0027c_t":{"find":1}
,"bigmemory":{"sql":1}
,"sql":{"support":1}
,"support":{"following":1}
,"following":{"ilike":1}
,"[charlist]":{"sets":1}
,"sets":{"ranges":1}
,"ranges":{"characters":1}
,"charlist]":{"charlist]":1,"matches":1}
,"matches":{"character":1}
,"specified":{"within":1}
,"within":{"brackets":1}
,"brackets":{"example":1}
,"boolean":{"operators":1}
,"operators":{"select":1}
,"key":{"value":1}
,"value":{"person":1}
,"(age":{"100":1}
,"100":{"zip":1}
,"zip":{"=20144)":1}
,"=20144)":{"select":1,"time":1,"(time":1}
,"time":{"10)":1}
,"10)":{"select":1}
}
;Search.control.loadWordPairs(pairs);
