var pairs =
{
"configuring":{"off-heap":1}
,"off-heap":{"store":1,"data":1,"memory":1,"1gb":1,"buffers":1,"cache":1,"area":1}
,"store":{"<<this":1,"extends":1,"memory":1,"subject":1,"non":1,"theoretically":1,"difference":1,"uses":1,"using":1,"note":1,"32-bit":1,"help":1,"tries":1,"off-heap":1,"configured":1,"overflows":1,"configuring":1,"done":1,"(maxentrieslocalheap)":1,"avoid":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1,"processes":1,"libraries":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs":1}
,"docs":{"ehc":1}
,"ehc":{"!>>":1}
,"!>>":{"off-heap":1}
,"extends":{"in-memory":1}
,"in-memory":{"store":1}
,"memory":{"outside":1,"store":1,"jvm":1,"off-heap":1,"may":1,"allocated":1,"configure":1,"allocate":1,"-xx:maxdirectmemorysize":1,"depends":1,"part":1,"requirements":1,"configured":1,"maximum":1,"space":1,"available":1,"64-bit":1,"hardware":1,"effectively":1,"left":1,"cause":1,"virtual":1,"process":1,"storage":1,"subject":1}
,"outside":{"object":1}
,"object":{"heap":1}
,"heap":{"store":1,"size":1,"separate":1,"allocated":1,"-xmx":1,"outofmemoryerror":1}
,"subject":{"java":1}
,"java":{"garbage":1,"-xx:maxdirectmemorysize=2g":1,"process":1,"lower":1,"issues":1,"cycles":1,"property":1}
,"garbage":{"collection":1}
,"collection":{"(gc)":1}
,"(gc)":{"limited":1}
,"limited":{"amount":1,"addressable":1}
,"amount":{"ram":1,"direct":1,"virtual":1,"physical":1,"heap-offload":1,"memory":1,"off-heap":1,"allocated":1}
,"ram":{"available":1,"likely":1,"due":1}
,"available":{"off-heap":1,"ram":1,"system":1,"java":1,"cache":1}
,"data":{"stored":1,"serializable":1,"overflowing":1,"model":1,"jvm":1,"stores":1}
,"stored":{"bytes":1}
,"bytes":{"data":1}
,"serializable":{"suitable":1,"data":1}
,"suitable":{"off-heap":1}
,"non":{"serializable":1}
,"overflowing":{"offheapmemorystore":1}
,"offheapmemorystore":{"simply":1}
,"simply":{"removed":1}
,"removed":{"warning":1}
,"warning":{"level":1,"logged":1}
,"level":{"log":1}
,"log":{"message":1}
,"message":{"emitted":1}
,"emitted":{"serialization":1}
,"serialization":{"deserialization":1}
,"deserialization":{"place":1}
,"place":{"putting":1}
,"putting":{"getting":1}
,"getting":{"off-heap":1}
,"theoretically":{"slower":1}
,"slower":{"memory":1}
,"difference":{"however":1}
,"however":{"mitigated":1,"note":1}
,"mitigated":{"involved":1}
,"involved":{"larger":1}
,"larger":{"heaps":1}
,"heaps":{"taken":1}
,"taken":{"account":1}
,"account":{"allocating":1}
,"allocating":{"direct":1,"3gb":1}
,"direct":{"memory":1}
,"jvm":{"off-heap":1,"allocate":1,"property":1,"java":1,"oracle":1,"requirements":1,"process":1,"may":1}
,"uses":{"direct-memory":1}
,"direct-memory":{"portion":1}
,"portion":{"jvm":1}
,"allocate":{"sufficient":1,"2gb":1,"least":1,"direct":1,"off-heap":1}
,"sufficient":{"direct":1}
,"using":{"jvm":1,"off-heap":1,"following":1}
,"property":{"maxdirectmemorysize":1}
,"maxdirectmemorysize":{"example":1,"added":1,"default":1}
,"example":{"allocate":1,"-xmx3g":1}
,"2gb":{"direct":1,"limit":1,"heap":1,"left":1}
,"-xx:maxdirectmemorysize=2g":{"direct":1}
,"may":{"shared":1,"default":1,"run":1,"cause":1,"<mmap>":1,"trigger":1,"true":1}
,"processes":{"allocate":1}
,"least":{"256mb":1,"100":1}
,"256mb":{"(or":1}
,"(or":{"preferably":1}
,"preferably":{"1gb)":1}
,"1gb)":{"direct":1}
,"allocated":{"off-heap":1,"-xmx":1,"maxdirectmemorysizemust":1,"within":1,"(with":1,"1mb":1}
,"note":{"following":1}
,"following":{"allocating":1,"everything":1,"xml":1,"programmatic":1}
,"configure":{"off-heap":1}
,"-xx:maxdirectmemorysize":{"default":1}
,"default":{"value":1,"equal":1,"particular":1}
,"value":{"direct":1,"maxdirectmemorysize":1,"allocated":1,"false":1}
,"depends":{"version":1,"process":1}
,"version":{"jvm":1}
,"oracle":{"hotspot":1}
,"hotspot":{"default":1}
,"equal":{"maximum":1}
,"maximum":{"heap":1,"amount":1,"virtual":1,"information":1}
,"size":{"(-xmx":1,"process":1,"available":1,"limit":1}
,"(-xmx":{"value)":1}
,"value)":{"although":1}
,"although":{"early":1}
,"early":{"versions":1}
,"versions":{"may":1}
,"particular":{"value":1,"operating-system":1}
,"added":{"local":1}
,"local":{"node\u0027s":1}
,"node\u0027s":{"startup":1}
,"startup":{"environment":1,"likely":1,"it\u0027s":1}
,"environment":{"direct":1}
,"part":{"java":1}
,"process":{"heap":1,"data":1,"model":1,"typically":1,"requires":1,"space":1}
,"separate":{"object":1}
,"-xmx":{"value":1,"example":1,"2047mb":1}
,"maxdirectmemorysizemust":{"exceed":1}
,"exceed":{"physical":1}
,"physical":{"ram":1,"memory":1}
,"likely":{"less":1,"occur":1,"-xms3g":1}
,"less":{"total":1}
,"total":{"available":1}
,"due":{"memory":1,"particular":1}
,"requirements":{"amount":1,"loading":1}
,"within":{"constraints":1}
,"constraints":{"available":1}
,"system":{"memory":1,"limitations":1,"amount":1,"using":1,"handle":1,"overhead":1}
,"configured":{"off-heap":1,"corresponding":1,"per-cache":1}
,"space":{"depends":1,"2gb":1,"code":1,"may":1}
,"model":{"(32-bit":1,"maximum":1}
,"(32-bit":{"64-bit)":1}
,"64-bit)":{"associated":1}
,"associated":{"operating":1}
,"operating":{"system":1,"systems":1}
,"limitations":{"amount":1,"operations":1}
,"virtual":{"memory":1,"address":1,"machine":1}
,"32-bit":{"jvms":1,"systems":1,"process":1,"operating":1,"jvm":1}
,"jvms":{"amount":1}
,"heap-offload":{"achieve":1}
,"achieve":{"limited":1}
,"addressable":{"memory":1,"space":1}
,"64-bit":{"systems":1}
,"systems":{"allow":1,"strict":1,"2gb":1}
,"allow":{"memory":1}
,"hardware":{"operating":1}
,"handle":{"32-bit":1}
,"strict":{"limitations":1}
,"effectively":{"managed":1}
,"managed":{"32-bit":1}
,"address":{"size":1}
,"typically":{"4gb":1}
,"4gb":{"32-bit":1,"addressable":1}
,"limit":{"maximum":1,"java":1}
,"lower":{"due":1,"values":1}
,"operating-system":{"(os)":1}
,"(os)":{"limitations":1}
,"operations":{"may":1,"used":1}
,"run":{"machine":1}
,"machine":{"(such":1,"start":1}
,"(such":{"mmap":1}
,"mmap":{"operations":1}
,"used":{"certain":1,"2047mb":1}
,"certain":{"apis)":1}
,"apis)":{"various":1}
,"various":{"jvm":1}
,"loading":{"shared":1}
,"libraries":{"code":1,"plus":1}
,"code":{"useful":1,"shared":1}
,"useful":{"rule":1}
,"rule":{"observe":1,"may":1}
,"observe":{"allocate":1}
,"left":{"-xmx":1,"off-heap":1}
,"-xmx3g":{"off-heap":1,"used":1}
,"1gb":{"breaking":1}
,"breaking":{"rule":1}
,"cause":{"outofmemoryerror":1,"error":1}
,"outofmemoryerror":{"startup":1,"likely":1,"configuring":1}
,"occur":{"point":1}
,"point":{"during":1}
,"during":{"jvm\u0027s":1}
,"jvm\u0027s":{"life":1}
,"life":{"java":1}
,"issues":{"afflicting":1}
,"afflicting":{"32-bit":1}
,"help":{"however":1}
,"everything":{"fit":1}
,"fit":{"4gb":1}
,"(with":{"-xmx2g)":1}
,"-xmx2g)":{"2gb":1}
,"requires":{"4gb":1}
,"plus":{"extra":1}
,"extra":{"operating":1}
,"overhead":{"allocating":1}
,"3gb":{"heap":1}
,"2047mb":{"off-heap":1}
,"error":{"startup":1}
,"it\u0027s":{"time":1}
,"time":{"grow":1}
,"grow":{"heap":1}
,"-xms3g":{"-xmx3g":1}
,"start":{"complain":1}
,"complain":{"soon":1}
,"soon":{"off-heap":1}
,"tries":{"allocate":1}
,"buffers":{"apis":1}
,"apis":{"java.util.zip.zipfile":1}
,"java.util.zip.zipfile":{"1.5":1}
,"1.5":{"jvm":1}
,"<mmap>":{"files":1}
,"files":{"memory":1}
,"trigger":{"outofmemoryerror":1,"warning":1}
,"corresponding":{"memory":1}
,"overflows":{"off-heap":1}
,"done":{"either":1}
,"either":{"xml":1,"method":1}
,"xml":{"programmatically":1,"configuration":1}
,"programmatically":{"either":1}
,"method":{"off-heap":1}
,"per-cache":{"basis":1}
,"basis":{"declarative":1}
,"declarative":{"configuration":1}
,"configuration":{"following":1,"creates":1,"options":1,"equivalent":1,"public":1}
,"creates":{"off-heap":1}
,"cache":{"in-heap":1,"utilize":1,"effect":1,"created":1,"createoffheapcache":1,"cache":1,"=new":1,"(config)":1}
,"in-heap":{"store":1}
,"(maxentrieslocalheap)":{"10,000":1}
,"10,000":{"elements":1}
,"elements":{"overflow":1,"using":1}
,"overflow":{"1-gigabyte":1}
,"1-gigabyte":{"off-heap":1}
,"area":{"<ehcache":1}
,"<ehcache":{"updatecheck=\u0022":1}
,"updatecheck=\u0022":{"false":1}
,"false":{"monitoring=\u0022":1,"<defaultcache":1,"<cache":1,"true":1,"maxbyteslocaloffheap":1}
,"monitoring=\u0022":{"dynamicconfig=\u0022":1}
,"dynamicconfig=\u0022":{"false":1}
,"<defaultcache":{"maxentrieslocalheap=\u0022":1}
,"maxentrieslocalheap=\u0022":{"10000":1}
,"10000":{"eternal=\u0022":1}
,"eternal=\u0022":{"true":1}
,"true":{"memorystoreevictionpolicy=\u0022":1,"maxbyteslocaloffheap=\u0022":1,"false":1,"enables":1,"minimum":1}
,"memorystoreevictionpolicy=\u0022":{"lru":1}
,"lru":{"statistics=\u0022":1,"overflowtooffheap=\u0022":1}
,"statistics=\u0022":{"false":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"sample-offheap-cache":1}
,"sample-offheap-cache":{"maxentrieslocalheap=\u0022":1,"10000)":1}
,"overflowtooffheap=\u0022":{"true":1}
,"maxbyteslocaloffheap=\u0022":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"configuration":1}
,"options":{"overflowtooffheap":1}
,"overflowtooffheap":{"values":1,"true":1}
,"values":{"may":1,"maxentrieslocalheap":1}
,"enables":{"cache":1}
,"utilize":{"off-heap":1}
,"storage":{"improve":1,"tiers":1}
,"improve":{"performance":1}
,"performance":{"off-heap":1,"degradation":1}
,"cycles":{"size":1}
,"maxbyteslocaloffheap":{"sets":1}
,"sets":{"amount":1}
,"effect":{"overflowtooffheap":1}
,"minimum":{"amount":1}
,"1mb":{"maximum":1}
,"information":{"sizing":1}
,"sizing":{"data":1,"storage":1}
,"stores":{"sizing":1}
,"tiers":{"maxentrieslocalheap":1}
,"maxentrieslocalheap":{"least":1,"trigger":1}
,"100":{"elements":1}
,"avoid":{"performance":1}
,"degradation":{"lower":1}
,"logged":{"programmatic":1}
,"programmatic":{"configuration":1}
,"equivalent":{"cache":1}
,"created":{"using":1}
,"public":{"cache":1}
,"createoffheapcache":{"{cacheconfiguration":1}
,"{cacheconfiguration":{"config":1}
,"config":{"=new":1}
,"=new":{"cacheconfiguration":1,"cache":1}
,"cacheconfiguration":{"sample-offheap-cache":1}
,"10000)":{".overflowtooffheap":1}
,".overflowtooffheap":{"(true)":1}
,"(true)":{".maxbyteslocaloffheap":1}
,".maxbyteslocaloffheap":{"cache":1}
,"(config)":{"manager.addcache":1}
,"manager.addcache":{"(cache)":1}
,"(cache)":{"return":1}
,"return":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
