var pairs =
{
"operator":{"events":1}
,"events":{"bigmemory":1,"terracotta":1}
,"bigmemory":{"hybrid":1}
,"hybrid":{"supports":1}
,"supports":{"existing":1}
,"existing":{"operator":1}
,"terracotta":{"server":1}
,"server":{"array":1}
,"array":{"(tsa)":1}
,"(tsa)":{"including":1}
,"including":{"throttle":1}
,"throttle":{"mode":1}
,"mode":{"amount":1,"system":1,"information":1}
,"amount":{"either":1}
,"either":{"ram":1}
,"ram":{"flash":1}
,"flash":{"approaching":1}
,"approaching":{"capacity":1}
,"capacity":{"limit":1}
,"limit":{"managing":1}
,"managing":{"near-memory-full":1}
,"near-memory-full":{"conditions":1}
,"conditions":{"restricted":1,"don":1}
,"restricted":{"mode":1}
,"system":{"entered":1}
,"entered":{"read-only":1}
,"read-only":{"mode":1}
,"information":{"managing":1}
,"don":{"added":1}
,"added":{"link":1}
}
;Search.control.loadWordPairs(pairs);
