var pairs =
{
"server":{"status":1,"instances":1,"queries":1,"responding":1,"ready":1,"using":1,"specified":1}
,"status":{"(server-stat)":1,"tool":1,"terracotta":1,"localhost":1}
,"(server-stat)":{"status":1}
,"tool":{"command-line":1,"returns":1,"fails":1,"[prompt]":1,"checks":1}
,"command-line":{"utility":1}
,"utility":{"checking":1}
,"checking":{"current":1}
,"current":{"status":1}
,"terracotta":{"server":1}
,"instances":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"bigmemory_home":1,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fserver-stat.sh":1,"server-stat.sh":1}
,"bigmemory_home":{"%\u005Cserver\u005Cbin\u005Cserver-stat.bat":1}
,"%\u005Cserver\u005Cbin\u005Cserver-stat.bat":{"<args>":1}
,"<args>":{"unix\u002Flinux":1,"<args>":1,"[-s]":1}
,"unix\u002Flinux":{"[prompt]":1}
,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fserver-stat.sh":{"<args>":1}
,"[-s]":{"host1":1,"host1:9520":1}
,"host1":{"host2":1}
,"host2":{"check":1}
,"check":{"servers":1}
,"servers":{"using":1,"defined":1,"always":1,"show":1}
,"using":{"given":1,"default":1,"listen":1}
,"given":{"hostnames":1}
,"hostnames":{"addresses":1}
,"addresses":{"using":1,"jmx":1}
,"default":{"jmx":1,"tool":1}
,"jmx":{"port":1,"events":1}
,"port":{"(9520)":1,"specified":1,"tcp":1,"server":1,"9520":1}
,"(9520)":{"[-s]":1}
,"host1:9520":{"host2:9521":1}
,"host2:9521":{"check":1}
,"specified":{"[-f]":1,"configuration":1,"default":1}
,"[-f]":{"<path>\u002Ftc-config.xml":1}
,"<path>\u002Ftc-config.xml":{"check":1}
,"defined":{"specified":1}
,"configuration":{"file":1}
,"file":{"[-k]":1}
,"[-k]":{"flag":1}
,"flag":{"causes":1}
,"causes":{"invalid":1}
,"invalid":{"tms":1}
,"tms":{"ssl":1}
,"ssl":{"certificates":1}
,"certificates":{"ignored":1,"(ones":1}
,"ignored":{"option":1}
,"option":{"accept":1}
,"accept":{"self-signed":1}
,"self-signed":{"certificates":1}
,"(ones":{"signed":1}
,"signed":{"trusted":1}
,"trusted":{"ca)":1}
,"ca)":{"status":1}
,"returns":{"following":1}
,"following":{"data":1,"example":1}
,"data":{"server":1}
,"queries":{"health":1}
,"health":{"(server":1}
,"(server":{"responding":1}
,"responding":{"normally)":1,"correctly)":1}
,"normally)":{"failed":1}
,"failed":{"(connection":1,"server":1}
,"(connection":{"failed":1}
,"correctly)":{"role":1}
,"role":{"server\u0027s":1}
,"server\u0027s":{"position":1}
,"position":{"active-mirror":1}
,"active-mirror":{"group":1}
,"group":{"single":1}
,"single":{"servers":1}
,"always":{"show":1}
,"show":{"active":1,"active-coordinator":1,"mirror-standby":1}
,"active":{"backups":1,"servers":1,"localhost.state":1}
,"backups":{"shown":1}
,"shown":{"mirror":1}
,"mirror":{"passive":1,"servers":1}
,"passive":{"state":1}
,"state":{"work":1,"server":1}
,"work":{"state":1}
,"ready":{"active":1}
,"active-coordinator":{"mirror":1,"localhost.jmxport":1}
,"mirror-standby":{"passive-standby":1}
,"passive-standby":{"jmx":1}
,"tcp":{"port":1}
,"listen":{"jmx":1}
,"events":{"error":1}
,"error":{"status":1,"example":1}
,"fails":{"type":1}
,"type":{"error":1}
,"example":{"following":1,"shows":1}
,"shows":{"usage":1}
,"usage":{"output":1}
,"output":{"status":1}
,"server-stat.sh":{"myhost:9521":1}
,"myhost:9521":{"localhost.health":1}
,"localhost.health":{"localhost.role":1}
,"localhost.role":{"active":1}
,"localhost.state":{"active-coordinator":1}
,"localhost.jmxport":{"9521":1}
,"9521":{"server":1}
,"checks":{"status":1}
,"localhost":{"jmx":1}
}
;Search.control.loadWordPairs(pairs);
