var pairs =
{
"consistency":{"modes":1,"application":1,"potentially":1,"attribute":1,"performance":1,"critical":1,"guarantees":1,"mode":1,"following":1,"explicit":1,"across":1,"used":1,"it\u0027s":1,"times":1,"unless":1,"race":1,"cache":1}
,"modes":{"cache":1,"configuration":1,"strong":1}
,"cache":{"consistency":1,"following":1,"remains":1,"eventually":1,"brief":1,"operations":1,"explicitly":1,"without":1,"required":1,"apis":1,"guaranteed":1,"cache":1,"operation":1,"methods":1,"key":1,"cache.removeelement":1,"decorator":1,"decorators":1}
,"configuration":{"settings":1,"file":1,"permanent":1}
,"settings":{"api":1,"affect":1}
,"api":{"methods":1,"information":1,"provides":1}
,"methods":{"control":1,"cluster-wide":1,"bulk-loading":1,"putall":1,"guarantee":1,"following":1,"used":1,"throw":1,"note":1}
,"control":{"behavior":1}
,"behavior":{"clustered":1}
,"clustered":{"caches":1,"locks":1}
,"caches":{"respect":1,"selectively":1}
,"respect":{"balancing":1,"(but":1,"non":1}
,"balancing":{"data":1}
,"data":{"consistency":1,"cache":1,"available":1}
,"application":{"performance":1,"cluster-wide":1,"bulk-load":1}
,"performance":{"cache":1,"mode":1,"substantially":1,"consider":1,"overhead":1,"information":1}
,"following":{"consistency":1,"apis":1,"compare":1}
,"strong":{"mode":1,"eventual)":1,"consistency":1}
,"mode":{"ensures":1,"using":1,"guarantees":1,"optimized":1,"batching":1,"(either":1,"cache":1,"during":1,"atomic":1}
,"ensures":{"data":1}
,"remains":{"consistent":1}
,"consistent":{"across":1,"read\u002Fwrite":1,"caches":1,"respect":1,"data":1,"bulk":1}
,"across":{"cluster":1}
,"cluster":{"times":1}
,"times":{"guarantees":1,"eventual":1,"operations":1,"avoid":1}
,"guarantees":{"read":1,"data":1,"mode":1}
,"read":{"gets":1}
,"gets":{"updated":1}
,"updated":{"value":1}
,"value":{"write":1,"completed":1,"new":1,"currently":1,"matches":1,"cache.replace":1,"key":1,"cache.putifabsent":1,"unlike":1,"normally":1,"eventual":1}
,"write":{"operations":1,"speeds":1,"consistency":1}
,"operations":{"value":1,"explicitly":1,"elements":1,"covered":1,"atomic":1,"available":1}
,"completed":{"put":1}
,"put":{"operation":1,"operations":1,"replace":1}
,"operation":{"separate":1,"committed":1}
,"separate":{"transaction":1}
,"transaction":{"locking":1,"acknowledgments":1,"used":1,"explicit":1}
,"locking":{"transaction":1,"application":1,"api":1,"specific":1,"elements":1,"potential":1,"developer":1,"stronglyconsistentcacheaccessor":1,"cache":1}
,"acknowledgments":{"maximizes":1}
,"maximizes":{"consistency":1}
,"potentially":{"substantial":1,"having":1}
,"substantial":{"cost":1}
,"cost":{"performance":1,"potentially":1}
,"using":{"ehcache":1,"eventually":1,"appropriate":1,"bulk-load":1,"locks":1}
,"ehcache":{"configuration":1}
,"file":{"cannot":1}
,"cannot":{"changed":1,"prevented":1}
,"changed":{"programmatically":1}
,"programmatically":{"(see":1}
,"(see":{"consistency":1}
,"attribute":{"<terracotta>":1}
,"<terracotta>":{"element)":1}
,"element)":{"eventual":1,"optimize":1}
,"eventual":{"mode":1,"cache":1,"consistency":1}
,"eventually":{"consistent":1}
,"read\u002Fwrite":{"performance":1}
,"substantially":{"boosted":1}
,"boosted":{"cost":1}
,"having":{"inconsistent":1}
,"inconsistent":{"cache":1}
,"brief":{"periods":1}
,"periods":{"time":1}
,"time":{"mode":1,"populating":1}
,"optimize":{"consistency":1}
,"consider":{"using":1}
,"selectively":{"using":1}
,"appropriate":{"locking":1}
,"cluster-wide":{"consistency":1,"(application-level)":1}
,"critical":{"times":1}
,"explicitly":{"locked":1}
,"locked":{"become":1,"operations)":1,"customer":1}
,"become":{"strongly":1}
,"strongly":{"consistent":1}
,"(but":{"respect":1}
,"non":{"locked":1}
,"operations)":{"example":1}
,"example":{"reservation":1}
,"reservation":{"system":1,"design":1,"process":1}
,"system":{"designed":1}
,"designed":{"eventual":1}
,"customer":{"starts":1}
,"starts":{"reservation":1}
,"design":{"eventually":1}
,"available":{"during":1,"cache.replace":1}
,"during":{"customer\u0027s":1,"reservation":1,"time":1}
,"customer\u0027s":{"search":1}
,"search":{"during":1}
,"process":{"reads":1}
,"reads":{"writes":1}
,"writes":{"strongly":1}
,"bulk":{"load":1,"loading":1}
,"load":{"mode":1}
,"optimized":{"bulk-loading":1}
,"bulk-loading":{"data":1,"methods":1,"cache":1}
,"without":{"slowness":1}
,"slowness":{"introduced":1}
,"introduced":{"locks":1}
,"locks":{"regular":1,"information":1,"special":1,"may":1}
,"regular":{"eviction":1}
,"eviction":{"similar":1}
,"similar":{"eventual":1}
,"batching":{"higher":1}
,"higher":{"write":1}
,"speeds":{"weaker":1}
,"weaker":{"consistency":1}
,"bulk-load":{"api":1,"mode":1}
,"information":{"bulk":1,"explicit":1,"cache":1}
,"loading":{"developer":1}
,"developer":{"guide":1}
,"guide":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"turned":1,"bulk-loading":1}
,"turned":{"allows":1}
,"allows":{"configured":1}
,"configured":{"consistency":1}
,"(either":{"strong":1}
,"eventual)":{"effect":1}
,"effect":{"again":1}
,"again":{"configuration":1}
,"permanent":{"consistency":1}
,"required":{"application":1}
,"populating":{"(warming)":1}
,"(warming)":{"refreshing":1}
,"refreshing":{"cache":1}
,"apis":{"related":1,"settings":1}
,"related":{"consistency":1}
,"affect":{"consistency":1}
,"explicit":{"locking":1,"lock":1}
,"provides":{"methods":1,"fine-grained":1}
,"(application-level)":{"locking":1}
,"specific":{"elements":1}
,"elements":{"cache":1,"covered":1,"provides":1}
,"guaranteed":{"consistency":1}
,"covered":{"lock":1,"explicit":1}
,"lock":{"used":1,"committed":1}
,"used":{"strong":1,"eventual":1}
,"committed":{"single":1}
,"single":{"transaction":1}
,"fine-grained":{"locking":1}
,"potential":{"contention":1,"race":1}
,"contention":{"blocked":1}
,"blocked":{"threads":1}
,"threads":{"increased":1}
,"increased":{"performance":1}
,"overhead":{"managing":1}
,"managing":{"clustered":1}
,"putall":{"getall":1}
,"getall":{"removeall":1}
,"removeall":{"provide":1}
,"provide":{"high-performance":1}
,"high-performance":{"eventual":1}
,"it\u0027s":{"unnecessary":1}
,"unnecessary":{"bulk-load":1}
,"atomic":{"methods":1}
,"guarantee":{"write":1,"return":1}
,"avoid":{"potential":1}
,"race":{"conditions":1,"condition":1}
,"conditions":{"put":1}
,"compare":{"swap":1}
,"swap":{"(cas)":1}
,"(cas)":{"operations":1}
,"cache.replace":{"(element":1,"(element)":1}
,"(element":{"old":1}
,"old":{"element":1,"value":1}
,"element":{"new)":1}
,"new)":{"conditionally":1}
,"conditionally":{"replaces":1,"removes":1}
,"replaces":{"specified":1}
,"specified":{"key\u0027s":1,"key":1,"value":1,"key\u002Fvalue":1}
,"key\u0027s":{"old":1}
,"new":{"value":1}
,"currently":{"existing":1,"mapped":1,"assigned":1}
,"existing":{"value":1,"key\u002Fvalue":1}
,"matches":{"old":1}
,"(element)":{"maps":1,"puts":1,"conditionally":1}
,"maps":{"specified":1}
,"key":{"specified":1,"currently":1,"mapped":1}
,"mapped":{"value":1,"specified":1}
,"cache.putifabsent":{"(element)":1}
,"puts":{"specified":1}
,"key\u002Fvalue":{"pair":1}
,"pair":{"cache":1,"putifabsent":1,"present":1}
,"assigned":{"value":1}
,"unlike":{"put":1}
,"replace":{"existing":1}
,"putifabsent":{"creates":1}
,"creates":{"key\u002Fvalue":1}
,"present":{"cache":1}
,"cache.removeelement":{"(element)":1}
,"removes":{"specified":1}
,"normally":{"methods":1}
,"unless":{"property":1}
,"property":{"org.terracotta.clusteredstore.eventual.cas.enabled":1}
,"org.terracotta.clusteredstore.eventual.cas.enabled":{"true":1}
,"true":{"methods":1}
,"throw":{"unsupportedoperationexception":1}
,"unsupportedoperationexception":{"used":1}
,"condition":{"cannot":1}
,"prevented":{"ways":1}
,"ways":{"guarantee":1}
,"return":{"value":1}
,"decorator":{"stronglyconsistentcacheaccessor":1}
,"stronglyconsistentcacheaccessor":{"explicit":1,"locks":1}
,"special":{"substituted":1}
,"substituted":{"versions":1}
,"versions":{"atomic":1}
,"note":{"using":1}
,"may":{"impact":1}
,"impact":{"performance":1}
,"decorators":{"explicit":1}
}
;Search.control.loadWordPairs(pairs);
