var pairs =
{
"automatic":{"client":1,"reconnect":1}
,"client":{"reconnect":1,"cannot":1,"setting":1,"attempts":1,"emits":1}
,"reconnect":{"clients":1,"cluster":1,"mechanism":1,"-with":1,"continue":1,"event-based":1}
,"clients":{"disconnected":1,"waiting":1,"server":1}
,"disconnected":{"terracotta":1}
,"terracotta":{"cluster":1,"clients":1,"event":1}
,"cluster":{"normally":1,"automatic":1,"performance":1,"disconnection":1,"client":1}
,"normally":{"require":1}
,"require":{"restart":1}
,"restart":{"reconnect":1,"terracotta":1}
,"mechanism":{"prevent":1,"works":1,"cannot":1,"triggered":1,"exposed":1,"l2.l1reconnect.enabled":1}
,"prevent":{"short":1}
,"short":{"network":1}
,"network":{"disruptions":1}
,"disruptions":{"forcing":1}
,"forcing":{"restart":1}
,"performance":{"impact":1}
,"impact":{"using":1}
,"using":{"automatic":1}
,"-with":{"feature":1}
,"feature":{"clients":1}
,"waiting":{"reconnect":1,"client":1}
,"continue":{"hold":1}
,"hold":{"locks":1}
,"locks":{"application":1}
,"application":{"threads":1}
,"threads":{"may":1}
,"may":{"block":1}
,"block":{"waiting":1}
,"event-based":{"reconnection":1}
,"reconnection":{"mechanism":1,"property":1}
,"works":{"independently":1}
,"independently":{"exclusively":1}
,"exclusively":{"healthchecker":1}
,"healthchecker":{"healthchecker":1,"already":1,"prevented":1}
,"already":{"triggered":1}
,"triggered":{"mechanism":1,"node":1,"first":1}
,"cannot":{"triggered":1,"override":1}
,"node":{"mechanism":1,"events":1}
,"first":{"internal":1}
,"internal":{"terracotta":1}
,"event":{"healthchecker":1}
,"prevented":{"triggered":1}
,"events":{"trigger":1}
,"trigger":{"mechanism":1}
,"exposed":{"api":1}
,"api":{"logged":1}
,"logged":{"configure":1}
,"configure":{"following":1}
,"following":{"properties":1}
,"properties":{"reconnect":1}
,"l2.l1reconnect.enabled":{"-(default":1,"true":1}
,"-(default":{"false)":1}
,"false)":{"true":1}
,"true":{"enables":1,"specifies":1}
,"enables":{"client":1}
,"disconnection":{"detected":1}
,"detected":{"property":1}
,"property":{"controls":1}
,"controls":{"server":1}
,"server":{"instance\u0027s":1,"instance":1}
,"instance\u0027s":{"reaction":1,"setting":1,"timeout":1}
,"reaction":{"attempt":1}
,"attempt":{"server":1}
,"instance":{"passed":1,"client":1}
,"passed":{"clients":1}
,"override":{"server":1}
,"setting":{"mismatch":1,"server":1,"client":1,"l2.l1reconnect.timeout.millis":1,"default":1}
,"mismatch":{"exists":1,"error":1}
,"exists":{"client":1}
,"attempts":{"reconnect":1}
,"emits":{"mismatch":1}
,"error":{"exits":1}
,"exits":{"cases":1}
,"cases":{"benefit":1}
,"benefit":{"enabling":1}
,"enabling":{"setting":1}
,"l2.l1reconnect.timeout.millis":{"-enabled":1}
,"-enabled":{"l2.l1reconnect.enabled":1}
,"specifies":{"timeout":1}
,"timeout":{"(in":1,"during":1}
,"(in":{"milliseconds)":1}
,"milliseconds)":{"reconnection":1}
,"during":{"attempt":1}
,"default":{"2000":1}
,"2000":{"parameter":1}
,"parameter":{"tuned":1}
,"tuned":{"handle":1}
,"handle":{"longer":1}
,"longer":{"network":1}
}
;Search.control.loadWordPairs(pairs);
