var pairs =
{
"bulk":{"loading":1}
,"loading":{"bigmemory":1,"caches":1,"designed":1,"overnight":1}
,"bigmemory":{"max":1}
,"max":{"bulk-loading":1}
,"bulk-loading":{"mode":1,"data":1}
,"mode":{"dramatically":1,"block":1}
,"dramatically":{"speeds":1}
,"speeds":{"bulk":1}
,"caches":{"using":1,"need":1}
,"using":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"array":1}
,"array":{"(tsa)":1}
,"(tsa)":{"bulk":1}
,"designed":{"used":1}
,"used":{"cache":1}
,"cache":{"warming":1,"bulk-load":1}
,"warming":{"caches":1}
,"need":{"filled":1}
,"filled":{"bringing":1}
,"bringing":{"application":1}
,"application":{"online":1}
,"online":{"periodic":1}
,"periodic":{"batch":1}
,"batch":{"loading":1,"process":1}
,"overnight":{"batch":1}
,"process":{"uploads":1}
,"uploads":{"data":1}
,"data":{"bulk-load":1,"removing":1}
,"bulk-load":{"api":1,"mode":1}
,"api":{"optimizes":1,"allows":1}
,"optimizes":{"bulk-loading":1}
,"removing":{"requirement":1}
,"requirement":{"locks":1}
,"locks":{"adding":1}
,"adding":{"transaction":1}
,"transaction":{"batching":1}
,"batching":{"bulk-load":1}
,"allows":{"applications":1}
,"applications":{"discover":1}
,"discover":{"whether":1}
,"whether":{"cache":1}
,"block":{"based":1}
,"based":{"mode":1}
}
;Search.control.loadWordPairs(pairs);
