var pairs =
{
"sizing":{"attributes":1,"data":1}
,"attributes":{"<<this":1,"sizing":1,"affect":1,"tier":1,"distributed":1,"number":1,"memory":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"following":1}
,"product":{"docs.>>":1}
,"docs.>>":{"tuning":1}
,"tuning":{"bigmemory":1}
,"bigmemory":{"max":1,"pooling":1}
,"max":{"often":1,"(using":1}
,"often":{"involves":1}
,"involves":{"sizing":1}
,"data":{"storage":1,"tiers":1,"local":1,"sets":1,"off-heap":1}
,"storage":{"tiers":1}
,"tiers":{"appropriately":1,"number":1,"effective":1}
,"appropriately":{"size":1}
,"size":{"different":1,"(bytes)":1}
,"different":{"data":1}
,"number":{"ways":1,"entries":1,"bytes":1,"cache":1}
,"ways":{"using":1}
,"using":{"simple":1,"maxbyteslocalheap":1,"maxbyteslocaldisk":1}
,"simple":{"sizing":1}
,"affect":{"memory":1}
,"memory":{"disk":1,"store":1,"cachemanager":1,"size":1}
,"disk":{"resources":1,"store":1,"cachemanager":1,"usage":1,"persistence":1,"n\u002Fa":1,"pooling":1}
,"resources":{"following":1}
,"following":{"table":1,"diagram":1}
,"table":{"summarizes":1}
,"summarizes":{"sizing":1}
,"tier":{"attribute":1}
,"attribute":{"description":1}
,"description":{"memory":1,"heap":1}
,"store":{"(heap)":1,"maxbyteslocaloffheap":1,"maxentrieslocaldiskmax":1,"distributed":1}
,"(heap)":{"maxentrieslocalheapmax":1}
,"maxentrieslocalheapmax":{"byteslocalheap":1}
,"byteslocalheap":{"maximum":1}
,"maximum":{"number":1}
,"entries":{"bytes":1,"clients":1,"elements":1}
,"bytes":{"data":1,"cache":1}
,"local":{"heap":1,"disk":1,"pool":1}
,"heap":{"memory":1,"maxentrieslocalheapmax":1}
,"cachemanager":{"level":1,"setting":1,"pooling":1,"note":1}
,"level":{"(maxbyteslocalheap":1,"pooling":1,"using":1,"pool":1,"disk":1,"(maxbyteslocaldisk":1,"local":1,"available":1}
,"(maxbyteslocalheap":{"only)":1}
,"only)":{"pool":1,"local":1}
,"pool":{"available":1,"configured":1}
,"available":{"data":1,"cachemanager":1,"caches":1,"terracotta":1,"attributes":1}
,"sets":{"cachemanager":1}
,"setting":{"required":1,"requires":1,"unlimited":1}
,"required":{"every":1}
,"every":{"cache":1}
,"cache":{"cachemanager":1,"entries":1,"local":1,"off-heap":1,"elements":1,"value":1}
,"pooling":{"available":1,"cachemanager":1}
,"maxbyteslocalheap":{"off-heap":1}
,"off-heap":{"store":1,"memory":1,"maxbyteslocaloffheap":1}
,"maxbyteslocaloffheap":{"maximum":1}
,"maxentrieslocaldiskmax":{"byteslocaldisk":1}
,"byteslocaldisk":{"maximum":1}
,"(maxbyteslocaldisk":{"only)":1}
,"note":{"settings":1}
,"settings":{"apply":1}
,"apply":{"temporary":1,"disk":1}
,"temporary":{"disk":1}
,"usage":{"(localtempswap)":1}
,"(localtempswap)":{"settings":1}
,"persistence":{"pooling":1}
,"maxbyteslocaldisk":{"bmm":1}
,"distributed":{"bigmemory":1,"caches":1,"cache":1}
,"(using":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"server":1,"array)":1,"array":1}
,"array)":{"tier":1}
,"caches":{"cachemanager":1,"cannot":1,"setting":1}
,"requires":{"bigmemory":1}
,"n\u002Fa":{"distributed":1}
,"cannot":{"local":1}
,"array":{"maxentriesincache":1,"store":1,"individual":1}
,"maxentriesincache":{"number":1}
,"elements":{"terracotta":1,"integer":1}
,"value":{"greater":1}
,"greater":{"equal":1}
,"equal":{"number":1}
,"clients":{"server":1}
,"individual":{"distributed":1}
,"unlimited":{"default":1}
,"default":{"pooling":1}
,"integer":{"attributes":1}
,"(bytes)":{"java":1}
,"java":{"-xmx":1}
,"-xmx":{"syntax":1}
,"syntax":{"(for":1}
,"(for":{"example":1}
,"example":{"500k":1,"percentages":1}
,"500k":{"200m":1}
,"200m":{"percentage":1}
,"percentage":{"(for":1}
,"percentages":{"however":1}
,"however":{"used":1}
,"used":{"case":1}
,"case":{"cachemanager-level":1}
,"cachemanager-level":{"pool":1}
,"configured":{"bigm":1}
,"bigm":{"following":1}
,"diagram":{"illustrates":1}
,"illustrates":{"tiers":1}
,"effective":{"sizing":1}
}
;Search.control.loadWordPairs(pairs);
