var pairs =
{
"effective":{"client-server":1,"range":1}
,"client-server":{"reconnection":1}
,"reconnection":{"settings":1,"window":1}
,"settings":{"prevent":1,"environment":1,"appropriate":1,"found":1,"within":1}
,"prevent":{"unwanted":1}
,"unwanted":{"disconnections":1}
,"disconnections":{"important":1,"certain":1}
,"important":{"understand":1}
,"understand":{"potentially":1}
,"potentially":{"complex":1}
,"complex":{"interaction":1}
,"interaction":{"settings":1}
,"environment":{"cluster":1,"lead":1}
,"cluster":{"runs":1,"l2-l2":1,"180":1}
,"runs":{"settings":1}
,"appropriate":{"particular":1}
,"particular":{"environment":1}
,"lead":{"unwanted":1}
,"certain":{"circumstances":1}
,"circumstances":{"general":1}
,"general":{"advisable":1}
,"advisable":{"maintain":1}
,"maintain":{"l1-l2":1}
,"l1-l2":{"healthchecker":1}
,"healthchecker":{"timeout":1,"triggers":1,"election":1,"settings":1}
,"timeout":{"falls":1,"modified":1}
,"falls":{"l2-l2":1}
,"l2-l2":{"healthchecker":1,"healthcheck":1}
,"modified":{"following":1}
,"following":{"inequality":1}
,"inequality":{"l2-l2":1}
,"healthcheck":{"election":1,"<l2-l2":1}
,"election":{"time":1,"time)":1,"disconnected":1}
,"time":{"<l1-l2":1,"client":1,"greater":1,"less":1}
,"<l1-l2":{"healthcheck":1}
,"<l2-l2":{"healthcheck":1}
,"client":{"reconnect":1,"reconnection":1}
,"reconnect":{"window":1,"until":1}
,"window":{"allows":1,"opened":1,"settings":1,"closed":1}
,"allows":{"cluster\u0027s":1}
,"cluster\u0027s":{"l1s":1}
,"l1s":{"avoid":1,"lost":1}
,"avoid":{"disconnecting":1}
,"disconnecting":{"client":1}
,"opened":{"backup":1,"(the":1}
,"backup":{"takes":1,"cluster":1}
,"takes":{"over)":1}
,"over)":{"disconnect":1}
,"disconnect":{"window":1,"active":1}
,"(the":{"original":1}
,"original":{"active":1}
,"active":{"functional)":1,"failure":1,"win":1}
,"functional)":{"election":1}
,"found":{"terracotta":1}
,"terracotta":{"configuration":1}
,"configuration":{"file":1}
,"file":{"respectively":1}
,"respectively":{"seconds":1}
,"seconds":{"120":1,"default":1,"backup":1,"(55":1,"clients":1,"(l2-l2":1}
,"120":{"seconds":1}
,"default":{"example":1}
,"example":{"cluster":1}
,"triggers":{"seconds":1,"time":1}
,"180":{"seconds":1}
,"(55":{"120)":1}
,"120)":{"l1-l2":1}
,"greater":{"180":1}
,"clients":{"may":1}
,"may":{"attempt":1,"disconnect":1}
,"attempt":{"reconnect":1}
,"until":{"reconnect":1}
,"closed":{"it\u0027s":1}
,"it\u0027s":{"late":1}
,"late":{"l1-l2":1}
,"less":{"seconds":1}
,"(l2-l2":{"healthchecker":1}
,"time)":{"clients":1}
,"failure":{"determined":1}
,"determined":{"active":1}
,"win":{"election":1}
,"disconnected":{"l1s":1}
,"lost":{"check":1}
,"check":{"performed":1}
,"performed":{"server":1}
,"server":{"startup":1}
,"startup":{"ensure":1}
,"ensure":{"l1-l2":1}
,"within":{"effective":1}
,"range":{"warning":1}
,"warning":{"prescription":1}
,"prescription":{"printed":1}
}
;Search.control.loadWordPairs(pairs);
