var pairs =
{
"terracotta":{"server":1,"cluster":1,"properties":1,"configuration":1,"log":1,"servers":1,"clients":1}
,"server":{"array":1,"properties":1,"client":1}
,"array":{"properties":1,"reconnection":1}
,"properties":{"terracotta":1,"often":1,"top":1,"-->":1,"following":1,"shown":1,"custom":1,"(<tc-properties>\u002F<property>":1,"control":1}
,"cluster":{"composed":1,"logging.maxbackups":1}
,"composed":{"clients":1}
,"clients":{"servers":1,"(l2":1,"terracotta":1}
,"servers":{"terracotta":1,"l2.l1reconnect.timeout":1,"(l2":1,"(l1":1}
,"often":{"shorthand":1}
,"shorthand":{"notation":1}
,"notation":{"client":1}
,"client":{"referred":1,"try":1,"fails":1}
,"referred":{"server":1}
,"top":{"tc-config.xml":1}
,"tc-config.xml":{"using":1}
,"using":{"configuration":1,"terracotta":1}
,"configuration":{"block":1,"properties":1,"source":1,"server":1}
,"block":{"similar":1}
,"similar":{"following":1}
,"following":{"<tc-properties>":1,"reconnection":1,"properties":1}
,"<tc-properties>":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"l2.nha.tcgroupcomm.reconnect.enabled":1}
,"l2.nha.tcgroupcomm.reconnect.enabled":{"value=\u0022":1}
,"value=\u0022":{"true":1}
,"true":{"<!--more":1,"enables":1}
,"<!--more":{"properties":1}
,"-->":{"<\u002Ftc-properties>":1}
,"<\u002Ftc-properties>":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
,"guide":{"information":1}
,"information":{"terracotta":1}
,"reconnection":{"logging":1,"properties":1,"timeout":1,"time":1}
,"logging":{"properties":1,"starts":1}
,"shown":{"default":1}
,"default":{"values":1,"value":1}
,"values":{"properties":1,"using":1}
,"custom":{"values":1}
,"(<tc-properties>\u002F<property>":{"elements":1}
,"elements":{"tc-config.xml)":1}
,"tc-config.xml)":{"property":1}
,"property":{"default":1}
,"value":{"notes":1}
,"notes":{"l2.nha.tcgroupcomm":1}
,"l2.nha.tcgroupcomm":{".reconnect.enabled":1,".reconnect.timeout":1}
,".reconnect.enabled":{"true":1}
,"enables":{"server-to-server":1,"reconnect":1}
,"server-to-server":{"reconnections":1}
,"reconnections":{"l2.nha.tcgroupcomm":1}
,".reconnect.timeout":{"5000ms":1}
,"5000ms":{"l2-l2":1,"reconnection":1}
,"l2-l2":{"reconnection":1}
,"timeout":{"l2.l1reconnect.enabled":1,"getting":1}
,"l2.l1reconnect.enabled":{"true":1}
,"reconnect":{"servers":1}
,"l2.l1reconnect.timeout":{".millis":1}
,".millis":{"5000ms":1}
,"time":{"disconnects":1}
,"disconnects":{"tc.config.getfromsource":1}
,"tc.config.getfromsource":{".timeout":1}
,".timeout":{"30000ms":1}
,"30000ms":{"timeout":1}
,"getting":{"configuration":1}
,"source":{"example":1}
,"example":{"controls":1}
,"controls":{"long":1}
,"long":{"client":1}
,"try":{"access":1}
,"access":{"configuration":1}
,"fails":{"fail":1}
,"fail":{"connect":1}
,"connect":{"cluster":1}
,"logging.maxbackups":{"upper":1}
,"upper":{"limit":1}
,"limit":{"number":1}
,"number":{"backups":1}
,"backups":{"terracotta":1}
,"log":{"files":1}
,"files":{"logging.maxlogfilesize":1,"rolling":1}
,"logging.maxlogfilesize":{"512mb":1}
,"512mb":{"maximum":1}
,"maximum":{"size":1}
,"size":{"terracotta":1}
,"rolling":{"logging":1}
,"starts":{"healthchecker":1}
,"healthchecker":{"tolerances":1}
,"tolerances":{"following":1,"terracotta":1}
,"control":{"disconnection":1}
,"disconnection":{"tolerances":1}
,"(l2":{"<->":1,"l1)":1}
,"<->":{"l2)":1,"tolerance":1}
,"l2)":{"terracotta":1,"<->":1}
,"l1)":{"terracotta":1}
,"(l1":{"l2)":1}
,"tolerance":{"secs":1,"10secs":1}
,"secs":{"cable":1}
,"cable":{"pull\u002Fnetwork":1}
,"pull\u002Fnetwork":{"down":1}
,"down":{"tolerance":1}
,"10secs":{"l2.healthcheck.l2.ping.enabled":1,"l2.healthcheck.l1.ping.enabled":1,"l1.healthcheck.l2.ping.enabled":1}
,"l2.healthcheck.l2.ping.enabled":{"=true":1}
,"=true":{"l2.healthcheck.l2.ping.idletime":1,"l2.healthcheck.l2.socketconnecttimeout":1,"l2.healthcheck.l1.ping.idletime":1,"l2.healthcheck.l1.socketconnecttimeout":1,"l1.healthcheck.l2.ping.idletime":1,"l1.healthcheck.l2.socketconnecttimeout":1}
,"l2.healthcheck.l2.ping.idletime":{"=5000":1}
,"=5000":{"l2.healthcheck.l2.ping.interval":1,"l2.healthcheck.l1.ping.interval":1,"l1.healthcheck.l2.ping.interval":1}
,"l2.healthcheck.l2.ping.interval":{"=1000":1}
,"=1000":{"l2.healthcheck.l2.ping.probes":1,"l2.healthcheck.l1.ping.probes":1,"l1.healthcheck.l2.ping.probes":1}
,"l2.healthcheck.l2.ping.probes":{"l2.healthcheck.l2.socketconnect":1}
,"l2.healthcheck.l2.socketconnect":{"=true":1}
,"l2.healthcheck.l2.socketconnecttimeout":{"l2.healthcheck.l2.socketconnectcount":1}
,"l2.healthcheck.l2.socketconnectcount":{"=10":1}
,"=10":{"l2->":1,"l1->":1}
,"l2->":{"tolerance":1}
,"l2.healthcheck.l1.ping.enabled":{"=true":1}
,"l2.healthcheck.l1.ping.idletime":{"=5000":1}
,"l2.healthcheck.l1.ping.interval":{"=1000":1}
,"l2.healthcheck.l1.ping.probes":{"l2.healthcheck.l1.socketconnect":1}
,"l2.healthcheck.l1.socketconnect":{"=true":1}
,"l2.healthcheck.l1.socketconnecttimeout":{"l2.healthcheck.l1.socketconnectcount":1}
,"l2.healthcheck.l1.socketconnectcount":{"=10":1}
,"l1->":{"tolerance":1}
,"l1.healthcheck.l2.ping.enabled":{"=true":1}
,"l1.healthcheck.l2.ping.idletime":{"=5000":1}
,"l1.healthcheck.l2.ping.interval":{"=1000":1}
,"l1.healthcheck.l2.ping.probes":{"l1.healthcheck.l2.socketconnect":1}
,"l1.healthcheck.l2.socketconnect":{"=true":1}
,"l1.healthcheck.l2.socketconnecttimeout":{"l1.healthcheck.l2.socketconnectcount":1}
,"l1.healthcheck.l2.socketconnectcount":{"=13":1}
}
;Search.control.loadWordPairs(pairs);
