var pairs =
{
"archive":{"utility":1}
,"utility":{"(archive-tool)":1}
,"(archive-tool)":{"archive-tool":1}
,"archive-tool":{"used":1}
,"used":{"gather":1}
,"gather":{"logs":1}
,"logs":{"generated":1,"directory":1}
,"generated":{"terracotta":1}
,"terracotta":{"server":1,"support":1,"config":1}
,"server":{"client":1}
,"client":{"purpose":1}
,"purpose":{"contacting":1}
,"contacting":{"terracotta":1}
,"support":{"query":1}
,"query":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"bigmemory_home":1,"${bigmemory_home}\u002Fserver\u002Fbin\u002Farchive-tool.sh":1}
,"bigmemory_home":{"%\u005Cserver\u005Cbin\u005Carchive-tool.bat":1}
,"%\u005Cserver\u005Cbin\u005Carchive-tool.bat":{"<args>":1}
,"<args>":{"unix\u002Flinux":1,"<args>":1,"[-n]":1}
,"unix\u002Flinux":{"[prompt]":1}
,"${bigmemory_home}\u002Fserver\u002Fbin\u002Farchive-tool.sh":{"<args>":1}
,"[-n]":{"(no":1}
,"(no":{"data":1}
,"data":{"-excludes":1,"files)":1}
,"-excludes":{"data":1}
,"files)":{"[-c]":1}
,"[-c]":{"(client":1}
,"(client":{"-include":1}
,"-include":{"files":1}
,"files":{"client)":1}
,"client)":{"[path":1}
,"[path":{"terracotta":1}
,"config":{"xml":1}
,"xml":{"file":1}
,"file":{"(tc-config.xml)":1}
,"(tc-config.xml)":{"path":1}
,"path":{"logs":1}
,"directory":{"[output":1}
,"[output":{"filename":1}
,"filename":{".zip":1}
,".zip":{"format]":1}
}
;Search.control.loadWordPairs(pairs);
