var pairs =
{
"monitoring":{"troubleshooting":1}
,"troubleshooting":{"dgc":1}
,"dgc":{"dgc":1,"events":1,"seem":1,"run":1,"able":1,"collects":1}
,"events":{"(both":1,"monitored":1}
,"(both":{"periodic":1}
,"periodic":{"inline)":1}
,"inline)":{"reported":1}
,"reported":{"terracotta":1}
,"terracotta":{"server":1,"management":1,"clients":1}
,"server":{"instance\u0027s":1}
,"instance\u0027s":{"logs":1}
,"logs":{"dgc":1}
,"monitored":{"using":1}
,"using":{"terracotta":1}
,"management":{"console":1}
,"console":{"dgc":1}
,"seem":{"collecting":1}
,"collecting":{"objects":1}
,"objects":{"expected":1,"fast":1,"become":1,"possible":1}
,"expected":{"rate":1,"collected":1}
,"rate":{"following":1}
,"following":{"issues":1}
,"issues":{"may":1}
,"may":{"cause":1,"resource":1}
,"cause":{"java":1}
,"java":{"able":1}
,"able":{"collect":1}
,"collect":{"objects":1}
,"fast":{"enough":1}
,"enough":{"client":1}
,"client":{"nodes":1}
,"nodes":{"may":1,"continue":1,"thus":1}
,"resource":{"pressure":1}
,"pressure":{"causing":1}
,"causing":{"collection":1}
,"collection":{"run":1}
,"run":{"behind":1}
,"behind":{"causes":1,"certain":1}
,"causes":{"dgc":1}
,"certain":{"client":1}
,"continue":{"hold":1}
,"hold":{"references":1}
,"references":{"objects":1}
,"become":{"garbage":1}
,"garbage":{"nodes":1}
,"thus":{"preventing":1}
,"preventing":{"dgc":1}
,"possible":{"shut":1}
,"shut":{"down":1}
,"down":{"terracotta":1}
,"clients":{"dgc":1}
,"collects":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
