var pairs =
{
"best":{"practices":1}
,"practices":{"optimizing":1}
,"optimizing":{"searches":1}
,"searches":{"<<this":1,"including":1,"longer":1,"create":1,"eventually":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"entire":1,"searches":1}
,"product":{"docs.>>":1}
,"docs.>>":{"construct":1}
,"construct":{"searches":1}
,"including":{"data":1,"query":1}
,"data":{"actually":1,"sets":1}
,"actually":{"required":1}
,"required":{"includekeys":1,"application":1}
,"includekeys":{"and\u002For":1,"includevalues":1}
,"and\u002For":{"includeattribute":1}
,"includeattribute":{"values":1}
,"values":{"required":1,"attributes":1,"deserialized":1,"automatically":1}
,"application":{"logic":1}
,"logic":{"need":1}
,"need":{"values":1}
,"attributes":{"careful":1,"keys":1}
,"careful":{"burden":1}
,"burden":{"queries":1}
,"queries":{"unnecessary":1,"<<ffc-find":1,"ilike":1,"using":1,"executed":1,"(created":1,"aggregate":1,"request":1}
,"unnecessary":{"work":1}
,"work":{"example":1,"topologies":1}
,"example":{"result.getvalue":1,"instead":1,"query":1,"constructed":1,"created":1}
,"result.getvalue":{"called":1,"run":1}
,"called":{"search":1,"however":1}
,"search":{"results":1,"query":1,"specific":1,"result":1,"api":1}
,"results":{"includevalues":1,"quickly":1,"consider":1,"until":1,"appear":1,"page-sized":1,"issuing":1,"returned":1,"specified":1,"resultbatchsize":1,"scroll":1,"groupby":1}
,"includevalues":{"query":1,"result.getvalue":1,"methods":1,"time":1}
,"query":{"consider":1,"includevalues":1,"keys":1,"turn":1,"trailing":1,"criteria":1,"fetch":1,"executionhints":1,"500":1,"whether":1,"constructed":1,"types":1}
,"consider":{"sufficient":1,"carefully":1,"maxresults":1,"using":1}
,"sufficient":{"attributes":1}
,"keys":{"demand":1,"include":1,"values":1}
,"demand":{"example":1}
,"instead":{"running":1,"leading":1,"\u0022*123":1,"possible":1,"lessthan":1,"using":1,"calling":1}
,"running":{"search":1}
,"run":{"query":1}
,"include":{"cache.get":1}
,"cache.get":{"individual":1}
,"individual":{"key":1}
,"key":{"includekeys":1}
,"methods":{"lazy":1}
,"lazy":{"deserialization":1}
,"deserialization":{"meaning":1}
,"meaning":{"keys":1}
,"deserialized":{"result.getkey":1}
,"result.getkey":{"result.getvalue":1}
,"however":{"calls":1}
,"calls":{"includekeys":1}
,"time":{"consider":1,"faster":1,"view":1}
,"carefully":{"constructing":1}
,"constructing":{"queries":1}
,"<<ffc-find":{"whether":1}
,"whether":{"leave":1,"query":1}
,"leave":{"ehcache":1}
,"ehcache":{"apply":1,"javadoc":1,"version":1}
,"apply":{"open":1}
,"open":{"source":1}
,"source":{"ehcache>":1}
,"ehcache>":{"searchable":1}
,"searchable":{"keys":1}
,"automatically":{"indexed":1}
,"indexed":{"default":1}
,"default":{"including":1}
,"turn":{"automatic":1}
,"automatic":{"indexing":1}
,"indexing":{"following":1}
,"following":{"<cache":1,"query":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"cachename":1}
,"cachename":{"<searchable":1}
,"<searchable":{"keys=\u0022":1}
,"keys=\u0022":{"false":1}
,"false":{"values=\u0022":1,"\u0022\u002F>":1}
,"values=\u0022":{"false":1}
,"\u0022\u002F>":{"<\u002Fsearchable>":1}
,"<\u002Fsearchable>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"limit":1}
,"limit":{"size":1}
,"size":{"result":1,"want":1}
,"result":{"depending":1,"ordered":1,"consider":1,"pagination":1,"ordering":1}
,"depending":{"case":1}
,"case":{"consider":1}
,"maxresults":{"aggregator":1,"useful":1,"want":1}
,"aggregator":{"pagination":1,"function":1,"work":1}
,"pagination":{"getting":1,"feature":1,"limits":1,"execution":1,"supported":1}
,"getting":{"subset":1}
,"subset":{"possible":1}
,"possible":{"results":1,"queries":1,"query":1}
,"quickly":{"important":1}
,"important":{"receiving":1}
,"receiving":{"results":1}
,"using":{"query.maxresults":1,"wildcard":1,"(startdate)":1,"pagination":1,"search":1}
,"query.maxresults":{"(int":1}
,"(int":{"number_of_results)":1}
,"number_of_results)":{"sometimes":1}
,"sometimes":{"maxresults":1}
,"useful":{"result":1}
,"ordered":{"items":1}
,"items":{"want":1}
,"want":{"included":1,"summary":1,"leading":1,"avoid":1,"query.execute":1}
,"included":{"within":1}
,"within":{"maxresults":1}
,"summary":{"statistic":1}
,"statistic":{"built-in":1}
,"built-in":{"aggregator":1}
,"function":{"count":1}
,"count":{"details":1,"aggregator":1}
,"details":{"net.sf.ehcache.search.aggregator":1}
,"net.sf.ehcache.search.aggregator":{"package":1}
,"package":{"ehcache":1}
,"javadoc":{"http:\u002F\u002Fwww.ehcache.org\u002Fapidocs\u002F2.10.1\u002F":1}
,"http:\u002F\u002Fwww.ehcache.org\u002Fapidocs\u002F2.10.1\u002F":{"search":1}
,"specific":{"possible":1,"queries":1}
,"ilike":{"criteria":1}
,"criteria":{"fuzzy":1,"instead":1}
,"fuzzy":{"(wildcard)":1}
,"(wildcard)":{"searches":1}
,"longer":{"specific":1}
,"wildcard":{"try":1,"searches":1,"instead":1}
,"try":{"making":1,"(between":1}
,"making":{"trailing":1}
,"trailing":{"part":1,"wildcard":1}
,"part":{"string":1,"321*\u0022":1}
,"string":{"instead":1,"value":1}
,"leading":{"part":1,"wildcard":1}
,"321*\u0022":{"instead":1}
,"\u0022*123":{"want":1}
,"create":{"<searchattribute>":1}
,"<searchattribute>":{"string":1}
,"value":{"reversed":1}
,"reversed":{"query":1}
,"lessthan":{"greaterthan":1}
,"greaterthan":{"lessthanorequal":1}
,"lessthanorequal":{"greaterthanorequal":1}
,"greaterthanorequal":{"example":1}
,"(startdate)":{"(enddate)":1}
,"(enddate)":{"try":1}
,"(between":{"(startdate":1}
,"(startdate":{"enddate))":1}
,"enddate))":{"<<ffc-this":1}
,"<<ffc-this":{"point":1}
,"point":{"appears":1}
,"appears":{"versions":1}
,"versions":{"2.8\u002F4.1":1}
,"2.8\u002F4.1":{"doc":1}
,"doc":{"remove":1}
,"remove":{"ehcache":1}
,"version":{"?>>":1,"execute":1}
,"?>>":{"index":1}
,"index":{"dates":1}
,"dates":{"integers":1}
,"integers":{"save":1}
,"save":{"time":1}
,"faster":{"conversion":1}
,"conversion":{"later":1}
,"later":{"bmm":1}
,"entire":{"<ul>":1}
,"<ul>":{"list":1}
,"list":{"bmm":1}
,"eventually":{"consistent":1}
,"consistent":{"bigmemory":1,"cache":1}
,"bigmemory":{"max":1,"sql":1}
,"max":{"data":1}
,"sets":{"fast":1}
,"fast":{"queries":1}
,"executed":{"immediately":1}
,"immediately":{"without":1,"runs":1}
,"without":{"waiting":1}
,"waiting":{"commit":1}
,"commit":{"pending":1}
,"pending":{"transactions":1}
,"transactions":{"local":1}
,"local":{"node":1}
,"node":{"thread":1}
,"thread":{"adds":1}
,"adds":{"element":1}
,"element":{"eventually":1,"visible":1}
,"cache":{"immediately":1}
,"runs":{"query":1}
,"fetch":{"element":1}
,"visible":{"search":1}
,"until":{"update":1}
,"update":{"published":1}
,"published":{"server":1}
,"server":{"want":1,"topology":1,"array":1}
,"avoid":{"outofmemoryerror":1}
,"outofmemoryerror":{"allowing":1}
,"allowing":{"terracotta":1}
,"terracotta":{"client":1,"server":1}
,"client":{"receive":1,"time":1,"example":1}
,"receive":{"extremely":1}
,"extremely":{"large":1}
,"large":{"result":1}
,"feature":{"pagination":1}
,"limits":{"total":1}
,"total":{"results":1}
,"appear":{"client":1}
,"view":{"results":1}
,"page-sized":{"batches":1}
,"batches":{"instead":1}
,"calling":{"parameterless":1}
,"parameterless":{"version":1}
,"execute":{"method":1}
,"method":{"query.execute":1}
,"query.execute":{"pass":1,"(new":1}
,"pass":{"executionhints":1}
,"executionhints":{"object":1,".setresultbatchsize":1,"results":1}
,"object":{"specifies":1}
,"specifies":{"page":1}
,"page":{"size":1}
,"(new":{"executionhints":1}
,".setresultbatchsize":{"(pagesize))":1}
,"(pagesize))":{"call":1}
,"call":{"results":1}
,"issuing":{"query":1}
,"returned":{"(same":1}
,"(same":{"behavior":1}
,"behavior":{"regular":1}
,"regular":{"query)":1}
,"query)":{"except":1}
,"except":{"number":1}
,"number":{"results":1}
,"specified":{"resultbatchsize":1}
,"resultbatchsize":{"appear":1,"100":1}
,"500":{"results":1}
,"100":{"500":1,"enable":1}
,"scroll":{"pages":1}
,"pages":{"100":1}
,"enable":{"search":1}
,"execution":{"phase":1}
,"phase":{"query":1}
,"constructed":{"using":1,"query.includeaggregator":1}
,"api":{"bigmemory":1}
,"sql":{"limitations":1}
,"limitations":{"results":1}
,"groupby":{"queries":1}
,"(created":{"query.addgroupby":1}
,"query.addgroupby":{"method)":1}
,"method)":{"cannot":1}
,"cannot":{"paginated":1}
,"paginated":{"regardless":1}
,"regardless":{"server":1}
,"topology":{"multi-stripe":1}
,"multi-stripe":{"(active\u002Factive)":1}
,"(active\u002Factive)":{"terracotta":1}
,"array":{"topologies":1}
,"topologies":{"pagination":1,"queries":1}
,"supported":{"following":1}
,"types":{"result-size":1}
,"result-size":{"capped":1}
,"capped":{"queries":1}
,"aggregate":{"functions":1}
,"functions":{"example":1}
,"query.includeaggregator":{".maxresults":1}
,".maxresults":{"-with":1}
,"-with":{"exception":1}
,"exception":{"count":1}
,"request":{"result":1}
,"ordering":{"example":1}
,"created":{"query.addorderby":1}
}
;Search.control.loadWordPairs(pairs);
