var pairs =
{
"data":{"consistency":1,"life":1}
,"consistency":{"conflict":1,"synchronization":1,"element":1}
,"conflict":{"resolution":1}
,"resolution":{"bidirectional":1,"modifications":1,"invoked":1}
,"bidirectional":{"mode":1}
,"mode":{"wan":1}
,"wan":{"replication":1}
,"replication":{"service":1}
,"service":{"balances":1}
,"balances":{"high":1}
,"high":{"performance":1}
,"performance":{"eventual":1,"local":1}
,"eventual":{"data":1}
,"synchronization":{"among":1}
,"among":{"orchestrators":1}
,"orchestrators":{"two":1}
,"two":{"additional":1,"updates":1}
,"additional":{"strategies":1}
,"strategies":{"employed":1}
,"employed":{"data":1}
,"element":{"versioning":1,"cause":1,"master":1,"winning":1}
,"versioning":{"optimistic":1,"element":1,"core":1,"ensures":1,"used":1}
,"optimistic":{"local":1}
,"local":{"modifications":1,"application":1,"element":1,"remove":1,"caches":1}
,"modifications":{"element":1,"(puts\u002Fupdates\u002Fdeletes)":1,"master":1,"(put\u002Fremove)":1,"rejected":1}
,"core":{"component":1}
,"component":{"data":1}
,"(puts\u002Fupdates\u002Fdeletes)":{"element":1}
,"cause":{"internal":1,"local":1}
,"internal":{"version":1}
,"version":{"incremented":1,"determine":1,"element":1,"region":1}
,"incremented":{"once":1}
,"once":{"successfully":1}
,"successfully":{"applied":1}
,"applied":{"versioning":1,"master":1,"rejected":1,"cache":1}
,"ensures":{"out-of-order":1}
,"out-of-order":{"updates":1}
,"updates":{"applied":1,"conflict":1,"arriving":1,"first":1,"regions":1}
,"master":{"cache":1,"repair":1}
,"cache":{"(no":1,"processes":1,"region":1,"first":1,"repairs":1,"subsequent":1,"local":1,"master":1,"force":1,"sent":1,"replicates":1,"rejects":1,"automatically":1,"repairing":1,"repair":1}
,"(no":{"duplicates":1}
,"duplicates":{"backward":1}
,"backward":{"counting":1}
,"counting":{"gaps)":1}
,"gaps)":{"versioning":1}
,"used":{"resolve":1}
,"resolve":{"simultaneous":1}
,"simultaneous":{"conflicting":1}
,"conflicting":{"updates":1}
,"invoked":{"two":1}
,"arriving":{"key":1}
,"key":{"version":1,"(key1)":1}
,"determine":{"update":1}
,"update":{"applied":1,"wins":1,"arrives":1}
,"rejected":{"decision":1,"master":1,"values":1}
,"decision":{"made":1}
,"made":{"based":1}
,"based":{"upon":1}
,"upon":{"order":1}
,"order":{"master":1}
,"processes":{"updates":1}
,"first":{"processed":1,"results":1}
,"processed":{"update":1}
,"wins":{"diagram":1,"update":1}
,"diagram":{"below":1,"region":1}
,"below":{"shows":1}
,"shows":{"concurrent":1}
,"concurrent":{"updates":1}
,"regions":{"key":1}
,"(key1)":{"resolved":1}
,"resolved":{"master":1}
,"region":{"region":1,"(key1=aaa)":1,"key1=bbb":1,"performs":1,"simultaneously":1,"contains":1,"master":1,"process":1,"cleared":1}
,"(key1=aaa)":{"wins":1}
,"arrives":{"master":1}
,"results":{"repair":1}
,"repair":{"region":1,"improve":1,"replica\u0027s":1,"means":1,"message":1,"value":1,"rejected":1}
,"key1=bbb":{"repaired":1}
,"repaired":{"key1=aaa":1}
,"key1=aaa":{"version":1}
,"repairs":{"second-to-arrive":1}
,"second-to-arrive":{"value":1}
,"value":{"match":1,"optimistic":1,"race":1,"master":1,"losing":1,"back":1}
,"match":{"first-to-arrive":1}
,"first-to-arrive":{"value":1}
,"improve":{"performance":1}
,"(put\u002Fremove)":{"optimistically":1}
,"optimistically":{"applied":1}
,"subsequent":{"reads":1}
,"reads":{"cache":1}
,"application":{"return":1}
,"return":{"expected":1}
,"expected":{"modified":1}
,"modified":{"value":1}
,"race":{"modify":1}
,"modify":{"element":1}
,"force":{"repair":1}
,"replica\u0027s":{"value":1}
,"means":{"racing":1}
,"racing":{"modifications":1}
,"sent":{"repair":1}
,"message":{"causes":1}
,"causes":{"local":1}
,"winning":{"state":1,"value":1}
,"state":{"mean":1}
,"mean":{"put":1}
,"put":{"may":1,"(xy=1":1,"(xy=2":1,"replica":1}
,"may":{"overwritten":1,"cause":1}
,"overwritten":{"winning":1}
,"losing":{"remove":1}
,"remove":{"may":1,"reverted":1}
,"reverted":{"following":1}
,"following":{"diagram":1}
,"performs":{"put":1}
,"(xy=1":{"version":1}
,"simultaneously":{"performs":1}
,"(xy=2":{"version":1}
,"contains":{"master":1}
,"replicates":{"xy=1:v1":1}
,"xy=1:v1":{"region":1}
,"rejects":{"put":1}
,"replica":{"cache":1}
,"automatically":{"resolves":1}
,"resolves":{"sends":1}
,"sends":{"repair":1}
,"back":{"region":1}
,"process":{"master":1,"non-replicated":1}
,"repairing":{"replica":1}
,"values":{"local":1}
,"caches":{"region":1,"information":1}
,"cleared":{"existing":1}
,"existing":{"process":1}
,"non-replicated":{"caches":1}
,"information":{"expiration":1}
,"expiration":{"eviction":1}
,"eviction":{"refer":1}
,"refer":{"managing":1}
,"managing":{"data":1}
,"life":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"configuration":1}
,"configuration":{"guide":1}
,"guide":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
}
;Search.control.loadWordPairs(pairs);
