var pairs =
{
"examples":{"uris":1,"section":1,"data":1}
,"uris":{"flexibility":1,"examples":1}
,"flexibility":{"management-service":1}
,"management-service":{"rest":1}
,"rest":{"api":1}
,"api":{"turn":1}
,"turn":{"makes":1}
,"makes":{"available":1}
,"available":{"flexible":1}
,"flexible":{"uri":1}
,"uri":{"syntax":1,"known":1}
,"syntax":{"examples":1}
,"section":{"illustrate":1}
,"illustrate":{"http":1}
,"http":{"responses":1,"operations":1}
,"responses":{"specific":1}
,"specific":{"uris":1}
,"data":{"returned":1}
,"returned":{"listed":1}
,"listed":{"http":1}
,"operations":{"shown":1}
,"shown":{"below":1}
,"below":{"without":1}
,"without":{"response":1}
,"response":{"headers":1}
,"headers":{"agent":1}
,"agent":{"ids":1}
,"ids":{"specified":1}
,"specified":{"uri":1}
,"known":{"agents":1}
,"agents":{"included":1}
}
;Search.control.loadWordPairs(pairs);
