var pairs =
{
"using":{"cleanup":1}
,"cleanup":{"utility":1,"caches":1,"performed":1}
,"utility":{"cache":1,"found":1}
,"cache":{"registered":1,"becomes":1,"whether":1,"non-wan":1,"wan-enabled":1,"note":1,"convert":1,"wan-enabled-cache":1}
,"registered":{"tsa":1}
,"tsa":{"subsequently":1,"attempt":1,"existing":1}
,"subsequently":{"becomes":1}
,"becomes":{"inactive":1,"active":1}
,"inactive":{"cache":1}
,"active":{"again":1}
,"again":{"tsa":1,"new":1}
,"attempt":{"verify":1}
,"verify":{"configuration":1}
,"configuration":{"therefore":1,"requirement":1,"parameter":1,"files":1}
,"therefore":{"order":1}
,"order":{"change":1}
,"change":{"wan":1}
,"wan":{"enabled\u002Fdisabled":1,"information":1}
,"enabled\u002Fdisabled":{"status":1}
,"status":{"caches":1}
,"caches":{"already":1,"mentioned":1,"cleanup":1,"wan-enabled":1}
,"already":{"registered":1}
,"existing":{"wan":1}
,"information":{"need":1,"terracotta":1}
,"need":{"removed":1,"either":1}
,"removed":{"cleanup-wan-metadata":1}
,"cleanup-wan-metadata":{"utility":1,"script":1}
,"found":{"\u002Fserver\u002Fbin":1}
,"\u002Fserver\u002Fbin":{"directory":1}
,"directory":{"bigmemory":1}
,"bigmemory":{"kit":1}
,"kit":{"provided":1}
,"provided":{"purpose":1}
,"purpose":{"run":1}
,"run":{"script":1,"cleanup-wan-metadata":1}
,"script":{"cleanup-wan-metadata.sh":1,"requires":1,"performs":1,"look":1,"modify":1,"new":1}
,"cleanup-wan-metadata.sh":{"configlocation":1}
,"configlocation":{"script":1,"argument":1,"specifies":1}
,"requires":{"configlocation":1}
,"argument":{"uri":1}
,"uri":{"location":1}
,"location":{"either":1}
,"either":{"wan_config.xml":1,"convert":1}
,"wan_config.xml":{"file":1,"script":1}
,"file":{"ehcache.xml":1,"configlocation":1}
,"ehcache.xml":{"file":1,"script":1,"locations":1,"wan-config.xml":1,"files":1}
,"specifies":{"ehcache.xml":1,"wan_config.xml":1}
,"performs":{"cleanup":1}
,"mentioned":{"configlocation":1}
,"look":{"ehcache.xml":1}
,"locations":{"listed":1}
,"listed":{"clean":1}
,"clean":{"caches":1}
,"performed":{"every":1}
,"every":{"cache":1}
,"whether":{"wan-enabled":1}
,"wan-enabled":{"useful":1,"cache":1,"system":1}
,"useful":{"want":1}
,"want":{"convert":1}
,"convert":{"wan-enabled":1,"caches":1,"non-wan":1}
,"non-wan":{"cache":1}
,"note":{"script":1}
,"modify":{"ehcache.xml":1,"wan-config.xml":1}
,"wan-config.xml":{"files":1,"ehcache.xml":1}
,"files":{"simply":1,"per":1}
,"simply":{"removes":1}
,"removes":{"wan-related":1}
,"wan-related":{"information":1}
,"terracotta":{"servers":1}
,"servers":{"procedure":1}
,"procedure":{"convert":1}
,"system":{"need":1}
,"wan-enabled-cache":{"follow":1}
,"follow":{"below":1}
,"below":{"steps":1}
,"steps":{"bring":1}
,"bring":{"down":1}
,"down":{"clients":1}
,"clients":{"orchestrator":1,"again":1}
,"orchestrator":{"modify":1,"clients":1}
,"per":{"new":1}
,"new":{"configuration":1}
,"requirement":{"run":1}
,"parameter":{"start":1}
,"start":{"orchestrator":1}
}
;Search.control.loadWordPairs(pairs);
