var pairs =
{
"available":{"statistics":1}
,"statistics":{"monitor":1,"following":1,"report":1}
,"monitor":{"following":1}
,"following":{"information":1,"statistics":1}
,"information":{"wan":1}
,"wan":{"replication":1,"number":1}
,"replication":{"service":1,"mode":1}
,"service":{"master":1}
,"master":{"cache":1,"orchestrator":1}
,"cache":{"statistics":1,"collected":1}
,"report":{"state":1,"overall":1,"particular":1}
,"state":{"master":1,"replicas":1}
,"collected":{"master":1,"replica":1}
,"orchestrator":{"statistic":1,"topology.replicas":1}
,"statistic":{"description":1}
,"description":{"cluster-listener.buffer.size":1,"config.replication-mode":1,"replica.status":1}
,"cluster-listener.buffer.size":{"shows":1}
,"shows":{"size":1,"replication":1,"number":1,"average":1,"host":1,"connection":1,"incremental":1,"synchronization":1}
,"size":{"cluster":1}
,"cluster":{"listener":1,"cluster":1,"replicate":1,"replica":1,"replica-specific":1}
,"listener":{"buffer":1}
,"buffer":{"config.replication-mode":1,"going":1}
,"config.replication-mode":{"shows":1}
,"mode":{"(unidirectional":1}
,"(unidirectional":{"bidirectional)":1}
,"bidirectional)":{"conflict.count":1,"replica.tps":1}
,"conflict.count":{"shows":1,"replication.tps":1}
,"number":{"conflicts":1,"element":1,"higher":1,"tend":1,"transactions":1,"broken":1,"entries":1}
,"conflicts":{"resolved":1}
,"resolved":{"conflict.table.size":1}
,"conflict.table.size":{"shows":1}
,"element":{"modification":1}
,"modification":{"entries":1}
,"entries":{"(puts\u002Fupdates\u002Fdeletes)":1,"may":1,"outbound":1}
,"(puts\u002Fupdates\u002Fdeletes)":{"currently":1}
,"currently":{"outstanding":1}
,"outstanding":{"entries":1}
,"may":{"may":1,"conflict":1}
,"conflict":{"simply":1}
,"simply":{"means":1}
,"means":{"replicated":1}
,"replicated":{"replicas":1}
,"replicas":{"wan":1,"count":1,"master":1,"total":1}
,"higher":{"conflict.count":1}
,"replication.tps":{"shows":1}
,"average":{"transaction":1,"transactions":1,"tps":1,"update":1}
,"transaction":{"rate":1}
,"rate":{"replicas":1,"during":1,"application\u0027s":1,"replica":1}
,"count":{"number":1}
,"tend":{"towards":1}
,"towards":{"slowest":1}
,"slowest":{"replica":1}
,"replica":{"cluster":1,"broken":1,"orchestrators":1,"statistics":1,"orchestrator":1,"cache":1,"replica.tps":1,"transactions":1,"sync.status":1,"sync.tps":1}
,"replicate":{"fast":1}
,"fast":{"slowest":1}
,"broken":{"down":1}
,"down":{"follows":1}
,"follows":{"replication.tps.oneminuterate":1,"replica.tps.oneminuterate":1,"sync.tps.oneminuterate":1}
,"replication.tps.oneminuterate":{"average":1}
,"transactions":{"per":1,"during":1,"application\u0027s":1}
,"per":{"second":1}
,"second":{"(tps)":1}
,"(tps)":{"rate":1,"broken":1}
,"during":{"previous":1,"application\u0027s":1}
,"previous":{"minute":1,"five":1,"fifteen":1}
,"minute":{"replication.tps.fiveminuterate":1,"replica.tps.fiveminuterate":1,"sync.tps.fiveminuterate":1}
,"replication.tps.fiveminuterate":{"average":1}
,"tps":{"rate":1,"during":1,"application\u0027s":1}
,"five":{"minutes":1}
,"minutes":{"replication.tps.fifteenminuterate":1,"replication.tps.meanrate":1,"replica.tps.fifteenminuterate":1,"replica.tps.meanrate":1,"sync.tps.fifteenminuterate":1,"sync.tps.meanrate":1}
,"replication.tps.fifteenminuterate":{"average":1}
,"fifteen":{"minutes":1}
,"replication.tps.meanrate":{"average":1}
,"application\u0027s":{"entire":1}
,"entire":{"lifetime":1}
,"lifetime":{"replication.tps.count":1,"topology.master":1,"replica.tps.count":1,"replicator.buffer.size":1,"sync.tps.count":1}
,"replication.tps.count":{"total":1}
,"total":{"number":1}
,"topology.master":{"shows":1}
,"host":{"name":1}
,"name":{"address":1}
,"address":{"cache\u0027s":1,"standby":1}
,"cache\u0027s":{"master":1,"replica":1}
,"topology.replicas":{"shows":1}
,"orchestrators":{"connected":1}
,"connected":{"topology.standby-masters":1}
,"topology.standby-masters":{"shows":1}
,"standby":{"(or":1}
,"(or":{"mirror)":1}
,"mirror)":{"server":1}
,"server":{"cluster":1}
,"overall":{"state":1}
,"replica.tps":{"shows":1}
,"update":{"rate":1}
,"replica.tps.oneminuterate":{"average":1}
,"replica.tps.fiveminuterate":{"average":1}
,"replica.tps.fifteenminuterate":{"average":1}
,"replica.tps.meanrate":{"average":1}
,"replica.tps.count":{"total":1}
,"replica-specific":{"statistics":1}
,"particular":{"replica":1}
,"replica.status":{"shows":1}
,"connection":{"status":1}
,"status":{"replica":1}
,"incremental":{"update":1}
,"replicator.buffer.size":{"shows":1}
,"outbound":{"buffer":1}
,"going":{"replica":1}
,"sync.status":{"shows":1}
,"synchronization":{"status":1,"rate":1}
,"sync.tps":{"shows":1}
,"sync.tps.oneminuterate":{"average":1}
,"sync.tps.fiveminuterate":{"average":1}
,"sync.tps.fifteenminuterate":{"average":1}
,"sync.tps.meanrate":{"average":1}
,"sync.tps.count":{"total":1}
}
;Search.control.loadWordPairs(pairs);
