var pairs =
{
"nonstop":{"operation":1,"feature":1,"timeout":1,"mode":1,"instance":1,"configuration":1,"instances":1,"behavior":1,"used":1}
,"operation":{"nonstop":1,"cannot":1,"unable":1}
,"feature":{"allows":1,"configuring":1}
,"allows":{"certain":1}
,"certain":{"operations":1}
,"operations":{"proceed":1,"example":1}
,"proceed":{"terracotta":1}
,"terracotta":{"clients":1,"cluster":1}
,"clients":{"become":1}
,"become":{"disconnected":1}
,"disconnected":{"cluster":1,"operation":1,"nonstop":1}
,"cluster":{"operation":1,"bigmemory":1,"offline":1,"high":1,"topology":1}
,"cannot":{"complete":1}
,"complete":{"nonstop":1,"within":1}
,"timeout":{"value":1,"allotted":1,"return":1}
,"value":{"useful":1}
,"useful":{"meeting":1,"write-through":1}
,"meeting":{"service-level":1}
,"service-level":{"agreement":1}
,"agreement":{"(sla)":1}
,"(sla)":{"requirements":1}
,"requirements":{"responding":1}
,"responding":{"node":1,"cluster":1}
,"node":{"failures":1}
,"failures":{"building":1}
,"building":{"robust":1}
,"robust":{"high":1}
,"high":{"availability":1}
,"availability":{"cluster":1,"cases":1,"consistency":1}
,"bigmemory":{"max":1}
,"max":{"nonstop":1,"rather":1,"becomes":1}
,"mode":{"client":1,"even":1}
,"client":{"receives":1,"disconnected":1,"unable":1}
,"receives":{"cluster":1}
,"offline":{"event":1}
,"event":{"note":1}
,"note":{"nonstop":1}
,"instance":{"nonstop":1}
,"even":{"client":1}
,"unable":{"complete":1,"locate":1}
,"within":{"timeout":1,"cap":1}
,"allotted":{"nonstop":1}
,"configuration":{"addition":1}
,"addition":{"nonstop":1}
,"instances":{"running":1}
,"running":{"client":1}
,"locate":{"tsa":1}
,"tsa":{"startup":1}
,"startup":{"initiate":1}
,"initiate":{"nonstop":1}
,"behavior":{"client":1}
,"used":{"conjunction":1}
,"conjunction":{"rejoin":1}
,"rejoin":{"information":1,"feature":1,"properties":1}
,"information":{"rejoin":1}
,"configuring":{"reconnection":1,"terracotta":1}
,"reconnection":{"rejoin":1}
,"properties":{"book":1}
,"book":{"configuring":1}
,"cases":{"include":1}
,"include":{"setting":1}
,"setting":{"timeouts":1}
,"timeouts":{"operations":1}
,"example":{"say":1}
,"say":{"bigmemory":1}
,"rather":{"mainframe":1}
,"mainframe":{"sla":1,"useful":1}
,"sla":{"calls":1}
,"calls":{"seconds":1}
,"seconds":{"temporary":1,"lookup":1}
,"temporary":{"network":1}
,"network":{"interruption":1,"partition":1}
,"interruption":{"delays":1}
,"delays":{"response":1}
,"response":{"cache":1}
,"cache":{"request":1}
,"request":{"timeout":1}
,"return":{"seconds":1}
,"lookup":{"done":1}
,"done":{"against":1}
,"against":{"mainframe":1}
,"write-through":{"writes":1}
,"writes":{"disk":1,"automatically":1}
,"disk":{"synchronous":1}
,"synchronous":{"writes":1}
,"automatically":{"responding":1}
,"topology":{"events":1}
,"events":{"pre-configured":1}
,"pre-configured":{"action":1}
,"action":{"allowing":1}
,"allowing":{"availability":1}
,"consistency":{"within":1}
,"cap":{"theorem":1}
,"theorem":{"network":1}
,"partition":{"occurs":1}
,"occurs":{"providing":1}
,"providing":{"graceful":1}
,"graceful":{"degradation":1}
,"degradation":{"user":1}
,"user":{"applications":1}
,"applications":{"distributed":1}
,"distributed":{"bigmemory":1}
,"becomes":{"unavailable":1}
}
;Search.control.loadWordPairs(pairs);
