var pairs =
{
"uninstalling":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"<<ffc-we":1,"following":1,"delete":1}
,"<<ffc-we":{"need":1}
,"need":{"develop":1}
,"develop":{"guidance":1}
,"guidance":{"regarding":1}
,"regarding":{"tmc":1}
,"tmc":{"tms":1,"directory":1}
,"tms":{"think":1,"tmc":1}
,"think":{"say":1}
,"say":{"removing":1}
,"removing":{"tms":1}
,"directory":{"name":1}
,"name":{"name":1,"used":1}
,"used":{"previous":1}
,"previous":{"topics":1}
,"topics":{"i\u2019m":1}
,"i\u2019m":{"confused":1}
,"confused":{"perhaps":1}
,"perhaps":{"tell":1}
,"tell":{"users":1}
,"users":{"stop":1}
,"stop":{"server":1}
,"server":{"running":1}
,"running":{"?>>":1}
,"?>>":{"want":1}
,"want":{"remove":1}
,"remove":{"terracotta":1}
,"following":{"uninstall":1}
,"uninstall":{"terracotta":1}
,"delete":{"~\u002F.tc\u002Fmgmt\u002Fdirectory":1}
}
;Search.control.loadWordPairs(pairs);
