var pairs =
{
".net":{"client":1}
,"client":{"demo":1,"step":1,"cross-language":1,"connector":1,"component":1,"dependencies":1}
,"demo":{"samples":1}
,"samples":{"following":1}
,"following":{"examples":1,"libraries":1,"files":1}
,"examples":{"provided":1}
,"provided":{"code-samples\u002Fdirectory":1}
,"code-samples\u002Fdirectory":{"kit":1}
,"kit":{"bson":1}
,"bson":{"example":1,"serializer":1}
,"example":{"bson":1,"consists":1,"create":1,"protocol":1,"recipe":1,"adding":1}
,"consists":{"three":1,"following":1}
,"three":{"files":1,".cs":1}
,"files":{"recipe2.cs":1,"add":1,"recipe.cs":1}
,"recipe2.cs":{"implementation":1}
,"implementation":{"recipe":1}
,"recipe":{"domain":1,"files":1,"object":1,"package":1,"classes":1}
,"domain":{"class":1,"attributes":1,"however":1,"object":1,"recipeserializer.cs":1}
,"class":{"includes":1,"itself":1,"class":1,"domain":1,"recipe2bsonserializer.cs":1,"tiny":1,"automatically":1,"simple":1}
,"includes":{"classes":1,"ingredients":1}
,"classes":{"recipe2":1,"things":1,"connector\u0027s":1,"classpath":1}
,"recipe2":{"class":1,"domain":1,"objects":1}
,"itself":{"plus":1}
,"plus":{"support":1}
,"support":{"classes":1}
,"things":{"ingredient":1}
,"ingredient":{"methoditem":1,"ingredient":1,"message":1,"{required":1,"optional":1,"alternative_ingredient":1}
,"methoditem":{"used":1,"items":1,"{required":1}
,"used":{"recipe2":1}
,"attributes":{"annotated":1}
,"annotated":{"bson":1}
,"serializer":{"necessary":1,"class":1,"recipe2consoleapp.cs":1,"simplerecipeconsoleapp.cs":1}
,"necessary":{"annotate":1}
,"annotate":{"domain":1}
,"however":{"add":1}
,"add":{"extra":1,"three":1,"following":1}
,"extra":{"code":1}
,"code":{"serializer":1}
,"recipe2bsonserializer.cs":{"implements":1}
,"implements":{"cacheserializer":1}
,"cacheserializer":{"<string":1,"interface":1}
,"<string":{"recipe2>":1}
,"recipe2>":{"interface":1}
,"interface":{"responsible":1,"serialization":1}
,"responsible":{"serializing":1}
,"serializing":{"deserializing":1}
,"deserializing":{"keys":1}
,"keys":{"values":1}
,"values":{"moving":1}
,"moving":{"recipe2":1}
,"object":{"thrift":1,"handled":1}
,"thrift":{"types":1}
,"types":{"value":1}
,"value":{"storedvalue":1}
,"storedvalue":{"serialization":1}
,"serialization":{"deserialization":1}
,"deserialization":{"recipe2":1,"recipe":1}
,"objects":{"handled":1}
,"handled":{"json.net":1,"google":1}
,"json.net":{"automatic":1}
,"automatic":{"bson":1}
,"recipe2consoleapp.cs":{"contains":1}
,"contains":{"main":1}
,"main":{"class":1}
,"tiny":{"repository":1}
,"repository":{"pre-generated":1}
,"pre-generated":{"recipes":1}
,"recipes":{"console":1}
,"console":{"app":1,"application":1}
,"app":{"understands":1}
,"understands":{"put":1}
,"put":{"assuming":1,"mac&cheese":1,"breadedchicken":1,"example":1}
,"assuming":{"start":1}
,"start":{"connector":1,"server":1}
,"connector":{"machine":1,"run":1,"classpaths":1,"component":1}
,"machine":{"may":1}
,"may":{"recipe2consoleapp":1}
,"recipe2consoleapp":{"put":1,"mac&cheese":1,"breadedchicken":1}
,"mac&cheese":{"recipe2consoleapp":1,"breadedchicken":1}
,"breadedchicken":{"recipe2consoleapp":1,"mac&cheese":1,"two":1}
,"two":{"preloaded":1}
,"preloaded":{"recipes)":1}
,"recipes)":{"run":1}
,"run":{"bson":1,"console":1,"protocol":1,"example":1,"simplerecipeconsoleapp":1}
,"create":{"new":1}
,"new":{"visual":1}
,"visual":{"studio":1}
,"studio":{"project":1}
,"project":{"add":1,"bigmemory_csharp.dll":1}
,".cs":{"recipe":1}
,"libraries":{"references":1}
,"references":{"section":1}
,"section":{"project":1}
,"bigmemory_csharp.dll":{"(included":1}
,"(included":{"kit)":1}
,"kit)":{"thrift.dll":1,"nirvana":1,"newtonsoft.json.dll":1,"protobuf-net.dll":1}
,"thrift.dll":{"(included":1}
,"nirvana":{"dotnet.dll":1}
,"dotnet.dll":{"(included":1}
,"newtonsoft.json.dll":{"(available":1}
,"(available":{"http:\u002F\u002Fjson.codeplex.com\u002F)":1,"http:\u002F\u002Fcode.google.com\u002Fp\u002Fprotobuf-net\u002F)":1}
,"http:\u002F\u002Fjson.codeplex.com\u002F)":{"start":1}
,"server":{"described":1}
,"described":{"installing":1}
,"installing":{"configuring":1}
,"configuring":{".net":1}
,"step":{"start":1}
,"application":{"(recipe2consoleapp.cs)":1,"(simplerecipeconsoleapp.cs)":1}
,"(recipe2consoleapp.cs)":{"protocol":1}
,"protocol":{"buffer":1}
,"buffer":{"example":1,"serializer":1}
,"recipe.cs":{"implementation":1}
,"automatically":{"generated":1}
,"generated":{"annotation":1}
,"annotation":{"included":1}
,"included":{"domain":1}
,"recipeserializer.cs":{"implements":1}
,"google":{"protocol":1}
,"simplerecipeconsoleapp.cs":{"contains":1}
,"simple":{"put":1}
,"package":{"includes":1,"recipeproject":1}
,"ingredients":{"measurements":1,"ingredients":1,"optional":1,"{repeated":1}
,"measurements":{"instructions":1}
,"instructions":{"package":1,"message":1}
,"recipeproject":{"message":1}
,"message":{"recipestructure":1,"ingredients":1,"ingredient":1,"measurement":1,"ingredientdescription":1,"method":1,"methoditem":1,"servinginstructions":1}
,"recipestructure":{"{required":1}
,"{required":{"string":1,"float":1,"int32":1}
,"string":{"name":1,"description":1,"measurement_type":1,"ingredient":1,"instruction":1}
,"name":{"required":1}
,"required":{"string":1,"int32":1,"method":1,"ingredients":1,"measurement":1,"ingredientdescription":1}
,"description":{"required":1}
,"int32":{"preparation_time":1,"baking_time":1,"step_number":1,"servings":1}
,"preparation_time":{"required":1}
,"method":{"method":1,"required":1,"{repeated":1,"run":1}
,"optional":{"int32":1,"servinginstructions":1,"ingredient":1,"method":1}
,"baking_time":{"optional":1}
,"servinginstructions":{"instructions":1,"{required":1}
,"{repeated":{"ingredient":1,"methoditem":1}
,"float":{"quantity":1}
,"quantity":{"required":1}
,"measurement":{"measurement":1,"required":1,"{required":1,"serving_measurement":1}
,"ingredientdescription":{"ingredient":1,"{required":1}
,"measurement_type":{"message":1}
,"alternative_ingredient":{"message":1}
,"items":{"message":1}
,"step_number":{"required":1}
,"instruction":{"message":1}
,"servings":{"required":1}
,"serving_measurement":{"optional":1}
,"protobuf-net.dll":{"(available":1}
,"http:\u002F\u002Fcode.google.com\u002Fp\u002Fprotobuf-net\u002F)":{"start":1}
,"(simplerecipeconsoleapp.cs)":{"already":1}
,"already":{"installed":1}
,"installed":{"bigmemory":1}
,"bigmemory":{"client":1,".net":1}
,"cross-language":{"connector":1}
,"adding":{"external":1}
,"external":{"protobuf":1}
,"protobuf":{"dependency":1}
,"dependency":{"maven":1,"need":1}
,"maven":{"link":1}
,"link":{"<dependency>":1}
,"<dependency>":{"<groupid>":1}
,"<groupid>":{"com.google.protobuf":1}
,"com.google.protobuf":{"<\u002Fgroupid>":1}
,"<\u002Fgroupid>":{"<artifactid>":1}
,"<artifactid>":{"protobuf-java":1}
,"protobuf-java":{"<\u002Fartifactid>":1}
,"<\u002Fartifactid>":{"<version>":1}
,"<version>":{"2.5.0":1}
,"2.5.0":{"<\u002Fversion>":1}
,"<\u002Fversion>":{"<\u002Fdependency>":1}
,"<\u002Fdependency>":{"dependency":1}
,"need":{"bigmemory":1}
,"classpaths":{"connector":1}
,"component":{"needs":1,"run":1}
,"needs":{"ehcachethriftconfiguration.builder":1}
,"ehcachethriftconfiguration.builder":{".cacheserializerfactory":1}
,".cacheserializerfactory":{"(recipeserializerfactory.class)":1}
,"(recipeserializerfactory.class)":{"recipeserializerfactory":1}
,"recipeserializerfactory":{"recipeserializer":1}
,"recipeserializer":{"recipe":1}
,"connector\u0027s":{"classpath":1}
,"classpath":{"bigmemory":1,"along":1}
,"simplerecipeconsoleapp":{"requires":1,"recipeserializer":1}
,"requires":{"simplerecipeconsoleapp":1}
,"along":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
