var pairs =
{
"specific":{"errors":1}
,"errors":{"warnings":1,"connectivity":1,"stating":1,"terracotta":1}
,"warnings":{"warning":1,"containing":1,"however":1}
,"warning":{"warn":1,"repeatedly":1,"logged":1,"changeapplicator":1,"messages":1}
,"warn":{"com.tc.bytes.tcbytebufferfactory":1,"com.tc.object.applicator.changeapplicator.com":1}
,"com.tc.bytes.tcbytebufferfactory":{"-asking":1}
,"-asking":{"large":1}
,"large":{"amount":1,"number":1,"fit":1}
,"amount":{"memory":1}
,"memory":{"mean":1}
,"mean":{"warning":1}
,"repeatedly":{"objects":1}
,"objects":{"larger":1,"sent":1,"shared":1}
,"larger":{"recommended":1}
,"recommended":{"maximum":1}
,"maximum":{"shared":1}
,"shared":{"terracotta":1,"low-memory":1}
,"terracotta":{"cluster":1,"server":1,"database":1,"product":1,"schema":1,"configuration":1,"kit":1,"ehcache":1,"servers":1,"sample":1,"welcome":1}
,"cluster":{"objects":1}
,"sent":{"clients":1}
,"clients":{"servers":1,"normally":1,"however":1}
,"servers":{"case":1,"restartable":1,"*******************************************************************************this":1,"crash":1,"java.net.unknownhostexception":1,"form":1,"cannot":1}
,"case":{"related":1,"warning":1,"action":1}
,"related":{"warnings":1}
,"containing":{"text":1}
,"text":{"similar":1,"confirm":1}
,"similar":{"attempt":1,"following":1,"com.sleepycat.je.log.checksumexception":1}
,"attempt":{"read":1}
,"read":{"byte":1,"invalid":1}
,"byte":{"array":1}
,"array":{"len":1}
,"len":{"12251178":1}
,"12251178":{"threshold=8000000":1}
,"threshold=8000000":{"attempting":1}
,"attempting":{"send":1}
,"send":{"message":1}
,"message":{"(com.tc.net.protocol.delivery.oooprotocolmessageimpl)":1,"starting":1}
,"(com.tc.net.protocol.delivery.oooprotocolmessageimpl)":{"size":1}
,"size":{"may":1}
,"may":{"appear":1,"result":1,"error":1,"need":1,"followed":1,"contain":1,"able":1,"behavior":1,"exceeding":1,"responsible":1}
,"appear":{"logs":1}
,"logs":{"large":1,"reveal":1}
,"number":{"over-sized":1,"processes":1}
,"over-sized":{"objects":1}
,"low-memory":{"issues":1}
,"issues":{"degradation":1}
,"degradation":{"performance":1}
,"performance":{"may":1,"(reads":1}
,"result":{"addition":1}
,"addition":{"elements":1}
,"elements":{"large":1}
,"fit":{"client":1}
,"client":{"cached":1}
,"cached":{"value":1}
,"value":{"stored":1}
,"stored":{"server":1}
,"server":{"thus":1,"throw":1,"expecting":1,"older":1,"fail":1,"fails":1,"element":1,"instances":1,"crash":1,"restart":1}
,"thus":{"degrading":1}
,"degrading":{"performance":1}
,"(reads":{"slower)":1}
,"slower)":{"case":1}
,"logged":{"starting":1}
,"starting":{"terracotta":1,"bootjartool":1,"two":1}
,"throw":{"dbversionmismatchexception":1}
,"dbversionmismatchexception":{"server":1}
,"expecting":{"terracotta":1}
,"database":{"compatible":1,"note":1}
,"compatible":{"version":1}
,"version":{"finding":1,"usually":1,"database":1,"terracotta":1,"you\u0027ve":1}
,"finding":{"non-compatible":1}
,"non-compatible":{"version":1}
,"usually":{"occurs":1}
,"occurs":{"starting":1,"there\u0027s":1,"experience":1}
,"older":{"version":1}
,"note":{"occur":1}
,"occur":{"servers":1,"example":1}
,"restartable":{"mode":1}
,"mode":{"getting":1}
,"getting":{"methodnotfound":1,"exceptions":1}
,"methodnotfound":{"classnotfound":1}
,"classnotfound":{"exceptions":1,"exception":1}
,"exceptions":{"you\u0027ve":1,"sure":1,"errors":1}
,"you\u0027ve":{"integrated":1,"specified":1}
,"integrated":{"terracotta":1}
,"product":{"framework":1,"isn\u0027t":1,"specified":1}
,"framework":{"spring":1}
,"spring":{"hibernate":1}
,"hibernate":{"getting":1}
,"sure":{"older":1}
,"isn\u0027t":{"classpath":1}
,"classpath":{"maven":1}
,"maven":{"involved":1}
,"involved":{"sometimes":1}
,"sometimes":{"older":1}
,"specified":{"framework\u0027s":1,"tools":1}
,"framework\u0027s":{"pom":1}
,"pom":{"ends":1}
,"ends":{"ahead":1}
,"ahead":{"current":1}
,"current":{"version":1}
,"tools":{"jconsole":1}
,"jconsole":{"jvisualvm":1}
,"jvisualvm":{"debug":1}
,"debug":{"specify":1}
,"specify":{"-xx":1}
,"-xx":{"traceclassloading":1}
,"traceclassloading":{"command":1}
,"command":{"line":1,"limits":1}
,"line":{"classnotfound":1,"column":1,"indicated":1}
,"exception":{"thrown":1}
,"thrown":{"startup":1,"try":1}
,"startup":{"refer":1}
,"refer":{"release":1}
,"release":{"platform":1}
,"platform":{"compatibility":1}
,"compatibility":{"information":1}
,"information":{"ensure":1}
,"ensure":{"supported":1}
,"supported":{"jdk":1}
,"jdk":{"(not":1,"1.6":1,"avoid":1}
,"(not":{"jre)":1}
,"jre)":{"installed":1}
,"installed":{"start":1}
,"start":{"terracotta":1,"error":1}
,"fail":{"schema":1}
,"schema":{"error":1,"[0]":1,"violation":1,"schema":1,"file":1,"files":1}
,"error":{"may":1,"similar":1,"message":1,"occurs":1,"text":1}
,"following":{"terracotta":1,"127.0.0.1":1,"command":1}
,"fails":{"start":1}
,"bootjartool":{"2008-10-08":1}
,"2008-10-08":{"10:29:29,278":1,"10:29:30,459":1}
,"10:29:29,278":{"info":1}
,"info":{"-terracotta":1}
,"-terracotta":{"2.7.0":1}
,"2.7.0":{"20081001-101049":1}
,"20081001-101049":{"(revision":1}
,"(revision":{"10251":1}
,"10251":{"cruise@rh4mo0":1}
,"cruise@rh4mo0":{"2.7)":1}
,"2.7)":{"2008-10-08":1}
,"10:29:30,459":{"fatal":1}
,"fatal":{"-*******************************************************************************the":1}
,"-*******************************************************************************the":{"configuration":1}
,"configuration":{"data":1,"file":1}
,"data":{"file":1}
,"file":{"\u0022\u002Fopt\u002Fterracotta\u002Fconf\u002Ftc-config.xml":1,"line":1,"follows":1,"included":1,"unknownhostexception":1,"may":1,"receive":1,"exists":1}
,"\u0022\u002Fopt\u002Fterracotta\u002Fconf\u002Ftc-config.xml":{"obey":1}
,"obey":{"terracotta":1}
,"[0]":{"line":1}
,"column":{"element":1}
,"element":{"allowed":1,"servers":1}
,"allowed":{"server":1}
,"*******************************************************************************this":{"error":1}
,"there\u0027s":{"schema":1}
,"violation":{"terracotta":1}
,"indicated":{"error":1}
,"confirm":{"configuration":1}
,"follows":{"required":1}
,"required":{"schema":1}
,"included":{"terracotta":1,"sample":1}
,"kit":{"kit":1,"includes":1}
,"includes":{"schema":1}
,"files":{"(*.xsd)":1}
,"(*.xsd)":{"terracotta":1}
,"ehcache":{"quartz":1}
,"quartz":{"configurations":1}
,"configurations":{"terracotta":1}
,"crash":{"regularly":1,"logging":1}
,"regularly":{"checksumexception":1,"java.io.ioexception":1}
,"checksumexception":{"logs":1}
,"reveal":{"error":1}
,"com.sleepycat.je.log.checksumexception":{"read":1}
,"invalid":{"log":1,"etc\u002Fhosts":1}
,"log":{"entry":1}
,"entry":{"type":1}
,"type":{"log_checksum":1}
,"log_checksum":{"likely":1}
,"likely":{"corrupted":1}
,"corrupted":{"disk":1}
,"disk":{"least":1,"space":1,"possible":1}
,"least":{"servers":1}
,"java.net.unknownhostexception":{"thrown":1}
,"try":{"run":1}
,"run":{"terracotta":1,"following":1,"shell":1}
,"sample":{"applications":1}
,"applications":{"unknownhostexception":1,"linux":1}
,"unknownhostexception":{"occurs":1,"may":1}
,"experience":{"trouble":1}
,"trouble":{"running":1}
,"running":{"terracotta":1}
,"welcome":{"application":1}
,"application":{"included":1}
,"linux":{"(especially":1}
,"(especially":{"ubuntu)":1}
,"ubuntu)":{"may":1}
,"need":{"edit":1}
,"edit":{"etc\u002Fhosts":1}
,"etc\u002Fhosts":{"file":1}
,"followed":{"unknown-ip-address":1}
,"unknown-ip-address":{"example":1}
,"example":{"etc\u002Fhosts":1,"starting":1,"limit":1}
,"contain":{"settings":1}
,"settings":{"similar":1}
,"127.0.0.1":{"localhost":1}
,"localhost":{"127.0.1.1":1}
,"127.0.1.1":{"myubuntu.usa":1,"host\u0027s":1}
,"myubuntu.usa":{"myubuntu":1}
,"myubuntu":{"myubuntu":1,"host":1}
,"host":{"change":1}
,"change":{"127.0.1.1":1}
,"host\u0027s":{"true":1}
,"true":{"address":1}
,"address":{"may":1}
,"able":{"successfully":1}
,"successfully":{"start":1}
,"instances":{"even":1}
,"even":{"invalid":1}
,"receive":{"exceptions":1}
,"connectivity":{"problems":1}
,"problems":{"occur":1}
,"two":{"terracotta":1}
,"form":{"mirror":1}
,"mirror":{"group":1}
,"group":{"(one":1}
,"(one":{"active":1}
,"active":{"standby)":1,"restart":1,"server":1}
,"standby)":{"may":1}
,"behavior":{"indicates":1}
,"indicates":{"servers":1}
,"cannot":{"communicate":1,"created":1}
,"communicate":{"node":1}
,"node":{"plenty":1}
,"plenty":{"ram":1}
,"ram":{"disk":1}
,"space":{"failure":1}
,"failure":{"errors":1,"update":1}
,"stating":{"native":1}
,"native":{"thread":1}
,"thread":{"cannot":1}
,"created":{"may":1}
,"exceeding":{"limit":1}
,"limit":{"system":1,"number":1}
,"system":{"level":1}
,"level":{"*nix":1}
,"*nix":{"run":1}
,"limits":{"ulimit":1}
,"ulimit":{"example":1}
,"processes":{"run":1}
,"shell":{"may":1}
,"responsible":{"errors":1}
,"java.io.ioexception":{"file":1}
,"exists":{"java.io.ioexception":1,"early":1}
,"early":{"versions":1}
,"versions":{"jdk":1}
,"1.6":{"jvm":1}
,"jvm":{"bug":1}
,"bug":{"caused":1}
,"caused":{"failure":1}
,"update":{"jdk":1}
,"avoid":{"issue":1}
,"issue":{"warning":1}
,"changeapplicator":{"servermapapplicator":1}
,"servermapapplicator":{"mean":1}
,"messages":{"warn":1}
,"com.tc.object.applicator.changeapplicator.com":{"terracotta.toolkit.collections.map.servermapapplicator":1}
,"terracotta.toolkit.collections.map.servermapapplicator":{"-servermap":1}
,"-servermap":{"received":1,"shouldn\u0027t":1}
,"received":{"delta":1}
,"delta":{"changes":1}
,"changes":{"methods":1,"unless":1,"broadcasted":1}
,"methods":{"clear":1}
,"clear":{"warn":1}
,"shouldn\u0027t":{"normally":1}
,"normally":{"broadcasting":1,"broadcasted":1}
,"broadcasting":{"changes":1}
,"unless":{"it\u0027s":1}
,"it\u0027s":{"clear\u002Fdestroy":1}
,"clear\u002Fdestroy":{"resent":1}
,"resent":{"txn":1}
,"txn":{"crash":1}
,"logging":{"telling":1}
,"telling":{"changes":1}
,"broadcasted":{"clients":1,"safe":1}
,"however":{"event":1,"probably":1}
,"event":{"failover":1}
,"failover":{"active":1,"case":1}
,"restart":{"disk":1,"failover":1}
,"possible":{"transactions":1}
,"transactions":{"broadcasted":1}
,"safe":{"ignore":1}
,"ignore":{"warnings":1}
,"probably":{"good":1}
,"good":{"idea":1}
,"idea":{"really":1}
,"really":{"active":1}
,"action":{"necessary":1}
}
;Search.control.loadWordPairs(pairs);
