var pairs =
{
"event":{"types":1,"help":1,"message":1}
,"types":{"definitions":1,"events":1}
,"definitions":{"section":1}
,"section":{"describes":1}
,"describes":{"types":1}
,"events":{"found":1,"notes":1,"indicate":1}
,"found":{"logs":1}
,"logs":{"viewed":1}
,"viewed":{"tmc":1}
,"tmc":{"memory.longgc":1}
,"memory.longgc":{"(memory":1}
,"(memory":{"manager)":1}
,"manager)":{"level":1}
,"level":{"warn":1,"info":1,"error":1,"critical":1}
,"warn":{"cause":1}
,"cause":{"full":1,"periodic":1,"(terracotta":1,"inline":1,"topology.node.joined":1,"specified":1,"changing":1,"unsuccessfully":1,"active":1,"mirror":1,"trying":1,"restart":1,"accepting":1,"cluster":1,"automatic":1,"system":1,"entered":1,"returned":1}
,"full":{"garbage":1}
,"garbage":{"collection":1,"creation":1,"dgc.periodic.finished":1,"dgc.inline.cleanup.started":1}
,"collection":{"(gc)":1,"(dgc)":1}
,"(gc)":{"longer":1}
,"longer":{"configured":1}
,"configured":{"threshold":1}
,"threshold":{"occurred":1,"seconds":1}
,"occurred":{"action":1}
,"action":{"reduce":1,"periodic":1,"action":1,"necessary":1,"investigate":1,"check":1,"rejoin":1,"mirror":1,"event":1,"synchronize":1,"managing":1}
,"reduce":{"cache":1}
,"cache":{"memory":1}
,"memory":{"footprint":1,"action":1,"resources":1}
,"footprint":{"(terracotta":1}
,"(terracotta":{"client)":1,"server)":1}
,"client)":{"investigate":1}
,"investigate":{"issues":1,"unusual":1,"possible":1}
,"issues":{"application":1,"issues":1,"local":1}
,"application":{"logic":1}
,"logic":{"garbage":1}
,"creation":{"notes":1}
,"notes":{"default":1,"periodic":1,"event":1,"seen":1,"possibly":1,"none":1,"zap":1,"restarted":1,"emitting":1}
,"default":{"critical":1,"mostly":1,"tolerance":1}
,"critical":{"threshold":1,"cause":1}
,"seconds":{"reconfigured":1}
,"reconfigured":{"tc.properties":1}
,"tc.properties":{"using":1,"terracotta":1}
,"using":{"longgc.threshhold":1,"fast":1,"time.sync.threshold":1}
,"longgc.threshhold":{"information":1}
,"information":{"setting":1}
,"setting":{"tc.properties":1}
,"terracotta":{"configuration":1,"server":1}
,"configuration":{"parameters":1,"started":1,"ended":1,"cancelled":1,"reloaded":1}
,"parameters":{"occurrence":1,"note":1}
,"occurrence":{"event":1}
,"help":{"diagnose":1}
,"diagnose":{"certain":1}
,"certain":{"failures":1}
,"failures":{"details":1}
,"details":{"configuring":1}
,"configuring":{"healthchecker":1}
,"healthchecker":{"properties":1}
,"properties":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"high-availability":1}
,"high-availability":{"guide":1}
,"guide":{"dgc.periodic.started":1}
,"dgc.periodic.started":{"(dgc)":1}
,"(dgc)":{"level":1,"explicitly":1,"action":1}
,"info":{"cause":1}
,"periodic":{"distributed":1,"dgc":1}
,"distributed":{"garbage":1}
,"explicitly":{"enabled":1}
,"enabled":{"configuration":1}
,"started":{"cleanup":1,"dirty":1}
,"cleanup":{"cycle":1,"finished":1}
,"cycle":{"action":1}
,"dgc":{"unneeded":1,"disabled":1,"explicitly":1,"[{0}":1,"wperiodichich":1,"operation":1}
,"unneeded":{"disable":1}
,"disable":{"improve":1}
,"improve":{"overall":1}
,"overall":{"cluster":1}
,"cluster":{"performance":1,"behavior":1,"action":1,"already":1,"configuration":1}
,"performance":{"notes":1,"may":1,"returned":1}
,"disabled":{"default":1}
,"mostly":{"useful":1}
,"useful":{"absence":1}
,"absence":{"automatic":1}
,"automatic":{"handling":1,"operation":1,"evictions":1}
,"handling":{"distributed":1}
,"dgc.periodic.finished":{"(dgc)":1}
,"ended":{"cleanup":1}
,"message":{"reads":1}
,"reads":{"dgc":1,"inline":1,"moved":1,"{0}":1,"split":1,"started":1,"dcv2":1}
,"[{0}":{"finished":1,"reference":1}
,"finished":{"begin":1}
,"begin":{"count":1}
,"count":{"{1}":1}
,"{1}":{"collected":1,"tried":1,"active":1,"two":1,"usage":1}
,"collected":{"{2}":1}
,"{2}":{"time":1,"server":1}
,"time":{"taken":1}
,"taken":{"{3}":1,"(msecs)={0}":1}
,"{3}":{"live":1}
,"live":{"objects":1}
,"objects":{"{4}":1}
,"{4}":{"dgc.periodic.canceled":1,"dgc.inline.cleanup.canceled":1}
,"dgc.periodic.canceled":{"(dgc)":1}
,"wperiodichich":{"explicitly":1}
,"cancelled":{"due":1}
,"due":{"interruption":1}
,"interruption":{"(for":1}
,"(for":{"example":1}
,"example":{"failover":1,"long":1,"initializing":1}
,"failover":{"operation)":1,"events":1}
,"operation)":{"action":1}
,"dgc.inline.cleanup.started":{"(dgc)":1}
,"server)":{"starting":1}
,"starting":{"active":1}
,"active":{"existing":1,"upon":1,"server":1,"left":1,"{0}":1,"role":1,"topology.db.dirty":1,"normally":1}
,"existing":{"data":1}
,"data":{"triggering":1,"place":1,"data":1,"may":1,"resync":1}
,"triggering":{"inline":1}
,"inline":{"distributed":1,"dgc":1}
,"necessary":{"notes":1}
,"seen":{"server":1}
,"server":{"starts":1,"connection":1,"left":1,"array":1}
,"starts":{"active":1}
,"upon":{"recovery":1}
,"recovery":{"using":1}
,"fast":{"restartability":1}
,"restartability":{"dgc.inline.cleanup.finished":1}
,"dgc.inline.cleanup.finished":{"(dgc)":1}
,"operation":{"completed":1,"interrupted":1,"restarted":1,"happens":1,"require":1}
,"completed":{"action":1}
,"reference":{"cleanup":1}
,"dgc.inline.cleanup.canceled":{"(dgc)":1}
,"interrupted":{"action":1}
,"unusual":{"cluster":1}
,"behavior":{"events":1}
,"possibly":{"occurs":1}
,"occurs":{"during":1}
,"during":{"failover":1}
,"indicate":{"real":1,"insufficient":1}
,"real":{"cause":1}
,"topology.node.joined":{"(cluster":1}
,"(cluster":{"topology)":1}
,"topology)":{"level":1}
,"specified":{"node":1}
,"node":{"joined":1,"left":1,"resources)":1}
,"joined":{"cluster":1}
,"none":{"topology.node.left":1,"topology.node.state":1,"topology.mirror.left":1,"topology.zap.received":1,"dcv2.servermap.eviction":1}
,"topology.node.left":{"(cluster":1}
,"left":{"cluster":1,"(for":1,"notes":1}
,"check":{"node":1,"state":1,"active":1,"mirror":1}
,"long":{"network":1}
,"network":{"issues":1}
,"local":{"node":1}
,"resources)":{"notes":1}
,"topology.node.state":{"(cluster":1}
,"changing":{"state":1}
,"state":{"(for":1,"change":1,"topology.handshake.reject":1,"zapped":1}
,"initializing":{"active)":1}
,"active)":{"action":1,"zapped":1}
,"change":{"expected":1}
,"expected":{"notes":1}
,"moved":{"{0}":1}
,"{0}":{"{0}":1,"new":1,"client":1,"{1}":1,"clients":1,"becomes":1,"mirror":1,"nearing":1,"identification":1,"capacity":1}
,"new":{"state":1}
,"topology.handshake.reject":{"(cluster":1}
,"error":{"cause":1}
,"unsuccessfully":{"trying":1}
,"trying":{"reconnect":1,"cause":1,"join":1}
,"reconnect":{"cluster":1}
,"already":{"expelled":1}
,"expelled":{"action":1}
,"rejoin":{"operation":1}
,"restarted":{"manually":1,"notes":1,"mirror":1}
,"manually":{"notes":1,"restart":1,"wiped":1}
,"client":{"{1}":1}
,"tried":{"connect":1}
,"connect":{"{2}":1}
,"connection":{"refused":1}
,"refused":{"topology.active.left":1}
,"topology.active.left":{"(cluster":1}
,"topology.mirror.left":{"(cluster":1}
,"mirror":{"server":1,"left":1,"behaves":1,"group":1,"manually":1,"trying":1,"automatically":1,"l2s":1}
,"topology.zap.received":{"(cluster":1}
,"restart":{"zap":1,"order":1,"notes":1,"wipe":1,"{0}":1}
,"zap":{"action":1,"operation":1,"order)":1,"order":1}
,"possible":{"split":1}
,"split":{"brain":1}
,"brain":{"situation":1,"{0}":1}
,"situation":{"mirror":1}
,"behaves":{"active)":1}
,"zapped":{"obey":1,"ensure":1}
,"obey":{"restart":1}
,"order":{"notes":1,"restart":1,"issued":1}
,"happens":{"within":1}
,"within":{"mirror":1}
,"group":{"event":1}
,"two":{"servers":1}
,"servers":{"vying":1}
,"vying":{"active":1}
,"role":{"topology.zap.accepted":1}
,"topology.zap.accepted":{"(cluster":1}
,"accepting":{"order":1}
,"order)":{"action":1}
,"ensure":{"restarts":1}
,"restarts":{"mirror":1}
,"issued":{"within":1}
,"clients":{"exiting":1}
,"exiting":{"{0}":1,"restart":1}
,"becomes":{"active":1}
,"topology.db.dirty":{"(cluster":1}
,"join":{"data":1}
,"place":{"action":1}
,"automatically":{"restart":1,"restarting":1}
,"wipe":{"data":1}
,"may":{"need":1,"degraded":1}
,"need":{"manually":1}
,"wiped":{"restarted":1}
,"l2s":{"wipe":1}
,"resync":{"active":1}
,"normally":{"automatic":1}
,"require":{"action":1}
,"dirty":{"database":1}
,"database":{"exiting":1}
,"restarting":{"topology.config.reloaded":1}
,"topology.config.reloaded":{"(cluster":1}
,"reloaded":{"action":1}
,"dcv2.servermap.eviction":{"(dcv2)":1}
,"(dcv2)":{"level":1}
,"evictions":{"optimizing":1}
,"optimizing":{"terracotta":1}
,"array":{"operations":1}
,"operations":{"action":1,"accepted":1}
,"dcv2":{"eviction":1}
,"eviction":{"-time":1}
,"-time":{"taken":1}
,"(msecs)={0}":{"number":1}
,"number":{"entries":1,"segments":1}
,"entries":{"evicted={1}":1}
,"evicted={1}":{"number":1}
,"segments":{"threshold={2}":1}
,"threshold={2}":{"total":1}
,"total":{"overshoot={3}":1}
,"overshoot={3}":{"system.time.different":1}
,"system.time.different":{"(system":1}
,"(system":{"setup)":1}
,"setup)":{"level":1}
,"system":{"clocks":1}
,"clocks":{"aligned":1,"notes":1}
,"aligned":{"action":1}
,"synchronize":{"system":1}
,"tolerance":{"seconds":1,"introduce":1}
,"time.sync.threshold":{"information":1}
,"note":{"overly":1}
,"overly":{"large":1}
,"large":{"tolerance":1}
,"introduce":{"unpredictable":1}
,"unpredictable":{"errors":1}
,"errors":{"behaviors":1}
,"behaviors":{"resource.capacity.near":1}
,"resource.capacity.near":{"(resource)":1}
,"(resource)":{"level":1}
,"entered":{"throttled":1,"restricted":1}
,"throttled":{"mode":1,"restricted":1}
,"mode":{"temporary":1,"action":1}
,"temporary":{"condition":1}
,"condition":{"(e.g":1}
,"(e.g":{"caused":1}
,"caused":{"bulk-loading)":1}
,"bulk-loading)":{"indicate":1}
,"insufficient":{"allocation":1}
,"allocation":{"memory":1}
,"managing":{"near-memory-full":1}
,"near-memory-full":{"conditions":1}
,"conditions":{"notes":1}
,"emitting":{"emit":1}
,"emit":{"resource.capacityrestored":1}
,"resource.capacityrestored":{"(return":1}
,"(return":{"normal":1}
,"normal":{"mode)":1,"throttled":1,"-{1}":1}
,"mode)":{"resource.fullcapacity":1,"based":1}
,"resource.fullcapacity":{"(move":1}
,"(move":{"restricted":1}
,"restricted":{"mode)":1,"mode":1}
,"based":{"resource":1}
,"resource":{"availability":1}
,"availability":{"event":1}
,"nearing":{"capacity":1}
,"capacity":{"limit":1,"restored":1}
,"limit":{"performance":1,"further":1}
,"degraded":{"-{1}":1}
,"-{1}":{"usage":1}
,"usage":{"{0}":1,"memory":1}
,"identification":{"{1}":1}
,"resources":{"allocated":1}
,"allocated":{"resource.capacity.full":1,"resource.capacity.restored":1}
,"resource.capacity.full":{"(resource)":1}
,"further":{"additive":1}
,"additive":{"operations":1}
,"accepted":{"-{1}":1}
,"resource.capacity.restored":{"(resource)":1}
,"returned":{"normal":1}
,"restored":{"performance":1}
}
;Search.control.loadWordPairs(pairs);
