var pairs =
{
"designing":{"testing":1}
,"testing":{"cluster":1,"robust":1,"necessary":1}
,"cluster":{"architecture":1}
,"architecture":{"section":1,"recommendations":1}
,"section":{"presents":1}
,"presents":{"recommendations":1}
,"recommendations":{"designing":1,"tested":1}
,"robust":{"cluster":1}
,"tested":{"shown":1}
,"shown":{"effective":1}
,"effective":{"certain":1}
,"certain":{"circumstances":1}
,"circumstances":{"custom":1}
,"custom":{"environment":1}
,"environment":{"additional":1}
,"additional":{"testing":1}
,"necessary":{"ensure":1}
,"ensure":{"optimal":1}
,"optimal":{"setup":1}
,"setup":{"meet":1}
,"meet":{"specific":1}
,"specific":{"demands":1}
,"demands":{"related":1}
,"related":{"factors":1}
,"factors":{"load":1}
}
;Search.control.loadWordPairs(pairs);
