var pairs =
{
"tuning":{"heap":1,"parameters":1}
,"heap":{"memory":1,"running":1}
,"memory":{"performance":1,"java":1,"subject":1,"footprint":1,"allocated":1}
,"performance":{"long":1,"large":1,"operational":1,"may":1}
,"long":{"garbage":1,"cycles":1}
,"garbage":{"collection":1,"garbage":1,"collected":1,"ensuring":1}
,"collection":{"(gc)":1,"time":1}
,"(gc)":{"cycles":1}
,"cycles":{"common":1,"cause":1,"understood":1,"increase":1,"tuning":1}
,"common":{"causes":1}
,"causes":{"issues":1}
,"issues":{"terracotta":1,"printing":1,"raises":1}
,"terracotta":{"cluster":1,"servers)":1}
,"cluster":{"full":1,"account":1}
,"full":{"event":1,"garbage":1}
,"event":{"pauses":1}
,"pauses":{"threads":1}
,"threads":{"jvm":1,"parallel":1}
,"jvm":{"servers":1,"options":1,"jdk":1,"refactoring":1}
,"servers":{"disconnecting":1,"timed-out":1}
,"disconnecting":{"clients":1}
,"clients":{"clients":1,"dropping":1}
,"dropping":{"servers":1}
,"timed-out":{"processes":1}
,"processes":{"just":1,"machine":1}
,"just":{"problems":1}
,"problems":{"long":1}
,"cause":{"having":1}
,"having":{"clear":1}
,"clear":{"understanding":1}
,"understanding":{"application":1,"create":1}
,"application":{"behaves":1,"using":1,"contexts":1,"processes":1,"data":1}
,"behaves":{"respect":1}
,"respect":{"creating":1}
,"creating":{"garbage":1}
,"collected":{"necessary":1}
,"necessary":{"avoiding":1}
,"avoiding":{"solving":1}
,"solving":{"issues":1}
,"printing":{"analyzing":1}
,"analyzing":{"logs":1}
,"logs":{"effective":1,"activity":1}
,"effective":{"gain":1}
,"gain":{"understanding":1}
,"create":{"profile":1,"garbage":1}
,"profile":{"application":1}
,"using":{"tools":1,"jvm":1,"java":1}
,"tools":{"made":1}
,"made":{"purpose":1}
,"purpose":{"consider":1}
,"consider":{"using":1,"following":1,"-xx":1}
,"options":{"generate":1}
,"generate":{"logs":1}
,"activity":{"-verbose:gc":1}
,"-verbose:gc":{"-xloggc":1}
,"-xloggc":{"<filename>":1}
,"<filename>":{"-xx":1}
,"-xx":{"printgcdetails":1,"printgctimestamps":1,"useparallelgc":1,"useparalleloldgc":1,"usecompressedoops":1}
,"printgcdetails":{"-xx":1}
,"printgctimestamps":{"apply":1}
,"apply":{"appropriate":1}
,"appropriate":{"parsing":1}
,"parsing":{"visualization":1}
,"visualization":{"tool":1}
,"tool":{"log":1}
,"log":{"files":1,"statistics":1}
,"files":{"help":1}
,"help":{"analyze":1}
,"analyze":{"contents":1}
,"contents":{"observing":1}
,"observing":{"statistics":1}
,"statistics":{"jstat":1,"using":1,"updated":1}
,"jstat":{"observe":1,"following":1,"-gcutil":1}
,"observe":{"statistics":1}
,"java":{"utility":1,"applications":1}
,"utility":{"jstat":1}
,"following":{"command":1,"solutions":1}
,"command":{"produce":1}
,"produce":{"log":1}
,"updated":{"every":1}
,"every":{"ten":1}
,"ten":{"seconds":1}
,"seconds":{"jstat":1,"acceptable":1}
,"-gcutil":{"<pid>":1}
,"<pid>":{"1000000":1}
,"1000000":{"important":1}
,"important":{"statistic":1}
,"statistic":{"full":1}
,"time":{"difference":1,"reading":1,"system":1}
,"difference":{"total":1}
,"total":{"time":1}
,"reading":{"amount":1}
,"amount":{"time":1}
,"system":{"paused":1}
,"paused":{"jump":1}
,"jump":{"few":1}
,"few":{"seconds":1}
,"acceptable":{"application":1}
,"contexts":{"solutions":1}
,"solutions":{"problematic":1,"maximizing":1}
,"problematic":{"once":1}
,"once":{"application\u0027s":1}
,"application\u0027s":{"typical":1}
,"typical":{"cycles":1}
,"understood":{"consider":1}
,"maximizing":{"bigmemory":1}
,"bigmemory":{"eliminate":1,"opens":1}
,"eliminate":{"drag":1}
,"drag":{"imposes":1}
,"imposes":{"performance":1}
,"large":{"heaps":1}
,"heaps":{"bigmemory":1}
,"opens":{"off-heap":1}
,"off-heap":{"memory":1}
,"applications":{"off-heap":1,"unnecessarily":1}
,"subject":{"configuring":1}
,"configuring":{"healthchecker":1}
,"healthchecker":{"parameters":1}
,"parameters":{"terracotta":1,"change":1}
,"account":{"observed":1}
,"observed":{"cycles":1}
,"increase":{"nodes":1}
,"nodes":{"tolerance":1,"due":1}
,"tolerance":{"inactivity":1}
,"inactivity":{"nodes":1}
,"due":{"cycles":1,"certain":1}
,"change":{"runs":1}
,"runs":{"heap":1}
,"running":{"multi-core":1,"multiple":1,"64-bit":1}
,"multi-core":{"machines":1}
,"machines":{"collector":1}
,"collector":{"specifically":1,"-xx:parallelgcthreads=<number>":1,"called":1,"normally":1}
,"specifically":{"configured":1}
,"configured":{"consider":1}
,"useparallelgc":{"-xx":1}
,"useparalleloldgc":{"running":1}
,"multiple":{"jvms":1}
,"jvms":{"application":1}
,"machine":{"tune":1}
,"tune":{"number":1}
,"number":{"concurrent":1}
,"concurrent":{"threads":1,"mark":1}
,"parallel":{"collector":1}
,"-xx:parallelgcthreads=<number>":{"collector":1}
,"called":{"concurrent":1}
,"mark":{"sweep":1}
,"sweep":{"(cms)":1}
,"(cms)":{"collector":1}
,"normally":{"recommended":1}
,"recommended":{"(especially":1}
,"(especially":{"terracotta":1}
,"servers)":{"due":1}
,"certain":{"performance":1,"circumstances":1}
,"operational":{"issues":1}
,"raises":{"however":1}
,"however":{"certain":1}
,"circumstances":{"related":1}
,"related":{"type":1}
,"type":{"hosting":1}
,"hosting":{"platform":1}
,"platform":{"application":1}
,"data":{"usage":1}
,"usage":{"characteristics":1}
,"characteristics":{"may":1}
,"may":{"boost":1,"worth":1}
,"boost":{"performance":1}
,"worth":{"testing":1}
,"testing":{"running":1}
,"64-bit":{"jvm":1}
,"jdk":{"supports":1}
,"supports":{"-xx":1}
,"usecompressedoops":{"setting":1}
,"setting":{"reduce":1}
,"reduce":{"substantially":1}
,"substantially":{"memory":1}
,"footprint":{"object":1}
,"object":{"pointer":1}
,"pointer":{"used":1}
,"used":{"jvm":1}
,"refactoring":{"clustered":1}
,"clustered":{"applications":1}
,"unnecessarily":{"create":1}
,"ensuring":{"problem":1}
,"problem":{"node":1}
,"node":{"enough":1}
,"enough":{"memory":1}
,"allocated":{"heap":1}
}
;Search.control.loadWordPairs(pairs);
