var pairs =
{
"configuring":{"security":1}
,"security":{"using":1,"based":1,"enabled":1,"effect":1,"incorrectly":1}
,"using":{"ldap":1,"earlier":1,"shutdown":1}
,"ldap":{"(via":1,"follow":1,"security":1}
,"(via":{"jaas)":1}
,"jaas)":{"lightweight":1}
,"lightweight":{"directory":1}
,"directory":{"access":1,"named":1}
,"access":{"protocol":1}
,"protocol":{"(ldap)":1}
,"(ldap)":{"security":1}
,"based":{"jaas":1}
,"jaas":{"requires":1}
,"requires":{"java":1}
,"java":{"1.6":1,"prevent":1,"property":1}
,"1.6":{"using":1}
,"earlier":{"version":1}
,"version":{"java":1}
,"prevent":{"terracotta":1}
,"terracotta":{"servers":1,"{com.sun.security.auth.module.ldaploginmodule":1,"configuration":1,"<\u002Flogin-config-name>":1,"server":1}
,"servers":{"running":1}
,"running":{"security":1}
,"enabled":{"configure":1}
,"configure":{"security":1}
,"follow":{"steps":1}
,"steps":{"save":1}
,"save":{"following":1,"file":1}
,"following":{"configuration":1}
,"configuration":{"file":1,"<server>":1}
,"file":{".java.login.config":1,"<server":1}
,".java.login.config":{"terracotta":1,"directory":1}
,"{com.sun.security.auth.module.ldaploginmodule":{"required":1}
,"required":{"java.naming.security.authentication=\u0022":1}
,"java.naming.security.authentication=\u0022":{"simple":1}
,"simple":{"userprovider=\u0022":1,"debug=true":1}
,"userprovider=\u0022":{"ldap:\u002F\u002Forgstage:389":1}
,"ldap:\u002F\u002Forgstage:389":{"authidentity=\u0022":1}
,"authidentity=\u0022":{"uid={username}":1}
,"uid={username}":{"ou=people":1}
,"ou=people":{"dc=terracotta":1}
,"dc=terracotta":{"dc=org":1}
,"dc=org":{"authzidentity=controlrole":1}
,"authzidentity=controlrole":{"usessl=false":1}
,"usessl=false":{"binddn=\u0022":1}
,"binddn=\u0022":{"cn=manager":1}
,"cn=manager":{"bindcredential=\u0022****\u0022":1}
,"bindcredential=\u0022****\u0022":{"bindauthenticationtype=\u0022":1}
,"bindauthenticationtype=\u0022":{"simple":1}
,"debug=true":{"edit":1}
,"edit":{"values":1}
,"values":{"userprovider":1,"environment":1}
,"userprovider":{"(ldap":1}
,"(ldap":{"server)":1}
,"server)":{"authidentity":1}
,"authidentity":{"(user":1}
,"(user":{"identity)":1}
,"identity)":{"bindcredential":1}
,"bindcredential":{"(encrypted":1}
,"(encrypted":{"password)":1}
,"password)":{"match":1}
,"match":{"values":1}
,"environment":{"save":1}
,"named":{"java":1}
,"property":{"user.home":1}
,"user.home":{"add":1}
,"add":{"following":1}
,"<server>":{"block":1}
,"block":{"terracotta":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"myhost":1}
,"myhost":{"name=\u0022":1}
,"name=\u0022":{"myserver":1}
,"myserver":{"<authentication>":1}
,"<authentication>":{"<mode>":1}
,"<mode>":{"<login-config-name>":1}
,"<login-config-name>":{"terracotta":1}
,"<\u002Flogin-config-name>":{"<\u002Fmode>":1}
,"<\u002Fmode>":{"<\u002Fauthentication>":1}
,"<\u002Fauthentication>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"start":1}
,"start":{"terracotta":1}
,"server":{"look":1,"started":1,"using":1}
,"look":{"log":1}
,"log":{"message":1}
,"message":{"containing":1}
,"containing":{"info":1}
,"info":{"-credentials":1}
,"-credentials":{"loginconfig":1}
,"loginconfig":{"[terracotta]":1}
,"[terracotta]":{"confirm":1}
,"confirm":{"ldap":1}
,"effect":{"security":1}
,"incorrectly":{"terracotta":1}
,"started":{"however":1}
,"however":{"able":1}
,"able":{"shut":1}
,"shut":{"down":1}
,"down":{"server":1}
,"shutdown":{"script":1}
,"script":{"(stop-tc-server)":1}
}
;Search.control.loadWordPairs(pairs);
