var pairs =
{
"sizing":{"panel":1}
,"panel":{"sizing":1,"provides":1,"shows":1}
,"provides":{"information":1}
,"information":{"usage":1}
,"usage":{"heap":1,"active":1,"tier":1,"graphs":1,"value":1}
,"heap":{"off-heap":1}
,"off-heap":{"disk":1}
,"disk":{"tiers":1}
,"tiers":{"caches":1}
,"caches":{"selected":1}
,"selected":{"cachemanager":1,"tier":1,"cache":1,"tier\u0027s":1}
,"cachemanager":{"view":1,"select":1,"cachemanager":1,"drop-down":1}
,"view":{"tier":1}
,"tier":{"usage":1,"relative":1,"-table":1,"selected":1,"drop-down":1,"graphs":1,"-overall":1,"bar":1,"-usage":1,"-the":1,"cache":1,"table":1,"menu":1}
,"active":{"cachemanager":1}
,"select":{"cachemanager":1}
,"drop-down":{"menu":1}
,"menu":{"usage":1,"table":1,"bar":1,"number":1,"selected":1,"determines":1,"indicates":1}
,"relative":{"cache":1}
,"cache":{"sizes":1,"-the":1,"icon":1,"distributed":1,"currently":1,"data":1,"entries":1,"entry":1,"usage":1,"choose":1,"selected":1,"drop-down":1,"miss":1,"misses":1,"specified":1,"menu":1,"shown":1,"uses":1}
,"sizes":{"tier":1}
,"-table":{"displays":1}
,"displays":{"usage":1}
,"table":{"following":1,"cache-related":1,"click":1}
,"following":{"columns":1,"bar":1}
,"columns":{"cache":1}
,"-the":{"name":1,"size":1,"total":1,"rate":1}
,"name":{"cache":1}
,"icon":{"indicates":1}
,"indicates":{"whether":1,"cache":1}
,"whether":{"cache":1}
,"distributed":{"standalone":1}
,"standalone":{"size":1}
,"size":{"(mb)":1,"cache\u0027s":1,"(bytes)":1,"cache":1}
,"(mb)":{"-the":1}
,"cache\u0027s":{"data":1}
,"data":{"megabytes":1,"used":1,"entries":1}
,"megabytes":{"value":1}
,"value":{"snapshot":1,"float":1}
,"snapshot":{"accurate":1}
,"accurate":{"until":1}
,"until":{"server":1}
,"server":{"fully":1}
,"fully":{"processed":1}
,"processed":{"data":1}
,"used":{"-percent":1,"cache":1}
,"-percent":{"total":1}
,"total":{"storage":1,"number":1,"resource":1}
,"storage":{"allotted":1}
,"allotted":{"cache":1}
,"currently":{"used":1}
,"entries":{"-the":1,"mean":1}
,"number":{"cache":1,"misses":1}
,"mean":{"entry":1}
,"entry":{"size":1,"click":1}
,"(bytes)":{"-an":1}
,"-an":{"estimate":1}
,"estimate":{"average":1}
,"average":{"size":1}
,"click":{"row":1,"tier\u0027s":1}
,"row":{"table":1}
,"cache-related":{"tier":1}
,"graphs":{"display":1,"panel":1,"usage":1,"highlighted":1}
,"display":{"values":1,"exact":1}
,"values":{"named":1,"tier":1}
,"named":{"cache":1}
,"shows":{"following":1,"total":1}
,"bar":{"graphs":1,"shows":1,"display":1,"selected":1,"lighter":1}
,"-overall":{"usage":1}
,"resource":{"allocated":1,"control":1}
,"allocated":{"amount":1}
,"amount":{"amount":1,"available":1}
,"available":{"cache":1}
,"-usage":{"tier":1}
,"choose":{"cache":1}
,"miss":{"rate":1}
,"rate":{"tier":1,"cache":1}
,"misses":{"tier":1,"displayed":1}
,"specified":{"selected":1}
,"displayed":{"bar":1}
,"exact":{"usage":1}
,"float":{"mouse":1}
,"mouse":{"pointer":1}
,"pointer":{"bar":1}
,"tier\u0027s":{"bar":1}
,"lighter":{"color":1}
,"color":{"bars":1}
,"bars":{"selected":1}
,"determines":{"cache":1}
,"shown":{"cache-related":1}
,"highlighted":{"relative":1}
,"uses":{"size-based":1}
,"size-based":{"(automatic":1}
,"(automatic":{"resource":1}
,"control":{"arc)":1}
,"arc)":{"entry-based":1}
,"entry-based":{"sizing":1}
}
;Search.control.loadWordPairs(pairs);
