var pairs =
{
"changing":{"cluster":1,"topology":1}
,"cluster":{"topology":1,"bigmemory":1}
,"topology":{"reload":1,"live":1}
,"reload":{"terracotta":1}
,"terracotta":{"configuration":1}
,"configuration":{"add":1,"file":1,"editing":1}
,"add":{"remove":1}
,"remove":{"servers":1}
,"servers":{"configuration":1,"section":1}
,"file":{"edited":1}
,"edited":{"made":1}
,"made":{"available":1}
,"available":{"every":1}
,"every":{"server":1}
,"server":{"client":1}
,"client":{"reloaded":1}
,"reloaded":{"successfully":1}
,"successfully":{"information":1}
,"information":{"terracotta":1}
,"editing":{"servers":1}
,"section":{"changing":1}
,"live":{"cluster":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
