var pairs =
{
"configuring":{"terracotta":1,"cluster":1}
,"terracotta":{"cluster":1,"server":1,"servers":1,"configuration":1,"unless":1,"separate":1}
,"cluster":{"step":1,"add":1,"multiple":1,"closer":1,"configuring":1,"high":1,"shut":1,"create":1,"sure":1,"information":1}
,"step":{"shows":1}
,"shows":{"run":1}
,"run":{"clients":1,"cluster":1}
,"clients":{"servers":1,"-->":1}
,"servers":{"separate":1,"creating":1,"install":1,"node":1,"<param-value>":1,"configured":1,"start":1}
,"separate":{"machines":1,"machine":1}
,"machines":{"add":1}
,"add":{"failover":1,"high":1,"second":1}
,"failover":{"(high":1}
,"(high":{"availability)":1}
,"availability)":{"expand":1}
,"expand":{"terracotta":1}
,"high":{"availability":1}
,"availability":{"doing":1,"bigmemory":1}
,"doing":{"following":1}
,"following":{"moving":1,"xml":1,"replacing":1}
,"moving":{"terracotta":1}
,"server":{"machine":1,"array":1,"found":1,"referred":1,"-->":1,"configure":1,"list":1,"following":1,"tc-config.xml":1,"start":1}
,"machine":{"creating":1,"server":1,"entering":1}
,"creating":{"cluster":1,"multiple":1}
,"multiple":{"terracotta":1,"application":1}
,"application":{"nodes":1,"node":1,"application":1,"servers":1,"server":1}
,"nodes":{"tasks":1}
,"tasks":{"bring":1}
,"bring":{"cluster":1}
,"closer":{"production":1}
,"production":{"architecture":1}
,"architecture":{"additional":1}
,"additional":{"details":1}
,"details":{"configuring":1}
,"array":{"terracotta":1}
,"configuration":{"parameters":1,"file":1,"add":1}
,"parameters":{"chapters":1}
,"chapters":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1,"high-availability":1}
,"administrator":{"guide":1}
,"guide":{"additional":1,"configure":1}
,"high-availability":{"guide":1}
,"configure":{"terracotta":1,"tc-config.xml":1}
,"shut":{"down":1}
,"down":{"terracotta":1}
,"create":{"terracotta":1}
,"file":{"called":1}
,"called":{"tc-config.xml":1}
,"tc-config.xml":{"contents":1,"copy":1,"location":1,"unix\u002Flinux":1}
,"contents":{"similar":1}
,"similar":{"following":1}
,"xml":{"version=\u0022":1}
,"version=\u0022":{"1.0":1}
,"1.0":{"encoding=\u0022":1}
,"encoding=\u0022":{"utf-8":1}
,"utf-8":{"<!--all":1}
,"<!--all":{"content":1}
,"content":{"terracotta":1}
,"unless":{"otherwise":1}
,"otherwise":{"indicated":1}
,"indicated":{"-->":1}
,"-->":{"<tc:tc-config":1,"<server":1,"<clients>":1}
,"<tc:tc-config":{"xsi:schemalocation=\u0022":1}
,"xsi:schemalocation=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":{"xmlns:tc=\u0022":1}
,"xmlns:tc=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"<servers>":1}
,"<servers>":{"<!--sets":1}
,"<!--sets":{"terracotta":1,"generated":1}
,"found":{"replace":1}
,"replace":{"value":1}
,"value":{"host":1}
,"host":{"server\u0027s":1}
,"server\u0027s":{"address":1}
,"address":{"-->":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"server.1.ip.address":1,"server.2.ip.address":1}
,"server.1.ip.address":{"name=\u0022":1}
,"name=\u0022":{"server1":1,"server2":1}
,"server1":{"<data>":1,"name":1,"microsoft":1,"configured":1}
,"<data>":{"(user.home)\u002Fterracotta\u002Fserver-data":1}
,"(user.home)\u002Fterracotta\u002Fserver-data":{"<\u002Fdata>":1}
,"<\u002Fdata>":{"<logs>":1}
,"<logs>":{"(user.home)\u002Fterracotta\u002Fserver-logs":1,"(user.home)\u002Fterracotta\u002Fclient-logs":1}
,"(user.home)\u002Fterracotta\u002Fserver-logs":{"<\u002Flogs>":1}
,"<\u002Flogs>":{"<\u002Fserver>":1,"<\u002Fclients>":1}
,"<\u002Fserver>":{"<!--if":1,"<\u002Fservers>":1}
,"<!--if":{"using":1}
,"using":{"standby":1,"jmx":1}
,"standby":{"terracotta":1,"passive":1,"servers":1}
,"referred":{"active-passive":1}
,"active-passive":{"configuration":1}
,"second":{"server":1}
,"server.2.ip.address":{"name=\u0022":1}
,"server2":{"<data>":1}
,"<\u002Fservers>":{"<!--sets":1}
,"generated":{"client":1}
,"client":{"logs":1}
,"logs":{"saved":1}
,"saved":{"clients":1}
,"<clients>":{"<logs>":1}
,"(user.home)\u002Fterracotta\u002Fclient-logs":{"<\u002Flogs>":1}
,"<\u002Fclients>":{"<\u002Ftc:tc-config>":1}
,"<\u002Ftc:tc-config>":{"install":1}
,"install":{"terracotta":1,"sessions":1,"application":1}
,"copy":{"tc-config.xml":1}
,"location":{"accessible":1}
,"accessible":{"terracotta":1}
,"sessions":{"jar":1,"managing":1,"using":1}
,"jar":{"files":1}
,"files":{"application":1,"installing":1}
,"node":{"want":1,"information":1}
,"want":{"run":1}
,"sure":{"install":1}
,"information":{"installing":1,"using":1}
,"installing":{"sessions":1,"session":1}
,"session":{"jars":1}
,"jars":{"edit":1}
,"edit":{"web.xml":1}
,"web.xml":{"application":1}
,"list":{"terracotta":1}
,"<param-value>":{"server.1.ip.address:9510":1}
,"server.1.ip.address:9510":{"server.2.ip.address:9510":1}
,"server.2.ip.address:9510":{"<\u002Fparam-value>":1}
,"<\u002Fparam-value>":{"start":1}
,"start":{"terracotta":1,"server":1,"becomes":1,"standby":1,"application":1,"jmx":1}
,"replacing":{"server1":1}
,"name":{"gave":1,"flag":1}
,"gave":{"server":1}
,"unix\u002Flinux":{"[prompt]":1}
,"[prompt]":{"${terracotta_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":1,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":1}
,"${terracotta_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":{"<path\u002Fto\u002Ftc-config.xml>":1}
,"<path\u002Fto\u002Ftc-config.xml>":{"\u005C-n":1}
,"\u005C-n":{"server1":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":{"<path\u005Cto\u005Ctc-config.xml>":1}
,"<path\u005Cto\u005Ctc-config.xml>":{"server1":1}
,"configured":{"second":1,"start":1}
,"entering":{"name":1}
,"flag":{"second":1}
,"becomes":{"hot":1}
,"hot":{"standby":1}
,"passive":{"servers":1}
,"jmx":{"console":1,"web":1}
,"console":{"tool":1}
,"tool":{"view":1}
,"view":{"cluster":1}
,"web":{"sessions":1}
,"managing":{"web":1}
}
;Search.control.loadWordPairs(pairs);
