var pairs =
{
"sizing":{"distributed":1,"attributes":1,"terracotta":1,"panel":1}
,"distributed":{"caches":1,"\u0022\u002F>":1}
,"caches":{"terracotta":1,"sized":1,"except":1,"storage":1,"elements":1}
,"terracotta":{"distributed":1,"server":1,"cluster":1,"management":1}
,"sized":{"caches":1}
,"except":{"local":1}
,"local":{"disk":1,"configuration":1}
,"disk":{"therefore":1}
,"therefore":{"cannot":1}
,"cannot":{"configured":1}
,"configured":{"*localdisk":1,"cache":1}
,"*localdisk":{"sizing":1}
,"attributes":{"distributed":1,"behave":1,"caches":1,"fixed":1,"vary":1}
,"storage":{"resources":1}
,"resources":{"available":1}
,"available":{"terracotta":1}
,"server":{"array":1}
,"array":{"bigmemory":1,"administrator":1,"provides":1,"evict":1,"based":1,"maxentriesincache":1}
,"bigmemory":{"max":1}
,"max":{"fast":1}
,"fast":{"restart":1,"restartability":1}
,"restart":{"store":1}
,"store":{"information":1}
,"information":{"fast":1,"eviction":1,"terracotta":1}
,"restartability":{"distributed":1}
,"cluster":{"reliability":1,"cache-configuration":1,"expected":1}
,"reliability":{"terracotta":1}
,"administrator":{"guide":1}
,"guide":{"cache-configuration":1,"sizing":1}
,"cache-configuration":{"sizing":1}
,"behave":{"local":1}
,"configuration":{"means":1,"loaded":1,"node":1,"terracotta":1}
,"means":{"every":1,"cache":1}
,"every":{"node":1}
,"node":{"load":1,"<cache":1,"configuration":1,"regardless":1}
,"load":{"sizing":1}
,"elements":{"attributes":1}
,"fixed":{"first":1}
,"first":{"ehcache":1}
,"ehcache":{"configuration":1}
,"loaded":{"cluster":1}
,"vary":{"across":1}
,"across":{"nodes":1}
,"nodes":{"cache":1}
,"cache":{"example":1,"may":1,"exceeds":1,"eviction":1,"addition":1,"entries":1,"unbounded":1,"respect":1,"sizes":1}
,"example":{"cache":1}
,"may":{"following":1}
,"following":{"configuration":1,"size":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"mycache":1}
,"mycache":{"maxentrieslocalheap=\u0022":1,"unlimited":1,"entries":1}
,"maxentrieslocalheap=\u0022":{"10000":1}
,"10000":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"eternal=\u0022":1,"10g":1}
,"eternal=\u0022":{"false":1}
,"false":{"timetoidleseconds=\u0022":1}
,"timetoidleseconds=\u0022":{"3600":1}
,"3600":{"timetoliveseconds=\u0022":1}
,"timetoliveseconds=\u0022":{"1800":1}
,"1800":{"<persistence":1,"maxentriesincache=\u0022":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"distributed":1}
,"\u0022\u002F>":{"<terracotta\u002F>":1}
,"<terracotta\u002F>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"cache":1,"terracotta":1}
,"size":{"configuration":1,"constraints":1,"configured":1,"terracotta":1,"entry":1,"reported":1}
,"10g":{"eternal=\u0022":1}
,"exceeds":{"size":1}
,"constraints":{"node":1}
,"provides":{"mycache":1}
,"unlimited":{"amount":1}
,"amount":{"space":1}
,"space":{"spillover":1}
,"spillover":{"backup":1}
,"backup":{"impose":1}
,"impose":{"limit":1}
,"limit":{"maxentriesincache":1,"imposed":1}
,"maxentriesincache":{"positive":1,"however":1,"maxentriesincache":1,"default":1,"based":1}
,"positive":{"non-zero":1}
,"non-zero":{"value":1}
,"value":{"<cache":1,"used":1,"using":1}
,"maxentriesincache=\u0022":{"1000000":1}
,"1000000":{"<persistence":1}
,"evict":{"mycache":1,"cache":1}
,"entries":{"stay":1,"exist":1,"size":1}
,"stay":{"within":1}
,"within":{"limit":1}
,"however":{"particular":1}
,"particular":{"cache":1}
,"eviction":{"terracotta":1,"(but":1,"unbounded":1,"understanding":1}
,"based":{"largest":1,"entries":1,"expected":1}
,"largest":{"size":1}
,"addition":{"terracotta":1}
,"exist":{"least":1}
,"least":{"client":1}
,"client":{"node":1}
,"regardless":{"limit":1}
,"imposed":{"maxentriesincache":1}
,"default":{"value":1}
,"used":{"means":1}
,"unbounded":{"undergo":1,"cache":1}
,"undergo":{"capacity":1}
,"capacity":{"eviction":1}
,"(but":{"periodic":1}
,"periodic":{"resource":1}
,"resource":{"evictions":1,"management":1}
,"evictions":{"allowed)":1}
,"allowed)":{"although":1}
,"although":{"bounds":1}
,"bounds":{"enforced":1}
,"enforced":{"capacity":1}
,"respect":{"practical":1}
,"practical":{"limitation":1}
,"limitation":{"equal":1}
,"equal":{"integer.max_value":1}
,"integer.max_value":{"(app":1}
,"(app":{"billion":1}
,"billion":{"entries)":1}
,"entries)":{"information":1}
,"understanding":{"automatic":1}
,"automatic":{"resource":1}
,"management":{"terracotta":1,"console":1}
,"expected":{"average":1,"data":1}
,"average":{"size":1,"cache-entry":1}
,"entry":{"discover":1}
,"discover":{"value":1}
,"using":{"terracotta":1}
,"console":{"(tmc)":1,"user":1}
,"(tmc)":{"test":1}
,"test":{"cluster":1}
,"data":{"connect":1,"sizing":1}
,"connect":{"tmc":1}
,"tmc":{"navigate":1,"estimate":1}
,"navigate":{"application":1}
,"application":{"data":1}
,"panel":{"review":1}
,"review":{"relative":1}
,"relative":{"cache":1}
,"sizes":{"tier":1}
,"tier":{"section":1}
,"section":{"note":1}
,"note":{"average":1}
,"cache-entry":{"size":1}
,"reported":{"tmc":1}
,"estimate":{"information":1}
,"user":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
