var pairs =
{
"example":{"nagios":1,"want":1}
,"nagios":{"integration":1,"plugins":1,"monitoring":1,"monitor":1,"report":1,"plugin":1,"node":1,"standard":1}
,"integration":{"nagios":1}
,"plugins":{"standalone":1,"either":1}
,"standalone":{"extensions":1}
,"extensions":{"nagios":1}
,"monitoring":{"tool":1}
,"tool":{"allow":1}
,"allow":{"nagios":1}
,"monitor":{"external":1}
,"external":{"systems":1}
,"systems":{"plugins":1}
,"either":{"executable":1}
,"executable":{"scripts":1}
,"scripts":{"compiled":1}
,"compiled":{"binaries":1}
,"binaries":{"return":1}
,"return":{"certain":1}
,"certain":{"codes":1}
,"codes":{"processed":1}
,"processed":{"nagios":1}
,"report":{"status":1}
,"status":{"monitored":1}
,"monitored":{"service":1}
,"service":{"script":1}
,"script":{"included":1,"tc-rest-plugin.sh":1,"located":1,"takes":1}
,"included":{"example":1}
,"plugin":{"check":1,"script":1,"installed":1}
,"check":{"node.left":1,"applies":1,"last":1}
,"node.left":{"event":1}
,"event":{"occurred":1,"occurs":1}
,"occurred":{"node.left":1}
,"occurs":{"node":1}
,"node":{"leaves":1,"available":1}
,"leaves":{"terracotta":1}
,"terracotta":{"cluster":1,"server":1}
,"cluster":{"example":1}
,"want":{"receive":1}
,"receive":{"alert":1}
,"alert":{"nagios":1}
,"available":{"anymore":1}
,"anymore":{"script":1}
,"tc-rest-plugin.sh":{"provided":1}
,"provided":{"example":1}
,"located":{"code-samples\u002Fexample08-nagios-integration":1}
,"code-samples\u002Fexample08-nagios-integration":{"area":1}
,"area":{"installed":1}
,"installed":{"kit":1,"nagios":1}
,"kit":{"script":1}
,"takes":{"three":1}
,"three":{"parameters":1}
,"parameters":{"follows":1}
,"follows":{".\u002Ftc-rest-plugin.sh":1}
,".\u002Ftc-rest-plugin.sh":{"<servername>":1}
,"<servername>":{"<portnumber>":1,"name":1}
,"<portnumber>":{"<interval>":1,"terracotta":1}
,"<interval>":{"<servername>":1,"amount":1}
,"name":{"terracotta":1}
,"server":{"<portnumber>":1,"port":1}
,"port":{"(e.g":1}
,"(e.g":{"9530)":1,"check":1}
,"9530)":{"<interval>":1}
,"amount":{"time":1}
,"time":{"minutes":1}
,"minutes":{"past":1}
,"past":{"check":1}
,"applies":{"(e.g":1}
,"last":{"minutes)":1}
,"minutes)":{"plugin":1}
,"standard":{"plugin":1}
}
;Search.control.loadWordPairs(pairs);
