var pairs =
{
"charts":{"panel":1}
,"panel":{"charts":1,"graphs":1,"useful":1,"overview":1,"addition":1}
,"graphs":{"statistics":1}
,"statistics":{"available":1,"overview":1,"choose":1}
,"available":{"overview":1,"statistics":1}
,"overview":{"panel":1}
,"useful":{"tracking":1}
,"tracking":{"performance":1}
,"performance":{"trends":1}
,"trends":{"discovering":1}
,"discovering":{"potential":1}
,"potential":{"issues":1}
,"issues":{"information":1}
,"information":{"statistics":1}
,"addition":{"able":1}
,"able":{"select":1}
,"select":{"cachemanager":1,"specific":1}
,"cachemanager":{"scope":1,"graph":1}
,"scope":{"displayed":1}
,"displayed":{"data":1}
,"data":{"select":1}
,"specific":{"cache":1}
,"cache":{"(or":1}
,"(or":{"caches)":1}
,"caches)":{"selected":1}
,"selected":{"cachemanager":1}
,"graph":{"plots":1,"float":1,"chosen":1}
,"plots":{"appropriate":1}
,"appropriate":{"metrics":1}
,"metrics":{"along":1}
,"along":{"axis":1,"single":1}
,"axis":{"against":1}
,"against":{"system":1}
,"system":{"time":1}
,"time":{"axis)":1}
,"axis)":{"view":1}
,"view":{"value":1}
,"value":{"along":1}
,"single":{"point":1}
,"point":{"graph":1,"displays":1}
,"float":{"mouse":1}
,"mouse":{"pointer":1}
,"pointer":{"point":1}
,"displays":{"units":1}
,"units":{"used":1}
,"used":{"statistic":1}
,"statistic":{"graphed":1,"click":1}
,"graphed":{"choose":1,"particular":1}
,"choose":{"type":1,"statistic":1}
,"type":{"statistic":1}
,"particular":{"chart":1}
,"chart":{"click":1,"immediately":1}
,"click":{"chart\u0027s":1,"accept":1}
,"chart\u0027s":{"corresponding":1}
,"corresponding":{"configure":1}
,"configure":{"link":1}
,"link":{"open":1}
,"open":{"list":1}
,"list":{"available":1}
,"accept":{"change":1}
,"change":{"chart":1}
,"immediately":{"begins":1}
,"begins":{"graph":1}
,"chosen":{"statistic":1}
}
;Search.control.loadWordPairs(pairs);
