var pairs =
{
"installation":{"overview":1,"using":1,"refer":1,"bigmemory":1}
,"overview":{"system":1}
,"system":{"requirements":1}
,"requirements":{"terracotta":1,"found":1}
,"terracotta":{"software":1}
,"software":{"products":1,"documentation":1,"system":1,"installer":1}
,"products":{"available":1,"components":1}
,"available":{"software":1}
,"documentation":{"web":1,"product\u0027s":1}
,"web":{"site":1}
,"site":{"http:\u002F\u002Fdocumentation.softwareag.com\u002F":1}
,"http:\u002F\u002Fdocumentation.softwareag.com\u002F":{"using":1}
,"using":{"empower":1,"software":1}
,"empower":{"login":1}
,"login":{"password":1}
,"password":{"received":1}
,"received":{"email":1}
,"email":{"licensed":1}
,"licensed":{"product":1}
,"product":{"select":1,"suite":1}
,"select":{"link":1}
,"link":{"software":1}
,"found":{"documentation":1}
,"product\u0027s":{"respective":1}
,"respective":{"version":1}
,"version":{"install":1}
,"install":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"two":1,"details":1}
,"two":{"different":1}
,"different":{"ways":1}
,"ways":{"using":1}
,"installer":{"thus":1,"details":1}
,"thus":{"simplifying":1}
,"simplifying":{"integration":1}
,"integration":{"software":1}
,"components":{"webmethods":1}
,"webmethods":{"product":1}
,"suite":{"refer":1}
,"refer":{"section":1}
,"section":{"installation":1,"performing":1}
,"details":{"self-contained":1}
,"self-contained":{"standalone":1}
,"standalone":{"installation":1}
,"performing":{"standalone":1}
}
;Search.control.loadWordPairs(pairs);
