var pairs =
{
"configuration":{"overview":1,"block":1,"presentation":1,"realms":1,"terracotta":1}
,"overview":{"active":1}
,"active":{"directory":1}
,"directory":{"standard":1}
,"standard":{"ldap":1}
,"ldap":{"configured":1,"url":1}
,"configured":{"<auth>":1,"using":1}
,"<auth>":{"section":1,"<realm>":1}
,"section":{"server\u0027s":1}
,"server\u0027s":{"configuration":1}
,"block":{"<servers":1}
,"<servers":{"secure=\u0022":1}
,"secure=\u0022":{"true":1}
,"true":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"172.16.254.1":1}
,"172.16.254.1":{"name=\u0022":1}
,"name=\u0022":{"server1":1}
,"server1":{"<security>":1}
,"<security>":{"<auth>":1}
,"<realm>":{"<\u002Frealm>":1,"<url>":1}
,"<\u002Frealm>":{"<url>":1}
,"<url>":{"<\u002Furl>":1,"elements":1}
,"<\u002Furl>":{"<user>":1}
,"<user>":{"<\u002Fuser>":1,"element":1}
,"<\u002Fuser>":{"<\u002Fauth>":1}
,"<\u002Fauth>":{"<\u002Fsecurity>":1}
,"<\u002Fsecurity>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"active":1}
,"using":{"<realm>":1}
,"elements":{"<user>":1}
,"element":{"used":1}
,"used":{"connections":1,"document":1,"ldap":1}
,"connections":{"terracotta":1,"url":1}
,"terracotta":{"servers":1,"-the":1}
,"servers":{"required":1,"clearing":1}
,"required":{"ldap-related":1,"log":1,"ldap":1}
,"ldap-related":{"configuration":1}
,"presentation":{"urls":1}
,"urls":{"used":1,"configuration":1}
,"document":{"line":1}
,"line":{"breaks":1}
,"breaks":{"line":1,"creating":1}
,"creating":{"urls":1}
,"realms":{"roles":1,"map":1}
,"roles":{"setup":1,"admin":1}
,"setup":{"ldap-based":1}
,"ldap-based":{"authentication":1}
,"authentication":{"authorization":1}
,"authorization":{"uses":1}
,"uses":{"shiro":1}
,"shiro":{"realms":1}
,"map":{"user":1}
,"user":{"groups":1,"admin":1,"sets":1}
,"groups":{"following":1}
,"following":{"two":1}
,"two":{"roles":1}
,"admin":{"-the":1,"role":1}
,"-the":{"user":1,"operator":1}
,"role":{"initial":1,"performs":1,"required":1,"operator":1,"thereafter":1,"connect":1}
,"initial":{"user":1}
,"sets":{"security":1}
,"security":{"thereafter":1}
,"thereafter":{"user":1,"person":1}
,"performs":{"system":1}
,"system":{"functions":1}
,"functions":{"shutting":1}
,"shutting":{"down":1}
,"down":{"servers":1}
,"clearing":{"deleting":1}
,"deleting":{"caches":1}
,"caches":{"cache":1}
,"cache":{"managers":1}
,"managers":{"reloading":1}
,"reloading":{"configuration":1}
,"operator":{"role":1}
,"log":{"tmc":1}
,"tmc":{"even":1,"add":1}
,"even":{"user":1,"wrapped":1}
,"person":{"operator":1}
,"connect":{"tmc":1}
,"add":{"connections":1}
,"url":{"encoding":1,"encoded":1,"described":1}
,"encoding":{"certain":1}
,"certain":{"characters":1}
,"characters":{"used":1,"may":1}
,"encoded":{"unless":1,"even":1}
,"unless":{"wrapped":1}
,"wrapped":{"cdata":1}
,"cdata":{"construct":1,"=(equals":1}
,"construct":{"characters":1}
,"may":{"required":1}
,"described":{"below":1}
,"below":{"&(ampersand)":1}
,"&(ampersand)":{"-encode":1}
,"-encode":{"{(left":1,"(right":1,"space":1,"spaces":1}
,"{(left":{"brace)":1}
,"brace)":{"-encode":1}
,"(right":{"brace)":1}
,"space":{"-encode":1}
,"spaces":{"always":1}
,"always":{"encoded":1}
,"=(equals":{"sign)":1}
,"sign)":{"-does":1}
,"-does":{"require":1}
,"require":{"encoding":1}
}
;Search.control.loadWordPairs(pairs);
