var pairs =
{
"removing":{"existing":1}
,"existing":{"server":1}
,"server":{"remove":1,"terracotta":1,"want":1,"first":1,"online":1,"topology":1}
,"remove":{"server":1,"cluster":1}
,"terracotta":{"cluster":1,"configuration":1,"management":1}
,"cluster":{"configuration":1,"shutting":1,"sure":1,"terracotta":1,"selected":1}
,"configuration":{"follow":1,"file":1}
,"follow":{"steps":1}
,"steps":{"shut":1}
,"shut":{"down":1}
,"down":{"server":1,"active":1}
,"want":{"remove":1}
,"shutting":{"down":1}
,"active":{"server":1}
,"first":{"ensure":1}
,"ensure":{"backup":1}
,"backup":{"server":1}
,"online":{"enable":1}
,"enable":{"failover":1}
,"failover":{"delete":1}
,"delete":{"<server>":1}
,"<server>":{"block":1}
,"block":{"associated":1}
,"associated":{"removed":1}
,"removed":{"server":1}
,"file":{"used":1,"\u0027\u002Fbigmemory-max-4\u002Ftc-config.xml":1}
,"used":{"cluster":1}
,"sure":{"connected":1}
,"connected":{"tmc":1,"target":1}
,"tmc":{"tmc":1,"connected":1,"don":1,"click":1,"display":1}
,"target":{"cluster":1}
,"management":{"console":1}
,"console":{"user\u0027s":1}
,"user\u0027s":{"guide":1}
,"guide":{"information":1}
,"information":{"using":1}
,"using":{"tmc":1}
,"don":{"added":1}
,"added":{"link":1}
,"link":{"target":1}
,"selected":{"tmc":1}
,"click":{"administration":1,"reload":1}
,"administration":{"tab":1}
,"tab":{"choose":1}
,"choose":{"change":1}
,"change":{"topology":1}
,"topology":{"panel":1,"file":1,"reloaded":1}
,"panel":{"click":1}
,"reload":{"message":1,"operation":1}
,"message":{"appears":1,"similar":1}
,"appears":{"result":1}
,"result":{"reload":1}
,"operation":{"successful":1,"logs":1}
,"successful":{"operation":1}
,"logs":{"message":1}
,"similar":{"following":1}
,"following":{"2013-03-14":1}
,"2013-03-14":{"13:25:44,821":1}
,"13:25:44,821":{"info":1}
,"info":{"-successfully":1}
,"-successfully":{"overridden":1}
,"overridden":{"server":1}
,"\u0027\u002Fbigmemory-max-4\u002Ftc-config.xml":{"tmc":1}
,"display":{"event":1}
,"event":{"server":1}
,"reloaded":{"file":1}
}
;Search.control.loadWordPairs(pairs);
