var pairs =
{
"deployment":{"configuration":1}
,"configuration":{"simple":1,"network":1,"additional":1,"necessary":1,"machine":1,"(ip":1,"correct":1}
,"simple":{"deployment":1,"(no":1,"ping":1}
,"(no":{"network":1}
,"network":{"redundancy)":1,"configuration":1,"redundancy":1,"operating-system":1,"test":1,"determine":1,"network":1,"configured":1,"cable":1}
,"redundancy)":{"description":1}
,"description":{"simplest":1}
,"simplest":{"network":1}
,"redundancy":{"failure":1,"fs7":1}
,"failure":{"occurs":1,"additional":1,"scenarios":1,"expected":1,"until":1}
,"occurs":{"good":1}
,"good":{"chance":1}
,"chance":{"part":1}
,"part":{"cluster":1}
,"cluster":{"stop":1,"continues":1,"fs4":1,"fs5":1,"test":1}
,"stop":{"functioning":1}
,"functioning":{"failover":1}
,"failover":{"activity":1}
,"activity":{"terracotta":1}
,"terracotta":{"software":1}
,"software":{"diagram":1}
,"diagram":{"addresses":1}
,"addresses":{"merely":1}
,"merely":{"examples":1}
,"examples":{"demonstrate":1}
,"demonstrate":{"l1s":1}
,"l1s":{"(l1a":1,"fail":1}
,"(l1a":{"&l1b)":1}
,"&l1b)":{"l2s":1}
,"l2s":{"(tcservera":1}
,"(tcservera":{"&tcserverb)":1}
,"&tcserverb)":{"live":1}
,"live":{"different":1}
,"different":{"subnets":1}
,"subnets":{"actual":1}
,"actual":{"addressing":1}
,"addressing":{"scheme":1}
,"scheme":{"specific":1}
,"specific":{"environment":1}
,"environment":{"single":1}
,"single":{"switch":1,"point":1}
,"switch":{"single":1,"non-functioning":1,"reload":1}
,"point":{"failure":1}
,"additional":{"configuration":1,"network":1}
,"operating-system":{"configuration":1}
,"necessary":{"configuration":1}
,"machine":{"needs":1}
,"needs":{"proper":1}
,"proper":{"network":1}
,"(ip":{"address":1}
,"address":{"subnet":1}
,"subnet":{"mask":1}
,"mask":{"gateway":1}
,"gateway":{"dns":1}
,"dns":{"ntp":1}
,"ntp":{"hostname)":1}
,"hostname)":{"plugged":1}
,"plugged":{"network":1}
,"test":{"plan":1,"configuration":1}
,"plan":{"-network":1}
,"-network":{"failures":1,"tests":1}
,"failures":{"non-redundant":1}
,"non-redundant":{"network":1}
,"determine":{"configuration":1}
,"correct":{"following":1}
,"following":{"tests":1}
,"tests":{"confirm":1,"non-redundant":1,"testid":1}
,"confirm":{"failure":1}
,"scenarios":{"behave":1}
,"behave":{"expected":1}
,"expected":{"testid":1,"outcome":1}
,"testid":{"failure":1,"host":1}
,"outcome":{"fs1":1,"nt1":1}
,"fs1":{"loss":1}
,"loss":{"l1a":1,"l1b":1,"switch":1,"active":1,"mirror":1,"tcservers":1}
,"l1a":{"(link":1,"fs3":1,"&l1b":1}
,"(link":{"system)":1}
,"system)":{"cluster":1,"mirror":1}
,"continues":{"normal":1}
,"normal":{"using":1,"without":1}
,"using":{"l1b":1,"l1a":1}
,"l1b":{"fs2":1,"(link":1}
,"fs2":{"loss":1}
,"fs3":{"loss":1}
,"&l1b":{"non-functioning":1}
,"non-functioning":{"cluster":1}
,"fs4":{"loss":1}
,"fs5":{"loss":1}
,"active":{"(link":1,"l1s":1,"fs6":1}
,"mirror":{"becomes":1,"cluster":1}
,"becomes":{"new":1}
,"new":{"active":1}
,"fail":{"new":1}
,"fs6":{"loss":1}
,"without":{"redundancy":1}
,"fs7":{"loss":1}
,"tcservers":{"non-functioning":1}
,"configured":{"test":1}
,"ping":{"tests":1,"every":1,"nt2":1,"ping":1,"failure":1}
,"host":{"action":1,"successful":1}
,"action":{"expected":1}
,"nt1":{"ping":1}
,"every":{"host":1}
,"successful":{"ping":1}
,"nt2":{"pull":1}
,"pull":{"network":1}
,"cable":{"during":1}
,"during":{"continuous":1}
,"continuous":{"ping":1}
,"until":{"link":1,"reload":1}
,"link":{"restored":1}
,"restored":{"nt3":1}
,"nt3":{"switch":1}
,"reload":{"pings":1,"complete":1}
,"pings":{"cease":1}
,"cease":{"until":1}
,"complete":{"links":1}
,"links":{"restored":1}
}
;Search.control.loadWordPairs(pairs);
