var pairs =
{
"behavior":{"tsa":1,"near-memory-full":1}
,"tsa":{"near-memory-full":1,"put":1,"move":1,"enters":1,"behavior":1,"attempts":1,"returns":1,"automatically":1}
,"near-memory-full":{"conditions":1,"condition":1}
,"conditions":{"near-memory-full":1,"usage":1}
,"condition":{"evictions":1}
,"evictions":{"happening":1,"continue":1,"state":1,"time":1}
,"happening":{"fast":1}
,"fast":{"enough":1}
,"enough":{"keep":1}
,"keep":{"data":1}
,"data":{"within":1,"access":1,"slowed":1,"blocked":1,"evictable":1,"present":1,"back":1}
,"within":{"bigmemory":1,"configured":1,"limitations":1}
,"bigmemory":{"size":1}
,"size":{"limitations":1}
,"limitations":{"tsa":1,"user":1}
,"put":{"throttle":1}
,"throttle":{"operations":1,"mode":1}
,"operations":{"temporary":1,"cache":1,"allowed":1}
,"temporary":{"period":1}
,"period":{"attempts":1}
,"attempts":{"automatically":1,"evict":1}
,"automatically":{"recover":1,"background":1,"continue":1}
,"recover":{"background":1,"tsa":1}
,"background":{"unable":1,"operator":1,"evictions":1}
,"unable":{"recover":1}
,"move":{"restricted":1}
,"restricted":{"mode":1}
,"mode":{"prevent":1,"allows":1,"writes":1,"restricted":1,"entered":1,"waiting":1}
,"prevent":{"out-of-memory":1}
,"out-of-memory":{"errors":1}
,"errors":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"(tmc)":1}
,"(tmc)":{"uses":1}
,"uses":{"events":1}
,"events":{"report":1,"don":1}
,"report":{"tsa":1}
,"enters":{"restricted":1,"throttle":1}
,"allows":{"execute":1}
,"execute":{"additional":1}
,"additional":{"recovery":1,"evictions":1}
,"recovery":{"measures":1,"automatic":1}
,"measures":{"monitoring":1}
,"monitoring":{"cluster":1}
,"cluster":{"events":1}
,"don":{"added":1}
,"added":{"link":1}
,"link":{"summary":1}
,"summary":{"tsa":1}
,"usage":{"reaches":1,"within":1,"usage":1,"falls":1,"crosses":1}
,"reaches":{"critical":1,"halt":1}
,"critical":{"threshold":1}
,"threshold":{"enters":1,"disk":1,"operator":1}
,"writes":{"slowed":1,"blocked":1}
,"slowed":{"tsa":1,"modifications":1}
,"evict":{"eligible":1}
,"eligible":{"cache":1}
,"cache":{"entries":1,"operations":1}
,"entries":{"order":1,"data":1}
,"order":{"bring":1}
,"bring":{"memory":1}
,"memory":{"usage":1,"evicted":1}
,"configured":{"range":1}
,"range":{"usage":1}
,"halt":{"threshold":1}
,"blocked":{"exception":1,"allowed":1}
,"exception":{"thrown":1}
,"thrown":{"operator":1}
,"operator":{"intervention":1,"event":1}
,"intervention":{"needed":1,"required":1,"clears":1}
,"needed":{"reduce":1}
,"reduce":{"memory":1,"data":1}
,"falls":{"below":1}
,"below":{"tsa":1}
,"returns":{"normal":1}
,"normal":{"operation":1}
,"operation":{"throttle":1,"soon":1}
,"entered":{"disk":1}
,"disk":{"datastorage":1}
,"datastorage":{"and\u002For":1}
,"and\u002For":{"offheap":1,"remove":1}
,"offheap":{"usage":1}
,"crosses":{"critical":1,"halt":1}
,"event":{"tps":1}
,"tps":{"seems":1}
,"seems":{"really":1}
,"really":{"low":1}
,"low":{"marking":1}
,"marking":{"throttled":1}
,"throttled":{"we\u0027re":1}
,"we\u0027re":{"restricted":1}
,"waiting":{"retrying":1}
,"retrying":{"data":1}
,"access":{"modifications":1}
,"modifications":{"in-memory":1}
,"in-memory":{"data":1}
,"allowed":{"operations":1,"gets":1,"actions":1}
,"gets":{"removes":1}
,"removes":{"config":1}
,"config":{"changes":1}
,"changes":{"allowed":1}
,"actions":{"evictions":1}
,"continue":{"automatically":1,"normal":1}
,"required":{"additional":1}
,"state":{"data":1}
,"evictable":{"data":1}
,"present":{"data":1,"memory":1}
,"evicted":{"evictor":1}
,"evictor":{"(all":1}
,"(all":{"caches":1}
,"caches":{"pinned)":1,"and\u002For":1}
,"pinned)":{"recovery":1}
,"automatic":{"tmc":1}
,"tmc":{"programmatically":1}
,"programmatically":{"clear":1}
,"clear":{"caches":1}
,"remove":{"entries":1}
,"back":{"normal":1}
,"soon":{"background":1}
,"time":{"catch":1}
,"catch":{"reduce":1}
,"user":{"intervention":1}
,"clears":{"space":1}
,"space":{"tsa":1}
}
;Search.control.loadWordPairs(pairs);
