var pairs =
{
"using":{"scripts":1,"(followed":1}
,"scripts":{"against":1}
,"against":{"server":1,"secured":1}
,"server":{"authentication":1,"correct":1,"run":1,"pass":1}
,"authentication":{"script":1}
,"script":{"targets":1,"backup-data":1,"entering":1}
,"targets":{"secured":1}
,"secured":{"terracotta":1,"server":1,"username":1}
,"terracotta":{"server":1,"script":1}
,"correct":{"login":1}
,"login":{"credentials":1}
,"credentials":{"access":1,"using":1}
,"access":{"server":1}
,"run":{"terracotta":1,"server-stat":1}
,"backup-data":{"server-stat":1}
,"server-stat":{"against":1,"script":1}
,"pass":{"credentials":1}
,"(followed":{"username)":1,"password)":1}
,"username)":{"(followed":1}
,"password)":{"flags":1}
,"flags":{"example":1}
,"example":{"server1":1}
,"server1":{"secured":1,"user1":1}
,"username":{"user1":1}
,"user1":{"password":1}
,"password":{"password":1,"run":1,"microsoft":1}
,"entering":{"following":1}
,"following":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"[prompt]${terracotta_home}\u002Fserver\u002Fbin\u002Fserver-stat.sh":1}
,"[prompt]${terracotta_home}\u002Fserver\u002Fbin\u002Fserver-stat.sh":{"server1":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"terracotta_home":1}
,"terracotta_home":{"%\u005Cserver\u005Cbin\u005Cserver-stat.bat":1}
,"%\u005Cserver\u005Cbin\u005Cserver-stat.bat":{"server1":1}
}
;Search.control.loadWordPairs(pairs);
