var pairs =
{
"terracotta":{"client":1,"server":1}
,"client":{"properties":1,"configuration":1,"settings":1,"disconnected":1}
,"properties":{"client":1,"typically":1,"ehcache.xml":1,"shown":1,"custom":1,"<<fffc-indicate":1,"change":1}
,"configuration":{"properties":1}
,"typically":{"address":1}
,"address":{"behavior":1}
,"behavior":{"size":1,"cache":1,"exception":1}
,"size":{"functionality":1,"bulk":1,"batch":1}
,"functionality":{"in-memory":1}
,"in-memory":{"data":1}
,"data":{"stores":1,"property":1,"ehcache.incoherent.putsbatch":1}
,"stores":{"others":1}
,"others":{"affect":1}
,"affect":{"certain":1,"in-memory":1,"behavior":1}
,"certain":{"types":1}
,"types":{"cache-related":1}
,"cache-related":{"bulk":1}
,"bulk":{"operations":1}
,"operations":{"server":1,"removeall":1,"default":1,"following":1,"putall":1}
,"server":{"settings":1,"array":1}
,"settings":{"override":1,"properties":1,"following":1,"affect":1,"configuring":1}
,"override":{"client":1}
,"ehcache.xml":{"except":1}
,"except":{"noted":1}
,"noted":{"general":1}
,"general":{"settings":1}
,"following":{"default":1,"properties":1}
,"default":{"settings":1,"value":1,"nonstop":1,"changed":1,"values":1}
,"property":{"default":1}
,"value":{"notes":1,"mode":1,"timeout":1}
,"notes":{"value":1,"enable":1,"ehcache.bulkops.maxkbsize":1}
,"mode":{"serialization":1,"persistence":1,"minimum":1,"maximum":1}
,"serialization":{"consistency":1}
,"consistency":{"eventual":1}
,"eventual":{"false":1}
,"false":{"orphan":1,"synchronous":1,"ttl":1,"timeout":1}
,"orphan":{"eviction":1}
,"eviction":{"true":1,"(but":1}
,"true":{"local":1}
,"local":{"key":1}
,"key":{"cache":1}
,"cache":{"false":1,"undergo":1,"following":1,"client":1,"property":1}
,"synchronous":{"writes":1}
,"writes":{"false":1}
,"ttl":{"means":1}
,"means":{"expire":1,"cache":1,"infinite":1}
,"expire":{"tti":1,"transactional":1}
,"tti":{"means":1}
,"transactional":{"mode":1}
,"persistence":{"strategy":1}
,"strategy":{"none":1}
,"none":{"maxentriesincache":1}
,"maxentriesincache":{"means":1}
,"undergo":{"capacity":1}
,"capacity":{"eviction":1}
,"(but":{"periodic":1}
,"periodic":{"resource":1}
,"resource":{"evictions":1}
,"evictions":{"allowed)":1}
,"allowed)":{"maxbyteslocalheap":1}
,"maxbyteslocalheap":{"maxbyteslocaloffheap":1}
,"maxbyteslocaloffheap":{"maxentrieslocalheap":1}
,"maxentrieslocalheap":{"means":1}
,"infinite":{"nonstop":1}
,"nonstop":{"cache":1,"timeout":1}
,"disconnected":{"cluster":1}
,"cluster":{"information":1}
,"information":{"settings":1}
,"configuring":{"nonstop":1}
,"enable":{"false":1}
,"timeout":{"behavior":1,"30000ms":1,"multiplication":1,"seconds":1,"300":1}
,"exception":{"timeout":1}
,"30000ms":{"net.sf.ehcache.nonstop":1}
,"net.sf.ehcache.nonstop":{"bulkopstimeoutmultiply":1}
,"bulkopstimeoutmultiply":{"factor":1}
,"factor":{"value":1,"affecting":1}
,"multiplication":{"factor":1}
,"affecting":{"bulk":1}
,"removeall":{"getall":1,"ehcache.getall.batchsize":1}
,"getall":{"default":1,"operation":1}
,"seconds":{"sets":1,"operations":1}
,"sets":{"timeout":1}
,"300":{"seconds":1}
,"changed":{"programmatically":1}
,"programmatically":{"cache.getterracottaconfiguration":1}
,"cache.getterracottaconfiguration":{".getnonstopconfiguration":1}
,".getnonstopconfiguration":{".setbulkopstimeoutmultiplyfactor":1}
,".setbulkopstimeoutmultiplyfactor":{"(10)":1}
,"(10)":{"bulk":1}
,"shown":{"default":1}
,"values":{"properties":1,"using":1}
,"custom":{"values":1}
,"using":{"terracotta":1}
,"array":{"properties":1}
,"<<fffc-indicate":{"properties":1}
,"change":{"reference":1}
,"reference":{"standard":1}
,"standard":{"details":1}
,"details":{"increasing":1}
,"increasing":{"batch":1}
,"batch":{"sizes":1,"size":1,"getall":1,"bulk-load":1,"puts":1}
,"sizes":{"may":1}
,"may":{"improve":1}
,"improve":{"throughput":1}
,"throughput":{"raise":1}
,"raise":{"latency":1}
,"latency":{"due":1}
,"due":{"load":1}
,"load":{"resources":1}
,"resources":{"processing":1}
,"processing":{"larger":1}
,"larger":{"blocks":1}
,"blocks":{"data":1}
,"ehcache.bulkops.maxkbsize":{"1mb":1}
,"1mb":{"batch":1}
,"putall":{"removeall":1}
,"ehcache.getall.batchsize":{"1000":1}
,"1000":{"number":1}
,"number":{"elements":1}
,"elements":{"per":1}
,"per":{"batch":1}
,"operation":{"ehcache.incoherent.putsbatch":1,"increasing":1,"takes":1}
,"ehcache.incoherent.putsbatch":{"bytesize":1,"timeinmillis":1}
,"bytesize":{"5mb":1}
,"5mb":{"bulk-loading":1}
,"bulk-loading":{"mode":1}
,"minimum":{"size":1}
,"bulk-load":{"operation":1}
,"timeinmillis":{"600":1}
,"600":{"bulk-loading":1}
,"maximum":{"time":1}
,"time":{"bulk-load":1}
,"takes":{"batch":1}
,"puts":{"flushing":1}
,"flushing":{"terracotta":1}
}
;Search.control.loadWordPairs(pairs);
