var pairs =
{
"terracotta":{"cluster":1,"pid":1,"mirror":1,"server":1,"client":1}
,"cluster":{"tests":1,"ability":1,"test":1,"failure":1,"failures":1,"begin":1}
,"tests":{"tests":1,"section":1,"succeed":1,"-verify":1,"testid":1,"system":1,"confirms":1,"testing":1,"confirm":1,"test":1}
,"section":{"run":1,"outlines":1}
,"run":{"network":1,"app":1,"~\u002Fbin\u002Fstop-tc-server.sh":1,"application":1,"stop-tc-server)":1,"second":1,"redundant":1}
,"network":{"tests":1,"section":1,"confirming":1,"connectivity":1,"consists":1,"cable":1}
,"succeed":{"test":1}
,"test":{"plan":1,"setup":1,"run":1}
,"plan":{"-active":1,"mirror":1,"-mirror":1,"testing":1,"-failover\u002Ffailback":1,"-loss":1,"-terracotta":1}
,"-active":{"system":1}
,"system":{"loss":1,"section":1}
,"loss":{"tests":1,"-kill":1,"-clean":1,"-power":1,"-reboot":1,"-pull":1,"single":1,"switch":1,"network":1,"nic":1}
,"-verify":{"mirror":1}
,"mirror":{"takeover":1,"systems":1,"server":1,"failures":1,"loss":1,"terracotta":1,"mode":1,"l1s":1}
,"takeover":{"test":1,"consists":1}
,"consists":{"following":1}
,"following":{"tests":1}
,"testid":{"test":1}
,"setup":{"steps":1}
,"steps":{"expected":1}
,"expected":{"result":1}
,"result":{"tal1":1,"tpl1":1,"tfo1":1,"tsl1":1,"tnl1":1,"tf1":1,"tcf1":1}
,"tal1":{"active":1}
,"active":{"loss":1,"l2-b":1,"takes":1,"server":1,"start-tc-server":1}
,"-kill":{"l2-a":1}
,"l2-a":{"active":1,"(active)":1,"(l2-a":1,"cleanly":1,"l2-a":1,"process":1,"traffic":1}
,"l2-b":{"mirror":1,"(mirror)":1,"restarted":1,"takes":1,"(l2-a":1,"txns":1,"interruptions":1,"user":1}
,"systems":{"running":1,"runnng":1}
,"running":{"available":1}
,"available":{"traffic":1}
,"traffic":{"run":1,"transparently":1,"timeouts":1}
,"app":{"kill":1,"run":1,"power":1,"reboot":1,"pull":1}
,"kill":{"terracotta":1,"l2-b":1,"(or":1,"l1-a":1}
,"pid":{"l2-a":1}
,"(active)":{"l2-b":1,"l2-a":1}
,"(mirror)":{"becomes":1,"data":1,"l2-a":1}
,"becomes":{"active":1}
,"takes":{"load":1,"active":1}
,"load":{"drop":1}
,"drop":{"tps":1}
,"tps":{"failover":1}
,"failover":{"tal2":1,"tal3":1,"tal4":1,"tal5":1,"test":1,"l2-a->":1,"occurs":1}
,"tal2":{"active":1}
,"-clean":{"shutdown":1,"l2-a":1}
,"shutdown":{"l2-a":1}
,"~\u002Fbin\u002Fstop-tc-server.sh":{"l2-a":1,"l2-b":1}
,"tal3":{"active":1}
,"-power":{"down":1}
,"down":{"l2-a":1,"l2-b":1,"l1s":1,"machines":1}
,"power":{"down":1,"cable":1,"down\u002Fpull":1}
,"tal4":{"active":1}
,"-reboot":{"l2-a":1}
,"reboot":{"l2-a":1,"l2-b":1}
,"tal5":{"active":1}
,"-pull":{"plug":1}
,"plug":{"l2-a":1,"l2-b":1,"switch":1}
,"pull":{"power":1,"plug":1}
,"cable":{"l2-a":1,"l2-b":1}
,"-mirror":{"system":1}
,"confirms":{"high":1}
,"high":{"availability":1}
,"availability":{"event":1}
,"event":{"loss":1}
,"single":{"system":1,"switch":1}
,"outlines":{"tests":1,"testing":1}
,"testing":{"failure":1,"terracotta":1,"fail":1,"loss":1}
,"failure":{"terracotta":1,"single":1,"network":1,"section":1,"recovery":1,"tests":1,"-l2-a":1}
,"server":{"test":1,"tpl2":1,"tpl3":1,"tpl4":1,"tpl5":1,"fail":1,"failure":1}
,"failures":{"consist":1,"test":1,"consists":1}
,"consist":{"following":1}
,"tpl1":{"mirror":1}
,"data":{"directory":1}
,"directory":{"needs":1}
,"needs":{"cleaned":1}
,"cleaned":{"l2-b":1}
,"restarted":{"re-synchs":1}
,"re-synchs":{"state":1}
,"state":{"active":1}
,"tpl2":{"mirror":1}
,"tpl3":{"mirror":1}
,"tpl4":{"mirror":1}
,"tpl5":{"mirror":1}
,"-failover\u002Ffailback":{"tests":1}
,"confirm":{"cluster":1,"successful":1}
,"ability":{"fail-over":1}
,"fail-over":{"mirror":1}
,"fail":{"back":1,"fail":1}
,"back":{"test":1,"consists":1}
,"tfo1":{"failover\u002Ffailback":1}
,"failover\u002Ffailback":{"l2-a":1}
,"application":{"kill":1,"power":1,"remove":1,"bring":1,"once":1}
,"(or":{"run":1}
,"stop-tc-server)":{"l2-a":1,"l2-b":1}
,"start-tc-server":{"l2-a":1}
,"(l2-a":{"mirror)":1,"active)":1}
,"mirror)":{"kill":1}
,"active)":{"first":1}
,"first":{"failover":1}
,"l2-a->":{"l2-b":1}
,"txns":{"continue":1,"test":1,"again":1,"process":1}
,"continue":{"l2-a":1}
,"cleanly":{"mirror":1}
,"mode":{"tc-server":1}
,"tc-server":{"run":1}
,"second":{"failover":1}
,"occurs":{"l2-b->":1,"test":1}
,"l2-b->":{"l2-a":1}
,"process":{"txns":1,"failure":1,"fails":1}
,"-loss":{"switch":1,"network":1}
,"switch":{"tests":1,"redundant":1,"consists":1,"switches":1,"traffic":1,"interruptions":1}
,"redundant":{"network":1,"configuration":1}
,"confirming":{"interrupt":1}
,"interrupt":{"service":1}
,"service":{"occurs":1}
,"tsl1":{"loss":1}
,"switches":{"redundant":1}
,"configuration":{"l2-a":1}
,"down\u002Fpull":{"plug":1}
,"transparently":{"moves":1}
,"moves":{"switch":1,"l2-b":1}
,"interruptions":{"test":1,"tnl2":1}
,"connectivity":{"section":1,"test":1}
,"tnl1":{"loss":1}
,"nic":{"wiring":1}
,"wiring":{"(active)":1,"(mirror)":1}
,"runnng":{"available":1}
,"remove":{"network":1}
,"tnl2":{"loss":1}
,"user":{"impact":1}
,"impact":{"cluster":1}
,"-terracotta":{"cluster":1}
,"successful":{"continued":1}
,"continued":{"operations":1}
,"operations":{"face":1}
,"face":{"terracotta":1}
,"tf1":{"process":1}
,"recovery":{"l2-a":1}
,"bring":{"down":1}
,"l1s":{"l2s":1,"cluster":1,"able":1,"l1-a":1}
,"l2s":{"start":1,"l1s":1}
,"start":{"l2s":1}
,"begin":{"taking":1}
,"taking":{"txns":1}
,"again":{"tf2":1}
,"tf2":{"server":1}
,"machines":{"start":1}
,"able":{"run":1}
,"once":{"servers":1}
,"servers":{"client":1}
,"client":{"failure":1,"failures":1}
,"tcf1":{"failure":1}
,"-l2-a":{"active":1}
,"l1-a":{"l1-b":1}
,"l1-b":{"systems":1,"incoming":1}
,"incoming":{"traffic":1}
,"timeouts":{"may":1}
,"may":{"occur":1}
,"occur":{"due":1}
,"due":{"txns":1}
}
;Search.control.loadWordPairs(pairs);
