var pairs =
{
"incompatible":{"configuration":1,"clustering":1}
,"configuration":{"attributes":1,"elements":1,"memorystoreevictionpolicy":1}
,"attributes":{"clustered":1,"elements":1,"replicateasynchronously":1}
,"clustered":{"cache":1,"caches":1}
,"cache":{"delete":1,"configuration":1}
,"delete":{"disable":1}
,"disable":{"edit":1}
,"edit":{"configuration":1}
,"elements":{"ehcache.xml":1,"deleted":1}
,"ehcache.xml":{"incompatible":1}
,"clustering":{"terracotta":1}
,"terracotta":{"clustered":1}
,"caches":{"<terracotta\u002F>":1}
,"<terracotta\u002F>":{"<terracotta":1}
,"<terracotta":{"clustered=\u0022":1}
,"clustered=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"element":1}
,"element":{"following":1}
,"following":{"ehcache":1}
,"ehcache":{"configuration":1}
,"deleted":{"disabled":1}
,"disabled":{"replication-related":1}
,"replication-related":{"attributes":1}
,"replicateasynchronously":{"replicateputs":1}
,"replicateputs":{"attribute":1}
,"attribute":{"memorystoreevictionpolicy":1}
,"memorystoreevictionpolicy":{"ignored":1,"may":1}
,"ignored":{"clock":1}
,"clock":{"eviction":1}
,"eviction":{"policy":1}
,"policy":{"used":1}
,"used":{"instead)":1}
,"instead)":{"however":1}
,"however":{"allowed":1}
,"allowed":{"remain":1}
,"remain":{"clustered":1}
,"may":{"cause":1}
,"cause":{"exception":1}
}
;Search.control.loadWordPairs(pairs);
