var pairs =
{
"example":{"automatic":1,"available":1,"512":1,"allocating":1}
,"automatic":{"resource":1}
,"resource":{"control":1}
,"control":{"following":1,"(arc)":1,"data":1}
,"following":{"description":1,"xml":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1,"<ehcache":1,"microsecond":1,"hardware":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"automatic":1}
,"(arc)":{"powerful":1}
,"powerful":{"capability":1}
,"capability":{"bigmemory":1}
,"bigmemory":{"max":1,"keep":1}
,"max":{"gives":1,"capable":1,"memory":1}
,"gives":{"ability":1}
,"ability":{"control":1}
,"data":{"stored":1,"off-heap":1,"heap":1,"bigmemory":1,"single":1,"<ehcache":1}
,"stored":{"heap":1}
,"heap":{"memory":1,"nanosecond":1,"sizes":1}
,"memory":{"off-heap":1,"bmm":1,"example":1,"used":1,"maximum":1,"limited":1,"fills":1,"ultra-fast":1,"physically":1,"bigmemory1":1,"bigmemory2":1}
,"off-heap":{"memory":1,"store":1}
,"bmm":{"following":1}
,"xml":{"configuration":1}
,"configuration":{"instructs":1,"keeps":1}
,"instructs":{"arc":1}
,"arc":{"allocate":1,"automatically":1,"capability":1}
,"allocate":{"maximum":1,"resources":1}
,"maximum":{"512":1,"amount":1}
,"512":{"heap":1,"data":1}
,"used":{"arc":1}
,"automatically":{"move":1}
,"move":{"data":1}
,"amount":{"off-heap":1,"physical":1}
,"limited":{"amount":1}
,"physical":{"ram":1}
,"ram":{"available":1}
,"<ehcache":{"xmlns:xsi=\u0022":1,"xmlns":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"updatecheck=\u0022":1}
,"updatecheck=\u0022":{"false":1}
,"false":{"monitoring=\u0022":1}
,"monitoring=\u0022":{"autodetect":1}
,"autodetect":{"dynamicconfig=\u0022":1}
,"dynamicconfig=\u0022":{"true":1}
,"true":{"name=\u0022":1}
,"name=\u0022":{"mymanager":1,"bigmemory1":1,"bigmemory2":1}
,"mymanager":{"maxbyteslocalheap=\u0022":1}
,"maxbyteslocalheap=\u0022":{"512m":1}
,"512m":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"<defaultcache>":1,"32g":1,"<\u002Fcache>":1,"24g":1}
,"<defaultcache>":{"<\u002Fdefaultcache>":1}
,"<\u002Fdefaultcache>":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"bigmemory1":{"<\u002Fcache>":1,"data":1,"maxbyteslocaloffheap=\u0022":1}
,"<\u002Fcache>":{"<cache":1,"<\u002Fehcache>":1}
,"bigmemory2":{"<\u002Fcache>":1,"data":1,"maxbyteslocaloffheap=\u0022":1}
,"<\u002Fehcache>":{"instructs":1}
,"keep":{"maximum":1}
,"nanosecond":{"microsecond":1}
,"microsecond":{"access":1,"speed":1}
,"access":{"example":1,"data":1}
,"fills":{"arc":1}
,"store":{"available":1}
,"speed":{"configuration":1}
,"keeps":{"heap":1}
,"sizes":{"small":1}
,"small":{"avoid":1}
,"avoid":{"garbage":1,"swapping":1}
,"garbage":{"collection":1}
,"collection":{"pauses":1}
,"pauses":{"tuning":1}
,"tuning":{"uses":1}
,"uses":{"large":1}
,"large":{"amounts":1}
,"amounts":{"in-process":1}
,"in-process":{"memory":1}
,"ultra-fast":{"access":1}
,"capable":{"addressing":1}
,"addressing":{"gigabytes":1}
,"gigabytes":{"terabytes":1}
,"terabytes":{"in-memory":1}
,"in-memory":{"data":1}
,"single":{"jvm":1}
,"jvm":{"however":1}
,"however":{"avoid":1}
,"swapping":{"care":1}
,"care":{"configure":1}
,"configure":{"bigmemory":1}
,"physically":{"available":1}
,"hardware":{"it\u0027s":1}
,"it\u0027s":{"possible":1}
,"possible":{"allocate":1}
,"resources":{"per-data":1}
,"per-data":{"basis":1}
,"basis":{"example":1}
,"allocating":{"off-heap":1}
,"xmlns":{"name=\u0022":1}
,"32g":{"maxbyteslocaldisk=\u0022":1}
,"maxbyteslocaldisk=\u0022":{"128g":1}
,"128g":{"<cache":1}
,"24g":{"<\u002Fcache>":1}
}
;Search.control.loadWordPairs(pairs);
