var pairs =
{
"off-line":{"data":1}
,"data":{"data":1,"lifecycle":1,"off-line":1,"panel":1}
,"lifecycle":{"operations":1}
,"operations":{"added":1}
,"added":{"tmc":1}
,"tmc":{"control":1}
,"control":{"visibility":1}
,"visibility":{"clustered":1}
,"clustered":{"data":1,"cache":1}
,"panel":{"provides":1}
,"provides":{"following":1}
,"following":{"capabilities":1}
,"capabilities":{"enumerate":1}
,"enumerate":{"caches":1}
,"caches":{"cache":1}
,"cache":{"managers":1,"clients":1,"administrator":1}
,"managers":{"server":1}
,"server":{"side":1,"logs":1}
,"side":{"even":1}
,"even":{"clients":1}
,"clients":{"connected":1}
,"connected":{"destroy":1,"know":1,"cache":1}
,"destroy":{"clustered":1,"feature":1}
,"know":{"clients":1}
,"administrator":{"destroy":1}
,"feature":{"feature":1,"appears":1}
,"appears":{"tmc\u002Ftms":1}
,"tmc\u002Ftms":{"logs":1}
,"logs":{"server":1}
}
;Search.control.loadWordPairs(pairs);
