var pairs =
{
"eviction":{"data":1,"entries":1,"terracotta":1,"done":1,"scheduler":1,"triggered":1,"started":1,"ends":1,"(but":1,"rate":1}
,"data":{"kept":1,"within":1,"reduces":1,"memory":1,"treated":1,"cache":1,"resides":1,"created":1,"stores":1,"data":1,"backed":1,"structures":1,"storage":1}
,"kept":{"memory":1}
,"memory":{"tsa":1,"becomes":1}
,"tsa":{"runs":1,"evict":1}
,"runs":{"evictions":1}
,"evictions":{"background":1,"allowed)":1}
,"background":{"keep":1,"periodic":1}
,"keep":{"data":1}
,"within":{"limitations":1}
,"limitations":{"eviction":1}
,"entries":{"data":1,"based":1}
,"reduces":{"amount":1}
,"amount":{"data":1,"off-heap":1,"usage":1}
,"becomes":{"full":1}
,"full":{"criteria":1}
,"criteria":{"entry":1}
,"entry":{"eligible":1}
,"eligible":{"eviction":1}
,"terracotta":{"client":1,"server":1}
,"client":{"(l1)":1}
,"(l1)":{"pinned":1}
,"pinned":{"terracotta":1}
,"server":{"held":1,"expiration":1,"eviction":1}
,"held":{"cache":1}
,"cache":{"backed":1,"-bigmemory\u0027s":1,"data":1,"maximum":1,"max":1,"unbounded":1}
,"backed":{"system":1,"sor":1}
,"system":{"record":1,"off-heap":1}
,"record":{"(sor)":1}
,"(sor)":{"store":1,"generally":1}
,"store":{"cache":1,"bigmemory":1,"tsa":1}
,"-bigmemory\u0027s":{"in-memory":1}
,"in-memory":{"data":1}
,"treated":{"store":1}
,"bigmemory":{"owns":1,"run-time":1,"stores":1,"data":1}
,"owns":{"data":1}
,"resides":{"system":1}
,"generally":{"data":1}
,"created":{"bigmemory":1,"application":1}
,"run-time":{"data":1}
,"application":{"examples":1}
,"examples":{"data":1}
,"evict":{"data":1,"cached":1,"approximately":1}
,"stores":{"primary":1,"check":1}
,"primary":{"records":1}
,"records":{"tsa":1}
,"cached":{"data":1}
,"sor":{"distinctions":1}
,"distinctions":{"data":1}
,"structures":{"handled":1}
,"handled":{"automatically":1}
,"automatically":{"eviction":1}
,"done":{"following":1}
,"following":{"evictors":1,"information":1}
,"evictors":{"work":1}
,"work":{"together":1,"continually":1}
,"together":{"background":1}
,"periodic":{"evictor":1,"tti\u002Fttl":1,"resource":1}
,"evictor":{"activated":1,"resource-based":1,"continuously":1,"work":1,"monitors":1,"run)":1}
,"activated":{"as-needed":1,"periodic":1,"cache":1}
,"as-needed":{"basis":1}
,"basis":{"removes":1}
,"removes":{"expired":1}
,"expired":{"entries":1,"elements":1}
,"based":{"tti\u002Fttl":1}
,"tti\u002Fttl":{"settings":1,"eviction":1}
,"settings":{"server":1}
,"expiration":{"rate":1}
,"rate":{"graph":1}
,"graph":{"tmc":1}
,"tmc":{"shows":1,"provides":1}
,"shows":{"activity":1,"configured":1}
,"activity":{"periodic":1,"resource":1}
,"resource-based":{"evictor":1}
,"scheduler":{"resource":1}
,"resource":{"monitoring":1,"usage":1,"critical":1,"falls":1,"eviction":1,"evictions":1,"capacity":1}
,"monitoring":{"events":1}
,"events":{"evictor":1}
,"continuously":{"polls":1}
,"polls":{"bigmemory":1}
,"check":{"current":1}
,"current":{"resource":1}
,"usage":{"approximately":1,"disk":1,"evicts":1,"graph":1,"space":1,"includes":1}
,"approximately":{"usage":1}
,"disk":{"datastorage":1}
,"datastorage":{"offheap":1,"size":1}
,"offheap":{"sizes":1,"usage":1,"size":1,"storage.)":1}
,"sizes":{"(configured":1}
,"(configured":{"tc-config.xml":1}
,"tc-config.xml":{"file)":1}
,"file)":{"starts":1}
,"starts":{"looking":1}
,"looking":{"tti\u002Fttl-expired":1}
,"tti\u002Fttl-expired":{"elements":1}
,"elements":{"evict":1,"monitored":1}
,"evicts":{"live":1}
,"live":{"expired":1}
,"monitored":{"resource":1}
,"critical":{"threshold":1}
,"threshold":{"evictor":1,"once":1}
,"continually":{"until":1}
,"until":{"monitored":1}
,"falls":{"below":1}
,"below":{"critical":1,"respective":1}
,"monitors":{"two":1}
,"two":{"off-heap":1}
,"off-heap":{"thresholds":1,"max":1,"represents":1,"used":1,"bigmemory":1,"hybrid":1}
,"thresholds":{"--used":1,"resource":1}
,"--used":{"space":1}
,"space":{"space":1,"resource":1,"above":1,"system":1}
,"triggered":{"either":1}
,"either":{"used":1}
,"used":{"space":1,"spaces":1,"represents":1}
,"above":{"threshold":1}
,"once":{"resource":1}
,"started":{"used":1}
,"spaces":{"fall":1}
,"fall":{"below":1}
,"respective":{"thresholds":1}
,"ends":{"offheap":1}
,"provides":{"following":1}
,"information":{"off-heap":1}
,"max":{"configured":1,"capacity":1}
,"configured":{"offheap":1,"datastorage":1,"maxentriesincache":1}
,"size":{"off-heap":1,"amount":1,"cache":1}
,"represents":{"usage":1,"amount":1}
,"storage":{"usage":1,"combined":1}
,"includes":{"off-heap":1}
,"hybrid":{"storage":1,"allows":1}
,"combined":{"(bigmemory":1}
,"(bigmemory":{"hybrid":1}
,"allows":{"mix":1}
,"mix":{"solid-state":1}
,"solid-state":{"drive":1}
,"drive":{"(ssd)":1}
,"(ssd)":{"dram-based":1}
,"dram-based":{"offheap":1}
,"storage.)":{"capacity-based":1}
,"capacity-based":{"evictor":1}
,"maximum":{"count":1}
,"count":{"(as":1,"attempts":1}
,"(as":{"configured":1}
,"maxentriesincache":{"plus":1,"attribute":1,"configuration":1,"gets":1}
,"plus":{"overshoot":1}
,"overshoot":{"count":1}
,"attempts":{"bring":1}
,"bring":{"size":1}
,"capacity":{"maxentriesincache":1,"evictor":1,"eviction":1,"evictors":1}
,"attribute":{"present":1}
,"present":{"ehcache":1}
,"ehcache":{"configuration":1}
,"configuration":{"(do":1,"want":1}
,"(do":{"include":1}
,"include":{"maxentriesincache":1}
,"want":{"capacity":1}
,"run)":{"maxentriesincache":1}
,"gets":{"default":1}
,"default":{"value":1}
,"value":{"means":1}
,"means":{"cache":1}
,"unbounded":{"undergo":1}
,"undergo":{"capacity":1}
,"(but":{"periodic":1}
,"allowed)":{"server":1}
}
;Search.control.loadWordPairs(pairs);
