var pairs =
{
"accessing":{"bigmemory":1}
,"bigmemory":{"data":1,"structured":1}
,"data":{"application":1,"made":1}
,"application":{"section":1,"explanation":1}
,"section":{"provides":1,"using":1}
,"provides":{"basic":1}
,"basic":{"code":1}
,"code":{"snippets":1,"samples)":1}
,"snippets":{"accessing":1}
,"explanation":{"refer":1}
,"refer":{"using":1,"api":1,"search":1}
,"using":{".net":1,"bigmemory":1,"client":1}
,".net":{"client":1}
,"client":{"api":1,"demo":1}
,"api":{"complete":1,"documentation":1}
,"complete":{"class":1}
,"class":{"library":1}
,"library":{"documentation":1}
,"documentation":{"refer":1,"\u002Fapis\u002Fcpp\u002Fapidoc-cpp.zip":1}
,"\u002Fapis\u002Fcpp\u002Fapidoc-cpp.zip":{"directory":1}
,"directory":{"kit":1}
,"kit":{"create":1,"(see":1}
,"create":{"cachemanager":1}
,"cachemanager":{"snippet":1,"configuration":1}
,"snippet":{"creates":1,"used":1}
,"creates":{"cachemanager":1}
,"configuration":{"uses":1}
,"uses":{"nirvana":1}
,"nirvana":{"shared":1}
,"shared":{"memory":1}
,"memory":{"(shm)":1}
,"(shm)":{"transport":1}
,"transport":{"provisions":1}
,"provisions":{"pool":1}
,"pool":{"connections":1}
,"connections":{"xplatform":1}
,"xplatform":{":createcachemanager":1}
,":createcachemanager":{"(terracotta":1}
,"(terracotta":{":ehcache":1}
,":ehcache":{":config":1}
,":config":{":configuration":1}
,":configuration":{"(\u0022\u002Fdev\u002Fshm":1}
,"(\u0022\u002Fdev\u002Fshm":{"10))":1}
,"10))":{"retrieve":1}
,"retrieve":{"cache":1}
,"cache":{"cachemanager":1,"snippet":1}
,"used":{".net":1}
,"demo":{"samples":1,"code":1}
,"samples":{"kit":1}
,"(see":{"demo":1}
,"samples)":{"notice":1}
,"notice":{"serializer":1,"option":1}
,"serializer":{"specified":1}
,"specified":{"cachemanager->":1}
,"cachemanager->":{"getcache":1}
,"getcache":{"(cachename":1}
,"(cachename":{"recipeprotobufserializer":1}
,"recipeprotobufserializer":{"())":1}
,"())":{"put":1}
,"put":{"entries":1,"operations":1,"(key":1}
,"entries":{"cache":1}
,"option":{"call":1}
,"call":{"configured":1}
,"configured":{"consistency":1}
,"consistency":{"type":1}
,"type":{"put":1}
,"operations":{"cache->":1}
,"cache->":{"put":1}
,"(key":{"recipestructure":1}
,"recipestructure":{"type)":1}
,"type)":{"search":1}
,"search":{"searches":1,"section":1}
,"searches":{"bigmemory":1}
,"made":{"using":1}
,"structured":{"query":1}
,"query":{"language":1}
,"language":{"(sql)":1}
,"(sql)":{"refer":1}
}
;Search.control.loadWordPairs(pairs);
