var pairs =
{
"implementing":{"element":1}
,"element":{"comparator":1,"element)":1}
,"comparator":{"transactional":1,"used":1,"specify":1,"specified":1}
,"transactional":{"caches":1}
,"caches":{"atomic":1}
,"atomic":{"methods":1,"operation":1}
,"methods":{"cache.removeelement":1,"desirable":1}
,"cache.removeelement":{"(element":1}
,"(element":{"element)":1,"old":1}
,"element)":{"cache.replace":1,"compare":1}
,"cache.replace":{"(element":1}
,"old":{"element":1}
,"compare":{"elements":1}
,"elements":{"atomic":1}
,"operation":{"complete":1}
,"complete":{"requires":1}
,"requires":{"objects":1}
,"objects":{"stored":1}
,"stored":{"cache":1}
,"cache":{"override":1,"configuration":1}
,"override":{"equals":1}
,"equals":{"hashcode":1}
,"hashcode":{"overriding":1}
,"overriding":{"methods":1}
,"desirable":{"application":1}
,"application":{"default":1}
,"default":{"comparator":1}
,"used":{"(net.sf.echache.store.defaultelementvaluecomparator)":1}
,"(net.sf.echache.store.defaultelementvaluecomparator)":{"implement":1}
,"implement":{"custom":1,"net.sf.ehcache.store.elementvaluecomparator":1}
,"custom":{"comparator":1,"comparators":1}
,"specify":{"cache":1}
,"configuration":{"<elementvaluecomparator>":1}
,"<elementvaluecomparator>":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"com.my.package.foo":1}
,"com.my.package.foo":{"maxentrieslocalheap=\u0022":1}
,"maxentrieslocalheap=\u0022":{"500":1}
,"500":{"eternal=\u0022":1}
,"eternal=\u0022":{"false":1}
,"false":{"copyonread=\u0022":1}
,"copyonread=\u0022":{"true":1}
,"true":{"copyonwrite=\u0022":1,"consistency=\u0022":1}
,"copyonwrite=\u0022":{"true":1}
,"consistency=\u0022":{"strong":1}
,"strong":{"transactionalmode=\u0022":1}
,"transactionalmode=\u0022":{"<elementvaluecomparator":1}
,"<elementvaluecomparator":{"class=\u0022":1}
,"class=\u0022":{"com.company.xyz.myelementcomparator":1}
,"com.company.xyz.myelementcomparator":{"<persistence":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"distributed":1}
,"distributed":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<terracotta":1}
,"<terracotta":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"custom":1}
,"comparators":{"implement":1}
,"net.sf.ehcache.store.elementvaluecomparator":{"comparator":1}
,"specified":{"programmatically":1}
}
;Search.control.loadWordPairs(pairs);
