var pairs =
{
"overview":{"high-availability":1}
,"high-availability":{"features":1,"deployments":1}
,"features":{"high":1,"terracotta":1}
,"high":{"availability":1}
,"availability":{"(ha)":1,"setup":1,"configurations":1}
,"(ha)":{"implementation":1}
,"implementation":{"designed":1}
,"designed":{"maintain":1}
,"maintain":{"uptime":1}
,"uptime":{"access":1,"services":1}
,"access":{"services":1}
,"services":{"even":1,"configurable":1}
,"even":{"during":1}
,"during":{"component":1}
,"component":{"overloads":1}
,"overloads":{"failures":1}
,"failures":{"terracotta":1}
,"terracotta":{"clusters":1,"server":1,"architecture":1,"healthchecker":1,"client":1,"configuration":1}
,"clusters":{"offer":1}
,"offer":{"simple":1}
,"simple":{"scalable":1}
,"scalable":{"implementations":1}
,"implementations":{"based":1}
,"based":{"terracotta":1}
,"server":{"array":1,"instances":1,"instance":1}
,"array":{"(see":1,"architecture":1,"learn":1}
,"(see":{"terracotta":1}
,"architecture":{"information)":1,"include":1}
,"information)":{"provide":1}
,"provide":{"correct":1}
,"correct":{"link":1}
,"link":{"main":1}
,"main":{"features":1}
,"include":{"instant":1}
,"instant":{"failover":1}
,"failover":{"using":1}
,"using":{"hot":1,"terracotta":1}
,"hot":{"standby":1,"standbys":1}
,"standby":{"multiple":1}
,"multiple":{"active":1}
,"active":{"servers":1}
,"servers":{"-provides":1}
,"-provides":{"continuous":1}
,"continuous":{"uptime":1}
,"configurable":{"automatic":1}
,"automatic":{"internode":1,"permanent":1,"reconnection":1,"client":1}
,"internode":{"monitoring":1}
,"monitoring":{"using":1}
,"healthchecker":{"configuring":1,"properties":1}
,"configuring":{"healthchecker":1}
,"properties":{"automatic":1}
,"permanent":{"storage":1}
,"storage":{"current":1}
,"current":{"shared":1}
,"shared":{"(in-memory)":1}
,"(in-memory)":{"data":1}
,"data":{"-available":1}
,"-available":{"server":1}
,"instances":{"(no":1,"clients":1}
,"(no":{"loss":1}
,"loss":{"application":1}
,"application":{"state)":1}
,"state)":{"automatic":1}
,"reconnection":{"temporarily":1,"refers":1}
,"temporarily":{"disconnected":1}
,"disconnected":{"server":1,"cluster":1}
,"clients":{"-restores":1,"reconnect":1,"disconnected":1}
,"-restores":{"hot":1}
,"standbys":{"without":1}
,"without":{"operator":1}
,"operator":{"intervention":1}
,"intervention":{"allows":1}
,"allows":{"lost":1}
,"lost":{"clients":1}
,"reconnect":{"client":1,"nomenclature":1}
,"client":{"reconnection":1,"reconnect":1,"(the":1}
,"refers":{"reconnecting":1}
,"reconnecting":{"clients":1,"bigmemory":1}
,"cluster":{"terracotta":1,"automatic":1}
,"learn":{"reconnecting":1}
,"bigmemory":{"max":1}
,"max":{"clients":1}
,"nomenclature":{"-this":1}
,"-this":{"document":1}
,"document":{"may":1}
,"may":{"refer":1}
,"refer":{"terracotta":1}
,"instance":{"terracotta":1}
,"(the":{"node":1}
,"node":{"running":1}
,"running":{"application)":1}
,"application)":{"shorthand":1}
,"shorthand":{"references":1}
,"references":{"used":1}
,"used":{"terracotta":1}
,"configuration":{"files":1}
,"files":{"important":1}
,"important":{"thoroughly":1}
,"thoroughly":{"test":1}
,"test":{"high":1}
,"setup":{"going":1}
,"going":{"production":1}
,"production":{"suggestions":1}
,"suggestions":{"testing":1}
,"testing":{"high":1,"high-availability":1}
,"configurations":{"provided":1}
,"provided":{"section":1}
,"section":{"testing":1}
}
;Search.control.loadWordPairs(pairs);
