var pairs =
{
"avoiding":{"commit":1}
,"commit":{"failures":1,"first":1,"example":1,"failure":1}
,"failures":{"atomic":1}
,"atomic":{"methods":1,"put":1}
,"methods":{"transaction":1,"cache.replace":1,"cannot":1}
,"transaction":{"writes":1,"fail":1}
,"writes":{"cache":1,"key":1}
,"cache":{"possible":1,"foocache":1,"configured":1}
,"possible":{"transaction":1}
,"fail":{"following":1,"mytransactionman.begin":1}
,"following":{"example":1}
,"example":{"second":1,"may":1}
,"second":{"transaction":1}
,"key":{"completes":1}
,"completes":{"commit":1}
,"first":{"commit":1}
,"may":{"fail":1}
,"mytransactionman.begin":{"cache":1,"int":1}
,"foocache":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"foo":1}
,"foo":{"foocache.put":1}
,"foocache.put":{"bar":1}
,"bar":{"mytransactionman.commit":1}
,"mytransactionman.commit":{"approach":1}
,"approach":{"prevent":1}
,"prevent":{"type":1}
,"type":{"commit":1}
,"failure":{"atomic":1}
,"put":{"methods":1,"method":1,"executed)":1}
,"cache.replace":{"mytransactionman.begin":1}
,"int":{"val":1}
,"val":{"=cache.get":1,"1))":1}
,"=cache.get":{"(key)":1}
,"(key)":{".getvalue":1}
,".getvalue":{"\u002F\u002F\u0022":1}
,"\u002F\u002F\u0022":{"cache":1}
,"configured":{"transactional":1}
,"transactional":{"element":1}
,"element":{"olde":1,"(key":1,"successfully":1,"exists":1,"(the":1}
,"olde":{"=new":1}
,"=new":{"element":1}
,"(key":{"val)":1,"val":1}
,"val)":{"\u002F\u002Ftrue":1}
,"\u002F\u002Ftrue":{"element":1}
,"successfully":{"replaced":1}
,"replaced":{"(cache.replace":1}
,"(cache.replace":{"(olde":1}
,"(olde":{"new":1}
,"new":{"element":1,"element\u0027s":1}
,"1))":{"{mytransactionman.commit":1}
,"{mytransactionman.commit":{"else":1}
,"else":{"{mytransactionman.rollback":1}
,"{mytransactionman.rollback":{"useful":1}
,"useful":{"atomic":1}
,"method":{"cache.putifabsent":1}
,"cache.putifabsent":{"(element":1}
,"(element":{"element)":1}
,"element)":{"returns":1}
,"returns":{"null":1,"existing":1}
,"null":{"success":1,"elements":1,"keys":1}
,"success":{"(no":1}
,"(no":{"previous":1}
,"previous":{"element":1}
,"exists":{"new":1}
,"element\u0027s":{"key)":1}
,"key)":{"returns":1}
,"existing":{"element":1}
,"(the":{"put":1}
,"executed)":{"atomic":1}
,"cannot":{"used":1}
,"used":{"null":1}
,"elements":{"elements":1,"null":1}
}
;Search.control.loadWordPairs(pairs);
