var pairs =
{
"performance":{"considerations":1,"comparisons":1}
,"considerations":{"managing":1}
,"managing":{"contention":1}
,"contention":{"<<this":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"either":1,"normal":1}
,"product":{"docs.>>":1}
,"docs.>>":{"two":1}
,"two":{"transactions":1}
,"transactions":{"bmm":1,"block":1,"work":1}
,"either":{"standalone":1,"first":1,"local":1}
,"standalone":{"across":1}
,"across":{"cluster":1}
,"cluster":{"attempt":1,"semantics":1}
,"attempt":{"perform":1}
,"perform":{"cache":1,"writes":1}
,"cache":{"operation":1,"adds":1}
,"operation":{"element":1,"until":1}
,"element":{"following":1,"involved":1,"marker":1,"(this":1,"itself":1}
,"following":{"rules":1,"transactions":1}
,"rules":{"apply":1}
,"apply":{"first":1}
,"first":{"transaction":1}
,"transaction":{"gets":1,"completes":1,"timeout":1,"replaced":1,"bmm":1,"thread":1}
,"gets":{"access":1}
,"access":{"following":1}
,"block":{"cache":1}
,"until":{"either":1}
,"completes":{"transaction":1}
,"timeout":{"occurs":1}
,"occurs":{"element":1}
,"involved":{"transaction":1}
,"replaced":{"new":1}
,"new":{"element":1}
,"marker":{"locked":1}
,"locked":{"along":1}
,"along":{"transaction":1}
,"normal":{"cluster":1}
,"semantics":{"used":1}
,"used":{"transactions":1,"bigmemory":1}
,"work":{"consistency=strong":1}
,"consistency=strong":{"caches":1}
,"caches":{"first":1}
,"thread":{"manages":1}
,"manages":{"atomically":1}
,"atomically":{"place":1}
,"place":{"soft":1}
,"soft":{"lock":1,"locks":1}
,"lock":{"element":1}
,"(this":{"done":1}
,"done":{"cas":1}
,"cas":{"based":1}
,"based":{"putifabsent":1}
,"putifabsent":{"replace":1}
,"replace":{"methods.)":1}
,"methods.)":{"granularity":1}
,"granularity":{"locking":1}
,"locking":{"used":1}
,"bigmemory":{"maxuses":1}
,"maxuses":{"soft":1}
,"locks":{"stored":1}
,"stored":{"element":1}
,"itself":{"key":1}
,"key":{"basis":1}
,"basis":{"performance":1}
,"comparisons":{"transactional":1}
,"transactional":{"cache":1}
,"adds":{"overhead":1}
,"overhead":{"significant":1}
,"significant":{"writes":1}
,"writes":{"nearly":1,"noticeably":1}
,"nearly":{"negligible":1}
,"negligible":{"reads":1}
,"reads":{"compared":1}
,"compared":{"transactionalmode=\u0022":1}
,"transactionalmode=\u0022":{"time":1}
,"time":{"takes":1}
,"takes":{"perform":1}
,"noticeably":{"slower":1}
,"slower":{"either":1}
,"local":{"specified":1}
,"specified":{"xa_strict":1}
,"xa_strict":{"slowest":1}
}
;Search.control.loadWordPairs(pairs);
