var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fsecurity\u002Fauth":{"element":1}
,"element":{"contains":1,"specifying":1}
,"contains":{"following":1}
,"following":{"subelements":1}
,"subelements":{"<realm>":1}
,"<realm>":{"element":1}
,"specifying":{"class":1}
,"class":{"defining":1,"specified":1,"specify":1}
,"defining":{"security":1}
,"security":{"realm":1}
,"realm":{"class":1,"configuration":1}
,"specified":{"com.tc.net.core.security.shiroinirealm":1}
,"com.tc.net.core.security.shiroinirealm":{"used":1}
,"used":{"<url>":1,"schemes":1}
,"<url>":{"uri":1}
,"uri":{"realm":1}
,"configuration":{"(.ini)":1}
,"(.ini)":{"file":1}
,"file":{"passed":1,"alternatively":1,"default":1}
,"passed":{"realm":1}
,"specify":{"authentication":1}
,"authentication":{"file":1}
,"alternatively":{"uris":1}
,"uris":{"ldap":1}
,"ldap":{"microsoft":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"directory":{"used":1}
,"schemes":{"implemented":1}
,"implemented":{"instead":1}
,"instead":{"<user>":1}
,"<user>":{"username":1}
,"username":{"represents":1}
,"represents":{"server":1}
,"server":{"authenticated":1}
,"authenticated":{"servers":1}
,"servers":{"name":1}
,"name":{"part":1}
,"part":{"credentials":1}
,"credentials":{"stored":1}
,"stored":{".ini":1}
,".ini":{"file":1}
,"default":{"value":1}
,"value":{"terracotta":1}
}
;Search.control.loadWordPairs(pairs);
