var pairs =
{
"fast":{"restart":1,"predictable":1}
,"restart":{"(frs)":1}
,"(frs)":{"disk":1}
,"disk":{"compaction":1,"persistence":1,"storage":1,"consumption":1,"space":1,"usage":1,"performance":1,"process":1,"capacity":1,"twice":1}
,"compaction":{"strategies":1,"policy":1,"strategy":1,"policy)":1,"process":1,"in-memory":1}
,"strategies":{"terracotta":1,"performance":1,"data":1}
,"terracotta":{"product":1,"supports":1,"cache":1,"periodically":1,"using":1,"data":1,"server":1,"servers":1,"usage":1,"server\u0027s":1}
,"product":{"intended":1,"heuristics":1,"operation":1}
,"intended":{"maximize":1,"used":1}
,"maximize":{"performance":1}
,"performance":{"performance-focused":1,"based":1,"expense":1,"overview":1,"paramount":1,"cost":1,"amount":1,"(i.e":1,"important)":1}
,"performance-focused":{"append-only-log":1}
,"append-only-log":{"architecture":1}
,"architecture":{"used":1}
,"used":{"frs":1,"illustrative":1,"disk":1,"disk-space":1,"read-heavy":1,"instead":1,"following":1,"used":1,"great":1,"determine":1}
,"frs":{"disk":1,"file":1,"files":1,"designed":1,"on-disk":1,"segment":1}
,"persistence":{"technology":1}
,"technology":{"terracotta":1}
,"supports":{"following":1}
,"following":{"two":1,"process":1,"observed":1,"intended":1,"behavior":1,"tc-property":1,"property":1}
,"two":{"compaction":1}
,"based":{"compaction":1,"internal":1,"data":1,"observed":1}
,"policy":{"-favors":1,"(default)":1,"default":1,"used":1,"attempt":1}
,"-favors":{"predictable":1}
,"predictable":{"performance":1,"disk":1}
,"expense":{"unpredictable":1}
,"unpredictable":{"disk":1,"performance":1}
,"storage":{"space":1,"capacity":1,"scenario":1,"access":1}
,"space":{"requirements":1,"reclaimed":1,"freed":1,"ensure":1,"successful":1,"associated":1,"put":1,"provide":1,"required":1,"(50":1,"requirement":1}
,"requirements":{"default":1,"expense":1,"deployment":1,"access":1,"recommended":1,"application":1}
,"default":{"strategy":1,"compaction":1,"frs":1,"size":1}
,"strategy":{"size":1,"provides":1,"frees":1,"intentionally":1,"wholly":1,"(size":1,"configured":1,"attempt":1}
,"size":{"based":1,"once":1,"file":1,"limit":1,"data":1,"approximately":1,"influenced":1,"default":1,"512":1,"relative":1,"<tc-properties>":1,"on-disk":1,"words":1}
,"overview":{"behavior":1}
,"behavior":{"following":1,"result":1}
,"process":{"describes":1,"regardless":1,"given":1,"repeat":1,"executed":1,"frs":1,"optional":1,"dependent":1,"formula":1}
,"describes":{"general":1}
,"general":{"expect":1}
,"expect":{"observe":1}
,"observe":{"occurring":1}
,"occurring":{"file":1}
,"file":{"system":1,"created":1,"name":1,"receives":1,"grow":1,"grows":1,"closed":1,"name\u0027s":1,"either":1,"older":1,"deleted":1,"slowly":1,"size":1}
,"system":{"configured":1}
,"configured":{"<data>":1,"data":1,"terracotta":1}
,"<data>":{"folder":1}
,"folder":{"process":1}
,"regardless":{"two":1}
,"data":{"added":1,"writes":1,"further":1,"newer":1,"older":1,"users":1,"either":1,"size":1,"volume":1,"lifetime":1,"frs":1,"use-cases":1,"volumes":1,"completely":1,"store":1,"life-cycle":1,"access":1,"use-case":1,"storage":1,"stripe":1,"distributed":1,"majority":1,"reconciliation":1,"normal":1,"sets":1,"stored":1,"compaction":1,"compacted":1,"<property":1}
,"added":{"terracotta":1}
,"cache":{"(s)":1,"strategy":1}
,"(s)":{"frs":1,"current":1}
,"created":{"file":1,"leads":1,"number":1}
,"name":{"pattern":1}
,"pattern":{"similar":1,"repeat":1}
,"similar":{"seg":1}
,"seg":{"<nnnn>":1}
,"<nnnn>":{".frs":1,"number":1,"incremented":1}
,".frs":{"<nnnn>":1}
,"number":{"file":1,"frs":1}
,"receives":{"current":1}
,"current":{"data":1,"frs":1}
,"writes":{"data":1}
,"further":{"added":1,"tuned":1}
,"grow":{"size":1,"approximately":1}
,"once":{"current":1,"cached":1,"every":1}
,"grows":{"predetermined":1,"size":1,"7.1":1,"normal":1}
,"predetermined":{"size":1}
,"closed":{"repeat":1,"file":1}
,"repeat":{"step":1,"itself":1,"1.5":1,"lifetime":1}
,"step":{"above":1}
,"above":{"file":1,"process":1,"performance":1,"options":1}
,"name\u0027s":{"<nnnn>":1}
,"incremented":{"important":1}
,"important":{"note":1,"determine":1,"performance":1}
,"note":{"above":1,"every":1}
,"given":{"frs":1}
,"limit":{"closed":1}
,"leads":{"increasing":1}
,"increasing":{"disk":1}
,"consumption":{"based":1}
,"internal":{"product":1}
,"heuristics":{"terracotta":1}
,"periodically":{"try":1}
,"try":{"copy":1}
,"copy":{"living\u002Fvalid":1}
,"living\u002Fvalid":{"data":1}
,"newer":{"frs":1}
,"files":{"once":1,"accumulates":1,"(each":1,"freed":1,"deleted":1,"normal":1,"512":1}
,"cached":{"data":1}
,"older":{"frs":1}
,"either":{"dead":1,"redundant":1}
,"dead":{"(i.e":1}
,"(i.e":{"time":1,"predictable":1}
,"time":{"live":1,"deployment":1,"terracotta":1,"default":1}
,"live":{"expired)":1}
,"expired)":{"successfully":1}
,"successfully":{"copied":1,"operate":1,"handled":1}
,"copied":{"newer":1}
,"deleted":{"entirety":1,"except":1,"(freeing":1}
,"entirety":{"associated":1}
,"associated":{"disk":1,"data":1}
,"reclaimed":{"short":1}
,"short":{"disk":1}
,"usage":{"accumulate":1,"following":1,"yield":1,"scenario":1,"cost":1,"grow":1,"peaking":1,"safe":1,"however":1,"temporarily":1,"important":1}
,"accumulate":{"amount":1}
,"amount":{"storage":1,"disk":1,"data":1}
,"freed":{"process":1,"old":1,"again":1}
,"itself":{"important":1}
,"determine":{"upper-bound":1,"minimal":1,"trigger":1}
,"upper-bound":{"used-disk":1,"pad":1}
,"used-disk":{"space":1}
,"ensure":{"environment":1,"600":1}
,"environment":{"always":1}
,"always":{"enough":1}
,"enough":{"free":1}
,"free":{"storage":1,"disk":1,"space":1,"on-disk":1}
,"capacity":{"safely":1,"terracotta":1,"during":1}
,"safely":{"function":1,"operate":1}
,"function":{"recommend":1}
,"recommend":{"determining":1,"ensuring":1}
,"determining":{"upper-bound":1}
,"pad":{"figure":1}
,"figure":{"approximately":1}
,"approximately":{"(to":1,"real":1,"512":1,"7.1":1,"recommend":1,"760":1,"190":1,"times":1}
,"(to":{"accommodate":1}
,"accommodate":{"variations":1}
,"variations":{"usage)":1}
,"usage)":{"minimum":1}
,"minimum":{"required":1,"free":1}
,"required":{"free":1,"successfully":1,"successful":1,"perform":1}
,"successful":{"product":1,"operation":1}
,"operation":{"performance":1,"test":1,"frs":1,"requires":1,"minimum":1}
,"(default)":{"noted":1}
,"noted":{"above":1}
,"provides":{"fastest":1,"fast":1}
,"fastest":{"predictable":1}
,"paramount":{"concern":1}
,"concern":{"big":1}
,"big":{"data":1}
,"users":{"strategy":1}
,"frees":{"disk":1}
,"redundant":{"removed":1}
,"removed":{"cache":1}
,"cost":{"large":1,"use-case":1}
,"large":{"(and":1}
,"(and":{"comparatively":1}
,"comparatively":{"cheap)":1}
,"cheap)":{"disk":1}
,"put":{"compaction":1}
,"intentionally":{"sacrifices":1}
,"sacrifices":{"disk":1}
,"provide":{"maximal":1}
,"maximal":{"disk":1}
,"operate":{"terracotta":1,"during":1}
,"using":{"compaction":1,"above":1}
,"wholly":{"dependent":1}
,"dependent":{"upon":1}
,"upon":{"variety":1,"data":1}
,"variety":{"use-case":1}
,"use-case":{"specific":1,"real":1,"different":1,"approximately":1,"results":1}
,"specific":{"factors":1}
,"factors":{"(such":1}
,"(such":{"data":1}
,"volume":{"configured":1}
,"lifetime":{"access":1,"requirements":1,"customer\u0027s":1}
,"access":{"patterns":1,"requirements":1}
,"patterns":{"etc.)":1,"following":1,"allows":1,"required":1}
,"etc.)":{"cannot":1}
,"cannot":{"reasonably":1}
,"reasonably":{"guessed":1}
,"guessed":{"determine":1}
,"minimal":{"frs":1}
,"deployment":{"know":1,"scenario":1,"used":1}
,"know":{"disk":1}
,"test":{"real":1}
,"real":{"use-case":1,"load":1,"world":1,"data":1}
,"load":{"monitor":1}
,"monitor":{"resulting":1}
,"resulting":{"disk":1}
,"observed":{"real":1,"peak":1,"application":1}
,"world":{"examples":1}
,"examples":{"please":1}
,"please":{"note":1}
,"every":{"use-case":1,"hours":1,"weeks":1}
,"different":{"particular":1,"results":1}
,"particular":{"usage":1}
,"yield":{"wildly":1}
,"wildly":{"different":1}
,"results":{"following":1,"frs":1}
,"illustrative":{"purposes":1}
,"purposes":{"show":1}
,"show":{"possible":1}
,"possible":{"normally":1}
,"normally":{"expected":1}
,"expected":{"disk":1}
,"scenario":{"real":1,"760":1}
,"designed":{"efficiently":1}
,"efficiently":{"manage":1}
,"manage":{"big":1}
,"use-cases":{"side":1,"successfully":1}
,"side":{"effect":1}
,"effect":{"small":1}
,"small":{"data":1}
,"volumes":{"typically":1}
,"typically":{"exhibit":1}
,"exhibit":{"high":1}
,"high":{"relative":1}
,"relative":{"disk":1,"amount":1}
,"completely":{"reloaded\u002Frefreshed":1}
,"reloaded\u002Frefreshed":{"every":1}
,"hours":{"backing":1}
,"backing":{"data":1}
,"store":{"based":1,"used":1}
,"result":{"frs":1}
,"slowly":{"grows":1}
,"512":{"file":1,"mb)":1,"each)":1,"(53687092":1}
,"accumulates":{"average":1}
,"average":{"frs":1}
,"(each":{"512":1}
,"mb)":{"configured":1}
,"life-cycle":{"coupled":1}
,"coupled":{"data":1}
,"allows":{"frs":1}
,"old":{"frs":1}
,"except":{"recent":1}
,"recent":{"frs":1}
,"normal":{"operation":1,"500":1}
,"7.1":{"(14":1,"point":1}
,"(14":{"files":1}
,"each)":{"frs":1}
,"(freeing":{"5.6":1}
,"5.6":{"gb)":1,"freed":1}
,"gb)":{"leaving":1}
,"leaving":{"1.5":1}
,"1.5":{"used":1,"grows":1}
,"point":{"5.6":1}
,"again":{"pattern":1}
,"customer\u0027s":{"deployment":1}
,"disk-space":{"observed":1}
,"peak":{"approximately":1}
,"ensuring":{"free":1}
,"(50":{"padded":1}
,"padded":{"dedicated":1}
,"dedicated":{"terracotta":1}
,"760":{"real":1,"data-set":1}
,"stripe":{"terracotta":1}
,"server":{"array)":1,"containing":1,"usage":1,"2000":1,"stores":1}
,"array)":{"use-case":1}
,"distributed":{"across":1}
,"across":{"terracotta":1}
,"servers":{"terracotta":1}
,"containing":{"approximately":1}
,"190":{"data":1,"per":1}
,"majority":{"time":1,"use-cases":1}
,"read-heavy":{"pure":1}
,"pure":{"caching":1}
,"caching":{"use-case":1}
,"peaking":{"500":1}
,"500":{"terracotta":1,"free":1,"based":1}
,"safe":{"ensure":1}
,"600":{"(500":1}
,"(500":{"free":1}
,"however":{"once":1}
,"weeks":{"write-heavy":1}
,"write-heavy":{"data-reconciliation":1}
,"data-reconciliation":{"process":1}
,"executed":{"updates":1}
,"updates":{"entire":1}
,"entire":{"760":1}
,"data-set":{"190":1}
,"per":{"server)":1}
,"server)":{"due":1}
,"due":{"access":1}
,"perform":{"data":1}
,"reconciliation":{"during":1,"operation":1}
,"during":{"bi-weekly":1,"window":1}
,"bi-weekly":{"process":1,"data":1}
,"temporarily":{"peaks":1}
,"peaks":{"during":1}
,"window":{"time":1}
,"2000":{"tb)":1}
,"tb)":{"summary":1}
,"summary":{"terracotta":1}
,"stores":{"approximately":1}
,"requires":{"least":1}
,"least":{"500":1,"2.4":1}
,"requirement":{"grows":1}
,"application":{"requirements":1,"configuration":1}
,"recommended":{"allocate":1}
,"allocate":{"least":1}
,"2.4":{"free":1}
,"optional":{"compaction":1}
,"(size":{"based":1}
,"policy)":{"constraining":1}
,"constraining":{"frs":1}
,"on-disk":{"usage":1,"size":1,"data":1,"stored":1}
,"important)":{"size":1}
,"instead":{"optional":1}
,"server\u0027s":{"tc-config.xml":1}
,"tc-config.xml":{"adding":1}
,"adding":{"new":1}
,"new":{"tc-property":1}
,"tc-property":{"tc-properties":1,"<property":1}
,"tc-properties":{"section":1}
,"section":{"follows":1}
,"follows":{"<tc-properties>":1,"included":1}
,"<tc-properties>":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"l2.frs.compactor.policy":1,"l2.frs.io.nio.segmentsize":1,"l2.frs.compactor.sizebased.threshold":1,"l2.frs.compactor.sizebased.amount":1}
,"l2.frs.compactor.policy":{"value=\u0022":1}
,"value=\u0022":{"sizebasedcompactionpolicy":1,"53687092":1,"33554432":1,"268435456":1,"0.50":1,"0.05":1}
,"sizebasedcompactionpolicy":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Ftc-properties>":1,"<!--512mb":1,"<property":1,"<!--32mb":1,"<!--256mb":1,"following":1}
,"<\u002Ftc-properties>":{"default":1,"configuration":1}
,"attempt":{"constrain":1,"free":1}
,"constrain":{"on-disk":1}
,"times":{"overall":1}
,"overall":{"data":1}
,"influenced":{"frs":1}
,"segment":{"size":1,"file":1}
,"(53687092":{"bytes)":1}
,"bytes)":{"further":1}
,"tuned":{"changing":1}
,"changing":{"value":1}
,"value":{"used":1,"parameter":1}
,"l2.frs.io.nio.segmentsize":{"value=\u0022":1}
,"53687092":{"\u0022\u002F>":1}
,"<!--512mb":{"=32":1}
,"=32":{"*1024":1}
,"*1024":{"*1024":1,"-->":1}
,"-->":{"small":1,"<\u002Ftc-properties>":1,"<property":1}
,"sets":{"sense":1}
,"sense":{"reduce":1}
,"reduce":{"frs":1}
,"stored":{"tuning":1,"data":1}
,"tuning":{"iterative":1,"parameters":1}
,"iterative":{"process":1}
,"configuration":{"example":1,"(advanced)":1}
,"example":{"segment":1,"256":1}
,"33554432":{"\u0022\u002F>":1}
,"<!--32mb":{"=32":1}
,"256":{"segment":1}
,"268435456":{"\u0022\u002F>":1}
,"<!--256mb":{"=256":1}
,"=256":{"*1024":1}
,"(advanced)":{"vast":1}
,"vast":{"majority":1}
,"handled":{"using":1}
,"options":{"follows":1}
,"included":{"completeness":1}
,"completeness":{"additional":1}
,"additional":{"tuning":1}
,"parameters":{"applicable":1}
,"applicable":{"size":1}
,"great":{"caution":1}
,"caution":{"value":1}
,"parameter":{"expressed":1}
,"expressed":{"percent":1}
,"percent":{"fraction":1}
,"fraction":{"1.0":1}
,"1.0":{"100":1}
,"100":{"%=1.0":1}
,"%=1.0":{"%=0.85":1}
,"%=0.85":{"%=0.5":1}
,"%=0.5":{"%=0.05":1}
,"%=0.05":{"following":1}
,"property":{"controls":1}
,"controls":{"trigger\u002Fstart":1,"data":1}
,"trigger\u002Fstart":{"on-disk":1}
,"formula":{"used":1}
,"trigger":{"threshold":1}
,"threshold":{"inmemory_data":1}
,"inmemory_data":{"\u002Fdisk_used":1}
,"\u002Fdisk_used":{"<!--start":1}
,"<!--start":{"compaction":1}
,"in-memory":{"size":1}
,"words":{"disk":1}
,"twice":{"-->":1}
,"l2.frs.compactor.sizebased.threshold":{"value=\u0022":1}
,"0.50":{"\u0022\u002F>":1}
,"compacted":{"time":1}
,"l2.frs.compactor.sizebased.amount":{"value=\u0022":1}
,"0.05":{"\u0022\u002F>":1}
}
;Search.control.loadWordPairs(pairs);
