var pairs =
{
"\u002Ftc:tc-config\u002Fservers":{"section":1}
,"section":{"defines":1,"omitted":1}
,"defines":{"terracotta":1,"certain":1}
,"terracotta":{"server":1,"configuration":1}
,"server":{"instances":1,"instance":1}
,"instances":{"present":1}
,"present":{"cluster":1}
,"cluster":{"entries":1,"information":1}
,"entries":{"defined":1}
,"defined":{"either":1}
,"either":{"directly":1}
,"directly":{"<servers>":1}
,"<servers>":{"element":1}
,"element":{"\u002Ftc:tc-config\u002Fservers\u002Fmirror-group":1}
,"\u002Ftc:tc-config\u002Fservers\u002Fmirror-group":{"section":1}
,"omitted":{"terracotta":1}
,"configuration":{"behaves":1}
,"behaves":{"there\u0027s":1}
,"there\u0027s":{"single":1}
,"single":{"server":1}
,"instance":{"default":1}
,"default":{"values":1}
,"values":{"section":1}
,"certain":{"global":1}
,"global":{"settings":1,"control":1}
,"settings":{"affect":1}
,"affect":{"servers":1}
,"servers":{"including":1}
,"including":{"attribute":1}
,"attribute":{"secure":1}
,"secure":{"global":1}
,"control":{"enabling":1}
,"enabling":{"true":1}
,"true":{"disabling":1}
,"disabling":{"false":1}
,"false":{"default)":1}
,"default)":{"ssl-based":1}
,"ssl-based":{"security":1}
,"security":{"entire":1,"bigmemory":1,"guide":1}
,"entire":{"cluster":1}
,"information":{"ssl-based":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
}
;Search.control.loadWordPairs(pairs);
