var pairs =
{
"distributed":{"garbage":1}
,"garbage":{"collector":1,"collection":1}
,"collector":{"(run-dgc)":1}
,"(run-dgc)":{"run-dgc":1}
,"run-dgc":{"utility":1,"force":1}
,"utility":{"causes":1,"relies":1}
,"causes":{"specified":1,"invalid":1}
,"specified":{"cluster":1,"[p]":1,"[a]":1}
,"cluster":{"perform":1}
,"perform":{"distributed":1}
,"collection":{"(dgc)":1,"sufficient":1,"managing":1}
,"(dgc)":{"run-dgc":1}
,"force":{"periodic":1}
,"periodic":{"dgc":1}
,"dgc":{"cycle":1,"effect":1,"collection":1,"initiated":1,"cycles":1}
,"cycle":{"environments":1,"server":1,"progress":1}
,"environments":{"inline":1,"utility":1}
,"inline":{"dgc":1}
,"effect":{"however":1}
,"however":{"automated":1}
,"automated":{"dgc":1}
,"sufficient":{"environments":1}
,"relies":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"server":1,"console":1}
,"server":{"(tms)":1,"tsa":1,"dgc":1}
,"(tms)":{"locate":1}
,"locate":{"execute":1}
,"execute":{"backups":1}
,"backups":{"tms":1}
,"tms":{"running":1,"omitted":1,"requires":1,"agent":1,"returns":1,"ssl":1}
,"running":{"connected":1}
,"connected":{"tsa":1}
,"tsa":{"dgc":1,"terracotta":1,"agent":1,"configured":1}
,"initiated":{"information":1}
,"information":{"connecting":1,"distributed":1}
,"connecting":{"terracotta":1}
,"console":{"user":1}
,"user":{"guide":1}
,"guide":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"bigmemory_home":1,"${bigmemory_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Frun-dgc.sh":1}
,"bigmemory_home":{"%\u005Ctools\u005Cmanagement-console\u005Cbin\u005Crun-dgc.bat":1}
,"%\u005Ctools\u005Cmanagement-console\u005Cbin\u005Crun-dgc.bat":{"<args>":1}
,"<args>":{"unix\u002Flinux":1,"<args>":1,"[l]":1}
,"unix\u002Flinux":{"[prompt]":1}
,"${bigmemory_home}\u002Ftools\u002Fmanagement-console\u002Fbin\u002Frun-dgc.sh":{"<args>":1}
,"[l]":{"<tms-host:port>":1}
,"<tms-host:port>":{"host":1}
,"host":{"port":1}
,"port":{"used":1}
,"used":{"connect":1,"default":1}
,"connect":{"tms":1}
,"omitted":{"localhost:9889":1}
,"localhost:9889":{"used":1}
,"default":{"[u]":1}
,"[u]":{"<username>":1}
,"<username>":{"tms":1}
,"requires":{"authentication":1}
,"authentication":{"username":1,"password":1}
,"username":{"specified":1}
,"[p]":{"<password>":1}
,"<password>":{"tms":1}
,"password":{"specified":1}
,"[a]":{"<agentid>":1}
,"<agentid>":{"specify":1}
,"specify":{"agent":1}
,"agent":{"tsa":1,"connection":1,"provided":1,"ids":1}
,"connection":{"name":1,"tsa":1}
,"name":{"connection":1}
,"configured":{"tms":1,"agent":1}
,"provided":{"tms":1}
,"returns":{"list":1}
,"list":{"configured":1}
,"ids":{"[k]":1}
,"[k]":{"flag":1}
,"flag":{"causes":1}
,"invalid":{"tms":1}
,"ssl":{"certificates":1}
,"certificates":{"ignored":1}
,"ignored":{"two":1}
,"two":{"dgc":1}
,"cycles":{"cannot":1}
,"cannot":{"run":1}
,"run":{"time":1,"dgc":1}
,"time":{"attempting":1}
,"attempting":{"run":1}
,"progress":{"generates":1}
,"generates":{"error":1}
,"error":{"information":1}
,"managing":{"distributed":1}
}
;Search.control.loadWordPairs(pairs);
