var pairs =
{
"fast":{"restart":1,"restartability":1}
,"restart":{"limitations":1,"restartable":1,"cache":1}
,"limitations":{"<<this":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"following":1}
,"following":{"recommendations":1}
,"recommendations":{"observed":1}
,"observed":{"configuring":1}
,"configuring":{"bigmemory":1}
,"bigmemory":{"fast":1}
,"restartability":{"size":1}
,"size":{"on-heap":1}
,"on-heap":{"off-heap":1}
,"off-heap":{"stores":1}
,"stores":{"changed":1}
,"changed":{"during":1}
,"during":{"shutdown":1}
,"shutdown":{"amount":1,"restartable":1}
,"amount":{"memory":1}
,"memory":{"allocated":1,"disk":1,"call":1}
,"allocated":{"reduced":1}
,"reduced":{"elements":1}
,"elements":{"evicted":1}
,"evicted":{"upon":1}
,"upon":{"restart":1}
,"restartable":{"caches":1,"cache":1}
,"caches":{"removed":1}
,"removed":{"cachemanager":1}
,"cachemanager":{"during":1}
,"cache":{"disposed":1,"deleted":1,"contents":1,"space":1,"dispose":1}
,"disposed":{"reference":1}
,"reference":{"cache":1}
,"deleted":{"cache":1}
,"contents":{"remain":1,"once":1}
,"remain":{"memory":1}
,"disk":{"restart":1,"safely":1,"memory":1}
,"once":{"again":1}
,"again":{"recovered":1}
,"recovered":{"memory":1}
,"safely":{"dispose":1}
,"dispose":{"unused":1}
,"unused":{"restartable":1}
,"space":{"disk":1}
,"call":{"clear":1}
,"clear":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
