var pairs =
{
"bulk-load":{"sample":1,"api":1,"operation":1}
,"sample":{"code":1}
,"code":{"following":1,"shows":1,"create":1,"intends":1,"handle":1}
,"following":{"sample":1}
,"shows":{"clustered":1}
,"clustered":{"application":1}
,"application":{"bigmemory":1,"code":1}
,"bigmemory":{"max":1}
,"max":{"bulk-load":1}
,"api":{"optimize":1,"allow":1}
,"optimize":{"bulk-load":1}
,"operation":{"import":1}
,"import":{"net.sf.ehcache.cache":1}
,"net.sf.ehcache.cache":{"public":1}
,"public":{"class":1}
,"class":{"mybulkloader":1}
,"mybulkloader":{"{cachemanager":1}
,"{cachemanager":{"cachemanager":1}
,"cachemanager":{"=new":1,"\u002F\u002Fassumes":1,"constructors":1,"already":1,"exist":1,"node":1}
,"=new":{"cachemanager":1}
,"\u002F\u002Fassumes":{"local":1}
,"local":{"ehcache.xml":1}
,"ehcache.xml":{"cache":1,"cache.setnodebulkloadenabled":1}
,"cache":{"cache":1,"=cachemanager.getehcache":1}
,"=cachemanager.getehcache":{"(\u005C\u0022":1}
,"(\u005C\u0022":{"mycache\u005C\u0022)":1}
,"mycache\u005C\u0022)":{"\u002F\u002Fmycache":1}
,"\u002F\u002Fmycache":{"defined":1,"bulk":1}
,"defined":{"ehcache.xml":1}
,"cache.setnodebulkloadenabled":{"(true)":1,"(false)":1}
,"(true)":{"\u002F\u002Fmycache":1}
,"bulk":{"mode":1}
,"mode":{"\u002F\u002Fload":1,"cache.setnodebulkloadenabled":1}
,"\u002F\u002Fload":{"data":1}
,"data":{"mycache":1,"cache.isclusterbulkloadenabled":1}
,"mycache":{"\u002F\u002Fdone":1,"back":1,"run":1,"consistent":1,"may":1}
,"\u002F\u002Fdone":{"mycache":1}
,"back":{"configured":1}
,"configured":{"consistency":1}
,"consistency":{"mode":1}
,"(false)":{"exists":1}
,"exists":{"potential":1,"jvm":1}
,"potential":{"error":1}
,"error":{"non-singleton":1,"code":1,"using":1}
,"non-singleton":{"cachemanagers":1}
,"cachemanagers":{"ehcache":1,"name":1,"violate":1}
,"ehcache":{"api":1}
,"allow":{"multiple":1}
,"multiple":{"cachemanagers":1}
,"name":{"exist":1,"jvm":1}
,"exist":{"jvm":1,"cachemanager.create":1}
,"jvm":{"cachemanager":1,"avoid":1,"named":1}
,"constructors":{"creating":1}
,"creating":{"non-singleton":1}
,"violate":{"rule":1}
,"rule":{"causing":1}
,"causing":{"error":1}
,"create":{"multiple":1,"information":1}
,"avoid":{"error":1}
,"using":{"static":1}
,"static":{"cachemanager.create":1}
,"cachemanager.create":{"methods":1}
,"methods":{"always":1,"create":1}
,"always":{"return":1}
,"return":{"named":1}
,"named":{"(or":1}
,"(or":{"default":1}
,"default":{"unnamed)":1}
,"unnamed)":{"cachemanager":1}
,"already":{"exists":1}
,"information":{"javadoc":1}
,"javadoc":{"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Ffor":1}
,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Ffor":{"cachemanager":1}
,"node":{"application":1}
,"intends":{"touch":1}
,"touch":{"mycache":1}
,"run":{"wait":1}
,"wait":{"based":1}
,"based":{"whether":1}
,"whether":{"mycache":1}
,"consistent":{"cache.isclusterbulkloadenabled":1}
,"cache.isclusterbulkloadenabled":{"())":1}
,"())":{"{\u002F\u002Fdo":1}
,"{\u002F\u002Fdo":{"work":1}
,"work":{"else":1,"waituntilbulkloadcomplete":1,"knowing":1}
,"else":{"{cache.waituntilbulkloadcomplete":1,"{\u002F\u002Fdo":1}
,"{cache.waituntilbulkloadcomplete":{"\u002F\u002Fdo":1}
,"\u002F\u002Fdo":{"work":1}
,"waituntilbulkloadcomplete":{"returns":1}
,"returns":{"waiting":1}
,"waiting":{"may":1}
,"may":{"necessary":1,"stale":1}
,"necessary":{"code":1}
,"handle":{"potentially":1}
,"potentially":{"stale":1}
,"stale":{"data":1}
,"knowing":{"data":1}
}
;Search.control.loadWordPairs(pairs);
