var pairs =
{
"configuring":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"second-level":1,"hibernate":1}
,"second-level":{"cache":1}
,"cache":{"provider":1,"region":1}
,"provider":{"configure":1}
,"configure":{"bigmemory":1}
,"hibernate":{"second-level":1,"configuration":1,"3.3":1,"singleton":1,"4.x":1,"org.hibernate.cache.ehcache.ehcacheregionfactory":1}
,"region":{"factory":1}
,"factory":{"property":1}
,"property":{"following":1}
,"following":{"hibernate":1}
,"configuration":{"hibernate":1,"specified":1}
,"specified":{"either":1}
,"either":{"hibernate.cfg.xml":1}
,"hibernate.cfg.xml":{"hibernate.properties":1,"hibernate":1}
,"hibernate.properties":{"spring":1}
,"spring":{"format":1}
,"format":{"shown":1}
,"shown":{"below":1}
,"below":{"hibernate.cfg.xml":1}
,"3.3":{"(and":1}
,"(and":{"later":1}
,"later":{"3.x":1}
,"3.x":{"versions)":1,"instead":1}
,"versions)":{"<<ffc-should":1}
,"<<ffc-should":{"say":1}
,"say":{"3.x":1}
,"instead":{"higher":1,"net.sf.ehcache.hibernate.ehcacheregionfactory":1,"net.sf.ehcache.hibernate.singletonehcacheregionfactory":1}
,"higher":{"higher":1,"include":1}
,"include":{"4.0":1}
,"4.0":{"covered":1}
,"covered":{"next":1}
,"next":{"section":1}
,"section":{"kind":1}
,"kind":{"confusing.>>":1}
,"confusing.>>":{"instance":1}
,"instance":{"creation":1}
,"creation":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"hibernate.cache.region.factory_class":1}
,"hibernate.cache.region.factory_class":{"net.sf.ehcache.hibernate.ehcacheregionfactory":1,"net.sf.ehcache.hibernate.singletonehcacheregionfactory":1}
,"net.sf.ehcache.hibernate.ehcacheregionfactory":{"<\u002Fproperty>":1,"org.hibernate.cache.ehcache.singletonehcacheregionfactory":1}
,"<\u002Fproperty>":{"force":1,"hibernate":1}
,"force":{"hibernate":1}
,"singleton":{"ehcache":1}
,"ehcache":{"cachemanager":1}
,"cachemanager":{"<property":1}
,"net.sf.ehcache.hibernate.singletonehcacheregionfactory":{"<\u002Fproperty>":1}
,"4.x":{"bigm":1}
,"bigm":{"hibernate":1}
,"org.hibernate.cache.ehcache.ehcacheregionfactory":{"instead":1}
,"org.hibernate.cache.ehcache.singletonehcacheregionfactory":{"instead":1}
}
;Search.control.loadWordPairs(pairs);
