var pairs =
{
"reading":{"keychain":1}
,"keychain":{"master":1,"password":1}
,"master":{"password":1,"keychain":1}
,"password":{"file":1,"startup":1,"cygwin":1,"implement":1,"given":1,"byte":1,"@override":1,"package":1,"terracotta":1,"similar":1}
,"file":{"instead":1,"example":1,"ioe)":1,"called":1,"specified":1}
,"instead":{"manually":1,"hardcode":1,"packaging":1}
,"manually":{"entering":1}
,"entering":{"master":1}
,"startup":{"servers":1,"server":1}
,"servers":{"clients":1,"automatically":1,"import":1}
,"clients":{"automatically":1,"read":1}
,"automatically":{"read":1,"reading":1}
,"read":{"password":1,"=fis.read":1,"keychain":1,"keychain\u0027s":1}
,"cygwin":{"(on":1}
,"(on":{"windows)":1}
,"windows)":{"supported":1}
,"supported":{"feature":1}
,"feature":{"servers":1}
,"implement":{"interface":1}
,"interface":{"com.terracotta.management.security.secretproviderbackend":1}
,"com.terracotta.management.security.secretproviderbackend":{"(located":1,"import":1,"public":1}
,"(located":{"jar":1}
,"jar":{"com.terracotta:security-keychain)":1,"containing":1,"file":1,"specify":1}
,"com.terracotta:security-keychain)":{"fetch":1}
,"fetch":{"password":1}
,"given":{"file":1}
,"example":{"package":1}
,"package":{"com.foo":1}
,"com.foo":{"import":1}
,"import":{"com.terracotta.management.security.secretproviderbackend":1,"java.io.bytearrayoutputstream":1,"java.io.fileinputstream":1,"java.io.ioexception":1,"org.terracotta.toolkit.secretprovider":1}
,"java.io.bytearrayoutputstream":{"import":1}
,"java.io.fileinputstream":{"import":1}
,"java.io.ioexception":{"public":1}
,"public":{"class":1,"void":1,"byte":1}
,"class":{"mysecretprovider":1,"using":1}
,"mysecretprovider":{"implements":1}
,"implements":{"secretproviderbackend":1}
,"secretproviderbackend":{"{private":1,"{\u002F\u002Fthis":1}
,"{private":{"byte":1}
,"byte":{"bytes":1,"array":1,"readpasswordfile":1,"[64]":1,"getsecret":1,"{\u0027p":1}
,"bytes":{"\u002F\u002Fthis":1,"create":1}
,"\u002F\u002Fthis":{"method":1}
,"method":{"reads":1,"returns":1}
,"reads":{"password":1}
,"array":{"@override":1,"containing":1}
,"@override":{"public":1}
,"void":{"fetchsecret":1}
,"fetchsecret":{"{try":1,"clients":1,"getsecret":1}
,"{try":{"{bytes":1}
,"{bytes":{"=readpasswordfile":1}
,"=readpasswordfile":{"password.pw":1}
,"password.pw":{"catch":1}
,"catch":{"(ioexception":1}
,"(ioexception":{"ioe)":1}
,"ioe)":{"{throw":1,"private":1}
,"{throw":{"new":1}
,"new":{"runtimeexception":1,"jar":1,"byte":1}
,"runtimeexception":{"cannot":1}
,"cannot":{"read":1}
,"private":{"byte":1}
,"readpasswordfile":{"(string":1}
,"(string":{"filename)":1}
,"filename)":{"throws":1}
,"throws":{"ioexception":1}
,"ioexception":{"{fileinputstream":1}
,"{fileinputstream":{"fis":1}
,"fis":{"=new":1}
,"=new":{"fileinputstream":1,"byte":1,"bytearrayoutputstream":1}
,"fileinputstream":{"(filename)":1}
,"(filename)":{"try":1}
,"try":{"{byte":1}
,"{byte":{"buffer":1}
,"buffer":{"=new":1}
,"[64]":{"bytearrayoutputstream":1}
,"bytearrayoutputstream":{"baos":1,"(true)":1}
,"baos":{"=new":1}
,"(true)":{"{int":1}
,"{int":{"read":1}
,"=fis.read":{"(buffer)":1}
,"(buffer)":{"(read":1}
,"(read":{"==-1)":1}
,"==-1)":{"{break":1}
,"{break":{"baos.write":1}
,"baos.write":{"(buffer":1}
,"(buffer":{"read)":1}
,"read)":{"return":1}
,"return":{"baos.tobytearray":1}
,"baos.tobytearray":{"finally":1}
,"finally":{"{fis.close":1}
,"{fis.close":{"\u002F\u002Fthis":1}
,"returns":{"byte":1}
,"containing":{"password":1,"implementation":1}
,"getsecret":{"{return":1,"shown":1}
,"{return":{"bytes":1,"new":1}
,"create":{"jar":1}
,"implementation":{"(mysecretprovider)":1,"<security>":1,"simpler":1,"jar":1}
,"(mysecretprovider)":{"copy":1}
,"copy":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"server\u002Flib":1,"server\u002Fbin":1}
,"server\u002Flib":{"directory":1}
,"directory":{"assuming":1}
,"assuming":{"new":1}
,"called":{"my-secret-provider.jar":1}
,"my-secret-provider.jar":{"edit":1}
,"edit":{"start-tc-server":1}
,"start-tc-server":{"script":1}
,"script":{"bigmemory":1}
,"server\u002Fbin":{"follows":1}
,"follows":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"change":1}
,"change":{"line":1}
,"line":{"-cp":1,"classpath=%":1}
,"-cp":{"\u0022${tc_install_dir}\u002Flib\u002Ftc.jar":1,"\u0022${tc_install_dir}\u002Flib\u002Ftc.jarr:${tc_install_dir}\u002Flib\u002Fmy-secret-provider.jar":1}
,"\u0022${tc_install_dir}\u002Flib\u002Ftc.jar":{"\u005Cto":1}
,"\u005Cto":{"-cp":1}
,"\u0022${tc_install_dir}\u002Flib\u002Ftc.jarr:${tc_install_dir}\u002Flib\u002Fmy-secret-provider.jar":{"\u005Cmicrosoft":1}
,"\u005Cmicrosoft":{"windows":1}
,"windows":{"change":1}
,"classpath=%":{"tc_install_dir":1}
,"tc_install_dir":{"%\u005Clib\u005Ctc.jar":1,"%\u005Clib\u005Cmy-secret-provider.jar":1}
,"%\u005Clib\u005Ctc.jar":{"classpath=%":1,"tc_install_dir":1}
,"%\u005Clib\u005Cmy-secret-provider.jar":{"ensure":1}
,"ensure":{"server\u0027s":1}
,"server\u0027s":{"configuration":1}
,"configuration":{"includes":1}
,"includes":{"<secret-provider>":1}
,"<secret-provider>":{"element":1,"com.foo.mysecretprovider":1}
,"element":{"specifying":1}
,"specifying":{"implementation":1}
,"<security>":{"<keychain>":1}
,"<keychain>":{"<url>\u002Fpath\u002Fto\u002Fmy\u002Fkeychain":1}
,"<url>\u002Fpath\u002Fto\u002Fmy\u002Fkeychain":{"<\u002Furl>":1}
,"<\u002Furl>":{"<secret-provider>":1}
,"com.foo.mysecretprovider":{"<\u002Fsecret-provider>":1}
,"<\u002Fsecret-provider>":{"<\u002Fkeychain>":1}
,"<\u002Fkeychain>":{"<\u002Fsecurity>":1}
,"<\u002Fsecurity>":{"startup":1}
,"server":{"read":1}
,"specified":{"implementation":1}
,"simpler":{"solution":1}
,"solution":{"instead":1}
,"hardcode":{"password":1}
,"{\u002F\u002Fthis":{"method":1}
,"{\u0027p":{"\u0027d\u0027}":1}
,"\u0027d\u0027}":{"@override":1}
,"terracotta":{"clients":1}
,"keychain\u0027s":{"master":1}
,"similar":{"servers":1}
,"org.terracotta.toolkit.secretprovider":{"override":1}
,"override":{"fetchsecret":1}
,"shown":{"above":1}
,"above":{"instead":1}
,"packaging":{"implementation":1}
,"specify":{"implementing":1}
,"implementing":{"class":1}
,"using":{"system":1}
,"system":{"property":1}
,"property":{"com.terracotta.express.secretprovider":1}
}
;Search.control.loadWordPairs(pairs);
