var pairs =
{
"manual":{"recovery":1}
,"recovery":{"tsa":1,"master":1,"process":1,"two":1}
,"tsa":{"failure":1}
,"failure":{"takes":1}
,"takes":{"place":1}
,"place":{"region":1}
,"region":{"master":1,"down":1,"region":1,"wan-config-1.xml":1,"ideally":1,"already":1,"becomes":1}
,"master":{"caches":1,"replica":1,"region":1,"used":1}
,"caches":{"upon":1,"cannot":1,"update":1}
,"upon":{"recovery":1}
,"cannot":{"automatically":1}
,"automatically":{"force":1}
,"force":{"resynchronization":1}
,"resynchronization":{"live":1}
,"live":{"replicas":1}
,"replicas":{"across":1}
,"across":{"wan":1}
,"wan":{"result":1}
,"result":{"data":1}
,"data":{"loss":1,"center":1}
,"loss":{"case":1}
,"case":{"entire":1}
,"entire":{"region":1}
,"down":{"(for":1,"configuration":1}
,"(for":{"example":1}
,"example":{"data":1}
,"center":{"offline)":1}
,"offline)":{"manual":1}
,"process":{"need":1}
,"need":{"designate":1}
,"designate":{"new":1}
,"new":{"master":1}
,"update":{"configuration":1}
,"configuration":{"restart":1,"region":1,"applied":1}
,"restart":{"orchestrators":1}
,"orchestrators":{"preparation":1}
,"preparation":{"disaster":1}
,"disaster":{"recovery":1}
,"two":{"orchestrator":1}
,"orchestrator":{"configurations":1,"configuration":1}
,"configurations":{"ready":1}
,"ready":{"orchestrator":1}
,"wan-config-1.xml":{"master":1}
,"replica":{"wan-config-2.xml":1,"master":1}
,"wan-config-2.xml":{"replica":1}
,"applied":{"region":1}
,"ideally":{"region":1}
,"already":{"serving":1}
,"serving":{"read-only":1}
,"read-only":{"backup":1}
,"backup":{"region":1}
,"becomes":{"master":1}
,"used":{"resynchronize":1}
,"resynchronize":{"region":1}
}
;Search.control.loadWordPairs(pairs);
