var pairs =
{
"summary":{"changes":1}
,"changes":{"3.7":1,"4.0":1,"version":1}
,"3.7":{"4.0":1,"<mirror-group>":1}
,"4.0":{"area":1,"tsa":1,"higher":1,"statistics":1}
,"area":{"change":1}
,"change":{"change":1,"3.7":1}
,"tsa":{"operation":1,"disk":1,"configuration":1,"monitoring":1,"security":1}
,"operation":{"added":1}
,"added":{"automatic":1,"recovery":1,"continuous":1,"reference":1,"references":1}
,"automatic":{"resource":1}
,"resource":{"management":1}
,"management":{"added":1,"console":1,"server":1}
,"recovery":{"near-memory-full":1}
,"near-memory-full":{"conditions":1}
,"conditions":{"added":1}
,"continuous":{"uptime":1,"availability":1}
,"uptime":{"4.0":1}
,"higher":{"tsa":1,"dso":1,"interoperability":1,"continuous":1,"improvements":1,"tc-config.xml":1,"http":1,"beginning":1}
,"disk":{"usage":1}
,"usage":{"data":1}
,"data":{"held":1,"include":1,"access":1,"ready":1,"files":1}
,"held":{"memory":1}
,"memory":{"fast":1}
,"fast":{"restartability":1}
,"restartability":{"tsa":1,"feature":1}
,"configuration":{"simplified":1,"tc-config.xml":1,"maxentriesincache":1,"blocks":1,"block":1,"elements":1,"file":1}
,"simplified":{"configuration":1}
,"tc-config.xml":{"4.0":1,"extensive":1}
,"dso":{"offheap":1}
,"offheap":{"required":1}
,"required":{"tsa":1,"terracotta":1}
,"monitoring":{"terracotta":1}
,"terracotta":{"management":1,"clients":1,"keychain":1,"servers":1}
,"console":{"(tmc)":1,"tsa":1}
,"(tmc)":{"replaces":1,"default":1}
,"replaces":{"dev":1,"maxelementsondisk":1}
,"dev":{"console":1}
,"security":{"security":1,"changes":1,"enabled":1,"guide)":1}
,"interoperability":{"bigmemory":1}
,"bigmemory":{"hadoop":1,"max":1}
,"hadoop":{"connector":1}
,"connector":{"api":1}
,"api":{"refresh":1}
,"refresh":{"ahead":1}
,"ahead":{"ehcachesizeofengine":1}
,"ehcachesizeofengine":{"tier":1}
,"tier":{"configuration":1}
,"maxentriesincache":{"replaces":1}
,"maxelementsondisk":{"pinning":1}
,"pinning":{"key-level":1,"removed":1}
,"key-level":{"pinning":1}
,"removed":{"pinningconfiguration.store":1,"statistics":1,"bigmemory":1}
,"pinningconfiguration.store":{"localheap":1}
,"localheap":{"removed":1}
,"statistics":{"statistics":1,"changes":1,"longer":1,"always":1,"sampled":1}
,"improvements":{"provide":1,"data":1}
,"provide":{"continuous":1}
,"availability":{"data":1}
,"include":{"support":1}
,"support":{"multiple":1,"available":1}
,"multiple":{"mirrors":1}
,"mirrors":{"mirror":1,"flexibility":1}
,"mirror":{"groups":1,"server":1}
,"groups":{"better":1}
,"better":{"utilization":1}
,"utilization":{"extra":1}
,"extra":{"mirrors":1}
,"flexibility":{"server":1}
,"server":{"startup":1,"start":1,"multi-stripe":1,"(tms)":1,"scripts":1}
,"startup":{"sequencing":1}
,"sequencing":{"mirror":1}
,"start":{"first":1,"kept":1}
,"first":{"during":1}
,"during":{"cluster":1}
,"cluster":{"restart":1}
,"restart":{"wait":1,"simplified":1}
,"wait":{"active":1}
,"active":{"server":1,"directory":1,"note":1}
,"multi-stripe":{"backup":1}
,"backup":{"capability":1}
,"capability":{"optimizations":1}
,"optimizations":{"bulk":1}
,"bulk":{"loading":1}
,"loading":{"performance":1}
,"performance":{"improvements":1,"call":1}
,"access":{"rejoin":1,"protocol":1}
,"rejoin":{"oracle":1}
,"oracle":{"berkeley":1}
,"berkeley":{"enabling":1}
,"enabling":{"in-memory":1}
,"in-memory":{"data":1}
,"ready":{"quickly":1}
,"quickly":{"planned":1}
,"planned":{"unplanned":1}
,"unplanned":{"restart":1}
,"extensive":{"changes":1}
,"version":{"3.7":1,"4.0":1}
,"<mirror-group>":{"element":1}
,"element":{"wrap":1,"specifies":1}
,"wrap":{"<server>":1}
,"<server>":{"configuration":1,"information":1}
,"blocks":{"eliminating":1}
,"eliminating":{"need":1}
,"need":{"repeat":1,"following":1}
,"repeat":{"setup":1}
,"setup":{"<server>":1}
,"information":{"<dso-port>":1}
,"<dso-port>":{"renamed":1}
,"renamed":{"<tsa-port>":1,"<tsa-group-port>":1}
,"<tsa-port>":{"<l2-group-port>":1}
,"<l2-group-port>":{"renamed":1}
,"<tsa-group-port>":{"<client-reconnect-window>":1}
,"<client-reconnect-window>":{"<garbage-collection>":1}
,"<garbage-collection>":{"(dgc)":1}
,"(dgc)":{"<restartable>":1}
,"<restartable>":{"settings":1}
,"settings":{"global":1}
,"global":{"servers":1}
,"servers":{"<data>":1,"terracotta":1,"(see":1}
,"<data>":{"element":1}
,"specifies":{"store":1}
,"store":{"data":1}
,"files":{"used":1,"uses":1}
,"used":{"fast":1}
,"feature":{"<clients>":1}
,"<clients>":{"section":1}
,"section":{"setting":1}
,"setting":{"<logs>":1,"authorization\u002Fauthentication":1}
,"<logs>":{"<security>":1}
,"<security>":{"new":1}
,"new":{"configuration":1}
,"block":{"setting":1}
,"authorization\u002Fauthentication":{"ssl":1}
,"ssl":{"<dso>":1}
,"<dso>":{"<system>":1}
,"<system>":{"<statistics>":1}
,"<statistics>":{"<persistence>":1}
,"<persistence>":{"<ha>":1}
,"<ha>":{"(and":1}
,"(and":{"unless":1}
,"unless":{"otherwise":1}
,"otherwise":{"noted":1}
,"noted":{"sub-elements)":1}
,"sub-elements)":{"removed":1}
,"max":{"administrator":1,"security":1,"history)":1}
,"administrator":{"guide":1}
,"guide":{"complete":1}
,"complete":{"listing":1}
,"listing":{"definitions":1}
,"definitions":{"configuration":1}
,"elements":{"don":1}
,"don":{"added":1}
,"reference":{"security":1}
,"http":{"authentication":1}
,"authentication":{"longer":1,"document":1}
,"longer":{"supported":1,"explicitly":1}
,"supported":{"security":1}
,"enabled":{"terracotta":1,"https":1,"disabled":1,"impact":1}
,"(tms)":{"level":1}
,"level":{"server":1}
,"scripts":{"need":1}
,"following":{"security":1}
,"https":{"tms":1}
,"tms":{"url":1}
,"url":{"username":1}
,"username":{"password":1}
,"password":{"keychain":1}
,"keychain":{"entries":1,"script":1,"files":1}
,"entries":{"required":1}
,"clients":{"servers":1,"(see":1}
,"default":{"keychain":1}
,"script":{"creates":1}
,"creates":{"terracotta":1}
,"uses":{"obfuscation":1}
,"obfuscation":{"scheme":1}
,"scheme":{"protect":1}
,"protect":{"passwords":1}
,"passwords":{"active":1}
,"directory":{"(ad)":1,"access":1,"authentication":1}
,"(ad)":{"lightweight":1}
,"lightweight":{"directory":1}
,"protocol":{"(ldap)":1}
,"(ldap)":{"support":1}
,"available":{"terracotta":1}
,"(see":{"using":1,"document":1}
,"using":{"ldap":1}
,"ldap":{"active":1}
,"document":{"bigmemory":1}
,"guide)":{"custom":1,"fdon":1}
,"custom":{"secretprovider":1}
,"secretprovider":{"available":1}
,"fdon":{"added":1}
,"references":{"statistics":1}
,"beginning":{"version":1}
,"explicitly":{"enabled":1}
,"disabled":{"via":1}
,"via":{"ehcache.xml":1,"tmc":1}
,"ehcache.xml":{"configuration":1}
,"file":{"core":1}
,"core":{"counters":1}
,"counters":{"statistics":1}
,"always":{"enabled":1}
,"impact":{"performance":1}
,"call":{"statistic":1}
,"statistic":{"via":1,"(latency":1,"continues":1,"kept":1}
,"tmc":{"programmatically":1}
,"programmatically":{"various":1}
,"various":{"components":1}
,"components":{"statistic":1}
,"(latency":{"avg":1}
,"avg":{"min":1}
,"min":{"max":1}
,"history)":{"start":1}
,"kept":{"long":1,"active":1}
,"long":{"statistic":1}
,"continues":{"sampled":1}
,"sampled":{"within":1}
,"within":{"defined":1}
,"defined":{"amount":1}
,"amount":{"time":1}
,"time":{"statistic":1}
,"note":{"done":1}
,"done":{"per-statistic":1}
,"per-statistic":{"basis":1}
,"basis":{"overhead":1}
,"overhead":{"vary":1}
,"vary":{"depending":1}
,"depending":{"statistics":1}
}
;Search.control.loadWordPairs(pairs);
