var pairs =
{
"group":{"clause":1,"results":1,"<attribute":1,"least":1,"examples":1,"age":1}
,"clause":{"group":1,"provides":1,"query":1,"bigmemory":1,"included":1,"special":1,"means":1,"adding":1}
,"provides":{"option":1}
,"option":{"group":1}
,"results":{"according":1,"allows":1}
,"according":{"specified":1}
,"specified":{"attributes":1,"group":1,"query":1}
,"attributes":{"adding":1,"general":1,"cannot":1,"required":1,"typically":1}
,"adding":{"group":1}
,"query":{"groups":1,"group":1,"changes":1,"grouped":1}
,"groups":{"results":1}
,"allows":{"aggregate":1}
,"aggregate":{"functions":1}
,"functions":{"performed":1}
,"performed":{"grouped":1}
,"grouped":{"attributes":1}
,"general":{"syntax":1}
,"syntax":{"group":1}
,"<attribute":{"<attribute":1,"following":1}
,"following":{"apply":1}
,"apply":{"ehcache":1,"within":1}
,"ehcache":{"search":1}
,"search":{"api\u0027s":1}
,"api\u0027s":{"group":1}
,"bigmemory":{"sql":1}
,"sql":{"attribute":1}
,"attribute":{"specified":1}
,"included":{"target":1,"result":1}
,"target":{"list":1}
,"list":{"select":1}
,"select":{"clause":1,"age":1}
,"special":{"key":1}
,"key":{"value":1}
,"value":{"attributes":1,"*cannot":1}
,"cannot":{"used":1}
,"used":{"group":1,"query":1}
,"means":{"key":1}
,"*cannot":{"used":1}
,"changes":{"semantics":1}
,"semantics":{"aggregators":1}
,"aggregators":{"passed":1}
,"passed":{"apply":1}
,"within":{"group":1}
,"least":{"aggregation":1}
,"aggregation":{"function":1}
,"function":{"specified":1}
,"required":{"included":1}
,"result":{"however":1,"processing":1}
,"however":{"grouped":1}
,"typically":{"requested":1}
,"requested":{"result":1}
,"processing":{"easier":1}
,"easier":{"group":1}
,"examples":{"select":1}
,"age":{"person":1,"select":1,"zip":1}
,"person":{"((age":1}
,"((age":{"100":1}
,"100":{"zip":1}
,"zip":{"=20144)":1,"person":1}
,"=20144)":{"time":1}
,"time":{"10)":1}
,"10)":{"group":1}
}
;Search.control.loadWordPairs(pairs);
