var pairs =
{
"terracotta":{"cluster":1,"servers":1,"server":1,"server\u0027s":1,"product":1,"server)":1}
,"cluster":{"reliability":1,"within":1,"<client-reconnect-window>":1}
,"reliability":{"using":1}
,"using":{"fast":1,"<data>":1}
,"fast":{"restart":1,"restartability":1}
,"restart":{"(frs)":1,"feature":1,"store":1,"data":1}
,"(frs)":{"persistence":1,"feature":1}
,"persistence":{"failover":1,"fast":1}
,"failover":{"scale":1}
,"scale":{"configuration":1}
,"configuration":{"above":1,"file":1}
,"above":{"may":1}
,"may":{"advantageous":1}
,"advantageous":{"development":1}
,"development":{"shared":1}
,"shared":{"in-memory":1}
,"in-memory":{"data":1,"performance":1}
,"data":{"persisted":1,"persistence":1,"kind":1,"available":1,"fast":1,"last":1,"recommended":1,"(<data>":1}
,"persisted":{"server":1}
,"server":{"configured":1,"fast":1,"array":1}
,"configured":{"local":1,"restartable":1}
,"local":{"disk":1}
,"disk":{"terracotta":1,"restart":1,"usage":1,"storage":1,"space":1,"i\u002Fo":1}
,"servers":{"achieve":1}
,"achieve":{"data":1}
,"feature":{"fast":1,"provides":1,"persists":1,"purposely":1}
,"restartability":{"fast":1,"add":1,"added":1,"requires":1}
,"provides":{"enterprise-ready":1}
,"enterprise-ready":{"crash":1}
,"crash":{"resilience":1}
,"resilience":{"keeping":1}
,"keeping":{"fully":1}
,"fully":{"consistent":1}
,"consistent":{"real-time":1}
,"real-time":{"record":1}
,"record":{"in-memory":1}
,"kind":{"shutdown":1}
,"shutdown":{"-planned":1}
,"-planned":{"unplanned":1}
,"unplanned":{"-the":1}
,"-the":{"next":1}
,"next":{"time":1}
,"time":{"application":1}
,"application":{"starts":1}
,"starts":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"data":1}
,"available":{"quickly":1,"amount":1}
,"quickly":{"accessible":1}
,"accessible":{"fast":1}
,"persists":{"real-time":1}
,"store":{"server\u0027s":1,"back":1,"search":1}
,"server\u0027s":{"local":1,"home":1,"tc-config.xml":1}
,"last":{"memory":1}
,"memory":{"(both":1,"addition":1}
,"(both":{"heap":1}
,"heap":{"off-heap":1}
,"off-heap":{"stores)":1}
,"stores)":{"automatically":1}
,"automatically":{"loads":1}
,"loads":{"fast":1}
,"back":{"memory":1}
,"addition":{"previously":1,"including":1}
,"previously":{"connected":1}
,"connected":{"clients":1}
,"clients":{"allowed":1}
,"allowed":{"rejoin":1}
,"rejoin":{"cluster":1}
,"within":{"window":1}
,"window":{"<client-reconnect-window>":1,"120":1}
,"<client-reconnect-window>":{"element":1,"120":1,"explicitly":1,"effect":1}
,"element":{"configure":1,"tc-config.xml":1,"server\u0027s":1,"size":1}
,"configure":{"terracotta":1}
,"add":{"enable":1}
,"enable":{"<restartable>":1}
,"<restartable>":{"element":1}
,"tc-config.xml":{"xml":1,"configuration":1}
,"xml":{"version=\u0022":1}
,"version=\u0022":{"1.0":1}
,"1.0":{"encoding=\u0022":1}
,"encoding=\u0022":{"utf-8":1}
,"utf-8":{"<tc:tc-config":1}
,"<tc:tc-config":{"xmlns:tc=\u0022":1}
,"xmlns:tc=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:schemalocation=\u0022":1}
,"xsi:schemalocation=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":{"<servers>":1}
,"<servers>":{"<server":1}
,"<server":{"name=\u0022":1}
,"name=\u0022":{"server1":1}
,"server1":{"<data>\u002Fopt\u002Fterracotta\u002Fserver1-data":1}
,"<data>\u002Fopt\u002Fterracotta\u002Fserver1-data":{"<\u002Fdata>":1}
,"<\u002Fdata>":{"<tsa-port>":1}
,"<tsa-port>":{"9510":1}
,"9510":{"<\u002Ftsa-port>":1}
,"<\u002Ftsa-port>":{"<jmx-port>":1}
,"<jmx-port>":{"9520":1}
,"9520":{"<\u002Fjmx-port>":1}
,"<\u002Fjmx-port>":{"<tsa-group-port>":1}
,"<tsa-group-port>":{"9530":1}
,"9530":{"<\u002Ftsa-group-port>":1}
,"<\u002Ftsa-group-port>":{"<management-port>":1}
,"<management-port>":{"9540":1}
,"9540":{"<\u002Fmanagement-port>":1}
,"<\u002Fmanagement-port>":{"<datastorage":1}
,"<datastorage":{"size=\u0022":1}
,"size=\u0022":{"<offheap":1,"\u0022\u002F>":1}
,"<offheap":{"size=\u0022":1}
,"\u0022\u002F>":{"<\u002Fdatastorage>":1,"<!--by":1}
,"<\u002Fdatastorage>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<!--fast":1}
,"<!--fast":{"restartability":1}
,"added":{"explicitly":1}
,"explicitly":{"-->":1,"specified":1,"default":1}
,"-->":{"<restartable":1,"<client-reconnect-window>":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1,"minimum":1}
,"<!--by":{"default":1}
,"default":{"window":1,"path":1,"value":1}
,"120":{"seconds":1,"<\u002Fclient-reconnect-window>":1}
,"seconds":{"-->":1}
,"<\u002Fclient-reconnect-window>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"<\u002Ftc:tc-config>":1}
,"<\u002Ftc:tc-config>":{"disk":1}
,"usage":{"fast":1}
,"requires":{"unique":1}
,"unique":{"explicitly":1}
,"specified":{"path":1}
,"path":{"default":1,"terracotta":1,"using":1}
,"home":{"directory":1}
,"directory":{"customize":1}
,"customize":{"path":1}
,"<data>":{"element":1}
,"file":{"terracotta":1}
,"array":{"configured":1}
,"restartable":{"addition":1,"mode":1}
,"including":{"searchable":1}
,"searchable":{"caches":1,"attributes":1}
,"caches":{"features":1}
,"features":{"require":1}
,"require":{"disk":1}
,"storage":{"enabled":1,"required":1}
,"enabled":{"sure":1,"understanding":1}
,"sure":{"enough":1}
,"enough":{"disk":1}
,"space":{"available":1,"requirements":1,"efficiency":1}
,"amount":{"disk":1,"in-memory":1}
,"required":{"dependent":1,"multiple":1}
,"dependent":{"case":1}
,"case":{"taking":1,"full":1}
,"taking":{"account":1}
,"account":{"aspects":1}
,"aspects":{"number":1}
,"number":{"searchable":1}
,"attributes":{"element":1}
,"size":{"read\u002Fwrite":1}
,"read\u002Fwrite":{"ratio":1}
,"ratio":{"transaction":1}
,"transaction":{"rate":1,"logs":1}
,"rate":{"reason":1}
,"reason":{"exact":1}
,"exact":{"figure":1}
,"figure":{"cannot":1}
,"cannot":{"given":1}
,"given":{"amount":1}
,"multiple":{"amount":1,"iterations":1}
,"recommended":{"determine":1,"store":1}
,"determine":{"true":1}
,"minimum":{"disk":1}
,"requirements":{"perform":1}
,"perform":{"multiple":1}
,"iterations":{"testing":1}
,"testing":{"real-world":1}
,"real-world":{"case":1}
,"full":{"highly":1}
,"highly":{"recommended":1}
,"search":{"index":1}
,"index":{"(<index>":1}
,"(<index>":{"fast":1}
,"(<data>":{"separate":1}
,"separate":{"disks":1}
,"disks":{"client":1}
,"client":{"reconnect":1}
,"reconnect":{"window":1}
,"value":{"acceptable":1}
,"acceptable":{"however":1}
,"however":{"single-server":1}
,"single-server":{"cluster":1}
,"effect":{"restartable":1}
,"mode":{"enabled":1}
,"understanding":{"frs":1}
,"frs":{"works":1,"trade-off":1,"feature":1,"transaction":1}
,"works":{"frs":1}
,"trade-off":{"space":1}
,"efficiency":{"against":1,"order":1}
,"against":{"performance":1}
,"performance":{"terracotta":1,"particular":1,"frs":1,"(latencies)":1}
,"product":{"performance":1}
,"particular":{"in-memory":1}
,"purposely":{"sacrifices":1}
,"sacrifices":{"on-disk":1}
,"on-disk":{"space":1}
,"order":{"avoid":1}
,"avoid":{"making":1}
,"making":{"process":1}
,"process":{"(the":1}
,"(the":{"terracotta":1}
,"server)":{"wait":1}
,"wait":{"complex":1}
,"complex":{"disk":1}
,"i\u002Fo":{"periods":1}
,"periods":{"extensive":1}
,"extensive":{"writing":1}
,"writing":{"(new":1}
,"(new":{"entries":1}
,"entries":{"updated":1,"deleted":1}
,"updated":{"entries":1}
,"deleted":{"entries)":1}
,"entries)":{"system":1}
,"system":{"frs":1}
,"logs":{"grow":1}
,"grow":{"extensively":1}
,"extensively":{"design":1}
,"design":{"preserves":1}
,"preserves":{"high":1}
,"high":{"predictable":1}
,"predictable":{"performance":1}
}
;Search.control.loadWordPairs(pairs);
