var pairs =
{
"concepts":{"architecture":1}
,"architecture":{"concepts":1,"bigmemory":1}
,"bigmemory":{"client":1,"in-memory":1,"cross-language":1,"clients":1,"data":1,"instance":1,"bigmemory":1,"using":1,"either":1,"deserializes":1,"terracotta":1}
,"client":{"cross-language":1,"vice":1,"(l1)":1,"connects":1,"library":1,"added":1,"application":1,"put":1,"converted":1,"different":1,"client":1,"retrieves":1,"may":1,"store":1,"platform":1,"specific":1,"(s)":1,"serialization":1}
,"cross-language":{"connector":1,"clients":1,"topology":1,"connectors":1,"support":1,"cacheserializers":1}
,"connector":{"enable":1,"bigmemory":1,"runs":1,"provides":1,"machine":1,"requires":1,"figure":1,"put":1,".net":1,"-the":1,"configured":1,"needs":1,"deployment":1,"deployments":1,"started":1}
,"enable":{"interoperability":1}
,"interoperability":{"application":1}
,"application":{"platforms":1,"read":1,"api":1,"cross-language":1,"may":1,"stored":1,"bigmemory":1,"embedded":1,"platform-neutral":1}
,"platforms":{"providing":1,"supported":1,"interoperate":1,"pnf":1}
,"providing":{"access":1}
,"access":{"bigmemory":1,"data":1,"patterns":1}
,"in-memory":{"data":1}
,"data":{"bigmemory":1,"multiple":1,"example":1,"added":1,"additional":1,"stored":1,"figure":1,"closer":1,"sets":1,"access":1,"shared":1,"want":1,"cross-language":1,"flow":1,".net":1,"retrieved":1,"either":1,"primarily":1,"java":1,"contained":1,"platform":1,"following":1}
,"clients":{"supply":1,"allow":1,"share":1,"data":1,"include":1,"processes":1}
,"supply":{"access":1}
,"multiple":{"platforms":1,"clients":1,"cross-language":1}
,"supported":{"platforms":1}
,"interoperate":{"using":1}
,"using":{"data":1,"well-defined":1,"bigmemory":1,"batch":1}
,"example":{"java":1,"figure":1,"factors":1,".net":1}
,"java":{"application":1,"virtual":1,"client":1,"format":1,"(f)":1,"cacheserializer":1}
,"read":{"data":1}
,"added":{".net":1,"application":1}
,".net":{"client":1,"clients":1,"etc.)":1}
,"vice":{"versa":1}
,"versa":{"bigmemory":1}
,"allow":{"searching":1}
,"searching":{"bigmemory":1}
,"additional":{"piece":1}
,"piece":{"infrastructure":1}
,"infrastructure":{"required":1}
,"required":{"java":1}
,"virtual":{"machine":1}
,"machine":{"(jvm)":1,"application":1}
,"(jvm)":{"hardware":1}
,"hardware":{"hosts":1,"client":1}
,"hosts":{"platform\u0027s":1}
,"platform\u0027s":{"code":1}
,"code":{"jvm":1}
,"jvm":{"host":1,"process":1,"figure":1,"standalone":1}
,"host":{"cross-language":1}
,"instance":{"cross-language":1,"opens":1}
,"runs":{"jvm":1,"terracotta":1,"dedicated":1}
,"process":{"talks":1,"runs":1,"within":1}
,"talks":{"bigmemory":1}
,"opens":{"communication":1}
,"communication":{"channel":1}
,"channel":{"processes":1}
,"processes":{"bigmemory":1,"connect":1,"connecting":1}
,"terracotta":{"client":1,"server":1}
,"(l1)":{"cluster":1}
,"cluster":{"perspective":1}
,"perspective":{"allows":1}
,"allows":{"processes":1}
,"connect":{"using":1}
,"well-defined":{"protocol":1,"primitive":1}
,"protocol":{"api":1}
,"api":{"bigmemory":1,"used":1,"cacheserializer":1,"directly":1}
,"connects":{"accesses":1,"terracotta":1}
,"accesses":{"data":1,"bigmemory":1}
,"stored":{"bigmemory":1}
,"library":{"installed":1}
,"installed":{"target":1}
,"target":{"platform":1,"application":1}
,"platform":{"appropriate":1,"-the":1,"(for":1,"platform-neutral":1,"domain":1,"deployment":1,"platform":1,"language":1}
,"appropriate":{"path":1}
,"path":{"within":1}
,"within":{"target":1,"cachemanager":1}
,"used":{"talk":1,"existing":1,"wire":1,"indexing\u002Fsearch":1}
,"talk":{"jvm":1}
,"figure":{"below":1,"cross-language":1,"bigmemory":1}
,"below":{"illustrates":1}
,"illustrates":{"topology":1,"flow":1}
,"topology":{"multiple":1,"example":1,"may":1,"include":1}
,"share":{"cross-language":1}
,"provides":{"access":1}
,"connectors":{"hosting":1,"bigmemory":1}
,"hosting":{"connector":1}
,"may":{"advantage":1,"good":1,"java":1}
,"advantage":{"keeping":1}
,"keeping":{"data":1,"discrete":1}
,"closer":{"reducing":1}
,"reducing":{"latency":1}
,"latency":{"connector":1,"server":1}
,"requires":{"cachemanager":1}
,"cachemanager":{"topology":1,"want":1,"need":1,"used":1}
,"good":{"approach":1}
,"approach":{"keeping":1}
,"discrete":{"data":1}
,"sets":{"available":1}
,"available":{"different":1,"client":1}
,"different":{"applications":1,"client":1}
,"applications":{"figure":1,"amount":1}
,"factors":{"consider":1}
,"consider":{"designing":1}
,"designing":{"topology":1}
,"include":{"data":1,"java":1}
,"patterns":{"data":1}
,"shared":{"among":1,"across":1}
,"among":{"applications":1}
,"amount":{"memory":1,"data":1}
,"memory":{"amount":1,"figure":1}
,"want":{"keep":1,"cachemanager":1}
,"keep":{"memory":1}
,"flow":{"data":1}
,"put":{"bigmemory":1}
,"converted":{"platform-neutral":1}
,"platform-neutral":{"format":1}
,"format":{"(pnf)":1,"ehcache":1,"send":1,"serialization":1,"used":1,"perform":1,"mixed":1}
,"(pnf)":{"transported":1,"ehcache":1,"thrift-based":1}
,"transported":{"cross-language":1}
,"either":{"directly":1,"ways":1}
,"directly":{"serialization":1,"java":1}
,"serialization":{"depending":1,"platform-neutral":1}
,"depending":{"upon":1}
,"upon":{"case":1}
,"case":{"data":1,"cross-language":1}
,"retrieved":{"bigmemory":1}
,"retrieves":{"serialized":1}
,"serialized":{"object":1,"cross-language":1}
,"object":{"bigmemory":1,"available":1,"transform":1}
,"deserializes":{"making":1}
,"making":{"domain":1,"simple":1}
,"domain":{"object":1}
,"store":{"access":1}
,"ways":{"bigmemory":1}
,"primarily":{"platform-neutral":1,"java":1}
,"ehcache":{"api":1,"application":1,"map":1}
,"cacheserializer":{"lazily":1,"components":1}
,"lazily":{"serializes\u002Fdeserializes":1}
,"serializes\u002Fdeserializes":{"data":1}
,"(f)":{"case":1}
,"components":{"cross-language":1}
,"-the":{"connector":1,"bigmemory":1}
,"configured":{"cross-lang-config.xml":1,"making":1}
,"cross-lang-config.xml":{"file":1}
,"file":{"accesses":1,"connector":1,"started":1}
,"contained":{"caches":1}
,"caches":{"defined":1}
,"defined":{"ehcache.xml":1}
,"ehcache.xml":{"file":1}
,"needs":{"cachemanager":1,"serialized":1}
,"need":{"connectors":1,"written":1}
,"specific":{"platform":1}
,"(for":{"example":1}
,"etc.)":{"convert":1,"keys":1}
,"convert":{"data":1}
,"send":{"connector":1}
,"deployment":{"bigmemory":1,"cacheserializers":1}
,"support":{"provided":1}
,"provided":{"client-server":1,"kit":1}
,"client-server":{"model":1}
,"model":{"server":1}
,"server":{"potentially":1,"array":1,"typically":1,"run":1,"two":1,"process":1}
,"potentially":{"connects":1}
,"array":{"(tsa)":1,"pnf":1,"opaque":1}
,"(tsa)":{"standalone":1}
,"standalone":{"caching":1,"server":1,"connector":1}
,"caching":{"server":1}
,"typically":{"order":1}
,"order":{"minimize":1}
,"minimize":{"latency":1}
,"run":{"hardware":1}
,"(s)":{"clients":1}
,"connecting":{"server":1}
,"two":{"main":1,"parts":1}
,"main":{"connector":1}
,"deployments":{"standalone":1}
,"dedicated":{"jvm":1}
,"started":{"stopped":1}
,"stopped":{"using":1,"via":1}
,"batch":{"shell":1}
,"shell":{"scripts":1}
,"scripts":{"provided":1}
,"kit":{"embedded":1}
,"embedded":{"server":1,"connector":1}
,"existing":{"ehcache":1}
,"simple":{"changes":1}
,"changes":{"ehcache.xml":1}
,"via":{"application":1}
,"thrift-based":{"opaque":1}
,"opaque":{"binary":1,"ehcache":1}
,"binary":{"format":1,"byte":1}
,"wire":{"transport":1}
,"transport":{"platforms":1}
,"pnf":{"objects":1,"data":1,"back":1}
,"objects":{"trivially":1}
,"trivially":{"stored":1}
,"following":{"characteristics":1}
,"characteristics":{"consists":1}
,"consists":{"well-defined":1}
,"primitive":{"types":1,"values":1}
,"types":{"(string":1}
,"(string":{"integer":1}
,"integer":{"float":1}
,"float":{"date":1}
,"date":{"byte":1}
,"byte":{"etc.)":1,"array":1}
,"keys":{"mapped":1}
,"mapped":{"type":1}
,"type":{"primitive":1}
,"values":{"comprised":1}
,"comprised":{"two":1}
,"parts":{"binary":1}
,"map":{"string":1}
,"string":{"<primitive":1}
,"<primitive":{"type>":1}
,"type>":{"used":1}
,"indexing\u002Fsearch":{"data":1}
,"across":{"languages":1}
,"languages":{"needs":1}
,"cacheserializers":{"implementations":1,"need":1}
,"implementations":{"platform":1}
,"transform":{"platform-neutral":1}
,"perform":{"operation":1}
,"operation":{"reverse":1}
,"reverse":{"pnf":1}
,"back":{"original":1}
,"original":{"format":1}
,"mixed":{"platform":1}
,"written":{"platform":1}
,"language":{"information":1}
,"information":{"client":1}
}
;Search.control.loadWordPairs(pairs);
