var pairs =
{
"run-time":{"monitoring":1,"statuses":1,"component":1,"status":1}
,"monitoring":{"statuses":1,"runtimestatus":1,"state":1}
,"statuses":{"terracotta":1}
,"terracotta":{"following":1,"run-time":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"run-time":1}
,"component":{"return":1}
,"return":{"response":1}
,"response":{"sagcc":1}
,"sagcc":{"monitoring":1}
,"runtimestatus":{"sagcc":1}
,"state":{"commands":1}
,"commands":{"along":1}
,"along":{"meaning":1}
,"meaning":{"run-time":1,"stopped":1}
,"status":{"run-time":1,"meaning":1}
,"stopped":{"server":1}
,"server":{"running":1,"find":1}
,"running":{"online_master":1,"master":1,"slave":1,"crashed":1,"responding":1}
,"online_master":{"server":1}
,"master":{"stripe":1}
,"stripe":{"online_slave":1,"failed":1}
,"online_slave":{"server":1}
,"slave":{"(mirror)":1}
,"(mirror)":{"stripe":1}
,"failed":{"server":1}
,"crashed":{"possible":1}
,"possible":{"reason":1}
,"reason":{"failure":1}
,"failure":{"server":1}
,"find":{"correct":1}
,"correct":{"license":1}
,"license":{"unresponsive":1}
,"unresponsive":{"server":1}
,"responding":{"specified":1}
,"specified":{"ports":1}
,"ports":{"possible":1}
}
;Search.control.loadWordPairs(pairs);
