var pairs =
{
"automatic":{"resource":1}
,"resource":{"management":1}
,"management":{"terracotta":1,"involves":1}
,"terracotta":{"server":1}
,"server":{"array":1}
,"array":{"resource":1}
,"involves":{"self-monitoring":1}
,"self-monitoring":{"polling":1}
,"polling":{"determine":1}
,"determine":{"real-time":1}
,"real-time":{"size":1}
,"size":{"data":1,"-the":1}
,"data":{"assess":1,"managed":1}
,"assess":{"amount":1}
,"amount":{"memory":1,"bigmemory":1}
,"memory":{"remaining":1}
,"remaining":{"according":1}
,"according":{"user-configured":1}
,"user-configured":{"limitations":1}
,"limitations":{"in-memory":1}
,"in-memory":{"data":1}
,"managed":{"three":1,"tsa":1}
,"three":{"directions":1}
,"directions":{"time":1}
,"time":{"-tti\u002Fttl":1}
,"-tti\u002Fttl":{"settings":1}
,"settings":{"configured":1}
,"configured":{"expire":1,"using":1}
,"expire":{"entries":1}
,"entries":{"evicted":1,"eternal":1,"caches":1,"per":1}
,"evicted":{"new":1,"size":1}
,"new":{"tsa":1}
,"tsa":{"eviction":1,"configured":1}
,"eviction":{"implementation":1}
,"implementation":{"configure":1}
,"configure":{"caches":1}
,"caches":{"entries":1,"evicted":1}
,"eternal":{"pin":1}
,"pin":{"entries":1}
,"-the":{"total":1}
,"total":{"amount":1,"number":1}
,"bigmemory":{"managed":1}
,"using":{"datastorage":1,"maxentriesincache":1}
,"datastorage":{"offheap":1}
,"offheap":{"elements":1}
,"elements":{"tc-config.xml":1}
,"tc-config.xml":{"file":1}
,"file":{"count":1}
,"count":{"-the":1}
,"number":{"entries":1}
,"per":{"cache":1}
,"cache":{"configured":1}
,"maxentriesincache":{"attribute":1}
,"attribute":{"ehcache.xml":1}
,"ehcache.xml":{"file":1}
}
;Search.control.loadWordPairs(pairs);
