var pairs =
{
"hello":{"world":1}
,"world":{"first":1,"\u002F\u002Fput":1,"next":1}
,"first":{"step":1}
,"step":{"using":1,"next":1,"basic":1}
,"using":{"bigmemory":1}
,"bigmemory":{"instances":1,"uses":1,"max":1,"data":1,"print":1}
,"instances":{"ehcache":1}
,"ehcache":{"bigmemory":1,"main":1}
,"uses":{"ehcache":1}
,"main":{"programming":1,"(final":1}
,"programming":{"interface":1}
,"interface":{"download":1}
,"download":{"unpack":1,"kit":1}
,"unpack":{"bigmemory":1}
,"max":{"download":1}
,"kit":{"add":1,"classpath":1}
,"add":{"license":1,"following":1}
,"license":{"key":1,"startup":1}
,"key":{"(terracotta-license.key)":1,"map":1,"greeting":1}
,"(terracotta-license.key)":{"classpath":1}
,"classpath":{"add":1,"apis\u002Fehcache\u002Flib\u002Fehcache-ee-<version>":1,"<ehcache":1}
,"following":{"jars":1}
,"jars":{"bigmemory":1}
,"apis\u002Fehcache\u002Flib\u002Fehcache-ee-<version>":{".jar":1}
,".jar":{"apis\u002Fehcache\u002Flib\u002Fslf4j-api-<version>":1,"apis\u002Fehcache\u002Flib\u002Fslf4j-jdk-<version>":1,"-only":1}
,"apis\u002Fehcache\u002Flib\u002Fslf4j-api-<version>":{".jar":1}
,"apis\u002Fehcache\u002Flib\u002Fslf4j-jdk-<version>":{".jar":1}
,"-only":{"versions":1}
,"versions":{"include":1}
,"include":{"jar":1}
,"jar":{"create":1}
,"create":{"configuration":1,"basic":1,"helloworld.java":1,"compile":1,"read":1}
,"configuration":{"file":1}
,"file":{"create":1,"name":1}
,"basic":{"configuration":1,"create":1}
,"name":{"ehcache.xml":1}
,"ehcache.xml":{"put":1}
,"put":{"classpath":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"helloworldconfig":1,"hello-world":1}
,"helloworldconfig":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"hello-world":{"maxbyteslocalheap=\u0022":1,"maximum":1,"final":1,"\u002F\u002Fcreate":1}
,"maxbyteslocalheap=\u0022":{"64m":1}
,"64m":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"tells":1}
,"tells":{"bigmemory":1}
,"data":{"store":1,"final":1,"element":1}
,"store":{"called":1,"datastore.put":1}
,"called":{"hello-world":1,"helloworld":1}
,"maximum":{"megabytes":1}
,"megabytes":{"heap":1}
,"heap":{"local":1}
,"local":{"java":1}
,"java":{"virtual":1,"class":1}
,"virtual":{"machine":1}
,"machine":{"create":1}
,"helloworld.java":{"create":1}
,"compile":{"java":1}
,"class":{"called":1,"helloworld":1}
,"helloworld":{"import":1,"{public":1}
,"import":{"net.sf.ehcache.cache":1,"net.sf.ehcache.cachemanager":1,"net.sf.ehcache.element":1}
,"net.sf.ehcache.cache":{"import":1}
,"net.sf.ehcache.cachemanager":{"import":1}
,"net.sf.ehcache.element":{"public":1}
,"public":{"class":1}
,"{public":{"static":1}
,"static":{"void":1}
,"void":{"main":1}
,"(final":{"string":1}
,"string":{"args)":1,"key":1,"hello":1}
,"args)":{"{\u002F\u002Fcreate":1}
,"{\u002F\u002Fcreate":{"cache":1}
,"cache":{"manager":1,"datastore":1}
,"manager":{"final":1}
,"final":{"cachemanager":1,"cache":1,"string":1,"element":1}
,"cachemanager":{"cachemanager":1,"=new":1,"\u002F\u002Fcreate":1}
,"=new":{"cachemanager":1,"element":1}
,"\u002F\u002Fcreate":{"data":1,"key":1}
,"datastore":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"hello-world":1}
,"map":{"data":1}
,"greeting":{"\u002F\u002Fcreate":1}
,"element":{"final":1,"putgreeting":1,"(key":1,"data":1,"getgreeting":1}
,"putgreeting":{"=new":1}
,"(key":{"hello":1}
,"\u002F\u002Fput":{"element":1}
,"datastore.put":{"(putgreeting)":1}
,"(putgreeting)":{"\u002F\u002Fretrieve":1}
,"\u002F\u002Fretrieve":{"data":1}
,"getgreeting":{"=datastore.get":1}
,"=datastore.get":{"(key)":1}
,"(key)":{"\u002F\u002Fprint":1}
,"\u002F\u002Fprint":{"value":1}
,"value":{"system.out.println":1}
,"system.out.println":{"(getgreeting.getobjectvalue":1}
,"(getgreeting.getobjectvalue":{"())":1}
,"())":{"execute":1}
,"execute":{"run":1}
,"run":{"program":1}
,"program":{"terminal":1}
,"terminal":{"bigmemory":1}
,"print":{"license":1}
,"startup":{"info":1}
,"info":{"string":1}
,"next":{"step":1}
,"read":{"update":1}
,"update":{"delete":1}
,"delete":{"(crud)":1}
}
;Search.control.loadWordPairs(pairs);
