var pairs =
{
"manage":{"sessions":1}
,"sessions":{"cluster":1,"mask":1,"cleared":1}
,"cluster":{"sure":1,"local":1,"without":1,"sticky":1}
,"sure":{"configured":1}
,"configured":{"time":1}
,"time":{"zone":1,"consistent":1}
,"zone":{"system":1}
,"system":{"time":1}
,"consistent":{"application":1}
,"application":{"servers":1}
,"servers":{"different":1}
,"different":{"session":1,"nodes":1}
,"session":{"may":1,"implementations":1,"object":1,"it\u0027s":1,"session":1,"=request.getsession":1,"becomes":1,"accessed":1,"=((httpservletrequest)":1}
,"may":{"appear":1,"substantially":1}
,"appear":{"expired":1}
,"expired":{"accessed":1}
,"accessed":{"different":1,"node":1}
,"nodes":{"-dcom.tc.session.debug.sessions=true":1}
,"-dcom.tc.session.debug.sessions=true":{"-dcom.tc.session.debug.invalidate=true":1}
,"-dcom.tc.session.debug.invalidate=true":{"generate":1}
,"generate":{"debugging":1}
,"debugging":{"information":1}
,"information":{"client":1}
,"client":{"logs":1,"node":1}
,"logs":{"clustered":1}
,"clustered":{"session":1}
,"implementations":{"(including":1}
,"(including":{"terracotta":1}
,"terracotta":{"sessions)":1,"property":1,"3.6.0":1}
,"sessions)":{"require":1}
,"require":{"mutated":1}
,"mutated":{"session":1,"call":1}
,"object":{"put":1,"value":1}
,"put":{"back":1}
,"back":{"session":1}
,"it\u0027s":{"mutated":1}
,"call":{"missing":1,"clear":1,"session":1}
,"missing":{"change":1}
,"change":{"isn\u0027t":1}
,"isn\u0027t":{"known":1}
,"known":{"cluster":1}
,"local":{"node":1}
,"node":{"example":1,"state":1,"add":1}
,"example":{"session":1}
,"=request.getsession":{"map":1}
,"map":{"=session.getattribute":1}
,"=session.getattribute":{"foo":1,"(name)":1}
,"foo":{"m.clear":1,"\u002F\u002Fwithout":1}
,"m.clear":{"session.setattribute":1}
,"session.setattribute":{"foo":1,"(name":1}
,"\u002F\u002Fwithout":{"call":1}
,"clear":{"effective":1}
,"effective":{"across":1}
,"across":{"cluster":1}
,"without":{"setattribute":1}
,"setattribute":{"call":1,"end":1}
,"becomes":{"inconsistent":1}
,"inconsistent":{"across":1}
,"sticky":{"sessions":1}
,"mask":{"issue":1}
,"issue":{"soon":1}
,"soon":{"session":1}
,"state":{"match":1}
,"match":{"expected":1}
,"expected":{"view":1}
,"view":{"inconsistency":1}
,"inconsistency":{"single":1}
,"single":{"client":1}
,"add":{"terracotta":1}
,"property":{"-dcom.tc.session.clear.on.access=true":1}
,"-dcom.tc.session.clear.on.access=true":{"force":1}
,"force":{"locally":1}
,"locally":{"cached":1}
,"cached":{"sessions":1}
,"cleared":{"every":1}
,"every":{"access":1,"request":1}
,"access":{"third-party":1}
,"third-party":{"code":1}
,"code":{"cannot":1}
,"cannot":{"refactored":1}
,"refactored":{"fix":1}
,"fix":{"problem":1}
,"problem":{"running":1}
,"running":{"terracotta":1}
,"3.6.0":{"higher":1}
,"higher":{"write":1}
,"write":{"servlet":1}
,"servlet":{"filter":1}
,"filter":{"calls":1,"{public":1}
,"calls":{"setattribute":1}
,"end":{"every":1}
,"request":{"note":1,"servletresponse":1}
,"note":{"solution":1}
,"solution":{"may":1}
,"substantially":{"degrade":1}
,"degrade":{"performance":1}
,"performance":{"package":1}
,"package":{"controller.filter":1}
,"controller.filter":{"import":1}
,"import":{"java.io.ioexception":1,"java.util.enumeration":1,"javax.servlet.filter":1,"javax.servlet.filterchain":1,"javax.servlet.filterconfig":1,"javax.servlet.servletexception":1,"javax.servlet.servletrequest":1,"javax.servlet.servletresponse":1,"javax.servlet.http.httpservletrequest":1,"javax.servlet.http.httpsession":1}
,"java.io.ioexception":{"import":1}
,"java.util.enumeration":{"import":1}
,"javax.servlet.filter":{"import":1}
,"javax.servlet.filterchain":{"import":1}
,"javax.servlet.filterconfig":{"import":1}
,"javax.servlet.servletexception":{"import":1}
,"javax.servlet.servletrequest":{"import":1}
,"javax.servlet.servletresponse":{"import":1}
,"javax.servlet.http.httpservletrequest":{"import":1}
,"javax.servlet.http.httpsession":{"public":1}
,"public":{"class":1,"void":1}
,"class":{"iteratefilter":1}
,"iteratefilter":{"implements":1}
,"implements":{"filter":1}
,"{public":{"void":1}
,"void":{"dofilter":1,"init":1,"destroy":1}
,"dofilter":{"(servletrequest":1}
,"(servletrequest":{"request":1}
,"servletresponse":{"response":1}
,"response":{"filterchain":1}
,"filterchain":{"chain)":1}
,"chain)":{"throws":1}
,"throws":{"ioexception":1,"servletexception":1}
,"ioexception":{"servletexception":1}
,"servletexception":{"{httpsession":1,"{\u002F\u002Ftodo":1}
,"{httpsession":{"session":1}
,"=((httpservletrequest)":{"request)":1}
,"request)":{".getsession":1}
,".getsession":{"(session":1}
,"(session":{"!=null)":1}
,"!=null)":{"{@suppresswarnings":1}
,"{@suppresswarnings":{"rawtypes":1}
,"rawtypes":{"enumeration":1}
,"enumeration":{"=session.getattributenames":1}
,"=session.getattributenames":{"(e.hasmoreelements":1}
,"(e.hasmoreelements":{"())":1}
,"())":{"{string":1}
,"{string":{"name":1}
,"name":{"=(string)":1}
,"=(string)":{"e.nextelement":1}
,"e.nextelement":{"object":1}
,"value":{"=session.getattribute":1}
,"(name)":{"session.setattribute":1}
,"(name":{"value)":1}
,"value)":{"public":1}
,"init":{"(filterconfig":1}
,"(filterconfig":{"filterconfig)":1}
,"filterconfig)":{"throws":1}
,"{\u002F\u002Ftodo":{"auto-generated":1}
,"auto-generated":{"method":1}
,"method":{"stub":1}
,"stub":{"public":1}
,"destroy":{"{\u002F\u002Ftodo":1}
}
;Search.control.loadWordPairs(pairs);
