var pairs =
{
"configuring":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"run":1,"array":1,"name":1,"want":1}
,"run":{"service":1,"terracotta":1,"script":1}
,"service":{"windows":1,"supports":1,"service":1,"wrapper":1,"java_home":1,"located":1,"bin\u002Ftsa-service.bat":1}
,"windows":{"service":1,"want":1}
,"supports":{"scheduling":1}
,"scheduling":{"automatic":1}
,"automatic":{"start":1}
,"start":{"restart":1,"service":1,"permissions":1,"stop":1,"bin\u002Ftsa-service.bat":1}
,"restart":{"want":1}
,"want":{"run":1,"configuration":1,"change":1,"start":1,"remove":1}
,"array":{"cross-language":1}
,"cross-language":{"connector":1}
,"connector":{"java":1,"need":1,"clc-service":1}
,"java":{"applications":1}
,"applications":{"windows":1}
,"wrapper":{"located":1,"read":1,"configurations":1,"directory":1,"service":1,"run":1,"configuration":1}
,"located":{"inside":1,"$installdir\u002Fserver\u002Fwrapper":1}
,"inside":{"kit":1}
,"kit":{"$installdir\u002Fserver\u002Fwrapper":1}
,"$installdir\u002Fserver\u002Fwrapper":{"(or":1,"install":1}
,"(or":{"3.7":1}
,"3.7":{"$installdir\u002Fwrapper":1}
,"$installdir\u002Fwrapper":{"java_home":1}
,"java_home":{"start":1,"conf\u002Fwrapper-tsa.conf":1,"environment":1,"registry":1}
,"conf\u002Fwrapper-tsa.conf":{"conf\u002Fwrapper-clc.conf":1,"file":1}
,"conf\u002Fwrapper-clc.conf":{"example":1}
,"example":{"set.java_home=c:\u002Fjava\u002Fjdk1.7.0_21":1}
,"set.java_home=c:\u002Fjava\u002Fjdk1.7.0_21":{"wrapper":1}
,"read":{"java_home":1}
,"environment":{"windows":1}
,"configuration":{"file":1,"files":1,"comments":1}
,"file":{"comment":1,"conf\u002Ftc-config.xml":1,"names":1,"match":1}
,"comment":{"java_home":1}
,"registry":{"instead":1}
,"instead":{"configuration":1}
,"files":{"cross-language":1,"conf\u002Fcross-language-config.xml":1,"want":1}
,"need":{"configuration":1,"modify":1}
,"conf\u002Fcross-language-config.xml":{"conf\u002Fehcache.xml":1}
,"conf\u002Fehcache.xml":{"tsa":1}
,"tsa":{"need":1,"conf\u002Fwrapper-tsa.conf":1,"script":1}
,"conf\u002Ftc-config.xml":{"overwrite":1}
,"overwrite":{"files":1}
,"change":{"file":1}
,"names":{"modify":1,"wrapper":1}
,"modify":{"names":1,"tsa":1,"jvm":1}
,"configurations":{"modify":1}
,"match":{"server":1}
,"name":{"tc-config.xml":1,"server":1}
,"tc-config.xml":{"set.server_name=server0":1}
,"set.server_name=server0":{"server0":1}
,"server0":{"represents":1}
,"represents":{"name":1}
,"permissions":{"services":1}
,"services":{"controlled":1}
,"controlled":{"administrator":1}
,"administrator":{"user":1}
,"user":{"confirm":1,"needs":1}
,"confirm":{"every":1}
,"every":{"action":1}
,"action":{"install":1}
,"install":{"start":1,"service":1,"parameter":1,"examples":1}
,"stop":{"remove":1,"want":1}
,"remove":{"addition":1,"service":1,"commands":1}
,"addition":{"administrator":1}
,"needs":{"read\u002Fwrite":1}
,"read\u002Fwrite":{"permission":1}
,"permission":{"wrapper":1}
,"directory":{"install":1}
,"script":{"install":1,"cross-language":1,"either":1,"without":1}
,"parameter":{"bin\u002Ftsa-service.bat":1,"need":1,"counts":1}
,"bin\u002Ftsa-service.bat":{"install":1,"start":1,"stop":1,"remove":1,"changing":1}
,"examples":{"section":1}
,"section":{"show":1}
,"show":{"tsa":1}
,"clc-service":{"clc-service.bat":1}
,"clc-service.bat":{"script":1}
,"either":{"start\u002Fstop":1}
,"start\u002Fstop":{"service":1}
,"commands":{"available":1}
,"available":{"run":1}
,"without":{"parameter":1}
,"changing":{"wrapper":1}
,"comments":{"wrapper-tsa.conf":1}
,"wrapper-tsa.conf":{"wrapper-clc.conf":1}
,"wrapper-clc.conf":{"explain":1}
,"explain":{"parameter":1}
,"jvm":{"system":1}
,"system":{"properties":1}
,"properties":{"classpath":1}
,"classpath":{"command":1}
,"command":{"line":1}
,"line":{"parameters":1}
,"parameters":{"follow":1}
,"follow":{"current":1}
,"current":{"pattern":1}
,"pattern":{"pay":1}
,"pay":{"close":1}
,"close":{"attention":1}
,"attention":{"numerical":1}
,"numerical":{"order":1}
,"order":{"parameter":1}
,"counts":{"information":1}
,"information":{"http:\u002F\u002Fwrapper.tanukisoftware.com\u002Fdoc\u002Fenglish\u002Fproperties.html":1}
}
;Search.control.loadWordPairs(pairs);
