var pairs =
{
"master-replica":{"deployment":1}
,"deployment":{"master":1,"may":1,"combination-region":1}
,"master":{"replica":1,"caches":1,"cache":1}
,"replica":{"caches":1,"region":1}
,"caches":{"arranged":1,"single":1,"mastered":1,"master-region":1,"confined":1,"time":1,"replicating":1,"figure":1,"combination-region":1}
,"arranged":{"two":1}
,"two":{"basic":1}
,"basic":{"deployments":1}
,"deployments":{"master-region":1}
,"master-region":{"combination-region":1,"master-region":1,"deployment":1}
,"combination-region":{"master-region":1,"combination-region":1,"deployment":1}
,"may":{"used":1,"mastering":1}
,"used":{"keep":1,"backup":1,"master":1}
,"keep":{"master":1}
,"single":{"region":1,"application":1}
,"region":{"arrangement":1,"used":1,"regions":1,"application":1,"may":1,"caches":1,"region":1,"replica":1}
,"arrangement":{"effective":1}
,"effective":{"single":1,"geographically":1}
,"application":{"using":1,"active":1}
,"using":{"wan":1}
,"wan":{"replication":1}
,"replication":{"replica":1}
,"backup":{"location":1}
,"location":{"disaster":1}
,"disaster":{"recovery":1}
,"recovery":{"figure":1}
,"figure":{"below":1}
,"below":{"shows":1}
,"shows":{"caches":1,"cache":1}
,"mastered":{"region":1}
,"regions":{"replicas":1}
,"replicas":{"caches":1}
,"confined":{"particular":1}
,"particular":{"region":1}
,"geographically":{"distributed":1}
,"distributed":{"applications":1}
,"applications":{"concurrently":1}
,"concurrently":{"bigmemory":1}
,"bigmemory":{"data":1}
,"data":{"master":1}
,"cache":{"located":1,"mastered":1}
,"located":{"region":1}
,"active":{"orchestrator":1}
,"orchestrator":{"manage":1}
,"manage":{"non-overlapping":1}
,"non-overlapping":{"master":1}
,"time":{"means":1}
,"means":{"region":1}
,"mastering":{"caches":1}
,"replicating":{"caches":1}
}
;Search.control.loadWordPairs(pairs);
