var pairs =
{
"overview":{"bigmemory":1}
,"bigmemory":{"max":1,".net":1}
,"max":{"security":1}
,"security":{"security":1,"applied":1,"strategy":1,"measure":1,"configuration":1,"environment":1,"outside":1,"related":1,"typical":1,"(tls)":1,"extensively":1,"cluster":1,"setting":1,"using":1}
,"applied":{"authentication":1}
,"authentication":{"(such":1,"using":1,"configuring":1,"bigmemory":1}
,"(such":{"login":1}
,"login":{"credentials)":1}
,"credentials)":{"authorization":1}
,"authorization":{"(the":1}
,"(the":{"privileges":1}
,"privileges":{"specific":1}
,"specific":{"roles)":1,"documentation":1}
,"roles)":{"recommend":1}
,"recommend":{"plan":1}
,"plan":{"implement":1}
,"implement":{"security":1}
,"strategy":{"encompasses":1}
,"encompasses":{"points":1}
,"points":{"potential":1}
,"potential":{"vulnerability":1}
,"vulnerability":{"environment":1}
,"environment":{"including":1,"specific":1,"previously":1,"tools":1}
,"including":{"necessarily":1}
,"necessarily":{"limited":1}
,"limited":{"application":1}
,"application":{"servers":1}
,"servers":{"(terracotta":1,"tsa":1,"applying":1}
,"(terracotta":{"clients)":1}
,"clients)":{"terracotta":1}
,"terracotta":{"servers":1,"management":1,"encrypt":1,"configuration":1,"cluster":1,"server":1,"client":1,"clients":1}
,"tsa":{"terracotta":1}
,"management":{"console":1,"server":1}
,"console":{"(tmc)":1,"user":1}
,"(tmc)":{"bigmemory":1,"terracotta":1}
,".net":{"clients":1}
,"clients":{"terracotta":1,"using":1,"cross-language":1,"user":1}
,"encrypt":{"data":1}
,"data":{"servers":1,"encryption":1}
,"applying":{"data":1}
,"encryption":{"possible":1}
,"possible":{"security":1,"options":1}
,"measure":{"scope":1}
,"scope":{"ssl":1,"documentation":1}
,"ssl":{"documentation":1,"java":1,"configuration":1,"configured":1,"ldap":1,"terracotta":1}
,"documentation":{"ssl":1,"assumes":1,"documentation":1}
,"java":{"security":1}
,"configuration":{"complex":1,"wish":1,"introducing":1,"intended":1,"securing":1}
,"complex":{"environment":1}
,"assumes":{"already":1,"solid":1}
,"already":{"working":1}
,"working":{"ssl":1}
,"wish":{"add":1}
,"add":{"terracotta":1}
,"introducing":{"ssl":1}
,"previously":{"ssl":1}
,"outside":{"scope":1}
,"solid":{"understanding":1}
,"understanding":{"ssl":1}
,"related":{"concepts":1}
,"concepts":{"freely":1}
,"freely":{"accessible":1}
,"accessible":{"documents":1}
,"documents":{"web":1}
,"web":{"guide":1,"site":1}
,"guide":{"learning":1,"need":1,"bigmemory":1}
,"learning":{"understanding":1}
,"typical":{"terms":1}
,"terms":{"search":1}
,"search":{"public":1}
,"public":{"key":1}
,"key":{"certificate":1}
,"certificate":{"transport":1}
,"transport":{"layer":1}
,"layer":{"security":1}
,"(tls)":{"keytool":1}
,"keytool":{"utility":1}
,"utility":{"descriptions":1}
,"descriptions":{"following":1,"setting":1}
,"following":{"sections":1,"descriptions":1}
,"sections":{"give":1}
,"give":{"examples":1}
,"examples":{"third":1,"setup":1}
,"third":{"party":1}
,"party":{"tools":1}
,"tools":{"help":1,"widely":1,"limit":1}
,"help":{"environment":1}
,"widely":{"used":1}
,"used":{"context":1}
,"context":{"java":1}
,"extensively":{"documented":1}
,"documented":{"web":1}
,"site":{"tool":1}
,"tool":{"supplier":1}
,"supplier":{"cases":1}
,"cases":{"attempt":1}
,"attempt":{"document":1}
,"document":{"possible":1}
,"options":{"tools":1,"required":1}
,"limit":{"ourselves":1}
,"ourselves":{"mentioning":1}
,"mentioning":{"just":1}
,"just":{"options":1}
,"required":{"commands":1}
,"commands":{"sequences":1,"following":1}
,"sequences":{"commands":1}
,"setting":{"security":1,"server":1,"tsa":1}
,"intended":{"outlines":1}
,"outlines":{"describe":1,"rough":1,"suite":1}
,"describe":{"basics":1}
,"basics":{"getting":1}
,"getting":{"ssl":1}
,"configured":{"setups":1}
,"setups":{"generally":1}
,"generally":{"work":1}
,"work":{"out-of-the-box":1}
,"out-of-the-box":{"customer":1}
,"customer":{"unique":1}
,"unique":{"requirements":1}
,"requirements":{"try":1}
,"try":{"copy":1}
,"copy":{"paste":1}
,"paste":{"examples":1}
,"setup":{"probably":1}
,"probably":{"valid":1}
,"valid":{"therefore":1}
,"therefore":{"outlines":1}
,"rough":{"guide":1}
,"need":{"tailor":1}
,"tailor":{"outlines":1}
,"suite":{"particular":1}
,"particular":{"configuration":1}
,"securing":{"terracotta":1,"against":1}
,"cluster":{"components":1,"setting":1}
,"components":{"terracotta":1}
,"server":{"array":1,"security":1,"using":1}
,"array":{"(tsa)":1}
,"(tsa)":{"using":1}
,"using":{"ssl":1,"ldap":1,"encrypted":1,"jmx":1}
,"ldap":{"jmx":1,"active":1}
,"jmx":{"introduction":1,"authentication":1}
,"introduction":{"security":1}
,"active":{"directory":1}
,"directory":{"authentication":1}
,"encrypted":{"keychains":1}
,"keychains":{"terracotta":1,"serialization":1}
,"client":{"(your":1}
,"(your":{"application)":1}
,"application)":{"enabling":1}
,"enabling":{"ssl":1}
,"serialization":{"securing":1}
,"against":{"untrusted":1}
,"untrusted":{"clients":1}
,"user":{"guide":1}
,"configuring":{"security":1}
,"cross-language":{"clients":1}
}
;Search.control.loadWordPairs(pairs);
