var pairs =
{
"configuration":{"production":1,"file":1,"terracotta":1,"server":1,"path":1,"files":1}
,"production":{"environment":1,"example":1,"host\u0027s":1,"clients":1,"terracotta":1}
,"environment":{"efficient":1,"it\u0027s":1,"launching":1,"start":1,"variables":1}
,"efficient":{"production":1}
,"it\u0027s":{"recommended":1,"effective":1}
,"recommended":{"maintain":1}
,"maintain":{"terracotta":1}
,"terracotta":{"configuration":1,"server":1,"environment":1,"client":1,"products":1,"web":1}
,"file":{"file":1,"loaded":1,"uses":1,"(ehcache.xml":1,"(quartz.properties":1}
,"loaded":{"terracotta":1}
,"server":{"(or":1,"element":1,"specified":1,"push":1,"setting":1,"available":1}
,"(or":{"servers)":1}
,"servers)":{"pushed":1}
,"pushed":{"clients":1}
,"clients":{"optional":1,"production":1}
,"optional":{"approach":1}
,"approach":{"it\u0027s":1}
,"effective":{"centralize":1}
,"centralize":{"decrease":1}
,"decrease":{"maintenance":1}
,"maintenance":{"terracotta":1}
,"uses":{"hostname":1}
,"hostname":{"attribute":1,"production":1,"myhostname":1}
,"attribute":{"server":1,"myhostname":1}
,"element":{"change":1,"ehcache":1}
,"change":{"actual":1,"host":1}
,"actual":{"hostname":1}
,"example":{"development":1}
,"development":{"used":1}
,"used":{"following":1,"terracotta":1}
,"following":{"<server":1,"environment":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"name=\u0022":1,"myhostname":1}
,"name=\u0022":{"server1":1}
,"server1":{"production":1,"clients":1}
,"host\u0027s":{"hostname":1}
,"myhostname":{"change":1,"<server":1,"name=\u0022":1}
,"host":{"attribute":1}
,"launching":{"application":1}
,"application":{"setting":1,"terracotta":1}
,"setting":{"terracotta":1,"tc.config":1}
,"start":{"application":1}
,"client":{"using":1,"alternatively":1,"specify":1}
,"using":{"scripts":1,"configuration":1}
,"scripts":{"first":1}
,"first":{"following":1}
,"variables":{"tc_install_dir=<path_to_local_terracotta_home>":1}
,"tc_install_dir=<path_to_local_terracotta_home>":{"tc_config_path=<path\u002Fto\u002Ftc-config.xml>":1}
,"tc_config_path=<path\u002Fto\u002Ftc-config.xml>":{"tc_config_path=<server_host>":1}
,"tc_config_path=<server_host>":{"<tsa-port>":1}
,"<tsa-port>":{"<server_host>":1,"points":1,"<server_host2>":1,"<server_host1>":1}
,"<server_host>":{"<tsa-port>":1}
,"points":{"running":1}
,"running":{"terracotta":1}
,"specified":{"terracotta":1}
,"push":{"configuration":1}
,"alternatively":{"client":1}
,"specify":{"configuration":1}
,"tc.config":{"system":1}
,"system":{"property":1}
,"property":{"-dtc.config=serverhost:tsaport":1,"quartz":1}
,"-dtc.config=serverhost:tsaport":{"terracotta":1}
,"available":{"enter":1}
,"enter":{"comma-separated":1}
,"comma-separated":{"list":1}
,"list":{"tc_config_path=<server_host1>":1}
,"tc_config_path=<server_host1>":{"<tsa-port>":1}
,"<server_host2>":{"<tsa-port>":1,"used":1}
,"<server_host1>":{"unavailable":1}
,"unavailable":{"<server_host2>":1}
,"products":{"terracotta":1,"configuration":1}
,"path":{"using":1}
,"files":{"bigmemory":1}
,"bigmemory":{"max":1,"<terracottaconfig>":1}
,"max":{"bigmemory":1}
,"<terracottaconfig>":{"element":1}
,"ehcache":{"configuration":1}
,"(ehcache.xml":{"default)":1}
,"default)":{"<terracottaconfig":1,"org.quartz.jobstore.tcconfigurl":1}
,"<terracottaconfig":{"url=\u0022":1}
,"url=\u0022":{"localhost:9510":1}
,"localhost:9510":{"quartz":1}
,"quartz":{"org.quartz.jobstore.tcconfigurl":1,"properties":1}
,"org.quartz.jobstore.tcconfigurl":{"property":1,"=\u002Fmypath\u002Fto\u002Ftc-config.xml":1}
,"properties":{"file":1}
,"(quartz.properties":{"default)":1}
,"=\u002Fmypath\u002Fto\u002Ftc-config.xml":{"terracotta":1}
,"web":{"sessions":1}
,"sessions":{"appropriate":1,"user":1}
,"appropriate":{"elements":1}
,"elements":{"web.xml":1}
,"web.xml":{"context.xml":1}
,"context.xml":{"(see":1}
,"(see":{"web":1}
,"user":{"guide)":1}
,"guide)":{"don":1}
,"don":{"added":1}
,"added":{"link":1}
}
;Search.control.loadWordPairs(pairs);
