var pairs =
{
"working":{"osgi":1}
,"osgi":{"allow":1,"component":1,"bundle":1}
,"allow":{"enterprise":1}
,"enterprise":{"ehcache":1}
,"ehcache":{"behave":1,"bundle":1}
,"behave":{"osgi":1}
,"component":{"following":1}
,"following":{"attributes":1,"jar":1,"directory":1,"example":1,"command":1}
,"attributes":{"shown":1}
,"shown":{"<cache":1}
,"<cache":{"copyonread=\u0022":1}
,"copyonread=\u0022":{"true":1}
,"true":{"<terracotta":1,"<\u002Fcache>":1}
,"<terracotta":{"clustered=\u0022":1}
,"clustered=\u0022":{"true":1}
,"<\u002Fcache>":{"osgi":1}
,"bundle":{"require":1,"created-by":1,"execute":1}
,"require":{"following":1}
,"jar":{"files":1,"cvfm":1}
,"files":{"(showing":1}
,"(showing":{"versions":1}
,"versions":{"bigmemory":1,"appropriate":1}
,"bigmemory":{"max":1}
,"max":{"4.0.0)":1}
,"4.0.0)":{"ehcache-ee-2.7.0.jar":1}
,"ehcache-ee-2.7.0.jar":{"terracotta-toolkit-runtime-ee-4.0.0.jar":1}
,"terracotta-toolkit-runtime-ee-4.0.0.jar":{"slf4j-api-1.6.6.jar":1}
,"slf4j-api-1.6.6.jar":{"slf4j-nop-1.6.1.jar":1,"slf4j-nop-1.6.6.jar":1}
,"slf4j-nop-1.6.1.jar":{"appropriate":1}
,"appropriate":{"logger":1,"setup":1}
,"logger":{"binding":1}
,"binding":{"following":1}
,"directory":{"structure":1,"jar":1}
,"structure":{"--net.sf.ehcache":1}
,"--net.sf.ehcache":{"-ehcache.xml":1}
,"-ehcache.xml":{"|-ehcache-ee-2.7.0.jar":1}
,"|-ehcache-ee-2.7.0.jar":{"|-terracotta-toolkit-runtime-ee-4.0.0.jar":1}
,"|-terracotta-toolkit-runtime-ee-4.0.0.jar":{"-slf4j-api-1.6.6.jar":1}
,"-slf4j-api-1.6.6.jar":{"-slf4j-nop-1.6.6.jar":1}
,"-slf4j-nop-1.6.6.jar":{"-meta-inf\u002F|":1}
,"-meta-inf\u002F|":{"-manifest.mf":1}
,"-manifest.mf":{"following":1}
,"example":{"manifest":1}
,"manifest":{"file":1}
,"file":{"manifest-version":1}
,"manifest-version":{"1.0":1}
,"1.0":{"export-package":1}
,"export-package":{"net.sf.ehcache":1}
,"net.sf.ehcache":{"version=\u0022":1,"bundle-requiredexecutionenvironment":1,"directory":1}
,"version=\u0022":{"2.7.0":1,"1.3.0":1}
,"2.7.0":{"bundle-vendor":1,"bundle-name":1}
,"bundle-vendor":{"terracotta":1}
,"terracotta":{"bundle-classpath":1}
,"bundle-classpath":{"ehcache-ee-2.7.0.jar":1}
,"slf4j-nop-1.6.6.jar":{"bundle-version":1}
,"bundle-version":{"2.7.0":1}
,"bundle-name":{"ehcache":1}
,"created-by":{"1.6.0_15":1}
,"1.6.0_15":{"(apple":1}
,"(apple":{"inc.)":1}
,"inc.)":{"bundle-manifestversion":1}
,"bundle-manifestversion":{"import-package":1}
,"import-package":{"org.osgi.framework":1}
,"org.osgi.framework":{"version=\u0022":1}
,"1.3.0":{"bundle-symbolicname":1}
,"bundle-symbolicname":{"net.sf.ehcache":1}
,"bundle-requiredexecutionenvironment":{"j2se-1.5":1}
,"j2se-1.5":{"versions":1}
,"setup":{"create":1}
,"create":{"bundle":1}
,"execute":{"following":1}
,"command":{"net.sf.ehcache":1}
,"cvfm":{"net.sf.ehcache.jar":1}
,"net.sf.ehcache.jar":{"manifest.mf":1}
}
;Search.control.loadWordPairs(pairs);
