var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fauthentication":{"turn":1}
,"turn":{"jmx":1}
,"jmx":{"authentication":1}
,"authentication":{"terracotta":1,"mechanism":1,"bigmemory":1}
,"terracotta":{"server":1}
,"server":{"empty":1}
,"empty":{"tag":1}
,"tag":{"(<authentication":1}
,"(<authentication":{"\u002F>)":1}
,"\u002F>)":{"defaults":1}
,"defaults":{"standard":1}
,"standard":{"java":1}
,"java":{"jmx":1}
,"mechanism":{"referring":1}
,"referring":{"password":1}
,"password":{"access":1,"followed":1}
,"access":{"files":1}
,"files":{"$java_home\u002Fjre\u002Flib\u002Fmanagement":1,"follows":1}
,"$java_home\u002Fjre\u002Flib\u002Fmanagement":{"$java_home\u002Fjre\u002Flib\u002Fmanagement\u002Fjmxremote.password":1}
,"$java_home\u002Fjre\u002Flib\u002Fmanagement\u002Fjmxremote.password":{"$java_home\u002Fjre\u002Flib\u002Fmanagement\u002Fjmxremote.access":1}
,"$java_home\u002Fjre\u002Flib\u002Fmanagement\u002Fjmxremote.access":{"modify":1}
,"modify":{"files":1}
,"follows":{"(or":1}
,"(or":{"none":1}
,"none":{"exist":1}
,"exist":{"create":1}
,"create":{"them)":1}
,"them)":{"jmxremote.password":1}
,"jmxremote.password":{"add":1,"$chown":1,"information":1}
,"add":{"line":1,"following":1}
,"line":{"end":1,"(with":1}
,"end":{"file":1}
,"file":{"declaring":1,"secretusername":1,"example":1}
,"declaring":{"username":1}
,"username":{"password":1}
,"followed":{"carriage":1}
,"carriage":{"return":1,"return)":1}
,"return":{"secretusername":1}
,"secretusername":{"secretpassword":1,"readwrite":1}
,"secretpassword":{"jmxremote.access":1}
,"jmxremote.access":{"add":1}
,"following":{"line":1}
,"(with":{"carriage":1}
,"return)":{"end":1}
,"readwrite":{"sure":1}
,"sure":{"assign":1}
,"assign":{"appropriate":1}
,"appropriate":{"permissions":1}
,"permissions":{"file":1}
,"example":{"*nix":1}
,"*nix":{"$chmod":1}
,"$chmod":{"500":1}
,"500":{"jmxremote.password":1}
,"$chown":{"<user":1}
,"<user":{"run":1}
,"run":{"server>":1}
,"server>":{"jmxremote.password":1}
,"information":{"alternatives":1}
,"alternatives":{"jmx":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
,"security":{"guide":1}
,"guide":{"note":1}
,"note":{"version":1}
,"version":{"4.x":1}
,"4.x":{"support":1}
,"support":{"http":1}
,"http":{"authentication":1}
}
;Search.control.loadWordPairs(pairs);
