var pairs =
{
"restricting":{"clients":1}
,"clients":{"specified":1,"restricted":1}
,"specified":{"servers":1}
,"servers":{"(optional)":1,"responding":1,"client":1,"follows":1,"hostnames":1,"client\u0027s":1,"listed":1}
,"(optional)":{"default":1}
,"default":{"clients":1}
,"restricted":{"authenticate":1}
,"authenticate":{"specific":1,"against":1}
,"specific":{"servers":1}
,"responding":{"rest":1}
,"rest":{"requests":1,"service":1,"request":1}
,"requests":{"however":1}
,"however":{"possible":1,"servers":1}
,"possible":{"explicitly":1}
,"explicitly":{"list":1}
,"list":{"servers":1,"allowed":1}
,"client":{"respond":1,"authenticate":1,"time":1}
,"respond":{"using":1}
,"using":{"<managementrestservice>":1}
,"<managementrestservice>":{"element\u0027s":1}
,"element\u0027s":{"securityservicelocation":1}
,"securityservicelocation":{"attribute":1}
,"attribute":{"ehcache":1,"empty":1}
,"ehcache":{"configuration":1}
,"configuration":{"attribute":1}
,"empty":{"(or":1}
,"(or":{"missing)":1}
,"missing)":{"restriction":1}
,"restriction":{"exists":1}
,"exists":{"client":1}
,"against":{"server":1}
,"server":{"cluster":1}
,"cluster":{"meets":1,"forward":1}
,"meets":{"established":1}
,"established":{"security":1}
,"security":{"requirements":1,"case":1,"required":1}
,"requirements":{"recommended":1}
,"recommended":{"setting":1}
,"setting":{"ssl":1}
,"ssl":{"connections":1}
,"connections":{"mechanism":1}
,"mechanism":{"authentication":1}
,"authentication":{"authorization":1}
,"authorization":{"provide":1}
,"provide":{"sufficient":1}
,"sufficient":{"security":1}
,"case":{"extra":1}
,"extra":{"layer":1}
,"layer":{"security":1}
,"required":{"client\u0027s":1}
,"client\u0027s":{"rest":1,"cluster":1}
,"service":{"configure":1}
,"configure":{"list":1}
,"allowed":{"servers":1}
,"follows":{"<managementrestservice":1}
,"<managementrestservice":{"securityservicelocation=\u0022":1}
,"securityservicelocation=\u0022":{"https:\u002F\u002Fmy-l2-node1\u002Ftmc\u002Fapi\u002Fassertidentity":1}
,"https:\u002F\u002Fmy-l2-node1\u002Ftmc\u002Fapi\u002Fassertidentity":{"https:\u002F\u002Fmy-l2-node2\u002Ftmc\u002Fapi\u002Fassertidentity":1}
,"https:\u002F\u002Fmy-l2-node2\u002Ftmc\u002Fapi\u002Fassertidentity":{"my-l2-node1":1}
,"my-l2-node1":{"my-l2-node2":1}
,"my-l2-node2":{"servers":1}
,"hostnames":{"however":1}
,"forward":{"rest":1}
,"request":{"client":1}
,"time":{"therefore":1}
,"therefore":{"feature":1}
,"feature":{"used":1}
,"used":{"servers":1}
}
;Search.control.loadWordPairs(pairs);
