var pairs =
{
"automatic":{"server":1,"reconnect":1}
,"server":{"instance":1,"instances":1,"array":1}
,"instance":{"reconnect":1,"attempt":1,"disconnection":1}
,"reconnect":{"automatic":1,"mechanism":1}
,"mechanism":{"prevent":1,"default":1,"event-based":1,"works":1,"cannot":1,"triggered":1,"exposed":1,"l2.nha.tcgroupcomm.reconnect.enabled":1}
,"prevent":{"short":1}
,"short":{"network":1}
,"network":{"disruptions":1}
,"disruptions":{"forcing":1}
,"forcing":{"restart":1}
,"restart":{"terracotta":1}
,"terracotta":{"server":1,"event":1}
,"instances":{"server":1}
,"array":{"hot":1}
,"hot":{"standbys":1}
,"standbys":{"disabled":1}
,"disabled":{"mechanism":1}
,"default":{"effect":1,"2000":1}
,"effect":{"clusters":1}
,"clusters":{"networked-based":1}
,"networked-based":{"mode":1}
,"mode":{"increased":1}
,"increased":{"time-to-failover":1}
,"time-to-failover":{"-this":1,"timeout":1}
,"-this":{"feature":1}
,"feature":{"increases":1}
,"increases":{"time-to-failover":1}
,"timeout":{"value":1,"(in":1}
,"value":{"automatic":1}
,"event-based":{"reconnection":1}
,"reconnection":{"mechanism":1,"peer":1,"default":1}
,"works":{"independently":1}
,"independently":{"exclusively":1}
,"exclusively":{"healthchecker":1}
,"healthchecker":{"healthchecker":1,"already":1,"prevented":1}
,"already":{"triggered":1}
,"triggered":{"mechanism":1,"node":1,"first":1}
,"cannot":{"triggered":1}
,"node":{"mechanism":1,"events":1}
,"first":{"internal":1}
,"internal":{"terracotta":1}
,"event":{"healthchecker":1}
,"prevented":{"triggered":1}
,"events":{"trigger":1}
,"trigger":{"mechanism":1}
,"exposed":{"api":1}
,"api":{"logged":1}
,"logged":{"configure":1}
,"configure":{"following":1}
,"following":{"properties":1}
,"properties":{"reconnect":1}
,"l2.nha.tcgroupcomm.reconnect.enabled":{"-(default":1,"true":1}
,"-(default":{"false)":1}
,"false)":{"true":1}
,"true":{"enables":1,"specifies":1}
,"enables":{"server":1}
,"attempt":{"reconnection":1}
,"peer":{"server":1}
,"disconnection":{"detected":1}
,"detected":{"cases":1}
,"cases":{"benefit":1}
,"benefit":{"enabling":1}
,"enabling":{"setting":1}
,"setting":{"l2.nha.tcgroupcomm.reconnect.timeout":1}
,"l2.nha.tcgroupcomm.reconnect.timeout":{"-enabled":1}
,"-enabled":{"l2.nha.tcgroupcomm.reconnect.enabled":1}
,"specifies":{"timeout":1}
,"(in":{"milliseconds)":1}
,"milliseconds)":{"reconnection":1}
,"2000":{"parameter":1}
,"parameter":{"tuned":1}
,"tuned":{"handle":1}
,"handle":{"longer":1}
,"longer":{"network":1}
}
;Search.control.loadWordPairs(pairs);
