var pairs =
{
"overview":{"monitoring":1}
,"monitoring":{"managing":1,"connect":1,"application":1,"capability":1}
,"managing":{"wan":1}
,"wan":{"replication":1}
,"replication":{"terracotta":1,"service":1}
,"terracotta":{"enables":1,"issues":1,"gathers":1,"exposes":1,"provides":1}
,"enables":{"monitor":1}
,"monitor":{"information":1}
,"information":{"following":1}
,"following":{"aspects":1}
,"aspects":{"wan":1}
,"service":{"wan\u0027s":1,"monitoring":1}
,"wan\u0027s":{"topology":1}
,"topology":{"configuration":1,"event":1}
,"configuration":{"addition":1,"parameters":1}
,"addition":{"terracotta":1}
,"issues":{"topology":1}
,"event":{"alerts":1}
,"alerts":{"replica":1}
,"replica":{"cache":1}
,"cache":{"connects":1,"wan-enabled":1,"including":1,"two":1}
,"connects":{"disconnects":1}
,"disconnects":{"master":1}
,"master":{"cache":1}
,"wan-enabled":{"cache":1}
,"including":{"performance":1}
,"performance":{"statistics":1}
,"statistics":{"details":1,"orchestrators":1,"jmx":1,"connect":1}
,"details":{"deployment":1}
,"deployment":{"conflicts":1}
,"conflicts":{"status":1}
,"status":{"terracotta":1}
,"gathers":{"statistics":1}
,"orchestrators":{"displays":1}
,"displays":{"cache":1}
,"two":{"ways":1}
,"ways":{"connect":1}
,"connect":{"wan":1,"via":1}
,"via":{"jmx":1,"rest":1}
,"jmx":{"terracotta":1,"mbeans":1,"monitoring":1}
,"exposes":{"jmx":1}
,"mbeans":{"gather":1}
,"gather":{"statistics":1}
,"application":{"jconsole":1}
,"jconsole":{"visualvm":1}
,"visualvm":{"view":1}
,"view":{"statistics":1}
,"rest":{"apis":1}
,"apis":{"terracotta":1}
,"provides":{"monitoring":1}
,"capability":{"enabled":1,"monitoringenabled":1}
,"enabled":{"default":1}
,"default":{"orchestrator":1}
,"orchestrator":{"want":1,"configuration":1}
,"want":{"disable":1}
,"disable":{"monitoring":1}
,"monitoringenabled":{"parameter":1}
,"parameter":{"false":1}
,"false":{"orchestrator\u0027s":1}
,"orchestrator\u0027s":{"wan-config.xml":1}
,"wan-config.xml":{"file":1}
,"file":{"orchestrator":1}
}
;Search.control.loadWordPairs(pairs);
