var pairs =
{
"example":{"nonstop\u002Frejoin":1,"available":1,"demonstrates":1}
,"nonstop\u002Frejoin":{"following":1}
,"following":{"description":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"nonstop":1}
,"nonstop":{"feature":1,"timeout":1,"rejoin":1,"working":1}
,"feature":{"allows":1,"working":1,"action":1}
,"allows":{"certain":1,"operations":1,"clients":1}
,"certain":{"operations":1}
,"operations":{"proceed":1}
,"proceed":{"clients":1,"even":1}
,"clients":{"become":1,"identify":1,"rejoin":1}
,"become":{"disconnected":1}
,"disconnected":{"cluster":1}
,"cluster":{"allows":1,"having":1,"timed":1}
,"even":{"cannot":1}
,"cannot":{"complete":1}
,"complete":{"nonstop":1}
,"timeout":{"value":1}
,"value":{"rejoin":1}
,"rejoin":{"feature":1,"cluster":1,"features":1,"working":1}
,"identify":{"source":1}
,"source":{"terracotta":1}
,"terracotta":{"configuration":1,"server":1}
,"configuration":{"clients":1,"below":1,"managerconfig":1,".terracotta":1}
,"having":{"either":1}
,"either":{"disconnected":1}
,"timed":{"terracotta":1}
,"server":{"example":1,"stop":1,"verify":1,"again":1,"using":1,"nonstop":1,"unreachable":1,"rejoin":1}
,"demonstrates":{"nonstop":1}
,"features":{"bigmemory":1}
,"bigmemory":{"max":1,"=manager.getehcache":1}
,"max":{"loading":1}
,"loading":{"configuration":1}
,"below":{"scripts":1}
,"scripts":{"provided":1}
,"provided":{"start":1}
,"start":{"run":1,"server":1}
,"run":{"server":1}
,"stop":{"server":1}
,"verify":{"nonstop":1}
,"working":{"start":1,"****\u0022)":1}
,"again":{"watch":1}
,"watch":{"rejoin":1}
,"action":{"configuration":1}
,"managerconfig":{"=new":1}
,"=new":{"configuration":1,"person":1}
,".terracotta":{"(new":1}
,"(new":{"terracottaclientconfiguration":1,"cacheconfiguration":1,"persistenceconfiguration":1,"terracottaconfiguration":1,"nonstopconfiguration":1,"element":1}
,"terracottaclientconfiguration":{".url":1}
,".url":{"localhost:9510":1}
,"localhost:9510":{".rejoin":1}
,".rejoin":{"(true))":1}
,"(true))":{".cache":1}
,".cache":{"(new":1}
,"cacheconfiguration":{".name":1}
,".name":{"nonstop-sample":1}
,"nonstop-sample":{".persistence":1,"try":1}
,".persistence":{"(new":1}
,"persistenceconfiguration":{".strategy":1}
,".strategy":{"(distributed))":1}
,"(distributed))":{".maxbyteslocalheap":1}
,".maxbyteslocalheap":{"(128":1}
,"(128":{"memoryunit.megabytes)":1}
,"memoryunit.megabytes)":{".maxbyteslocaloffheap":1}
,".maxbyteslocaloffheap":{"memoryunit.gigabytes)":1}
,"memoryunit.gigabytes)":{".terracotta":1}
,"terracottaconfiguration":{".nonstop":1}
,".nonstop":{"(new":1}
,"nonstopconfiguration":{".immediatetimeout":1}
,".immediatetimeout":{"(false)":1}
,"(false)":{".timeoutmillis":1}
,".timeoutmillis":{"(10000)":1}
,"(10000)":{".enabled":1}
,".enabled":{"(true)":1}
,"(true)":{"cachemanager":1,"{bigmemory.get":1}
,"cachemanager":{"manager":1}
,"manager":{"=cachemanager.create":1}
,"=cachemanager.create":{"(managerconfig)":1}
,"(managerconfig)":{"ehcache":1}
,"ehcache":{"bigmemory":1}
,"=manager.getehcache":{"nonstop-sample":1}
,"try":{"{system.out.println":1,"{while":1}
,"{system.out.println":{"(\u0022****put":1}
,"(\u0022****put":{"key":1}
,"key":{"\u002Fvalue":1}
,"\u002Fvalue":{"timdoe":1}
,"timdoe":{"****\u0022)":1,"=new":1}
,"****\u0022)":{"final":1,"system.out.println":1,"try":1,"system.out":1,"boolean":1,"finally":1}
,"final":{"person":1}
,"person":{"timdoe":1,"tim":1}
,"tim":{"doe":1}
,"doe":{"person.gender.male":1}
,"person.gender.male":{"eck":1}
,"eck":{"street":1}
,"street":{"san":1}
,"san":{"mateo":1}
,"mateo":{"bigmemory.put":1}
,"bigmemory.put":{"(new":1}
,"element":{"timdoe))":1}
,"timdoe))":{"system.out.println":1}
,"system.out.println":{"(\u0022****get":1,"(bigmemory.get":1}
,"(\u0022****get":{"key":1}
,"(bigmemory.get":{"\u0022))":1}
,"\u0022))":{"waitforinput":1}
,"waitforinput":{"system.out":1}
,"system.out":{".println":1}
,".println":{"(\u0022****now":1,"(\u0022****server":1}
,"(\u0022****now":{"kill":1,"restart":1}
,"kill":{"server":1}
,"using":{"stop-sample-server.bat":1,"start-sample-server.bat":1}
,"stop-sample-server.bat":{"windows":1}
,"windows":{"stop-sample-server.sh":1,"start-sample-server.sh":1}
,"stop-sample-server.sh":{"otherwise":1}
,"otherwise":{"****\u0022)":1}
,"{while":{"(true)":1}
,"{bigmemory.get":{"catch":1,"\u002F\u002Fif":1}
,"catch":{"(nonstopcacheexception":1}
,"(nonstopcacheexception":{"{system.out":1,"system.out":1}
,"{system.out":{".println":1}
,"(\u0022****server":{"unreachable":1,"reachable":1}
,"unreachable":{"-nonstopexception":1,"exception":1}
,"-nonstopexception":{"received":1}
,"received":{"trying":1}
,"trying":{"server":1}
,"restart":{"server":1}
,"start-sample-server.bat":{"windows":1}
,"start-sample-server.sh":{"otherwise":1}
,"boolean":{"serverstart":1}
,"serverstart":{"=false":1,"=true":1}
,"=false":{"(serverstart":1}
,"(serverstart":{"==false)":1}
,"==false)":{"{try":1}
,"{try":{"{bigmemory.get":1}
,"\u002F\u002Fif":{"server":1}
,"exception":{"thrown":1}
,"thrown":{"doing":1}
,"doing":{"serverstart":1}
,"=true":{"catch":1}
,"reachable":{"-no":1}
,"-no":{"nonstopexception":1}
,"nonstopexception":{"received":1}
,"finally":{"{if":1}
,"{if":{"(manager":1}
,"(manager":{"!=null)":1}
,"!=null)":{"manager.shutdown":1}
}
;Search.control.loadWordPairs(pairs);
