var pairs =
{
"transaction":{"support":1,"context":1,"modes":1,"api":1}
,"support":{"<<this":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"bigmemory":1,"discussion":1,"doc":1}
,"product":{"docs.>>":1}
,"docs.>>":{"bmm":1}
,"bigmemory":{"max":1}
,"max":{"supports":1,"<<ffc-currently":1}
,"supports":{"global":1}
,"global":{"transactions":1}
,"transactions":{"xa_strict":1,"local":1,"operations":1,"return":1,"case":1,"even":1}
,"xa_strict":{"modes":1,"similar":1}
,"modes":{"local":1,"related":1,"methods":1,"transactional":1,"enable":1}
,"local":{"transactions":1,"mode":1,"jvm":1,"want":1}
,"mode":{"bmm":1,"need":1,"useful":1,"cache":1,"cached":1,"afford":1}
,"discussion":{"modes":1}
,"related":{"topics":1}
,"topics":{"working":1}
,"working":{"transactional":1}
,"transactional":{"caches":1,"cache":1,"methods":1,"context":1,"including":1,"modes":1}
,"caches":{"configuration":1,"data":1,"performed":1,"atomically":1}
,"configuration":{"guide":1}
,"guide":{"bigmemory":1,"need":1}
,"<<ffc-currently":{"working":1}
,"cache":{"bmm":1,"enabled":1,"either":1,"transactional":1,"contains":1,"data":1}
,"doc":{"probably":1,"added":1}
,"probably":{"versions":1,"section":1}
,"versions":{"probably":1}
,"section":{"config":1,"appears":1}
,"config":{"guide":1}
,"need":{"look":1,"rewrite":1,"update":1,"strict":1}
,"look":{"future":1}
,"future":{"release":1}
,"release":{"nothing":1}
,"nothing":{"cache":1}
,"enabled":{"transactions":1}
,"operations":{"happen":1,"caches":1}
,"happen":{"within":1}
,"within":{"transaction":1,"outside":1}
,"context":{"otherwise":1,"run":1,"change":1}
,"otherwise":{"transactionexception":1}
,"transactionexception":{"thrown":1}
,"thrown":{"transactional":1}
,"methods":{"bigm":1,"require":1,"work":1}
,"bigm":{"<<ffc-this":1,"doc":1,"bigmemory\u2019s":1}
,"<<ffc-this":{"section":1}
,"appears":{"bigm":1}
,"added":{"ehcache":1}
,"ehcache":{"?>>":1,"read_committed":1,"work":1}
,"?>>":{"following":1}
,"following":{"methods":1,"items":1}
,"require":{"transactional":1}
,"run":{"put":1}
,"put":{"getquiet":1,"remove":1}
,"getquiet":{"remove":1}
,"remove":{"getkeys":1,"putwithwriter":1}
,"getkeys":{"getsize":1}
,"getsize":{"containskey":1}
,"containskey":{"removeall":1}
,"removeall":{"putwithwriter":1,"mutating":1}
,"putwithwriter":{"removewithwriter":1}
,"removewithwriter":{"putifabsent":1,"removeall":1}
,"putifabsent":{"removeelement":1}
,"removeelement":{"replace":1}
,"replace":{"list":1}
,"list":{"applies":1}
,"applies":{"transaction":1}
,"work":{"non-transactionally":1,"xaresource":1}
,"non-transactionally":{"called":1}
,"called":{"transactional":1,"until":1}
,"either":{"within":1}
,"outside":{"transactional":1}
,"change":{"visibility":1}
,"visibility":{"isolation":1}
,"isolation":{"level":1}
,"level":{"offered":1}
,"offered":{"bigm":1}
,"bigmemory\u2019s":{"ehcache":1}
,"read_committed":{"ehcache":1}
,"xaresource":{"case":1}
,"case":{"full":1,"crash":1}
,"full":{"two-phase":1}
,"two-phase":{"commit":1}
,"commit":{"supported":1,"called":1,"mode":1}
,"supported":{"specifically":1}
,"specifically":{"mutating":1}
,"mutating":{"changes":1}
,"changes":{"cache":1,"visible":1,"across":1,"committed":1}
,"including":{"put":1}
,"visible":{"transactions":1}
,"jvm":{"across":1}
,"across":{"cluster":1,"multiple":1}
,"cluster":{"until":1}
,"until":{"commit":1,"reads":1}
,"reads":{"cache.get":1,"block":1}
,"cache.get":{"transactions":1}
,"return":{"old":1}
,"old":{"copy":1}
,"copy":{"reads":1}
,"block":{"transactional":1}
,"enable":{"perform":1}
,"perform":{"atomic":1}
,"atomic":{"operations":1,"control":1}
,"data":{"stores":1,"calculated":1,"mode":1,"data":1,"sync":1,"brief":1}
,"stores":{"<<ffc-we":1,"dbms":1}
,"<<ffc-we":{"need":1}
,"rewrite":{"following":1}
,"items":{"parallel.>>":1}
,"parallel.>>":{"local":1}
,"want":{"changes":1,"atomic":1}
,"multiple":{"caches":1}
,"performed":{"atomically":1}
,"atomically":{"mode":1,"changes":1}
,"update":{"caches":1}
,"committed":{"rolled":1}
,"rolled":{"back":1}
,"back":{"using":1}
,"using":{"straightforward":1}
,"straightforward":{"api":1}
,"api":{"mode":1,"java":1,"without":1}
,"useful":{"cache":1}
,"contains":{"data":1}
,"calculated":{"cached":1}
,"cached":{"data":1}
,"dbms":{"jms":1}
,"jms":{"want":1}
,"control":{"jta":1}
,"jta":{"api":1}
,"java":{"transaction":1}
,"without":{"overhead":1}
,"overhead":{"full":1}
,"sync":{"resources":1}
,"resources":{"participating":1}
,"participating":{"transactions":1}
,"crash":{"therefore":1,"however":1}
,"therefore":{"mode":1}
,"afford":{"live":1}
,"live":{"stale":1}
,"stale":{"data":1}
,"brief":{"period":1}
,"period":{"time":1}
,"time":{"xa_strict":1}
,"similar":{"need":1}
,"strict":{"disaster":1}
,"disaster":{"recovery":1}
,"recovery":{"guarantees":1}
,"guarantees":{"mode":1}
,"even":{"case":1}
,"however":{"extra":1}
,"extra":{"safety":1}
,"safety":{"performance":1}
,"performance":{"decreases":1}
,"decreases":{"significantly":1}
}
;Search.control.loadWordPairs(pairs);
