var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fmirror-group":{"mirror":1}
,"mirror":{"group":1,"(or":1,"server":1}
,"group":{"stripe":1,"active":1,"configurations":1}
,"stripe":{"tsa":1,"having":1,"active":1,"<mirror-group>":1}
,"tsa":{"consisting":1,"<servers>":1}
,"consisting":{"active":1}
,"active":{"server":1,"(the":1,"server\u0027s":1,"mirror":1}
,"server":{"mirror":1,"<servers>":1,"rest":1,"array":1}
,"(or":{"backup)":1}
,"backup)":{"servers":1}
,"servers":{"configuration":1,"assume":1,"become":1,"split":1}
,"configuration":{"<mirror-group>":1}
,"<mirror-group>":{"element":1,"configurations":1}
,"element":{"produce":1}
,"produce":{"one-stripe":1}
,"one-stripe":{"tsa":1}
,"<servers>":{"<server":1,"<mirror-group":1,"may":1,"work":1,"mirror":1}
,"<server":{"name=\u0022":1}
,"name=\u0022":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<server":1,"<\u002Fservers>":1,"<\u002Fmirror-group>":1}
,"<\u002Fservers>":{"named":1,"stripe":1}
,"named":{"servers":1}
,"assume":{"role":1}
,"role":{"active":1}
,"(the":{"started":1}
,"started":{"first":1}
,"first":{"wins":1}
,"wins":{"election)":1}
,"election)":{"remaining":1}
,"remaining":{"servers":1}
,"become":{"mirrors":1}
,"mirrors":{"note":1,"sufficient":1,"create":1}
,"note":{"typical":1}
,"typical":{"stripe":1}
,"having":{"two":1}
,"two":{"mirrors":1,"stripes":1}
,"sufficient":{"less":1}
,"less":{"taxing":1}
,"taxing":{"active":1}
,"server\u0027s":{"resources":1}
,"resources":{"(as":1}
,"(as":{"needs":1}
,"needs":{"sync":1}
,"sync":{"mirror)":1}
,"mirror)":{"following":1}
,"following":{"example":1}
,"example":{"shows":1}
,"shows":{"servers":1}
,"split":{"two":1}
,"stripes":{"<servers>":1}
,"<mirror-group":{"group-name=\u0022":1}
,"group-name=\u0022":{"team1":1,"team2":1}
,"team1":{"<server":1}
,"<\u002Fmirror-group>":{"<mirror-group":1,"<\u002Fservers>":1}
,"team2":{"<server":1}
,"may":{"either":1}
,"either":{"<server>":1}
,"<server>":{"<mirror-group>":1,"configurations":1}
,"configurations":{"<server>":1,"directly":1,"include":1,"examples":1}
,"directly":{"<servers>":1}
,"work":{"together":1}
,"together":{"mirror":1}
,"rest":{"mirrors":1}
,"create":{"stripe":1}
,"include":{"<server>":1}
,"examples":{"information":1}
,"information":{"configuring":1}
,"configuring":{"terracotta":1}
,"terracotta":{"server":1}
}
;Search.control.loadWordPairs(pairs);
