var pairs =
{
"pinning":{"data":1,"expired":1,"gives":1,"depending":1,"configuration":1,"entire":1,"element":1,"accomplished":1,"cache":1,"option":1,"pinning":1,"setting":1,"configured":1,"used":1,"bmm":1,"achieved":1,"lost":1}
,"data":{"<<this":1,"evicted":1,"remain":1,"pinned":1,"stored":1,"(such":1,"heap":1,"removed":1,"remaining":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"localmemory":1,"pinning":1,"terracotta":1}
,"product":{"docs.>>":1}
,"docs.>>":{"without":1}
,"without":{"pinning":1}
,"expired":{"cache":1,"type":1}
,"cache":{"entries":1,"described":1,"tier":1,"data":1,"configured":1,"sizing":1,"size":1,"pinning":1,"eligible":1,"potentially":1,"maxentrieslocalheap":1,"bulk":1,"unpin":1,"specific":1,"using":1,"cache.removeall":1,"itself":1,"removed":1}
,"entries":{"flushed":1,"entire":1,"evicted":1,"<cache":1,"heap":1,"surpasses":1,"longer":1,"clear":1,"removed":1}
,"flushed":{"eventually":1,"evicted":1}
,"eventually":{"evicted":1}
,"evicted":{"even":1,"resource":1,"bigmemory":1,"bmm":1,"event":1,"expired":1,"example":1}
,"even":{"non-expired":1}
,"non-expired":{"elements":1}
,"elements":{"flushed":1,"faulted":1,"resident":1}
,"resource":{"limitations":1,"constraints":1}
,"limitations":{"reached":1}
,"reached":{"pinning":1}
,"gives":{"per-cache":1}
,"per-cache":{"control":1}
,"control":{"whether":1}
,"whether":{"data":1,"pinning":1}
,"bigmemory":{"max":1,"products.)":1}
,"max":{"data":1}
,"remain":{"memory":1}
,"memory":{"pinned":1,"store":1,"unless":1,"distributed":1}
,"pinned":{"cannot":1,"using":1,"cache":1,"memory":1,"caches":1,"unless":1,"data":1,"entries":1,"bmm":1}
,"cannot":{"pin":1,"evicted":1,"cause":1}
,"pin":{"individual":1,"entries":1}
,"individual":{"entries":1}
,"entire":{"cache":1,"caches":1}
,"described":{"following":1}
,"following":{"topics":1,"values":1,"cache":1}
,"topics":{"two":1}
,"two":{"types":1}
,"types":{"pinning":1}
,"depending":{"upon":1}
,"upon":{"whether":1,"pinning":1}
,"configuration":{"precedence":1,"element":1,"cache":1,"depends":1,"(off-heap":1,"reinstated":1,"file":1}
,"precedence":{"resource":1}
,"constraints":{"around":1}
,"around":{"configuring":1}
,"configuring":{"pinning":1}
,"caches":{"pinned":1,"grow":1}
,"using":{"pinning":1,"cache.remove":1}
,"element":{"ehcache":1,"required":1}
,"ehcache":{"configuration":1,"client":1}
,"required":{"attribute":1}
,"attribute":{"(store)":1,"either":1}
,"(store)":{"specify":1}
,"specify":{"pinning":1}
,"accomplished":{"store":1}
,"store":{"attribute":1,"off-heap":1,"entries":1}
,"either":{"following":1}
,"values":{"incache":1}
,"incache":{"data":1,"<\u002Fcache>":1,"pinning":1}
,"tier":{"cache":1,"chosen":1,"becomes":1}
,"stored":{"tier":1}
,"chosen":{"based":1}
,"based":{"performance-enhancing":1}
,"performance-enhancing":{"efficiency":1}
,"efficiency":{"algorithms":1}
,"algorithms":{"unexpired":1}
,"unexpired":{"entries":1}
,"localmemory":{"data":1,"<\u002Fcache>":1,"pinning":1}
,"off-heap":{"store":1,"<cache":1,"memory":1}
,"event":{"store\u0027s":1}
,"store\u0027s":{"configured":1}
,"configured":{"size":1,"pin":1,"cache":1}
,"size":{"exceeded":1,"elements":1,"caches":1,"takes":1,"entries":1}
,"exceeded":{"updated":1}
,"updated":{"copies":1}
,"copies":{"invalidated":1}
,"invalidated":{"elements":1}
,"faulted":{"server":1,"back":1}
,"server":{"behavior":1,"array":1}
,"behavior":{"override":1}
,"override":{"setting":1,"pinning":1}
,"setting":{"terracotta":1,"takes":1,"localmemory":1,"exists":1}
,"terracotta":{"property":1,"bigmemory":1,"server":1}
,"property":{"l1.servermapmanager.faultinvalidatedpinnedentries":1}
,"l1.servermapmanager.faultinvalidatedpinnedentries":{"false":1}
,"false":{"example":1}
,"example":{"following":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"cache1":1,"cache2":1,"mycache":1}
,"cache1":{"<pinning":1}
,"<pinning":{"store=\u0022":1}
,"store=\u0022":{"incache":1,"localmemory":1}
,"<\u002Fcache>":{"following":1,"pinning":1,"scope":1}
,"heap":{"bigm":1}
,"bigm":{"off-heap":1}
,"cache2":{"<pinning":1}
,"sizing":{"interaction":1,"configuration":1}
,"interaction":{"pinning":1}
,"depends":{"upon":1}
,"option":{"used":1,"cannot":1}
,"used":{"incache":1,"optimization":1}
,"takes":{"priority":1}
,"priority":{"configured":1,"pinning":1}
,"resident":{"cache":1}
,"type":{"pinned":1}
,"eligible":{"eviction":1}
,"eviction":{"maxentriesincache":1}
,"maxentriesincache":{"configured":1}
,"potentially":{"pinned":1}
,"grow":{"unlimited":1}
,"unlimited":{"size":1}
,"unless":{"designed":1,"until":1}
,"designed":{"hold":1}
,"hold":{"limited":1}
,"limited":{"amount":1}
,"amount":{"data":1}
,"(such":{"reference":1}
,"reference":{"data)":1}
,"data)":{"usage":1}
,"usage":{"expiration":1}
,"expiration":{"characteristics":1}
,"characteristics":{"understood":1}
,"understood":{"enough":1}
,"enough":{"conclude":1}
,"conclude":{"cannot":1}
,"cause":{"errors":1}
,"errors":{"localmemory":1}
,"optimization":{"keep":1}
,"keep":{"data":1}
,"until":{"tier":1}
,"becomes":{"full":1}
,"full":{"number":1}
,"number":{"entries":1}
,"surpasses":{"configured":1}
,"maxentrieslocalheap":{"maxbyteslocaloffheap":1}
,"maxbyteslocaloffheap":{"settings":1}
,"settings":{"override":1}
,"(off-heap":{"storage":1}
,"storage":{"available":1}
,"available":{"terracotta":1}
,"products.)":{"<cache":1}
,"mycache":{"maxentrieslocalheap=\u0022":1}
,"maxentrieslocalheap=\u0022":{"10000":1}
,"10000":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"<pinning":1}
,"scope":{"pinning":1}
,"exists":{"local":1}
,"local":{"ehcache":1}
,"client":{"(l1)":1}
,"(l1)":{"memory":1}
,"distributed":{"cluster":1}
,"cluster":{"case":1,"cache":1}
,"case":{"pinned":1}
,"bulk":{"loaded":1}
,"loaded":{"pinned":1}
,"removed":{"faulted":1,"cache":1,"(cache.dispose":1,"locally":1,"bmm":1}
,"back":{"terracotta":1}
,"array":{"pinning":1,"disk":1}
,"achieved":{"programmatically":1}
,"programmatically":{"persisted":1}
,"persisted":{"restart":1}
,"restart":{"pinned":1}
,"longer":{"pinned":1}
,"lost":{"rejoins":1}
,"rejoins":{"cluster":1}
,"reinstated":{"configuration":1}
,"file":{"explicitly":1}
,"explicitly":{"removing":1}
,"removing":{"data":1}
,"unpin":{"cache\u0027s":1}
,"cache\u0027s":{"pinned":1}
,"clear":{"cache":1}
,"specific":{"entries":1}
,"cache.remove":{"empty":1}
,"empty":{"cache":1}
,"cache.removeall":{"cache":1}
,"itself":{"removed":1}
,"(cache.dispose":{"cachemanager.removecache":1}
,"cachemanager.removecache":{"())":1}
,"())":{"data":1}
,"remaining":{"cache":1,"data":1}
,"locally":{"however":1}
,"however":{"remaining":1}
,"disk":{"(if":1}
,"(if":{"localrestartable)":1}
}
;Search.control.loadWordPairs(pairs);
