var pairs =
{
"cache":{"events":1,"event":1}
,"events":{"configuration":1,"puts":1,"local":1,"detected":1,"nodes":1,"example":1,"<cache":1,"terracotta":1}
,"configuration":{"<cache>":1,"allows":1}
,"<cache>":{"sub-element":1}
,"sub-element":{"<cacheeventlistenerfactory>":1}
,"<cacheeventlistenerfactory>":{"registers":1,"default":1}
,"registers":{"listeners":1}
,"listeners":{"cache":1,"scope":1,"type":1,"developers":1}
,"puts":{"updates":1}
,"updates":{"notification":1}
,"notification":{"scope":1}
,"scope":{"controlled":1,"includes":1}
,"controlled":{"attribute":1}
,"attribute":{"listenfor":1,"following":1,"<cacheeventlistenerfactory>":1}
,"listenfor":{"attribute":1}
,"following":{"values":1,"configuration":1}
,"values":{"local":1}
,"local":{"listen":1,"node":1,"events":1,"(default)":1,"remote":1}
,"listen":{"events":1}
,"node":{"remote":1}
,"remote":{"events":1,"listen":1,"nodes":1}
,"detected":{"remote":1,"local":1}
,"nodes":{"local":1,"order":1,"terracotta":1}
,"(default)":{"listen":1}
,"order":{"cache":1}
,"terracotta":{"cluster":1}
,"cluster":{"event":1,"information":1,"cache":1}
,"event":{"listeners":1}
,"includes":{"remote":1}
,"example":{"following":1}
,"allows":{"listeners":1}
,"type":{"mycachelistener":1}
,"mycachelistener":{"detect":1}
,"detect":{"local":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"mycache":1}
,"mycache":{"<!--not":1}
,"<!--not":{"defining":1}
,"defining":{"listenfor":1}
,"default":{"equivalent":1}
,"equivalent":{"listenfor=\u0022":1}
,"listenfor=\u0022":{"-->":1}
,"-->":{"<cacheeventlistenerfactory":1}
,"<cacheeventlistenerfactory":{"class=\u0022":1}
,"class=\u0022":{"net.sf.ehcache.event.terracottacacheeventreplicationfactory":1}
,"net.sf.ehcache.event.terracottacacheeventreplicationfactory":{"<terracotta":1,"factory":1}
,"<terracotta":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"net.sf.ehcache.event.terracottacacheeventreplicationfactory":1}
,"factory":{"class":1}
,"class":{"enable":1}
,"enable":{"cluster-wide":1}
,"cluster-wide":{"cache-event":1}
,"cache-event":{"broadcasts":1}
,"broadcasts":{"terracotta":1}
,"information":{"cache":1}
,"developers":{"guide":1}
,"guide":{"bigmemory":1}
,"bigmemory":{"max":1}
}
;Search.control.loadWordPairs(pairs);
