var pairs =
{
"basic":{"connection":1}
,"connection":{"security":1,"attempts":1,"adding":1}
,"security":{"secure":1,"environments":1,"guide":1,"(authentication":1}
,"secure":{"connections":1}
,"connections":{"tms":1}
,"tms":{"managed":1,"exposed":1,"fully":1,"truststore":1,"following":1,"create":1,"location":1,"enter":1,"note":1}
,"managed":{"agents":1,"agent":1,"agent\u0027s":1}
,"agents":{"using":1,"managed":1,"attack":1,"recommended":1,"described":1,"storing":1,"running":1,"agent":1}
,"using":{"built-in":1,"certificate":1,"command":1,"system":1,"agent\u0027s":1}
,"built-in":{"hash-based":1}
,"hash-based":{"message":1}
,"message":{"authentication":1}
,"authentication":{"scheme":1,"feature":1}
,"scheme":{"digital":1}
,"digital":{"certificates":1}
,"certificates":{"known":1,"keystore":1,"chain":1,"import":1}
,"known":{"identity":1}
,"identity":{"assertion":1}
,"assertion":{"(ia)":1,"complete":1,"described":1,"create":1,"configure":1,"trust":1}
,"(ia)":{"level":1,"terracotta":1}
,"level":{"security":1}
,"environments":{"tms":1}
,"exposed":{"unwanted":1}
,"unwanted":{"connection":1}
,"attempts":{"rogue":1}
,"rogue":{"agents":1,"tms":1}
,"attack":{"rogue":1}
,"fully":{"secure":1}
,"recommended":{"ssl":1}
,"ssl":{"used":1,"connection":1,"identity":1}
,"used":{"encryption":1,"connect":1}
,"encryption":{"information":1}
,"information":{"adding":1}
,"adding":{"ssl":1,"securityservicelocation":1}
,"complete":{"following":1}
,"following":{"steps":1,"keytool":1,"ways":1,"example":1,"procedures":1,"script":1}
,"steps":{"truststore":1}
,"truststore":{"described":1,"configure":1,"tms":1,"containing":1,"creating":1,"available":1,"jvm":1}
,"described":{"setting":1,"configuring":1,"creating":1}
,"setting":{"truststore":1}
,"configure":{"identity":1,"terracotta":1}
,"configuring":{"identity":1}
,"create":{"shared":1,"password":1}
,"shared":{"secret":1,"tms":1}
,"secret":{"tms":1,"setting":1,"create":1,"assertion":1,"choice":1,"enter":1,"?>>":1,"managed":1,"terracotta":1,"associated":1,"matches":1}
,"creating":{"shared":1,"shown":1}
,"containing":{"public-key":1}
,"public-key":{"certificate":1}
,"certificate":{"every":1,"authority":1}
,"every":{"agent":1}
,"agent":{"connects":1,"using":1,"keystore":1,"value":1,"example":1,"keychain":1}
,"connects":{"using":1}
,"authority":{"(which":1}
,"(which":{"provides":1}
,"provides":{"public":1}
,"public":{"keys)":1,"keys":1}
,"keys)":{"export":1}
,"export":{"public":1}
,"keys":{"self-signed":1,"tms":1,"default":1}
,"self-signed":{"certificates":1}
,"keystore":{"agent":1,"explorer":1,"examples":1}
,"command":{"similar":1,"line":1}
,"similar":{"following":1}
,"keytool":{"-export":1,"-import":1,"utility":1,"want":1}
,"-export":{"-alias":1}
,"-alias":{"myagent":1}
,"myagent":{"-keystore":1,"-file":1}
,"-keystore":{"keystore-file.jks":1}
,"keystore-file.jks":{"\u005C-file":1}
,"\u005C-file":{"myagentcert.cert":1}
,"myagentcert.cert":{"import":1,"\u005C-keystore":1}
,"import":{"keys":1,"refer":1,"public":1}
,"shown":{"(if":1}
,"(if":{"already":1}
,"already":{"exist)":1,"exist":1,"exists":1}
,"exist)":{"keytool":1}
,"-import":{"-alias":1}
,"-file":{"myagentcert.cert":1}
,"\u005C-keystore":{"truststore.jks":1}
,"truststore.jks":{"keytool":1}
,"utility":{"maintain":1,"alternative":1}
,"maintain":{"additional":1}
,"additional":{"certificates":1}
,"chain":{"trust":1}
,"trust":{"file":1,"tms":1}
,"file":{"cacerts":1,"scripts":1,"<user_home>\u002F.tc\u002Fmgmt\u002Fkeychain":1,"remain":1,"shared":1,".\u002Fkeychain.sh":1,"already":1,"enter":1,"terracotta":1,"successfully":1}
,"cacerts":{"wish":1,"file)":1}
,"wish":{"additional":1,"associate":1}
,"refer":{"option":1}
,"option":{"-trustcacerts":1}
,"-trustcacerts":{"documentation":1}
,"documentation":{"keytool":1}
,"alternative":{"using":1}
,"line":{"tool":1}
,"tool":{"keytool":1,"keystore":1}
,"want":{"try":1}
,"try":{"open":1}
,"open":{"source":1,"keychain":1}
,"source":{"graphical":1}
,"graphical":{"tool":1}
,"explorer":{"available":1}
,"available":{"http:\u002F\u002Fwww.keystore-explorer.org\u002Findex.html":1,"tms":1}
,"http:\u002F\u002Fwww.keystore-explorer.org\u002Findex.html":{"managed":1}
,"examples":{"bigmemory":1}
,"bigmemory":{"max":1,"procedure":1}
,"max":{"security":1}
,"guide":{"<<ffc-give":1,"examples.>>":1,"configure":1}
,"<<ffc-give":{"users":1}
,"users":{"hint":1}
,"hint":{"look":1}
,"look":{"guide":1}
,"examples.>>":{"truststore":1}
,"ways":{"${user.home}\u002F.tc\u002Fmgmt\u002Ftms-truststore":1}
,"${user.home}\u002F.tc\u002Fmgmt\u002Ftms-truststore":{"location":1}
,"location":{"configured":1,"tms-related":1,"prompted":1}
,"configured":{"system":1}
,"system":{"property":1}
,"property":{"javax.net.ssl.truststore":1,"com.tc.management.config.directory":1}
,"javax.net.ssl.truststore":{"alternatively":1}
,"alternatively":{"import":1}
,"default":{"truststore":1,"location":1}
,"jvm":{"(typically":1}
,"(typically":{"cacerts":1}
,"file)":{"different":1}
,"different":{"default":1}
,"tms-related":{"files":1}
,"files":{"required":1}
,"required":{"using":1,"following":1}
,"com.tc.management.config.directory":{"configuring":1}
,"terracotta":{"server":1,"client":1,"keychain":1,"management":1}
,"server":{"array":1}
,"array":{"bigmemory":1}
,"client":{"enable":1,"creating":1,"keychain":1}
,"enable":{"security":1,"value":1}
,"(authentication":{"ia)":1}
,"ia)":{"rest":1}
,"rest":{"service":1}
,"service":{"adding":1}
,"securityservicelocation":{"attribute":1,"authentication":1}
,"attribute":{"managementrestservice":1}
,"managementrestservice":{"element":1}
,"element":{"managed":1}
,"agent\u0027s":{"configuration":1,"uri":1}
,"configuration":{"following":1}
,"example":{"ehcache":1,"above":1,".\u002Fadd-tc-agent.sh":1}
,"ehcache":{"<ehcache":1}
,"<ehcache":{"<managementrestservice":1}
,"<managementrestservice":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"securityservicelocation=\u0022":1}
,"securityservicelocation=\u0022":{"http:\u002F\u002Flocalhost:9889\u002Ftmc\u002Fapi\u002Fassertidentity":1}
,"http:\u002F\u002Flocalhost:9889\u002Ftmc\u002Fapi\u002Fassertidentity":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"securityservicelocation":1}
,"feature":{"disabled":1}
,"disabled":{"enable":1}
,"value":{"uri":1,"correspond":1}
,"uri":{"used":1,"bigmemory":1,"agent":1,"tmc":1,"script":1}
,"connect":{"tmc":1,"given":1}
,"tmc":{"\u002Ftmc\u002Fapi\u002Fassertidentity":1,"uri":1,"connect":1,"\u002Ftc-management-api":1}
,"\u002Ftmc\u002Fapi\u002Fassertidentity":{"appended":1}
,"appended":{"example":1,"named":1}
,"above":{"http:\u002F\u002Flocalhost:9889":1}
,"http:\u002F\u002Flocalhost:9889":{"tmc":1}
,"procedure":{"terracotta":1}
,"password":{"(or":1,"e.g":1,"wish":1,"http:\u002F\u002Fmyhost:9889\u002Fsuccessfully":1}
,"(or":{"secret)":1}
,"secret)":{"shared":1}
,"storing":{"terracotta":1}
,"keychain":{"file":1,"entry":1,"entering":1}
,"scripts":{"required":1,"microsoft":1}
,"procedures":{"found":1}
,"found":{"${bigmemory_go_home}\u002Fmanagement-console\u002Fbin":1}
,"${bigmemory_go_home}\u002Fmanagement-console\u002Fbin":{"${bigmemory_max_home}\u002Ftools\u002Fmanagement-console\u002Fbin":1}
,"${bigmemory_max_home}\u002Ftools\u002Fmanagement-console\u002Fbin":{"equivalent":1}
,"equivalent":{".bat":1}
,".bat":{"scripts":1}
,"microsoft":{"windows":1}
,"windows":{"shared":1,"script":1}
,"running":{"following":1,"node":1}
,"script":{".\u002Fadd-tc-agent.sh":1,"automatically":1,"once":1,"saves":1}
,".\u002Fadd-tc-agent.sh":{"<agent-url>":1,"http:\u002F\u002Flocalhost:9888":1}
,"<agent-url>":{"<agent-url>":1,"uri":1}
,"correspond":{"exactly":1}
,"exactly":{"uri":1}
,"given":{"agent":1}
,"http:\u002F\u002Flocalhost:9888":{"add-tc-agent.bat":1}
,"add-tc-agent.bat":{"microsoft":1}
,"automatically":{"creates":1}
,"creates":{"terracotta":1}
,"<user_home>\u002F.tc\u002Fmgmt\u002Fkeychain":{"already":1}
,"exist":{"move":1}
,"move":{"delete":1}
,"delete":{"keychain":1}
,"remain":{"accessible":1}
,"accessible":{"tms":1}
,"prompted":{"enter":1}
,"enter":{"shared":1,"need":1,"again":1,"master":1,"password":1,"match":1}
,"choice":{"sure":1}
,"sure":{"remember":1}
,"remember":{"secret":1}
,"need":{"enter":1}
,"again":{"later":1}
,"later":{"step":1}
,"step":{"<<ffc-shouldn\u2019t":1}
,"<<ffc-shouldn\u2019t":{"provide":1}
,"provide":{"requirements\u002Fconstraints":1}
,"requirements\u002Fconstraints":{"regarding":1}
,"regarding":{"password":1}
,"e.g":{"spaces":1}
,"spaces":{"allowed":1}
,"allowed":{"pass":1}
,"pass":{"phrases":1}
,"phrases":{"allow":1}
,"allow":{"passwords":1}
,"passwords":{"type":1}
,"type":{"shared":1}
,"?>>":{"run":1}
,"run":{"add-tc-agent":1}
,"add-tc-agent":{"script":1}
,"once":{"agent":1}
,"saves":{"entries":1}
,"entries":{"keychain":1}
,"entry":{"access":1}
,"access":{"shared":1}
,".\u002Fkeychain.sh":{"<user_home>\u002F.tc\u002Fmgmt\u002Fagentkeychainfile":1}
,"<user_home>\u002F.tc\u002Fmgmt\u002Fagentkeychainfile":{"\u005Chttp:\u002F\u002Fmyhost:9889\u002Ftc-management-api":1}
,"\u005Chttp:\u002F\u002Fmyhost:9889\u002Ftc-management-api":{"<tmc-url>":1}
,"<tmc-url>":{"uri":1}
,"\u002Ftc-management-api":{"appended":1}
,"named":{"keychain":1}
,"exists":{"node":1}
,"node":{"omit":1,"share":1}
,"omit":{"flag":1}
,"flag":{"agents":1}
,"share":{"keychain":1}
,"master":{"key":1}
,"key":{"keychain":1,"enter":1}
,"management":{"console":1}
,"console":{"-keychain":1}
,"-keychain":{"client":1}
,"successfully":{"created":1}
,"created":{"\u002Fpath\u002Fto\u002Fagentkeychainfile":1}
,"\u002Fpath\u002Fto\u002Fagentkeychainfile":{"open":1}
,"entering":{"master":1}
,"associated":{"tms":1}
,"associate":{"url":1}
,"url":{"password":1}
,"http:\u002F\u002Fmyhost:9889\u002Fsuccessfully":{"stored":1}
,"stored":{"secret":1,"tms":1}
,"match":{"entered":1}
,"entered":{"tms":1}
,"note":{"script\u0027s":1}
,"script\u0027s":{"success":1}
,"success":{"acknowledgment":1}
,"acknowledgment":{"confirm":1}
,"confirm":{"secret":1}
,"matches":{"stored":1}
}
;Search.control.loadWordPairs(pairs);
