var pairs =
{
"configuring":{"cachemanager":1}
,"cachemanager":{"cachemanager":1,"configuration":1,"name":1,"want":1,"check":1,"automatically":1,"terracotta":1,"manager":1,"(configuration)":1}
,"configuration":{"elements":1,"files":1,"cachemanagers":1,"specified":1,"configuration":1,"=new":1,".terracotta":1}
,"elements":{"attributes":1}
,"attributes":{"fully":1,"<ehcache>":1}
,"fully":{"described":1}
,"described":{"ehcache.xml":1}
,"ehcache.xml":{"reference":1,"attributes":1}
,"reference":{"file":1}
,"file":{"available":1}
,"available":{"kit":1}
,"kit":{"via":1}
,"via":{"ehcache.xml":1}
,"<ehcache>":{"name":1,"element":1}
,"name":{"optional":1,"cachemanager":1,"cache":1,"uniquely":1,"show":1,"attribute":1}
,"optional":{"name":1,"primarily":1,"boolean":1,"setting":1}
,"primarily":{"used":1}
,"used":{"documentation":1}
,"documentation":{"distinguish":1}
,"distinguish":{"terracotta":1}
,"terracotta":{"clustered":1,"clustering":1,"configuration":1}
,"clustered":{"cache":1,"caches":1,"memory":1}
,"cache":{"state":1,"name":1,"store":1,"named":1}
,"state":{"terracotta":1}
,"caches":{"combination":1}
,"combination":{"cachemanager":1}
,"uniquely":{"identify":1}
,"identify":{"particular":1,"specific":1}
,"particular":{"cache":1}
,"store":{"terracotta":1}
,"memory":{"name":1}
,"show":{"tmc":1}
,"tmc":{"employ":1,"provides":1}
,"employ":{"multiple":1}
,"multiple":{"ehcache":1}
,"ehcache":{"configuration":1,"internet":1}
,"files":{"name":1}
,"attribute":{"<ehcache>":1}
,"element":{"identify":1}
,"specific":{"cachemanagers":1}
,"cachemanagers":{"cluster":1,"configured":1}
,"cluster":{"tmc":1}
,"provides":{"menu":1}
,"menu":{"listing":1}
,"listing":{"names":1}
,"names":{"allowing":1}
,"allowing":{"choose":1}
,"choose":{"cachemanager":1}
,"want":{"view":1}
,"view":{"updatecheck":1}
,"updatecheck":{"optional":1}
,"boolean":{"flag":1}
,"flag":{"specifying":1}
,"specifying":{"whether":1}
,"whether":{"cachemanager":1}
,"check":{"new":1}
,"new":{"versions":1}
,"versions":{"ehcache":1}
,"internet":{"specified":1}
,"specified":{"updatecheck=\u0022":1,"url":1}
,"updatecheck=\u0022":{"true":1}
,"true":{"monitoring":1,"monitoring=\u0022":1}
,"monitoring":{"optional":1,"useful":1}
,"setting":{"determines":1}
,"determines":{"whether":1}
,"automatically":{"register":1}
,"register":{"sampledcachembean":1}
,"sampledcachembean":{"system":1}
,"system":{"mbean":1}
,"mbean":{"server":1,"allowed":1}
,"server":{"currently":1}
,"currently":{"monitoring":1}
,"useful":{"using":1}
,"using":{"terracotta":1}
,"clustering":{"autodetect":1,"registers":1}
,"autodetect":{"value":1,"<ehcache":1,"programmatic":1}
,"value":{"detects":1}
,"detects":{"presence":1}
,"presence":{"terracotta":1}
,"registers":{"mbean":1}
,"allowed":{"values":1}
,"values":{"default":1}
,"default":{"autodetect":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"ehcache.xsd":1}
,"ehcache.xsd":{"updatecheck=\u0022":1}
,"monitoring=\u0022":{"autodetect":1}
,"programmatic":{"configuration":1}
,"configured":{"programmatically":1}
,"programmatically":{"fluent":1}
,"fluent":{"api":1}
,"api":{"example":1}
,"example":{"below":1,"configuration":1,"100)":1}
,"below":{"creates":1}
,"creates":{"cachemanager":1,"defaultcache":1}
,"url":{"creates":1}
,"defaultcache":{"cache":1,"100))":1}
,"named":{"example":1}
,"=new":{"configuration":1,"cachemanager":1}
,".terracotta":{"(new":1}
,"(new":{"terracottaclientconfiguration":1,"cacheconfiguration":1,"terracottaconfiguration":1}
,"terracottaclientconfiguration":{".url":1}
,".url":{"localhost:9510":1}
,"localhost:9510":{"\u0022))":1}
,"\u0022))":{".defaultcache":1}
,".defaultcache":{"(new":1}
,"cacheconfiguration":{"defaultcache":1,"example":1}
,"100))":{".cache":1}
,".cache":{"(new":1}
,"100)":{".timetoidleseconds":1}
,".timetoidleseconds":{"(5)":1}
,"(5)":{".timetoliveseconds":1}
,".timetoliveseconds":{"(120)":1}
,"(120)":{".terracotta":1}
,"terracottaconfiguration":{"()))":1}
,"()))":{"cachemanager":1}
,"manager":{"=new":1}
}
;Search.control.loadWordPairs(pairs);
