var pairs =
{
"building":{"maven":1}
,"maven":{"dependency":1}
,"dependency":{"versions":1,"build":1,"<dependency>":1,"hibernate":1,"specific":1}
,"versions":{"vary":1,"need":1,"hibernate-ehcache":1}
,"vary":{"specific":1}
,"specific":{"kit":1,"version":1}
,"kit":{"intend":1,"guaranteed":1,"configure":1}
,"intend":{"kit":1}
,"guaranteed":{"contain":1}
,"contain":{"compatible":1}
,"compatible":{"artifacts":1}
,"artifacts":{"find":1}
,"find":{"artifact":1}
,"artifact":{"versions":1}
,"need":{"downloading":1}
,"downloading":{"kit":1}
,"configure":{"add":1}
,"add":{"following":1,"ehcache":1}
,"following":{"repository":1,"dependency":1}
,"repository":{"build":1}
,"build":{"(pom.xml)":1}
,"(pom.xml)":{"<repository>":1,"bigm":1}
,"<repository>":{"<id>":1}
,"<id>":{"terracotta-releases":1}
,"terracotta-releases":{"<\u002Fid>":1}
,"<\u002Fid>":{"<url>":1}
,"<url>":{"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":{"<\u002Furl>":1}
,"<\u002Furl>":{"<releases>":1}
,"<releases>":{"<enabled>":1}
,"<enabled>":{"true":1,"false":1}
,"true":{"<\u002Fenabled>":1}
,"<\u002Fenabled>":{"<\u002Freleases>":1,"<\u002Fsnapshots>":1}
,"<\u002Freleases>":{"<snapshots>":1}
,"<snapshots>":{"<enabled>":1}
,"false":{"<\u002Fenabled>":1}
,"<\u002Fsnapshots>":{"<\u002Frepository>":1}
,"<\u002Frepository>":{"configure":1}
,"ehcache":{"bigmemory":1,"check":1}
,"bigmemory":{"modules":1,"<\u002Fartifactid>":1}
,"modules":{"defined":1}
,"defined":{"following":1}
,"bigm":{"<dependency>":1}
,"<dependency>":{"<groupid>":1}
,"<groupid>":{"net.sf.ehcache":1,"org.terracotta.bigmemory":1,"org.hibernate":1}
,"net.sf.ehcache":{"<\u002Fgroupid>":1}
,"<\u002Fgroupid>":{"<artifactid>":1}
,"<artifactid>":{"ehcache-ee":1,"bigmemory":1,"hibernate-ehcache":1}
,"ehcache-ee":{"<\u002Fartifactid>":1}
,"<\u002Fartifactid>":{"<version>${ehcacheversion}":1,"<version>${bigmemoryversion}":1,"<version>${hibernateversion}":1,"<version>":1}
,"<version>${ehcacheversion}":{"<\u002Fversion>":1}
,"<\u002Fversion>":{"<\u002Fdependency>":1}
,"<\u002Fdependency>":{"<dependency>":1,"hibernate-ehcache":1,"example":1,"versions":1}
,"org.terracotta.bigmemory":{"<\u002Fgroupid>":1}
,"<version>${bigmemoryversion}":{"<\u002Fversion>":1}
,"hibernate-ehcache":{"integration":1,"<\u002Fartifactid>":1,"dependency":1,"pom":1}
,"integration":{"add":1,"dependency":1}
,"org.hibernate":{"<\u002Fgroupid>":1}
,"<version>${hibernateversion}":{"<\u002Fversion>":1}
,"example":{"hibernate-ehcache":1}
,"hibernate":{"4.0.0":1}
,"4.0.0":{"<dependency>":1,"<\u002Fversion>":1}
,"<version>":{"4.0.0":1}
,"version":{"ehcache":1}
,"check":{"hibernate-ehcache":1}
}
;Search.control.loadWordPairs(pairs);
