var pairs =
{
"preparing":{"maintenance":1}
,"maintenance":{"version":1}
,"version":{"upgrades":1,"terracotta":1}
,"upgrades":{"4.2":1}
,"4.2":{"attempting":1,"confirm":1}
,"attempting":{"perform":1}
,"perform":{"rolling":1}
,"rolling":{"upgrade":1}
,"upgrade":{"4.2":1,"intended":1}
,"confirm":{"following":1}
,"following":{"ensure":1}
,"ensure":{"terracotta":1,"upgrade":1}
,"terracotta":{"servers":1,"ensure":1,"run":1}
,"servers":{"clients":1,"cannot":1}
,"clients":{"target":1}
,"target":{"cluster":1}
,"cluster":{"running":1,"persistence":1,"recommend":1,"without":1}
,"running":{"version":1}
,"intended":{"version":1}
,"run":{"cluster":1}
,"persistence":{"enabled":1}
,"enabled":{"cluster":1}
,"recommend":{"back":1}
,"back":{"data":1}
,"data":{"folder":1}
,"folder":{"upgrading":1}
,"upgrading":{"described":1}
,"described":{"database":1}
,"database":{"backup":1}
,"backup":{"utility":1}
,"utility":{"(backup-data)":1}
,"(backup-data)":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
,"guide":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"non-persistent":1}
,"non-persistent":{"cluster":1}
,"without":{"mirror":1,"losing":1}
,"mirror":{"servers":1}
,"cannot":{"upgraded":1}
,"upgraded":{"without":1}
,"losing":{"data":1}
}
;Search.control.loadWordPairs(pairs);
