var pairs =
{
"system":{"requirements":1,"utilization":1}
,"requirements":{"bigmemory":1}
,"bigmemory":{"hybrid":1}
,"hybrid":{"supports":1,"capacity":1,"recommended":1}
,"supports":{"writing":1}
,"writing":{"single":1}
,"single":{"mount":1,"device":1}
,"mount":{"bigmemory":1,"used":1}
,"capacity":{"presented":1}
,"presented":{"terracotta":1}
,"terracotta":{"process":1,"server":1}
,"process":{"continuous":1,"system":1}
,"continuous":{"region":1}
,"region":{"single":1}
,"device":{"raid":1}
,"raid":{"mount":1}
,"used":{"exclusively":1}
,"exclusively":{"terracotta":1}
,"server":{"process":1}
,"utilization":{"higher":1}
,"higher":{"using":1}
,"using":{"bigmemory":1}
,"recommended":{"run":1,"deploy":1}
,"run":{"multiple":1}
,"multiple":{"servers":1}
,"servers":{"machine":1,"therefore":1,"different":1}
,"machine":{"doing":1}
,"doing":{"result":1}
,"result":{"health":1}
,"health":{"checkers":1}
,"checkers":{"timing":1}
,"timing":{"killing":1}
,"killing":{"restarting":1}
,"restarting":{"servers":1}
,"therefore":{"important":1}
,"important":{"provision":1}
,"provision":{"sufficient":1}
,"sufficient":{"hardware":1}
,"hardware":{"highly":1}
,"highly":{"recommended":1}
,"deploy":{"servers":1}
,"different":{"machines":1}
}
;Search.control.loadWordPairs(pairs);
