var pairs =
{
"requirements":{"order":1}
,"order":{"run":1}
,"run":{"sample":1}
,"sample":{"application":1}
,"application":{"java":1,"build":1}
,"java":{"1.6":1,"home>":1}
,"1.6":{"higher":1}
,"higher":{"java_home":1}
,"java_home":{"follows":1}
,"follows":{"windows":1}
,"windows":{"following":1}
,"following":{"command":1}
,"command":{"java_home=\u0022":1,"export":1}
,"java_home=\u0022":{"<path":1}
,"<path":{"java":1}
,"home>":{"unix\u002Flinux":1,"intend":1}
,"unix\u002Flinux":{"following":1}
,"export":{"java_home=\u0022":1}
,"intend":{"modify":1}
,"modify":{"source":1}
,"source":{"code":1}
,"code":{"application":1}
,"build":{"need":1}
,"need":{"maven":1}
}
;Search.control.loadWordPairs(pairs);
