var pairs =
{
"configuring":{"bigmemory":1}
,"bigmemory":{"hybrid":1,"max":1,"difference":1}
,"hybrid":{"configure":1,"include":1,"-enables":1,"option":1,"element":1,"functionality":1,"enabled":1,"value":1,"mode":1,"tag":1,"requires":1,"fast":1,"bigmemory":1}
,"configure":{"bigmemory":1}
,"include":{"following":1}
,"following":{"elements":1}
,"elements":{"tc-config.xml":1}
,"tc-config.xml":{"file":1,"configuration":1}
,"file":{"datastorage":1,"bigmemory":1}
,"datastorage":{"-specifies":1,"element":1,"size":1}
,"-specifies":{"maximum":1}
,"maximum":{"amount":1}
,"amount":{"data":1}
,"data":{"plan":1,"hold":1,"loaded":1,"terracotta":1}
,"plan":{"store":1}
,"store":{"server":1}
,"server":{"using":1,"don":1}
,"using":{"either":1,"<data>":1}
,"either":{"dram":1}
,"dram":{"alone":1,"ssd":1,"hybrid":1,"example":1,"times":1,"operation":1}
,"alone":{"dram":1}
,"ssd":{"flash":1,"devices":1}
,"flash":{"memory":1}
,"memory":{"offheap":1,"addition":1}
,"offheap":{"-specifies":1,"element":1,"size":1}
,"hold":{"dram":1}
,"-enables":{"hybrid":1}
,"option":{"ssd":1}
,"addition":{"off-heap":1}
,"off-heap":{"dram":1}
,"example":{"<servers>":1}
,"<servers>":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"hostname":1}
,"hostname":{"name=\u0022":1}
,"name=\u0022":{"server1":1}
,"server1":{"<datastorage":1}
,"<datastorage":{"size=\u0022":1}
,"size=\u0022":{"800g":1,"200g":1}
,"800g":{"<offheap":1}
,"<offheap":{"size=\u0022":1}
,"200g":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<hybrid\u002F>":1}
,"<hybrid\u002F>":{"<\u002Fdatastorage>":1}
,"<\u002Fdatastorage>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"terracotta":1}
,"terracotta":{"servers":1,"server\u0027s":1,"server":1}
,"servers":{"minimum":1}
,"minimum":{"recommended":1}
,"recommended":{"size":1}
,"size":{"attribute":1,"offheap":1,"default":1}
,"attribute":{"offheap":1,"datastorage":1,"migrating":1}
,"element":{"hybrid":1,"present":1,"exceed":1,"enables":1,"absent":1,"less":1,"case":1,"required":1,"optional":1,"value":1,"replaced":1,"old":1,"compatible":1,"server\u0027s":1}
,"present":{"bigmemory":1}
,"functionality":{"enabled":1,"hybrid":1}
,"enabled":{"hybrid":1,"value":1,"restart":1}
,"value":{"size":1,"assigned":1}
,"exceed":{"size":1}
,"enables":{"ssd":1}
,"devices":{"supplement":1}
,"supplement":{"dram":1}
,"times":{"larger":1}
,"larger":{"dram":1}
,"absent":{"bigmemory":1,"datastorage":1}
,"less":{"equal":1}
,"equal":{"value":1}
,"case":{"offheap":1}
,"required":{"datastorage":1,"system":1}
,"default":{"512":1,"path":1}
,"512":{"although":1}
,"although":{"datastorage":1}
,"optional":{"included":1}
,"included":{"element":1}
,"assigned":{"size":1}
,"migrating":{"bigmemory":1}
,"max":{"4.0":1}
,"4.0":{"4.1":1}
,"4.1":{"datastorage":1}
,"replaced":{"maxdatasize":1}
,"maxdatasize":{"element":1}
,"old":{"element":1}
,"compatible":{"pure":1}
,"pure":{"dram":1}
,"operation":{"enable":1}
,"enable":{"hybrid":1}
,"mode":{"new":1}
,"new":{"4.1-compatible":1}
,"4.1-compatible":{"datastorage":1}
,"tag":{"disk":1}
,"disk":{"storage":1,"may":1}
,"storage":{"path":1}
,"path":{"bigmemory":1,"default":1,"terracotta":1,"using":1}
,"requires":{"unique":1}
,"unique":{"explicitly":1}
,"explicitly":{"specified":1}
,"specified":{"path":1}
,"server\u0027s":{"home":1,"tc-config.xml":1}
,"home":{"directory":1}
,"directory":{"customize":1}
,"customize":{"path":1}
,"<data>":{"element":1}
,"configuration":{"file":1}
,"fast":{"restartability":1,"restartabillity":1}
,"restartability":{"fast":1,"don":1}
,"restartabillity":{"enabled":1}
,"restart":{"data":1,"artifacts":1}
,"loaded":{"bigmemory":1}
,"difference":{"behavior":1}
,"behavior":{"time":1}
,"time":{"required":1}
,"system":{"running":1}
,"running":{"again":1}
,"again":{"fast":1}
,"don":{"added":1}
,"added":{"link":1}
,"link":{"fast":1}
,"artifacts":{"previous":1}
,"previous":{"run":1}
,"run":{"left":1}
,"left":{"disk":1}
,"may":{"want":1}
,"want":{"remove":1}
,"remove":{"information":1}
,"information":{"clearing":1}
,"clearing":{"data":1}
}
;Search.control.loadWordPairs(pairs);
