var pairs =
{
"(basic":{"jta":1}
,"jta":{"support)":1,"operations":1,"transactions":1}
,"support)":{"transactional":1}
,"transactional":{"caches":1}
,"caches":{"provide":1}
,"provide":{"support":1}
,"support":{"basic":1}
,"basic":{"jta":1}
,"operations":{"configuring":1}
,"configuring":{"using":1}
,"using":{"differ":1,"local":1,"atomikos":1}
,"differ":{"using":1}
,"local":{"transactions":1}
,"transactions":{"except":1,"using":1,"<cache":1}
,"except":{"mode":1}
,"mode":{"requires":1}
,"requires":{"transaction":1}
,"transaction":{"manager":1,"database":1}
,"manager":{"allows":1,"sure":1}
,"allows":{"cache":1}
,"cache":{"participate":1,"configured":1}
,"participate":{"jta":1}
,"atomikos":{"transaction":1,"configuration":1,"behaves":1}
,"sure":{"com.atomikos.icatch.threaded_2pc=false":1}
,"com.atomikos.icatch.threaded_2pc=false":{"atomikos":1}
,"configuration":{"helps":1}
,"helps":{"prevent":1}
,"prevent":{"unintended":1}
,"unintended":{"rollbacks":1}
,"rollbacks":{"due":1}
,"due":{"bug":1}
,"bug":{"atomikos":1}
,"behaves":{"certain":1}
,"certain":{"conditions":1}
,"conditions":{"example":1}
,"example":{"following":1}
,"following":{"cache":1}
,"configured":{"jta":1,"compliant":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"com.my.package.foo":1}
,"com.my.package.foo":{"maxentrieslocalheap=\u0022":1}
,"maxentrieslocalheap=\u0022":{"500":1}
,"500":{"eternal=\u0022":1}
,"eternal=\u0022":{"false":1}
,"false":{"copyonread=\u0022":1}
,"copyonread=\u0022":{"true":1}
,"true":{"copyonwrite=\u0022":1,"consistency=\u0022":1}
,"copyonwrite=\u0022":{"true":1}
,"consistency=\u0022":{"strong":1}
,"strong":{"transactionalmode=\u0022":1}
,"transactionalmode=\u0022":{"<persistence":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"distributed":1}
,"distributed":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<terracotta":1}
,"<terracotta":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"resource":1}
,"resource":{"involved":1}
,"involved":{"transaction":1}
,"database":{"configured":1}
}
;Search.control.loadWordPairs(pairs);
