var pairs =
{
"cluster":{"events":1}
,"events":{"cluster":1,"report":1,"logged":1,"memory":1}
,"report":{"topology":1}
,"topology":{"changes":1}
,"changes":{"performance":1}
,"performance":{"issues":1}
,"issues":{"errors":1}
,"errors":{"operations":1}
,"operations":{"events":1}
,"logged":{"terracotta":1}
,"terracotta":{"server":1,"management":1,"property":1,"configuration":1}
,"server":{"(l2)":1}
,"(l2)":{"client":1}
,"client":{"(l1)":1}
,"(l1)":{"viewed":1}
,"viewed":{"tmc":1}
,"tmc":{"(see":1,"edit":1}
,"(see":{"terracotta":1}
,"management":{"console":1}
,"console":{"user\u0027s":1}
,"user\u0027s":{"guide)":1}
,"guide)":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"default":1}
,"default":{"stores":1}
,"stores":{"maximum":1}
,"maximum":{"100":1}
,"100":{"events":1}
,"memory":{"number":1}
,"number":{"pulled":1,"terracotta":1}
,"pulled":{"tmc":1}
,"edit":{"number":1}
,"property":{"l2.operator.events.store":1,"terracotta":1}
,"l2.operator.events.store":{"property":1,"value=\u0022":1}
,"configuration":{"file":1}
,"file":{"<tc-properties>":1}
,"<tc-properties>":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"l2.operator.events.store":1}
,"value=\u0022":{"500":1}
,"500":{"<\u002Ftc-properties>":1}
}
;Search.control.loadWordPairs(pairs);
