var pairs =
{
"configuration":{"development":1,"file":1,"options":1,"adequate":1,"settings":1,"allows":1}
,"development":{"environment":1,"terracotta":1,"two-server":1,"explicitly":1}
,"environment":{"development":1,"using":1,"case":1}
,"using":{"different":1,"start-tc-server.sh":1,"<server>":1,"configuration":1}
,"different":{"configuration":1,"ports":1,"location":1,"addresses":1}
,"file":{"terracotta":1,"tc-config.xml":1,"approaches":1,"configuration":1,"loaded":1,"specifies":1,"passing":1}
,"terracotta":{"client":1,"one-server":1,"server":1,"servers":1,"configuration":1,"tc-config.xml":1}
,"client":{"facilitates":1,"-dtc.config=path\u002Fto\u002Fmy-tc-config.xml":1}
,"facilitates":{"testing":1}
,"testing":{"tuning":1}
,"tuning":{"configuration":1}
,"options":{"efficient":1}
,"efficient":{"effective":1}
,"effective":{"gain":1}
,"gain":{"valuable":1}
,"valuable":{"insight":1}
,"insight":{"best":1}
,"best":{"practices":1}
,"practices":{"clustering":1}
,"clustering":{"application":1}
,"application":{"terracotta":1,"want":1}
,"one-server":{"setup":1}
,"setup":{"development":1,"sometimes":1,"active":1,"specifying":1}
,"server":{"default":1,"using":1,"instance":1,"separately":1,"different":1,"names":1,"start-tc-server.sh":1,"instances":1,"name":1,"script":1,"address":1}
,"default":{"configuration":1}
,"adequate":{"default":1}
,"settings":{"start":1}
,"start":{"terracotta":1,"application":1}
,"start-tc-server.sh":{"(or":1,"server1":1}
,"(or":{"start-tc-server.bat)":1}
,"start-tc-server.bat)":{"script":1}
,"script":{"directory":1,"however":1,"assumes":1}
,"directory":{"contain":1,"different":1,"run":1}
,"contain":{"file":1}
,"tc-config.xml":{"[prompt]":1,"exists":1}
,"[prompt]":{"${terracotta_home}\u005Cbin\u005Cstart-tc-server.sh":1}
,"${terracotta_home}\u005Cbin\u005Cstart-tc-server.sh":{"specify":1}
,"specify":{"configuration":1,"name":1,"client\u0027s":1}
,"approaches":{"discussed":1}
,"discussed":{"terracotta":1}
,"servers":{"configured":1,"define":1,"host":1,"starting":1,"restartable":1}
,"configured":{"two-server":1}
,"two-server":{"setup":1}
,"sometimes":{"referred":1}
,"referred":{"active-mirror":1}
,"active-mirror":{"setup":1}
,"active":{"server":1}
,"instance":{"hot":1}
,"hot":{"standby":1}
,"standby":{"(the":1}
,"(the":{"mirror)":1}
,"mirror)":{"load":1}
,"load":{"configuration":1}
,"loaded":{"terracotta":1,"without":1}
,"define":{"server":1}
,"separately":{"using":1}
,"<server>":{"elements":1}
,"elements":{"example":1,"name":1}
,"example":{"<tc:tc-config":1,"running":1,"terracotta":1}
,"<tc:tc-config":{"xsi:schemalocation=\u0022":1}
,"xsi:schemalocation=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fschema\u002Fterracotta-9.xsd":{"xmlns:tc=\u0022":1}
,"xmlns:tc=\u0022":{"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fconfig":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"<!--use":1}
,"<!--use":{"address":1}
,"address":{"resolvable":1,"corresponding":1,"target":1}
,"resolvable":{"host":1}
,"host":{"name":1,"attribute":1,"<tsa-port>":1,"specify":1}
,"name":{"host":1,"attribute":1,"optional":1}
,"attribute":{"-->":1,"may":1,"unambiguous":1}
,"-->":{"<server":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"123.456.7.890":1,"myresolvablehostname":1}
,"123.456.7.890":{"name=\u0022":1}
,"name=\u0022":{"server1":1,"server2":1}
,"server1":{"<server":1,"active":1,"<path_to_configuration_file>":1}
,"myresolvablehostname":{"name=\u0022":1}
,"server2":{"<\u002Ftc:tc-config>":1,"mirror":1}
,"<\u002Ftc:tc-config>":{"assuming":1}
,"assuming":{"server1":1}
,"allows":{"server2":1}
,"mirror":{"maintain":1}
,"maintain":{"environment":1}
,"case":{"failover":1}
,"failover":{"running":1}
,"running":{"servers":1,"terracotta":1}
,"<tsa-port>":{"server":1,"having":1}
,"ports":{"automatically":1}
,"automatically":{"generated":1}
,"generated":{"<tsa-port>":1}
,"having":{"separate":1}
,"separate":{"log":1}
,"log":{"location":1}
,"location":{"good":1,"requirement":1}
,"good":{"idea":1}
,"idea":{"failing":1}
,"failing":{"prevent":1}
,"prevent":{"servers":1}
,"starting":{"servers":1,"server":1,"terracotta":1}
,"restartable":{"setting":1}
,"setting":{"data":1}
,"data":{"directory":1}
,"requirement":{"server":1}
,"names":{"startup":1}
,"startup":{"multiple":1}
,"multiple":{"<server>":1}
,"may":{"required":1}
,"required":{"avoid":1}
,"avoid":{"ambiguity":1}
,"ambiguity":{"starting":1}
,"<path_to_configuration_file>":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"start-tc-server.bat":1}
,"start-tc-server.bat":{"example":1}
,"instances":{"host":1,"unambiguous":1}
,"unambiguous":{"target":1,"setup":1}
,"target":{"script":1,"clients":1}
,"however":{"starting":1}
,"specifying":{"server":1}
,"optional":{"example":1}
,"specifies":{"different":1}
,"addresses":{"server":1}
,"assumes":{"server":1}
,"corresponding":{"local":1}
,"local":{"address":1}
,"clients":{"development":1}
,"explicitly":{"specify":1}
,"client\u0027s":{"terracotta":1}
,"passing":{"-dtc.config=path\u002Fto\u002Fmy-tc-config.xml":1}
,"-dtc.config=path\u002Fto\u002Fmy-tc-config.xml":{"start":1,"-cp":1}
,"-cp":{"classes":1}
,"classes":{"myapp.class.main":1}
,"myapp.class.main":{"myapp.class.main":1,"class":1}
,"class":{"used":1}
,"used":{"launch":1}
,"launch":{"application":1}
,"want":{"cluster":1}
,"cluster":{"terracotta":1}
,"exists":{"directory":1}
,"run":{"java":1}
,"java":{"loaded":1}
,"without":{"-dtc.config":1}
}
;Search.control.loadWordPairs(pairs);
