var pairs =
{
"tuning":{"healthchecker":1}
,"healthchecker":{"allow":1,"work":1,"disconnect":1}
,"allow":{"interruptions":1,"healthchecker":1,"clients":1}
,"interruptions":{"cycles":1,"difference":1,"adjust":1}
,"cycles":{"affect":1}
,"affect":{"node\u0027s":1}
,"node\u0027s":{"ability":1}
,"ability":{"respond":1}
,"respond":{"socket-connection":1}
,"socket-connection":{"requests":1,"attempts":1}
,"requests":{"network":1}
,"network":{"interruptions":1,"issues":1,"disconnection":1}
,"difference":{"used":1}
,"used":{"tune":1}
,"tune":{"healthchecker":1}
,"work":{"efficiently":1}
,"efficiently":{"cluster":1}
,"cluster":{"issues":1,"longer":1}
,"issues":{"likely":1,"favor":1}
,"likely":{"occur":1}
,"occur":{"favor":1}
,"favor":{"detection":1}
,"detection":{"network":1,"pauses":1}
,"adjust":{"socketconnectcount":1}
,"socketconnectcount":{"down":1,"(since":1}
,"down":{"(since":1,"add":1}
,"(since":{"socket":1}
,"socket":{"connections":1}
,"connections":{"fail)":1,"succeed)":1}
,"fail)":{"allow":1}
,"disconnect":{"client":1}
,"client":{"sooner":1}
,"sooner":{"due":1}
,"due":{"network":1}
,"pauses":{"adjust":1}
,"succeed)":{"allow":1}
,"clients":{"remain":1}
,"remain":{"cluster":1}
,"longer":{"network":1}
,"disconnection":{"occurred":1}
,"occurred":{"ping":1}
,"ping":{"interval":1}
,"interval":{"increases":1,"adjusted":1}
,"increases":{"time":1}
,"time":{"socket-connection":1}
,"attempts":{"kick":1}
,"kick":{"verify":1}
,"verify":{"health":1}
,"health":{"remote":1}
,"remote":{"node":1}
,"node":{"ping":1}
,"adjusted":{"down":1}
,"add":{"less":1}
,"less":{"tolerance":1}
,"tolerance":{"either":1}
,"either":{"situations":1}
,"situations":{"listed":1}
,"listed":{"above":1}
}
;Search.control.loadWordPairs(pairs);
