var pairs =
{
"available":{"security":1,"information":1}
,"security":{"levels":1,"architecture":1,"available":1,"authentication":1,"default":1,"standard":1,"secured":1,"information":1,"case":1,"disabled":1,"layers":1,"required":1,"basic":1,"together":1,"perspective":1,"context":1}
,"levels":{"terracotta":1,"security":1}
,"terracotta":{"management":1}
,"management":{"server":1,"console":1}
,"server":{"(tms)":1}
,"(tms)":{"includes":1}
,"includes":{"flexible":1}
,"flexible":{"multi-level":1}
,"multi-level":{"security":1}
,"architecture":{"easily":1}
,"easily":{"integrate":1}
,"integrate":{"variety":1}
,"variety":{"environments":1}
,"environments":{"following":1}
,"following":{"levels":1}
,"authentication":{"limited":1,"built":1,"authorization":1,"enhances":1,"noted":1}
,"limited":{"secured":1}
,"secured":{"connections":1}
,"connections":{"additional":1,"based":1}
,"additional":{"details":1}
,"details":{"security":1,"default":1,"basic":1,"certificate-based":1}
,"default":{"security":1,"role-based":1}
,"role-based":{"user":1}
,"user":{"authentication":1}
,"built":{"setup":1}
,"setup":{"first":1}
,"first":{"connect":1}
,"connect":{"tms":1}
,"tms":{"intended":1,"additional":1,"however":1,"terracotta":1}
,"intended":{"control":1}
,"control":{"access":1}
,"access":{"tms":1}
,"standard":{"ldap":1}
,"ldap":{"microsoft":1,"active":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"directory":{"integration":1,"setting":1,"authorization":1}
,"integration":{"available":1}
,"information":{"using":1}
,"using":{"ldap":1,"ssl":1}
,"setting":{"ldap":1}
,"authorization":{"basic":1,"bigmemory":1}
,"basic":{"connection":1,"security":1}
,"connection":{"security":1}
,"bigmemory":{"bigmemory":1,"max":1}
,"max":{"nodes":1}
,"nodes":{"(referred":1}
,"(referred":{"agents":1}
,"agents":{"managed":1,"context)":1}
,"managed":{"agents":1}
,"context)":{"message":1}
,"message":{"hashing":1}
,"hashing":{"protective":1}
,"protective":{"measures":1}
,"measures":{"additional":1}
,"based":{"secure":1}
,"secure":{"sockets":1}
,"sockets":{"layer":1}
,"layer":{"(ssl)":1}
,"(ssl)":{"technology":1}
,"technology":{"used":1}
,"used":{"conjunction":1,"together":1}
,"conjunction":{"basic":1}
,"ssl":{"adding":1,"certificate-based":1}
,"adding":{"ssl":1}
,"certificate-based":{"client":1}
,"client":{"authentication":1}
,"enhances":{"ssl-based":1}
,"ssl-based":{"security":1}
,"case":{"basic":1}
,"disabled":{"additional":1}
,"noted":{"exceptions":1}
,"exceptions":{"security":1}
,"layers":{"used":1,"together":1}
,"together":{"provide":1,"don\u2019t":1,"?>>":1}
,"provide":{"overall":1}
,"overall":{"level":1}
,"level":{"security":1}
,"required":{"environment":1}
,"environment":{"<<ffc-we":1}
,"<<ffc-we":{"need":1}
,"need":{"clarify":1}
,"clarify":{"statement":1}
,"statement":{"don\u2019t":1}
,"don\u2019t":{"understand":1,"think":1}
,"understand":{"layers":1}
,"think":{"security":1}
,"?>>":{"document":1}
,"document":{"discusses":1}
,"discusses":{"security":1}
,"perspective":{"tms":1}
,"however":{"tms":1}
,"console":{"(tmc)":1}
,"(tmc)":{"function":1}
,"function":{"security":1}
}
;Search.control.loadWordPairs(pairs);
