var pairs =
{
"commands":{"terracotta":1,"listed":1,"additional":1,"command":1}
,"terracotta":{"supports":1,"takes":1,"information":1}
,"supports":{"terracotta":1,"command":1,"details":1,"sagcc":1}
,"command":{"central":1,"cli":1,"lifecycle":1}
,"central":{"cli":1,"help":1}
,"cli":{"(command":1,"commands":1}
,"(command":{"line":1}
,"line":{"interface)":1}
,"interface)":{"commands":1}
,"listed":{"following":1}
,"following":{"table":1}
,"table":{"cases":1,"lists":1}
,"cases":{"terracotta-specific":1}
,"terracotta-specific":{"information":1}
,"information":{"table":1,"sagcc":1,"configuration":1,"using":1,"command":1}
,"lists":{"learn":1}
,"learn":{"arguments":1}
,"arguments":{"options":1}
,"options":{"terracotta":1}
,"details":{"actions":1}
,"actions":{"terracotta":1}
,"takes":{"execute":1}
,"execute":{"exec":1}
,"exec":{"command":1,"lifecycle":1}
,"additional":{"information":1}
,"sagcc":{"configuration":1,"list":1,"diagnostic":1,"monitoring":1,"inventory":1,"exec":1}
,"configuration":{"data":1,"types":1,"instances":1}
,"data":{"terracotta-specific":1}
,"types":{"configuration":1,"terracotta":1,"sagcc":1}
,"instances":{"sagcc":1}
,"list":{"configuration":1,"inventory":1}
,"diagnostic":{"logs":1}
,"logs":{"sagcc":1}
,"monitoring":{"sagcc":1}
,"inventory":{"components":1}
,"components":{"sagcc":1}
,"lifecycle":{"terracotta-specific":1,"actions":1}
,"using":{"command":1}
}
;Search.control.loadWordPairs(pairs);
