var pairs =
{
"security":{"related":1,"java":1}
,"related":{"files":1,"information":1}
,"files":{"terracotta":1,"implement":1,"tools":1,"read":1,"startup":1}
,"terracotta":{"server":1,"keychain":1,"kit":1,"client":1}
,"server":{"uses":1,"note":1,"files":1}
,"uses":{"following":1,"authenticate":1}
,"following":{"types":1}
,"types":{"files":1}
,"implement":{"security":1}
,"java":{"keystore":1,"cacerts":1,"documentation":1}
,"keystore":{"-contains":1,"protected":1,"file":1,"entries":1}
,"-contains":{"server\u0027s":1}
,"server\u0027s":{"private":1,"keystore":1}
,"private":{"key":1}
,"key":{"public-key":1}
,"public-key":{"certificate":1}
,"certificate":{"keystore":1,"authority":1,"chains":1}
,"protected":{"keystore\u002Fcertificate-entry":1,"changing":1}
,"keystore\u002Fcertificate-entry":{"password":1}
,"password":{"truststore":1,"file":1,"uses":1}
,"truststore":{"keystore":1}
,"file":{"containing":1,"needed":1,"provided":1,"password-protected":1,"located":1,"protected":1,"permissions":1,"stores":1}
,"containing":{"public":1}
,"public":{"keys":1}
,"keys":{"certificates":1}
,"certificates":{"file":1,"rather":1,"included":1,"play":1}
,"needed":{"using":1}
,"using":{"self-signed":1,"ldap":1}
,"self-signed":{"certificates":1}
,"rather":{"certificate":1}
,"authority":{"(ca)":1}
,"(ca)":{"keychain":1}
,"keychain":{"-stores":1,"file":1}
,"-stores":{"passwords":1}
,"passwords":{"including":1,"server\u0027s":1}
,"including":{"passwords":1}
,"entries":{"files":1}
,"tools":{"creating":1}
,"creating":{"managing":1}
,"managing":{"terracotta":1}
,"provided":{"terracotta":1}
,"kit":{"authorization":1}
,"authorization":{".ini":1}
,".ini":{"file":1}
,"password-protected":{"user":1}
,"user":{"accounts":1}
,"accounts":{"roles":1}
,"roles":{"servers":1}
,"servers":{"clients":1}
,"clients":{"connect":1}
,"connect":{"server":1}
,"note":{"microsoft":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"directory":{"standard":1,"authentication":1}
,"standard":{"ldap":1,"java":1}
,"ldap":{"authentication\u002Fauthorization":1,"active":1}
,"authentication\u002Fauthorization":{"available":1}
,"available":{"options":1}
,"options":{"using":1}
,"authentication":{"related":1}
,"information":{"standard":1}
,"cacerts":{"file":1}
,"located":{"${java_home}":1}
,"${java_home}":{"java.home\u002Flib\u002Fsecurity":1}
,"java.home\u002Flib\u002Fsecurity":{"default":1}
,"default":{"system-wide":1,"password":1}
,"system-wide":{"repository":1}
,"repository":{"root":1}
,"root":{"certificates":1}
,"included":{"jdk":1}
,"jdk":{"certificates":1}
,"play":{"part":1}
,"part":{"certificate":1}
,"chains":{"java":1}
,"documentation":{"recommends":1}
,"recommends":{"cacerts":1}
,"changing":{"default":1}
,"permissions":{"terracotta":1}
,"client":{"keychain":1}
,"stores":{"password":1}
,"authenticate":{"server":1}
,"read":{"startup":1,"unless":1}
,"startup":{"changes":1,"cannot":1}
,"changes":{"made":1}
,"made":{"files":1}
,"cannot":{"read":1}
,"unless":{"cluster":1}
,"cluster":{"restarted":1}
}
;Search.control.loadWordPairs(pairs);
