var pairs =
{
"configuration":{"development":1,"file":1}
,"development":{"operations":1}
,"operations":{"questions":1}
,"questions":{"enable":1,"sizing":1}
,"enable":{"restartable":1}
,"restartable":{"mode":1}
,"mode":{"servers":1}
,"servers":{"section":1,"configure":1,"<servers>":1,"running":1,"using":1,"tool":1,"clients":1}
,"section":{"tc-config.xml":1,"terracotta":1,"tc-config":1}
,"tc-config.xml":{"include":1,"terracotta":1}
,"include":{"following":1}
,"following":{"configurations":1,"line":1,"wget":1}
,"configurations":{"<servers>":1,"load":1}
,"<servers>":{"<server":1,"section":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"host1":1}
,"host1":{"name=\u0022":1}
,"name=\u0022":{"server1":1}
,"server1":{"<data-backup>":1}
,"<data-backup>":{"path\u002Fto\u002Fmy\u002Fbackup\u002Fdirectory":1}
,"path\u002Fto\u002Fmy\u002Fbackup\u002Fdirectory":{"<\u002Fdata-backup>":1}
,"<\u002Fdata-backup>":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"<restartable":1}
,"<restartable":{"enabled=\u0022":1,"enabled>":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1,"example":1,"terracotta":1}
,"\u0022\u002F>":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"persistence":1}
,"persistence":{"shared":1}
,"shared":{"data":1}
,"data":{"required":1,"terracotta":1,"handled":1,"yield":1,"going":1,"l1s":1,"shutdown":1,"exiting":1}
,"required":{"across":1,"release":1}
,"across":{"restarts":1}
,"restarts":{"<restartable":1}
,"enabled>":{"false":1}
,"false":{"configure":1}
,"configure":{"failover":1,"servers":1,"logging":1}
,"failover":{"work":1,"scenarios":1}
,"work":{"properly":1}
,"properly":{"two":1}
,"two":{"terracotta":1,"billion":1}
,"terracotta":{"servers":1,"configuration":1,"server":1,"cluster":1,"client":1,"management":1,"clients":1,"servers)":1,"process":1,"active":1,"script":1,"rest":1,"node":1}
,"file":{"start":1,"server":1,"specified":1,"maximum":1,"called":1,"configure":1,"searched":1}
,"start":{"two":1}
,"server":{"instances":1,"assumes":1,"groups":1,"instance":1,"array":1,"started":1,"logs":1,"running":1,"user":1,"reclaim":1}
,"instances":{"configuration":1}
,"assumes":{"control":1}
,"control":{"cluster":1,"logging":1}
,"cluster":{"(the":1,"high":1,"topology":1,"need":1,"terracotta":1,"number":1,"theoretically":1,"desired":1,"data":1,"load":1,"test":1,"configurations":1,"events":1,"don\u0027t":1,"failing":1}
,"(the":{"active)":1,"passive)":1}
,"active)":{"second":1}
,"second":{"becomes":1,"node":1}
,"becomes":{"mirror":1}
,"mirror":{"(the":1}
,"passive)":{"information":1}
,"information":{"configuring":1,"terracotta":1}
,"configuring":{"terracotta":1}
,"high":{"availability":1}
,"availability":{"know":1,"typical":1}
,"know":{"application":1}
,"application":{"started":1,"data":1,"listen":1,"nodes":1,"check":1,"logic":1}
,"started":{"terracotta":1,"without":1}
,"client":{"sharing":1,"nodes":1,"started":1,"bad":1,"disconnects":1,"required":1}
,"sharing":{"data":1}
,"management":{"console":1}
,"console":{"(tmc)":1,"user":1,"(see":1,"rest":1}
,"(tmc)":{"displays":1}
,"displays":{"cluster":1}
,"topology":{"listing":1}
,"listing":{"terracotta":1}
,"groups":{"connected":1}
,"connected":{"client":1}
,"nodes":{"navigation":1,"using":1}
,"navigation":{"tree":1}
,"tree":{"information":1}
,"user":{"guide":1,"guide)":1,"defined":1}
,"guide":{"addition":1}
,"addition":{"check":1}
,"check":{"standard":1,"terracotta":1,"system":1,"server\u0027s":1}
,"standard":{"output":1,"log4j.properties":1}
,"output":{"messages":1}
,"messages":{"terracotta":1,"file":1,"server":1}
,"without":{"errors":1}
,"errors":{"terracotta":1,"check":1,"location":1}
,"clients":{"log":1,"(l1s)":1,"create":1}
,"log":{"messages":1}
,"specified":{"<clients>":1,"tc-config.xml":1,"environment":1}
,"<clients>":{"section":1}
,"tc-config":{"file":1}
,"maximum":{"number":1,"however":1}
,"number":{"objects":1,"l1s":1,"typically":1,"requirements":1,"reasons":1}
,"objects":{"held":1}
,"held":{"terracotta":1}
,"instance":{"number":1,"two":1}
,"billion":{"limit":1}
,"limit":{"imposed":1}
,"imposed":{"design":1}
,"design":{"java":1}
,"java":{"collections":1}
,"collections":{"unlikely":1,"inside":1,"stored":1}
,"unlikely":{"terracotta":1}
,"need":{"approach":1}
,"approach":{"even":1}
,"even":{"percent":1}
,"percent":{"maximum":1}
,"however":{"issues":1}
,"issues":{"may":1}
,"may":{"arise":1,"hang":1,"block":1}
,"arise":{"require":1}
,"require":{"rearchitecting":1}
,"rearchitecting":{"application":1}
,"handled":{"cluster":1}
,"(l1s)":{"connect":1}
,"connect":{"terracotta":1,"servers":1,"version":1}
,"array":{"(l2s)":1}
,"(l2s)":{"cluster":1}
,"l1s":{"exist":1,"bigmemory":1,"l2s":1}
,"exist":{"terracotta":1}
,"theoretically":{"unbounded":1}
,"unbounded":{"(and":1}
,"(and":{"cannot":1}
,"cannot":{"configured)":1}
,"configured)":{"effectively":1}
,"effectively":{"planning":1}
,"planning":{"resource":1}
,"resource":{"limitations":1}
,"limitations":{"size":1}
,"size":{"shared":1,"cluster":1}
,"yield":{"optimum":1}
,"optimum":{"number":1,"size":1}
,"typically":{"important":1}
,"important":{"factors":1,"method":1}
,"factors":{"impact":1}
,"impact":{"number":1}
,"requirements":{"performance":1,"what\u0027s":1}
,"performance":{"availability":1}
,"typical":{"questions":1}
,"sizing":{"cluster":1}
,"desired":{"transactions-per-second":1}
,"transactions-per-second":{"failover":1}
,"scenarios":{"fast":1}
,"fast":{"reliable":1}
,"reliable":{"network":1}
,"network":{"hardware":1}
,"hardware":{"memory":1}
,"memory":{"disk":1}
,"disk":{"space":1}
,"space":{"machine":1}
,"machine":{"shared":1}
,"going":{"stored":1}
,"stored":{"cluster":1,"values":1}
,"bigmemory":{"used":1}
,"used":{"stripes":1}
,"stripes":{"(active":1}
,"(active":{"terracotta":1}
,"servers)":{"cluster":1}
,"load":{"l1s":1,"observe":1}
,"l2s":{"important":1}
,"method":{"determining":1}
,"determining":{"optimum":1}
,"test":{"various":1}
,"various":{"cluster":1,"cleanup":1}
,"observe":{"setup":1}
,"setup":{"meets":1}
,"meets":{"overall":1}
,"overall":{"requirements":1}
,"what\u0027s":{"best":1}
,"best":{"application":1}
,"listen":{"terracotta":1}
,"events":{"lost":1,"api":1}
,"lost":{"application":1}
,"using":{"ehcache":1,"terracotta":1}
,"ehcache":{"cluster-events":1,"api":1}
,"cluster-events":{"ehcache":1}
,"api":{"application":1,"(see":1,"developer":1,"second":1,"call":1}
,"process":{"alive":1}
,"alive":{"runtime":1}
,"runtime":{"application":1}
,"system":{"property":1}
,"property":{"tc.active":1}
,"tc.active":{"true":1,"confirm":1}
,"example":{"following":1,"server":1}
,"line":{"code":1}
,"code":{"return":1,"detects":1}
,"return":{"true":1}
,"active":{"time":1}
,"time":{"run":1}
,"run":{"boolean.getboolean":1}
,"boolean.getboolean":{"tc.active":1}
,"confirm":{"terracotta":1}
,"running":{"correctly":1,"connect":1,"localhost":1,"server":1,"client":1}
,"correctly":{"ways":1}
,"ways":{"confirm":1,"monitor":1}
,"(see":{"terracotta":1,"wan":1}
,"guide)":{"check":1,"monitoring":1,"control":1}
,"server\u0027s":{"logs":1}
,"logs":{"server":1,"specified":1}
,"location":{"server":1}
,"script":{"server-stat.sh":1,"running":1}
,"server-stat.sh":{"server-stat.bat":1}
,"server-stat.bat":{"generate":1}
,"generate":{"short":1}
,"short":{"status":1}
,"status":{"report":1}
,"report":{"terracotta":1}
,"tool":{"wget":1}
,"wget":{"access":1,"command":1,"http:\u002F\u002Flocalhost:9889\u002Fversion":1}
,"access":{"\u002Fconfig":1}
,"\u002Fconfig":{"\u002Fversion":1}
,"\u002Fversion":{"servlet":1}
,"servlet":{"example":1,"[prompt]":1}
,"localhost":{"port":1}
,"port":{"9889":1}
,"9889":{"following":1}
,"command":{"connect":1}
,"version":{"servlet":1}
,"[prompt]":{"wget":1}
,"http:\u002F\u002Flocalhost:9889\u002Fversion":{"ways":1}
,"monitor":{"cluster":1}
,"don\u0027t":{"involve":1}
,"involve":{"using":1}
,"rest":{"api":1}
,"developer":{"guide)":1}
,"monitoring":{"feature":1}
,"feature":{"provided":1}
,"provided":{"wan":1}
,"wan":{"replication":1}
,"replication":{"service":1,"user":1}
,"service":{"(see":1}
,"logging":{"level":1,"including":1}
,"level":{"terracotta":1}
,"create":{"file":1}
,"called":{".tc.custom.log4j.properties":1}
,".tc.custom.log4j.properties":{"edit":1}
,"edit":{"standard":1}
,"log4j.properties":{"file":1}
,"including":{"level":1}
,"node":{"loads":1,"attempts":1,"may":1,"(one":1,"exiting":1}
,"loads":{"file":1}
,"searched":{"path":1}
,"path":{"specified":1}
,"environment":{"variable":1}
,"variable":{"tc_install_dir":1}
,"tc_install_dir":{"defined":1}
,"defined":{"start-server":1,"running":1}
,"start-server":{"script":1}
,"bad":{"idea":1}
,"idea":{"change":1}
,"change":{"shared":1}
,"shutdown":{"hook":1,"thread":1}
,"hook":{"node":1}
,"attempts":{"change":1}
,"exiting":{"shutdown":1,"using":1}
,"thread":{"blocks":1,"may":1}
,"blocks":{"node":1}
,"hang":{"dropped":1}
,"dropped":{"cluster":1}
,"failing":{"exit":1}
,"exit":{"planned":1}
,"planned":{"thread":1}
,"block":{"number":1}
,"reasons":{"failure":1}
,"failure":{"obtain":1}
,"obtain":{"lock":1}
,"lock":{"better":1}
,"better":{"alternative":1}
,"alternative":{"cluster":1}
,"(one":{"exiting)":1}
,"exiting)":{"execute":1}
,"execute":{"certain":1}
,"certain":{"code":1}
,"detects":{"first":1}
,"first":{"node":1}
,"call":{"org.terracotta.api.terracotta.registerbeforeshutdownhook":1}
,"org.terracotta.api.terracotta.registerbeforeshutdownhook":{"(runnable":1}
,"(runnable":{"beforeshutdownhook)":1}
,"beforeshutdownhook)":{"perform":1}
,"perform":{"various":1}
,"cleanup":{"tasks":1}
,"tasks":{"terracotta":1}
,"disconnects":{"shuts":1}
,"shuts":{"down":1}
,"down":{"note":1,"terracotta":1}
,"note":{"terracotta":1}
,"release":{"locks":1}
,"locks":{"shutting":1,"although":1}
,"shutting":{"down":1}
,"reclaim":{"locks":1}
,"although":{"outstanding":1}
,"outstanding":{"transactions":1}
,"transactions":{"committed":1}
,"committed":{"store":1}
,"store":{"collections":1}
,"inside":{"collections":1}
,"values":{"cache":1,"modified":1}
,"cache":{"recommended":1}
,"recommended":{"unless":1}
,"unless":{"application":1}
,"logic":{"takes":1}
,"takes":{"careful":1}
,"careful":{"account":1}
,"account":{"values":1}
,"modified":{"safely":1}
,"safely":{"race":1}
,"race":{"conditions":1}
,"conditions":{"undefined":1}
,"undefined":{"results":1}
,"results":{"concurrentmodificationexception":1}
,"concurrentmodificationexception":{"problems":1}
,"problems":{"arise":1}
}
;Search.control.loadWordPairs(pairs);
