var pairs =
{
"creating":{"keychain":1}
,"keychain":{"entry":1,"file":1,"script":1}
,"entry":{"terracotta":1,"every":1,"uses":1,"server":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1,"client\u0027s":1}
,"terracotta":{"client":1,"server":1,"kit":1,"management":1}
,"client":{"keychain":1,"password":1,"username":1,"searches":1}
,"file":{"entry":1,"stores":1,"switch":1,"already":1,"serves":1,"ldap":1,"following":1,"successfully":1}
,"every":{"terracotta":1}
,"server":{"cluster":1,"example":1,"along":1,"address":1}
,"cluster":{"format":1}
,"format":{"entry":1}
,"uses":{"scheme":1}
,"scheme":{"tc:\u002F\u002F<client-username>@<host>":1,"requiring":1,"using":1}
,"tc:\u002F\u002F<client-username>@<host>":{"<tsa-port>":1}
,"<tsa-port>":{"entry":1}
,"example":{"configuration":1,"using":1}
,"configuration":{"look":1}
,"look":{"tc:\u002F\u002Fclient1@172.16.254.1:9510":1}
,"tc:\u002F\u002Fclient1@172.16.254.1:9510":{"keychain":1,"default":1,"prompted":1,"successfully":1}
,"script":{"terracotta":1,"operation":1,"run":1,"following":1,"verify":1}
,"kit":{"add":1}
,"add":{"entry":1}
,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":{"clientkeychainfile":1}
,"clientkeychainfile":{"tc:\u002F\u002Fclient1@172.16.254.1:9510":1,"enter":1}
,"default":{"keychain":1}
,"stores":{"passwords":1}
,"passwords":{"using":1}
,"using":{"obfuscation":1,"encrypted":1,"keychain":1}
,"obfuscation":{"scheme":1}
,"requiring":{"(hyphen":1}
,"(hyphen":{"capital":1}
,"capital":{"letter":1}
,"letter":{"keychain":1}
,"operation":{"file":1}
,"switch":{"secure":1}
,"secure":{"encryption-based":1}
,"encryption-based":{"scheme":1}
,"encrypted":{"keychains":1}
,"keychains":{"keychain":1}
,"already":{"exist":1}
,"exist":{"flag":1}
,"flag":{"create":1}
,"create":{"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"prompted":{"enter":1}
,"enter":{"client":1,"password":1}
,"password":{"associate":1,"provided":1,"wish":1,"tc:\u002F\u002Fclient1@172.16.254.1:9510":1}
,"associate":{"uri":1,"url":1}
,"uri":{"entry":1}
,"client\u0027s":{"keychain":1,"password":1}
,"serves":{"key":1}
,"key":{"client\u0027s":1}
,"provided":{"server":1}
,"along":{"client":1}
,"username":{"client1":1}
,"client1":{"example)":1}
,"example)":{"credentials":1}
,"credentials":{"match":1,"terracotta":1,"server":1}
,"match":{"server\u0027s":1}
,"server\u0027s":{".ini":1}
,".ini":{"file":1}
,"ldap":{"active":1}
,"active":{"directory":1}
,"directory":{"credentials":1}
,"searches":{"keychain":1}
,"following":{"locations":1,"prompt":1}
,"locations":{"(user.home)\u002F.tc\u002Fmgmt\u002Fkeychain":1}
,"(user.home)\u002F.tc\u002Fmgmt\u002Fkeychain":{"(user.dir)\u002Fkeychain.tkc":1}
,"(user.dir)\u002Fkeychain.tkc":{"path":1}
,"path":{"specified":1}
,"specified":{"system":1}
,"system":{"property":1}
,"property":{"com.tc.security.keychain.url":1}
,"com.tc.security.keychain.url":{"example":1}
,"run":{"keychain":1}
,"prompt":{"appear":1}
,"appear":{"terracotta":1}
,"management":{"console":1}
,"console":{"-keychain":1}
,"-keychain":{"client":1}
,"successfully":{"created":1,"stored":1}
,"created":{"clientkeychainfile":1}
,"wish":{"associate":1}
,"url":{"password":1}
,"stored":{"note":1}
,"note":{"script":1}
,"verify":{"credentials":1}
}
;Search.control.loadWordPairs(pairs);
