var pairs =
{
"working":{"vmware":1}
,"vmware":{"vmotion":1}
,"vmotion":{"software":1,"environment":1}
,"software":{"recommends":1,"terracotta":1}
,"recommends":{"against":1}
,"against":{"allowing":1}
,"allowing":{"live":1}
,"live":{"migrations":1,"migration":1,"again":1}
,"migrations":{"virtual":1}
,"virtual":{"machine":1}
,"machine":{"(s)":1}
,"(s)":{"software":1}
,"terracotta":{"server":1}
,"server":{"processes":1,"create":1}
,"processes":{"downtime":1,"elect":1,"runtime":1,"excluded":1}
,"downtime":{"introduced":1}
,"introduced":{"during":1}
,"during":{"live":1}
,"migration":{"process":1}
,"process":{"cause":1,"becomes":1}
,"cause":{"terracotta":1}
,"elect":{"new":1}
,"new":{"active":1}
,"active":{"server":1}
,"create":{"data":1}
,"data":{"consistency":1}
,"consistency":{"problems":1}
,"problems":{"migrated":1}
,"migrated":{"process":1}
,"becomes":{"live":1}
,"again":{"vmotion":1}
,"environment":{"please":1}
,"please":{"sure":1}
,"sure":{"terracotta":1}
,"runtime":{"processes":1}
,"excluded":{"live":1}
}
;Search.control.loadWordPairs(pairs);
