var pairs =
{
"configuring":{"encrypted":1}
,"encrypted":{"client":1}
,"client":{"keychain":1,"searches":1}
,"keychain":{"files":1,"file":1,"avoid":1,"script":1,"entering":1,"password":1}
,"files":{"clients":1}
,"clients":{"secret":1,"automatically":1}
,"secret":{"provider":1,"associated":1}
,"provider":{"following":1}
,"following":{"property":1,"prompt":1,"locations":1}
,"property":{"com.terracotta.express.secretprovider=net.sf.ehcache.terracotta.security.consolefetchingsecretprovider":1,"com.tc.security.keychain.url":1}
,"com.terracotta.express.secretprovider=net.sf.ehcache.terracotta.security.consolefetchingsecretprovider":{"add":1}
,"add":{"entries":1}
,"entries":{"keychain":1}
,"file":{"described":1,"successfully":1,"already":1,"prompted":1,"following":1}
,"described":{"setting":1}
,"setting":{"server":1}
,"server":{"keychain":1,"uri":1,"address":1}
,"avoid":{"using":1}
,"using":{"flag":1,"keychain":1}
,"flag":{"using":1,"create":1}
,"script":{"example":1,"following":1,"verify":1}
,"example":{"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":{"clientkeychainfile":1}
,"clientkeychainfile":{"tc:\u002F\u002Fclient1@172.16.254.1:9510":1,"open":1}
,"tc:\u002F\u002Fclient1@172.16.254.1:9510":{"run":1,"successfully":1,"creating":1}
,"run":{"keychain":1}
,"prompt":{"appear":1}
,"appear":{"terracotta":1}
,"terracotta":{"management":1,"client":1}
,"management":{"console":1}
,"console":{"-keychain":1}
,"-keychain":{"client":1}
,"successfully":{"created":1,"stored":1}
,"created":{"clientkeychainfile":1}
,"open":{"keychain":1}
,"entering":{"master":1}
,"master":{"key":1,"password":1}
,"key":{"enter":1,"answer":1}
,"enter":{"master":1,"password":1}
,"answer":{"prompts":1}
,"prompts":{"secret":1}
,"associated":{"server":1}
,"uri":{"enter":1}
,"password":{"wish":1,"tc:\u002F\u002Fclient1@172.16.254.1:9510":1,"automate":1,"clients":1,"terracotta":1}
,"wish":{"associate":1}
,"associate":{"url":1}
,"url":{"password":1}
,"stored":{"note":1}
,"note":{"script":1}
,"verify":{"credentials":1}
,"credentials":{"server":1}
,"address":{"keychain":1}
,"already":{"exist":1}
,"exist":{"flag":1}
,"create":{"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"creating":{"keychain":1}
,"prompted":{"master":1}
,"automate":{"entry":1}
,"entry":{"master":1}
,"automatically":{"reading":1}
,"reading":{"keychain":1}
,"searches":{"keychain":1}
,"locations":{"(user.home)\u002F.tc\u002Fmgmt\u002Fkeychain":1}
,"(user.home)\u002F.tc\u002Fmgmt\u002Fkeychain":{"(user.dir)\u002Fkeychain.tkc":1}
,"(user.dir)\u002Fkeychain.tkc":{"path":1}
,"path":{"specified":1}
,"specified":{"system":1}
,"system":{"property":1}
}
;Search.control.loadWordPairs(pairs);
