var pairs =
{
"using":{"rejoin":1}
,"rejoin":{"reconnect":1,"cluster":1,"process":1,"feature":1,"clusters":1,"new":1,"restarted":1,"nonstop-related":1,"operation":1,"enabled":1,"client":1,"disconnection":1,"may":1,"rejoin":1,"attribute":1,"certain":1,"exception":1,"attempt":1}
,"reconnect":{"terracotta":1}
,"terracotta":{"clients":1,"client":1,"clustering":1}
,"clients":{"terracotta":1,"automatically":1,"rejoin":1,"cannot":1,"allowed":1}
,"client":{"may":1,"hardware":1,"continues":1,"rejoin":1,"rejoins":1,"configuring":1,"follow":1,"without":1}
,"may":{"disconnect":1,"unsuccessful":1,"generate":1,"cause":1}
,"disconnect":{"timed":1}
,"timed":{"(ejected)":1}
,"(ejected)":{"cluster":1}
,"cluster":{"typically":1,"causes":1,"ejected":1,"(receives":1,"clients":1,"tsa":1}
,"typically":{"occurs":1}
,"occurs":{"network":1,"unlock":1}
,"network":{"communication":1}
,"communication":{"interruptions":1}
,"interruptions":{"lasting":1}
,"lasting":{"longer":1}
,"longer":{"configured":1}
,"configured":{"settings":1}
,"settings":{"cluster":1,"senses":1}
,"causes":{"include":1}
,"include":{"long":1}
,"long":{"pauses":1}
,"pauses":{"slowdowns":1,"inconsistencies":1}
,"slowdowns":{"introduced":1}
,"introduced":{"processes":1,"cluster":1}
,"processes":{"running":1}
,"running":{"client":1,"jvm":1}
,"hardware":{"configure":1}
,"configure":{"clients":1}
,"automatically":{"rejoin":1}
,"ejected":{"ejected":1,"client":1}
,"continues":{"run":1}
,"run":{"nonstop":1}
,"nonstop":{"cache":1,"enabled":1}
,"cache":{"settings":1}
,"senses":{"reconnected":1}
,"reconnected":{"cluster":1}
,"(receives":{"clusteronline":1}
,"clusteronline":{"event)":1}
,"event)":{"begin":1}
,"begin":{"rejoin":1,"(and":1}
,"process":{"note":1}
,"note":{"following":1}
,"following":{"using":1}
,"feature":{"disconnected":1,"disabled":1,"terracotta":1}
,"disconnected":{"clients":1}
,"clusters":{"previously":1}
,"previously":{"connected":1}
,"connected":{"clients":1}
,"new":{"members":1,"cluster":1}
,"members":{"wipe":1}
,"wipe":{"cached":1}
,"cached":{"data":1}
,"data":{"ensure":1,"persisted":1}
,"ensure":{"pauses":1,"caches":1,"application":1,"locks":1}
,"inconsistencies":{"introduced":1}
,"cannot":{"rejoin":1}
,"tsa":{"restarted":1}
,"restarted":{"data":1,"tsa":1}
,"persisted":{"clients":1}
,"allowed":{"rejoin":1}
,"nonstop-related":{"operations":1}
,"operations":{"begin":1,"try-finally":1}
,"(and":{"complete)":1}
,"complete)":{"rejoin":1}
,"operation":{"completes":1,"takes":1}
,"completes":{"may":1}
,"unsuccessful":{"may":1}
,"generate":{"nonstopcacheexception":1}
,"nonstopcacheexception":{"terracotta":1}
,"enabled":{"running":1,"nonstop":1,"ensure":1,"enable":1}
,"jvm":{"clients":1}
,"disconnection":{"remaining":1}
,"remaining":{"clients":1}
,"cause":{"application":1}
,"application":{"behave":1,"create":1,"invalidlockafterrejoinexception":1,"code":1}
,"behave":{"unpredictably":1}
,"unpredictably":{"once":1}
,"once":{"client":1}
,"rejoins":{"clusterrejoined":1}
,"clusterrejoined":{"event":1}
,"event":{"fired":1}
,"fired":{"client":1}
,"configuring":{"rejoin":1,"<terracottaconfig>":1}
,"disabled":{"default":1}
,"default":{"enable":1}
,"enable":{"rejoin":1}
,"follow":{"steps":1}
,"steps":{"ensure":1}
,"caches":{"ehcache":1,"client":1}
,"ehcache":{"configuration":1}
,"configuration":{"file":1,"elements":1,"guide":1}
,"file":{"rejoin":1}
,"create":{"caches":1}
,"without":{"nonstop":1}
,"attribute":{"client\u0027s":1}
,"client\u0027s":{"<terracottaconfig>":1}
,"<terracottaconfig>":{"element":1,"terracotta":1}
,"element":{"<terracottaconfig":1}
,"<terracottaconfig":{"url=\u0022":1}
,"url=\u0022":{"myhost:9510":1}
,"myhost:9510":{"rejoin=\u0022":1}
,"rejoin=\u0022":{"true":1}
,"true":{"options":1}
,"options":{"configuring":1}
,"clustering":{"configuration":1}
,"elements":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"configuration":1}
,"guide":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"exception":1}
,"exception":{"during":1,"occurs":1}
,"during":{"rejoin":1,"client":1}
,"certain":{"circumstances":1}
,"circumstances":{"lock":1}
,"lock":{"used":1,"obtained":1}
,"used":{"application":1}
,"invalidlockafterrejoinexception":{"thrown":1}
,"thrown":{"during":1}
,"unlock":{"operation":1}
,"takes":{"place":1}
,"place":{"lock":1}
,"obtained":{"rejoin":1}
,"attempt":{"completed":1}
,"completed":{"ensure":1}
,"locks":{"released":1}
,"released":{"properly":1}
,"properly":{"application":1}
,"code":{"encapsulate":1}
,"encapsulate":{"lock-unlock":1}
,"lock-unlock":{"operations":1}
,"try-finally":{"blocks":1}
,"blocks":{"mylock.acquirelock":1}
,"mylock.acquirelock":{"try":1}
,"try":{"{\u002F\u002Fdo":1}
,"{\u002F\u002Fdo":{"work":1}
,"work":{"finally":1}
,"finally":{"{mylock.unlock":1}
}
;Search.control.loadWordPairs(pairs);
