var pairs =
{
"running":{"multiple":1}
,"multiple":{"listeners":1,"event":1}
,"listeners":{"separate":1}
,"separate":{"nodes":1}
,"nodes":{"following":1,"listener":1}
,"following":{"example":1,"code":1}
,"example":{"running":1,"listener":1}
,"event":{"listeners":1,"generated":1,"unless":1,"(if":1,"\u002F\u002Fthis":1}
,"listener":{"node":1,"performs":1,"detects":1,"receive":1,"fail":1,"public":1}
,"node":{"listening":1,"fail":1}
,"listening":{"event":1}
,"generated":{"action":1,"put":1}
,"action":{"listener":1,"different":1}
,"fail":{"receive":1}
,"receive":{"event":1}
,"unless":{"listener":1}
,"performs":{"action":1}
,"different":{"thread":1}
,"thread":{"example":1}
,"detects":{"put":1}
,"put":{"cache":1,"\u002F\u002Fthis":1}
,"cache":{"turn":1,"listener":1,"however":1}
,"turn":{"puts":1}
,"puts":{"element":1}
,"element":{"cache":1}
,"(if":{"correctly":1}
,"correctly":{"registered":1}
,"registered":{"cache":1}
,"however":{"following":1}
,"code":{"listener":1,"allows":1}
,"\u002F\u002Fthis":{"method":1}
,"method":{"within":1}
,"within":{"listener":1}
,"public":{"void":1}
,"void":{"notifyelementput":1,"run":1}
,"notifyelementput":{"cache.put":1,"{executorservice.execute":1}
,"cache.put":{"following":1}
,"allows":{"listener":1}
,"{executorservice.execute":{"(new":1}
,"(new":{"runnable":1}
,"runnable":{"{public":1}
,"{public":{"void":1}
,"run":{"cache.put":1}
}
;Search.control.loadWordPairs(pairs);
