var pairs =
{
"safe":{"failover":1}
,"failover":{"procedure":1,"(passive-standby":1,"concern":1}
,"procedure":{"safely":1}
,"safely":{"migrate":1}
,"migrate":{"clients":1}
,"clients":{"standby":1,"connect":1,"fail":1}
,"standby":{"server":1,"state":1}
,"server":{"without":1,"using":1,"already":1,"ready":1,"standby":1,"failover":1,"restart":1,"within":1,"rejoin":1,"restartable":1}
,"without":{"stopping":1}
,"stopping":{"cluster":1}
,"cluster":{"follow":1,"standby":1}
,"follow":{"steps":1}
,"steps":{"already":1}
,"already":{"running":1,"configured":1}
,"running":{"start":1}
,"start":{"standby":1}
,"using":{"start-tc-server":1,"stop-tc-server":1}
,"start-tc-server":{"script":1}
,"script":{"standby":1,"note":1,"detects":1}
,"configured":{"terracotta":1,"reconnection":1}
,"terracotta":{"configuration":1,"management":1}
,"configuration":{"file":1}
,"file":{"ensure":1}
,"ensure":{"standby":1}
,"ready":{"failover":1}
,"(passive-standby":{"status)":1}
,"status)":{"terracotta":1}
,"management":{"console":1}
,"console":{"(tmc)":1}
,"(tmc)":{"status":1}
,"status":{"light":1}
,"light":{"cyan":1}
,"cyan":{"shut":1}
,"shut":{"down":1}
,"down":{"active":1}
,"active":{"server":1}
,"stop-tc-server":{"script":1}
,"note":{"script":1}
,"detects":{"mirror":1}
,"mirror":{"server":1}
,"state":{"isn\u0027t":1}
,"isn\u0027t":{"reachable":1}
,"reachable":{"issues":1}
,"issues":{"warning":1}
,"warning":{"fails":1}
,"fails":{"shut":1}
,"concern":{"override":1}
,"override":{"behavior":1}
,"behavior":{"--force":1}
,"--force":{"flag":1}
,"flag":{"clients":1}
,"connect":{"new":1}
,"new":{"active":1}
,"restart":{"clients":1}
,"fail":{"reconnect":1}
,"reconnect":{"new":1}
,"within":{"configured":1}
,"reconnection":{"window":1}
,"window":{"previously":1}
,"previously":{"active":1}
,"rejoin":{"cluster":1}
,"restartable":{"mode":1}
,"mode":{"enabled":1}
,"enabled":{"data":1}
,"data":{"first":1,"read":1}
,"first":{"removed":1}
,"removed":{"current":1}
,"current":{"data":1}
,"read":{"active":1}
}
;Search.control.loadWordPairs(pairs);
