var pairs =
{
"hardware":{"capacity":1}
,"capacity":{"guidelines":1}
,"guidelines":{"account":1}
,"account":{"overhead":1}
,"overhead":{"necessary":1}
,"necessary":{"consistent":1}
,"consistent":{"performance":1}
,"performance":{"formulas":1}
,"formulas":{"below":1}
,"below":{"suggested":1}
,"suggested":{"initial":1}
,"initial":{"starting":1}
,"starting":{"points":1}
,"points":{"sizing":1}
,"sizing":{"amount":1}
,"amount":{"space":1}
,"space":{"allocated":1}
,"allocated":{"bigmemory":1}
,"bigmemory":{"hybrid":1}
,"hybrid":{"operation":1}
,"operation":{"minimum":1}
,"minimum":{"ssd":1,"dram":1}
,"ssd":{"flash":1}
,"flash":{"memory":1}
,"memory":{"requirement":1}
,"requirement":{"=planned":1}
,"=planned":{"total":1,"maximum":1}
,"total":{"data":1}
,"data":{"size":1}
,"size":{"*3.2":1}
,"*3.2":{"minimum":1}
,"dram":{"requirement":1}
,"maximum":{"number":1}
,"number":{"elements":1}
,"elements":{"*(168":1}
,"*(168":{"key":1}
,"key":{"size)":1}
,"size)":{"strongly":1}
,"strongly":{"recommended":1}
,"recommended":{"configure":1}
,"configure":{"enough":1}
,"enough":{"offheap":1}
,"offheap":{"accommodate":1}
,"accommodate":{"cache":1}
,"cache":{"keys":1}
,"keys":{"dram":1}
}
;Search.control.loadWordPairs(pairs);
