var pairs =
{
"example":{"using":1,"available":1,"shows":1}
,"using":{"bigmemory":1}
,"bigmemory":{"max":1,"used":1,"until":1}
,"max":{"cache":1,"powerful":1,"may":1,"following":1,"configuration":1}
,"cache":{"following":1,"speed":1,"external":1,"timetoidleseconds":1}
,"following":{"description":1,"programmatic":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1,"block":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1,"bigmemory":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"bigmemory":1}
,"powerful":{"in-memory":1}
,"in-memory":{"data":1}
,"data":{"management":1,"slow":1,"sources":1,"first":1,"elements":1,"store":1,"want":1,"stay":1}
,"management":{"solution":1}
,"solution":{"among":1}
,"among":{"applications":1}
,"applications":{"bigmemory":1}
,"may":{"used":1}
,"used":{"cache":1}
,"speed":{"access":1}
,"access":{"data":1,"element":1}
,"slow":{"expensive":1}
,"expensive":{"databases":1}
,"databases":{"remote":1}
,"remote":{"data":1}
,"sources":{"example":1}
,"shows":{"enable":1,"time-to-live":1}
,"enable":{"configure":1}
,"configure":{"caching":1}
,"caching":{"features":1}
,"features":{"available":1}
,"programmatic":{"configuration":1}
,"configuration":{"snippet":1,"managerconfiguration":1,"managerconfiguration.name":1}
,"snippet":{"shows":1}
,"time-to-live":{"(ttl)":1}
,"(ttl)":{"time-to-idle":1}
,"time-to-idle":{"(tti)":1}
,"(tti)":{"policies":1}
,"policies":{"data":1}
,"first":{"code":1}
,"block":{"bigmem":1}
,"bigmem":{"second":1,"max":1}
,"second":{"bigmem":1}
,"managerconfiguration":{"=new":1}
,"=new":{"configuration":1}
,"managerconfiguration.name":{"cachemanagercompleteexample":1}
,"cachemanagercompleteexample":{".terracotta":1}
,".terracotta":{"(new":1}
,"(new":{"terracottaclientconfiguration":1,"cacheconfiguration":1,"terracottaconfiguration":1}
,"terracottaclientconfiguration":{".url":1}
,".url":{"localhost:9510":1}
,"localhost:9510":{"\u0022))":1}
,"\u0022))":{".cache":1}
,".cache":{"(new":1}
,"cacheconfiguration":{".name":1}
,".name":{"sample-cache":1}
,"sample-cache":{".maxbyteslocalheap":1}
,".maxbyteslocalheap":{"(128":1}
,"(128":{"memoryunit.megabytes)":1}
,"memoryunit.megabytes)":{".timetoliveseconds":1}
,".timetoliveseconds":{"(4)":1}
,"(4)":{".timetoidleseconds":1}
,".timetoidleseconds":{"(2)":1}
,"(2)":{".terracotta":1}
,"terracottaconfiguration":{"())":1}
,"())":{"cachemanager":1}
,"cachemanager":{"manager":1}
,"manager":{"=cachemanager.create":1}
,"=cachemanager.create":{"(managerconfiguration)":1}
,"(managerconfiguration)":{"timetoliveseconds":1}
,"timetoliveseconds":{"directive":1}
,"directive":{"sets":1}
,"sets":{"maximum":1}
,"maximum":{"age":1,"ttl":1,"time":1,"tti":1}
,"age":{"element":1}
,"element":{"data":1,"elements":1}
,"elements":{"older":1,"idle":1}
,"older":{"maximum":1}
,"ttl":{"returned":1,"tti":1}
,"returned":{"data":1}
,"store":{"useful":1}
,"useful":{"bigmemory":1}
,"external":{"data":1}
,"want":{"ensure":1,"bias":1}
,"ensure":{"freshness":1}
,"freshness":{"cache":1}
,"timetoidleseconds":{"directive":1}
,"time":{"last":1}
,"last":{"access":1}
,"idle":{"longer":1,"entries":1}
,"longer":{"maximum":1}
,"tti":{"returned":1,"(or":1}
,"bias":{"eviction":1}
,"eviction":{"algorithm":1}
,"algorithm":{"towards":1}
,"towards":{"removing":1}
,"removing":{"idle":1}
,"entries":{"neither":1}
,"neither":{"ttl":1}
,"(or":{"zero)":1}
,"zero)":{"data":1}
,"stay":{"bigmemory":1}
,"until":{"explicitly":1}
,"explicitly":{"removed":1}
}
;Search.control.loadWordPairs(pairs);
