var pairs =
{
"tuning":{"off-heap":1,"tips":1}
,"off-heap":{"store":1,"stores":1,"memory":1,"allocation":1,"buffer":1}
,"store":{"performance":1,"suggested":1,"substantial":1,"4mb":1,"holds":1,"large":1,"(called":1,"recorded":1,"reduced":1,"3gb":1}
,"performance":{"<<this":1,"issues":1,"functional":1,"portion":1,"heaps":1,"introducing":1,"problems":1,"example":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs":1}
,"docs":{"ehc":1}
,"ehc":{"!>>":1}
,"!>>":{"memory-related":1}
,"memory-related":{"performance":1,"errors":1}
,"issues":{"arise":1,"systems":1,"objects":1}
,"arise":{"during":1,"traced":1}
,"during":{"operations":1,"garbage-collection":1}
,"operations":{"related":1,"leading":1,"situation":1,"fail":1,"resulted":1}
,"related":{"improper":1}
,"improper":{"allocation":1}
,"allocation":{"memory":1,"committing":1,"based":1,"operations":1,"time":1,"lead":1}
,"memory":{"off-heap":1,"allocation":1,"likely":1,"disk":1,"allocated":1,"items":1,"overallocation":1,"(or":1,"available":1,"allotted":1,"size":1,"meta-data":1,"account":1,"requirements":1,"multiple":1,"comes":1,"quickly":1,"takes":1,"running":1,"efficient":1,"pages":1,"starve":1,"performance":1,"store":1,"forcing":1}
,"functional":{"issues":1}
,"traced":{"back":1}
,"back":{"off-heap":1,"memory":1}
,"suggested":{"tuning":1}
,"tips":{"section":1}
,"section":{"general":1,"applies":1}
,"general":{"memory":1,"sum":1,"bigmemory":1}
,"committing":{"system\u0027s":1}
,"system\u0027s":{"physical":1}
,"physical":{"memory":1,"ram":1}
,"likely":{"result":1,"during":1}
,"result":{"paging":1}
,"paging":{"virtual":1,"even":1,"disk":1}
,"virtual":{"memory":1}
,"disk":{"quite":1,"thus":1,"even":1,"heap":1,"stores":1,"store":1}
,"quite":{"likely":1}
,"garbage-collection":{"operations":1}
,"leading":{"significant":1}
,"significant":{"performance":1}
,"systems":{"multiple":1}
,"multiple":{"java":1,"processes":1,"times":1}
,"java":{"processes":1,"heaps":1,"update":1}
,"processes":{"multiple":1,"general":1,"exceed":1,"require":1,"may":1}
,"sum":{"java":1}
,"heaps":{"off-heap":1,"32gb":1}
,"stores":{"processes":1,"default":1}
,"exceed":{"size":1}
,"size":{"physical":1,"data":1,"jvm":1,"swapped":1,"however":1,"element":1,"limits":1,"require":1}
,"ram":{"system":1,"swap":1,"data":1}
,"system":{"besides":1,"resources":1,"property":1}
,"besides":{"memory":1}
,"allocated":{"heap":1,"over-allocating":1}
,"heap":{"java":1,"portion":1,"memory-intensive":1,"memory":1}
,"require":{"memory":1,"example":1}
,"items":{"code":1}
,"code":{"(classes)":1}
,"(classes)":{"stacks":1}
,"stacks":{"permgen":1}
,"permgen":{"note":1}
,"note":{"maxdirectmemorysize":1,"users":1,"setting":1}
,"maxdirectmemorysize":{"sets":1,"account":1}
,"sets":{"upper":1}
,"upper":{"limit":1}
,"limit":{"jvm":1,"direct":1,"classes":1,"pathologically":1}
,"jvm":{"enforce":1,"object":1,"running":1,"however":1,"halted":1,"shutdown":1,"oracle":1}
,"enforce":{"actually":1}
,"actually":{"allocate":1}
,"allocate":{"specified":1,"least":1,"off-heap":1,"buffer":1}
,"specified":{"memory":1}
,"overallocation":{"direct":1}
,"direct":{"memory":1,"buffer":1,"buffers":1}
,"(or":{"buffer)":1,"different":1}
,"buffer)":{"space":1}
,"space":{"therefore":1,"maxdirectmemorysize":1,"java":1,"crash":1}
,"therefore":{"possible":1}
,"possible":{"lead":1}
,"lead":{"paging":1,"memory":1}
,"even":{"memory-related":1,"memory":1}
,"errors":{"limit":1}
,"buffer":{"space":1,"memory":1,"large":1,"warning":1}
,"account":{"total":1,"additional":1}
,"total":{"physical":1}
,"available":{"amount":1}
,"amount":{"memory":1}
,"allotted":{"jvm":1}
,"object":{"heap":1}
,"portion":{"direct":1,"off-heap":1}
,"may":{"consume":1,"begin":1,"target":1,"swapped":1}
,"consume":{"addition":1}
,"addition":{"sure":1}
,"sure":{"allocate":1}
,"least":{"percent":1}
,"percent":{"off-heap":1,"cache":1}
,"data":{"maximize":1,"memory":1,"appears":1,"ram":1,"may":1,"frequently":1,"off-heap":1,"frequency":1,"memory)":1,"large":1,"disk":1,"5gb":1}
,"maximize":{"performance":1}
,"meta-data":{"purposes":1}
,"purposes":{"note":1}
,"users":{"direct":1,"review":1}
,"buffers":{"(such":1,"large":1}
,"(such":{"nio":1}
,"nio":{"certain":1}
,"certain":{"frameworks":1}
,"frameworks":{"containers)":1}
,"containers)":{"consider":1}
,"consider":{"allocating":1,"enabling":1}
,"allocating":{"additional":1,"buffers":1}
,"additional":{"direct":1,"usage":1}
,"usage":{"compressed":1,"memory":1,"swappiness":1}
,"compressed":{"references":1}
,"references":{"64-bit":1,"improve":1,"stored":1,"enabled":1}
,"64-bit":{"jvms":1,"mode":1}
,"jvms":{"running":1,"-xcompressedrefs":1}
,"running":{"java":1,"32-bit":1,"low":1}
,"update":{"higher":1}
,"higher":{"consider":1}
,"enabling":{"compressed":1}
,"improve":{"overall":1}
,"overall":{"performance":1,"cluster":1}
,"32gb":{"feature":1}
,"feature":{"causes":1}
,"causes":{"references":1}
,"stored":{"half":1}
,"half":{"size":1}
,"32-bit":{"mode":1}
,"mode":{"freeing":1,"retaining":1,"oracle":1}
,"freeing":{"substantial":1}
,"substantial":{"amounts":1,"off-heap":1}
,"amounts":{"heap":1,"data":1}
,"memory-intensive":{"applications":1}
,"applications":{"jvm":1}
,"however":{"remains":1,"note":1}
,"remains":{"64-bit":1}
,"retaining":{"advantages":1}
,"advantages":{"mode":1}
,"oracle":{"hotspot":1,"solaris":1}
,"hotspot":{"compressed":1,"-xx":1}
,"enabled":{"using":1}
,"using":{"option":1,"bigmemory":1}
,"option":{"-xx":1}
,"-xx":{"usecompressedoops":1,"uselargepages":1}
,"usecompressedoops":{"ibm":1}
,"ibm":{"jvms":1}
,"-xcompressedrefs":{"slow":1}
,"slow":{"off-heap":1}
,"based":{"configuration":1}
,"configuration":{"usage":1}
,"requirements":{"bigmemory":1}
,"bigmemory":{"allocate":1,"store":1,"benefits":1,"ehcache":1}
,"times":{"off-heap":1}
,"comes":{"pressure":1}
,"pressure":{"due":1}
,"due":{"over-allocation":1}
,"over-allocation":{"host":1}
,"host":{"may":1,"stop":1}
,"begin":{"paging":1}
,"thus":{"slowing":1}
,"slowing":{"down":1}
,"down":{"allocation":1}
,"situation":{"worsens":1,"degrading":1}
,"worsens":{"off-heap":1}
,"large":{"fit":1,"pages":1,"enough":1}
,"fit":{"memory":1,"off-heap":1}
,"quickly":{"deplete":1}
,"deplete":{"critical":1}
,"critical":{"system":1}
,"resources":{"ram":1}
,"swap":{"space":1,"data":1}
,"crash":{"host":1}
,"stop":{"situation":1}
,"degrading":{"off-heap":1}
,"time":{"measured":1}
,"measured":{"avoid":1}
,"avoid":{"allocating":1}
,"takes":{"1.5":1,"seconds":1}
,"1.5":{"seconds":1}
,"seconds":{"allocate":1,"jvm":1}
,"warning":{"issued":1}
,"issued":{"takes":1}
,"halted":{"system.exit":1}
,"system.exit":{"(or":1}
,"different":{"method":1}
,"method":{"security":1}
,"security":{"manager":1}
,"manager":{"prevents":1}
,"prevents":{"this)":1}
,"this)":{"prevent":1}
,"prevent":{"jvm":1}
,"shutdown":{"15-second":1}
,"15-second":{"delay":1}
,"delay":{"occurred":1}
,"occurred":{"net.sf.ehcache.offheap.donothaltoncriticalallocationdelay":1}
,"net.sf.ehcache.offheap.donothaltoncriticalallocationdelay":{"system":1}
,"property":{"true":1,"net.sf.ehcache.offheap.cache_name.config.idealmaxsegmentsize":1}
,"true":{"case":1}
,"case":{"error":1}
,"error":{"logged":1}
,"logged":{"instead":1}
,"instead":{"swappiness":1}
,"swappiness":{"huge":1,"size":1}
,"huge":{"pages":1}
,"pages":{"swap":1,"general":1,"(also":1,"large":1,"superpages)":1,"configuring":1}
,"low":{"purpose":1}
,"purpose":{"optimization":1}
,"optimization":{"data":1}
,"appears":{"unused":1}
,"unused":{"may":1}
,"target":{"swapping":1}
,"swapping":{"bigmemory":1,"degrade":1}
,"swapped":{"swapping":1,"memory":1}
,"degrade":{"overall":1}
,"cluster":{"performance":1}
,"introducing":{"thrashing":1}
,"thrashing":{"condition":1}
,"condition":{"data":1}
,"frequently":{"moved":1}
,"moved":{"forth":1}
,"forth":{"back":1}
,"efficient":{"linux":1}
,"linux":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"oracle":1}
,"solaris":{"users":1}
,"review":{"configuration":1}
,"benefits":{"lowered":1}
,"lowered":{"swappiness":1}
,"(also":{"known":1}
,"known":{"big":1}
,"big":{"pages":1}
,"superpages)":{"settings":1}
,"settings":{"behaviors":1}
,"behaviors":{"vary":1}
,"vary":{"jvm":1}
,"uselargepages":{"-xx:largepagesizeinbytes=<size>":1}
,"-xx:largepagesizeinbytes=<size>":{"(where":1}
,"(where":{"<size>":1}
,"<size>":{"value":1}
,"value":{"allowed":1}
,"allowed":{"specific":1}
,"specific":{"cpus)":1}
,"cpus)":{"used":1}
,"used":{"control":1}
,"control":{"page":1}
,"page":{"size":1}
,"setting":{"affect":1}
,"affect":{"off-heap":1}
,"over-allocating":{"huge":1}
,"configuring":{"substantial":1}
,"starve":{"off-heap":1}
,"problems":{"maximum":1}
,"maximum":{"serialized":1}
,"serialized":{"size":1}
,"element":{"section":1}
,"applies":{"using":1}
,"ehcache":{"api":1}
,"api":{"unlike":1}
,"unlike":{"memory":1}
,"default":{"off-heap":1,"limits":1,"size":1}
,"4mb":{"limit":1}
,"classes":{"high":1,"string":1}
,"high":{"quality":1}
,"quality":{"hashcodes":1}
,"hashcodes":{"256kb":1,"built-in":1,"issues":1}
,"256kb":{"limit":1}
,"pathologically":{"bad":1}
,"bad":{"hashcodes":1}
,"built-in":{"classes":1}
,"string":{"java.lang.number":1}
,"java.lang.number":{"subclasses":1}
,"subclasses":{"long":1}
,"long":{"integer":1}
,"integer":{"high":1}
,"objects":{"expected":1}
,"expected":{"larger":1}
,"larger":{"default":1}
,"limits":{"override":1,"system":1}
,"override":{"default":1}
,"net.sf.ehcache.offheap.cache_name.config.idealmaxsegmentsize":{"size":1}
,"example":{"net.sf.ehcache.offheap.com.company.domain.state.config.idealmaxsegmentsize=30m":1,"tests":1}
,"net.sf.ehcache.offheap.com.company.domain.state.config.idealmaxsegmentsize=30m":{"reducing":1}
,"reducing":{"faulting":1}
,"faulting":{"memory":1}
,"holds":{"hotset":1}
,"hotset":{"subset)":1}
,"subset)":{"entire":1}
,"entire":{"data":1}
,"enough":{"hold":1}
,"hold":{"entire":1}
,"frequency":{"misses":1}
,"misses":{"(get":1,"turn":1,"off-heap":1,"reached":1}
,"(get":{"operations":1}
,"fail":{"find":1}
,"find":{"data":1}
,"memory)":{"begins":1}
,"begins":{"rise":1}
,"rise":{"data":1}
,"forcing":{"gets":1}
,"gets":{"fetch":1}
,"fetch":{"data":1}
,"(called":{"faulting)":1}
,"faulting)":{"misses":1}
,"turn":{"raise":1}
,"raise":{"latency":1}
,"latency":{"lower":1}
,"lower":{"performance":1}
,"tests":{"4gb":1}
,"4gb":{"data":1,"1.7":1}
,"5gb":{"off-heap":1}
,"recorded":{"misses":1}
,"reduced":{"4gb":1}
,"1.7":{"percent":1}
,"cache":{"operations":1}
,"resulted":{"misses":1}
,"3gb":{"misses":1}
,"reached":{"percent":1}
}
;Search.control.loadWordPairs(pairs);
