var pairs =
{
"performing":{"standalone":1}
,"standalone":{"installation":1,"product":1,"bigmemory":1}
,"installation":{"bigmemory":1,"using":1}
,"bigmemory":{"max":1,"write":1,"localrestartable":1,"information":1,"basics":1}
,"max":{"section":1,"intend":1,"standalone":1,"part":1,"easy":1,"kit":1,"apis\u002Fehcache\u002Flib\u002Fslf4j-api-<version>":1,"logging":1,"license":1,"home":1,"download":1,"uses":1,"create":1,"configuration":1,"find":1}
,"section":{"describes":1,"installation":1}
,"describes":{"perform":1}
,"perform":{"installation":1}
,"intend":{"bigmemory":1}
,"product":{"plan":1,"instead":1}
,"plan":{"install":1}
,"install":{"bigmemory":1}
,"part":{"software":1}
,"software":{"bundle":1,"rather":1,"installer":1}
,"bundle":{"software":1}
,"rather":{"standalone":1}
,"instead":{"software":1}
,"installer":{"described":1,"performing":1}
,"described":{"section":1,"working":1}
,"using":{"software":1,"jdk":1,"-xmx":1}
,"easy":{"downloading":1}
,"downloading":{"kit":1}
,"kit":{"ensuring":1,"download":1,"packaged":1,"application\u0027s":1,"example":1,"-xx:maxdirectmemorysize":1}
,"ensuring":{"correct":1}
,"correct":{"files":1}
,"files":{"application\u0027s":1,"bigmemory":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"platform":1,"apis\u002Fehcache\u002Flib\u002Fehcache-ee-<version>":1,"explicitly":1,"information":1}
,"platform":{"requirement":1}
,"requirement":{"using":1}
,"jdk":{"1.6":1}
,"1.6":{"higher":1}
,"higher":{"install":1}
,"download":{"http:\u002F\u002Fterracotta.org\u002Fdownloads\u002Fbigmemorymax":1,"alternatively":1}
,"http:\u002F\u002Fterracotta.org\u002Fdownloads\u002Fbigmemorymax":{"kit":1}
,"packaged":{"tar.gz":1}
,"tar.gz":{"file":1}
,"file":{"unpack":1,"contains":1,"bridge":1,"bigmemory":1,"called":1,"application\u0027s":1,"described":1,"update":1,"top-level":1,"config-samples":1}
,"unpack":{"command":1}
,"command":{"line":1}
,"line":{"appropriate":1}
,"appropriate":{"decompression":1}
,"decompression":{"application":1}
,"application":{"add":1,"example":1}
,"add":{"following":1,"license":1}
,"following":{"jars":1}
,"jars":{"kit":1}
,"apis\u002Fehcache\u002Flib\u002Fehcache-ee-<version>":{".jar":1}
,".jar":{"file":1}
,"contains":{"api":1,"libraries":1}
,"api":{"bigmemory":1}
,"apis\u002Fehcache\u002Flib\u002Fslf4j-api-<version>":{".jar":1}
,"bridge":{"logging":1}
,"logging":{"facade":1,"framework":1}
,"facade":{"bigmemory":1}
,"framework":{"apis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-<version>":1}
,"apis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-<version>":{".jar":1}
,"libraries":{"terracotta":1}
,"terracotta":{"server":1,"license":1,"element":1}
,"server":{"array":1,"-->":1}
,"array":{"save":1,"-->":1,"configuration":1}
,"save":{"bigmemory":1}
,"license":{"key":1,"files":1}
,"key":{"file":1}
,"home":{"directory":1}
,"directory":{"file":1,"bigmemory":1}
,"called":{"terracotta-license.key":1}
,"terracotta-license.key":{"attached":1}
,"attached":{"email":1}
,"email":{"received":1}
,"received":{"registering":1}
,"registering":{"bigmemory":1}
,"alternatively":{"add":1}
,"explicitly":{"specify":1}
,"specify":{"location":1}
,"location":{"license":1}
,"working":{"terracotta":1}
,"uses":{"ehcache":1}
,"ehcache":{"user-facing":1}
,"user-facing":{"interface":1}
,"interface":{"configure":1}
,"configure":{"bigmemory":1}
,"create":{"ehcache.xml":1}
,"ehcache.xml":{"configuration":1,"file":1}
,"configuration":{"file":1,"case":1,"retrieved":1,"options":1,"guide":1,"plus":1}
,"update":{"provided":1}
,"provided":{"config-samples\u002Fdirectory":1}
,"config-samples\u002Fdirectory":{"bigmemory":1}
,"example":{"<ehcache":1,"-xx:maxdirectmemorysize=9g":1,"-xmx1g":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"mybigmemorymaxconfig":1,"mybigmemorymaxstore":1}
,"mybigmemorymaxconfig":{"<!--tell":1}
,"<!--tell":{"bigmemory":1}
,"write":{"data":1}
,"data":{"disk":1,"without":1,"managed":1}
,"disk":{"-->":1}
,"-->":{"<diskstore":1,"<cache":1,"<persistence":1,"<terracotta\u002F>":1,"<terracottaconfig":1}
,"<diskstore":{"path=\u0022\u002Fpath\u002Fto\u002Fmy\u002Fdisk\u002Fstore\u002Fdirectory":1}
,"path=\u0022\u002Fpath\u002Fto\u002Fmy\u002Fdisk\u002Fstore\u002Fdirectory":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<!--set":1,"<!--include":1}
,"<!--set":{"\u0027maxbyteslocaloffheap":1}
,"\u0027maxbyteslocaloffheap":{"amount":1}
,"amount":{"off-heap":1,"bigmemory":1}
,"off-heap":{"in-memory":1,"storage":1}
,"in-memory":{"storage":1,"data":1}
,"storage":{"want":1,"tiers":1,"specified":1}
,"want":{"memory":1}
,"memory":{"invisible":1,"jvm":1,"usage":1}
,"invisible":{"java":1}
,"java":{"garbage":1,"option":1}
,"garbage":{"collector":1,"collection":1}
,"collector":{"providing":1}
,"providing":{"gigabytes":1}
,"gigabytes":{"terabytes":1}
,"terabytes":{"in-memory":1}
,"without":{"garbage":1}
,"collection":{"pauses":1}
,"pauses":{"-->":1}
,"<cache":{"name=\u0022":1}
,"mybigmemorymaxstore":{"maxbyteslocalheap=\u0022":1}
,"maxbyteslocalheap=\u0022":{"512m":1}
,"512m":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"<!--tell":1}
,"localrestartable":{"persistence":1,"\u0022\u002F>":1}
,"persistence":{"strategy":1}
,"strategy":{"fast":1}
,"fast":{"restart":1}
,"restart":{"(optional)":1}
,"(optional)":{"-->":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"localrestartable":1}
,"<!--include":{"terracotta":1}
,"element":{"data":1}
,"managed":{"client":1}
,"client":{"terracotta":1}
,"<terracotta\u002F>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"<!--specify":1}
,"<!--specify":{"find":1}
,"find":{"server":1,"resources":1}
,"case":{"configuration":1}
,"retrieved":{"local":1}
,"local":{"server":1}
,"<terracottaconfig":{"url=\u0022":1}
,"url=\u0022":{"localhost:9510":1}
,"localhost:9510":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"place":1}
,"place":{"ehcache.xml":1}
,"top-level":{"classpath":1}
,"information":{"configuration":1,"step":1}
,"options":{"configuring":1}
,"configuring":{"storage":1}
,"tiers":{"bigmemory":1}
,"guide":{"reference":1,"allocate":1}
,"reference":{"ehcache.xml":1}
,"config-samples":{"directory":1}
,"-xx:maxdirectmemorysize":{"java":1}
,"option":{"allocate":1,"accommodate":1}
,"allocate":{"enough":1,"least":1}
,"enough":{"direct":1,"heap":1,"extra":1}
,"direct":{"memory":1}
,"jvm":{"accommodate":1,"bigmemory":1}
,"accommodate":{"off-heap":1,"on-heap":1}
,"specified":{"configuration":1}
,"plus":{"least":1,"enough":1}
,"least":{"250mb":1,"enough":1}
,"250mb":{"allow":1}
,"allow":{"direct":1}
,"usage":{"occur":1}
,"occur":{"application":1}
,"-xx:maxdirectmemorysize=9g":{"maxdirectmemorysize":1}
,"maxdirectmemorysize":{"amount":1}
,"step":{"allocating":1}
,"allocating":{"direct":1}
,"heap":{"using":1,"run":1}
,"-xmx":{"java":1}
,"on-heap":{"storage":1}
,"extra":{"heap":1}
,"run":{"rest":1}
,"rest":{"application":1}
,"-xmx1g":{"finally":1}
,"finally":{"necessary":1}
,"necessary":{"define":1}
,"define":{"java_home":1}
,"java_home":{"environment":1}
,"environment":{"variable":1}
,"variable":{"learn":1}
,"learn":{"bigmemory":1}
,"basics":{"tutorials":1}
,"tutorials":{"look":1}
,"look":{"code":1}
,"code":{"samples":1}
,"samples":{"examples":1}
,"examples":{"employ":1}
,"employ":{"various":1}
,"various":{"features":1}
,"features":{"capabilities":1}
,"capabilities":{"bigmemory":1}
,"resources":{"online":1}
,"online":{"documentation":1}
,"documentation":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
