var pairs =
{
"default":{"security":1}
,"security":{"default":1,"consists":1,"controls":1,"bigmemory":1,"guide":1}
,"consists":{"built-in":1}
,"built-in":{"role-based":1}
,"role-based":{"accounts":1}
,"accounts":{"used":1}
,"used":{"log":1}
,"log":{"tmc":1}
,"tmc":{"level":1,"appropriate":1,"managed":1,"perform":1}
,"level":{"security":1}
,"controls":{"access":1}
,"access":{"tmc":1,"trusted":1}
,"appropriate":{"environments":1}
,"environments":{"components":1}
,"components":{"including":1}
,"including":{"tmc":1}
,"managed":{"agents":1}
,"agents":{"custom":1,"remain":1}
,"custom":{"rich":1}
,"rich":{"internet":1}
,"internet":{"applications":1}
,"applications":{"(rias)":1}
,"(rias)":{"protected":1}
,"protected":{"networks":1}
,"networks":{"internal":1}
,"internal":{"network":1}
,"network":{"behind":1}
,"behind":{"firewall":1}
,"firewall":{"access":1}
,"trusted":{"example":1}
,"example":{"environment":1}
,"environment":{"note":1}
,"note":{"connections":1}
,"connections":{"tmc":1,"tab":1}
,"remain":{"unsecured":1}
,"unsecured":{"optionally":1}
,"optionally":{"integration":1}
,"integration":{"ldap":1}
,"ldap":{"microsoft":1,"active":1}
,"microsoft":{"active":1}
,"active":{"directory":1,"directory)":1}
,"directory":{"available":1}
,"available":{"information":1}
,"information":{"initial":1,"tsa":1}
,"initial":{"setup":1}
,"setup":{"tms\u002Ftmc":1}
,"tms\u002Ftmc":{"authentication":1,"user":1,"secure":1,"cluster":1}
,"authentication":{"configured":1}
,"configured":{"(whether":1}
,"(whether":{".ini":1}
,".ini":{"file":1}
,"file":{"ldap":1}
,"directory)":{"non-administrator":1}
,"non-administrator":{"user":1}
,"user":{"logs":1,"unable":1,"tms":1,"perform":1}
,"logs":{"tms\u002Ftmc":1}
,"unable":{"administration":1}
,"administration":{"panel":1}
,"panel":{"tmc":1}
,"perform":{"administrative":1}
,"administrative":{"tasks":1}
,"tasks":{"shutting":1,"cluster":1}
,"shutting":{"down":1}
,"down":{"server":1}
,"server":{"however":1}
,"however":{"cluster":1}
,"cluster":{"secured":1,"words":1,"user":1,"rest":1,"unsure":1}
,"secured":{"non-administrator":1,"connections":1}
,"tms":{"rest":1}
,"rest":{"api":1}
,"api":{"perform":1,"prevent":1}
,"words":{"secure":1}
,"secure":{"tms\u002Ftmc":1,"tsa":1}
,"tsa":{"cluster":1,"security":1}
,"prevent":{"secure":1}
,"unsure":{"whether":1}
,"whether":{"cluster":1}
,"tab":{"settings":1}
,"settings":{"window":1}
,"window":{"look":1}
,"look":{"locked":1}
,"locked":{"padlock":1}
,"padlock":{"icon":1}
,"icon":{"next":1}
,"next":{"connection":1}
,"connection":{"information":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
}
;Search.control.loadWordPairs(pairs);
