var pairs =
{
"connecting":{"via":1}
,"via":{"jmx":1,"rmi":1}
,"jmx":{"section":1,"jmx":1,"mbeans":1,"monitoring":1,"configured":1,"via":1,"access":1,"either":1,"listen":1,"beans":1,"terracotta":1}
,"section":{"describes":1}
,"describes":{"connect":1}
,"connect":{"via":1,"monitoring":1,"test-cache-1":1}
,"mbeans":{"display":1,"within":1}
,"display":{"statistics":1,"overall":1}
,"statistics":{"jmx":1,"orchestrators":1,"overall":1,"cache":1,"master":1,"particular":1,"cache\u0027s":1,"configured":1,"client":1}
,"monitoring":{"application":1}
,"application":{"programmatically":1,"orchestrator":1}
,"programmatically":{"access":1}
,"access":{"statistics":1,"jmx":1,"remote":1}
,"configured":{"orchestrator":1,"wan.xml":1}
,"orchestrator":{"process":1,"running":1}
,"process":{"listen":1,"jmx":1,"add":1,"started":1,"else":1,"directly":1,"using":1,"via":1}
,"listen":{"jmx":1,"rmi":1}
,"rmi":{"setting":1,"orchestrator":1,"convenience":1,"may":1,"port":1}
,"setting":{"connect":1}
,"either":{"following":1}
,"following":{"ways":1,"arguments":1,"objectname":1}
,"ways":{"via":1}
,"add":{"following":1}
,"arguments":{"java_opts":1}
,"java_opts":{"environment":1,"inside":1}
,"environment":{"variable":1}
,"variable":{"executing":1,"visible":1}
,"executing":{"start-wan.sh":1}
,"start-wan.sh":{"java_opts=\u0022-dcom.sun.management.jmxremote.port=<number>":1}
,"java_opts=\u0022-dcom.sun.management.jmxremote.port=<number>":{"-dcom.sun.management.jmxremote.authenticate=false":1}
,"-dcom.sun.management.jmxremote.authenticate=false":{"-dcom.sun.management.jmxremote.ssl=false":1}
,"-dcom.sun.management.jmxremote.ssl=false":{"additional":1}
,"additional":{"orchestrator":1}
,"started":{"machine":1}
,"machine":{"fail":1}
,"fail":{"address":1}
,"address":{"error":1}
,"error":{"java_opts":1}
,"visible":{"thus":1}
,"thus":{"java_opts":1}
,"inside":{"script":1,"wan-core.jar":1}
,"script":{"starts":1}
,"starts":{"process":1}
,"else":{"port":1}
,"port":{"number":1,"replica":1,"1234":1,"9999":1}
,"number":{"changed":1}
,"changed":{"communicating":1}
,"communicating":{"orchestrator":1}
,"directly":{"simply":1}
,"simply":{"start":1}
,"start":{"wan":1}
,"wan":{"region":1}
,"region":{"connect":1}
,"using":{"jmx":1}
,"beans":{"display":1}
,"orchestrators":{"expose":1}
,"expose":{"mbean":1}
,"mbean":{"cache":1,"replica":1}
,"cache":{"mbean":1,"replicas":1,"displaying":1,"manager":1,"specifies":1,"enclosed":1,"test-cache-1":1,"append":1,"connect":1}
,"replica":{"once":1,"cache":1,"display":1,"example":1,"hostname":1}
,"once":{"connected":1}
,"connected":{"orchestrator":1}
,"terracotta":{"wan-specific":1,"maven":1}
,"wan-specific":{"mbeans":1}
,"within":{"org.terracotta.wan":1}
,"org.terracotta.wan":{"domain":1}
,"domain":{"display":1}
,"overall":{"state":1,"statistics":1,"cache-wide":1}
,"state":{"master":1}
,"master":{"cache":1}
,"replicas":{"particular":1,"following":1,"org.terracotta.wan:type=wan":1}
,"particular":{"replica":1}
,"displaying":{"overall":1,"statistics":1}
,"objectname":{"form":1,"displays":1,"follows":1}
,"form":{"display":1}
,"org.terracotta.wan:type=wan":{"cachemanager=\u0022":1}
,"cachemanager=\u0022":{"<name>":1,"test":1}
,"<name>":{"cache=\u0022":1,"cachemanager":1,"replica=<host_port>":1}
,"cache=\u0022":{"<name>":1,"test-cache-1":1}
,"cachemanager":{"specifies":1,"test":1}
,"specifies":{"name":1,"host":1}
,"name":{"cache\u0027s":1,"cache":1,"port":1}
,"cache\u0027s":{"cache":1,"replica":1}
,"manager":{"enclosed":1,"previous":1}
,"enclosed":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"cache":1,"example":1}
,"example":{"following":1,"myhost_1234":1,"orchestrator":1,"implementation":1}
,"displays":{"overall":1,"statistics":1}
,"cache-wide":{"statistics":1}
,"test-cache-1":{"cachemanager":1,"displaying":1,"replica=myhost_1234":1,"test":1,"\u002F\u002Fget":1}
,"test":{"org.terracotta.wan:type=wan":1,"cache=\u0022":1,"cache":1,"test-cache-1":1}
,"append":{"replica=<host_port>":1}
,"replica=<host_port>":{"objectname":1,"<host_port>":1}
,"follows":{"org.terracotta.wan:type=wan":1}
,"<host_port>":{"specifies":1}
,"host":{"name":1}
,"myhost_1234":{"enclose":1}
,"enclose":{"value":1}
,"value":{"quotation":1,"(i.e":1,"change)":1,"certain":1,"updates":1,"cached":1}
,"hostname":{"myhost":1}
,"myhost":{"listens":1}
,"listens":{"port":1}
,"1234":{"(as":1}
,"(as":{"configured":1}
,"wan.xml":{"replica)":1}
,"replica)":{"org.terracotta.wan:type=wan":1}
,"replica=myhost_1234":{"programmatic":1}
,"programmatic":{"access":1}
,"convenience":{"classes":1}
,"classes":{"added":1,"inside":1}
,"added":{"programmatic":1}
,"remote":{"statistics":1}
,"may":{"rmistatisticconnection":1}
,"rmistatisticconnection":{"class":1,"=new":1,"localhost":1}
,"class":{"example":1}
,"running":{"localhost":1}
,"localhost":{"rmi":1,"9999":1}
,"9999":{"cache":1,"test":1}
,"previous":{"examples":1}
,"examples":{"\u002F\u002Fcreate":1}
,"\u002F\u002Fcreate":{"connection":1}
,"connection":{"statisticconnection":1,"rmistatisticsconnection.close":1}
,"statisticconnection":{"rmistatisticconnection":1}
,"=new":{"rmistatisticconnection":1}
,"\u002F\u002Fget":{"statistic":1}
,"statistic":{"gauge":1,"system.out.println":1}
,"gauge":{"<string>":1}
,"<string>":{"=rmistatisticconnection.getstatistic":1}
,"=rmistatisticconnection.getstatistic":{"(statisticname.config_replication_mode)":1}
,"(statisticname.config_replication_mode)":{"\u002F\u002Fdo":1}
,"\u002F\u002Fdo":{"something":1}
,"something":{"statistic":1}
,"system.out.println":{"(g.getvalue":1}
,"(g.getvalue":{"())":1}
,"())":{"\u002F\u002Fclose":1}
,"\u002F\u002Fclose":{"connection":1}
,"rmistatisticsconnection.close":{"gauges":1}
,"gauges":{"whose":1}
,"whose":{"values":1}
,"values":{"non-numeric":1,"numeric":1}
,"non-numeric":{"calling":1}
,"calling":{"getvalue":1}
,"getvalue":{"method":1,"eventually":1}
,"method":{"again":1}
,"again":{"fetch":1}
,"fetch":{"latest":1}
,"latest":{"value":1}
,"(i.e":{"call":1}
,"call":{"loop":1}
,"loop":{"expect":1}
,"expect":{"value":1,"getvalue":1}
,"change)":{"statistics":1}
,"client":{"classes":1}
,"wan-core.jar":{"order":1,"terracotta":1}
,"order":{"pull":1}
,"pull":{"wan-core.jar":1}
,"maven":{"plugin":1}
,"plugin":{"dependency":1}
,"dependency":{"gauges":1}
,"numeric":{"expect":1}
,"eventually":{"return":1}
,"return":{"recent":1}
,"recent":{"value":1}
,"certain":{"delay":1}
,"delay":{"depending":1}
,"depending":{"cluster\u0027s":1}
,"cluster\u0027s":{"configuration":1}
,"configuration":{"example":1}
,"implementation":{"throttle":1}
,"throttle":{"value":1}
,"updates":{"default":1,"place":1}
,"default":{"value":1}
,"cached":{"seconds":1}
,"seconds":{"matter":1}
,"matter":{"actual":1}
,"actual":{"updates":1}
,"place":{"during":1}
,"during":{"interval":1}
}
;Search.control.loadWordPairs(pairs);
