var pairs =
{
"bigmemory":{"hybrid":1,"max":1,"terracotta":1}
,"hybrid":{"bigmemory":1,"optional":1,"data":1,"(though":1,"allows":1,"different":1,"overflow":1}
,"optional":{"extension":1}
,"extension":{"bigmemory":1}
,"max":{"enables":1}
,"enables":{"scaling":1}
,"scaling":{"economical":1}
,"economical":{"solid-state":1}
,"solid-state":{"drive":1}
,"drive":{"(ssd)":1}
,"(ssd)":{"flash":1}
,"flash":{"memory":1,"disk":1}
,"memory":{"motionless":1,"(dram)":1,"means":1,"provides":1,"providing":1,"data":1}
,"motionless":{"disks":1}
,"disks":{"conjunction":1,"although":1}
,"conjunction":{"conventional":1}
,"conventional":{"dynamic":1,"hard":1}
,"dynamic":{"random-access":1}
,"random-access":{"memory":1}
,"(dram)":{"memory":1}
,"means":{"cache":1}
,"cache":{"size":1,"performs":1,"keys":1}
,"size":{"exceed":1,"cache":1}
,"exceed":{"available":1}
,"available":{"off-heap":1,"version":1}
,"off-heap":{"memory":1,"pushed":1}
,"provides":{"predictable":1}
,"predictable":{"low":1,"performance":1,"optimized":1}
,"low":{"latency":1}
,"latency":{"large":1}
,"large":{"scale":1}
,"scale":{"manages":1}
,"manages":{"data":1}
,"data":{"flow":1,"stored":1,"closer":1,"disk":1,"ssd\u002Fflash":1,"fit":1}
,"flow":{"seamlessly":1}
,"seamlessly":{"automatically":1}
,"automatically":{"dram":1}
,"dram":{"flash":1,"in-memory":1}
,"disk":{"according":1,"comes":1,"bigmemory":1,"available":1,"manages":1,"hence":1}
,"according":{"size":1}
,"performs":{"faster":1}
,"faster":{"conventional":1}
,"hard":{"disks":1}
,"although":{"quite":1}
,"quite":{"fast":1}
,"fast":{"pure":1,"restart":1}
,"pure":{"dram":1}
,"in-memory":{"solution":1}
,"solution":{"supports":1}
,"supports":{"searching":1}
,"searching":{"fast":1}
,"restart":{"backup":1,"technology":1}
,"backup":{"recovery":1}
,"recovery":{"web":1}
,"web":{"sessions":1}
,"sessions":{"quartz":1}
,"quartz":{"wan":1}
,"wan":{"replication":1}
,"replication":{"works":1}
,"works":{"industry-standard":1,"terracotta":1}
,"industry-standard":{"ssd":1}
,"ssd":{"devices":1,"works":1,"usage":1}
,"devices":{"popular":1}
,"popular":{"vendors":1}
,"vendors":{"fusion":1}
,"fusion":{"intel":1}
,"intel":{"ssd":1}
,"terracotta":{"servers":1}
,"servers":{"using":1,"keeping":1}
,"using":{"bigmemory":1,"hybrid":1}
,"stored":{"ssd\u002Fflash":1,"off-heap":1}
,"ssd\u002Fflash":{"drives":1,"predictable":1}
,"drives":{"keys":1}
,"keys":{"stored":1,"disk":1}
,"providing":{"optimal":1}
,"optimal":{"performance":1}
,"performance":{"using":1,"penalty":1,"cache":1,"less":1}
,"(though":{"option":1}
,"option":{"store":1}
,"store":{"cache":1,"data":1}
,"comes":{"performance":1}
,"penalty":{"recommended)":1}
,"recommended)":{"figure":1}
,"figure":{"bigmemory":1}
,"allows":{"expand":1}
,"expand":{"bigmemory":1}
,"keeping":{"data":1}
,"closer":{"application":1}
,"application":{"increased":1}
,"increased":{"transactions":1}
,"transactions":{"per":1}
,"per":{"second":1}
,"second":{"(tps)":1}
,"(tps)":{"bigmemory":1}
,"different":{"overflow":1}
,"overflow":{"disk":1}
,"version":{"4.1":1,"3.7":1}
,"4.1":{"available":1}
,"3.7":{"leverages":1}
,"leverages":{"bigmemory\u0027s":1}
,"bigmemory\u0027s":{"fast":1}
,"technology":{"depends":1}
,"depends":{"upon":1}
,"upon":{"berkeley":1}
,"berkeley":{"store":1}
,"fit":{"off-heap":1}
,"pushed":{"disk":1}
,"hence":{"performance":1}
,"less":{"predictable":1}
,"optimized":{"ssd":1}
,"usage":{"optimization":1}
,"optimization":{"done":1}
,"done":{"ssds":1}
}
;Search.control.loadWordPairs(pairs);
