var pairs =
{
"cross-language":{"connector":1,"clients":1,"(cl)":1}
,"connector":{"security":1,"connector":1,"bigmemory":1,"client":1,"referred":1}
,"security":{"note":1,"links":1,"guide":1,"bigmemory":1,"setup":1,"tsa":1}
,"note":{"brief":1}
,"brief":{"overview":1}
,"overview":{"terracotta":1}
,"terracotta":{"security":1,"server":1,"server)":1}
,"links":{"individual":1}
,"individual":{"topics":1}
,"topics":{"bigmemory":1}
,"bigmemory":{"max":1,"cross-language":1,".net":1}
,"max":{"security":1}
,"guide":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"ssl":1}
,"ssl":{"security":1}
,"clients":{"requires":1}
,"requires":{"setup":1}
,"setup":{"two":1,"connection":1,"application":1}
,"two":{"main":1}
,"main":{"connections":1}
,"connections":{"terracotta":1}
,"server":{"array":1,"client":1,"(the":1,"connector":1,"referred":1}
,"array":{"(tsa)":1}
,"(tsa)":{"cross-language":1}
,"(cl)":{"connector":1}
,".net":{"client":1}
,"client":{"connector":1,"tsa":1,"terracotta":1}
,"tsa":{"security":1,"connector":1}
,"connection":{"setup":1}
,"application":{"server":1}
,"server)":{"terracotta":1}
,"(the":{"app":1}
,"app":{"server":1}
,"referred":{"terracotta":1,"l2.)":1}
,"l2.)":{"information":1}
,"information":{"security":1}
}
;Search.control.loadWordPairs(pairs);
