var pairs =
{
"configuring":{"robust":1,"nonstop":1}
,"robust":{"distributed":1,"typically":1}
,"distributed":{"in-memory":1}
,"in-memory":{"data":1}
,"data":{"sets":1,"system":1}
,"sets":{"making":1}
,"making":{"bigmemory":1}
,"bigmemory":{"max":1,"hybrid":1,"terracotta":1}
,"max":{"in-memory":1,"high-availability":1,"administrator":1}
,"system":{"robust":1}
,"typically":{"combination":1}
,"combination":{"ehcache":1}
,"ehcache":{"configuration":1,"node":1,"nodes":1}
,"configuration":{"terracotta":1,"architecture":1}
,"terracotta":{"configuration":1,"cluster":1,"server":1,"servers":1}
,"architecture":{"information":1,"design":1}
,"information":{"following":1,"configuring":1,"bigmemory":1}
,"following":{"documentation":1}
,"documentation":{"nonstop":1}
,"nonstop":{"caches":1,"cache":1}
,"caches":{"configure":1,"specified":1}
,"configure":{"caches":1,"nodes":1}
,"specified":{"action":1}
,"action":{"ehcache":1}
,"node":{"appears":1}
,"appears":{"disconnected":1}
,"disconnected":{"cluster":1}
,"cluster":{"information":1,"allow":1,"new":1,"configure":1,"provides":1}
,"cache":{"rejoin":1}
,"rejoin":{"cluster":1}
,"allow":{"ehcache":1}
,"nodes":{"rejoin":1,"ride":1}
,"new":{"clients":1}
,"clients":{"disconnected":1}
,"high-availability":{"guide":1}
,"guide":{"high":1,"architecture":1,"bigmemory":1}
,"high":{"availability":1}
,"availability":{"terracotta":1}
,"ride":{"network":1}
,"network":{"interruptions":1}
,"interruptions":{"long":1}
,"long":{"java":1}
,"java":{"garbage":1}
,"garbage":{"collection":1}
,"collection":{"cycles":1}
,"cycles":{"connect":1}
,"connect":{"backup":1}
,"backup":{"terracotta":1}
,"server":{"information":1}
,"design":{"cluster":1}
,"provides":{"failover":1}
,"failover":{"information":1}
,"hybrid":{"extend":1,"storage":1}
,"extend":{"bigmemory":1}
,"servers":{"hybrid":1}
,"storage":{"include":1}
,"include":{"ssd":1}
,"ssd":{"flash":1}
,"flash":{"technologies":1}
,"technologies":{"dram":1}
,"dram":{"information":1}
,"administrator":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
