var pairs =
{
"managing":{"web":1}
,"web":{"sessions":1}
,"sessions":{"using":1,"start":1,"mbeans":1,"expired":1,"long":1,"exist":1,"cache":1,"created":1,"creation":1}
,"using":{"jmx":1}
,"jmx":{"terracotta":1,"mbeans":1,"monitoring":1,"web":1}
,"terracotta":{"exposes":1,"server":1}
,"exposes":{"jmx":1}
,"mbeans":{"gather":1,"following":1,"mbean":1}
,"gather":{"statistics":1}
,"statistics":{"view":1,"using":1}
,"view":{"statistics":1}
,"monitoring":{"application":1}
,"application":{"jconsole":1,"server":1,"waits":1}
,"jconsole":{"visualvm":1}
,"visualvm":{"jmx":1}
,"start":{"management":1}
,"management":{"console":1}
,"console":{"connect":1,"below":1}
,"connect":{"application":1}
,"server":{"console":1,"store":1,"array":1}
,"below":{"displays":1}
,"displays":{"web":1}
,"following":{"table":1}
,"table":{"describes":1}
,"describes":{"web":1}
,"mbean":{"data":1}
,"data":{"type":1}
,"type":{"description":1}
,"description":{"average":1}
,"average":{"session":1,"local":1}
,"session":{"lifetime":1,"size":1,"objects":1,"locking":1,"timeout":1,"waits":1,"creation":1}
,"lifetime":{"integer":1,"(in":1,"sessions":1}
,"integer":{"average":1,"maximum":1,"minimum":1,"number":1}
,"local":{"session":1,"hit":1,"memory":1}
,"(in":{"seconds)":1,"bytes)":1}
,"seconds)":{"@return":1}
,"@return":{"average":1,"hit":1,"maximum":1,"minimum":1}
,"expired":{"average":1,"minimum":1,"nonstop":1}
,"size":{"long":1,"(in":1}
,"long":{"average":1,"total":1,"maximum":1,"number":1,"rate":1}
,"bytes)":{"concurrency":1}
,"concurrency":{"(integer)":1,"explicitly":1}
,"(integer)":{"number":1}
,"number":{"segments":1,"sessions":1,"live":1,"bytes":1,"milliseconds":1,"session":1,"seconds":1,"represents":1}
,"segments":{"map":1}
,"map":{"backing":1}
,"backing":{"underlying":1}
,"underlying":{"server":1}
,"store":{"managed":1}
,"managed":{"terracotta":1}
,"array":{"concurrency":1,"blocking":1}
,"explicitly":{"(or":1}
,"(or":{"system":1}
,"system":{"selects":1}
,"selects":{"optimized":1}
,"optimized":{"value":1}
,"value":{"context":1}
,"context":{"path":1,"global":1}
,"path":{"string":1,"servlet":1}
,"string":{"context":1}
,"servlet":{"context":1}
,"global":{"number":1}
,"total":{"number":1,"session":1,"local":1}
,"live":{"sessions":1}
,"exist":{"cluster":1}
,"cluster":{"hit":1,"ejected":1}
,"hit":{"ratio":1}
,"ratio":{"double":1,"sessions":1,"nan":1}
,"double":{"local":1}
,"cache":{"@return":1,"operation":1}
,"nan":{"unavailable":1}
,"unavailable":{"max":1}
,"max":{"bytes":1}
,"bytes":{"heap":1,"allowed":1}
,"heap":{"long":1,"tier":1}
,"maximum":{"number":1,"session":1,"local":1}
,"allowed":{"off-heap":1,"heap":1}
,"off-heap":{"tier":1}
,"tier":{"max":1,"maximum":1}
,"minimum":{"session":1,"local":1}
,"nonstop":{"timeout":1}
,"timeout":{"long":1,"configured":1,"seconds":1}
,"milliseconds":{"application":1}
,"waits":{"cache":1,"timing":1}
,"operation":{"return":1}
,"return":{"timing":1}
,"timing":{"timeout":1}
,"configured":{"number":1,"automatically":1,"sessions":1,"synchronously":1}
,"objects":{"local":1}
,"memory":{"rejoin":1}
,"rejoin":{"enabled":1,"cluster":1}
,"enabled":{"boolean":1,"session":1}
,"boolean":{"whether":1}
,"whether":{"client":1,"session":1,"configured":1}
,"client":{"configured":1}
,"automatically":{"rejoin":1}
,"ejected":{"session":1}
,"locking":{"boolean":1,"enabled":1}
,"seconds":{"integer":1,"session":1}
,"created":{"count":1,"locally":1,"previous":1}
,"count":{"long":1}
,"locally":{"initial":1}
,"initial":{"startup":1}
,"startup":{"sessions":1,"number":1}
,"creation":{"rate":1,"initial":1}
,"rate":{"long":1,"local":1}
,"represents":{"number":1}
,"previous":{"minute":1}
,"minute":{"synchronous":1}
,"synchronous":{"write":1}
,"write":{"boolean":1}
,"synchronously":{"flush":1}
,"flush":{"enclosed":1}
,"enclosed":{"changes":1}
,"changes":{"terracotta":1,"acknowledged":1}
,"blocking":{"unlocking":1}
,"unlocking":{"thread":1}
,"thread":{"until":1}
,"until":{"changes":1}
,"acknowledged":{"committed":1}
,"committed":{"total":1}
}
;Search.control.loadWordPairs(pairs);
