var pairs =
{
"transactional":{"caches":1,"cache\u0027s":1,"except":1,"cache":1}
,"caches":{"transactional":1,"add":1,"support":1,"slower":1,"due":1,"following":1,"strongly":1,"cannot":1,"modes":1,"dynamically":1,"transaction":1,"strict":1}
,"add":{"level":1}
,"level":{"safety":1}
,"safety":{"cached":1}
,"cached":{"data":1}
,"data":{"ensure":1,"external":1,"stores":1,"critical":1,"however":1,"accessed":1,"access":1,"sources":1,"preserved":1}
,"ensure":{"cached":1}
,"external":{"data":1}
,"stores":{"sync":1}
,"sync":{"distributed":1,"database":1}
,"distributed":{"caches":1}
,"support":{"java":1,"developer":1,"transactions":1,"jta":1,"common":1}
,"java":{"transaction":1}
,"transaction":{"api":1,"support":1,"case":1,"managers":1,"modes":1,"manager":1,"times":1}
,"api":{"(jta)":1}
,"(jta)":{"transactions":1}
,"transactions":{"resource":1,"may":1,"written":1}
,"resource":{"useful":1}
,"useful":{"jta":1}
,"jta":{"applications":1,"xaxa":1,"components":1}
,"applications":{"requiring":1}
,"requiring":{"caching":1}
,"caching":{"cached":1}
,"critical":{"persisted":1}
,"persisted":{"remain":1}
,"remain":{"consistent":1}
,"consistent":{"system":1,"transactional":1}
,"system":{"record":1}
,"record":{"data":1}
,"however":{"transactional":1,"preserved":1}
,"slower":{"non-transactional":1}
,"non-transactional":{"caches":1}
,"due":{"overhead":1}
,"overhead":{"having":1}
,"having":{"write":1}
,"write":{"transactionally":1,"underlying":1}
,"transactionally":{"transactional":1,"even":1}
,"following":{"restrictions":1}
,"restrictions":{"data":1}
,"accessed":{"transactionally":1}
,"even":{"read-only":1}
,"read-only":{"purposes":1}
,"purposes":{"encapsulate":1}
,"encapsulate":{"data":1}
,"access":{"begin":1}
,"begin":{"commit":1}
,"commit":{"statements":1,"fails":1}
,"statements":{"may":1}
,"may":{"necessary":1,"compatible":1,"fall":1}
,"necessary":{"certain":1}
,"certain":{"circumstances":1}
,"circumstances":{"(see":1,"result":1}
,"(see":{"example":1}
,"example":{"discussion":1}
,"discussion":{"spring":1}
,"spring":{"transaction":1}
,"developer":{"guide":1}
,"guide":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"copyonread":1,"choose":1}
,"copyonread":{"copyonwrite":1}
,"copyonwrite":{"enabled":1}
,"enabled":{"<cache>":1}
,"<cache>":{"attributes":1}
,"attributes":{"false":1}
,"false":{"default":1}
,"default":{"true":1}
,"true":{"caches":1}
,"strongly":{"consistent":1}
,"cache\u0027s":{"consistency":1}
,"consistency":{"attribute":1}
,"attribute":{"strong":1}
,"strong":{"nonstop":1}
,"nonstop":{"caches":1}
,"cannot":{"made":1}
,"made":{"transactional":1}
,"except":{"strict":1}
,"strict":{"mode":1,"full":1,"may":1}
,"mode":{"(xa_strict)":1,"attempt":1,"require":1,"write":1}
,"(xa_strict)":{"transactional":1}
,"modes":{"contain":1,"transactional":1,"mode":1}
,"contain":{"<nonstop>":1}
,"<nonstop>":{"sub-element":1}
,"sub-element":{"objects":1}
,"objects":{"stored":1}
,"stored":{"transactional":1}
,"cache":{"override":1,"data":1}
,"override":{"equals":1}
,"equals":{"hashcode":1}
,"hashcode":{"overriding":1,"possible":1}
,"overriding":{"equals":1}
,"possible":{"implementing":1}
,"implementing":{"element":1}
,"element":{"comparator":1}
,"comparator":{"caches":1}
,"dynamically":{"changed":1}
,"changed":{"bulk-load":1}
,"bulk-load":{"mode":1}
,"attempt":{"perform":1}
,"perform":{"transaction":1}
,"case":{"throw":1,"failure":1}
,"throw":{"cacheexception":1}
,"cacheexception":{"information":1}
,"information":{"transactional":1}
,"choose":{"three":1}
,"three":{"different":1}
,"different":{"modes":1}
,"full":{"support":1}
,"compatible":{"transaction":1}
,"managers":{"fully":1,"unlike":1}
,"fully":{"support":1}
,"xaxa":{"support":1}
,"common":{"jta":1}
,"components":{"likely":1}
,"likely":{"compatible":1,"faster":1}
,"unlike":{"strict":1}
,"fall":{"sync":1}
,"database":{"failure":1}
,"failure":{"(has":1,"local":1}
,"(has":{"recovery)":1}
,"recovery)":{"integrity":1}
,"integrity":{"cache":1}
,"preserved":{"local":1,"case":1}
,"local":{"local":1,"transactions":1,"store":1,"mode":1}
,"written":{"local":1}
,"store":{"likely":1,"synchronously":1}
,"faster":{"transaction":1}
,"require":{"transaction":1}
,"manager":{"synchronize":1}
,"synchronize":{"remote":1}
,"remote":{"data":1}
,"sources":{"integrity":1}
,"underlying":{"store":1}
,"synchronously":{"using":1}
,"using":{"pessimistic":1}
,"pessimistic":{"locking":1}
,"locking":{"certain":1}
,"result":{"deadlock":1}
,"deadlock":{"generates":1}
,"generates":{"deadlockexception":1}
,"deadlockexception":{"transaction":1,"(or":1}
,"times":{"commit":1}
,"fails":{"application":1}
,"application":{"catch":1,"code":1}
,"catch":{"deadlockexception":1}
,"(or":{"transactionexception)":1}
,"transactionexception)":{"call":1}
,"call":{"rollback":1}
,"rollback":{"deadlocks":1}
,"deadlocks":{"severe":1,"indicates":1}
,"severe":{"impact":1}
,"impact":{"performance":1}
,"performance":{"high":1}
,"high":{"number":1}
,"number":{"deadlocks":1}
,"indicates":{"need":1}
,"need":{"refactor":1}
,"refactor":{"application":1}
,"code":{"prevent":1}
,"prevent":{"races":1}
,"races":{"concurrent":1}
,"concurrent":{"threads":1}
,"threads":{"attempting":1}
,"attempting":{"update":1}
,"update":{"data":1}
}
;Search.control.loadWordPairs(pairs);
