var pairs =
{
"stopping":{"secured":1}
,"secured":{"server":1}
,"server":{"stop":1,"secure":1}
,"stop":{"server":1}
,"secure":{"terracotta":1}
,"terracotta":{"cluster":1}
,"cluster":{"using":1}
,"using":{"stop-tc-server":1}
,"stop-tc-server":{"script":1}
,"script":{"following":1}
,"following":{"arguments":1}
,"arguments":{"<tc-config-file>":1}
,"<tc-config-file>":{"valid":1}
,"valid":{"path":1}
,"path":{"self-signed":1}
,"self-signed":{"certificate":1,"certificates":1}
,"certificate":{"specified":1}
,"specified":{"server\u0027s":1,"admin":1}
,"server\u0027s":{"configuration":1}
,"configuration":{"file":1}
,"file":{"<username>":1}
,"<username>":{"-the":1}
,"-the":{"user":1}
,"user":{"specified":1}
,"admin":{"role":1}
,"role":{"<password>":1}
,"<password>":{"-this":1}
,"-this":{"flag":1}
,"flag":{"causes":1}
,"causes":{"invalid":1}
,"invalid":{"tms":1}
,"tms":{"ssl":1}
,"ssl":{"certificates":1}
,"certificates":{"ignored":1,"(ones":1}
,"ignored":{"option":1}
,"option":{"accept":1}
,"accept":{"self-signed":1}
,"(ones":{"signed":1}
,"signed":{"trusted":1}
,"trusted":{"ca)":1}
}
;Search.control.loadWordPairs(pairs);
