var pairs =
{
"creating":{"server":1,"self-signed":1}
,"server":{"certificates":1,"keystore":1,"following":1,"security":1,"configured":1,"running":1,"scripts":1,"certificate":1,"called":1,"exporting":1,"copy":1,"example":1,"truststore":1,"cluster":1,"create":1}
,"certificates":{"terracotta":1,"important":1,"less":1,"lack":1,"certificate":1,"signed":1,"need":1,"keystores":1,"details":1,"using":1,"java":1,"server":1,"chain":1,"import":1}
,"terracotta":{"server":1}
,"keystore":{"file":1,"java":1,"(jks)":1,"place":1,"import":1,"keystore":1,"already":1,"prompt":1,"entry":1,"explorer":1}
,"file":{"containing":1,"server":1,"used":1,"working":1,"cacerts":1}
,"containing":{"digital":1,"public-key":1,"every":1}
,"digital":{"certificate":1,"signature":1,"certificates":1}
,"certificate":{"associated":1,"chains":1,"authority":1,"keyed":1,"match":1,"(not":1,"already":1,"expires":1,"truststore":1,"server":1,"server2":1,"appears":1,"every":1}
,"associated":{"private":1}
,"private":{"key":1}
,"key":{"document":1,"passwords":1,"pair":1,"copy":1}
,"document":{"assumes":1,"used":1}
,"assumes":{"self-signed":1}
,"self-signed":{"certificates":1,"certificate":1}
,"important":{"security":1}
,"security":{"consideration":1,"details":1,"password":1,"requirements":1}
,"consideration":{"self-signed":1}
,"less":{"safe":1}
,"safe":{"ca-signed":1}
,"ca-signed":{"certificates":1}
,"lack":{"third-party":1}
,"third-party":{"identity":1}
,"identity":{"verification":1,"prompts":1}
,"verification":{"carry":1}
,"carry":{"digital":1}
,"signature":{"official":1}
,"official":{"organization":1}
,"organization":{"already":1}
,"already":{"policies":1,"stored":1,"exist":1}
,"policies":{"procedures":1}
,"procedures":{"place":1,"regarding":1,"outlined":1}
,"place":{"regarding":1,"server":1}
,"regarding":{"generation":1,"using":1}
,"generation":{"digital":1}
,"chains":{"including":1}
,"including":{"certificates":1,"-keyalg":1}
,"signed":{"certificate":1,"trusted":1}
,"authority":{"(ca)":1}
,"(ca)":{"follow":1}
,"follow":{"organization\u0027s":1}
,"organization\u0027s":{"policies":1}
,"using":{"digital":1,"self-signed":1,"java":1,"cacerts":1,"keytool":1,"client":1,"command":1}
,"need":{"adjust":1}
,"adjust":{"procedures":1}
,"outlined":{"document":1}
,"used":{"terracotta":1,"create":1,"export":1,"import":1,"clients":1}
,"following":{"conditions":1,"used":1,"command":1}
,"conditions":{"met":1}
,"met":{"certificates":1}
,"keystores":{"keystore":1,"truststores":1,"logical":1}
,"java":{"keystore":1,"keytool":1,"truststore":1}
,"(jks)":{"compatible":1}
,"compatible":{"jdk":1}
,"jdk":{"1.6":1,"documentation":1}
,"1.6":{"higher":1}
,"higher":{"certificate":1}
,"keyed":{"alias":1}
,"alias":{"named":1}
,"named":{"value":1}
,"value":{"<certificate>":1,"entered":1}
,"<certificate>":{"element":1}
,"element":{"server\u0027s":1}
,"server\u0027s":{"configuration":1,"hostname":1,"entry":1,"public-key":1,"public":1}
,"configuration":{"configure":1,"example":1,"hostname":1}
,"configure":{"server":1}
,"details":{"common":1,"using":1}
,"common":{"name":1}
,"name":{"(cn)":1,"contain":1,"-dname":1,"[unknown]":1}
,"(cn)":{"field":1,"match":1}
,"field":{"distinguished":1,"designating":1}
,"distinguished":{"name":1}
,"contain":{"hostname":1}
,"hostname":{"server":1,"matches":1,"address":1}
,"configured":{"configure":1}
,"password":{"securing":1,"words":1,"key":1,"javax.net.ssl.truststorepassword":1,"prompt":1}
,"securing":{"certificate":1}
,"match":{"keystore\u0027s":1,"field":1,"server\u0027s":1}
,"keystore\u0027s":{"main":1}
,"main":{"password":1}
,"words":{"store":1}
,"store":{"password":1}
,"passwords":{"identical":1}
,"identical":{"using":1}
,"(not":{"signed":1}
,"trusted":{"ca)":1}
,"ca)":{"create":1,"option":1}
,"create":{"custom":1,"creating":1,"public-private":1,"keystores":1,"keystore":1,"truststore":1,"single":1}
,"custom":{"truststore":1,"truststore\u0027s":1}
,"truststore":{"storing":1,"-note":1,"custom":1,"specified":1,"following":1,"every":1,"import":1,"containing":1,"-instead":1,"used":1,"keytool":1}
,"storing":{"public":1}
,"public":{"keys":1,"key":1}
,"keys":{"section":1,"(including":1}
,"section":{"exporting":1}
,"exporting":{"importing":1}
,"importing":{"certificates":1}
,"option":{"stopping":1,"left":1,"-trustcacerts":1}
,"stopping":{"server":1}
,"running":{"server":1}
,"scripts":{"keystore":1}
,"stored":{"keystore":1}
,"import":{"keystore":1,"server1":1,"refer":1}
,"exist":{"create":1}
,"keytool":{"testing":1,"command":1,"refers":1,"-genkey":1,"options":1,"jdk":1,"-export":1,"-import":1,"utility":1,"want":1}
,"testing":{"purposes":1}
,"purposes":{"intend":1}
,"intend":{"self-signed":1}
,"command":{"create":1,"keytool":1,"line":1}
,"public-private":{"key":1,"keys":1}
,"pair":{"command":1}
,"truststores":{"note":1,"keystores":1}
,"note":{"keytool":1,"values":1}
,"refers":{"truststores":1}
,"logical":{"difference":1}
,"difference":{"specifying":1}
,"specifying":{"custom":1}
,"-note":{"using":1}
,"cacerts":{"default":1,"wish":1}
,"default":{"java":1,"password":1,"dsa)":1,"90)":1}
,"specified":{"javax.net.ssl.truststore":1}
,"javax.net.ssl.truststore":{"system":1}
,"system":{"property":1}
,"property":{"case":1}
,"case":{"choose":1}
,"choose":{"reset":1}
,"reset":{"custom":1}
,"truststore\u0027s":{"default":1}
,"javax.net.ssl.truststorepassword":{"following":1}
,"(including":{"certificate)":1}
,"certificate)":{"keystore":1}
,"called":{"server1":1}
,"server1":{"configuration":1,"certificate":1}
,"example":{"above":1,"create":1}
,"above":{"keytool":1}
,"-genkey":{"-keystore":1}
,"-keystore":{"keystore-file.jks":1}
,"keystore-file.jks":{"-dname":1,"\u005C-file":1}
,"-dname":{"cn=172.16.254.1":1,"option":1}
,"cn=172.16.254.1":{"ou=terracotta":1}
,"ou=terracotta":{"o=sag":1}
,"o=sag":{"l=san":1}
,"l=san":{"francisco":1}
,"francisco":{"s=california":1}
,"s=california":{"c=us":1}
,"c=us":{"-alias":1}
,"-alias":{"server1alias":1}
,"server1alias":{"-storepass":1,"-keystore":1,"-file":1}
,"-storepass":{"server1pass":1,"-keypass":1}
,"server1pass":{"-keypass":1,"note":1}
,"-keypass":{"server1pass":1,"match":1}
,"values":{"passed":1}
,"passed":{"-storepass":1}
,"designating":{"common":1}
,"matches":{"value":1}
,"entered":{"server\u0027s":1}
,"address":{"resolvable":1}
,"resolvable":{"domain":1}
,"domain":{"name":1}
,"left":{"series":1}
,"series":{"identity":1}
,"prompts":{"(distinguished-name":1}
,"(distinguished-name":{"fields":1}
,"fields":{"based":1}
,"based":{"x.500":1}
,"x.500":{"standard)":1}
,"standard)":{"appear":1}
,"appear":{"server\u0027s":1}
,"entry":{"created":1,"terracotta":1}
,"created":{"keystore":1}
,"prompt":{"appears":1,"information":1}
,"appears":{"shown":1,"prompted":1}
,"shown":{"first":1}
,"first":{"last":1}
,"last":{"name":1}
,"[unknown]":{"number":1}
,"number":{"keytool":1}
,"options":{"consider":1,"dependent":1}
,"consider":{"including":1}
,"-keyalg":{"(cryptographic":1}
,"(cryptographic":{"algorithm":1}
,"algorithm":{"default":1}
,"dsa)":{"-validity":1}
,"-validity":{"(number":1}
,"(number":{"days":1}
,"days":{"until":1}
,"until":{"certificate":1,"every":1}
,"expires":{"default":1}
,"90)":{"options":1}
,"dependent":{"environment":1}
,"environment":{"security":1}
,"requirements":{"information":1}
,"information":{"using":1,"certificate":1}
,"documentation":{"create":1,"keytool":1}
,"copy":{"server\u0027s":1,"cert":1,"every":1}
,"public-key":{"certificate":1}
,"export":{"certificate":1}
,"-export":{"-alias":1}
,"\u005C-file":{"server1selfsignedcert.cert":1}
,"server1selfsignedcert.cert":{"cert":1,"\u005C-keystore":1}
,"cert":{"file":1}
,"every":{"server":1,"server\u0027s":1}
,"server2":{"copy":1,"following":1}
,"working":{"directory":1}
,"directory":{"server2":1}
,"-import":{"-alias":1}
,"-file":{"server1selfsignedcert.cert":1}
,"\u005C-keystore":{"truststore.jks":1}
,"truststore.jks":{"password":1}
,"prompted":{"trust":1}
,"trust":{"repeat":1,"file":1}
,"repeat":{"process":1}
,"process":{"until":1}
,"cluster":{"single":1}
,"single":{"truststore":1}
,"-instead":{"recreating":1}
,"recreating":{"truststore":1}
,"clients":{"using":1}
,"client":{"truststore":1}
,"utility":{"maintain":1,"alternative":1}
,"maintain":{"additional":1}
,"additional":{"certificates":1}
,"chain":{"trust":1}
,"wish":{"additional":1}
,"refer":{"option":1}
,"-trustcacerts":{"documentation":1}
,"alternative":{"using":1}
,"line":{"tool":1}
,"tool":{"keytool":1,"keystore":1}
,"want":{"try":1}
,"try":{"open":1}
,"open":{"source":1}
,"source":{"graphical":1}
,"graphical":{"tool":1}
,"explorer":{"available":1}
,"available":{"http:\u002F\u002Fwww.keystore-explorer.org\u002Findex.html":1}
}
;Search.control.loadWordPairs(pairs);
