var pairs =
{
"using":{"client":1,"self-signed":1}
,"client":{"truststore":1,"import":1,"first":1,"find":1}
,"truststore":{"terracotta":1,"client":1,"already":1,"server":1,"java":1,"file":1,"accessing":1,"password":1,"master":1}
,"terracotta":{"servers":1}
,"servers":{"using":1}
,"self-signed":{"certificates":1}
,"certificates":{"(not":1,"signed":1}
,"(not":{"certificates":1}
,"signed":{"well-known":1}
,"well-known":{"ca)":1}
,"ca)":{"create":1}
,"create":{"truststore":1}
,"import":{"server\u0027s":1}
,"server\u0027s":{"public-key":1}
,"public-key":{"certificate":1}
,"certificate":{"truststore":1,"copy":1,"changing":1}
,"already":{"created":1}
,"created":{"truststore":1}
,"server":{"tsa":1}
,"tsa":{"copy":1}
,"copy":{"file":1,"client":1}
,"file":{"client":1,"case":1}
,"first":{"importing":1}
,"importing":{"server\u0027s":1}
,"find":{"truststore":1}
,"java":{"system":1}
,"system":{"property":1}
,"property":{"javax.net.ssl.truststore":1,"javax.net.ssl.truststorepassword":1}
,"javax.net.ssl.truststore":{"location":1}
,"location":{"truststore":1}
,"case":{"note":1}
,"note":{"existing":1}
,"existing":{"secrets":1,"truststore":1}
,"secrets":{"opening":1}
,"opening":{"truststore":1}
,"accessing":{"certificate":1}
,"changing":{"truststore":1}
,"password":{"-to":1,"java":1}
,"-to":{"change":1}
,"change":{"existing":1}
,"master":{"password":1}
}
;Search.control.loadWordPairs(pairs);
