var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Frestartable":{"fast-restart":1}
,"fast-restart":{"persistence":1}
,"persistence":{"mechanism":1,"allows":1}
,"mechanism":{"explicitly":1}
,"explicitly":{"enabled":1}
,"enabled":{"tsa":1,"server":1}
,"tsa":{"using":1,"failure":1,"reload":1,"data":1}
,"using":{"element":1}
,"element":{"<restartable":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"case":1}
,"case":{"tsa":1}
,"failure":{"fast-restart":1}
,"allows":{"tsa":1}
,"reload":{"shared":1}
,"shared":{"cluster":1}
,"cluster":{"data":1}
,"data":{"function":1,"backup":1}
,"function":{"feature":1}
,"feature":{"requires":1,"enabled":1}
,"requires":{"<offheap>":1,"feature":1}
,"<offheap>":{"enabled":1}
,"server":{"backups":1}
,"backups":{"tsa":1}
,"backup":{"feature":1}
}
;Search.control.loadWordPairs(pairs);
