var pairs =
{
"demo":{"sample":1,"different":1}
,"sample":{"application":1}
,"application":{"demonstrates":1,"involves":1,"single":1,"located":1}
,"demonstrates":{"bigmemory":1}
,"bigmemory":{"wan":1,"max":1}
,"wan":{"replication":1,"run":1}
,"replication":{"service":1,"enables":1}
,"service":{"bigmemory":1}
,"max":{"clusters":1}
,"clusters":{"wan":1,"share":1,"named":1}
,"enables":{"two":1}
,"two":{"bigmemory":1}
,"share":{"data":1}
,"data":{"eventually":1,"stored":1}
,"eventually":{"consistent":1}
,"consistent":{"manner":1}
,"manner":{"scenario":1}
,"scenario":{"simulated":1}
,"simulated":{"application":1}
,"involves":{"two":1}
,"named":{"region-1":1}
,"region-1":{"region-2":1,"shown":1}
,"region-2":{"data":1,"vice":1}
,"stored":{"region-1":1}
,"shown":{"replicated":1}
,"replicated":{"region-2":1}
,"vice":{"versa":1}
,"versa":{"run":1}
,"run":{"sample":1,"demo":1}
,"single":{"machine":1}
,"machine":{"machines":1}
,"machines":{"actually":1,"need":1}
,"actually":{"connected":1}
,"connected":{"via":1}
,"via":{"wan":1}
,"different":{"machines":1}
,"need":{"specify":1}
,"specify":{"correct":1}
,"correct":{"ip:port":1}
,"ip:port":{"addresses":1}
,"addresses":{"xml":1}
,"xml":{"configuration":1}
,"configuration":{"files":1}
,"files":{"sample":1}
,"located":{"<bigmemory_kit>\u002Fcode-samples\u002Fexample09-wan-replication\u002F":1,"\u002Fcode-samples\u002Fsrc\u002F":1}
,"<bigmemory_kit>\u002Fcode-samples\u002Fexample09-wan-replication\u002F":{"code":1}
,"code":{"used":1}
,"used":{"application":1}
}
;Search.control.loadWordPairs(pairs);
