var pairs =
{
"restoring":{"data":1}
,"data":{"backup":1,"data":1,"directory":1,"files":1,"required":1}
,"backup":{"tsa":1,"data":1}
,"tsa":{"fails":1}
,"fails":{"restart":1}
,"restart":{"automatically":1,"terracotta":1}
,"automatically":{"restores":1}
,"restores":{"data":1}
,"directory":{"recreating":1,"deleted":1}
,"recreating":{"application":1}
,"application":{"state":1}
,"state":{"current":1}
,"current":{"data":1}
,"files":{"corrupt":1,"delete":1,"terracotta":1,"directory":1,"restart":1}
,"corrupt":{"missing":1}
,"missing":{"situations":1}
,"situations":{"earlier":1}
,"earlier":{"snapshot":1}
,"snapshot":{"data":1}
,"required":{"restore":1}
,"restore":{"backups":1}
,"backups":{"shut":1}
,"shut":{"down":1}
,"down":{"terracotta":1}
,"terracotta":{"cluster":1,"servers":1}
,"cluster":{"(optional)":1}
,"(optional)":{"copies":1}
,"copies":{"existing":1}
,"existing":{"data":1}
,"delete":{"existing":1}
,"servers":{"copy":1}
,"copy":{"backup":1}
,"deleted":{"original":1}
,"original":{"(existing)":1}
,"(existing)":{"data":1}
}
;Search.control.loadWordPairs(pairs);
