var pairs =
{
"bigmemory":{"max":1}
,"max":{"code":1,"general":1,"kit":1}
,"code":{"samples":1}
,"samples":{"code":1,"illustrate":1,"available":1,"themselves":1,"maven":1}
,"illustrate":{"various":1}
,"various":{"features":1}
,"features":{"bigmemory":1}
,"general":{"information":1}
,"information":{"related":1,"settings.xml":1,"working":1}
,"related":{"code":1}
,"available":{"\u002Fcode-samples":1}
,"\u002Fcode-samples":{"directory":1}
,"directory":{"bigmemory":1}
,"kit":{"full":1}
,"full":{"code":1}
,"themselves":{"located":1}
,"located":{"\u002Fcode-samples\u002Fsrc\u002F":1}
,"\u002Fcode-samples\u002Fsrc\u002F":{"running":1}
,"running":{"codes":1}
,"codes":{"samples":1}
,"maven":{"run":1,"need":1,"repositories":1,"settings.xml":1,"developer":1}
,"run":{"code":1}
,"need":{"add":1}
,"add":{"terracotta":1,"following":1}
,"terracotta":{"maven":1}
,"repositories":{"maven":1}
,"settings.xml":{"file":1}
,"file":{"add":1,"<repository>":1}
,"following":{"repository":1}
,"repository":{"information":1}
,"<repository>":{"<id>":1}
,"<id>":{"terracotta-repository":1}
,"terracotta-repository":{"<\u002Fid>":1}
,"<\u002Fid>":{"<url>":1}
,"<url>":{"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":{"<\u002Furl>":1}
,"<\u002Furl>":{"<releases>":1}
,"<releases>":{"<enabled>":1}
,"<enabled>":{"true":1}
,"true":{"<\u002Fenabled>":1}
,"<\u002Fenabled>":{"<\u002Freleases>":1}
,"<\u002Freleases>":{"<\u002Frepository>":1}
,"<\u002Frepository>":{"further":1}
,"further":{"information":1}
,"working":{"apache":1}
,"apache":{"maven":1}
,"developer":{"guide":1}
,"guide":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
