var pairs =
{
"procedure":{"upgrading":1,"procedure":1,"used":1,"backup":1,"follows":1}
,"upgrading":{"4.1":1}
,"4.1":{"4.2":1,"data":1,"bigmemory":1,"installation":1}
,"4.2":{"section":1,"upgrading":1,"existing":1,"installation":1,"upgrade":1}
,"section":{"describes":1,"4.1":1}
,"describes":{"upgrade":1}
,"upgrade":{"4.1":1,"procedure":1,"tasks":1,"terracotta":1}
,"existing":{"4.1":1}
,"data":{"preserved":1,"described":1,"4.2":1}
,"preserved":{"every":1,"anyway":1}
,"every":{"installation":1}
,"installation":{"unique":1,"(optional)":1,"manually":1,"later":1,"directory":1}
,"unique":{"factors":1}
,"factors":{"affect":1}
,"affect":{"upgrade":1}
,"used":{"checklist":1}
,"checklist":{"relevant":1}
,"relevant":{"topics":1}
,"topics":{"basic":1}
,"basic":{"upgrade":1}
,"tasks":{"download":1}
,"download":{"bigmemory":1}
,"bigmemory":{"kit":1,"max":1,"installation":1}
,"kit":{"verify":1,"config-samples\u002Fdirectory":1,"upgrade":1}
,"verify":{"correct":1}
,"correct":{"license":1}
,"license":{"keys":1}
,"keys":{"version":1}
,"version":{"installing":1,"bigmemory":1,"restarting":1}
,"installing":{"prepare":1}
,"prepare":{"new":1}
,"new":{"configuration":1,"bigmemory":1}
,"configuration":{"files":1}
,"files":{"sample":1,"located":1,"specific":1}
,"sample":{"configuration":1,"files":1}
,"located":{"bigmemory":1}
,"config-samples\u002Fdirectory":{"modify":1}
,"modify":{"sample":1}
,"specific":{"information":1}
,"information":{"installation":1}
,"(optional)":{"persistence":1}
,"persistence":{"enabled":1}
,"enabled":{"backup":1}
,"backup":{"data":1,"utility":1,"restore":1,"case":1}
,"described":{"database":1}
,"database":{"backup":1}
,"utility":{"section":1}
,"max":{"documentation":1}
,"documentation":{"backup":1}
,"restore":{"4.1":1}
,"manually":{"note":1}
,"note":{"existing":1}
,"anyway":{"during":1}
,"during":{"4.2":1}
,"case":{"need":1}
,"need":{"revert":1}
,"revert":{"4.1":1}
,"later":{"stage":1}
,"stage":{"shut":1}
,"shut":{"down":1}
,"down":{"server":1,"mirror":1,"clients":1,"shut":1,"application":1,"active":1}
,"server":{"array":1}
,"array":{"safe":1}
,"safe":{"shutdown":1}
,"shutdown":{"procedure":1}
,"follows":{"shut":1}
,"mirror":{"servers":1}
,"servers":{"using":1,"removing":1,"cluster":1,"new":1}
,"using":{"stop-tc-server":1}
,"stop-tc-server":{"script":1}
,"script":{"shut":1,"clear":1}
,"clients":{"terracotta":1,"servers":1}
,"terracotta":{"client":1,"clients":1}
,"client":{"shut":1}
,"application":{"shut":1}
,"active":{"servers":1}
,"clear":{"servers":1}
,"removing":{"old":1}
,"old":{"version":1}
,"directory":{"install":1}
,"install":{"new":1}
,"cluster":{"version":1,"start":1}
,"restarting":{"cluster":1}
,"start":{"servers":1}
}
;Search.control.loadWordPairs(pairs);
