var pairs =
{
"\u002Ftc:tc-config\u002Fclients\u002Flogs":{"section":1}
,"section":{"lets":1}
,"lets":{"configure":1}
,"configure":{"terracotta":1}
,"terracotta":{"client":1,"services)":1,"services":1}
,"client":{"writes":1,"(that":1,"assigned":1}
,"writes":{"logs":1}
,"logs":{"sample":1,"directory":1}
,"sample":{"configuration":1}
,"configuration":{"snippet":1}
,"snippet":{"<!--this":1}
,"<!--this":{"value":1}
,"value":{"undergoes":1,"\u0027client-logs-%":1}
,"undergoes":{"parameter":1}
,"parameter":{"substitution":1}
,"substitution":{"used":1}
,"used":{"thus":1}
,"thus":{"value":1,"recommended":1}
,"\u0027client-logs-%":{"expand":1}
,"expand":{"\u0027client-logs-banana":1}
,"\u0027client-logs-banana":{"running":1}
,"running":{"host":1}
,"host":{"\u0027banana":1}
,"\u0027banana":{"product":1}
,"product":{"guide":1}
,"guide":{"details":1}
,"details":{"relative":1}
,"relative":{"path":1,"current":1,"directory":1}
,"path":{"interpreted":1,"default":1}
,"interpreted":{"relative":1}
,"current":{"working":1}
,"working":{"directory":1}
,"directory":{"client":1,"started":1,"relative":1,"invoked":1,"example":1}
,"(that":{"directory":1}
,"started":{"program":1}
,"program":{"uses":1}
,"uses":{"terracotta":1}
,"services)":{"thus":1}
,"recommended":{"specify":1}
,"specify":{"absolute":1,"stderr":1}
,"absolute":{"path":1}
,"default":{"\u0027logs-%":1}
,"\u0027logs-%":{"places":1}
,"places":{"logs":1}
,"invoked":{"program":1}
,"services":{"(your":1}
,"(your":{"client)":1}
,"client)":{"calls":1}
,"calls":{"directory":1}
,"example":{"\u0027logs-10.0.0.57":1,"<logs>":1}
,"\u0027logs-10.0.0.57":{"machine":1}
,"machine":{"client":1}
,"assigned":{"address":1}
,"address":{"10.0.0.57":1}
,"10.0.0.57":{"-->":1}
,"-->":{"<logs>":1}
,"<logs>":{"logs-%":1,"stdout":1}
,"logs-%":{"<\u002Flogs>":1}
,"<\u002Flogs>":{"specify":1,"logging":1}
,"stderr":{"stdout":1}
,"stdout":{"output":1,"<\u002Flogs>":1}
,"output":{"destination":1}
,"destination":{"log":1}
,"log":{"messages":1}
,"messages":{"example":1}
,"logging":{"level":1}
,"level":{"logging":1}
}
;Search.control.loadWordPairs(pairs);
