var pairs =
{
"nonstop":{"exceptions":1,"cache":1,"cache\u0027s":1,"mode":1,"timeout":1,"caches":1}
,"exceptions":{"typically":1,"application":1,"handles":1,"nonstop":1,"using":1}
,"typically":{"application":1}
,"application":{"code":1,"encounter":1,"handle":1,"framework":1}
,"code":{"may":1,"using":1}
,"may":{"access":1}
,"access":{"cache":1}
,"cache":{"frequently":1,"application":1,"client":1,"nonstop":1,"types":1,"fault":1}
,"frequently":{"various":1}
,"various":{"points":1}
,"points":{"therefore":1}
,"therefore":{"nonstop":1}
,"encounter":{"nonstopcacheexceptions":1}
,"nonstopcacheexceptions":{"difficult":1,"handle":1}
,"difficult":{"predict":1}
,"predict":{"following":1}
,"following":{"sections":1,"example":1}
,"sections":{"provide":1}
,"provide":{"guidance":1}
,"guidance":{"expect":1}
,"expect":{"nonstopcacheexceptions":1}
,"handle":{"nonstopcacheexception":1,"nonstop":1}
,"nonstopcacheexception":{"thrown":1,"usually":1}
,"thrown":{"nonstopcacheexception":1,"configured":1,"seconds":1,"even":1,"cache":1,"related":1,"during":1}
,"usually":{"thrown":1}
,"configured":{"behavior":1,"nonstop":1}
,"behavior":{"nonstop":1,"throw":1}
,"client":{"disconnects":1,"rejoin":1}
,"disconnects":{"cluster":1}
,"cluster":{"following":1,"offline":1}
,"example":{"exception":1,"refer":1,"decorator":1}
,"exception":{"thrown":1,"<\u002Fnonstop>":1,"happen":1,"invalidlockafterrejoinexception":1,"occurs":1,"outside":1}
,"seconds":{"disconnection":1}
,"disconnection":{"(or":1}
,"(or":{"cluster":1}
,"offline":{"event":1}
,"event":{"received)":1}
,"received)":{"<nonstop":1}
,"<nonstop":{"immediatetimeout=\u0022":1}
,"immediatetimeout=\u0022":{"false":1}
,"false":{"timeoutmillis=\u0022":1}
,"timeoutmillis=\u0022":{"30000":1}
,"30000":{"<timeoutbehavior":1}
,"<timeoutbehavior":{"type=\u0022":1}
,"type=\u0022":{"exception":1}
,"<\u002Fnonstop>":{"however":1}
,"however":{"certain":1}
,"certain":{"circumstances":1,"lock":1}
,"circumstances":{"nonstopcache":1}
,"nonstopcache":{"exception":1}
,"even":{"nonstop":1}
,"cache\u0027s":{"timeout":1}
,"timeout":{"behavior":1,"exception":1}
,"throw":{"exception":1}
,"happen":{"cache":1}
,"mode":{"during":1}
,"during":{"attempt":1,"client":1}
,"attempt":{"acquire":1,"completed":1}
,"acquire":{"release":1}
,"release":{"lock":1,"locks":1}
,"lock":{"lock":1,"operations":1,"apis":1,"obtained":1}
,"operations":{"associated":1,"try-finally":1}
,"associated":{"certain":1}
,"apis":{"special":1,"encapsulate":1}
,"special":{"cache":1}
,"types":{"explicit":1}
,"explicit":{"locking":1}
,"locking":{"blockingcache":1}
,"blockingcache":{"selfpopulatingcache":1}
,"selfpopulatingcache":{"updatingselfpopulatingcache":1}
,"updatingselfpopulatingcache":{"nonstopcacheexception":1}
,"fault":{"element":1}
,"element":{"satisfy":1}
,"satisfy":{"operation":1}
,"operation":{"terracotta":1,"takes":1}
,"terracotta":{"server":1,"clients":1}
,"server":{"array":1}
,"array":{"cannot":1}
,"cannot":{"respond":1}
,"respond":{"within":1}
,"within":{"configured":1}
,"related":{"exception":1}
,"invalidlockafterrejoinexception":{"thrown":1}
,"rejoin":{"exception":1,"attempt":1,"using":1,"automatically":1}
,"occurs":{"unlock":1}
,"unlock":{"operation":1}
,"takes":{"place":1}
,"place":{"lock":1}
,"obtained":{"rejoin":1}
,"completed":{"information":1}
,"information":{"rejoin":1}
,"using":{"rejoin":1,"try-finally":1,"ehcache":1,"dedicated":1}
,"automatically":{"reconnect":1}
,"reconnect":{"terracotta":1}
,"clients":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"high-availability":1}
,"high-availability":{"guide":1}
,"guide":{"using":1}
,"try-finally":{"blocks":1}
,"blocks":{"release":1,"mylock.acquirelock":1}
,"locks":{"ensure":1,"released":1}
,"ensure":{"locks":1}
,"released":{"properly":1}
,"properly":{"application":1}
,"ehcache":{"lock":1,"decorator":1}
,"encapsulate":{"lock-unlock":1}
,"lock-unlock":{"operations":1}
,"mylock.acquirelock":{"try":1}
,"try":{"{\u002F\u002Fdo":1,"{cache.put":1}
,"{\u002F\u002Fdo":{"work":1}
,"work":{"finally":1}
,"finally":{"{mylock.unlock":1}
,"{mylock.unlock":{"handling":1}
,"handling":{"nonstop":1}
,"handles":{"exceptions":1}
,"caches":{"unhandled-exceptions":1}
,"unhandled-exceptions":{"handler":1}
,"handler":{"example":1}
,"refer":{"separate":1}
,"separate":{"thread":1}
,"thread":{"cleanup":1}
,"cleanup":{"needed":1}
,"needed":{"manage":1}
,"manage":{"problem":1}
,"problem":{"effectively":1}
,"effectively":{"handle":1}
,"dedicated":{"ehcache":1}
,"decorator":{"manages":1,"operate":1}
,"manages":{"exception":1}
,"outside":{"application":1}
,"framework":{"following":1}
,"operate":{"try":1}
,"{cache.put":{"(element)":1}
,"(element)":{"catch":1}
,"catch":{"(nonstopcacheexception":1}
,"(nonstopcacheexception":{"{handler.handleexception":1}
,"{handler.handleexception":{"(cache":1}
,"(cache":{"element":1}
}
;Search.control.loadWordPairs(pairs);
