var pairs =
{
"bigmemory":{"sql":1,"using":1}
,"sql":{"<<this":1,"allows":1,"alternative":1,"similarly":1,"query":1,"supports":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"bigmemory":1}
,"allows":{"search":1,"lookup-style":1}
,"search":{"in-memory":1,"api":1}
,"in-memory":{"data":1}
,"data":{"bigmemory":1}
,"using":{"expressions":1,"search":1,"bigmemory":1}
,"expressions":{"similar":1}
,"similar":{"structured":1}
,"structured":{"query":1}
,"query":{"language":1,"constructed":1,"expressed":1,"cache":1}
,"language":{"bigmemory":1}
,"alternative":{"programmatic":1}
,"programmatic":{"java-based":1}
,"java-based":{"search":1}
,"api":{"described":1,"expressed":1,"search":1,"allows":1}
,"described":{"searching":1}
,"searching":{"cache":1}
,"cache":{"query":1,"terracotta":1}
,"constructed":{"using":1}
,"expressed":{"using":1,"search":1}
,"similarly":{"bigmemory":1}
,"lookup-style":{"queries":1}
,"queries":{"bigmemory":1}
,"supports":{"select":1}
,"select":{"statements":1}
,"statements":{"(and":1}
,"(and":{"example":1}
,"example":{"insert":1}
,"insert":{"delete":1}
,"delete":{"even":1}
,"even":{"found":1}
,"found":{"sql92)":1}
,"sql92)":{"information":1}
,"information":{"null":1}
,"null":{"support":1}
,"support":{"options":1}
,"options":{"working":1}
,"working":{"nulls":1}
,"nulls":{"bigmemory":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"procedures":1,"user":1}
,"procedures":{"terracotta":1}
,"user":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
