var pairs =
{
"strict":{"(support":1,"<cache":1}
,"(support":{"jta":1}
,"jta":{"components)":1,"transactions":1,"transactional":1,"value":1}
,"components)":{"note":1}
,"note":{"ehcache":1}
,"ehcache":{"resource":1,"force":1,"hibernate":1,"using":1,"2.1.0":1}
,"resource":{"isolation":1,"able":1,"involved":1}
,"isolation":{"level":1}
,"level":{"readcommitted":1}
,"readcommitted":{"updates":1}
,"updates":{"underlying":1,"org.hibernate.cache.updatetimestampscache":1}
,"underlying":{"store":1}
,"store":{"asynchronously":1}
,"asynchronously":{"potentially":1}
,"potentially":{"creating":1}
,"creating":{"update":1}
,"update":{"conflicts":1}
,"conflicts":{"optimistic":1}
,"optimistic":{"locking":1}
,"locking":{"approach":1}
,"approach":{"ehcache":1}
,"force":{"transaction":1}
,"transaction":{"manager":1,"commit":1,"managers":1,"database":1,"ended":1,"example":1,"writes":1,"fail":1,"manager)":1,"api":1}
,"manager":{"roll":1,"start":1}
,"roll":{"back":1}
,"back":{"entire":1}
,"entire":{"transaction":1}
,"commit":{"generates":1,"failures":1}
,"generates":{"rollbackexception":1}
,"rollbackexception":{"(indicating":1}
,"(indicating":{"conflict)":1}
,"conflict)":{"work":1}
,"work":{"alongside":1}
,"alongside":{"resources":1}
,"resources":{"jdbc":1,"guarantees":1,"configured":1}
,"jdbc":{"jms":1}
,"jms":{"resources":1}
,"guarantees":{"data":1}
,"data":{"always":1}
,"always":{"synchronized":1}
,"synchronized":{"resources":1}
,"configured":{"per-cache":1,"jta":1,"compliant":1,"transactional":1}
,"per-cache":{"basis":1}
,"basis":{"(transactional":1}
,"(transactional":{"non-transactional":1}
,"non-transactional":{"caches":1}
,"caches":{"exist":1,"hibernate":1,"second-level":1,"using":1,"cause":1}
,"exist":{"configuration)":1}
,"configuration)":{"automatically":1}
,"automatically":{"performs":1}
,"performs":{"enlistment":1}
,"enlistment":{"used":1}
,"used":{"standalone":1,"second-level":1}
,"standalone":{"integrated":1}
,"integrated":{"frameworks":1}
,"frameworks":{"hibernate":1}
,"hibernate":{"tested":1,"45557}":1,"ensure":1,"updates":1,"using":1,"3.3":1,"transaction":1,"mapping":1}
,"tested":{"common":1}
,"common":{"transaction":1}
,"managers":{"atomikos":1}
,"atomikos":{"bitronix":1}
,"bitronix":{"jboss":1}
,"jboss":{"weblogic":1}
,"weblogic":{"others":1}
,"others":{"configuration":1}
,"configuration":{"configure":1}
,"configure":{"cache":1}
,"cache":{"resource":1,"configured":1,"transactions":1,"foocache":1,"possible":1,"ehcache":1,"clustered":1,"updatetimestampscache":1,"net.sf.ehcache.hibernate.ehcacheregionfactory":1,"turned":1,"concurrency":1}
,"able":{"participate":1}
,"participate":{"jta":1,"transactions":1}
,"transactions":{"following":1,"strict":1,"usage":1,"hibernate":1}
,"following":{"<cache>":1,"cache":1,"ehcache":1}
,"<cache>":{"attributes":1,"sub-element":1,"element":1}
,"attributes":{"shown":1}
,"shown":{"transactionalmode=\u0022":1}
,"transactionalmode=\u0022":{"xa_strict":1,"<terracotta":1}
,"xa_strict":{"copyonread=\u0022":1,"<persistence":1}
,"copyonread=\u0022":{"true":1}
,"true":{"copyonwrite=\u0022":1,"addition":1,"consistency=\u0022":1,"\u0022>)":1}
,"copyonwrite=\u0022":{"true":1}
,"addition":{"<cache>":1}
,"sub-element":{"<terracotta>":1,"<terracotta":1}
,"<terracotta>":{"clustering":1}
,"clustering":{"disabled":1}
,"disabled":{"example":1}
,"example":{"following":1,"mytransactionman.begin":1,"cache":1}
,"<cache":{"name=\u0022":1,"usage=\u0022":1}
,"name=\u0022":{"com.my.package.foo":1}
,"com.my.package.foo":{"maxentrieslocalheap=\u0022":1,"transactionalmode=\u0022":1,"hibernate.cfg.xml":1,"usage=\u0022":1}
,"maxentrieslocalheap=\u0022":{"500":1}
,"500":{"eternal=\u0022":1}
,"eternal=\u0022":{"false":1}
,"false":{"copyonread=\u0022":1}
,"consistency=\u0022":{"strong":1}
,"strong":{"transactionalmode=\u0022":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"distributed":1}
,"distributed":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<terracotta":1,"hibernate":1,"using":1}
,"<terracotta":{"<\u002Fcache>":1,"clustered=\u0022":1}
,"<\u002Fcache>":{"resource":1,"cache":1}
,"involved":{"transaction":1}
,"database":{"configured":1}
,"compliant":{"usage":1}
,"usage":{"application":1,"occur":1}
,"application":{"directly":1,"using":1}
,"directly":{"transactional":1}
,"transactional":{"cache":1,"caches":1,"<cache":1,"hibernate":1,"example":1,"\u0022\u002F>":1,"concurrency":1}
,"occur":{"transaction":1}
,"start":{"new":1}
,"new":{"transaction":1}
,"ended":{"transaction":1}
,"mytransactionman.begin":{"cache":1}
,"foocache":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"foo":1}
,"foo":{"foocache.put":1,"warning":1}
,"foocache.put":{"bar":1}
,"bar":{"mytransactionman.commit":1}
,"mytransactionman.commit":{"transaction":1}
,"writes":{"cache":1}
,"possible":{"transaction":1}
,"fail":{"avoiding":1}
,"avoiding":{"commit":1}
,"failures":{"atomic":1}
,"atomic":{"methods":1}
,"methods":{"setting":1}
,"setting":{"transactional":1}
,"45557}":{"application":1}
,"using":{"jta":1,"ehcache":1,"hibernate":1,"annotations":1,"types":1}
,"second-level":{"cache":1}
,"ensure":{"following":1}
,"2.1.0":{"higher":1}
,"higher":{"attribute":1}
,"attribute":{"transactionalmode":1}
,"transactionalmode":{"xa-strict":1}
,"xa-strict":{"cache":1}
,"clustered":{"(the":1}
,"(the":{"<cache>":1}
,"element":{"sub-element":1}
,"clustered=\u0022":{"true":1}
,"\u0022>)":{"example":1}
,"updatetimestampscache":{"configured":1}
,"org.hibernate.cache.updatetimestampscache":{"prevent":1}
,"prevent":{"able":1}
,"3.3":{"factory":1}
,"factory":{"class":1}
,"class":{"used":1,"(see":1,"hibernate":1,"foo":1}
,"net.sf.ehcache.hibernate.ehcacheregionfactory":{"query":1}
,"query":{"cache":1}
,"turned":{"value":1}
,"value":{"current_session_context_class":1,"transaction.manager_lookup_class":1,"transaction.factory_class":1}
,"current_session_context_class":{"jta":1}
,"transaction.manager_lookup_class":{"name":1}
,"name":{"transactionmanagerlookup":1,"transactionfactory":1}
,"transactionmanagerlookup":{"class":1}
,"(see":{"transaction":1}
,"manager)":{"value":1}
,"transaction.factory_class":{"name":1}
,"transactionfactory":{"class":1}
,"api":{"cache":1}
,"concurrency":{"strategy":1}
,"strategy":{"transactional":1,"com.my.package.foo":1}
,"hibernate.cfg.xml":{"<class-cache":1}
,"<class-cache":{"class=\u0022":1}
,"class=\u0022":{"com.my.package.foo":1}
,"usage=\u0022":{"transactional":1}
,"mapping":{"file":1}
,"file":{"(hbm":1}
,"(hbm":{"file)":1}
,"file)":{"<cache":1}
,"annotations":{"@cache":1}
,"@cache":{"(usage=cacheconcurrencystrategy.transactional)":1}
,"(usage=cacheconcurrencystrategy.transactional)":{"public":1}
,"public":{"class":1}
,"warning":{"transactional":1}
,"types":{"caches":1}
,"cause":{"errors":1}
}
;Search.control.loadWordPairs(pairs);
