var pairs =
{
"running":{"demo":1}
,"demo":{"run":1}
,"run":{"application":1}
,"application":{"demonstrate":1,"using":1,"started":1,"command":1,"fill":1,"[k0":1}
,"demonstrate":{"wan":1,"replication":1}
,"wan":{"replication":1,"orchestrator":1,"services":1}
,"replication":{"list":1,"process":1}
,"list":{"commands":1}
,"commands":{"available":1}
,"available":{"typing":1}
,"typing":{"help":1,"following":1}
,"help":{"wan-config-region-1.xml":1}
,"wan-config-region-1.xml":{"wan-config-region-2.xml":1}
,"wan-config-region-2.xml":{"files":1}
,"files":{"replace":1}
,"replace":{"wan-samples-root-dir":1}
,"wan-samples-root-dir":{"placeholder":1}
,"placeholder":{"actual":1}
,"actual":{"location":1}
,"location":{"folder":1}
,"folder":{"(for":1}
,"(for":{"example":1,"unix\u002Flinux)":1,"windows)":1}
,"example":{"$wan_samples\u002F)":1}
,"$wan_samples\u002F)":{"launch":1}
,"launch":{"region-1":1,"region-2":1}
,"region-1":{"tsa":1,"wan":1,"application":1,"cluster":1,"elements":1,"successfully":1,"type":1,"[k0":1}
,"tsa":{"using":1,"wan":1,"typing":1}
,"using":{"command":1}
,"command":{"start-sample-server-1.sh":1,"start-sample-server-2.sh":1,"start-orch-1.sh":1,"start-orch-2.sh":1,"run.sh":1,"prompt":1,"region-1":1,"put":1,"region-2":1,"command":1}
,"start-sample-server-1.sh":{"(for":1}
,"unix\u002Flinux)":{"start-sample-server-1.bat":1,"start-sample-server-2.bat":1,"start-orch-1.bat":1,"start-orch-2.bat":1,"run.bat":1}
,"start-sample-server-1.bat":{"(for":1}
,"windows)":{"launch":1,"tsa":1,"command":1}
,"region-2":{"tsa":1,"wan":1,"application":1,"cluster":1,"change":1,"typing":1,"visible":1}
,"start-sample-server-2.sh":{"(for":1}
,"start-sample-server-2.bat":{"(for":1}
,"orchestrator":{"using":1}
,"start-orch-1.sh":{"(for":1}
,"start-orch-1.bat":{"(for":1}
,"start-orch-2.sh":{"(for":1}
,"start-orch-2.bat":{"(for":1}
,"services":{"regions":1}
,"regions":{"started":1}
,"started":{"ready":1}
,"ready":{"run":1,"accept":1}
,"process":{"start":1}
,"start":{"region-1":1,"application\u0027s":1,"region-2":1}
,"run.sh":{"(for":1}
,"run.bat":{"(for":1}
,"prompt":{"indicates":1,"type":1,"region-1":1}
,"indicates":{"application":1,"key":1,"successful":1}
,"accept":{"various":1}
,"various":{"instructions":1}
,"instructions":{"command":1}
,"type":{"connect":1,"following":1}
,"connect":{"localhost:9510":1,"localhost:9610":1}
,"localhost:9510":{"bar":1}
,"bar":{"bar":1,"sample":1}
,"sample":{"cache":1}
,"cache":{"name":1,"manager":1}
,"name":{"name":1,"want":1}
,"want":{"start":1}
,"application\u0027s":{"cache":1}
,"manager":{"region-1":1,"region-2":1}
,"cluster":{"operational":1}
,"operational":{"start":1,"store":1}
,"localhost:9610":{"bar":1}
,"store":{"elements":1}
,"elements":{"region-1":1,"replicated":1}
,"following":{"command":1}
,"fill":{"100":1}
,"100":{"command":1,"keys":1}
,"put":{"100":1,"baz":1,"happened":1}
,"keys":{"named":1}
,"named":{"k99":1}
,"k99":{"values":1}
,"values":{"v99":1}
,"v99":{"region-1":1}
,"replicated":{"region-2":1}
,"[k0":{"v0]":1,"baz]":1}
,"v0]":{"result":1}
,"result":{"indicates":1}
,"key":{"inserted":1}
,"inserted":{"region-1":1}
,"successfully":{"replicated":1}
,"change":{"value":1}
,"value":{"region-2":1}
,"baz":{"put":1}
,"happened":{"region-2":1}
,"visible":{"region-1":1}
,"baz]":{"result":1}
,"successful":{"replication":1}
}
;Search.control.loadWordPairs(pairs);
