var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fdatastorage":{"configuration":1}
,"configuration":{"block":1,"snippet":1}
,"block":{"includes":1}
,"includes":{"required":1}
,"required":{"offheap":1}
,"offheap":{"element":1,"size":1}
,"element":{"optional":1,"<offheap>":1,"present":1}
,"optional":{"hybrid":1}
,"hybrid":{"element":1,"sum":1,"option":1}
,"<offheap>":{"configured":1}
,"configured":{"server":1}
,"server":{"minimum":1,"represents":1}
,"minimum":{"amount":1}
,"amount":{"<datastorage>":1,"data":1}
,"<datastorage>":{"specifies":1}
,"specifies":{"maximum":1}
,"maximum":{"amount":1}
,"data":{"store":1}
,"store":{"server":1}
,"represents":{"hybrid":1}
,"sum":{"off-heap":1}
,"off-heap":{"dram":1}
,"dram":{"plus":1}
,"plus":{"flash":1}
,"flash":{"ssd":1}
,"ssd":{"<hybrid\u002F>":1}
,"<hybrid\u002F>":{"included":1,"<\u002Fdatastorage>":1}
,"included":{"enables":1}
,"enables":{"hybrid":1}
,"option":{"sample":1}
,"sample":{"configuration":1}
,"snippet":{"<datastorage":1}
,"<datastorage":{"size=\u0022":1}
,"size=\u0022":{"800g":1,"200g":1}
,"800g":{"<offheap":1}
,"<offheap":{"size=\u0022":1}
,"200g":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<hybrid\u002F>":1}
,"<\u002Fdatastorage>":{"hybrid":1}
,"present":{"datastorage":1}
,"datastorage":{"size":1}
,"size":{"may":1,"however":1,"less":1}
,"may":{"exceed":1}
,"exceed":{"offheap":1}
,"however":{"hybrid":1}
,"less":{"equal":1}
,"equal":{"offheap":1}
}
;Search.control.loadWordPairs(pairs);
