var pairs =
{
"using":{".net":1,"xplatform.createcachemanager":1,"search":1,"bson":1,"provided":1,"native":1}
,".net":{"client":1,"(recipe2":1}
,"client":{"api":1,"located":1,"connector":1}
,"api":{"section":1,"documentation":1,"byte":1,"documented":1}
,"section":{"covers":1,"provides":1,"mean":1}
,"covers":{"connecting":1}
,"connecting":{"working":1,"connector":1}
,"working":{"searching":1}
,"searching":{"bigmemory":1}
,"bigmemory":{"data":1,"client":1,"detailed":1,"max":1,"sql":1,"searched":1}
,"data":{"complete":1,"stored":1,"first":1}
,"complete":{"class":1}
,"class":{"library":1,"value":1,"user":1,"usercacheserializer":1,"defining":1,"example":1}
,"library":{"documentation":1}
,"documentation":{"refer":1,"\u002Fapis\u002Fcsharp\u002Fapidoc-csharp.zip":1}
,"refer":{"api":1,"consistency":1}
,"\u002Fapis\u002Fcsharp\u002Fapidoc-csharp.zip":{"directory":1}
,"directory":{"kit":1}
,"kit":{"connecting":1}
,"connector":{"application":1,"via":1,"configuration":1,"located":1,"nirvana":1,"bigmemory":1,"access":1,"retrieve":1,"provide":1,"\u002F\u002Fcreate":1,"execute":1,"type":1}
,"application":{"communicate":1}
,"communicate":{"connector":1}
,"via":{"icachemanager":1,"terracotta.ehcache.utilities.dateutility.trimtomillisgranularity":1}
,"icachemanager":{"interface":1,"using":1,"cachemanager":1,"needs":1,"connected":1,"example":1}
,"interface":{"begin":1}
,"begin":{"creating":1}
,"creating":{"configuration":1}
,"configuration":{"object":1,"nirvana":1,"cfg=new":1,"(\u0022\u002Fdev\u002Fshm":1,"connects":1,"localhost":1,"instance":1,"ehcache.xml":1,"scan":1}
,"object":{"deployment":1,"graphs":1,"trimmed":1,"trimming":1,"recipe2bsonserializer":1}
,"deployment":{"bigmemory":1}
,"located":{"machine":1,"different":1}
,"machine":{"connector":1}
,"nirvana":{"shared":1,"socket":1}
,"shared":{"memory":1}
,"memory":{"(shm)":1}
,"(shm)":{"transport":1,"-configuration":1}
,"transport":{"configuration":1,"example":1,"provisions":1,"types":1}
,"cfg=new":{"configuration":1}
,"(\u0022\u002Fdev\u002Fshm":{"16))":1}
,"16))":{"deployment":1}
,"different":{"machines":1,"transport":1,"parameters":1}
,"machines":{"configuration":1,"once":1}
,"socket":{"transport":1,"-configuration":1}
,"example":{"create":1,"byte":1,"user":1,"below":1,"using":1,"previous":1,"<ehcache>":1,"searchresults":1}
,"create":{"configuration":1,"icachemanager":1}
,"connects":{"local":1}
,"local":{"host":1}
,"host":{"default":1}
,"default":{"port":1,"unindexed":1}
,"port":{"uses":1}
,"uses":{"nirvana":1}
,"provisions":{"pool":1}
,"pool":{"connections":1}
,"connections":{"share":1}
,"share":{"configuration":1}
,"localhost":{"constants.defaultport":1}
,"constants.defaultport":{"transporttype.nirvana":1}
,"transporttype.nirvana":{"16)":1,"clientpoolsize)":1}
,"16)":{"notice":1}
,"notice":{"configurations":1}
,"configurations":{"different":1}
,"types":{"require":1,"serializers":1,"bool":1,"connector":1,"cache":1,"add":1}
,"require":{"different":1}
,"parameters":{"nirvana":1}
,"-configuration":{"shmlocation":1,"hostname":1}
,"shmlocation":{"clientpoolsize)":1}
,"clientpoolsize)":{"-generally":1,"-used":1}
,"-generally":{"used":1}
,"used":{"bigmemory":1,"within":1,"configure":1}
,"hostname":{"portnumber":1}
,"portnumber":{"transporttype.nirvana":1}
,"-used":{"connector":1}
,"once":{"configuration":1,"you\u0027ve":1}
,"instance":{"ready":1,"cache":1}
,"ready":{"create":1}
,"xplatform.createcachemanager":{"static":1}
,"static":{"method":1}
,"method":{"icachemanager":1,"cachemanager.close":1,"returns":1,"user":1,"providing":1}
,"cachemanager":{"=xplatform.createcachemanager":1}
,"=xplatform.createcachemanager":{"(cfg)":1}
,"(cfg)":{"shutting":1}
,"shutting":{"connection":1}
,"connection":{"down":1}
,"down":{"icachemanager":1}
,"needs":{"closed":1,"holds":1}
,"closed":{"order":1}
,"order":{"release":1,"search":1}
,"release":{"resources":1}
,"resources":{"(like":1}
,"(like":{"connections)":1}
,"connections)":{"close":1}
,"close":{"invoking":1,"method":1}
,"invoking":{"close":1}
,"cachemanager.close":{"accessing":1}
,"accessing":{"cache":1}
,"cache":{"once":1,"known":1,"need":1,"say":1,"retrieve":1,"icachemanager":1,"named":1,"icache":1,"=cachemanager.getcache":1,"key":1,"remove":1,"consistency":1,"configuration":1,"supported":1}
,"you\u0027ve":{"obtained":1}
,"obtained":{"reference":1}
,"reference":{"icachemanager":1,"order":1}
,"connected":{"connector":1}
,"access":{"cache":1}
,"known":{"connector":1}
,"retrieve":{"thread-safe":1,"defined":1,"cache":1,"key":1,"recipe2":1}
,"thread-safe":{"instance":1}
,"need":{"name":1,"provide":1,"add":1}
,"name":{"type":1}
,"type":{"key":1,"public":1,"value":1,"byte":1}
,"key":{"value":1,"value)":1,"case":1,"invoke":1,"currently":1,"mapped":1,"specified":1}
,"value":{"serializer":1,"(true":1,"types":1,"type":1,"serializekey":1,"v.stringvalue":1,"idval":1,"emailval":1,"(in":1,"name-value":1,"good":1,"unlike":1,"replace":1,"key":1,"new":1,"currently":1,"matches":1,"information":1}
,"serializer":{"types":1,"serialize":1,"public":1,"icacheserializer":1,"=new":1,"class)":1}
,"serializers":{"protocol":1}
,"protocol":{"recognizes":1}
,"recognizes":{"following":1}
,"following":{"types":1,"class":1,"example":1,"cas":1}
,"bool":{"boolean":1}
,"boolean":{"value":1}
,"(true":{"false)":1}
,"false)":{"byte":1}
,"byte":{"byte":1,"signed":1,"i16":1,"array":1,"arrays":1,"indexed":1}
,"signed":{"byte":1,"integer":1}
,"i16":{"16-bit":1}
,"16-bit":{"signed":1}
,"integer":{"i32":1,"i64":1,"double":1}
,"i32":{"32-bit":1}
,"32-bit":{"signed":1}
,"i64":{"64-bit":1}
,"64-bit":{"signed":1,"floating":1}
,"double":{"64-bit":1}
,"floating":{"point":1}
,"point":{"number":1}
,"number":{"byte":1}
,"array":{"bytes":1,"representation":1,"indexable":1}
,"bytes":{"string":1}
,"string":{"encoding":1,"want":1,"login":1,"email":1,"need":1,"deserializekey":1,"values":1,"representation":1,"example":1}
,"encoding":{"agnostic":1}
,"agnostic":{"text":1}
,"text":{"binary":1}
,"binary":{"string":1,"representation":1}
,"want":{"send":1,"note":1}
,"send":{"complex":1}
,"complex":{"types":1,"key":1}
,"provide":{"serializer":1}
,"serialize":{"complex":1,"deserialize":1}
,"say":{"following":1}
,"public":{"class":1,"string":1,"storedvalue":1,"user":1}
,"user":{"{public":1,"deserializevalue":1,"=new":1,"user.login":1,"note":1,"email":1,"user":1,"user1":1,"user1.id":1,"users.put":1,"someuser":1}
,"{public":{"long":1,"value":1}
,"long":{"{get":1}
,"{get":{"public":1,"store":1}
,"login":{"{get":1,"string":1,"key":1}
,"email":{"{get":1,"=emailval":1,".stringvalue":1,"stored":1,"class=\u0022":1,"ilike":1}
,"store":{"keyed":1,"whatever":1,"retrieve":1}
,"keyed":{"login":1}
,"usercacheserializer":{"icacheserializer":1,"\u002F\u002Fget":1}
,"icacheserializer":{"<string":1,"cache":1}
,"<string":{"user>":1,"value>":1,"recipe2>":1}
,"user>":{"{public":1,"serializer":1,"users":1,"result":1}
,"serializekey":{"(string":1}
,"(string":{"key)":1}
,"key)":{"{value":1}
,"{value":{"=new":1}
,"=new":{"value":1,"dictionary":1,"storedvalue":1,"user":1,"usercacheserializer":1}
,"v.stringvalue":{"=key":1}
,"=key":{"return":1}
,"return":{"public":1,"user":1}
,"deserializekey":{"(value":1}
,"(value":{"serializedkey)":1}
,"serializedkey)":{"{return":1}
,"{return":{"serializedkey.stringvalue":1}
,"serializedkey.stringvalue":{"public":1}
,"storedvalue":{"serializevalue":1,"=new":1,"sv.value":1,"composed":1,"hold":1,"sent":1}
,"serializevalue":{"(user":1}
,"(user":{"objectvalue)":1}
,"objectvalue)":{"{dictionary":1}
,"{dictionary":{"<string":1}
,"value>":{"nvpairs":1,"value":1}
,"nvpairs":{"=new":1,"=idval":1,"email":1}
,"dictionary":{"<string":1}
,"idval":{"=valuehelper.newvalue":1}
,"=valuehelper.newvalue":{"(objectvalue.id)":1,"(objectvalue.email)":1,"(encoding.unicode.getbytes":1}
,"(objectvalue.id)":{"nvpairs":1}
,"=idval":{"value":1}
,"emailval":{"=valuehelper.newvalue":1}
,"(objectvalue.email)":{"nvpairs":1}
,"=emailval":{"storedvalue":1}
,"sv.value":{"=valuehelper.newvalue":1}
,"(encoding.unicode.getbytes":{"(objectvalue.login))":1}
,"(objectvalue.login))":{"sv.nvpairs":1}
,"sv.nvpairs":{"=nvpairs":1}
,"=nvpairs":{"return":1}
,"deserializevalue":{"(storedvalue":1}
,"(storedvalue":{"serializedvalue)":1}
,"serializedvalue)":{"{user":1}
,"{user":{"user":1}
,"user.login":{"=encoding.unicode.getstring":1}
,"=encoding.unicode.getstring":{"(serializedvalue.value.binaryvalue)":1}
,"(serializedvalue.value.binaryvalue)":{"user.id":1}
,"user.id":{"=serializedvalue.nvpairs":1}
,"=serializedvalue.nvpairs":{".longvalue":1,"email":1}
,".longvalue":{"user.email":1}
,"user.email":{"=serializedvalue.nvpairs":1}
,".stringvalue":{"return":1}
,"note":{"serialize":1,"name-value":1,"java":1}
,"deserialize":{"methods":1}
,"methods":{"(whether":1}
,"(whether":{"key":1}
,"value)":{"kept":1}
,"kept":{"symmetric":1}
,"symmetric":{"storedvalue":1}
,"composed":{"actual":1}
,"actual":{"value":1}
,"(in":{"example":1}
,"representation":{"user\u0027s":1,"within":1,"parts":1}
,"user\u0027s":{"login)":1}
,"login)":{"storedvalue":1}
,"hold":{"entire":1}
,"entire":{"object":1}
,"graphs":{"serialized":1}
,"serialized":{"whatever":1}
,"whatever":{"serialization":1,"want":1}
,"serialization":{"strategies":1,"deserialization":1}
,"strategies":{"fits":1}
,"fits":{"needs":1}
,"holds":{"arbitrary":1}
,"arbitrary":{"amount":1}
,"amount":{"name\u002Fvalue":1}
,"name\u002Fvalue":{"pairs":1}
,"pairs":{"names":1,"store":1,"become":1,"above":1,"pnf\u0027s":1}
,"names":{"string":1}
,"values":{"type":1,"cache":1,"name\u002Fvalue":1}
,"name-value":{"pairs":1}
,"become":{"indexable":1}
,"indexable":{"searchable":1,"however":1,"search":1}
,"searchable":{"using":1,"(continuing":1}
,"search":{"api":1,"enabled":1,"section":1,"bigmemory":1,"types":1,"attributes":1}
,"however":{"used":1}
,"within":{"name-value":1,"default":1,"ehcache.xml":1,"bigmemory":1}
,"above":{"example":1}
,"stored":{"byte":1,"within":1}
,"arrays":{"even":1,"indexable":1}
,"even":{"byte":1}
,"enabled":{"attributes":1}
,"attributes":{"login":1,"values":1,"using":1}
,"case":{"storing":1}
,"storing":{"binary":1}
,"unindexed":{"value":1}
,"good":{"enough":1}
,"enough":{"special":1}
,"special":{"handling":1}
,"handling":{"datetime":1,"first":1}
,"datetime":{"objects":1,"object":1}
,"objects":{"captures":1,"millisecond":1}
,"captures":{"date":1}
,"date":{"information":1}
,"information":{"precision":1,"refer":1,"atomic":1,"may":1,"construct":1}
,"precision":{"java":1}
,"java":{"means":1,"prepared":1,"(pojo)":1}
,"means":{"string":1}
,"parts":{"java":1,"handling":1}
,"prepared":{"parse":1}
,"parse":{"two":1}
,"two":{"parts":1}
,"first":{"isodatetimeconverter":1,"need":1}
,"isodatetimeconverter":{"side":1}
,"side":{"serialization":1}
,"deserialization":{"code":1}
,"code":{"second":1,"sample":1}
,"second":{"trim":1}
,"trim":{"datetime":1}
,"millisecond":{"granularity":1}
,"granularity":{"via":1}
,"terracotta.ehcache.utilities.dateutility.trimtomillisgranularity":{"(datetime":1}
,"(datetime":{"dt)":1}
,"dt)":{"method":1}
,"returns":{"new":1}
,"new":{"datetime":1,"recipe2bsonserializer":1,"value":1}
,"trimmed":{"appropriately":1}
,"appropriately":{"alternatively":1}
,"alternatively":{"valuehelper.newvalue":1}
,"valuehelper.newvalue":{"datetime":1}
,"trimming":{"key-based":1}
,"key-based":{"store":1}
,"defined":{"icacheserializer":1,"cache":1}
,"below":{"assumes":1}
,"assumes":{"defined":1}
,"named":{"usercache":1}
,"usercache":{"within":1,"serializer)":1,"<searchable\u002F>":1,"<searchable>":1,"email":1}
,"ehcache.xml":{"file":1}
,"file":{"used":1,"<ehcache>":1}
,"configure":{"connector":1}
,"\u002F\u002Fcreate":{"serializer":1}
,"\u002F\u002Fget":{"cache":1}
,"icache":{"<string":1}
,"users":{"=cachemanager.getcache":1}
,"=cachemanager.getcache":{"usercache":1,"testcache":1}
,"serializer)":{"\u002F\u002Fmake":1}
,"\u002F\u002Fmake":{"user":1}
,"user1":{"=new":1,"consistencytype.strong)":1}
,"user1.id":{"user1.email":1}
,"user1.email":{"someone@somewhere":1}
,"someone@somewhere":{"user1.login":1}
,"user1.login":{"secretpasswd":1}
,"secretpasswd":{"\u002F\u002Fput":1}
,"\u002F\u002Fput":{"user":1}
,"users.put":{"(user1.login":1}
,"(user1.login":{"user1":1}
,"consistencytype.strong)":{"following":1,"consistencytype":1}
,"bson":{"code":1}
,"sample":{".net":1}
,"(recipe2":{"class":1}
,"defining":{"domain":1}
,"domain":{"object":1}
,"recipe2bsonserializer":{"serializer":1,"())":1}
,"class)":{"icache":1}
,"recipe2>":{"cache":1}
,"testcache":{"new":1}
,"())":{"cache.put":1}
,"cache.put":{"(rec.name":1}
,"(rec.name":{"rec":1}
,"rec":{"consistencytype.strong)":1,"=(recipe2)":1}
,"consistencytype":{"attribute":1}
,"attribute":{"sets":1}
,"sets":{"consistency":1}
,"consistency":{"strong":1,"retrieve":1,"refer":1,"search":1}
,"strong":{"eventual":1}
,"eventual":{"expect":1}
,"expect":{"connector":1}
,"execute":{"operation":1}
,"operation":{"information":1}
,"invoke":{"method":1}
,"someuser":{"=usercache.get":1}
,"=usercache.get":{"(somelogin":1}
,"(somelogin":{"consistencytype.eventual)":1}
,"consistencytype.eventual)":{"retrieve":1,"compare":1}
,"recipe2":{"rec":1}
,"=(recipe2)":{"cache.get":1}
,"cache.get":{"(args":1}
,"(args":{"[1]":1}
,"[1]":{"consistencytype.eventual)":1}
,"compare":{"swap":1}
,"swap":{"(cas)":1}
,"(cas)":{"operations":1}
,"operations":{"following":1,"provided":1,"cache":1}
,"cas":{"operations":1}
,"provided":{"putifabsent":1,"attributeextractor":1}
,"putifabsent":{"(tkey":1,"creates":1}
,"(tkey":{"tvalue)":1,"oldvalue":1}
,"tvalue)":{"-puts":1,"-conditionally":1,"-maps":1}
,"-puts":{"specified":1}
,"specified":{"key\u002Fvalue":1,"key":1,"value":1,"key\u0027s":1}
,"key\u002Fvalue":{"pair":1}
,"pair":{"cache":1,"putifabsent":1,"present":1}
,"currently":{"assigned":1,"mapped":1,"existing":1}
,"assigned":{"value":1}
,"unlike":{"put":1}
,"put":{"replace":1}
,"replace":{"existing":1,"(tkey":1}
,"existing":{"key\u002Fvalue":1,"value":1}
,"creates":{"key\u002Fvalue":1}
,"present":{"cache":1}
,"remove":{"(tkey":1}
,"-conditionally":{"removes":1,"replaces":1}
,"removes":{"specified":1}
,"mapped":{"specified":1,"value":1}
,"-maps":{"specified":1}
,"oldvalue":{"newvalue)":1}
,"newvalue)":{"-conditionally":1}
,"replaces":{"specified":1}
,"key\u0027s":{"old":1}
,"old":{"value":1}
,"matches":{"old":1}
,"atomic":{"operations":1}
,"provides":{"overview":1}
,"overview":{"cross-language":1}
,"cross-language":{"searches":1}
,"searches":{"pnf":1}
,"pnf":{"data":1}
,"detailed":{"information":1}
,"may":{"found":1}
,"found":{"bigmemory":1}
,"max":{"developer":1}
,"developer":{"guide":1}
,"guide":{"don":1,"note":1}
,"don":{"added":1}
,"added":{"reference":1}
,"add":{"<searchable\u002F>":1,"search":1}
,"<searchable\u002F>":{"tag":1,"<\u002Fcache>":1}
,"tag":{"cache":1}
,"<ehcache>":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"usercache":1,"email":1}
,"<\u002Fcache>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"configuration":1,"perform":1}
,"scan":{"keys":1}
,"keys":{"values":1}
,"supported":{"search":1}
,"pnf\u0027s":{"storedvalue":1}
,"sent":{"connector":1}
,"indexed":{"made":1}
,"made":{"searchable":1}
,"(continuing":{"example":1}
,"previous":{"section":1}
,"mean":{"email.)":1}
,"email.)":{"add":1}
,"attributeextractor":{"class":1}
,"<searchable>":{"<searchattribute":1}
,"<searchattribute":{"name=\u0022":1}
,"class=\u0022":{"net.sf.ehcache.xplatform.search.indexer":1}
,"net.sf.ehcache.xplatform.search.indexer":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Fsearchable>":1}
,"<\u002Fsearchable>":{"<\u002Fcache>":1}
,"perform":{"query":1}
,"query":{"cache.query":1,"string":1}
,"cache.query":{"(string)":1}
,"(string)":{"method":1}
,"providing":{"bigmemory":1}
,"sql":{"query":1,"queries":1,"bigmemory":1}
,"searchresults":{"<string":1}
,"result":{"=usercache.query":1}
,"=usercache.query":{"select":1}
,"select":{"*from":1}
,"*from":{"usercache":1}
,"ilike":{"%@terracottatech.com":1}
,"%@terracottatech.com":{"information":1}
,"construct":{"bigmemory":1}
,"queries":{"searching":1}
,"(pojo)":{"data":1}
,"searched":{"using":1}
,"native":{"ehcache":1}
,"ehcache":{"search":1}
,"documented":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
