var pairs =
{
"distributed":{"garbage":1}
,"garbage":{"collection":1,"immediately":1}
,"collection":{"(dgc)":1}
,"(dgc)":{"two":1}
,"two":{"types":1}
,"types":{"dgc":1}
,"dgc":{"periodic":1,"configurable":1,"automatic":1,"disabled":1,"algorithm":1}
,"periodic":{"inline":1,"dgc":1}
,"inline":{"periodic":1,"dgc":1}
,"configurable":{"run":1}
,"run":{"manually":1}
,"manually":{"(see":1}
,"(see":{"below)":1}
,"below)":{"inline":1}
,"automatic":{"garbage-collection":1}
,"garbage-collection":{"process":1}
,"process":{"intended":1}
,"intended":{"maintain":1}
,"maintain":{"server\u0027s":1}
,"server\u0027s":{"memory":1}
,"memory":{"runs":1}
,"runs":{"even":1}
,"even":{"periodic":1}
,"disabled":{"note":1}
,"note":{"inline":1}
,"algorithm":{"operates":1}
,"operates":{"intervals":1}
,"intervals":{"optimal":1}
,"optimal":{"maximizing":1}
,"maximizing":{"performance":1}
,"performance":{"necessarily":1}
,"necessarily":{"collect":1}
,"collect":{"distributed":1}
}
;Search.control.loadWordPairs(pairs);
