var pairs =
{
"summary":{"changes":1}
,"changes":{"4.1\u002F4.2":1,"4.2":1,"4.1":1}
,"4.1\u002F4.2":{"4.3":1}
,"4.3":{"changes":1,"area":1,"terracotta":1}
,"4.2":{"4.3":1,"area":1,"bigmemory":1,"tmc":1}
,"area":{"change":1}
,"change":{"change":1,"4.2":1,"4.1":1,"value":1}
,"terracotta":{"management":1,"server":1,"configuration":1,"server\u0027s":1}
,"management":{"console":1,"monitoring":1}
,"console":{"(tmc)":1}
,"(tmc)":{"tmc":1,"(port":1}
,"tmc":{"provides":1,"new":1,"used":1,"uses":1}
,"provides":{"wan":1}
,"wan":{"tab":1,"replication":1}
,"tab":{"enables":1}
,"enables":{"monitor":1}
,"monitor":{"information":1,"deployment":1}
,"information":{"following":1}
,"following":{"aspects":1}
,"aspects":{"wan":1}
,"replication":{"service":1,"ability":1,"improved":1,"management":1}
,"service":{"wan\u0027s":1}
,"wan\u0027s":{"topology":1}
,"topology":{"configuration":1}
,"configuration":{"wan-enabled":1,"status":1,"file":1}
,"wan-enabled":{"cache":1}
,"cache":{"including":1}
,"including":{"performance":1}
,"performance":{"statistics":1,"bigmemory":1}
,"statistics":{"details":1}
,"details":{"deployment":1}
,"deployment":{"orchestrator":1,"terracotta":1}
,"orchestrator":{"topology":1}
,"status":{"changes":1}
,"4.1":{"4.2":1}
,"bigmemory":{"hybrid":1,"max":1}
,"hybrid":{"ability":1,"maximize":1}
,"ability":{"auto":1,"support":1}
,"auto":{"tune":1}
,"tune":{"bigmemory":1}
,"maximize":{"performance":1}
,"max":{"zero":1}
,"zero":{"down-time":1}
,"down-time":{"maintenance":1}
,"maintenance":{"version":1}
,"version":{"upgrade":1}
,"upgrade":{"capability":1}
,"capability":{"wan":1}
,"support":{"even":1,"large":1}
,"even":{"higher":1}
,"higher":{"data":1}
,"data":{"limits":1}
,"limits":{"providing":1}
,"providing":{"greater":1}
,"greater":{"fault":1}
,"fault":{"tolerance":1}
,"tolerance":{"wan":1}
,"improved":{"efficiency":1}
,"efficiency":{"wan":1}
,"monitoring":{"support":1}
,"large":{"number":1}
,"number":{"clients":1,"attempts":1}
,"clients":{"connected":1}
,"connected":{"cluster":1}
,"cluster":{"rest":1}
,"rest":{"apis":1}
,"apis":{"provided":1}
,"provided":{"monitor":1}
,"server":{"array":1}
,"array":{"new":1,"jmx":1,"property":1}
,"new":{"port":1,"section":1}
,"port":{"dedicated":1,"used":1,"specified":1,"disabled":1,"terracotta":1,"defaults":1}
,"dedicated":{"tmc":1}
,"section":{"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fmanagement-port":1,"specifies":1,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fjmx-port":1,"used":1}
,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fmanagement-port":{"added":1,"terracotta":1}
,"added":{"terracotta":1}
,"file":{"section":1,"tc-config.xml":1}
,"specifies":{"port":1}
,"used":{"terracotta":1,"ports":1,"specify":1}
,"(port":{"9540":1,"9510":1,"9530":1}
,"9540":{"default)":1}
,"default)":{"prior":1,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Ftsa-group-port":1,"tmc":1}
,"prior":{"4.2":1}
,"ports":{"specified":1}
,"specified":{"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Ftsa-port":1,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fmanagement-port":1}
,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Ftsa-port":{"(port":1}
,"9510":{"default)":1}
,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Ftsa-group-port":{"(port":1}
,"9530":{"default)":1}
,"uses":{"port":1}
,"jmx":{"port":1,"connector":1}
,"disabled":{"-in":1,"default":1}
,"-in":{"terracotta":1}
,"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fjmx-port":{"disabled":1}
,"default":{"enable":1,"value":1}
,"enable":{"change":1}
,"value":{"jmx-enabled=from":1,"jmx-port":1,"tsa-port":1}
,"jmx-enabled=from":{"false":1}
,"false":{"true":1}
,"true":{"terracotta":1}
,"tc-config.xml":{"section":1}
,"specify":{"port":1}
,"server\u0027s":{"jmx":1}
,"connector":{"listens":1}
,"listens":{"default":1}
,"jmx-port":{"9520":1}
,"9520":{"tsa-port":1}
,"tsa-port":{"port":1,"plus":1}
,"defaults":{"value":1}
,"plus":{"terracotta":1}
,"property":{"deprecated":1}
,"deprecated":{"-the":1,"client":1}
,"-the":{"l1.max.connect.retries":1}
,"l1.max.connect.retries":{"property":1}
,"client":{"given":1}
,"given":{"unlimited":1}
,"unlimited":{"number":1}
,"attempts":{"connect":1}
}
;Search.control.loadWordPairs(pairs);
