var pairs =
{
"configuration":{"affects":1,"constraints":1}
,"affects":{"eviction":1}
,"eviction":{"distributed":1,"crucial":1,"expiration":1,"intended":1,"controlling":1,"server":1,"automatic":1}
,"distributed":{"cache":1}
,"cache":{"element":1,"elements":1,"managing":1,"infinite":1}
,"element":{"eviction":1,"necessarily":1,"cache":1,"(sometimes":1,"evicted":1,"however":1}
,"crucial":{"part":1}
,"part":{"keeping":1}
,"keeping":{"cluster":1}
,"cluster":{"resources":1}
,"resources":{"operating":1}
,"operating":{"efficiently":1}
,"efficiently":{"element":1}
,"expiration":{"related":1}
,"related":{"expired":1}
,"expired":{"element":1,"elements":1,"cache":1,"unexpired":1}
,"necessarily":{"evicted":1,"expired":1}
,"evicted":{"immediately":1,"element":1,"due":1,"terracotta":1,"accurately":1,"meet":1,"faulted":1}
,"immediately":{"evicted":1}
,"elements":{"evicted":1,"faulted":1,"whenever":1,"elements":1,"become":1,"orphaned":1}
,"due":{"resource":1}
,"resource":{"configuration":1,"management":1}
,"constraints":{"expired":1,"learn":1}
,"terracotta":{"client":1,"server":1}
,"client":{"put":1,"tier":1,"may":1,"elements":1,"information":1}
,"put":{"operation":1}
,"operation":{"occurs":1}
,"occurs":{"element":1}
,"(sometimes":{"called":1}
,"called":{"inline":1}
,"inline":{"eviction)":1}
,"eviction)":{"terracotta":1}
,"server":{"array":1}
,"array":{"contains":1,"typically":1,"servers":1,"data":1}
,"contains":{"full":1}
,"full":{"key":1}
,"key":{"(as":1}
,"(as":{"values)":1}
,"values)":{"clients":1}
,"clients":{"contain":1,"mean":1}
,"contain":{"subset":1}
,"subset":{"keys":1}
,"keys":{"values":1}
,"values":{"based":1,"resident":1}
,"based":{"elements":1}
,"faulted":{"server":1,"back":1}
,"typically":{"expired":1}
,"accurately":{"flushed":1}
,"flushed":{"client":1}
,"tier":{"lower":1,"put":1,"reached":1}
,"lower":{"tier":1}
,"however":{"client":1}
,"may":{"flush":1}
,"flush":{"expired":1}
,"unexpired":{"elements":1}
,"whenever":{"cache\u0027s":1}
,"cache\u0027s":{"sizing":1,"eternal":1}
,"sizing":{"limit":1,"storage":1}
,"limit":{"specific":1}
,"specific":{"tier":1}
,"reached":{"memory":1}
,"memory":{"pressure":1,"constraints":1}
,"pressure":{"type":1}
,"type":{"eviction":1}
,"intended":{"meet":1}
,"meet":{"configured":1,"following":1}
,"configured":{"real":1}
,"real":{"memory":1}
,"learn":{"eviction":1}
,"controlling":{"size":1}
,"size":{"cache":1}
,"managing":{"data":1}
,"data":{"life":1,"eviction":1}
,"life":{"sizing":1}
,"storage":{"tiers":1}
,"tiers":{"flushing":1}
,"flushing":{"clients":1}
,"mean":{"eviction":1}
,"servers":{"evict":1,"run":1}
,"evict":{"expired":1}
,"become":{"candidates":1}
,"candidates":{"eviction":1}
,"run":{"low":1}
,"low":{"allocated":1}
,"allocated":{"bigmemory":1}
,"bigmemory":{"unexpired":1,"max":1}
,"following":{"criteria":1}
,"criteria":{"cache":1}
,"infinite":{"tti\u002Fttl":1}
,"tti\u002Fttl":{"(time":1,"enabling":1,"values":1}
,"(time":{"idle":1}
,"idle":{"time":1}
,"time":{"live)":1}
,"live)":{"explicit":1}
,"explicit":{"settings":1}
,"settings":{"tti\u002Fttl":1}
,"enabling":{"cache\u0027s":1}
,"eternal":{"flag":1}
,"flag":{"overrides":1}
,"overrides":{"finite":1}
,"finite":{"tti\u002Fttl":1}
,"resident":{"terracotta":1}
,"orphaned":{"once":1}
,"once":{"evicted":1}
,"back":{"system":1}
,"system":{"record":1}
,"record":{"requested":1}
,"requested":{"client":1}
,"information":{"terracotta":1}
,"automatic":{"resource":1}
,"management":{"bigmemory":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
