var pairs =
{
"example":{"search":1,"available":1,"computes":1,"finds":1}
,"search":{"following":1,"capabilities":1,"operations":1,"api":1,"attributes":1,"criteria":1}
,"following":{"description":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"bigmemory":1}
,"bigmemory":{"max":1,"sql":1,"=manager.getehcache":1}
,"max":{"comes":1}
,"comes":{"powerful":1}
,"powerful":{"in-memory":1}
,"in-memory":{"search":1,"data":1}
,"capabilities":{"sample":1}
,"sample":{"shows":1}
,"shows":{"perform":1}
,"perform":{"basic":1,"computations":1}
,"basic":{"search":1}
,"operations":{"in-memory":1}
,"data":{"using":1,"bigmemory.put":1,"query":1,"ages":1,"live":1}
,"using":{"search":1,"bigmemory":1,"aggregators":1}
,"api":{"issue":1}
,"issue":{"queries":1}
,"queries":{"using":1}
,"sql":{"either":1,"first":1}
,"either":{"command":1}
,"command":{"line":1}
,"line":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"(tmc)":1}
,"(tmc)":{"sql-like":1}
,"sql-like":{"language":1}
,"language":{"documented":1}
,"documented":{"searching":1}
,"searching":{"bigmemory":1}
,"first":{"create":1}
,"create":{"cache":1,"search":1}
,"cache":{"searchable":1}
,"searchable":{"attributes":1,".searchattribute":1}
,"attributes":{"configuration":1,"construct":1,"example":1}
,"configuration":{"managerconfig":1,".cache":1}
,"managerconfig":{"=new":1}
,"=new":{"configuration":1}
,".cache":{"(new":1}
,"(new":{"cacheconfiguration":1,"searchable":1,"searchattribute":1,"element":1}
,"cacheconfiguration":{".name":1}
,".name":{"mysearchabledatastore":1,"age":1,"gender":1,"state":1,"name":1}
,"mysearchabledatastore":{".eternal":1,"next":1}
,".eternal":{"(true)":1}
,"(true)":{".maxbyteslocalheap":1}
,".maxbyteslocalheap":{"(512":1}
,"(512":{"memoryunit.megabytes)":1}
,"memoryunit.megabytes)":{".maxbyteslocaloffheap":1}
,".maxbyteslocaloffheap":{"(32":1}
,"(32":{"memoryunit.gigabytes)":1}
,"memoryunit.gigabytes)":{".searchable":1}
,".searchable":{"(new":1}
,".searchattribute":{"(new":1}
,"searchattribute":{".name":1}
,"age":{"\u0022))":1,"=bigmemory.getsearchattribute":1,"attribute":1,"people":1,"averageagequery.execute":1,"agesbetween.execute":1}
,"\u0022))":{".searchattribute":1,"newjerseycountquery.includeaggregator":1}
,"gender":{".expression":1,"=bigmemory.getsearchattribute":1,"attribute":1}
,".expression":{"value.getgender":1,"value.getaddress":1}
,"value.getgender":{"\u0022))":1}
,"state":{".expression":1,"=bigmemory.getsearchattribute":1,"query":1}
,"value.getaddress":{".getstate":1}
,".getstate":{"\u0022))":1}
,"name":{".classname":1,"=bigmemory.getsearchattribute":1,"attribute":1}
,".classname":{"(nameattributeextractor.class.getname":1}
,"(nameattributeextractor.class.getname":{"()))":1}
,"()))":{"cachemanager":1}
,"cachemanager":{"manager":1}
,"manager":{"=cachemanager.create":1}
,"=cachemanager.create":{"(managerconfig)":1}
,"(managerconfig)":{"ehcache":1}
,"ehcache":{"bigmemory":1}
,"=manager.getehcache":{"mysearchabledatastore":1}
,"next":{"insert":1}
,"insert":{"data":1}
,"bigmemory.put":{"(new":1}
,"element":{"new":1}
,"new":{"person":1,"jersey":1}
,"person":{"jane":1,"marie":1,"john":1,"paul":1,"juliet":1}
,"jane":{"doe":1}
,"doe":{"gender.female":1}
,"gender.female":{"eck":1,"berry":1,"dah":1}
,"eck":{"street":1}
,"street":{"san":1}
,"san":{"mateo":1}
,"mateo":{"\u0022)))":1}
,"\u0022)))":{"bigmemory.put":1,"(int":1,"create":1}
,"marie":{"antoinette":1}
,"antoinette":{"gender.female":1}
,"berry":{"parsippany":1}
,"parsippany":{"\u0022)))":1}
,"john":{"smith":1}
,"smith":{"gender.male":1}
,"gender.male":{"big":1,"cool":1}
,"big":{"wig":1}
,"wig":{"beverly":1}
,"beverly":{"hills":1}
,"hills":{"\u0022)))":1}
,"paul":{"dupont":1}
,"dupont":{"gender.male":1}
,"cool":{"agent":1}
,"agent":{"madison":1}
,"madison":{"\u0022)))":1}
,"juliet":{"capulet":1}
,"capulet":{"gender.female":1,"person.gender.male":1}
,"dah":{"man":1}
,"man":{"bangladesh":1}
,"bangladesh":{"\u0022)))":1}
,"(int":{"<1000":1}
,"<1000":{"{bigmemory.put":1}
,"{bigmemory.put":{"(new":1}
,"person.gender.male":{"dah":1}
,"construct":{"query":1}
,"query":{"attribute":1,"query":1,"=bigmemory.createquery":1,"look":1,"results":1,"averageagequery":1,"agesbetween":1,"newjerseycountquery":1}
,"attribute":{"<integer>":1,"<gender>":1,"<string>":1}
,"<integer>":{"age":1}
,"=bigmemory.getsearchattribute":{"age":1,"gender":1,"name":1,"state":1}
,"<gender>":{"gender":1}
,"<string>":{"name":1,"state":1}
,"=bigmemory.createquery":{"query.includekeys":1,"averageagequery.includeaggregator":1,"agesbetween.addcriteria":1,".addcriteria":1}
,"query.includekeys":{"query.includevalues":1}
,"query.includevalues":{"query.addcriteria":1}
,"query.addcriteria":{"(name.ilike":1}
,"(name.ilike":{"jul*\u0022)":1}
,"jul*\u0022)":{".and":1}
,".and":{"(gender.eq":1}
,"(gender.eq":{"(gender.female)))":1}
,"(gender.female)))":{".addorderby":1}
,".addorderby":{"(age":1}
,"(age":{"direction.ascending)":1}
,"direction.ascending)":{".maxresults":1}
,".maxresults":{"(10)":1}
,"(10)":{"execute":1}
,"execute":{"query":1}
,"look":{"results":1}
,"results":{"results":1,"=query.execute":1,"example":1}
,"=query.execute":{"system.out.println":1}
,"system.out.println":{"size":1,"(\u0022----results-----\u005Cn":1,"average":1,"count":1}
,"size":{"results.size":1}
,"results.size":{"())":1}
,"())":{"system.out.println":1,"{system.out.println":1,"restrict":1,"using":1}
,"(\u0022----results-----\u005Cn":{"(result":1}
,"(result":{"result":1}
,"result":{"results.all":1}
,"results.all":{"())":1}
,"{system.out.println":{"maxt":1}
,"maxt":{"key":1}
,"key":{"result.getkey":1}
,"result.getkey":{"value":1}
,"value":{"class":1,"result.getvalue":1}
,"class":{"result.getvalue":1}
,"result.getvalue":{".getclass":1,"aggregators":1}
,".getclass":{"value":1}
,"aggregators":{"perform":1,"find":1}
,"computations":{"across":1}
,"across":{"query":1}
,"computes":{"average":1}
,"average":{"age":1}
,"people":{"data":1,"newjerseycountquery.execute":1}
,"averageagequery":{"=bigmemory.createquery":1}
,"averageagequery.includeaggregator":{"(aggregators.average":1}
,"(aggregators.average":{"(age))":1}
,"(age))":{"system.out.println":1}
,"averageagequery.execute":{".all":1}
,".all":{".iterator":1}
,".iterator":{".next":1}
,".next":{".getaggregatorresults":1}
,".getaggregatorresults":{"())":1}
,"restrict":{"calculation":1}
,"calculation":{"subset":1}
,"subset":{"based":1}
,"based":{"search":1}
,"ages":{"query":1}
,"agesbetween":{"=bigmemory.createquery":1}
,"agesbetween.addcriteria":{"(age.between":1}
,"(age.between":{"(30":1}
,"(30":{"40))":1}
,"40))":{"agesbetween.includeaggregator":1}
,"agesbetween.includeaggregator":{"(aggregators.average":1}
,"agesbetween.execute":{".all":1}
,"find":{"number":1}
,"number":{"entries":1,"people":1}
,"entries":{"match":1}
,"match":{"search":1}
,"criteria":{"example":1}
,"finds":{"number":1}
,"live":{"new":1}
,"jersey":{"query":1}
,"newjerseycountquery":{"=bigmemory.createquery":1}
,".addcriteria":{"(state.eq":1}
,"(state.eq":{"\u0022))":1}
,"newjerseycountquery.includeaggregator":{"(aggregators.count":1}
,"(aggregators.count":{"())":1}
,"count":{"people":1}
,"newjerseycountquery.execute":{".all":1}
}
;Search.control.loadWordPairs(pairs);
