var pairs =
{
"terracotta":{"<terracotta>":1,"clustering":1,"server":1,"clients":1,"servers":1}
,"<terracotta>":{"element":1,"sub-element":1,"attribute":1,"attributes":1}
,"element":{"optional":1,"configuring":1}
,"optional":{"sub-element":1}
,"sub-element":{"<cache>":1,"<nonstop>":1}
,"<cache>":{"differently":1,"defined":1,"block":1}
,"differently":{"<cache>":1}
,"defined":{"ehcache.xml":1}
,"ehcache.xml":{"<terracotta>":1}
,"<nonstop>":{"information":1,"element":1}
,"information":{"<nonstop>":1,"consistency":1,"tune":1}
,"configuring":{"nonstop":1}
,"nonstop":{"cache":1}
,"cache":{"following":1,"consistency":1,"may":1,"using":1,"clustering":1,"data":1,"bigmemory":1,"hotset":1,"number":1,"elements":1,"present":1}
,"following":{"<terracotta>":1,"attributes":1,"<cache":1}
,"attribute":{"allows":1,"specified":1}
,"allows":{"control":1,"reads":1}
,"control":{"type":1}
,"type":{"data":1}
,"data":{"consistency":1,"exchange":1,"forcing":1,"reside":1,"safety":1}
,"consistency":{"distributed":1,"uses":1,"strong":1,"mode":1,"modes":1}
,"distributed":{"cache":1,"caches":1,"\u0022\u002F>":1}
,"uses":{"cache-level":1}
,"cache-level":{"locks":1}
,"locks":{"better":1,"immediate":1,"means":1,"may":1}
,"better":{"performance":1}
,"performance":{"eventual":1,"strong":1,"large":1,"distributed":1,"allowing":1,"cost":1}
,"eventual":{"default)":1,"allows":1,"bulk":1,"<\u002Fcache>":1}
,"default)":{"uses":1,"disables":1,"synchronous":1,"local":1}
,"immediate":{"cache":1}
,"strong":{"eventual":1,"guarantees":1}
,"reads":{"without":1}
,"without":{"locks":1,"waiting":1}
,"means":{"cache":1}
,"may":{"temporarily":1,"need":1,"improve":1}
,"temporarily":{"return":1}
,"return":{"stale":1}
,"stale":{"data":1,"value":1}
,"exchange":{"substantially":1}
,"substantially":{"improved":1}
,"improved":{"performance":1}
,"guarantees":{"update":1}
,"update":{"completed":1}
,"completed":{"local":1,"orphan":1}
,"local":{"read":1,"caching":1,"key":1,"eviction":1}
,"read":{"return":1}
,"value":{"potentially":1,"ffc-the":1,"300000":1,"less":1}
,"potentially":{"high":1}
,"high":{"cost":1}
,"cost":{"performance":1,"requiring":1}
,"large":{"number":1}
,"number":{"locks":1,"segments":1,"(positive":1,"local":1,"cycles":1}
,"need":{"stored":1}
,"stored":{"client":1}
,"client":{"server":1,"receive":1,"proceed":1}
,"server":{"heaps":1,"array":1,"acknowledgment":1,"store":1,"instances":1,"lower":1,"concern":1}
,"heaps":{"once":1}
,"once":{"consistency":1}
,"mode":{"cannot":1,"eventual":1}
,"cannot":{"changed":1}
,"changed":{"except":1,"programmatically":1}
,"except":{"reconfiguring":1,"special":1}
,"reconfiguring":{"cache":1}
,"using":{"configuration":1,"bulk-load":1}
,"configuration":{"file":1}
,"file":{"reloading":1,"setting":1}
,"reloading":{"file":1}
,"setting":{"cannot":1}
,"programmatically":{"information":1}
,"modes":{"except":1}
,"special":{"cases":1}
,"cases":{"following":1,"synchronouswrites":1,"synchronous":1,"note":1}
,"attributes":{"operate":1,"localcacheenabled":1,"used":1}
,"operate":{"default":1}
,"default":{"values":1,"value":1,"number":1,"behavior":1,"adding":1}
,"values":{"clustered":1}
,"clustered":{"enables":1}
,"enables":{"true":1}
,"true":{"default)":1,"disables":1,"provide":1,"ignored)":1,"consistency=\u0022":1}
,"disables":{"false":1,"effects":1}
,"false":{"terracotta":1,"local":1,"default)":1,"maximize":1,"orphan":1,"timetoidleseconds=\u0022":1}
,"clustering":{"specific":1,"enabled":1,"disables":1}
,"specific":{"cache":1}
,"enabled":{"attribute":1,"default":1}
,"specified":{"disabling":1}
,"disabling":{"clustering":1,"local":1}
,"effects":{"attributes":1}
,"localcacheenabled":{"enables":1}
,"caching":{"distributed":1,"may":1}
,"forcing":{"cached":1}
,"cached":{"data":1}
,"reside":{"terracotta":1}
,"array":{"disabling":1,"concurrency":1}
,"improve":{"performance":1}
,"caches":{"write-heavy":1}
,"write-heavy":{"cases":1}
,"synchronouswrites":{"enables":1}
,"synchronous":{"writes":1}
,"writes":{"terracotta":1,"(synchronouswrites=\u0022":1,"occur":1}
,"clients":{"(application":1,"proceed":1,"add":1}
,"(application":{"servers)":1}
,"servers)":{"terracotta":1}
,"servers":{"asynchronous":1}
,"asynchronous":{"writes":1}
,"(synchronouswrites=\u0022":{"false":1,"true":1}
,"maximize":{"performance":1}
,"allowing":{"clients":1}
,"proceed":{"without":1,"cache\u0027s":1}
,"waiting":{"transaction":1}
,"transaction":{"received":1,"client":1}
,"received":{"acknowledgment":1}
,"acknowledgment":{"server":1,"unnecessary":1,"transaction":1}
,"unnecessary":{"cases":1}
,"provide":{"extreme":1}
,"extreme":{"data":1}
,"safety":{"performance":1}
,"requiring":{"client":1}
,"receive":{"server":1}
,"cache\u0027s":{"consistency":1}
,"bulk":{"load":1}
,"load":{"using":1}
,"bulk-load":{"api":1}
,"api":{"asynchronous":1}
,"occur":{"(synchronouswrites=\u0022":1,"hibernate)":1}
,"ignored)":{"concurrency":1}
,"concurrency":{"sets":1,"explicitly":1,"information":1}
,"sets":{"number":1}
,"segments":{"map":1}
,"map":{"backing":1}
,"backing":{"underlying":1}
,"underlying":{"server":1}
,"store":{"managed":1}
,"managed":{"terracotta":1}
,"explicitly":{"(or":1}
,"(or":{"system":1}
,"system":{"selects":1}
,"selects":{"optimized":1}
,"optimized":{"value":1}
,"ffc-the":{"topic":1}
,"topic":{"referenced":1}
,"referenced":{"seem":1}
,"seem":{"exist":1}
,"exist":{"anymore":1}
,"anymore":{"[[see":1}
,"[[see":{"tuning":1}
,"tuning":{"concurrency":1}
,"tune":{"value.]]":1}
,"value.]]":{"removing":1}
,"removing":{"statement":1}
,"statement":{"now.>>":1}
,"now.>>":{"following":1}
,"used":{"hibernate":1}
,"hibernate":{"localkeycache":1,"second-level":1}
,"localkeycache":{"enables":1,"enabled":1}
,"key":{"cache":1}
,"bigmemory":{"max":1}
,"max":{"cache":1}
,"hotset":{"keys":1}
,"keys":{"clients":1,"small":1}
,"add":{"locality-of-reference":1}
,"locality-of-reference":{"feature":1}
,"feature":{"suitable":1}
,"suitable":{"read-only":1}
,"read-only":{"cases":1}
,"note":{"keys":1}
,"small":{"enough":1}
,"enough":{"available":1}
,"available":{"memory":1}
,"memory":{"localkeycachesize":1}
,"localkeycachesize":{"defines":1}
,"defines":{"size":1}
,"size":{"local":1}
,"(positive":{"integer)":1}
,"integer)":{"elements":1}
,"elements":{"effect":1,"resident":1}
,"effect":{"localkeycache":1}
,"300000":{"tuned":1}
,"tuned":{"meet":1}
,"meet":{"application":1}
,"application":{"requirements":1}
,"requirements":{"environmental":1}
,"environmental":{"limitations":1}
,"limitations":{"orphaneviction":1}
,"orphaneviction":{"enables":1}
,"orphan":{"eviction":1}
,"eviction":{"orphans":1,"cycles":1,"place":1,"reduce":1}
,"orphans":{"cache":1}
,"resident":{"hibernate":1}
,"second-level":{"cache":1}
,"present":{"cluster\u0027s":1}
,"cluster\u0027s":{"terracotta":1}
,"instances":{"orphanevictionperiod":1}
,"orphanevictionperiod":{"number":1}
,"cycles":{"(that":1,"raise":1}
,"(that":{"occur":1}
,"hibernate)":{"completed":1}
,"place":{"default":1}
,"raise":{"value":1}
,"less":{"aggressive":1}
,"aggressive":{"orphan":1}
,"reduce":{"faulting":1}
,"faulting":{"terracotta":1}
,"lower":{"garbage":1}
,"garbage":{"terracotta":1}
,"concern":{"default":1}
,"behavior":{"default":1}
,"adding":{"<terracotta\u002F>":1,"following":1}
,"<terracotta\u002F>":{"<cache>":1}
,"block":{"equivalent":1}
,"equivalent":{"adding":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"sampleterracottacache":1}
,"sampleterracottacache":{"maxentrieslocalheap=\u0022":1}
,"maxentrieslocalheap=\u0022":{"1000":1}
,"1000":{"eternal=\u0022":1}
,"eternal=\u0022":{"false":1}
,"timetoidleseconds=\u0022":{"3600":1}
,"3600":{"timetoliveseconds=\u0022":1}
,"timetoliveseconds=\u0022":{"1800":1}
,"1800":{"<persistence":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"distributed":1}
,"\u0022\u002F>":{"<terracotta":1}
,"<terracotta":{"clustered=\u0022":1}
,"clustered=\u0022":{"true":1}
,"consistency=\u0022":{"eventual":1}
}
;Search.control.loadWordPairs(pairs);
