var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fsecurity\u002Fkeychain":{"element":1}
,"element":{"contains":1,"specifying":1}
,"contains":{"following":1}
,"following":{"subelements":1}
,"subelements":{"<class>":1}
,"<class>":{"element":1}
,"specifying":{"class":1}
,"class":{"defining":1,"specified":1,"specify":1,"name":1,"read":1}
,"defining":{"keychain":1}
,"keychain":{"file":1,"class":1}
,"file":{"class":1,"passed":1,"<secret-provider>":1}
,"specified":{"com.terracotta.management.keychain.filestorekeychain":1}
,"com.terracotta.management.keychain.filestorekeychain":{"used":1}
,"used":{"<url>":1}
,"<url>":{"uri":1}
,"uri":{"keychain":1}
,"passed":{"keychain":1}
,"specify":{"keychain":1}
,"<secret-provider>":{"fully":1}
,"fully":{"qualified":1}
,"qualified":{"class":1}
,"name":{"user":1}
,"user":{"implementation":1}
,"implementation":{"com.terracotta.management.security.secretproviderbackend":1}
,"com.terracotta.management.security.secretproviderbackend":{"class":1}
,"read":{"provide":1}
,"provide":{"keychain":1}
}
;Search.control.loadWordPairs(pairs);
