var pairs =
{
"definitions":{"functional":1}
,"functional":{"characteristics":1}
,"characteristics":{"major":1,"mirror":1}
,"major":{"components":1}
,"components":{"terracotta":1}
,"terracotta":{"installation":1,"server":1,"client":1,"clients":1,"mirror":1,"configuration":1,"cluster":1}
,"installation":{"following":1}
,"following":{"cluster":1,"functional":1}
,"cluster":{"-all":1,"mirror":1,"clustered":1,"three":1,"terracotta":1,"following":1,"ready":1,"automatically":1,"--they":1,"pause":1,"functions":1,"brought":1,"provide":1}
,"-all":{"terracotta":1}
,"server":{"instances":1,"instance":1,"active":1,"array":1,"mirror":1,"having":1}
,"instances":{"clients":1,"awareness":1,"single":1,"management":1,"mirror":1,"hot-swapped":1}
,"clients":{"work":1,"run":1,"manage":1,"coordinates":1,"mirror":1}
,"work":{"together":1,"shared":1}
,"together":{"share":1}
,"share":{"application":1}
,"application":{"state":1,"servers":1}
,"state":{"data":1}
,"data":{"terracotta":1,"server":1,"active":1,"allotted":1,"managed":1,"called":1,"shared":1,"partitioned":1,"cluster":1,"intact":1}
,"client":{"-terracotta":1,"(the":1}
,"-terracotta":{"clients":1}
,"run":{"application":1}
,"servers":{"along":1,"add":1,"optional":1,"due":1,"self-coordinating":1,"shut":1,"added":1,"address":1}
,"along":{"applications":1}
,"applications":{"clustered":1,"running":1}
,"clustered":{"terracotta":1,"applications":1,"data":1}
,"manage":{"live":1}
,"live":{"shared-object":1,"backup":1,"cluster":1}
,"shared-object":{"graphs":1}
,"graphs":{"terracotta":1}
,"instance":{"single":1,"manages":1,"continuously":1,"instantaneously":1,"least":1,"active":1,"terracotta":1,"per":1}
,"single":{"terracotta":1,"cluster":1}
,"active":{"server":1,"active":1,"fails":1,"terracotta":1,"mode":1,"servers":1}
,"manages":{"terracotta":1,"persists":1,"third":1}
,"coordinates":{"shared":1}
,"shared":{"objects":1,"data":1}
,"objects":{"persists":1}
,"persists":{"data":1,"fraction":1}
,"awareness":{"clustered":1}
,"running":{"terracotta":1,"application)":1}
,"mirror":{"(sometimes":1,"servers":1,"group":1,"terracotta":1,"server":1,"groups":1,"manages":1,"every":1,"different":1}
,"(sometimes":{"called":1}
,"called":{"hot":1,"stripe":1,"in-memory":1}
,"hot":{"standby":1}
,"standby":{"live":1}
,"backup":{"server":1}
,"continuously":{"replicates":1}
,"replicates":{"shared":1,"(or":1}
,"instantaneously":{"replacing":1}
,"replacing":{"active":1}
,"fails":{"mirror":1}
,"add":{"failover":1,"capacity":1,"remove":1}
,"failover":{"coverage":1,"terracotta":1,"failover":1,"provided":1}
,"coverage":{"within":1}
,"within":{"mirror":1}
,"group":{"terracotta":1,"unit":1,"composed":1,"mirror":1,"replicates":1,"active":1,"automatically":1,"number":1,"cluster":1,"third":1,"across":1,"down":1,"back":1}
,"unit":{"terracotta":1}
,"array":{"sometimes":1,"-the":1,"fig":1}
,"sometimes":{"called":1}
,"stripe":{"mirror":1}
,"composed":{"exactly":1}
,"exactly":{"active":1}
,"least":{"mirror":1}
,"fraction":{"shared":1}
,"allotted":{"mirror":1}
,"(or":{"mirrors)":1}
,"mirrors)":{"shared":1}
,"managed":{"active":1}
,"groups":{"add":1,"mirror":1,"number":1,"fig":1,"cannot":1,"provide":1}
,"capacity":{"cluster":1}
,"optional":{"highly":1}
,"highly":{"recommended":1}
,"recommended":{"providing":1}
,"providing":{"failover":1}
,"-the":{"platform":1}
,"platform":{"consisting":1}
,"consisting":{"terracotta":1}
,"in-memory":{"data":1}
,"partitioned":{"equally":1,"distributed":1}
,"equally":{"among":1}
,"among":{"active":1,"themselves":1}
,"management":{"persistence":1}
,"persistence":{"purposes":1}
,"purposes":{"nomenclature":1}
,"nomenclature":{"-this":1}
,"-this":{"documentation":1}
,"documentation":{"may":1}
,"may":{"refer":1,"become":1}
,"refer":{"terracotta":1}
,"(the":{"node":1}
,"node":{"running":1}
,"application)":{"shorthand":1}
,"shorthand":{"references":1}
,"references":{"used":1}
,"used":{"terracotta":1}
,"configuration":{"files":1,"required":1,"file":1,"changing":1}
,"files":{"figure":1}
,"figure":{"illustrates":1}
,"illustrates":{"terracotta":1}
,"three":{"mirror":1}
,"third":{"shared":1}
,"automatically":{"elects":1,"partitioned":1}
,"elects":{"active":1}
,"per":{"mirror":1}
,"number":{"mirrors":1,"partitions":1,"mirror":1}
,"mirrors":{"however":1}
,"however":{"performance":1,"add":1}
,"performance":{"overhead":1}
,"overhead":{"may":1}
,"become":{"evident":1}
,"evident":{"adding":1}
,"adding":{"mirror":1}
,"due":{"load":1}
,"load":{"placed":1}
,"placed":{"active":1}
,"having":{"synchronize":1}
,"synchronize":{"mirror":1}
,"every":{"mirror":1}
,"mode":{"cluster":1}
,"ready":{"work":1}
,"distributed":{"mirror":1}
,"partitions":{"equals":1}
,"equals":{"number":1}
,"fig":{"mirror":1}
,"cannot":{"provide":1}
,"provide":{"failover":1,"scale":1,"correct":1}
,"provided":{"within":1}
,"across":{"mirror":1}
,"scale":{"managing":1}
,"managing":{"discrete":1}
,"discrete":{"portions":1}
,"portions":{"shared":1}
,"--they":{"replicate":1}
,"replicate":{"fig":1}
,"down":{"cluster":1,"replaced":1,"note":1}
,"pause":{"(stop":1}
,"(stop":{"work)":1}
,"work)":{"until":1}
,"until":{"mirror":1}
,"back":{"portion":1}
,"portion":{"shared":1}
,"intact":{"active":1}
,"self-coordinating":{"among":1}
,"themselves":{"additional":1}
,"additional":{"configuration":1}
,"required":{"coordinate":1}
,"coordinate":{"active":1}
,"hot-swapped":{"array":1}
,"shut":{"down":1}
,"replaced":{"affect":1,"mirror":1}
,"affect":{"cluster":1}
,"functions":{"however":1}
,"remove":{"entire":1}
,"entire":{"mirror":1}
,"brought":{"down":1}
,"note":{"case":1}
,"case":{"original":1}
,"original":{"terracotta":1}
,"file":{"effect":1}
,"effect":{"new":1}
,"new":{"servers":1}
,"added":{"replaced":1,"link":1}
,"address":{"(hostname":1}
,"(hostname":{"address)":1}
,"address)":{"swap":1}
,"swap":{"mirror":1}
,"different":{"configuration":1}
,"changing":{"topology":1}
,"topology":{"live":1}
,"correct":{"link":1}
,"link":{"don":1}
,"don":{"added":1}
}
;Search.control.loadWordPairs(pairs);
