var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fsecurity":{"section":1}
,"section":{"contains":1}
,"contains":{"data":1}
,"data":{"necessary":1}
,"necessary":{"running":1}
,"running":{"secure":1}
,"secure":{"cluster":1}
,"cluster":{"based":1,"bigmemory":1}
,"based":{"ssl":1}
,"ssl":{"digital":1}
,"digital":{"certificates":1}
,"certificates":{"node":1}
,"node":{"authentication":1}
,"authentication":{"authorization":1}
,"authorization":{"information":1}
,"information":{"security":1}
,"security":{"cluster":1,"guide":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
}
;Search.control.loadWordPairs(pairs);
