var pairs =
{
"setting":{"authentication\u002Fauthorization":1}
,"authentication\u002Fauthorization":{"servers":1,"mechanism":1}
,"servers":{"clients":1,"<username>":1,"information":1}
,"clients":{"connect":1,"usermanagement":1,"username":1,"admin":1}
,"connect":{"secured":1}
,"secured":{"server":1,"terracotta":1}
,"server":{"credentials":1,"itself":1,"username":1,"tools\u002Fsecurity\u002Fbin\u002Fusermanagement.sh":1,"configuration":1}
,"credentials":{"(usernames\u002Fpasswords)":1}
,"(usernames\u002Fpasswords)":{"roles":1}
,"roles":{"(authorization)":1,"associated":1,"refer":1,"example":1}
,"(authorization)":{"defined":1}
,"defined":{"section":1}
,"section":{"discusses":1}
,"discusses":{"authentication\u002Fauthorization":1}
,"mechanism":{"based":1}
,"based":{"using":1}
,"using":{".ini":1,"usermanagement":1}
,".ini":{"file":1}
,"file":{"ldap":1,"contains":1,"nodes":1,"local":1,"already":1,"add":1,"<auth>":1}
,"ldap":{"microsoft":1,"active":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"directory":{"instead":1,"setup":1,"script":1}
,"instead":{"ldap":1}
,"setup":{"page":1}
,"page":{"authentication":1}
,"authentication":{"authorization":1}
,"authorization":{"using":1}
,"usermanagement":{"script":1}
,"script":{"located":1,"creates":1,"following":1}
,"located":{"terracotta":1}
,"terracotta":{"kit\u0027s":1,"cluster":1,"required":1,"role":1,"servers":1,"add":1,"(read)":1}
,"kit\u0027s":{"tools\u002Fsecurity\u002Fbin":1}
,"tools\u002Fsecurity\u002Fbin":{"directory":1}
,"creates":{".ini":1}
,"contains":{"required":1}
,"required":{"usernames":1,"file":1}
,"usernames":{"roles":1}
,"associated":{"passwords":1}
,"passwords":{"stored":1}
,"stored":{"keychain":1}
,"keychain":{"file":1}
,"nodes":{"secured":1}
,"cluster":{"entry":1}
,"entry":{"server\u0027s":1}
,"server\u0027s":{".ini":1}
,"local":{"server":1}
,"itself":{"servers":1}
,"following":{"format":1}
,"format":{"tools\u002Fsecurity\u002Fbin\u002Fusermanagement.sh":1}
,"tools\u002Fsecurity\u002Fbin\u002Fusermanagement.sh":{"<file>":1,"my_auth.ini":1}
,"<file>":{"<username>":1}
,"<username>":{"terracotta":1,"used":1}
,"already":{"exist":1}
,"exist":{"servers":1}
,"used":{"value":1,"start":1}
,"value":{"configured":1}
,"configured":{"<security>\u002F<auth>\u002F<user>":1}
,"<security>\u002F<auth>\u002F<user>":{"clients":1}
,"username":{"match":1,"role":1}
,"match":{"used":1}
,"start":{"client":1}
,"client":{"terracotta":1,"tools\u002Fsecurity\u002Fbin\u002Fusermanagement.sh":1}
,"role":{"appropriate":1,"necessary":1,"tools\u002Fsecurity\u002Fbin\u002Fusermanagement.sh":1}
,"appropriate":{"terracotta":1}
,"admin":{"role":1,"(read\u002Fwrite)":1,"add":1}
,"necessary":{"performing":1}
,"performing":{"system":1}
,"system":{"functions":1}
,"functions":{"stopping":1}
,"stopping":{"servers":1}
,"information":{"roles":1}
,"refer":{"user":1}
,"user":{"roles":1,"admin":1,"terracotta":1}
,"example":{"create":1}
,"create":{".ini":1}
,"add":{"server":1,"client":1,"user":1}
,"my_auth.ini":{"server1username":1,"server2username":1,"client1username":1,"admin1username":1,"console1username":1}
,"server1username":{"terracotta":1,"<\u002Fuser>":1}
,"server2username":{"terracotta":1}
,"client1username":{"terracotta":1}
,"(read\u002Fwrite)":{"role":1}
,"admin1username":{"admin":1}
,"(read)":{"role":1}
,"console1username":{"operator":1}
,"operator":{"correct":1}
,"correct":{"apache":1}
,"apache":{"shiro":1}
,"shiro":{"realm":1}
,"realm":{"specified":1}
,"specified":{"server":1}
,"configuration":{"along":1}
,"along":{"path":1}
,"path":{".ini":1}
,"<auth>":{"<realm>":1}
,"<realm>":{"com.tc.net.core.security.shiroinirealm":1}
,"com.tc.net.core.security.shiroinirealm":{"<\u002Frealm>":1}
,"<\u002Frealm>":{"<url>":1}
,"<url>":{"file:\u002F\u002F\u002F%":1}
,"file:\u002F\u002F\u002F%":{"(user.dir)\u002Fmy_auth.ini":1}
,"(user.dir)\u002Fmy_auth.ini":{"<\u002Furl>":1}
,"<\u002Furl>":{"<user>":1}
,"<user>":{"server1username":1}
,"<\u002Fuser>":{"<\u002Fauth>":1}
}
;Search.control.loadWordPairs(pairs);
