var pairs =
{
"run-time":{"monitoring":1,"component":1}
,"monitoring":{"states":1,"runtimestate":1,"state":1}
,"states":{"terracotta":1}
,"terracotta":{"response":1,"run-time":1,"server":1}
,"response":{"sagcc":1}
,"sagcc":{"monitoring":1}
,"runtimestate":{"sagcc":1}
,"state":{"commands":1}
,"commands":{"terracotta":1}
,"component":{"provides":1}
,"provides":{"information":1}
,"information":{"following":1}
,"following":{"key":1}
,"key":{"performance":1}
,"performance":{"indicators":1}
,"indicators":{"(kpis)":1}
,"(kpis)":{"kpi":1}
,"kpi":{"description":1}
,"description":{"live":1}
,"live":{"object":1,"objects":1}
,"object":{"count":1}
,"count":{"number":1}
,"number":{"live":1}
,"objects":{"cache":1}
,"cache":{"offheap":1,"write":1,"kpis":1}
,"offheap":{"off-heap":1}
,"off-heap":{"storage":1}
,"storage":{"capacity":1}
,"capacity":{"cache":1}
,"write":{"operations":1}
,"operations":{"rate":1,"cache":1}
,"rate":{"rate":1,"write":1}
,"kpis":{"apply":1}
,"apply":{"whole":1}
,"whole":{"terracotta":1}
,"server":{"array":1}
,"array":{"cluster":1}
}
;Search.control.loadWordPairs(pairs);
