var pairs =
{
"cross-language":{"clients":1}
,"clients":{"bigmemory":1,"provide":1}
,"bigmemory":{"cross-language":1,"data":1,"(.net":1,"via":1}
,"provide":{"access":1}
,"access":{"bigmemory":1,"data":1}
,"data":{"multiple":1,"created":1,"transport":1}
,"multiple":{"client":1}
,"client":{"platforms":1,"library":1}
,"platforms":{"java":1,"means":1}
,"java":{".net":1,"application":1}
,".net":{"interoperability":1,"applications":1}
,"interoperability":{"client":1}
,"means":{"application":1}
,"application":{"access":1,"java":1,".net":1}
,"created":{"java":1,"application":1}
,"applications":{"full":1}
,"full":{"advantage":1}
,"advantage":{"bigmemory\u0027s":1}
,"bigmemory\u0027s":{"scalability":1}
,"scalability":{"performance":1}
,"performance":{"bigmemory":1}
,"(.net":{"client":1}
,"library":{"installed":1}
,"installed":{"target":1}
,"target":{"platform":1}
,"platform":{"apis":1}
,"apis":{"communication":1}
,"communication":{"data":1}
,"transport":{"bigmemory":1,"(universal":1}
,"via":{"cross":1,"nirvana":1}
,"cross":{"language":1}
,"language":{"(cl)":1}
,"(cl)":{"connector":1}
,"connector":{"connection":1,"via":1,"runs":1}
,"connection":{"connector":1}
,"nirvana":{"sockets":1}
,"sockets":{"shared":1}
,"shared":{"memory":1}
,"memory":{"transport":1}
,"(universal":{"messaging)":1}
,"messaging)":{"connector":1}
,"runs":{"jvm":1}
,"jvm":{"process":1}
,"process":{"communicating":1}
,"communicating":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
