var pairs =
{
"configuring":{"nonstop":1}
,"nonstop":{"cache":1,"behavior":1,"operation":1,"enabled":1,"disabled":1,"<nonstop":1}
,"cache":{"nonstop":1}
,"behavior":{"configured":1}
,"configured":{"specifying":1,"nonstop":1}
,"specifying":{"<nonstop>":1}
,"<nonstop>":{"element":1,"specified":1}
,"element":{"<terracotta>":1,"within":1,"present":1,"supplied":1}
,"<terracotta>":{"element":1,"<nonstop":1}
,"within":{"<cache>":1}
,"<cache>":{"block":1}
,"block":{"following":1}
,"following":{"example":1}
,"example":{"mycache":1}
,"mycache":{"configured":1,"maxentrieslocalheap=\u0022":1}
,"operation":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"mycache":1}
,"maxentrieslocalheap=\u0022":{"10000":1}
,"10000":{"eternal=\u0022":1}
,"eternal=\u0022":{"false":1}
,"false":{"<terracotta>":1,"timeoutmillis=\u0022":1,"nonstop":1}
,"<nonstop":{"immediatetimeout=\u0022":1,"<nonstop>":1}
,"immediatetimeout=\u0022":{"false":1}
,"timeoutmillis=\u0022":{"30000":1}
,"30000":{"<timeoutbehavior":1}
,"<timeoutbehavior":{"type=\u0022":1}
,"type=\u0022":{"noop":1}
,"noop":{"<\u002Fnonstop>":1}
,"<\u002Fnonstop>":{"<\u002Fterracotta>":1}
,"<\u002Fterracotta>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"nonstop":1}
,"enabled":{"<nonstop>":1}
,"present":{"however":1}
,"however":{"<nonstop>":1}
,"specified":{"attribute":1}
,"attribute":{"enabled=\u0022":1}
,"enabled=\u0022":{"false":1,"true":1}
,"disabled":{"default":1}
,"default":{"setting":1}
,"setting":{"optional":1}
,"optional":{"attribute":1}
,"true":{"minimal":1}
,"minimal":{"syntax":1}
,"syntax":{"enable":1}
,"enable":{"nonstop":1}
,"supplied":{"nonstop":1}
}
;Search.control.loadWordPairs(pairs);
