var pairs =
{
"configuration":{"using":1,"panel":1,"information":1,"file":1}
,"using":{"subpanels":1,"process":1}
,"subpanels":{"configuration":1,"available":1}
,"panel":{"displays":1,"following":1}
,"displays":{"status":1,"server":1}
,"status":{"environment":1,"list":1}
,"environment":{"configuration":1,"-the":1}
,"information":{"servers":1,"useful":1}
,"servers":{"clients":1,"panel":1}
,"clients":{"selected":1}
,"selected":{"cluster":1,"view":1}
,"cluster":{"node":1}
,"node":{"menu":1}
,"menu":{"information":1}
,"useful":{"debugging":1}
,"debugging":{"reporting":1}
,"reporting":{"problems":1}
,"problems":{"main":1}
,"main":{"subpanel":1}
,"subpanel":{"displays":1,"administrators":1}
,"server":{"status":1,"selected":1,"using":1,"started":1}
,"list":{"properties":1}
,"properties":{"including":1,"tcproperties":1,"server":1}
,"including":{"address":1}
,"address":{"version":1}
,"version":{"license":1}
,"license":{"(capabilities)":1}
,"(capabilities)":{"restartability":1}
,"restartability":{"failover":1}
,"failover":{"modes":1}
,"modes":{"specific":1}
,"specific":{"server":1}
,"view":{"subpanel":1}
,"administrators":{"shut":1}
,"shut":{"down":1}
,"down":{"servers":1}
,"following":{"additional":1}
,"additional":{"subpanels":1}
,"available":{"environment":1}
,"-the":{"server\u0027s":1,"terracotta":1,"jvm":1}
,"server\u0027s":{"jvm":1}
,"jvm":{"system":1,"arguments":1}
,"system":{"properties":1}
,"tcproperties":{"-the":1}
,"terracotta":{"properties":1,"configuration":1}
,"process":{"args":1}
,"args":{"-the":1}
,"arguments":{"server":1}
,"started":{"tcconfig":1}
,"tcconfig":{"-the":1}
,"file":{"server":1}
}
;Search.control.loadWordPairs(pairs);
