var pairs =
{
"diagnostics":{"following":1}
,"following":{"uri":1}
,"uri":{"extensions":1}
,"extensions":{"base":1}
,"base":{"extension":1}
,"extension":{"\u002Fagents\u002Fdiagnostics":1}
,"\u002Fagents\u002Fdiagnostics":{"\u002Fv2\u002Fagents\u002Fdiagnostics":1}
,"\u002Fv2\u002Fagents\u002Fdiagnostics":{"return":1}
,"return":{"information":1}
,"information":{"useful":1,"(including":1,"getting":1}
,"useful":{"diagnosing":1}
,"diagnosing":{"trouble":1}
,"trouble":{"initiate":1}
,"initiate":{"dgc":1}
,"dgc":{"cycle":1,"cycles":1}
,"cycle":{"thread":1,"post":1}
,"thread":{"dumps":1,"dump":1}
,"dumps":{"full":1,"written":1,"saved":1,"node":1,"dgc":1}
,"full":{"thread":1}
,"dump":{"servers":1,"clients":1}
,"servers":{"clients":1,"\u002Fthreaddump\u002Fservers":1,"included":1}
,"clients":{"\u002Fthreaddump":1,"\u002Fthreaddump\u002Fclients":1,"included":1}
,"\u002Fthreaddump":{"thread":1}
,"\u002Fthreaddump\u002Fservers":{"names=a":1}
,"names=a":{"names":1}
,"names":{"specified":1}
,"specified":{"servers":1,"clients":1}
,"included":{"thread":1}
,"\u002Fthreaddump\u002Fclients":{"ids=x":1}
,"ids=x":{"ids":1}
,"ids":{"specified":1}
,"written":{"logs":1}
,"logs":{"respective":1}
,"respective":{"nodes":1}
,"nodes":{"generated":1}
,"generated":{"thread":1}
,"saved":{"zip":1}
,"zip":{"file":1}
,"file":{"threaddumparchive":1}
,"threaddumparchive":{"instead":1}
,"instead":{"threaddump":1}
,"threaddump":{"write":1,"action":1}
,"write":{"cluster":1}
,"cluster":{"state":1}
,"state":{"information":1}
,"(including":{"example":1}
,"example":{"locks)":1}
,"locks)":{"addition":1}
,"addition":{"thread":1}
,"node":{"dumpclusterstate":1}
,"dumpclusterstate":{"instead":1}
,"action":{"generates":1}
,"generates":{"substantially":1}
,"substantially":{"information":1}
,"getting":{"thread":1}
,"cycles":{"initiate":1}
,"post":{"\u002Fdgc":1}
}
;Search.control.loadWordPairs(pairs);
