var pairs =
{
"viewing":{"session":1}
,"session":{"vms":1,"data":1}
,"vms":{"session":1}
,"data":{"automatically":1,"sharing":1,"shared":1}
,"automatically":{"made":1,"transparently":1}
,"made":{"consistent":1}
,"consistent":{"available":1}
,"available":{"application":1}
,"application":{"server":1,"code":1}
,"server":{"click":1,"link":1,"web":1,"instances":1}
,"click":{"server":1}
,"link":{"colored":1,"observe":1}
,"colored":{"box":1}
,"box":{"notice":1}
,"notice":{"product":1}
,"product":{"browsing":1}
,"browsing":{"history":1}
,"history":{"intact":1}
,"intact":{"even":1}
,"even":{"application":1}
,"web":{"sessions":1}
,"sessions":{"automatically":1}
,"transparently":{"clustering":1}
,"clustering":{"session":1}
,"sharing":{"two":1}
,"two":{"server":1}
,"instances":{"demand":1,"fine-grained":1}
,"demand":{"change":1}
,"change":{"cart":1}
,"cart":{"click":1}
,"observe":{"session":1}
,"shared":{"across":1}
,"across":{"two":1}
,"fine-grained":{"field-change":1}
,"field-change":{"level":1}
,"level":{"independent":1}
,"independent":{"application":1}
}
;Search.control.loadWordPairs(pairs);
