var pairs =
{
"cache":{"events":1,"operations":1,"uses":1,"update":1,"methods":1,"updates":1}
,"events":{"terracotta":1,"fired":1,"caches":1,"whenever":1,"cache":1}
,"terracotta":{"cluster":1,"server":1,"property":1,"configuration":1}
,"cluster":{"cache":1,"defining":1}
,"fired":{"certain":1,"random":1}
,"certain":{"cache":1}
,"operations":{"evictions":1,"(cache.containskey":1}
,"evictions":{"eviction":1}
,"eviction":{"client":1,"event":1,"terracotta":1,"orphan":1}
,"client":{"generates":1,"eviction":1,"puts":1,"updates":1,"orphan":1,"information":1}
,"generates":{"eviction":1,"put":1}
,"event":{"client":1,"random":1,"fired":1,"handler":1}
,"server":{"fires":1,"array":1}
,"fires":{"event":1}
,"random":{"client":1}
,"puts":{"put":1,"updates":1,"protect":1,"else":1}
,"put":{"client":1,"event":1,"events":1,"updated":1,"operations":1}
,"updates":{"cache":1,"check":1,"setting":1}
,"uses":{"fast":1}
,"fast":{"restart":1}
,"restart":{"update":1}
,"update":{"client":1,"events":1}
,"orphan":{"eviction":1,"element":1,"evicted":1}
,"element":{"exists":1,"during":1,"\u002F\u002Freturns":1,"((olde":1}
,"exists":{"terracotta":1}
,"array":{"orphan":1,"<tc-properties>":1}
,"evicted":{"eviction":1}
,"information":{"configuring":1}
,"configuring":{"scope":1}
,"scope":{"cache":1}
,"defining":{"distributed":1}
,"distributed":{"configuration":1}
,"configuration":{"configuration":1,"guide":1,"file":1}
,"guide":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"handling":1}
,"handling":{"cache":1}
,"caches":{"generate":1}
,"generate":{"put":1}
,"whenever":{"elements":1}
,"elements":{"put":1}
,"updated":{"important":1}
,"important":{"application":1}
,"application":{"distinguish":1}
,"distinguish":{"puts":1}
,"check":{"existence":1}
,"existence":{"element":1}
,"during":{"put":1}
,"(cache.containskey":{"(key))":1}
,"(key))":{"{cache.put":1}
,"{cache.put":{"(element)":1}
,"(element)":{"\u002F\u002Faction":1}
,"\u002F\u002Faction":{"event":1}
,"handler":{"replace":1,"new":1}
,"replace":{"else":1,"code":1}
,"else":{"{cache.put":1,"{cache.replace":1}
,"new":{"puts":1}
,"protect":{"against":1}
,"against":{"races":1}
,"races":{"wrap":1}
,"wrap":{"block":1}
,"block":{"explicit":1}
,"explicit":{"locks":1,"locking)":1}
,"locks":{"(see":1}
,"(see":{"using":1}
,"using":{"explicit":1}
,"locking)":{"atomic":1}
,"atomic":{"cache":1}
,"methods":{"putifabsent":1}
,"putifabsent":{"check":1}
,"\u002F\u002Freturns":{"null":1,"true":1}
,"null":{"successful":1}
,"successful":{"returns":1,"\u002F\u002Faction":1}
,"returns":{"existing":1}
,"existing":{"(old)":1}
,"(old)":{"element":1}
,"((olde":{"=cache.putifabsent":1}
,"=cache.putifabsent":{"(element))":1}
,"(element))":{"==null)":1}
,"==null)":{"{\u002F\u002Faction":1}
,"{\u002F\u002Faction":{"event":1}
,"{cache.replace":{"(old":1}
,"(old":{"newelement)":1}
,"newelement)":{"\u002F\u002Freturns":1}
,"true":{"successful":1,"<\u002Ftc-properties>":1}
,"code":{"cannot":1}
,"cannot":{"approaches":1}
,"approaches":{"(or":1}
,"(or":{"similar":1}
,"similar":{"workaround)":1}
,"workaround)":{"force":1}
,"force":{"update":1}
,"setting":{"terracotta":1}
,"property":{"ehcache.clusteredstore.checkcontainskeyonput":1,"substantially":1}
,"ehcache.clusteredstore.checkcontainskeyonput":{"top":1,"value=\u0022":1}
,"top":{"terracotta":1}
,"file":{"(tc-config.xml":1}
,"(tc-config.xml":{"default)":1}
,"default)":{"starting":1}
,"starting":{"terracotta":1}
,"<tc-properties>":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"ehcache.clusteredstore.checkcontainskeyonput":1}
,"value=\u0022":{"true":1}
,"<\u002Ftc-properties>":{"enabling":1}
,"enabling":{"property":1}
,"substantially":{"degrade":1}
,"degrade":{"performance":1}
}
;Search.control.loadWordPairs(pairs);
