var pairs =
{
"faq":{"bigmemory":1}
,"bigmemory":{"max":1,"max\u0027s":1}
,"max":{"application":1,"support":1}
,"application":{"hibernate":1,"may":1}
,"hibernate":{"second-level":1,"app\u0027s":1,"case":1,"distribution":1,"2.1":1,"included":1,"bigmemory":1,"whenever":1,"invalidates":1,"issue":1,"entities":1,"identifies":1,"read\u002Fwrite":1,"messages":1}
,"second-level":{"caching":1}
,"caching":{"try":1}
,"try":{"cachemanager":1}
,"cachemanager":{"created":1,"automatic":1}
,"created":{"hibernate":1}
,"app\u0027s":{"caches":1}
,"caches":{"share":1,"sometimes":1}
,"share":{"resource":1}
,"resource":{"file":1,"control":1}
,"file":{"two":1}
,"two":{"cachemanagers":1,"recommended":1}
,"cachemanagers":{"clear":1}
,"clear":{"separation":1}
,"separation":{"two":1}
,"recommended":{"application":1}
,"may":{"different":1}
,"different":{"lifecycle":1,"provider":1}
,"lifecycle":{"hibernate":1}
,"case":{"cachemanager":1}
,"automatic":{"resource":1}
,"control":{"settings":1}
,"settings":{"need":1}
,"need":{"different":1}
,"provider":{"hibernate":1,"periodically":1,"ehcache":1}
,"distribution":{"bigmemory":1,"new":1}
,"max\u0027s":{"ehcache":1}
,"ehcache":{"hibernate":1,"cacheprovider":1,"core":1,"2.1":1}
,"2.1":{"hibernate":1,"certain":1}
,"included":{"ehcache":1}
,"cacheprovider":{"provider":1}
,"periodically":{"synced":1}
,"synced":{"provider":1}
,"core":{"distribution":1,"provider":1}
,"new":{"features":1}
,"features":{"generally":1}
,"generally":{"added":1}
,"added":{"ehcache":1}
,"support":{"transactional":1}
,"transactional":{"strategy":1}
,"strategy":{"introduced":1,"force":1}
,"introduced":{"ehcache":1}
,"certain":{"caches":1}
,"sometimes":{"automatically":1}
,"automatically":{"cleared":1}
,"cleared":{"hibernate":1}
,"whenever":{"query.executeupdate":1,"stored":1}
,"query.executeupdate":{"run":1}
,"run":{"hibernate":1}
,"invalidates":{"affected":1}
,"affected":{"cache":1,"database":1}
,"cache":{"regions":1,"locked":1,"commit":1,"during":1,"fail":1,"entry":1}
,"regions":{"(those":1}
,"(those":{"corresponding":1}
,"corresponding":{"affected":1}
,"database":{"tables)":1,"row":1,"during":1,"does)":1,"next":1,"load":1}
,"tables)":{"ensure":1}
,"ensure":{"stale":1}
,"stale":{"data":1}
,"data":{"cached":1}
,"cached":{"happen":1,"entities":1}
,"happen":{"whenever":1}
,"stored":{"procedures":1}
,"procedures":{"executed":1}
,"executed":{"information":1}
,"information":{"hibernate":1}
,"issue":{"hhh-2224":1}
,"hhh-2224":{"https:\u002F\u002Fhibernate.atlassian.net\u002Fbrowse\u002Fhhh-2224":1}
,"https:\u002F\u002Fhibernate.atlassian.net\u002Fbrowse\u002Fhhh-2224":{"hibernate":1}
,"entities":{"keyed":1,"using":1}
,"keyed":{"hibernate":1}
,"identifies":{"cached":1}
,"using":{"object":1}
,"object":{"normally":1,"non-fatal":1}
,"normally":{"primary":1}
,"primary":{"key":1}
,"key":{"database":1}
,"row":{"compound":1}
,"compound":{"keys":1}
,"keys":{"supported":1}
,"supported":{"getting":1}
,"getting":{"error":1}
,"error":{"message":1}
,"message":{"item":1}
,"item":{"expired":1}
,"expired":{"cache":1}
,"locked":{"soft":1,"thus":1}
,"soft":{"locks":1}
,"locks":{"implemented":1}
,"implemented":{"replacing":1}
,"replacing":{"value":1}
,"value":{"special":1}
,"special":{"type":1}
,"type":{"marks":1}
,"marks":{"element":1}
,"element":{"locked":1,"used":1,"evicted":1,"evicted)":1}
,"thus":{"indicating":1}
,"indicating":{"threads":1}
,"threads":{"treat":1}
,"treat":{"differently":1}
,"differently":{"normal":1}
,"normal":{"element":1}
,"used":{"hibernate":1}
,"read\u002Fwrite":{"strategy":1}
,"force":{"fall-through":1}
,"fall-through":{"database":1}
,"during":{"two-phase":1}
,"two-phase":{"commit":1}
,"commit":{"cannot":1,"process":1,"once":1,"completes":1}
,"cannot":{"know":1}
,"know":{"exactly":1}
,"exactly":{"returned":1}
,"returned":{"cache":1}
,"process":{"(but":1}
,"(but":{"database":1}
,"does)":{"soft-locked":1}
,"soft-locked":{"element":1}
,"evicted":{"cache":1}
,"once":{"two-phase":1}
,"completes":{"cache":1}
,"fail":{"update":1}
,"update":{"(since":1}
,"(since":{"soft-locked":1}
,"evicted)":{"cache":1}
,"entry":{"reloaded":1}
,"reloaded":{"database":1}
,"next":{"read":1}
,"read":{"object":1}
,"non-fatal":{"increase":1}
,"increase":{"database":1}
,"load":{"slightly":1}
,"slightly":{"summary":1}
,"summary":{"hibernate":1}
,"messages":{"problematic":1}
,"problematic":{"underlying":1}
,"underlying":{"cause":1}
,"cause":{"probabilistic":1}
,"probabilistic":{"evictor":1}
,"evictor":{"theoretically":1,"avoid":1}
,"theoretically":{"evict":1}
,"evict":{"recently":1}
,"recently":{"loaded":1}
,"loaded":{"items":1}
,"items":{"deterministic":1}
,"deterministic":{"evictor":1}
,"avoid":{"problem":1}
,"problem":{"specify":1}
,"specify":{"-dnet.sf.ehcache.use.classic.lru=true":1}
,"-dnet.sf.ehcache.use.classic.lru=true":{"system":1}
,"system":{"property":1}
,"property":{"turn":1}
,"turn":{"classic":1}
,"classic":{"lru":1}
,"lru":{"contains":1}
,"contains":{"deterministic":1}
}
;Search.control.loadWordPairs(pairs);
