var pairs =
{
"terracotta":{"server":1,"xml":1,"clients":1,"configuration":1,"bigmemory":1,"servers":1,"kit":1}
,"server":{"configuration":1,"instances":1,"client":1,"development":1,"array":1}
,"configuration":{"terracotta":1,"files":1,"file":1}
,"xml":{"configuration":1}
,"files":{"characteristics":1,"available":1}
,"characteristics":{"behavior":1}
,"behavior":{"terracotta":1}
,"instances":{"terracotta":1}
,"clients":{"easiest":1}
,"easiest":{"create":1}
,"create":{"terracotta":1}
,"file":{"editing":1,"terracotta":1,"config-samples\u002Ftc-config-reference.xml":1}
,"editing":{"copy":1}
,"copy":{"sample":1}
,"sample":{"configuration":1}
,"available":{"terracotta":1}
,"bigmemory":{"max":1}
,"max":{"kit":1}
,"kit":{"locate":1}
,"locate":{"terracotta":1}
,"client":{"configurations":1}
,"configurations":{"loaded":1}
,"loaded":{"depends":1}
,"depends":{"stage":1}
,"stage":{"project":1,"terracotta":1,"document":1}
,"project":{"architecture":1}
,"architecture":{"document":1,"comprehensive":1}
,"document":{"covers":1,"discusses":1}
,"covers":{"following":1}
,"following":{"cases":1}
,"cases":{"development":1}
,"development":{"stage":1}
,"servers":{"deployment":1}
,"deployment":{"stage":1}
,"discusses":{"cluster":1}
,"cluster":{"configuration":1}
,"array":{"learn":1,"architecture":1}
,"learn":{"terracotta":1}
,"comprehensive":{"fully":1}
,"fully":{"annotated":1}
,"annotated":{"configuration":1}
,"config-samples\u002Ftc-config-reference.xml":{"terracotta":1}
}
;Search.control.loadWordPairs(pairs);
