var pairs =
{
"clear":{"data":1}
,"data":{"terracotta":1,"directory":1,"retained":1,"server":1,"deleted":1}
,"terracotta":{"server":1,"configuration":1}
,"server":{"terracotta":1,"restarted":1,"restart":1,"shutdown":1}
,"restarted":{"certain":1}
,"certain":{"circumstances":1}
,"circumstances":{"retain":1,"include":1}
,"retain":{"artifacts":1}
,"artifacts":{"previous":1}
,"previous":{"runs":1}
,"runs":{"data":1}
,"directory":{"manually":1,"\u002Fdirty-objectdb-backup\u002Fdirty-objectdb-<timestamp>":1}
,"manually":{"cleared":1,"delete":1}
,"cleared":{"circumstances":1}
,"include":{"running":1}
,"running":{"fast":1}
,"fast":{"restartability":1}
,"restartability":{"disabled":1}
,"disabled":{"bigmemory":1}
,"bigmemory":{"hybrid":1}
,"hybrid":{"enabled":1}
,"enabled":{"may":1,"automatically":1}
,"may":{"source":1,"consume":1}
,"source":{"errors":1}
,"errors":{"during":1}
,"during":{"split":1,"mirror":1}
,"split":{"brain":1}
,"brain":{"resolution":1}
,"resolution":{"during":1}
,"mirror":{"server":1}
,"restart":{"default":1}
,"default":{"number":1}
,"number":{"copies":1,"backups":1}
,"copies":{"server\u0027s":1,"may":1}
,"server\u0027s":{"objectdb":1,"data":1}
,"objectdb":{"data":1}
,"retained":{"unlimited":1}
,"unlimited":{"time":1}
,"time":{"frequent":1}
,"frequent":{"restarts":1}
,"restarts":{"copies":1}
,"consume":{"substantial":1,"available":1}
,"substantial":{"amount":1}
,"amount":{"disk":1}
,"disk":{"space":1}
,"space":{"manually":1,"want":1}
,"delete":{"files":1}
,"files":{"saved":1}
,"saved":{"server\u0027s":1}
,"\u002Fdirty-objectdb-backup\u002Fdirty-objectdb-<timestamp>":{"limit":1}
,"limit":{"number":1}
,"backups":{"adding":1,"altogether":1}
,"adding":{"following":1}
,"following":{"element":1}
,"element":{"terracotta":1}
,"configuration":{"file\u0027s":1}
,"file\u0027s":{"<tc-properties>":1}
,"<tc-properties>":{"block":1}
,"block":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"l2.nha.dirtydb.rolling":1}
,"l2.nha.dirtydb.rolling":{"value=\u0022":1}
,"value=\u0022":{"<myvalue>":1}
,"<myvalue>":{"<myvalue>":1,"integer":1}
,"integer":{"fast":1}
,"automatically":{"remove":1}
,"remove":{"older":1}
,"older":{"data":1}
,"shutdown":{"setting":1}
,"setting":{"property":1}
,"property":{"l2.nha.dirtydb.autodelete":1,"l2.nha.dirtydb.backup.enabled":1}
,"l2.nha.dirtydb.autodelete":{"true":1}
,"true":{"important":1}
,"important":{"note":1}
,"note":{"backup":1}
,"backup":{"copy":1}
,"copy":{"made":1}
,"made":{"configured":1}
,"configured":{"\u002Fdirty-objectdb-backup":1}
,"\u002Fdirty-objectdb-backup":{"folder":1}
,"folder":{"prior":1}
,"prior":{"recent":1}
,"recent":{"working":1}
,"working":{"data":1}
,"deleted":{"potentially":1}
,"potentially":{"consume":1}
,"available":{"disk":1}
,"want":{"disable":1}
,"disable":{"creation":1}
,"creation":{"backups":1}
,"altogether":{"property":1}
,"l2.nha.dirtydb.backup.enabled":{"false":1}
}
;Search.control.loadWordPairs(pairs);
