var pairs =
{
"charts":{"panel":1,"display":1,"displayed":1,"average":1,"total":1,"number":1,"size":1}
,"panel":{"master":1,"alternative":1,"view":1,"wan":1,"select":1}
,"master":{"caches":1,"cache":1,"orchestrator":1}
,"caches":{"charts":1}
,"alternative":{"view":1}
,"view":{"master":1,"click":1,"following":1}
,"cache":{"statistics":1,"information":1,"want":1,"field":1}
,"statistics":{"available":1}
,"available":{"overview":1}
,"overview":{"panel":1}
,"information":{"charts":1}
,"wan":{"tab":1,"number":1}
,"tab":{"click":1}
,"click":{"charts":1,"masters":1}
,"display":{"charts":1}
,"select":{"cachemanager":1,"cache":1}
,"cachemanager":{"master":1}
,"want":{"view":1}
,"masters":{"cache":1}
,"field":{"select":1}
,"following":{"charts":1}
,"displayed":{"processing":1}
,"processing":{"rate":1,"count":1}
,"rate":{"charts":1,"application\u0027s":1}
,"average":{"processed":1}
,"processed":{"transactions":1,"transaction":1}
,"transactions":{"per":1,"during":1}
,"per":{"second":1}
,"second":{"(tps)":1}
,"(tps)":{"during":1,"rate":1}
,"during":{"replication":1,"application\u0027s":1}
,"replication":{"chart":1,"rates":1,"conflict":1}
,"chart":{"plots":1}
,"plots":{"replication":1}
,"rates":{"one-minute":1}
,"one-minute":{"five-minute":1}
,"five-minute":{"fifteen-minute":1}
,"fifteen-minute":{"periods":1}
,"periods":{"processed":1}
,"transaction":{"recorded":1}
,"recorded":{"master":1}
,"orchestrator":{"immediate":1}
,"immediate":{"eventual":1}
,"eventual":{"transmission":1}
,"transmission":{"replica":1}
,"replica":{"orchestrators":1}
,"orchestrators":{"mean":1}
,"mean":{"processing":1}
,"application\u0027s":{"entire":1}
,"entire":{"lifetime":1}
,"lifetime":{"processing":1,"conflict":1}
,"count":{"charts":1,"inbound":1}
,"total":{"number":1}
,"number":{"processed":1,"conflicts":1,"element":1,"higher":1}
,"conflict":{"count":1,"table":1,"simply":1}
,"conflicts":{"resolved":1}
,"resolved":{"during":1}
,"table":{"size":1}
,"size":{"charts":1,"cluster":1}
,"element":{"modification":1}
,"modification":{"entries":1}
,"entries":{"(puts\u002Fupdates\u002Fdeletes)":1,"may":1}
,"(puts\u002Fupdates\u002Fdeletes)":{"currently":1}
,"currently":{"outstanding":1}
,"outstanding":{"entries":1}
,"may":{"may":1,"conflict":1}
,"simply":{"means":1}
,"means":{"replicated":1}
,"replicated":{"replicas":1}
,"replicas":{"wan":1}
,"higher":{"conflict":1}
,"inbound":{"buffer":1}
,"buffer":{"size":1}
,"cluster":{"listener":1}
,"listener":{"buffer":1}
}
;Search.control.loadWordPairs(pairs);
