var pairs =
{
"concepts":{"architecture":1}
,"architecture":{"bigmemory":1}
,"bigmemory":{"wan":1,"data":1}
,"wan":{"replication":1}
,"replication":{"uses":1,"topology":1,"designated":1,"updates":1}
,"uses":{"regional":1}
,"regional":{"orchestrators":1}
,"orchestrators":{"manage":1,"orchestrator":1,"regions":1}
,"manage":{"data":1,"multiple":1,"replication":1}
,"data":{"consistency":1,"center":1,"held":1,"consistent":1,"against":1}
,"consistency":{"region":1}
,"region":{"data":1,"holds":1,"orchestrators":1}
,"center":{"typically":1}
,"typically":{"geographically":1}
,"geographically":{"distinct":1}
,"distinct":{"connected":1}
,"connected":{"regions":1}
,"regions":{"high-speed":1,"replicates":1,"orchestrators":1,"order":1,"wan":1}
,"high-speed":{"link":1}
,"link":{"region":1}
,"holds":{"terracotta":1}
,"terracotta":{"server":1}
,"server":{"arrays":1}
,"arrays":{"(tsas)":1}
,"(tsas)":{"support":1}
,"support":{"multiple":1}
,"multiple":{"orchestrators":1,"caches":1}
,"orchestrator":{"-the":1,"communicates":1}
,"-the":{"process":1,"cache":1}
,"process":{"coordinates":1}
,"coordinates":{"communication":1}
,"communication":{"among":1}
,"among":{"regions":1}
,"replicates":{"cache":1}
,"cache":{"modifications":1,"master":1,"-the":1,"serves":1,"active":1,"cache":1,"mirror":1,"replica":1,"becomes":1}
,"modifications":{"regions":1}
,"caches":{"region-orchestrator":1,"orchestrators":1,"synchronized":1}
,"region-orchestrator":{"example":1}
,"example":{"figure":1}
,"figure":{"below":1}
,"below":{"application":1}
,"application":{"access":1}
,"access":{"bigmemory":1}
,"held":{"tsa":1}
,"tsa":{"orchestrator":1,"region":1}
,"communicates":{"tsa":1}
,"order":{"keep":1}
,"keep":{"data":1}
,"consistent":{"across":1}
,"across":{"regions":1}
,"topology":{"master":1}
,"master":{"replica":1,"cache":1,"time":1}
,"replica":{"caches":1,"instances":1,"cache":1}
,"designated":{"master":1}
,"instances":{"cache":1}
,"serves":{"authoritative":1}
,"authoritative":{"data":1}
,"against":{"replica":1}
,"synchronized":{"replicated":1}
,"replicated":{"cache":1}
,"active":{"master":1,"fully":1}
,"time":{"replica":1}
,"mirror":{"receives":1}
,"receives":{"replication":1}
,"updates":{"master":1}
,"becomes":{"active":1}
,"fully":{"synchronizes":1}
,"synchronizes":{"master":1}
}
;Search.control.loadWordPairs(pairs);
