var pairs =
{
"web":{"sessions":1,"architecture":1,"framework":1,"e-commerce":1,"frameworks":1}
,"sessions":{"terracotta":1,"fast":1,"works":1,"simple":1,"visibility":1,"easy":1,"makes":1,"watch":1,"in-memory":1,"scale":1,"full":1,"updated":1,"outperform":1}
,"terracotta":{"web":1,"dynamically":1,"session":1,"keeps":1}
,"fast":{"reliable":1,"restartable":1}
,"reliable":{"scalability":1,"access":1}
,"scalability":{"benefits":1}
,"benefits":{"stateless":1}
,"stateless":{"web":1}
,"architecture":{"without":1,"yields":1}
,"without":{"overloading":1,"downtime":1,"sacrificing":1}
,"overloading":{"database":1}
,"database":{"rewriting":1,"terracotta":1}
,"rewriting":{"application":1}
,"application":{"supporting":1,"container":1,"cluster":1,"throughput":1,"servers":1,"tier":1,"performance":1}
,"supporting":{"java":1}
,"java":{"servlet":1}
,"servlet":{"session":1}
,"session":{"standard":1,"objects":1,"data":1,"access":1,"consistency":1}
,"standard":{"terracotta":1}
,"works":{"favorite":1,"major":1}
,"favorite":{"web":1,"application":1}
,"framework":{"favorite":1}
,"container":{"custom":1,"support":1}
,"custom":{"session":1}
,"objects":{"easy":1}
,"easy":{"setup":1,"debugging":1,"configure":1,"add":1}
,"setup":{"terracotta":1}
,"simple":{"good":1}
,"good":{"fit":1}
,"fit":{"wide":1}
,"wide":{"range":1}
,"range":{"cases":1,"popular":1}
,"cases":{"departmental":1}
,"departmental":{"applications":1}
,"applications":{"large-scale":1}
,"large-scale":{"web":1}
,"e-commerce":{"sites":1}
,"sites":{"sessions":1}
,"visibility":{"performance":1}
,"performance":{"entire":1,"boost":1,"high":1,"punishing":1}
,"entire":{"application":1}
,"cluster":{"glance":1}
,"glance":{"browse":1}
,"browse":{"live":1}
,"live":{"contents":1}
,"contents":{"user":1}
,"user":{"sessions":1,"session":1}
,"debugging":{"problem":1}
,"problem":{"resolution":1}
,"resolution":{"terracotta":1}
,"makes":{"easy":1}
,"configure":{"optimize":1}
,"optimize":{"sessions":1}
,"watch":{"performance":1}
,"boost":{"you\u0027re":1}
,"you\u0027re":{"getting":1}
,"getting":{"real":1}
,"real":{"time":1}
,"time":{"in-memory":1}
,"in-memory":{"speed":1}
,"speed":{"terracotta":1,"architecture":1}
,"dynamically":{"partitions":1}
,"partitions":{"optimizes":1}
,"optimizes":{"locality":1}
,"locality":{"user":1}
,"data":{"provide":1,"without":1,"always":1,"memory":1,"network":1}
,"provide":{"coherent":1}
,"coherent":{"reliable":1,"consistent":1}
,"access":{"hot":1,"latency":1}
,"hot":{"sessions":1}
,"yields":{"high":1}
,"high":{"application":1,"availability":1,"performance":1}
,"throughput":{"low":1,"without":1}
,"low":{"session":1}
,"latency":{"matter":1}
,"matter":{"application":1}
,"servers":{"concurrent":1,"application":1,"event":1,"wide":1}
,"concurrent":{"users":1}
,"users":{"scale":1}
,"scale":{"terracotta":1,"critical":1}
,"add":{"additional":1}
,"additional":{"servers":1}
,"tier":{"high":1}
,"availability":{"sessions":1,"enjoy":1,"(99.999":1}
,"critical":{"increasing":1}
,"increasing":{"application":1}
,"downtime":{"disrupting":1}
,"disrupting":{"customer":1}
,"customer":{"experience":1}
,"experience":{"high":1,"unaffected":1}
,"enjoy":{"high":1}
,"(99.999":{"uptime)":1}
,"uptime)":{"session":1}
,"sacrificing":{"application":1}
,"punishing":{"database":1}
,"full":{"advantage":1}
,"advantage":{"bigmemory\u0027s":1}
,"bigmemory\u0027s":{"fault":1}
,"fault":{"tolerance":1}
,"tolerance":{"fast":1}
,"restartable":{"store":1}
,"store":{"ensure":1}
,"ensure":{"session":1}
,"always":{"available":1,"guaranteed":1}
,"available":{"even":1}
,"even":{"event":1}
,"event":{"server":1}
,"server":{"failure":1}
,"failure":{"restart":1,"restarts":1}
,"restart":{"session":1}
,"consistency":{"terracotta":1}
,"guaranteed":{"coherent":1}
,"consistent":{"up-to-date":1}
,"up-to-date":{"ensures":1}
,"ensures":{"customers":1}
,"customers":{"experience":1}
,"unaffected":{"routed":1}
,"routed":{"different":1}
,"different":{"application":1}
,"restarts":{"efficiency":1}
,"efficiency":{"terracotta":1}
,"keeps":{"locally":1}
,"locally":{"active":1}
,"active":{"session":1}
,"memory":{"sends":1,"network":1}
,"sends":{"changed":1}
,"changed":{"data":1}
,"network":{"sessions":1,"resources":1}
,"updated":{"efficient":1}
,"efficient":{"memory":1}
,"resources":{"enables":1}
,"enables":{"terracotta":1}
,"outperform":{"competitive":1}
,"competitive":{"solutions":1}
,"solutions":{"broad":1}
,"broad":{"container":1}
,"support":{"terracotta":1}
,"major":{"application":1}
,"popular":{"web":1}
}
;Search.control.loadWordPairs(pairs);
