var pairs =
{
"replication":{"modes":1,"service":1,"bidirectional":1,"active-passive":1}
,"modes":{"bigmemory":1,"unidirectional":1}
,"bigmemory":{"wan":1}
,"wan":{"replication":1}
,"service":{"offers":1}
,"offers":{"two":1}
,"two":{"replication":1,"directions":1,"modes":1}
,"unidirectional":{"mode":1,"replication":1,"switch":1}
,"mode":{"replicates":1,"unidirectional":1,"orchestrator":1,"conflict":1}
,"replicates":{"data":1,"cache":1}
,"data":{"direction":1,"two":1,"table":1,"element":1,"conflict":1}
,"direction":{"master":1}
,"master":{"replica":1,"used":1,"cache\u0027s":1,"cache":1}
,"replica":{"used":1,"replica":1,"master":1,"caches":1}
,"used":{"active-passive":1,"active-active":1}
,"active-passive":{"deployments":1,"deployment":1}
,"deployments":{"disaster":1,"updates":1}
,"disaster":{"recovery":1}
,"recovery":{"bidirectional":1,"example":1}
,"bidirectional":{"mode":1,"replication":1,"wan":1}
,"directions":{"master":1}
,"active-active":{"deployments":1,"deployment":1}
,"updates":{"region":1}
,"region":{"incorporated":1}
,"incorporated":{"master":1}
,"cache\u0027s":{"authoritative":1}
,"authoritative":{"data":1}
,"table":{"below":1}
,"below":{"summarizes":1}
,"summarizes":{"two":1}
,"deployment":{"active-active":1,"master":1}
,"cache":{"replicates":1,"element":1,"receives":1,"maintains":1,"tracks":1}
,"element":{"modifications":1,"tracking":1,"maintains":1}
,"modifications":{"replica":1,"master":1}
,"caches":{"master":1,"replicate":1,"operate":1}
,"replicate":{"cache":1}
,"operate":{"locally":1}
,"locally":{"replicate":1}
,"receives":{"replications":1}
,"replications":{"replica":1}
,"maintains":{"authoritative":1}
,"tracking":{"necessary":1}
,"necessary":{"master":1,"automatic":1}
,"tracks":{"cache":1}
,"conflict":{"resolution":1}
,"resolution":{"necessary":1,"example":1,"bidirectional":1}
,"automatic":{"conflict":1}
,"example":{"case":1}
,"case":{"disaster":1,"regional":1}
,"regional":{"operations":1}
,"operations":{"default":1}
,"default":{"mode":1}
,"switch":{"bidirectional":1}
,"orchestrator":{"configuration":1}
,"configuration":{"parameters":1}
,"parameters":{"information":1}
,"information":{"bidirectional":1}
}
;Search.control.loadWordPairs(pairs);
