var pairs =
{
"terracotta":{"server":1,"products":1,"clusters":1}
,"server":{"array":1,"instances":1}
,"array":{"terracotta":1,"(tsa)":1,"vary":1,"providing":1,"include":1}
,"(tsa)":{"provides":1}
,"provides":{"platform":1}
,"platform":{"terracotta":1}
,"products":{"backbone":1}
,"backbone":{"terracotta":1}
,"clusters":{"terracotta":1}
,"vary":{"basic":1}
,"basic":{"two-node":1}
,"two-node":{"tandem":1}
,"tandem":{"multi-node":1}
,"multi-node":{"array":1}
,"providing":{"configurable":1}
,"configurable":{"scale":1,"health":1}
,"scale":{"high":1}
,"high":{"performance":1,"availability":1}
,"performance":{"deep":1}
,"deep":{"failover":1}
,"failover":{"coverage":1,"continuous":1}
,"coverage":{"main":1}
,"main":{"features":1}
,"features":{"terracotta":1}
,"include":{"distributed":1}
,"distributed":{"in-memory":1}
,"in-memory":{"data":1}
,"data":{"management":1,"memory":1,"grids":1,"automatic":1}
,"management":{"-manages":1}
,"-manages":{"10-100x":1}
,"10-100x":{"data":1}
,"memory":{"data":1}
,"grids":{"scalability":1}
,"scalability":{"without":1}
,"without":{"complexity":1,"operator":1}
,"complexity":{"-simple":1}
,"-simple":{"configuration":1}
,"configuration":{"add":1}
,"add":{"server":1}
,"instances":{"meet":1,"clients":1}
,"meet":{"growing":1}
,"growing":{"demand":1}
,"demand":{"facilitate":1}
,"facilitate":{"capacity":1}
,"capacity":{"planning":1}
,"planning":{"high":1}
,"availability":{"-instant":1}
,"-instant":{"failover":1}
,"continuous":{"uptime":1}
,"uptime":{"services":1}
,"services":{"configurable":1}
,"health":{"monitoring":1}
,"monitoring":{"-terracotta":1,"information":1}
,"-terracotta":{"healthchecker":1}
,"healthchecker":{"inter-node":1,"properties":1}
,"inter-node":{"monitoring":1}
,"information":{"configuring":1}
,"configuring":{"healthchecker":1}
,"properties":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"high-availability":1}
,"high-availability":{"guide":1}
,"guide":{"persistent":1}
,"persistent":{"application":1}
,"application":{"state":1}
,"state":{"-automatic":1}
,"-automatic":{"permanent":1}
,"permanent":{"storage":1}
,"storage":{"current":1}
,"current":{"shared":1}
,"shared":{"in-memory":1}
,"automatic":{"node":1}
,"node":{"reconnection":1}
,"reconnection":{"-temporarily":1}
,"-temporarily":{"disconnected":1}
,"disconnected":{"server":1}
,"clients":{"rejoin":1}
,"rejoin":{"cluster":1}
,"cluster":{"without":1}
,"operator":{"intervention":1}
}
;Search.control.loadWordPairs(pairs);
