var pairs =
{
"fast":{"restart":1,"restartability":1,"disk":1}
,"restart":{"performance":1,"in-memory":1}
,"performance":{"<<this":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"configured":1}
,"configured":{"fast":1}
,"restartability":{"localrestartable":1}
,"localrestartable":{"persistence":1}
,"persistence":{"strategy)":1}
,"strategy)":{"bigmemory":1}
,"bigmemory":{"becomes":1,"restarted":1}
,"becomes":{"active":1}
,"active":{"restart":1}
,"in-memory":{"data":1}
,"data":{"loaded":1,"speed":1}
,"loaded":{"amount":1}
,"amount":{"time":1,"in-memory":1}
,"time":{"until":1}
,"until":{"bigmemory":1}
,"restarted":{"proportionate":1}
,"proportionate":{"amount":1}
,"speed":{"underlying":1,"ssd":1,"during":1}
,"underlying":{"infrastructure":1}
,"infrastructure":{"generally":1}
,"generally":{"recovery":1}
,"recovery":{"occur":1}
,"occur":{"fast":1}
,"disk":{"speed":1}
,"ssd":{"example":1}
,"example":{"read":1}
,"read":{"throughput":1}
,"throughput":{"per":1}
,"per":{"second":1}
,"second":{"similar":1}
,"similar":{"loading":1}
,"loading":{"speed":1}
,"during":{"recovery":1}
}
;Search.control.loadWordPairs(pairs);
