var pairs =
{
"special":{"client":1,"cases":1}
,"client":{"connection":1,"connections":1,"failover":1,"first":1,"server":1,"-dcom.tc.tc.config.total.timeout=5000":1,"spends":1}
,"connection":{"properties":1,"connection":1,"terracotta":1,"attempt":1,"attempts":1}
,"properties":{"client":1,"associated":1,"sure":1,"==retry":1}
,"connections":{"tuned":1}
,"tuned":{"following":1}
,"following":{"special":1,"properties":1,"property":1}
,"cases":{"client":1,"already":1}
,"failover":{"server":1,"clusters":1}
,"server":{"failure":1,"instance":1,"available":1,"becomes":1,"automatically":1,"however":1,"-this":1,"restarted":1,"running":1,"l1.socket.reconnect.waitinterval=1000":1}
,"failure":{"first-time":1,"active":1}
,"first-time":{"client":1}
,"associated":{"cases":1}
,"already":{"optimized":1}
,"optimized":{"typical":1}
,"typical":{"environments":1}
,"environments":{"attempt":1}
,"attempt":{"tune":1,"timed":1}
,"tune":{"properties":1}
,"sure":{"thoroughly":1}
,"thoroughly":{"test":1}
,"test":{"new":1}
,"new":{"settings":1,"active":1}
,"settings":{"client":1}
,"active":{"terracotta":1,"server":1}
,"terracotta":{"server":1,"clients":1,"configuration":1,"client":1,"l1.connect.versionmatchcheck.enabled":1}
,"instance":{"fails":1,"based":1}
,"fails":{"mirror":1}
,"mirror":{"terracotta":1,"server":1}
,"available":{"mirror":1}
,"becomes":{"active":1}
,"clients":{"connected":1,"limited":1,"fail":1}
,"connected":{"previous":1}
,"previous":{"active":1}
,"automatically":{"switch":1}
,"switch":{"new":1}
,"however":{"clients":1,"single-server":1}
,"limited":{"window":1}
,"window":{"time":1,"applies":1,"effect":1,"configured":1}
,"time":{"complete":1,"(in":1}
,"complete":{"failover":1}
,"clusters":{"single":1}
,"single":{"server":1,"terracotta":1}
,"-this":{"reconnection":1}
,"reconnection":{"window":1}
,"applies":{"cluster":1}
,"cluster":{"single":1,"<restartable>":1,"first-time":1}
,"restarted":{"however":1,"successfully":1}
,"single-server":{"cluster":1}
,"<restartable>":{"enabled":1}
,"enabled":{"reconnection":1}
,"effect":{"window":1}
,"configured":{"terracotta":1,"seconds":1,"servers":1}
,"configuration":{"file":1,"resolved":1}
,"file":{"using":1}
,"using":{"<client-reconnect-window>":1}
,"<client-reconnect-window>":{"element":1,"120":1}
,"element":{"<servers>":1,"explicitly":1}
,"<servers>":{"<client-reconnect-window>":1}
,"120":{"<\u002Fclient-reconnect-window>":1,"default":1}
,"<\u002Fclient-reconnect-window>":{"<!--the":1}
,"<!--the":{"reconnect":1}
,"reconnect":{"window":1,"cluster":1}
,"seconds":{"default":1}
,"default":{"value":1}
,"value":{"120":1,"built":1,"required":1}
,"built":{"element":1}
,"explicitly":{"added":1}
,"added":{"unless":1}
,"unless":{"different":1}
,"different":{"value":1}
,"required":{"-->":1}
,"-->":{"<\u002Fservers>":1}
,"<\u002Fservers>":{"clients":1}
,"fail":{"connect":1}
,"connect":{"new":1,"terracotta":1,"server":1}
,"successfully":{"reconnect":1}
,"first":{"started":1}
,"started":{"(or":1}
,"(or":{"restarted)":1}
,"restarted)":{"attempts":1}
,"attempts":{"connect":1,"configuration":1}
,"based":{"following":1}
,"==retry":{"configured":1}
,"servers":{"eternally":1}
,"eternally":{"client":1}
,"running":{"version":1}
,"version":{"terracotta":1}
,"l1.connect.versionmatchcheck.enabled":{"=true":1}
,"=true":{"time":1}
,"(in":{"milliseconds)":1,"milliseconds":1}
,"milliseconds)":{"socket":1,"client":1}
,"socket":{"connection":1}
,"timed":{"l1.socket.connect.timeout=10000":1}
,"l1.socket.connect.timeout=10000":{"time":1}
,"milliseconds":{"minimum":1}
,"minimum":{"10)":1}
,"10)":{"attempts":1}
,"l1.socket.reconnect.waitinterval=1000":{"control":1}
,"control":{"connection":1}
,"resolved":{"following":1}
,"property":{"client":1,"limits":1}
,"-dcom.tc.tc.config.total.timeout=5000":{"property":1}
,"limits":{"time":1}
,"spends":{"attempting":1}
,"attempting":{"initial":1}
,"initial":{"connection":1}
}
;Search.control.loadWordPairs(pairs);
