var pairs =
{
"distributed":{"configurations":1}
,"configurations":{"bigmemory":1,"terracotta":1}
,"bigmemory":{"max":1}
,"max":{"configuration":1}
,"configuration":{"file":1,"instance":1,"persisted":1,"edited":1,"removed":1,"survives":1,"following":1,"terracottaconfig":1}
,"file":{"(ehcache.xml":1,"application\u0027s":1,"ehcache.xml":1,"effect":1}
,"(ehcache.xml":{"default)":1}
,"default)":{"contains":1,"wiping":1}
,"contains":{"configuration":1}
,"instance":{"cachemanager":1}
,"cachemanager":{"(the":1,"configuring":1,"clustering":1}
,"(the":{"ehcache":1}
,"ehcache":{"class":1}
,"class":{"managing":1}
,"managing":{"defined":1}
,"defined":{"caches)":1}
,"caches)":{"configuration":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"found":1}
,"found":{"using":1}
,"using":{"war":1,"terracotta":1}
,"war":{"file":1}
,"ehcache.xml":{"copied":1,"terracotta":1,"in-memory":1,"loaded":1,"servers":1}
,"copied":{"web-inf\u002Fclasses":1}
,"web-inf\u002Fclasses":{"note":1}
,"note":{"following":1}
,"following":{"ehcache.xml":1,"configured":1}
,"terracotta":{"cluster":1,"client":1,"servers":1,"management":1,"configuration":1,"source":1}
,"cluster":{"copy":1,"once":1,"survives":1,"load":1}
,"copy":{"disk":1,"ehcache.xml":1}
,"disk":{"loaded":1}
,"loaded":{"memory":1,"configuration":1,"in-memory":1}
,"memory":{"first":1,"terracotta":1}
,"first":{"terracotta":1}
,"client":{"(also":1,"restarts":1,"configuration":1}
,"(also":{"called":1}
,"called":{"application":1}
,"application":{"server":1}
,"server":{"node)":1,"restarts":1}
,"node)":{"join":1}
,"join":{"cluster":1}
,"once":{"loaded":1}
,"persisted":{"memory":1,"shared":1}
,"servers":{"cluster":1,"persistent":1,"persistence":1,"database":1,"server-data":1}
,"survives":{"client":1,"server":1}
,"restarts":{"in-memory":1,"servers":1}
,"in-memory":{"configuration":1,"cache":1}
,"edited":{"terracotta":1}
,"management":{"console":1}
,"console":{"(tmc)":1}
,"(tmc)":{"changes":1}
,"changes":{"effect":1}
,"effect":{"immediately":1,"(tc-config.xml":1}
,"immediately":{"written":1}
,"written":{"original":1}
,"original":{"on-disk":1,"(on-disk)":1}
,"on-disk":{"copy":1}
,"cache":{"configuration":1,"configurations":1}
,"removed":{"server":1}
,"persistent":{"mode":1}
,"mode":{"(<restartable":1}
,"(<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"false":1,"true":1}
,"false":{"\u0022>)":1}
,"\u0022>)":{"default":1,"using":1}
,"default":{"original":1}
,"(on-disk)":{"ehcache.xml":1}
,"true":{"\u0022>)":1}
,"persistence":{"shared":1}
,"shared":{"data":1}
,"data":{"want":1,"files":1,"lost":1}
,"want":{"cluster":1}
,"load":{"original":1}
,"database":{"wiped":1,"causes":1}
,"wiped":{"removing":1}
,"removing":{"data":1}
,"files":{"servers":1}
,"server-data":{"directory":1}
,"directory":{"directory":1,"specified":1}
,"specified":{"terracotta":1}
,"(tc-config.xml":{"default)":1}
,"wiping":{"database":1}
,"causes":{"persisted":1}
,"lost":{"minimal":1}
,"minimal":{"distributed-cache":1}
,"distributed-cache":{"configuration":1}
,"configured":{"cachemanager":1}
,"configuring":{"cachemanager":1}
,"clustering":{"element":1}
,"element":{"individual":1}
,"individual":{"cache":1}
,"source":{"terracotta":1}
}
;Search.control.loadWordPairs(pairs);
