var pairs =
{
"authentication":{"mechanisms":1,"-uses":1,"database":1,"-provides":1,"scheme":1}
,"mechanisms":{"enterprise":1,"control":1,"causes":1}
,"enterprise":{"edition":1}
,"edition":{"terracotta":1}
,"terracotta":{"kit":1,"servers":1,"server":1,"scripts":1}
,"kit":{"provides":1}
,"provides":{"standard":1}
,"standard":{"authentication":1}
,"control":{"access":1}
,"access":{"terracotta":1}
,"servers":{"enabling":1,"ssl-based":1,"jmx-based":1,"note":1,"without":1}
,"enabling":{"mechanisms":1}
,"causes":{"terracotta":1}
,"server":{"require":1}
,"require":{"credentials":1}
,"credentials":{"allowing":1,"script":1}
,"allowing":{"jmx":1}
,"jmx":{"connection":1}
,"connection":{"choose":1}
,"choose":{"following":1}
,"following":{"secure":1}
,"secure":{"servers":1,"access":1}
,"ssl-based":{"security":1}
,"security":{"-authenticates":1}
,"-authenticates":{"nodes":1}
,"nodes":{"(including":1}
,"(including":{"clients)":1}
,"clients)":{"secures":1}
,"secures":{"entire":1}
,"entire":{"cluster":1}
,"cluster":{"encrypted":1}
,"encrypted":{"connections":1}
,"connections":{"includes":1}
,"includes":{"role-based":1}
,"role-based":{"authorization":1}
,"authorization":{"ldap-based":1}
,"ldap-based":{"authentication":1}
,"-uses":{"organization\u0027s":1}
,"organization\u0027s":{"authentication":1}
,"database":{"secure":1}
,"jmx-based":{"authentication":1}
,"-provides":{"simple":1}
,"simple":{"authentication":1}
,"scheme":{"protect":1}
,"protect":{"access":1}
,"note":{"terracotta":1}
,"scripts":{"cannot":1}
,"cannot":{"used":1}
,"used":{"secured":1}
,"secured":{"servers":1}
,"without":{"passing":1}
,"passing":{"credentials":1}
}
;Search.control.loadWordPairs(pairs);
