var pairs =
{
"exporting":{"configuration":1,"customized":1}
,"configuration":{"terracotta":1,"live":1,"exist":1,"values":1,"file":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"create":1,"user":1}
,"create":{"edit":1,"cache":1,"file":1}
,"edit":{"cache":1}
,"cache":{"configuration":1,"config":1}
,"live":{"cluster":1}
,"cluster":{"terracotta":1,"last":1}
,"user":{"guide":1}
,"guide":{"<<ffc-we":1}
,"<<ffc-we":{"need":1}
,"need":{"point":1}
,"point":{"readers":1}
,"readers":{"section":1}
,"section":{"describes":1}
,"describes":{"edit":1}
,"config":{"topic":1}
,"topic":{"editing":1}
,"editing":{"cache":1}
,"exist":{"anymore":1}
,"anymore":{"persist":1}
,"persist":{"custom":1}
,"custom":{"cache":1}
,"values":{"create":1}
,"file":{"exporting":1,"conforms":1,"place":1,"used":1}
,"customized":{"configuration":1}
,"conforms":{"required":1}
,"required":{"format":1}
,"format":{"file":1}
,"place":{"configuration":1}
,"used":{"cluster":1}
,"last":{"started":1}
}
;Search.control.loadWordPairs(pairs);
