var pairs =
{
"forcing":{"ssl":1}
,"ssl":{"connections":1,"disable":1,"browser":1}
,"connections":{"tmc":1,"recognize":1,"usually":1}
,"tmc":{"clients":1,"deployed":1,"unsecured":1,"war":1}
,"clients":{"tmc":1}
,"deployed":{"provided":1,"different":1}
,"provided":{"jetty":1}
,"jetty":{"web":1,"container\u0027s":1}
,"web":{"server":1,"browsers":1}
,"server":{"web":1}
,"browsers":{"connecting":1,"connect":1}
,"connecting":{"tmc":1}
,"unsecured":{"connection":1}
,"connection":{"(via":1,"available":1}
,"(via":{"http":1}
,"http":{"port":1}
,"port":{"9889)":1,"9443":1,"<property":1}
,"9889)":{"secure":1}
,"secure":{"ssl-based":1}
,"ssl-based":{"connection":1}
,"available":{"using":1}
,"using":{"https":1,"ssl":1}
,"https":{"port":1}
,"9443":{"force":1}
,"force":{"web":1}
,"connect":{"using":1}
,"disable":{"non-secure":1}
,"non-secure":{"connector":1}
,"connector":{"commenting":1,"<call":1}
,"commenting":{"\u002Fmanagement-console\u002Fetc\u002Fjetty.xml":1}
,"\u002Fmanagement-console\u002Fetc\u002Fjetty.xml":{"(located":1}
,"(located":{"bigmemory":1}
,"bigmemory":{"kit)":1}
,"kit)":{"<!--disabled":1}
,"<!--disabled":{"non-secure":1}
,"<call":{"name=\u0022":1}
,"name=\u0022":{"addconnector":1,"host":1,"jetty.host":1,"port":1,"jetty.port":1,"forwarded":1,"maxidletime":1,"acceptors":1,"statson":1,"confidentialport":1,"lowresourcesconnections":1,"lowresourcesmaxidletime":1}
,"addconnector":{"<arg>":1}
,"<arg>":{"<new":1}
,"<new":{"class=\u0022":1}
,"class=\u0022":{"org.eclipse.jetty.server.nio.selectchannelconnector":1}
,"org.eclipse.jetty.server.nio.selectchannelconnector":{"<set":1}
,"<set":{"name=\u0022":1}
,"host":{"<property":1}
,"<property":{"name=\u0022":1}
,"jetty.host":{"<\u002Fset>":1}
,"<\u002Fset>":{"<set":1,"<\u002Fnew>":1}
,"jetty.port":{"default=\u0022":1}
,"default=\u0022":{"9889":1}
,"9889":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<\u002Fset>":1}
,"forwarded":{"true":1}
,"true":{"<\u002Fset>":1}
,"maxidletime":{"300000":1}
,"300000":{"<\u002Fset>":1}
,"acceptors":{"<\u002Fset>":1}
,"statson":{"false":1}
,"false":{"<\u002Fset>":1}
,"confidentialport":{"8443":1}
,"8443":{"<\u002Fset>":1}
,"lowresourcesconnections":{"20000":1}
,"20000":{"<\u002Fset>":1}
,"lowresourcesmaxidletime":{"5000":1}
,"5000":{"<\u002Fset>":1}
,"<\u002Fnew>":{"<\u002Farg>":1}
,"<\u002Farg>":{"<\u002Fcall>":1}
,"<\u002Fcall>":{"-->":1}
,"-->":{"tmc":1}
,"war":{"deployed":1}
,"different":{"container":1}
,"container":{"equivalent":1,"default":1}
,"equivalent":{"changes":1}
,"changes":{"appropriate":1}
,"appropriate":{"container":1}
,"default":{"keystore":1,"built-in":1}
,"keystore":{"default":1,"contains":1}
,"built-in":{"jetty":1}
,"container\u0027s":{"configuration":1}
,"configuration":{"file":1}
,"file":{"(management-console\u002Fetc\u002Fjetty.xml)":1}
,"(management-console\u002Fetc\u002Fjetty.xml)":{"uses":1}
,"uses":{"jks":1}
,"jks":{"identity":1}
,"identity":{"store":1}
,"store":{"located":1}
,"located":{"directory":1}
,"directory":{"keystore":1}
,"contains":{"self-signed":1}
,"self-signed":{"certificate":1}
,"certificate":{"(not":1,"authority)":1,"ssl":1,"register":1}
,"(not":{"signed":1}
,"signed":{"certificate":1}
,"authority)":{"intend":1}
,"intend":{"untrusted":1}
,"untrusted":{"certificate":1}
,"browser":{"connections":1,"first":1}
,"recognize":{"certificate":1}
,"register":{"exception":1}
,"exception":{"future":1}
,"future":{"connections":1}
,"usually":{"done":1}
,"done":{"time":1}
,"time":{"browser":1}
,"first":{"connects":1}
,"connects":{"tms":1}
}
;Search.control.loadWordPairs(pairs);
