var pairs =
{
"changing":{"topology":1}
,"topology":{"using":1,"live":1,"conflicts":1}
,"using":{"tmc":1}
,"tmc":{"change":1}
,"change":{"topology":1}
,"live":{"cluster":1}
,"cluster":{"reloading":1,"affect":1,"data":1}
,"reloading":{"edited":1}
,"edited":{"terracotta":1,"configuration":1,"reloaded":1,"exactly":1}
,"terracotta":{"configuration":1}
,"configuration":{"file":1,"servers":1,"files":1}
,"file":{"note":1,"allowed":1,"avoid":1,"configuration":1,"edited":1}
,"note":{"following":1}
,"following":{"restrictions":1}
,"restrictions":{"removal":1}
,"removal":{"addition":1}
,"addition":{"<server>":1}
,"<server>":{"blocks":1}
,"blocks":{"<servers>":1}
,"<servers>":{"<mirror-group>":1}
,"<mirror-group>":{"section":1}
,"section":{"terracotta":1}
,"allowed":{"servers":1}
,"servers":{"clients":1,"part":1,"configuration":1,"changing":1,"continue":1}
,"clients":{"load":1}
,"load":{"configuration":1}
,"avoid":{"topology":1}
,"conflicts":{"servers":1}
,"part":{"server":1}
,"server":{"array":1}
,"array":{"share":1,"redistributed":1}
,"share":{"edited":1}
,"reloaded":{"shown":1}
,"shown":{"below":1}
,"below":{"clients":1}
,"files":{"edited":1}
,"exactly":{"match":1}
,"match":{"servers":1}
,"affect":{"distribution":1}
,"distribution":{"data":1}
,"data":{"already":1,"server":1}
,"already":{"loaded":1}
,"loaded":{"tsa":1}
,"tsa":{"example":1}
,"example":{"added":1}
,"added":{"stripe":1}
,"stripe":{"live":1,"used":1}
,"redistributed":{"utilize":1}
,"utilize":{"instead":1}
,"instead":{"new":1}
,"new":{"stripe":1,"caches":1}
,"used":{"adding":1}
,"adding":{"new":1}
,"caches":{"original":1}
,"original":{"servers":1,"data":1}
,"continue":{"manage":1}
,"manage":{"original":1}
}
;Search.control.loadWordPairs(pairs);
