var pairs =
{
"configuring":{"security":1}
,"security":{"using":1,"mechanisms":1}
,"using":{"jmx":1}
,"jmx":{"authentication":1,"password":1,"access":1}
,"authentication":{"terracotta":1,"relies":1,"follow":1}
,"terracotta":{"standard":1,"configuration":1}
,"standard":{"java":1}
,"java":{"security":1}
,"mechanisms":{"jmx":1}
,"relies":{"creation":1}
,"creation":{".access":1}
,".access":{".password":1}
,".password":{"files":1}
,"files":{"correct":1,"jdk":1}
,"correct":{"permissions":1}
,"permissions":{"default":1}
,"default":{"location":1}
,"location":{"files":1,"($java_home\u002Fjre\u002Flib\u002Fmanagement)":1,"add":1}
,"jdk":{"1.5":1}
,"1.5":{"higher":1}
,"higher":{"$java_home\u002Fjre\u002Flib\u002Fmanagement":1}
,"$java_home\u002Fjre\u002Flib\u002Fmanagement":{"configure":1}
,"configure":{"security":1}
,"follow":{"steps":1}
,"steps":{"ensure":1}
,"ensure":{"desired":1}
,"desired":{"usernames":1,"roles":1}
,"usernames":{"passwords":1}
,"passwords":{"securing":1}
,"securing":{"target":1}
,"target":{"servers":1}
,"servers":{"jmx":1}
,"password":{"file":1}
,"file":{"jmxremote.password":1,"jmxremote.access":1,"<server":1,"found":1,"exist":1}
,"jmxremote.password":{"desired":1,"default":1}
,"roles":{"jmx":1}
,"access":{"file":1}
,"jmxremote.access":{"jmxremote.access":1,"jmxremote.password":1,"default":1}
,"($java_home\u002Fjre\u002Flib\u002Fmanagement)":{"add":1}
,"add":{"following":1}
,"following":{"configuration":1}
,"configuration":{"<server>":1,"file":1}
,"<server>":{"block":1}
,"block":{"terracotta":1}
,"<server":{"host=\u0022":1}
,"host=\u0022":{"myhost":1}
,"myhost":{"name=\u0022":1}
,"name=\u0022":{"myserver":1}
,"myserver":{"jmx-enabled=\u0022":1}
,"jmx-enabled=\u0022":{"true":1}
,"true":{"<authentication":1,"<authentication>":1}
,"<authentication":{"<\u002Fserver>":1}
,"<\u002Fserver>":{"jmxremote.password":1,"jmxremote.access":1,"jmx":1}
,"<authentication>":{"<mode>":1}
,"<mode>":{"<password-file>\u002Fpath\u002Fto\u002Fjmx.password":1,"<password-file>\u002Fpath\u002Fto\u002Fjmxremote.password":1}
,"<password-file>\u002Fpath\u002Fto\u002Fjmx.password":{"<\u002Fpassword-file>":1}
,"<\u002Fpassword-file>":{"<\u002Fmode>":1}
,"<\u002Fmode>":{"<\u002Fauthentication>":1,"<access-file>\u002Fpath\u002Fto\u002Fjmxremote.access":1}
,"<\u002Fauthentication>":{"<\u002Fserver>":1}
,"<password-file>\u002Fpath\u002Fto\u002Fjmxremote.password":{"<\u002Fpassword-file>":1}
,"<access-file>\u002Fpath\u002Fto\u002Fjmxremote.access":{"<\u002Faccess-file>":1}
,"<\u002Faccess-file>":{"<\u002Fauthentication>":1}
,"found":{"server":1}
,"server":{"starts":1}
,"starts":{"error":1}
,"error":{"logged":1}
,"logged":{"stating":1}
,"stating":{"password":1}
}
;Search.control.loadWordPairs(pairs);
