var pairs =
{
"listening":{"cluster":1}
,"cluster":{"events":1,"**@param":1,"execute":1,"*cannot":1,"again":1,"nodes":1,"=mgr.getcluster":1,"newnode)":1}
,"events":{"interface":1,"public":1,"happen":1}
,"interface":{"net.sf.ehcache.cluster.clustertopologylistener":1,"clustertopologylistener":1}
,"net.sf.ehcache.cluster.clustertopologylistener":{"provides":1}
,"provides":{"methods":1}
,"methods":{"detecting":1}
,"detecting":{"following":1}
,"following":{"cluster":1}
,"public":{"interface":1,"void":1}
,"clustertopologylistener":{"{\u002F***a":1,"prints":1,"{public":1}
,"{\u002F***a":{"node":1}
,"node":{"joined":1,"joining":1,"*\u002Fvoid":1,"left":1,"departing":1,"established":1,"current":1,"lost":1,"rejoined":1,"disconnected":1,"rejoin":1,"nodes)":1,"clusternode":1}
,"joined":{"cluster":1,"public":1}
,"**@param":{"node":1}
,"joining":{"node":1}
,"*\u002Fvoid":{"nodejoined":1,"nodeleft":1,"clusteronline":1,"clusteroffline":1,"clusterrejoined":1}
,"nodejoined":{"(clusternode":1}
,"(clusternode":{"node)":1,"oldnode":1,"node":1}
,"node)":{"\u002F***a":1,"\u002F***this":1,"{system.out.println":1}
,"\u002F***a":{"node":1}
,"left":{"cluster":1,"public":1}
,"departing":{"node":1}
,"nodeleft":{"(clusternode":1}
,"\u002F***this":{"node":1}
,"established":{"contact":1}
,"contact":{"cluster":1,"(possibly":1,"rejoined":1}
,"execute":{"clustered":1}
,"clustered":{"*operations":1,"operations":1}
,"*operations":{"**@param":1}
,"current":{"node":1,"nodes":1}
,"clusteronline":{"(clusternode":1}
,"lost":{"contact":1}
,"(possibly":{"temporarily)":1}
,"temporarily)":{"cluster":1}
,"*cannot":{"execute":1}
,"operations":{"**@param":1}
,"clusteroffline":{"(clusternode":1}
,"rejoined":{"cluster":1,"*connected":1}
,"again":{"**this":1}
,"**this":{"event":1}
,"event":{"fired":1}
,"fired":{"node":1}
,"*connected":{"nodes":1}
,"nodes":{"*@param":1,"registers":1,"collection":1,"=cluster.getnodes":1}
,"*@param":{"oldnode":1,"newnode":1}
,"oldnode":{"old":1,"clusternode":1}
,"old":{"node":1}
,"disconnected":{"*@param":1}
,"newnode":{"new":1}
,"new":{"node":1}
,"rejoin":{"*\u002Fvoid":1}
,"clusterrejoined":{"(clusternode":1}
,"clusternode":{"newnode)":1}
,"newnode)":{"example":1,"{system.out.println":1}
,"example":{"code":1,"prints":1}
,"code":{"example":1}
,"prints":{"cluster":1,"events":1}
,"registers":{"clustertopologylistener":1}
,"happen":{"cachemanager":1}
,"cachemanager":{"mgr":1}
,"mgr":{"cachecluster":1}
,"cachecluster":{"cluster":1}
,"=mgr.getcluster":{"terracotta":1}
,"terracotta":{"\u002F\u002Fget":1}
,"\u002F\u002Fget":{"current":1}
,"collection":{"<clusternode>":1}
,"<clusternode>":{"nodes":1}
,"=cluster.getnodes":{"(clusternode":1}
,"nodes)":{"{system.out.println":1}
,"{system.out.println":{"(node.getid":1,"(node":1}
,"(node.getid":{"node.gethostname":1}
,"node.gethostname":{"node.getip":1}
,"node.getip":{"())":1}
,"())":{"\u002F\u002Fregister":1}
,"\u002F\u002Fregister":{"listener":1}
,"listener":{"cluster.addtopologylistener":1}
,"cluster.addtopologylistener":{"(new":1}
,"(new":{"clustertopologylistener":1}
,"{public":{"void":1}
,"void":{"nodejoined":1,"nodeleft":1,"clusteronline":1,"clusteroffline":1,"clusterrejoined":1}
,"(node":{"joined":1,"left":1,"enabled":1,"disabled":1,"rejoined":1}
,"enabled":{"public":1}
,"disabled":{"public":1}
}
;Search.control.loadWordPairs(pairs);
