var pairs =
{
"setting":{"authorization":1}
,"authorization":{"tmc":1,"setup":1}
,"tmc":{"queries":1,"query":1,"specify":1,"currently":1,"roles":1,"role":1}
,"queries":{"terracotta":1,"query":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"allows":1}
,"allows":{"execute":1}
,"execute":{"sql-like":1}
,"sql-like":{"queries":1}
,"query":{"field":1,"feature":1,"panel":1,"ability":1}
,"field":{"application":1,"longer":1}
,"application":{"data":1}
,"data":{"contents":1}
,"contents":{"panel":1}
,"panel":{"initially":1,"user":1,"example":1,"administrator":1}
,"initially":{"users":1}
,"users":{"access":1,"configuration":1}
,"access":{"tmc":1}
,"feature":{"may":1,"disabling":1,"defined":1,"open":1,"particular":1}
,"may":{"want":1}
,"want":{"restrict":1,"ini-file":1,"modify":1,"hide":1,"disable":1}
,"restrict":{"usage":1}
,"usage":{"query":1}
,"disabling":{"certain":1,"query":1}
,"certain":{"user":1}
,"user":{"roles\u002Fidentities":1,"account":1,"name)":1,"want":1,"restart":1,"[users]":1,"needs":1,"operator":1,"simply":1,"using":1,"belongs":1}
,"roles\u002Fidentities":{"follows":1}
,"follows":{"using":1}
,"using":{"simple":1,"user\u0027s":1,"ldap-based":1,"ldap":1,"text":1,"credentials":1}
,"simple":{"account-based":1}
,"account-based":{"authentication":1}
,"authentication":{"(ini-file)":1,"security":1,"done":1,"method":1}
,"(ini-file)":{"security":1}
,"security":{"using":1,"authorization":1,"following":1}
,"setup":{"disabling":1}
,"defined":{"security.ini":1,"append":1}
,"security.ini":{"file":1,"text":1,"nobmsql":1}
,"file":{"located":1,"created":1,"security.ini":1,"shiro.ini":1}
,"located":{"mgmt":1}
,"mgmt":{"folder":1}
,"folder":{"user":1,"example":1,"(location":1}
,"account":{"path":1}
,"path":{"operating":1}
,"operating":{"system":1}
,"system":{"level":1}
,"level":{"file":1}
,"created":{"tmc":1}
,"specify":{"want":1,"required":1}
,"ini-file":{"authentication":1,"security)":1}
,"done":{"settings":1}
,"settings":{"menu":1}
,"menu":{"tmc":1}
,"required":{"authentication":1}
,"method":{"windows":1}
,"windows":{"systems":1,"user":1}
,"systems":{"location":1}
,"location":{"mgmt":1}
,"example":{"c:\u005Cusers\u005Cmyusername\u005C.tc":1,"security.ini":1,"tmcopstgroup2":1}
,"c:\u005Cusers\u005Cmyusername\u005C.tc":{"(where":1}
,"(where":{"myusername":1}
,"myusername":{"windows":1}
,"name)":{"linux":1}
,"linux":{"~\u002F.tc":1}
,"~\u002F.tc":{"following":1}
,"following":{"steps":1}
,"steps":{"disable":1}
,"disable":{"query":1}
,"open":{"file":1}
,"text":{"editor":1}
,"editor":{"line":1,"open":1}
,"line":{"user":1,"order":1}
,"modify":{"defined":1}
,"append":{"nobmsql":1}
,"nobmsql":{"role":1,"applied":1,"users":1,"administrator":1,"behind":1}
,"role":{"end":1,"want":1,"user":1,"[s]":1}
,"end":{"line":1}
,"order":{"disable":1}
,"restart":{"tms":1}
,"tms":{"log":1}
,"log":{"using":1}
,"user\u0027s":{"credentials":1}
,"credentials":{"ensure":1,"user":1}
,"ensure":{"query":1}
,"longer":{"visible":1}
,"visible":{"application":1}
,"applied":{"operator":1}
,"operator":{"user":1,"admin":1,"nobmsql":1,"long":1,"roles":1,"role":1,"want":1}
,"[users]":{"admin=$shiro1$sha-1$1000000$pibmtfx7zzykty57dlcsvw==$enbpzpwb\u002F\u002Fl5fbvz":1}
,"admin=$shiro1$sha-1$1000000$pibmtfx7zzykty57dlcsvw==$enbpzpwb\u002F\u002Fl5fbvz":{"+\u002Fjekj4fm\u002F4=":1}
,"+\u002Fjekj4fm\u002F4=":{"operator":1}
,"admin":{"operator=$shiro1$sha-1$1000000$3mydiqq2gjldlii7qaadsg==$timdm92xa6uxwxzn\u002Fmeh2ah7n8a=":1,"operator":1}
,"operator=$shiro1$sha-1$1000000$3mydiqq2gjldlii7qaadsg==$timdm92xa6uxwxzn\u002Fmeh2ah7n8a=":{"operator":1}
,"configuration":{"admin":1}
,"long":{"string":1}
,"string":{"behind":1,"tmc":1}
,"behind":{"encrypted":1,"mapping":1}
,"encrypted":{"password":1}
,"password":{"automatically":1,"tmc":1}
,"automatically":{"generated":1}
,"generated":{"first":1}
,"first":{"time":1}
,"time":{"configure":1}
,"configure":{"password":1}
,"currently":{"roles":1}
,"roles":{"available":1,"operator":1,"ldap":1}
,"available":{"admin":1}
,"administrator":{"user":1}
,"needs":{"assigned":1}
,"assigned":{"admin":1,"operator":1}
,"hide":{"query":1}
,"simply":{"add":1}
,"add":{"nobmsql":1}
,"ldap-based":{"security":1}
,"ldap":{"based":1,"groups":1,"group":1}
,"based":{"security":1}
,"particular":{"user":1}
,"shiro.ini":{"mgmt":1}
,"(location":{"described":1}
,"described":{"above":1}
,"above":{"ini-file":1}
,"security)":{"find":1}
,"find":{"entry":1}
,"entry":{"ldaprealm.grouprolesmapasstring":1}
,"ldaprealm.grouprolesmapasstring":{"mapping":1}
,"mapping":{"string":1,"restart":1}
,"groups":{"formatted":1}
,"formatted":{"ldap":1}
,"group":{"tmc":1,"add":1,"ensure":1}
,"[s]":{"example":1}
,"tmcopstgroup2":{"admin":1}
,"ability":{"ldap":1}
,"belongs":{"ldap":1}
}
;Search.control.loadWordPairs(pairs);
