var pairs =
{
"wan":{"replication":1,"link":1,"fault":1}
,"replication":{"service":1,"reliably":1,"ensures":1,"integrates":1,"automatically":1}
,"service":{"bigmemory":1,"includes":1}
,"bigmemory":{"wan":1,"reliability":1}
,"reliably":{"replicates":1}
,"replicates":{"data":1}
,"data":{"per-cache":1,"centers":1,"bigmemory":1,"consistency":1}
,"per-cache":{"basis":1}
,"basis":{"across":1}
,"across":{"two":1,"wan":1}
,"two":{"regions":1}
,"regions":{"connected":1}
,"connected":{"wide":1}
,"wide":{"area":1}
,"area":{"networks":1}
,"networks":{"allows":1}
,"allows":{"geographically":1}
,"geographically":{"remote":1}
,"remote":{"data":1}
,"centers":{"maintain":1}
,"maintain":{"consistent":1}
,"consistent":{"views":1}
,"views":{"data":1}
,"reliability":{"predictability":1}
,"predictability":{"wan":1}
,"ensures":{"business":1}
,"business":{"continuity":1}
,"continuity":{"used":1}
,"used":{"part":1}
,"part":{"disaster":1}
,"disaster":{"recovery":1}
,"recovery":{"plan":1}
,"plan":{"bigmemory":1}
,"integrates":{"application":1}
,"application":{"caches":1}
,"caches":{"marked":1}
,"marked":{"wan":1}
,"automatically":{"synchronized":1}
,"synchronized":{"across":1}
,"link":{"service":1}
,"includes":{"guaranteed":1}
,"guaranteed":{"data":1}
,"consistency":{"across":1}
,"fault":{"tolerance":1}
,"tolerance":{"scaling":1}
,"scaling":{"(both":1}
,"(both":{"local":1}
,"local":{"cluster":1}
,"cluster":{"number":1}
,"number":{"wan-linked":1}
,"wan-linked":{"clusters)":1}
,"clusters)":{"support":1}
,"support":{"multiple":1}
,"multiple":{"topologies":1}
,"topologies":{"operational":1}
,"operational":{"simplicity":1}
}
;Search.control.loadWordPairs(pairs);
