var pairs =
{
"active":{"directory":1}
,"directory":{"configuration":1,"components":1,"perform":1,"searchbase":1,"domain":1,"groups":1}
,"configuration":{"specify":1,"follows":1}
,"specify":{"realm":1,"correct":1}
,"realm":{"url":1}
,"url":{"<security>":1,"defined":1}
,"<security>":{"section":1}
,"section":{"terracotta":1}
,"terracotta":{"configuration":1,"keychain":1,"server":1,"roles":1,"terracotta":1}
,"follows":{"<auth>":1}
,"<auth>":{"<realm>":1}
,"<realm>":{"com.tc.net.core.security.shiroactivedirectoryrealm":1,"element":1}
,"com.tc.net.core.security.shiroactivedirectoryrealm":{"<\u002Frealm>":1}
,"<\u002Frealm>":{"<url>":1}
,"<url>":{"ldap:\u002F\u002Fadmin_user@server_address:server_port\u002Fsearchbase=search_domain":1,"ldap:\u002F\u002Fbmarley@172.16.254.1:389":1}
,"ldap:\u002F\u002Fadmin_user@server_address:server_port\u002Fsearchbase=search_domain":{"groupbindings=groups_to_roles":1}
,"groupbindings=groups_to_roles":{"<\u002Furl>":1}
,"<\u002Furl>":{"<user>":1}
,"<user>":{"<\u002Fuser>":1}
,"<\u002Fuser>":{"<\u002Fauth>":1}
,"<\u002Fauth>":{"note":1}
,"note":{"value":1}
,"value":{"<realm>":1}
,"element":{"specify":1}
,"correct":{"class":1}
,"class":{"(or":1}
,"(or":{"shiro":1}
,"shiro":{"security":1}
,"security":{"realm)":1}
,"realm)":{"active":1}
,"components":{"url":1}
,"defined":{"following":1}
,"following":{"table":1}
,"table":{"component":1}
,"component":{"description":1}
,"description":{"ldap:\u002F\u002Ffor":1}
,"ldap:\u002F\u002Ffor":{"scheme":1}
,"scheme":{"either":1}
,"either":{"ldap:\u002F\u002For":1}
,"ldap:\u002F\u002For":{"ldaps:\u002F\u002Fadmin_user":1}
,"ldaps:\u002F\u002Fadmin_user":{"name":1}
,"name":{"user":1,"server":1}
,"user":{"sufficient":1,"password":1}
,"sufficient":{"active":1}
,"perform":{"search":1}
,"search":{"domain":1}
,"domain":{"specified":1,"name":1,"searched":1,"reggae.jamaica.org":1,"admins":1}
,"specified":{"searchbase":1,"names)":1}
,"searchbase":{"password":1,"specifies":1,"groups":1}
,"password":{"user":1,"stored":1}
,"stored":{"terracotta":1}
,"keychain":{"used":1}
,"used":{"terracotta":1}
,"server":{"using":1,"port":1}
,"using":{"key":1}
,"key":{"root":1}
,"root":{"ldap":1}
,"ldap":{"uri":1}
,"uri":{"ldap:\u002F\u002Fadmin_user@server_name:server_port":1}
,"ldap:\u002F\u002Fadmin_user@server_name:server_port":{"trailing":1}
,"trailing":{"slash":1}
,"slash":{"(\u0022\u002F\u0022)":1}
,"(\u0022\u002F\u0022)":{"server_address":1}
,"server_address":{"server_port":1}
,"server_port":{"address":1}
,"address":{"resolvable":1}
,"resolvable":{"fully":1}
,"fully":{"qualified":1}
,"qualified":{"domain":1}
,"port":{"active":1}
,"specifies":{"active":1,"mappings":1}
,"searched":{"example":1}
,"example":{"active":1,"groupbindings=domain":1,"<auth>":1}
,"reggae.jamaica.org":{"format":1}
,"format":{"searchbase=dc=reggae":1}
,"searchbase=dc=reggae":{"dc=jamaica":1}
,"dc=jamaica":{"dc=org":1}
,"dc=org":{"groupbindings":1,"groupbindings=domain":1}
,"groupbindings":{"specifies":1}
,"mappings":{"active":1}
,"groups":{"terracotta":1,"domain":1,"part":1,"(including":1}
,"roles":{"example":1,"respectively":1}
,"groupbindings=domain":{"20admins=admin":1}
,"20admins=admin":{"users=terracotta":1}
,"users=terracotta":{"maps":1,"<\u002Furl>":1}
,"maps":{"active":1}
,"admins":{"users":1}
,"users":{"admin":1}
,"admin":{"terracotta":1}
,"respectively":{"mapped":1}
,"mapped":{"named":1}
,"named":{"active":1}
,"part":{"domain":1}
,"(including":{"specified":1}
,"names)":{"domains":1}
,"domains":{"ignored":1}
,"ignored":{"example":1}
,"ldap:\u002F\u002Fbmarley@172.16.254.1:389":{"searchbase=dc=reggae":1}
}
;Search.control.loadWordPairs(pairs);
