var pairs =
{
"automatic":{"recovery":1,"client":1}
,"recovery":{"scenarios":1}
,"scenarios":{"orchestrator":1}
,"orchestrator":{"failover":1,"mandatory":1,"processes":1,"resume":1,"done":1,"once":1,"takes":1,"configuration":1,"deactivates":1,"resumed":1,"resynchronize":1}
,"failover":{"recommended":1,"protection":1,"process":1,"master":1}
,"recommended":{"run":1}
,"run":{"multiple":1,"time":1}
,"multiple":{"orchestrators":1}
,"orchestrators":{"region":1,"time":1,"passive":1}
,"region":{"either":1,"dropped":1,"(similarly":1,"master":1,"lose":1,"new":1}
,"either":{"machine":1}
,"machine":{"rack":1}
,"rack":{"different":1}
,"different":{"racks":1}
,"racks":{"ensure":1}
,"ensure":{"availability":1}
,"availability":{"although":1}
,"although":{"master":1}
,"master":{"orchestrator":1,"cache":1,"(if":1,"failover":1,"replicas":1,"re-starts":1,"listed":1,"region":1,"fail":1,"behavior":1,"lost":1,"described":1,"choose":1,"changes":1,"failed":1,"restart":1,"case":1,"writes":1,"tsa":1,"caches":1}
,"mandatory":{"start":1}
,"start":{"standby":1}
,"standby":{"orchestrators":1,"replica":1}
,"time":{"during":1,"provide":1,"specified":1}
,"during":{"application":1}
,"application":{"run":1}
,"provide":{"failover":1}
,"protection":{"standby":1}
,"passive":{"running":1}
,"running":{"extra":1}
,"extra":{"orchestrator":1}
,"processes":{"minimal":1}
,"minimal":{"runtime":1}
,"runtime":{"impact":1}
,"impact":{"upon":1}
,"upon":{"failure":1,"reconnection":1,"disconnection":1}
,"failure":{"regions":1}
,"regions":{"look":1,"change":1}
,"look":{"next":1}
,"next":{"available":1}
,"available":{"orchestrator":1}
,"resume":{"replication":1,"immediately":1}
,"replication":{"failover":1,"mode":1,"place)":1,"resume":1}
,"process":{"replica":1}
,"replica":{"orchestrator":1,"caches":1,"cache":1,"region":1,"act":1,"master":1,"good":1}
,"done":{"fault-tolerant":1}
,"fault-tolerant":{"manner":1}
,"manner":{"failover":1}
,"once":{"standby":1}
,"takes":{"re-syncs":1}
,"re-syncs":{"replica":1}
,"caches":{"scratch":1,"subsequently":1,"resynchronize":1}
,"scratch":{"switches":1}
,"switches":{"normal":1}
,"normal":{"replication":1}
,"mode":{"behavior":1}
,"behavior":{"cause":1,"replicas":1,"controlled":1}
,"cause":{"slowness":1}
,"slowness":{"master":1}
,"cache":{"contains":1,"fails":1,"master":1,"reactivated":1}
,"contains":{"large":1}
,"large":{"number":1}
,"number":{"entries":1}
,"entries":{"master-replica":1}
,"master-replica":{"disconnection":1}
,"disconnection":{"master":1,"upon":1,"tsa":1}
,"fails":{"control":1}
,"control":{"given":1}
,"given":{"failover":1}
,"(if":{"any)":1}
,"any)":{"listed":1}
,"listed":{"wan-config.xml":1}
,"wan-config.xml":{"replica":1,"default":1,"upon":1,"master":1,"reflect":1}
,"replicas":{"continue":1,"governed":1,"attempt":1,"deactivated":1,"become":1}
,"continue":{"operate":1}
,"operate":{"isolation":1}
,"isolation":{"(i.e":1}
,"(i.e":{"replication":1}
,"place)":{"master":1}
,"re-starts":{"behavior":1}
,"governed":{"replicadisconnectbehavior":1}
,"replicadisconnectbehavior":{"property":1,"property.)":1}
,"property":{"wan-config.xml":1,"property":1,"described":1}
,"default":{"replicas":1}
,"attempt":{"reconnect":1}
,"reconnect":{"master":1,"bigmemory":1,"timeout":1}
,"reconnection":{"master":1}
,"deactivated":{"cleared":1}
,"cleared":{"resynchronized":1}
,"resynchronized":{"master":1}
,"reactivated":{"local":1}
,"local":{"changes":1}
,"changes":{"replica":1,"occurred":1,"may":1}
,"dropped":{"favor":1}
,"favor":{"whatever":1}
,"whatever":{"master":1}
,"(similarly":{"even":1}
,"even":{"master":1}
,"fail":{"replicas":1}
,"become":{"disconnected":1}
,"disconnected":{"master":1}
,"controlled":{"replicadisconnectbehavior":1}
,"property.)":{"information":1}
,"information":{"refer":1}
,"refer":{"orchestrator":1}
,"configuration":{"parameters":1,"without":1}
,"parameters":{"failover":1}
,"lost":{"operator":1,"regions":1}
,"operator":{"option":1}
,"option":{"restart":1}
,"restart":{"replica":1}
,"act":{"master":1}
,"described":{"below":1,"automatic":1}
,"below":{"bi-directional":1}
,"bi-directional":{"configuration":1}
,"without":{"failover":1,"need":1}
,"choose":{"important":1}
,"important":{"replica":1}
,"occurred":{"master":1}
,"failed":{"lost":1}
,"change":{"wan-config.xml":1}
,"reflect":{"replica":1}
,"good":{"idea":1}
,"idea":{"remove":1}
,"remove":{"comment":1}
,"comment":{"old":1}
,"old":{"master":1}
,"case":{"comes":1}
,"comes":{"back":1}
,"back":{"uni-directional":1}
,"uni-directional":{"configuration":1}
,"writes":{"performed":1}
,"performed":{"region":1}
,"lose":{"changes":1}
,"may":{"simply":1}
,"simply":{"designate":1}
,"designate":{"replica":1}
,"new":{"master":1}
,"tsa":{"disconnection":1,"orchestrator":1}
,"deactivates":{"waits":1}
,"waits":{"amount":1}
,"amount":{"time":1}
,"specified":{"l2.l1reconnect.timeout.millis":1}
,"l2.l1reconnect.timeout.millis":{"property":1}
,"client":{"reconnect":1}
,"bigmemory":{"max":1}
,"max":{"high-availability":1}
,"high-availability":{"guide":1}
,"guide":{"don":1}
,"don":{"added":1}
,"added":{"reference":1}
,"reference":{"communication":1}
,"communication":{"tsa":1}
,"resumed":{"downtime":1}
,"downtime":{"shorter":1,"exceeded":1}
,"shorter":{"configured":1}
,"configured":{"reconnect":1}
,"timeout":{"wan":1,"orchestrator":1}
,"wan":{"replication":1}
,"immediately":{"without":1}
,"need":{"resynchronization":1}
,"resynchronization":{"downtime":1}
,"exceeded":{"configured":1}
,"resynchronize":{"master":1,"replica":1}
,"subsequently":{"master":1}
}
;Search.control.loadWordPairs(pairs);
