var pairs =
{
"copy":{"read":1}
,"read":{"copyonread":1,"application":1}
,"copyonread":{"setting":1,"enabled":1,"copyonread":1,"effect":1,"eliminates":1,"values":1}
,"setting":{"easily":1}
,"easily":{"explained":1}
,"explained":{"first":1}
,"first":{"examining":1}
,"examining":{"enabled":1}
,"enabled":{"exploring":1,"following":1}
,"exploring":{"potential":1}
,"potential":{"problems":1}
,"problems":{"arise":1}
,"arise":{"cache":1}
,"cache":{"copyonread":1,"mapping":1,"storing":1,"value":1,"instance":1,"duplicated":1,"values":1,"service":1,"consider":1,"containing":1,"foo":1,"local":1,"longer":1,"worth":1}
,"following":{"reference":1}
,"reference":{"comparison":1,"returned":1,"cache":1}
,"comparison":{"always":1}
,"always":{"true":1}
,"true":{"object":1}
,"object":{"obj1":1,"obj2":1,"reference":1,"references":1}
,"obj1":{"=c.get":1}
,"=c.get":{"key":1}
,"key":{".getvalue":1}
,".getvalue":{"\u002F\u002Fassume":1,"(obj1":1,"foo.field":1}
,"\u002F\u002Fassume":{"thread":1}
,"thread":{"changes":1,"context":1}
,"changes":{"cache":1}
,"mapping":{"operations":1}
,"operations":{"object":1,"implies":1}
,"obj2":{"=c.get":1}
,"(obj1":{"==obj2)":1}
,"==obj2)":{"{system.err.println":1}
,"{system.err.println":{"value":1}
,"value":{"objects":1,"default":1,"types":1,"previously":1,"type":1}
,"objects":{"fact":1,"imagine":1,"distributed":1}
,"fact":{"object":1}
,"returned":{"across":1}
,"across":{"multiple":1}
,"multiple":{"operations":1}
,"implies":{"cache":1,"core":1}
,"storing":{"direct":1}
,"direct":{"reference":1}
,"default":{"behavior":1}
,"behavior":{"(copyonread=false)":1}
,"(copyonread=false)":{"usually":1}
,"usually":{"desired":1}
,"desired":{"although":1}
,"although":{"least":1}
,"least":{"two":1}
,"two":{"scenarios":1,"web":1}
,"scenarios":{"problematic":1}
,"problematic":{"caches":1}
,"caches":{"shared":1}
,"shared":{"classloaders":1,"bundles":1}
,"classloaders":{"mutable":1}
,"mutable":{"value":1}
,"imagine":{"two":1,"further":1}
,"web":{"applications":1,"application":1}
,"applications":{"access":1}
,"access":{"cache":1}
,"instance":{"(this":1,"re-put":1,"put":1}
,"(this":{"implies":1}
,"core":{"ehcache":1}
,"ehcache":{"classes":1}
,"classes":{"common":1,"value":1}
,"common":{"classloader)":1,"loader)":1,"loader":1,"cache":1}
,"classloader)":{"imagine":1}
,"further":{"classes":1}
,"types":{"cache":1,"common":1}
,"duplicated":{"web":1}
,"application":{"(so":1,"accessed":1,"obvious":1}
,"(so":{"present":1}
,"present":{"common":1}
,"loader)":{"scenario":1}
,"scenario":{"classcastexceptions":1}
,"classcastexceptions":{"web":1}
,"accessed":{"value":1}
,"previously":{"read":1}
,"obvious":{"solution":1}
,"solution":{"problem":1}
,"problem":{"move":1}
,"move":{"value":1}
,"loader":{"enable":1,"caller":1}
,"enable":{"copyonread":1}
,"effect":{"object":1}
,"references":{"unique":1,"means":1}
,"unique":{"every":1,"object":1}
,"every":{"having":1}
,"having":{"unique":1}
,"means":{"thread":1}
,"context":{"loader":1}
,"caller":{"used":1}
,"used":{"materialize":1}
,"materialize":{"cache":1}
,"values":{"feature":1,"call":1,"deserialized":1}
,"feature":{"utility":1}
,"utility":{"osgi":1}
,"osgi":{"environments":1}
,"environments":{"common":1}
,"service":{"shared":1}
,"bundles":{"subtle":1}
,"subtle":{"issue":1}
,"issue":{"concerns":1}
,"concerns":{"mutable":1}
,"distributed":{"cache":1}
,"consider":{"simple":1}
,"simple":{"code":1}
,"code":{"cache":1}
,"containing":{"mutable":1}
,"type":{"(foo)":1}
,"(foo)":{"class":1}
,"class":{"foo":1}
,"foo":{"{int":1,"foo":1,"=(foo)":1,"instance":1}
,"{int":{"field":1}
,"field":{"foo":1}
,"=(foo)":{"c.get":1}
,"c.get":{"key":1}
,"foo.field":{"\u002F\u002Ffoo":1}
,"\u002F\u002Ffoo":{"instance":1}
,"re-put":{"cache":1}
,"put":{"back":1}
,"back":{"cache":1}
,"local":{"cache":1}
,"longer":{"consistent":1}
,"consistent":{"cluster":1}
,"cluster":{"(it":1}
,"(it":{"locally":1}
,"locally":{"modified":1}
,"modified":{"only)":1}
,"only)":{"enabling":1}
,"enabling":{"copyonread":1}
,"eliminates":{"possibility":1}
,"possibility":{"affect":1}
,"affect":{"cache":1}
,"call":{"mutator":1}
,"mutator":{"methods":1}
,"methods":{"cache":1}
,"worth":{"noting":1}
,"noting":{"performance":1}
,"performance":{"penalty":1}
,"penalty":{"copyonread":1}
,"deserialized":{"every":1}
}
;Search.control.loadWordPairs(pairs);
