var pairs =
{
"requirements":{"transactional":1}
,"transactional":{"caches":1,"cache":1,"stores":1,"mode":1}
,"caches":{"<<this":1,"dynamically":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"additional":1}
,"product":{"docs.>>":1}
,"docs.>>":{"objects":1}
,"objects":{"store":1,"cache":1}
,"store":{"transactional":1,"cached":1}
,"cache":{"implement":1,"distributed":1}
,"implement":{"java.io.serializable":1,"isolation":1}
,"java.io.serializable":{"required":1}
,"required":{"store":1,"copy-on-read":1}
,"cached":{"objects":1}
,"distributed":{"terracotta":1}
,"terracotta":{"cluster":1,"consistency=\u0022":1}
,"cluster":{"required":1}
,"copy-on-read":{"\u002Fcopy-on-write":1}
,"\u002Fcopy-on-write":{"mechanism":1}
,"mechanism":{"used":1}
,"used":{"implement":1}
,"isolation":{"override":1}
,"override":{"equals":1}
,"equals":{"hashcode":1}
,"hashcode":{"overridden":1}
,"overridden":{"transactional":1}
,"stores":{"rely":1}
,"rely":{"element":1}
,"element":{"value":1}
,"value":{"comparison":1}
,"comparison":{"elementvaluecomparator":1}
,"elementvaluecomparator":{"elementvaluecomparator":1,"configuration":1}
,"configuration":{"setting":1}
,"setting":{"bmm":1}
,"additional":{"restrictions":1}
,"restrictions":{"transactional":1}
,"mode":{"terracotta":1,"attempt":1}
,"consistency=\u0022":{"strong":1}
,"strong":{"caches":1}
,"dynamically":{"changed":1}
,"changed":{"bulk-load":1}
,"bulk-load":{"mode":1}
,"attempt":{"perform":1}
,"perform":{"transaction":1}
,"transaction":{"case":1}
,"case":{"causes":1}
,"causes":{"cacheexception":1}
,"cacheexception":{"thrown":1}
,"thrown":{"using":1}
,"using":{"xa_strict":1}
,"xa_strict":{"synchronous":1}
,"synchronous":{"writes":1}
,"writes":{"(in":1}
,"(in":{"ehcache.xml)":1}
,"ehcache.xml)":{"prevent":1}
,"prevent":{"potential":1}
,"potential":{"loss":1}
,"loss":{"unwritten":1}
,"unwritten":{"data":1}
,"data":{"client":1}
,"client":{"<terracotta":1}
,"<terracotta":{"synchronouswrites=\u0022":1}
,"synchronouswrites=\u0022":{"true":1}
}
;Search.control.loadWordPairs(pairs);
