var pairs =
{
"version":{"utility":1,"tool":1,"date":1}
,"utility":{"(version)":1,"script":1}
,"(version)":{"version":1}
,"tool":{"utility":1,"expedite":1}
,"script":{"outputs":1}
,"outputs":{"information":1}
,"information":{"bigmemory":1,"[r]":1,"property=value":1}
,"bigmemory":{"installation":1}
,"installation":{"including":1,"created":1}
,"including":{"version":1}
,"date":{"version-control":1}
,"version-control":{"change":1}
,"change":{"number":1}
,"number":{"installation":1}
,"created":{"contacting":1}
,"contacting":{"terracotta":1}
,"terracotta":{"support":1}
,"support":{"query":1}
,"query":{"please":1}
,"please":{"include":1}
,"include":{"output":1}
,"output":{"version":1}
,"expedite":{"resolution":1}
,"resolution":{"issue":1}
,"issue":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"[prompt]":{"bigmemory_home":1,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fversion.sh&use":1}
,"bigmemory_home":{"%\u005Cserver\u005Cbin\u005Cversion.bat":1}
,"%\u005Cserver\u005Cbin\u005Cversion.bat":{"unix\u002Flinux":1}
,"unix\u002Flinux":{"[prompt]":1}
,"${bigmemory_home}\u002Fserver\u002Fbin\u002Fversion.sh&use":{"following":1}
,"following":{"flags":1}
,"flags":{"produce":1}
,"produce":{"information":1}
,"[r]":{"produces":1}
,"produces":{"detailed":1}
,"detailed":{"raw":1,"information":1}
,"raw":{"information":1}
,"property=value":{"format":1}
,"format":{"[v]":1}
,"[v]":{"produces":1}
}
;Search.control.loadWordPairs(pairs);
