var pairs =
{
"using":{"bulk":1,"method":1}
,"bulk":{"load":1,"loading":1}
,"load":{"api":1,"(true)":1}
,"api":{"bulk":1,"putting":1,"used":1,"methods":1,"crucial":1}
,"loading":{"api":1}
,"putting":{"data":1}
,"data":{"bigmemory":1,"cache":1}
,"bigmemory":{"max":1}
,"max":{"stays":1,"following":1,"public":1}
,"stays":{"just":1}
,"just":{"cache.put":1,"node":1}
,"cache.put":{"cache.load":1}
,"cache.load":{"cache.loadall":1}
,"cache.loadall":{"changes":1}
,"changes":{"special":1,"automatically":1}
,"special":{"mode":1}
,"mode":{"suspends":1,"cache":1,"allow":1,"terracotta":1,"(is":1,"configured":1,"(false)":1,"specified":1,"consistency":1}
,"suspends":{"normal":1}
,"normal":{"distributed-cache":1}
,"distributed-cache":{"consistency":1}
,"consistency":{"guarantees":1,"mode":1,"cannot":1}
,"guarantees":{"provides":1}
,"provides":{"optimized":1}
,"optimized":{"flushing":1}
,"flushing":{"terracotta":1}
,"terracotta":{"server":1,"clustering":1}
,"server":{"array":1}
,"array":{"(the":1}
,"(the":{"cache)":1}
,"cache)":{"initial":1}
,"initial":{"consistency":1}
,"cache":{"configuration":1,"bulk-load":1,"already":1,"multiple":1,"consistent":1,"updated":1,"understanding":1}
,"configuration":{"cannot":1,"elements":1,"guide":1}
,"cannot":{"changed":1,"guaranteed":1}
,"changed":{"programmatically":1}
,"programmatically":{"bulk-load":1}
,"bulk-load":{"api":1,"operations":1,"mode":1,"operation":1}
,"used":{"temporarily":1}
,"temporarily":{"suspending":1}
,"suspending":{"configured":1}
,"configured":{"consistency":1,"nonstop":1,"manually":1}
,"allow":{"bulk-load":1}
,"operations":{"information":1}
,"information":{"setting":1,"tuning":1}
,"setting":{"consistency":1}
,"clustering":{"configuration":1}
,"elements":{"configuration":1}
,"guide":{"bigmemory":1}
,"following":{"bulk-load":1}
,"methods":{"available":1,"fail":1}
,"available":{"org.terracotta.modules.ehcache.cache":1}
,"org.terracotta.modules.ehcache.cache":{"public":1}
,"public":{"boolean":1,"void":1}
,"boolean":{"isclusterbulkloadenabled":1,"isnodebulkloadenabled":1}
,"isclusterbulkloadenabled":{"returns":1,"return":1}
,"returns":{"true":1,"false":1,"immediately":1}
,"true":{"cache":1}
,"(is":{"consistent)":1}
,"consistent)":{"throughout":1,"anywhere":1,"current":1}
,"throughout":{"cluster":1}
,"cluster":{"returns":1,"public":1,"notes":1}
,"false":{"cache":1,"node":1}
,"anywhere":{"cluster":1}
,"isnodebulkloadenabled":{"returns":1}
,"current":{"node":1}
,"node":{"returns":1,"public":1,"operation":1,"just":1,"calls":1}
,"void":{"setnodebulkloadenabled":1,"waituntilbulkloadcomplete":1}
,"setnodebulkloadenabled":{"(boolean)":1,"using":1,"(true)":1}
,"(boolean)":{"sets":1}
,"sets":{"cache\u0027s":1}
,"cache\u0027s":{"consistency":1,"timeout":1}
,"(false)":{"bulk":1}
,"(true)":{"local":1,"cache":1}
,"local":{"node":1}
,"operation":{"cache":1,"complete":1}
,"already":{"mode":1}
,"specified":{"setnodebulkloadenabled":1}
,"method":{"nonstop":1,"fails":1}
,"nonstop":{"cache":1,"cache\u0027s":1,"behavior":1,"timeouts":1}
,"multiple":{"nonstop":1,"prevent":1}
,"timeout":{"value":1,"multiple":1}
,"value":{"applies":1}
,"applies":{"bulk-load":1}
,"complete":{"within":1}
,"within":{"timeout":1}
,"prevent":{"configured":1}
,"behavior":{"taking":1}
,"taking":{"effect":1}
,"effect":{"information":1}
,"tuning":{"nonstop":1}
,"timeouts":{"tuning":1,"behaviors":1}
,"behaviors":{"configuration":1}
,"waituntilbulkloadcomplete":{"waits":1}
,"waits":{"until":1}
,"until":{"cache":1}
,"consistent":{"returning":1,"throughout":1,"objectnotfound":1}
,"returning":{"changes":1}
,"automatically":{"batched":1}
,"batched":{"cache":1}
,"updated":{"throughout":1}
,"immediately":{"cache":1}
,"notes":{"bulk-load":1}
,"guaranteed":{"isclusterbulkloadenabled":1}
,"return":{"false":1,"null":1}
,"calls":{"setnodebulkloadenabled":1}
,"understanding":{"exactly":1}
,"exactly":{"application":1}
,"application":{"uses":1}
,"uses":{"bulk-load":1}
,"crucial":{"effectively":1}
,"effectively":{"managing":1}
,"managing":{"integrity":1}
,"integrity":{"cached":1}
,"cached":{"data":1}
,"objectnotfound":{"exceptions":1,"return":1,"exception":1}
,"exceptions":{"may":1}
,"may":{"occur":1}
,"occur":{"logged":1}
,"logged":{"methods":1}
,"fail":{"objectnotfound":1}
,"null":{"<<ffc-is":1,"original":1}
,"<<ffc-is":{"rewite":1}
,"rewite":{"method":1}
,"fails":{"objectnotfound":1}
,"exception":{"return":1}
,"original":{"difficult":1}
,"difficult":{"understand.>>":1}
,"understand.>>":{"eviction":1}
,"eviction":{"independent":1,"proceeds":1}
,"independent":{"consistency":1}
,"manually":{"executed":1}
,"executed":{"eviction":1}
,"proceeds":{"unaffected":1}
,"unaffected":{"cache\u0027s":1}
}
;Search.control.loadWordPairs(pairs);
