var pairs =
{
"using":{"tmc":1}
,"tmc":{"bigmemory":1}
,"bigmemory":{"hybrid":1}
,"hybrid":{"terracotta":1,"feature":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"(tmc)":1}
,"(tmc)":{"effect":1}
,"effect":{"bigmemory":1}
,"feature":{"monitoring":1}
,"monitoring":{"runtime":1}
,"runtime":{"stats":1}
,"stats":{"panel":1}
,"panel":{"data":1}
,"data":{"storage":1,"used":1}
,"storage":{"usage":1}
,"usage":{"cache":1,"graph":1}
,"cache":{"operating":1}
,"operating":{"steady":1}
,"steady":{"state":1}
,"state":{"data":1}
,"used":{"typically":1}
,"typically":{"exceeds":1}
,"exceeds":{"offheap":1}
,"offheap":{"max":1,"usage":1}
,"max":{"shown":1}
,"shown":{"offheap":1}
}
;Search.control.loadWordPairs(pairs);
