var pairs =
{
"adding":{"entries":1}
,"entries":{"encrypted":1,"keychain":1}
,"encrypted":{"keychain":1}
,"keychain":{"files":1,"file":1,"avoid":1,"script":1,"file\u0027s":1,"entering":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"files":{"add":1}
,"add":{"entries":1,"option":1}
,"file":{"described":1,"exist":1}
,"described":{"setting":1}
,"setting":{"server":1}
,"server":{"keychain":1}
,"avoid":{"using":1}
,"using":{"flag":1,"keychain":1}
,"flag":{"using":1}
,"script":{"example":1}
,"example":{"create":1,"above":1}
,"create":{"entry":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"entry":{"local":1,"server1":1,"server2":1}
,"local":{"server\u0027s":1}
,"server\u0027s":{"keystore":1,"certificate":1}
,"keystore":{"password":1,"example":1}
,"password":{"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1,"password":1,"associate":1,"used":1,"wish":1,"jks:server1alias@keystore-file.jks":1}
,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":{"<keychain-file>":1,"server1keychain.tkc":1}
,"<keychain-file>":{"<certificate-uri>":1}
,"<certificate-uri>":{"keychain":1,"prompted":1}
,"exist":{"add":1}
,"option":{"create":1}
,"prompted":{"keychain":1}
,"file\u0027s":{"master":1}
,"master":{"password":1,"key":1}
,"associate":{"uri":1,"url":1}
,"uri":{"uri":1,"enter":1}
,"enter":{"password":1,"tools\u002Fsecurity\u002Fbin\u002Fkeychain.sh":1}
,"used":{"secure":1}
,"secure":{"server\u0027s":1}
,"certificate":{"keystore":1}
,"server1":{"configuration":1,"keychain":1}
,"configuration":{"example":1}
,"above":{"enter":1}
,"server1keychain.tkc":{"jks:server1alias@keystore-file.jks":1,"tc:\u002F\u002Fserver2username@172.16.254.2:9530":1}
,"jks:server1alias@keystore-file.jks":{"terracotta":1,"successfully":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"-keychain":1}
,"-keychain":{"client":1}
,"client":{"open":1}
,"open":{"keychain":1}
,"entering":{"master":1}
,"key":{"xxxxxxx":1}
,"xxxxxxx":{"enter":1}
,"wish":{"associate":1}
,"url":{"server1pass":1}
,"server1pass":{"confirm":1,"password":1}
,"confirm":{"password":1}
,"successfully":{"stored":1}
,"stored":{"create":1}
,"server2":{"server1":1}
}
;Search.control.loadWordPairs(pairs);
