var pairs =
{
"reliability":{"high":1}
,"high":{"availability":1}
,"availability":{"failover":1}
,"failover":{"tuning":1}
,"tuning":{"terracotta":1,"scaling":1,"additional":1}
,"terracotta":{"server":1,"comes":1}
,"server":{"array":1}
,"array":{"tuned":1,"architecture":1}
,"tuned":{"various":1}
,"various":{"scenarios":1}
,"scenarios":{"depending":1}
,"depending":{"requirements":1}
,"requirements":{"application":1}
,"application":{"terracotta":1}
,"comes":{"certain":1}
,"certain":{"default":1}
,"default":{"settings":1}
,"settings":{"however":1}
,"however":{"configured":1}
,"configured":{"accordingly":1}
,"accordingly":{"understand":1}
,"understand":{"setting":1}
,"setting":{"refer":1}
,"refer":{"section":1}
,"section":{"terracotta":1}
,"architecture":{"subsections":1}
,"subsections":{"discuss":1}
,"discuss":{"features":1}
,"features":{"fast":1}
,"fast":{"restart":1}
,"restart":{"high":1}
,"scaling":{"failover":1}
,"additional":{"component":1}
,"component":{"guaranteed":1}
,"guaranteed":{"consistency":1}
,"consistency":{"across":1}
,"across":{"data":1}
,"data":{"centers":1}
,"centers":{"requires":1}
,"requires":{"feature":1}
,"feature":{"part":1}
,"part":{"license":1}
,"license":{"key":1}
,"key":{"contact":1}
,"contact":{"nearest":1}
,"nearest":{"software":1}
,"software":{"representative":1}
,"representative":{"case":1}
,"case":{"questions":1}
}
;Search.control.loadWordPairs(pairs);
