var pairs =
{
"overview":{"panel":1}
,"panel":{"replica":1,"display":1,"top":1,"select":1}
,"replica":{"caches":1,"cache":1,"orchestrator":1,"cache\u0027s":1,"select":1}
,"caches":{"overview":1,"enabling":1,"want":1,"replicas":1}
,"display":{"information":1,"orchestrator\u0027s":1}
,"information":{"performance":1,"collected":1,"overview":1,"wan\u0027s":1}
,"performance":{"statistics":1,"resource":1}
,"statistics":{"cachemanagers":1,"displayed":1,"descriptions":1,"wan":1}
,"cachemanagers":{"replica":1,"information":1}
,"enabling":{"track":1}
,"track":{"performance":1}
,"resource":{"usage":1}
,"usage":{"across":1}
,"across":{"cachemanagers":1}
,"collected":{"master":1}
,"master":{"orchestrators":1,"cache\u0027s":1}
,"orchestrators":{"view":1}
,"view":{"replica":1,"click":1,"information":1}
,"cache":{"information":1,"column":1,"replica":1}
,"top":{"overview":1}
,"select":{"cachemanager":1,"(or":1}
,"cachemanager":{"replica":1}
,"want":{"view":1}
,"click":{"replicas":1,"address":1,"topology":1,"configure":1,"replica":1}
,"replicas":{"wan":1,"button":1}
,"wan":{"contains":1,"tab":1}
,"contains":{"replica":1}
,"button":{"greyed":1}
,"greyed":{"following":1}
,"following":{"columns":1}
,"columns":{"displayed":1,"pop-up":1}
,"displayed":{"default":1,"click":1}
,"default":{"replica":1,"statistics":1}
,"column":{"description":1}
,"description":{"cache":1}
,"orchestrator":{"address":1,"process":1,"topology":1}
,"address":{"(hostname":1,"(the":1,"link":1}
,"(hostname":{"communication":1}
,"communication":{"port)":1}
,"port)":{"orchestrator":1,"master":1}
,"(the":{"hostname":1}
,"hostname":{"communication":1}
,"cache\u0027s":{"orchestrator":1,"replication":1}
,"process":{"display":1}
,"orchestrator\u0027s":{"xml":1}
,"xml":{"configuration":1}
,"configuration":{"click":1}
,"link":{"view":1}
,"wan\u0027s":{"orchestrator":1}
,"topology":{"click":1,"example":1}
,"example":{"linux-001.net:9001":1}
,"linux-001.net:9001":{"linux-002.net:9001":1}
,"linux-002.net:9001":{"replication":1}
,"replication":{"mode":1,"rate":1,"last":1,"mean":1,"count":1}
,"mode":{"replica":1,"(unidirectional":1}
,"(unidirectional":{"bidirectional)":1}
,"bidirectional)":{"inbound":1}
,"inbound":{"buffer":1}
,"buffer":{"size":1,"replication":1}
,"size":{"size":1,"cluster":1}
,"cluster":{"listener":1}
,"listener":{"buffer":1}
,"rate":{"min.)":1,"average":1}
,"min.)":{"average":1}
,"average":{"transactions":1}
,"transactions":{"per":1,"entire":1}
,"per":{"second":1}
,"second":{"(tps)":1}
,"(tps)":{"during":1,"entire":1}
,"during":{"replication":1}
,"last":{"minute":1}
,"minute":{"replication":1}
,"mean":{"rate":1}
,"entire":{"synchronization":1}
,"synchronization":{"interval":1}
,"interval":{"replication":1,"change":1}
,"count":{"total":1}
,"total":{"number":1}
,"number":{"transactions":1}
,"change":{"default":1}
,"configure":{"columns":1}
,"pop-up":{"displays":1}
,"displays":{"click":1}
,"(or":{"all)":1}
,"all)":{"statistics":1}
,"descriptions":{"statistics":1}
,"tab":{"statistics":1}
}
;Search.control.loadWordPairs(pairs);
