var pairs =
{
"events":{"events":1,"panel":1,"received":1,"location":1,"shown":1,"red":1,"lower":1,"level":1,"display":1,"filtered":1,"warn":1,"read":1,"information":1,"bigmemory":1}
,"panel":{"displays":1,"quickly":1}
,"displays":{"cluster":1}
,"cluster":{"events":1}
,"received":{"terracotta":1}
,"terracotta":{"server":1,"logs":1}
,"server":{"array":1}
,"array":{"panel":1}
,"quickly":{"view":1}
,"view":{"events":1}
,"location":{"easy-to-read":1}
,"easy-to-read":{"format":1}
,"format":{"without":1}
,"without":{"having":1}
,"having":{"search":1}
,"search":{"terracotta":1}
,"logs":{"number":1}
,"number":{"unread":1}
,"unread":{"events":1,"clear":1}
,"shown":{"badge":1}
,"badge":{"clustered":1,"color":1}
,"clustered":{"connection\u0027s":1}
,"connection\u0027s":{"mini":1}
,"mini":{"dashboard":1}
,"dashboard":{"badge":1}
,"color":{"indicates":1}
,"indicates":{"severity":1}
,"severity":{"unread":1,"monitoring":1}
,"red":{"warnings":1}
,"warnings":{"above":1}
,"above":{"gray":1}
,"gray":{"unread":1}
,"lower":{"severity":1}
,"monitoring":{"events":1,"cluster":1}
,"level":{"dropdown":1,"select":1}
,"dropdown":{"list":1}
,"list":{"allows":1,"buttons":1}
,"allows":{"select":1}
,"select":{"debug":1,"example":1,"info":1,"warn":1}
,"debug":{"info":1,"events":1}
,"info":{"warn":1,"debug":1}
,"warn":{"error":1,"events":1}
,"error":{"critical":1}
,"critical":{"events":1,"levels":1}
,"display":{"equal":1}
,"equal":{"higher":1}
,"higher":{"level":1}
,"example":{"select":1}
,"filtered":{"select":1}
,"levels":{"click":1}
,"click":{"column":1}
,"column":{"head":1}
,"head":{"order":1}
,"order":{"list":1}
,"buttons":{"mark":1}
,"mark":{"events":1}
,"read":{"unread":1,"events":1}
,"clear":{"read":1}
,"information":{"event":1}
,"event":{"types":1}
,"types":{"monitoring":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
