var pairs =
{
"controlling":{"cache":1,"size":1}
,"cache":{"size":1,"configuration":1,"information":1,"managing":1}
,"size":{"<<dropping":1,"cache":1}
,"<<dropping":{"topic":1}
,"topic":{"thin>>":1,"it\u2019s":1}
,"thin>>":{"certain":1}
,"certain":{"ehcache":1}
,"ehcache":{"cache":1}
,"configuration":{"attributes":1,"affects":1}
,"attributes":{"affect":1}
,"affect":{"caches":1}
,"caches":{"clustered":1}
,"clustered":{"terracotta":1}
,"terracotta":{"configuration":1}
,"affects":{"eviction":1}
,"eviction":{"distributed":1,"<<insert":1,"controlling":1}
,"distributed":{"cache":1}
,"information":{"configuration":1}
,"<<insert":{"xref":1,"links":1}
,"xref":{"topic":1}
,"it\u2019s":{"data":1}
,"data":{"life":1}
,"life":{"chapter":1,"sizing":1}
,"chapter":{"book>>":1}
,"book>>":{"learn":1}
,"learn":{"eviction":1}
,"managing":{"data":1}
,"sizing":{"storage":1}
,"storage":{"tiers":1}
,"tiers":{"<<insert":1}
,"links":{"chapters":1}
,"chapters":{"book>>":1}
}
;Search.control.loadWordPairs(pairs);
