var pairs =
{
"working":{"terracotta":1}
,"terracotta":{"license":1,"products":1,"enterprise":1,"extension":1,"software":1,"runtime":1,"installation":1,"configuration":1,"max":1}
,"license":{"files":1,"file":1,"loaded":1,"number":1,"type":1}
,"files":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bigmemory":1}
,"bigmemory":{"max":1,"install":1,"max)":1}
,"max":{"bigmemory":1,"client":1}
,"install":{"guides":1}
,"guides":{"terracotta":1}
,"file":{"required":1,"terracotta-license.key":1,"configuration":1,"provided":1,"placed":1,"file":1,"terracotta":1,"different":1,"specified":1,"(tc-config.xml":1,"war":1,"substitute":1,"(terracotta-license.key)":1}
,"required":{"run":1}
,"run":{"enterprise":1}
,"enterprise":{"versions":1,"products":1,"version":1,"suite":1}
,"versions":{"terracotta":1}
,"products":{"name":1,"expire":1,"features":1}
,"name":{"file":1}
,"terracotta-license.key":{"changed":1}
,"changed":{"trial":1}
,"trial":{"versions":1,"period":1,"licensee":1}
,"expire":{"trial":1}
,"period":{"expiration":1}
,"expiration":{"warnings":1,"date":1}
,"warnings":{"issued":1}
,"issued":{"logs":1}
,"logs":{"standard":1,"message":1}
,"standard":{"output":1,"terracotta":1}
,"output":{"allow":1,"message":1}
,"allow":{"enough":1}
,"enough":{"time":1}
,"time":{"contact":1}
,"contact":{"terracotta":1}
,"extension":{"node":1}
,"node":{"using":1}
,"using":{"enterprise":1,"bigmemory":1,"web":1}
,"version":{"terracotta":1}
,"software":{"requires":1,"kit":1,"logs":1}
,"requires":{"copy":1}
,"copy":{"license":1}
,"configuration":{"specifies":1,"file":1}
,"specifies":{"file\u0027s":1}
,"file\u0027s":{"location":1}
,"location":{"default":1,"leave":1,"license":1,"specify":1}
,"default":{"file":1}
,"provided":{"root":1}
,"root":{"directory":1}
,"directory":{"terracotta":1,"generally":1,"specify":1}
,"kit":{"avoid":1}
,"avoid":{"having":1}
,"having":{"explicitly":1}
,"explicitly":{"specify":1,"specifying":1}
,"specify":{"file\u0027s":1,"-dtc.install-root=\u002Fpath\u002Fto\u002Fterracotta-install-dir":1,"-dcom.tc.productkey.path=\u002Fpath\u002Fto\u002Fterracotta-license.key":1}
,"leave":{"kit\u0027s":1}
,"kit\u0027s":{"root":1}
,"generally":{"(if":1}
,"(if":{"using":1}
,"max)":{"ensure":1}
,"ensure":{"resource":1}
,"resource":{"\u002Fterracotta-license.key":1}
,"\u002Fterracotta-license.key":{"classpath":1}
,"classpath":{"standard":1}
,"runtime":{"jars":1}
,"jars":{"example":1}
,"example":{"license":1}
,"placed":{"web-inf\u002Fclasses":1}
,"web-inf\u002Fclasses":{"using":1}
,"web":{"application":1}
,"application":{"explicitly":1}
,"specifying":{"location":1}
,"installation":{"directory":1}
,"-dtc.install-root=\u002Fpath\u002Fto\u002Fterracotta-install-dir":{"file":1}
,"different":{"location":1}
,"-dcom.tc.productkey.path=\u002Fpath\u002Fto\u002Fterracotta-license.key":{"alternatively":1}
,"alternatively":{"path":1}
,"path":{"license":1}
,"specified":{"adding":1}
,"adding":{"following":1}
,"following":{"beginning":1,"2010-11-03":1}
,"beginning":{"terracotta":1}
,"(tc-config.xml":{"default)":1}
,"default)":{"<tc-properties>":1}
,"<tc-properties>":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"productkey.path":1}
,"productkey.path":{"value=\u0022":1,"verifying":1}
,"value=\u0022":{"path\u002Fto\u002Fterracotta-license.key":1}
,"path\u002Fto\u002Fterracotta-license.key":{"<!--other":1}
,"<!--other":{"tc.properties":1}
,"tc.properties":{"-->":1}
,"-->":{"<\u002Ftc-properties>":1}
,"<\u002Ftc-properties>":{"refer":1}
,"refer":{"license":1}
,"war":{"jar":1}
,"jar":{"file":1}
,"substitute":{"productkey.resource.path":1}
,"productkey.resource.path":{"productkey.path":1}
,"verifying":{"products":1}
,"features":{"number":1,"allowed":1}
,"number":{"ways":1,"0000":1}
,"ways":{"verify":1}
,"verify":{"products":1}
,"allowed":{"limitations":1}
,"limitations":{"imposed":1}
,"imposed":{"product":1}
,"product":{"key":1,"enterprise":1}
,"key":{"first":1,"second":1,"message":1}
,"first":{"looking":1}
,"looking":{"readable":1}
,"readable":{"file":1}
,"(terracotta-license.key)":{"containing":1}
,"containing":{"product":1}
,"second":{"startup":1}
,"startup":{"terracotta":1}
,"message":{"detailing":1,"printed":1,"appear":1}
,"detailing":{"product":1}
,"printed":{"log":1}
,"log":{"standard":1}
,"appear":{"similar":1}
,"similar":{"following":1}
,"2010-11-03":{"15:56:53,701":1}
,"15:56:53,701":{"info":1}
,"info":{"-terracotta":1}
,"-terracotta":{"license":1}
,"loaded":{"\u002Fdownloads\u002Fterracotta-ee-3.4.0\u002Fterracotta-license.key":1}
,"\u002Fdownloads\u002Fterracotta-ee-3.4.0\u002Fterracotta-license.key":{"capabilities":1}
,"capabilities":{"dcv2":1}
,"dcv2":{"authentication":1}
,"authentication":{"ehcache":1}
,"ehcache":{"ehcache":1,"monitor":1,"offheap":1}
,"monitor":{"ehcache":1}
,"offheap":{"operator":1,"server":1}
,"operator":{"console":1}
,"console":{"quartz":1}
,"quartz":{"roots":1}
,"roots":{"server":1}
,"server":{"array":1,"striping":1}
,"array":{"offheap":1}
,"striping":{"sessions":1}
,"sessions":{"date":1}
,"date":{"issue":1,"2011-01-03":1}
,"issue":{"2010-10-16":1}
,"2010-10-16":{"edition":1}
,"edition":{"expiration":1}
,"2011-01-03":{"license":1}
,"0000":{"license":1}
,"type":{"trial":1}
,"licensee":{"terracotta":1}
,"client":{"count":1}
,"count":{"100":1}
,"100":{"product":1}
,"suite":{"ehcache.maxoffheap":1}
,"ehcache.maxoffheap":{"200g":1}
,"200g":{"terracotta.serverarray.maxoffheap":1}
,"terracotta.serverarray.maxoffheap":{"200g":1}
}
;Search.control.loadWordPairs(pairs);
