var pairs =
{
"running":{"periodic":1}
,"periodic":{"distributed":1,"dgc":1}
,"distributed":{"garbage":1}
,"garbage":{"collection":1,"necessary":1}
,"collection":{"periodic":1}
,"dgc":{"run":1,"externally":1,"server\u0027s":1,"disabled":1}
,"run":{"following":1,"automatically":1,"(such":1}
,"following":{"ways":1}
,"ways":{"run-dgc":1}
,"run-dgc":{"shell":1}
,"shell":{"script":1}
,"script":{"-call":1,"trigger":1}
,"-call":{"run-dgc":1}
,"trigger":{"dgc":1}
,"externally":{"jmx":1}
,"jmx":{"-trigger":1,"management":1}
,"-trigger":{"dgc":1}
,"server\u0027s":{"jmx":1}
,"management":{"interface":1}
,"interface":{"default":1}
,"default":{"dgc":1}
,"disabled":{"terracotta":1,"run":1}
,"terracotta":{"configuration":1}
,"configuration":{"file":1}
,"file":{"<garbage-collection>":1}
,"<garbage-collection>":{"section":1}
,"section":{"however":1}
,"however":{"even":1}
,"even":{"disabled":1}
,"automatically":{"certain":1}
,"certain":{"circumstances":1}
,"circumstances":{"clearing":1}
,"clearing":{"garbage":1}
,"necessary":{"inline":1}
,"inline":{"dgc":1}
,"(such":{"crashed":1}
,"crashed":{"server":1}
,"server":{"returns":1}
,"returns":{"cluster)":1}
}
;Search.control.loadWordPairs(pairs);
