var pairs =
{
"starting":{"cluster":1}
,"cluster":{"terracotta":1,"start":1}
,"terracotta":{"function":1,"server":1}
,"function":{"properly":1}
,"properly":{"sure":1}
,"sure":{"java_home":1}
,"java_home":{"setting":1}
,"setting":{"start":1}
,"start":{"cluster":1,"terracotta":1,"application":1,"management":1}
,"server":{"unix\u002Flinux":1,"information":1}
,"unix\u002Flinux":{"[prompt]":1}
,"[prompt]":{"${terracotta_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":1,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":1}
,"${terracotta_home}\u002Fserver\u002Fbin\u002Fstart-tc-server.sh":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"[prompt]":1}
,"${terracotta_home}\u005Cserver\u005Cbin\u005Cstart-tc-server.bat":{"start":1}
,"application":{"servers":1,"server":1}
,"servers":{"(optional)":1}
,"(optional)":{"start":1}
,"management":{"console":1}
,"console":{"(any":1}
,"(any":{"jmx":1}
,"jmx":{"monitoring":1}
,"monitoring":{"tool":1}
,"tool":{"fine)":1}
,"fine)":{"connect":1}
,"connect":{"application":1}
,"information":{"refer":1}
,"refer":{"managing":1}
,"managing":{"web":1}
,"web":{"sessions":1}
,"sessions":{"using":1}
,"using":{"jmx":1}
}
;Search.control.loadWordPairs(pairs);
