var pairs =
{
"fast":{"restart":1,"restarts":1,"read":1}
,"restart":{"(frs)":1,"feature":1,"real-time":1,"provides":1,"store":1}
,"(frs)":{"<<this":1,"feature":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"bigmemory\u2019s":1}
,"bigmemory\u2019s":{"fast":1}
,"feature":{"provides":1,"include":1}
,"provides":{"enterprise-ready":1,"true":1,"equivalent":1}
,"enterprise-ready":{"crash":1}
,"crash":{"resilience":1}
,"resilience":{"keeping":1}
,"keeping":{"fully":1}
,"fully":{"consistent":1}
,"consistent":{"real-time":1,"record":1}
,"real-time":{"record":1}
,"record":{"in-memory":1}
,"in-memory":{"data":1,"speeds":1}
,"data":{"kind":1,"bigmemory":1,"survives":1,"need":1,"source":1,"provides":1,"consistency":1,"opens":1,"sets":1}
,"kind":{"shutdown":1}
,"shutdown":{"planned":1}
,"planned":{"unplanned":1}
,"unplanned":{"next":1}
,"next":{"time":1}
,"time":{"application":1}
,"application":{"starts":1}
,"starts":{"data":1}
,"bigmemory":{"available":1}
,"available":{"quickly":1}
,"quickly":{"accessible":1}
,"accessible":{"advantages":1}
,"advantages":{"fast":1}
,"include":{"in-memory":1}
,"survives":{"crashes":1}
,"crashes":{"enables":1}
,"enables":{"fast":1}
,"restarts":{"in-memory":1}
,"need":{"reloaded":1}
,"reloaded":{"remote":1}
,"remote":{"data":1}
,"source":{"applications":1}
,"applications":{"resume":1}
,"resume":{"full":1}
,"full":{"speed":1,"data":1}
,"speed":{"restart":1}
,"true":{"fault":1}
,"fault":{"tolerance":1}
,"tolerance":{"fast":1}
,"equivalent":{"local":1}
,"local":{"hot":1}
,"hot":{"mirror":1}
,"mirror":{"guarantees":1}
,"guarantees":{"full":1}
,"consistency":{"consistent":1}
,"opens":{"possibilities":1}
,"possibilities":{"business":1}
,"business":{"innovation":1}
,"innovation":{"arranging":1}
,"arranging":{"data":1}
,"sets":{"according":1,"around":1}
,"according":{"time-based":1}
,"time-based":{"needs":1}
,"needs":{"moving":1}
,"moving":{"data":1}
,"around":{"different":1}
,"different":{"locations":1}
,"locations":{"uses":1}
,"uses":{"fast":1}
,"store":{"range":1,"in-memory":1}
,"range":{"simple":1}
,"simple":{"key-value":1}
,"key-value":{"persistence":1}
,"persistence":{"mechanism":1}
,"mechanism":{"fast":1}
,"read":{"performance":1}
,"performance":{"operational":1}
,"operational":{"store":1}
,"speeds":{"during":1}
,"during":{"operation":1}
,"operation":{"reads":1}
,"reads":{"writes":1}
}
;Search.control.loadWordPairs(pairs);
