var pairs =
{
"client":{"serialization":1}
,"serialization":{"data":1,"include":1}
,"data":{"shared":1}
,"shared":{"across":1}
,"across":{"languages":1}
,"languages":{"needs":1}
,"needs":{"serialized":1,"choice":1}
,"serialized":{"choice":1}
,"choice":{"serializer":1}
,"serializer":{"depends":1,"pros":1,"manually":1,"automatically":1,"however":1}
,"depends":{"upon":1}
,"upon":{"environment":1}
,"environment":{"planning":1}
,"planning":{"consideration":1}
,"consideration":{"needs":1}
,"pros":{"cons":1}
,"cons":{"related":1}
,"related":{"example":1}
,"example":{"json":1,"demonstrates":1}
,"json":{"serializer":1}
,"manually":{"annotate":1}
,"annotate":{"domain":1}
,"domain":{"object":1}
,"object":{"desired":1,"annotation":1,"using":1,"value":1}
,"desired":{"attributes":1}
,"attributes":{"hand":1}
,"hand":{"google":1}
,"google":{"protocol":1}
,"protocol":{"buffer":1}
,"buffer":{"serializer":1,"serialization":1}
,"automatically":{"generate":1}
,"generate":{"domain":1}
,"annotation":{"serializer":1}
,"however":{"existing":1}
,"existing":{"domain":1}
,"using":{"automatic":1}
,"automatic":{"generation":1}
,"generation":{"intrusive":1}
,"intrusive":{"serializer\u002Fdeserializer":1}
,"serializer\u002Fdeserializer":{"class":1,"example":1}
,"class":{"include":1,"definition":1}
,"include":{"following":1,"recipeprotobufserializer.h":1}
,"following":{"list":1,"methods\u002Ffunctions":1,"serializer\u002Fdeserializer":1}
,"list":{"namespaces\u002Fpackages":1}
,"namespaces\u002Fpackages":{"used":1}
,"used":{"class":1}
,"definition":{"consisting":1}
,"consisting":{"following":1}
,"methods\u002Ffunctions":{"serializekey":1}
,"serializekey":{"-accepts":1}
,"-accepts":{"key":1,"pnf":1,"object":1}
,"key":{"returns":1,"serializevalue":1}
,"returns":{"platform-neutral":1,"key":1,"pnf":1,"object":1}
,"platform-neutral":{"format":1}
,"format":{"(pnf)":1}
,"(pnf)":{"value":1}
,"value":{"deserializekey":1,"returns":1,"following":1,"=cachevalue":1,"recipestructure":1}
,"deserializekey":{"-accepts":1}
,"pnf":{"value":1,"valueobject":1}
,"serializevalue":{"-accepts":1}
,"valueobject":{"deserializevalue":1,"returns":1,"recipeprotobufserializer":1,":stringvalue":1}
,"deserializevalue":{"-accepts":1}
,"demonstrates":{"google":1}
,"recipeprotobufserializer.h":{"valueobject":1}
,"recipeprotobufserializer":{":serializekey":1,":deserializekey":1,":serializevalue":1,":deserializevalue":1}
,":serializekey":{"(std":1}
,"(std":{":string":1}
,":string":{"&deserializedkey)":1,"recipeprotobufserializer":1,"valueobject>":1}
,"&deserializedkey)":{"{return":1}
,"{return":{"valueobject":1,"serializedkey.getstring":1}
,":stringvalue":{"(deserializedkey)":1,"(deserializedvalue.name":1}
,"(deserializedkey)":{"std":1}
,"std":{":string":1,":map":1}
,":deserializekey":{"(valueobject":1}
,"(valueobject":{"&serializedkey)":1,":binaryvalue":1}
,"&serializedkey)":{"{return":1}
,"serializedkey.getstring":{"cachevalue":1}
,"cachevalue":{"recipeprotobufserializer":1}
,":serializevalue":{"(recipestructure":1}
,"(recipestructure":{"&deserializedvalue)":1}
,"&deserializedvalue)":{"{cachevalue":1}
,"{cachevalue":{"value":1}
,"=cachevalue":{"value.setvalue":1}
,"value.setvalue":{"(valueobject":1}
,":binaryvalue":{"(deserializedvalue.serializeasstring":1}
,"(deserializedvalue.serializeasstring":{"()))":1}
,"()))":{"std":1}
,":map":{"<std":1}
,"<std":{":string":1}
,"valueobject>":{"nvpairs":1}
,"nvpairs":{"nvpairs":1,"[key_name]":1}
,"[key_name]":{"=valueobject":1}
,"=valueobject":{":stringvalue":1}
,"(deserializedvalue.name":{"())":1}
,"())":{"value.setnvpairs":1,"{recipe.parsefromstring":1,"return":1}
,"value.setnvpairs":{"(nvpairs)":1}
,"(nvpairs)":{"return":1}
,"return":{"value":1,"recipe":1}
,"recipestructure":{"recipeprotobufserializer":1}
,":deserializevalue":{"(cachevalue":1}
,"(cachevalue":{"&serializedvalue)":1}
,"&serializedvalue)":{"{recipestructure":1}
,"{recipestructure":{"recipe":1}
,"recipe":{"=recipeproject":1}
,"=recipeproject":{":recipestructure":1}
,":recipestructure":{"(serializedvalue.isvalueset":1}
,"(serializedvalue.isvalueset":{"())":1}
,"{recipe.parsefromstring":{"(serializedvalue.getvalue":1}
,"(serializedvalue.getvalue":{".getbinary":1}
,".getbinary":{"())":1}
}
;Search.control.loadWordPairs(pairs);
