var pairs =
{
"overview":{"panel":1}
,"panel":{"overview":1,"displays":1}
,"displays":{"health":1,"long":1,"searches":1,"rollback":1,"transaction":1,"total":1}
,"health":{"metrics":1}
,"metrics":{"cachemanagers":1}
,"cachemanagers":{"caches":1,"real-time":1}
,"caches":{"including":1,"low":1,"transaction":1,"writer":1}
,"including":{"certain":1}
,"certain":{"cache":1}
,"cache":{"statistics":1,"hits":1,"(every":1,"hit":1,"shows":1,"misses":1,"searches":1,"puts":1,"high":1,"expired":1,"evicted":1}
,"statistics":{"help":1,"displayed":1,"choose":1,"(or":1,"sort":1}
,"help":{"track":1}
,"track":{"performance":1}
,"performance":{"resource":1}
,"resource":{"usage":1}
,"usage":{"across":1,"algorithm":1}
,"across":{"cachemanagers":1}
,"real-time":{"statistics":1}
,"displayed":{"table":1}
,"table":{"following":1,"click":1,"immediately":1,"specific":1}
,"following":{"columns":1}
,"columns":{"hit":1,"open":1}
,"hit":{"ratio-the":1,"rate":1}
,"ratio-the":{"ratio":1}
,"ratio":{"cache":1,"1.00":1,"(closer":1}
,"hits":{"attempts":1,"per":1,"relative":1,"(no":1,"available":1}
,"attempts":{"ratio":1}
,"1.00":{"means":1}
,"means":{"requested":1}
,"requested":{"data":1}
,"data":{"obtained":1,"outside":1,"size":1,"expiration":1}
,"obtained":{"cache":1}
,"(every":{"put":1}
,"put":{"hit)":1,"rate":1,"updates":1}
,"hit)":{"low":1}
,"low":{"ratio":1,"overall":1}
,"(closer":{"0.00)":1}
,"0.00)":{"implies":1}
,"implies":{"higher":1,"high":1}
,"higher":{"number":1}
,"number":{"misses":1,"cache":1,"hits":1,"puts":1,"updates":1,"elements":1,"writes":1}
,"misses":{"result":1,"local":1,"per":1,"(causing":1,"every":1}
,"result":{"faulting":1}
,"faulting":{"data":1}
,"outside":{"cache":1}
,"rate":{"-the":1,"(data":1,"local":1,"remove":1,"element":1,"rapidly":1,"(as":1}
,"-the":{"number":1,"fault":1,"rate":1,"average":1,"search-rate":1,"write-behind":1}
,"per":{"second":1}
,"second":{"effective":1,"executed":1,"number":1,"elements":1,"reaching":1,"cache":1}
,"effective":{"cache":1}
,"shows":{"high":1}
,"high":{"number":1,"eviction":1}
,"relative":{"misses":1}
,"local":{"disk":1,"disk)":1,"heap":1,"(in-heap)":1,"(off-heap)":1,"offheap":1,"memory":1}
,"disk":{"hit":1,"miss":1,"size":1,"local":1,"bytes":1}
,"fault":{"rate":1}
,"(data":{"faulted":1}
,"faulted":{"local":1,"remote":1}
,"disk)":{"local":1}
,"heap":{"hit":1,"miss":1,"size":1,"local":1,"bytes":1}
,"(in-heap)":{"hits":1,"misses":1}
,"(no":{"faulting)":1}
,"faulting)":{"offheap":1,"available":1}
,"offheap":{"hit":1,"miss":1,"size":1,"bytes":1}
,"(off-heap)":{"memory":1,"available":1}
,"memory":{"hits":1,"configured":1,"misses":1,"(off-heap)":1}
,"available":{"off-heap":1,"statistics":1}
,"off-heap":{"memory":1}
,"configured":{"miss":1,"size":1,"local":1,"average":1}
,"miss":{"rate":1,"leads":1}
,"remote":{"source)":1}
,"source)":{"local":1}
,"(causing":{"faulting)":1}
,"size":{"-overall":1,"(in":1,"limits":1}
,"-overall":{"data":1}
,"(in":{"entries)":1,"bytes)":1}
,"entries)":{"local":1}
,"bytes":{"-overall":1}
,"bytes)":{"local":1}
,"average":{"time":1,"search":1}
,"time":{"-the":1,"executing":1,"graph":1}
,"executing":{"operation":1}
,"operation":{"average":1,"takes":1}
,"search":{"time":1,"operation":1,"time)":1,"rate":1}
,"graph":{"displays":1,"indicates":1,"provides":1}
,"long":{"search":1,"searches":1}
,"takes":{"(as":1}
,"(as":{"current":1}
,"current":{"values":1,"value":1}
,"values":{"search":1,"rate)":1}
,"time)":{"graph":1,"searches":1}
,"indicates":{"quickly":1}
,"quickly":{"cache":1}
,"searches":{"performed":1,"taking":1,"executed":1,"per":1}
,"performed":{"notice":1}
,"notice":{"correlation":1}
,"correlation":{"long":1}
,"taking":{"(average":1}
,"(average":{"search":1}
,"executed":{"(search":1,"(as":1,"per":1}
,"(search":{"rate)":1}
,"rate)":{"search":1,"graph":1,"put":1,"transactional":1}
,"search-rate":{"graph":1}
,"provides":{"view":1}
,"view":{"cache":1}
,"puts":{"executed":1,"always":1,"efficient":1}
,"always":{"equals":1}
,"equals":{"exceeds":1}
,"exceeds":{"number":1}
,"every":{"miss":1}
,"leads":{"put":1}
,"updates":{"counted":1,"per":1,"implies":1}
,"counted":{"puts":1}
,"efficient":{"caches":1}
,"overall":{"put":1}
,"remove":{"rate":1}
,"element":{"eviction":1}
,"eviction":{"update":1,"rate":1}
,"update":{"rate":1}
,"elements":{"cache":1,"per":1,"automatically":1,"evicted":1,"expired":1}
,"rapidly":{"changing":1}
,"changing":{"data":1}
,"expiration":{"rate":1,"cache":1}
,"reaching":{"expiration":1}
,"expired":{"elements":1,"evicted":1}
,"automatically":{"evicted":1}
,"evicted":{"eviction":1,"per":1,"elements":1,"according":1}
,"according":{"usage":1}
,"algorithm":{"size":1}
,"limits":{"exceeded":1}
,"exceeded":{"transaction":1}
,"transaction":{"rollback":1,"api":1,"commit":1}
,"rollback":{"rate-a":1,"rate":1}
,"rate-a":{"java":1,"jta":1}
,"java":{"transaction":1}
,"api":{"(jta)":1}
,"(jta)":{"graph":1}
,"transactional":{"caches":1}
,"commit":{"rate-a":1,"rate":1}
,"jta":{"graph":1}
,"writer":{"queue":1}
,"queue":{"length":1,"queues":1}
,"length":{"-the":1}
,"write-behind":{"graph":1,"queue":1}
,"total":{"number":1}
,"writes":{"write-behind":1}
,"queues":{"(blue":1}
,"(blue":{"line)":1}
,"line)":{"current":1}
,"value":{"choose":1}
,"choose":{"types":1,"statistics":1}
,"types":{"statistics":1}
,"click":{"configure":1,"accept":1,"column":1}
,"configure":{"columns":1}
,"open":{"list":1}
,"list":{"available":1}
,"(or":{"option":1}
,"option":{"display":1}
,"display":{"statistics)":1,"chosen":1}
,"statistics)":{"click":1}
,"accept":{"change":1}
,"change":{"table":1}
,"immediately":{"begins":1}
,"begins":{"display":1}
,"chosen":{"statistics":1}
,"sort":{"table":1}
,"specific":{"statistic":1}
,"statistic":{"click":1}
,"column":{"head":1}
,"head":{"statistic":1}
}
;Search.control.loadWordPairs(pairs);
