var pairs =
{
"overview":{"maintenance":1}
,"maintenance":{"version":1}
,"version":{"upgrades":1,"4.2.x":1,"4.2":1,"client":1,"long":1,"third":1,"may":1}
,"upgrades":{"4.2":1,"using":1}
,"4.2":{"section":1,"cluster":1,"upgrade":1}
,"section":{"describes":1}
,"describes":{"upgrade":1}
,"upgrade":{"version":1,"installation":1,"versions":1,"rolling":1,"means":1,"node":1,"active":1,"support":1,"expected":1,"entire":1,"until":1}
,"4.2.x":{"4.2.y":1}
,"4.2.y":{"procedure":1}
,"procedure":{"assumes":1}
,"assumes":{"currently":1}
,"currently":{"running":1}
,"running":{"version":1,"client":1}
,"cluster":{"high":1,"without":1,"servers":1,"node":1,"downtime":1,"includes":1,"affected":1,"partially":1,"intended":1,"running":1}
,"high":{"availability":1}
,"availability":{"deployment":1}
,"deployment":{"configuration":1}
,"configuration":{"cluster":1}
,"without":{"mirror":1,"mirrors":1,"losing":1,"shutting":1}
,"mirror":{"servers":1,"server":1}
,"servers":{"downtime":1,"cannot":1,"clients":1,"(which":1,"run":1}
,"downtime":{"unavoidable":1,"cluster":1,"installing":1}
,"unavoidable":{"during":1}
,"during":{"upgrade":1}
,"installation":{"additionally":1}
,"additionally":{"cluster":1}
,"mirrors":{"non-persistent":1}
,"non-persistent":{"cluster":1}
,"cannot":{"upgraded":1}
,"upgraded":{"without":1,"mirror":1,"cluster":1}
,"losing":{"data":1}
,"data":{"starting":1,"perform":1}
,"starting":{"4.2":1}
,"versions":{"servers":1,"(e.g":1}
,"clients":{"cluster":1,"however":1,"4.2.0":1}
,"node":{"time":1,"install":1,"restart":1,"cluster":1}
,"time":{"without":1}
,"shutting":{"down":1}
,"down":{"cluster":1,"node":1}
,"includes":{"mirror":1}
,"(which":{"passive-standby":1}
,"passive-standby":{"state)":1}
,"state)":{"avoid":1}
,"avoid":{"cluster":1}
,"installing":{"upgrades":1}
,"using":{"rolling":1}
,"rolling":{"upgrade":1}
,"means":{"shut":1}
,"shut":{"down":1}
,"install":{"upgrade":1}
,"restart":{"node":1}
,"affected":{"rolling":1}
,"active":{"server":1}
,"server":{"instance":1,"continue":1,"different":1}
,"instance":{"upgraded":1,"operations":1}
,"operations":{"cluster":1}
,"perform":{"rolling":1}
,"client":{"server":1}
,"continue":{"running":1,"implement":1}
,"different":{"version":1,"first":1,"minor":1}
,"long":{"major\u002Fminor":1}
,"major\u002Fminor":{"version":1}
,"third":{"digit":1}
,"digit":{"version":1}
,"may":{"different":1}
,"first":{"two":1}
,"two":{"digits":1}
,"digits":{"(major\u002Fminor)":1}
,"(major\u002Fminor)":{"example":1}
,"example":{"4.2.1":1}
,"4.2.1":{"servers":1}
,"run":{"4.2.0":1}
,"4.2.0":{"clients":1,"servers)":1}
,"however":{"rolling":1}
,"support":{"provided":1}
,"provided":{"mix":1}
,"mix":{"different":1}
,"minor":{"versions":1}
,"(e.g":{"4.1.0":1}
,"4.1.0":{"clients":1}
,"servers)":{"perform":1}
,"expected":{"upgrade":1}
,"entire":{"cluster":1}
,"partially":{"upgraded":1}
,"intended":{"temporary":1}
,"temporary":{"state":1}
,"state":{"continue":1}
,"implement":{"rolling":1}
,"until":{"entire":1}
}
;Search.control.loadWordPairs(pairs);
