var pairs =
{
"introduction":{"brief":1}
,"brief":{"overview":1}
,"overview":{"terracotta":1,"bigmemory":1}
,"terracotta":{"security":1,"server":1,"clusters":1,"servers":1}
,"security":{"links":1,"instead":1,"infrastructure":1}
,"links":{"individual":1}
,"individual":{"topics":1}
,"topics":{"overview":1}
,"bigmemory":{"max":1}
,"max":{"security":1}
,"instead":{"using":1}
,"using":{"built-in":1}
,"built-in":{"user":1}
,"user":{"management":1}
,"management":{"system":1}
,"system":{"authentication":1}
,"authentication":{"authorization":1,"supported":1}
,"authorization":{"terracotta":1}
,"server":{"array":1}
,"array":{"(tsa)":1}
,"(tsa)":{"based":1}
,"based":{"lightweight":1}
,"lightweight":{"directory":1}
,"directory":{"access":1,"standard":1}
,"access":{"protocol":1,"terracotta":1}
,"protocol":{"(ldap)":1}
,"(ldap)":{"allows":1}
,"allows":{"existing":1}
,"existing":{"security":1}
,"infrastructure":{"controlling":1}
,"controlling":{"access":1}
,"clusters":{"two":1}
,"two":{"types":1}
,"types":{"ldap-based":1}
,"ldap-based":{"authentication":1}
,"supported":{"microsoft":1,"terracotta":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"standard":{"ldap":1}
,"ldap":{"addition":1,"used":1,"concepts":1}
,"addition":{"ldaps":1}
,"ldaps":{"(ldap":1}
,"(ldap":{"ssl)":1}
,"ssl)":{"supported":1}
,"servers":{"configured":1}
,"configured":{"ssl":1}
,"ssl":{"active":1}
,"used":{"topic":1}
,"topic":{"assumes":1}
,"assumes":{"reader":1}
,"reader":{"knowledge":1}
,"knowledge":{"standard":1}
,"concepts":{"usage":1}
}
;Search.control.loadWordPairs(pairs);
