var pairs =
{
"new":{"bigmemory":1,"format":1}
,"bigmemory":{"max":1,"hybrid\u0027s":1,"hybrid":1,"distributed":1}
,"max":{"4.x":1,"security":1,"administrator":1}
,"4.x":{"4.x":1,"tsa":1}
,"tsa":{"in-memory":1,"protects":1,"providing":1,"data":1,"longer":1}
,"in-memory":{"data":1}
,"data":{"platform":1,"resource":1,"memory":1,"eviction":1,"fast":1,"persistence":1,"matter":1,"storage":1,"stored":1,"tsa":1,"information":1,"time":1,"include":1,"access":1,"ready":1}
,"platform":{"providing":1,"monitoring":1}
,"providing":{"faster":1,"crash":1}
,"faster":{"consistent":1}
,"consistent":{"predictable":1,"record":1}
,"predictable":{"access":1,"eviction":1,"behavior":1}
,"access":{"data":1,"rejoin":1,"protocol":1}
,"resource":{"management":1}
,"management":{"data":1,"resource":1,"provides":1,"provide":1,"console":1,"monitoring":1}
,"memory":{"available":1,"becomes":1}
,"available":{"tsa":1,"protect":1}
,"protects":{"itself":1}
,"itself":{"going":1}
,"going":{"limit":1}
,"limit":{"data":1}
,"eviction":{"throttling":1,"strategy":1,"provide":1}
,"throttling":{"cases":1}
,"cases":{"recover":1}
,"recover":{"back":1}
,"back":{"normal":1}
,"normal":{"working":1}
,"working":{"state":1}
,"state":{"automatically":1}
,"automatically":{"addition":1,"ensure":1}
,"addition":{"four":1,"tsa":1}
,"four":{"systems":1}
,"systems":{"available":1}
,"protect":{"data":1}
,"fast":{"restart":1,"restartability":1}
,"restart":{"(frs)":1,"terracotta":1}
,"(frs)":{"feature":1}
,"feature":{"bigmemory":1,"integrated":1}
,"hybrid\u0027s":{"ssd\u002Fflash":1}
,"ssd\u002Fflash":{"active-mirror":1,"additional":1}
,"active-mirror":{"server":1}
,"server":{"groups":1,"array":1,"startup":1}
,"groups":{"backups":1,"multi-stripe":1}
,"backups":{"fast":1}
,"restartability":{"data":1,"provide":1}
,"persistence":{"bigmemory\u0027s":1}
,"bigmemory\u0027s":{"fast":1}
,"integrated":{"tsa":1,"platform":1}
,"crash":{"resilience":1}
,"resilience":{"quick":1}
,"quick":{"recovery":1}
,"recovery":{"plus":1,"near-memory-full":1}
,"plus":{"consistent":1,"simplified":1}
,"record":{"entire":1}
,"entire":{"in-memory":1}
,"matter":{"large":1}
,"large":{"information":1}
,"information":{"frs":1,"using":1,"automatic":1,"eviction":1,"start":1,"bigmemory":1}
,"frs":{"fast":1}
,"provide":{"correct":1,"continuous":1}
,"correct":{"link":1}
,"link":{"don":1,"hybrid":1,"resource":1,"predictable":1,"continuous":1}
,"don":{"added":1}
,"added":{"link":1,"reference":1}
,"hybrid":{"data":1,"extends":1,"mixture":1,"provide":1}
,"storage":{"bigmemory":1,"managed":1}
,"extends":{"bigmemory":1}
,"distributed":{"terracotta":1}
,"terracotta":{"server":1,"management":1,"deployments":1,"servers":1,"clients":1}
,"array":{"data":1}
,"stored":{"across":1}
,"across":{"hybrid":1}
,"mixture":{"ram":1}
,"ram":{"ssd\u002Fflash":1}
,"additional":{"storage":1,"rest":1,"security":1}
,"managed":{"in-memory":1}
,"using":{"bigmemory":1}
,"provides":{"better":1}
,"better":{"control":1,"utilization":1}
,"control":{"tsa\u0027s":1}
,"tsa\u0027s":{"in-memory":1,"3-pronged":1}
,"time":{"size":1}
,"size":{"count":1}
,"count":{"limitations":1}
,"limitations":{"enables":1,"tsa\u0027s":1}
,"enables":{"automatic":1}
,"automatic":{"handling":1,"resource":1}
,"handling":{"recovery":1}
,"near-memory-full":{"conditions":1}
,"conditions":{"information":1}
,"strategy":{"based":1,"works":1}
,"based":{"upon":1}
,"upon":{"user-configured":1}
,"user-configured":{"time":1}
,"3-pronged":{"eviction":1}
,"works":{"automatically":1}
,"ensure":{"predictable":1}
,"behavior":{"memory":1}
,"becomes":{"full":1}
,"full":{"information":1}
,"continuous":{"uptime":1,"availability":1}
,"uptime":{"improvements":1}
,"improvements":{"provide":1,"data":1}
,"availability":{"data":1}
,"include":{"flexibility":1}
,"flexibility":{"server":1}
,"startup":{"sequencing":1}
,"sequencing":{"better":1}
,"utilization":{"extra":1}
,"extra":{"mirrors":1}
,"mirrors":{"mirror":1}
,"mirror":{"groups":1}
,"multi-stripe":{"backup":1}
,"backup":{"capability":1}
,"capability":{"optimizations":1}
,"optimizations":{"bulk":1}
,"bulk":{"load":1}
,"load":{"performance":1}
,"performance":{"improvements":1}
,"rejoin":{"addition":1}
,"longer":{"uses":1}
,"uses":{"oracle":1}
,"oracle":{"berkeley":1}
,"berkeley":{"enabling":1}
,"enabling":{"in-memory":1}
,"ready":{"quickly":1}
,"quickly":{"planned":1}
,"planned":{"unplanned":1}
,"unplanned":{"restart":1}
,"console":{"(tmc)":1,"operations":1,"user\u0027s":1}
,"(tmc)":{"expanded":1}
,"expanded":{"tmc":1}
,"tmc":{"replaces":1}
,"replaces":{"developer":1}
,"developer":{"console":1}
,"operations":{"center":1}
,"center":{"integrated":1}
,"monitoring":{"managing":1,"information":1}
,"managing":{"administering":1}
,"administering":{"terracotta":1}
,"deployments":{"support":1}
,"support":{"additional":1,"terracotta":1}
,"rest":{"apis":1}
,"apis":{"management":1}
,"start":{"terracotta":1}
,"user\u0027s":{"guide":1}
,"guide":{"provide":1}
,"reference":{"additional":1,"dso":1}
,"security":{"features":1,"guide":1}
,"features":{"active":1}
,"active":{"directory":1}
,"directory":{"(ad)":1,"access":1}
,"(ad)":{"lightweight":1}
,"lightweight":{"directory":1}
,"protocol":{"(ldap)":1}
,"(ldap)":{"support":1}
,"servers":{"custom":1}
,"custom":{"secretprovider":1}
,"secretprovider":{"terracotta":1}
,"clients":{"information":1}
,"dso":{"plus":1,"configuration":1}
,"simplified":{"configuration":1}
,"configuration":{"dso":1,"deprecated":1}
,"deprecated":{"tc-config":1}
,"tc-config":{"new":1}
,"format":{"elements":1}
,"elements":{"structure":1}
,"structure":{"revised":1}
,"revised":{"information":1}
,"administrator":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
