var pairs =
{
"clause":{"default":1,"cachemanagers":1,"multiple":1}
,"default":{"querymanager":1}
,"querymanager":{"locates":1,"built":1,"=querymanagerbuilder.newquerymanagerbuilder":1}
,"locates":{"cache":1}
,"cache":{"name":1,"managers":1,"unique":1,"manager":1,"defined":1}
,"name":{"attached":1,"example":1,"address":1,"type=\u0022":1,"users.address":1,"person":1,"users":1,"\u002F\u002Fis":1,"detailed-address.address":1,"found":1,"exists":1}
,"attached":{"clause":1}
,"cachemanagers":{"specified":1,"two":1}
,"specified":{"querymanager":1,"clause":1}
,"built":{"[cache":1}
,"[cache":{"cachemanager.cache":1}
,"cachemanager.cache":{"multiple":1}
,"multiple":{"cachemanagers":1,"caches":1}
,"two":{"cache":1}
,"example":{"suppose":1}
,"suppose":{"addition":1}
,"addition":{"ehcache-users.xml":1}
,"ehcache-users.xml":{"configuration":1,"cachemanager":1}
,"configuration":{"(presented":1,"file":1}
,"(presented":{"using":1}
,"using":{"bigmemory":1}
,"bigmemory":{"sql)":1}
,"sql)":{"configuration":1}
,"file":{"called":1}
,"called":{"ehcache-address.xml":1}
,"ehcache-address.xml":{"provides":1,"\u002F\u002Fneeded":1,"cachemanager":1}
,"provides":{"detailed":1}
,"detailed":{"address":1}
,"address":{"information":1,"present":1,"<searchable>":1,"prefix":1,"cache":1}
,"information":{"<ehcache":1}
,"<ehcache":{"name=\u0022":1}
,"name=\u0022":{"detailed-address":1,"address":1,"name":1,"street":1,"apartment":1,"city":1,"zip":1}
,"detailed-address":{"<!--another":1,"query":1}
,"<!--another":{"cache":1}
,"present":{"ehcache-users.xml-->":1}
,"ehcache-users.xml-->":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"<searchable>":{"<searchattribute":1}
,"<searchattribute":{"name=\u0022":1}
,"type=\u0022":{"string":1,"int":1}
,"string":{"expression=\u0022":1}
,"expression=\u0022":{"value.getname":1,"value.getstreet":1,"value.getapartment":1,"value.getcity":1,"value.getzip":1}
,"value.getname":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<searchattribute":1,"<\u002Fsearchable>":1}
,"street":{"type=\u0022":1}
,"value.getstreet":{"\u0022\u002F>":1}
,"apartment":{"type=\u0022":1}
,"value.getapartment":{"\u0022\u002F>":1}
,"city":{"type=\u0022":1}
,"value.getcity":{"\u0022\u002F>":1}
,"zip":{"type=\u0022":1,"=94115":1}
,"int":{"expression=\u0022":1}
,"value.getzip":{"\u0022\u002F>":1}
,"<\u002Fsearchable>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"cache":1}
,"prefix":{"cachemanager":1}
,"cachemanager":{"name":1,"userscachemanager":1,"ehcache-users.xml":1,"addresscachemanager":1,"ehcache-address.xml":1,"specified":1}
,"users.address":{"detailed-address.address":1,"zip":1}
,"detailed-address.address":{"\u002F\u002Fget":1,"zip":1}
,"\u002F\u002Fget":{"cache":1,"results":1}
,"managers":{"cachemanager":1}
,"userscachemanager":{"=new":1}
,"=new":{"cachemanager":1}
,"addresscachemanager":{"=new":1}
,"\u002F\u002Fneeded":{"once":1}
,"once":{"querymanager":1}
,"=querymanagerbuilder.newquerymanagerbuilder":{".addallcahcescurrentlyin":1}
,".addallcahcescurrentlyin":{"(users":1}
,"(users":{"detailed-address)":1}
,"detailed-address)":{".build":1}
,".build":{"\u002F\u002F**default":1}
,"\u002F\u002F**default":{"case":1}
,"case":{"\u002F\u002Fsince":1,"\u002F\u002Fsearch":1}
,"\u002F\u002Fsince":{"person":1}
,"person":{"cache":1,"age":1}
,"unique":{"don\u0027t":1}
,"don\u0027t":{"need":1}
,"need":{"supply":1}
,"supply":{"cache":1}
,"manager":{"query":1}
,"query":{"namequery1":1,"namequery2":1,"namequery3":1}
,"namequery1":{"=qm.createquery":1}
,"=qm.createquery":{"select":1}
,"select":{"name":1}
,"age":{"\u002F\u002F**explicit":1}
,"\u002F\u002F**explicit":{"scoping":1}
,"scoping":{"case":1}
,"\u002F\u002Fsearch":{"address":1}
,"defined":{"ehcache-users.xml":1,"ehcache-address.xml":1}
,"users":{"query":1}
,"namequery2":{"=qm.createquery":1}
,"=94115":{"\u002F\u002F**explicit":1,"\u002F\u002Fget":1}
,"\u002F\u002Fis":{"detailed-address":1}
,"namequery3":{"=qm.createquery":1}
,"results":{"results":1,"allnamesinuserrecordsover21":1,"allnamesinuserrecordsin94115":1,"allnamesinaddressbookin94115":1,"cachemanager":1}
,"allnamesinuserrecordsover21":{"=namequery1.end":1}
,"=namequery1.end":{".execute":1}
,".execute":{"results":1,"\u002F\u002Fiterate":1}
,"allnamesinuserrecordsin94115":{"=namequery2.end":1}
,"=namequery2.end":{".execute":1}
,"allnamesinaddressbookin94115":{"=namequery3.end":1}
,"=namequery3.end":{".execute":1}
,"\u002F\u002Fiterate":{"results":1}
,"caches":{"name":1}
,"found":{"exception":1}
,"exception":{"thrown":1}
,"thrown":{"message":1}
,"message":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
