var pairs =
{
"\u002Ftc:tc-config\u002Fservers\u002Fserver\u002Fsecurity\u002Fmanagement":{"element":1}
,"element":{"contains":1}
,"contains":{"subelements":1}
,"subelements":{"needed":1}
,"needed":{"allow":1}
,"allow":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"server":1}
,"server":{"(tms)":1,"tms":1,"match":1,"hostname":1}
,"(tms)":{"secure":1}
,"secure":{"connection":1}
,"connection":{"tsa":1}
,"tsa":{"https":1}
,"https":{"url":1}
,"url":{"domain":1}
,"domain":{"tms":1}
,"tms":{"followed":1,"hostname":1}
,"followed":{"port":1}
,"port":{"9443":1}
,"9443":{"path":1}
,"path":{"\u002Ftmc\u002Fapi\u002Fassertidentity":1}
,"\u002Ftmc\u002Fapi\u002Fassertidentity":{"timeout":1}
,"timeout":{"timeout":1,"value":1}
,"value":{"(in":1}
,"(in":{"milliseconds)":1}
,"milliseconds)":{"connections":1}
,"connections":{"server":1}
,"hostname":{"used":1,"server":1}
,"used":{"dns":1,"certificate":1}
,"dns":{"hostname":1,"address":1}
,"match":{"server":1}
,"certificate":{"mismatch":1}
,"mismatch":{"enter":1}
,"enter":{"dns":1}
,"address":{"server":1}
}
;Search.control.loadWordPairs(pairs);
