var pairs =
{
"optional":{"configuration":1}
,"configuration":{"attributes":1,"installation":1,"guide":1,"nonstop":1}
,"attributes":{"terracotta":1,"described":1,"add":1}
,"terracotta":{"web":1,"server":1,"servers":1}
,"web":{"sessions":1}
,"sessions":{"designed":1,"application":1,"enable":1,"gives":1}
,"designed":{"optimum":1}
,"optimum":{"performance":1}
,"performance":{"configuration":1,"enable":1,"added":1,"hashing":1}
,"installation":{"cases":1}
,"cases":{"may":1}
,"may":{"necessary":1,"exceed":1,"applied":1,"create":1}
,"necessary":{"configuration":1}
,"described":{"following":1}
,"following":{"sections":1,"information":1}
,"sections":{"session":1}
,"session":{"locking":1}
,"locking":{"default":1,"terracotta":1,"enable":1,"add":1,"deadlocks":1,"enabled":1,"operation":1}
,"default":{"session":1}
,"application":{"requires":1,"waits":1}
,"requires":{"disabling":1}
,"disabling":{"concurrent":1}
,"concurrent":{"requests":1}
,"requests":{"sessions":1}
,"enable":{"session":1,"synchronous":1}
,"add":{"<init-param>":1}
,"<init-param>":{"block":1,"<param-name>":1,"blocks":1}
,"block":{"follows":1,"web.xml":1}
,"follows":{"<filter>":1}
,"<filter>":{"<filter-name>":1}
,"<filter-name>":{"terracotta-filter":1}
,"terracotta-filter":{"<\u002Ffilter-name>":1}
,"<\u002Ffilter-name>":{"<filter-class>":1}
,"<filter-class>":{"org.terracotta.session.terracottacontainerspecificsessionfilter":1}
,"org.terracotta.session.terracottacontainerspecificsessionfilter":{"<\u002Ffilter-class>":1}
,"<\u002Ffilter-class>":{"<init-param>":1}
,"<param-name>":{"tcconfigurl":1,"sessionlocking":1,"synchronouswrite":1,"maxbytesonheap":1,"maxbytesoffheap":1,"nonstoptimeout":1,"concurrency":1}
,"tcconfigurl":{"<\u002Fparam-name>":1}
,"<\u002Fparam-name>":{"<param-value>":1}
,"<param-value>":{"localhost:9510":1,"true":1,"128m":1,"<\u002Fparam-value>":1,"30000":1,"256":1}
,"localhost:9510":{"<\u002Fparam-value>":1}
,"<\u002Fparam-value>":{"<\u002Finit-param>":1}
,"<\u002Finit-param>":{"<init-param>":1,"<\u002Ffilter>":1}
,"sessionlocking":{"<\u002Fparam-name>":1}
,"true":{"<\u002Fparam-value>":1}
,"<\u002Ffilter>":{"enable":1,"sizing":1,"nonstop":1,"tuning":1}
,"deadlocks":{"session":1}
,"enabled":{"common":1}
,"common":{"issues":1}
,"issues":{"synchronous":1}
,"synchronous":{"writes":1,"write":1}
,"writes":{"synchronous":1,"add":1}
,"write":{"locks":1,"lock":1}
,"locks":{"provide":1,"substantially":1}
,"provide":{"extra":1}
,"extra":{"layer":1}
,"layer":{"data":1}
,"data":{"protection":1,"off-heap":1,"provides":1,"required":1,"used":1,"sets":1,"segments":1}
,"protection":{"having":1}
,"having":{"client":1}
,"client":{"node":1,"releases":1}
,"node":{"wait":1,"disconnected":1}
,"wait":{"until":1}
,"until":{"receives":1}
,"receives":{"acknowledgement":1}
,"acknowledgement":{"terracotta":1,"note":1}
,"server":{"array":1,"store":1,"map":1}
,"array":{"changes":1,"concurrency":1,"contains":1,"require":1,"(or":1,"optimally":1}
,"changes":{"committed":1}
,"committed":{"client":1}
,"releases":{"write":1}
,"lock":{"receiving":1,"trigger":1,"couldn\u0027t":1,"contention":1}
,"receiving":{"acknowledgement":1}
,"note":{"enabling":1,"nonstop":1}
,"enabling":{"synchronous":1}
,"substantially":{"raise":1}
,"raise":{"latency":1}
,"latency":{"rates":1}
,"rates":{"thus":1}
,"thus":{"degrading":1}
,"degrading":{"cluster":1}
,"cluster":{"performance":1,"clients":1,"offline":1,"segmented":1}
,"synchronouswrite":{"<\u002Fparam-name>":1}
,"sizing":{"options":1,"attributes":1}
,"options":{"web":1,"nonstop":1}
,"gives":{"option":1}
,"option":{"configure":1}
,"configure":{"heap":1,"tune":1}
,"heap":{"off-heap":1}
,"off-heap":{"memory":1,"store":1,"information":1}
,"memory":{"tiers":1,"store":1,"holds":1,"configuring":1}
,"tiers":{"memory":1,"bigmemory":1}
,"store":{"-heap":1,"subject":1,"-limited":1,"serialized":1,"using":1,"managed":1}
,"-heap":{"memory":1}
,"holds":{"copy":1}
,"copy":{"hottest":1}
,"hottest":{"subset":1}
,"subset":{"data":1}
,"subject":{"java":1}
,"java":{"garbage":1,"store":1}
,"garbage":{"collection":1}
,"collection":{"(gc)":1}
,"(gc)":{"off-heap":1}
,"-limited":{"size":1}
,"size":{"available":1}
,"available":{"ram":1}
,"ram":{"subject":1}
,"serialized":{"data":1}
,"provides":{"overflow":1,"additional":1}
,"overflow":{"capacity":1}
,"capacity":{"memory":1}
,"using":{"off-heap":1}
,"information":{"allocating":1,"provides":1}
,"allocating":{"direct":1}
,"direct":{"memory":1}
,"configuring":{"storage":1}
,"storage":{"tiers":1}
,"bigmemory":{"max":1}
,"max":{"configuration":1}
,"guide":{"sizing":1}
,"blocks":{"web.xml":1}
,"web.xml":{"follows":1}
,"maxbytesonheap":{"<\u002Fparam-name>":1}
,"128m":{"<\u002Fparam-value>":1}
,"maxbytesoffheap":{"<\u002Fparam-name>":1}
,"nonstop":{"rejoin":1,"timeout":1,"allows":1,"mode":1,"cache":1,"configuration":1}
,"rejoin":{"options":1}
,"timeout":{"number":1,"allotted":1,"add":1,"tune":1,"value":1,"waiting":1,"less":1,"avoids":1,"multiplier":1}
,"number":{"milliseconds":1,"segments":1,"active":1,"expected":1}
,"milliseconds":{"application":1}
,"waits":{"cache":1}
,"cache":{"operation":1,"nonstop":1,"operations":1,"employs":1,"elements":1}
,"operation":{"return":1,"unable":1,"may":1}
,"return":{"timing":1,"data":1}
,"timing":{"nonstop":1}
,"allows":{"certain":1,"number":1}
,"certain":{"operations":1}
,"operations":{"proceed":1,"slow":1}
,"proceed":{"clients":1}
,"clients":{"become":1,"nonstop":1,"cluster":1}
,"become":{"disconnected":1}
,"disconnected":{"cluster":1,"cache":1}
,"mode":{"receive":1,"even":1,"lock":1}
,"receive":{"cluster":1}
,"offline":{"event":1}
,"event":{"note":1}
,"even":{"node":1}
,"unable":{"complete":1}
,"complete":{"within":1}
,"within":{"timeout":1}
,"allotted":{"nonstop":1}
,"nonstoptimeout":{"<\u002Fparam-name>":1,"value":1}
,"30000":{"<\u002Fparam-value>":1}
,"tuning":{"nonstop":1,"concurrency":1,"explicit":1}
,"tune":{"timeout":1,"concurrency":1}
,"value":{"fit":1,"environment":1,"prevent":1,"configure":1,"optimized":1,"concurrency":1,"too-low":1,"cause":1,"may":1,"general":1,"less":1,"improve":1,"close":1}
,"fit":{"environment":1}
,"environment":{"following":1,"regular":1,"cache":1}
,"additional":{"guidance":1}
,"guidance":{"choosing":1}
,"choosing":{"nonstoptimeout":1,"concurrency":1}
,"regular":{"network":1}
,"network":{"interruptions":1}
,"interruptions":{"consider":1,"environment":1}
,"consider":{"increasing":1}
,"increasing":{"timeout":1}
,"prevent":{"timeouts":1,"frequent":1}
,"timeouts":{"interruptions":1,"example":1}
,"slow":{"return":1}
,"required":{"always":1}
,"always":{"sync":1}
,"sync":{"increase":1}
,"increase":{"timeout":1}
,"frequent":{"timeouts":1}
,"example":{"locking":1}
,"exceed":{"nonstop":1}
,"waiting":{"lock":1}
,"trigger":{"nonstop":1}
,"couldn\u0027t":{"acquired":1}
,"acquired":{"time":1}
,"time":{"setting":1}
,"setting":{"method\u0027s":1}
,"method\u0027s":{"timeout":1}
,"less":{"nonstop":1,"number":1}
,"avoids":{"problem":1}
,"problem":{"nonstop":1}
,"employs":{"bulk":1}
,"bulk":{"loading":1}
,"loading":{"aware":1}
,"aware":{"timeout":1}
,"multiplier":{"may":1}
,"applied":{"bulk-loading":1}
,"bulk-loading":{"method":1}
,"method":{"concurrency":1}
,"concurrency":{"concurrency":1,"attribute":1,"explicitly":1,"add":1,"<\u002Fparam-name>":1,"server":1,"circumstances":1,"value":1}
,"attribute":{"allows":1,"making":1}
,"segments":{"map":1,"terracotta":1,"holding":1,"reduces":1}
,"map":{"backing":1,"underlying":1}
,"backing":{"underlying":1}
,"underlying":{"server":1,"terracotta":1}
,"managed":{"terracotta":1}
,"explicitly":{"(or":1}
,"(or":{"system":1,"segments":1}
,"system":{"selects":1}
,"selects":{"optimized":1}
,"optimized":{"value":1,"terracotta":1}
,"256":{"<\u002Fparam-value>":1}
,"contains":{"data":1}
,"used":{"clients":1}
,"segmented":{"improve":1}
,"improve":{"performance":1}
,"added":{"concurrency":1}
,"circumstances":{"concurrency":1}
,"require":{"tuning":1}
,"explicit":{"fixed":1}
,"fixed":{"segmentation":1}
,"segmentation":{"value":1}
,"making":{"sure":1}
,"sure":{"appropriate":1}
,"appropriate":{"concurrency":1}
,"too-low":{"concurrency":1}
,"cause":{"unexpected":1}
,"unexpected":{"eviction":1}
,"eviction":{"elements":1}
,"elements":{"too-high":1,"concurrency":1}
,"too-high":{"concurrency":1}
,"create":{"empty":1}
,"empty":{"segments":1}
,"holding":{"few":1}
,"few":{"just":1,"cache":1}
,"just":{"element)":1}
,"element)":{"following":1}
,"general":{"concurrency":1}
,"active":{"servers":1,"terracotta":1}
,"servers":{"terracotta":1,"extremely":1}
,"optimally":{"least":1}
,"least":{"twice":1}
,"twice":{"number":1}
,"extremely":{"large":1}
,"large":{"data":1}
,"sets":{"high":1}
,"high":{"concurrency":1}
,"hashing":{"data":1}
,"reduces":{"lock":1}
,"contention":{"environments":1}
,"environments":{"few":1}
,"close":{"number":1}
,"expected":{"elements":1}
}
;Search.control.loadWordPairs(pairs);
