var pairs =
{
"installing":{"session":1}
,"session":{"jars":1}
,"jars":{"download":1}
,"download":{"terracotta":1,"bigmemory":1,"terracotta-license.key":1}
,"terracotta":{"web":1,"distribution":1,"client":1}
,"web":{"sessions":1,"application":1}
,"sessions":{"download":1,"unpack":1,"add":1,"jar":1}
,"bigmemory":{"max":1}
,"max":{"kit":1}
,"kit":{"includes":1,"unpack":1}
,"includes":{"terracotta":1}
,"unpack":{"kit":1,"distribution":1}
,"distribution":{"directory":1}
,"directory":{"system":1,"<terracotta>\u002F":1,"paths":1,"file":1}
,"system":{"following":1}
,"following":{"instructions":1,"two":1}
,"instructions":{"refer":1}
,"refer":{"directory":1}
,"<terracotta>\u002F":{"forward":1}
,"forward":{"slashes":1}
,"slashes":{"(\u0022\u002F\u0022)":1,"(\u0022\u005C\u0022)":1}
,"(\u0022\u002F\u0022)":{"given":1}
,"given":{"directory":1}
,"paths":{"substitute":1}
,"substitute":{"back":1}
,"back":{"slashes":1}
,"(\u0022\u005C\u0022)":{"microsoft":1}
,"microsoft":{"windows":1}
,"windows":{"installations":1}
,"installations":{"copy":1}
,"copy":{"license":1}
,"license":{"key":1}
,"key":{"copy":1,"terracotta":1}
,"file":{"called":1}
,"called":{"terracotta-license.key":1}
,"terracotta-license.key":{"attached":1,"<terracotta>\u002Fcopy":1}
,"attached":{"email":1}
,"email":{"received":1}
,"received":{"registering":1}
,"registering":{"download":1}
,"<terracotta>\u002Fcopy":{"jar":1}
,"jar":{"files":1,"apis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-<version>":1,"contains":1}
,"files":{"cluster":1,"application\u0027s":1,"web-inf\u002Flib":1,"${terracotta_home}\u002F":1}
,"cluster":{"application\u0027s":1}
,"application\u0027s":{"web":1,"classpath":1}
,"add":{"following":1}
,"two":{"jar":1}
,"classpath":{"place":1}
,"place":{"files":1}
,"web-inf\u002Flib":{"folder":1}
,"folder":{"web":1}
,"application":{"archive":1,"servers":1}
,"archive":{"(war)":1}
,"(war)":{"application":1}
,"servers":{"files":1}
,"${terracotta_home}\u002F":{"sessions\u002Flib\u002Fweb-sessions-<version>":1}
,"sessions\u002Flib\u002Fweb-sessions-<version>":{".jar":1}
,".jar":{"<version>":1,"particular":1}
,"<version>":{"current":1}
,"current":{"version":1}
,"version":{"terracotta":1}
,"apis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-<version>":{".jar":1}
,"particular":{"jar":1}
,"contains":{"terracotta":1}
,"client":{"libraries":1}
}
;Search.control.loadWordPairs(pairs);
