var pairs =
{
"security":{"rest":1,"headers":1,"project":1}
,"rest":{"api":1}
,"api":{"usage":1,"two":1}
,"usage":{"without":1}
,"without":{"tmc":1}
,"tmc":{"issuing":1}
,"issuing":{"http":1}
,"http":{"requests":1,"headers":1}
,"requests":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"every":1}
,"every":{"request":1}
,"request":{"include":1,"tms":1}
,"include":{"two":1}
,"two":{"security":1,"http":1}
,"headers":{"owasp_csrftoken":1,"required":1}
,"owasp_csrftoken":{"x-requested-with":1,"dynamic":1,"m9di-bumd-2ppk-c45i-t6qm-ztbe-wkkk-yt8m":1}
,"x-requested-with":{"value":1,"static":1,"owasp":1}
,"value":{"owasp_csrftoken":1,"x-requested-with":1}
,"dynamic":{"found":1}
,"found":{"header":1}
,"header":{"response":1}
,"response":{"tms":1,"received":1}
,"tms":{"value":1,"rest":1,"information":1}
,"static":{"always":1}
,"always":{"equal":1}
,"equal":{"owasp":1}
,"owasp":{"csrfguard":1}
,"csrfguard":{"project":1}
,"project":{"doing":1,"example":1,"refer":1,"site":1}
,"doing":{"post":1}
,"post":{"delete":1}
,"delete":{"put":1,"http:\u002F\u002Flocalhost:9889\u002Ftc-management-api\u002Fv2\u002Fagents":1}
,"put":{"request":1}
,"required":{"example":1}
,"example":{"delete":1,"above":1}
,"http:\u002F\u002Flocalhost:9889\u002Ftc-management-api\u002Fv2\u002Fagents":{"id=client01\u002Fcachemanagers":1}
,"id=client01\u002Fcachemanagers":{"names=foo\u002Fcaches":1}
,"names=foo\u002Fcaches":{"names=bar\u002Felements":1}
,"names=bar\u002Felements":{"owasp_csrftoken":1}
,"m9di-bumd-2ppk-c45i-t6qm-ztbe-wkkk-yt8m":{"x-requested-with":1,"latest":1}
,"above":{"owasp_csrftoken":1}
,"latest":{"response":1}
,"received":{"tms":1}
,"information":{"csrfguard":1}
,"refer":{"open":1}
,"open":{"web":1}
,"web":{"application":1}
,"application":{"security":1}
}
;Search.control.loadWordPairs(pairs);
