var pairs =
{
"configuring":{"web":1}
,"web":{"sessions":1}
,"sessions":{"cluster":1}
,"cluster":{"terracotta":1,"configured":1}
,"terracotta":{"servers":1,"clients":1,"configuration":1,"clustering":1,"<\u002Ffilter-name>":1,"filter":1}
,"servers":{"terracotta":1,"cluster":1,"started":1}
,"clients":{"running":1,"configuration":1}
,"running":{"application":1}
,"application":{"servers":1,"specify":1,"server":1}
,"configured":{"terracotta":1}
,"configuration":{"file":1,"default":1,"add":1,"including":1,"snippet":1,"source":1,"-->":1}
,"file":{"tc-config.xml":1,"add":1}
,"tc-config.xml":{"default":1,"terracotta":1}
,"default":{"servers":1,"configuration":1}
,"started":{"specified":1}
,"specified":{"configuration":1}
,"add":{"terracotta":1,"following":1}
,"clustering":{"application":1}
,"specify":{"terracotta":1}
,"including":{"source":1}
,"source":{"web.xml":1,"changes":1}
,"web.xml":{"file":1,"<filter>":1,"filters":1,"\u002Fweb-inf":1}
,"following":{"configuration":1,"init-params":1,"table":1}
,"snippet":{"web.xml":1}
,"<filter>":{"<filter-name>":1,"element":1}
,"<filter-name>":{"terracotta":1,"contain":1}
,"<\u002Ffilter-name>":{"<!--the":1,"<url-pattern>\u002F*<\u002Furl-pattern>":1}
,"<!--the":{"filter":1,"following":1}
,"filter":{"class":1,"name":1,"first":1,"may":1}
,"class":{"specific":1}
,"specific":{"application":1}
,"server":{"-->":1}
,"-->":{"<filter-class>":1,"<param-value>":1,"<\u002Ffilter>":1,"<filter-name>":1,"<dispatcher>":1}
,"<filter-class>":{"org.terracotta.session":1,"following":1,"glassfish":1}
,"org.terracotta.session":{"{container-specific-class}":1}
,"{container-specific-class}":{"<\u002Ffilter-class>":1}
,"<\u002Ffilter-class>":{"<init-param>":1}
,"<init-param>":{"<param-name>":1}
,"<param-name>":{"tcconfigurl":1,"synchronouswrite":1,"sessionlocking":1,"maxbytesonheap":1,"maxbytesoffheap":1,"rejoin":1,"nonstoptimeout":1,"concurrency":1}
,"tcconfigurl":{"<\u002Fparam-name>":1,"<param-value>":1}
,"<\u002Fparam-name>":{"<!--<init-param>":1,"<param-value>":1,"<param-value>-1":1}
,"<!--<init-param>":{"type":1}
,"type":{"tcconfigurl":1}
,"<param-value>":{"element":1,"localhost:9510":1,"false":1,"128m":1,"<\u002Fparam-value>":1}
,"element":{"containing":1,"listed":1}
,"containing":{"url":1}
,"url":{"filepath":1}
,"filepath":{"(for":1}
,"(for":{"example":1}
,"example":{"\u002Flib\u002Ftc-config.xml)":1}
,"\u002Flib\u002Ftc-config.xml)":{"tc-config.xml":1}
,"changes":{"later":1}
,"later":{"time":1}
,"time":{"updated":1}
,"updated":{"configuration":1}
,"localhost:9510":{"<\u002Fparam-value>":1}
,"<\u002Fparam-value>":{"<\u002Finit-param>":1}
,"<\u002Finit-param>":{"<!--the":1,"<init-param>":1,"<!--end":1}
,"init-params":{"optional":1,"-->":1}
,"optional":{"<init-param>":1,"init-params":1}
,"synchronouswrite":{"<\u002Fparam-name>":1}
,"false":{"<\u002Fparam-value>":1}
,"sessionlocking":{"<\u002Fparam-name>":1}
,"maxbytesonheap":{"<\u002Fparam-name>":1}
,"128m":{"<\u002Fparam-value>":1}
,"maxbytesoffheap":{"<\u002Fparam-name>":1}
,"rejoin":{"<\u002Fparam-name>":1}
,"nonstoptimeout":{"<\u002Fparam-name>":1}
,"<param-value>-1":{"<\u002Fparam-value>":1}
,"concurrency":{"<\u002Fparam-name>":1}
,"<!--end":{"optional":1}
,"<\u002Ffilter>":{"<filter-mapping>":1}
,"<filter-mapping>":{"<!--must":1}
,"<!--must":{"match":1}
,"match":{"filter":1,"<filter-mapping>\u002F<filter-name>":1}
,"name":{"above":1}
,"above":{"-->":1}
,"<url-pattern>\u002F*<\u002Furl-pattern>":{"<!--enable":1}
,"<!--enable":{"available":1}
,"available":{"dispatchers":1}
,"dispatchers":{"-->":1}
,"<dispatcher>":{"error":1,"include":1,"forward":1,"request":1}
,"error":{"<\u002Fdispatcher>":1}
,"<\u002Fdispatcher>":{"<dispatcher>":1,"<\u002Ffilter-mapping>":1}
,"include":{"<\u002Fdispatcher>":1}
,"forward":{"<\u002Fdispatcher>":1}
,"request":{"<\u002Fdispatcher>":1}
,"<\u002Ffilter-mapping>":{"<filter-name>":1}
,"contain":{"string":1}
,"string":{"choice":1}
,"choice":{"however":1}
,"however":{"value":1}
,"value":{"<filter>\u002F<filter-name>":1,"<filter-class>":1}
,"<filter>\u002F<filter-name>":{"match":1}
,"<filter-mapping>\u002F<filter-name>":{"choose":1}
,"choose":{"appropriate":1}
,"appropriate":{"value":1}
,"table":{"container":1}
,"container":{"value":1}
,"glassfish":{"org.terracotta.session.terracottaglassfish31xsessionfilter":1}
,"org.terracotta.session.terracottaglassfish31xsessionfilter":{"jboss":1}
,"jboss":{"6.1.x":1,"7.1.x":1,"7.2.x":1}
,"6.1.x":{"org.terracotta.session.terracottajboss61xsessionfilter":1}
,"org.terracotta.session.terracottajboss61xsessionfilter":{"jboss":1}
,"7.1.x":{"org.terracotta.session.terracottajboss71xsessionfilter":1}
,"org.terracotta.session.terracottajboss71xsessionfilter":{"jboss":1}
,"7.2.x":{"org.terracotta.session.terracottajboss72xsessionfilter":1}
,"org.terracotta.session.terracottajboss72xsessionfilter":{"jetty":1}
,"jetty":{"8.1.x":1,"9.0.x":1}
,"8.1.x":{"org.terracotta.session.terracottajetty81xsessionfilter":1}
,"org.terracotta.session.terracottajetty81xsessionfilter":{"jetty":1}
,"9.0.x":{"org.terracotta.session.terracottajetty90xsessionfilter":1}
,"org.terracotta.session.terracottajetty90xsessionfilter":{"resin":1}
,"resin":{"org.terracotta.session.terracottaresin40xsessionfilter":1}
,"org.terracotta.session.terracottaresin40xsessionfilter":{"tomcat":1}
,"tomcat":{"6.0.x":1,"7.0.x":1}
,"6.0.x":{"org.terracotta.session.terracottatomcat60xsessionfilter":1}
,"org.terracotta.session.terracottatomcat60xsessionfilter":{"tomcat":1}
,"7.0.x":{"org.terracotta.session.terracottatomcat70xsessionfilter":1,"org.terracotta.session.terracottawebsphere70xsessionfilter":1}
,"org.terracotta.session.terracottatomcat70xsessionfilter":{"weblogic":1}
,"weblogic":{"10.3.x":1,"12.1.x":1}
,"10.3.x":{"org.terracotta.session.terracottaweblogic103xsessionfilter":1}
,"org.terracotta.session.terracottaweblogic103xsessionfilter":{"weblogic":1}
,"12.1.x":{"org.terracotta.session.terracottaweblogic121xsessionfilter":1}
,"org.terracotta.session.terracottaweblogic121xsessionfilter":{"websphere":1}
,"websphere":{"7.0.x":1,"8.0.x":1,"8.5.x":1}
,"org.terracotta.session.terracottawebsphere70xsessionfilter":{"websphere":1}
,"8.0.x":{"org.terracotta.session.terracottawebsphere80xsessionfilter":1}
,"org.terracotta.session.terracottawebsphere80xsessionfilter":{"websphere":1}
,"8.5.x":{"org.terracotta.session.terracottawebsphere85xsessionfilter":1}
,"org.terracotta.session.terracottawebsphere85xsessionfilter":{"ensure":1}
,"ensure":{"terracotta":1}
,"first":{"<filter>":1}
,"listed":{"web.xml":1}
,"filters":{"processed":1}
,"processed":{"ahead":1}
,"ahead":{"terracotta":1}
,"may":{"disrupt":1}
,"disrupt":{"processing":1}
,"processing":{"web.xml":1}
,"\u002Fweb-inf":{"using":1}
,"using":{"war":1}
,"war":{"file":1}
}
;Search.control.loadWordPairs(pairs);
