var pairs =
{
"using":{"query":1,"show":1}
,"query":{"parameters":1,"returns":1}
,"parameters":{"uris":1,"executed":1,"haswritebehindwriter":1}
,"uris":{"head":1}
,"head":{"http":1}
,"http":{"operations":1}
,"operations":{"execute":1}
,"execute":{"queries":1}
,"queries":{"specific":1}
,"specific":{"resources":1}
,"resources":{"query":1}
,"executed":{"using":1}
,"show":{"parameter":1}
,"parameter":{"\u002Fagents":1}
,"\u002Fagents":{"ids={comma_sep_agent_ids}]\u002Fcachemanagers":1,"ids=foo\u002Fcachemanagers":1}
,"ids={comma_sep_agent_ids}]\u002Fcachemanagers":{"names=\u00A0":1}
,"names=\u00A0":{"{comma_sep_cache_manager_names}]\u002Fcaches":1}
,"{comma_sep_cache_manager_names}]\u002Fcaches":{"names={comma_sep_cache_names}":1}
,"names={comma_sep_cache_names}":{"show=[parameter]&show=[parameter]":1}
,"show=[parameter]&show=[parameter]":{"example":1}
,"example":{"retrieve":1}
,"retrieve":{"values":1}
,"values":{"parameters":1}
,"haswritebehindwriter":{"maxbyteslocaldiskasstring":1,":true":1}
,"maxbyteslocaldiskasstring":{"cachemanager":1,"300m":1}
,"cachemanager":{"cm1":1}
,"cm1":{"ehcache":1,"attributes":1}
,"ehcache":{"foo":1}
,"foo":{"following":1}
,"following":{"\u002Fagents":1,"[{\u0022":1}
,"ids=foo\u002Fcachemanagers":{"names=cm1":1}
,"names=cm1":{"show=haswritebehindwriter":1}
,"show=haswritebehindwriter":{"show=maxbyteslocaldiskasstring":1}
,"show=maxbyteslocaldiskasstring":{"query":1}
,"returns":{"json":1}
,"json":{"object":1}
,"object":{"similar":1}
,"similar":{"following":1}
,"[{\u0022":{"name":1}
,"name":{"cm1":1}
,"attributes":{"haswritebehindwriter":1}
,":true":{"maxbyteslocaldiskasstring":1}
,"300m":{"guid":1}
,"guid":{"95d40b093c9f44389f3cc122fbe1c30b":1}
,"95d40b093c9f44389f3cc122fbe1c30b":{"agentid":1}
,"agentid":{"embedded":1}
,"embedded":{"version":1}
,"version":{"1.0.0":1}
,"1.0.0":{"\u0022}]":1}
}
;Search.control.loadWordPairs(pairs);
