var pairs =
{
"viewing":{"example":1}
,"example":{"shopping":1}
,"shopping":{"cart":1}
,"cart":{"sample":1,"once":1,"look":1}
,"sample":{"starts":1,"application":1,"running":1}
,"starts":{"two":1}
,"two":{"instances":1}
,"instances":{"jetty":1,"started":1}
,"jetty":{"connected":1,"instances":1,"loads":1}
,"connected":{"terracotta":1}
,"terracotta":{"server":1,"store":1}
,"server":{"access":1,"view":1}
,"access":{"shared":1}
,"shared":{"session":1}
,"session":{"data":1,"read":1,"displayed":1}
,"data":{"sample":1,"scalable":1,"jetty":1}
,"application":{"uses":1,"server":1,"visiting":1,"select":1}
,"uses":{"terracotta":1}
,"store":{"session":1}
,"scalable":{"high":1}
,"high":{"availability":1}
,"availability":{"session":1}
,"read":{"application":1}
,"view":{"cart":1,"sample":1}
,"once":{"jetty":1}
,"started":{"view":1}
,"visiting":{"following":1}
,"following":{"links":1}
,"links":{"http:\u002F\u002Flocalhost:9081\u002Fcart":1,"work":1}
,"http:\u002F\u002Flocalhost:9081\u002Fcart":{"http:\u002F\u002Flocalhost:9082\u002Fcart":1}
,"http:\u002F\u002Flocalhost:9082\u002Fcart":{"links":1}
,"work":{"unless":1}
,"unless":{"sample":1}
,"running":{"create":1}
,"create":{"session":1}
,"loads":{"sample":1}
,"select":{"item":1}
,"item":{"place":1,"stored":1}
,"place":{"cart":1}
,"look":{"something":1}
,"something":{"browser":1}
,"browser":{"notice":1}
,"notice":{"item":1}
,"stored":{"session":1}
,"displayed":{"page":1}
}
;Search.control.loadWordPairs(pairs);
