var pairs =
{
"json":{"schema":1,"objects":1}
,"schema":{"schema":1,"guide":1,"subject":1,"following":1}
,"guide":{"parsing":1}
,"parsing":{"json":1}
,"objects":{"returned":1}
,"returned":{"rest":1}
,"rest":{"api":1}
,"api":{"validate":1,"versions":1,"uris":1}
,"validate":{"structure":1}
,"structure":{"data":1}
,"data":{"scripts":1}
,"scripts":{"ria":1}
,"ria":{"sends":1}
,"sends":{"agents":1}
,"agents":{"note":1}
,"note":{"schema":1}
,"subject":{"change":1}
,"change":{"api":1}
,"versions":{"rest":1}
,"uris":{"examples":1}
,"examples":{"json":1}
,"following":{"cachemanager":1}
,"cachemanager":{"cache":1}
,"cache":{"cacheconfig":1}
,"cacheconfig":{"cachestatisticssample":1}
}
;Search.control.loadWordPairs(pairs);
