var pairs =
{
"rest":{"api":1,"agents":1}
,"api":{"versions":1,"includes":1,"agent":1,"access":1,"include":1,"available":1,"version":1,"differences":1}
,"versions":{"rest":1,"original":1,"affect":1,"older":1,"cause":1}
,"includes":{"two":1}
,"two":{"versions":1}
,"original":{"version":1,"may":1,"api":1,"rest":1}
,"version":{"version":1,"(v2)":1,"previously":1,"bigmemory":1,"\u002Fv2\u002Fagents\u002Fcachemanagers\u002F\u2014":1,"available":1,"avoid":1,"connected":1,"unrelated":1,"terracotta":1,"mismatches":1,"exposing":1}
,"(v2)":{"original":1}
,"previously":{"version":1}
,"bigmemory":{"4.2":1,"nodes":1}
,"4.2":{"higher":1}
,"higher":{"either":1,"rest":1,"continues":1}
,"either":{"original":1}
,"may":{"used":1,"able":1}
,"used":{"\u002Fagents\u002Fcachemanagers\u002F\u2014":1}
,"\u002Fagents\u002Fcachemanagers\u002F\u2014":{"original":1}
,"\u002Fv2\u002Fagents\u002Fcachemanagers\u002F\u2014":{"version":1}
,"available":{"terracotta":1,"bigmemory":1,"capabilities":1}
,"terracotta":{"4.2":1,"products":1,"api":1}
,"agent":{"resources":1,"api":1}
,"resources":{"accessible":1}
,"accessible":{"via":1}
,"via":{"path":1}
,"path":{"methods":1,"example":1}
,"methods":{"return":1}
,"return":{"responses":1}
,"responses":{"vary":1}
,"vary":{"content":1}
,"content":{"and\u002For":1}
,"and\u002For":{"format":1}
,"format":{"original":1}
,"access":{"rest":1}
,"include":{"part":1}
,"part":{"path":1}
,"example":{"http:\u002F\u002F<host>":1}
,"http:\u002F\u002F<host>":{"<port>\u002Ftmc\u002Fapi\u002Fv2":1,"<port>\u002Ftc-management-api\u002Fv2":1}
,"<port>\u002Ftmc\u002Fapi\u002Fv2":{"http:\u002F\u002F<host>":1}
,"<port>\u002Ftc-management-api\u002Fv2":{"original":1}
,"continues":{"perform":1}
,"perform":{"pre-4.2":1}
,"pre-4.2":{"bigmemory":1}
,"nodes":{"rest":1,"tms":1}
,"avoid":{"risk":1}
,"risk":{"issues":1}
,"issues":{"due":1}
,"due":{"differing":1}
,"differing":{"features":1}
,"features":{"capabilities":1,"functionality":1}
,"capabilities":{"discover":1,"newer":1}
,"discover":{"api":1}
,"connected":{"rest":1}
,"agents":{"using":1,"api":1}
,"using":{"operation":1,"external":1}
,"operation":{"\u002Fagents\u002Finfo":1}
,"\u002Fagents\u002Finfo":{"uri":1}
,"uri":{"(see":1}
,"(see":{"head)":1}
,"head)":{"note":1}
,"note":{"rest":1}
,"unrelated":{"version":1}
,"products":{"terracotta":1}
,"differences":{"rest":1,"apis":1}
,"affect":{"features":1}
,"functionality":{"offered":1,"differences":1}
,"offered":{"monitoring":1}
,"monitoring":{"tools":1}
,"tools":{"create":1}
,"create":{"time":1}
,"time":{"version":1}
,"mismatches":{"arise":1}
,"arise":{"tms":1}
,"tms":{"tsa":1,"standalone":1,"may":1,"unable":1}
,"tsa":{"(when":1}
,"(when":{"using":1}
,"external":{"tms)":1}
,"tms)":{"tms":1}
,"standalone":{"nodes":1}
,"able":{"compensate":1}
,"compensate":{"agents":1}
,"older":{"version":1}
,"exposing":{"available":1}
,"newer":{"agent":1}
,"cause":{"inconsistent":1}
,"inconsistent":{"behavior":1}
,"behavior":{"malfunction":1}
,"malfunction":{"tms":1}
,"unable":{"handle":1}
,"handle":{"unfamiliar":1}
,"unfamiliar":{"schema":1}
,"schema":{"functionality":1}
}
;Search.control.loadWordPairs(pairs);
