var pairs =
{
"welcome":{"web":1}
,"web":{"sessions":1,"architecture":1,"framework":1}
,"sessions":{"4.3":1,"web":1,"scalability":1,"works":1}
,"4.3":{"online":1}
,"online":{"documentation":1}
,"documentation":{"library":1,"web":1}
,"library":{"library":1,"contains":1}
,"contains":{"product":1}
,"product":{"documentation":1}
,"scalability":{"benefits":1}
,"benefits":{"stateless":1}
,"stateless":{"web":1}
,"architecture":{"without":1}
,"without":{"overloading":1}
,"overloading":{"database":1}
,"database":{"rewriting":1}
,"rewriting":{"application":1}
,"application":{"supporting":1,"container":1}
,"supporting":{"java":1}
,"java":{"servlet":1}
,"servlet":{"session":1}
,"session":{"standard":1,"objects":1}
,"standard":{"terracotta":1}
,"terracotta":{"web":1}
,"works":{"favorite":1}
,"favorite":{"web":1,"application":1}
,"framework":{"favorite":1}
,"container":{"custom":1}
,"custom":{"session":1}
}
;Search.control.loadWordPairs(pairs);
