var pairs =
{
"architecture":{"following":1,"typical":1}
,"following":{"diagram":1}
,"diagram":{"shows":1}
,"shows":{"architecture":1}
,"typical":{"terracotta-enabled":1}
,"terracotta-enabled":{"web":1}
,"web":{"application":1,"sessions":1}
,"application":{"load":1,"server":1,"application":1,"servers":1,"terracotta":1}
,"load":{"balancer":1,"information":1}
,"balancer":{"parcels":1,"uses":1}
,"parcels":{"http":1}
,"http":{"requests":1,"session":1}
,"requests":{"internet":1,"corresponding":1}
,"internet":{"application":1}
,"server":{"maximize":1,"however":1,"process":1}
,"maximize":{"locality":1}
,"locality":{"reference":1}
,"reference":{"clustered":1}
,"clustered":{"http":1}
,"session":{"data":1,"affinity":1,"routed":1}
,"data":{"load":1}
,"uses":{"http":1}
,"affinity":{"requests":1}
,"corresponding":{"http":1}
,"routed":{"application":1}
,"however":{"terracotta-enabled":1}
,"process":{"request":1}
,"request":{"terracotta":1}
,"terracotta":{"web":1,"client":1,"cluster":1,"clusters":1}
,"sessions":{"clusters":1,"allowing":1,"survive":1}
,"clusters":{"sessions":1,"refer":1}
,"allowing":{"sessions":1}
,"survive":{"node":1}
,"node":{"hops":1}
,"hops":{"failures":1}
,"failures":{"application":1}
,"servers":{"run":1,"may":1}
,"run":{"web":1}
,"client":{"software":1}
,"software":{"called":1}
,"called":{"clients":1}
,"clients":{"terracotta":1}
,"cluster":{"application":1}
,"may":{"deployed":1}
,"deployed":{"needed":1}
,"needed":{"handle":1}
,"handle":{"site":1}
,"site":{"load":1}
,"information":{"terracotta":1}
,"refer":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
