var pairs =
{
"starting":{"example":1,"sample":1}
,"example":{"we\u0027ll":1,"start":1}
,"we\u0027ll":{"cart":1}
,"cart":{"sample":1}
,"sample":{"sessions":1,"application":1,"bin\u002Fstart-sample.sh":1}
,"sessions":{"samples":1,"starting":1,"unpack":1}
,"samples":{"directory":1}
,"directory":{"terracotta":1,"start":1}
,"terracotta":{"distribution":1,"web":1,"server":1}
,"distribution":{"demonstrate":1,"directory":1}
,"demonstrate":{"clustered":1}
,"clustered":{"web":1}
,"web":{"sessions":1}
,"application":{"sure":1}
,"sure":{"performed":1}
,"performed":{"following":1}
,"following":{"steps":1}
,"steps":{"described":1}
,"described":{"installing":1}
,"installing":{"session":1}
,"session":{"jars":1}
,"jars":{"download":1}
,"download":{"terracotta":1}
,"unpack":{"kit":1}
,"kit":{"copy":1}
,"copy":{"license":1}
,"license":{"key":1}
,"key":{"distribution":1}
,"start":{"example":1,"terracotta":1,"sample":1}
,"server":{"<terracotta>\u002Fsessions\u002Fcode-samples\u002Fcart":1}
,"<terracotta>\u002Fsessions\u002Fcode-samples\u002Fcart":{"bin\u002Fstart-sample-server.sh":1}
,"bin\u002Fstart-sample-server.sh":{"start":1}
}
;Search.control.loadWordPairs(pairs);
