var pairs =
{
"operator":{"events":1}
,"events":{"return":1,"using":1,"last":1,"certain":1,"bigmemory":1}
,"return":{"operator":1}
,"using":{"uri":1}
,"uri":{"extension":1}
,"extension":{"\u002Fagents\u002Foperatorevents":1}
,"\u002Fagents\u002Foperatorevents":{"\u002Fv2\u002Fagents\u002Foperatorevents":1,"sincewhen=10m":1,"sincewhen=10m&eventlevels=error":1}
,"\u002Fv2\u002Fagents\u002Foperatorevents":{"limit":1,"eventlevels=error":1,"eventtypes=topology.node.joined":1}
,"limit":{"size":1,"events":1}
,"size":{"returned":1}
,"returned":{"data":1}
,"data":{"sincewhen":1}
,"sincewhen":{"query":1}
,"query":{"operator":1}
,"last":{"ten":1}
,"ten":{"minutes":1}
,"minutes":{"\u002Fagents\u002Foperatorevents":1}
,"sincewhen=10m":{"filter":1}
,"filter":{"event":1}
,"event":{"levels":1,"types":1}
,"levels":{"add":1,"debug":1}
,"add":{"eventlevels":1,"eventtypes":1}
,"eventlevels":{"\u002Fv2\u002Fagents\u002Foperatorevents":1}
,"eventlevels=error":{"warn":1}
,"warn":{"available":1,"error":1}
,"available":{"event":1}
,"debug":{"info":1}
,"info":{"warn":1}
,"error":{"critical":1}
,"critical":{"limit":1}
,"certain":{"types":1}
,"types":{"add":1,"monitoring":1}
,"eventtypes":{"\u002Fv2\u002Fagents\u002Foperatorevents":1}
,"eventtypes=topology.node.joined":{"topology.node.left":1}
,"topology.node.left":{"resource.capacity.near":1}
,"resource.capacity.near":{"event":1}
,"monitoring":{"cluster":1}
,"cluster":{"events":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
,"guide":{"parameters":1}
,"parameters":{"combined":1}
,"combined":{"example":1}
,"example":{"\u002Fagents\u002Foperatorevents":1}
,"sincewhen=10m&eventlevels=error":{"warn":1}
}
;Search.control.loadWordPairs(pairs);
