var pairs =
{
"overview":{"panel":1}
,"panel":{"master":1,"displays":1,"top":1,"select":1}
,"master":{"caches":1,"cache":1,"cache\u0027s":1,"orchestrator":1,"replica":1}
,"caches":{"overview":1,"replicated":1,"want":1,"expand":1}
,"displays":{"information":1,"click":1}
,"information":{"performance":1,"provided":1,"overview":1,"wan\u0027s":1,"master":1}
,"performance":{"statistics":1}
,"statistics":{"caches":1,"displayed":1,"descriptions":1,"wan":1}
,"replicated":{"remote":1,"replicas":1}
,"remote":{"data":1}
,"data":{"centers":1}
,"centers":{"wide-area-network":1}
,"wide-area-network":{"(wan)":1}
,"(wan)":{"information":1}
,"provided":{"orchestrators":1}
,"orchestrators":{"performing":1,"view":1}
,"performing":{"replication":1}
,"replication":{"view":1,"mode":1,"conflict":1}
,"view":{"master":1,"click":1,"information":1,"synchronization":1}
,"cache":{"information":1,"column":1,"master":1,"name":1,"(available":1,"complete":1}
,"top":{"overview":1}
,"select":{"cachemanager":1,"(or":1}
,"cachemanager":{"master":1}
,"want":{"view":1}
,"click":{"masters":1,"address":1,"topology":1,"configure":1,"either":1}
,"masters":{"following":1}
,"following":{"columns":1}
,"columns":{"displayed":1,"pop-up":1}
,"displayed":{"default":1,"click":1}
,"default":{"master":1,"replica":1,"statistics":1}
,"column":{"description":1}
,"description":{"cache":1,"replica":1}
,"name":{"orchestrator":1,"following":1}
,"orchestrator":{"address":1,"process":1,"topology":1,"immediate":1}
,"address":{"(the":1,"link":1,"(hostname":1}
,"(the":{"hostname":1}
,"hostname":{"communication":1}
,"communication":{"port)":1}
,"port)":{"master":1,"replica":1}
,"cache\u0027s":{"orchestrator":1,"replication":1,"replica":1,"synchronization":1}
,"process":{"display":1}
,"display":{"orchestrator\u0027s":1}
,"orchestrator\u0027s":{"xml":1}
,"xml":{"configuration":1}
,"configuration":{"click":1}
,"link":{"view":1}
,"wan\u0027s":{"orchestrator":1}
,"topology":{"click":1,"example":1}
,"example":{"linux-001.net:9001":1}
,"linux-001.net:9001":{"linux-002.net:9001":1}
,"linux-002.net:9001":{"replication":1}
,"mode":{"master":1,"(unidirectional":1}
,"(unidirectional":{"bidirectional)":1}
,"bidirectional)":{"conflict":1}
,"conflict":{"count":1,"table":1,"simply":1}
,"count":{"number":1,"inbound":1,"total":1}
,"number":{"conflicts":1,"element":1,"higher":1,"transactions":1}
,"conflicts":{"resolved":1}
,"resolved":{"during":1}
,"during":{"replication":1}
,"table":{"size":1}
,"size":{"number":1,"size":1,"cluster":1}
,"element":{"modification":1}
,"modification":{"entries":1}
,"entries":{"(puts\u002Fupdates\u002Fdeletes)":1,"may":1}
,"(puts\u002Fupdates\u002Fdeletes)":{"currently":1}
,"currently":{"outstanding":1}
,"outstanding":{"entries":1}
,"may":{"may":1,"conflict":1}
,"simply":{"means":1}
,"means":{"replicated":1}
,"replicas":{"wan":1}
,"wan":{"number":1,"tab":1}
,"higher":{"conflict":1}
,"inbound":{"buffer":1}
,"buffer":{"size":1,"processing":1}
,"cluster":{"listener":1}
,"listener":{"buffer":1}
,"processing":{"rate":1}
,"rate":{"min.)":1,"average":1}
,"min.)":{"average":1}
,"average":{"processed":1,"synchronization":1,"transactions":1}
,"processed":{"transactions":1,"transaction":1}
,"transactions":{"per":1,"entire":1}
,"per":{"second":1}
,"second":{"(tps)":1,"last":1}
,"(tps)":{"one-minute":1,"entire":1}
,"one-minute":{"period":1}
,"period":{"processed":1}
,"transaction":{"recorded":1}
,"recorded":{"master":1}
,"immediate":{"eventual":1}
,"eventual":{"transmission":1}
,"transmission":{"replica":1}
,"replica":{"orchestrators":1,"caches":1,"cache":1,"replica":1,"orchestrator":1,"status":1,"cache\u0027s":1,"select":1}
,"synchronization":{"information":1,"master":1,"transactions":1,"interval":1}
,"expand":{"master":1}
,"(hostname":{"communication":1}
,"status":{"connection":1,"replica":1,"indicates":1}
,"connection":{"status":1}
,"(available":{"unavailable)":1}
,"unavailable)":{"sync":1}
,"sync":{"status":1,"rate":1,"mean":1,"count":1}
,"indicates":{"whether":1}
,"whether":{"replica":1}
,"complete":{"running":1}
,"running":{"sync":1}
,"last":{"minute":1}
,"minute":{"sync":1}
,"mean":{"rate":1}
,"entire":{"synchronization":1}
,"interval":{"sync":1,"change":1}
,"total":{"number":1}
,"change":{"default":1}
,"configure":{"columns":1}
,"pop-up":{"displays":1}
,"either":{"master":1}
,"(or":{"all)":1}
,"all)":{"statistics":1}
,"descriptions":{"statistics":1}
,"tab":{"statistics":1}
}
;Search.control.loadWordPairs(pairs);
