var pairs =
{
"using":{"tc-maven":1}
,"tc-maven":{"plugin":1}
,"plugin":{"<<this":1,"simplify":1,"supplies":1,"add":1,"goal":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"tc-maven":1}
,"simplify":{"process":1}
,"process":{"integrating":1}
,"integrating":{"testing":1}
,"testing":{"terracotta":1}
,"terracotta":{"products":1,"servers":1,"4.3.0)":1,"server":1,"developer":1,"data":1}
,"products":{"assets":1}
,"assets":{"plugin":1}
,"supplies":{"number":1}
,"number":{"useful":1}
,"useful":{"tasks":1}
,"tasks":{"including":1}
,"including":{"starting":1}
,"starting":{"stopping":1}
,"stopping":{"pausing":1}
,"pausing":{"terracotta":1}
,"servers":{"integrate":1,"started":1}
,"integrate":{"plugin":1}
,"add":{"following":1}
,"following":{"project\u0027s":1,"abbreviated":1}
,"project\u0027s":{"pom":1}
,"pom":{"(version":1}
,"(version":{"shown":1}
,"shown":{"terracotta":1}
,"4.3.0)":{"<plugin>":1}
,"<plugin>":{"<groupid>":1}
,"<groupid>":{"org.terracotta.maven.plugins":1}
,"org.terracotta.maven.plugins":{"<\u002Fgroupid>":1}
,"<\u002Fgroupid>":{"<artifactid>":1}
,"<artifactid>":{"tc-maven-plugin":1}
,"tc-maven-plugin":{"<\u002Fartifactid>":1}
,"<\u002Fartifactid>":{"<version>":1}
,"<version>":{"2.0.0":1}
,"2.0.0":{"<\u002Fversion>":1}
,"<\u002Fversion>":{"<\u002Fplugin>":1}
,"<\u002Fplugin>":{"following":1}
,"abbreviated":{"list":1}
,"list":{"goals":1}
,"goals":{"available":1}
,"available":{"tc-maven":1}
,"goal":{"function":1}
,"function":{"tc:help":1}
,"tc:help":{"print":1}
,"print":{"help":1,"detailed":1}
,"help":{"tc:start":1}
,"tc:start":{"start":1}
,"start":{"terracotta":1,"multiple":1}
,"server":{"tc:stop":1,"tc:restart":1,"tc:dev-console":1,"client":1}
,"tc:stop":{"stop":1}
,"stop":{"terracotta":1,"web":1}
,"tc:restart":{"restart":1}
,"restart":{"terracotta":1}
,"tc:dev-console":{"start":1}
,"developer":{"console":1}
,"console":{"tc:run":1}
,"tc:run":{"start":1,"execute":1}
,"multiple":{"terracotta":1}
,"client":{"processes":1}
,"processes":{"tc:clean":1}
,"tc:clean":{"clean":1}
,"clean":{"terracotta":1}
,"data":{"logs":1}
,"logs":{"directories":1}
,"directories":{"tc:terminate":1}
,"tc:terminate":{"stop":1}
,"web":{"servers":1}
,"started":{"tc:run":1}
,"execute":{"tc:help":1}
,"detailed":{"information":1}
,"information":{"goals":1}
}
;Search.control.loadWordPairs(pairs);
