var pairs =
{
"management":{"panel":1}
,"panel":{"management":1,"displays":1,"list":1}
,"displays":{"table":1}
,"table":{"listing":1,"node":1,"cache":1,"caches":1,"following":1,"nodes":1}
,"listing":{"information":1,"expanded":1}
,"information":{"selected":1}
,"selected":{"cachemanager":1,"cache":1}
,"cachemanager":{"node":1,"exists)":1,"cachemanager":1,"list":1}
,"node":{"(where":1,"list":1,"view":1,"click":1,"clicking":1,"cache":1,"wipe":1,"listing":1}
,"(where":{"cachemanager":1}
,"exists)":{"caches":1}
,"caches":{"choose":1,"radio":1,"selected":1,"disabled":1,"indicates":1}
,"choose":{"cachemanagers":1}
,"cachemanagers":{"radio":1}
,"radio":{"button":1}
,"button":{"show":1,"clearing":1,"cache":1}
,"show":{"table":1}
,"list":{"caches":1,"tables":1,"cache":1,"table":1,"cachemanager":1}
,"cache":{"list":1,"disable\u002Fenable":1,"cache":1,"manager":1,"-the":1,"enabled":1,"cluster":1,"instances":1,"distributed":1,"click":1,"wipe":1,"using":1,"button":1,"listing":1,"name":1,"table":1,"node":1,"disabled":1,"pinned":1,"data":1,"example":1,"bulk-load":1,"element":1,"view":1}
,"tables":{"(and":1}
,"(and":{"sublist":1}
,"sublist":{"tables)":1,"appears":1}
,"tables)":{"sorted":1}
,"sorted":{"ordered":1}
,"ordered":{"column":1}
,"column":{"clicking":1,"head":1}
,"clicking":{"column":1,"disable":1}
,"head":{"global":1}
,"global":{"cache":1}
,"disable\u002Fenable":{"controls":1}
,"controls":{"top":1}
,"top":{"panel":1}
,"manager":{"table":1}
,"following":{"columns":1,"parameters":1}
,"columns":{"cache":1,"address":1}
,"-the":{"name":1,"connection":1,"total":1}
,"name":{"cache":1,"sublist":1,"node":1}
,"enabled":{"-shows":1,"total":1,"-indicates":1,"node":1}
,"-shows":{"instances":1}
,"instances":{"cache":1,"cluster":1,"once":1}
,"total":{"number":1}
,"number":{"instances":1,"elements":1}
,"cluster":{"clicking":1,"caches":1,"sure":1}
,"disable":{"disables":1,"cache":1,"button":1}
,"disables":{"(stops)":1}
,"(stops)":{"instances":1,"cache":1}
,"disabled":{"control":1}
,"control":{"becomes":1}
,"becomes":{"enable":1}
,"enable":{"enable":1,"operations":1}
,"operations":{"cache":1}
,"once":{"terracotta":1}
,"terracotta":{"clustered":1,"consistency":1}
,"clustered":{"-shows":1,"caches":1}
,"distributed":{"element":1}
,"element":{"count-shows":1,"count-the":1,"count":1}
,"count-shows":{"total":1}
,"elements":{"instances":1,"cache":1}
,"click":{"clear":1,"view":1,"edit":1}
,"clear":{"cache":1}
,"wipe":{"data":1}
,"data":{"instances":1,"pinned":1,"stored":1,"cache":1}
,"sure":{"disable":1}
,"using":{"disable":1,"arrow":1}
,"clearing":{"clear":1}
,"expanded":{"using":1}
,"arrow":{"left":1}
,"left":{"cache":1,"connection":1}
,"appears":{"table":1}
,"nodes":{"contain":1,"selected":1}
,"contain":{"cache":1}
,"address":{"-the":1}
,"connection":{"name":1}
,"view":{"cache\u0027s":1,"config":1,"cachemanager\u0027s":1}
,"cache\u0027s":{"configuration":1,"data":1}
,"configuration":{"node":1,"click":1}
,"config":{"click":1,"open":1}
,"edit":{"config":1,"values":1}
,"open":{"dialog":1}
,"dialog":{"edit":1}
,"values":{"following":1,"read":1}
,"parameters":{"(depending":1,"present)":1,"depending":1,"present":1}
,"(depending":{"upon":1}
,"upon":{"settings":1}
,"settings":{"subset":1}
,"subset":{"parameters":1}
,"present)":{"maxentriesincache":1}
,"maxentriesincache":{"maxentrieslocalheap":1}
,"maxentrieslocalheap":{"maxbyteslocalheap":1}
,"maxbyteslocalheap":{"timetoidleseconds":1}
,"timetoidleseconds":{"timetoliveseconds":1}
,"timetoliveseconds":{"terracotta":1,"enabled":1}
,"consistency":{"-for":1,"eventual":1,"uses":1}
,"-for":{"clustered":1}
,"indicates":{"whether":1,"least":1}
,"whether":{"consistency":1,"cache":1}
,"eventual":{"(default)":1,"consistency":1}
,"(default)":{"strong":1}
,"strong":{"eventual":1,"consistency":1}
,"uses":{"cache-level":1,"locks":1}
,"cache-level":{"locks":1}
,"locks":{"superior":1,"prevent":1}
,"superior":{"performance":1}
,"performance":{"allowing":1,"setting":1}
,"allowing":{"short":1}
,"short":{"window":1}
,"window":{"stale":1}
,"stale":{"values":1,"reads":1}
,"read":{"strong":1}
,"prevent":{"stale":1}
,"reads":{"high":1}
,"high":{"cost":1}
,"cost":{"performance":1}
,"setting":{"dynamic":1}
,"dynamic":{"enabled":1}
,"-indicates":{"whether":1,"cache":1,"eviction":1}
,"pinned":{"-indicates":1,"local":1,"(na)":1}
,"local":{"memory":1}
,"memory":{"(localmemory)":1}
,"(localmemory)":{"anywhere":1}
,"anywhere":{"cache\u0027s":1}
,"stored":{"(incache)":1}
,"(incache)":{"pinned":1}
,"(na)":{"eviction":1}
,"eviction":{"policy":1}
,"policy":{"-indicates":1,"used":1,"effect":1}
,"used":{"evicting":1,"policy":1}
,"evicting":{"entries":1}
,"entries":{"cache":1}
,"example":{"lru":1}
,"lru":{"indicates":1}
,"least":{"recently":1}
,"recently":{"used":1}
,"effect":{"mode":1}
,"mode":{"-indicates":1,"applications":1,"temporarily":1}
,"bulk-load":{"normal":1,"mode":1}
,"normal":{"operating":1}
,"operating":{"mode":1}
,"applications":{"cache":1}
,"temporarily":{"warming":1}
,"warming":{"cache":1}
,"count-the":{"total":1}
,"cachemanager\u0027s":{"configuration":1}
,"depending":{"upon":1}
,"present":{"maxentriesincache":1}
,"count":{"-the":1}
}
;Search.control.loadWordPairs(pairs);
