var pairs =
{
"integrating":{"nagios":1}
,"nagios":{"monitor":1,"monitoring":1,"plugin":1}
,"monitor":{"terracotta":1}
,"terracotta":{"nodes":1,"management":1}
,"nodes":{"using":1}
,"using":{"nagios":1}
,"monitoring":{"solution":1}
,"solution":{"-see":1}
,"-see":{"http:\u002F\u002Fwww.nagios.com\u002F":1}
,"http:\u002F\u002Fwww.nagios.com\u002F":{"create":1}
,"create":{"nagios":1}
,"plugin":{"nagios":1,"query":1}
,"query":{"terracotta":1}
,"management":{"server":1,"rest":1}
,"server":{"(tms)":1}
,"(tms)":{"information":1}
,"information":{"tms":1,"rest":1}
,"tms":{"rest":1}
,"rest":{"interface":1,"developer":1}
,"interface":{"directly":1,"information":1,"terracotta":1}
,"directly":{"node\u0027s":1}
,"node\u0027s":{"rest":1}
,"developer":{"guide":1,"guidelines":1}
,"guide":{"plugins":1}
,"plugins":{"written":1}
,"written":{"variety":1}
,"variety":{"languages":1}
,"languages":{"follow":1}
,"follow":{"developer":1}
,"guidelines":{"published":1}
,"published":{"http:\u002F\u002Fnagiosplug.sourceforge.net\u002Fdeveloper-guidelines.html":1}
}
;Search.control.loadWordPairs(pairs);
