var pairs =
{
"tmc":{"home":1,"panel":1,"connection":1,"functionality":1,"default":1}
,"home":{"page":1,"icon":1}
,"page":{"home":1,"provides":1,"comprised":1,"add":1,"clicking":1,"click":1,"provide":1,"navigating":1,"return":1}
,"provides":{"overview":1}
,"overview":{"terracotta":1}
,"terracotta":{"servers":1}
,"servers":{"clients":1}
,"clients":{"buttons":1,"appearing":1,"enter":1,"want":1}
,"buttons":{"drop-down":1}
,"drop-down":{"menus":1,"menu":1}
,"menus":{"allow":1,"within":1,"filter":1}
,"allow":{"navigate":1}
,"navigate":{"directly":1,"tmc":1}
,"directly":{"tmc":1}
,"panel":{"view":1}
,"view":{"home":1,"connections":1,"tmc":1,"connection":1,"using":1}
,"comprised":{"connection":1}
,"connection":{"panes":1,"group":1,"pane":1,"top":1,"details":1,"name":1,"alternatively":1}
,"panes":{"cluster":1}
,"cluster":{"connection":1}
,"group":{"recognized":1}
,"recognized":{"tmc":1}
,"pane":{"shows":1,"select":1,"active":1,"click":1,"return":1}
,"shows":{"status":1}
,"status":{"connection\u0027s":1}
,"connection\u0027s":{"server":1,"client":1}
,"server":{"(s)":1}
,"(s)":{"lists":1,"direct":1}
,"lists":{"connection\u0027s":1}
,"client":{"(s)":1,"list":1}
,"direct":{"access":1}
,"access":{"tmc":1}
,"functionality":{"view":1}
,"connections":{"first":1,"appear":1,"global":1}
,"first":{"view":1}
,"default":{"connections":1}
,"appear":{"additional":1,"home":1}
,"additional":{"connections":1,"information":1}
,"add":{"either":1}
,"either":{"clicking":1}
,"clicking":{"create":1,"settings":1,"home":1}
,"create":{"new":1}
,"new":{"connection":1}
,"top":{"page":1,"toolbar":1}
,"settings":{"top":1,"view":1}
,"toolbar":{"information":1,"click":1}
,"information":{"refer":1,"example":1}
,"refer":{"connections":1}
,"global":{"settings":1}
,"details":{"home":1,"connection":1}
,"click":{"connection":1,"magnifier":1,"filter":1}
,"select":{"select":1,"connection":1}
,"name":{"drop-down":1}
,"menu":{"top":1}
,"magnifier":{"icon":1}
,"icon":{"start":1,"next":1,"appears":1}
,"start":{"viewing":1}
,"viewing":{"details":1}
,"alternatively":{"navigate":1}
,"using":{"buttons":1}
,"within":{"connection":1}
,"active":{"tooltips":1}
,"tooltips":{"home":1}
,"provide":{"additional":1}
,"example":{"cachemanager":1}
,"cachemanager":{"names":1}
,"names":{"pop":1}
,"pop":{"hover":1}
,"hover":{"app":1}
,"app":{"data":1}
,"data":{"drop-down":1}
,"filter":{"client":1,"clients":1,"icon":1}
,"list":{"filter":1}
,"appearing":{"connection":1}
,"next":{"connected":1}
,"connected":{"clients":1}
,"enter":{"addresses":1}
,"addresses":{"clients":1}
,"want":{"view":1}
,"return":{"home":1,"clicking":1}
,"navigating":{"away":1}
,"away":{"home":1}
,"appears":{"top":1}
}
;Search.control.loadWordPairs(pairs);
