var pairs =
{
"put":{"creates":1,"201":1}
,"creates":{"specified":1}
,"specified":{"resource":1,"content":1}
,"resource":{"updates":1,"representation":1,"409":1,"given":1}
,"updates":{"resource":1,"updating":1,"possible":1}
,"representation":{"allowed":1,"means":1}
,"allowed":{"resource":1}
,"updating":{"resource":1,"cache":1}
,"means":{"editing":1}
,"editing":{"value":1}
,"value":{"following":1}
,"following":{"boolean":1,"uri":1,"content":1}
,"boolean":{"cache":1}
,"cache":{"attributes":1,"statisticsenabled":1,"disabling":1,"attribute":1,"baz":1,"successfully":1}
,"attributes":{"enabled":1,"specified":1,"statisticsenabled":1,"modify":1}
,"enabled":{"enable":1,"statistics":1,"updating":1}
,"enable":{"(true":1}
,"(true":{"default)":1}
,"default)":{"disable":1}
,"disable":{"(false)":1}
,"(false)":{"cache":1,"statistics":1,"sampled":1}
,"statisticsenabled":{"enable":1,":false}}":1}
,"statistics":{"gathering":1,"improve":1,"disabled":1,"automatically":1,"sampled":1,"used":1,"enabled":1}
,"gathering":{"cache":1,"automatically":1}
,"disabling":{"statistics":1}
,"improve":{"cache\u0027s":1}
,"cache\u0027s":{"performance":1}
,"performance":{"limits":1}
,"limits":{"monitoring":1}
,"monitoring":{"capabilities":1}
,"capabilities":{"note":1}
,"note":{"statistics":1}
,"disabled":{"sampled":1,"sampledstatiscsenabled":1}
,"sampled":{"statistics":1}
,"automatically":{"disabled":1,"enabled":1}
,"sampledstatiscsenabled":{"enable":1}
,"used":{"providing":1}
,"providing":{"averages":1}
,"averages":{"aggregate":1}
,"aggregate":{"values":1}
,"values":{"sampled":1}
,"attribute":{"following":1}
,"uri":{"update":1,"specify":1}
,"update":{"cache":1}
,"content":{"\u002Fagents":1,"attributes":1}
,"\u002Fagents":{"ids=myconnectiongroup_myehcache\u002Fcachemanagers":1}
,"ids=myconnectiongroup_myehcache\u002Fcachemanagers":{"names=foo\u002Fcaches":1}
,"names=foo\u002Fcaches":{"names=baz":1}
,"names=baz":{"example":1}
,"example":{"turn":1}
,"turn":{"statistics":1}
,"baz":{"following":1}
,":false}}":{"attributes":1}
,"modify":{"described":1}
,"described":{"allowed":1}
,"possible":{"http":1}
,"http":{"status":1}
,"status":{"codes":1}
,"codes":{"put":1}
,"201":{"operation":1}
,"operation":{"successful":1}
,"successful":{"204":1}
,"204":{"cache":1}
,"successfully":{"updated":1}
,"updated":{"400":1}
,"400":{"uri":1}
,"specify":{"single":1}
,"single":{"resource":1}
,"409":{"resource":1}
,"given":{"name":1}
,"name":{"already":1}
,"already":{"exists":1}
}
;Search.control.loadWordPairs(pairs);
