var pairs =
{
"overview":{"management":1}
,"management":{"components":1,"agents":1,"server":1,"console":1,"rest":1}
,"components":{"terracotta":1,"management":1}
,"terracotta":{"provides":1,"server":1,"management":1}
,"provides":{"following":1,"rest":1}
,"following":{"management":1}
,"agents":{"embedded":1,"terracotta":1}
,"embedded":{"bigmemory":1}
,"bigmemory":{"terracotta":1}
,"server":{"array":1,"(tms)":1}
,"array":{"(tsa)":1}
,"(tsa)":{"provide":1}
,"provide":{"rest":1}
,"rest":{"interface":1}
,"interface":{"terracotta":1,"bridges":1,"tms":1,"write":1}
,"(tms)":{"process":1}
,"process":{"provides":1}
,"bridges":{"cluster":1}
,"cluster":{"management":1}
,"console":{"(tmc)":1}
,"(tmc)":{"served":1,"simplicity":1}
,"served":{"tms":1}
,"tms":{"communicates":1,"using":1,"management":1,"running":1}
,"communicates":{"tms":1}
,"using":{"rest":1}
,"write":{"custom":1}
,"custom":{"scripts":1,"rich":1}
,"scripts":{"create":1}
,"create":{"custom":1}
,"rich":{"internet":1}
,"internet":{"application":1}
,"application":{"(ria)":1}
,"(ria)":{"place":1}
,"place":{"terracotta":1}
,"simplicity":{"examples":1}
,"examples":{"given":1}
,"given":{"document":1}
,"document":{"assume":1}
,"assume":{"tms":1}
,"running":{"locally":1}
,"locally":{"therefore":1}
,"therefore":{"localhost":1}
,"localhost":{"used":1}
,"used":{"host":1}
,"host":{"address":1}
}
;Search.control.loadWordPairs(pairs);
