var pairs =
{
"troubleshooting":{"tab":1,"terracotta":1}
,"tab":{"troubleshooting":1,"information":1}
,"terracotta":{"clusters":1}
,"clusters":{"tmc":1}
,"tmc":{"includes":1}
,"includes":{"passive":1}
,"passive":{"monitoring":1}
,"monitoring":{"viewing":1,"panels":1,"system":1,"tab":1}
,"viewing":{"events":1,"server":1}
,"events":{"statistical":1,"monitoring":1}
,"statistical":{"trends":1}
,"trends":{"using":1}
,"using":{"monitoring":1}
,"panels":{"proactively":1}
,"proactively":{"investigating":1}
,"investigating":{"logs":1}
,"logs":{"thread":1,"generating":1}
,"thread":{"dumps":1}
,"dumps":{"information":1,"viewing":1,"cluster":1}
,"information":{"viewing":1,"examining":1,"behavior":1}
,"system":{"trends":1}
,"examining":{"logs":1}
,"generating":{"thread":1}
,"server":{"logs":1}
,"cluster":{"crosses":1}
,"crosses":{"certain":1}
,"certain":{"resource":1}
,"resource":{"thresholds":1}
,"thresholds":{"enter":1}
,"enter":{"mode":1}
,"mode":{"limited":1}
,"limited":{"functionality":1}
,"functionality":{"prevent":1}
,"prevent":{"crash":1}
,"crash":{"information":1}
,"behavior":{"understanding":1}
,"understanding":{"special":1}
,"special":{"tsa":1}
,"tsa":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
