var pairs =
{
"creating":{"enterprise":1,"terracotta":1}
,"enterprise":{"edition":1}
,"edition":{"clients":1}
,"clients":{"<<this":1,"need":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1,"installation":1,"sure":1}
,"docs.>>":{"following":1}
,"following":{"example":1,"dependencies":1,"locations":1}
,"example":{"shows":1,"probably":1,"correct":1}
,"shows":{"dependencies":1,"artifact":1}
,"dependencies":{"needed":1,"required":1,"listed":1}
,"needed":{"creating":1}
,"terracotta":{"4.3.1":1,"sessions":1,"version":1}
,"4.3.1":{"clients":1}
,"need":{"adapt":1}
,"adapt":{"entries":1}
,"entries":{"match":1}
,"match":{"specific":1,"version":1}
,"specific":{"product":1}
,"installation":{"<dependencies>":1,"find":1,"location)":1}
,"<dependencies>":{"<dependency>":1}
,"<dependency>":{"<groupid>":1}
,"<groupid>":{"org.terracotta":1,"net.sf.ehcache":1}
,"org.terracotta":{"<\u002Fgroupid>":1}
,"<\u002Fgroupid>":{"<artifactid>":1}
,"<artifactid>":{"terracotta-toolkit-runtime-ee":1,"ehcache-ee":1,"web-sessions":1,"tags)":1}
,"terracotta-toolkit-runtime-ee":{"<\u002Fartifactid>":1}
,"<\u002Fartifactid>":{"<version>":1}
,"<version>":{"4.3.1.0.133":1,"2.10.1.0.52":1,"tags)":1,"tags":1}
,"4.3.1.0.133":{"<\u002Fversion>":1}
,"<\u002Fversion>":{"<\u002Fdependency>":1}
,"<\u002Fdependency>":{"<!--the":1,"<\u002Fdependencies>":1}
,"<!--the":{"following":1}
,"required":{"using":1,"logging":1}
,"using":{"ehcache":1,"terracotta":1}
,"ehcache":{"dependencies":1,"version":1}
,"listed":{"include":1}
,"include":{"slf4j":1,"explicit-locking":1}
,"slf4j":{"api":1,"binding":1}
,"api":{"jar":1}
,"jar":{"(version":1,"choice":1}
,"(version":{"1.6.1)":1}
,"1.6.1)":{"slf4j":1}
,"binding":{"jar":1}
,"choice":{"jars":1}
,"jars":{"specify":1}
,"specify":{"required":1}
,"logging":{"framework":1}
,"framework":{"include":1}
,"explicit-locking":{"jar.-->":1}
,"jar.-->":{"<dependency>":1}
,"net.sf.ehcache":{"<\u002Fgroupid>":1}
,"ehcache-ee":{"<\u002Fartifactid>":1}
,"2.10.1.0.52":{"<\u002Fversion>":1}
,"sessions":{"-->":1,"version":1}
,"-->":{"<dependency>":1}
,"web-sessions":{"<\u002Fartifactid>":1}
,"<\u002Fdependencies>":{"example":1}
,"artifact":{"ids":1}
,"ids":{"(in":1}
,"(in":{"<artifactid>":1,"<version>":1}
,"tags)":{"corresponding":1,"contents":1}
,"corresponding":{"version":1}
,"version":{"numbers":1,"<installdir>\u002Fterracotta\u002Fapis\u002Fehcache\u002Flib\u002Fehcache-ee-<version>":1,"<installdir>\u002Fterracotta\u002Fapis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-<version>":1,"<installdir>\u002Fterracotta\u002Fsessions\u002Flib\u002Fweb-sessions-<version>":1,"(only":1,"<installdir>\u002Fterracotta\u002Fserver\u002Flib\u002Fwan-core-<version>":1}
,"numbers":{"(in":1,"installed":1,"example":1}
,"contents":{"<version>":1}
,"tags":{"shown":1}
,"shown":{"example":1}
,"probably":{"match":1}
,"installed":{"product":1}
,"sure":{"replace":1}
,"replace":{"versions":1}
,"versions":{"numbers":1}
,"correct":{"values":1}
,"values":{"installation":1,"following":1}
,"find":{"values":1}
,"locations":{"(<installdir>":1}
,"(<installdir>":{"represents":1}
,"represents":{"product":1}
,"location)":{"ehcache":1}
,"<installdir>\u002Fterracotta\u002Fapis\u002Fehcache\u002Flib\u002Fehcache-ee-<version>":{".jar":1}
,".jar":{"terracotta":1,"web":1,"quartz":1,"wan":1}
,"<installdir>\u002Fterracotta\u002Fapis\u002Ftoolkit\u002Flib\u002Fterracotta-toolkit-runtime-ee-<version>":{".jar":1}
,"web":{"sessions":1}
,"<installdir>\u002Fterracotta\u002Fsessions\u002Flib\u002Fweb-sessions-<version>":{".jar":1}
,"quartz":{"version":1}
,"(only":{"digits)":1}
,"digits)":{"<installdir>\u002Fterracotta\u002Fquartz-ee\u002Flib\u002Fquartz-ee-<version>":1}
,"<installdir>\u002Fterracotta\u002Fquartz-ee\u002Flib\u002Fquartz-ee-<version>":{".jar":1}
,"wan":{"version":1}
,"<installdir>\u002Fterracotta\u002Fserver\u002Flib\u002Fwan-core-<version>":{".jar":1}
}
;Search.control.loadWordPairs(pairs);
