var pairs =
{
"charts":{"panel":1,"display":1,"displayed":1,"average":1,"total":1,"size":1}
,"panel":{"replica":1,"alternative":1,"view":1,"wan":1,"select":1}
,"replica":{"caches":1,"cache":1}
,"caches":{"charts":1}
,"alternative":{"view":1}
,"view":{"replica":1,"click":1,"following":1}
,"cache":{"statistics":1,"information":1,"want":1,"field":1}
,"statistics":{"available":1}
,"available":{"overview":1}
,"overview":{"panel":1}
,"information":{"charts":1}
,"wan":{"tab":1}
,"tab":{"click":1}
,"click":{"charts":1,"replicas":1}
,"display":{"charts":1}
,"select":{"cachemanager":1,"cache":1}
,"cachemanager":{"replica":1}
,"want":{"view":1}
,"replicas":{"cache":1}
,"field":{"select":1}
,"following":{"charts":1}
,"displayed":{"replication":1}
,"replication":{"rate":1,"chart":1,"rates":1,"count":1}
,"rate":{"charts":1,"application\u0027s":1}
,"average":{"transactions":1}
,"transactions":{"per":1,"during":1}
,"per":{"second":1}
,"second":{"(tps)":1}
,"(tps)":{"during":1,"rate":1}
,"during":{"replication":1,"application\u0027s":1}
,"chart":{"plots":1}
,"plots":{"replication":1}
,"rates":{"one-minute":1}
,"one-minute":{"five-minute":1}
,"five-minute":{"fifteen-minute":1}
,"fifteen-minute":{"periods":1}
,"periods":{"mean":1}
,"mean":{"replication":1}
,"application\u0027s":{"entire":1}
,"entire":{"lifetime":1}
,"lifetime":{"replication":1,"inbound":1}
,"count":{"charts":1}
,"total":{"number":1}
,"number":{"transactions":1}
,"inbound":{"buffer":1}
,"buffer":{"size":1}
,"size":{"charts":1,"cluster":1}
,"cluster":{"listener":1}
,"listener":{"buffer":1}
}
;Search.control.loadWordPairs(pairs);
