var pairs =
{
"troubleshooting":{"questions":1}
,"questions":{"created":1}
,"created":{"new":1,"cache":1}
,"new":{"cache":1,"cachemanager":1,"instance":1}
,"cache":{"status":1,"cachemanager":1,"mycache":1,"testdiskonly":1,"data":1,"name":1,"config":1,"expected":1}
,"status":{"status_uninitialised":1}
,"status_uninitialised":{"initialize":1}
,"initialize":{"need":1,"servlet":1}
,"need":{"add":1,"define":1}
,"add":{"newly":1,"default":1,"cache":1,"defaultcache":1}
,"newly":{"created":1}
,"cachemanager":{"gets":1,"manager":1,"using":1,"warn":1,"creating":1,"means":1,"configuration":1}
,"gets":{"initialized":1,"noticeable":1}
,"initialized":{"code":1}
,"code":{"following":1}
,"following":{"cachemanager":1,"error":1}
,"manager":{"=cachemanager.create":1}
,"=cachemanager.create":{"cache":1}
,"mycache":{"=new":1}
,"=new":{"cache":1}
,"testdiskonly":{"true":1}
,"true":{"false":1}
,"false":{"manager.addcache":1}
,"manager.addcache":{"(mycache)":1}
,"(mycache)":{"crashed":1}
,"crashed":{"standalone":1}
,"standalone":{"bigmemory":1}
,"bigmemory":{"node":1,"configuration":1,"distribute":1,"max":1,"provide":1,"automatically":1,"redeploying":1,"runs":1,"start":1}
,"node":{"data":1,"information":1}
,"data":{"intact":1,"client":1,"bigmemory":1,"latency":1,"fits":1,"sets":1}
,"intact":{"persistence":1}
,"persistence":{"configured":1,"strategy":1}
,"configured":{"configured":1,"correctly":1}
,"correctly":{"node":1}
,"information":{"configuring":1}
,"configuring":{"fast":1}
,"fast":{"restart":1}
,"restart":{"bigmemory":1}
,"configuration":{"guide":1,"depending":1,"per":1,"defaultcache":1,"fix":1,"restart":1}
,"guide":{"added":1}
,"added":{"data":1,"name":1}
,"client":{"can\u0027t":1,"bigmemory":1}
,"can\u0027t":{"client":1}
,"distribute":{"data":1}
,"max":{"bigmemory":1,"product":1}
,"product":{"documentation":1}
,"documentation":{"small":1,"<<ffc-update":1}
,"small":{"data":1}
,"latency":{"seems":1}
,"seems":{"high":1}
,"high":{"few":1}
,"few":{"ways":1}
,"ways":{"try":1}
,"try":{"solve":1,"pinning":1,"programmatically":1}
,"solve":{"order":1}
,"order":{"preference":1}
,"preference":{"try":1}
,"pinning":{"cache":1,"certain":1}
,"fits":{"comfortably":1}
,"comfortably":{"heap":1}
,"heap":{"expected":1}
,"expected":{"grow":1,"exist":1}
,"grow":{"speed":1}
,"speed":{"gets":1}
,"noticeable":{"factor":1}
,"factor":{"pinning":1}
,"certain":{"elements":1,"cases":1}
,"elements":{"and\u002For":1}
,"and\u002For":{"tuning":1}
,"tuning":{"arc":1}
,"arc":{"settings":1}
,"settings":{"effective":1}
,"effective":{"certain":1}
,"cases":{"increase":1}
,"increase":{"size":1}
,"size":{"off-heap":1}
,"off-heap":{"store":1}
,"store":{"allow":1}
,"allow":{"data":1}
,"sets":{"cannot":1}
,"cannot":{"fit":1,"added":1}
,"fit":{"heap-but":1,"memory-to":1}
,"heap-but":{"fit":1}
,"memory-to":{"remain":1}
,"remain":{"close":1}
,"close":{"application":1}
,"application":{"using":1,"trying":1,"redeployed":1}
,"using":{"java":1,"simplepagecachingfilter":1,"resource":1,"diskstorepath":1}
,"java":{"getting":1,"-java":1,"version":1,"4-6":1}
,"getting":{"java.lang.verifyerror":1}
,"java.lang.verifyerror":{"backport":1}
,"backport":{"concurrent":1}
,"concurrent":{"classes":1}
,"classes":{"backport-concurrent":1}
,"backport-concurrent":{"library":1}
,"library":{"used":1}
,"used":{"bigmemory":1,"existing":1}
,"provide":{"java.util.concurrency":1}
,"java.util.concurrency":{"facilities":1}
,"facilities":{"java":1}
,"-java":{"either":1}
,"either":{"java":1}
,"version":{"compatible":1,"jdk":1,"book":1}
,"compatible":{"java":1}
,"4-6":{"version":1}
,"jdk":{"javax.servlet.servletexception":1}
,"javax.servlet.servletexception":{"initialize":1}
,"servlet":{"filter":1}
,"filter":{"using":1}
,"simplepagecachingfilter":{"default":1,"need":1}
,"default":{"implementation":1,"cache":1}
,"implementation":{"cache":1}
,"name":{"called":1,"ehcache.xml":1,"warning":1,"default":1,"cachemanager.add":1}
,"called":{"simplepagecachingfilter":1,"net.sf.ehcache.hibernate.singletonehcacheprovider":1}
,"define":{"cache":1}
,"ehcache.xml":{"override":1}
,"override":{"cachingfilter":1}
,"cachingfilter":{"required":1}
,"required":{"cache":1}
,"warning":{"application\u0027s":1,"separate":1}
,"application\u0027s":{"log":1}
,"log":{"new":1}
,"resource":{"already":1}
,"already":{"cachemanager":1,"used":1}
,"warn":{"cachemanager":1}
,"creating":{"new":1}
,"instance":{"cachemanager":1,"want":1,"singleton":1}
,"diskstorepath":{"c:\u005Ctemp\u005Ctempcache":1,"eliminate":1}
,"c:\u005Ctemp\u005Ctempcache":{"already":1}
,"existing":{"cachemanager":1}
,"means":{"reason":1}
,"reason":{"application":1}
,"trying":{"create":1}
,"create":{"additional":1}
,"additional":{"instances":1}
,"instances":{"cachemanager":1}
,"depending":{"upon":1}
,"upon":{"persistence":1}
,"strategy":{"bigmemory":1}
,"automatically":{"resolve":1}
,"resolve":{"disk-path":1}
,"disk-path":{"conflict":1}
,"conflict":{"know":1}
,"know":{"explicitly":1}
,"explicitly":{"configure":1}
,"configure":{"diskstorepath":1}
,"eliminate":{"warning":1}
,"separate":{"configuration":1}
,"per":{"instance":1}
,"want":{"instance":1}
,"singleton":{"creation":1}
,"creation":{"methods":1}
,"methods":{"i.e":1}
,"i.e":{"cachemanager.getinstance":1}
,"cachemanager.getinstance":{"hibernate":1}
,"hibernate":{"special":1}
,"special":{"provider":1}
,"provider":{"called":1}
,"net.sf.ehcache.hibernate.singletonehcacheprovider":{"integrations":1}
,"integrations":{"book":1}
,"book":{"ehcache":1,"available>>":1}
,"ehcache":{"product":1}
,"<<ffc-update":{"reference":1}
,"reference":{"point":1}
,"point":{"bigm":1}
,"bigm":{"version":1}
,"available>>":{"following":1}
,"error":{"mean":1,"add":1}
,"mean":{"caches":1}
,"caches":{"cannot":1}
,"config":{"specified":1,"please":1,"configuration":1}
,"specified":{"config":1}
,"please":{"add":1}
,"defaultcache":{"optional":1,"cachemanager\u0027s":1}
,"optional":{"try":1}
,"programmatically":{"add":1}
,"cachemanager.add":{"(string":1}
,"(string":{"name)":1}
,"name)":{"default":1}
,"exist":{"cachemanager":1}
,"fix":{"error":1}
,"cachemanager\u0027s":{"configuration":1}
,"redeploying":{"container":1}
,"container":{"errors":1}
,"errors":{"occur":1}
,"occur":{"bigmemory":1}
,"runs":{"web":1}
,"web":{"application":1}
,"redeployed":{"causing":1,"sure":1}
,"causing":{"bigmemory":1}
,"start":{"properly":1}
,"properly":{"web":1}
,"sure":{"restart":1}
}
;Search.control.loadWordPairs(pairs);
