var pairs =
{
"updating":{"terracotta":1}
,"terracotta":{"management":1,"kit":1}
,"management":{"server":1}
,"server":{"installing":1}
,"installing":{"new":1}
,"new":{"version":1}
,"version":{"terracotta":1,"tms":1,"started":1}
,"kit":{"installs":1}
,"installs":{"updated":1}
,"updated":{"version":1}
,"tms":{"new":1}
,"started":{"checks":1}
,"checks":{"existing":1}
,"existing":{"configuration":1}
,"configuration":{"files":1}
,"files":{"<user.home>\u002F.tc\u002Fmgmt":1,"(extension":1}
,"<user.home>\u002F.tc\u002Fmgmt":{"backing":1}
,"backing":{"incompatible":1}
,"incompatible":{"files":1}
,"(extension":{".bak)":1}
,".bak)":{"case":1}
,"case":{"previously":1}
,"previously":{"configured":1}
,"configured":{"connections":1}
,"connections":{"appear":1}
,"appear":{"tmc":1}
,"tmc":{"re-added":1}
}
;Search.control.loadWordPairs(pairs);
