var pairs =
{
"backing":{"cluster":1}
,"cluster":{"data":1}
,"data":{"backups":1,"following":1,"backup":1}
,"backups":{"panel":1,"(for":1,"restoring":1}
,"panel":{"provides":1}
,"provides":{"control":1}
,"control":{"creating":1,"backup":1}
,"creating":{"backup":1}
,"backup":{"cluster":1,"execution":1,"files":1,"terracotta":1}
,"following":{"server":1}
,"server":{"configuration":1,"array":1}
,"configuration":{"elements":1}
,"elements":{"control":1}
,"execution":{"<restartable":1}
,"<restartable":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1}
,"true":{"\u0022\u002F>":1,"backups":1}
,"\u0022\u002F>":{"-global":1}
,"-global":{"setting":1}
,"setting":{"required":1,"path":1}
,"required":{"true":1}
,"(for":{"servers)":1}
,"servers)":{"enabled":1}
,"enabled":{"false":1}
,"false":{"default":1}
,"default":{"<data-backup>":1,"path":1}
,"<data-backup>":{"terracotta\u002Fbackups":1}
,"terracotta\u002Fbackups":{"-server-level":1}
,"-server-level":{"element":1}
,"element":{"setting":1}
,"path":{"storing":1,"shown":1}
,"storing":{"backup":1}
,"files":{"default":1}
,"shown":{"information":1}
,"information":{"restoring":1}
,"restoring":{"backups":1,"data":1}
,"terracotta":{"server":1}
,"array":{"administer":1}
,"administer":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
