var pairs =
{
"wan":{"tab":1,"replication":1}
,"tab":{"wan":1,"enables":1}
,"enables":{"monitor":1}
,"monitor":{"information":1}
,"information":{"following":1,"overview":1}
,"following":{"aspects":1}
,"aspects":{"wan":1}
,"replication":{"service":1,"user":1}
,"service":{"wan\u0027s":1}
,"wan\u0027s":{"topology":1}
,"topology":{"configuration":1}
,"configuration":{"wan-enabled":1,"status":1,"parameters":1}
,"wan-enabled":{"cache":1}
,"cache":{"including":1,"display":1}
,"including":{"performance":1}
,"performance":{"statistics":1}
,"statistics":{"details":1,"orchestrators":1}
,"details":{"deployment":1,"orchestrator":1}
,"deployment":{"orchestrator":1}
,"orchestrator":{"topology":1,"want":1,"configuration":1}
,"status":{"terracotta":1}
,"terracotta":{"gathers":1}
,"gathers":{"statistics":1}
,"orchestrators":{"displays":1}
,"displays":{"cache":1}
,"display":{"information":1}
,"overview":{"format":1}
,"format":{"table)":1,"monitoring":1}
,"table)":{"charts":1}
,"charts":{"format":1}
,"monitoring":{"capability":1}
,"capability":{"enabled":1,"monitoringenabled":1}
,"enabled":{"default":1}
,"default":{"orchestrator":1}
,"want":{"disable":1}
,"disable":{"monitoring":1}
,"monitoringenabled":{"parameter":1}
,"parameter":{"false":1}
,"false":{"orchestrator\u0027s":1}
,"orchestrator\u0027s":{"wan-config.xml":1}
,"wan-config.xml":{"file":1}
,"file":{"details":1}
,"parameters":{"wan":1}
,"user":{"guide":1}
,"guide":{"caches":1}
,"caches":{"currently":1}
,"currently":{"replicated":1}
,"replicated":{"indicated":1}
,"indicated":{"wan":1}
}
;Search.control.loadWordPairs(pairs);
