var pairs =
{
"bigmemory":{"<<needs":1,"commercial":1,"provides":1,"enables":1,"general-purpose":1}
,"<<needs":{"fix-this":1}
,"fix-this":{"entire":1}
,"entire":{"topic":1}
,"topic":{"needs":1}
,"needs":{"reviewed":1}
,"reviewed":{"foram>>":1}
,"foram>>":{"bigmemory":1}
,"commercial":{"extension":1}
,"extension":{"ehcache":1}
,"ehcache":{"open-source":1,"enabling":1,"bigmemory":1}
,"open-source":{"standards-based":1}
,"standards-based":{"widely":1}
,"widely":{"used":1}
,"used":{"java-based":1}
,"java-based":{"caching":1}
,"caching":{"program":1,"in-memory":1}
,"program":{"boosting":1}
,"boosting":{"performance":1}
,"performance":{"offloading":1}
,"offloading":{"database":1}
,"database":{"simplifying":1}
,"simplifying":{"scalability":1}
,"scalability":{"bigmemory":1}
,"provides":{"features":1}
,"features":{"ehcache":1}
,"enabling":{"access":1}
,"access":{"off-heap":1}
,"off-heap":{"memory":1}
,"memory":{"caching":1,"enables":1}
,"in-memory":{"data":1}
,"data":{"storage":1,"cache":1,"store":1}
,"storage":{"off-heap":1,"without":1}
,"enables":{"java":1,"perform":1}
,"java":{"applications":1}
,"applications":{"leverage":1}
,"leverage":{"virtually":1}
,"virtually":{"ram":1}
,"ram":{"in-memory":1}
,"without":{"lengthy":1}
,"lengthy":{"pauses":1}
,"pauses":{"garbage":1}
,"garbage":{"collection":1}
,"collection":{"bigmemory":1}
,"perform":{"sql":1}
,"sql":{"queries":1}
,"queries":{"data":1}
,"cache":{"in-memory":1,"hibernate":1}
,"store":{"ehcache":1,"second-level":1}
,"general-purpose":{"cache\u002Fin-memory":1}
,"cache\u002Fin-memory":{"data":1}
,"second-level":{"cache":1}
,"hibernate":{"additionally":1}
,"additionally":{"integrate":1}
,"integrate":{"third-party":1}
,"third-party":{"products":1}
,"products":{"coldfusion":1}
,"coldfusion":{"google":1}
,"google":{"app":1}
,"app":{"engine":1}
,"engine":{"spring":1}
}
;Search.control.loadWordPairs(pairs);
