var pairs =
{
"limit":{"clause":1,"100":1,"<integer>":1}
,"clause":{"limit":1,"used":1,"top":1,"takes":1}
,"used":{"restrict":1,"order":1}
,"restrict":{"number":1,"result":1}
,"number":{"results":1}
,"results":{"returned":1,"select":1}
,"returned":{"search":1}
,"search":{"query":1,"results":1}
,"query":{"ordinarily":1}
,"ordinarily":{"limit":1}
,"order":{"clause":1,"age":1}
,"top":{"results":1}
,"select":{"*from":1,"age":1}
,"*from":{"person":1}
,"person":{"age":1,"((age":1}
,"age":{"<80":1,"zip":1,"asc":1}
,"<80":{"limit":1}
,"100":{"limit":1,"zip":1}
,"takes":{"single":1}
,"single":{"integer":1}
,"integer":{"argument":1}
,"argument":{"restrict":1}
,"result":{"general":1}
,"general":{"form":1}
,"form":{"limit":1}
,"<integer>":{"example":1}
,"example":{"limiting":1}
,"limiting":{"search":1}
,"zip":{"person":1,"=20144)":1}
,"((age":{"100":1}
,"=20144)":{"time":1}
,"time":{"10)":1}
,"10)":{"order":1}
,"asc":{"limit":1}
}
;Search.control.loadWordPairs(pairs);
