var pairs =
{
"example":{"create":1,"available":1,"demonstrates":1,"creates":1,"512":1}
,"create":{"read":1,"update":1}
,"read":{"update":1,"data":1,"multiple":1}
,"update":{"delete":1,"final":1,"multiple":1}
,"delete":{"following":1,"(crud)":1,"operations":1,"bigmemory.remove":1,"multiple":1,"everything":1}
,"following":{"description":1,"example":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1,"microsecond":1,"hardware":1,"start":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"create":1}
,"(crud)":{"example":1}
,"demonstrates":{"basic":1}
,"basic":{"create":1}
,"operations":{"bmg":1}
,"bmg":{"following":1}
,"creates":{"data":1}
,"data":{"store":1,"heap":1,"off-heap":1,"bigmemory":1,"single":1,"final":1}
,"store":{"configured":1,"available":1}
,"configured":{"512":1,"available":1}
,"512":{"heap":1,"data":1}
,"heap":{"memory":1,"nanosecond":1,"sizes":1}
,"memory":{"off-heap":1,"configuration":1,"fills":1,"ultra-fast":1,"physically":1}
,"off-heap":{"memory":1,"store":1}
,"configuration":{"managerconfiguration":1,"managerconfiguration.updatecheck":1,"keeps":1}
,"managerconfiguration":{"=new":1}
,"=new":{"configuration":1,"person":1,"arraylist":1}
,"managerconfiguration.updatecheck":{"(true)":1}
,"(true)":{".monitoring":1}
,".monitoring":{"(configuration.monitoring.autodetect)":1}
,"(configuration.monitoring.autodetect)":{".name":1}
,".name":{"config":1,"bigmemory-crud":1}
,"config":{".cache":1}
,".cache":{"(new":1}
,"(new":{"cacheconfiguration":1,"element":1}
,"cacheconfiguration":{".name":1}
,"bigmemory-crud":{".maxbyteslocalheap":1,"instructs":1}
,".maxbyteslocalheap":{"(512":1}
,"(512":{"memoryunit.megabytes)":1}
,"memoryunit.megabytes)":{".maxbyteslocaloffheap":1}
,".maxbyteslocaloffheap":{"(32":1}
,"(32":{"memoryunit.gigabytes)":1}
,"memoryunit.gigabytes)":{"cachemanager":1}
,"cachemanager":{"manager":1}
,"manager":{"=cachemanager.create":1}
,"=cachemanager.create":{"(managerconfiguration)":1}
,"(managerconfiguration)":{"cache":1}
,"cache":{"bigmemory":1}
,"bigmemory":{"=manager.getcache":1,"keep":1,"capable":1,"memory":1,"instance":1}
,"=manager.getcache":{"bigmemory-crud":1}
,"instructs":{"automatic":1}
,"automatic":{"resource":1}
,"resource":{"control":1}
,"control":{"(arc)":1}
,"(arc)":{"capability":1}
,"capability":{"bigmemory":1}
,"keep":{"maximum":1}
,"maximum":{"512":1}
,"nanosecond":{"microsecond":1}
,"microsecond":{"access":1,"speed":1}
,"access":{"example":1,"data":1}
,"fills":{"arc":1}
,"arc":{"automatically":1}
,"automatically":{"move":1}
,"move":{"data":1}
,"speed":{"configuration":1}
,"keeps":{"heap":1}
,"sizes":{"small":1}
,"small":{"avoid":1}
,"avoid":{"garbage":1,"swapping":1}
,"garbage":{"collection":1}
,"collection":{"pauses":1,"<element>":1}
,"pauses":{"tuning":1}
,"tuning":{"uses":1}
,"uses":{"large":1}
,"large":{"amounts":1}
,"amounts":{"in-process":1}
,"in-process":{"memory":1}
,"ultra-fast":{"access":1}
,"capable":{"addressing":1}
,"addressing":{"gigabytes":1}
,"gigabytes":{"terabytes":1}
,"terabytes":{"in-memory":1}
,"in-memory":{"data":1}
,"single":{"jvm":1}
,"jvm":{"it\u0027s":1}
,"it\u0027s":{"free":1}
,"free":{"however":1}
,"however":{"avoid":1}
,"swapping":{"care":1}
,"care":{"configure":1}
,"configure":{"bigmemory":1}
,"physically":{"available":1}
,"hardware":{"bigmemory":1}
,"instance":{"configured":1}
,"start":{"creating":1}
,"creating":{"data":1}
,"final":{"person":1,"element":1,"map":1}
,"person":{"timdoe":1,"tim":1,"pamelajones":1,"pamela":1,"jane":1,"marie":1,"john":1,"paul":1,"juliet":1}
,"timdoe":{"=new":1}
,"tim":{"doe":1}
,"doe":{"person.gender.male":1,"person.gender.female":1}
,"person.gender.male":{"eck":1,"big":1}
,"eck":{"street":1}
,"street":{"san":1}
,"san":{"mateo":1}
,"mateo":{"bigmemory.put":1,"\u0022)))":1}
,"bigmemory.put":{"(new":1}
,"element":{"timdoe))":1,"element":1,"=bigmemory.get":1,"pamelajones))":1,"updated":1,"removed":1,"new":1}
,"timdoe))":{"read":1}
,"=bigmemory.get":{"system.out.println":1}
,"system.out.println":{"value":1,"try":1}
,"value":{"key":1}
,"key":{"element.getobjectvalue":1,"updated.getobjectvalue":1,"updated":1,"final":1,"removed":1,"deleted":1}
,"element.getobjectvalue":{"())":1}
,"())":{"update":1}
,"pamelajones":{"=new":1}
,"pamela":{"jones":1}
,"jones":{"person.gender.female":1}
,"person.gender.female":{"berry":1,"eck":1,"big":1}
,"berry":{"parsippany":1}
,"parsippany":{"bigmemory.put":1,"\u0022)))":1}
,"pamelajones))":{"final":1}
,"updated":{"=bigmemory.get":1,"delete":1}
,"updated.getobjectvalue":{"key":1}
,"bigmemory.remove":{"system.out.println":1}
,"try":{"retrieve":1}
,"retrieve":{"key":1}
,"removed":{"=bigmemory.get":1,"key":1}
,"deleted":{"create":1}
,"multiple":{"entries":1}
,"entries":{"once":1}
,"once":{"collection":1,"final":1,"bigmemory.removeall":1}
,"<element>":{"elements":1,"elements.add":1}
,"elements":{"=new":1}
,"arraylist":{"<element>":1}
,"elements.add":{"(new":1}
,"new":{"person":1}
,"jane":{"doe":1}
,"\u0022)))":{"elements.add":1,"bigmemory.putall":1}
,"marie":{"antoinette":1}
,"antoinette":{"person.gender.female":1}
,"john":{"smith":1}
,"smith":{"person.gender.male":1}
,"big":{"wig":1}
,"wig":{"beverly":1}
,"beverly":{"hills":1}
,"hills":{"\u0022)))":1}
,"paul":{"dupont":1}
,"dupont":{"person.gender.male":1}
,"juliet":{"capulet":1}
,"capulet":{"person.gender.female":1}
,"bigmemory.putall":{"(elements)":1}
,"(elements)":{"read":1}
,"map":{"<object":1}
,"<object":{"element>":1}
,"element>":{"elementsmap":1}
,"elementsmap":{"=bigmemory.getall":1}
,"=bigmemory.getall":{"(arrays.aslist":1}
,"(arrays.aslist":{"\u0022))":1}
,"\u0022))":{"delete":1}
,"bigmemory.removeall":{"(arrays.aslist":1}
,"everything":{"once":1}
}
;Search.control.loadWordPairs(pairs);
