var pairs =
{
"understanding":{"special":1}
,"special":{"tsa":1}
,"tsa":{"modes":1,"enters":1,"automatically":1}
,"modes":{"terracotta":1,"initiated":1}
,"terracotta":{"management":1}
,"management":{"console":1,"panel":1}
,"console":{"flashes":1}
,"flashes":{"warnings":1}
,"warnings":{"tsa":1}
,"enters":{"throttled":1}
,"throttled":{"restricted":1,"mode":1}
,"restricted":{"mode":1}
,"mode":{"modes":1,"sufficient":1,"entered":1,"indication":1}
,"initiated":{"memory":1}
,"memory":{"resources":1,"available":1}
,"resources":{"drop":1,"under-allocated":1}
,"drop":{"below":1}
,"below":{"certain":1}
,"certain":{"threshold":1,"conditions":1}
,"threshold":{"endanger":1}
,"endanger":{"operations":1}
,"operations":{"cluster":1}
,"cluster":{"tsa":1,"need":1,"operations":1}
,"automatically":{"recover":1}
,"recover":{"throttled":1}
,"sufficient":{"expired":1}
,"expired":{"data":1}
,"data":{"evicted":1}
,"evicted":{"certain":1}
,"conditions":{"recovery":1}
,"recovery":{"fail":1}
,"fail":{"restricted":1}
,"entered":{"provide":1}
,"provide":{"temporary":1}
,"temporary":{"relief":1}
,"relief":{"clearing":1}
,"clearing":{"disabling":1}
,"disabling":{"caches":1}
,"caches":{"information":1,"management":1}
,"information":{"clearing":1}
,"panel":{"tsa":1}
,"indication":{"memory":1}
,"under-allocated":{"cluster":1}
,"need":{"stopped":1}
,"stopped":{"additional":1}
,"additional":{"steps":1}
,"steps":{"taken":1}
,"taken":{"ensure":1}
,"ensure":{"enough":1}
,"enough":{"memory":1}
,"available":{"cover":1}
,"cover":{"cluster":1}
}
;Search.control.loadWordPairs(pairs);
