var pairs =
{
"statistics":{"following":1,"last":1,"statistics":1,"servers":1,"requested":1,"clients":1}
,"following":{"uri":1}
,"uri":{"extensions":1}
,"extensions":{"base":1}
,"base":{"extension":1}
,"extension":{"\u002Fagents\u002Fstatistics":1}
,"\u002Fagents\u002Fstatistics":{"\u002Fv2\u002Fagents\u002Fstatistics":1}
,"\u002Fv2\u002Fagents\u002Fstatistics":{"return":1}
,"return":{"statistical":1}
,"statistical":{"information":1}
,"information":{"dgc":1}
,"dgc":{"runs":1}
,"runs":{"statistics":1,"\u002Fdgc":1}
,"last":{"1000":1}
,"1000":{"dgc":1}
,"\u002Fdgc":{"server":1}
,"server":{"statistics":1}
,"servers":{"\u002Fservers":1,"requested":1}
,"\u002Fservers":{"names=a":1}
,"names=a":{"show=k":1,"show=k&show=l&show=m":1}
,"show=k":{"\u002Fservers":1,"\u002Fclients":1}
,"show=k&show=l&show=m":{"names":1,"ids":1}
,"names":{"specified":1}
,"specified":{"statistics":1}
,"requested":{"show":1,"client":1}
,"show":{"omitted":1}
,"omitted":{"statistics":1}
,"client":{"statistics":1}
,"clients":{"\u002Fclients":1,"requested":1}
,"\u002Fclients":{"ids=x":1}
,"ids=x":{"show=k":1,"show=k&show=l&show=m":1}
,"ids":{"specified":1}
}
;Search.control.loadWordPairs(pairs);
