var pairs =
{
"welcome":{"bigmemory":1}
,"bigmemory":{"4.3":1,"lets":1,"unlimited":1,"instructions":1,"installing":1,"data":1}
,"4.3":{"online":1}
,"online":{"documentation":1}
,"documentation":{"library":1}
,"library":{"bigmemory":1}
,"lets":{"put":1}
,"put":{"data":1}
,"data":{"memory":1,"management":1,"<<ffc=shouldn\u2019t":1,"stores":1}
,"memory":{"limited":1}
,"limited":{"ram":1}
,"ram":{"machine":1}
,"machine":{"bigmemory":1,"(jvm)":1}
,"unlimited":{"in-memory":1}
,"in-memory":{"data":1}
,"management":{"java":1,"in-memory":1}
,"java":{"virtual":1}
,"virtual":{"machine":1}
,"(jvm)":{"advanced":1}
,"advanced":{"monitoring":1}
,"monitoring":{"search":1}
,"search":{"management":1}
,"<<ffc=shouldn\u2019t":{"mention":1}
,"mention":{"fast":1}
,"fast":{"restartability":1}
,"restartability":{"arc":1}
,"arc":{"?>>":1}
,"?>>":{"started":1}
,"started":{"installing":1}
,"installing":{"bigmemory":1,"license":1}
,"instructions":{"downloading":1}
,"downloading":{"bigmemory":1}
,"license":{"key":1}
,"key":{"connecting":1}
,"connecting":{"applications":1}
,"applications":{"new":1}
,"new":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
