var pairs =
{
"topology":{"types":1,"used":1,"offers":1,"recommended":1,"available":1,"application":1,"ensures":1}
,"types":{"bigm":1}
,"bigm":{"(section)":1}
,"(section)":{"standalone":1}
,"standalone":{"data":1,"topology":1}
,"data":{"held":1,"time-to-live":1,"drift":1,"application":1,"using":1}
,"held":{"application":1,"remote":1}
,"application":{"node":1,"nodes":1,"weak":1,"environment":1,"clusters":1,"appear":1,"instances":1}
,"node":{"application":1,"topology":1}
,"nodes":{"independent":1,"running":1}
,"independent":{"communication":1}
,"communication":{"standalone":1}
,"used":{"multiple":1,"data":1}
,"multiple":{"application":1,"instances":1}
,"running":{"application":1}
,"weak":{"consistency":1}
,"consistency":{"contain":1,"options":1}
,"contain":{"consistent":1}
,"consistent":{"values":1}
,"values":{"immutable":1}
,"immutable":{"data":1}
,"time-to-live":{"element":1}
,"element":{"completed":1,"needs":1}
,"completed":{"element":1}
,"needs":{"reloaded":1}
,"reloaded":{"distributed":1}
,"distributed":{"data":1,"topology":1}
,"remote":{"server":1}
,"server":{"(or":1}
,"(or":{"array":1}
,"array":{"servers)":1}
,"servers)":{"subset":1}
,"subset":{"recently":1}
,"recently":{"used":1}
,"offers":{"rich":1}
,"rich":{"consistency":1}
,"options":{"distributed":1}
,"recommended":{"approach":1}
,"approach":{"clustered":1}
,"clustered":{"scaled-out":1}
,"scaled-out":{"application":1}
,"environment":{"provides":1}
,"provides":{"highest":1}
,"highest":{"level":1}
,"level":{"performance":1}
,"performance":{"availability":1}
,"availability":{"scalability":1}
,"scalability":{"distributed":1,"without":1}
,"available":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"production":1}
,"production":{"applications":1}
,"applications":{"deployed":1}
,"deployed":{"clusters":1}
,"clusters":{"multiple":1,"experience":1}
,"instances":{"availability":1,"happens":1,"kept":1}
,"without":{"distributed":1}
,"experience":{"data":1}
,"drift":{"meaning":1}
,"meaning":{"updates":1}
,"updates":{"made":1}
,"made":{"data":1}
,"appear":{"instances":1}
,"happens":{"web":1}
,"web":{"session":1}
,"session":{"data":1}
,"using":{"distributed":1}
,"ensures":{"data":1}
,"kept":{"sync":1}
}
;Search.control.loadWordPairs(pairs);
