var pairs =
{
"select":{"clause":1,"statement":1,"[*|":1,"cache":1,"*from":1,"key":1,"value":1,"age":1,"avg":1}
,"clause":{"<<this":1,"general":1,"defines":1,"attributes":1,"\u002F\u002Fget":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"section":1}
,"section":{"provides":1}
,"provides":{"detailed":1}
,"detailed":{"specification":1}
,"specification":{"select":1}
,"general":{"form":1}
,"form":{"select":1}
,"statement":{"select":1}
,"[*|":{"key":1}
,"key":{"value":1,"select":1,"person":1,"sum":1,"average":1}
,"value":{"[(attribute":1,"denoted":1,"select":1,"person":1,"attributes":1}
,"[(attribute":{"attribute":1}
,"attribute":{"attribute":1,"aggregatorfunction":1}
,"aggregatorfunction":{"(attribute)":1}
,"(attribute)":{"[from":1}
,"[from":{"cache]":1}
,"cache]":{"[where":1}
,"[where":{"condition":1}
,"condition":{"[group":1}
,"[group":{"attribute]":1}
,"attribute]":{"[order":1}
,"[order":{"{attribute}]":1}
,"{attribute}]":{"[limit":1}
,"[limit":{"{count":1}
,"{count":{"select":1}
,"defines":{"attributes":1}
,"attributes":{"selected":1,"specified":1,"keys":1,"wildcard":1,"person":1}
,"selected":{"attributes":1}
,"specified":{"names":1,"using":1,"attribute\u0027s":1}
,"names":{"match":1}
,"match":{"search":1}
,"search":{"configuration":1}
,"configuration":{"otherwise":1}
,"otherwise":{"exception":1}
,"exception":{"thrown":1}
,"thrown":{"select":1}
,"cache":{"key":1,"queried":1}
,"denoted":{"keywords":1}
,"keywords":{"key":1}
,"keys":{"values":1}
,"values":{"order":1,"following":1}
,"order":{"return":1}
,"return":{"searchable":1}
,"searchable":{"attributes":1}
,"wildcard":{"character":1}
,"character":{"\u0022*\u0022":1}
,"\u0022*\u0022":{"name":1}
,"name":{"cache":1,"=\u0027dave":1}
,"queried":{"specified":1}
,"using":{"clause":1}
,"\u002F\u002Fget":{"attributes":1,"key":1,"value":1,"age":1,"average":1}
,"person":{"named":1,"name":1,"age":1,"select":1}
,"named":{"dave":1}
,"dave":{"select":1}
,"*from":{"person":1}
,"=\u0027dave":{"\u002F\u002Fget":1,"aggregator":1}
,"age":{"person":1,"zip":1,"persons":1,"aggregation":1,"select":1}
,"zip":{"select":1,"person":1}
,"aggregator":{"functions":1}
,"functions":{"aggregator":1,"used":1,"available":1}
,"used":{"perform":1}
,"perform":{"calculations":1}
,"calculations":{"specified":1}
,"attribute\u0027s":{"values":1}
,"following":{"functions":1}
,"available":{"sum":1}
,"sum":{"max":1,"(age)":1}
,"max":{"min":1}
,"min":{"average":1,"(age)":1}
,"average":{"(can":1,"age":1,"(age)":1}
,"(can":{"\u0027average":1}
,"\u0027average":{"\u0027avg\u0027)":1}
,"\u0027avg\u0027)":{"count":1}
,"count":{"\u002F\u002Fget":1}
,"persons":{"older":1}
,"older":{"select":1}
,"avg":{"(age)":1}
,"(age)":{"person":1,"min":1}
,"aggregation":{"examples":1}
,"examples":{"select":1}
}
;Search.control.loadWordPairs(pairs);
