var pairs =
{
"order":{"clause":1,"query":1,"<attribute":1,"examples":1,"age":1}
,"clause":{"order":1,"general":1}
,"query":{"results":1}
,"results":{"add":1}
,"add":{"order":1}
,"general":{"form":1}
,"form":{"order":1}
,"<attribute":{"<asc":1}
,"<asc":{"[ending]":1}
,"[ending]":{"desc":1}
,"desc":{"[ending]>":1,"select":1,"zip":1}
,"[ending]>":{"<attribute":1,"default":1}
,"default":{"ordering":1}
,"ordering":{"direction":1}
,"direction":{"ascending":1}
,"ascending":{"order":1}
,"examples":{"select":1}
,"select":{"*from":1,"age":1}
,"*from":{"person":1}
,"person":{"age":1,"((age":1}
,"age":{"order":1,"asc":1,"person":1,"descending":1,"zip":1,"desc":1}
,"asc":{"name":1}
,"name":{"desc":1}
,"((age":{"100":1}
,"100":{"zip=20144)":1}
,"zip=20144)":{"time":1}
,"time":{"10)":1}
,"10)":{"order":1}
,"descending":{"select":1}
,"zip":{"person":1,"asc":1}
}
;Search.control.loadWordPairs(pairs);
