var pairs =
{
"terracotta":{"repositories":1}
,"repositories":{"<<this":1,"available":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"following":1}
,"following":{"contains":1}
,"contains":{"terracotta":1}
,"available":{"<repositories>":1}
,"<repositories>":{"<repository>":1}
,"<repository>":{"<id>":1}
,"<id>":{"terracotta-snapshots":1,"terracotta-releases":1}
,"terracotta-snapshots":{"<\u002Fid>":1}
,"<\u002Fid>":{"<url>":1}
,"<url>":{"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Fsnapshots":1,"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Fsnapshots":{"<\u002Furl>":1}
,"<\u002Furl>":{"<releases>":1}
,"<releases>":{"<enabled>":1}
,"<enabled>":{"false":1,"true":1}
,"false":{"<\u002Fenabled>":1}
,"<\u002Fenabled>":{"<\u002Freleases>":1,"<\u002Fsnapshots>":1}
,"<\u002Freleases>":{"<snapshots>":1}
,"<snapshots>":{"<enabled>":1}
,"true":{"<\u002Fenabled>":1}
,"<\u002Fsnapshots>":{"<\u002Frepository>":1,"<\u002Fpluginrepository>":1}
,"<\u002Frepository>":{"<repository>":1,"<\u002Frepositories>":1}
,"terracotta-releases":{"<\u002Fid>":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":{"<\u002Furl>":1}
,"<\u002Frepositories>":{"<pluginrepositories>":1}
,"<pluginrepositories>":{"<pluginrepository>":1}
,"<pluginrepository>":{"<id>":1}
,"<\u002Fpluginrepository>":{"<pluginrepository>":1,"<\u002Fpluginrepositories>":1}
}
;Search.control.loadWordPairs(pairs);
