var pairs =
{
"general":{"questions":1}
,"questions":{"need":1}
,"need":{"enterprise":1}
,"enterprise":{"support":1}
,"support":{"bigmemory":1,"contact":1}
,"bigmemory":{"terracotta":1,"part":1,"bigmemory":1,"max":1,"in-memory":1,"overview":1}
,"terracotta":{"provides":1,"what\u0027s":1}
,"provides":{"enterprise":1}
,"part":{"software":1}
,"software":{"subscription":1}
,"subscription":{"enterprise":1}
,"contact":{"terracotta":1}
,"what\u0027s":{"difference":1}
,"difference":{"bigmemory":1}
,"max":{"bigmemory":1,"distributed":1}
,"in-memory":{"data":1,"management":1}
,"data":{"management":1}
,"management":{"single":1,"across":1}
,"single":{"jvm":1}
,"jvm":{"(in-process)":1}
,"(in-process)":{"bigmemory":1}
,"distributed":{"in-memory":1}
,"across":{"array":1}
,"array":{"servers":1}
,"servers":{"max":1}
}
;Search.control.loadWordPairs(pairs);
