var pairs =
{
"pooling":{"resources":1,"need":1}
,"resources":{"versus":1}
,"versus":{"sizing":1}
,"sizing":{"individual":1,"configuration":1,"configured":1,"pooling":1}
,"individual":{"data":1,"cache":1}
,"data":{"sets":1,"specific":1,"set\u0027s":1,"claims":1,"tier":1,"persistence":1}
,"sets":{"<<this":1,"specific":1,"size":1,"explicit":1,"pools":1,"explicitly":1,"specify":1,"share":1,"bytes-based":1,"checked":1,"tier":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"bigm":1}
,"bigm":{"constrain":1,"off-heap":1,"information":1}
,"constrain":{"size":1}
,"size":{"data":1,"cachemanager\u0027s":1,"cachemanager":1,"configuration":1,"remaining":1,"tier":1,"provided":1,"exception":1}
,"specific":{"tier":1,"cache":1}
,"tier":{"data":1,"configuring":1,"individual":1,"specified":1,"receive":1,"exactly":1,"warning":1,"cannot":1,"nothing":1,"cache":1,"either":1,"during":1,"information":1}
,"set\u0027s":{"configuration":1}
,"configuration":{"constrain":1,"cachemanager-level":1,"tier":1,"claimed":1,"doing":1,"reload":1,"off-heap":1}
,"cachemanager\u0027s":{"data":1}
,"configuring":{"overall":1,"disk":1}
,"overall":{"size":1}
,"cachemanager":{"level":1,"eight":1,"(maxbyteslocalheap":1,"off-heap":1,"pool":1}
,"level":{"cachemanager-level":1}
,"cachemanager-level":{"pool":1,"pools":1}
,"pool":{"specified":1,"case":1,"(after":1,"entries-based":1,"startup":1,"invalidconfigurationexception":1,"sizes":1,"configured":1,"however":1,"removed":1,"cannot":1,"remaining":1}
,"specified":{"tier":1,"configuration":1,"data":1,"portion":1}
,"claims":{"amount":1}
,"amount":{"tier":1,"pool":1}
,"case":{"data":1,"cache":1,"every":1,"prevent":1}
,"receive":{"equal":1}
,"equal":{"share":1}
,"share":{"remainder":1,"600mb":1}
,"remainder":{"pool":1}
,"(after":{"data":1}
,"explicit":{"sizing":1}
,"claimed":{"portion)":1}
,"portion)":{"example":1}
,"example":{"cachemanager":1}
,"eight":{"data":1}
,"pools":{"gigabyte":1,"over-allocated":1}
,"gigabyte":{"heap":1}
,"heap":{"two":1,"remaining":1,"equally":1,"either":1,"setting":1}
,"two":{"data":1}
,"explicitly":{"specify":1,"taken":1,"setting":1}
,"specify":{"200mb":1,"size":1}
,"200mb":{"heap":1}
,"remaining":{"data":1,"caches":1}
,"600mb":{"heap":1}
,"equally":{"note":1}
,"note":{"data":1,"percentages":1,"exception":1}
,"bytes-based":{"attributes":1}
,"attributes":{"claim":1,"maxentrieslocal":1}
,"claim":{"portion":1,"specified":1,"unused":1}
,"portion":{"pool":1,"heap":1,"allot":1}
,"entries-based":{"attributes":1}
,"maxentrieslocal":{"cannot":1}
,"cannot":{"used":1,"tier":1,"add":1,"claim":1}
,"used":{"pool":1,"data":1}
,"startup":{"sizes":1}
,"sizes":{"specified":1}
,"checked":{"ensure":1}
,"ensure":{"cachemanager-level":1}
,"over-allocated":{"over-allocation":1}
,"over-allocation":{"occurs":1}
,"occurs":{"pool":1}
,"invalidconfigurationexception":{"thrown":1,"pool":1}
,"thrown":{"note":1,"cache":1}
,"percentages":{"add":1}
,"add":{"100":1,"caches":1}
,"100":{"single":1}
,"single":{"pool":1}
,"exactly":{"entire":1}
,"entire":{"cachemanager-level":1,"off-heap":1}
,"warning":{"logged":1}
,"logged":{"case":1}
,"nothing":{"left":1}
,"left":{"memory":1}
,"memory":{"store":1}
,"store":{"(heap)":1,"bigm":1,"attempts":1,"exceed":1,"local":1,"<<ffc-this":1,"give":1,"data":1}
,"(heap)":{"size":1}
,"provided":{"heap":1}
,"either":{"cachemanager":1,"configured":1,"temporary":1}
,"(maxbyteslocalheap":{"only)":1,"maxentrieslocalheap)":1}
,"only)":{"individual":1}
,"cache":{"(maxbyteslocalheap":1,"allows":1,"claim":1,"setting":1,"heap":1,"ehcache":1,"overflowtooffheap":1,"overflowing":1,"using":1}
,"maxentrieslocalheap)":{"doing":1}
,"doing":{"causes":1,"generates":1}
,"causes":{"invalidconfigurationexception":1}
,"configured":{"combined":1,"pool":1,"explicitly":1,"cachemanager":1,"bytes":1,"off-heap":1,"using":1}
,"combined":{"heap":1}
,"setting":{"individual":1,"configured":1,"maxbyteslocalheap":1,"either":1,"overflowtooffheap":1,"configure":1}
,"allows":{"cache":1}
,"however":{"case":1}
,"maxbyteslocalheap":{"(same":1}
,"(same":{"cachemanager)":1}
,"cachemanager)":{"case":1}
,"every":{"cache":1}
,"taken":{"pool":1}
,"off-heap":{"store":1,"sizing":1,"application":1,"configuration":1,"pool":1,"data":1,"overflowtooffheap":1,"explicitly":1}
,"bytes":{"entries":1}
,"entries":{"cachemanager":1}
,"application":{"cannot":1}
,"caches":{"dynamically":1,"used":1,"pool":1,"remove":1,"case":1}
,"dynamically":{"off-heap":1}
,"generates":{"error":1}
,"error":{"addition":1}
,"addition":{"caches":1}
,"removed":{"programmatically":1}
,"programmatically":{"terracotta":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"(tmc)":1}
,"(tmc)":{"caches":1}
,"unused":{"portion":1}
,"allot":{"entire":1}
,"remove":{"unwanted":1}
,"unwanted":{"cache":1}
,"ehcache":{"configuration":1}
,"reload":{"configuration":1}
,"overflowtooffheap":{"true":1,"attribute":1}
,"true":{"cachemanager":1,"caches":1}
,"using":{"off-heap":1,"disk":1}
,"attribute":{"automatically":1,"false":1}
,"automatically":{"true":1}
,"prevent":{"specific":1}
,"overflowing":{"off-heap":1}
,"false":{"note":1}
,"exception":{"thrown":1,"contain":1}
,"attempts":{"put":1}
,"put":{"element":1}
,"element":{"cause":1,"[key":1}
,"cause":{"off-heap":1}
,"exceed":{"allotted":1}
,"allotted":{"size":1}
,"contain":{"message":1}
,"message":{"similar":1}
,"similar":{"following":1}
,"following":{"element":1}
,"[key":{"=25274":1}
,"=25274":{"value=[b@3ebb2a91":1}
,"value=[b@3ebb2a91":{"version=1":1}
,"version=1":{"hitcount=0":1}
,"hitcount=0":{"creationtime":1}
,"creationtime":{"=1367966069431":1}
,"=1367966069431":{"lastaccesstime":1,"large":1}
,"lastaccesstime":{"=1367966069431":1}
,"large":{"stored":1}
,"stored":{"offheap":1}
,"offheap":{"store":1}
,"local":{"disk":1}
,"disk":{"store":1,"used":1,"persistence":1,"temporary":1}
,"<<ffc-this":{"section":1}
,"section":{"repeats":1}
,"repeats":{"already":1}
,"already":{"disk":1}
,"give":{"guidance":1}
,"guidance":{"sizing":1}
,"need":{"consider":1}
,"consider":{"re-writing":1}
,"re-writing":{"eliminating.>>":1}
,"eliminating.>>":{"local":1}
,"temporary":{"storage":1,"tier":1}
,"storage":{"disk":1}
,"persistence":{"once":1,"data":1,"implementation":1}
,"once":{"disk":1}
,"during":{"bigmemory":1}
,"bigmemory":{"operation":1}
,"operation":{"persistencestrategy":1}
,"persistencestrategy":{"localtempswap":1}
,"localtempswap":{"maxbyteslocaldisk":1}
,"maxbyteslocaldisk":{"setting":1}
,"configure":{"size":1}
,"information":{"using":1}
}
;Search.control.loadWordPairs(pairs);
