var pairs =
{
"setting":{"ldap":1}
,"ldap":{"active":1,"topic":1,"server":1,"standard":1,"636":1,"allow":1,"want":1,"url":1,"instance":1,"attribute":1}
,"active":{"directory":1}
,"directory":{"authorization":1,"authentication":1,"url":1,"system":1,"manager":1,"want":1}
,"authorization":{"<<ffc-karen":1,"method":1,"information":1}
,"<<ffc-karen":{"says":1}
,"says":{"need":1}
,"need":{"generally":1}
,"generally":{"reorganize":1}
,"reorganize":{"content":1}
,"content":{"guide":1}
,"guide":{"relating":1}
,"relating":{"ldap":1}
,"topic":{"integrated":1}
,"integrated":{"linked":1}
,"linked":{"default":1}
,"default":{"security":1}
,"security":{"topic.>>":1}
,"topic.>>":{"select":1}
,"select":{"either":1}
,"either":{"ldap":1}
,"method":{"tmc":1}
,"tmc":{"authentication":1,"enterprise":1,"supply":1,"keychain":1}
,"authentication":{"page":1,"authorization":1}
,"page":{"setup":1,"opens":1,"allows":1}
,"setup":{"page":1,"form":1}
,"opens":{"filling":1}
,"filling":{"form":1}
,"form":{"setup":1,"enter":1}
,"allows":{"tmc":1,"anonymous":1}
,"enterprise":{"directory":1}
,"information":{"below":1}
,"below":{"clarifies":1}
,"clarifies":{"required":1}
,"required":{"fields":1}
,"fields":{"setup":1}
,"enter":{"directory":1,"attribute":1}
,"url":{"complete":1,"ldap":1,"format":1,"ldaps:\u002F\u002Fldapserv1:700":1,"define":1,"ldap:\u002F\u002Fvminrwa04:1389":1,"ldap:\u002F\u002F10.60.29.212:389":1}
,"complete":{"url":1}
,"server":{"url":1,"port":1,"running":1,"example":1,"allows":1}
,"format":{"protocol:\u002F\u002Fhostname:portnumber":1}
,"protocol:\u002F\u002Fhostname:portnumber":{"protocol":1}
,"protocol":{"ldap":1}
,"standard":{"connections":1}
,"connections":{"ldaps":1,"host":1}
,"ldaps":{"secure":1,"example":1}
,"secure":{"connections":1,"connection":1}
,"host":{"host":1,"name":1,"called":1}
,"name":{"address":1,"tmcoperatoruser3":1}
,"address":{"ldap":1}
,"port":{"port":1,"server":1,"optional":1,"defaults":1,"700":1}
,"running":{"port":1,"nonstandard":1}
,"optional":{"omitted":1}
,"omitted":{"port":1}
,"defaults":{"389":1}
,"389":{"ldap":1}
,"636":{"ldaps":1}
,"example":{"specifying":1,"directory":1,"value":1,"suppose":1,"prompt":1}
,"specifying":{"url":1}
,"ldaps:\u002F\u002Fldapserv1:700":{"create":1}
,"create":{"secure":1}
,"connection":{"ldap":1}
,"nonstandard":{"port":1}
,"700":{"host":1}
,"called":{"ldapserv1":1}
,"ldapserv1":{"enter":1}
,"system":{"username":1,"user":1}
,"username":{"user":1,"map":1}
,"user":{"tmc":1,"permission":1,"name":1,"group":1}
,"supply":{"connect":1}
,"connect":{"ldap":1}
,"manager":{"user":1}
,"permission":{"query":1}
,"query":{"groups":1}
,"groups":{"group":1,"ldap":1,"enter":1,"operator":1,"active":1,"tmcadminstgroup1":1}
,"group":{"membership":1,"names":1,"template":1,"uniquemember":1,"tmcadminstgroup1":1,"keychain":1,"members":1,"feature":1,"share":1,"departmentnumber":1,"tmcopstgroup1":1}
,"membership":{"ldap":1}
,"anonymous":{"access":1}
,"access":{"leave":1,"username":1}
,"leave":{"field":1}
,"field":{"blank":1}
,"blank":{"ldap":1}
,"allow":{"anonymous":1}
,"map":{"password":1}
,"password":{"tmc":1,"managead12":1}
,"keychain":{"configured":1,"formation":1,".tc\u005Cmgmt\u005Ckeychain":1,"password":1}
,"configured":{"bin\u002Fkeychain.sh":1}
,"bin\u002Fkeychain.sh":{"~\u002F.tc\u002Fmgmt\u002Fkeychain":1}
,"~\u002F.tc\u002Fmgmt\u002Fkeychain":{"ldap:\u002F\u002Fadmin@localhost:1389":1}
,"ldap:\u002F\u002Fadmin@localhost:1389":{"static":1}
,"static":{"groups":1}
,"want":{"ldap":1,"active":1}
,"define":{"rules":1}
,"rules":{"explicit":1,"match":1}
,"explicit":{"group":1}
,"names":{"consider":1,"works":1}
,"consider":{"following":1}
,"following":{"configuration":1}
,"configuration":{"prompt":1,"example":1}
,"prompt":{"example":1}
,"value":{"enter":1}
,"ldap:\u002F\u002Fvminrwa04:1389":{"directory":1}
,"tmcoperatoruser3":{"search":1}
,"search":{"base":1}
,"base":{"dc=localdomain":1,"dc=igomega":1}
,"dc=localdomain":{"dc=com":1}
,"dc=com":{"userdn":1,"group":1,"ldap":1,"admin":1}
,"userdn":{"template":1}
,"template":{"uid={0}":1,"cn={0}":1}
,"uid={0}":{"ou=users":1}
,"ou=users":{"dc=localdomain":1}
,"cn={0}":{"ou=groups":1}
,"ou=groups":{"dc=localdomain":1}
,"instance":{"working":1}
,"working":{"against":1}
,"against":{"dynamic":1}
,"dynamic":{"groups":1,"group":1}
,"attribute":{"matching":1,"attributes":1,"departmentnumber":1}
,"matching":{"user":1}
,"uniquemember":{"admin":1}
,"admin":{"groups":1,"operator":1,"department":1}
,"operator":{"group":1,"ldap":1,"department":1}
,"tmcadminstgroup1":{"tmcadminstgroup2":1}
,"tmcadminstgroup2":{"tmcadminstgroup3":1}
,"tmcadminstgroup3":{"tmcopstgroup1":1,"operator":1,"keychain":1}
,"tmcopstgroup1":{"tmcopstgroup2":1}
,"tmcopstgroup2":{"tmcopstgroup3":1}
,"tmcopstgroup3":{"tmcadminstgroup1":1}
,"formation":{"command":1,"keychain":1}
,"command":{"keychain":1}
,".tc\u005Cmgmt\u005Ckeychain":{"ldap:\u002F\u002Ftmcoperatoruser3@vminrwa04:1389":1,"ldap:\u002F\u002Ftmcoperatoruser3@10.60.29.212:389":1}
,"ldap:\u002F\u002Ftmcoperatoruser3@vminrwa04:1389":{"keychain":1}
,"managead12":{"dynamic":1,"static":1}
,"match":{"group":1}
,"members":{"dynamic":1,"admin":1}
,"feature":{"alternative":1}
,"alternative":{"explicit":1}
,"works":{"filter":1}
,"filter":{"values":1,"example":1}
,"values":{"provide":1}
,"provide":{"members":1}
,"share":{"common":1}
,"common":{"attribute":1}
,"attributes":{"defined":1}
,"defined":{"memberurl":1}
,"memberurl":{"filter":1}
,"suppose":{"organization":1}
,"organization":{"two":1}
,"two":{"departments":1}
,"departments":{"admin":1}
,"departmentnumber":{"members":1,"admin":1}
,"department":{"equivalent":1,"configure":1}
,"equivalent":{"operator":1}
,"configure":{"follows":1}
,"follows":{"prompt":1}
,"ldap:\u002F\u002F10.60.29.212:389":{"directory":1}
,"dc=igomega":{"dc=com":1}
,"ldap:\u002F\u002Ftmcoperatoruser3@10.60.29.212:389":{"keychain":1}
}
;Search.control.loadWordPairs(pairs);
