var pairs =
{
"configuration":{"questions":1,"elements":1,"details":1,"guide":1,"element)":1,"attributes":1,"file":1,"ehcache.xml":1}
,"questions":{"source":1}
,"source":{"code":1}
,"code":{"bigmemory":1,"tell":1,"checking":1}
,"bigmemory":{"open-source":1,"single":1,"kit":1,"auto-versioning":1,"offers":1,"configuration":1,"developer":1,"memory":1,"disk":1,"targeted":1,"off-heap":1,"guaranteed":1,"second-level":1,"outside":1,"ehcache.xml":1}
,"open-source":{"product":1,"caching":1}
,"product":{"open-source":1}
,"caching":{"project":1,"write-through":1,"writes":1,"uses":1}
,"project":{"instance":1}
,"instance":{"bigmemory":1}
,"single":{"jvm":1}
,"jvm":{"create":1,"restarts":1}
,"create":{"cachemanager":1}
,"cachemanager":{"using":1,"keep":1,"separate":1}
,"using":{"new":1,"sizing":1,"-xss":1}
,"new":{"cachemanager":1,"ones":1}
,"keep":{"hold":1}
,"hold":{"reference":1}
,"reference":{"singleton":1}
,"singleton":{"approach":1}
,"approach":{"accessible":1}
,"accessible":{"getinstance":1,"multiple":1}
,"getinstance":{"method":1}
,"method":{"available":1}
,"available":{"however":1,"write-through":1}
,"however":{"hundreds":1,"write":1,"minimize":1,"getobjectvalue":1}
,"hundreds":{"caches":1}
,"caches":{"supported":1,"bigmemory":1,"auto-versioning":1,"hibernate":1,"interact":1}
,"supported":{"cachemanager":1,"lru":1,"element":1}
,"separate":{"cachemanagers":1}
,"cachemanagers":{"different":1}
,"different":{"configurations":1}
,"configurations":{"needed":1}
,"needed":{"hibernate":1}
,"hibernate":{"provider":1,"bigmemory":1,"time":1,"names":1,"caches":1}
,"provider":{"updated":1}
,"updated":{"support":1}
,"support":{"behavior":1}
,"behavior":{"elements":1}
,"elements":{"mandatory":1,"auto-versioning":1,"handled":1,"ignored":1,"allowed":1,"memory":1,"bytes":1,"multiplied":1}
,"mandatory":{"ehcache.xml":1}
,"ehcache.xml":{"file":1,"may":1,"configure":1}
,"file":{"ehcache.xsd":1,"systems":1,"per":1}
,"ehcache.xsd":{"bigmemory":1}
,"kit":{"latest":1}
,"latest":{"information":1}
,"information":{"required":1,"javadoc":1}
,"required":{"configuration":1}
,"auto-versioning":{"elements":1,"enable":1,"system":1,"effect":1,"silently":1}
,"handled":{"automatic":1}
,"automatic":{"element":1}
,"element":{"versioning":1,"values":1,"globally":1,"reinsert":1,"bigmemory":1,"removed":1,"exist":1,"programmatically":1,"class":1,"key":1,"element":1,"=cache.get":1,"cache":1,"flushed":1,"added":1,"gets":1,"equality":1,"(key":1}
,"versioning":{"works":1,"cache":1}
,"works":{"memory-store":1}
,"memory-store":{"caches":1}
,"enable":{"auto-versioning":1}
,"system":{"property":1}
,"property":{"net.sf.ehcache.element.version.auto":1,"turned":1}
,"net.sf.ehcache.element.version.auto":{"true":1}
,"true":{"(it":1}
,"(it":{"false":1}
,"false":{"default)":1,"timetoidleseconds=\u0022":1}
,"default)":{"manual":1}
,"manual":{"(user":1}
,"(user":{"provided)":1}
,"provided)":{"versioning":1}
,"cache":{"elements":1,"cause":1,"acts":1,"write-behind":1,"common":1,"outside":1,"per":1,"code":1,"prevent":1,"null":1,"entries":1,"key":1,"however":1,"else":1,"cache":1,"configuration":1,"hibernate":1}
,"ignored":{"auto-versioning":1}
,"effect":{"note":1}
,"note":{"property":1}
,"turned":{"ineligible":1}
,"ineligible":{"caches":1}
,"silently":{"fail":1}
,"fail":{"memory-only":1}
,"memory-only":{"store":1}
,"store":{"persist":1,"just":1,"however":1,"remember":1,"(heap)":1,"without":1,"whether":1,"eternally":1,"expiry":1,"stores":1,"running":1,"diskexpirythreadintervalseconds":1}
,"persist":{"disk":1}
,"disk":{"jvm":1,"persistence":1,"store":1,"stores":1,"clean":1,"store\u0027s":1}
,"restarts":{"bigmemory":1}
,"offers":{"fast":1}
,"fast":{"robust":1,"restart":1}
,"robust":{"disk":1}
,"persistence":{"configuration":1,"strategy":1}
,"details":{"frs":1,"write-through":1,"sizing":1,"ehcache":1,"managing":1}
,"frs":{"description":1}
,"description":{"fast":1}
,"restart":{"(frs)":1}
,"(frs)":{"bigmemory":1}
,"guide":{"recommended":1,"file":1,"thread-safe":1,"attributes":1}
,"recommended":{"write":1}
,"write":{"database":1,"happens":1}
,"database":{"two":1,"bigmemory":1,"excessively":1}
,"two":{"patterns":1}
,"patterns":{"available":1}
,"write-through":{"write-behind":1,"caching":1,"cache":1}
,"write-behind":{"caching":1,"caches":1}
,"writes":{"cache":1,"underlying":1}
,"cause":{"writes":1}
,"underlying":{"resource":1}
,"resource":{"cache":1,"pattern":1,"database":1}
,"acts":{"facade":1}
,"facade":{"underlying":1,"write-through":1}
,"pattern":{"often":1}
,"often":{"makes":1}
,"makes":{"sense":1}
,"sense":{"read":1}
,"read":{"cache":1}
,"uses":{"client":1}
,"client":{"api":1}
,"api":{"however":1}
,"happens":{"asynchronously":1,"maxentrieslocalheap":1}
,"asynchronously":{"details":1,"off-heap":1}
,"developer":{"guide":1}
,"systems":{"web-service":1}
,"web-service":{"clients":1}
,"clients":{"underlie":1}
,"underlie":{"facade":1}
,"common":{"underlying":1}
,"memory":{"store":1,"using":1,"consume":1,"consumed":1,"reached":1,"equal":1,"turns":1,"disk-store":1,"concerned":1}
,"just":{"persistence":1}
,"strategy":{"(in":1}
,"(in":{"<cache>":1}
,"<cache>":{"configuration":1,"<persistence":1}
,"element)":{"none":1}
,"none":{"<cache>":1,"\u0022\u002F>":1,"evicted":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"none":1}
,"\u0022\u002F>":{"<\u002Fcache>":1}
,"<\u002Fcache>":{"bigmemory":1}
,"minimize":{"usage":1}
,"usage":{"memory":1}
,"sizing":{"configuration":1,"storage":1}
,"storage":{"tiers":1}
,"tiers":{"bigmemory":1}
,"thread-safe":{"modify":1}
,"modify":{"element":1,"value":1}
,"values":{"retrieval":1,"place":1,"tested":1,"stored":1,"memory":1}
,"retrieval":{"store":1}
,"remember":{"value":1}
,"value":{"element":1,"safer":1,"delete":1,"updatingcacheentryfactory":1,"signaling":1,"cache.put":1,"=element.getobjectvalue":1,"cache":1,"eviction":1}
,"globally":{"accessible":1}
,"multiple":{"threads":1}
,"threads":{"inherently":1,"bigmemory":1}
,"inherently":{"thread-safe":1}
,"safer":{"retrieve":1}
,"retrieve":{"value":1}
,"delete":{"element":1}
,"reinsert":{"value":1}
,"updatingcacheentryfactory":{"work":1}
,"work":{"modifying":1,"serialization":1}
,"modifying":{"contents":1}
,"contents":{"values":1}
,"place":{"cache":1}
,"outside":{"core":1,"hibernate":1}
,"core":{"bigmemory":1}
,"targeted":{"high":1}
,"high":{"performance":1,"number":1}
,"performance":{"cacheentryfactories":1,"timetoidleseconds":1}
,"cacheentryfactories":{"selfpopulatingcaches":1}
,"selfpopulatingcaches":{"details":1}
,"ehcache":{"javadoc":1}
,"javadoc":{"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Fcache.html":1,"element":1}
,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Fcache.html":{"getquiet":1}
,"getquiet":{"28java.io.serializable":1}
,"28java.io.serializable":{"non-serializable":1}
,"non-serializable":{"objects":1,"object":1,"element":1}
,"objects":{"stored":1}
,"stored":{"non-serializable":1,"bigmemory":1,"cache":1}
,"object":{"stored":1,"value":1}
,"(heap)":{"attempt":1}
,"attempt":{"made":1}
,"made":{"overflow":1}
,"overflow":{"non-serializable":1}
,"off-heap":{"disk":1,"store":1}
,"stores":{"element":1,"in-memory":1,"bigmemory":1}
,"removed":{"warning":1,"used":1}
,"warning":{"logged":1}
,"logged":{"difference":1}
,"difference":{"ttl":1,"intentional":1}
,"ttl":{"tti":1,"settings":1}
,"tti":{"eternal":1,"ttl":1}
,"eternal":{"three":1,"flag":1,"setting":1}
,"three":{"configuration":1}
,"attributes":{"used":1,"configuration":1}
,"used":{"design":1,"(lru)":1,"case":1,"values":1}
,"design":{"effective":1}
,"effective":{"data":1}
,"data":{"lifetimes":1,"life":1,"allowed":1}
,"lifetimes":{"assigned":1}
,"assigned":{"values":1}
,"tested":{"tuned":1}
,"tuned":{"help":1}
,"help":{"optimize":1}
,"optimize":{"performance":1}
,"timetoidleseconds":{"(tti)":1}
,"(tti)":{"maximum":1}
,"maximum":{"number":1,"memory":1,"size":1}
,"number":{"seconds":1,"elements":1,"day":1}
,"seconds":{"element":1}
,"exist":{"store":1,"code":1}
,"without":{"accessed":1}
,"accessed":{"timetoliveseconds":1,"eternal":1,"lru":1}
,"timetoliveseconds":{"(ttl)":1,"setting":1}
,"(ttl)":{"maximum":1}
,"whether":{"accessed":1}
,"flag":{"elements":1}
,"allowed":{"exist":1,"fixed":1}
,"eternally":{"none":1}
,"evicted":{"eternal":1}
,"setting":{"overrides":1,"force":1,"diskexpirythreadintervalseconds":1}
,"overrides":{"tti":1}
,"settings":{"details":1}
,"managing":{"data":1}
,"life":{"bigmemory":1}
,"per":{"cache":1,"element":1,"thread":1}
,"programmatically":{"information":1}
,"class":{"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Felement":1}
,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Felement":{"null":1}
,"null":{"values":1,"value":1,"object":1}
,"tell":{"difference":1}
,"intentional":{"nulls":1}
,"nulls":{"non-existent":1,"versus":1}
,"non-existent":{"entries":1,"cache":1}
,"entries":{"application":1,"may":1}
,"application":{"querying":1}
,"querying":{"database":1}
,"excessively":{"find":1}
,"find":{"result":1}
,"result":{"result":1,"nothing":1}
,"nothing":{"cache":1}
,"prevent":{"query":1}
,"query":{"executed":1}
,"executed":{"unnecessarily":1}
,"unnecessarily":{"cache":1}
,"signaling":{"particular":1}
,"particular":{"key":1}
,"key":{"doesn\u0027t":1,"null))":1,"(element":1,"(or":1}
,"doesn\u0027t":{"exist":1}
,"checking":{"intentional":1}
,"versus":{"non-existent":1}
,"may":{"look":1,"null":1}
,"look":{"\u002F\u002Fcache":1,"similar":1}
,"\u002F\u002Fcache":{"explicit":1}
,"explicit":{"null":1}
,"cache.put":{"(new":1}
,"(new":{"element":1}
,"null))":{"element":1}
,"=cache.get":{"key":1}
,"(element":{"==null)":1}
,"==null)":{"{\u002F\u002Fnothing":1,"{\u002F\u002Fa":1}
,"{\u002F\u002Fnothing":{"cache":1}
,"(or":{"expired)":1}
,"expired)":{"else":1}
,"else":{"{\u002F\u002Fthere":1,"{\u002F\u002Fa":1}
,"{\u002F\u002Fthere":{"valid":1}
,"valid":{"element":1}
,"getobjectvalue":{"may":1}
,"=element.getobjectvalue":{"(value":1}
,"(value":{"==null)":1}
,"{\u002F\u002Fa":{"null":1,"non-null":1}
,"non-null":{"value":1}
,"similar":{"following":1}
,"following":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"name=\u0022":{"some.cache.name":1}
,"some.cache.name":{"maxentrieslocalheap=\u0022":1}
,"maxentrieslocalheap=\u0022":{"10000":1}
,"10000":{"eternal=\u0022":1}
,"eternal=\u0022":{"false":1}
,"timetoidleseconds=\u0022":{"300":1}
,"300":{"timetoliveseconds=\u0022":1}
,"timetoliveseconds=\u0022":{"600":1}
,"600":{"finite":1}
,"finite":{"timetoliveseconds":1}
,"force":{"occasional":1}
,"occasional":{"update":1}
,"update":{"threads":1}
,"consume":{"amount":1}
,"amount":{"memory":1}
,"consumed":{"per":1}
,"thread":{"determined":1,"disk":1,"memory":1,"keeps":1}
,"determined":{"stack":1}
,"stack":{"size":1}
,"size":{"using":1,"element":1,"lru":1}
,"-xss":{"happens":1}
,"maxentrieslocalheap":{"reached":1}
,"reached":{"oldest":1,"least":1}
,"oldest":{"items":1}
,"items":{"expired":1}
,"expired":{"new":1}
,"ones":{"maximum":1}
,"least":{"recently":1}
,"recently":{"used":1}
,"(lru)":{"element":1}
,"case":{"means":1}
,"means":{"inserted":1}
,"inserted":{"put":1}
,"put":{"accessed":1}
,"lru":{"element":1,"lfu":1}
,"flushed":{"asynchronously":1,"disk":1}
,"expiry":{"thread":1,"need":1}
,"in-memory":{"data":1}
,"fixed":{"maximum":1}
,"bytes":{"maximum":1}
,"equal":{"number":1}
,"multiplied":{"average":1}
,"average":{"size":1,"memory":1}
,"added":{"beyond":1}
,"beyond":{"maximum":1}
,"gets":{"flushed":1}
,"running":{"expiry":1}
,"turns":{"expensive":1}
,"expensive":{"operation":1}
,"operation":{"potentially":1}
,"potentially":{"contentious":1}
,"contentious":{"far":1}
,"far":{"efficient":1}
,"efficient":{"check":1}
,"check":{"expiry":1}
,"need":{"rather":1}
,"rather":{"explicitly":1}
,"explicitly":{"search":1}
,"search":{"tradeoff":1}
,"tradeoff":{"higher":1}
,"higher":{"average":1}
,"disk-store":{"expiry":1}
,"keeps":{"disk":1}
,"clean":{"hopefully":1}
,"hopefully":{"less":1}
,"less":{"contention":1}
,"contention":{"disk":1}
,"store\u0027s":{"locks":1}
,"locks":{"commonly":1}
,"commonly":{"used":1}
,"concerned":{"cpu":1}
,"cpu":{"utilization":1}
,"utilization":{"locking":1}
,"locking":{"disk":1}
,"diskexpirythreadintervalseconds":{"high":1,"large":1}
,"day":{"effectively":1}
,"effectively":{"turn":1}
,"turn":{"setting":1}
,"large":{"value":1}
,"eviction":{"strategies":1}
,"strategies":{"supported":1}
,"lfu":{"fifo":1}
,"fifo":{"eviction":1}
,"equality":{"work":1}
,"serialization":{"mode":1}
,"mode":{"element":1}
,"(key":{"value)":1}
,"value)":{"bigmemory":1}
,"guaranteed":{".equals":1}
,".equals":{"moves":1}
,"moves":{"stores":1}
,"second-level":{"cache":1}
,"time":{"instance":1}
,"configure":{"caches":1}
,"names":{"hibernate":1}
,"interact":{"directly":1}
,"directly":{"outside":1}
}
;Search.control.loadWordPairs(pairs);
