var pairs =
{
"installing":{"bigmemory":1}
,"bigmemory":{"installing":1,"easy":1,"bigmemory":1,"kit":1,"slf4j-api-<version>":1,"logging":1,"license-key":1,"home":1,"download":1,"uses":1,"create":1,"write":1,"localrestartable":1,"configuration":1,"information":1,"code":1}
,"easy":{"downloading":1}
,"downloading":{"kit":1}
,"kit":{"ensuring":1,"download":1,"packaged":1,"-xx:maxdirectmemorysize":1,"examples":1}
,"ensuring":{"correct":1}
,"correct":{"files":1}
,"files":{"application\u0027s":1,"bigmemory":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"platform":1,"ehcache-ee-<version>":1,"explicitly":1,"information":1}
,"platform":{"requirement":1}
,"requirement":{"using":1}
,"using":{"jdk":1,"-xmx":1}
,"jdk":{"1.6":1}
,"1.6":{"higher":1}
,"higher":{"install":1}
,"install":{"bigmemory":1}
,"download":{"http:\u002F\u002Fterracotta.org\u002Fdownloads\u002Fbigmemorygo":1,"alternatively":1,"kit":1}
,"http:\u002F\u002Fterracotta.org\u002Fdownloads\u002Fbigmemorygo":{"kit":1}
,"packaged":{"tar.gz":1}
,"tar.gz":{"file":1}
,"file":{"unpack":1,"contains":1,"bridge":1,"bigmemory":1,"called":1,"application\u0027s":1,"described":1,"specify":1,"ehcache.xml":1,"config-samples":1}
,"unpack":{"command":1}
,"command":{"line":1}
,"line":{"appropriate":1}
,"appropriate":{"decompression":1}
,"decompression":{"application":1}
,"application":{"following":1,"example":1}
,"following":{"jars":1}
,"jars":{"found":1}
,"found":{"kit\u0027s":1}
,"kit\u0027s":{"lib":1}
,"lib":{"directory":1}
,"directory":{"added":1,"file":1,"bigmemory":1}
,"added":{"application\u0027s":1}
,"ehcache-ee-<version>":{".jar":1}
,".jar":{"file":1}
,"contains":{"api":1}
,"api":{"bigmemory":1}
,"slf4j-api-<version>":{".jar":1}
,"bridge":{"logging":1}
,"logging":{"facade":1,"framework":1}
,"facade":{"bigmemory":1}
,"framework":{"save":1}
,"save":{"bigmemory":1}
,"license-key":{"file":1}
,"home":{"directory":1}
,"called":{"terracotta-license.key":1}
,"terracotta-license.key":{"attached":1}
,"attached":{"email":1}
,"email":{"received":1}
,"received":{"registering":1}
,"registering":{"bigmemory":1}
,"alternatively":{"add":1}
,"add":{"license":1}
,"license":{"key":1,"file":1,"files":1}
,"key":{"file":1}
,"explicitly":{"specify":1}
,"specify":{"location":1,"off-heap":1}
,"location":{"license":1}
,"described":{"working":1}
,"working":{"terracotta":1}
,"terracotta":{"license":1}
,"uses":{"ehcache":1}
,"ehcache":{"user-facing":1,"configuration":1}
,"user-facing":{"interface":1}
,"interface":{"configure":1}
,"configure":{"bigmemory":1}
,"create":{"update":1}
,"update":{"ehcache":1}
,"configuration":{"file":1,"options":1,"guide":1,"plus":1}
,"off-heap":{"in-memory":1,"memory":1,"storage":1}
,"in-memory":{"storage":1,"data":1}
,"storage":{"want":1,"specified":1}
,"want":{"may":1,"memory":1,"depending":1}
,"may":{"configure":1}
,"write":{"data":1}
,"data":{"local":1,"disk":1,"without":1,"physical":1}
,"local":{"disk":1}
,"disk":{"store":1,"-->":1}
,"store":{"fast":1}
,"fast":{"restart":1}
,"restart":{"example":1,"(optional)":1}
,"example":{"<ehcache":1,"-dcom.tc.productkey.path=\u002Fpath\u002Fto\u002Fterracotta-license.key":1,"xmx1g":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"mybigmemorygoconfig":1,"mybigmemorygostore":1}
,"mybigmemorygoconfig":{"<!--tell":1}
,"<!--tell":{"bigmemory":1}
,"-->":{"<diskstore":1,"<cache":1,"<persistence":1}
,"<diskstore":{"path=\u0022\u002Fpath\u002Fto\u002Fmy\u002Fdisk\u002Fstore\u002Fdirectory":1}
,"path=\u0022\u002Fpath\u002Fto\u002Fmy\u002Fdisk\u002Fstore\u002Fdirectory":{"\u0022\u002F>":1}
,"\u0022\u002F>":{"<!--set":1,"<\u002Fcache>":1}
,"<!--set":{"maxbyteslocaloffheap":1}
,"maxbyteslocaloffheap":{"amount":1}
,"amount":{"off-heap":1,"bigmemory":1}
,"memory":{"want":1,"invisible":1,"single":1,"jvm":1,"usage":1}
,"invisible":{"java":1}
,"java":{"garbage":1,"option":1}
,"garbage":{"collector":1,"collection":1}
,"collector":{"providing":1}
,"providing":{"gigabytes":1}
,"gigabytes":{"terabytes":1,"multiple":1}
,"terabytes":{"in-memory":1,"off-heap":1}
,"without":{"garbage":1}
,"collection":{"pauses":1,"name":1}
,"pauses":{"-->":1}
,"<cache":{"name=\u0022":1}
,"mybigmemorygostore":{"maxbyteslocalheap=\u0022":1}
,"maxbyteslocalheap=\u0022":{"512m":1}
,"512m":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"32g":1}
,"32g":{"<!--tell":1}
,"localrestartable":{"persistence":1,"\u0022\u002F>":1}
,"persistence":{"strategy":1}
,"strategy":{"fast":1}
,"(optional)":{"-->":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"localrestartable":1}
,"<\u002Fcache>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"maxbyteslocaloffheap":1}
,"depending":{"data":1}
,"physical":{"ram":1}
,"ram":{"available":1}
,"available":{"just":1}
,"just":{"few":1}
,"few":{"gigabytes":1}
,"multiple":{"terabytes":1}
,"single":{"jvm":1}
,"jvm":{"ultra-fast":1,"accomodate":1,"bigmemory":1}
,"ultra-fast":{"access":1}
,"access":{"garbage":1}
,"name":{"configuration":1}
,"ehcache.xml":{"place":1,"configuration":1}
,"place":{"top-level":1}
,"top-level":{"classpath":1}
,"information":{"configuration":1,"step":1,"code":1}
,"options":{"bigmemory":1}
,"guide":{"reference":1,"allocate":1}
,"reference":{"ehcache.xml":1}
,"config-samples":{"directory":1}
,"-xx:maxdirectmemorysize":{"java":1}
,"option":{"allocate":1,"accommodate":1}
,"allocate":{"enough":1,"least":1}
,"enough":{"direct":1,"heap":1,"extra":1}
,"direct":{"memory":1}
,"accomodate":{"off-heap":1}
,"specified":{"configuration":1}
,"plus":{"least":1,"enough":1}
,"least":{"250mb":1,"enough":1}
,"250mb":{"allow":1}
,"allow":{"direct":1}
,"usage":{"occur":1}
,"occur":{"application":1}
,"-dcom.tc.productkey.path=\u002Fpath\u002Fto\u002Fterracotta-license.key":{"maxdirectmemorysize":1}
,"maxdirectmemorysize":{"amount":1}
,"step":{"allocating":1}
,"allocating":{"direct":1}
,"heap":{"using":1,"run":1}
,"-xmx":{"java":1}
,"accommodate":{"on-heap":1}
,"on-heap":{"storage":1}
,"extra":{"heap":1}
,"run":{"rest":1}
,"rest":{"application":1}
,"xmx1g":{"refer":1}
,"refer":{"download":1}
,"examples":{"employ":1}
,"employ":{"various":1}
,"various":{"features":1}
,"features":{"capabilities":1}
,"capabilities":{"bigmemory":1}
,"code":{"samples":1}
,"samples":{"bigmemory":1,"online":1}
,"online":{"documentation":1}
,"documentation":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
