var pairs =
{
"using":{"querymanager":1}
,"querymanager":{"api":1,"builder":1,"build":1,"{query":1,"querymanager":1,"=querymanagerbuilder":1,"snapshot":1,"built":1}
,"api":{"querymanager":1}
,"builder":{"interface":1}
,"interface":{"<<this":1,"public":1,"querymanager":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"bigmemory":1}
,"bigmemory":{"sql":1}
,"sql":{"searches":1,"specify":1,"select":1}
,"searches":{"performed":1}
,"performed":{"using":1}
,"public":{"final":1,"querymanagerbuilder":1,"querymanager":1,"interface":1}
,"final":{"class":1}
,"class":{"querymanagerbuilder":1}
,"querymanagerbuilder":{"{public":1,"newquerymanagerbuilder":1,"addcache":1,"addallcachescurrentlyin":1}
,"{public":{"static":1}
,"static":{"querymanagerbuilder":1}
,"newquerymanagerbuilder":{"public":1}
,"addcache":{"(ehcache":1}
,"(ehcache":{"cache)":1}
,"cache)":{"public":1}
,"addallcachescurrentlyin":{"(cachemanager":1}
,"(cachemanager":{"cachemanager)":1}
,"cachemanager)":{"{for":1}
,"{for":{"(string":1}
,"(string":{"cachemanager.getcachenames":1,"querystring)":1}
,"cachemanager.getcachenames":{"())":1}
,"())":{"{final":1}
,"{final":{"ehcache":1}
,"ehcache":{"cache":1}
,"cache":{"=cachemanager.getehcache":1,"searched":1}
,"=cachemanager.getehcache":{"(s)":1}
,"(s)":{"public":1}
,"build":{"public":1,"querymanager":1,"new":1}
,"{query":{"createquery":1}
,"createquery":{"(string":1,"method":1}
,"querystring)":{"specifying":1}
,"specifying":{"caches":1,"query":1}
,"caches":{"query":1,"following":1,"cachemanagers":1,"added":1}
,"query":{"explicitly":1,"specifying":1,"createquery":1,"query":1,"=querymanager.createquery":1}
,"explicitly":{"add":1}
,"add":{"cache":1}
,"searched":{"bigmemory":1}
,"specify":{"cachemanager":1}
,"cachemanager":{"contains":1}
,"contains":{"caches":1}
,"following":{"example":1}
,"example":{"querymanager":1}
,"=querymanagerbuilder":{".newquerymanagerbuilder":1}
,".newquerymanagerbuilder":{".addcache":1}
,".addcache":{"(cache1)":1,"(cache2)":1}
,"(cache1)":{".addcache":1}
,"(cache2)":{".addallcachescurrentlyin":1}
,".addallcachescurrentlyin":{"(cachemanager1)":1,"(cachemanager2)":1}
,"(cachemanager1)":{".addallcachescurrentlyin":1}
,"(cachemanager2)":{".build":1}
,".build":{"build":1}
,"snapshot":{"state":1}
,"state":{"cachemanagers":1}
,"cachemanagers":{"caches":1}
,"added":{"removed":1}
,"removed":{"build":1}
,"new":{"querymanager":1}
,"built":{"issuing":1}
,"issuing":{"query":1}
,"method":{"takes":1}
,"takes":{"string":1}
,"string":{"argument":1}
,"argument":{"represents":1}
,"represents":{"bigmemory":1}
,"select":{"clause":1}
,"clause":{"query":1}
,"=querymanager.createquery":{"querystring":1}
}
;Search.control.loadWordPairs(pairs);
