var pairs =
{
"example":{"declarative":1,"available":1,"shows":1}
,"declarative":{"configuration":1}
,"configuration":{"following":1,"file":1,"api":1,"element":1}
,"following":{"description":1,"example":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1,"server":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"configure":1}
,"configure":{"bigmemory":1,"basic":1}
,"bigmemory":{"declaratively":1,"=manager.getcache":1,"\u002F\u002Fnow":1,"maxbyteslocalheap=\u0022":1,"unique":1}
,"declaratively":{"using":1,"xml":1}
,"using":{"xml":1}
,"xml":{"configuration":1,"file":1}
,"file":{"programmatically":1,"configure":1,"create":1,"name":1,"classpath":1,"used":1}
,"programmatically":{"via":1}
,"via":{"fluent":1}
,"fluent":{"configuration":1}
,"api":{"sample":1}
,"sample":{"shows":1,"<ehcache":1}
,"shows":{"configure":1,"create":1}
,"basic":{"instance":1}
,"instance":{"bigmemory":1,"passing":1}
,"create":{"cachemanager":1}
,"cachemanager":{"instance":1,"url":1,"manager":1}
,"passing":{"file":1}
,"name":{"url":1}
,"url":{"object":1,"xml":1}
,"object":{"constructor":1}
,"constructor":{"following":1}
,"classpath":{"\u002Fxml\u002Fehcache.xml":1}
,"\u002Fxml\u002Fehcache.xml":{"cachemanager":1}
,"manager":{"=cachemanager.newinstance":1}
,"=cachemanager.newinstance":{"(getclass":1}
,"(getclass":{".getresource":1}
,".getresource":{"(\u0022\u002Fxml\u002Fehcache.xml":1}
,"(\u0022\u002Fxml\u002Fehcache.xml":{"\u0022))":1}
,"\u0022))":{"try":1}
,"try":{"{cache":1}
,"{cache":{"bigmemory":1}
,"=manager.getcache":{"bigmemory":1}
,"\u002F\u002Fnow":{"stuff":1}
,"stuff":{"finally":1}
,"finally":{"{if":1}
,"{if":{"(manager":1}
,"(manager":{"!=null)":1}
,"!=null)":{"manager.shutdown":1}
,"manager.shutdown":{"contents":1}
,"contents":{"xml":1}
,"used":{"sample":1}
,"<ehcache":{"xmlns:xsi=\u0022":1}
,"xmlns:xsi=\u0022":{"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":1}
,"http:\u002F\u002Fwww.w3.org\u002F2001\u002Fxmlschema-instance":{"xsi:nonamespaceschemalocation=\u0022":1}
,"xsi:nonamespaceschemalocation=\u0022":{"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":1}
,"http:\u002F\u002Fehcache.org\u002Fehcache.xsd":{"name=\u0022":1}
,"name=\u0022":{"config":1,"bigmemory":1}
,"config":{"<cache":1}
,"<cache":{"name=\u0022":1}
,"maxbyteslocalheap=\u0022":{"512m":1}
,"512m":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"32g":1}
,"32g":{"copyonread=\u0022":1}
,"copyonread=\u0022":{"true":1}
,"true":{"statistics=\u0022":1,"eternal=\u0022":1,"<\u002Fcache>":1}
,"statistics=\u0022":{"true":1}
,"eternal=\u0022":{"true":1}
,"<\u002Fcache>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"configuration":1}
,"element":{"maxbyteslocaloffheap":1}
,"maxbyteslocaloffheap":{"lets":1}
,"lets":{"off-heap":1,"memory":1}
,"off-heap":{"memory":1}
,"memory":{"bigmemory":1,"storage":1,"available":1}
,"unique":{"off-heap":1}
,"storage":{"lets":1}
,"server":{"single":1}
,"single":{"jvm":1}
,"jvm":{"gigabytes":1}
,"gigabytes":{"multiple":1}
,"multiple":{"terabytes":1}
,"terabytes":{"without":1}
,"without":{"causing":1}
,"causing":{"garbage":1}
,"garbage":{"collection":1}
,"collection":{"pauses":1}
}
;Search.control.loadWordPairs(pairs);
