var pairs =
{
"data":{"persistence":1,"persists":1,"last":1,"option":1,"storage":1,"none":1,"disk":1,"kept":1,"recovered":1,"may":1,"synchronously":1,"consistency":1}
,"persistence":{"implementation":1,"configured":1,"localtempswap":1,"therefore":1}
,"implementation":{"<<this":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1,"strategy":1}
,"product":{"docs.>>":1}
,"docs.>>":{"bigm":1}
,"bigm":{"bigmemory":1}
,"bigmemory":{"fast":1,"data":1}
,"fast":{"restart":1,"restartability":1}
,"restart":{"feature":1,"store":1,"data":1,"disk":1}
,"feature":{"works":1,"automatically":1,"disk":1}
,"works":{"creating":1}
,"creating":{"real-time":1}
,"real-time":{"record":1}
,"record":{"in-memory":1,"data":1}
,"in-memory":{"data":1}
,"persists":{"fast":1}
,"store":{"local":1,"back":1,"persisted":1,"path":1,"size":1}
,"local":{"disk":1}
,"disk":{"restart":1,"usage":1,"cleared":1,"option":1,"times":1,"happen":1,"write":1,"happens":1,"files":1,"store":1,"tier":1,"persistence":1}
,"last":{"memory":1,"synced":1,"2-3":1}
,"memory":{"(both":1,"data":1,"default":1}
,"(both":{"heap":1}
,"heap":{"off-heap":1}
,"off-heap":{"stores)":1}
,"stores)":{"automatically":1}
,"automatically":{"loads":1,"logs":1}
,"loads":{"fast":1}
,"back":{"memory":1}
,"configured":{"adding":1,"options":1,"<diskstore>":1,"localrestartable":1,"localtempswap":1}
,"adding":{"<persistence>":1}
,"<persistence>":{"sub-element":1}
,"sub-element":{"cache":1,"includes":1,"ehcache":1}
,"cache":{"configuration":1,"operations":1}
,"configuration":{"<persistence>":1,"localrestartable":1}
,"includes":{"two":1}
,"two":{"attributes":1}
,"attributes":{"strategy":1}
,"strategy":{"synchronouswrites":1,"options":1,"attribute":1}
,"synchronouswrites":{"<<in":1,"attribute":1,"synchronouswrites=\u0022":1,"false":1,"soft":1}
,"<<in":{"following":1}
,"following":{"code":1}
,"code":{"sample":1}
,"sample":{"distributed":1}
,"distributed":{"option":1}
,"option":{"marked":1,"provides":1,"working":1,"specifies":1,"faster":1,"slower":1}
,"marked":{"bmm":1}
,"options":{"options":1,"strategy":1,"synchronouswrites":1}
,"attribute":{"localrestartable":1,"configured":1}
,"localrestartable":{"enables":1,"synchronouswrites":1,"unique":1,"disk":1}
,"enables":{"fast":1,"temporary":1}
,"logs":{"bigmemory":1}
,"provides":{"fast":1,"extra":1,"full":1}
,"restartability":{"fault-tolerant":1}
,"fault-tolerant":{"data":1}
,"localtempswap":{"enables":1,"disk":1,"measures":1}
,"temporary":{"local":1}
,"usage":{"option":1}
,"extra":{"tier":1}
,"tier":{"data":1,"default":1,"conventional":1}
,"storage":{"during":1}
,"during":{"operation":1}
,"operation":{"store":1}
,"persisted":{"restart":1}
,"cleared":{"bigmemory":1,"next":1}
,"none":{"offload":1}
,"offload":{"data":1}
,"working":{"data":1}
,"kept":{"memory":1,"disk":1}
,"default":{"mode":1,"synchronouswrites":1,"path":1}
,"mode":{"synchronous":1}
,"synchronous":{"writes":1}
,"writes":{"options":1,"disk":1}
,"synchronouswrites=\u0022":{"false":1,"true":1}
,"false":{"option":1,"synchronouswrites=\u0022":1,"crash":1}
,"specifies":{"eventually":1,"fully":1}
,"eventually":{"consistent":1}
,"consistent":{"record":1}
,"times":{"writes":1,"changes":1}
,"happen":{"efficient":1}
,"efficient":{"cache":1}
,"operations":{"proceed":1}
,"proceed":{"without":1}
,"without":{"waiting":1}
,"waiting":{"acknowledgement":1}
,"acknowledgement":{"writing":1}
,"writing":{"disk":1}
,"recovered":{"last":1,"exactly":1}
,"synced":{"option":1}
,"faster":{"synchronouswrites=\u0022":1}
,"true":{"crash":1,"option":1}
,"crash":{"last":1,"provides":1,"middle":1}
,"2-3":{"seconds":1}
,"seconds":{"written":1}
,"written":{"data":1}
,"may":{"lost":1}
,"lost":{"specified":1}
,"specified":{"default":1,"path":1}
,"fully":{"consistent":1}
,"changes":{"made":1}
,"made":{"data":1}
,"synchronously":{"recorded":1}
,"recorded":{"disk":1}
,"write":{"disk":1}
,"happens":{"return":1}
,"return":{"caller":1,"zero":1,"size":1}
,"caller":{"restart":1}
,"exactly":{"shutdown":1}
,"shutdown":{"option":1}
,"slower":{"synchronouswrites=\u0022":1}
,"full":{"data":1}
,"consistency":{"transaction":1}
,"transaction":{"caching":1,"upon":1}
,"caching":{"synchronouswrites":1}
,"soft":{"locks":1}
,"locks":{"used":1,"cleared":1}
,"used":{"protect":1,"disk":1}
,"protect":{"access":1}
,"access":{"crash":1,"diskstore":1}
,"middle":{"transaction":1}
,"upon":{"recovery":1}
,"recovery":{"soft":1}
,"next":{"access":1}
,"diskstore":{"path":1}
,"path":{"path":1,"directory":1,"required":1,"specified":1,"used":1,"auto-resolved":1}
,"directory":{"required":1}
,"required":{"disk":1,"localtempswap":1}
,"files":{"created":1}
,"created":{"configured":1}
,"<diskstore>":{"sub-element":1}
,"ehcache":{"configuration":1}
,"unique":{"explicitly":1}
,"explicitly":{"specified":1}
,"auto-resolved":{"case":1}
,"case":{"conflict":1}
,"conflict":{"cachemanager":1}
,"cachemanager":{"fast":1}
,"conventional":{"disk":1}
,"therefore":{"configured":1}
,"size":{"measures":1,"values":1}
,"measures":{"cache.getdiskstoresize":1,"return":1}
,"cache.getdiskstoresize":{"cache.calculateondisksize":1}
,"cache.calculateondisksize":{"applicable":1}
,"applicable":{"return":1}
,"zero":{"hand":1}
,"hand":{"configured":1}
}
;Search.control.loadWordPairs(pairs);
