var pairs =
{
"connections":{"errors":1}
,"errors":{"connection":1,"containing":1}
,"connection":{"refused":1,"managed":1,"setup":1,"node":1,"found":1,"returns":1,"causes":1,"timed":1,"fails":1,"attempted":1,"problem":1,"cause":1,"agent":1,"errors)":1}
,"refused":{"problem":1}
,"problem":{"attempt":1}
,"attempt":{"add":1}
,"add":{"connection":1,"entry":1}
,"managed":{"agent":1}
,"agent":{"rejected":1,"unreachable":1,"working":1,"process":1,"within":1,"ssl":1,"missing":1,"identity":1,"using":1,"configured":1,"log":1}
,"rejected":{"cause":1}
,"cause":{"agent":1,"uri":1,"unsecure":1,"secure":1,"connection":1,"agent\u0027s":1,"tms":1}
,"unreachable":{"running":1}
,"running":{"solution":1,"agent":1,"expected":1}
,"solution":{"check":1,"ensure":1,"add":1,"import":1}
,"check":{"following":1}
,"following":{"uri":1}
,"uri":{"connection":1,"used":1,"correct":1,"using":1}
,"setup":{"correct":1,"incorrect":1}
,"correct":{"network":1,"port":1,"(by":1}
,"network":{"connection":1}
,"node":{"running":1,"404":1,"unexpected":1}
,"working":{"agent":1}
,"process":{"running":1}
,"expected":{"node":1}
,"404":{"connection":1,"status":1}
,"found":{"problem":1,"cause":1,"tms":1,"agent\u0027s":1}
,"returns":{"404":1,"401":1}
,"status":{"code":1}
,"code":{"cause":1,"errors":1}
,"used":{"connection":1,"uri":1}
,"incorrect":{"malformed":1}
,"malformed":{"solution":1}
,"port":{"used":1}
,"(by":{"default":1}
,"default":{"9888":1}
,"9888":{"bigmemory":1}
,"bigmemory":{"9540":1,"max)":1}
,"9540":{"bigmemory":1}
,"max)":{"message":1,"connection":1}
,"message":{"body":1,"plaintext":1}
,"body":{"reader":1}
,"reader":{"java":1}
,"java":{"class":1,"type":1}
,"class":{"found":1,"java.util.collection":1}
,"causes":{"exception":1}
,"exception":{"message":1}
,"java.util.collection":{"java":1,"mime":1}
,"type":{"java.util.collection":1,"unknown\u002Funknown":1}
,"mime":{"media":1}
,"media":{"type":1}
,"unknown\u002Funknown":{"found":1}
,"timed":{"problem":1}
,"fails":{"tms":1,"eof":1,"error":1}
,"tms":{"failed":1,"keychain":1,"truststore":1,"log":1,"public":1}
,"failed":{"reach":1,"sun.security.provider.certpath.suncertpathbuilderexception":1}
,"reach":{"agent":1}
,"within":{"timeout":1}
,"timeout":{"limit":1}
,"limit":{"cause":1}
,"unexpected":{"end":1}
,"end":{"file":1}
,"file":{"server":1}
,"server":{"problem":1}
,"eof":{"error":1}
,"error":{"cause":1,"unrecognized":1,"missing":1}
,"unsecure":{"connection":1}
,"attempted":{"agent":1}
,"ssl":{"solution":1,"message":1,"agent":1,"returns":1,"connection":1}
,"ensure":{"uri":1}
,"using":{"https:\u002F\u002F\u0022":1,"http:\u002F\u002F\u0022":1,"add-tc-agent":1}
,"https:\u002F\u002F\u0022":{"http:\u002F\u002F":1,"ssl":1}
,"http:\u002F\u002F":{"unrecognized":1}
,"unrecognized":{"ssl":1}
,"plaintext":{"connection":1}
,"secure":{"connection":1}
,"http:\u002F\u002F\u0022":{"https:\u002F\u002F\u0022":1}
,"missing":{"keychain":1}
,"keychain":{"entry":1,"cannot":1}
,"entry":{"problem":1,"url":1,"solution":1,"agent":1}
,"url":{"<agent-url>":1}
,"<agent-url>":{"cause":1}
,"identity":{"assertion":1}
,"assertion":{"tms":1,"returns":1,"ssl":1}
,"cannot":{"find":1,"found":1}
,"find":{"agent\u0027s":1,"valid":1}
,"agent\u0027s":{"entry":1,"public":1,"truststore":1}
,"add-tc-agent":{"script":1}
,"script":{"(see":1}
,"(see":{"setting":1,"logged":1}
,"setting":{"security)":1}
,"security)":{"401":1,"problem":1}
,"401":{"unauthorized":1,"status":1}
,"unauthorized":{"problem":1}
,"configured":{"identity":1}
,"public":{"key":1}
,"key":{"cannot":1,"tms":1,"agent\u0027s":1}
,"truststore":{"solution":1,"(see":1}
,"import":{"agent\u0027s":1,"tms":1}
,"containing":{"unknown_certificate":1}
,"unknown_certificate":{"pkix":1}
,"pkix":{"path":1}
,"path":{"building":1,"requested":1}
,"building":{"failed":1}
,"sun.security.provider.certpath.suncertpathbuilderexception":{"unable":1}
,"unable":{"find":1}
,"valid":{"certification":1}
,"certification":{"path":1}
,"requested":{"target":1}
,"target":{"appear":1}
,"appear":{"agent":1}
,"log":{"tms":1,"(see":1}
,"logged":{"ssl":1}
,"errors)":{"cause":1}
}
;Search.control.loadWordPairs(pairs);
