var pairs =
{
"searching":{"<<this":1,"bigmemory":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"search":1}
,"search":{"api":1,"32-year-old":1,"index":1,"types":1}
,"api":{"allows":1,"using":1,"attribute":1,"creating":1}
,"allows":{"execute":1}
,"execute":{"arbitrarily":1}
,"arbitrarily":{"complex":1}
,"complex":{"queries":1}
,"queries":{"against":1,"using":1}
,"against":{"caches":1,"element":1}
,"caches":{"development":1}
,"development":{"alternative":1}
,"alternative":{"indexes":1}
,"indexes":{"values":1}
,"values":{"provides":1,"keys":1,"summary":1,"(aggregators)":1,"results":1,"treated":1,"directly":1,"made":1,"attributes":1}
,"provides":{"ability":1}
,"ability":{"data":1}
,"data":{"looked":1}
,"looked":{"based":1}
,"based":{"multiple":1}
,"multiple":{"criteria":1}
,"criteria":{"instead":1}
,"instead":{"just":1}
,"just":{"keys":1}
,"keys":{"searchable":1,"values":1}
,"searchable":{"attributes":1,"information":1,"searches":1,"simply":1,"extracting":1}
,"attributes":{"extracted":1,"element":1,"supported":1,"themselves":1}
,"extracted":{"keys":1}
,"summary":{"values":1}
,"(aggregators)":{"returned":1}
,"returned":{"simple":1}
,"simple":{"example":1}
,"example":{"search":1}
,"32-year-old":{"males":1}
,"males":{"return":1}
,"return":{"cache":1}
,"cache":{"values":1,"configuration":1,"searchable":1}
,"results":{"results":1,"=cache.createquery":1}
,"=cache.createquery":{".includevalues":1}
,".includevalues":{".addcriteria":1,".execute":1}
,".addcriteria":{"(age.eq":1,"(age.gt":1}
,"(age.eq":{"(32)":1}
,"(32)":{".and":1}
,".and":{"(gender.eq":1}
,"(gender.eq":{"male":1}
,"male":{"\u0022)))":1}
,"\u0022)))":{".execute":1}
,".execute":{"bigm":1,"\u002F\u002Fbigmemory":1}
,"bigm":{"formulate":1,"information":1}
,"formulate":{"queries":1}
,"using":{"search":1,"bigmemory":1}
,"bigmemory":{"sql":1}
,"sql":{"\u002F\u002Fbigmemory":1,"querymanager":1,"searching":1,"searchable":1}
,"\u002F\u002Fbigmemory":{"search":1,"sql":1}
,"attribute":{"<integer>":1}
,"<integer>":{"age":1}
,"age":{"=cache.getsearchattribute":1,"person.createquery":1,"creating":1}
,"=cache.getsearchattribute":{"age":1}
,"person.createquery":{".addcriteria":1}
,"(age.gt":{"(30))":1}
,"(30))":{".includevalues":1}
,"querymanager":{"querymanager":1,"=querymanagerbuilder":1}
,"=querymanagerbuilder":{".newquerymanagerbuilder":1}
,".newquerymanagerbuilder":{".addcache":1}
,".addcache":{"(person)":1,"(address)":1}
,"(person)":{".addcache":1}
,"(address)":{".build":1}
,".build":{"query":1}
,"query":{"personquery":1,"cache":1,"bigm":1}
,"personquery":{"=querymanager.createquery":1}
,"=querymanager.createquery":{"select":1}
,"select":{"*from":1}
,"*from":{"person":1}
,"person":{"age":1}
,"creating":{"query":1,"queries":1}
,"configuration":{"prepared":1}
,"prepared":{"described":1}
,"described":{"making":1}
,"making":{"cache":1}
,"information":{"creating":1}
,"searches":{"performed":1}
,"performed":{"against":1}
,"element":{"keys":1}
,"treated":{"attributes":1}
,"directly":{"searchable":1}
,"simply":{"added":1}
,"added":{"search":1}
,"index":{"attributes":1}
,"made":{"searchable":1}
,"extracting":{"attributes":1}
,"supported":{"search":1}
,"types":{"keys":1}
,"themselves":{"searchable":1}
}
;Search.control.loadWordPairs(pairs);
