var pairs =
{
"uri":{"terracotta":1,"used":1,"allows":1,"path":1,"specifies":1,"names":1,"\u002Fagents\u002Fclusters\u002Fcachemanagers\u002Fcaches\u002Fthis":1}
,"terracotta":{"management":1,"client":1}
,"management":{"service":1,"agent":1}
,"service":{"typical":1,"following":1}
,"typical":{"uri":1}
,"used":{"connect":1,"identified":1}
,"connect":{"terracotta":1,"tsa":1,"cache":1}
,"following":{"format":1,"hierarchy":1,"form":1}
,"format":{"<scheme>":1}
,"<scheme>":{":\u002F\u002F<host>":1}
,":\u002F\u002F<host>":{"<port>]\u002F<path>":1}
,"<port>]\u002F<path>":{"<query>":1}
,"<query>":{"uris":1}
,"uris":{"standard":1,"uri":1}
,"standard":{"scheme":1}
,"scheme":{"domain":1,"http":1}
,"domain":{"http":1}
,"http":{"assumed":1,"operations":1}
,"assumed":{"scheme":1}
,"operations":{"access":1}
,"access":{"rest":1,"client":1,"broad":1,"via":1,"offline":1}
,"rest":{"api":1,"interface":1,"apis":1,"interfaces":1,"management":1}
,"api":{"uris":1}
,"allows":{"query":1}
,"query":{"strings":1}
,"strings":{"certain":1}
,"certain":{"circumstances":1}
,"circumstances":{"uri":1}
,"path":{"<path>":1,"takes":1}
,"<path>":{"portion":1}
,"portion":{"uri":1}
,"specifies":{"resource":1}
,"resource":{"locations":1}
,"locations":{"using":1}
,"using":{"following":1,"unique":1,"configured":1}
,"hierarchy":{"agent":1}
,"agent":{"ids":1,"embedded":1,"information":1}
,"ids":{"list":1,"given":1,"used":1}
,"list":{"desired":1,"cachemanagers":1,"caches":1}
,"desired":{"clients":1}
,"clients":{"using":1,"accessed":1}
,"unique":{"identifiers":1}
,"identifiers":{"connection":1}
,"connection":{"tms":1,"made":1}
,"tms":{"ids":1,"interface":1}
,"given":{"known":1,"cachemanagers":1,"caches":1}
,"known":{"clients":1}
,"accessed":{"connection":1,"cache":1,"cachemanagers":1,"case":1}
,"made":{"directly":1}
,"directly":{"terracotta":1}
,"client":{"ids":1,"rest":1,"(agentid":1}
,"identified":{"host:port":1}
,"host:port":{"addresses":1}
,"addresses":{"tsa":1}
,"tsa":{"rest":1,"(agentid":1}
,"interface":{"provide":1,"tsa":1,"determine":1,"returns":1,"access":1,"delete":1}
,"provide":{"access":1}
,"apis":{"need":1}
,"need":{"specify":1}
,"specify":{"agentid":1}
,"agentid":{"connect":1}
,"determine":{"whether":1}
,"whether":{"connecting":1,"(online)":1}
,"connecting":{"client":1}
,"(agentid":{"192.168.99.100_36364":1,"embedded":1}
,"192.168.99.100_36364":{"example)":1}
,"example)":{"tsa":1}
,"embedded":{"standalone":1,"cachemanager":1}
,"standalone":{"(including":1}
,"(including":{"tsa)":1}
,"tsa)":{"rest":1}
,"interfaces":{"return":1}
,"return":{"agent":1}
,"cachemanager":{"names":1}
,"names":{"list":1,"cachemanagers":1,"given":1,"caches":1}
,"cachemanagers":{"using":1,"specified":1,"accessed":1}
,"configured":{"names":1}
,"specified":{"uri":1,"clients":1}
,"cache":{"names":1,"managers":1}
,"caches":{"using":1,"specified":1,"belonging":1,"cluster":1,"interface":1,"longer":1}
,"belonging":{"accessed":1}
,"case":{"access":1}
,"broad":{"substantial":1}
,"substantial":{"amount":1}
,"amount":{"data":1}
,"data":{"returned":1,"anywhere":1}
,"returned":{"operation":1,"cache":1}
,"operation":{"structure":1}
,"structure":{"path":1}
,"takes":{"following":1}
,"form":{"\u002Fagents":1}
,"\u002Fagents":{"ids={comma_sep_agent_ids}]\u002Fcachemanagers":1}
,"ids={comma_sep_agent_ids}]\u002Fcachemanagers":{"names={\u00A0":1}
,"names={\u00A0":{"comma_sep_cache_manager_names}]\u002Fcaches":1}
,"comma_sep_cache_manager_names}]\u002Fcaches":{"names={comma_sep_cache_names}":1}
,"names={comma_sep_cache_names}":{"connect":1}
,"managers":{"caches":1,"and\u002For":1,"regardless":1,"currently":1}
,"cluster":{"agents\u002Fclusters":1}
,"agents\u002Fclusters":{"uri":1}
,"\u002Fagents\u002Fclusters\u002Fcachemanagers\u002Fcaches\u002Fthis":{"interface":1}
,"returns":{"entities":1,"information":1}
,"entities":{"attributes":1}
,"attributes":{"concerning":1}
,"concerning":{"state":1}
,"state":{"clustered":1}
,"clustered":{"cache":1}
,"and\u002For":{"caches":1}
,"via":{"tms":1,"rest":1}
,"information":{"defined":1,"returned":1}
,"defined":{"cache":1}
,"regardless":{"whether":1}
,"(online)":{"(offline)":1}
,"(offline)":{"interface":1}
,"currently":{"offline":1}
,"offline":{"cannot":1,"data":1}
,"cannot":{"access":1}
,"anywhere":{"tms":1}
,"delete":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
