var pairs =
{
"working":{"apache":1,"terracotta":1}
,"apache":{"maven":1}
,"maven":{"<<this":1,"users":1,"repository":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"apache":1}
,"users":{"terracotta":1}
,"terracotta":{"repository":1,"artifacts":1,"projects)":1,"repositories":1,"snapshot":1,"products":1}
,"repository":{"terracotta":1,"url":1}
,"artifacts":{"(including":1,"specific":1}
,"(including":{"ehcache":1}
,"ehcache":{"quartz":1}
,"quartz":{"terracotta":1}
,"projects)":{"using":1}
,"using":{"url":1,"maven":1}
,"url":{"shown":1,"browsable":1}
,"shown":{"<repository>":1}
,"<repository>":{"<id>":1}
,"<id>":{"terracotta-repository":1}
,"terracotta-repository":{"<\u002Fid>":1}
,"<\u002Fid>":{"<url>":1}
,"<url>":{"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":1}
,"http:\u002F\u002Fwww.terracotta.org\u002Fdownload\u002Freflector\u002Freleases":{"<\u002Furl>":1}
,"<\u002Furl>":{"<releases>":1}
,"<releases>":{"<enabled>":1}
,"<enabled>":{"true":1}
,"true":{"<\u002Fenabled>":1}
,"<\u002Fenabled>":{"<\u002Freleases>":1}
,"<\u002Freleases>":{"<\u002Frepository>":1}
,"<\u002Frepository>":{"complete":1}
,"complete":{"list":1}
,"list":{"repositories":1}
,"repositories":{"terracotta":1,"note":1}
,"note":{"following":1}
,"following":{"using":1}
,"browsable":{"intend":1}
,"intend":{"work":1}
,"work":{"terracotta":1}
,"snapshot":{"projects":1}
,"projects":{"(usually":1,"artifact":1}
,"(usually":{"trunk)":1}
,"trunk)":{"working":1}
,"artifact":{"versions":1}
,"versions":{"specific":1,"terracotta":1,"products":1}
,"specific":{"kit":1}
,"kit":{"configuring":1,"guaranteed":1}
,"configuring":{"pom":1}
,"pom":{"artifacts":1}
,"guaranteed":{"compatible":1}
,"compatible":{"certain":1}
,"certain":{"frameworks":1,"spring":1}
,"frameworks":{"including":1}
,"including":{"hibernate":1}
,"hibernate":{"certain":1}
,"spring":{"modules":1}
,"modules":{"may":1}
,"may":{"poms":1,"run":1}
,"poms":{"dependencies":1}
,"dependencies":{"outdated":1,"running":1}
,"outdated":{"versions":1,"dependencies":1}
,"products":{"cause":1,"installed":1,"resulting":1}
,"cause":{"older":1}
,"older":{"versions":1}
,"installed":{"application\u0027s":1}
,"application\u0027s":{"classpath":1}
,"classpath":{"ahead":1}
,"ahead":{"current":1}
,"current":{"versions":1}
,"resulting":{"noclassdeffound":1}
,"noclassdeffound":{"nosuchmethod":1}
,"nosuchmethod":{"errors":1}
,"errors":{"best":1}
,"best":{"application":1}
,"application":{"may":1}
,"run":{"perform":1}
,"perform":{"correctly":1}
,"correctly":{"sure":1}
,"sure":{"locate":1}
,"locate":{"remove":1}
,"remove":{"outdated":1}
,"running":{"maven":1}
}
;Search.control.loadWordPairs(pairs);
