var pairs =
{
"connections":{"global":1,"polling":1,"connections":1,"allow":1,"terracotta":1,"agents":1,"tms":1,"uri":1,"nodes":1,"exist":1,"default":1,"appear":1,"add":1,"panel":1,"managed":1,"list":1,"unsecured":1,"secured":1,"custom":1}
,"global":{"settings":1,"tmc":1}
,"settings":{"click":1,"top":1,"window":1,"toolbar":1,"settings":1,"requires":1}
,"click":{"settings":1,"create":1,"next":1,"red":1,"delete":1,"trash":1,"pencil":1,"save":1,"edit":1,"polling":1,"reset":1,"security":1}
,"top":{"toolbar":1,"home":1}
,"toolbar":{"open":1,"view":1,"connections":1}
,"open":{"window":1}
,"window":{"connections":1,"includes":1,"top":1,"new":1,"click":1}
,"tmc":{"options":1,"default":1,"hang":1,"changing":1}
,"options":{"configured":1}
,"configured":{"settings":1,"tc-config.xml":1,"connections":1}
,"includes":{"connections":1}
,"polling":{"security":1,"period":1,"tab":1,"interval":1,"intervals":1}
,"security":{"panels":1,"settings":1,"tab":1,"choose":1,"used":1,"require":1,"connections":1,"panel":1,"setting":1}
,"panels":{"working":1}
,"working":{"connections":1}
,"allow":{"monitor":1}
,"monitor":{"administer":1,"click":1}
,"administer":{"nodes":1}
,"nodes":{"clustered":1,"participating":1,"typical":1,"polled":1,"lost":1}
,"clustered":{"standalone":1,"connections":1}
,"standalone":{"clustered":1,"connections":1,"connection":1}
,"terracotta":{"server":1,"client":1,"management":1}
,"server":{"arrays":1,"terracotta":1,"array":1,"similar":1,"(tms)":1}
,"arrays":{"connection":1}
,"connection":{"groups":1,"initially":1,"appears":1,"default":1,"click":1,"button":1,"wizard":1,"location":1,"group":1,"create":1,"enter":1,"timeout":1,"unreachable":1,"unresponsive":1,"save":1,"cancel":1,"editing":1,"delete":1,"connection":1,"pane":1,"edit":1,"want":1,"menu":1}
,"groups":{"standalone":1,"simplify":1,"create":1}
,"agents":{"assigned":1,"made":1}
,"assigned":{"groups":1}
,"simplify":{"management":1}
,"management":{"tasks":1,"port":1,"server":1}
,"tasks":{"connections":1}
,"tms":{"agents":1,"running":1,"note":1}
,"made":{"using":1}
,"using":{"location":1}
,"location":{"uri":1,"agent":1,"relative":1,"localhost":1,"group":1,"timeouts":1}
,"uri":{"following":1,"server":1,"terracotta":1,"node":1}
,"following":{"form":1,"changing":1}
,"form":{"<scheme>":1}
,"<scheme>":{"<host-address>":1}
,"<host-address>":{"<port>":1}
,"<port>":{"uris":1}
,"uris":{"showing":1}
,"showing":{"http":1}
,"http":{"non-secure":1}
,"non-secure":{"connections":1}
,"array":{"nodes":1}
,"participating":{"cluster":1}
,"cluster":{"automatically":1,"connection":1,"group":1}
,"automatically":{"found":1}
,"found":{"required":1,"given":1,"warning":1}
,"required":{"create":1}
,"create":{"separate":1,"new":1,"connection":1}
,"separate":{"connections":1}
,"typical":{"uri":1}
,"similar":{"http:\u002F\u002Fmyserver:9540":1,"http:\u002F\u002Fmyhost:9888":1}
,"http:\u002F\u002Fmyserver:9540":{"address":1}
,"address":{"resolvable":1}
,"resolvable":{"hostname":1}
,"hostname":{"followed":1}
,"followed":{"management-port":1,"agent\u0027s":1}
,"management-port":{"number":1}
,"number":{"(9540":1}
,"(9540":{"default)":1}
,"default)":{"port":1,"node\u0027s":1}
,"port":{"configured":1,"(9888":1,"specified":1}
,"tc-config.xml":{"typical":1}
,"client":{"bigmemory":1}
,"bigmemory":{"appear":1,"example":1}
,"appear":{"similar":1,"unavailable":1,"connections":1}
,"http:\u002F\u002Fmyhost:9888":{"address":1}
,"agent\u0027s":{"management":1}
,"(9888":{"default)":1}
,"node\u0027s":{"configuration":1}
,"configuration":{"file":1,"information":1}
,"file":{"bigmemory":1}
,"example":{"managementrestservice":1}
,"managementrestservice":{"element":1}
,"element":{"ehcache.xml":1}
,"ehcache.xml":{"adding":1}
,"adding":{"connection":1}
,"initially":{"log":1}
,"log":{"tmc":1}
,"default":{"connections":1,"connection":1,"location":1,"value":1,"values":1,"java":1,"directory":1}
,"exist":{"node":1}
,"node":{"monitored":1,"want":1,"enter":1,"click":1}
,"monitored":{"running":1}
,"running":{"localhost":1,"terracotta":1,"machine":1,"choose":1}
,"localhost":{"port":1,"machine":1}
,"specified":{"default":1,"security":1}
,"appears":{"active":1,"enter":1,"confirming":1,"connection":1}
,"active":{"connection":1}
,"unavailable":{"(inactive)":1}
,"(inactive)":{"connections":1}
,"add":{"new":1,"security":1}
,"new":{"connection":1,"click":1,"group":1,"values":1}
,"button":{"connections":1}
,"panel":{"settings":1,"locate":1,"click":1,"information":1}
,"home":{"page":1}
,"page":{"first":1,"click":1}
,"first":{"window":1}
,"wizard":{"appears":1}
,"enter":{"location":1,"name":1,"connection":1,"read":1}
,"want":{"monitor":1,"delete":1,"edit":1}
,"next":{"screen":1,"enter":1,"connection\u0027s":1,"group\u0027s":1}
,"screen":{"appears":1}
,"confirming":{"agent":1}
,"agent":{"found":1}
,"given":{"location":1}
,"warning":{"appears":1}
,"relative":{"machine":1}
,"machine":{"running":1,"tms":1,"browser":1}
,"(tms)":{"default":1}
,"browser":{"running":1}
,"choose":{"existing":1,"group":1,"change":1}
,"existing":{"connection":1,"standalone":1,"cluster":1,"groups":1}
,"group":{"connection":1,"configured":1,"name":1,"create":1,"enter":1,"edit":1}
,"name":{"identify":1,"delete":1,"alternatively":1,"choose":1,"group":1,"connection":1}
,"identify":{"connection":1}
,"timeout":{"accept":1,"ensures":1}
,"accept":{"default":1}
,"value":{"connection":1,"read":1}
,"ensures":{"tmc":1}
,"hang":{"waiting":1}
,"waiting":{"connection":1}
,"unreachable":{"node":1}
,"read":{"timeout":1}
,"unresponsive":{"node":1}
,"save":{"new":1,"changes":1}
,"cancel":{"discard":1,"revert":1}
,"discard":{"new":1}
,"editing":{"deleting":1}
,"deleting":{"connections":1}
,"managed":{"connections":1}
,"list":{"edited":1,"click":1}
,"edited":{"deleted":1}
,"deleted":{"delete":1}
,"delete":{"connection":1,"existing":1,"next":1,"edit":1}
,"view":{"connections":1}
,"locate":{"connection":1}
,"red":{"next":1}
,"connection\u0027s":{"name":1,"location":1}
,"group\u0027s":{"name":1}
,"alternatively":{"home":1}
,"trash":{"icon":1}
,"icon":{"connection":1}
,"pane":{"want":1}
,"edit":{"standalone":1,"edit":1,"connection\u0027s":1,"cluster":1,"group":1}
,"pencil":{"icon":1}
,"menu":{"existing":1}
,"changes":{"save":1}
,"values":{"cancel":1,"edit":1,"polling":1,"click":1}
,"revert":{"original":1}
,"original":{"values":1}
,"timeouts":{"click":1}
,"period":{"settings":1}
,"tab":{"polling":1,"configure":1}
,"interval":{"seconds":1}
,"seconds":{"controls":1}
,"controls":{"granularity":1}
,"granularity":{"polled":1}
,"polled":{"statistical":1,"reset":1}
,"statistical":{"data":1}
,"data":{"note":1}
,"note":{"shorter":1,"following":1}
,"shorter":{"polling":1}
,"intervals":{"greater":1}
,"greater":{"effect":1}
,"effect":{"overall":1}
,"overall":{"performance":1}
,"performance":{"nodes":1}
,"reset":{"default":1,"defaults":1}
,"defaults":{"security":1}
,"configure":{"security":1}
,"change":{"type":1}
,"type":{"security":1}
,"used":{"tms":1}
,"changing":{"security":1,"type":1}
,"requires":{"restarting":1}
,"restarting":{"tmc":1}
,"require":{"additional":1}
,"additional":{"configuration":1}
,"information":{"infrastructure":1,"setting":1}
,"infrastructure":{"add":1}
,"unsecured":{"nodes":1}
,"lost":{"disable":1,"ssl":1}
,"disable":{"authentication":1}
,"authentication":{"connections":1}
,"secured":{"nodes":1}
,"ssl":{"connections":1}
,"custom":{"truststore":1}
,"truststore":{"instead":1,"located":1}
,"instead":{"default":1}
,"java":{"cacerts":1}
,"cacerts":{"custom":1}
,"located":{"default":1}
,"directory":{"specified":1}
,"setting":{"security":1}
}
;Search.control.loadWordPairs(pairs);
