var pairs =
{
"dashboards":{"tabs":1,"click":1,"automatically":1,"tmc":1}
,"tabs":{"management":1,"application":1}
,"management":{"panels":1,"panel":1}
,"panels":{"once":1,"connection":1,"click":1}
,"once":{"navigated":1}
,"navigated":{"away":1}
,"away":{"home":1}
,"home":{"page":1}
,"page":{"configured":1,"click":1,"elements":1}
,"configured":{"connection":1,"connections":1}
,"connection":{"groups":1,"group":1,"drop-down":1,"group\u0027s":1,"note":1}
,"groups":{"appear":1}
,"appear":{"mini-dashboards":1,"whenever":1,"dashboard":1}
,"mini-dashboards":{"across":1}
,"across":{"top":1}
,"top":{"page":1,"toolbar":1}
,"click":{"dashboard":1,"settings":1,"directly":1,"tab":1,"panel":1}
,"dashboard":{"select":1,"displays":1,"including":1,"control":1,"associated":1,"choose":1,"restore":1,"connections":1,"checkbox":1,"top":1,"hover":1}
,"select":{"view":1,"connection":1}
,"view":{"management":1,"information":1}
,"group":{"alternatively":1,"dashboard":1,"example":1,"hide":1}
,"alternatively":{"select":1}
,"drop-down":{"menu":1}
,"menu":{"top":1,"commands":1,"connection":1}
,"toolbar":{"tsa":1,"enable":1,"note":1}
,"tsa":{"connection-group":1,"certain":1}
,"connection-group":{"dashboard":1}
,"displays":{"number":1}
,"number":{"connected":1,"clients":1,"configured":1,"currently":1,"level":1}
,"connected":{"active":1,"tsa":1,"dashboard":1}
,"active":{"(green)":1,"tooltip":1}
,"(green)":{"mirror":1}
,"mirror":{"(blue)":1}
,"(blue)":{"servers":1}
,"servers":{"displays":1}
,"clients":{"connected":1}
,"certain":{"server":1}
,"server":{"states":1,"starting":1,"unreachable":1}
,"states":{"indicated":1}
,"indicated":{"dashboard":1}
,"including":{"server":1}
,"starting":{"recovering":1}
,"recovering":{"(yellow)":1}
,"(yellow)":{"server":1}
,"unreachable":{"(red)":1}
,"(red)":{"standalone":1}
,"standalone":{"connection":1}
,"connections":{"number":1,"unaffected":1,"click":1}
,"currently":{"connected":1}
,"control":{"drop-down":1,"menu":1}
,"commands":{"applicable":1}
,"applicable":{"dashboard":1}
,"associated":{"connection":1}
,"example":{"hide":1}
,"hide":{"connection":1,"(or":1}
,"group\u0027s":{"dashboard":1,"connections":1}
,"choose":{"hide":1}
,"unaffected":{"hiding":1}
,"hiding":{"dashboard":1}
,"restore":{"dashboard":1}
,"settings":{"toolbar":1}
,"enable":{"show":1}
,"show":{"dashboard":1}
,"checkbox":{"group":1}
,"(or":{"view)":1}
,"view)":{"dashboards":1}
,"note":{"dashboards":1,"management":1}
,"automatically":{"appear":1}
,"whenever":{"unread":1}
,"unread":{"events":1,"operator":1}
,"events":{"unread":1,"flame":1,"click":1,"panel":1}
,"operator":{"events":1}
,"flame":{"icon":1}
,"icon":{"appear":1}
,"hover":{"number":1,"various":1}
,"level":{"events":1}
,"directly":{"monitoring":1}
,"monitoring":{"events":1,"administration":1}
,"panel":{"below":1,"view":1,"active":1}
,"below":{"dashboards":1}
,"tmc":{"tabs":1}
,"application":{"data":1}
,"data":{"monitoring":1}
,"administration":{"troubleshooting":1}
,"troubleshooting":{"wan":1}
,"wan":{"click":1}
,"tab":{"access":1}
,"access":{"panels":1}
,"information":{"selected":1}
,"selected":{"connection":1}
,"tooltip":{"hints":1}
,"hints":{"pop":1}
,"pop":{"hover":1}
,"various":{"page":1}
}
;Search.control.loadWordPairs(pairs);
