var pairs =
{
"learn":{"bigmemory":1}
,"bigmemory":{"works":1,"information":1,"review":1,"bigmemory":1,"configuration":1,"configured":1,"architecture":1}
,"works":{"explore":1}
,"explore":{"code":1}
,"code":{"samples":1}
,"samples":{"provided":1,"code":1,"online":1}
,"provided":{"kit":1}
,"kit":{"learn":1}
,"information":{"samples":1}
,"online":{"documentation":1}
,"documentation":{"bigmemory":1}
,"review":{"configuring":1}
,"configuring":{"bigmemory":1,"storage":1}
,"configuration":{"guide":1}
,"guide":{"learn":1}
,"configured":{"review":1}
,"storage":{"tiers":1}
,"tiers":{"bigmemory":1}
}
;Search.control.loadWordPairs(pairs);
