var pairs =
{
"runtime":{"statistics":1,"statistic":1}
,"statistics":{"runtime":1,"graphs":1,"view":1,"tsa":1,"selected":1,"cluster\u0027s":1,"defined":1,"appear":1}
,"graphs":{"provide":1}
,"provide":{"continuous":1}
,"continuous":{"feed":1}
,"feed":{"server":1}
,"server":{"client":1,"-display":1,"clients":1,"expiration":1,"read\u002Fwrite":1,"operations":1,"data":1}
,"client":{"metrics":1,"specific":1}
,"metrics":{"sampling":1}
,"sampling":{"begins":1}
,"begins":{"automatically":1}
,"automatically":{"runtime":1}
,"statistic":{"panel":1,"available":1,"reported":1}
,"panel":{"first":1}
,"first":{"viewed":1,"time":1}
,"viewed":{"historical":1}
,"historical":{"data":1}
,"data":{"saved":1,"evict":1,"due":1,"storage":1,"max":1,"used":1}
,"saved":{"select":1}
,"select":{"view":1}
,"view":{"menu":1,"following":1}
,"menu":{"runtime":1}
,"following":{"servers":1,"sections":1}
,"servers":{"-display":1,"clients":1}
,"-display":{"aggregated":1,"runtime":1}
,"aggregated":{"statistics":1}
,"tsa":{"specified":1,"mirror":1,"selected":1,"response":1}
,"specified":{"mirror":1,"server":1,"client-display":1}
,"mirror":{"group":1}
,"group":{"-display":1,"specified":1,"server":1}
,"selected":{"mirror":1,"server":1,"client":1,"statistic":1}
,"clients":{"-display":1,"specified":1,"trend":1,"cluster":1,"eviction":1,"selected":1}
,"cluster\u0027s":{"clients":1}
,"client-display":{"runtime":1}
,"specific":{"runtime":1}
,"defined":{"following":1}
,"sections":{"cluster":1}
,"cluster":{"components":1,"mirror":1,"eventually":1}
,"components":{"statistic":1}
,"available":{"indicated":1,"server\u0027s":1,"off-heap":1,"offheap":1}
,"indicated":{"text":1}
,"text":{"live":1}
,"live":{"object":1,"objects":1}
,"object":{"count":1,"available":1}
,"count":{"shows":1}
,"shows":{"total":1,"number":1,"hybrid":1,"amount":1,"configured":1}
,"total":{"number":1,"amount":1}
,"number":{"live":1,"entries":1,"expired":1,"completed":1,"drops":1}
,"objects":{"cluster":1,"continuously":1,"(per":1,"requested":1,"flushed":1}
,"trend":{"total":1}
,"continuously":{"clients":1}
,"eventually":{"run":1}
,"run":{"memory":1}
,"memory":{"applications":1,"constraints":1,"request":1,"allocation":1,"flash":1,"(configured":1,"(containing":1,"configured":1,"(offheap":1,"currently":1}
,"applications":{"fail":1}
,"fail":{"upward":1}
,"upward":{"trends":1}
,"trends":{"indicate":1}
,"indicate":{"problem":1,"issues":1,"inadequate":1}
,"problem":{"application":1}
,"application":{"logic":1,"requests":1}
,"logic":{"garbage":1}
,"garbage":{"collection":1}
,"collection":{"tuning":1}
,"tuning":{"clients":1}
,"eviction":{"rate":1,"expiration":1}
,"rate":{"shows":1,"(see":1,"low":1,"tracking":1}
,"entries":{"evicted":1,"found":1}
,"evicted":{"cluster":1}
,"expiration":{"rate":1,"operations":1}
,"expired":{"entries":1}
,"found":{"(and":1}
,"(and":{"evicted)":1}
,"evicted)":{"tsa":1}
,"read\u002Fwrite":{"operation":1}
,"operation":{"rate":1}
,"completed":{"writes":1}
,"writes":{"(or":1,"little":1}
,"(or":{"mutations)":1}
,"mutations)":{"tsa":1}
,"operations":{"include":1,"cause":1,"rate":1}
,"include":{"evictions":1}
,"evictions":{"expirations":1}
,"expirations":{"large-scale":1,"statistical":1}
,"large-scale":{"eviction":1}
,"cause":{"spikes":1}
,"spikes":{"operations":1}
,"(see":{"corresponding":1}
,"corresponding":{"evictions":1}
,"statistical":{"graphs)":1}
,"graphs)":{"rate":1}
,"low":{"read-mostly":1}
,"read-mostly":{"situations":1}
,"situations":{"indicating":1}
,"indicating":{"few":1}
,"few":{"writes":1}
,"little":{"data":1}
,"evict":{"number":1}
,"drops":{"deviates":1}
,"deviates":{"regularly":1}
,"regularly":{"established":1}
,"established":{"baseline":1}
,"baseline":{"indicate":1}
,"issues":{"network":1}
,"network":{"connections":1}
,"connections":{"overloaded":1}
,"overloaded":{"servers":1}
,"reported":{"write":1}
,"write":{"transaction":1,"transactions":1}
,"transaction":{"rate":1}
,"tracking":{"client-to-server":1}
,"client-to-server":{"write":1}
,"transactions":{"measure":1}
,"measure":{"objects":1}
,"(per":{"second)":1}
,"second)":{"faulted":1}
,"faulted":{"tsa":1,"disk":1}
,"response":{"application":1}
,"requests":{"faults":1}
,"faults":{"off-heap":1}
,"off-heap":{"disk":1,"cache":1,"memory":1,"storage":1,"alone":1,"dram":1}
,"disk":{"occur":1,"high":1}
,"occur":{"object":1,"heap":1}
,"server\u0027s":{"on-heap":1}
,"on-heap":{"cache":1}
,"cache":{"flushes":1,"clear":1}
,"flushes":{"occur":1}
,"heap":{"off-heap":1}
,"clear":{"data":1}
,"due":{"memory":1}
,"constraints":{"objects":1}
,"requested":{"first":1}
,"time":{"objects":1}
,"flushed":{"off-heap":1}
,"request":{"arrives":1}
,"arrives":{"faulted":1}
,"high":{"rates":1}
,"rates":{"indicate":1}
,"inadequate":{"memory":1}
,"allocation":{"server":1}
,"storage":{"usage":1,"data":1,"includes":1,"configured":1,"currently":1}
,"usage":{"bigmemory":1,"graph":1,"shows":1}
,"bigmemory":{"max":1,"off-heap":1,"hybrid":1}
,"max":{"provides":1,"shows":1}
,"provides":{"support":1}
,"support":{"hybrid":1}
,"hybrid":{"mix":1,"maximum":1,"configured":1}
,"mix":{"solid-state":1}
,"solid-state":{"device":1}
,"device":{"(ssd)":1}
,"(ssd)":{"flash":1}
,"flash":{"drives":1,"drive":1}
,"drives":{"along":1,"entirely":1}
,"along":{"standard":1}
,"standard":{"dram-based":1}
,"dram-based":{"off-heap":1}
,"graph":{"compared":1,"shows":1}
,"compared":{"offheap":1}
,"offheap":{"usage":1,"(made":1,"max":1,"shows":1,"used":1}
,"maximum":{"data":1,"available":1,"amount":1}
,"includes":{"off-heap":1}
,"entirely":{"larger":1}
,"larger":{"scale":1}
,"scale":{"off-heap":1}
,"alone":{"data":1}
,"amount":{"data":1,"(datastorage":1,"megabytes":1,"off-heap":1}
,"configured":{"amount":1,"data":1,"offheap":1,"maximum":1}
,"(datastorage":{"size":1}
,"size":{"tc-config.xml)":1}
,"tc-config.xml)":{"stored":1,"offheap":1}
,"stored":{"bigmemory":1}
,"dram":{"ssd":1}
,"ssd":{"flash":1}
,"drive":{"bigmemory":1}
,"used":{"shows":1,"off-heap":1}
,"currently":{"offheap":1,"available":1,"(containing":1}
,"megabytes":{"gigabytes":1}
,"gigabytes":{"maximum":1}
,"(configured":{"limit)":1}
,"limit)":{"offheap":1}
,"(made":{"available)":1}
,"available)":{"used":1}
,"(containing":{"data)":1}
,"data)":{"statistics":1}
,"appear":{"off-heap":1}
,"(offheap":{"size":1}
}
;Search.control.loadWordPairs(pairs);
