var pairs =
{
"delete":{"clears":1,"examples":1,"400":1}
,"clears":{"cache":1}
,"cache":{"clears":1,"statistics":1,"\u002Fagents":1,"bar":1,"foo":1}
,"statistics":{"following":1,"\u002Fagents":1,"cache":1}
,"following":{"delete":1}
,"examples":{"organized":1}
,"organized":{"task":1}
,"task":{"uri":1}
,"uri":{"clear":1,"specify":1,"cannot":1}
,"clear":{"cache":1}
,"\u002Fagents":{"id=client01\u002Fcachemanagers":1}
,"id=client01\u002Fcachemanagers":{"names=foo\u002Fcaches":1}
,"names=foo\u002Fcaches":{"names=bar\u002Felements":1,"names=bar\u002Fconfigs":1}
,"names=bar\u002Felements":{"removes":1}
,"removes":{"elements":1}
,"elements":{"cache":1}
,"bar":{"cachemanager":1}
,"cachemanager":{"foo":1}
,"foo":{"ehcache":1,"resets":1}
,"ehcache":{"node":1}
,"node":{"client01":1}
,"client01":{"clear":1}
,"names=bar\u002Fconfigs":{"clears":1}
,"resets":{"counters":1}
,"counters":{"zero":1}
,"zero":{"possible":1}
,"possible":{"http":1}
,"http":{"status":1}
,"status":{"codes":1}
,"codes":{"delete":1}
,"400":{"uri":1}
,"specify":{"single":1}
,"single":{"resource":1}
,"resource":{"404":1,"specified":1}
,"404":{"resource":1}
,"specified":{"uri":1}
,"cannot":{"found":1}
}
;Search.control.loadWordPairs(pairs);
