var pairs =
{
"configuring":{"terracotta":1}
,"terracotta":{"management":1,"ehcache":1,"property":1,"configuration":1,"server":1}
,"management":{"server":1,"console":1,"service":1}
,"server":{"bigmemory":1,"following":1,"array":1}
,"bigmemory":{"max":1,"go)":1,"cachemanagers":1}
,"max":{"cluster":1,"generate":1}
,"cluster":{"managed":1,"servers":1}
,"managed":{"directly":1}
,"directly":{"connecting":1}
,"connecting":{"terracotta":1}
,"console":{"(tmc)":1}
,"(tmc)":{"servers":1}
,"servers":{"cluster":1,"clients":1}
,"clients":{"become":1,"impacts":1}
,"become":{"visible":1}
,"visible":{"tmc":1}
,"tmc":{"initial":1,"enable":1,"heavy":1,"track":1,"loading":1,"rest":1,"update":1,"usage":1}
,"initial":{"connection":1}
,"connection":{"create":1,"enter":1}
,"create":{"new":1}
,"new":{"connection":1}
,"enter":{"uri":1}
,"uri":{"server":1}
,"following":{"form":1,"element":1,"defaults":1,"system":1}
,"form":{"<scheme>":1}
,"<scheme>":{":\u002F\u002F<host-address>":1}
,":\u002F\u002F<host-address>":{"<management-port>":1}
,"<management-port>":{"<management-port>":1,"port":1}
,"port":{"number":1,"network":1}
,"number":{"configured":1,"used":1,"clients":1}
,"configured":{"server\u0027s":1}
,"server\u0027s":{"tc-config.xml":1}
,"tc-config.xml":{"file":1}
,"file":{"default":1,"(tc-config.xml":1}
,"default":{"9540":1,"caches":1,"disable":1}
,"9540":{"<<ffc-what":1}
,"<<ffc-what":{"terracotta":1}
,"ehcache":{"?>>":1,"client":1}
,"?>>":{"manage":1}
,"manage":{"client":1,"node":1}
,"client":{"standalone":1,"bigmemory":1}
,"standalone":{"node":1,"caches.)":1}
,"node":{"(terracotta":1,"setting":1,"following":1}
,"(terracotta":{"ehcache":1}
,"go)":{"using":1}
,"using":{"tmc":1,"production":1,"multiple":1}
,"enable":{"rest":1}
,"rest":{"management":1,"=new":1,"agent":1}
,"service":{"node":1,"enabled":1}
,"setting":{"following":1}
,"element":{"ehcache.xml":1}
,"ehcache.xml":{"configuration":1}
,"configuration":{"<ehcache":1,"file":1}
,"<ehcache":{"<managementrestservice":1}
,"<managementrestservice":{"enabled=\u0022":1}
,"enabled=\u0022":{"true":1,"false":1}
,"true":{"bind=\u0022":1,"standalone":1,"<\u002Ftc-properties>":1}
,"bind=\u0022":{"<ip_address>":1,"0.0.0.0:9888":1}
,"<ip_address>":{"<port>":1,"local":1}
,"<port>":{"\u0022\u002F>":1,"port":1}
,"\u0022\u002F>":{"<\u002Fehcache>":1}
,"<\u002Fehcache>":{"<ip_address>":1}
,"local":{"network":1,"node.)":1}
,"network":{"interface\u0027s":1,"interfaces":1}
,"interface\u0027s":{"address":1}
,"address":{"<port>":1,"binds":1}
,"used":{"manage":1}
,"defaults":{"effect":1}
,"effect":{"<managementrestservice>":1,"enabling":1}
,"<managementrestservice>":{"enabled=\u0022":1}
,"false":{"(this":1}
,"(this":{"true":1,"address":1}
,"caches.)":{"bind=\u0022":1}
,"0.0.0.0:9888":{"(this":1,"rest.setenabled":1}
,"binds":{"specified":1}
,"specified":{"port":1}
,"interfaces":{"local":1}
,"node.)":{"rest":1}
,"enabled":{"programmatically":1,"jvm":1}
,"programmatically":{"managementrestserviceconfiguration":1}
,"managementrestserviceconfiguration":{"rest":1,"rest.setbind":1}
,"=new":{"managementrestserviceconfiguration":1}
,"rest.setbind":{"0.0.0.0:9888":1}
,"rest.setenabled":{"(true)":1}
,"(true)":{"config.addmanagementrestservice":1}
,"config.addmanagementrestservice":{"(rest)":1}
,"(rest)":{"performance":1}
,"performance":{"becomes":1,"displaying":1,"using":1}
,"becomes":{"issue":1}
,"issue":{"tmc":1}
,"heavy":{"number":1}
,"impacts":{"performance":1}
,"displaying":{"update":1}
,"update":{"statistics":1,"checker":1}
,"statistics":{"default":1}
,"caches":{"distributed":1}
,"distributed":{"bigmemory":1}
,"generate":{"put":1}
,"put":{"events":1,"updated":1}
,"events":{"whenever":1}
,"whenever":{"elements":1}
,"elements":{"put":1}
,"updated":{"tmc":1}
,"track":{"display":1}
,"display":{"updates":1}
,"updates":{"separately":1,"collects":1}
,"separately":{"puts":1}
,"puts":{"terracotta":1}
,"property":{"ehcache.clusteredstore.checkcontainskeyonput":1,"substantially":1,"using":1,"-dcom.terracotta.management.skipupdatecheck=true":1}
,"ehcache.clusteredstore.checkcontainskeyonput":{"top":1,"value=\u0022":1}
,"top":{"terracotta":1}
,"(tc-config.xml":{"default)":1}
,"default)":{"starting":1}
,"starting":{"terracotta":1}
,"array":{"<tc-properties>":1}
,"<tc-properties>":{"<property":1}
,"<property":{"name=\u0022":1}
,"name=\u0022":{"ehcache.clusteredstore.checkcontainskeyonput":1}
,"value=\u0022":{"true":1}
,"<\u002Ftc-properties>":{"enabling":1}
,"enabling":{"property":1}
,"substantially":{"degrade":1}
,"degrade":{"performance":1}
,"production":{"test":1}
,"test":{"effect":1}
,"multiple":{"instances":1}
,"instances":{"bigmemory":1}
,"cachemanagers":{"tmc":1,"loaded":1}
,"loading":{"multiple":1}
,"agent":{"enabled":1}
,"jvm":{"cachemanagers":1}
,"loaded":{"distinct":1,"two":1}
,"distinct":{"classloaders":1}
,"classloaders":{"two":1,"tmc":1}
,"two":{"different":1}
,"different":{"web":1,"wars)":1,"classloaders":1}
,"web":{"applications":1}
,"applications":{"(two":1}
,"(two":{"different":1}
,"wars)":{"example":1}
,"example":{"loaded":1}
,"checker":{"update":1,"automatically":1,"default":1,"following":1}
,"automatically":{"checks":1}
,"checks":{"latest":1}
,"latest":{"updates":1}
,"collects":{"diagnostic":1}
,"diagnostic":{"information":1}
,"information":{"tmc":1}
,"usage":{"update":1}
,"disable":{"update":1}
,"system":{"property":1}
}
;Search.control.loadWordPairs(pairs);
