var pairs =
{
"display":{"errors":1,"runtime":1}
,"errors":{"bad":1,"&*\u0022":1,"sizing":1,"tmc":1}
,"bad":{"cache":1}
,"cache":{"cachemanager":1,"configuration":1,"sizing":1}
,"cachemanager":{"names":1}
,"names":{"using":1,"caches":1}
,"using":{"following":1}
,"following":{"characters":1}
,"characters":{"names":1}
,"caches":{"cachemanagers":1,"sizing":1}
,"cachemanagers":{"causes":1}
,"causes":{"display":1}
,"runtime":{"errors":1,"cacheexception":1}
,"&*\u0022":{"issues":1}
,"issues":{"caused":1}
,"caused":{"include":1}
,"include":{"statistics":1}
,"statistics":{"appearing":1}
,"appearing":{"correctly":1}
,"correctly":{"overview":1}
,"overview":{"panel":1}
,"panel":{"pop-up":1}
,"pop-up":{"tmc":1}
,"tmc":{"error":1,"displays":1}
,"error":{"messages":1}
,"messages":{"response":1}
,"response":{"attempt":1}
,"attempt":{"view":1}
,"view":{"cache":1}
,"configuration":{"runtime":1,"guide)":1}
,"cacheexception":{"errors":1}
,"sizing":{"errors":1,"information":1,"operation":1,"operation\u0027s":1}
,"displays":{"cache":1}
,"information":{"certain":1,"displayed":1}
,"certain":{"panels":1}
,"panels":{"appear":1}
,"appear":{"errors":1}
,"displayed":{"nonstop":1}
,"nonstop":{"caches":1,"timeout":1,"timeouts":1}
,"operation":{"timing":1}
,"timing":{"(it":1}
,"(it":{"uses":1}
,"uses":{"nonstop":1}
,"timeout":{"value)":1,"value":1}
,"value)":{"tune":1}
,"tune":{"sizing":1}
,"operation\u0027s":{"timeout":1}
,"value":{"setting":1}
,"setting":{"bulkopstimeoutmultiplyfactor":1}
,"bulkopstimeoutmultiplyfactor":{"(see":1}
,"(see":{"tuning":1}
,"tuning":{"nonstop":1}
,"timeouts":{"behaviors":1}
,"behaviors":{"bigmemory":1}
,"bigmemory":{"max":1}
,"max":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
