var pairs =
{
"example":{"programmatic":1,"available":1}
,"programmatic":{"configuration":1}
,"configuration":{"following":1,"api":1,"managerconfiguration":1,".name":1}
,"following":{"description":1}
,"description":{"focuses":1}
,"focuses":{"code":1}
,"code":{"snippets":1,"example":1}
,"snippets":{"full":1}
,"full":{"code":1}
,"available":{"\u002Fcode-samples\u002Fsrc\u002Flocation":1}
,"\u002Fcode-samples\u002Fsrc\u002Flocation":{"installed":1}
,"installed":{"product":1}
,"product":{"kit":1}
,"kit":{"configure":1}
,"configure":{"bigmemory":1}
,"bigmemory":{"programmatically":1,".maxbyteslocalheap":1,"=manager.getcache":1,"\u002F\u002Fnow":1}
,"programmatically":{"ehcache":1}
,"ehcache":{"fluent":1}
,"fluent":{"configuration":1}
,"api":{"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Fconfig\u002Fconfiguration.html":1}
,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Fconfig\u002Fconfiguration.html":{"configuration":1}
,"managerconfiguration":{"=new":1}
,"=new":{"configuration":1}
,".name":{"bigmemory-config":1,"bigmemory":1}
,"bigmemory-config":{".cache":1}
,".cache":{"(new":1}
,"(new":{"cacheconfiguration":1}
,"cacheconfiguration":{".name":1}
,".maxbyteslocalheap":{"(512":1}
,"(512":{"memoryunit.megabytes)":1}
,"memoryunit.megabytes)":{".maxbyteslocaloffheap":1}
,".maxbyteslocaloffheap":{"memoryunit.gigabytes)":1}
,"memoryunit.gigabytes)":{".copyonread":1}
,".copyonread":{"(true)":1}
,"(true)":{".statistics":1,".eternal":1,"cachemanager":1}
,".statistics":{"(true)":1}
,".eternal":{"(true)":1}
,"cachemanager":{"manager":1}
,"manager":{"=cachemanager.create":1}
,"=cachemanager.create":{"(managerconfiguration)":1}
,"(managerconfiguration)":{"try":1}
,"try":{"{cache":1}
,"{cache":{"bigmemory":1}
,"=manager.getcache":{"bigmemory":1}
,"\u002F\u002Fnow":{"stuff":1}
,"stuff":{"finally":1}
,"finally":{"{if":1}
,"{if":{"(manager":1}
,"(manager":{"!=null)":1}
,"!=null)":{"manager.shutdown":1}
}
;Search.control.loadWordPairs(pairs);
