var pairs =
{
"terracotta":{"management":1}
,"management":{"console":1,"capabilities":1,"server":1,"services":1}
,"console":{"terracotta":1,"(tmc)":1}
,"(tmc)":{"web-based":1}
,"web-based":{"administration":1}
,"administration":{"monitoring":1}
,"monitoring":{"application":1}
,"application":{"following":1}
,"following":{"advantages":1}
,"advantages":{"multi-level":1}
,"multi-level":{"security":1}
,"security":{"architecture":1,"context":1}
,"architecture":{"end-to-end":1}
,"end-to-end":{"ssl":1}
,"ssl":{"secure":1}
,"secure":{"connections":1,"production":1}
,"connections":{"available":1}
,"available":{"feature-rich":1,"accessible":1}
,"feature-rich":{"easy-to-use":1}
,"easy-to-use":{"interface":1}
,"interface":{"remote":1}
,"remote":{"management":1}
,"capabilities":{"requiring":1}
,"requiring":{"web":1}
,"web":{"browser":1}
,"browser":{"network":1}
,"network":{"connection":1}
,"connection":{"cross-platform":1,"security":1}
,"cross-platform":{"deployment":1}
,"deployment":{"role-based":1,"model":1}
,"role-based":{"authentication":1}
,"authentication":{"authorization":1}
,"authorization":{"support":1}
,"support":{"ldap":1}
,"ldap":{"directories":1}
,"directories":{"microsoft":1}
,"microsoft":{"active":1}
,"active":{"directory":1}
,"directory":{"aggregate":1}
,"aggregate":{"statistics":1}
,"statistics":{"multiple":1}
,"multiple":{"nodes":1}
,"nodes":{"flexible":1,"clusters":1}
,"flexible":{"deployment":1}
,"model":{"plug":1}
,"plug":{"development":1}
,"development":{"environments":1}
,"environments":{"secure":1}
,"production":{"architectures":1}
,"architectures":{"tmc":1}
,"tmc":{"monitor":1,"tms":1,"provide":1}
,"monitor":{"bigmemory":1}
,"bigmemory":{"nodes":1,"kit":1}
,"clusters":{"terracotta":1}
,"server":{"(tms)":1}
,"(tms)":{"tms":1}
,"tms":{"acts":1,"available":1,"included":1}
,"acts":{"aggregator":1}
,"aggregator":{"provides":1}
,"provides":{"connection":1}
,"context":{"tmc":1}
,"accessible":{"tmc":1}
,"provide":{"management":1}
,"services":{"tms":1}
,"included":{"bigmemory":1}
,"kit":{"tools\u002Fmanagement-console":1}
,"tools\u002Fmanagement-console":{"directory":1}
}
;Search.control.loadWordPairs(pairs);
