var pairs =
{
"example":{"shell":1,"plugin":1}
,"shell":{"script":1}
,"script":{"plugin":1,"particular":1,"install":1,"find":1}
,"plugin":{"following":1,"using":1,"reports":1,"able":1,"detected":1,"low-level":1,"occurred":1}
,"following":{"example":1}
,"using":{"shell":1}
,"particular":{"plugin":1}
,"reports":{"event":1}
,"event":{"nagios":1,"occurs":1,"resturl=\u0022":1,"$server_list":1,"${server}":1}
,"nagios":{"node.left":1,"plugins":1,"number":1}
,"node.left":{"event":1}
,"occurs":{"node.left":1,"whenever":1}
,"whenever":{"node":1}
,"node":{"leaves":1,"left":1}
,"leaves":{"cluster":1}
,"cluster":{"list":1,"monitoring":1,"events":1}
,"list":{"kinds":1}
,"kinds":{"events":1}
,"events":{"occur":1,"bigmemory":1,"editing":1}
,"occur":{"terracotta":1}
,"terracotta":{"cluster":1,"server":1,"server\u0027s":1}
,"monitoring":{"cluster":1}
,"bigmemory":{"max":1}
,"max":{"administrator":1}
,"administrator":{"guide":1}
,"guide":{"!\u002Fbin\u002Fbash":1}
,"!\u002Fbin\u002Fbash":{"parameters":1}
,"parameters":{"----------server=$1":1}
,"----------server=$1":{"address":1}
,"address":{"resolvable":1}
,"resolvable":{"hostname":1}
,"hostname":{"terracotta":1}
,"server":{"port=$2":1}
,"port=$2":{"terracotta":1}
,"server\u0027s":{"management-port":1}
,"management-port":{"(9540":1}
,"(9540":{"default)":1}
,"default)":{"interval=$3":1}
,"interval=$3":{"far":1}
,"far":{"back":1}
,"back":{"time":1}
,"time":{"minutes":1}
,"minutes":{"search":1}
,"search":{"event":1}
,"resturl=\u0022":{"http:\u002F\u002F${server}":1}
,"http:\u002F\u002F${server}":{":${port}\u002Ftc-management-api\u002Fagents\u002Foperatorevents":1}
,":${port}\u002Ftc-management-api\u002Fagents\u002Foperatorevents":{"sincewhen=${interval}":1}
,"sincewhen=${interval}":{"get_info=`":1}
,"get_info=`":{"curl":1}
,"curl":{"\u0022$resturl":1}
,"\u0022$resturl":{"grep":1}
,"grep":{"left":1}
,"left":{"nb_lines=`":1,"cluster.*\u002F\u005C1\u002Fg":1,"event":1}
,"nb_lines=`":{"echo":1}
,"echo":{"$get_info":1,"$server_list":1,"node":1,"check":1}
,"$get_info":{"[[$nb_lines":1,"sed":1}
,"[[$nb_lines":{"-gt":1}
,"-gt":{"server_list=":1}
,"server_list=":{"echo":1}
,"sed":{"\u0027s\u002F.*node\u005C(.*\u005C)":1}
,"\u0027s\u002F.*node\u005C(.*\u005C)":{"left":1}
,"cluster.*\u002F\u005C1\u002Fg":{"server_list=\u0022$server_list":1}
,"server_list=\u0022$server_list":{"done":1}
,"done":{"echo":1}
,"$server_list":{"check=\u0022":1,"exit":1}
,"check=\u0022":{"node_left":1,"no_event":1}
,"node_left":{"else":1,"echo":1}
,"else":{"check=\u0022":1,"echo":1}
,"no_event":{"[[\u0022$check":1,"echo":1}
,"[[\u0022$check":{"==\u0022":1}
,"==\u0022":{"node_left":1,"no_event":1}
,"exit":{"elif":1,"else":1,"note":1,"codes":1}
,"elif":{"[[\u0022$check":1}
,"${server}":{"exit":1}
,"check":{"failed":1,"service":1}
,"failed":{"exit":1}
,"note":{"script\u0027s":1}
,"script\u0027s":{"exit":1}
,"codes":{"follow":1}
,"follow":{"standard":1}
,"standard":{"required":1}
,"required":{"nagios":1}
,"plugins":{"value":1,"generally":1,"available":1}
,"value":{"status":1}
,"status":{"description":1}
,"description":{"plugin":1}
,"able":{"check":1}
,"service":{"appeared":1,"running":1}
,"appeared":{"functioning":1,"above":1}
,"functioning":{"properly":1}
,"properly":{"warning":1,"critical":1}
,"warning":{"plugin":1,"threshold":1}
,"above":{"warning":1,"critical":1}
,"threshold":{"working":1,"unknown":1}
,"working":{"properly":1}
,"critical":{"plugin":1,"threshold":1}
,"detected":{"either":1}
,"either":{"service":1}
,"running":{"above":1}
,"unknown":{"invalid":1,"states":1}
,"invalid":{"command":1}
,"command":{"line":1}
,"line":{"arguments":1}
,"arguments":{"supplied":1}
,"supplied":{"plugin":1}
,"low-level":{"failures":1}
,"failures":{"internal":1}
,"internal":{"plugin":1}
,"occurred":{"(such":1}
,"(such":{"unable":1,"name":1}
,"unable":{"fork":1}
,"fork":{"open":1}
,"open":{"tcp":1}
,"tcp":{"socket)":1}
,"socket)":{"prevent":1}
,"prevent":{"performing":1}
,"performing":{"specified":1}
,"specified":{"operation":1}
,"operation":{"higher-level":1}
,"higher-level":{"errors":1}
,"errors":{"(such":1,"socket":1}
,"name":{"resolution":1}
,"resolution":{"errors":1}
,"socket":{"timeouts)":1}
,"timeouts)":{"outside":1}
,"outside":{"control":1}
,"control":{"plugins":1}
,"generally":{"reported":1}
,"reported":{"unknown":1}
,"states":{"create":1}
,"create":{"script":1}
,"install":{"nagios":1}
,"number":{"tutorials":1}
,"tutorials":{"installing":1}
,"installing":{"nagios":1}
,"available":{"internet":1}
,"internet":{"http:\u002F\u002Fwww.youtube.com\u002Fwatch":1}
,"http:\u002F\u002Fwww.youtube.com\u002Fwatch":{"v=jg1lvnire4e":1}
,"v=jg1lvnire4e":{"generalize":1}
,"generalize":{"script":1}
,"find":{"events":1}
,"editing":{"regex":1}
,"regex":{"pattern":1}
,"pattern":{"edit":1}
,"edit":{"resturl":1}
,"resturl":{"return":1}
,"return":{"types":1}
,"types":{"information":1}
}
;Search.control.loadWordPairs(pairs);
