var pairs =
{
"options":{"working":1}
,"working":{"nulls":1}
,"nulls":{"<<this":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"ehc":1}
,"ehc":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs.>>":1}
,"docs.>>":{"<<ffc-this":1}
,"<<ffc-this":{"section":1}
,"section":{"currently":1}
,"currently":{"ehcache":1}
,"ehcache":{"doc":1}
,"doc":{"deliberate":1}
,"deliberate":{"search":1}
,"search":{"api":1,"criteria":1}
,"api":{"supports":1}
,"supports":{"using":1}
,"using":{"presence":1,"absence":1}
,"presence":{"null":1,"absence":1}
,"null":{"search":1,"select":1,"alternatively":1}
,"criteria":{"myquery.addcriteria":1,"select":1,"isnull":1,"notnull":1}
,"myquery.addcriteria":{"(cache.getattribute":1}
,"(cache.getattribute":{"middle_name":1}
,"middle_name":{".isnull":1,".notnull":1,"criteria":1}
,".isnull":{"())":1,".not":1}
,"())":{"supports":1,"equivalent":1,"bigm":1}
,"absence":{"null":1}
,".notnull":{"())":1}
,"equivalent":{"myquery.addcriteria":1,"logic":1}
,".not":{"())":1}
,"bigm":{"bigmemory":1}
,"bigmemory":{"sql":1}
,"sql":{"supports":1}
,"select":{"*from":1}
,"*from":{"searchable":1}
,"searchable":{"birthdate":1}
,"birthdate":{"null":1}
,"alternatively":{"call":1}
,"call":{"constructors":1}
,"constructors":{"equivalent":1}
,"logic":{"criteria":1}
,"isnull":{"=new":1,"middle_name":1}
,"=new":{"isnull":1,"notnull":1}
,"notnull":{"=new":1,"middle_name":1}
}
;Search.control.loadWordPairs(pairs);
