var pairs =
{
"operations":{"questions":1,"guide":1}
,"questions":{"element":1}
,"element":{"without":1,"put":1,"programmatically":1}
,"without":{"affecting":1,"updating":1}
,"affecting":{"statistics":1}
,"statistics":{"cache.getquiet":1,"details":1,"counters":1,"gathering":1,"enabled":1}
,"cache.getquiet":{"method":1}
,"method":{"returns":1,"ehcache":1}
,"returns":{"element":1}
,"updating":{"statistics":1}
,"details":{"getquiet":1,"shutting":1,"terracotta":1}
,"getquiet":{"method":1,"28java.io.serializable":1}
,"ehcache":{"javadoc":1,"bigmemory":1}
,"javadoc":{"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Fcache.html":1,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002F":1}
,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002Fnet\u002Fsf\u002Fehcache\u002Fcache.html":{"getquiet":1}
,"28java.io.serializable":{"simple":1}
,"simple":{"disable":1}
,"disable":{"bigmemory":1}
,"bigmemory":{"testing":1,"easily":1,"disabled":1,"shutdown":1,"call":1,"operations":1,"cachemanager.shutdown":1,"internally":1,"bigmemory":1,"experience":1}
,"testing":{"system":1}
,"system":{"property":1}
,"property":{"net.sf.ehcache.disabled=true":1}
,"net.sf.ehcache.disabled=true":{"disable":1}
,"easily":{"done":1}
,"done":{"using":1}
,"using":{"-dnet.sf.ehcache.disabled=true":1,"cache.getkeys":1,"bigmemory":1,"cache":1}
,"-dnet.sf.ehcache.disabled=true":{"command":1}
,"command":{"line":1}
,"line":{"bigmemory":1}
,"disabled":{"elements":1,"default":1}
,"elements":{"added":1,"values":1}
,"added":{"stores":1}
,"stores":{"dynamically":1}
,"dynamically":{"change":1}
,"change":{"cache":1}
,"cache":{"attributes":1,"cache":1,"=new":1,"test2":1,"none":1,"elements":1,"cachemanager.removecache":1,"need":1,"memory":1,"generates":1,"configuration":1}
,"attributes":{"runtime":1}
,"runtime":{"possible":1}
,"possible":{"however":1}
,"however":{"achieve":1,"call":1,"deadlocks":1}
,"achieve":{"result":1}
,"result":{"follows":1}
,"follows":{"create":1}
,"create":{"new":1,"shut":1}
,"new":{"cache":1,"cachemanager":1,"allowing":1}
,"=new":{"cache":1}
,"test2":{"true":1}
,"true":{"true":1,"120":1,"<cache>":1}
,"120":{"cachemanager.addcache":1}
,"cachemanager.addcache":{"(cache)":1}
,"(cache)":{"parameters":1}
,"parameters":{"ehcache":1}
,"http:\u002F\u002Fehcache.org\u002Fapidocs\u002F2.10.1\u002F":{"list":1}
,"list":{"keys":1}
,"keys":{"using":1}
,"cache.getkeys":{"element":1}
,"put":{"new":1}
,"none":{"memory":1}
,"memory":{"new":1,"released":1}
,"values":{"reference":1}
,"reference":{"data":1}
,"data":{"original":1}
,"original":{"cache":1}
,"cachemanager.removecache":{"oldcachename":1}
,"oldcachename":{"remove":1}
,"remove":{"original":1}
,"need":{"explicitly":1}
,"explicitly":{"shut":1}
,"shut":{"down":1}
,"down":{"cachemanager":1,"ehcache":1,"number":1}
,"cachemanager":{"finish":1,"null":1,"bigmemory":1,"singleton":1}
,"finish":{"bigmemory":1}
,"shutdown":{"hook":1,"jvm":1}
,"hook":{"calls":1}
,"calls":{"shutdown":1}
,"jvm":{"exit":1,"keeps":1,"details":1}
,"exit":{"jvm":1}
,"keeps":{"running":1}
,"running":{"stop":1}
,"stop":{"using":1}
,"call":{"cachemanager.getinstance":1,"cachemanager.shutdown":1,"cachemanager.create":1}
,"cachemanager.getinstance":{".shutdown":1}
,".shutdown":{"threads":1}
,"threads":{"stopped":1}
,"stopped":{"cache":1}
,"released":{"back":1}
,"back":{"jvm":1}
,"shutting":{"down":1}
,"guide":{"bigmemory":1,"function":1}
,"cachemanager.shutdown":{"call":1,"sets":1}
,"sets":{"singleton":1}
,"singleton":{"cachemanager":1,"gets":1}
,"null":{"using":1}
,"generates":{"cacheexception":1}
,"cacheexception":{"however":1}
,"cachemanager.create":{"instantiate":1}
,"instantiate":{"new":1}
,"internally":{"cachemanager":1}
,"gets":{"new":1}
,"allowing":{"create":1}
,"number":{"times":1}
,"times":{"statistics":1}
,"counters":{"showing":1}
,"showing":{"active":1}
,"active":{"caches":1}
,"caches":{"statistics":1,"following":1}
,"gathering":{"disabled":1,"caches":1}
,"default":{"order":1}
,"order":{"optimize":1}
,"optimize":{"performance":1}
,"performance":{"enable":1}
,"enable":{"statistics":1}
,"following":{"ways":1}
,"ways":{"cache":1}
,"configuration":{"adding":1,"terracotta":1}
,"adding":{"statistics=\u0022":1}
,"statistics=\u0022":{"true":1}
,"<cache>":{"element":1}
,"programmatically":{"setting":1}
,"setting":{"cache\u0027s":1}
,"cache\u0027s":{"configuration":1}
,"terracotta":{"management":1}
,"management":{"console":1}
,"console":{"details":1,"user":1,"require":1}
,"user":{"guide":1}
,"function":{"certain":1}
,"certain":{"features":1,"tools":1}
,"features":{"terracotta":1}
,"require":{"statistics":1}
,"enabled":{"detect":1}
,"detect":{"deadlocks":1}
,"deadlocks":{"bigmemory":1,"however":1,"application":1}
,"experience":{"deadlocks":1}
,"application":{"code":1}
,"code":{"detected":1}
,"detected":{"certain":1}
,"tools":{"jdk":1}
,"jdk":{"tool":1}
,"tool":{"jconsole":1}
}
;Search.control.loadWordPairs(pairs);
