var pairs =
{
"off-heap":{"configuration":1,"assuming":1,"heap":1,"rest":1}
,"configuration":{"examples":1,"compare":1}
,"examples":{"<<this":1,"show":1}
,"<<this":{"topic":1}
,"topic":{"shared":1}
,"shared":{"bmg":1}
,"bmg":{"bmm":1}
,"bmm":{"product":1}
,"product":{"docs":1}
,"docs":{"ehc":1}
,"ehc":{"!>>":1}
,"!>>":{"examples":1}
,"show":{"allocate":1}
,"allocate":{"8gb":1,"1gb":1}
,"8gb":{"machine":1}
,"machine":{"memory":1}
,"memory":{"different":1}
,"different":{"stores":1}
,"stores":{"assumes":1}
,"assumes":{"data":1}
,"data":{"7gb":1,"reducing":1,"java":1,"small":1,"kept":1}
,"7gb":{"-say":1,"data":1}
,"-say":{"cache":1}
,"cache":{"items":1,"off-heap":1}
,"items":{"(each":1,"(or":1}
,"(each":{"1kb":1}
,"1kb":{"size)":1}
,"size)":{"want":1}
,"want":{"minimal":1,"cache":1,"best":1,"combination":1}
,"minimal":{"application":1}
,"application":{"response-time":1,"java":1,"response":1}
,"response-time":{"variance":1}
,"variance":{"(or":1,"likely":1}
,"(or":{"minimizing":1,"1gb)":1}
,"minimizing":{"pause":1}
,"pause":{"times)":1}
,"times)":{"likely":1}
,"likely":{"want":1}
,"assuming":{"1gb":1}
,"1gb":{"heap":1,"maxdirectmemorysize":1}
,"heap":{"needed":1,"used":1,"<cache":1}
,"needed":{"rest":1}
,"rest":{"application":1,"remain":1,"example":1}
,"java":{"config":1,"-xms1g":1,"-xms2g":1}
,"config":{"follows":1,"<cache":1}
,"follows":{"java":1}
,"-xms1g":{"-xmx1g":1}
,"-xmx1g":{"-xx:maxdirectmemorysize=7g":1}
,"-xx:maxdirectmemorysize=7g":{"ehcache":1}
,"ehcache":{"config":1}
,"<cache":{"maxentrieslocalheap=100":1,"maxentrieslocalheap=1m":1}
,"maxentrieslocalheap=100":{"overflowtooffheap=\u0022":1}
,"overflowtooffheap=\u0022":{"true":1,"false":1}
,"true":{"maxbyteslocaloffheap=\u0022":1}
,"maxbyteslocaloffheap=\u0022":{"accommodate":1,"configuration":1}
,"accommodate":{"server":1}
,"server":{"communications":1,"needs":1}
,"communications":{"layer":1}
,"layer":{"requirements":1}
,"requirements":{"value":1}
,"value":{"maxdirectmemorysize":1,"maxbyteslocaloffheap":1}
,"maxdirectmemorysize":{"greater":1,"certainly":1}
,"greater":{"value":1,"depends":1}
,"maxbyteslocaloffheap":{"exact":1,"minimum":1}
,"exact":{"amount":1}
,"amount":{"greater":1}
,"depends":{"upon":1}
,"upon":{"size":1}
,"size":{"maxbyteslocaloffheap":1}
,"minimum":{"256mb":1}
,"256mb":{"allocate":1}
,"certainly":{"sufficient":1}
,"sufficient":{"server":1}
,"needs":{"rest":1}
,"remain":{"available":1}
,"available":{"want":1}
,"best":{"possible":1}
,"possible":{"performance":1}
,"performance":{"hot":1}
,"hot":{"data":1,"items":1}
,"reducing":{"overall":1}
,"overall":{"application":1}
,"response":{"time":1}
,"time":{"variance":1}
,"combination":{"on-heap":1}
,"on-heap":{"off-heap":1}
,"used":{"hotset":1,"<cache":1}
,"hotset":{"off-heap":1}
,"example":{"hot":1}
,"1gb)":{"7gb":1}
,"-xms2g":{"-xmx2g":1}
,"-xmx2g":{"-xx:maxdirectmemorysize=6g":1}
,"-xx:maxdirectmemorysize=6g":{"ehcache":1}
,"maxentrieslocalheap=1m":{"overflowtooffheap=\u0022":1,"<persistence":1}
,"compare":{"favorably":1}
,"favorably":{"against":1}
,"against":{"alternative":1}
,"alternative":{"keeping":1}
,"keeping":{"less-hot":1}
,"less-hot":{"database":1}
,"database":{"(100x":1}
,"(100x":{"slower)":1}
,"slower)":{"caching":1,"data":1}
,"caching":{"local":1}
,"local":{"disk":1}
,"disk":{"(20x":1,"used":1}
,"(20x":{"slower)":1}
,"small":{"pauses":1}
,"pauses":{"problem":1}
,"problem":{"whole":1}
,"whole":{"data":1}
,"kept":{"heap":1}
,"false":{"latency":1}
,"latency":{"isn\u0027t":1}
,"isn\u0027t":{"issue":1}
,"issue":{"disk":1}
,"<persistence":{"strategy=\u0022":1}
,"strategy=\u0022":{"localtempswap":1}
,"localtempswap":{"\u0022\u002F>":1}
}
;Search.control.loadWordPairs(pairs);
